### ISSUE TITLE
TPUStrategy broken in TF2 Keras

### ISSUE THREAD

**Issue by kpe** [tensorflow/tensorflow#34391] opened 2019-11-18 20:24 UTC
**System information**
- Have I written custom code: YES
- OS Platform and Distribution: Google Colab
- TensorFlow installed from (source or binary): Colab
- TensorFlow version (use command below):  ('v2.0.0-rc2-26-g64c3d38', '2.0.0')
- GPU model and memory:  Colab TPU

**Describe the current behavior**
TPU in collab cannot be used with TF 2, trying to use `TFRecordDataset` as an input to a Keras `Model.fit()` generates different exceptions depending on the whether `TPUStrategy.experimental_distribute_dataset()` is used or not.

1. when `TPUStrategy.experimental_distribute_dataset()` is **not** used or used but not within an `/job:worker` context:
```
InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:worker/replica:0/task:0/device:CPU:0 in order to run AutoShardDataset: Unable to parse tensor proto
Additional GRPC error information:
{"created":"@1574107145.043685979","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"Unable to parse tensor proto","grpc_status":3} [Op:AutoShardDataset]
```

2. using a `/job:worker` context without `experimental_distribute_dataset` crashes the Colab session with:
```
Nov 18, 2019, 9:17:39 PM	WARNING	2019-11-18 20:17:39.591672: E tensorflow/core/framework/variant.cc:102] Could not decode variant with type_name: "tensorflow::DatasetVariantWrapper". Perhaps you forgot to register a decoder via REGISTER_UNARY_VARIANT_DECODE_FUNCTION?
Nov 18, 2019, 9:09:53 PM	WARNING	2019-11-18 20:09:53.396513: E tensorflow/core/framework/dataset.cc:76] The Encode() method is not implemented for DatasetVariantWrapper objects.
Nov 18, 2019, 9:08:19 PM	WARNING	2019-11-18 20:08:19.842178: E tensorflow/core/framework/dataset.cc:76] The Encode() method is not implemented for DatasetVariantWrapper objects.
```

3. and 4. when `experimental_distribute_dataset` is used in a `tf.device("/job:worker")` context:
```
/tensorflow-2.0.0/python3.6/tensorflow_core/python/keras/engine/training.py in _distribution_standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, validation_split, shuffle, epochs, allow_partial_batch)
   2313         x = ds.batch(batch_size, drop_remainder=drop_remainder)
   2314       else:
-> 2315         assert isinstance(x, dataset_ops.DatasetV2)
   2316         training_utils.validate_dataset_input(x, y, sample_weight,
   2317                                               validation_split)
```

**Describe the expected behavior**
There should be at least one way of making the example bellow work with TF2 (it works with TF1).

**Code to reproduce the issue**
could also be checked here https://colab.research.google.com/gist/kpe/22340866c1dd3208d9177d2c8a9322e3/tpu-emb.ipynb

```python
%tensorflow_version 2.x
import tensorflow as tf
print("TF version:", tf.__version__)

import os

tfrec_path = "gs://kpe-pub/pub/tpu-strategy-ds-issue/test.tfrecords"

def parse_example(proto):
    return tf.io.parse_single_example(proto, {
        "feature": tf.io.VarLenFeature(tf.float32), 
        "label":   tf.io.VarLenFeature(tf.int64)
    })

def from_tfrecords_file(tfrec_path):
    ds = tf.data.TFRecordDataset([tfrec_path], compression_type="GZIP")
    ds = ds.map(parse_example)
    def to_dense(example):
        feature = tf.cast(tf.sparse.to_dense(example["feature"]), tf.float32)
        label   = tf.cast(tf.sparse.to_dense(example["label"]), tf.int32)
        return feature, tf.squeeze(label, -1)
    ds = ds.map(to_dense)
    return ds

try:
    TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']
    tf.config.experimental_connect_to_host(TPU_WORKER)
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
    tf.tpu.experimental.initialize_tpu_system(tpu)
    strategy = tf.distribute.experimental.TPUStrategy(tpu)
except:
    strategy = tf.distribute.get_strategy()
print(strategy)


def test_strategy(use_case):
    assert use_case in [0,1,2,3,4]

    if tf.__version__.startswith("1."): # in TF1 no need to distribute the dataset
        ds = from_tfrecords_file(tfrec_path).repeat().batch(32)
    else:
        if use_case == 0:
            ds = from_tfrecords_file(tfrec_path).repeat().batch(32)
        if use_case == 1:
            ds = from_tfrecords_file(tfrec_path).repeat().batch(32)
            ds = strategy.experimental_distribute_dataset(ds)
        if use_case == 2:            
            with tf.device("/job:worker"):
                ds = from_tfrecords_file(tfrec_path).repeat().batch(32)
        if use_case == 3:
            with tf.device("/job:worker"):
                ds = from_tfrecords_file(tfrec_path).repeat().batch(32)
                ds = strategy.experimental_distribute_dataset(ds)
        if use_case == 4:
            with strategy.scope(), tf.device("/job:worker"):
                ds = from_tfrecords_file(tfrec_path).repeat().batch(32)
                ds = strategy.experimental_distribute_dataset(ds)

    with strategy.scope():
        model = tf.keras.models.Sequential([
            tf.keras.layers.InputLayer(input_shape=(128,)),
            tf.keras.layers.Dense(2)
        ])
        model.build()
        model.compile("adam", loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))
        model.fit(ds, steps_per_epoch=4)

test_strategy(0) # try 0 ot 4
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by kpe** [comment] 2019-11-23 11:23
Just noted, that disabling eager execution, makes the test cases 0 and 2 above work again, i.e. without `experimental_distribute_dataset()` it works fine, just `eager_execution` needs to be disabled.

**Comment by javicivit** [comment] 2019-12-04 17:08
If I don't disable eager execution in Colab now tf.config.experimental_connect_to_cluster(cluster_resolver)
dose not return

**Comment by javicivit** [comment] 2019-12-04 17:24
Using the nightly build (Tensorflow version 2.1.0-dev20191203) it returns but then tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
Produces:
NFO:tensorflow:Initializing the TPU system: grpc://10.68.77.162:8470
INFO:tensorflow:Initializing the TPU system: grpc://10.68.77.162:8470
INFO:tensorflow:Clearing out eager caches
INFO:tensorflow:Clearing out eager caches
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-46-fbbe9ad0029d> in <module>()
----> 1 tf.tpu.experimental.initialize_tpu_system(cluster_resolver)

3 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

NotFoundError: '__inference__tpu_init_fn_105' is neither a type of a primitive operation nor a name of a function registered in binary running on n-050d2992-w-0. Make sure the operation or function is registered in the binary running in this process.

**Comment by jhseu** [comment] 2019-12-05 00:12
That error indicates that the backend is old relative to the Python version. You'll have to wait until the TF 2.1 release for this to work, or use a nightly TPU backend.

**Comment by javicivit** [comment] 2019-12-19 10:26
The error has not been solved in nightly builds yet. Any idea about when will a solution be available?

**Comment by srinjay-paul** [comment] 2020-02-12 22:46
Issue persists in TF2.1.0 and nightly (12/2) releases.

**Comment by puneetjindal** [comment] 2020-02-13 05:37
i am also looking for a solution of training CRNN model with TPU strategy but shows 

> InvalidArgumentError: {{function_node __inference_distributed_function_65800}} Compilation failure: Detected unsupported operations when trying to compile graph cluster_distributed_function_5228616458413911404[] on XLA_TPU_JIT: CTCLoss (No registered 'CTCLoss' OpKernel for XLA_TPU_JIT devices compatible with node {{node model_1/lambda_1/CTCLoss}}
	.  Registered:  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
){{node model_1/lambda_1/CTCLoss}}
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_10567693008944060997/_8]]

Link to the issue [here](https://github.com/tensorflow/tpu/issues/692)

**Comment by EthanPhan** [comment] 2020-02-21 08:14
I run into this problem when I try to train the huggingface's distilbert model on google cloud. Any update on this issue?

**Comment by auwal84** [comment] 2020-02-27 11:48
having same problem, any idea about the solution?

**Comment by rxsang** [comment] 2020-02-27 18:33
The original issue should have been resolved in TF2.1 and nightly. Now users don't need to manage the device scope themselves.

The issue @puneetjindal reported is actually because CTCLoss is not supported in TPU, but other than that, your job should have been initialized and run, it just encounters a compilation error.

@srinjay-paul, @EthanPhan, @auwal84, can you post more details on your error? It is likely the errors are caused by different causes.

**Comment by huan** [comment] 2020-03-30 19:18
I believe I have found a way to fix this issue. See https://github.com/huan/tensorflow-handbook-tpu/issues/1#issuecomment-606189444

**Comment by sushreebarsa** [comment] 2021-08-06 09:57
@kpe It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Can you please execute your code using Latest stable Version(2.5) and let us know if the issue still persists?Please refer to this [issue comment ](https://github.com/huan/tensorflow-handbook-tpu/issues/1#issuecomment-606189444)  and let us know if it helps? Thanks!

**Closed** 2021-08-20 10:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:dist-strat, comp:tpus, TF 2.0
