### ISSUE TITLE
ValueError: No variables to save | Tensorflow

### ISSUE THREAD

**Issue by uthiraa** [tensorflow/tensorflow#21141] opened 2018-07-26 01:43 UTC
Traceback (most recent call last):
  File "train.py", line 184, in <module>
    tf.app.run()
  File "C:\Users\uthir\Anaconda3\envs\qwerty\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "train.py", line 180, in main
    graph_hook_fn=graph_rewriter_fn)
  File "C:\tensorflow12345\models\research\object_detection\trainer.py", line 392, in train
    init_saver = tf.train.Saver(available_var_map)
  File "C:\Users\uthir\Anaconda3\envs\qwerty\lib\site-packages\tensorflow\python\training\saver.py", line 1338, in __init__
    self.build()
  File "C:\Users\uthir\Anaconda3\envs\qwerty\lib\site-packages\tensorflow\python\training\saver.py", line 1347, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\uthir\Anaconda3\envs\qwerty\lib\site-packages\tensorflow\python\training\saver.py", line 1372, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

I am trying to train my own model using ssd_mobile_v2_coco with ssd_mobilenet_v1_pets.config. I got this error. Please help me to solve this.

**Comment by tensorflowbutler** [comment] 2018-07-26 12:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by wf-ai** [comment] 2018-08-08 15:46
I have  the same issue ,using ssd_resnet50_v1

**Comment by asimshankar** [comment] 2018-08-08 15:54
Could you provide more context about what you're doing? Ideally a [minimal, comete, verifiable example](https://stackoverflow.com/help/mcve). 

Without additional context, it's hard to provide help. 

The error itself is suggesting that the model you're trying to checkpoint has no trainable parameters

**Comment by tensorflowbutler** [comment] 2018-08-31 08:11
It has been 22 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-15 18:50
It has been 37 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by asimshankar** [comment] 2018-09-15 19:03
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by asimshankar** 2018-09-15 19:03 UTC
Labels: stat:awaiting response

**Comment by minda163** [comment] 2018-10-05 01:29
I have the same issue ,using ssd_resnet50_v1

**Comment by minda163** [comment] 2018-10-05 01:31
>           I have  the same issue ,using ssd_resnet50_v1

Have you solved the problem?

**Comment by asimshankar** [comment] 2018-10-05 22:48
@minda163  see https://github.com/tensorflow/tensorflow/issues/21141#issuecomment-411456740

If you can provide a reproduction or more information (such as whether your model has any variables or not), that would be helpful. Thanks.

**Comment by zkl99999** [comment] 2018-10-26 11:30
python ~/code/gitmaster/tensorflow-master2/tensorflow-master/tensorflow/python/tools/freeze_graph.py --input_checkpoint="./model.ckpt-5000" --output_graph= xxx.pb --input_mete_graph= ./model.ckpt-5000.meta --output_node_names=output

raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by faezakamran** [comment] 2018-11-04 12:17
I am getting the same error: 
Traceback (most recent call last):
  File "cnn.py", line 77, in <module>
    saver = tf.train.Saver()
  File "/home/faeza/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1094, in __init__
    self.build()
  File "/home/faeza/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1106, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/faeza/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1131, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

and here is the code:
```
saver = tf.train.Saver()

def train_neural_network(x):
    prediction = convolutional_neural_network(x)
    cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=prediction, labels=y))
    optimizer = tf.train.AdamOptimizer(learning_rate=1e-3).minimize(cost)

    hm_epochs = 5
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        successful_runs = 0
        total_runs = 0

        for epoch in range(hm_epochs):
            epoch_loss = 0
            for data in train_data:
                total_runs += 1
                try:
                    x_batch = data[0]
                    y_batch = data[1]
                    _, c = sess.run([optimizer, cost], feed_dict={x: x_batch, y: y_batch})
                    epoch_loss += c
                    successful_runs += 1

                except Exception as e:
                    # I am passing for the sake of notebook space, but we are getting 1 shaping issue from one
                    # input tensor. Not sure why, will have to look into it. Guessing it's
                    # one of the depths that doesn't come to 20.
                    pass
                    #print(str(e))

            #print('Epoch', epoch + 1, 'completed out of', hm_epochs, 'loss:', epoch_loss)

            correct = tf.equal(tf.argmax(prediction), tf.argmax(y))
            accuracy = tf.reduce_mean(tf.cast(correct, 'float'))

            #print('Accuracy:', accuracy.eval({x: [i[0] for i in validation_data], y: [i[1] for i in validation_data]}))
        correct = tf.equal(tf.argmax(prediction), tf.argmax(y))
        accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
        saver.save(sess, "model.ckpt")
        print('Done. Finishing accuracy:')
        a =  accuracy.eval({x: [i[0] for i in validation_data], y: [i[1] for i in validation_data]})
        print('Accuracy:', a)
```

**Comment by RishikMani** [comment] 2019-10-01 10:56
I am also having the same issue. It could be easily reproduced using the code below:

```python
import tensorflow as tf

w1 = tf.placeholder('float', name='w1')
w2 = tf.placeholder('float', name='w2')
b = tf.placeholder('float', name='b')

feed_dict = {w1:4, w2:8, b:2}
w3 = tf.add(w1, w2)
w4 = tf.multiply(w3, b, name='op_to_restore')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    print(sess.run(w4, feed_dict))
    saver.save(sess, './train_dir/my_test_model', global_step=1000)
```

Can anybody help me with this?
