### ISSUE TITLE
Reoccurring issue with tensorflow-gpu install

### ISSUE THREAD

**Issue by arcosmin** [tensorflow/tensorflow#8253] opened 2017-03-09 22:30 UTC
Hi all,

There is still this reoccurring issue with the tensorflow-gpu install with the latest version from pip.

When i try and test using the "Hello World" constant I get the below errors even though it works.

E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots

**Comment by samodadela** [comment] 2017-03-09 22:44
Have the same problem!

**Comment by samodadela** [comment] 2017-03-09 22:48
It seems this is the same problem but for the cpu version: https://github.com/tensorflow/tensorflow/issues/7500

The fix is to install a nightly build or wait for next release. When is it planned (for gpu)?

**Comment by samodadela** [comment] 2017-03-09 22:51
Is there a nightly that fixes the problem for gpu? Please specify instruction on how to update.

**Comment by argcos** [comment] 2017-03-09 23:03
Tried the nightly build but that gets me into other issues which are supposed to be fixed.

**Comment by prb12** [comment] 2017-03-09 23:10
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

I'm guessing you are on some variant of Windows from the pathnames?

**Comment by argcos** [comment] 2017-03-09 23:13
windows 10 64-bit. tensorflow-gpu 1.0.1

**Comment by prb12** [comment] 2017-03-09 23:17
Closing as duplicate of #8229

**Comment by herozhang** [comment] 2017-03-10 15:38
Have the same problem!
windows 10 64-bit. tensorflow-gpu 1.0.1. python 64bit 3.5.2

**Comment by tobiasberr** [comment] 2017-03-10 16:12
I have the same problem. #8229 did not help either

**Comment by tobiasberr** [comment] 2017-03-10 16:15
I was able to run all my tensorflow programs with out any problems on the cpu version, but since I installed CUDA8.0 and CuDDN5.1 none of my programs run anymore without errors:

"C:\Program Files\Python35\python.exe" D:/tobylabtop/AI/tensorflowbook/chapters/06_recurrent_neural_networks_and_natural_language_processing/01_wikipedia/tobytest.py
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library curand64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 960M
major: 5 minor: 0 memoryClockRate (GHz) 1.176
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.65GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0 
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y 
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0)
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
b'Hello, TensorFlow!'

Process finished with exit code 0

**Comment by tomwanzek** [comment] 2017-03-10 17:27
@prb12 can this issue please be reopened? As pointed out, this seems to be a recent regression.
When I run Win GPU nightly build 105 in a conda environment, I do not experience the above warnings as opposed to the Win GPU 1.0.0 build.

Having just created a conda environment with Win GPU 1.0.1, it re-appears. Thx.

**Comment by prb12** [comment] 2017-03-10 19:08
@tomwanzek I don't understand your comment ... you're saying the problem is fixed in the nightly build 105 (from March 7th) ... but you want to re-open the issue because the older binary package has a problem?

**Comment by tomwanzek** [comment] 2017-03-10 19:47
@prb12 No, the latest Win GPU v1.0.1 release seems to be the issue. In the Jenkins build history the first wheel referring to v1.0.1 would be build 108, to be precise.

While I installed v1.0.1 from 
`https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.0.1-cp35-cp35m-win_amd64.whl` as per tensorflow installation guide, I am assuming that it should correspond to build 108 given the patch version numbers.

This version does exhibit the behavior previously fixed in by 105.

So this seems to be a recent regression of sorts. If need be, I could download the wheel for 108 directly from Jenkins and install to verify.

Hope this clarifies.

**Comment by prb12** [comment] 2017-03-10 19:50
@tomwanzek Thanks for the clarification and delving through the version numbers! 

Maybe the 1.0.1 release was cherry-picked in a strange way.  @gunan Do you know why this fix may have reverted?

**Comment by tomwanzek** [comment] 2017-03-10 20:03
No worries, I have not check the nightlies between 105 and 108 to pin it down further...

**Comment by gunan** [comment] 2017-03-10 21:12
@mrry for windows @jhseu for the cherrypicks on the release 1.0.1

Any idea why this resurfaced in 1.0.1?

**Comment by gunan** [comment] 2017-03-10 21:14
@tomwanzek the release radically different from nightly builds.
The release branch base is synced to January 15 of master. Then we cherrypicked many fixes into the release branch. So there are no nightlies that have 1-1 correspondence to any of our releases.

**Comment by tomwanzek** [comment] 2017-03-10 21:36
@gunan Ah, did not realize you cherrypicked. I assumed, the semantic version releases were also cut from `master` whenever one was ready to ship. So while the nightly build might not be spot on, I thought them to be sufficiently close to the release build. Should have been digging deeper I suppose...:smile:

**Comment by mrry** [comment] 2017-03-10 22:14
@gunan It would be good to get this into 1.0.2 if there's going to be such a release (I think a few other bug fixes might have fallen into the cracks as well). Are we planning to have one?

**Comment by gunan** [comment] 2017-03-14 04:00
we will start working on 1.1 soon, therefore I don't think a 1.0.2 release is likely.
Since this issue is resolved at head, are we ok to close this issue?

**Comment by JerryKurata** [comment] 2017-03-14 18:03
@all if we need to get rid of these messages now.  What is the option.  I assume the nightly have moved on to the version that does not have the patch that suppresses the warning message.  

I ask this because I am building training classes and do screen captures.  I need to know if I can rerun them soon without the message, or need to get busy manually deleting these from my captures.

**Comment by gunan** [comment] 2017-03-14 18:09
Nightlies still have the patch. The patch was never rolled back.
Rather, release branch was so old that it never really had the patch.

**Comment by dineshbvadhia** [comment] 2017-03-17 13:03
Want to confirm this is (still) a problem with the CPU version - TF 1.0.1 - for Windows 10.

Upgraded to TF 1.0.1 (and keras 2.0.1)  on Windows 10. Using Anaconda but the TF/keras install is with native pip ie.

> pip uninstall tensorflow
> pip install -U tensorflow
> pip uninstall keras
> pip install -U --no-deps keras

Errors are:

E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for
unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"')
for unknown op: UpdateFertileSlots

**Comment by gunan** [comment] 2017-03-17 15:26
Correct, it is still a problem with 1.0.1.
Please see the messages above for more information.

**Comment by skye** [comment] 2017-06-16 20:46
@gunan I'm assuming this has been cherry-picked into a release. I'm gonna close this, please reopen if it's still an issue.

**Closed by skye** 2017-06-16 20:46 UTC
Labels: stat:awaiting tensorflower
