### ISSUE TITLE
Keras doesn't allow tf.data validation without validation_steps

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#28995] opened 2019-05-24 11:16 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.14.4, Ubuntu 18.01
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.1.dev20190524 | 1.14.0rc0 | 1.14.0
- Python version: 3.6.8
- CUDA/cuDNN version: -
- GPU model and memory: -

**Describe the current behavior**
Using `tf.data` as `validation_data` without defining `validation_steps` fails with `TypeError: 'DatasetV1Adapter' object does not support indexing`.  Using `tf.data` without `steps_per_epoch` works as expected when using it as training data instead.

**Describe the expected behavior**
I think the behaviour of training data and validation data in Keras `model.fit` should be consistent. This would make Keras a lot easier to use together with `tf.data` because it gets rid of the need for defining a exact number of steps. 
**Code to reproduce the issue**
```python
import tensorflow as tf
import tensorflow_datasets as tfds

train, test = tfds.load(name="mnist", split=[tfds.Split.TRAIN, tfds.Split.TEST], as_supervised=True)

def scale(image, label):
    return tf.cast(image, tf.float32) / 255, label

model = tf.keras.Sequential(
    [
        tf.keras.layers.Conv2D(32, 3, activation="relu", input_shape=(28, 28, 1)),
        tf.keras.layers.MaxPooling2D(),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(10, activation="softmax"),
    ]
)

model.compile(loss="sparse_categorical_crossentropy", optimizer="adam")

model.fit(
    train.batch(256),
    validation_data=test.batch(256),
)
```

**Other info / logs**
```python traceback
  File "test.py", line 24, in <module>
    epochs=10,
  File "/Users/lukasgeiger/miniconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 644, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/lukasgeiger/miniconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 615, in fit
    steps_name='steps_per_epoch')
  File "/Users/lukasgeiger/miniconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 145, in model_iteration
    _print_train_info(inputs, val_inputs, steps_per_epoch, verbose)
  File "/Users/lukasgeiger/miniconda3/envs/tf-nightly/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 450, in _print_train_info
    hasattr(inputs[0], 'shape') and hasattr(val_inputs[0], 'shape')):
TypeError: 'DatasetV1Adapter' object does not support indexing
```

**Comment by gadagashwini** [comment] 2019-05-27 09:31
@lgeiger Can you please provide tensorflow version?. 
With Tensorflow tf-nightly and tf-2.0.0-alpha the above code outputs expected output. Thanks!

**Comment by lgeiger** [comment] 2019-05-27 09:37
> @lgeiger Can you please provide tensorflow version?.
With Tensorflow tf-nightly and tf-2.0.0-alpha the above code outputs expected output. Thanks!

Sorry for the missing version, I am using `tf-nightly==1.14.1.dev20190524`

**Comment by gadagashwini** [comment] 2019-05-27 09:54
@lgeiger I tried with tf-nightly==1.14.1.dev20190524 and tensorflow==1.14.0rc0 but the code executed without any error. Can you try once again and let us know if that still gives error. Thanks!

**Comment by lgeiger** [comment] 2019-05-27 10:34
> Can you try once again and let us know if that still gives error.

Yep, just tried it with `tensorflow==1.14.0rc0` and it still gives an error. Which python version are you using?

**Comment by gadagashwini** [comment] 2019-05-27 10:43
@lgeiger Thanks for confirming. I am using Python 3.6.7 version.

**Comment by lgeiger** [comment] 2019-05-27 11:12
I can still reproduce this with Python 3.6.8, TensorFlow 1.14.0-rc0 and TensorFlow Datasets 1.0.2

**Comment by jvishnuvardhan** [comment] 2019-05-30 18:16
@lgeiger I don't see the error you mentioned. I ran your code using `tensorflow==2.0.0-alpha0`([gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/1f15082053c715c76643058dda5eae58/tf28995_gpu.ipynb)), `tensorflow-gpu==2.0.0-alpha0` ([gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/4736ce8fd58e1bd2657728409a34752e/tf_gpu_28995_gpu.ipynb)), and `tf-nightly-gpu-2.0-preview==2.0.0-dev20190530` ([gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/ba8cfffda7f0bb54ca55d41643f06381/tf-nightly_gpu_28995_gpu.ipynb)).

Please try to run it yourself. If you see any issues, let us know. Thanks!

**Comment by lgeiger** [comment] 2019-05-30 18:28
> I don't see the error you mentioned. I ran your code using tensorflow==2.0.0-alpha0(gist), tensorflow-gpu==2.0.0-alpha0 (gist), and tf-nightly-gpu-2.0-preview==2.0.0-dev20190530 (gist).

Thanks for reproducing. As mentioned above the issue is related to `1.14.1.dev20190524` and `1.14.0rc0`. TF 2 works fine.

**Comment by jvishnuvardhan** [comment] 2019-05-30 19:36
@lgeiger I ran it in `1.14.1.dev20190524` and don't see any error. Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/6f99cbefa5cd7f90169f7098fe67f4f0/tf_nightly_1_14_1_gpu_28995_gpu.ipynb). 

It will be helpful If you can create a gist and share.  Thanks!

**Comment by lgeiger** [comment] 2019-05-30 20:04
[Here](https://colab.research.google.com/drive/1gxC8Apn7xVExkaPo4ncBUU9YQKfe4ZK0) is a colab using 1.14.0rc0

**Comment by jvishnuvardhan** [comment] 2019-05-30 21:53
@lgeiger I could reproduce the issue when i select "cpu". If I select "gpu" as shown in my gist, there is no error. Thanks!

**Comment by lgeiger** [comment] 2019-05-30 22:02
> @lgeiger I could reproduce the issue when i select "cpu". If I select "gpu" as shown in my gist, there is no error. Thanks!

Strange. Good that you can reproduce it now

**Comment by jvishnuvardhan** [comment] 2019-05-31 03:19
@jsimsa Is this intended behavior? Can you please take a look at this issue? Thanks!

**Comment by jsimsa** [comment] 2019-05-31 15:40
This is a question for tf.keras folks, not tf.data.

**Comment by tsing-cv** [comment] 2019-06-16 04:46
I also encounter this problem, tf.keras + tf.data. My tensorflow version is tf13.1.

**Comment by lgeiger** [comment] 2019-07-11 00:06
@jvishnuvardhan Any updates on this issue?

**Comment by Pari-singh** [comment] 2019-07-13 00:02
Facing the similar issue.

**Comment by lgeiger** [comment] 2019-07-17 09:07
@omalleyt12 I can still reproduce this issue with TensorFlow 1.14.0:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-89e74e90b73d> in <module>
     21 model.fit(
     22     train.batch(256),
---> 23     validation_data=test.batch(256),
     24 )

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    778           validation_steps=validation_steps,
    779           validation_freq=validation_freq,
--> 780           steps_name='steps_per_epoch')
    781 
    782   def evaluate(self,

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    143 
    144   if mode == ModeKeys.TRAIN:
--> 145     _print_train_info(inputs, val_inputs, steps_per_epoch, verbose)
    146 
    147   # Enter tf.distribute.Strategy scope.

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py in _print_train_info(inputs, val_inputs, steps_per_epoch, verbose)
    448 def _print_train_info(inputs, val_inputs, steps_per_epoch, verbose):
    449   if (val_inputs and steps_per_epoch is None and verbose and inputs and
--> 450       hasattr(inputs[0], 'shape') and hasattr(val_inputs[0], 'shape')):
    451     print('Train on %d samples, validate on %d samples' %
    452           (inputs[0].shape[0], val_inputs[0].shape[0]))

TypeError: 'DatasetV1Adapter' object is not subscriptable
```

**Comment by benyeoh** [comment] 2019-07-24 08:19
Yup, can reproduce here as well with `1.14.0`.

Suboptimal workarounds are:

1. Set `verbose=0`
2. Set `steps_per_epoch` to something that is not `None`
3. Don't use `validation_data`

**Comment by qlzh727** [comment] 2019-07-24 16:13
Hi @lgeiger, sorry for the very late reply. That indeed seems to be a bug for certain runtime condition. As @benyeoh, mentioned, the quickest workaround is to set verbose = 0, which suppress the print of the message, and still give u the same training/eval behavior.

We are in the middle of a refactoring of the training logic, and will take care of the issue in 2.0 release.

**Comment by lgeiger** [comment] 2019-07-24 16:28
Thanks for taking a look

> We are in the middle of a refactoring of the training logic, and will take care of the issue in 2.0 release.

Does that mean TF 1.14 won't receive a fix for this? I understand that you are focusing on 2.0 at the moment, but a fix would be very useful for people currently relying still relying on TF 1.x.

**Comment by qlzh727** [comment] 2019-07-24 16:37
We probably won't update 1.14 release for this bug.

Also just check the docstring of model.fit()

> validation_data: Data on which to evaluate the loss and any model metrics at the end of each epoch. The model will not be trained on this data. validation_data will override validation_split. validation_data could be:
tuple (x_val, y_val) of Numpy arrays or tensors
tuple (x_val, y_val, val_sample_weights) of Numpy arrays
dataset or a dataset iterator.
For the first two cases, batch_size must be provided. For the last case, validation_steps must be provided.

Seems that the validation_steps is needed if the validation_data is a dataset.

**Comment by ymodak** [comment] 2019-08-08 20:59
This is fixed with latest tf-nightly version '1.15.0-dev20190808'

**Closed** 2019-08-15 20:27 UTC
Labels: comp:keras, stat:awaiting response, type:bug

**Comment by Lukeeeeee** [comment] 2020-06-19 16:33
> Sorry for opening this after almost a year, but from docstring of model.fit():
> 
> `steps_per_epoch`: Integer or None. Total number of steps (batches of samples) before declaring one epoch finished and starting the next epoch. When training with input tensors such as TensorFlow data tensors, the default None is equal to the number of samples in your dataset divided by the batch size, or 1 if that cannot be determined. **If x is a tf.data dataset, and 'steps_per_epoch' is None, the epoch will run until the input dataset is exhausted**. This argument is not supported with array inputs.
> 
> Why not do the same (**If x is a tf.data dataset, and 'steps_per_epoch' is None, the epoch will run until the input dataset is exhausted**) for validation data?
> 
> The docstring is a bit confusing
> 
> `validation_data`: Data on which to evaluate the loss and any model metrics at the end of each epoch. The model will not be trained on this data. validation_data will override validation_split. validation_data could be:
> 
> * tuple (x_val, y_val) of Numpy arrays or tensors
> * tuple (x_val, y_val, val_sample_weights) of Numpy arrays
>   dataset For the first two cases, batch_size must be provided. **For the last case, validation_steps must be provided.**
> 
> However
> 
> `validation_steps`: Only relevant if validation_data is provided and is a tf.data dataset. Total number of steps (batches of samples) to draw before stopping when performing validation at the end of every epoch. **If validation_data is a tf.data dataset and 'validation_steps' is None, validation will run until the validation_data dataset is exhausted.**
> 
> For 1.15 during `model.fit()` when validation data is `tf.data` and `validation_steps` is `None` the following error raises:
> 
> `` ValueError: When using data tensors as input to a model, you should specify the `steps_per_epoch` argument. ``
> 
> But this is not raised during `model.evaluate()` with `steps` = `None`

same issue here.

**Comment by Lukeeeeee** [comment] 2020-06-19 16:33
> Sorry for opening this after almost a year, but from docstring of model.fit():
> 
> `steps_per_epoch`: Integer or None. Total number of steps (batches of samples) before declaring one epoch finished and starting the next epoch. When training with input tensors such as TensorFlow data tensors, the default None is equal to the number of samples in your dataset divided by the batch size, or 1 if that cannot be determined. **If x is a tf.data dataset, and 'steps_per_epoch' is None, the epoch will run until the input dataset is exhausted**. This argument is not supported with array inputs.
> 
> Why not do the same (**If x is a tf.data dataset, and 'steps_per_epoch' is None, the epoch will run until the input dataset is exhausted**) for validation data?
> 
> The docstring is a bit confusing
> 
> `validation_data`: Data on which to evaluate the loss and any model metrics at the end of each epoch. The model will not be trained on this data. validation_data will override validation_split. validation_data could be:
> 
> * tuple (x_val, y_val) of Numpy arrays or tensors
> * tuple (x_val, y_val, val_sample_weights) of Numpy arrays
>   dataset For the first two cases, batch_size must be provided. **For the last case, validation_steps must be provided.**
> 
> However
> 
> `validation_steps`: Only relevant if validation_data is provided and is a tf.data dataset. Total number of steps (batches of samples) to draw before stopping when performing validation at the end of every epoch. **If validation_data is a tf.data dataset and 'validation_steps' is None, validation will run until the validation_data dataset is exhausted.**
> 
> For 1.15 during `model.fit()` when validation data is `tf.data` and `validation_steps` is `None` the following error raises:
> 
> `` ValueError: When using data tensors as input to a model, you should specify the `steps_per_epoch` argument. ``
> 
> But this is not raised during `model.evaluate()` with `steps` = `None`

same issue here

**Comment by ssnirgudkar** [comment] 2020-12-23 03:44
Hello,
I am hitting same error - TensorFlow 1.5, Python 2.7.17 inside docker container.
Minimal logical code -

images, labels = read_list ( data_dir, data_list ) <= here data_dir is full path of dir. containing image & label files. data_list is a text file, 2 column containing names of image file and lable file.
The output is array consisting of full path of images & corresponding labels.

queue = tf.data.Dataset.from_tensor_slices([images, labels])
img_contents = tf.io.read_file(queue[0]) <= Error location
label_contents = tf.io.read_file(queue[1])

File "/wasr/wasr_models/image_reader.py", line 180, in read_images_from_disk
    img_contents = tf.io.read_file(input_queue[0])
TypeError: 'DatasetV1Adapter' object does not support indexing

I have tried reading various posts but this post has come closest to what I am looking for. Any help to fix the issue will be greatly appreciated.

Thanks,
-Shailesh

**Comment by marchss** [comment] 2021-01-01 06:38
> > Sorry for opening this after almost a year, but from docstring of model.fit():
> > `steps_per_epoch`: Integer or None. Total number of steps (batches of samples) before declaring one epoch finished and starting the next epoch. When training with input tensors such as TensorFlow data tensors, the default None is equal to the number of samples in your dataset divided by the batch size, or 1 if that cannot be determined. **If x is a tf.data dataset, and 'steps_per_epoch' is None, the epoch will run until the input dataset is exhausted**. This argument is not supported with array inputs.
> > Why not do the same (**If x is a tf.data dataset, and 'steps_per_epoch' is None, the epoch will run until the input dataset is exhausted**) for validation data?
> > The docstring is a bit confusing
> > `validation_data`: Data on which to evaluate the loss and any model metrics at the end of each epoch. The model will not be trained on this data. validation_data will override validation_split. validation_data could be:
> > 
> > * tuple (x_val, y_val) of Numpy arrays or tensors
> > * tuple (x_val, y_val, val_sample_weights) of Numpy arrays
> >   dataset For the first two cases, batch_size must be provided. **For the last case, validation_steps must be provided.**
> > 
> > However
> > `validation_steps`: Only relevant if validation_data is provided and is a tf.data dataset. Total number of steps (batches of samples) to draw before stopping when performing validation at the end of every epoch. **If validation_data is a tf.data dataset and 'validation_steps' is None, validation will run until the validation_data dataset is exhausted.**
> > For 1.15 during `model.fit()` when validation data is `tf.data` and `validation_steps` is `None` the following error raises:
> > `` ValueError: When using data tensors as input to a model, you should specify the `steps_per_epoch` argument. ``
> > But this is not raised during `model.evaluate()` with `steps` = `None`
> 
> same issue here

same problem encountered. Could anyone in tensorflow team at least clarify what does the conflicting doc string mean? If the bug is not fixed in TF1.14, what is the intended behavior according to above doc string? It is pretty confusing.

**Comment by zuston** [comment] 2021-02-05 08:06
Any update on it?
