### ISSUE TITLE
Tensorflow Lite: iOS 14 breaks the NPU Delegate

### ISSUE THREAD

**Issue by boost-app** [tensorflow/tensorflow#43339] opened 2020-09-18 14:48 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
 iOS 14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
iPhone 11 pro,
- TensorFlow installed from (source or binary):
via pods: pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'
- TensorFlow version (use command below):
TensorFlowLiteSwift 0.0.1-nightly

**Describe the current behavior**
The update to iOS 14 broke the NPU (coreML) Delegate in tensorflow Lite.
The issue presents itself in the tensorflow lite example on iOS for posenet.
As soon as the coreML delegate is selected the joints of the body arent recognized properly anymore and the output of the net is garbage.

Images showing the correct (GPU) and incorrect (NPU) pose estimation:
[https://imgur.com/a/UzMM6Pt](https://imgur.com/a/UzMM6Pt)

**Describe the expected behavior**
The NPU delegate should produce the same results as CPU/GPU

**Standalone code to reproduce the issue**
Download the tensorflow Lite example for posenet on iOS and select the NPU delegate on a iOS 14 device

**Comment by teijeong** [comment] 2020-09-23 06:08
Hi @boost-app , I can confirm I'm seeing the same issue on iOS 14 (iPhone Xs).

Thanks for the report and will take a look.

**Comment by teijeong** [comment] 2020-09-28 11:51
With the manually converted mlmodel from tflite model, I could reproduce the same issue on iOS PoseFinder demo app. (see details on the coremltools issue.) Will keep investigating is this is actually a bug in iOS 14 or the delegate.

**Comment by AlexeyAB** [comment] 2020-10-16 01:54
@teijeong Hi,
Seems to be this issue with wrong model (wrong activation) is solved.

But there is another issue with PoseNet example, if you run PoseNet-example and the press Off button (short press side button), and then try to return to the application, then the image will be frozen, and after many attempts the application cannot be closed at all from the iPhone (I managed to stop it only from xcode). iOS 13.7, and all the same settings.

**Comment by fotiDim** [comment] 2020-11-10 14:25
I tested again on iOS 14.1 and 14.2 and it seems to be resolved. Can someone verify?

**Comment by AlexeyAB** [comment] 2020-11-11 16:05
Yes, it works well for iOS 13.7, 14.1, 14.2. 
But it didn't work for iOS 14.0.

**Comment by sushreebarsa** [comment] 2021-08-09 15:16
@boost-app It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest  stable Version of TF 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-23 16:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TF 2.3
