### ISSUE TITLE
[TF2.0] KerasLayer cannot be loaded from .h5

### ISSUE THREAD

**Issue by frogermcs** [tensorflow/tensorflow#26835] opened 2019-03-18 14:25 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
Run on Colab example from copied from tensorflow/hub: https://colab.research.google.com/drive/1ymmzlWHieCuXR7UjXezULnYsNsDeHc9m

Version:  2.0.0-alpha0
Eager mode:  True
Hub version:  0.3.0
GPU is available

**The issue**
When I try to run Colab example from tensorflow/hub for image retraining and then save/load model according to [the documentation](https://www.tensorflow.org/alpha/guide/keras/saving_and_serializing), there are some issues with it.

After retraining, when we try to save the model::
```
# Save the model
model.save('path_to_my_model.h5')
```
This error occurs (already described here: #26811 )
```
//...skipped, see ticket above for details ^
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
h5py/h5o.pyx in h5py.h5o.link()
RuntimeError: Unable to create link (name already exists)
```

But actually `path_to_my_model.h5` file is created. Then when I try to load it via:
```
# Recreate the exact same model purely from the file
new_model = keras.models.load_model('path_to_my_model.h5')
new_model.summary()
```
I get an error:
```
ValueError: Unknown layer: KerasLayer
```

Entire stacktrace:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-0ceb2f1e6ad5> in <module>()
----> 1 new_model = keras.models.load_model('path_to_my_model.h5')
      2 
      3 new_model.summary()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_model(filepath, custom_objects, compile)
    213     model_config = json.loads(model_config.decode('utf-8'))
    214     model = model_config_lib.model_from_config(model_config,
--> 215                                                custom_objects=custom_objects)
    216 
    217     # set weights

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/model_config.py in model_from_config(config, custom_objects)
     53                     '`Sequential.from_config(config)`?')
     54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
---> 55   return deserialize(config, custom_objects=custom_objects)
     56 
     57 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
     93       module_objects=globs,
     94       custom_objects=custom_objects,
---> 95       printable_module_name='layer')

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    190             custom_objects=dict(
    191                 list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 192                 list(custom_objects.items())))
    193       with CustomObjectScope(custom_objects):
    194         return cls.from_config(cls_config)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py in from_config(cls, config, custom_objects)
    349     for layer_config in layer_configs:
    350       layer = layer_module.deserialize(layer_config,
--> 351                                        custom_objects=custom_objects)
    352       model.add(layer)
    353     if not model.inputs and build_input_shape:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
     93       module_objects=globs,
     94       custom_objects=custom_objects,
---> 95       printable_module_name='layer')

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    179     config = identifier
    180     (cls, cls_config) = class_and_config_for_serialized_keras_object(
--> 181         config, module_objects, custom_objects, printable_module_name)
    182 
    183     if hasattr(cls, 'from_config'):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in class_and_config_for_serialized_keras_object(config, module_objects, custom_objects, printable_module_name)
    164     cls = module_objects.get(class_name)
    165     if cls is None:
--> 166       raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
    167   return (cls, config['config'])
    168 

ValueError: Unknown layer: KerasLayer
```

Entire colab to review: https://colab.research.google.com/drive/1ymmzlWHieCuXR7UjXezULnYsNsDeHc9m

**Comment by alimaan2935** [comment] 2019-03-28 01:14
same problem here.

**Comment by MartinMacek** [comment] 2019-03-28 12:58
Same for Unknown layer: DenseFeatures

**Comment by littlehome-eugene** [comment] 2019-04-04 13:57
same for Unknown layer: DenseFeatures

**Comment by Shalomash** [comment] 2019-04-04 14:31
Same issue for LSTM layers. When using 'ModelCheckpoint' callback.
 File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
 File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
 File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)

**Comment by Tbbas** [comment] 2019-04-14 15:31
Same here. 

```
ValueError: Unknown layer: DenseFeatures
```

Is there any update on this?

**Comment by frogermcs** [comment] 2019-04-18 14:01
I'm wondering if it's a good idea to use tf.keras.applications.MobileNetV2 model instead of the module loaded from TF Hub. 
It seems working after quick checks - tested model saving in this example: https://www.tensorflow.org/alpha/tutorials/images/transfer_learning

**Comment by JPatrick9793** [comment] 2019-04-22 15:15
Not perfect, but there is a workaround:

SImply create the model from scratch every time (instead of loading from JSON/YAML) and then load the weights. 

When using the DenseFeatures layer, the model will not be built after calling compile, so you will not be able to load the weights right away. You must either manually call the build() method or run a single batch through the model and then load the weights.

**Comment by frogermcs** [comment] 2019-04-22 20:07
I think I found the solution (or another workaround).

Instead of:
```
model.save('path_to_my_model.h5')
```

Call:
```
tf.keras.experimental.export_saved_model(model, 'path_to_my_model.h5')
```

Instead of:
```
new_model = keras.models.load_model('path_to_my_model.h5')
new_model.summary()
```

Call:
```
reloaded_model = tf.keras.experimental.load_from_saved_model('path_to_my_model.h5', custom_objects={'KerasLayer':hub.KerasLayer})
print(reloaded_model.get_config())

#Get input shape from model.get_config()
reloaded_model.build((None, 224, 224, 3))
print(reloaded_model.summary())
```

Works like a charm. :) 

Colaboratory with the code above: https://colab.research.google.com/drive/17YerjXGUwqp48mB3-WSTipv4itizuOCP

**Comment by qo-o-op** [comment] 2019-05-03 06:58
I use follow this code it work
`
model.save('./model/saved.h5')

new_model = tf.keras.models.load_model('./model/saved.h5',custom_objects={'KerasLayer':hub.KerasLayer})
new_model.summary()`

**Comment by arnoegw** [comment] 2019-05-03 15:58
The crash with hub.KerasLayer likely needs to be fixed in tensorflow-hub, not tensorflow. I've filed issue https://github.com/tensorflow/hub/issues/287 for that.

Can this issue here be closed then?

**Comment by miguno** [comment] 2019-05-09 21:06
👍 Same problem.

**Comment by arnoegw** [comment] 2019-05-10 11:35
The crash with hub.KerasLayer and an image module from tfhub.dev should be fixed by updating to their latest versions:
https://tfhub.dev/google/tf2-preview/inception_v3/feature_vector/3
https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/3
For details, see issue https://github.com/tensorflow/hub/issues/287

Can this issue be closed now, or is anyone using it to track the DenseLayer and LSTM problems with similar error messages but probably different root causes?

**Comment by H4wking** [comment] 2019-05-17 19:35
Any updates on ValueError: Unknown layer: DenseFeatures ?

**Comment by bjm88620** [comment] 2019-05-20 09:28
Have the same issue when do model.save('model.h5') under tensorflow 1.13.1

**Comment by qo-o-op** [comment] 2019-05-20 09:40
> Have the same issue when do model.save('model.h5') under tensorflow 1.13.1
Recommended to install tf-nightly or tf-nightly-gpu also

and test follow https://github.com/tensorflow/tensorflow/issues/26835#issuecomment-488972247

**Comment by qo-o-op** [comment] 2019-05-20 09:40
> Have the same issue when do model.save('model.h5') under tensorflow 1.13.1


Recommended to install tf-nightly or tf-nightly-gpu also
and test follow https://github.com/tensorflow/tensorflow/issues/26835#issuecomment-488972247

**Comment by bjm88620** [comment] 2019-05-20 11:34
resolved by updating tf version to 2.0

发自我的 iPhone

在 2019年5月20日，17:47，OooO <notifications@github.com<mailto:notifications@github.com>> 写道：


Have the same issue when do model.save('model.h5') under tensorflow 1.13.1
Recommended to install tf-nightly or tf-nightly-gpu also

and test follow #26835 (comment)<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftensorflow%2Ftensorflow%2Fissues%2F26835%23issuecomment-488972247&data=02%7C01%7C%7C7e2e94c948854a0bf13508d6dd08346b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636939424643466257&sdata=M5tDagIFSyWvX%2Bh%2BX1eWmEPBeT8Xeaqrb7HyaTHTWHI%3D&reserved=0>

**Comment by Zoltrix** [comment] 2019-05-29 06:55
Same for Unknown layer: DenseFeatures

**Comment by mengfu188** [comment] 2019-06-06 06:37
I find a solution [https://github.com/tensorflow/tensorflow/issues/26496#issuecomment-477246896](https://github.com/tensorflow/tensorflow/issues/26496#issuecomment-477246896)

```py
# Load the Keras model into a session.
keras_model = tf.keras.models.load_model(
    keras_file, custom_objects={'VladPooling': VladPooling})
sess = tf.keras.backend.get_session()

# Convert the model.
converter = tf.lite.TFLiteConverter.from_session(sess, keras_model.inputs,
                                                 keras_model.outputs)
converter.convert()
```

**Comment by Mark-DelGrande** [comment] 2019-06-10 22:07
Has anyone found a solution for how I can save a model with a feature layer. Right now I saved the weights of my model and then I rebuild the model and fit the model with epochs= 0; seems to do the trick and works to some extent.  For some unknown reason to me my predictions turn out a little different each time I try this though.

**Comment by ymodak** [comment] 2019-08-02 22:02
This is fixed in latest tf-nightly build '2.0.0-dev20190802'.
Thanks!

**Closed by ymodak** 2019-08-02 22:02 UTC
Labels: 2.0, 2.0.0-alpha0, comp:keras, stat:awaiting tensorflower, type:bug

**Comment by Ehsan-Yaghoubi** [comment] 2019-11-04 15:58
> I think I found the solution (or another workaround).
> 
> Instead of:
> 
> ```
> model.save('path_to_my_model.h5')
> ```
> 
> Call:
> 
> ```
> tf.keras.experimental.export_saved_model(model, 'path_to_my_model.h5')
> ```
> 
> Instead of:
> 
> ```
> new_model = keras.models.load_model('path_to_my_model.h5')
> new_model.summary()
> ```
> 
> Call:
> 
> ```
> reloaded_model = tf.keras.experimental.load_from_saved_model('path_to_my_model.h5', custom_objects={'KerasLayer':hub.KerasLayer})
> print(reloaded_model.get_config())
> 
> #Get input shape from model.get_config()
> reloaded_model.build((None, 224, 224, 3))
> reloaded_model.summary()
> ```
> 
> Works like a charm. :)
> 
> Colaboratory with the code above: https://colab.research.google.com/drive/17YerjXGUwqp48mB3-WSTipv4itizuOCP

Thank you, It is worked for me in this way:

```
from keras.models import load_model
import keras.layers as KL
trained_model_path = "./RESULTS/2019_10_30_10_17_53/bestmodel/MultiLabel_BIODI_weights.best.hdf5"
BIODI_model = load_model(trained_model_path, custom_objects={'BatchNorm':KL.BatchNormalization})
BIODI_model.summary()
```

**Comment by HansGabriel** [comment] 2020-04-26 12:09
> Not perfect, but there is a workaround:
> 
> SImply create the model from scratch every time (instead of loading from JSON/YAML) and then load the weights.
> 
> When using the DenseFeatures layer, the model will not be built after calling compile, so you will not be able to load the weights right away. You must either manually call the build() method or run a single batch through the model and then load the weights.

This is what I do every time but is there a faster way?

**Comment by neobie** [comment] 2020-05-04 06:25
same unknown layer: kerasLayer

**Comment by AlAlaa-Tashkandi** [comment] 2020-05-27 09:19
> I use follow this code it work
> 
> ```
> model.save('./model/saved.h5')
> new_model = tf.keras.models.load_model('./model/saved.h5',custom_objects='KerasLayer':hub.KerasLayer})
>  new_model.summary()
> ```
> 
> https://colab.research.google.com/drive/1JLkVWpXhDwImuF930i5PWstJvu4ENDoc

don't miss '{' after 'custom_objects='

**Comment by HansGabriel** [comment] 2020-05-28 06:14
Oh, thanks for pointing out. I was also wondering why my code didn't run last time. 
    On Wednesday, 27 May 2020, 05:20:00 pm GMT+8, AlAlaa Tashkandi <notifications@github.com> wrote:  
 
 



I use follow this code it work
model.save('./model/saved.h5')
new_model = tf.keras.models.load_model('./model/saved.h5',custom_objects='KerasLayer':hub.KerasLayer})
 new_model.summary()

https://colab.research.google.com/drive/1JLkVWpXhDwImuF930i5PWstJvu4ENDoc


don't miss '{' after 'custom_objects='

**Comment by PhilipPurwoko** [comment] 2020-05-31 08:51
> _Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template_
> 
> **System information**
> Run on Colab example from copied from tensorflow/hub: https://colab.research.google.com/drive/1ymmzlWHieCuXR7UjXezULnYsNsDeHc9m
> 
> Version: 2.0.0-alpha0
> Eager mode: True
> Hub version: 0.3.0
> GPU is available
> 
> **The issue**
> When I try to run Colab example from tensorflow/hub for image retraining and then save/load model according to [the documentation](https://www.tensorflow.org/alpha/guide/keras/saving_and_serializing), there are some issues with it.
> 
> After retraining, when we try to save the model::
> 
> ```
> # Save the model
> model.save('path_to_my_model.h5')
> ```
> 
> This error occurs (already described here: #26811 )
> 
> ```
> //...skipped, see ticket above for details ^
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> h5py/_objects.pyx in h5py._objects.with_phil.wrapper()
> h5py/h5o.pyx in h5py.h5o.link()
> RuntimeError: Unable to create link (name already exists)
> ```
> 
> But actually `path_to_my_model.h5` file is created. Then when I try to load it via:
> 
> ```
> # Recreate the exact same model purely from the file
> new_model = keras.models.load_model('path_to_my_model.h5')
> new_model.summary()
> ```
> 
> I get an error:
> 
> ```
> ValueError: Unknown layer: KerasLayer
> ```
> 
> Entire stacktrace:
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-15-0ceb2f1e6ad5> in <module>()
> ----> 1 new_model = keras.models.load_model('path_to_my_model.h5')
>       2 
>       3 new_model.summary()
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/hdf5_format.py in load_model(filepath, custom_objects, compile)
>     213     model_config = json.loads(model_config.decode('utf-8'))
>     214     model = model_config_lib.model_from_config(model_config,
> --> 215                                                custom_objects=custom_objects)
>     216 
>     217     # set weights
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/saving/model_config.py in model_from_config(config, custom_objects)
>      53                     '`Sequential.from_config(config)`?')
>      54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
> ---> 55   return deserialize(config, custom_objects=custom_objects)
>      56 
>      57 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
>      93       module_objects=globs,
>      94       custom_objects=custom_objects,
> ---> 95       printable_module_name='layer')
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
>     190             custom_objects=dict(
>     191                 list(_GLOBAL_CUSTOM_OBJECTS.items()) +
> --> 192                 list(custom_objects.items())))
>     193       with CustomObjectScope(custom_objects):
>     194         return cls.from_config(cls_config)
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py in from_config(cls, config, custom_objects)
>     349     for layer_config in layer_configs:
>     350       layer = layer_module.deserialize(layer_config,
> --> 351                                        custom_objects=custom_objects)
>     352       model.add(layer)
>     353     if not model.inputs and build_input_shape:
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/serialization.py in deserialize(config, custom_objects)
>      93       module_objects=globs,
>      94       custom_objects=custom_objects,
> ---> 95       printable_module_name='layer')
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
>     179     config = identifier
>     180     (cls, cls_config) = class_and_config_for_serialized_keras_object(
> --> 181         config, module_objects, custom_objects, printable_module_name)
>     182 
>     183     if hasattr(cls, 'from_config'):
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in class_and_config_for_serialized_keras_object(config, module_objects, custom_objects, printable_module_name)
>     164     cls = module_objects.get(class_name)
>     165     if cls is None:
> --> 166       raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
>     167   return (cls, config['config'])
>     168 
> 
> ValueError: Unknown layer: KerasLayer
> ```
> 
> Entire colab to review: https://colab.research.google.com/drive/1ymmzlWHieCuXR7UjXezULnYsNsDeHc9m

use this
tf.keras.models.load_model('model.h5',custom_objects={'KerasLayer':tfhub.KerasLayer})

**Comment by PhilipPurwoko** [comment] 2020-05-31 08:52
Use this code instead :
tf.keras.models.load_model('DogVisionModel.h5',custom_objects={'KerasLayer':tfhub.KerasLayer})

**Comment by HansGabriel** [comment] 2020-05-31 09:20
Thanks! I will update the code according to your post. I really appreciate your effort.
    On Sunday, 31 May 2020, 04:52:21 pm GMT+8, Philip Purwoko <notifications@github.com> wrote:  
 
 


Use this code instead :
tf.keras.models.load_model('DogVisionModel.h5',custom_objects={'KerasLayer':tfhub.KerasLayer})

**Comment by NikosSpanos** [comment] 2020-07-05 10:32
> I use follow this code it work
> 
> ```
> model.save('./model/saved.h5')
> new_model = tf.keras.models.load_model('./model/saved.h5',custom_objects='KerasLayer':hub.KerasLayer})
>  new_model.summary()
> ```
> 
> https://colab.research.google.com/drive/1JLkVWpXhDwImuF930i5PWstJvu4ENDoc

Adding the KeralLayer inside the model_from_json command also did the trick for me.
```
with open(os.path.join(os.getcwd(), 'model_three\\model_english_google_news_without_OOV_{0}batchsize_{1}.json'.format(str(dense_layer_batch_size), version_data_control)),'r') as f:
        model_json = json.load(f)

model_imported = model_from_json(model_json, custom_objects={'KerasLayer':hub.KerasLayer})

model_imported.load_weights(os.path.join(os.getcwd(), 'model_three\\model_english_google_news_without_OOV_{0}batchsize_{1}.h5'.format(str(dense_layer_batch_size), version_data_control)))

model_imported.compile(optimizer=optimizer_adam_v2(x_train_data_shape, training_validation_split_ratio, dense_layer_batch_size),
                           loss=model_loss_function,
                           metrics=model_metric_function)
print(type(model_imported))
print("\nModel is loaded successfully\n")
```

**Comment by HansGabriel** [comment] 2020-07-12 04:08
Thanks for the effort Nikos Spanos. I'll be updating my colab code.    On Sunday, July 5, 2020, 06:33:15 PM GMT+8, Nikos Spanos <notifications@github.com> wrote:  
 
 



I use follow this code it work
model.save('./model/saved.h5')
new_model = tf.keras.models.load_model('./model/saved.h5',custom_objects='KerasLayer':hub.KerasLayer})
 new_model.summary()

https://colab.research.google.com/drive/1JLkVWpXhDwImuF930i5PWstJvu4ENDoc


Adding the KeralLayer inside the model_from_json command also did the trick for me.
with open(os.path.join(os.getcwd(), 'model_three\\model_english_google_news_without_OOV_{0}batchsize_{1}.json'.format(str(dense_layer_batch_size), version_data_control)),'r') as f:
        model_json = json.load(f)

model_imported = model_from_json(model_json, custom_objects={'KerasLayer':hub.KerasLayer})

model_imported.load_weights(os.path.join(os.getcwd(), 'model_three\\model_english_google_news_without_OOV_{0}batchsize_{1}.h5'.format(str(dense_layer_batch_size), version_data_control)))

model_imported.compile(optimizer=optimizer_adam_v2(x_train_data_shape, training_validation_split_ratio, dense_layer_batch_size),
                           loss=model_loss_function,
                           metrics=model_metric_function)
print(type(model_imported))
print("\nModel is loaded successfully\n")

**Comment by mrugeles** [comment] 2020-08-09 16:14
> I'm wondering if it's a good idea to use tf.keras.applications.MobileNetV2 model instead of the module loaded from TF Hub.
> It seems working after quick checks - tested model saving in this example: https://www.tensorflow.org/alpha/tutorials/images/transfer_learning

Agree, I'm discarding TF Hub for the moment because of that issue,  tf.keras.applications.MobileNetV2 worked just fine.

**Comment by tocom242242** [comment] 2020-11-23 02:30
In my case, I could solve this problem by updating tensorflow from 2.2.0 to 2.3.0

**Comment by adhitio-github** [comment] 2021-05-20 21:27
# SAVE MODEL
MODEL_BASE_PATH = "MODEL"
PROJECT_NAME = model_name
SAVE_MODEL_NAME = 'model.h5'
save_model_path = os.path.join(MODEL_BASE_PATH, PROJECT_NAME, SAVE_MODEL_NAME)
if os.path.exists(os.path.join(MODEL_BASE_PATH, PROJECT_NAME)) == False:
    os.makedirs(os.path.join(MODEL_BASE_PATH, PROJECT_NAME))
    
print('Saving Model At {}...'.format(save_model_path))
model.save(save_model_path,include_optimizer=False)



#LOAD MODEL
from tensorflow.keras.models import load_model
MODEL_PATH = 'MODEL/model_name/model.h5'
model = load_model(MODEL_PATH,compile=False, custom_objects={'KerasLayer': hub.KerasLayer})
