### ISSUE TITLE
C++ load and running Tensorflow Model Crash

### ISSUE THREAD

**Issue by Qsevent** [tensorflow/tensorflow#20006] opened 2018-06-14 04:55 UTC
I use C++ load and running tensorflow model , but it`s crash.
the core is :
![304826260213283160](https://user-images.githubusercontent.com/19491069/41392235-15e627ce-6fd2-11e8-98c8-461d430ce05d.png)
please tell me how to solve it
Thinks!!!

**Comment by tensorflowbutler** [comment] 2018-06-14 12:35
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Qsevent** [comment] 2018-06-15 03:27
Thank you for your Answer
I compile tensorflow source code and use it on two different servers
**compile:**
- Linux version 2.6.32-431.el6.x86_64(redhat 4.4.7)
- gcc4.8.5
- bazel0.9.0
- TensorFlow installed from github(https://github.com/tensorflow/tensorflow/releases?after=v1.5.1)
- TensorFlow 1.4.0
- CUDA Version 8.0.61  /cuDNN: CUDNN_MAJOR  5
- GPU:Tesla K40m  Memory:11439MiB

**use:**
- Linux version 2.6.32-279.el6.x86_64(redhat 4.4.6)
- gcc4.4.6 (but i use it with libstdc++.so.6)

I write a dome that just create a session and run it. After my datas have been recycled many times, the program crashed. I supervised the memory and it is stable.
The crash happened in the libtensorflow_framework.so. I don't konw how it works.

Can give me your contact information? This communication method is too slow

**Comment by bignamehyp** [comment] 2018-06-20 06:51
Sorry I have difficulty understand your question. 

In generalThis question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by tensorflowbutler** [comment] 2018-07-04 18:43
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-20 01:18
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by bignamehyp** [comment] 2018-08-02 17:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by bignamehyp** 2018-08-02 17:26 UTC
Labels: stat:awaiting response
