### ISSUE TITLE
tf_upgrade_v2 does not preserve file attributes and symbolic links

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#26902] opened 2019-03-19 21:52 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):n/a
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):archlinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below): tf2 preview nightly yesterday
- Python version:3.7
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

1. `tf_upgrade_v2` changes executable files to non-executable files. I expect executable files are still executable after the upgrade.

2. `tf_upgrade_v2` always changes symbolic links to regular files. However I expect:
(1)For in-place upgrade, modify the file the link points to, but the symbolic link should be the same.
(2) For non-in-place upgrade, if `--intree` and `--outtree` is used, symbolic links which point to files within the tree should become symbolic links pointing to the new file in the outtree. Symbolic links which point to external files should become a regular file.
(3) For non-in-place single-file upgrade, the output should be a regular file.

**Comment by annarev** [comment] 2019-07-17 23:17
Hi @ppwwyyxx! Do you have a simple example where tf_upgrade_v2 changes a file to be non-executable?

I just tried the following:
```
touch test1/bar.sh
chmod +x test1/bar.sh
pip install tf-nightly-2.0-preview
tf_upgrade_v2 --intree=test1/ --outtree=test2/ --copyotherfiles=True
```

After these commands are run, `test2/bar.sh` does have executable permissions. Could it be instead that file ownership changed?

**Comment by annarev** [comment] 2019-07-25 22:34
I submitted a change to fix symbolic link behavior. However, the behavior is slightly different than you proposed. Specifically, I keep symlink unchanged if it points to external file (as opposed to converting it to regular file).

I was thinking that someone who has code in a different directory might want to update it separately, while keeping the symlink.

I will keep this issue open for the executable permission. Per my previous comment, I need some example to reproduce it.

**Comment by jvishnuvardhan** [comment] 2019-11-11 19:28
@ppwwyyxx Can you check whether the issue resolved in the `TF2.0` or `tf-nightly`? If this was resolved, please close the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2019-11-26 12:39
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-12-11 12:28
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-12-26 12:32
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by mihaimaruseac** [comment] 2019-12-26 17:00
Closing due to no other updates

**Closed by mihaimaruseac** 2019-12-26 17:00 UTC
Labels: TF 2.0-rc0, comp:ops, stat:awaiting response, type:bug
