### ISSUE TITLE
Inference problem using a tflite model java.lang.IllegalArgumentException: Invalid output Tensor index: 1

### ISSUE THREAD

**Issue by Anasel23** [tensorflow/tensorflow#39157] opened 2020-05-04 14:06 UTC
[Input and output shape][1]
[Java exception][2]
how did you solve this exception please
java.lang.IllegalArgumentException: Invalid output Tensor index: 1.
i converted a yolov3-tiny model
i changed the NUM_DETECTION into 2535 (NUM_DETECTION=2535) because the input shape is (1,416,416,6) and the output shape is (1,2535,6).
I ve trained the model on license plates so it can detect them. like i said i've worked with the yolov3-tiny version with darknet, so i converted it to pb file then tflite file so i can use in an android app and detect plates in real time

  [1]: https://i.stack.imgur.com/Rhw4R.png
  [2]: https://i.stack.imgur.com/2ekGP.jpg

**Comment by Anasel23** [comment] 2020-05-04 14:17
Please help if you have any suggestion or answer for this exception

**Comment by jvishnuvardhan** [comment] 2020-05-05 21:42
Can you pleas share a a standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2020-05-21 03:46
@Anasel23 Please try to use `tf-nightly` while converting model to tflite. Please provide a standalone code if this was not resolved for you. 

Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-05-21 03:46 UTC
Labels: comp:lite, stat:awaiting response, type:support

**Comment by SirTapir** [comment] 2020-05-22 13:04
I'm having the exact same problem with the same error. (Wasn't sure if i should create a new issue)

I'm using yolov3-tiny that was trained (using transfer learning) to detect 2 custom objects (knife and machete).

I used mystic's implementation https://github.com/mystic123/tensorflow-yolo-v3 to convert the .weight file to a .pb

Then I used the following code to convert the .pb file to .tflite

```
import tensorflow as tf

graph_def_file = "frozen_darknet_yolov3_model.pb"
input_arrays = ["inputs"]
output_arrays = ["output_boxes"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(
        graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```
(I'm using tensorflow 1.15 to run this code)

The .tflite that was created is then moved to the assets folder of the object_detection example of tflite https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

The tflite and labelfile that I used can be found here https://drive.google.com/file/d/1Av7Q1mjLdOIEE81oNnt8cLENlXykxnEu/view?usp=sharing

I changed the following on DetectorActivity.java
```
TF_OD_API_INPUT_SIZE from 300 to 416
TF_OD_API_IS_QUANTIZED from true to false
```
Then I changed the following on TFLiteObjectDetectionAPIModel.java
```
NUM_DETECTIONS from 10 to 2535
d.outputLocations = new float[1][NUM_DETECTIONS][4] to d.outputLocations = new float[1][NUM_DETECTIONS][7];
```
Here's the DetectorActivity.java and TFLiteObjectDetectionAPIModel.java that I use [here](https://drive.google.com/file/d/1Zf0i2Y_Tjyh7Li3UcxteKRB_k5Bwhhgt/view?usp=sharing)

When I try to run the app on mobile phone, the app crashed with the following error 
```
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 5535
    java.lang.IllegalArgumentException: Invalid output Tensor index: 1
        at org.tensorflow.lite.NativeInterpreterWrapper.getOutputTensor(NativeInterpreterWrapper.java:292)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:166)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:204)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:181)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

Any assistance would be appreciated @jvishnuvardhan

**Comment by jvishnuvardhan** [comment] 2020-05-22 16:34
@SirTapir Please create a new issue with a standalone code to reproduce the issue. Ping me in that issue. Thanks!

**Comment by Anasel23** [comment] 2020-05-22 21:59
I am sorry for being late i still have the same problem can you please give me more information about tf-nightly ?
and how i can use it

**Comment by Anasel23** [comment] 2020-05-22 22:00
@SirTapir we have the exact same problem i changed everything in the android code exactly like you but still dealing with this issue
did you solve it ?

**Comment by SirTapir** [comment] 2020-05-23 06:50
> @SirTapir Please create a new issue with a standalone code to reproduce the issue. Ping me in that issue. Thanks!

Alright, I'm opening a new issue now



> @SirTapir we have the exact same problem i changed everything in the android code exactly like you but still dealing with this issue
> did you solve it ?

Not yet, still facing the same problem

**Comment by Anasel23** [comment] 2020-05-24 00:21
@SirTapir Too i don't know of it is due to the pb conversion or the TFLite conversion. I am using Netron to visualize the graph and to specify the input_array and output_array. What are the parameters that you used for the TFLite conversion ?

**Comment by SirTapir** [comment] 2020-05-24 14:30
@Anasel23 Well, the code that I used to convert the .pb to .tflite is this
```
import tensorflow as tf

graph_def_file = "frozen_darknet_yolov3_model.pb"
input_arrays = ["inputs"]
output_arrays = ["output_boxes"]

converter = tf.lite.TFLiteConverter.from_frozen_graph(
        graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```
While the input array and output array names are found by running this
```
import tensorflow as tf
gf = tf.GraphDef()   
m_file = open('frozen_darknet_yolov3_model.pb','rb')
gf.ParseFromString(m_file.read())

with open('somefile.txt', 'a') as the_file:
    for n in gf.node:
        the_file.write(n.name+'\n')

file = open('somefile.txt','r')
data = file.readlines()
print("output name = ")
print(data[len(data)-1])

print("Input name = ")
file.seek ( 0 )
print(file.readline())
```

**Comment by Anasel23** [comment] 2020-05-24 20:31
@SirTapir Thank you so much for your reply hope that you solved the problem. If you did can you explain what did you do, stil stuck with this issue.

**Comment by Anasel23** [comment] 2020-05-25 13:12
@SirTapir the parameters are the same can i ask you a question please. What is the size of your tflite model ?

**Comment by kaunghtetsan275** [comment] 2020-11-02 08:27
I'm running into the exact same problem right now .. have you already solved this issue? @SirTapir @Anasel23

**Comment by SirTapir** [comment] 2020-11-02 08:49
@kaunghtetsan275 Yep, I've changed my converter to [hunglc007](https://github.com/hunglc007/tensorflow-yolov4-tflite)'s and used the android example in their repo as a reference to implement yolov3 to work in mobile app.

**Comment by kaunghtetsan275** [comment] 2020-11-04 09:25
@SirTapir thank you so much for this.. i've been having headache for the past few days because of this issue.. i've re-tried using the repo you've mentioned and the conversion and inference now work beautifully

**Comment by SirTapir** [comment] 2020-11-04 09:45
@kaunghtetsan275 Happy to help
