### ISSUE TITLE
MutableGraphView::MutableGraphView error: node has self cycle fanin - But graph is not cyclic

### ISSUE THREAD

**Issue by hfinkel** [tensorflow/tensorflow#38222] opened 2020-04-04 16:47 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 

 - Python 3.6.6 on Fedora
 - `python3 -c 'import tensorflow as tf; print(tf.__version__)'` -> 2.1.0
 - `tf.version.GIT_VERSION` -> v2.1.0-rc2-17-ge5bf8de
 - TensorFlow installed using `pip3 install --upgrade tensorflow`
 - Running on AMD CPU, no GPU acceleration

**Describe the current behavior**

For graphs that are not cyclic, I sometimes receive messages like this:

```
2020-04-04 11:20:02.351817: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model_4/up_sampling1d_2/concat' has self cycle fanin 'model_4/up_sampling1d_2/concat'.
2020-04-04 11:20:02.355486: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.357350: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.371116: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] arithmetic_optimizer failed: Invalid argument: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.372145: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model_4/up_sampling1d_2/concat' has self cycle fanin 'model_4/up_sampling1d_2/concat'.
2020-04-04 11:20:02.373345: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.374334: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.377600: W tensorflow/core/common_runtime/process_function_library_runtime.cc:697] Ignoring multi-device function optimization failure: Invalid argument: The graph couldn't be sorted in topological order.
```

**Describe the expected behavior**

I expect that TensorFlow should not print these messages (and presumably, be able to topologically order the non-cyclic graph).

**Standalone code to reproduce the issue** 

```
import tensorflow as tf
import numpy as np
import random

random.seed(1)
np.random.seed(1)

input_data = np.random.random(20000).reshape(10000, 2)
output_data = np.sin(input_data)

json = '''{"class_name": "Model", "config": {"name": "model_4", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 2], "dtype": "float32", "sparse": false, "ragged": false, "name": "input_5"}, "name": "input_5", "inbound_nodes": []}, {"class_name": "Reshape", "config": {"name": "reshape_2", "trainable": true, "dtype": "float32", "target_shape": [1, 2]}, "name": "reshape_2", "inbound_nodes": [[["input_5", 0, 0, {}]]]}, {"class_name": "Reshape", "config": {"name": "reshape_1", "trainable": true, "dtype": "float32", "target_shape": [1, 2]}, "name": "reshape_1", "inbound_nodes": [[["input_5", 0, 0, {}]]]}, {"class_name": "Reshape", "config": {"name": "reshape", "trainable": true, "dtype": "float32", "target_shape": [2, 1]}, "name": "reshape", "inbound_nodes": [[["input_5", 0, 0, {}]]]}, {"class_name": "UpSampling1D", "config": {"name": "up_sampling1d_2", "trainable": true, "dtype": "float32", "size": 3}, "name": "up_sampling1d_2", "inbound_nodes": [[["reshape_2", 0, 0, {}]]]}, {"class_name": "UpSampling1D", "config": {"name": "up_sampling1d_1", "trainable": true, "dtype": "float32", "size": 3}, "name": "up_sampling1d_1", "inbound_nodes": [[["reshape_1", 0, 0, {}]]]}, {"class_name": "UpSampling1D", "config": {"name": "up_sampling1d", "trainable": true, "dtype": "float32", "size": 2}, "name": "up_sampling1d", "inbound_nodes": [[["reshape", 0, 0, {}]]]}, {"class_name": "Reshape", "config": {"name": "reshape_5", "trainable": true, "dtype": "float32", "target_shape": [2, 1]}, "name": "reshape_5", "inbound_nodes": [[["input_5", 0, 0, {}]]]}, {"class_name": "ZeroPadding1D", "config": {"name": "zero_padding1d_1", "trainable": true, "dtype": "float32", "padding": [0, 1]}, "name": "zero_padding1d_1", "inbound_nodes": [[["up_sampling1d_2", 0, 0, {}]]]}, {"class_name": "ZeroPadding1D", "config": {"name": "zero_padding1d", "trainable": true, "dtype": "float32", "padding": [0, 1]}, "name": "zero_padding1d", "inbound_nodes": [[["up_sampling1d_1", 0, 0, {}]]]}, {"class_name": "Conv1D", "config": {"name": "conv1d", "trainable": true, "dtype": "float32", "filters": 2, "kernel_size": [1], "strides": [1], "padding": "valid", "data_format": "channels_last", "dilation_rate": [1], "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "name": "conv1d", "inbound_nodes": [[["up_sampling1d", 0, 0, {}]]]}, {"class_name": "MaxPooling1D", "config": {"name": "max_pooling1d", "trainable": true, "dtype": "float32", "strides": [2], "pool_size": [2], "padding": "valid", "data_format": "channels_last"}, "name": "max_pooling1d", "inbound_nodes": [[["reshape_5", 0, 0, {}]]]}, {"class_name": "Reshape", "config": {"name": "reshape_3", "trainable": true, "dtype": "float32", "target_shape": [2, 1]}, "name": "reshape_3", "inbound_nodes": [[["input_5", 0, 0, {}]]]}, {"class_name": "Conv1D", "config": {"name": "conv1d_1", "trainable": true, "dtype": "float32", "filters": 4, "kernel_size": [1], "strides": [1], "padding": "valid", "data_format": "channels_last", "dilation_rate": [1], "activation": "linear", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "name": "conv1d_1", "inbound_nodes": [[["zero_padding1d_1", 0, 0, {}]]]}, {"class_name": "Dot", "config": {"name": "dot", "trainable": true, "dtype": "float32", "axes": -1, "normalize": false}, "name": "dot", "inbound_nodes": [[["zero_padding1d", 0, 0, {}], ["conv1d", 0, 0, {}]]]}, {"class_name": "SpatialDropout1D", "config": {"name": "spatial_dropout1d", "trainable": true, "dtype": "float32", "rate": 0.4, "noise_shape": null, "seed": null}, "name": "spatial_dropout1d", "inbound_nodes": [[["max_pooling1d", 0, 0, {}]]]}, {"class_name": "GlobalAveragePooling1D", "config": {"name": "global_average_pooling1d", "trainable": true, "dtype": "float32", "data_format": "channels_last"}, "name": "global_average_pooling1d", "inbound_nodes": [[["reshape_3", 0, 0, {}]]]}, {"class_name": "Dot", "config": {"name": "dot_1", "trainable": true, "dtype": "float32", "axes": -1, "normalize": false}, "name": "dot_1", "inbound_nodes": [[["conv1d_1", 0, 0, {}], ["dot", 0, 0, {}]]]}, {"class_name": "AlphaDropout", "config": {"name": "alpha_dropout", "trainable": true, "dtype": "float32", "rate": 0.24308844217362846}, "name": "alpha_dropout", "inbound_nodes": [[["spatial_dropout1d", 0, 0, {}]]]}, {"class_name": "Reshape", "config": {"name": "reshape_4", "trainable": true, "dtype": "float32", "target_shape": [1, 1]}, "name": "reshape_4", "inbound_nodes": [[["global_average_pooling1d", 0, 0, {}]]]}, {"class_name": "Dropout", "config": {"name": "dropout", "trainable": true, "dtype": "float32", "rate": 0.4, "noise_shape": null, "seed": null}, "name": "dropout", "inbound_nodes": [[["dot_1", 0, 0, {}]]]}, {"class_name": "Flatten", "config": {"name": "flatten", "trainable": true, "dtype": "float32", "data_format": "channels_last"}, "name": "flatten", "inbound_nodes": [[["alpha_dropout", 0, 0, {}]]]}, {"class_name": "GlobalAveragePooling1D", "config": {"name": "global_average_pooling1d_1", "trainable": true, "dtype": "float32", "data_format": "channels_last"}, "name": "global_average_pooling1d_1", "inbound_nodes": [[["reshape_4", 0, 0, {}]]]}, {"class_name": "Flatten", "config": {"name": "flatten_1", "trainable": true, "dtype": "float32", "data_format": "channels_last"}, "name": "flatten_1", "inbound_nodes": [[["dropout", 0, 0, {}]]]}, {"class_name": "Concatenate", "config": {"name": "concatenate", "trainable": true, "dtype": "float32", "axis": -1}, "name": "concatenate", "inbound_nodes": [[["input_5", 0, 0, {}], ["flatten", 0, 0, {}], ["global_average_pooling1d_1", 0, 0, {}], ["flatten_1", 0, 0, {}]]]}, {"class_name": "Dense", "config": {"name": "dense_4", "trainable": true, "dtype": "float32", "units": 2, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}, "name": "dense_4", "inbound_nodes": [[["concatenate", 0, 0, {}]]]}], "input_layers": [["input_5", 0, 0]], "output_layers": [["dense_4", 0, 0]]}, "keras_version": "2.2.4-tf", "backend": "tensorflow"}'''

model = tf.keras.models.model_from_json(json)
model.compile(loss = 'mse', optimizer = 'adam')

model.summary()

model.fit(x = input_data.reshape(-1, 2), y = output_data.reshape(-1, 2), epochs = 3, validation_split = 0.2)
```

This runs and produces the following output:

```
2020-04-04 11:19:57.409765: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-04-04 11:19:57.409910: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-04-04 11:19:57.409938: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-04-04 11:20:00.326542: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-04-04 11:20:00.326615: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-04 11:20:00.326705: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (sapling6): /proc/driver/nvidia/version does not exist
2020-04-04 11:20:00.357649: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2195855000 Hz
2020-04-04 11:20:00.358616: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55b2db3a0250 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-04 11:20:00.358698: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_5 (InputLayer)            [(None, 2)]          0                                            
__________________________________________________________________________________________________
reshape_2 (Reshape)             (None, 1, 2)         0           input_5[0][0]                    
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 1, 2)         0           input_5[0][0]                    
__________________________________________________________________________________________________
reshape (Reshape)               (None, 2, 1)         0           input_5[0][0]                    
__________________________________________________________________________________________________
up_sampling1d_2 (UpSampling1D)  (None, 3, 2)         0           reshape_2[0][0]                  
__________________________________________________________________________________________________
up_sampling1d_1 (UpSampling1D)  (None, 3, 2)         0           reshape_1[0][0]                  
__________________________________________________________________________________________________
up_sampling1d (UpSampling1D)    (None, 4, 1)         0           reshape[0][0]                    
__________________________________________________________________________________________________
reshape_5 (Reshape)             (None, 2, 1)         0           input_5[0][0]                    
__________________________________________________________________________________________________
zero_padding1d_1 (ZeroPadding1D (None, 4, 2)         0           up_sampling1d_2[0][0]            
__________________________________________________________________________________________________
zero_padding1d (ZeroPadding1D)  (None, 4, 2)         0           up_sampling1d_1[0][0]            
__________________________________________________________________________________________________
conv1d (Conv1D)                 (None, 4, 2)         4           up_sampling1d[0][0]              
__________________________________________________________________________________________________
max_pooling1d (MaxPooling1D)    (None, 1, 1)         0           reshape_5[0][0]                  
__________________________________________________________________________________________________
reshape_3 (Reshape)             (None, 2, 1)         0           input_5[0][0]                    
__________________________________________________________________________________________________
conv1d_1 (Conv1D)               (None, 4, 4)         12          zero_padding1d_1[0][0]           
__________________________________________________________________________________________________
dot (Dot)                       (None, 4, 4)         0           zero_padding1d[0][0]             
                                                                 conv1d[0][0]                     
__________________________________________________________________________________________________
spatial_dropout1d (SpatialDropo (None, 1, 1)         0           max_pooling1d[0][0]              
__________________________________________________________________________________________________
global_average_pooling1d (Globa (None, 1)            0           reshape_3[0][0]                  
__________________________________________________________________________________________________
dot_1 (Dot)                     (None, 4, 4)         0           conv1d_1[0][0]                   
                                                                 dot[0][0]                        
__________________________________________________________________________________________________
alpha_dropout (AlphaDropout)    (None, 1, 1)         0           spatial_dropout1d[0][0]          
__________________________________________________________________________________________________
reshape_4 (Reshape)             (None, 1, 1)         0           global_average_pooling1d[0][0]   
__________________________________________________________________________________________________
dropout (Dropout)               (None, 4, 4)         0           dot_1[0][0]                      
__________________________________________________________________________________________________
flatten (Flatten)               (None, 1)            0           alpha_dropout[0][0]              
__________________________________________________________________________________________________
global_average_pooling1d_1 (Glo (None, 1)            0           reshape_4[0][0]                  
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 16)           0           dropout[0][0]                    
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 20)           0           input_5[0][0]                    
                                                                 flatten[0][0]                    
                                                                 global_average_pooling1d_1[0][0] 
                                                                 flatten_1[0][0]                  
__________________________________________________________________________________________________
dense_4 (Dense)                 (None, 2)            42          concatenate[0][0]                
==================================================================================================
Total params: 58
Trainable params: 58
Non-trainable params: 0
__________________________________________________________________________________________________
Train on 8000 samples, validate on 2000 samples
Epoch 1/3
2020-04-04 11:20:02.351817: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model_4/up_sampling1d_2/concat' has self cycle fanin 'model_4/up_sampling1d_2/concat'.
2020-04-04 11:20:02.355486: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.357350: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.371116: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] arithmetic_optimizer failed: Invalid argument: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.372145: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model_4/up_sampling1d_2/concat' has self cycle fanin 'model_4/up_sampling1d_2/concat'.
2020-04-04 11:20:02.373345: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.374334: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:02.377600: W tensorflow/core/common_runtime/process_function_library_runtime.cc:697] Ignoring multi-device function optimization failure: Invalid argument: The graph couldn't be sorted in topological order.
7904/8000 [============================>.] - ETA: 0s - loss: 0.16842020-04-04 11:20:04.124781: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model_4/up_sampling1d_2/concat' has self cycle fanin 'model_4/up_sampling1d_2/concat'.
2020-04-04 11:20:04.126366: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:04.127223: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:04.132842: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] arithmetic_optimizer failed: Invalid argument: The graph couldn't be sorted in topological order.
2020-04-04 11:20:04.133249: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model_4/up_sampling1d_2/concat' has self cycle fanin 'model_4/up_sampling1d_2/concat'.
2020-04-04 11:20:04.133728: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:04.134178: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-04 11:20:04.135585: W tensorflow/core/common_runtime/process_function_library_runtime.cc:697] Ignoring multi-device function optimization failure: Invalid argument: The graph couldn't be sorted in topological order.
8000/8000 [==============================] - 3s 429us/sample - loss: 0.1671 - val_loss: 0.0197
Epoch 2/3
8000/8000 [==============================] - 2s 204us/sample - loss: 0.0260 - val_loss: 0.0089
Epoch 3/3
8000/8000 [==============================] - 2s 204us/sample - loss: 0.0112 - val_loss: 0.0054
```

**Comment by amahendrakar** [comment] 2020-04-06 08:45
@hfinkel,
I tried reproducing the issue, but was able to run the code without any warning or error logs. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/20b6214077c4d93d5f268ab0f1c009a9/38222-2-1.ipynb).

Could you please try changing the log level using the following code and let us know if it works?
```
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import tensorflow as tf
```
Thanks!

**Comment by hfinkel** [comment] 2020-04-08 19:04
> Could you please try changing the log level using the following code and let us know if it works?

No, that does not have an effect on those messages. Setting the log level to 2 does remove the informational messages at the beginning of the execution:

```
2020-04-08 14:00:29.272792: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2195855000 Hz
2020-04-08 14:00:29.274725: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5596233c6980 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-08 14:00:29.274803: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
```

So those are gone, but these:

```2020-04-08 14:01:03.347880: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model_4/up_sampling1d_2/concat' has self cycle fanin 'model_4/up_sampling1d_2/concat'.
2020-04-08 14:01:03.351566: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-08 14:01:03.353443: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-08 14:01:03.368067: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] arithmetic_optimizer failed: Invalid argument: The graph couldn't be sorted in topological order.
2020-04-08 14:01:03.369385: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:561] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model_4/up_sampling1d_2/concat' has self cycle fanin 'model_4/up_sampling1d_2/concat'.
2020-04-08 14:01:03.370744: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-08 14:01:03.371978: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:717] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
```

and so on still remain.

**Comment by amahendrakar** [comment] 2020-04-09 19:21
@hfinkel,
Seems like the issue is fixed in the latest TF-nightly build. Please find the [attached gist](https://colab.research.google.com/gist/amahendrakar/e9ec3ba4a35e93cb6a6682e27fbbb5a9/38222-tf-nightly.ipynb#scrollTo=f1uK4LjIVjNI&line=1&uniqifier=1). 

Could you please verify it on your end? Thanks!

**Comment by amahendrakar** [comment] 2020-04-16 17:32
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-23 18:33
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-23 18:33 UTC
Labels: TF 2.0, stalled, stat:awaiting response, type:bug
