### ISSUE TITLE
Component function execution failed: Unknown: Fail to find the dnn implementation.

### ISSUE THREAD

**Issue by tawe141** [tensorflow/tensorflow#26959] opened 2019-03-20 20:31 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): should be 2.0.0 alpha; command below throws AttributeError
- Python version: 3.6.7 (Anaconda)
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.5
- GPU model and memory: GTX 1050 2gb

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

Using an LSTM with the Keras package works great until I try to fit my data. This error appears:

```
UnknownError: Fail to find the dnn implementation.
	 [[{{node unified_lstm/CudnnRNN}}]] [Op:__inference_keras_scratch_graph_1590]
```

A similar error appears when I try to use CuDNNLSTM

**Describe the expected behavior**

The call to `model.fit(X, Y)` should fit the model

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
model = tf.keras.Sequential()

model.add(tf.keras.layers.LSTM(256, return_sequences=True))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.LSTM(256))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(1))
model.compile(loss='mse', optimizer='sgd')
```
```
model.fit(X, Y)
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Don't know what would be helpful, but `tf.test.is_gpu_available()` returns true. I followed the instructions for installing Tensorflow 2.0 with GPU support here: https://www.tensorflow.org/install/gpu

Another error I get along the way is 
```
tensorflow/stream_executor/cuda/cuda_dnn.cc:338] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
```

I've tried one of the solutions in #6698, but `tf.ConfigProto()` was not found.

**Comment by jvishnuvardhan** [comment] 2019-03-21 22:24
@tawe141 Were you able to run any TF code that requires GPU? Did you check whether the cuDNN and CUDA are referenced correctly. Could you create any GitHub gist with public data and share it. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-04-03 21:17
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-03 21:17 UTC
Labels: 2.0.0-alpha0, stat:awaiting response

**Comment by joelzou925** [comment] 2019-05-23 13:28
I am getting the same error on Colab,  when running either tensorflow-gpu=2.0.0-alpha0 or tf-nightly-gpu, it throws Unknown: Fail to find the dnn implementation or Failed to get convolution algorithm. This is probably because cuDNN failed to initialize. 

It works when I go use CPU only, but obviously very slow. This happens for any kind of keras layers. I am using subclass API.

**Comment by radiantone** [comment] 2019-05-26 00:56
I am also getting this error on Pop! OS 19.04 running keras with cudnn in conda.

**Comment by jvishnuvardhan** [comment] 2019-05-28 19:34
Please create a new issue with details of your environment and with any reproducible code. Thanks!
