### ISSUE TITLE
tf.keras.callbacks.BaseLogger() is broken since "metrics" is no longer a key in Callback.params dict

### ISSUE THREAD

**Issue by CubasMike** [tensorflow/tensorflow#46344] opened 2021-01-11 17:52 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Oracle Linux Server 7.4
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.8.5

**Problem description**
I get an error when using tf.keras.callbacks.BaseLogger() since "metrics" is no longer a key of self.params within Callbacks. This same issue was handled in the new implementation of the TQDM progress bar Callback. The changes in code can be seen by checking the old and new versions of the TQDM callback.

Old: https://github.com/tensorflow/addons/blob/r0.8/tensorflow_addons/callbacks/tqdm_progress_bar.py
New: https://github.com/tensorflow/addons/blob/v0.11.2/tensorflow_addons/callbacks/tqdm_progress_bar.py#L26-L259

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(8, input_shape=(5,)))
model.add(tf.keras.layers.Dense(1))
model.compile(optimizer="Adam", loss="binary_crossentropy")
x = np.random.rand(4,5)
y = np.random.randint(0, 2, (4,))
model.fit(x, y, epochs=10, callbacks=[tf.keras.callbacks.BaseLogger()])
```

**Output/Traceback**
Epoch 1/10
1/1 [==============================] - ETA: 0s - loss: 0.2872Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/emsu/py38_tf23/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/scratch/emsu/py38_tf23/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1137, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/scratch/emsu/py38_tf23/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 416, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/scratch/emsu/py38_tf23/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 873, in on_epoch_end
    for k in self.params['metrics']:
KeyError: 'metrics'

**Comment by Saduf2019** [comment] 2021-01-12 08:44
@CubasMike 
I ran the stand alone code shared and face a different error, please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/d37c9154077ce362b67b92eb527c60e8/untitled493.ipynb), if possible please share a colab gist with the error reported.

**Comment by CubasMike** [comment] 2021-01-12 14:33
> @CubasMike
> I ran the stand alone code shared and face a different error, please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/d37c9154077ce362b67b92eb527c60e8/untitled493.ipynb), if possible please share a colab gist with the error reported.

Sorry, I copied the wrong line from the terminal. It should say:
```python
x = np.random.rand(4,5)
```

I updated the code with the correct line.

**Comment by Saduf2019** [comment] 2021-01-15 08:26
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/f2306d6dfdfdcc1a6c384dadb73da903/untitled495.ipynb)

**Comment by saikumarchalla** [comment] 2021-05-28 16:47
Was able to reproduce the issue in Tf Nighly 2.6 as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/4c19285d753f1ad75c00829512911ee8/untitled90.ipynb).Thanks!

**Comment by suneeta-mall** [comment] 2021-08-24 20:25
@rmothukuru @Saduf2019  Have you had any luck with this issue? I have been hit by this and trying to understand what the Tensorflow team's vision is with BaseLogger.

Looks like BaseLogger was applied by default on all keras model but this is only true for TensorFlow V1 models as indicated here https://github.com/tensorflow/tensorflow/blob/e104b6a9e87ea5956451ab56c1f5ca486c511bc4/tensorflow/python/keras/callbacks.py#L73-L112.
I have been debugging into this code flow and it appears that BaseLogger is no longer applied by default to V2 models. 

Also, it appears that BaseLogger is severely broken for use in v2 graphs as no such `metrics` exists in param https://github.com/tensorflow/tensorflow/blob/e104b6a9e87ea5956451ab56c1f5ca486c511bc4/tensorflow/python/keras/callbacks.py#L944. I think the right fix here is to change `self.params['metrics']`  to `logs.keys()`. However, looking at how averaging is done, that part also seems broken as `self.seem` is always zero for generator, dataset-based training as `batch` value is always 0 for those cases. Also, then here https://github.com/tensorflow/tensorflow/blob/e104b6a9e87ea5956451ab56c1f5ca486c511bc4/tensorflow/python/keras/callbacks.py#L927-L930
no such thing as `size` or `num_steps` exists on log anymore on `v2` graphs, so default of 0/1 is picked that makes seen ==0 leading to `ZeroDivisionError: float division by zero`. 

Is there another alternative approach recommended for BaseLogger for v2 then? Documentation seems to suggest https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/BaseLogger?hl=en BaseLogger continues to be applied on by default to all keras model v2 or v1 but I disagree with this, this is not true anymore with v2, I never break into this flow unless I have custom callback-based of BaseLogger.

I am confused looking at inactivity on this issue, surely this should be a very critical bug that should be fixed ASAP if BaseLogger is the `the` way to add to customize log stream, if not what is the alternate method. 

If I was to ignore BaseLogger completely, what is the recommended approach to write custom Callback so I can compute `seen` sample counts if I use generator/dataset based train where `model.fit` is not called with batch size?

Could you please advise?

**Comment by Saduf2019** [comment] 2021-08-25 08:26
@CubasMike 
Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues).
To know more refer to:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

**Comment by jvishnuvardhan** [comment] 2021-09-17 00:21
@CubasMike This is a bug. Thanks for finding this bug.

As this is related to keras and keras code moved to a [separate repo](https://github.com/keras-team/keras/issues) to focus on only keras, we will track the  progress in the following issue which was already assigned to a codeowner.
https://github.com/keras-team/keras/issues/15246

So, I am closing this issue here and lets track progress in keras-team/keras repo. Thanks!

**Closed by jvishnuvardhan** 2021-09-17 00:21 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:keras, TF 2.3
