### ISSUE TITLE
Allow mixing values with tensors in lists that specify the shape of a Tensor.

### ISSUE THREAD

**Issue by cesarsalgado** [tensorflow/tensorflow#465] opened 2015-12-10 14:11 UTC
There are many methods that expect a list or a tensor specifying a shape as argument. It is often the case that I want to pass an argument such as shape=[t1, v2] where t1 is a tensor with shape = TensorShape([]) and v2 is a value. This is currently not possible in many (maybe all) methods.

My current work around is the following.
1- convert v2 to a tensor t2 with tf.convert_to_tensor
2- use t1 = tf.expand_dims(0, t1) and t2 = tf.expand_dims(0, t2) to add a dimension of size 1 to the tensors
3- pass the argument as shape=tf.concat(0, [t1, t2])

Am I missing a simpler way to accomplish that? Is it a good idea to add a feature that allows passing mixture of tensors and values inside a list as argument?

Edit: I just found out that the method tf.pack allows lists with tensors and values as argument. But the method tf.truncated_normal for instance, doesn't allow.
I also realized that I can use tf.pack to replace the steps (1,2,3) above. But it still would be nice if all methods had the same behaviour.

**Comment by girving** [comment] 2015-12-10 19:24
Agreed, I've wanted this too.  There are some annoying obstacles, since in some places we automatically convert singleton tensors to lists and this feature would be backwards incompatible, but we've had some internal discussion about removing that magical (and fairly unidiomatic) list conversion.  If we did that, we'd be able to add *your* automatic conversion, which would be great.

**Comment by mrry** [comment] 2016-05-16 18:37
Closing this as a duplicate of #2328.

**Closed by mrry** 2016-05-16 18:37 UTC
Labels: enhancement
