### ISSUE TITLE
ResourceExhausted while doing K-fold cross-validation regardless of the chosen K

### ISSUE THREAD

**Issue by marcojulioarg** [tensorflow/tensorflow#33995] opened 2019-11-05 03:53 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
windows 10
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
Tensorflow 2.0.0
- Python version: 
3.7
- CUDA/cuDNN version: CUDA 10, cuDNN 7.6
- GPU model and memory: Titan V 12GB

**Describe the current behavior**
ResourceExhausted at last K fold of a K-fold cross-validation. Regardless of the K chosen. I've tried
3 fold, 5 fold and 10 fold and it always happens at the last fold.

**Code to reproduce the issue**
`
for j, (train_indices, val_indices) in enumerate(kf.split(datos_random)):

    train = datos.iloc[train_indices]
    val = datos.iloc[val_indices]    

    metrics = ['accuracy']
    model = build_model(DROPOUT, FC_LAYERS, num_classes=NUM_CLASSES, opt=OPT, metrics=metrics)

    train_datagen =  keras.preprocessing.image.ImageDataGenerator(
        preprocessing_function=preprocess_input,
        horizontal_flip=True,
        vertical_flip=True,
        # rotation_range=25,
        fill_mode='constant'
        
    )
    
    test_datagen = keras.preprocessing.image.ImageDataGenerator(
        preprocessing_function=preprocess_input,
    )
    
    train_generator = train_datagen.flow_from_dataframe(
                                          train,
                                          None,
                                          x_col='file',
                                          target_size=(WIDTH, HEIGHT),
                                          y_col=f'Class_cat_{NUM_CLASSES}', 
                                          batch_size=BATCH_SIZE, 
                                          seed=SEED,
                                          has_ext=True,class_mode='categorical')

    
    test_generator = test_datagen.flow_from_dataframe(val, 
                                          None, 
                                          x_col='file', 
                                          target_size=(WIDTH, HEIGHT),
                                          y_col=f'Class_cat_{NUM_CLASSES}', 
                                          batch_size=BATCH_SIZE,
                                          seed=SEED,
                                          has_ext=True,
                                          class_mode='categorical', 
                                          shuffle=True)
    class_list = list(test_generator.class_indices.keys())
   
    checkpoint = keras.callbacks.ModelCheckpoint(name_weights, 
                                                 monitor="val_accuracy", 
                                                 verbose=1, 
                                                 mode='max', 
                                                 save_best_only=True)
    callbacks_list = [
                      checkpoint, 
                      keras.callbacks.CSVLogger(os.path.join(fold_dir, 'log.csv'))
    ]
    print('Iniciando entrenamiento')
    history = model.fit(train_generator, 
                        epochs=EPOCHS, 
                        workers=16, 
                        shuffle=True, 
                        callbacks=callbacks_list, 
                        verbose=1, 
                        steps_per_epoch=math.ceil(len(train_indices) / BATCH_SIZE),
                        validation_data=test_generator, 
                        validation_steps=math.ceil(len(val_indices) / BATCH_SIZE)
                                 )
    
    acc = history.history['accuracy']
    val_accuracy = history.history['val_accuracy']

    loss = history.history['loss']
    val_loss = history.history['val_loss']
    
    avg_loss.append(val_loss[-1])
    avg_acc.append(val_accuracy[-1]*100)
                                      
    model.save(os.path.join(fold_dir, 'model.h5')) `
`

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
`
ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[128,64,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node block1_conv2_8/Conv2D}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[128,64,256,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node block1_conv2_8/Conv2D}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[metrics_16/accuracy/Identity/_3869]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.
`

**Comment by gadagashwini** [comment] 2019-11-06 06:25
@marcojulioarg, Please provide the complete code to reproduce the reported issue. Thanks!

**Comment by gadagashwini** [comment] 2019-11-14 05:05
@marcojulioarg,Any update on complete standalone code. Thanks!

**Comment by gadagashwini** [comment] 2019-11-25 11:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-11-25 11:52 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support
