### ISSUE TITLE
Segmentation Fault in Shape Function When Accessing Attr

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8473] opened 2017-03-16 16:16 UTC
Adding this to shape function causes segfault (full example below):
```c++
      string data_format;
      Status s = c->GetAttr("test_str", &data_format);
```

On OS X:
```
$ bazel version
Build label: 0.4.3-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 15:20:22 2016 (1482420022)
Build timestamp: 1482420022
Build timestamp as int: 1482420022
```

```
$git rev-parse
07bb8ea2379bd459832b23951fb20ec47f3fdbd4
```

Using the [ZeroOut op](https://www.tensorflow.org/extend/adding_an_op) but modifying the shape function:
```c++
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/framework/shape_inference.h"

using namespace tensorflow;

REGISTER_OP("ZeroOut")
    .Input("to_zero: int32")
    .Output("zeroed: int32")
    .Attr("test_str: {'alex', 'bob'} = 'alex'")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
      string data_format;
      Status s = c->GetAttr("test_str", &data_format);
      c->set_output(0, c->input(0));
      return Status::OK();
    });

class ZeroOutOp : public OpKernel {
 public:
  explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    // Grab the input tensor
    const Tensor& input_tensor = context->input(0);

    // Create an output tensor
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
                                                     &output_tensor));

  }
};

REGISTER_KERNEL_BUILDER(Name("ZeroOut").Device(DEVICE_CPU), ZeroOutOp);
```

and then running (within `tf.TestCase`):
```python
class Alex(tf.test.TestCase):
    def test_alex(self):
        so_path = (cur_dir + "/../../../../" +
            "bazel-bin/tensorflow/core/user_ops/zero.so")
        my_module = tf.load_op_library(so_path)
        with self.test_session():
            print my_module.zero_out([1,1,2,1]).eval()
```

The segfault it self seems to be coming from protobuf. I filed a ticket there as well: https://github.com/google/protobuf/issues/2863.

**Comment by skye** [comment] 2017-03-23 22:55
I was unable to reproduce this on 1.0. I didn't run in a test session:
```
import tensorflow as tf
zero_out_module = tf.load_op_library('zero_out.so')
with tf.Session(''):
  zero_out_module.zero_out([[1, 1, 2, 4]]).eval()
```

I also ran with gcc instead of bazel.

I don't have any super compelling theories, but maybe try running in a regular session like above, using the g++ command given in the tutorial, and/or upgrading bazel?

**Comment by cancan101** [comment] 2017-03-23 23:15
I upgraded bazel and am still seeing the segfault:
```
$ bazel version
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:39:33 2017 (1489671573)
Build timestamp: 1489671573
Build timestamp as int: 1489671573
```
What is best way to compile with GCC?

**Comment by skye** [comment] 2017-03-24 15:54
Cool, thanks for narrowing that down! I'll work on reproing the bad bazel artifact, and I'm glad you found a workaround for now.

**Comment by girving** [comment] 2017-06-16 20:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by girving** 2017-06-16 20:36 UTC
Labels: stat:awaiting tensorflower

**Comment by cancan101** [comment] 2017-06-16 20:43
wait... the last comment on this thread was @skye taking a look at the issue.
