### ISSUE TITLE
beta-1: tf.keras.layers.Conv2D with dilation_rate > 1 returns tensor with shape None

### ISSUE THREAD

**Issue by flobotics** [tensorflow/tensorflow#29843] opened 2019-06-16 17:43 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tensorflow-gpu==2.0.0-beta1 colab
- TensorFlow version (use command below):tensorflow-gpu==2.0.0-beta1
- Python version: pip3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: colab
- GPU model and memory:

**Describe the current behavior**
if tf.keras.layers.Conv2D is used with dilation_rate param > 1 it returns tensors with shape None!

**Comment by gadagashwini** [comment] 2019-06-17 13:09
@flobotics In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by flobotics** [comment] 2019-06-18 18:25
you can run the code directly in colab. 

https://github.com/flobotics/colab/blob/master/tf2_ganimorph.ipynb

github now shows directly the notebook with the error message in the def Discriminator function. You can also run it directly with colab.

the error message is

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-34-4221abe9b435> in <module>()
----> 1 discriminator = Discriminator()
      2 
      3 if not TEST:
      4   noise = tf.random.normal([1, 3, 128, 128])
      5 

<ipython-input-33-8aedbb5db62a> in Discriminator()
    105                         bias_initializer=None)(atrous)
    106 
--> 107   atrous2 = tfa.layers.InstanceNormalization()(atrous2)
    108   atrous2 = layers.ReLU()(atrous2)
    109 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    614           # Build layer if applicable (if the `build` method has been
    615           # overridden).
--> 616           self._maybe_build(inputs)
    617 
    618           # Wrapping `call` function in autograph to allow for dynamic control

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   1964         # operations.
   1965         with tf_utils.maybe_init_scope(self):
-> 1966           self.build(input_shapes)
   1967       # We must set self.built since user defined build functions are not
   1968       # constrained to set self.built.

/usr/local/lib/python3.6/dist-packages/tensorflow_addons/layers/normalizations.py in build(self, input_shape)
    102     def build(self, input_shape):
    103 
--> 104         self._check_if_input_shape_is_none(input_shape)
    105         self._set_number_of_groups_for_instance_norm(input_shape)
    106         self._check_size_of_dimensions(input_shape)

/usr/local/lib/python3.6/dist-packages/tensorflow_addons/layers/normalizations.py in _check_if_input_shape_is_none(self, input_shape)
    203                              'input tensor should have a defined dimension '
    204                              'but the layer received an input with shape ' +
--> 205                              str(input_shape) + '.')
    206 
    207     def _set_number_of_groups_for_instance_norm(self, input_shape):

ValueError: Axis -1 of input tensor should have a defined dimension but the layer received an input with shape (None, 512, None, None).
```


hope that is good enough ,or do you need more?

**Comment by gadagashwini** [comment] 2019-06-20 05:12
Was able to reproduce the issue on colab link with Tensorflow 2.0.0.beta1. Thanks!

**Comment by flobotics** [comment] 2019-06-22 19:57
are there some news/updates ?

**Comment by martinwicke** [comment] 2019-06-23 08:25
The shape information gets lost somewhere in `__call__`. `call` itself is fine.

I debugged a little, trying to find where exactly the shape is list, but I haven't found it: https://colab.sandbox.google.com/drive/1IKVe8cJhmnOV0SHztLmryYT9xvkJTIAm#scrollTo=_rbSDPnQH9ak

A simple workaround is to call `output.set_shape(layer.compute_output_shape(input.shape))` on the output, but there's clearly a bug here.

**Comment by martinwicke** [comment] 2019-06-23 09:07
I'm closing this as a duplicate of #29542

**Closed by martinwicke** 2019-06-23 09:07 UTC
Labels: 2.0.0-beta0, comp:keras, type:bug/performance
