### ISSUE TITLE
Bogus cache keys in Network._output_shape_cache can cause wrong output shapes (and gradual but unbounded memory growth)

### ISSUE THREAD

**Issue by gthb** [tensorflow/tensorflow#34827] opened 2019-12-04 13:08 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

Increasing amounts of memory get allocated and not garbage-collected on successive calls to `model.predict_on_batch(...)`, because output tensor shapes are cached into `Network._output_shape_cache` with cache keys based on Python object identity (which is based on the memory address of the object, in CPython), and cache entries are never expired (the cache is just a standard Python dict). This happens at the end of `Network._run_internal_graph`:

```python
      cache_key = generic_utils.object_list_uid(input_shapes)
      self._output_shape_cache[cache_key] = nest.pack_sequence_as(
          self._nested_outputs, output_shapes)
```

This is seen in the output of my script (see further below), which shows memory growth like this:

```
...
Notable memory usage diff over last 3000 predictions:
+177 B     (+0 B    per prediction)   +3 objs (0.00 per prediction) at:
    kerasbug.py:37
    .../tensorflow_core/python/keras/engine/training.py:1135
    .../tensorflow_core/python/keras/engine/training_v2_utils.py:370
    .../tensorflow_core/python/keras/engine/base_layer.py:891
    .../tensorflow_core/python/keras/engine/network.py:708
    .../tensorflow_core/python/keras/engine/network.py:877
    .../tensorflow_core/python/keras/utils/generic_utils.py:564
    .../tensorflow_core/python/keras/utils/generic_utils.py:564

model._output_shape_cache has grown to 300, new elements are:
('5492540304', TensorShape([None, 3]))
('5492540688', TensorShape([None, 3]))
('5492539600', TensorShape([None, 3]))
```

In practice, at least in my simple script, the growth rate _does_ decrease with time and the overall memory use _probably_ levels off, because input shape objects get garbage collected and their memory gets reused so new input shape objects _often_ get allocated at the same memory addresses, so their cache keys are already present in the cache. But there is no guarantee of this reuse of memory addresses and thus object identities (and its likelihood probably depends on what else is going on in the process), and thus there is no real guarantee of an upper bound to the growth of this cache.

Additionally, this cache key scheme hints at a likely functional bug: an input shape object that gets created at the same memory address as a previous input shape object will get the same object identity, and can thus lead to the same cache key in the output shape cache, even if it is not the same input shape. Such a case can cause `compute_output_shape` to return the wrong output shape (one that was valid for a _previous_ set of input shapes, still present in the cache). I have not tried to write code with varying input shapes to manifest this suspected bug.

**Describe the expected behavior**

I expect memory growth on successive model predictions to have an upper bound, when I  repeatedly call `predict_on_batch`.

I expect the output tensor shape returned by `Network.compute_output_shape` to be unaffected by the shapes of inputs of _previous_ runs. (But I haven't demonstrated a failure of this expectation, just conjectured how it would happen.)

**Code to reproduce the issue**

The following script shows the (theoretically) unbounded memory growth.

```python
import gc
import time
from itertools import islice
import tracemalloc
from os.path import basename

import tensorflow as tf
import numpy as np

TRACEMALLOC_EVERY = 3000
TRACEMALLOC_IGNORE = "tracemalloc.py:",

input_tensor = tf.keras.Input(shape=(3,), name='input')
output_tensor = tf.keras.layers.Dense(3, name='output')(input_tensor)
model = tf.keras.Model(inputs=[input_tensor], outputs=[output_tensor])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['categorical_accuracy'])


def random_input():
    return np.random.random_sample([1, 3])

model.predict_on_batch(random_input())

tracemalloc.start(50)

last_snapshot = tracemalloc.take_snapshot()
already_printed_from_output_shape_cache = []

while True:
    for _ in range(TRACEMALLOC_EVERY):
        model.predict_on_batch(random_input())

    gc.collect()
    time.sleep(0.1)
    snapshot = tracemalloc.take_snapshot()
    top_stats = snapshot.compare_to(last_snapshot, 'traceback')
    last_snapshot = snapshot

    notable_mem_usage_diff = "\n".join(
        f"{tracemalloc._format_size(stat.size_diff, True):10} "
        f"({tracemalloc._format_size(stat.size_diff // TRACEMALLOC_EVERY, True):7} per prediction) "
        f"{stat.count_diff:+4} objs "
        f"({stat.count_diff / TRACEMALLOC_EVERY:.2f} per prediction) at:\n"
        + "\n".join("    %s" % tb for tb in stat.traceback)
        for stat in islice(
            (s for s in top_stats
             if not any(i in str(tb) for tb in s.traceback for i in TRACEMALLOC_IGNORE)
             and not all(basename(__file__) + ":" in str(tb) for tb in s.traceback)
             and abs(s.size_diff) > 0  # // TRACEMALLOC_EVERY >= 8
             ),
            20
        )
    )
    if notable_mem_usage_diff:
        print("Notable memory usage diff over last %d predictions:\n%s\n" % (TRACEMALLOC_EVERY, notable_mem_usage_diff))
    else:
        print("No notable memory usage diff over last %d predictions\n" % (TRACEMALLOC_EVERY,))
    new_cache_elements = [item for item in model._output_shape_cache.items()
                          if item not in already_printed_from_output_shape_cache]
    if new_cache_elements:
        print("model._output_shape_cache has grown to %d, new elements are:\n%s\n" % (
            len(model._output_shape_cache),
            "\n".join(str(item) for item in new_cache_elements)
        ))
        already_printed_from_output_shape_cache.extend(new_cache_elements)
```

**Other info / logs**

As a sidenote, we are calling `predict_on_batch` instead of `predict` as a workaround for https://github.com/tensorflow/tensorflow/issues/33009 (another memory leak issue).

**Comment by gowthamkpr** [comment] 2019-12-09 21:26
@gthb I am running into a few errors. Can you please correct them [here](https://colab.sandbox.google.com/gist/gowthamkpr/942f5057dd37df0ec67d7d2d3ee4ff4b/untitled257.ipynb). Thanks!

**Comment by gthb** [comment] 2019-12-11 17:44
@gowthamkpr I only see one error there, which is that `__file__` is not defined, which must be because you're running in a notebook, not a Python file on disk. You can probably just remove that line (and maybe get some more uninteresting memory allocations as noise), that condition is just there to ignore memory allocations occurring within the top-level module. If removing it yields too much noise, then maybe something like this will help:

```python
and "<ipython-input" in str(s.traceback[-1]))
```

... but that's not tested.

**Comment by gowthamkpr** [comment] 2019-12-11 22:47
@gthb Can you please try reproducing it in colab and share the gist. Thanks!

**Comment by gthb** [comment] 2019-12-12 11:52
[Here it is as a public gist in Github](https://gist.github.com/gthb/0498ea482a4d19df1b43dd74d93a1262). (Saving it as a Colab-published gist required me to grant Google access to all of my secret gists in Github (!) just to publish this gist _publicly_ in Colab 🤔)

I changed it a bit to show only stack traces with at least one stack frame with tensorflow in its code file path, and only those that have a memory usage delta of at least one byte per request _since the beginning_ (unless you change `CUMULATIVE` to `False`). That turns out to filter out all the small plus and minus allocation noise and reveal that this test case does not exhibit any notable growth in memory allocations by Tensorflow overall — but does exhibit the gradual (and I think useless) growth of `Network._output_shape_cache`.

To be clear, I think this gradual growth is a minor issue and the more important thing here (I'll rename the issue accordingly) is the prospect of returning wrong output shapes because of the clearly incorrect use of object identities as cache keys. That's a code review observation, and a different test case (with varying output shapes) would be needed to demonstrate the wrong-output effects in practice.

**Comment by amahendrakar** [comment] 2020-08-27 17:23
@gthb,
Is this still an issue? 

I ran the code for over 50000 predictions and did not observe any memory usage difference or growth in model._output_shape_cache / new elements. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a39cdf91bfcfeb34a43b4b43ff214231/untitled257.ipynb). Thanks!

**Comment by gthb** [comment] 2020-09-04 22:50
> @gthb,
> Is this still an issue?

I don't know.
* **gradual growth:** I prevented this in my use case by just blowing away that cache periodically, and even before that I never observed it to be a _significant_ problem (I just happened to stumble across it when troubleshooting an unrelated unbounded memory growth problem, not involving Tensorflow).
* **returning wrong output shapes** — the possibility of this is a code review observation and I never tried to observe it actually happening. I haven't tried to quantify how _probable_ it is, and the probability each time may well be _very_ low, but I am quite certain it is nonzero, as the bogus use of object identities as cache keys definitely invites it.

**Comment by sushreebarsa** [comment] 2021-08-31 14:28
@gthb It looks like you are using an older Version of Tensorflow (2.3). Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version 2.6.0 and let us know if the issue still persists? Thanks!

**Comment by gthb** [comment] 2021-08-31 15:10
Sorry @sushreebarsa, I have since changed jobs and no longer have access to the codebase where I observed this, so can't check in a way that's reliably comparable to what I saw before. Also am not currently using Tensorflow at all so this is out of scope for me.

**Comment by sushreebarsa** [comment] 2021-08-31 15:13
@gthb Thanks for the quick update!

**Comment by tensorflowbutler** [comment] 2021-12-14 23:24
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Closed** 2022-01-11 17:47 UTC
Labels: stat:awaiting tensorflower, comp:keras, type:performance, TF 2.3
