### ISSUE TITLE
after quantization aware training and convert to tflite, when running the converted tflite model, ERROR: tensorflow/lite/kernels/pooling.cc:104 input->params.scale != output->params.scale (0 != 1067861562)

### ISSUE THREAD

**Issue by Sean0123456789** [tensorflow/tensorflow#27813] opened 2019-04-13 10:37 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Android 8.1
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):1.14
- Python version:3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
when run tflite model using tflite benchmark tool, following error happened:

ERROR: tensorflow/lite/kernels/pooling.cc:104 input->params.scale != output->params.scale (0 != 1067861562)
ERROR: Node number 92 (AVERAGE_POOL_2D) failed to prepare.
**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Sean0123456789** [comment] 2019-04-13 10:37
any ideas to solve this problem?

**Comment by achandraa** [comment] 2019-04-15 11:31
In order to expedite the trouble-shooting process, Please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by achandraa** [comment] 2019-04-22 05:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-04-22 05:27 UTC
Labels: comp:lite, stat:awaiting response, type:support
