### ISSUE TITLE
[tflite] multithreaded DepthwiseConv returns wrong results on aarch64 platform

### ISSUE THREAD

**Issue by freedomtan** [tensorflow/tensorflow#27200] opened 2019-03-27 14:33 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): nope
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android Pie (Pixel 2) and Debian (Coral EdgeTPU Dev Board)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Pixel 2
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): recent master 8d1c139712a65a25419e951eca737c38f917262b
- Python version: N/A
- Bazel version (if compiling from source): 0.24.0
- GCC/Compiler version (if compiling from source): gcc 6 on Coral Dev Board, clang in Android NDK r17b
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
```
> adb shell
walleye:/ $ cd /data/local/tmp
walleye:/data/local/tmp $ ./label_image_new_aarch64  -m mobilenet_v1_1.0_224_quant.tflite  -t 1                                                              
Loaded model mobilenet_v1_1.0_224_quant.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
invoked 
average time: 66.784 ms 
0.419608: 907 Windsor tie
0.356863: 653 military uniform
0.0352941: 458 bow tie
0.027451: 668 mortarboard
0.0235294: 543 drumstick
walleye:/data/local/tmp $./label_image_new_aarch64  -m mobilenet_v1_1.0_224_quant.tflite  -t 2                                                              
Loaded model mobilenet_v1_1.0_224_quant.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
invoked 
average time: 36.938 ms 
0.215686: 543 drumstick
0.129412: 594 harmonica
0.0470588: 700 panpipe
0.0470588: 559 flute
0.0235294: 773 safety pin
walleye:/data/local/tmp $./label_image_new_aarch64  -m mobilenet_v1_1.0_224_quant.tflite  -t 3                                                              
Loaded model mobilenet_v1_1.0_224_quant.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
invoked 
average time: 32.779 ms 
0.592157: 797 ski mask
0.258824: 434 bathing cap
0.0156863: 728 planetarium
0.0117647: 736 poncho
0.00784314: 773 safety pin
walleye:/data/local/tmp $ ./label_image_new_aarch64  -m mobilenet_v1_1.0_224_quant.tflite  -t 4                                                              <
Loaded model mobilenet_v1_1.0_224_quant.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
invoked 
average time: 25.737 ms 
0.823529: 728 planetarium
0.0352941: 669 mosque
0.0156863: 434 bathing cap
0.0156863: 418 balloon
0.0117647: 611 jersey
walleye:/data/local/tmp $ 
```
**Describe the expected behavior**
2, 3, 4 threads (`-t 2, -t 3, -t 4`) are expected to return the same results as single-thread case.
**Code to reproduce the issue**
TFLite `label_image_new_aarch64`: 

```
bazel build --config android_arm --cxxopt=-std=c++11  tensorflow/lite/examples/label_image:label_image  --config monolithic
```

label_image needs input image and labels file. I use
input_image:  [grace_hoper.bmp](https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp)
labels.txt: from [mobilenet_v1_1.0_224_frozen.tgz](https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_1.0_224_frozen.tgz 
)
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by buaadf** [comment] 2019-04-03 01:41
Did you use `implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'` , I  rebuild my project and got incorrect result recently but it works fine a few weeks ago,  I change that to version 1.13.1 and I got correct result but longer inference time, I think that's a bug in new version since it updates every day.

**Comment by buaadf** [comment] 2019-04-03 01:43
FYI, I got wrong results only when I use multiThreads

**Comment by freedomtan** [comment] 2019-04-03 01:59
@buaadf I built from source code. I think what you got from `org.tensorflow:tensorflow-lite:0.0.0-nightly` is the same problem. That is, source code changes intended to improve performance broke multithreaded results.

**Comment by WenguoLi** [comment] 2019-04-03 08:50
I have the same problem!

**Comment by tanzhenyu** [comment] 2019-04-05 17:46
Reassigning to TFLite.

**Comment by JionBin** [comment] 2019-04-10 07:10
Any update? I also encounter the same issue on arm-64 linux.
`./label_image --labels=labels.txt --image=dog.bmp --tflite_model=mobilenet_quant_v1_224.tflite --**threads=1**
Loaded model mobilenet_quant_v1_224.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
invoked 
average time: 242.961 ms 
0.988235: 209 Labrador retriever
0.00784314: 208 golden retriever
0.00392157: 435 bath towel
0.00392157: 163 beagle`
`./label_image --labels=labels.txt --image=dog.bmp --tflite_model=mobilenet_quant_v1_224.tflite --**threads=4**
Loaded model mobilenet_quant_v1_224.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
invoked 
average time: 70.697 ms 
0.172549: 751 quilt
0.145098: 895 wardrobe
0.0627451: 521 crib
0.0392157: 877 tub
0.0313726: 670 mosquito net`
`./label_image --labels=labels.txt --image=dog.bmp --tflite_model=mobilenet_quant_v1_224.tflite --**threads=6**
Loaded model mobilenet_quant_v1_224.tflite
resolved reporter
INFO: Initialized TensorFlow Lite runtime.
invoked 
average time: 52.457 ms_ 
0.392157: 521 crib
0.203922: 670 mosquito net
0.145098: 751 quilt
0.0901961: 832 studio couch
0.0901961: 565 four-poster`

**Comment by lu-wang-g** [comment] 2019-04-10 23:38
I tried to convert the .pb model as attached in the issue into tflite, but failed due to the ops "Dequantize". May I know how was this mobilenet_v1_1.0_224_quant.tflite generated?

**Comment by freedomtan** [comment] 2019-04-11 00:20
@lu-wang-g the `mobilenet_v1_1.0_224_quant.tflite` I tried is from this [hosted model](http://download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224_quant.tgz). There is no labels in this hosted model. So I have to get it elsewhere. Sorry for confusing you.

**Comment by lu-wang-g** [comment] 2019-04-22 23:43
Thank you for reporting the issue and providing information to reproduce it! There is a fix to the bug, and the change has been submitted. Please check it.

**Closed by lu-wang-g** 2019-04-22 23:43 UTC
Labels: comp:lite, type:bug/performance
