### ISSUE TITLE
Very low accuracy in the mnist dataset with cnn when running on a GPU using tensorflow

### ISSUE THREAD

**Issue by vivounicorn** [tensorflow/tensorflow#3891] opened 2016-08-18 05:10 UTC
hi everyone:
I tried to run an examples of MNIST with cnn and when i only use cpu the code can work well  **but when i use gpu it is not working well and  it has very low accuracy**. 
## environment like this
 GPU:Geforce GTX1070
 Cuda toolkit version：7.5
 cuDNN version：7.0
tensorflow version：0.9r

## code like this:
``` python
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

def weight_varible(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')


mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
print("Download Done!")

sess = tf.InteractiveSession()

# paras
W_conv1 = weight_varible([5, 5, 1, 32])
b_conv1 = bias_variable([32])

# conv layer-1
x = tf.placeholder(tf.float32, [None, 784])
x_image = tf.reshape(x, [-1, 28, 28, 1])

h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)

# conv layer-2
W_conv2 = weight_varible([5, 5, 32, 64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)

# full connection
W_fc1 = weight_varible([7 * 7 * 64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1, 7 * 7 * 64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

# dropout
keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

# output layer: softmax
W_fc2 = weight_varible([1024, 10])
b_fc2 = bias_variable([10])

y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2) + b_fc2)
y_ = tf.placeholder(tf.float32, [None, 10])

# model training
cross_entropy = -tf.reduce_sum(y_ * tf.log(y_conv))
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

correct_prediction = tf.equal(tf.arg_max(y_conv, 1), tf.arg_max(y_, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

sess.run(tf.initialize_all_variables())

for i in range(20000):
    batch = mnist.train.next_batch(50)

    if i % 100 == 0:
        train_accuacy = accuracy.eval(feed_dict={x: batch[0], y_: batch[1], keep_prob: 1.0})
        print("step %d, training accuracy %g"%(i, train_accuacy))
    train_step.run(feed_dict = {x: batch[0], y_: batch[1], keep_prob: 0.5})

# accuacy on test
print("test accuracy %g"%(accuracy.eval(feed_dict={x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0})))
```

### on cpu
step 0, training accuracy 0.06
step 100, training accuracy 0.8
step 200, training accuracy 0.94
step 300, training accuracy 0.9
step 400, training accuracy 0.92
step 500, training accuracy 0.84
step 600, training accuracy 1
step 700, training accuracy 0.96
step 800, training accuracy 0.94
step 900, training accuracy 1
step 1000, training accuracy 0.98
step 1100, training accuracy 0.92
step 1200, training accuracy 0.96
step 1300, training accuracy 1
step 1400, training accuracy 1
step 1500, training accuracy 1
......
test accuracy 0.9671
### on gpu
step 0, training accuracy 0.1
step 100, training accuracy 0.08
step 200, training accuracy 0.02
step 300, training accuracy 0.12
step 400, training accuracy 0.1
step 500, training accuracy 0.1
step 600, training accuracy 0.12
step 700, training accuracy 0.12
step 800, training accuracy 0.1
step 900, training accuracy 0.04
step 1000, training accuracy 0.12
step 1100, training accuracy 0.3
step 1200, training accuracy 0.1
step 1300, training accuracy 0.08
step 1400, training accuracy 0.12
step 1500, training accuracy 0.2
......
test accuracy 0.1160

**Comment by vivounicorn** [comment] 2016-08-18 05:19
Sometimes there will be some mistakes, the gpu log like this(it looks like out of memory):
>
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (256): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (512): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (1024): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (2048): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (4096): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (8192): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (16384): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (32768): 	Total Chunks: 1, Chunks in use: 0 34.2KiB allocated for chunks. 4.79MiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (65536): 	Total Chunks: 1, Chunks in use: 0 125.0KiB allocated for chunks. 4B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (131072): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (262144): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (524288): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (2097152): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (4194304): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (8388608): 	Total Chunks: 1, Chunks in use: 0 12.25MiB allocated for chunks. 390.6KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:639] Bin (268435456): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
I tensorflow/core/common_runtime/bfc_allocator.cc:656] Bin for 29.91MiB was 16.00MiB, Chunk State: 
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005800000 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005800100 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005800200 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005800300 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005800400 of size 4096
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005801400 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005801500 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005801600 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005801700 of size 3328
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005802400 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005802500 of size 204800
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005834500 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10005834600 of size 12845056
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006474600 of size 4096
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006475600 of size 40960
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000647f600 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000647f700 of size 3328
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480400 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480500 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480600 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480700 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480800 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480900 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480a00 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480b00 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480c00 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006480d00 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006489700 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006489800 of size 4096
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000648a800 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000648a900 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000648aa00 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000648ab00 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000648ac00 of size 3328
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000648b900 of size 40960
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006495900 of size 3328
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006496600 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006496700 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10006496800 of size 204800
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x100064c8800 of size 204800
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x100064fa800 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x100064fa900 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x100064faa00 of size 12845056
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000713aa00 of size 12845056
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10007d7aa00 of size 4096
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10007d7ba00 of size 4096
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10007d7ca00 of size 40960
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10007d86a00 of size 40960
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10007d90a00 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10007d90b00 of size 256
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10007d90c00 of size 80128
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10007dc3900 of size 204800
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10008a35900 of size 12845056
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x10009675900 of size 31360000
I tensorflow/core/common_runtime/bfc_allocator.cc:674] Chunk at 0x1000b45dd00 of size 1733108480
I tensorflow/core/common_runtime/bfc_allocator.cc:683] Free at 0x10006480e00 of size 35072
I tensorflow/core/common_runtime/bfc_allocator.cc:683] Free at 0x10007da4500 of size 128000
I tensorflow/core/common_runtime/bfc_allocator.cc:683] Free at 0x10007df5900 of size 12845056
I tensorflow/core/common_runtime/bfc_allocator.cc:689]      Summary of in-use Chunks by size: 
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 31 Chunks of size 256 totalling 7.8KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 4 Chunks of size 3328 totalling 13.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 5 Chunks of size 4096 totalling 20.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 4 Chunks of size 40960 totalling 160.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 80128 totalling 78.2KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 4 Chunks of size 204800 totalling 800.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 4 Chunks of size 12845056 totalling 49.00MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 31360000 totalling 29.91MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:692] 1 Chunks of size 1733108480 totalling 1.61GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] Sum Total of in-use chunks: 1.69GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:698] Stats: 
Limit:                  1829961728
InUse:                  1816953600
MaxInUse:               1816953600
NumAllocs:                  114506
MaxAllocSize:           1733108480
>
W tensorflow/core/common_runtime/bfc_allocator.cc:270] *************************************************************xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
W tensorflow/core/common_runtime/bfc_allocator.cc:271] Ran out of memory trying to allocate 29.91MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:909] Resource exhausted: OOM when allocating tensor with shape[10000,1,28,28]

**Comment by suiyuan2009** [comment] 2016-08-18 10:54
you can compute memory need of  your model to see if it exceeds your GPU memory.

**Comment by prb12** [comment] 2016-08-22 18:29
If you are getting out of memory errors when using GPU then clearly something is wrong and it is unlikely to train properly.  
Please can you clarify what card you're using.  The log messages imply you only have 1.69GB in use - I'm assuming this is quite a small GPU?
Also, as @suiyuan2009 states, you should probably check what the memory requirements of your model are.

This seems unlikely to be a TensorFlow bug, and you will probably be better off asking for support on StackOverflow.

**Comment by vivounicorn** [comment] 2016-08-23 01:47
@prb12 @suiyuan2009 thank you for your reply , my GPU is shared by 3 persons, so sometimes there has insufficient memory, but the low accuracy result is got when on exclusive resources.
so my point is why a low accuracy  result in the mnist dataset is got when running on a GPU. the following message is from **mnist_cnn.py** (a cnn example from tensorflow)
@vrv @vincentvanhoucke 

> (tensorflow)liyiran@seele:~/dllearning/mnist$ vim mnist_cnn.py 
(tensorflow)liyiran@seele:~/dllearning/mnist$ python mnist_cnn.py 
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Using TensorFlow backend.
X_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:924] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.7845
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.10GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 8s - loss: 2.3031 - acc: 0.1116 - val_loss: 2.3021 - val_acc: 0.1114
Epoch 2/12
60000/60000 [==============================] - 3s - loss: 2.3051 - acc: 0.1120 - val_loss: 2.3011 - val_acc: 0.1135
Epoch 3/12
60000/60000 [==============================] - 3s - loss: 2.3016 - acc: 0.1122 - val_loss: 2.3032 - val_acc: 0.1134
Epoch 4/12
60000/60000 [==============================] - 2s - loss: 2.3028 - acc: 0.1123 - val_loss: 2.3010 - val_acc: 0.1135
Epoch 5/12
60000/60000 [==============================] - 2s - loss: 2.3013 - acc: 0.1124 - val_loss: 2.3025 - val_acc: 0.1134
Epoch 6/12
60000/60000 [==============================] - 2s - loss: 2.3023 - acc: 0.1123 - val_loss: 2.3010 - val_acc: 0.1135
Epoch 7/12
60000/60000 [==============================] - 2s - loss: 2.3013 - acc: 0.1124 - val_loss: 2.3009 - val_acc: 0.1135
Epoch 8/12
60000/60000 [==============================] - 3s - loss: 2.3013 - acc: 0.1124 - val_loss: 2.3010 - val_acc: 0.1135
Epoch 9/12
60000/60000 [==============================] - 3s - loss: 2.3013 - acc: 0.1124 - val_loss: 2.3022 - val_acc: 0.1135
Epoch 10/12
60000/60000 [==============================] - 3s - loss: 2.3013 - acc: 0.1124 - val_loss: 2.3010 - val_acc: 0.1135
Epoch 11/12
60000/60000 [==============================] - 3s - loss: 2.3012 - acc: 0.1123 - val_loss: 2.3028 - val_acc: 0.1135
Epoch 12/12
60000/60000 [==============================] - 3s - loss: 2.3014 - acc: 0.1123 - val_loss: 2.3010 - val_acc: 0.1135
Test score: 2.30167105103
Test accuracy: 0.1135

the code of mnist_cnn.py is:
``` python
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility
import tensorflow as tf
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils

def run():
  batch_size = 128
  nb_classes = 10
  nb_epoch = 12

  # input image dimensions
  img_rows, img_cols = 28, 28
  # number of convolutional filters to use
  nb_filters = 32
  # size of pooling area for max pooling
  nb_pool = 2
  # convolution kernel size
  nb_conv = 3


  # the data, shuffled and split between train and test sets
  (X_train, y_train), (X_test, y_test) = mnist.load_data()

  X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
  X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
  X_train = X_train.astype('float32')
  X_test = X_test.astype('float32')
  X_train /= 255
  X_test /= 255
  print('X_train shape:', X_train.shape)
  print(X_train.shape[0], 'train samples')
  print(X_test.shape[0], 'test samples')
  
  # convert class vectors to binary class matrices
  Y_train = np_utils.to_categorical(y_train, nb_classes)
  Y_test = np_utils.to_categorical(y_test, nb_classes)

  model = Sequential()

  model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                          border_mode='valid',
                          input_shape=(img_rows, img_cols, 1), dim_ordering='tf'))
  model.add(Activation('relu'))
  model.add(Convolution2D(nb_filters, nb_conv, nb_conv))
  model.add(Activation('relu'))
  model.add(MaxPooling2D(pool_size=(nb_pool, nb_pool)))
  model.add(Dropout(0.25))

  model.add(Flatten())
  model.add(Dense(128))
  model.add(Activation('relu'))
  model.add(Dropout(0.5))
  model.add(Dense(nb_classes))
  model.add(Activation('softmax'))

  model.compile(loss='categorical_crossentropy',
                optimizer='adadelta',
                metrics=['accuracy'])

  model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
            verbose=1, validation_data=(X_test, Y_test))
  score = model.evaluate(X_test, Y_test, verbose=0)
  print('Test score:', score[0])
  print('Test accuracy:', score[1])

if __name__ == "__main__":
  with tf.device('/gpu:0'): 
  #with tf.device('/cpu:0'): 
    run()
```

when i replace gpu by cpu, then the result is like this:
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Using TensorFlow backend.
X_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:924] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.7845
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.10GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 65s - loss: 0.3884 - acc: 0.8818 - val_loss: 0.1009 - val_acc: 0.9686
Epoch 2/12
60000/60000 [==============================] - 71s - loss: 0.1462 - acc: 0.9561 - val_loss: 0.0661 - val_acc: 0.9793
Epoch 3/12
60000/60000 [==============================] - 69s - loss: 0.1109 - acc: 0.9672 - val_loss: 0.0541 - val_acc: 0.9828
Epoch 4/12
60000/60000 [==============================] - 66s - loss: 0.0903 - acc: 0.9734 - val_loss: 0.0498 - val_acc: 0.9840
Epoch 5/12
60000/60000 [==============================] - 68s - loss: 0.0826 - acc: 0.9759 - val_loss: 0.0421 - val_acc: 0.9863
Epoch 6/12
60000/60000 [==============================] - 67s - loss: 0.0734 - acc: 0.9786 - val_loss: 0.0383 - val_acc: 0.9871
Epoch 7/12
60000/60000 [==============================] - 68s - loss: 0.0659 - acc: 0.9802 - val_loss: 0.0373 - val_acc: 0.9879
Epoch 8/12
60000/60000 [==============================] - 66s - loss: 0.0622 - acc: 0.9818 - val_loss: 0.0348 - val_acc: 0.9883
Epoch 9/12
60000/60000 [==============================] - 66s - loss: 0.0574 - acc: 0.9826 - val_loss: 0.0361 - val_acc: 0.9880
Epoch 10/12
60000/60000 [==============================] - 66s - loss: 0.0538 - acc: 0.9843 - val_loss: 0.0331 - val_acc: 0.9888
Epoch 11/12
60000/60000 [==============================] - 66s - loss: 0.0520 - acc: 0.9843 - val_loss: 0.0311 - val_acc: 0.9900
Epoch 12/12
60000/60000 [==============================] - 64s - loss: 0.0495 - acc: 0.9849 - val_loss: 0.0311 - val_acc: 0.9901
Test score: 0.0310514848216
Test accuracy: 0.9901

**Comment by vrv** [comment] 2016-08-23 02:05
Try using CUDA 8.0 RC, I don't think TF works with 1070 or 1080 series GPUs unless you compile from source with CUDA 8.0.

**Comment by vrv** [comment] 2016-08-23 02:06
(Closing because I think this is a duplicate of a lot of existing issues that are solved by upgrading cuda)

**Closed by vrv** 2016-08-23 02:06 UTC
Labels: awaiting response

**Comment by Mazecreator** [comment] 2016-08-23 02:11
cuDNN needs to be 5.0 and CUDA needs to be 8.0 with latest Video driver 367.35.0

**Comment by vivounicorn** [comment] 2016-08-23 02:48
@vrv @Mazecreator thank you very much!

**Comment by vivounicorn** [comment] 2016-09-05 12:49
the problem is solved. TF 0.9/0.10 need CUDA 8.0, pip install can not support it, so we should compile it form source code and choose CUDA version 8.0.
