### ISSUE TITLE
input tensor lost in --mode eightbit quantization

### ISSUE THREAD

**Issue by tachim** [tensorflow/tensorflow#4847] opened 2016-10-08 19:36 UTC
Quantizing with --mode eightbit somehow loses the input tensor, whereas other methods like weights_rounded don't. If I do this:

`python quantize_graph.py --input ~/proc/frozen_inference_optimized.pb --output ~/proc/frozen_inference_optimized_quantized.pb --output_node_names on_logits --mode eightbit`

the following error pops up in the iOS tensorflow runtime:

`Running model failed:Not found: FeedInputs: unable to find feed output preprocess/centered_bgr`

Here `preprocess/centered_bgr` is the node I want to use as the input. If instead I use something like `--mode weights_rounded` no error is raised and the network functions as expected.
### Environment info

Operating System: ubuntu / iOS

Installed version of CUDA and cuDNN: 

```
root@0f1fd91e29a1:~/w/tensorflow/tensorflow/contrib/quantization/tools# ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root 322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root 720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
```

Commit I'm using: 8915f0f8072c406ae3fe0dff888f51b4cad02d7d. bazel version 0.3.0.

cc @petewarden

**Comment by jart** [comment] 2016-10-13 04:13
Does this information help solve your problem?

```markdown
### I am getting APP_ERROR(5) during inference, how do I fix that?

Here's a typical error:

`"APP_ERROR(5) FeedInputs: unable to find feed output x"`

This typically means that your model was not exported correctly, or that you've
not formatted the request properly. Double check your [signatures](#signatures)
and request format.
```

**Comment by tachim** [comment] 2016-10-13 15:12
Hi @jart, no, it doesn't because it works with a different quantization of the same frozen model file and the same runtime code on iOS.

**Comment by jart** [comment] 2016-10-15 08:02
Thank you for your patience @tachim.

@petewarden and @cwhipkey would be the best ones to help out with this.

**Comment by petewarden** [comment] 2016-10-17 21:23
As a temporary workaround, can you try the following to see if it fixes the issue?

`python quantize_graph.py --input ~/proc/frozen_inference_optimized.pb --output ~/proc/frozen_inference_optimized_quantized.pb --output_node_names on_logits,preprocess/centered_bgr --mode eightbit`

Here I've added the input node to the list of outputs. The issue is that it's deciding that the input node 'preprocess/centered_bgr' isn't needed, so I'm forcing it to include it by listing it as an output. If that fixes the immediate issue, it will give more information about what's going wrong.

**Comment by vincentvanhoucke** [comment] 2017-02-02 17:28
Is this still an open issue?

**Comment by girving** [comment] 2017-06-16 20:56
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by girving** 2017-06-16 20:56 UTC
