### ISSUE TITLE
TensorFlow 1.4 (gpu Linux) Py36 not built with Py36

### ISSUE THREAD

**Issue by dartdog** [tensorflow/tensorflow#14218] opened 2017-11-03 15:48 UTC
Installed TF 1.4 with pip install --ignore-installed --upgrade  https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.0-cp36-cp36m-linux_x86_64.whl
Gives me this error on import:
/home/tom/anaconda3/envs/tf4/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Similar error reported form Tensorboard:
/home/tom/anaconda3/envs/tf4/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
TensorBoard 0.4.0rc2 at http://tomServal:6006 (Press CTRL+C to quit)

**Comment by zhedongzheng** [comment] 2017-11-03 15:56
the same

**Comment by mrry** [comment] 2017-11-03 17:39
Closing this as a duplicate of #14182. Please follow along on that thread!

**Closed by mrry** 2017-11-03 17:39 UTC
