### ISSUE TITLE
full integer quantization error

### ISSUE THREAD

**Issue by shlomi-amitai** [tensorflow/tensorflow#44052] opened 2020-10-15 13:54 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (or github SHA if from source):
Nightly

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
The exact command
tflite_model = converter.convert()

**The output from the converter invocation**
Exception has occurred: ValueError
Failed to parse the model: pybind11::init(): factory function returned nullptr.

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
runtime error
Failed to parse the model: pybind11::init(): factory function returned nullptr.

the conversion works w/o quantization AND with dynamic range quantization. BUT, when I add representive dataset for converting full integer quantization with float fallback it fails with the above error.

I also use these flags:
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
since some of the operators are not yet implemented in tflite so maybe it's related to the root cause.

Would be happy to get your advice.

**Comment by amahendrakar** [comment] 2020-10-16 08:50
@shlomi-amitai,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by shlomi-amitai** [comment] 2020-10-18 07:01
Hi,
I'm sorry but can't send the source code.
I will try, however, to send a snippet.

Shlomi

**Comment by shlomi-amitai** [comment] 2020-10-20 10:44
[model4Quant.zip](https://github.com/tensorflow/tensorflow/files/5408084/model4Quant.zip)
Hi,
protobuffer (.pb) model and test code attached.
tf nightly version : 2.4.0.dev20201002

**Comment by amahendrakar** [comment] 2020-10-26 12:43
Was able to reproduce the issue. 

Session crashes on running the code with TF v2.3. Whereas, with TF-nightly, the error changes to `<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3221034a61bfcd53444ff2a277322845/44052.ipynb). Thanks!

**Comment by shlomi-amitai** [comment] 2020-10-26 13:22
I have slicing and tensor indexing in the model. when I remove them, the problem solved.
but then there is another problem. the output values are constant or zeros.
my guess is that it's related to the tf ops that are not supported by tflite.
attached the tflite model.
[model.zip](https://github.com/tensorflow/tensorflow/files/5438984/model.zip)

**Comment by shlomi-amitai** [comment] 2020-10-26 13:23
I use these flags:
        converter.optimizations = [tf.lite.Optimize.DEFAULT] # dynamic range quantization
        converter.representative_dataset = representative_data_gen  # + float fallback quantization
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

**Comment by sushreebarsa** [comment] 2021-08-09 15:36
@shlomi-amitai It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest  stable Version of TF 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-23 16:53 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:lite, TFLiteConverter, TF 2.3
