### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by kiteros** [tensorflow/tensorflow#21967] opened 2018-08-30 08:37 UTC
Hello, I have tried many times to install tensorflow 1.5 on windows 10, but I encounter the same error each time : 
`python
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jules\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\jules\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\jules\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\jules\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.`

any help would be greatly appreciated

**Comment by tensorflowbutler** [comment] 2018-08-31 07:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Saltiyx** [comment] 2018-09-11 05:30
I have the same exact problem

**Comment by gunan** [comment] 2018-09-11 16:12
Maybe this?
https://github.com/protocolbuffers/protobuf/issues/5046

**Comment by tensorflowbutler** [comment] 2018-09-26 19:00
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-10-11 18:54
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-10-26 12:48
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-11-14 21:55
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-11-14 21:55 UTC
Labels: stat:awaiting response

**Comment by LazzariPaolo** [comment] 2018-11-26 11:39
I resolved this by upgrading Python 3.6.0 to Python 3.6.1, as suggested by @dongwenjian [here.](https://github.com/protocolbuffers/protobuf/issues/5046#issuecomment-439736098)

**Comment by Alfred17686** [comment] 2019-03-02 01:52
> 
> 
> I resolved this by upgrading Python 3.6.0 to Python 3.6.1, as suggested by @dongwenjian [here.](https://github.com/protocolbuffers/protobuf/issues/5046#issuecomment-439736098)

Just tried this and it worked! Thanks :)

**Comment by AVI18794** [comment] 2019-11-20 07:01
I have the lastest version of python and still I am facing the same issue. Any help will be appreciated. I tried upgrading and downgrading the python version as well.

**Comment by akshaydamale0312** [comment] 2020-05-20 11:05
ImportError: DLL load failed: The specified procedure could not be found.
