### ISSUE TITLE
Tensorflow and Opencv in C++

### ISSUE THREAD

**Issue by xav12358** [tensorflow/tensorflow#21785] opened 2018-08-22 06:50 UTC
Hello,

I just buy a Tensorflow and OpenCV application in C++ in Ubuntu. As soon as I add a Tensorflow object in my program I can't read images from the VideoCapture. The sended images are all black.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: IUbuntu 16.04
- **TensorFlow installed from (source or binary)**: I use Tensorflow 1.5 source to generate the 2 so files
- **TensorFlow version (use command below)**: 1.5 (source
- **Bazel version (if compiling from source)**: 0.9.0
- **GCC/Compiler version (if compiling from source)**: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
- **CUDA/cuDNN version**: None
- **GPU model and memory**: None
------------------------

I don't really understand why Tensorflow so file change the behaviors of OpenCV.

**Comment by tensorflowbutler** [comment] 2018-08-22 19:16
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment] 2018-09-06 18:58
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-21 19:03
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment] 2018-09-28 20:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-09-28 20:42 UTC
Labels: stat:awaiting response
