### ISSUE TITLE
HEAD compiles without error, but not completely? build_pip_package fails.

### ISSUE THREAD

**Issue by rdipietro** [tensorflow/tensorflow#2405] opened 2016-05-17 15:20 UTC
CentOS 6.7
Cuda 7.0
cuDNN 4.0.7

I resolve https://github.com/tensorflow/tensorflow/issues/2266 by hard coding the python2.7 path in `third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc`.

After also resolving a similar problem with `swig`, it compiles without errors:

```
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 228.884s, Critical Path: 199.55s
```

But it seems that `build_pip_package` was only partially (?) completed:

```
rdipiet2@jhu.edu@login-node03 tensorflow $ bazel-bin/tensorflow/tools/pip_package/build_pip_package testonly
Tue May 17 11:09:33 EDT 2016 : === Using tmpdir: /tmp/tmp.akIEI1WBAX
cp: cannot stat `bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/tensorflow': No such file or directory
cp: cannot stat `bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/external': No such file or directory
```

Any ideas? Could something be failing silently?

**Comment by zszhong** [comment] 2016-05-17 15:52
refer to `https://github.com/tensorflow/tensorflow/issues/2040`, they have solved this problem.

cp -r bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/__main__/* bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/

**Comment by mrry** [comment] 2016-05-17 16:29
Thanks for replying @zszhong! Closing this as a duplicate of #2040.

**Closed by mrry** 2016-05-17 16:29 UTC
