### ISSUE TITLE
install issue! --No module named core.framework.graph_pb2

### ISSUE THREAD

**Issue by andyyuan78** [tensorflow/tensorflow#1285] opened 2016-02-25 17:21 UTC
I build with the source code.
envy@ub1404:~/os_pri/github/tensorflow$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

envy@ub1404:~/os_pri/github$ sudo pip install /tmp/tensorflow_pkg/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
Unpacking /tmp/tensorflow_pkg/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /home/envy/.local/lib/python2.7/site-packages (from tensorflow==0.7.1)
Downloading/unpacking protobuf==3.0.0b2 (from tensorflow==0.7.1)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB): 326kB downloaded
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python2.7/dist-packages (from tensorflow==0.7.1)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.2 in /home/envy/.local/lib/python2.7/site-packages (from tensorflow==0.7.1)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/envy/.local/lib/python2.7/site-packages (from protobuf==3.0.0b2->tensorflow==0.7.1)
Installing collected packages: tensorflow, protobuf
Successfully installed tensorflow protobuf
Cleaning up...
envy@ub1404:~/os_pri/github$ pip show protobuf
---
Name: protobuf
Version: 3.0.0b2
Location: /usr/local/lib/python2.7/dist-packages
Requires: setuptools, six
envy@ub1404:~/os_pri/github$ pip show tensorflow
---
Name: tensorflow
Version: 0.7.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, protobuf, wheel, numpy
envy@ub1404:~/os_pri/github$ python tensorflow/tensorflow/models/image/mnist/convolutional.py
Traceback (most recent call last):
  File "tensorflow/tensorflow/models/image/mnist/convolutional.py", line 34, in <module>
    import tensorflow as tf
  File "/home/envy/os_pri/github/tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/envy/os_pri/github/tensorflow/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/envy/os_pri/github/tensorflow/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
envy@ub1404:~/os_pri/github$

**Comment by yash14123** [comment] 2016-02-25 18:30
[](http://stackoverflow.com/questions/33625824/importerror-no-module-named-core-framework-graph-pb2)
Is this of any help?

**Comment by yash14123** [comment] 2016-02-25 18:31
http://stackoverflow.com/questions/33625824/importerror-no-module-named-core-framework-graph-pb2
Is this of any help?

**Comment by andyyuan78** [comment] 2016-02-26 03:40
I had tried, it doesn;t not works,

**Comment by vrv** [comment] 2016-02-26 03:58
The error message should be pretty helpful, I think.

**Comment by jp330108** [comment] 2016-03-01 00:40
Having same problem after using pip install:

**[user@localhost ~]# sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl**
Collecting tensorflow==0.7.1 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.8MB 26kB/s 
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: six>=1.10.0 in /usr/lib/python2.7/site-packages (from tensorflow==0.7.1)
Collecting protobuf==3.0.0b2 (from tensorflow==0.7.1)
  Downloading protobuf-3.0.0b2-py2.py3-none-any.whl (326kB)
    100% |████████████████████████████████| 327kB 1.2MB/s 
Collecting wheel (from tensorflow==0.7.1)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 69kB 2.4MB/s 
Collecting numpy>=1.8.2 (from tensorflow==0.7.1)
  Downloading numpy-1.10.4.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 150kB/s 
Collecting setuptools (from protobuf==3.0.0b2->tensorflow==0.7.1)
  Downloading setuptools-20.2.2-py2.py3-none-any.whl (508kB)
    100% |████████████████████████████████| 512kB 1.3MB/s 
Building wheels for collected packages: numpy
  Running setup.py bdist_wheel for numpy
  Stored in directory: /root/.cache/pip/wheels/66/f5/d7/f6ddd78b61037fcb51a3e32c9cd276e292343cdd62d5384efd
Successfully built numpy
Installing collected packages: setuptools, protobuf, wheel, numpy, tensorflow
  Found existing installation: setuptools 18.8
    Uninstalling setuptools-18.8:
      Successfully uninstalled setuptools-18.8
  Found existing installation: protobuf 3.0.0a3
    Uninstalling protobuf-3.0.0a3:
      Successfully uninstalled protobuf-3.0.0a3
  Found existing installation: wheel 0.26.0
    Uninstalling wheel-0.26.0:
      Successfully uninstalled wheel-0.26.0
  Found existing installation: numpy 1.10.1
    Uninstalling numpy-1.10.1:
      Successfully uninstalled numpy-1.10.1
  Found existing installation: tensorflow 0.6.0
    Uninstalling tensorflow-0.6.0:
      Successfully uninstalled tensorflow-0.6.0
Successfully installed numpy-1.10.4 protobuf-3.0.0b2 setuptools-20.2.2 tensorflow-0.7.1 wheel-0.29.0
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


**[user@localhost ~]# python -c "import tensorflow as tf"**
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by girving** [comment] 2016-06-06 21:48
Closing.  The issue is that "you should not try to import tensorflow from its source directory", as the error message states.

**Closed by girving** 2016-06-06 21:48 UTC
