### ISSUE TITLE
Executing genrule //tensorflow/cc:string_ops_genrule failed (Exit 127): bash failed

### ISSUE THREAD

**Issue by aashishgaba-cn** [tensorflow/tensorflow#53794] opened 2022-01-17 10:56 UTC
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from source
- TensorFlow version: 1.14
- Python version: 2.7
- Installed using virtualenv? pip? conda?:
- Bazel version : 0.24.1
- GCC/Compiler version: 4.8
- CUDA/cuDNN version: 10.0
- I'm using an EC2 instance
   - Instance type: p2xlarge
   - AMI: Deep Learning Base AMI (Ubuntu 18.04) Version 47.0

**Describe the problem**
- I was following installation steps from here: https://github.com/cjweeks/tensorflow-cmake/blob/master/README.md

#### Step 1 => Clone tensorflow repo
```
sudo apt-get install autoconf automake libtool curl make g++ unzip  # Protobuf Dependencies
sudo apt-get install python-numpy swig python-dev python-wheel      # TensorFlow Dependencies
git clone https://github.com/tensorflow/tensorflow
git checkout v1.14.0
```
Enter the cloned repository, and append the following to the tensorflow/BUILD file:

#### Step 2 => Add build rule
```
cc_binary(
    name = "libtensorflow_all.so",
    linkshared = 1,
    linkopts = ["-Wl,--version-script=tensorflow/tf_version_script.lds"], # Remove this line if you are using MacOS
    deps = [
        "//tensorflow/core:framework_internal",
        "//tensorflow/core:tensorflow",
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/cc:scope",
        "//tensorflow/c:c_api",
    ],
)
```
#### Step 3 =>
```
./configure      # Note that this requires user input
bazel build tensorflow:libtensorflow_all.so --verbose_failures
```

## Error
- I'm getting some error on the last command `bazel build tensorflow:libtensorflow_all.so --verbose_failures` that the build failed
- The error log is stated in the next section

**Any other info / logs**
```
INFO: Analysed target //tensorflow:libtensorflow_all.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/ubuntu/downl/tensorflow/tensorflow/cc/BUILD:492:1: Executing genrule //tensorflow/cc:string_ops_genrule failed (Exit 127): bash failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/364fbdb85a069ae1952a655335bcdb22/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/opt/amazon/efa/lib:/opt/amazon/openmpi/lib:/usr/local/lib:/usr/lib: \
    PATH=/home/ubuntu/.local/bin:/opt/amazon/openmpi/bin/:/opt/amazon/efa/bin/:/usr/local/cuda/bin:/opt/aws/neuron/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_CONFIGURE_IOS=0 \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.7 \
    TF_NEED_CUDA=1 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_NEED_ROCM=0 \
    TF_NEED_TENSORRT=0 \
  /bin/bash bazel-out/k8-opt/genfiles/tensorflow/cc/string_ops_genrule.genrule_script.sh)
Execution platform: @bazel_tools//platforms:host_platform
bazel-out/host/bin/tensorflow/cc/ops/string_ops_gen_cc: symbol lookup error: bazel-out/host/bin/tensorflow/cc/ops/string_ops_gen_cc: undefined symbol: _ZN10tensorflow15shape_inference36BroadcastBinaryOpOutputShapeFnHelperEPNS0_16InferenceContextENS0_11ShapeHandleES3_PS3_
Target //tensorflow:libtensorflow_all.so failed to build
INFO: Elapsed time: 2.181s, Critical Path: 1.24s
INFO: 3 processes: 3 local.
FAILED: Build did NOT complete successfully
```

**Comment by tilakrayal** [comment] 2022-01-18 04:29
@aashishgaba-cn ,
We see that you are using tf version 1.14, 1.x is not actively supported, please update to latest stable v2.7 and let us know if you are using same issue.Also please take a look at this issue [1](https://stackoverflow.com/questions/33620794/how-to-build-and-use-google-tensorflow-c-api/33622489#33622489), [2](https://github.com/tensorflow/tensorflow/issues/23342) with the similar error.It helps.Thanks!

**Comment by aashishgaba-cn** [comment] 2022-01-18 16:12
@tilakrayal Thanks for the help.

I was able to build it but the `bazel-genfiles` folder wasn't generated.
I'm following this [link](https://github.com/cjweeks/tensorflow-cmake/blob/master/README.md) for building tensorflow from source. In one of the steps I need to copy the header files present in the `bazel-genfiles` [PFA: Screenshot]

![image](https://user-images.githubusercontent.com/69104012/149974709-fc7273ad-838f-4466-bd43-ce5b964c19d8.png)

Am I doing anything wrong?

**Comment by tilakrayal** [comment] 2022-01-19 09:29
@aashishgaba-cn ,
Glad that the build issue got resolved.Please take a look at this link [1](https://github.com/tensorflow/tensorflow/issues/53381) and [2](https://github.com/tensorflow/tensorflow/issues/35534) for the bazel files issue.It helps.Thanks!

**Comment by aashishgaba-cn** [comment] 2022-01-19 10:53
Hi @tilakrayal , thanks for sharing these. I've checked those issues out but couldn't use anything from them.
They point to a StackOverflow post, to which there's no solution.

My two main concerns are
1) my build doesn't create the bazel-genfiles folder needed for it.
2) missing device_attributes.pb.h

https://github.com/tensorflow/tensorflow/issues/53381
This issue talks about these but there's no clear solution mentioned there.

Can you point out the steps that I should take next?

**Comment by tilakrayal** [comment] 2022-01-19 10:54
@aashishgaba-cn ,
Looks like this is duplicate of issue #53381.Can you please close this issue, since it is already being tracked there? Thanks!

**Comment by aashishgaba-cn** [comment] 2022-01-19 10:57
@tilakrayal 
But I don't see a solution there and that issue is closed already.
The guy resolved something himself and didn't share what he did to resolve that. [Please check screenshot attached]
![image](https://user-images.githubusercontent.com/69104012/150116801-97e8fe71-9bb0-4451-b3ab-32c2b3b05519.png)


In case you know what it was, can you please share it here?

**Comment by sachinprasadhs** [comment] 2022-02-16 00:01
@aashishgaba-cn , The source which you are following is from the unofficial source and which was updated long back. There could have been changes in  the build configurations since then. 
Could you please try the build methods mentioned in our Tensorflow website. Thanks!

**Closed** 2022-03-02 00:31 UTC
Labels: stat:awaiting response, type:build/install, stalled, subtype: ubuntu/linux, TF 1.14
