### ISSUE TITLE
TensorBoard shows no histograms or events

### ISSUE THREAD

**Issue by orome** [tensorflow/tensorflow#2708] opened 2016-06-07 16:42 UTC
Running TensorBoard r0.9 results in graph visualizations as expected but all events and histograms that successfully displayed in r0.8 [are not](http://stackoverflow.com/q/37684739/656912).

Has r0.9 introduced a change to the command line that should be used to launch TensorBoard, or to the code needed to generate events and histograms for TensorBoard to display?

Note that neither new summaries and histograms written with recent runs using r0.9 TensorFlow, nor existing ones written (and displayed) in the past, are displayed. Graphs generated with both releases display as expected.

### Environment info
Operating System: OS X 10.11.5
TensorFlow: .9.0rc0

### Steps to reproduce
`tensorboard --logdir ./tflog --purge_orphaned_data`

### What have you tried?
Reverting to r0.8, which works as it originally did, displaying all events and histograms present in the `tflog `directory provided as the `logdir`. Reinstalling r0.9, which reproduces the error. A second attempt at reinstalling r0.8 resulted in a TensorBoard that displays jus the menu (no content) and uses a different style (a serif face).

**Comment by caisq** [comment] 2016-06-07 16:51
PTAL, @danmane

**Comment by orome** [comment] 2016-06-07 16:56
Here's the "events" page source:

```
<!DOCTYPE html>
<html>
  <head>
    <title>TensorBoard</title>
    <link rel="stylesheet" type="text/css" href="/lib/css/global.css">

    <script src="external/lodash/lodash.min.js"></script>
    <script src="external/d3/d3.min.js"></script>
    <script src="/external/plottable/plottable.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/external/plottable/plottable.css">

    <script src="external/graphlib/dist/graphlib.core.min.js"></script>
    <script src="external/dagre/dist/dagre.core.min.js"></script>

    <link rel="import" href="external/polymer/polymer.html">
    <script src="external/webcomponentsjs/webcomponents-lite.min.js"></script>

    <link rel="import" href="external/iron-ajax/iron-ajax.html">
    <link rel="import" href="external/iron-collapse/iron-collapse.html">
    <link rel="import" href="external/iron-list/iron-list.html">
    <link rel="import" href="external/paper-button/paper-button.html">
    <link rel="import" href="external/paper-checkbox/paper-checkbox.html">
    <link rel="import" href="external/paper-dialog/paper-dialog.html">
    <link rel="import" href="external/paper-dropdown-menu/paper-dropdown-menu.html">
    <link rel="import" href="external/paper-header-panel/paper-header-panel.html">
    <link rel="import" href="external/paper-icon-button/paper-icon-button.html">
    <link rel="import" href="external/paper-input/paper-input.html">
    <link rel="import" href="external/paper-item/paper-item.html">
    <link rel="import" href="external/paper-menu/paper-menu.html">
    <link rel="import" href="external/paper-progress/paper-progress.html">
    <link rel="import" href="external/paper-radio-button/paper-radio-button.html">
    <link rel="import" href="external/paper-radio-group/paper-radio-group.html">
    <link rel="import" href="external/paper-slider/paper-slider.html">
    <link rel="import" href="external/paper-styles/paper-styles.html">
    <link rel="import" href="external/paper-toggle-button/paper-toggle-button.html">
    <link rel="import" href="external/paper-toolbar/paper-toolbar.html">
    <link rel="import" href="external/paper-tabs/paper-tabs.html">

    <link rel="import" href="dist/tf-tensorboard.html">

  </head>
  <body>
    <tf-tensorboard></tf-tensorboard>
  </body>
</html>
```

**Comment by orome** [comment] 2016-06-07 16:58
I also get an

> SyntaxError: Unexpected token ')'

in the final line of 

    data:text/javascript;charset=utf-8,%0A…%0A:81

below:

```
      this.updateStyles();
      // The updateStyles call fails silently if the browser doesn't have focus,
      // e.g. if TensorBoard was opened into a new tab that isn't visible.
      // As a workaround... we know requestAnimationFrame won't fire until the
      // page has focus, so updateStyles again on requestAnimationFrame.
      window.requestAnimationFrame(() => this.updateStyles());
    },
```

**Comment by danmane** [comment] 2016-06-08 18:56
You're using Safari, right? This is a duplicate of https://github.com/tensorflow/tensorflow/issues/2607. It's fixed in source code but not in the distributed tf-tensorboard bundle; an update for the bundle is coming today.

**Closed by danmane** 2016-06-08 18:56 UTC
Labels: triaged

**Comment by orome** [comment] 2016-06-08 19:11
@danmane: Yes Safari. Thanks!

**Comment by alexmonroe87** [comment] 2016-08-14 18:16
I have this problem with Chromium 51.0.2704.79 Ubuntu 14.04 64bit
No visuals except for the main graph are showing.

**Comment by danmane** [comment] 2016-08-15 17:03
@alexmonroe87 Can you run TensorBoard with the --inspect flag and post what is generated?
