### ISSUE TITLE
TPU: keras support for multiples inputs layers

### ISSUE THREAD

**Issue by davidpham87** [tensorflow/tensorflow#23659] opened 2018-11-10 21:26 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colaboratory

**Describe the current behavior**

I am using the functional api of keras models, and TPU does not yet support multiple inputs layers.

**Describe the expected behavior**

It should support multiple inputs models.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in _validate_shapes(model)
   2077   """Validate that all layers in `model` have constant shape."""
   2078   for layer in model.layers:
-> 2079     if isinstance(layer.input_shape, tuple):
   2080       input_shapes = [layer.input_shape]
   2081     else:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in input_shape(self)
   1351     else:
   1352       raise AttributeError('The layer "' + str(self.name) +
-> 1353                            ' has multiple inbound nodes, '
   1354                            'with different input shapes. Hence '
   1355                            'the notion of "input shape" is '

AttributeError: The layer "model_encoder_vgg19 has multiple inbound nodes, with different input shapes. Hence the notion of "input shape" is ill-defined for the layer. Use `get_input_shape_at(node_index)` instead.
```
The issue is at line 2079 of `keras_support.py` where `get_input_shape_at(node_index)` should be used instead.

**Comment by torinaki** [comment] 2018-11-27 21:21
I have the similar issue when trying to reuse already compiled keras model and convert it into TPU model:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-002cb4c34948> in <module>()
     11     tf.keras.layers.Dense(1000)(training_model(training_model.inputs)),
     12     strategy=tf.contrib.tpu.TPUDistributionStrategy(
---> 13         tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)))
     14 
     15 tpu_model.fit_generator(

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/framework/experimental.py in new_func(*args, **kwargs)
     62         'any time, and without warning.',
     63         decorator_utils.get_qualified_name(func), func.__module__)
---> 64     return func(*args, **kwargs)
     65   new_func.__doc__ = _add_experimental_function_notice_to_docstring(
     66       func.__doc__)

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in tpu_model(model, strategy)
   2139     A new `KerasTPUModel` instance.
   2140   """
-> 2141   _validate_shapes(model)
   2142   # TODO(xiejw): Validate TPU model. TPUModel only?
   2143   # TODO(xiejw): Validate replicas. Full or 1. Shall we allow subset?

/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py in _validate_shapes(model)
   2076 def _validate_shapes(model):
   2077   """Validate that all layers in `model` have constant shape."""
-> 2078   for layer in model.layers:
   2079     if isinstance(layer.input_shape, tuple):
   2080       input_shapes = [layer.input_shape]

AttributeError: 'Tensor' object has no attribute 'layers'
```
I can be reproduced with ["Predict Shakespeare with Cloud TPUs and Keras"](https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/shakespeare_with_tpu_and_keras.ipynb#scrollTo=VzBYDJI0_Tfm) example. 
Changed code cell:
```python
tf.keras.backend.clear_session()

training_model = lstm_model(seq_len=100, batch_size=128, stateful=False)

tpu_model = tf.contrib.tpu.keras_to_tpu_model(
    training_model,
    strategy=tf.contrib.tpu.TPUDistributionStrategy(
        tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)))

tpu_model_reused = tf.contrib.tpu.keras_to_tpu_model(
    tf.keras.layers.Dense(1000)(training_model(training_model.inputs)),
    strategy=tf.contrib.tpu.TPUDistributionStrategy(
        tf.contrib.cluster_resolver.TPUClusterResolver(TPU_WORKER)))

tpu_model.fit_generator(
    training_generator(seq_len=100, batch_size=1024),
    steps_per_epoch=100,
    epochs=10,
)
tpu_model.save_weights('/tmp/bard.h5', overwrite=True)
```

**Comment by tgs266** [comment] 2019-01-04 01:16
@davidpham87 did you ever find a fix for this?

**Comment by davidpham87** [comment] 2019-01-04 08:39
I implemented the Estimator API (which will be depreciated in TF 2.0, lol)

**Comment by Lisandro79** [comment] 2019-03-13 05:41
@davidpham87  

I am trying to implement a siamese neural network with tf.keras and TPUs and I am running into the same issue "ValueError: The dataset must return a 2-element tuple" (when I have 2 input signals and 1 labelp; 3 inputs in total for the model)

I am getting this error even when using the Estimator API. May I ask you what Estimator API you used to solve this problem?

**Comment by saeta** [comment] 2019-03-13 17:59
Note: I'm working on Swift now, sorry!

**Comment by jvishnuvardhan** [comment] 2019-04-16 00:19
@davidpham87 Is this still an issue or was it resolved? Could you check with latest version of TF and let us know. Thanks!

**Comment by tensorflowbutler** [comment] 2019-04-30 13:05
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-04-30 15:43
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-30 15:43 UTC
Labels: comp:tpus, stat:awaiting response, type:bug/performance

**Comment by naoya-i** [comment] 2019-06-22 00:56
Hi! Has anyone solved this issue?

My workaround is to replace the first half of `_validate_shapes()` function in `keras_support.py` with the following. It works great for me, at least!

```
def _validate_shapes(model):
  """Validate that all layers in `model` have constant shape."""
  for layer in model.layers:
    for i in range(len(layer._inbound_nodes)):
      input_shape = layer.get_input_shape_at(i)

      if isinstance(input_shape, tuple):
        input_shapes = [input_shape]
      else:
        input_shapes = input_shape

    for i in range(len(layer._inbound_nodes)):
      output_shape = layer.get_output_shape_at(i)

      if isinstance(output_shape, tuple):
        output_shapes = [output_shape]
      else:
        output_shapes = output_shape

  for shape in input_shapes + output_shapes:
    for dim in shape[1:]:
```

I hope this helps!
