### ISSUE TITLE
TF-TRT slower than plain TF on FasterRCNN type networks. 

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#30779] opened 2019-07-16 23:02 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda-10.1
- GPU model and memory: T4

**Describe the current behavior**
I have noticed that   throughput of FasterRCNN type object detector is slower with TF-TRT than just TF. 
 
**Describe the expected behavior**
Was expecting to see  higher throughput  with TF-TRT.

**Code to reproduce the issue**
Try any off the shelf FasterRCNN network 

**Other info / logs**
None

**Comment by ravikyram** [comment] 2019-07-17 08:45
@sgambient 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sgambient** [comment] 2019-07-19 22:07
Hi, tried to recreate the problem with a Tensorflow Object Detection model. Looks like TF_TRT is not even able to convert.  The error I get is as follows: 

`ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: {{node Preprocessor/map/while/ResizeToRange/strided_slice/stack}}`


**My hacked up code follow**s: 

(https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb )

```
# cat object_detection_tutorial.py
import numpy as np                              
import os        
import six.moves.urllib as urllib                      
import sys                              
import tarfile
import tensorflow as tf                                                                              
import tensorflow.contrib.tensorrt as trt     
import zipfile                                                                                            
import time                      
                                        
from distutils.version import StrictVersion
from collections import defaultdict
from io import StringIO                                             
#from matplotlib import pyplot as plt
from PIL import Image               
                                   
# This is needed since the notebook is stored in the object_detection folder.
sys.path.append("..")              
from object_detection.utils import ops as utils_ops                               
                                                                              
if StrictVersion(tf.__version__) < StrictVersion('1.12.0'):
  raise ImportError('Please upgrade your TensorFlow installation to v1.12.*.')
                                               
# This is needed to display the images.            
#%matplotlib inline                                                          
                                                     
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util
                                                
# What model to download.
MODEL_NAME = 'ssd_mobilenet_v1_coco_2017_11_17'
MODEL_NAME = 'faster_rcnn_resnet101_coco_2018_01_28'
MODEL_FILE = MODEL_NAME + '.tar.gz'                                    
DOWNLOAD_BASE = 'http://download.tensorflow.org/models/object_detection/'

# Path to frozen detection graph. This is the actual model that is used for the object detection.
PATH_TO_FROZEN_GRAPH = MODEL_NAME + '/frozen_inference_graph.pb'
                                                                                        
# List of the strings that is used to add correct label for each box.    
PATH_TO_LABELS = os.path.join('data', 'mscoco_label_map.pbtxt')                                                  
                                                                                
def download_ckpt():                                                                 
    opener = urllib.request.URLopener()                                                     
    opener.retrieve(DOWNLOAD_BASE + MODEL_FILE, MODEL_FILE)                   
    tar_file = tarfile.open(MODEL_FILE)                                      
    for file in tar_file.getmembers():     
      file_name = os.path.basename(file.name)                   
      if 'frozen_inference_graph.pb' in file_name:                
        tar_file.extract(file, os.getcwd())                                             
                                        
def load_image_into_numpy_array(image):                                                                                                                                                               [107/1176]
  (im_width, im_height) = image.size
  return np.array(image.getdata()).reshape(
      (im_height, im_width, 3)).astype(np.uint8)

# For the sake of simplicity we will use only 2 images:
# image1.jpg
# image2.jpg
# If you want to test the code with your images, just add path to the images to the TEST_IMAGE_PATHS.
PATH_TO_TEST_IMAGES_DIR = 'test_images'
TEST_IMAGE_PATHS = [ os.path.join(PATH_TO_TEST_IMAGES_DIR, 'image{}.jpg'.format(i)) for i in range(1, 3) ]

# Size, in inches, of the output images.
IMAGE_SIZE = (12, 8)

def build_graph (detection_graph):

  with detection_graph.as_default():
    od_graph_def = tf.GraphDef()
    with tf.gfile.GFile(PATH_TO_FROZEN_GRAPH, 'rb') as fid:
      serialized_graph = fid.read()
      od_graph_def.ParseFromString(serialized_graph)
      tf.import_graph_def(od_graph_def, name='')

  with detection_graph.as_default():
      # Get handles to input and output tensors
      ops = tf.get_default_graph().get_operations()
      all_tensor_names = {output.name for op in ops for output in op.outputs}
      tensor_dict = {}
      for key in [
          'num_detections', 'detection_boxes', 'detection_scores',
          'detection_classes', 'detection_masks'
      ]:
        tensor_name = key + ':0'
        if tensor_name in all_tensor_names:
          tensor_dict[key] = tf.get_default_graph().get_tensor_by_name(
              tensor_name)

      if 'detection_masks' in tensor_dict:
        # The following processing is only for single image
        detection_boxes = tf.squeeze(tensor_dict['detection_boxes'], [0])
        detection_masks = tf.squeeze(tensor_dict['detection_masks'], [0])
        # Reframe is required to translate mask from box coordinates to image coordinates and fit the image size.
        real_num_detection = tf.cast(tensor_dict['num_detections'][0], tf.int32)
        detection_boxes = tf.slice(detection_boxes, [0, 0], [real_num_detection, -1])
        detection_masks = tf.slice(detection_masks, [0, 0, 0], [real_num_detection, -1, -1])
        detection_masks_reframed = utils_ops.reframe_box_masks_to_image_masks(
            detection_masks, detection_boxes, image.shape[1], image.shape[2])
        detection_masks_reframed = tf.cast(
            tf.greater(detection_masks_reframed, 0.5), tf.uint8)
        # Follow the convention by adding back the batch dimension
        tensor_dict['detection_masks'] = tf.expand_dims(
            detection_masks_reframed, 0)

      return tensor_dict

class TfTrt():                                                                                                                                                                                         [51/1176]

    @staticmethod
    def build(sess, graph):
        tensor_dict = build_graph(graph)

        outputl = []
        for i,nname in enumerate(tensor_dict):
            print( i, nname, tensor_dict[nname].name )
            outputl.append(nname)
        print ( "outputl ", outputl)

        # Freeze the graph:
        frozen_graph = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        output_node_names= outputl)

        # remove training nodes
        frozen_graph = tf.compat.v1.graph_util.remove_training_nodes(frozen_graph)
        # Now you can create a TensorRT inference graph from your frozen graph

        trt_graph = trt.create_inference_graph(
            input_graph_def=frozen_graph,
            outputs = outputl,
            max_batch_size=1,
            max_workspace_size_bytes= 1024*1024*1024,
            precision_mode="FP16")

        output_nodes = tf.import_graph_def(
            trt_graph,
            return_elements = outputl
        )

        return output_nodes

    @staticmethod
    def run(sess, tensor_dict, image_tensor, image_np_expanded):
        output_dict = sess.run(tensor_dict, feed_dict={image_tensor: image_np_expanded})
        return output_dict

class Tf():

    @staticmethod
    def build(sess, graph):
        return build_graph(graph)

    @staticmethod
    def run(sess, tensor_dict, image_tensor, image_np_expanded):
        output_dict = sess.run(tensor_dict, feed_dict={image_tensor: image_np_expanded})
        return output_dict

def run (RunClass):

    category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS, use_display_name=True)
    graph = tf.Graph()
    #tensor_dict = RunClass.build(graph)

    with tf.Session(graph=graph) as sess:
        tensor_dict = RunClass.build(sess, graph)
        file_writer = tf.summary.FileWriter('tensorboard', sess.graph)
        image_path = TEST_IMAGE_PATHS[0]
        print ( "image_path {}".format(image_path))
        image = Image.open(image_path)
        image = image.resize((640,480))
        image_np = load_image_into_numpy_array(image)
        image_np_expanded = np.expand_dims(image_np, axis=0)
        image_tensor = graph.get_tensor_by_name('image_tensor:0')
        time0 = time.time()
        for i in range(1,10001):
            # Actual detection.
            #output_dict = sess.run(tensor_dict, feed_dict={image_tensor: image_np_expanded})
            output_dict = RunClass.run(sess, tensor_dict, image_tensor, image_np_expanded)
            #output_dict = run_inference_for_single_image(sess, graph, image_np_expanded, tensor_dict)
            time_taken = (time.time() - time0 )/(i * 1.0)
            print ( "i ", i, time_taken)
        time_taken = (time.time() - time0 )/(i * 1.0)
        print ("time_taken ", time_taken)

        # all outputs are float32 numpy arrays, so convert types as appropriate
        output_dict['num_detections'] = int(output_dict['num_detections'][0])
        output_dict['detection_classes'] = output_dict[
            'detection_classes'][0].astype(np.int64)
        output_dict['detection_boxes'] = output_dict['detection_boxes'][0]
        output_dict['detection_scores'] = output_dict['detection_scores'][0]
        if 'detection_masks' in output_dict:
          output_dict['detection_masks'] = output_dict['detection_masks'][0]
        # Visualization of the results of a detection.
        vis_util.visualize_boxes_and_labels_on_image_array(
            image_np,
            output_dict['detection_boxes'],
            output_dict['detection_classes'],
            output_dict['detection_scores'],
            category_index,
            instance_masks=output_dict.get('detection_masks'),
            use_normalized_coordinates=True,
            line_thickness=8)
        im = Image.fromarray(image_np)
        save_file = "out-"+os.path.basename(image_path)
        im.save(save_file)


if __name__ == '__main__':

    run (TfTrt)
```

**Comment by jvishnuvardhan** [comment] 2019-07-23 20:26
@sgambient Can you try both `tf-nighly` and TF1.14 and let us know whether the issue persists with the latest TF versions. Thanks!

**Comment by sgambient** [comment] 2019-08-02 23:05
Hi, tried it on 1.14 and get the following error. 

```
E tensorflow/core/grappler/grappler_item_builder.cc:631] Fetch node num_detections doesn't exist in graph
Traceback (most recent call last):
  File "./object_detection_tutorial.py", line 212, in <module>
    run (TfTrt)
  File "./object_detection_tutorial.py", line 167, in run
    tensor_dict = RunClass.build(sess, graph)
  File "./object_detection_tutorial.py", line 135, in build
    precision_mode="FP16")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorrt/python/trt_convert.py", line 51, in create_inference_graph
    session_config=session_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1146, in create_inference_graph
    converted_graph_def = trt_converter.convert()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 298, in convert
    self._convert_graph_def()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 226, in _convert_graph_def
    self._run_conversion()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 204, in _run_conversion
    graph_id=b"tf_graph")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/grappler/tf_optimizer.py", line 41, in OptimizeGraph
    verbose, graph_id)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to import metagraph, check error log for more info.
```

**Comment by sgambient** [comment] 2019-08-03 01:41
Same crap out on tensorflow/tensorflow:devel-gpu 

```
2019-08-03 01:33:54.323115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14221 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
2019-08-03 01:33:55.446324: E tensorflow/core/grappler/grappler_item_builder.cc:631] Fetch node num_detections doesn't exist in graph
Traceback (most recent call last):
  File "./object_detection_tutorial.py", line 212, in <module>
    run (TfTrt)
  File "./object_detection_tutorial.py", line 167, in run
    tensor_dict = RunClass.build(sess, graph)
  File "./object_detection_tutorial.py", line 135, in build
    precision_mode="FP16")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tensorrt/python/trt_convert.py", line 51, in create_inference_graph
    session_config=session_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 1146, in create_inference_graph
    converted_graph_def = trt_converter.convert()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 298, in convert
    self._convert_graph_def()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 226, in _convert_graph_def
    self._run_conversion()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 204, in _run_conversion
    graph_id=b"tf_graph")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/grappler/tf_optimizer.py", line 41, in OptimizeGraph
    verbose, graph_id)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to import metagraph, check error log for more info.
```

**Comment by aaroey** [comment] 2019-09-17 17:02
Thanks @sgambient for the script. I can reproduce the error with 1.15rc1.
The problem is the `remove_training_nodes` will remove identity nodes like the ones in the `outoutl` list in your script. Adding `protected_nodes=outputl` to the call solved the problem for me. 

I'm closing, feel free to reopen if the problem persists.

**Closed by aaroey** 2019-09-17 17:02 UTC
Labels: TF 1.13, comp:gpu, type:performance
