### ISSUE TITLE
tf.math.xdivy decorated with @tf.function returns 0 when the input is large

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#51643] opened 2021-08-23 20:47 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.6.0
- Python version: 3.7.11
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: running on CPU
- GPU model and memory: running on CPU

**Describe the current behavior**
When we feed large inputs to tf.math.xdivy decorated with @tf.function, we get outputs of 0, which is wrong.

**Describe the expected behavior**
The function returns correct results, just like what it does in eager mode.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**

    import pickle
    import tensorflow as tf
    
    input_path = "tf_math_xdivy_inputs.p"
    data = pickle.load(open(input_path, 'rb'))
    
    fun = tf.math.xdivy
    
    output1 = fun(**data) 
    print(output1)  # the results in eager mode is correct
    
    @tf.function
    def fun_wrapper(data):
        return fun(**data)
    
    output2 = fun_wrapper(data)
    print(output2)  # the results of tf function is wrong

The inputs are {'x': array([-3.0127542e+38+0.j], dtype=complex64), 'y': (2.0609168319398798e+37-2.2877970645017637e+38j)}.

Output1 is tf.Tensor([-0.11767363-1.3062797j], shape=(1,), dtype=complex64).

Output2 is tf.Tensor([-0.+0.j], shape=(1,), dtype=complex64).

This is the input for reproduction. Please decompress it before use.
[tf_math_xdivy_inputs.p.zip](https://github.com/tensorflow/tensorflow/files/7034126/tf_math_xdivy_inputs.p.zip)

We also detect similar issues with other apis. They are: tf.nn.compute_average_loss, tf.realdiv, tf.math.sign. We can provide corresponding inputs if necessary.

**Comment by sushreebarsa** [comment] 2021-08-24 07:45
@jiannanWang Could you please have a look at the[ link](https://www.tensorflow.org/guide/function), [link1](https://www.tensorflow.org/api_docs/python/tf/math/xdivy) and let us know if it helps? Thanks!

**Comment by jiannanWang** [comment] 2021-08-24 15:12
Thank you for your quick response! I have read the two links you provided, but I'm afraid they don't help. I think it's a correctness issue rather than a performance issue. Can you please be clearer and maybe provide more information? Because I don't understand why these two links might be helpful.

**Comment by sushreebarsa** [comment] 2021-08-25 11:57
@sanatmpa1 Was able to replicate the issue on colab using 2.5, 2.6 and tf-nightly,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/b1bc00df59ef75d376701bd93029f4fd/untitled407.ipynb#scrollTo=sJ0t_IhtGLP9) for reference.Thank you!

**Comment by jiannanWang** [comment] 2021-08-30 21:03
I simplified the code to reproduce and now you don't need to download the input file.

    import tensorflow as tf
    import numpy as np
    
    x = np.array([-3.e+38+0.j], dtype='complex64')
    y = (2.e+37-2.e+38j)
    
    output1 = tf.math.xdivy(x, y)
    print(output1)  # the results in eager mode is correct
    
    @tf.function
    def fun_wrapper(x, y):
        return tf.math.xdivy(x, y)
    
    output2 = fun_wrapper(x, y)
    print(output2)  # the results of tf function is wrong

It seems to me this bug is caused by overflow or type conversion. I hope this can help you localize the bug. Thank you!

**Comment by jvishnuvardhan** [comment] 2021-08-31 23:12
@jiannanWang I can reproduce the issue. [Here](https://colab.research.google.com/gist/jvishnuvardhan/498379c3bd9ad6df2675ea405b7df307/untitled.ipynb) is a gist for our reference. Thanks!

**Comment by cantonios** [comment] 2021-09-02 18:23
Yes, this looks like an XLA overflow issue for complex division.  It's probably using the native complex division algorithm.

**Comment by chunduriv** [comment] 2022-06-15 13:20
@jiannanWang,

Sorry for the late response.    

Quote from documentation: 

>x | A Tensor. Must be one of the following types: half, float32, float64, complex64, complex128.
>y | A Tensor. Must have the same type as x.

Working Code:

```
import tensorflow as tf
import numpy as np

x1 = np.array([-3.e+38+0.j])
y1 = np.array([2.e+37-2.e+38j])

output1 = tf.math.xdivy(x1, y1)
print(output1)  # the results in eager mode are correct

@tf.function
def fun_wrapper(x, y):
    return tf.math.xdivy(x, y,)

output2 = fun_wrapper(x1, y1)
print(output2)  # the results of tf function is correct
```
Output:

```
tf.Tensor([-0.14851485-1.48514851j], shape=(1,), dtype=complex128)
tf.Tensor([-0.14851485-1.48514851j], shape=(1,), dtype=complex128)
```

**Comment by cantonios** [comment] 2022-06-16 01:17
Okay, so I tracked down the issue: in the case of the python constant,
```
y = (2.e+37-2.e+38j)
```
the `tf.function` version does some constant-folding graph optimizations, realizes the denominator is a constant scalar, computes the reciprocal `1/y` which underflows to zero, then applies `x * (1/y)`, resulting in zero.  I don't think we're going to remove this constant-folding optimization, since in the usual case it is correct and faster, especially when `x` is a very large tensor.  To manually fix this, you can create a numpy constant
```
y = np.csingle(2.e+37-2.e+38j)
```
or tensorflow constant
```
y = tf.constant(2.e+37-2.e+38j, dtype=tf.complex64)
```
and do the same `xdivy` division.  In both these cases, it will actually perform the x/y and give a non-zero result.

Closing, since this _is_ by design, and there is an easy work-around.

**Closed by cantonios** 2022-06-16 01:17 UTC
Labels: stat:awaiting response, type:bug, comp:tf.function, 2.6.0
