### ISSUE TITLE
lecun_normal and he_normal crash when type casting: TypeError: he_normal() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by nicolas-gervais** [tensorflow/tensorflow#39624] opened 2020-05-17 13:48 UTC
**System information**
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device if the issue happens on mobile device:
- TensorFlow installed from (source or binary): idk
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: none
- GPU model and memory: none

**Describe the expected behavior**

Successful type casting in `tf.data.Dataset.map()` function

**Standalone code to reproduce the issue**

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from tensorflow.keras import Model
import tensorflow as tf
from tensorflow.keras.layers import Dense
import tensorflow_datasets as tfds
from tensorflow.keras.initializers import glorot_normal, he_normal, lecun_normal

dataset, info = tfds.load('binary_alpha_digits', with_info=True, split='train')
data = dataset.map(lambda x: (tf.cast(x['image'], tf.float32), x['label'])).batch(8)


class Model(Model):
    def __init__(self):
        super(Model, self).__init__()
        self.layer1 = Dense(16, kernel_initializer=he_normal)
        self.layer2 = Dense(units=info.features['label'].num_classes)

    def call(self, inputs, training=None, **kwargs):
        x = self.layer1(inputs)
        x = self.layer2(x)
        return x


model = Model()
_ = model(next(iter(data))[0])
```
`glorot_normal`: works
`he_normal`: doesn't work
`lecun_normal`: doesn't work

**Comment by amahendrakar** [comment] 2020-05-18 12:49
@nicolas-gervais,
I was able to reproduce the error with TF v2.1 and [TF v2.2](https://colab.research.google.com/gist/amahendrakar/ef75f5e07621f04c2702ef3f789e243c/39624-2-2.ipynb). However, I was able to run the code without any issues with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/7c9fd985c3b0e15ee6b1e475b73a54e4/39624-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by nicolas-gervais** [comment] 2020-05-18 21:15
> @nicolas-gervais,
> Please find the attached gist. Thanks!
Hi, what response are you awaiting from me exactly? I am unable to change TF versions at the moment

**Comment by amahendrakar** [comment] 2020-05-19 04:36
@nicolas-gervais,
The issue you are facing seems to be fixed with the TF-nightly version. I did not face any errors while running the code with TF-nightly and have attached the link for Python notebook below

https://colab.research.google.com/gist/amahendrakar/7c9fd985c3b0e15ee6b1e475b73a54e4/39624-tf-nightly.ipynb

Could you please verify it on your end and let us know if it works. Thanks!

**Closed** 2020-06-02 06:10 UTC
Labels: TF 2.2, comp:data, stalled, stat:awaiting response, type:bug
