### ISSUE TITLE
mixed_precision make train and predict very slow when only using cpu

### ISSUE THREAD

**Issue by DachuanZhao** [tensorflow/tensorflow#45441] opened 2020-12-07 09:20 UTC
tensorflow : 2.3
Here is the [colab](https://colab.research.google.com/drive/1glypA7wC988kivuGe07Qfk_XHuq1j9aS?usp=sharing)
You can see that it costs 3s to train a epoch while costs 187s to train the same epoch using ```mixed_precision ```

```
Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2968 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1448 - accuracy: 0.9575
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1073 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0861 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0734 - accuracy: 0.9769
```
vs
```
Epoch 1/5
1875/1875 [==============================] - 187s 100ms/step - loss: 0.2936 - accuracy: 0.9141
Epoch 2/5
1179/1875 [=================>............] - ETA: 1:11 - loss: 0.1455 - accuracy: 0.9555
```

**Comment by Saduf2019** [comment] 2020-12-07 09:58
@DachuanZhao 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [steps followed before you ran into this error or stand alone code to reproduce the issue faced, if possible colab gist with the error]

**Comment by DachuanZhao** [comment] 2020-12-07 10:04
> @DachuanZhao
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [steps followed before you ran into this error or stand alone code to reproduce the issue faced, if possible colab gist with the error]

I think this bug is a common bug which means it may exist in many versions . So I only give the tensroflow version . 
I have post a colab , and you can run the code in the colab .

**Comment by byronyi** [comment] 2020-12-07 10:20
Why using mixed precision with CPU? As said in the [doc](https://www.tensorflow.org/guide/mixed_precision), 

> As mentioned before, the mixed_float16 policy will most significantly improve performance on NVIDIA GPUs with compute capability of at least 7.0. The policy will run on other GPUs and CPUs but may not improve performance. For TPUs, the mixed_bfloat16 policy should be used instead.

This slowdown is pretty much expected.

**Comment by DachuanZhao** [comment] 2020-12-07 10:25
> This slowdown is pretty much expected.
```it may not improve performance.```

In fact , it leads to worse performance ......

**Comment by byronyi** [comment] 2020-12-07 10:26
I don't think it is a bug. This feature is not meant to accelerate your model on regular CPUs.

**Comment by DachuanZhao** [comment] 2020-12-07 10:34
> I don't think it is a bug. This feature is not meant to accelerate your model on regular CPUs.

But at least it should't make the performance  worse ...... We often train a model with gpu and deploy it with cpu . In this situation, the bug has a big impact ......

**Comment by byronyi** [comment] 2020-12-07 10:36
> > I don't think it is a bug. This feature is not meant to accelerate your model on regular CPUs.
> 
> But at least it should't make the performance worse ...... We often train a model with gpu and deploy it with cpu . In this situation, the bug has a big impact ......

There is nothing prevent you to deploy a model trained in mixed precision with full precision. The model itself is always stored in full precision.

**Comment by DachuanZhao** [comment] 2020-12-07 10:48
> > > I don't think it is a bug. This feature is not meant to accelerate your model on regular CPUs.
> > 
> > 
> > But at least it should't make the performance worse ...... We often train a model with gpu and deploy it with cpu . In this situation, the bug has a big impact ......
> 
> There is nothing prevent you deploying a model trained in mixed precision with full precision. The model itself is always stored in full precision.

The strange thing is that when you deploy a model which is trained with mixed_precision on tf-serving-cpu , you will find the model is slower than the model trained without mixed_precision ......

**Comment by byronyi** [comment] 2020-12-07 11:03
I've clearly stated that mixed precision training has nothing to do with serving your model in full precision. Even in mixed precision training your model is saved in full precision.

**Comment by byronyi** [comment] 2020-12-07 11:04
> > > > I don't think it is a bug. This feature is not meant to accelerate your model on regular CPUs.
> > > 
> > > 
> > > But at least it should't make the performance worse ...... We often train a model with gpu and deploy it with cpu . In this situation, the bug has a big impact ......
> > 
> > 
> > There is nothing prevent you deploying a model trained in mixed precision with full precision. The model itself is always stored in full precision.
> 
> The strange thing is that when you deploy a model which is trained with mixed_precision on tf-serving-cpu , you will find the model is slower than the model trained without mixed_precision ......

If you actually meet a bug, which is unlikely IMHO, you could raise an issue on tensorflow/serving.

**Comment by DachuanZhao** [comment] 2020-12-07 11:09
> > > > > I don't think it is a bug. This feature is not meant to accelerate your model on regular CPUs.
> > > > 
> > > > 
> > > > But at least it should't make the performance worse ...... We often train a model with gpu and deploy it with cpu . In this situation, the bug has a big impact ......
> > > 
> > > 
> > > There is nothing prevent you deploying a model trained in mixed precision with full precision. The model itself is always stored in full precision.
> > 
> > 
> > The strange thing is that when you deploy a model which is trained with mixed_precision on tf-serving-cpu , you will find the model is slower than the model trained without mixed_precision ......
> 
> If you actually meet a bug, which is unlikely IMHO, you could raise an issue on tensorflow/serving.

Have you run the code in my colab ?  It's acceptable that training a model with mixed_precision on cpu is 60 times slower than training it without mixed_precision  ?

**Comment by yutaochen1998** [comment] 2020-12-07 12:24
> > > > > > I don't think it is a bug. This feature is not meant to accelerate your model on regular CPUs.
> > > > > 
> > > > > 
> > > > > But at least it should't make the performance worse ...... We often train a model with gpu and deploy it with cpu . In this situation, the bug has a big impact ......
> > > > 
> > > > 
> > > > There is nothing prevent you deploying a model trained in mixed precision with full precision. The model itself is always stored in full precision.
> > > 
> > > 
> > > The strange thing is that when you deploy a model which is trained with mixed_precision on tf-serving-cpu , you will find the model is slower than the model trained without mixed_precision ......
> > 
> > 
> > If you actually meet a bug, which is unlikely IMHO, you could raise an issue on tensorflow/serving.
> 
> Have you run the code in my colab ? It's acceptable that training a model with mixed_precision on cpu is 60 times slower than training it without mixed_precision ?

"The dtype policy mixed_float16 may run slowly because this machine does not have a GPU. Only Nvidia GPUs with compute capability of at least 7.0 run quickly with mixed_float16."
Mixed precision is not meant to accelerate training on CPU. It's expected to impact performance.

**Comment by byronyi** [comment] 2020-12-07 12:31
> > > > > > I don't think it is a bug. This feature is not meant to accelerate your model on regular CPUs.
> > > > > 
> > > > > 
> > > > > But at least it should't make the performance worse ...... We often train a model with gpu and deploy it with cpu . In this situation, the bug has a big impact ......
> > > > 
> > > > 
> > > > There is nothing prevent you deploying a model trained in mixed precision with full precision. The model itself is always stored in full precision.
> > > 
> > > 
> > > The strange thing is that when you deploy a model which is trained with mixed_precision on tf-serving-cpu , you will find the model is slower than the model trained without mixed_precision ......
> > 
> > 
> > If you actually meet a bug, which is unlikely IMHO, you could raise an issue on tensorflow/serving.
> 
> Have you run the code in my colab ? It's acceptable that training a model with mixed_precision on cpu is 60 times slower than training it without mixed_precision ?

float16 are accelerated by hardware, not software. Software enables such acceleration with supported hardware, while regular CPUs do not have fp16 capability. I am surprised it actually runs btw.

**Comment by Saduf2019** [comment] 2020-12-08 09:28
@byronyi 
is this still an issue.

**Comment by byronyi** [comment] 2020-12-08 14:21
> @byronyi
> is this still an issue.

I don't think so and this issue could be closed.

**Comment by Saduf2019** [comment] 2020-12-08 14:32
Moving this to closed status with confirmation.

**Closed by Saduf2019** 2020-12-08 14:32 UTC
Labels: TF 2.3, stat:awaiting response, type:bug

**Comment by DachuanZhao** [comment] 2020-12-09 03:22
> > @byronyi
> > is this still an issue.
> 
> I don't think so and this issue could be closed.

Why not ???
You say : "I am surprised it actually runs btw." , but you don't think it's a bug ???

**Comment by DachuanZhao** [comment] 2020-12-09 03:25
> Moving this to closed status with confirmation.

I suggest you run the code in my colab and you decide whether it's a bug or not by yourself ......

**Comment by DachuanZhao** [comment] 2020-12-09 03:31
> accelerate

So the conclusion is that "It's acceptable that training or predicting a model with mixed_precision on cpu is slower than without mixed_precision" ?

**Comment by byronyi** [comment] 2020-12-09 03:36
You should really consult your CPU vendor. There is nothing TF can fix this for you except for disabling mixed precision on unsupported hardware all together.

**Comment by byronyi** [comment] 2020-12-09 03:36
cc @reedwm

**Comment by DachuanZhao** [comment] 2020-12-09 03:46
> You should really consult your CPU vendor. There is nothing TF can do to fix this for you except for disabling mixed precision on unsupported hardware all together.

This problem can reproduce at google colab . You think it may be a common problem on different types of CPUs ? So TF can't fix it ?

**Comment by reedwm** [comment] 2020-12-09 20:44
As @byronyi has stated, CPUs do not have hardware support for float16 and so will be slower with mixed_float16. I'll clarify in the tutorial that mixed precision can actually significantly slow down a model on CPUs, instead of just not speeding it up. 

As for the TF serving issue: A float32 and a mixed_float16 `tf.train.Checkpoint` are identical for the same model, as checkpoints do not store the dtype of computations. On the other hand, a float32 and mixed_float16 SavedModel are different, as SavedModels store the graph of computations, which includes the dtype of computations. Using a mixed_float16 SavedModel with TF-Serving on a device that does not support mixed precision will be slow. As a workaround, checkpoints can be used instead, then when a SavedModel is required, the checkpoint can be loaded into a float32 model and a float32 SavedModel can be generated. I'll talk people working on SavedModel to work on a better solution.

**Comment by KichangKim** [comment] 2021-01-21 10:40
> As @byronyi has stated, CPUs do not have hardware support for float16 and so will be slower with mixed_float16. I'll clarify in the tutorial that mixed precision can actually significantly slow down a model on CPUs, instead of just not speeding it up.
> 
> As for the TF serving issue: A float32 and a mixed_float16 `tf.train.Checkpoint` are identical for the same model, as checkpoints do not store the dtype of computations. On the other hand, a float32 and mixed_float16 SavedModel are different, as SavedModels store the graph of computations, which includes the dtype of computations. Using a mixed_float16 SavedModel with TF-Serving on a device that does not support mixed precision will be slow. As a workaround, checkpoints can be used instead, then when a SavedModel is required, the checkpoint can be loaded into a float32 model and a float32 SavedModel can be generated. I'll talk people working on SavedModel to work on a better solution.

@reedwm 
Hi. Is there any progress on that issue? it will be very helpful when using mixed precision for only "training" time, and serve model on CPU devices.

**Comment by DachuanZhao** [comment] 2021-01-21 10:44
> As @byronyi has stated, CPUs do not have hardware support for float16 and so will be slower with mixed_float16. I'll clarify in the tutorial that mixed precision can actually significantly slow down a model on CPUs, instead of just not speeding it up.
> 
> As for the TF serving issue: A float32 and a mixed_float16 `tf.train.Checkpoint` are identical for the same model, as checkpoints do not store the dtype of computations. On the other hand, a float32 and mixed_float16 SavedModel are different, as SavedModels store the graph of computations, which includes the dtype of computations. Using a mixed_float16 SavedModel with TF-Serving on a device that does not support mixed precision will be slow. As a workaround, checkpoints can be used instead, then when a SavedModel is required, the checkpoint can be loaded into a float32 model and a float32 SavedModel can be generated. I'll talk people working on SavedModel to work on a better solution.

@reedwm @byronyi Thanks for all your explanation ~~~
