### ISSUE TITLE
Cifar-10 link inside Tensorflow webpage report 404

### ISSUE THREAD

**Issue by concerttttt** [tensorflow/tensorflow#9774] opened 2017-05-09 02:11 UTC
Not sure if this is the right place for an 404 error...

The link to CIFAR-10 source code on Tensorflow webpage reports 404 since yesterday afternoon (08/May/2017), kindly help to fix it.

This is the page found contains error:
[https://www.tensorflow.org/tutorials/deep_cnn](url)

This is the link found to reports 404:
[https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/image/cifar10/](url)

Thanks

**Comment by concretevitamin** [comment] 2017-05-09 23:20
@wolffg - could you please take a look?

**Comment by wolffg** [comment] 2017-05-11 15:45
This is a duplicate of #9637, and we will be fixing that as soon as we can.   Thanks for reporting!

**Closed by wolffg** 2017-05-11 15:45 UTC
