### ISSUE TITLE
Incorrect Cupti dll name on W10

### ISSUE THREAD

**Issue by peachthiefmedia** [tensorflow/tensorflow#44697] opened 2020-11-09 10:21 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 20H2
- TensorFlow installed from (source or binary): Binary (pip)
- TensorFlow version (use command below): 2.4.0-rc0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0 / 8
- GPU model and memory: Nvidia 2080Ti 11Gb

**Describe the current behavior**
On Windows it looks for the dll 'cupti64_110.dll' however Cuda Toolkit 11 and others now installs as 'cupti64_2020.1.0.dll' on W10.

**Describe the expected behavior**
Correctly identify the cupti dll name to work on W10 with the default Cuda Toolkit install.

**Standalone code to reproduce the issue**
Any training code with profiling or logging on W10.

**Other info / logs** 
Can be fixed by copying/renaming the dll to 'cupti64_110.dll' in the 'Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\extras\CUPTI\lib64' folder.

**Comment by Saduf2019** [comment] 2020-11-10 04:43
@peachthiefmedia 
Can you please paste the error log (using makrdown formatting around it) .

**Comment by peachthiefmedia** [comment] 2020-11-10 10:07
Apologies, I'd corrected it before I took logs. Here they are

```
2020-11-10 09:58:31.729040: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2020-11-10 09:58:31.729156: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2020-11-10 09:58:31.729246: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1365] Profiler found 1 GPUs
2020-11-10 09:58:31.749207: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cupti64_110.dll'; dlerror: cupti64_110.dll not found
2020-11-10 09:58:31.768347: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cupti.dll'; dlerror: cupti.dll not found
2020-11-10 09:58:31.768472: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1415] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-11-10 09:58:31.768581: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2020-11-10 09:58:31.768812: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1496] function cupti_interface_->Finalize()failed with error CUPTI could not be loaded or symbol could not be found.
```

It should say 

```
2020-11-10 08:30:03.445479: I tensorflow/core/profiler/lib/profiler_session.cc:136] Profiler session initializing.
2020-11-10 08:30:03.445562: I tensorflow/core/profiler/lib/profiler_session.cc:155] Profiler session started.
2020-11-10 08:30:03.445634: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1365] Profiler found 1 GPUs
2020-11-10 08:30:03.466975: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cupti64_110.dll
2020-11-10 08:30:03.562410: I tensorflow/core/profiler/lib/profiler_session.cc:172] Profiler session tear down.
2020-11-10 08:30:03.562604: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1487] CUPTI activity buffer flushed
```

**Comment by mihaimaruseac** [comment] 2020-11-16 16:40
@sanjoy can you take a look please?

**Comment by chsigg** [comment] 2020-11-18 08:28
Would you be OK with a local work-around?

Replace [this](https://github.com/tensorflow/tensorflow/blob/667244c2e450ed9491e8ad964a0db6b2945929dd/third_party/gpus/cuda_configure.bzl#L589) `_check_cuda_libs_params(...)` with `(cuda_config.config["cupti_library_dir"] + "/cupti64_2020.1.0.dll", True)`

We have plans to streamline cuda_configure.bzl, which would be a good time to take care of this as well.

**Comment by bhack** [comment] 2020-12-02 17:32
This is already a duplicate of https://github.com/tensorflow/tensorflow/issues/43030 then we have https://github.com/tensorflow/tensorflow/issues/44291.
I don't think that we could leave this open until TF 2.5.

**Comment by yutaochen1998** [comment] 2020-12-24 16:35
I simply made a copy of 'cupti64_2020.1.1.dll' and rename it to 'cupti64_110.dll', now everything works fine.

**Comment by sachinprasadhs** [comment] 2021-06-22 10:28
@peachthiefmedia , Does the above comment resolve your issue?

**Closed** 2021-07-10 01:47 UTC
Labels: TF 2.4, comp:gpu, stalled, stat:awaiting response, subtype:windows, type:build/install
