### ISSUE TITLE
TensorFlow 2.0 Alpha Tensorboard graph bug

### ISSUE THREAD

**Issue by plentypvp** [tensorflow/tensorflow#27577] opened 2019-04-06 18:04 UTC
**System information**
- Have I written custom code: No, I'm using MNIST Tensorboard example provided by Google.
- OS Platform and Distribution: Ubuntu 16.04
- Binary installation (sudo pip3 install tf-nightly-2.0-preview)
- TensorFlow version (use command below): 2.0.0-dev20190405
- Python version: 3.5.2
- CUDA/cuDNN version: 10.0
- GPU model and memory: NVIDIA GTX 1080 Ti 11GB

**Describe the current behavior**
My code is provided below.

Running this code gives a directory called logs. I launch Tensorboard using **tensorboard --logdir=./logs**
I go to localhost:6006, click the Graphs tab in my browser, and I get the message saying:
**Graph: Failed Normalizing names**
Tensorboard console doesn't show any errors.

I'm using the MNIST Tensorboard example provided here: https://www.tensorflow.org/tensorboard/r2/graphs
And it doesn't work in TensorFlow 2.0. Why?

**Describe the expected behavior**
I expect it to show the graph for the model.

**Code to reproduce the issue**
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from datetime import datetime
#from packaging import version

import tensorflow as tf
from tensorflow import keras

print("TensorFlow version: ", tf.__version__)

# Define the model.
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])
(train_images, train_labels), _ = keras.datasets.fashion_mnist.load_data()
train_images = train_images / 255.0

logdir="logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

# Train the model.
model.fit(
    train_images,
    train_labels, 
    batch_size=64,
    epochs=5, 
    callbacks=[tensorboard_callback])
```

Attached file is zipped logs directory to be viewed with Tensorboard.
[logs.zip](https://github.com/tensorflow/tensorflow/files/3050778/logs.zip)

**Comment by amanp592** [comment] 2019-04-06 21:00
@plentypvp hey! i used the same code and ran tensorboard i didn't faced any issue and got the graph as expected!!
Did you tried running it again and starting tensorboard again??

**Comment by plentypvp** [comment] 2019-04-06 21:25
Yes, I have tried doing it multiple times. I'm using TensorBoard 1.14.0a20190319. If you got the graph as expected, can you share your OS distro, Python version, TensorFlow version, TensorBoard version?

**Comment by amanp592** [comment] 2019-04-07 05:03
@plentypvp I ran your given code and for me the keras tag worked without any changing like you mentioned but yes the tag batch_2 stuck at `Parsing graph.pbtxt`

OS: Ubuntu 116.04
Tensorflow Version: Tensorflow 2.0 Alpha
Python 3.6

**Comment by plentypvp** [comment] 2019-04-07 08:51
"for me the keras tag worked without any changing like you mentioned". It worked without any changing for you probably because you have Python 3.6.

"but yes the tag batch_2 stuck at Parsing graph.pbtxt". And that's the bug that should be forwarded to Tensorflow team.

In conclusion, I get the following:
Ubuntu 16.04
Python 3.5.2

1. Tensorflow v2.0.0-dev20190405, TensorBoard 1.14.0a20190319:
The graph doesn't show up at all: Graph: Failed Normalizing names

2. Tensorflow v2.0.0-alpha0, TensorBoard 1.14.0a20190301:
The graph shows up. Keras (conceptual) graph shows up after a change mentioned above, but this is probably becuase of Python version. Batch_2 graph doesn't show up, getting stuck at "Parsing graph.pbtxt".

Let's wait until TensorFlow Team responds.

**Comment by amanp592** [comment] 2019-04-07 09:26
@wchargin  @nfelt  what would you say for this??

**Comment by wchargin** [comment] 2019-04-12 21:51
This may be a duplicate of tensorflow/tensorboard#2062, which should be
fixed in the latest version of `tb-nightly`. Could you please try
uninstalling TensorBoard and then running `pip install -U tb-nightly`
inside your virtualenv to see whether the issue persists?

**Comment by plentypvp** [comment] 2019-04-12 23:34
I don't use virtualenv. Ubuntu 16.04 (fresh installation), Python 3.5.2.
sudo pip3 install tensorflow-gpu==2.0.0-alpha0
sudo pip3 install -U tb-nightly

These commands resulted in having Tensorflow 2.0.0-alpha0 and TensorBoard 1.14.0a20190412 installed. After installation, I ran the same code as in the beginning. As expected, it created logs directory. In Tensorboard "Default" graph showed up as expected, "keras" and "batch_2" gave the same error (see the screenshots below).
![image](https://user-images.githubusercontent.com/49348066/56071046-21d36580-5da5-11e9-949a-229727e9a77d.png)
![image](https://user-images.githubusercontent.com/49348066/56071058-3f083400-5da5-11e9-8e2b-914722fd171b.png)

Tensorboard console log:
```
TensorBoard 1.14.0a20190412 at http://AI:6006 (Press CTRL+C to quit)
I0413 04:27:05.439245 140161711109888 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:05] "GET / HTTP/1.1" 200 -
I0413 04:27:05.726644 140161702717184 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:05] "GET /font-roboto/oMMgfZMQthOryQo9n22dcuvvDin1pK8aKteLpeZ5c0A.woff2 HTTP/1.1" 200 -
I0413 04:27:06.709269 140161702717184 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/environment HTTP/1.1" 200 -
I0413 04:27:06.709728 140161585235712 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/runs HTTP/1.1" 200 -
I0413 04:27:06.711792 140161576843008 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/experiments HTTP/1.1" 200 -
I0413 04:27:06.712903 140161711109888 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/plugins_listing HTTP/1.1" 200 -
I0413 04:27:06.919516 140161711109888 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /font-roboto/RxZJdnzeo3R5zSexge8UUZBw1xU1rKptJj_0jans920.woff2 HTTP/1.1" 200 -
I0413 04:27:06.920198 140161576843008 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/plugin/scalars/tags HTTP/1.1" 200 -
I0413 04:27:06.920916 140161702717184 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/environment HTTP/1.1" 200 -
I0413 04:27:06.924833 140161585235712 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/plugins_listing HTTP/1.1" 200 -
I0413 04:27:06.925154 140161358755584 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/runs HTTP/1.1" 200 -
I0413 04:27:06.925925 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /data/experiments HTTP/1.1" 200 -
I0413 04:27:06.951884 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:06] "GET /font-roboto/d-6IYplOFocCacKzxwXSOJBw1xU1rKptJj_0jans920.woff2 HTTP/1.1" 200 -
I0413 04:27:07.041337 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:07] "GET /data/plugin/scalars/scalars?tag=epoch_accuracy&run=logs%2Ffit%2F20190413-042625%2Ftrain&experiment= HTTP/1.1" 200 -
I0413 04:27:07.041760 140161358755584 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:07] "GET /data/plugin/scalars/scalars?tag=epoch_loss&run=logs%2Ffit%2F20190413-042625%2Ftrain&experiment= HTTP/1.1" 200 -
I0413 04:27:07.046586 140161358755584 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:07] "GET /data/plugin/scalars/tags HTTP/1.1" 200 -
I0413 04:27:07.224785 140161358755584 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:07] "GET /data/plugin/scalars/scalars?tag=epoch_loss&run=logs%2Ffit%2F20190413-042625%2Ftrain&experiment= HTTP/1.1" 200 -
I0413 04:27:07.225165 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:07] "GET /data/plugin/scalars/scalars?tag=epoch_accuracy&run=logs%2Ffit%2F20190413-042625%2Ftrain&experiment= HTTP/1.1" 200 -
I0413 04:27:08.560219 140161358755584 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:08] "GET /data/plugin/graphs/info HTTP/1.1" 200 -
I0413 04:27:08.561780 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:08] "GET /data/plugins_listing HTTP/1.1" 200 -
I0413 04:27:08.705659 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:08] "GET /data/plugin/graphs/graph?run=logs%2Ffit%2F20190413-042625%2Ftrain&conceptual=false HTTP/1.1" 200 -
I0413 04:27:09.080152 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:09] "GET /data/plugins_listing HTTP/1.1" 200 -
I0413 04:27:12.141783 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:27:12] "GET /data/plugin/graphs/graph?run=logs%2Ffit%2F20190413-042625%2Ftrain&conceptual=false&tag=batch_2 HTTP/1.1" 200 -
I0413 04:30:51.835412 140161333577472 _internal.py:122] ::ffff:127.0.0.1 - - [13/Apr/2019 04:30:51] "GET /data/plugin/graphs/graph?run=logs%2Ffit%2F20190413-042625%2Ftrain&conceptual=true&tag=keras HTTP/1.1" 500 -
E0413 04:30:51.837328 140161333577472 _internal.py:122] Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 302, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 290, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/backend/application.py", line 309, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wrappers/base_request.py", line 235, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/plugins/graph/graphs_plugin.py", line 218, in graph_route
    result = self.graph_impl(run, tag, is_conceptual, limit_attr_size, large_attrs_key)
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/plugins/graph/graphs_plugin.py", line 151, in graph_impl
    keras_model_config = json.loads(tensor_events[0].tensor_proto.string_val[0])
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```
I also attached generated logs directory as zip.
[logs.zip](https://github.com/tensorflow/tensorflow/files/3075465/logs.zip)

**Comment by hgadig** [comment] 2019-04-15 19:22
@nfelt  @wchargin Can this be migrated to tensorboard repo?

**Comment by tensorflowbutler** [comment] 2019-05-02 13:04
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-05-17 13:24
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-06-01 12:49
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by plentypvp** [comment] 2019-06-01 17:03
No

**Closed** 2019-06-01 19:38 UTC
Labels: 2.0.0-alpha0, comp:tensorboard, stat:awaiting response, type:bug/performance
