### ISSUE TITLE
C++ compilation of rule '//tensorflow/core/kernels:gather_nd_op' failed

### ISSUE THREAD

**Issue by FlorinAndrei** [tensorflow/tensorflow#4214] opened 2016-09-05 22:56 UTC
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

none

### Environment info
Operating System:

Ubuntu 16.04 64bit

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
# ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   560184 Sep  5 22:07 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep  5 22:07 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep  5 22:07 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Sep  5 22:07 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Sep  5 22:07 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Sep  5 22:08 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Sep  5 22:08 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 79337624 Sep  5 22:08 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Sep  5 22:08 /usr/local/cuda/lib64/libcudnn_static.a
```

I've downloaded these from Nvidia and installed them per "official" instructions:

- cuda_8.0.27_linux.run
- cuda_8.0.27.1_linux.run
- cudnn-8.0-linux-x64-v5.1.tgz

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)

```
# git rev-parse HEAD
2ab7e6326296987ea0ce975afb3434a16d1aa21a
```

2. The output of `bazel version`

```
# bazel version
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0
```

```
# dpkg -l | grep bazel | awk '{print $3}'
0.3.1
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
./configure

# Hit ENTER on every question except:
# Do you wish to build TensorFlow with GPU support? (answer: y)
# Please specify a list of comma-separated Cuda compute capabilities you want to build with. (answer: 6.1)
# Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: (answer 8.0)
```

### What other attempted solutions have you tried?

Tried to google around, hoping it's a known issue. Could not find anything related.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

Gist with last messages during compilation:

https://gist.github.com/FlorinAndrei/23ada4fb714776e68c2693502c615305

**Comment by davidzchen** [comment] 2016-09-06 06:27
This appears to be caused by an internal compiler error:

```
ERROR: /vagrant/packages/tensorflow/tensorflow/core/kernels/BUILD:371:1: C++ compilation of rule '//tensorflow/core/kernels:gather_nd_op' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 119 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 431.231s, Critical Path: 406.66s
```

**Comment by tatatodd** [comment] 2016-09-07 05:21
Thanks for reporting this bug @FlorinAndrei!  I'm closing this out as a duplicate of #2559 that you've already mentioned; support for cuda 8.0 is the main issue.

**Closed by tatatodd** 2016-09-07 05:21 UTC
Labels: duplicate
