### ISSUE TITLE
Feature request: Ability to specify some GPUs and ignore all others

### ISSUE THREAD

**Issue by rdipietro** [tensorflow/tensorflow#1888] opened 2016-04-12 18:26 UTC
Right now, to specify a particular GPU, I do something like this:

```
gpu = 0
available_devices = os.environ['CUDA_VISIBLE_DEVICES'].split(',')
os.environ['CUDA_VISIBLE_DEVICES'] = available_devices[gpu]
```

after which TensorFlow will only allocate resources on the first GPU device. It would be nice to include a native way to do this.

Side note: There isn't much documentation (any?) on `device_count`, so I'm not sure if it's meant to handle this. Either way, I have experimented with the `device_count`, but with no luck: if I use `device_count = {'GPU': 1}`, TensorFlow still allocates memory on all available GPUs.

**Comment by gibiansky** [comment] 2016-08-23 07:22
I would like to implement this, as it's important for some things besides just convenience; for example, you cannot use `CUDA_VISIBLE_DEVICES` with CUDA IPC, so Tensorflow cannot be used with anything that needs access to the GPU memory in other processes (without copying it to CPU first). 

Is there a particular API that would make sense for this?

Some options:

1. Another environment variable, besides `CUDA_VISIBLE_DEVICES`, which tells Tensorflow which GPUs to use. For example, `TENSORFLOW_CUDA_DEVICES`, which *must* be a subset of `CUDA_VISIBLE_DEVICES` (if `CUDA_VISIBLE_DEVICES` is specified).
2. Modify the `GPUOptions` proto with a `repeated` field along the lines of `gpu_id`, which select which of the `CUDA_VISIBLE_DEVICES` to use. This seems cleaner, but I'm not sure how invasive that change would be (when does Tensorflow allocate GPU memory, call `cuGetDevice`, and otherwise initialize the StreamExecutor? Is it upon `tf.Session()`? Or is it earlier? If it's earlier, this change may be tricky to implement.)

Finally, if I were to implement option (2) or (1), what would I need to do in order to get the contribution accepted to Tensorflow?

**Comment by gibiansky** [comment] 2016-08-24 23:30
@zffchen78 If I were to implement this, what strategy would be most likely to get accepted as a patch to tensorflow?

The least invasive strategy is one which uses an environment variable, because GPUs are allocated  statically; In `gpu_init.cc` `InitModule()` is called, which eventually calls `ExecutorForDevice`, which allocates the GPUs. The GPUs aren't stored in the `Session`, and are not freed after a session ends; the `CUDAPlatform` is also stored statically and initialized on load. Effectively the architecture was not designed to allow the choice of GPUs to happen dynamically at runtime, but since environment variables are also global and exist at startup, this would be straightforward to implement.

An alternative route would be to fix the main design issue: Have a `Session` track which GPUs its using, and, when it's done, deallocate the GPUs and destroy the `StreamExecutor` contexts. To do this we would probably have to move the `Platform` from a global static variable into a `Session`-local one, and have it be initialized on session startup rather than global startup.

Please, let me know which of these is most likely to be accepted by the Tensorflow team if this is implemented and tested. If this is not a viable modification, please remove the "contributions welcome" tag.

**Comment by vrv** [comment] 2016-08-25 02:10
@gibiansky, independently for another reason I essentially implemented option 2 in your first post earlier this week.  I haven't submitted it yet, but maybe it might work for you.  Concretely, what I did was:
 
GPUOptions has a field called 'visible_gpu_devices', which is a comma-separated string.  It maps from "visible" devices to "logical" devices.  As an example, let's say the TensorFlow process has 8 GPUs visible to it.  One could pass visible_gpu_devices="5,3", and it would map visible device 5 as "/gpu:0" and visible device 3 as "/gpu:1", and it would leave all other devices untouched / uninitialized.

So it's basically like CUDA_VISIBLE_DEVICES, except CUDA_VISIBLE_DEVICES acts prior to the process starting, and controls what I would call 'physical GPUs' (e.g., what the driver reports) to "visible GPUs", which is the order that the process sees it, and this new option would allow one to remap from "visible" to "logical", with the default empty string meaning that the "visible" to "logical" map is one to one.

Let me know if you think this satisfies this feature request and I can try to send it for review.

**Comment by vrv** [comment] 2016-08-25 02:11
@rdipietro in addition, I believe now the device_count approach should maybe work for your case, since we now only allocate memory lazily on first memory allocation on GPU, so if you never ran an op on GPUs, it shouldn't allocate any memory on it either.

**Comment by gibiansky** [comment] 2016-08-25 02:19
@vrv Yes! This would be perfect! (In fact, I started implementing *literally* the same thing today, in the same manner.)

Minor questions:
- Shouldn't that be part of ConfigProto not GPUOptions? (GPUOptions seems like it is settings that affect a single GPU, while ConfigProto has settings related to many GPUs, for example device_count)
- Why pass `visible_gpu_devices` as a string, rather than as a `repeated int`?
- To confirm: this interacts fluidly with `CUDA_VISIBLE_DEVICES`. For example, if, on an 8-GPU system, `CUDA_VISIBLE_DEVICES=5,2,0,6`, and you set `visible_gpu_devices=0,3`, Tensorflow will end up running on GPUs 5 and 6.
- Does this change also mean that, since the GPU info is stored in the `Session`, `Session.close()` can now actually deallocate the GPU and destroy the context? If that's the case that would be *awesome*. (If you look right now, `nvidia-smi` will show that even after `Session.close()`, the GPU contexts still exist and thus you cannot launch more processes that use them.)

**Comment by vrv** [comment] 2016-08-25 02:27
* Yeah, we can put it in something other than GPUOptions (I'm loathe to put it top level, I'd rather scope it appropriately).

* Because that's how CUDA_VISIBLE_DEVICES works, and I kind of wanted it to be 'familiar' to people :).  I could make it repeated too.

* Yes, exactly.

* Unfortunately I think some part of the GPU initialization is still global (held by process_state), so destroying the session would not release it.  However, if you never used it, it shouldn't establish any context.  It would be nice to have it release on session close, but it will require some work to properly refcount the currently global state.  Heck, if you wanted to work on that instead, that would be nice.

**Comment by gibiansky** [comment] 2016-08-25 02:29
Great, SGTM. No strong opinions here wrt GPUOptions vs other locations; if it's in GPUOptions it may make sense to change the comment in the ConfigProto GPUOptions field to reflect that GPUOptions are not only per-GPU settings.

Thanks! Please ping me / close this issue when this is merged. It will be very helpful for the work I am doing right now.

**Comment by vrv** [comment] 2016-08-25 02:32
(I just checked, the comment on GPUOptions in ConfigProto explicitly mentions 'options that applies to all GPUs -- maybe we'll add a repeated PerGPUOptions field in the future...)

**Comment by gibiansky** [comment] 2016-08-25 02:33
Perfect, I just misinterpreted it then when I read it, for some reason I assumed that meant it was "single-GPU options that are applied to every single GPU uniformly". You're right though that my interpretation doesn't make sense given the comment. Oops, sorry!

**Comment by vrv** [comment] 2016-08-25 02:40
Well, some of those options could apply individually with different settings for each GPU, so your interpretation is also reasonable -- we just haven't implemented it that way (yet).

**Comment by gibiansky** [comment] 2016-08-25 22:24
@vrv BTW: By implementing a very hacky version of this patch, I have confirmed that with this fix will allow you to use Tensorflow with CUDA IPC. (My hacky version just edited cuda_platform.cc to always select just one GPU based on an environment variable, and to return 1 for VisibleDeviceCount()). So definitely looking forward to this patch landing in Tensorflow master – do you know a rough ETA for this? Thank you!!

**Comment by vrv** [comment] 2016-08-25 22:30
It'll probably in master tonight or tomorrow

**Comment by gibiansky** [comment] 2016-08-26 20:35
@rmlarsen @vrv This change got rolled back automatically; please re-open this issue!

**Comment by vrv** [comment] 2016-08-26 20:36
It got rolled forward again with a fix.

**Comment by gibiansky** [comment] 2016-08-26 20:37
In which commit was it rolled forward? I just cloned master and do not see the change.

**Comment by vrv** [comment] 2016-08-26 20:38
Oh, it hasn't been pushed to master yet (so, on the next push).  Sorry about the wait...

**Comment by gibiansky** [comment] 2016-08-26 20:39
Ah, got it. How do pushes to master work? Do you do one every few hours?

**Comment by vrv** [comment] 2016-08-26 20:44
It's a manual process, usually once a day.  Until then, you could sync at the commit that closed this feature (the bug was related to when you run on a machine that doesn't have GPUs, but you compiled with GPU support).

**Comment by gibiansky** [comment] 2016-08-27 00:07
I just tested this patch. It does not work. Please re-open this bug!

You can verify as follows:
```python
import tensorflow as tf
config = tf.ConfigProto(tf.GPUOptions(visible_device_list="0"))
session = tf.Session(config=config)

import subprocess
subprocess.check_call("nvidia-smi")
```

The output you will see will look like this on a 2-GPU system:

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     19236    C   /mnt/home/gibiansky/env/bin/python           10893MiB |
|    1     19236    C   /mnt/home/gibiansky/env/bin/python              73MiB |
+-----------------------------------------------------------------------------+
```

Specifically, note how there are *two* contexts opened, not just one! That means that no other process can access _either_ GPU.

The reason this is happening is because `platform->ExecutorForDevice(device)` is being called in more places than what you have addressed. For example, take a look at these pieces of code, that are called upon session startup:

- [platform.cc:96](https://github.com/tensorflow/tensorflow/blob/d42facc3cc9611f0c9722c81551a7404a0bd3f6b/tensorflow/stream_executor/platform.cc#L96)
- [platform.cc:113](https://github.com/tensorflow/tensorflow/blob/d42facc3cc9611f0c9722c81551a7404a0bd3f6b/tensorflow/stream_executor/platform.cc#L113)
- [gpu_init.cc:38](https://github.com/tensorflow/tensorflow/blob/d42facc3cc9611f0c9722c81551a7404a0bd3f6b/tensorflow/core/common_runtime/gpu/gpu_init.cc#L33)

I believe there are others as well; you can get a complete list with `grep -iIr "->ExecutorForDevice" /path/to/tensorflow/directory`.

I believe the trickiest bit is in `gpu_init.cc`. Specifically, if you look at `gpu_init.cc:161`, you see that the first time `GPUMachineManager()` is called (which happens upon Session creation), it calls `InitModule()`. `InitModule` in turn calls `InitGPU()`, which has the devilish line of code:
```c++
int dev_count = platform->VisibleDeviceCount();
...
for (int i = 0; i < dev_count; ++i) {
  auto executor = platform->ExecutorForDevice(i);
  ...
}
```
What this means is that the first time anything related to GPUs happens (and thus a GPU machine manager is created), you find out the number of visible devices and initialize every single one of them, _no matter what_. I emphasize the "no matter what" because GPUMachineManager() takes no parameters, and neither does `InitModule`. Because all of this is static global state there is nothing you can do per-session that fixes this.

My approach was a bit different, and IMHO uglier but less fragile:

- Inside `CUDAPlatform`, check for a `TENSORFLOW_VISIBLE_DEVICES` environment variable, which was exactly the same in meaning as your `visible_device_list` configuration option.
- If that environment variable exists, then instead of returning `CUDADriver::DeviceCount()` from `VisibleDeviceCount()`, return `visible_device_list.size()`, where `visible_device_list` is the variable holding the parsed contents of `TENSORFLOW_VISIBLE_DEVICES`.
- Whenever you call `ExecutorForDevice` (or any variant thereof), remap the provided ordinal as directed by `visible_device_list`. That way, you *know* that Tensorflow cannot accidentally claim more GPUs than it is allowed to, because `CUDAPlatform` is the only available interface to GPUs, and it does not allow any caller to touch GPUs that it should not be seeing.

What do you think? Is that a viable strategy? The current patch does not solve this problem at all (whereas the approach described above is uglier but fixes the issue). There _is_ an alternative which would be refactoring `CUDAPlatform` to be a part of the session state instead of the global device, and then having things like `GPUMachineManager` take and store a `CUDAPlatform`. This might be a pretty invasive change though and I'm not sure how many other pieces of global state would have to be pulled into local state in order to get this to work.

**Comment by vrv** [comment] 2016-08-27 00:11
Ah, I didn't realize the StreamExecutor was establishing contexts too.  We don't maintain StreamExecutor ourselves, so I'll have to talk with the owners to figure out how to get this working as intended.

**Comment by gibiansky** [comment] 2016-08-27 00:16
Thank you! Yes, sadly if you look at the code behind `ExecutorForDevice`, it eventually calls [`GetUncachedExecutor`](https://github.com/tensorflow/tensorflow/blob/d42facc3cc9611f0c9722c81551a7404a0bd3f6b/tensorflow/stream_executor/cuda/cuda_platform.cc#L149); this creates a new `CUDAExecutor` and calls `Init`; in turn, that calls `CUDADriver::GetDevice`, which then calls `cuDeviceGet`, which is the low-level call that I believe actually creates the context.

It seems like in this case StreamExecutor is doing everything right – when you call `ExecutorForDevice`, it *should* allocate a context and prepare for running things on the device, since you're about to run things on the device! (That's what executors do, presumably.) However, the mistake is in Tensorflow core -- Tensorflow shouldn't be asking for the stream executors in the first place.

**Comment by gibiansky** [comment] 2016-08-27 00:16
FYI, if the environment variable-based approach I described above is acceptable, I am happy to make a patch and submit it as a PR.

**Comment by vrv** [comment] 2016-08-27 00:22
So we can't put TF specific code in stream executor because StreamExecutor is being opensourced separately from TensorFlow, so whatever solution we choose has to work more generally.  If they are happy with the environment variable approach, we could add it.

StreamExecutor was never really designed to co-exist well with other processes, unfortunately.

**Comment by gibiansky** [comment] 2016-08-27 00:40
Ah, I understand. You are correct -- `cuda_platform.cc` is part of StreamExecutor, not Tensorflow.

I cannot think of a way of doing this without modifying StreamExecutor or duplicating part of its functionality. At the very least `GetPeerAccessMap` and `EnablePeerAccess` are broken in their current implementations.

Thank you for continuing to push on this; this is really important for being able to scale Tensorflow. Please let me know what I can do to help this along -- if you or other members of the team are busy and so it will take a while to get this going, but you think this is a patch that an external contributor will be able to push through, please let me know what I can do. I understand that this may be tricky and that it may require an internal contributor, though.

**Comment by vrv** [comment] 2016-08-27 04:22
I played around with some approaches only touching code in gpu_init.cc and gpu_device.cc and got it so that it didn't establish a context on a device that wasn't in gpu_device_list.  The only implication is that once established, I don't think we could de-establish it.  That is, if you started with gpu_device_list="0,1" but then closed that session and reopened it with "1", I'm pretty sure 0 would still have the context established.

But I think we could do it so that if you did "0", it would only establish on 0, and in the same process, you could probably then add "0,1" in another session and it might still work.  Would that satisfy your requirements?

**Comment by gibiansky** [comment] 2016-08-27 08:54
Ultimately yes if it's possible to start a Tensorflow session without defining CUDA_VISIBLE_DEVICES and use `nvidia-smi` to verify that only a single context is active... then I am happy :) 

Obviously this isn't the best in the long-term but for the short term (and for my requirements) it's definitely enough!

**Comment by gibiansky** [comment] 2016-08-30 01:11
Any progress on an updated patch? :)

**Comment by vrv** [comment] 2016-08-31 03:35
Yeah, I just submitted it, should be pushed by tomorrow some time.

**Comment by gibiansky** [comment] 2016-08-31 16:39
Awesome, thanks @vrv! I'll test this out today but it looks very promising.

**Comment by gibiansky** [comment] 2016-09-02 19:20
Just tested this out today.

It's closer than the previous one... but still not quite there -- reopen the issue again? The bug here is insidious and somewhat unexpected:

:(

It comes from the following line: [gpu/process_state.cc:188](https://github.com/tensorflow/tensorflow/blob/d42facc3cc9611f0c9722c81551a7404a0bd3f6b/tensorflow/core/common_runtime/gpu/process_state.cc#L188)

If you take a look at that, you see that when you allocate memory on the host that is known to CUDA, you always use `ExecutorForDevice(0)`, even though `0` may not be in your `visible_device_list`. 

You can test this with:

```python
import time
import tensorflow as tf

c = tf.ConfigProto()
c.gpu_options.visible_device_list="1"

s = tf.Session(config=c)
s.run(tf.constant(10))
time.sleep(5)
```

And then if you look at `nvidia-smi` you will see two contexts, one on 0 and one on 1, even though only one was requested. (The difference between this test and the previous one is that you use a `s.run`)

I'm not sure this is fixable without changing stream executor, but the patch isn't super helpful in its current state :(

**Comment by vrv** [comment] 2016-09-02 19:50
Ha, fun times.  I think it is fixable without too much work:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/gpu/process_state.cc#L99

gpu_allocators_ is a sparse array indexed by visible gpu id.  So instead of using '0', we need to find any non-null entry in gpu_allocators_ and use the index of that executor.  I believe we are guaranteed that the gpu_allocators_ are allocated prior to the first call to GetCudaHostAllocator.

If you want to give that a try, let me know, otherwise I will try to find time to get to it.

**Comment by gibiansky** [comment] 2016-09-02 19:51
SGTM, I'll give it a shot.

**Comment by gibiansky** [comment] 2016-09-02 21:05
PR opened, I've confirmed that with that change `nvidia-smi` gives the desired output. I don't know whether there is any code style that I should be observing but am not, so just let me know what needs to be done to get this merged (whether by merging my almost-trivial PR or something else).

**Closed** 2016-09-06 18:19 UTC

**Comment by cbquillen** [comment] 2017-01-18 16:40
I am seeing a problem with this implementation on some machines, where the device ordering used by nvidia-smi (and the NVML library) doesn't match the ordering in cuDeviceGet().  On those machines you end up having to specify a different number than the obvious one that you might see via nvidia-smi or via the python pynvml library.  Please see my comment in #152.

**Comment by RexYing** [comment] 2017-07-22 00:14
I could use config.gpu_options.visible_device_list in python, and it works.
But when I try to set the visible device list in c++ using the protobuf methods (eg. set_visible_device_list), it not only changes the visible_device_list field, but also the allocator_type field), and I got the error "Invalid allocator type: 0,1,2,3".

It seems that the two fields got mapped into the same string address. Anyone knows what might be going on?

**Comment by bravelywangexocr** [comment] 2017-11-24 06:41
@RexYing,  meet the same invalid allocator type issue, have you figured out the solution? thanks.

**Comment by kitterive** [comment] 2018-01-16 09:28
I met the same issue, any solutions? thanks.

**Comment by mattdingmeng** [comment] 2018-01-25 01:23
I have the same issue. When I use C++ api 'set_visible_device_list("0")', the program crash and said 'E tensorflow/core/common_runtime/gpu/process_state.cc:130] Invalid allocator type: 0
Segmentation fault (core dumped)'

I think it's a bug. @kitterive @bravelywangexocr @RexYing

**Comment by ChengshuLi** [comment] 2018-02-28 22:33
@kitterive @bravelywangexocr @RexYing @mattdingmeng 

Just want to create more context, I tried to debug a little bit and I found that when I called set_visible_device_list("1,2"), it also set "allocator_type" to "1,2", which is an invalid value for allocator_type. That's why the error message is "Invalid allocator type: 1,2". 

In other words, allocator_type and visible_device seem to share the same memory location.
https://github.com/tensorflow/tensorflow/blob/3378865c5509dfb6d18e6f95f28757437f67d3da/tensorflow/core/protobuf/config.proto

Please see the code snippet below as an example

```
auto options = tensorflow::SessionOptions();
const auto& static_gpu_options = options.config.gpu_options();
auto mutable_gpu_options = options.config.mutable_gpu_options();

std::cout << static_gpu_options.visible_device_list() << std::endl;     // print ""
std::cout << static_gpu_options.allocator_type() << std::endl;          // print ""

mutable_gpu_options->set_visible_device_list("1");

std::cout << static_gpu_options.visible_device_list() << std::endl;     // print "1"
std::cout << static_gpu_options.allocator_type() << std::endl;          // print "1"

mutable_gpu_options->set_allocator_type("");

std::cout << static_gpu_options.visible_device_list() << std::endl;     // print ""
std::cout << static_gpu_options.allocator_type() << std::endl;          // print ""
```

**Comment by Kejie-Wang** [comment] 2018-03-15 03:10
@ChengshuLi 
The same issue when I use c++ API and my tensorflow version is 1.5.0. I also find that it works if I compile the source codes without `--config=monolithic` option and use `libtensorflow_cc` and `libtensorflow_framework` as a dynamic library linked into my project. Theis problem only arises when I compile with `--config=monolithic` option to get a single dynamic library `libtensorflow_cc`.
