### ISSUE TITLE
[TF2.0] can't restore path with brackets

### ISSUE THREAD

**Issue by morgangiraud** [tensorflow/tensorflow#32614] opened 2019-09-18 09:30 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
- TensorFlow installed from (source or binary): `pip install tensorflow==2.0.0-rc1`
- TensorFlow version (use command below): v2.0.0-rc0-101-gd2d2566eef 2.0.0-rc1
- Python version: 3.6.8
- CUDA/cuDNN version: `None`
- GPU model and memory: `None`

**Describe the current behavior**
I can't restore a model stored ina directory containing a bracket

**Describe the expected behavior**
I can restore a model stored ina directory containing a bracket

**Code to reproduce the issue**
```python
import os
import shutil
import tensorflow as tf

current_dir = os.path.realpath(os.path.dirname(__file__))
save_dir = os.path.join(current_dir, 'testhop')
save_dir_wbracket = os.path.join(current_dir, 'test[hop')


if os.path.isdir(save_dir):
    shutil.rmtree(save_dir)
os.mkdir(save_dir)
assert os.path.isdir(save_dir)

if os.path.isdir(save_dir_wbracket):
    shutil.rmtree(save_dir_wbracket)
os.mkdir(save_dir_wbracket)
assert os.path.isdir(save_dir_wbracket)

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(
        16, batch_input_shape=[256, 1], activation='relu'),
    tf.keras.layers.Dense(16, activation='tanh'),
    tf.keras.layers.Dense(1),
])

lr = tf.Variable(1.)
reg_param = tf.Variable(1.)
optim = tf.keras.optimizers.SGD(lr)

ckpt = tf.train.Checkpoint(
    model=model,
    lr=lr,
    reg_param=reg_param,
)

manager = tf.train.CheckpointManager(ckpt, save_dir, max_to_keep=1)
manager_wbracket = tf.train.CheckpointManager(ckpt, save_dir_wbracket, max_to_keep=1)

manager.save()
assert os.path.isfile(os.path.join(save_dir, 'checkpoint'))
manager_wbracket.save()
assert os.path.isfile(os.path.join(save_dir_wbracket, 'checkpoint'))

# Works
print(manager.latest_checkpoint)
ckpt.restore(manager.latest_checkpoint)

# Does not work
print(manager_wbracket.latest_checkpoint)
ckpt.restore(manager_wbracket.latest_checkpoint)
```

**Other info / logs**
Note: Saving is working

Outputs:
```
/Users/morgangiraud/Sites/git/ray/python/ray/tune/examples/pbt/PBTTrain/testhop/ckpt-1
/Users/morgangiraud/Sites/git/ray/python/ray/tune/examples/pbt/PBTTrain/test[hop/ckpt-2
Traceback (most recent call last):
  File "debug.py", line 51, in <module>
    ckpt.restore(manager_wbracket.latest_checkpoint)
  File "/Users/morgangiraud/miniconda3/envs/ray/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 1971, in restore
    status = self._saver.restore(save_path=save_path)
  File "/Users/morgangiraud/miniconda3/envs/ray/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/util.py", line 1228, in restore
    reader = pywrap_tensorflow.NewCheckpointReader(save_path)
  File "/Users/morgangiraud/miniconda3/envs/ray/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 873, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
  File "/Users/morgangiraud/miniconda3/envs/ray/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 885, in __init__
    this = _pywrap_tensorflow_internal.new_CheckpointReader(filename)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files
```

**Comment by gowthamkpr** [comment] 2019-09-18 23:20
@morgangiraud Tried to reproduce your issue but was not able to reproduce it. Please find my github gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/ee11f049cc9ecf3855959d0d9df5f970/untitled146.ipynb).

**Comment by morgangiraud** [comment] 2019-09-19 07:19
First time that I have different behaviours on my mac and in collab but I'm even more puzzled now.
I've tested again just in case but it keeps failing on my mac book.

It also works with `test]hop` and  `test{hop`. 

Is there anyone who could try to run the script on a macbook to see if it is reproducible?

**Comment by gowthamkpr** [comment] 2019-09-19 21:21
@morgangiraud You can take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/6082) and it should help you resolve your problem.

**Comment by morgangiraud** [comment] 2019-09-20 06:39
Thanks, so it looks, like for some reason, I should just avoid the "[" character in my model's paths.

@ppwwyyxx, why you had the insight of removing the "[" character?

**Comment by gowthamkpr** [comment] 2019-09-20 21:44
@morgangiraud Glad that it worked. Can i close this issue?

**Comment by morgangiraud** [comment] 2019-09-21 08:09
Well, it depends on your policy I guess. 
The problem is not only mine (based on the issue you linked) and is not solved (since I can reproduce it) but it is not happening on all platform so I don't know if this is the kind of bug the TF team is going after.

**Comment by gowthamkpr** [comment] 2019-09-23 17:40
@morgangiraud Will look into it in future. Closing this issue as of now as it has been resolved.

**Closed by gowthamkpr** 2019-09-23 17:40 UTC
Labels: TF 2.0, comp:keras, type:support
