### ISSUE TITLE
TF2.9 perf is slower

### ISSUE THREAD

**Issue by dengpanyin** [tensorflow/tensorflow#58791] opened 2022-12-05 23:42 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

tf2.9

### Custom Code

No

### GPU model and memory

A100 

### Current Behaviour?

```shell
We migrate from tf2.4 to tf2.9, and observed that the training speed of some models has ~20% decrease. 

On tf2.4, it takes ~30mins after starting the job, before processing the 1st batch. Training speed increase and then become stable.
On tf2.9, it takes ~5mins after starting the job, before processing the 1st batch. Training speed does not increase.

Q1: Can we use tf2.4 to train the model and use tf2.9 for inferencing? Any potential issues?
Q2: How can we find the root cause of tf2.9 training slowness?
```

### Standalone code to reproduce the issue

```shell
Can't share the source code.
```

### Relevant log output

_No response_</details>

**Comment by cybergeekgyan** [comment] 2022-12-05 23:59
I would like to work on this issue and get it done for which I would be needing your help with the code. Can you assign this to me

**Comment by dengpanyin** [comment] 2022-12-06 00:04
@cybergeekgyan Thanks for the response. Can you assign this to yourself? I don't have edit privilege on the assignees section.

**Comment by cybergeekgyan** [comment] 2022-12-06 00:07
@dengpanyin How can I assign this issue to myself as I also don't have the privileges on the assignee task.
@tiruk007 please look into the matter

**Comment by mohantym** [comment] 2022-12-06 02:57
Hi @dengpanyin !
Could you share the sample code to reproduce this issue.  
Thank you!

**Comment by dengpanyin** [comment] 2022-12-06 19:14
@mohantym  Sorry, unable to share the code publicly due to company policy.  Can we schedule a live debugging session if that help?

**Comment by mohantym** [comment] 2022-12-07 00:41
@dengpanyin !

We should not write the model in 2.4 and use in 2.9 because the commands will be bit different and will contain depreciated api when migrating from 2.4 to 2.9 or higher.

You can use 'git diff'  to see difference  2.4 and 2.9  aside checking at[ release notes ](https://github.com/tensorflow/tensorflow/releases)of 2.9 and 2.4 which would have mentioned the  bug fixes and feature addition.

Getting 5 mins warm up time in 2.9 sounds awesome compared to 30 mins warm up time (2.4) . Curious on Training speed   w.r.to both version. 

I will investigate with Keras example notebooks  and post you on this 
Any toy models or  example notebook from tensorflow.org to replicate this issue would be appreciated.

Thank you!

**Comment by mohantym** [comment] 2022-12-08 07:20
@dengpanyin !
Thanks for the clarification. You can post same on TF Forum too.

@SuryanarayanaY !
Could you look at this issue.

Thank you!

**Comment by SuryanarayanaY** [comment] 2022-12-08 16:06
Hi @dengpanyin ,

Could you provide minimal code snippet that you are using?Also you are missing details like OS, Bazel versions(If built from source),CUDA versions etc that might be required for analysis.Could you please share those?Without that it is difficult to address your issue.
Could you also share the epoch wise training time for 2.4 and 2.9 versions.

Thankyou!

**Comment by SuryanarayanaY** [comment] 2022-12-13 10:31
Hi @dengpanyin ,

For better performance with newer TF versions Recommended way of passing data for training is `tf.data.Dataset` API. Please refer the attached API [Documentation](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly) and try to convert your data into `tf.data.Dataset` using the suitable methods and let us know the results.

Thankyou!

**Comment by dengpanyin** [comment] 2022-12-14 23:59
We are already use tf.data.dataset APIs both tf2.4 & tf2.9

**Comment by SuryanarayanaY** [comment] 2022-12-21 06:25
Hi @dengpanyin ,

Could you please provide some Toy code to replicate the issue.Since `tf.data.Dataset` optimized for performance and if it is not working as mentioned by you we should check the code and replicate the issue to find out the reason.Please provide minimal code snippet for same.

Thank you!

**Closed** 2023-01-04 07:19 UTC
Labels: stat:awaiting response, stalled, comp:model, type:performance, TF 2.9
