### ISSUE TITLE
Why eager concat  inputs?

### ISSUE THREAD

**Issue by soenkyo** [tensorflow/tensorflow#14209] opened 2017-11-03 13:06 UTC
I am using eager to implement a seq2seq model. 
Here is a [toy model](https://github.com/soenkyo/toy_seq2seq_4_debug):
No error arise in forward calculate, but in backprop, I get:

`Traceback (most recent call last):
  File "/home/usr/eager/test.py", line 18, in <module>
    tf.app.run()
  File "/home/usr/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/usr/eager/test.py", line 14, in main
    empirical_loss, gradients_and_variables = cal_gradient()
  File "/home/usr/miniconda2/lib/python2.7/site-packages/tensorflow/python/eager/backprop.py", line 362, in grad_fn
    sources)
  File "/home/usr/miniconda2/lib/python2.7/site-packages/tensorflow/python/eager/imperative_grad.py", line 230, in imperative_grad
    result.append(vspace.aggregate_fn(g))
  File "/home/usr/miniconda2/lib/python2.7/site-packages/tensorflow/python/eager/backprop.py", line 716, in _aggregate_grads
    for x in indexed_slices_list], 0)
  File "/home/usr/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1110, in concat
    return gen_array_ops._concat_v2(values=values, axis=axis, name=name)
  File "/home/usr/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 719, in _concat_v2
    attrs=_attrs, ctx=_ctx, name=name)
  File "/home/usr/miniconda2/lib/python2.7/site-packages/tensorflow/python/eager/execute.py", line 67, in execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "/home/usr/miniconda2/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [16,100] vs. shape[1] = [16,400] [Op:ConcatV2] name: concat
`

**Comment by asimshankar** [comment] 2017-11-03 17:53
Thanks for the report. Though, without seeing more of the code, it's hard to tell what the problem might be.

Would it be possible to share detailed instructions on reproducing the problem? Ideally a small, self-contained snippet of code that I can run to reproduce the problem?

Thanks!

**Comment by soenkyo** [comment] 2017-11-04 08:49
@asimshankar  I updated a toy code [here](https://github.com/soenkyo/toy_seq2seq_4_debug)

**Comment by tensorflowbutler** [comment] 2018-01-04 19:10
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:10
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-23 13:57
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:31
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by drpngx** [comment] 2018-03-31 21:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by drpngx** 2018-03-31 21:21 UTC
Labels: comp:eager, stat:awaiting tensorflower

**Comment by shantianyang** [comment] 2018-06-22 03:07
hi. @soenkyo ,, "InvalidArgumentError: ConcatOp : Dimensions of inputs should match" , I meet the same problem, Did you have some solutions? thanks!!!

**Comment by vishal2612200** [comment] 2019-06-13 11:08
@shantianyang Did you solve the problem? I also have the same problem.
