### ISSUE TITLE
TensorFlow Serving cannot handle more than 350 requests/second

### ISSUE THREAD

**Issue by roshanzameer** [tensorflow/tensorflow#35149] opened 2019-12-16 09:41 UTC
Docker Image: Tensorflow/Serving:latest
Model: Fashion_Mnist (per the official Docs)
Docker Version: 19.03.2, build 6a30dfc

I'm using Docker Container to serve a Tensorflow SavedModel over the REST API Port 8501. The inference latency is 2ms which is great. 

Problem: I'm trying to perform load-testing and notice that the rate of requests stay constant at approximately 350 requests/sec. Beyond which the request fails. Every request has a single batch payload. 

Observation: At the point of failure, the resource usage is only 10%. Server throws error code 404 and 401.

Troubleshooting: 
1. Have tried running `tensorflow_model_server` directly instead of the docker image and face the same issue. 
2. Have served different models (deep_mnist, custom models). Same issue persists.
3. Built a docker image with suitable instruction set. Same issue persists.
4. Deployed the Docker image on a K8 cluster. Set 4 Replicas behind a loadbalancer. Same issue persists. 
5. Pulled different tensorflow/serving image. Same issue persists. 

What have I been doing wrong?

**Comment by gowthamkpr** [comment] 2019-12-20 22:26
@roshanzameer Duplicate of this [issue ](https://github.com/tensorflow/serving/issues/1517) in tensorflow serving. I am gonna close this issue as it is a seving issue and is being tracked there. Thanks!

**Closed by gowthamkpr** 2019-12-20 22:26 UTC
Labels: TF 2.0, type:performance
