### ISSUE TITLE
const_op.h missing from C++ API documentation

### ISSUE THREAD

**Issue by Remi-Coulom** [tensorflow/tensorflow#13549] opened 2017-10-07 09:37 UTC
I could not find the documentation for tensorflow::ops::Const starting from the C++ API documentation. I figured out it is declared in ops/const_op.h, but there is no link from the main C++ docs:
https://www.tensorflow.org/api_docs/cc/

A search returns this, but it looks orphaned:
https://www.tensorflow.org/api_docs/cc/group/const-op

So I guess there is something wrong in the docs.

**Comment by asimshankar** [comment] 2017-10-07 18:08
@skye - Is `const_op.h` somehow excluded when generating the API docs?

**Comment by skye** [comment] 2017-10-09 14:37
I'm not sure what's going on. @dr4b do you have any ideas? I wonder if this somehow has to do with Const being in the namespace ops, and all the other op methods being in nested namespaces inside ops?

**Comment by Remi-Coulom** [comment] 2017-10-09 17:32
Another strange problem I noticed is that tensorflow::Input::Initializer appears twice in the menu on the left:
https://www.tensorflow.org/api_docs/cc/struct/tensorflow/input/initializer

**Comment by dr4b** [comment] 2017-10-12 22:40
hey, so I looked into the const_op thing and basically it's not showing up because that module/file has no classes in it (you might notice the index pages are all based around listening classes/structs in each part of the API).  We'll have to think of a way to deal with this, I guess.

(Initializer is a separate bug that I was aware of a while ago but didn't realize was still there)

**Comment by tensorflowbutler** [comment] 2017-12-20 01:10
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:04
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-18 19:07
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:14
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tatatodd** [comment] 2018-01-26 00:07
Assigning to @dr4b, since it seems like this is a bug we should fix.  Feel free to re-assign as appropriate.

**Comment by dr4b** [comment] 2018-01-26 21:26
I've already looked into this but I'm still not sure what the right solution is given that seriously const_op had no classes/structs in it.  Unless that's changed?

The duplicate inner struct bug that Remi mentioned, however, is out against me in our internal tools and I should look into that at some point, it's true.

**Comment by tensorflowbutler** [comment] 2018-02-10 19:18
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-03 07:55
Nagging Assignee @dr4b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-17 14:59
Nagging Assignee @dr4b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-01 12:32
Nagging Assignee @dr4b: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dr4b** [comment] 2018-04-02 20:52
I no longer work on Tensorflow and won't be able to address this any time soon (as I said, the issue is that there's nothing inside the file that Doxygen is going to pick up.)  Reassigning if Wolff cares to deal with it.

**Comment by tensorflowbutler** [comment] 2018-04-17 12:46
Nagging Assignee @wolffg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:12
Nagging Assignees @wolffg, @MarkDaoust: It has been 22 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:43
Nagging Assignees @wolffg, @MarkDaoust: It has been 37 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:08
Nagging Assignees @wolffg, @MarkDaoust: It has been 52 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:00
Nagging Assignees @wolffg, @MarkDaoust: It has been 67 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:55
Nagging Assignees @wolffg, @MarkDaoust: It has been 82 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 12:59
Nagging Assignees @wolffg, @MarkDaoust: It has been 97 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:42
Nagging Assignees @wolffg, @MarkDaoust: It has been 112 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MarkDaoust** [comment] 2018-08-24 22:01
There's no simple way to fix this, and the C++ api is relatively low priority.

Sorry.

**Closed by MarkDaoust** 2018-08-24 22:01 UTC
Labels: type:docs
