### ISSUE TITLE
iPhone 6 crash: EXC_BAD_INSTRUCTION in v1.14.0-rc1

### ISSUE THREAD

**Issue by travbid** [tensorflow/tensorflow#29627] opened 2019-06-11 04:43 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Compiled on MacOS 10.14.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
[iPhone6](https://en.wikipedia.org/wiki/IPhone_6), iOS 11.4
- TensorFlow installed from (source or binary):
Source
iOS tensorflow lib built with the script: `tensorflow/contrib/makefile/build_all_ios.sh`
- TensorFlow version (use command below):
v1.14.0-rc1
- GCC/Compiler version (if compiling from source):
XCode 10.2.1
```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Describe the current behavior**
I have written an iOS app that uses TensorFlow from C++.
The app crashes on Session::Run() with `Thread 6: EXC_BAD_INSTRUCTION (code=1, subcode=0xd53be053)`
XCode breaks and highlights an assembler line 329: ->  ```0x1014e7f30 <+1308>: mrs    x19, CNTVCT_EL0```

**Describe the expected behavior**
No crash. The same app built with TensorFlow v1.13.1 runs successfully.

**Other info / logs**
This appears to have been introduced with commit [9a486811ca07b5ca3f60f6fd96e69fc1df889818](https://github.com/tensorflow/tensorflow/commit/9a486811ca07b5ca3f60f6fd96e69fc1df889818) which was not in 1.13.1 but is in 1.14.0-rc0.
It introduces the struct `KernelTimer`, which calls `profile_utils::CpuUtils::GetCurrentClockCycle()` in [cpu_utils.h](https://github.com/tensorflow/tensorflow/blob/v1.14.0-rc1/tensorflow/core/platform/profile_utils/cpu_utils.h#L58) on initialization. On aarch64, this calls `asm volatile("mrs %0, cntvct_el0" : "=r"(virtual_timer_value));` which is the line XCode breaks on.
If I [exit that function with an early return](https://github.com/travbid/tensorflow/commit/8b6b0d2ddb7fb3262c41f471e5f299b9ee377560#diff-5f82d595cba7425ac17d71e7615343d9) then the session runs without crashing.
After consulting the [armv8 reference guide](https://developer.arm.com/docs/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile) the instruction in question looks right to me and can be found in other code samples with a google search.

Unfortunately, I don't have any other iOS devices to test on currently.

I know little about assembler or ARM architectures and have reached the limits of my debugging ability here. Could this be a hardware bug in iPhone 6? Any insight appreciated.

**Comment by fbobital** [comment] 2019-07-08 07:45
I have the same problem when I try to use my iPhone 6s plus. When I test my application using the simulator (any of them), I can execute the method Session::Run(), my application crashes. @travbid, did you find out a solution for this problem?

**Comment by travbid** [comment] 2019-07-09 02:11
@fbobital I worked around this by editing cpu_utils.h as in https://github.com/travbid/tensorflow/commit/8b6b0d2ddb7fb3262c41f471e5f299b9ee377560#diff-5f82d595cba7425ac17d71e7615343d9 and re-compiling TensorFlow.

**Comment by fbobital** [comment] 2019-07-10 07:12
@travbid It also worked for me. Thanks.

**Comment by winstondu** [comment] 2020-08-29 09:02
@mihaimaruseac , can we get this fix into 1.15?

**Comment by mihaimaruseac** [comment] 2020-08-31 17:58
1.14 is old and unsupported. contrib is no longer maintained. Makefile build is only community supported.

**Comment by winstondu** [comment] 2020-09-01 20:33
@mihaimaruseac , I understand, but the issue is fundamentally one about `CPU_utils.h` library file. Apparently, `asm volatile("mrs %0, cntvct_el0" : "=r"(virtual_timer_value));` is a privileged instruction on Apple devices.

Moreover, it still occurs in 1.15 (which is still supposed to be supported for a few more months)

**Comment by mihaimaruseac** [comment] 2020-09-02 16:57
Can you send a patch to 1.15  branch please? Mention me in the PR.

**Comment by mihaimaruseac** [comment] 2020-09-23 17:26
Patch landed, we can close this now. Patch release will come today/tomorrow

**Closed by mihaimaruseac** 2020-09-23 17:26 UTC
Labels: comp:lite, type:bug
