### ISSUE TITLE
Performance regression for FP16 Relu kernel from TF2.6 to TF2.7

### ISSUE THREAD

**Issue by wenscarl** [tensorflow/tensorflow#53476] opened 2021-12-17 20:32 UTC
**Current behavior**
Migrating from TF2.6 to TF2.7 FP16 Relu kernel has changed from EigenMetaKernel to MLIR. 
Tested on Volta and Ampere, the memory throughput gets halved and compute throughput is also reduced. Collected by nsight compute. 
| Throughput %                    | compute | memory |
|---------------------------------|---------|--------|
| EigenMetaKernel                 | 35.79   | 84.20  | 
| Relu_GPU_DT_HALF_DT_HALF_kernel | 28.17   | 45.02  |

A roughly 2x slowdown of the forward pass is observed. The better bandwidth utilization of EigenMetaKernel is contributed from wider vectors for GPU-half implementation for libeigen.

**Comment by mohantym** [comment] 2021-12-20 05:44
Hi @wenscarl ! Could you please provide a minimal stand alone code to reproduce this issue?

**Comment by wenscarl** [comment] 2021-12-21 22:39
```
import numpy as np
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision

policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_global_policy(policy)

inputs = keras.Input(shape=(784,), name='digits')
num_units = 4096

dense1 = layers.Dense(num_units, activation='relu', name='dense_1')
x = dense1(inputs)
dense2 = layers.Dense(num_units, activation='relu', name='dense_2')
x = dense2(x)

x = layers.Dense(10, name='dense_logits')(x)
outputs = layers.Activation('softmax', dtype='float32', name='predictions')(x)

model = keras.Model(inputs=inputs, outputs=outputs)
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=keras.optimizers.RMSprop(),
              metrics=['accuracy'])

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.reshape(60000, 784).astype('float32') / 255
x_test = x_test.reshape(10000, 784).astype('float32') / 255
history = model.fit(x_train, y_train,
                    batch_size=8192,
                    epochs=5,
                    validation_split=0.2)
test_scores = model.evaluate(x_test, y_test, verbose=2)
```
The above is a repo code. On TF2.7, I collected nsight-compute profile by
`ncu -k Relu_GPU_DT_HALF_DT_HALF_kernel --target-processes all -f -o repo_TF27  python repo.py`
On TF2.6, kernel Relu_GPU_DT_HALF_DT_HALF_kernel  just doesn't exist, so just  `ncu -k EigenMetaKernel ...`.  For this repo code, no such big difference in memory throughput is observed.  The big difference in last comment has been seen from [DLRM ](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow2/Recommendation/DLRM)model.

**Comment by mohantym** [comment] 2021-12-23 04:28
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by sachinprasadhs** [comment] 2021-12-27 18:56
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by wenscarl** [comment] 2022-01-04 22:14
Posted on keras-team/keras repo as suggested. Though the repo code is in keras, the root cause should relate to TF directly.

**Comment by chsigg** [comment] 2022-01-29 06:46
Closing this one as duplicate of https://github.com/keras-team/keras/issues/15857.

**Closed by chsigg** 2022-01-29 06:46 UTC
Labels: stat:awaiting tensorflower, comp:gpu, type:performance, TF 2.7
