### ISSUE TITLE
TensorBoard graph key does not match documentation

### ISSUE THREAD

**Issue by orome** [tensorflow/tensorflow#10428] opened 2017-06-04 12:59 UTC
The key in the TensorBoard UI indicates a "Reference edge" as a single-headed arrow:

[![enter image description here][1]][1]

while the documentation shows these as double-headed arrows:

[![enter image description here][2]][2]

Moreover, it appears that the edges indicated as references edges in the UI (according to the key there) are not in fact such edges. For example neither 

    cs = tf.constant([1,2,3], name='const_share')
    vs = tf.Variable([1,2,3], name='var_share')
    tf.add(cs, vs, name='opVS1')
    tf.add(vs, cs, name='opVS2')

<img src="https://i.stack.imgur.com/8z1Bn.png" height="350">

note

    tf.add([4],[3], name='opA')

[![enter image description here][3]][3]

should include reference edges (should they?). But in both cases the key in the UI says that they do.

  [1]: https://i.stack.imgur.com/5MhdF.png
  [2]: https://i.stack.imgur.com/fWRZL.png
  [3]: https://i.stack.imgur.com/eZHmm.png

**Comment by orome** [comment] 2017-06-04 13:04
[Related SO question](https://stackoverflow.com/q/44345863/656912).

**Comment by chihuahua** [comment] 2017-06-04 18:10
By convention, dataflow edges are directed upwards, so that is why the "dataflow edges" lack arrowheads - we assume the reader understands the convention.

If we must make a dataflow edge that points downwards (or close to downwards like in your second picture) - and sometimes that is necessary, we add an arrowhead to make that clear.

Several people (including some folks on deep mind) have told me that this is unclear. For starters, perhaps we can update the documentation to clarify the convention as well as why only some dataflow edges have arrowheads (They just flow downwards).

**Comment by orome** [comment] 2017-06-04 21:50
@chihuahua Indeed, that wasn't at all clear (I'm glad to have company at DeepMind). 

IMV it would be a lot clearer if direction of flow was always indicated, and there was something distinct for "reference edges" (whatever those are).

And of course: the documentation should agree with the docs!

**Comment by jart** [comment] 2017-06-05 04:28
Assigning to @chihuahua as a documentation issue.

**Comment by chihuahua** [comment] 2017-06-06 06:19
FYI, I am moving forward with an internal code change that 

1. Makes reference edges orange (and dataflow edges the same grey as before). The final colors might differ based on input from a designer, but the bottom line is that dataflow and reference edges will contrast in color.
2. Adds arrows to all dataflow edges no matter where they point.

I will subsequently update tensorflow.org docs to match.

Here is a preview. The edges from the "save" node are reference edges because "assign ops" can modify other tensor values.

![qhfhkq7cwb9](https://cloud.githubusercontent.com/assets/4221553/26816188/4324c082-4a45-11e7-9e6e-2b21b61bd5ca.png)

**Comment by chihuahua** [comment] 2017-06-16 19:11
I have migrated this issue to tensorflow/tensorboard#48.

The issue is almost fixed (It is already in the code.). The documentation code just has to be updated, so [this tensorflow.org page](https://www.tensorflow.org/get_started/graph_viz) changes.

**Closed by chihuahua** 2017-06-16 19:11 UTC
Labels: tensorboard, type:docs
