### ISSUE TITLE
test with random fail on graph mode

### ISSUE THREAD

**Issue by amitport** [tensorflow/tensorflow#44642] opened 2020-11-06 08:08 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
v1.12.1-44421-g5e5730ba9d 2.4.0-rc0
- Python version:
3.7.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
11.1
- GPU model and memory:
960m cuda

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
running the followin:
```python
import tensorflow as tf
from tensorflow.python.framework import test_util


class WeirdTest(tf.test.TestCase):

  @test_util.run_in_graph_and_eager_modes
  def test_test(self):
    with self.cached_session():
      x = tf.random.normal([])
      self.assertAllClose(x, x)


if __name__ == '__main__':
  tf.random.set_seed(42)
  tf.test.main()
```

fails with assertion error (the x is not equal to itself!)
(eager mode works fine)

**Describe the expected behavior**
the test should pass

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

attached above (not sure how to run tests on colab)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
Failure
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Program Files\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
  File "D:\python3_venvs\tf_2_4\lib\site-packages\tensorflow\python\framework\test_util.py", line 1196, in decorated
    f(self, *args, **kwargs)
  File "C:\Users\amitp\dev\github\amitport\federated-learning-research\federated_learning_research\v2\encoders\sign_encoder_test.py", line 11, in test_encode
    self.assertAllClose(x, x)
  File "D:\python3_venvs\tf_2_4\lib\site-packages\tensorflow\python\framework\test_util.py", line 1236, in decorated
    return f(*args, **kwds)
  File "D:\python3_venvs\tf_2_4\lib\site-packages\tensorflow\python\framework\test_util.py", line 2711, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "D:\python3_venvs\tf_2_4\lib\site-packages\tensorflow\python\framework\test_util.py", line 2671, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "D:\python3_venvs\tf_2_4\lib\site-packages\tensorflow\python\framework\test_util.py", line 2606, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "D:\python3_venvs\tf_2_4\lib\site-packages\numpy\testing\_private\utils.py", line 1528, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "D:\python3_venvs\tf_2_4\lib\site-packages\numpy\testing\_private\utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=1e-06
Mismatched value: a is different from b. 
not close lhs = 0.4722212255001068
not close rhs = -1.5251041650772095
not close dif = 1.9973254203796387
not close tol = 2.525104165077209e-06
dtype = float32, shape = ()
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 1.9973254
Max relative difference: 1.3096322
 x: array(0.472221, dtype=float32)
 y: array(-1.525104, dtype=float32)
```

**Comment by amahendrakar** [comment] 2020-11-06 15:36
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/905b70e15ffb5cfc8ea2d81d35f0cad9/44642-2-3.ipynb#scrollTo=NpVjmosnL7hg), [TF v2.4.0rc0](https://colab.research.google.com/gist/amahendrakar/e72ce48377783ee0f30debcb5a0b4525/44642-2-4.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/d080f341e52044024ea8c9bfe65d3f6e/44642-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by amitport** [comment] 2020-11-06 17:30
@amahendrakar thanks for reproducing. I have to ask, what was the `type:bug` label removed? Should this be done differently?

**Comment by WindQAQ** [comment] 2020-11-28 02:11
@amitport  I believe this is not a bug. In graph mode, `x = tf.random.normal([])` is returned as an operation, and `self.assertAllClose` will evaluate both input arguments and get the real value (if they are operations). Therefore, `x` is evaluated twice and returned different values. To fix it, you can try to use `self.evaluate` to get the exact value before asserting them.

https://colab.research.google.com/drive/19iN2UNQ4vJ0erH64gskuVkvdZZQO8F8D?usp=sharing

**Comment by amitport** [comment] 2020-11-28 08:11
@WindQAQ thanks. I got to say this is very unintuitive and does not seem correct to me. I would expect assertion methods to evaluate the inputs' shared graph together. (DK if I l'm looking at bug or feature request, I just wonder if it could behave differently)

Is there a use case to evaluate the shared graph part twice?

**Comment by WindQAQ** [comment] 2020-11-28 08:45
> Is there a use case to evaluate the shared graph part twice?

@amitport I would say that in most cases, we are evaluating a (shared) graph multiple times. For example, the ideal training pipeline in both eager and graph model is

```python
# Here is how the (shared) graph is built
model = build_model()

# Here is how operations in the graph are evaluated
# including what kind of inputs are feeding and what kind of outputs are fetched
do_something(model)
```

Let me roughly expand the internal implementation of the example in this PR. What we are doing in graph mode is 

```python
x = tf.random.normal([])

with tf.Session() as sess:
    first = sess.run(x)
    second = sess.run(x)
    np.testing.assert_allclose(first, second)
```

Maybe it's more intuitive for users. If `x` is always evaluted as the same values in runtime, how can we get the different numbers without constructing new graphs?

Consider another common example that sometimes users add "noise" into the input.

```python
input = tf.placeholder(foo)
noise = tf.random.normal([])
noisy_output = input + noise

# do something

with tf.Session() as sess:
    for i in range(10):
        y = sess.run(noisy_output, feed_dict=bar)
```

I think users would expect `y` to be different during iterations as they want noisy outputs even the graph is shared or unchanged.

Let me know if this answers your question. Thank you.

**Comment by amitport** [comment] 2020-11-30 12:06
@WindQAQ Thank you for the example. I still think that these implementation details should not affect the test writer and assert methods could be smarter. That is, I realize it is implemented like this but it seems wrong for test case usage. (just look again at the first example in the issue, why would anyone expect this behavior?)

**Comment by edloper** [comment] 2021-05-17 17:05
@amitport ade73c6af0957e7cbe420ae515c6a5d9acc6ecb3 updated assertAllEqual and similar functions to evaluate `a` and `b` in the same graph.  Closing this as fixed, but please feel free to re-open if you find that this change doesn't address your problem.

**Closed by edloper** 2021-05-17 17:05 UTC
Labels: TF 2.4, comp:apis, stat:awaiting tensorflower, type:bug
