### ISSUE TITLE
import packages of tf2.0.0rc in pycharm

### ISSUE THREAD

**Issue by Xie-Fangyuan** [tensorflow/tensorflow#32534] opened 2019-09-15 03:12 UTC
i'm using tf2.0.0rc, win10.

when i write the below code in pycharm, `Dataset` is underlined with a red line, and shows a message `cannot find reference 'Dataset' in '__init__.py' `, and pycharm can't auto-complete `Dataset`'s functions, but the script can run well.

```python
from tensorflow_core.python.data import Dataset

dataset = Dataset.from_tensors([2])
```

when i write the below code, there is no red line, and pycharm can auto-complete `Dataset`'s functions, but the script has error:`KeyError: "Registering two gradient with name 'ReduceDataset'! (Previous registration was in register /home/xiefangyuan/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/registry.py:66)"`

```python
from tensorflow_core.python.data.ops.dataset_ops import Dataset

dataset = Dataset.from_tensors([2])
```

**Comment by Xie-Fangyuan** [comment] 2019-09-15 03:13
it has the same problem when i import almost every packsge of tf2.0.0rc in pycharm

**Comment by makercob** [comment] 2019-09-16 03:04
see https://github.com/tensorflow/tensorflow/issues/31973

**Comment by ravikyram** [comment] 2019-09-16 06:49
I have tried on colab with TF version 2.0.0-rc0, 2.0.0-rc1  and observed that 
```
from tensorflow_core.python.data import Dataset

dataset = Dataset.from_tensors([2])
```
has no issue. However i can reproduce the issue with 
```
from tensorflow_core.python.data.ops.dataset_ops import Dataset

dataset = Dataset.from_tensors([2])
```
Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/015651d955d4b6d1d2900daaa4efbe0c/untitled187.ipynb).Thanks!

**Comment by Xie-Fangyuan** [comment] 2019-09-16 07:07
> I have tried on colab with TF version 2.0.0-rc0, 2.0.0-rc1 and observed that
> 
> ```
> from tensorflow_core.python.data import Dataset
> 
> dataset = Dataset.from_tensors([2])
> ```
> 
> has no issue. However i can reproduce the issue with
> 
> ```
> from tensorflow_core.python.data.ops.dataset_ops import Dataset
> 
> dataset = Dataset.from_tensors([2])
> ```
> 
> Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/015651d955d4b6d1d2900daaa4efbe0c/untitled187.ipynb).Thanks!

it is the same, the first one can run well, but in pycharm, there is no autocomplete, and cannot find reference 'Dataset' in '__init__.py' . the second one support autocomplete, but it has error.

what i am expecting is both no error and autocomplete in pycharm. i just go back to use tf1.14.0.

**Comment by annarev** [comment] 2019-09-17 18:04
The supported way to use tensorflow is with the following import:
`import tensorflow as tf`
In this case, you would use `tf.data.Dataset` instead. If you want to use V1 dataset, then you can reference it using tf.compat.v1.data.Dataset.

Code under tensorflow_core.python or tensorflow.python is not a part of our public API and has no guarantees.

**Comment by annarev** [comment] 2019-09-17 18:05
Closing, since this question is about unsupported usecase for TensorFlow.

**Closed by annarev** 2019-09-17 18:05 UTC
Labels: TF 2.0-rc0, comp:data, type:bug

**Comment by Xie-Fangyuan** [comment] 2019-09-18 02:43
> The supported way to use tensorflow is with the following import:
> `import tensorflow as tf`
> In this case, you would use `tf.data.Dataset` instead. If you want to use V1 dataset, then you can reference it using `tf.compat.v1.data.Dataset`.
> 
> Code under tensorflow_core.python or tensorflow.python is not a part of our public API and has no guarantees.

what i really want is autocomplete and no reference errors or warnings in pycharm **editor**(i think pycharm can standardize my code and prevent potential errors), but by writing `import tensorflow as tf` and using tf 2.0.0rc0, pycharm can not autocomplete tf's packages or functions, and show some reference errors in the **editor** not in the terminal, even though the code can run well, but the code doesn't look fine in the pycharm **editor**.

but never mind, up to now, i think stable tf 1.14.0 is better for me.

**Comment by annarev** [comment] 2019-09-18 04:19
You are right that 2.0.0rc0 had autocomplete issues. You can try 2.0.0rc1, which had some of the autocomplete issues fixed.
