### ISSUE TITLE
1.10 build fails with "No module named 'keras_applications'"

### ISSUE THREAD

**Issue by skeydan** [tensorflow/tensorflow#21518] opened 2018-08-09 15:36 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Fedora 28
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.16
- **GCC/Compiler version (if compiling from source)**: 7.3
- **CUDA/cuDNN version**: 9.2
- **GPU model and memory**: Quadro M2200 4G
- **Exact command to reproduce**: bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

Hi, a recent checkout of master (~ 2 hours ago) fails (for me) with

```
ERROR: /home/key/code/tensorflow/tensorflow/BUILD:584:1: Executing genrule //tensorflow:tensorflow_python_api_gen failed (Exit 1)
/home/key/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import applications
  File "/home/key/.cache/bazel/_bazel_key/8de93c72df6c3fec3e289f10fadff72b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/applications/__init__.py", line 21, in <module>
    import keras_applications
ModuleNotFoundError: No module named 'keras_applications'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3855.754s, Critical Path: 156.93s
INFO: 8932 processes: 8932 local.
FAILED: Build did NOT complete successfully
```

Could you please advise?

**Comment by av8ramit** [comment] 2018-08-09 19:47
I believe the following will fix this issue:

```
pip install keras_applications==1.0.4 --no-deps
pip install keras_preprocessing==1.0.2 --no-deps
```

@yifeif any additional info?

**Comment by yifeif** [comment] 2018-08-09 19:54
You might also need `pip install h5py==2.8.0`

**Comment by av8ramit** [comment] 2018-08-09 20:59
https://github.com/tensorflow/tensorflow/pull/21527

@skeydan please let us know if this helps.

**Comment by geekonedge** [comment] 2018-08-09 21:25
I can confirm that installing the three packages resolves the issue as per [this link](https://stackoverflow.com/questions/51771039/error-compiling-tensorflow-from-source-no-module-named-keras-applications/51774943#51774943)

**Comment by skeydan** [comment] 2018-08-10 07:53
works great, thank you!!

**Comment by claynerobison** [comment] 2018-08-10 20:30
@gunan Are you going to update the Dockerfiles or do you want me to submit a PR for it? All the containerized builds are failing too.

**Comment by gunan** [comment] 2018-08-10 22:56
AH, I completely missed that.
@av8ramit, could you send a PR to update all our dockerfiles to install the 3 pip packages mentioned in this issue?

**Comment by av8ramit** [comment] 2018-08-10 23:29
Sure, sounds good.

**Comment by av8ramit** [comment] 2018-08-14 00:02
Sent internally.

**Comment by av8ramit** [comment] 2018-08-14 22:37
This issue has now been fixed.

**Comment by dodiknikola** [comment] 2018-08-16 12:16
Building master works for me, but when I try to run tflite_convert, I get the same error:

```
INFO: Running command line: bazel-bin/tensorflow/contrib/lite/python/tflite_convert '--graph_def_file=graph.pb' '--output_format=TFLITE' '--output_file=graph.tflite' '--input_arrays=Input' '--inference_input_type=QUANTIZED_UINT8' '--output_arrays=Output' '--dump_graphviz_dir=graphviz_dir
INFO: Build completed successfully, 3833 total actions
Traceback (most recent call last):
  File "/home/dfp/.cache/bazel/_bazel_dfp/0417b0005f0f3d4bbe5d828c76e5a252/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/contrib/lite/python/tflite_convert.runfiles/org_tensorflow/tensorflow/contrib/lite/python/tflite_convert.py", line 25, in <module>
    from tensorflow.contrib.lite.python import lite
  File "/home/dfp/.cache/bazel/_bazel_dfp/0417b0005f0f3d4bbe5d828c76e5a252/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/contrib/lite/python/tflite_convert.runfiles/org_tensorflow/tensorflow/contrib/lite/python/lite.py", line 41, in <module>
    from tensorflow.contrib.lite.python import lite_constants as constants
  File "/home/dfp/.cache/bazel/_bazel_dfp/0417b0005f0f3d4bbe5d828c76e5a252/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/contrib/lite/python/tflite_convert.runfiles/org_tensorflow/tensorflow/contrib/lite/python/lite_constants.py", line 23, in <module>
    from tensorflow.python.util.all_util import remove_undocumented
  File "/home/dfp/.cache/bazel/_bazel_dfp/0417b0005f0f3d4bbe5d828c76e5a252/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/contrib/lite/python/tflite_convert.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/home/dfp/.cache/bazel/_bazel_dfp/0417b0005f0f3d4bbe5d828c76e5a252/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/contrib/lite/python/tflite_convert.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import applications
  File "/home/dfp/.cache/bazel/_bazel_dfp/0417b0005f0f3d4bbe5d828c76e5a252/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/contrib/lite/python/tflite_convert.runfiles/org_tensorflow/tensorflow/python/keras/applications/__init__.py", line 21, in <module>
    import keras_applications
ImportError: No module named 'keras_applications'
```

**Comment by owengray-brainco** [comment] 2018-08-16 23:30
I am still having this issue. I have installed keras(-applications) and h5py according to [this](https://stackoverflow.com/questions/51771039/error-compiling-tensorflow-from-source-no-module-named-keras-applications/51774943#51774943).
Running
`bazel build -c opt --copt=-march=native //tensorflow/tools/pip_package:build_pip_package`
The error ends with
`ERROR: /Users/owengray/Desktop/git/tensorflow/tensorflow/BUILD:576:1: Executing genrule //tensorflow:tensorflow_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_owengray/8e2e063d880456f5e168abd014557d0b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/private/var/tmp/_bazel_owengray/8e2e063d880456f5e168abd014557d0b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 81, in <module>
    from tensorflow.python import keras
  File "/private/var/tmp/_bazel_owengray/8e2e063d880456f5e168abd014557d0b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 25, in <module>
    from tensorflow.python.keras import applications
  File "/private/var/tmp/_bazel_owengray/8e2e063d880456f5e168abd014557d0b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/applications/__init__.py", line 21, in <module>
    import keras_applications
ModuleNotFoundError: No module named 'keras_applications'
Target //tensorflow/tools/pip_package:build_pip_package failed to build`

**Comment by av8ramit** [comment] 2018-08-16 23:37
What python version are you running with? What was the output of your pip install commands?

**Comment by owengray-brainco** [comment] 2018-08-16 23:44
`Owens-MBP:~ owengray$ pip install keras_applications==1.0.4 --no-deps
Requirement already satisfied: keras_applications==1.0.4 in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.0.4)
Owens-MBP:~ owengray$ pip install keras_preprocessing==1.0.2 --no-deps
Requirement already satisfied: keras_preprocessing==1.0.2 in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.0.2)
Owens-MBP:~ owengray$ pip install h5py==2.8.0
Requirement already satisfied: h5py==2.8.0 in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (2.8.0)
Requirement already satisfied: numpy>=1.7 in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from h5py==2.8.0) (1.15.0)
Requirement already satisfied: six in /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from h5py==2.8.0) (1.11.0)`
`Owens-MBP:~ owengray$ /usr/local/bin/python3 --version
Python 3.6.5`

**Comment by owengray-brainco** [comment] 2018-08-16 23:46
Also,
`Owens-MBP:tensorflow owengray$ ./configure 
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
You have bazel 0.16.1 installed.
Please specify the location of python. [Default is /usr/bin/python]: /usr/local/bin/python3

Found possible Python library paths:
  /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages]`

I get several errors running bazel fetch ... -k, but they don't seem related.

**Comment by av8ramit** [comment] 2018-08-16 23:50
Yup, that looks like it's it. Please let us know if it works now.

**Comment by owengray-brainco** [comment] 2018-08-17 15:34
Still didn't work.
`Found possible Python library paths:
  /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages]
/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages`
`  File "/private/var/tmp/_bazel_owengray/8e2e063d880456f5e168abd014557d0b/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/create_tensorflow.python_api.runfiles/org_tensorflow/tensorflow/python/keras/applications/__init__.py", line 21, in <module>
    import keras_applications
ModuleNotFoundError: No module named 'keras_applications'
Target //tensorflow/tools/pip_package:build_pip_package failed to build`

**Comment by av8ramit** [comment] 2018-08-17 18:38
My theory is you're not installing keras_applications to the right python path that you're specifying.

**Comment by owengray-brainco** [comment] 2018-08-17 18:59
`ls /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras
keras/               keras_applications/  keras_preprocessing/`

**Comment by jeanpat** [comment] 2018-08-23 13:59
What about building tensorflow in a virtual environment?

**Comment by gunan** [comment] 2018-08-23 16:41
You will either need to create the virtualenv with `--system-site-packages`, or run `pip install keras-applications` (and other pip install commands) after you activate the virtualenv.

**Comment by HsinM** [comment] 2018-09-03 17:06
If you set PIP_REQUIRE_VIRTUALENV environment variable, disable/remark it. All will be well!!
This environment variable is usually placed in  `~/.bashrc` file.
#export PIP_REQUIRE_VIRTUALENV=true

**Comment by mpekalski** [comment] 2018-09-05 08:32
I am building TF with debug symbols, the latest greatest commit, and it looks like Tensorflow requires 
```
    'keras_applications >= 1.0.5',
    'keras_preprocessing >= 1.0.3',
```
but keras itself wants different version
```
error: Keras-Applications 1.0.5 is installed but keras-applications==1.0.4 is required by {'keras'}
```

https://github.com/tensorflow/tensorflow/blob/6729cd7d1c07e547298fa2a02d1e36390dc62f0a/tensorflow/tools/pip_package/setup.py



```
% pip install keras_applications==1.0.4  --no-deps
Requirement already satisfied: keras_applications==1.0.4 in ~/.pyenv/versions/venv36/lib/python3.5/site-packages (1.0.4)
                 
% pip install keras_preprocessing==1.0.2  --no-deps
Requirement already satisfied: keras_preprocessing==1.0.2 in ~/.pyenv/versions/env36/lib/python3.5/site-packages (1.0.2)
                          
% python3 setup.py develop
running develop
running egg_info
writing entry points to tensorflow.egg-info/entry_points.txt
writing requirements to tensorflow.egg-info/requires.txt
writing top-level names to tensorflow.egg-info/top_level.txt
writing tensorflow.egg-info/PKG-INFO
writing dependency_links to tensorflow.egg-info/dependency_links.txt
reading manifest file 'tensorflow.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.py' under directory '*'
warning: no files found matching '*.pd' under directory '*'
warning: no files found matching '*.so' under directory '*'
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.csv' under directory '*'
warning: no files found matching '*' under directory 'tensorflow/aux-bin'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/Eigen'
warning: no files found matching '*' under directory 'tensorflow/include/external'
warning: no files found matching '*.h' under directory 'tensorflow/include/google'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
warning: no files found matching '*' under directory 'tensorflow/include/unsupported'
writing manifest file 'tensorflow.egg-info/SOURCES.txt'
running build_ext
Creating ~/.pyenv/versions/venv36/lib/python3.5/site-packages/tensorflow.egg-link (link to .)
tensorflow 1.10.0 is already the active version in easy-install.pth
Installing saved_model_cli script to ~/.pyenv/versions/venv36/bin
Installing tensorboard script to ~/.pyenv/versions/venv36/bin
Installing tflite_convert script to ~/.pyenv/versions/venv36/bin
Installing toco_from_protos script to `/.pyenv/versions/venv36/bin
Installing freeze_graph script to ~/.pyenv/versions/venv36/bin
Installing toco script to ~/.pyenv/versions/venv36/bin

Installed tensorflow/tensorflow/tools/pip_package
Processing dependencies for tensorflow==1.10.0
error: Keras-Applications 1.0.5 is installed but keras-applications==1.0.4 is required by {'keras'}
```

Even if I downgrade keras_applications and keras_processing TF installation overwrites them and complains that {keras} wants different version.

**Comment by owengray-brainco** [comment] 2018-09-05 16:02
I finally got it working. I just needed to make sure that the version of python I passed to the first question in ./configure could successfully import keras when run from command line. I may have also needed to set PYTHONPATH.
I also found that the option --copt=-march=native did not work, and I needed to manually specify e.g. --copt=-mavx2
I also got the keras version mismatch error, but the compilation succeeded and works fine.

**Comment by mpekalski** [comment] 2018-09-05 19:35
In my case it was the problem that there are two different versions of packages with `-` and `_` after keras so `keras_applications` and `keras-applications`. I was looking at one and TF was requiring the other one. The same goes for `keras_preprocessing`

**Comment by av8ramit** [comment] 2018-09-10 19:28
Closing this for now. Please comment if this is still an issue for you in virtualenv.

**Closed by av8ramit** 2018-09-10 19:28 UTC
Labels: stat:awaiting response

**Comment by tarod13** [comment] 2019-02-04 04:51
I had the same problem during the installation in virtualenv. It worked once I installed 

pip install keras_applications==1.0.4 --no-deps
pip install keras_preprocessing==1.0.2 --no-deps
pip install h5py==2.8.0

**outside** of the virtual environment.

**Comment by LearnerInGithub** [comment] 2019-04-11 07:59
@yifeif  I alse faced same problem, Environment information: keras==2.2.4, tensorflow-gpu==1.10.0, keras_applications==1.0.7, keras_preprocessing==1.0.9, CentOS 7.0, Python==3.6.5, very strange thing is that the training phase is OK, but while saved the trained model, and then load the trained model in testing phase, the system show the bellow error informatin:

  File "nasnet_predict.py", line 278, in <module>
    model = load_model("res_models/model.h5")
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/site-packages/keras/engine/network.py", line 1032, in from_config
    process_node(layer, node_data)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/network.py", line 991, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/layers/core.py", line 687, in call
    return self.function(inputs, **arguments)
  File "/usr/local/lib/python3.6/site-packages/keras/applications/__init__.py", line 23, in wrapper
    def keras_modules_injection(base_fun):
NameError: name 'keras_applications' is not defined

**Comment by lorenzob** [comment] 2019-05-14 16:35
I solved this error (on 1.13.1) by running:

pip3 install keras_applications==1.0.6 --no-deps
pip3 install keras_preprocessing==1.0.5 --no-deps
pip3 install h5py==2.8.0

**Comment by drblind42** [comment] 2019-09-10 12:41
still got the same problem

windows 10
python 3.6
tensorflow-gpu 1.1.2
keras 2.2.4
keras-applications 1.0.6
keras-preprocessing 1.0.5


**NameError: name 'keras_applications is not defined**

**Comment by drblind42** [comment] 2019-09-10 12:42
> I solved this error (on 1.13.1) by running:
> 
> pip3 install keras_applications==1.0.6 --no-deps
> pip3 install keras_preprocessing==1.0.5 --no-deps
> pip3 install h5py==2.8.0

still got the same problem

windows 10
python 3.6
tensorflow-gpu 1.1.2
keras 2.2.4
keras-applications 1.0.6
keras-preprocessing 1.0.5
h5py 2.8.0

NameError: name 'keras_applications is not defined

**Comment by lorenzob** [comment] 2019-09-10 12:55
tensorflow-gpu 1.1.2 ? I use 1.13.1

**Comment by drblind42** [comment] 2019-09-11 07:18
> tensorflow-gpu 1.1.2 ? I use 1.13.1

tensorflow-gpu 1.12.0 
My mistake

**Comment by mayd-in** [comment] 2019-10-31 17:56
I encountered the same problem after 6 hours of compiling.

If I run build again, does it start compiling all over again or resume? Because I don't want to compile 6 hours again.

**Comment by wu-yy** [comment] 2020-02-28 12:35
when you install the [Keras-Preprocessing ](https://pypi.org/project/Keras-Preprocessing), This error is not resolved, you can check if you have multi versions of python. and it not been installed in your compile python version.
