### ISSUE TITLE
[bug] CUDA messes up after improperly closing Tensorflow session 

### ISSUE THREAD

**Issue by ArturoDeza** [tensorflow/tensorflow#12394] opened 2017-08-18 15:02 UTC
Whenever I run Keras sessions on PyCharm, and I "forget" to properly close the session (example: I log off the computer, or close session). It seems like the CUDA driver stops working. I can still run `$nvcc -V` and `$nvidia-smi` successfully but running the `./deviceQuery` sanity check from the CUDA samples fails, which means the system has stopped detecting the graphics card.

Has anyone else had this problem? I definitely recall that this is not the first time this has happened to me using tensorflow vs say using torch, pytorch that also use the graphics card and "forgetting" to close my session.

Perhaps I am just being spoiled? Note that this has happened both using tensorflow directly and using keras with tensorflow as backend (where I do not have direct control over closing sessions directly as far as I know).

**Comment by reedwm** [comment] 2017-08-18 17:01
@ArturoDeza does this also occur if you kill the TensorFlow process, or just when you log out?

@zheng-xq is this a known problem? Since it happens in other ML libraries, it sounds like a bug in Cuda or the Nvidia drivers.

**Comment by ArturoDeza** [comment] 2017-08-18 17:13
@reedwm I have never had this issue happen to me on PyTorch or Torch, either by me not closing the session properly or just killing the process. So I think this is more of a bug on the tensorflow side.

**Comment by reedwm** [comment] 2017-08-18 17:36
Whoops sorry, I misinterpreted your comment. If it only occurs in TensorFlow, it is less likely to be a bug in Cuda.

I cannot reproduce by creating a TensorFlow `tf.Session` then closing it or killing the process. I haven't tried logging out yet since that will close all my windows which is inconvenient, but I'll try that later.

@zheng-xq do you know what the issue is?

**Comment by ArturoDeza** [comment] 2017-08-18 18:54
Thank you @reedwm for looking into this. Once I find the exact cause of this issue again, I will repost it. I guess I felt a quite frustrated since I did a mix of these things, and had to re-install the CUDA driver three times in the last 2 days because of running a process on keras with tensorflow in the backend, and all of a sudden the next day (or hour) the driver stopped working. But this has definitely happened to me before with pure tensorflow processes on other computers.

**Comment by ArturoDeza** [comment] 2017-08-23 14:54
@reedwm @zheng-xq **Bug Reproduced:** I started an interactive python keras program with tensorflow in the backend, and "closed my laptop". I left it closed overnight at work, and got back in the morning, and when I still had the interactive python console on, the GPU didn't seem to respond. I could still get a positive response by typing in `$nvcc -V` and `$nvidia-smi `, but couldn't run the `./deviceQuery` and `./bandwidthTest` samples from the NVIDIA CUDA Samples folder.

**Solution:** Restart computer. It seems like the Driver gets messed up when you leave a process hanging in an interactive console and don't close the console before logging out of the session or "making the computer sleep" (the case of the laptop when you close it). It works fine now as if nothing has happened.

**Closed** 2017-08-23 14:55 UTC
Labels: stat:awaiting tensorflower
