### ISSUE TITLE
Bug: Exception ignored in BaseSession.__del__

### ISSUE THREAD

**Issue by Hvass-Labs** [tensorflow/tensorflow#3388] opened 2016-07-19 11:00 UTC
Hello Everyone,

The following code produces an error in TensorFlow:

```
import tensorflow as tf

a = tf.constant(123)
b = tf.constant(456)
c = a * b

session = tf.Session()

# A slightly different error is produced if this is removed.
session.run(tf.initialize_all_variables())

result = session.run(c)

print(result)

session.close()    # The error is produced regardless of this.

#quit()            # This produces the error.

import sys
sys.exit()         # This also produces the error.
```

This is the contents of sandbox3.py which I run in PyCharm.

The output is:

```
/home/magnus/anaconda3/envs/tensorflow/bin/python /home/magnus/development/TensorFlow-Tutorials/sandbox3.py
56088
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fb4ecd301d0>>
Traceback (most recent call last):
  File "/home/magnus/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 171, in __del__
  File "/home/magnus/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 167, in close
AttributeError: 'NoneType' object has no attribute 'raise_exception_on_not_ok_status'

Process finished with exit code 0
```

I'm using the following versions:
- TensorFlow 0.9.0 CPU installed from binary.
- Python 3.5.1
- Anaconda 2.5.0
- PyCharm 5.0.4
- Linux Mint 17.3

**Comment by concretevitamin** [comment] 2016-07-20 22:46
I cannot reproduce this on Ubuntu or my local Mac laptop -- both run fine, with or without the `quit()` line.  FYI, Linux Mint is not officially supported, so I'm marking this as community support.

**Comment by wjbaibai** [comment] 2016-09-09 09:18
Same bug with me, anyway, it didn't happen every time, just occasionally.

**Comment by bzamecnik** [comment] 2016-09-26 12:01
Also happens to me occassionally on TensorFlow 0.10.0, Python 3.5, Ubuntu 15.10.

**Comment by oxydron** [comment] 2016-10-04 19:14
Same problem on elementary OS 0.4 Loki

- conda version : 4.2.9
- conda-env version : 4.2.9
- conda-build version : 2.0.2
- python version : 3.5.2.final.0
- tensorflow                0.10.0

Not everytime too.

**Comment by yaroslavvb** [comment] 2016-10-04 19:58
That should be fixed in 0.11rc0 by
https://github.com/tensorflow/tensorflow/commit/b21c69a266b9058133827d12f8915829ae07cd9a

**Comment by liusida** [comment] 2016-10-31 12:19
Unfortunately, after [b21c69a](https://github.com/tensorflow/tensorflow/commit/b21c69a266b9058133827d12f8915829ae07cd9a) fix, this exception will come up oftenly (not every time.):

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f78b6702a58>>
Traceback (most recent call last):
  File "/home/liusida/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 532, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus'

**Comment by motiur** [comment] 2016-11-12 06:06
Hi @liusida - can the bug be fixed . I am somehow getting this error - though not often but I am getting it. My grades in class is somehow dependent on it.

**Comment by liusida** [comment] 2016-11-12 09:05
@motiur If you build tensorflow from source code, and if you cannot wait, and if you just want to mute this error message temporarily, I think you can just comment this line out:
.../site-packages/tensorflow/python/client/session.py, line 532, in __del__
`tf_session.TF_DeleteStatus(status)`

But I suggest you to wait for the official fix.

**Comment by motiur** [comment] 2016-11-13 19:56
@liusida Hi I have commented out `try` and` finally` block  of code:
```
try:
  status = tf_seesion.TF_NewStatus( )
  tf_session.TF_DeleteSession(self._session, status)
finally:
  tf_session_TF_DeleteStatus(status)

```
Hope it wouldn't have drastic impact down the road.

**Comment by atemerev** [comment] 2016-11-16 20:14
@yaroslavvb Looks like it wasn't:

```
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f86c267fe80>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 532, in __del__
UnboundLocalError: local variable 'status' referenced before assignment
```

**Comment by yaroslavvb** [comment] 2016-11-16 20:33
@atemerev that's a different error, which seems to be fixed at head -- https://github.com/tensorflow/tensorflow/blob/7e94b1ee27cb4e009f8bbee1f230c7ca3adfccf3/tensorflow/python/client/session.py#L578

```
 def __del__(self):
    # cleanly ignore all exceptions
    try:
      self.close()
    except Exception:  # pylint: disable=broad-except
      pass
    if self._session is not None:
      try:
        status = tf_session.TF_NewStatus()
        tf_session.TF_DeleteDeprecatedSession(self._session, status)
      finally:
        tf_session.TF_DeleteStatus(status)
      self._session = None
```

**Comment by biolee** [comment] 2016-12-21 11:41
it induced by different gc sequence, you can force python to del session by:

`sel session`

or if you are using keras, you cant get the session instance, you can run folloing code:
`import gc
gc.collect()`

**Comment by lanceturnbull** [comment] 2016-12-28 03:57
@biolee It works for me. Thanks a lot! I'm using keras.

**Comment by ksrinivs64** [comment] 2017-01-06 14:47
I'm using Keras but this fix doesn't work for me.  Still fails intermittently.

**Comment by lanceturnbull** [comment] 2017-01-06 23:00
@ksrinivs64  Can you post your error message and the problematic code here?

**Comment by kengz** [comment] 2017-01-07 20:24
@ksrinivs64 try delete session from keras backend:
```python
from keras import backend as K

# ... code
K.clear_session()
```

**Comment by ods94065** [comment] 2017-01-11 21:00
Here's code that reproduces the Keras problem for me from a recent build of my test system. Ubuntu 14.04, Python 3.4 (default OS version), TensorFlow 0.12.1, Keras 1.2.0:

```
"""Verify that Keras works correctly.

Example comes from: http://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
"""
from keras import models
from keras import layers
import numpy
import gc

# fix random seed for reproducibility
numpy.random.seed(7)

dataset = numpy.loadtxt('pima.csv', delimiter=',')
# First 8 columns are the input variables
X = dataset[:, 0:8]
# Last column is the output variable
Y = dataset[:, 8]

# Create fully-connected network with three layers.
# The last layer has one neuron to predict the class.
model = models.Sequential()
model.add(layers.Dense(12, input_dim=8, init='uniform', activation='relu'))
model.add(layers.Dense(8, init='uniform', activation='relu'))
model.add(layers.Dense(1, init='uniform', activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, nb_epoch=150, batch_size=10, verbose=False)

scores = model.evaluate(X, Y, verbose=False)
print('{}: {}%'.format(model.metrics_names[1], scores[1] * 100))

# Explicitly reap session to avoid a dumb AttributeError sometimes thrown by
# TensorFlow on shutdown. See:
# https://github.com/tensorflow/tensorflow/issues/3388
gc.collect()
```

**Comment by ods94065** [comment] 2017-01-11 23:04
Another update: ITOT the `gc.collect()` solution I attempted in my straight-up TensorFlow test ended up not working reliably either. So, I went from doing this:

```
import gc
with tf.Session() as session:
    session.run(...)
gc.collect()
```

To doing this:

```
with tf.Session() as session:
    session.run(...)
del session
```

It's a nondeterminstic error, so we'll see if that takes.

**Comment by yufengg** [comment] 2017-01-21 21:30
Just hit this error too. Another system spec data point: Python 3.5.0, TF 0.12.1, Macbook Pro, Nvidia 980 Ti GPU (external)

**Comment by sevazhidkov** [comment] 2017-01-22 18:38
+1

**Comment by biolee** [comment] 2017-01-22 22:18
i think is some obj reference bug that Swig induced , so i propose by `del sess` or `gc.collect()`, if it not reliable as report before, further debug TBD 


@kengz clear_session is not delete，original code is
```
def clear_session():
    """Destroys the current TF graph and creates a new one.
    Useful to avoid clutter from old models / layers.
    """
    global _SESSION
    global _GRAPH_LEARNING_PHASES
    tf.reset_default_graph()
    reset_uids()
    _SESSION = None
    phase = tf.placeholder(dtype='bool', name='keras_learning_phase')
    _GRAPH_LEARNING_PHASES[tf.get_default_graph()] = phase
```

**Comment by oxydron** [comment] 2017-01-23 18:30
@biolee you can add your last comment (on how to solve it) there on the source code as a comment (I think the github offers that).

**Comment by apiszcz** [comment] 2017-02-24 12:28
Another: TF1.0.0, Win10

[Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x000001D3B79EF358>>
Traceback (most recent call last):
  File "lib\tensorflow_gpu\tensorflow\python\client\session.py", line 582, in __del__
UnboundLocalError: local variable 'status' referenced before assignment](url)

**Comment by pkit** [comment] 2017-03-14 21:50
Seems like the module-level functions are cleared before `Session.__del__()` is called.
Which is standard cpython behaviour on shutdown (i.e. `tf_session = None` is called by python modules cleanup before `tf_session.TF_NewStatus()`).
Should not be a problem in `python > 3.4` but having python 3.5 bug reports here, I'm not sure.

**Closed** 2017-03-20 20:31 UTC
Labels: stat:community support

**Comment by aiwabdn** [comment] 2017-04-24 10:26
I am on TF 1.1 rc2 freshly built from source on macOS Sierra and keras 2.0.2. Facing the same problem. Commented out the try-finally block at line 595 in session.py to make it work. Don't know if the hack will have any effect on the model.

**Comment by ChristopherLucas** [comment] 2017-05-30 00:32
I'm also using TF1.1.0, Python 3.5, Ubuntu 16.04.2 and am still getting this error. Are there any solutions aside from commenting out the section of code below from `session.py`? If not, is there any reason to worry about commenting this code out?
```
        if status is not None:
          tf_session.TF_DeleteStatus(status)
```

**Comment by dkerzig** [comment] 2017-06-23 09:05
Getting the same error with TF (GPU) 1.12.0, Python 3.5.3, 1080ti (external) on my MBP running Win10. The code was basically the sample code from this MNIST Keras-Tutorial: https://github.com/wxs/keras-mnist-tutorial/blob/master/MNIST%20in%20Keras.ipynb (until [10]) .

**Comment by jamiechoi1995** [comment] 2017-10-26 10:17
Same issue happened occasionally.

Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f88e5b52908>>
Traceback (most recent call last):
  File "/home/wcai/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 701, in __del__
TypeError: 'NoneType' object is not callable

Python 3.5.2
TensorFlow 1.3.0 GPU version installed by virtualenv
Linux Mint 18 64-bit

**Comment by MartinBasti** [comment] 2017-12-20 17:35
@ChristopherLucas I agree with you, something inside `status = c_api_util.ScopedTFStatus()` must call `None()`

Because during GC there is guaranteed almost nothing, the best may be even `except Exception`

**Comment by barathbheeman** [comment] 2017-12-21 21:20
So can someone tell me what the final fix is?

**Comment by JaviFuentes94** [comment] 2018-03-07 17:17
I was having the same problem and it was caused because when loading the weights of a previous model it also loaded the number of epochs, based on that previous session. So when you try to load your model from epoch = 50 and train it for epochs = 25 it will give you a Nonetype object because you already pass those 25 epochs. 

Summing up, set `n_epochs_new_model>n_epochs_loaded_model`.

**Comment by hosford42** [comment] 2018-04-21 02:13
@barathbheeman 

Calling `K.clear_session()` at the end got rid of this issue for me.

**Comment by chinmay5** [comment] 2018-05-22 19:09
@JaviFuentes94 sorry for the question but when you mention setting `n_epochs_new_model>n_epochs_loaded_model` where should this be set?

**Comment by juiceboxjoe** [comment] 2018-05-30 20:30
Hello everyone,

Same issue still happening to me occasionally even though I cleared the TF session with `K.clear_session()` as @hosford42 suggested **_before_** and **_after_** each forward pass. @Nimi42 also suggested that in #8652. 

Adding `import tensorflow as tf` like @Ares513 suggested in #8652 didn't work either.

I'm making inferences on multiple images, which are kicked off from separate bash scripts that are executing sequentially so I'm wondering if clearing the session would actually help since every forward pass of my net is invoked from a different process.

I'm using python 3.4, keras 2.1.6, and tensorflow 1.8.0 (no GPU support). 

This is the error:

`
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f037640b198>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/client/session.py", line 707, in __del__
TypeError: 'NoneType' object is not callable
`

Don't know if it may be related but this is also a warning I get each time I run my inference script:

`
/usr/lib/python3.4/importlib/_bootstrap.py:321: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  return f(*args, **kwds)
`

#8652  is related and some also solved it by placing `K.clear_session()` **_after_** all the code was done. Note that contrary to what the author of #8652 states this issue is not closed and @naatje80 mentions it's a Keras issue but [this](https://github.com/fizyr/keras-retinanet/issues/192) is a related Keras issue that was closed stating it's a TF issue. [This](https://github.com/tensorflow/cleverhans/issues/17) issue is also related and also states it's a tensorflow issue.

This is a nagging issue which is very important for me to sort out due to an upcoming checkpoint for the [xView dataset challenge](http://xviewdataset.org/) (June 15). If anyone can shed some light on this I will greatly appreciate it.

Thanks in advance.

**Comment by princeofpotato** [comment] 2018-07-07 17:17
The code from @ChristopherLucas should work.  Let's see the reason:
The  original code:
if self._session is not None:
 try:
   if self._created_with_new_api:
     tf_session.TF_DeleteSession(self._session)
   else:
     tf_session.TF_DeleteDeprecatedSession(self._session)
 except AttributeError:
   # At shutdown, `c_api_util` or `tf_session` may have been garbage
   # collected, causing the above method calls to fail. In this case,
   # silently leak since the program is about to terminate anyway.
   pass
 self._session = None

Look at the comments. What the comment said should also be suitable for the NoneType Error, I think. So the code from @ChristopherLucas should work perfectly.

I did a similar change to the code and it works fine:
      except (AttributeError, TypeError) as e:
        # At shutdown, `c_api_util` or `tf_session` may have been garbage
        # collected, causing the above method calls to fail. In this case,
        # silently leak since the program is about to terminate anyway.
        print('Error passed, Do not worry. `c_api_util` or `tf_session` may have been garbage collected. The error is ',e.args[-1])
        pass

**Comment by muneebullahkhan** [comment] 2018-08-09 08:08
i run this code 
import tensorflow as tf    
# read and decode the image
image_contents = tf.read_file("~/Desktop/test.jpg")
image = tf.image.decode_jpeg(image_contents, channels=3)

with tf.Session() as sess:   
    img = sess.run(image)
    print(img)
and give this flowing error how to fix it
NotFoundError                             Traceback (most recent call last)
~\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

~\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1306       return self._call_tf_sessionrun(
-> 1307           options, feed_dict, fetch_list, target_list, run_metadata)
   1308

**Comment by rfgm6** [comment] 2018-08-28 02:09
For those using tensorflow as keras backend, you may add the following function to your code:

def set_keras_backend(backend):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        importlib.reload(K)
        assert K.backend() == backend
    if backend == "tensorflow":
        K.get_session().close()
        cfg = K.tf.ConfigProto()
        cfg.gpu_options.allow_growth = True
        #cfg.gpu_options.allocator_type = 'BFC'
        K.set_session(K.tf.Session(config=cfg))
        K.clear_session()

set_keras_backend("tensorflow")

**Comment by rfgm6** [comment] 2018-08-28 02:18
For those using tensorflow as keras backend, you may add the following function to your code. It is also useful in case you need to manage your memory.
```
import os
import importlib
from keras import backend as K

def set_keras_backend(backend):
    if K.backend() != backend:
        os.environ['KERAS_BACKEND'] = backend
        importlib.reload(K)
        assert K.backend() == backend
    if backend == "tensorflow":
        K.get_session().close()
        cfg = K.tf.ConfigProto()
        cfg.gpu_options.allow_growth = True
        K.set_session(K.tf.Session(config=cfg))
        K.clear_session()

set_keras_backend("tensorflow")  
```

**Comment by free-variation** [comment] 2018-09-27 18:12
Thank you @rfgm6, I tried your suggestion.  The frequency of this bug has dropped from "always" to "sometimes", but unfortunately, for us, isn't a complete solution yet.

**Comment by adr-arroyo** [comment] 2018-12-04 09:15
I am getting the same error when loading two models in two different threads (one thread is for training and the other for predicting):

> Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x00000000220AD7B8>>
Traceback (most recent call last):
  File "C:\Users\a703572\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1455, in __del__
    self._session._session, self._handle, status)
  File "C:\Users\a703572\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x00000000226AD390>>
Traceback (most recent call last):
  File "C:\Users\a703572\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1455, in __del__
    self._session._session, self._handle, status)
  File "C:\Users\a703572\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.

However, there is no "Process finished with exit code 0" so i can keep up with the usual workflow, but I am afraid that in production this might actually crash at any time. I am still not sure if this error might come from using different graphs and sessions for predicting and training (this is the solution i found, together with some filelocks, for multithread in keras).
I use the following code when doing any tf operations:

                with graph_pred.as_default():
                    with tf.Session(graph=graph):

Is there any advance in this issue?

**Comment by wangyexiang** [comment] 2019-03-02 12:15
Have you solved your problem? @adr-arroyo

**Comment by adr-arroyo** [comment] 2019-03-08 08:09
Actually no :(
I guess it is because I force the use of several models. But I do not know how to avoid this exception yet

**Comment by jasperchih** [comment] 2019-04-01 06:53
i encounter this issue too. please see the log file as below
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x0000018D3D47D0F0>>
Traceback (most recent call last):
  File "C:\Users\Gakki\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1455, in __del__
    self._session._session, self._handle, status)
  File "C:\Users\Gakki\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x0000018D3D492CC0>>
Traceback (most recent call last):
  File "C:\Users\Gakki\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1455, in __del__
    self._session._session, self._handle, status)
  File "C:\Users\Gakki\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
Exception ignored in: <bound method BaseSession._Callable.__del__ of <tensorflow.python.client.session.BaseSession._Callable object at 0x0000018D3E670048>>
Traceback (most recent call last):
  File "C:\Users\Gakki\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1455, in __del__
    self._session._session, self._handle, status)
  File "C:\Users\Gakki\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.CancelledError: Session has been closed.
Train on 60 samples, validate on 60 samples
Epoch 1/10
2019-04-01 14:50:46.963109: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-04-01 14:50:46.963378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-01 14:50:46.963695: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-04-01 14:50:46.963872: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-04-01 14:50:46.964132: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3857 MB memory) -> physical GPU (device: 0, name: Quadro P2000, pci bus id: 0000:01:00.0, compute capability: 6.1)

**Comment by adr-arroyo** [comment] 2019-04-01 10:55
I avoided some of the errors by removing this redundant code:

    with tf.get_default_graph():
        with tf.Session as sess:

But ocassionally the sesion keeps closing again.

**Comment by AleksLi1** [comment] 2021-08-01 21:49
Getting the following error once after running my code seems to make it no longer runable
`Exception ignored in: <function _CheckpointRestoreCoordinatorDeleter.__del__ at 0x0000027B7FEA34C0>
Traceback (most recent call last):
  File "D:\Users\user\anaconda3\envs\Prophet\lib\site-packages\tensorflow\python\training\tracking\util.py", line 158, in __del__
TypeError: 'NoneType' object is not callable`
I've noticed that a 'Untitled Project' file gets created in my project directory 
![image_2021-08-02_004857](https://user-images.githubusercontent.com/87274844/127786276-35ff20c9-aa6b-47c4-bc5e-7736c1549468.png)
after running my code, and deleting it seems to make the code work again.
