### ISSUE TITLE
Incompatible shapes between op input and calculated input gradient for nn.conv3d_transpose

### ISSUE THREAD

**Issue by Bedrettin-Cetinkaya** [tensorflow/tensorflow#21875] opened 2018-08-25 15:34 UTC
This is code:

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from utils import init_weight
import tensorflow as tf

slim = tf.contrib.slim


@tf.contrib.framework.add_arg_scope
def conv3d_transpose(inputs,
                     num_outputs,
                     kernel_size,
                     weights,
                     biases,
                     stride,
                     padding,
                     activation_fn=tf.nn.relu,
                     weights_initializer=tf.contrib.layers.xavier_initializer(),
                     biases_initializer=tf.zeros_initializer(),
                     reuse=None,
                     trainable=True,
                     scope=None):

  with tf.variable_scope(
      scope, 'Conv3d_transpose', [inputs], reuse=reuse):
    dtype = inputs.dtype.base_dtype
    kernel_d, kernel_h, kernel_w = kernel_size[0:3]
    num_filters_in = inputs.get_shape()[4]
    weights_shape = [kernel_d, kernel_h, kernel_w, num_outputs, num_filters_in]
    
    weights = tf.get_variable('weights',
                              shape=weights_shape,
                              dtype=dtype,
                              initializer=tf.constant_initializer(weights),
                              trainable=trainable)
    
    tf.contrib.framework.add_model_variable(weights)
    
    input_shape = inputs.get_shape().as_list()
    batch_size = input_shape[0]
    depth = input_shape[1]
    height = input_shape[2]
    width = input_shape[3]

    def get_deconv_dim(dim_size, stride_size,pading,kernel):
      if isinstance(dim_size, tf.Tensor):
        sub = tf.subtract(dim_size,1)
        dim_size = tf.multiply(dim_size,sub)
        dim_size = tf.subtract(dim_size, 2*pading)
        dim_size = tf.add(dim_size,kernel)
        
      elif dim_size is not None:
        dim_size  = (dim_size -1)*stride_size - 2*pading + kernel
      return dim_size
   
    pad = 1
    if padding == 'VALID':
      pad = 0
    out_depth = get_deconv_dim(depth, stride,pad,weights.get_shape().as_list()[0])
    out_height = get_deconv_dim(height, stride,pad,weights.get_shape().as_list()[1])
    out_width = get_deconv_dim(width, stride,pad,weights.get_shape().as_list()[2])

    out_shape = [batch_size, out_depth, out_height, out_width, num_outputs]
    outputs = tf.nn.conv3d_transpose(inputs, weights, out_shape,
                                     [1, stride, stride, stride, 1],
                                     padding)

    biases = tf.get_variable('biases',
                               shape=[num_outputs,],
                               dtype=dtype,
                               initializer=tf.constant_initializer(biases),
                               trainable=trainable)
    tf.contrib.framework.add_model_variable(biases)
    outputs = tf.nn.bias_add(outputs, biases)
    
    if activation_fn:
      outputs = activation_fn(outputs)
    return outputs


def model(identities, params, is_training):
  """Model transforming embedding to voxels."""
  del is_training  # Unused
  f_dim = params.f_dim
  with slim.arg_scope(
      [slim.fully_connected, conv3d_transpose]):
    w0 = init_weight("DecoderWeights/Layer1_13824_512_w.txt",[13824,512],"w")
    print(identities.get_shape().as_list())
    h0 = slim.fully_connected(
        identities, 3 * 3 * 3 * f_dim * 8, weights_initializer = tf.constant_initializer(w0), activation_fn=tf.nn.relu)
    b0 = init_weight("DecoderWeights/Layer1_13824_b.txt",[13824],"b")
    b0 = tf.get_variable('db0',shape=[13824], initializer=tf.constant_initializer(b0),trainable=True)
    h0 = tf.nn.bias_add(h0,b0)

    h1 = tf.reshape(h0, [-1, 3, 3, 3, f_dim * 8])
    print(h1.get_shape().as_list())
    w1 = init_weight("DecoderWeights/Layer2_512_256_4_4_4_w.txt",[512,256,4,4,4],"w")
    b1 = init_weight("DecoderWeights/Layer2_256_b.txt",[256],"b")
    h1 = conv3d_transpose(
        h1, f_dim * 4, [4, 4, 4],w1, b1,stride=1, padding= 'VALID',activation_fn=tf.nn.relu)
    print(h1.get_shape().as_list())
    w2 = init_weight("DecoderWeights/Layer3_256_96_5_5_5_w.txt",[256,96,5,5,5],"w")
    b2 = init_weight("DecoderWeights/Layer3_96_b.txt",[96],"b")
    h2 = conv3d_transpose(
        h1, int(f_dim * 3 / 2), [5, 5, 5],w2 , b2, stride=2,padding ='VALID' ,activation_fn=tf.nn.relu)
    print(h2.get_shape().as_list())
    w3 = init_weight("DecoderWeights/Layer4_96_1_6_6_6_w.txt",[96,1,6,6,6],"w")
    b3 = init_weight("DecoderWeights/Layer4_1_b.txt",[1],"b")
    h3 = conv3d_transpose(
        h2, 1, [6, 6, 6], w3,b3, stride=2, padding ='SAME' ,activation_fn=tf.nn.sigmoid)
    print(h3.get_shape().as_list())
  return h3
```

This is error:
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    epsilon=1e-08).minimize(loss, global_step=global_step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 609, in gradients
    % (op.name, i, t_in.shape, in_grad.shape))
ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: decoder/Conv3d_transpose_2/conv3d_transpose.  Input index: 2. Original input shape: (6, 15, 15, 15, 96).  Calculated input gradient shape: (6, 16, 16, 16, 96)

Tf version : 1.4.1

I have 4 layers, 1 fc and 3 conv3d_transpose.

Layer shape as follows:

[6, 512]
[6, 3, 3, 3, 512]
[6, 6, 6, 6, 256]
[6, 15, 15, 15, 96]
[6, 32, 32, 32, 1]

I calculated conv3d_tranpose output shape as follows:
```
 def get_deconv_dim(dim_size, stride_size,pading,kernel):
      if dim_size is not None:
        dim_size  = (dim_size -1)*stride_size - 2*pading + kernel
      return dim_size
   
   pad = 1
   if padding == 'VALID':
     pad = 0
   out_depth = get_deconv_dim(depth, stride,pad,weights.get_shape().as_list()[0])
   out_height = get_deconv_dim(height, stride,pad,weights.get_shape().as_list()[1])
   out_width = get_deconv_dim(width, stride,pad,weights.get_shape().as_list()[2])
   out_shape = [batch_size, out_depth, out_height, out_width, num_outputs]
   outputs = tf.nn.conv3d_transpose(inputs, weights, out_shape,
                                     [1, stride, stride, stride, 1],
                                     padding)
```
In the last conv3d_transpose layer, while its output is calculated as (6,15,15,15,96), input gradient is calculated as (6,16,16,16,96). Therefore, this leads to error.

When i call last conv3d_transpose layer with padding="SAME", it didn't gives error.

edit:

Environment:
Os: Ubuntu 16.04.3 LTS
bazel: N/a
Tensorflow : 1.4.1 via pip install
cuda: 9.0.176
GPU: tesla k40, memory: 12gb
command: I uploaded only erroneous python script, just run "python blabla.py".  If you want, i can upload all python scripts.

**Comment by tensorflowbutler** [comment] 2018-08-31 07:49
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Bedrettin-Cetinkaya** [comment] 2018-08-31 08:11
@tensorflowbutler , sorry for missing information. I updated my post.

**Comment by tensorflowbutler** [comment] 2018-09-16 02:31
Nagging Assignee @rohan100jain: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 13:00
Nagging Assignee @rohan100jain: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-25 12:41
Nagging Assignee @sguada: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-09 18:50
Nagging Assignee @sguada: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-24 18:31
Nagging Assignee @sguada: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wangluyao123456** [comment] 2019-11-21 03:01
> @tensorflowbutler，对不起，所有权信息。我更新了我的帖子。

你好，我想请教一下这个应该怎么改，我也遇到了这种问题，但是我毫无头绪
`
        with tf.variable_scope('Decoder'):
            print('self.masked_v',self.masked_v.get_shape())
            vector_j= tf.reshape(self.masked_v, shape=(cfg.batch_size, 2, 16, 1, 1))
            kernel2 = tf.constant(1.0, shape=[3, 3, 2, 1, 1])  # 反向卷积核
            kernel3 = tf.constant(1.0, shape=[3, 1, 29, 1, 1])  # 反向卷积核
            deconv11 = tf.nn.conv3d_transpose(vector_j, kernel2, output_shape=[cfg.batch_size,3, 16, 18, 1],
                                        strides=[1, 2, 2, 2, 1], padding="SAME")
            print('deconv1',deconv11.get_shape())

            self.decoded= tf.nn.conv3d_transpose(deconv11, kernel3, output_shape=[cfg.batch_size, 9, 32, 32, 1],
                                        strides=[1, 2, 1, 2, 1], padding="SAME")
            print('self.decoded',self.decoded.get_shape())   #self.decoded (20, 9, 32, 32, 1)
`

**Comment by sushreebarsa** [comment] 2021-09-13 17:02
@Bedrettin-Cetinkaya  It looks like you are using an older Version of Tensorflow which is out of support window. Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version (2.6.0) and let us know if the issue still persists? Thanks!

**Closed** 2021-10-03 07:59 UTC
Labels: stat:awaiting response, stat:awaiting tensorflower, type:bug, stalled
