### ISSUE TITLE
How to create an NLP pipeline in Tensorflow 2 in a simple and efficient approach?

### ISSUE THREAD

**Issue by Ceceu** [tensorflow/tensorflow#39684] opened 2020-05-19 14:17 UTC
Using a `TorchText` to create a NLP pipeline is simple as one, two, three:

```python
# 1. indicate the fields and how to tokenizer them:
TEXT = data.Field(
    tokenize=tokenizer.encode,
    batch_first=True,
    fix_length=32
)
LABELS = data.Field()

# 2. bind it to the dataset path
train, val, test = data.TabularDataset.splits(
    path=dataset_path,
    train='train.json',
    validation='val.json',
    test='test.json', 
    format='json',
    fields=[('text', TEXT), ('labels', LABELS)])

# 3. get the train, val and test batches
train_iter, valid_iter, test_iter = data.BucketIterator.splits(
    (train, valid, test), batch_sizes=(16, 256, 256)
)
 
```

This is what you expect from a Deep Learning framework in which you don't need a lot of coding simply to prepare the data for each new project.

Is there anything similar in Tensorflow 2?

**Comment by Saduf2019** [comment] 2020-05-20 04:36
@Ceceu 
Please check these links for reference [link](https://towardsdatascience.com/best-practices-for-nlp-classification-in-tensorflow-2-0-a5a3d43b7b73) [link1](https://cs230.stanford.edu/blog/datapipeline/) [link2](https://stackoverflow.com/questions/59177925/tensorflow-how-to-build-efficient-nlp-pipeline-using-tf-dataset) 

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
As i see you have already raised this on stack over flow i am moving this issue to closed status.

**Closed by Saduf2019** 2020-05-20 04:36 UTC
