### ISSUE TITLE
Tensorflow silently renaming variables on implicitly defined scope

### ISSUE THREAD

**Issue by mgbckr** [tensorflow/tensorflow#19156] opened 2018-05-08 17:13 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.8.0-0-g93bc2e2072 1.8.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**:  N/A
- **GPU model and memory**:  N/A
- **Exact command to reproduce**:
```python
import tensorflow as tf

tf.logging.set_verbosity(tf.logging.DEBUG)

n_input = 5
input = tf.placeholder(tf.float32, (None, n_input), 'input')
output = tf.placeholder(tf.float32, (None, 1), 'output')
check = tf.placeholder(tf.float32, (None, 1), 'check')

with tf.variable_scope("scope1",
                       initializer=tf.random_normal_initializer(mean=0, stddev=1)):
    w = tf.get_variable(name="w", shape=(n_input, 1))
    y_predicted = tf.matmul(input, w)

cost = tf.losses.mean_squared_error(check, y_predicted)
cost = tf.reduce_mean(cost, name="mean_squared_error")

tf.get_default_graph().get_tensor_by_name("mean_squared_error:0")
```

### Describe the problem
When using losses from `tf.losses` various scopes a defined implicitly. For example for `tf.losses.mean_squared_error` the scope `mean_squared_error` is defined. If I now try to define a variable named `mean_squared_error`, e.g., for later showing results in Tensorboard, then I get a `KeyError`:
```
KeyError: "The name 'mean_squared_error:0' refers to a Tensor which does not exist. The operation, 'mean_squared_error', does not exist in the graph."
```
This is due to Tensorflow silently renaming my explicitly defined variable because of the implicitly defined scope (by `tf.losses.mean_squared_error`). This is rather counter intuitive and potentially can easily result in unexpected behavior. I suggest throwing an error or at least printing a warning in such a case.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:00
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory

**Comment by mgbckr** [comment] 2018-05-10 09:05
Hi, I updated the post.

**Comment by alextp** [comment] 2018-05-22 19:54
By "variable" you mean Tensor? Can you post the graph that actually gets generated?

I think, from looking at your code, that everything is working as intended; TensorFlow graphs need to uniquify the operation names somehow, so you specifying a name which conflicts with the name of something else in the graph will cause the name you specified to not actually be used.

**Comment by tensorflowbutler** [comment] 2018-06-10 21:55
Nagging Assignee @alextp: It has been 18 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by alextp** [comment] 2018-06-11 17:13
Closing since it looks to me like it's working as intended. Please reopen with answers to my questions above if I'm wrong.

**Closed by alextp** 2018-06-11 17:13 UTC
