### ISSUE TITLE
Feature request: Add a subclass of seq2seq.Decoder to support regression

### ISSUE THREAD

**Issue by rickyhan** [tensorflow/tensorflow#10815] opened 2017-06-19 07:20 UTC
Currently, seq2seq decoder class only supports classification which uses 1D softmax with embedding. The library is very good for this particular task. However, seq2seq is also extremely useful in regression tasks by replacing embedding with a dense layer.

As of 1.2, the current architecture only allows 1D sequence data by supplying a Dense layer as _embedding_fn to TrainingHelper. Currently, training is working(loss decreases) but I have yet to find a way to decode.

I have tried to modify these following pieces to support 2D regression:
`TrainingHelper`
`BasicDecoder`
`dynamic_decode`
`GreedyEmbeddingHelper`(used during decoding, not working)

I had to change a lot of seq2seq internals, but here is more or less my code:
```python
            self.decoder_cell, self.decoder_initial_state = self.build_decoder_cell()

            # Input projection layer to feed embedded inputs to the cell
            # ** Essential when use_residual=True to match input/output dims
            input_layer = Dense(self.hidden_units, dtype=self.dtype, name='input_projection')

            # Output projection layer to convert cell_outputs to actual values
            output_layer = Dense(self.dimension, name='output_projection')

```
```python

if self.mode == 'train':
    # decoder_inputs_train :: [batch_size , max_time_steps + 1]
    # Decoder inputs having gone through input projection layer
    self.decoder_inputs_proj = input_layer(self.decoder_inputs_train)

    # Helper to feed inputs for training: read inputs from dense ground truth vectors
    training_helper = seq2seq.TrainingHelper(inputs=self.decoder_inputs_proj,
                                       sequence_length=self.decoder_inputs_length_train,
                                       time_major=False,
                                       name='training_helper')

    training_decoder = seq2seq.BasicDecoder(cell=self.decoder_cell,
                                       helper=training_helper,
                                       initial_state=self.decoder_initial_state,
                                       output_layer=output_layer)
                                       #output_layer=None)

    # Maximum decoder time_steps in current batch
    max_decoder_length = tf.reduce_max(self.decoder_inputs_length_train)

    # decoder_outputs_train: BasicDecoderOutput
    #                        namedtuple(rnn_outputs, sample_id)
    # decoder_outputs_train.rnn_output: [batch_size, max_time_step + 1, dimension] if output_time_major=False
    #                                   [max_time_step + 1, batch_size, dimension] if output_time_major=True
    # decoder_outputs_train.sample_id: [batch_size], tf.int32
    (self.decoder_outputs_train, self.decoder_last_state_train,
     self.decoder_outputs_length_train) = (seq2seq.dynamic_decode(
        decoder=training_decoder,
        output_time_major=False,
        impute_finished=True,
        maximum_iterations=max_decoder_length))

    # More efficient to do the projection on the batch-time-concatenated tensor
    # logits_train: [batch_size, max_time_step + 1, dimension]
    self.decoder_logits_train = tf.identity(self.decoder_outputs_train.rnn_output)

    # RMSE
    self.loss = tf.reduce_mean(tf.sqrt(
          tf.abs(tf.subtract(self.decoder_logits_train, self.decoder_targets_train))
        ), axis=2)
    self.loss = tf.reduce_sum(self.loss)

    # Contruct graphs for minimizing loss
    self.init_optimizer()
```
And here is the code for `decoding` and this is where I get all sorts of errors:

```

elif self.mode == 'decode':

    # Start_tokens: [batch_size,] `int32` vector
    start_tokens = tf.ones([self.batch_size, self.dimension], tf.float32) * 0.1337
    end_token = 0.1337

    def project_inputs(inputs):
        print "INPUT SHAPE", inputs.shape
        return input_layer(inputs)

    if not self.use_beamsearch_decode:
        # Helper to feed inputs for greedy decoding: uses the argmax of the output
        decoding_helper = seq2seq.GreedyEmbeddingHelper(start_tokens=start_tokens,
                                                        end_token=end_token,
                                                        embedding=project_inputs)
        # Basic decoder performs greedy decoding at each time step
        print("building greedy decoder..")
        inference_decoder = seq2seq.BasicDecoder(cell=self.decoder_cell,
                                                 helper=decoding_helper,
                                                 initial_state=self.decoder_initial_state,
                                                 output_layer=output_layer)
    # For GreedyDecoder, return
    # decoder_outputs_decode: BasicDecoderOutput instance
    #                         namedtuple(rnn_outputs, sample_id)
    # decoder_outputs_decode.rnn_output: [batch_size, max_time_step, num_decoder_symbols]   if output_time_major=False
    #                                    [max_time_step, batch_size, num_decoder_symbols]   if output_time_major=True
    # decoder_outputs_decode.sample_id: [batch_size, max_time_step], tf.int32       if output_time_major=False
    #                                   [max_time_step, batch_size], tf.int32               if output_time_major=True

    (self.decoder_outputs_decode, self.decoder_last_state_decode,
     self.decoder_outputs_length_decode) = (seq2seq.dynamic_decode(
        decoder=inference_decoder,
        output_time_major=False,
        #impute_finished=True,  # error occurs
        maximum_iterations=self.max_decode_step))

    if not self.use_beamsearch_decode:
        # decoder_outputs_decode.sample_id: [batch_size, max_time_step]
        # Or use argmax to find decoder symbols to emit:
        # self.decoder_pred_decode = tf.argmax(self.decoder_outputs_decode.rnn_output,
        #                                      axis=-1, name='decoder_pred_decode')

        # Here, we use expand_dims to be compatible with the result of the beamsearch decoder
        # decoder_pred_decode: [batch_size, max_time_step, 1] (output_major=False)
        self.decoder_pred_decode = tf.expand_dims(self.decoder_outputs_decode.sample_id, -1)
```

It would be great if someone could sort it out and streamline the process.

**Comment by rickyhan** [comment] 2017-06-19 08:12
[Related paper](http://www.ijcaonline.org/archives/volume143/number11/zaytar-2016-ijca-910497.pdf)

Graph on page 2

**Comment by tatatodd** [comment] 2017-06-20 01:17
@lukaszkaiser might have an opinion on whether this is feasible.

**Comment by lukaszkaiser** [comment] 2017-06-20 02:29
I'm not sure, I'll defer to @ebrevdo to decide on that.

**Comment by ppyht2** [comment] 2017-06-20 14:35
I am also running into this exact issue, a more streamlined approach would be very much appreciated.

**Comment by ebrevdo** [comment] 2017-06-20 16:11
There is already class for this, it's called ScheduledOutputTrainingHelper.  You can get regression by creating this helper with sampling_probability=0 and then putting an l2 loss on the output.  Alternatively you can use a higher sampling probability to get scheduled sampling.  Rui is currently fixing #10736 which should remove any blockers.

We may need a [Regression/Feedback]OutputTrainingHelper which doesn't require training inputs, for inference mode; but for training the current class should be sufficient.

**Comment by rickyhan** [comment] 2017-06-20 17:59
@ebrevdo here is my toy example for decoder. It's still WIP:

```

    enc_inp = tf.placeholder(tf.float32, shape=(batch_size, seq_length_in, input_dim))

    dec_target = tf.placeholder(tf.float32,
        shape=(batch_size, seq_length_out, output_dim))

    with tf.variable_scope("ENCODE"):
        # enc_cells = []
        # for i in range(0, encoder_depth):
        #     with tf.variable_scope('enc_RNN_{}'.format(i)):
        #         cell = tf.contrib.rnn.GRUCell(hidden_dim)  # Or LSTMCell(hidden_dim)
        #         cell = tf.contrib.rnn.DropoutWrapper(cell, output_keep_prob=1.0-dropout)
        #         enc_cells.append(cell)
        # enc_cell = tf.contrib.rnn.MultiRNNCell(enc_cells)
        enc_cell = tf.contrib.rnn.LSTMCell(hidden_dim)

        enc_inp_len = np.array([seq_length_in for _ in range(batch_size)])

        ((encoder_fw_outputs,
          encoder_bw_outputs),
         (encoder_fw_final_state,
          encoder_bw_final_state)) = (
            tf.nn.bidirectional_dynamic_rnn(cell_fw=enc_cell,
                                            cell_bw=enc_cell,
                                            inputs=enc_inp,
                                            sequence_length=enc_inp_len,
                                            dtype=tf.float32)
            )
        encoder_outputs = tf.concat((encoder_fw_outputs, encoder_bw_outputs), 2)

        encoder_final_state_c = tf.concat(
            (encoder_fw_final_state.c, encoder_bw_final_state.c), 1)

        encoder_final_state_h = tf.concat(
            (encoder_fw_final_state.h, encoder_bw_final_state.h), 1)

        encoder_final_state = tf.contrib.rnn.LSTMStateTuple(
            c=encoder_final_state_c,
            h=encoder_final_state_h
        )

    W = tf.Variable(tf.random_uniform([hidden_dim, output_dim], -1, 1), dtype=tf.float32)
    b = tf.Variable(tf.zeros([output_dim]), dtype=tf.float32)
    decoder_lengths = seq_length_out + 10
    dec_inp_initial = tf.zeros([batch_size, hidden_dim], dtype=np.float32, name="GO") # BUG:


    def loop_fn_initial():
        initial_elements_finished = (0 >= decoder_lengths)  # all False at the initial step
        initial_input = dec_inp_initial
        initial_cell_state = encoder_final_state
        initial_cell_output = None
        initial_loop_state = None  # we don't need to pass any additional information
        return (initial_elements_finished,
                initial_input,
                initial_cell_state,
                initial_cell_output,
                initial_loop_state)

    def loop_fn_transition(time, previous_output, previous_state, previous_loop_state):
        def get_next_input():
            output_logits = tf.add(tf.matmul(previous_output, W), b) # time x output_dim
            prediction = tf.argmax(output_logits, axis=1)
            next_input = tf.nn.embedding_lookup(embeddings, prediction)
            return next_input
        elements_finished = (time >= decoder_lengths) # this operation produces boolean tensor of [batch_size]
                                                      # defining if corresponding sequence has ended
        finished = tf.reduce_all(elements_finished) # -> boolean scalar
        input = tf.cond(finished, lambda: dec_inp_initial, lambda: dec_inp_initial)
        state = previous_state
        output = previous_output
        loop_state = None
        return (elements_finished, 
                input,
                state,
                output,
                loop_state)
    def loop_fn(time, previous_output, previous_state, previous_loop_state):
        if previous_state is None:    # time == 0
            assert previous_output is None and previous_state is None
            return loop_fn_initial()
        else:
            return loop_fn_transition(time, previous_output, previous_state, previous_loop_state)


    with tf.variable_scope("DECODE"):
        # dec_cells = []
        # # name="dec_cell_{}".format(i)
        # for i in range(0, decoder_depth):
        #     with tf.variable_scope('dec_RNN_{}'.format(i)):
        #         cell = tf.contrib.rnn.GRUCell(hidden_dim)
        #         cell = tf.contrib.rnn.DropoutWrapper(cell, output_keep_prob=1.0-dropout)
        #         dec_cells.append(cell)
        # dec_cell = tf.contrib.rnn.MultiRNNCell(dec_cells)
        decoder_cell = tf.contrib.rnn.LSTMCell(hidden_dim*2) # BUG:

        decoder_outputs_ta, decoder_final_state, _ = tf.nn.raw_rnn(decoder_cell, loop_fn)
        decoder_outputs = decoder_outputs_ta.stack()




    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        sess.run(init)

        print sess.run(decoder_outputs, feed_dict={
            enc_inp: sample_x,
            dec_target: sample_y
        })
```

**Comment by ebrevdo** [comment] 2017-06-21 00:55
Ricky, is your question about tf.contrib.seq2seq?  Looks like you've rolled
your own

**Comment by ppyht2** [comment] 2017-06-21 08:29
Apologies if this this is a stupid question, I am trying to understand how to use ScheduledOutputTrainingHelper. 

In the function, one of the argument is next_input_layer, which apply the RNN output to create the next input. I am confused as to what input should I feed the layer object to create the instance? 

Below is the toy model I'm currently using. Thanks in advance. 

``` python
n_steps = 14
n_input = 2
n_output = 1
inp_seq_len = out_seq_len = n_steps
layers_stacked_count = 2 
n_hidden = 20

tf.reset_default_graph()
sess = tf.InteractiveSession()

# Placeholders
enc_inp = tf.placeholder(tf.float32, [None, inp_seq_len, n_input], name='encoder_input')
dec_target = tf.placeholder(tf.float32, [None, out_seq_len, n_output], name ='decoder_input')
#dec_targets = [tf.placeholder(tf.float32, [None, n_output]) for i in range(out_seq_len)]

target_length = tf.placeholder(tf.int32, [None], name='target_seq_length')
keep_prob = tf.placeholder(tf.float32, [], name='dropout_keep_prob')
sample_rate = tf.placeholder(tf.float32, [], name = 'sample_rate')

# ---- Encoder
enc_cells = [tf.contrib.rnn.DropoutWrapper(tf.contrib.rnn.BasicLSTMCell(n_hidden), output_keep_prob=keep_prob) for i in range(layers_stacked_count)]
enc_stk_cell = tf.contrib.rnn.MultiRNNCell(enc_cells)

encoded_outputs, encoded_states = tf.nn.dynamic_rnn(enc_stk_cell, enc_inp, dtype=tf.float32)

# ---- Decoder
dec_cells = [tf.contrib.rnn.DropoutWrapper(tf.contrib.rnn.BasicLSTMCell(n_hidden), output_keep_prob=keep_prob) for i in range(layers_stacked_count)]
dec_stk_cell = tf.contrib.rnn.MultiRNNCell(dec_cells)

#old helper = tf.contrib.seq2seq.TrainingHelper(expect, expect_length) # Old
helper = tf.contrib.seq2seq.ScheduledOutputTrainingHelper(dec_target, target_length, sample_rate,
                                                         next_input_layer = tf.layers.dense(encoded_states, n_output))

decoder = tf.contrib.seq2seq.BasicDecoder(cell=dec_stk_cell, helper=helper, initial_state=encoded_states)

decoder_outputs, final_decoder_state = tf.contrib.seq2seq.dynamic_decode(decoder)
decoder_logits = decoder_outputs.rnn_output

h = tf.contrib.layers.fully_connected(decoder_logits, n_output)

diff = tf.squared_difference(h, expect)
batch_loss = tf.reduce_sum(diff, axis=1)
loss = tf.reduce_mean(batch_loss)

optimiser = tf.train.AdamOptimizer(1e-3)
training_op = optimiser.minimize(loss)
```

**Comment by ggaemo** [comment] 2017-08-31 06:06
@ebrevdo 
hello, I noticed something strange about your comment on ScheduledOutputTrainingHelper. Shouldn't the sampling_probability be 1 during the inference phase? The API documentation says that the sampling_probability is the probability of sampling from the outputs instead of reading directly from the inputs.

**Comment by chococig** [comment] 2017-08-31 09:26
@ebrevdo 
hello, I also have a question about ScheduledOutputTrainingHelper. I'm currently doing regression using ScheduledOutputTrainingHelper. But, in the inference stage, is it right to set the sampling probability to 1 and use an arbitrary input? For the classification case, GreedyEmbeddingHelper can be used, but for regression there is no Greedy'Output'Helper.

* sampling_probability: the probability of sampling from the outputs instead of reading directly from the inputs.

my decoder_input is like Start_value(zeros) + y_target[:-1]
'''
x_1 = tf.placeholder(dtype=tf.float32, shape=[None, n_step, n_1])
x_2 = tf.placeholder(dtype=tf.float32, shape=[None, n_step, n_2])
y_target = tf.placeholder(dtype=tf.float32, shape=[None, n_step, 1])

phase = tf.placeholder(tf.bool) # if True: training / if False: inference
length = tf.placeholder(dtype=tf.int32, shape=[None,])
tf_batch_size = tf.placeholder(dtype=tf.int32, shape = [])

encoder_input = tf.concat([x_1,x_2], axis=2)

# like Start_token + target[:-1]
decoder_input = tf.concat([tf.fill([tf_batch_size,1,1], 0.0), # Start by Zeros
                           y_target[:,:-1,:]], #targets[:-1]
                           axis=1)
'''
then my decoder is like this

```
def decoder(encoder_output, decoder_initial_state, decoder_dimension, phase):    
    cell = LayerNormBasicLSTMCell(decoder_dimension)
    
    cell = AttentionWrapper(cell, 
                            attention_mechanism=BahdanauAttention(decoder_dimension, encoder_output), 
                            initial_cell_state = (LSTMStateTuple(decoder_initial_state, decoder_initial_state)),
                            alignment_history = True) 

    output_cell = OutputProjectionWrapper(cell, output_size=1)
    
    sampling_prob = tf.cond(phase,
                            
                            #training
                            lambda :tf.constant(1.0) - tf.train.inverse_time_decay(learning_rate=1.0,
                                                                                   global_step=global_step,
                                                                                   decay_steps=1000,
                                                                                   decay_rate=0.9),
                            
                            #inference
                            lambda : tf.constant(1.0))

    helper = ScheduledOutputTrainingHelper(decoder_input, 
                                           sequence_length=length, 
                                           sampling_probability=sampling_prob)    
    
    my_decoder = BasicDecoder(cell=output_cell, 
                              helper=helper, 
                              initial_state=output_cell.zero_state(batch_size=tf_batch_size, dtype=tf.float32))
    
    final_outputs, final_state, final_sequence_length = dynamic_decode(my_decoder, maximum_iterations=24)
        
    return final_outputs.rnn_output
...

In the inference stage, if i feed zero values(or any arbitrary value) to y_target and set sampling_probabilty to 1.0, i think result has to be same as the case when I feed ground truth values to y_target, because sampling_prob=1 means model always sample from the previous outputs, not ground truth value. So what I'm saying is that if the sampling_probability is set to 1.0, is should not matter what value I feed to y_target.

However, result is slightly different like below(but almost same)
![image](https://user-images.githubusercontent.com/31504573/29915809-eab1f3ee-8e77-11e7-8a94-006ec10222ae.png)

is this a precision(float32) issue of python? or problem of ScheduledOutputTrainingHelper?

**Comment by ebrevdo** [comment] 2017-09-06 03:23
I think it's just setting the seed to get consistent samples.  Your
randomness is different between the two runs.

Adam Roberts added two new inference helpers for this exact case, but they
are only in the nightlies, not in tf 1.3.  look for InferenceHelper, which
you can use to implement sample-only decoding.

**Comment by wangshang19911011** [comment] 2017-09-20 03:11
Hi, I'm doing similar decoder, but the decoder inputs is conditioned by the encoder final hidden states (context vector), [Related Paper](https://arxiv.org/pdf/1702.05538.pdf) see picture a in page 3. The decoder is trying to fully inference during training with feeding previous outputs and context vector as inputs at each step.

`class RNNEncoder_Decoder(object):

    def __init__(self,input_dim,
                 context_dim,output_dim,hidden_dim,
                 layers_stacked_count,learning_rate):
        
        self.graph = tf.get_default_graph()
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.context_dim = context_dim
        self.hidden_dim = hidden_dim
        self.layers_stacked_count = layers_stacked_count
        self.learning_rate = learning_rate
        self.sampling_probability = tf.constant(dtype=tf.float32,value=1.0)
        
        # [batch_size,sequence_length,input_dimension]
        self.enc_inp = tf.placeholder(tf.float32, [None,None,self.input_dim], name='encoder_inputs')
        self.expected_out = tf.placeholder(tf.float32, [None,None,self.input_dim], name='expected_outs')
        # fullly inference during trianing
        self.dec_inp = tf.zeros_like(self.expected_out,dtype=tf.float32,name='decoder_inputs')
                
        seq_length = tf.reduce_sum(tf.sign(tf.reduce_max(tf.abs(self.enc_inp), 2)), 1)
        self.seq_length = tf.cast(seq_length, tf.int32)
        
        with tf.variable_scope('RNNEncoderDecoder'):
            with tf.variable_scope("Enocder") as encoder_varscope:
                # create encoder LSTM cell
                encoder_cells = []
                for i in range(self.layers_stacked_count):
                    with tf.variable_scope('EncoderCell_{}'.format(i)):
                        encoder_cells.append(tf.nn.rnn_cell.LSTMCell(self.hidden_dim,
                                                             use_peepholes=True))
                self.encoder_cell = tf.nn.rnn_cell.MultiRNNCell(encoder_cells)

                # ruuning dynamic rnn encoder                
                _, enc_state = tf.nn.dynamic_rnn(cell = self.encoder_cell,
                                                 initial_state=None,
                                                 dtype=tf.float32,
                                                 inputs = self.enc_inp,
                                                 sequence_length = self.seq_length
                                                )
 
                # extract top layer hidden state as feature representation
                self.context_vector = enc_state[-1].h
                
                cell_state0 = tf.zeros_like(enc_state[0].c,dtype=tf.float32)
                hidden_state0 = tf.zeros_like(enc_state[0].h,dtype=tf.float32)

                dec_init_state = (enc_state[1], # pass the top layer state of enocder to the bottom layer of decoder
                                  tf.nn.rnn_cell.LSTMStateTuple(cell_state0, hidden_state0))
                
                # condition extracted features on decoder inputs
                # with a shape that matches decoder inputs in all but (potentially) the final dimension. 
                # tile context vector from [batch_size,context_dim] to [batch_size,decoder_sequence_length,context_dim]
                context_vector_shape = tf.shape(self.context_vector)
                context_vector_reshaped = tf.reshape(self.context_vector, 
                                                     [context_vector_shape[0], 1, context_vector_shape[1]]
                                                    )
                enc_inp_shape = tf.shape(self.enc_inp)
                self.auxiliary_inputs = tf.tile(context_vector_reshaped,
                                           multiples=[1,enc_inp_shape[1],1]
                                          )
                
            with tf.variable_scope("Deocder") as decoder_varscope:
                # create decoder LSTM cell
                decoder_cells = []
                for i in range(self.layers_stacked_count):
                    with tf.variable_scope('DecoderCell_{}'.format(i)):
                        decoder_cells.append(tf.nn.rnn_cell.LSTMCell(self.hidden_dim,
                                                             use_peepholes=True))
                self.decoder_cell = tf.nn.rnn_cell.MultiRNNCell(decoder_cells)

                dec_out_dense = Dense(units = self.output_dim,
                                      activation = None,
                                      use_bias = False,
                                      kernel_initializer = tf.truncated_normal_initializer(
                                          dtype=tf.float32,
                                          stddev = 1.0 / math.sqrt(float(self.hidden_dim))
                                      ),
                                      name = 'dec_outp_linear_projection'
                                     )
                
                training_helper = tf.contrib.seq2seq.ScheduledOutputTrainingHelper(
                    inputs = self.dec_inp,
                    sequence_length = self.seq_length,
                    auxiliary_inputs = self.auxiliary_inputs, # condtional on inputs
                    sampling_probability = 1.0, # for fullly inference
                    name = 'feeding_conditional_input'
                )
                
                decoder = tf.contrib.seq2seq.BasicDecoder(
                    cell = self.decoder_cell,
                    helper = training_helper,
                    initial_state = dec_init_state,
                    output_layer = dec_out_dense
                )
                
                outputs, _ , final_seq_lengths = tf.contrib.seq2seq.dynamic_decode(decoder=decoder,
                                                                                   impute_finished = True
                                                                                  )
            self.outputs = outputs
            
    ### optimize loss part
    
    def get_decoder_prediction(self,X,session):
        feed_dict = {
            self.enc_inp:X
        }
        feed_dict.update({self.expected_out:X})
        run = [self.outputs]
        return session.run(run,feed_dict=feed_dict)
RNN_test = RNNEncoder_Decoder(input_dim=1,context_dim=32,output_dim=1,hidden_dim=32,layers_stacked_count=2,learning_rate=0.01)`

Without "auxiliary_inputs = self.auxiliary_inputs", it running successfully,
but with auxiliary_inputs = self.auxiliary_inputs
And I got following:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-02522a01f0d8> in <module>()
      9                           hidden_dim=hidden_dim,
     10                           layers_stacked_count=layers_stacked_count,
---> 11                           learning_rate=learning_rate
     12                          )

<ipython-input-2-86494b8d99fa> in __init__(self, input_dim, context_dim, output_dim, hidden_dim, layers_stacked_count, learning_rate)
     98 
     99                 outputs, _ , final_seq_lengths = tf.contrib.seq2seq.dynamic_decode(decoder=decoder,
--> 100                                                                                    impute_finished = True
    101                                                                                   )
    102             self.outputs = outputs

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py in dynamic_decode(decoder, output_time_major, impute_finished, maximum_iterations, parallel_iterations, swap_memory, scope)
    284         ],
    285         parallel_iterations=parallel_iterations,
--> 286         swap_memory=swap_memory)
    287 
    288     final_outputs_ta = res[1]

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py in while_loop(cond, body, loop_vars, shape_invariants, parallel_iterations, back_prop, swap_memory, name)
   2773     context = WhileContext(parallel_iterations, back_prop, swap_memory, name)
   2774     ops.add_to_collection(ops.GraphKeys.WHILE_CONTEXT, context)
-> 2775     result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
   2776     return result
   2777 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py in BuildLoop(self, pred, body, loop_vars, shape_invariants)
   2602       self.Enter()
   2603       original_body_result, exit_vars = self._BuildLoop(
-> 2604           pred, body, original_loop_vars, loop_vars, shape_invariants)
   2605     finally:
   2606       self.Exit()

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py in _BuildLoop(self, pred, body, original_loop_vars, loop_vars, shape_invariants)
   2552         structure=original_loop_vars,
   2553         flat_sequence=vars_for_body_with_tensor_arrays)
-> 2554     body_result = body(*packed_vars_for_body)
   2555     if not nest.is_sequence(body_result):
   2556       body_result = [body_result]

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py in body(time, outputs_ta, state, inputs, finished, sequence_lengths)
    232       """
    233       (next_outputs, decoder_state, next_inputs,
--> 234        decoder_finished) = decoder.step(time, inputs, state)
    235       next_finished = math_ops.logical_or(decoder_finished, finished)
    236       if maximum_iterations is not None:

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py in step(self, time, inputs, state, name)
    137     """
    138     with ops.name_scope(name, "BasicDecoderStep", (time, inputs, state)):
--> 139       cell_outputs, cell_state = self._cell(inputs, state)
    140       if self._output_layer is not None:
    141         cell_outputs = self._output_layer(cell_outputs)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py in __call__(self, inputs, state, scope)
    178       with vs.variable_scope(vs.get_variable_scope(),
    179                              custom_getter=self._rnn_get_variable):
--> 180         return super(RNNCell, self).__call__(inputs, state)
    181 
    182   def _rnn_get_variable(self, getter, *args, **kwargs):

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/layers/base.py in __call__(self, inputs, *args, **kwargs)
    448         # Check input assumptions set after layer building, e.g. input shape.
    449         self._assert_input_compatibility(inputs)
--> 450         outputs = self.call(inputs, *args, **kwargs)
    451 
    452         # Apply activity regularization.

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py in call(self, inputs, state)
    936                                       [-1, cell.state_size])
    937           cur_state_pos += cell.state_size
--> 938         cur_inp, new_state = cell(cur_inp, cur_state)
    939         new_states.append(new_state)
    940 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py in __call__(self, inputs, state, scope)
    178       with vs.variable_scope(vs.get_variable_scope(),
    179                              custom_getter=self._rnn_get_variable):
--> 180         return super(RNNCell, self).__call__(inputs, state)
    181 
    182   def _rnn_get_variable(self, getter, *args, **kwargs):

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/layers/base.py in __call__(self, inputs, *args, **kwargs)
    448         # Check input assumptions set after layer building, e.g. input shape.
    449         self._assert_input_compatibility(inputs)
--> 450         outputs = self.call(inputs, *args, **kwargs)
    451 
    452         # Apply activity regularization.

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py in call(self, inputs, state)
    554     input_size = inputs.get_shape().with_rank(2)[1]
    555     if input_size.value is None:
--> 556       raise ValueError("Could not infer input size from inputs.get_shape()[-1]")
    557     scope = vs.get_variable_scope()
    558     with vs.variable_scope(scope, initializer=self._initializer) as unit_scope:

ValueError: Could not infer input size from inputs.get_shape()[-1]`

Could anyone help me with:
Is this a correct way to condition the last hidden state of encoder on the inputs of decoder?
and why the inputs of decoder become None after I feed the auxiliary_inputs as the error?

**Comment by tensorflowbutler** [comment] 2018-01-04 19:22
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by ebrevdo** [comment] 2018-01-04 22:20
At inference time, there is now a `InferenceHelper` class to which you provide your sampling function, end_function, and an optional `next_inputs` function.  That should allow you to avoid having to use the scheduled output helper.

**Comment by ebrevdo** [comment] 2018-01-04 22:21
@ggaemo ^^ that should help you.

**Comment by takotab** [comment] 2018-01-11 16:12
Thank you this seems to solve the problem. Is there some example code that I could use to use this? Because I can not just use it as a helper function, can I?

**Comment by tensorflowbutler** [comment] 2018-01-23 23:07
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by fritzfitzpatrick** [comment] 2018-01-24 21:34
Has someone managed to get the new InferenceHelper to work with floating point regression tasks?
I am feeding the encoder a tensor [batch, 100 time steps, 4 features], decoder input and decoder expected output are of shape [batch, 10 time steps, 1 feature]. Training works nicely with the TrainingHelper and converges to an okay loss, but I am stuck with getting the inference part to work. The data itself is being fed by using tf's generators.

**Comment by tatatodd** [comment] 2018-01-25 01:52
@ebrevdo perhaps you can summarize the state of this issue?  I.e. should it be closed, or are there remaining tasks to complete?

**Comment by ebrevdo** [comment] 2018-01-25 02:38
I think we can close this, InferenceHelper essentially solved the problem.  For remaining how-do-i-do-X type questions, stackoverflow is a better venue.

**Closed by ebrevdo** 2018-01-25 02:38 UTC
Labels: stat:awaiting tensorflower
