### ISSUE TITLE
Bazel problem when using Tensorflow as an external dependency.

### ISSUE THREAD

**Issue by raraujosc** [tensorflow/tensorflow#6706] opened 2017-01-07 00:31 UTC
When using the HEAD version of Tensorflow as an external Bazel dependency (like tensorflow_serving does), we run into an issue in the line:

`load("@//third_party:common.bzl", "template_rule")`

inside

`tensorflow/third_party/jpeg/jpeg.BUILD`

That line assumes that Tensorflow is the main repository. But when Tensorflow is included in another project the main repository is the main project so that common.bzl file is not found. I think that line needs to read:

`load("@org_tensorflow//third_party:common.bzl", "template_rule")`

**Comment by yaroslavvb** [comment] 2017-01-07 04:53
So a straightforward fix [fails](https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu/3179/console) with

```
INFO: Loading package: @png_archive//
ERROR: /workspace/tensorflow/core/platform/default/build_config/BUILD:108:1: error loading package '@jpeg//': Encountered error while reading extension file 'third_party/common.bzl': no such package '@org_tensorflow//third_party': error loading package 'external': The repository named 'org_tensorflow' could not be resolved and referenced by '//tensorflow/core/platform/default/build_config:jpeg'.

```

**Comment by jart** [comment] 2017-01-08 03:51
It's not possible to use TensorFlow as an external dependency yet due to https://github.com/bazelbuild/bazel/issues/1248

**Comment by raraujosc** [comment] 2017-01-08 05:08
Well, tensorflow_serving certainly uses it right now, but synced to a slightly older version that didn't have this issue. We also do it for an internal project at Snapchat.

I think there should be workaround in Tensorflow while Bazel doesn't fix that issue. The problem was introduced recently in Tensorflow.

**Comment by martinwicke** [comment] 2017-01-08 05:51
Do you know what change caused the issue?

**Comment by jart** [comment] 2017-01-08 05:56
Your problem most likely originated in https://github.com/tensorflow/tensorflow/pull/6462. I wasn't aware that other Bazel projects were referencing TensorFlow as an external dependency. So it seems fixing this should be much higher on our list of priorities.

As a workaround, what we can do is add an `omit_jpeg` parameter to [tf_workspace](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L39) similar to what Closure Rules [does](https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl). Then you could copy jpeg.BUILD into your codebase, replace `@//` with `@org_tensorflow//` and then declare the new_http_archive for jpeg repository yourself. That's the best workaround that I can think of at the moment that doesn't involve patching Bazel.

If you're willing to use a patched Bazel, I can take a peak into the codebase and see if I can fix the issue referenced above in the next few days.

**Comment by jart** [comment] 2017-01-08 05:56
This is a bug that's actually been bugging me for the better part of a year. So I'd really love to see it solved.

**Comment by jart** [comment] 2017-01-08 05:58
We can also do what @gunan is proposing (https://github.com/tensorflow/tensorflow/pull/6710#issuecomment-271129858) and rollback the change.

**Comment by raraujosc** [comment] 2017-01-19 17:38
Can you please rollback the breaking change until Bazel is fixed? Today the nasm library URL broke and there is no commit that both has all the working urls and a working BUILD rule for jpeg.

**Comment by martinwicke** [comment] 2017-01-19 17:45
@jart let's roll this back so we stop breaking tensorflow/serving in particular. @damienmg told me the fix for this should be in bazel 0.4.4, so hopefully we can re-enable this soon.

**Comment by gunan** [comment] 2017-01-20 00:10
https://github.com/tensorflow/tensorflow/pull/6958
This PR pushed out our workarounds we implemented internally with @damienmg's help.
@kirilg confirmed that the workarounds fixed servo's problems.

@raraujosc could you try syncing to head and retry?

**Comment by raraujosc** [comment] 2017-01-20 23:13
I've verified that using the HEAD version of tensorflow and passing extra arguments to tf_workspace now allows me to add tensorflow as an external dependency. Thanks!

**Comment by gunan** [comment] 2017-01-20 23:42
Then i think we can close this issue for now.

**Comment by jart** [comment] 2017-02-01 18:12
Are we sure this is fixed? As far as I can tell, running `./configure` is still mandatory, so I'm not sure how TensorFlow could be used as an external dependency.

**Comment by gunan** [comment] 2017-02-01 22:07
What this issue refers to should be fixed.
But you are right, I am not sure how the options set by `configure` are handled.

@kirilg @raraujosc @nealwu how do you handle `configure` script when depending on tensorflow as an external dependency?
Do you simply default to GPU? Or create your own configure script?

**Comment by raraujosc** [comment] 2017-02-01 22:10
Yes, this issue is fixed but is not in 1.0 release. Can you please cherrypick it into 1.0? Thanks.

**Comment by kirilg** [comment] 2017-02-01 22:16
TensorFlow serving requires you to run ./configure from within the TensorFlow directory. It would be great if we could somehow depend on TF as a workspace target and configure it with some defaults, but I agree it's a different issue and this one is resolved (though may need to be cherrypicked into 1.0 as Robson mentioned).

**Comment by damienmg** [comment] 2017-02-01 22:25
FWIW a bit update on Bazel side:

We released 0.4.4 that should remove the need for the @%s// trick (to be verified).

The change for removing need from ./configure as a separate step are still in-flight: see https://cr.bazel.build/8218 and its parent, should be in next Bazel release.

Once those change are in the Bazel release, we can update TF configure script to be only an user interface that set the good environment variable and just call `bazel fetch //...` at the end.

**Comment by martinwicke** [comment] 2017-04-14 18:11
I believe this is fixed now. @girving, you have a project depending on TF using workspace... does everything work now?

**Comment by girving** [comment] 2017-04-14 18:15
Yes, everything should work now (the repo is https://github.com/tensorflow/deepmath).  I haven't synced in the past little while, so it's possible other bugs have surfaced since then (there are no continuous tests for this stuff).

**Comment by martinwicke** [comment] 2017-04-14 18:24
Thanks. I'll close this issue then. An integration test would indeed be nice.

**Closed by martinwicke** 2017-04-14 18:24 UTC
Labels: type:build/install

**Comment by girving** [comment] 2017-04-14 18:30
For posterity, this was the commit that fixed my issue: https://github.com/tensorflow/tensorflow/commit/c699e5fa03b1f01913636de620aae5e550e58d40.

**Comment by raraujosc** [comment] 2017-04-14 18:32
Is there a bug to track the being able to include tensorflow in your project without having to run ./configure?

**Comment by martinwicke** [comment] 2017-04-14 18:38
I don't think we have an issue for that, but we're working on it. You can
see that we've moved some code in configure to just modifying --action_env
already. Once that's all it does, you don't have to run it any more. Still
WIP.

**Comment by fferroni** [comment] 2017-10-19 15:32
Any update on this?

**Comment by gunan** [comment] 2017-10-19 17:27
At the moment, you can depend on TF the same way tensorflow/serving github project is depending.
We are working on making things better, but it is taking time.

**Comment by fferroni** [comment] 2017-10-19 18:01
Thanks. Regarding this I have a few questions:

1. If you have a new_http_archive which can be Tensorflow git .zip, rather than using a local_archive how do you run ./configure ? Should I maybe write a gen_rule?

2. What is io_bazel_rules_closure within the top WORKSPACE file in serving?

I also tried pre-compiling separately tensorflow_cc and creating a include and lib folder, but I some issues including Eigen, which has a BUILD file which calls some other Tensorflow stuff...

**Comment by raraujosc** [comment] 2017-10-19 18:14
I haven't tried, but I think the easiest way to use tensorflow without ./configure right now would be:
1 - fork it
2 - run ./configure
3 - add the 3 generated files to your repo
4 - depend on the forked repo

**Comment by girving** [comment] 2017-11-07 20:59
@martinwicke Didn't you say configure wasn't necessary, or was that rerunning configure?

**Comment by martinwicke** [comment] 2017-11-07 21:56
@gunan, it shouldn't be, is it still?

**Comment by gunan** [comment] 2017-11-07 21:58
Unfortunately it is, still.
@case540 has volunteered and working towards making configure script completely optional.
He can report on his progress.
