### ISSUE TITLE
miss file after install tensorflow

### ISSUE THREAD

**Issue by MisayaZ** [tensorflow/tensorflow#1295] opened 2016-02-26 08:16 UTC
After installing tensorflow, I found only one tensorflow folder in the path tensorflow/inlcude. In fact, it shoud consist of many other folders such as third_party, google, Eigen and so on. I don't known the reason why I could not find these folders. The way which I used to install tensorflow is "sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl"

Thanks

**Comment by vrv** [comment] 2016-02-26 17:57
Can you explain what you want to do with these files?

It's possible this is a duplicate of https://github.com/tensorflow/tensorflow/issues/720: we don't yet have a devel package that installs all of the headers -- the pip package just distributes the python interface and C++ runtime, not the code to do development on it.  You currently have to integrate with bazel and our github tree to do development, but we're hoping to get #720 resolved eventually to make it easier.

**Comment by MisayaZ** [comment] 2016-02-27 01:18
@vrv, I need these files when I was adding a new Op to tensorflow with TensorFlow binary installation. Some files need heads in the path like /third_party/.., but I can not find third_party anywhere. I saw these third_party folders in others tensorflow/inlcude path, howerver, they are not in mine. As a result. when I used g++ to compile it, it told me that it could not find the files.

Thanks

**Comment by vrv** [comment] 2016-02-27 04:54
Gotcha -- yes I think this is related to https://github.com/tensorflow/tensorflow/issues/1270 -- we have a fix to the pip package installation to make these available.  Our test nodes are down for the weekend so we'll push on Monday.  Let's take discussion to #1270.

**Closed** 2016-02-27 04:54 UTC
