### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by DevDaring** [tensorflow/tensorflow#24562] opened 2018-12-25 13:46 UTC
I am new to tensorflow.I have installed tensorflow without GPU as my machine won't support gpu version.
I have installed it in portable winpython.

![image](https://user-images.githubusercontent.com/46132760/50423282-63351900-0879-11e9-9d74-4753a482e0c0.png)

Here is my stack trace

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.6\helpers\pydev\pydev_monkey_qt.py", line 71, in patched_import
    return original_import(name, *args, **kwargs)
  File "D:\Life_In_IEM\Project\Predicting_Riot\Mine_Data\WPy-3670\python-3.6.7.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "D:\Life_In_IEM\Project\Predicting_Riot\Mine_Data\WPy-3670\python-3.6.7.amd64\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\Life_In_IEM\Project\Predicting_Riot\Mine_Data\WPy-3670\python-3.6.7.amd64\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "D:\Life_In_IEM\Project\Predicting_Riot\Mine_Data\WPy-3670\python-3.6.7.amd64\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by jvishnuvardhan** [comment] 2018-12-27 23:02
Hi @DevDaring, as it is not clear to find the root-cause of the issue, could you fill the following build/installation template.  Please report the installation process and commands used.  Here is the [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md).

**Comment by tensorflowbutler** [comment] 2019-01-11 18:57
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by DevDaring** [comment] 2019-01-12 02:10
Hello Team,
Thanks for your cooperation.
I found the root cause of the issue.
I was using portable python package.I installed tensorflow in that package.It created a long path of some files that same path was replicated in local cache.Due to long path name in cache,it was not properly created hence the issue occurred.
I just put my package outside of folder,directly in drive and it worked.You can close the ticket.

**Comment by jvishnuvardhan** [comment] 2019-01-14 18:17
@DevDaring Great! I am happy that you found the root cause of the issue. I am closing this issue.

**Closed by jvishnuvardhan** 2019-01-14 18:17 UTC
Labels: type:build/install
