### ISSUE TITLE
tensorflow.keras Dense layers complain if the input is a sparse Input layer.

### ISSUE THREAD

**Issue by JamesGlooTeam** [tensorflow/tensorflow#23748] opened 2018-11-14 16:19 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes.
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
OSX Mojave 10.14.1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
na
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
1.10.0 (v1.10.0-rc1-19-g656e7a2b34)
- Python version:
3.5
- Bazel version (if compiling from source):
NA
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
See below, which I ran on a OSX Mojave Macbook Pro (Early 2015), ipython running python 3.5, tensorflow 1.10.0:

```
In [1]: from tensorflow.keras.models import Model
//anaconda/envs/dssm/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)

In [2]: from tensorflow.keras.layers import Input, Dense

In [3]: i = Input((4,), sparse=True)

In [4]: d = Dense(4)(i)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-0fb73bda26dc> in <module>
----> 1 d = Dense(4)(i)

//anaconda/envs/dssm/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    718
    719         # Check input assumptions set before layer building, e.g. input rank.
--> 720         self._assert_input_compatibility(inputs)
    721         if input_list and self._dtype is None:
    722           try:

//anaconda/envs/dssm/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py in _assert_input_compatibility(self, inputs)
   1408           spec.min_ndim is not None or
   1409           spec.max_ndim is not None):
-> 1410         if x.shape.ndims is None:
   1411           raise ValueError('Input ' + str(input_index) + ' of layer ' +
   1412                            self.name + ' is incompatible with the layer: '

AttributeError: 'SparseTensor' object has no attribute 'shape'
```

**Describe the expected behavior**

If I were using normal Keras, I'd expect no errors trying to do the above and for the model to compile subsequently without issue.

**Code to reproduce the issue**
See the code in my snippet above.

**Other info / logs**

**Comment by karmel** [comment] 2018-12-03 21:33
@omalleyt12 -- I recall you worked on something similar recently; can you comment on what is expected here?

Note that in 1.12 the above gives a different error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-0347ad7938f4> in <module>()
      2 from tensorflow.keras.layers import Input, Dense
      3 i = Input(shape=(4,), sparse=True)
----> 4 d = Dense(4)(i)

google3/third_party/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    532       if not self.built:
    533         # Build layer if applicable (if the `build` method has been overridden).
--> 534         self._maybe_build(inputs)
    535         # We must set self.built since user defined build functions are not
    536         # constrained to set self.built.

google3/third_party/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   1592     # Only call `build` if the user has manually overridden the build method.
   1593     if not hasattr(self.build, '_is_default'):
-> 1594       self.build(input_shapes)
   1595 
   1596 

google3/third_party/tensorflow/python/keras/layers/core.py in build(self, input_shape)
    928     input_shape = tensor_shape.TensorShape(input_shape)
    929     if tensor_shape.dimension_value(input_shape[-1]) is None:
--> 930       raise ValueError('The last dimension of the inputs to `Dense` '
    931                        'should be defined. Found `None`.')
    932     last_dim = tensor_shape.dimension_value(input_shape[-1])

ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
```

**Comment by yongtang** [comment] 2018-12-03 21:59
@karmel @omalleyt12 I looked into this issue last week. There are several things that need to be fixed. 
One is that sparse.placeholder could not recognize `(None, 4)`. It will always converts to `(None, None)` so that the error of:
```
ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
```

I created a PR #24048 to fix the above shape inforamtion issue first.

There might be some other places that need to be fixed to make @JamesGlooTeam example work though.

(Note: as pointed out by @omalleyt12, the error is based in 1.12 and is different from the original error posted by @JamesGlooTeam )

**Comment by omalleyt12** [comment] 2018-12-03 22:12
This is because for SparseTensors, the `shape` is actually a Tensor. Tensors can't have `None` values.

You can get around this on the `Input` layer by defining your `batch_size`:

```python
x = keras.Input(batch_size=10, shape=(4,), sparse=True)
```
However, `Dense` layers (and most layers in general it seems) don't support sparse inputs, so you would need to subclass Layer in order to call `tf.sparse.sparse_dense_matmul` on your inputs, or create a Lambda layer to convert your sparse inputs to dense.

**Comment by omalleyt12** [comment] 2018-12-03 22:14
Ideally, the `shape` of a `SparseTensor` would probably be a `TensorShape`, but I think that would be a pretty substantial rewrite of a lot of the sparse ops in order to allow `None` values to flow through

**Comment by yongtang** [comment] 2018-12-03 22:55
@omalleyt12 The PR #24048 propose to convert `(None, 4)` to `(-1, 4)` for the shape tensor then the information could be preserved without making drastic changes.

**Comment by baslia** [comment] 2019-03-04 17:52
Hi,
I got the same issue, if the input is sparse then even when I apply the Dense layer I got an error.
That's too bad because to train a neural network, specifying sparse=True in the input layer makes the learning phase 5 times faster ...

Anyone has a solution for that ?

Thanks a lot.

**Comment by heydatatalks** [comment] 2019-03-21 02:43
> @omalleyt12 -- I recall you worked on something similar recently; can you comment on what is expected here?
> 
> Note that in 1.12 the above gives a different error:
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-4-0347ad7938f4> in <module>()
>       2 from tensorflow.keras.layers import Input, Dense
>       3 i = Input(shape=(4,), sparse=True)
> ----> 4 d = Dense(4)(i)
> 
> google3/third_party/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
>     532       if not self.built:
>     533         # Build layer if applicable (if the `build` method has been overridden).
> --> 534         self._maybe_build(inputs)
>     535         # We must set self.built since user defined build functions are not
>     536         # constrained to set self.built.
> 
> google3/third_party/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
>    1592     # Only call `build` if the user has manually overridden the build method.
>    1593     if not hasattr(self.build, '_is_default'):
> -> 1594       self.build(input_shapes)
>    1595 
>    1596 
> 
> google3/third_party/tensorflow/python/keras/layers/core.py in build(self, input_shape)
>     928     input_shape = tensor_shape.TensorShape(input_shape)
>     929     if tensor_shape.dimension_value(input_shape[-1]) is None:
> --> 930       raise ValueError('The last dimension of the inputs to `Dense` '
>     931                        'should be defined. Found `None`.')
>     932     last_dim = tensor_shape.dimension_value(input_shape[-1])
> 
> ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.
> ```

i got the same error in tf1.13. Anyones has a quick local fix solution? 
Thanks a lot!

**Comment by omalleyt12** [comment] 2019-03-21 17:27
SparseTensors aren't supported in Dense layer currently, although this is something we are considering. You can implement a custom layer that calls `tf.sparse.sparse_dense_matmul` on your SparseTensor

**Comment by Hoeze** [comment] 2019-04-25 14:09
@omalleyt12 Is there some progress on this issue?

I'd like to build a large sparse logistic regression model with Keras and having a dense layer supporting sparse input in Keras would be quite cool.
- Should I wait for landing such a feature in Keras or should I implement my own layer?
- Is there already an existing snippet with such a layer somewhere?

**Comment by SharoneDayan** [comment] 2019-07-22 13:28
Maybe, the medium article I wrote on ingesting sparse inputs in Tensorflow Keras can help you out : https://medium.com/dailymotion/how-to-design-deep-learning-models-with-sparse-inputs-in-tensorflow-keras-fd5e754abec1

**Comment by anttttti** [comment] 2019-08-26 02:35
@SharoneDayan 
> Maybe, the medium article I wrote on ingesting sparse inputs in Tensorflow Keras can help you out : https://medium.com/dailymotion/how-to-design-deep-learning-models-with-sparse-inputs-in-tensorflow-keras-fd5e754abec1

On TensorFlow 2.0.0-rc0 I get "ValueError: The two structures don't have the same nested structure." trying your DenseLayerForSparse layer. Using sparse inputs as to regular Dense gives the "ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`." There doesn't seem to be any simple fix to this that doesn't involve in-depth understanding of TF2 internals..

Fixing the batch_size to all inputs as @omalleyt12 suggests gives the same "two structures don't have the same nested structure" error, and it seems that SparseTensorSpec gets the training dataset size as its first axis, whereas the SparseTensor -structure gets the batch_size as its first axis. Same when trying the DenseLayerSparse workaround.l

Sparse inputs have worked out of the box for Keras so far, as in every other DL backend. These are a common use case with document and graph data, so it's strange that this feature is not working so close to TF2 full release, especially since SparseTensors are one of the advertised new features.

**Comment by cadama** [comment] 2019-08-27 08:49
@anttttti 

Possibly related:

https://github.com/tensorflow/tensorflow/issues/31999

**Comment by danielegrattarola** [comment] 2019-09-24 22:11
Can confirm that updating to >=1.14 breaks most code dealing with sparse data, which is especially relevant for graphs and text as @anttttti mentioned. 

This does not seem to be an issue that can be easily worked around, and the only stable solution is to use Keras 2.2.5 (not 2.3, because that's broken too since it was made to be similar to `tf.keras`). 
This seems like a huge step back and effectively makes it impossible to use sparse tensors in a Keras model.

**Comment by kechan** [comment] 2019-10-12 04:09
For tensorflow 2.0 (not rc):

x = Input(shape=(32,), sparse=True)
y = Dense(1, activation='sigmoid')(x)

model = Model(x, y)

I am still getting:

ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

Anyone know how to resolve?

**Comment by quangkevin** [comment] 2019-11-22 18:43
Hi @kechan, did you figure out the solution? I'm running into the same issue too.

**Comment by kechan** [comment] 2019-11-22 20:16
@quangkevin 
No. I haven't looked into it again. I thought i just use Masking for my particular model and move on. But try install tf.nightly and see if the issue is still there. it appears this "bug" has been opened for a long while.

**Comment by mmichaelzhang** [comment] 2019-11-26 22:31
> This is because for SparseTensors, the `shape` is actually a Tensor. Tensors can't have `None` values.
> 
> You can get around this on the `Input` layer by defining your `batch_size`:
> 
> ```python
> x = keras.Input(batch_size=10, shape=(4,), sparse=True)
> ```
> 
> However, `Dense` layers (and most layers in general it seems) don't support sparse inputs, so you would need to subclass Layer in order to call `tf.sparse.sparse_dense_matmul` on your inputs, or create a Lambda layer to convert your sparse inputs to dense.

Hi omalleyt12,

I have tried using the tf.sparse.sparse_dense_matmul() function to convert my sparse tensor into a dense one. But it still cannot fit into a dense layer:

 for p, dim in zip(adjacency_powers, dim_per_power):
    net_p = adj_times_x(sparse_adjacency, x, p)

    with tf.variable_scope('r%i_l%i_p%s' % (replica, layer_id, str(p))):
      layer = tf.layers.Dense(
          dim,
          kernel_regularizer=kernel_regularizer,
          activation=None, use_bias=False)
      net_p = layer.apply(net_p)

def adj_times_x(adj, x, adj_pow=1):
  """Multiplies (adj^adj_pow)*x."""
  for i in range(adj_pow):
    x = tf.sparse_tensor_dense_matmul(adj, x)
  return x

and the error is still "ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`."

Any suggestions regarding this?

Thanks

**Comment by cgarciae** [comment] 2020-01-12 22:34
This is not fixed in 2.1.0 :(
This is a major blocker for the [Spektral](https://danielegrattarola.github.io/spektral/) library. Can we get some attention on this issue?

**Comment by karmel** [comment] 2020-02-06 18:54
@cgarciae -- can you file a new bug with a minimal repro in 2.x? This bug is very old, and it's hard to tell exactly what condition set doesn't work here.

**Comment by MarkDaoust** [comment] 2020-02-06 19:41
Hi @karmel, 

I just submitted the fix for this. It should be synced out shortly.

**Closed** 2020-02-06 19:47 UTC
Labels: comp:keras, type:bug
