### ISSUE TITLE
Feature Request: Backprop through the transformation matrix in tf.contrib.image.transform and tf.contrib.image.rotate

### ISSUE THREAD

**Issue by sascha1990** [tensorflow/tensorflow#18649] opened 2018-04-18 12:02 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary, cpu
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 2.7
- **Have I written custom code**: No
- **Bazel version**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: GTX 730M but not in use
- **Exact command to reproduce**: N/A

Hello Guys,

today I met a problem while using tf.contrib.image.rotate and tf.contrib.image.translate in TensorFlow. I want to train a Convolutional Network to estimate the rotation and translation between two 2D Laserscan images as Input (estimate some kind of odometry).
`network = NeuralTransformEstimator()`
`xy, alpha = tf.split(network.logits, [2, 1], 1)`
`img1, img2 = tf.split(network.inputs, [1, 1], 3)`
`alphas = tf.squeeze(alpha, axis=1)`
`rotated = tf.contrib.image.rotate(img1, alphas, interpolation='NEAREST')`
`translated = tf.contrib.image.translate(rotated, xy, interpolation='NEAREST')`
`loss_function = tf.reduce_mean(tf.square(img2-translated))`

The Network outputs three values(x,y, alpha) and the input is two images. When I use BackProp I get this error message:

> ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables

So I created a more lightweight approach to check if I did something wrong elsewhere but it seems that translate and rotate do not provide gradients.
Is there a chance that this feature will be added?

**Comment by tensorflowbutler** [comment] 2018-04-18 19:02
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-05-04 18:40
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by sascha1990** [comment] 2018-05-04 18:59
Yes, I need this feature for my master thesis. It would be great if this issue could be resolved.

Von meinem iPhone gesendet

**Comment by jart** [comment] 2018-05-04 20:26
@ringw you've done a lot of work on tf.contrib.image. Is this feature request something you find appealing?

**Comment by ringw** [comment] 2018-05-04 20:48
The gradient is implemented for [the image pixels but not the transformation](https://github.com/tensorflow/tensorflow/blob/daecc72653e81d3c4592ad4ab246275a2cbd2712/tensorflow/contrib/image/python/ops/image_ops.py#L366). I haven't really developed or even directly used TF gradients yet, but I can take a look when I get a chance. This might be significantly more complex than the original image gradient, not sure yet.

**Comment by tensorflowbutler** [comment] 2018-05-26 18:59
Nagging Assignee @ringw: It has been 21 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 21:49
Nagging Assignee @ringw: It has been 36 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:13
Nagging Assignee @ringw: It has been 66 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 19:06
Nagging Assignee @ringw: It has been 81 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:09
Nagging Assignee @ringw: It has been 96 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ringw** [comment] 2018-08-10 20:31
Sorry for the delay. Closing because I think this would require another C++ kernel. The gradient for bilinear interpolation can't be calculated using the existing projective transformation, because the interpolation would also depend on the gradient of the transformation matrix. I don't think we can support a second C++ kernel for this particular case.

I think this use case is something like [optical flow](https://en.wikipedia.org/wiki/Optical_flow) between two frames. However, I'm not sure if gradient descent on the transformation matrix will work as well as some of the methods mentioned in the article. It also might be out of scope for TensorFlow, where the purpose of image processing is mostly for data augmentation for a classifier, and this kind of computer vision is better handled by OpenCV.

**Closed by ringw** 2018-08-10 20:31 UTC
Labels: type:feature

**Comment by gautamsreekumar** [comment] 2018-10-05 06:50
Hi, is there a way that the feature for computing gradients through the translation in `tf.contrib.image.translate` could be added? It does not involve any interpolation like in `tf.contrib.image.transform` or `tf.contrib.image.rotate`.
