### ISSUE TITLE
how can i run tensorflow in second gpu 

### ISSUE THREAD

**Issue by abdoelsayed2016** [tensorflow/tensorflow#40842] opened 2020-06-26 16:44 UTC
I am tired to make TensorFlow 2.1 to work in the second , third, fourth GPU  
but every time TensorFlow uses the first GPU 
I have 4 GPU and I want to train 4 model each model in different GPU 

**System information**
- windows 10 x64 
- python 3.6 
- TensorFlow  2.1 
- nvcc: NVIDIA (R) Cuda compiler driver
 Copyright (c) 2005-2019 NVIDIA Corporation
 Built on Fri_Feb__8_19:08:26_Pacific_Standard_Time_2019
 Cuda compilation tools, release 10.1, V10.1.105
- GPU : Tesla K20Xm
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 441.22       Driver Version: 441.22       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K20Xm         TCC  | 00000000:03:00.0 Off |                    0 |
| N/A   29C    P8    18W / 235W |      9MiB /  5696MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K20Xm         TCC  | 00000000:04:00.0 Off |                    0 |
| N/A   26C    P8    18W / 235W |      9MiB /  5696MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K20Xm         TCC  | 00000000:83:00.0 Off |                    0 |
| N/A   22C    P8    18W / 235W |      9MiB /  5696MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K20Xm         TCC  | 00000000:84:00.0 Off |                  N/A |
| N/A   21C    P8    18W / 235W |      9MiB /  5696MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
I tired before run jupyter notebook write this command 
set CUDA_VISIBLE_DEVICES=0 & jupyter notebook
set CUDA_VISIBLE_DEVICES=1 & jupyter notebook
set CUDA_VISIBLE_DEVICES=2 & jupyter notebook
set CUDA_VISIBLE_DEVICES=3 & jupyter notebook
also inside jupyter  
import os
os.environ["CUDA_VISIBLE_DEVICES"]="1,2,3"
what is solution please ??

**Comment by nikitamaia** [comment] 2020-06-26 17:08
Hi @abdoelsayed2016, in order to use multiple GPUs with Tensorflow please take a look at the [Distributed training with TensorFlow guide](https://www.tensorflow.org/guide/distributed_training). This guide walks through the distribution strategies available and shows how to use them.

**Comment by abdoelsayed2016** [comment] 2020-06-26 17:59
hi @nikitamaia  , thank for your replay 
I want to run each jupyter in different gpu ,
in this [link ](https://www.tensorflow.org/guide/gpu#using_a_single_gpu_on_a_multi-gpu_system) , i need to change all code in jupyter to add it 
i need a solution to make TensorFlow use not default gpu:0

**Comment by nikitamaia** [comment] 2020-06-26 19:51
I'm not sure I understand your question? The solution to make TF not use default gpu:0 is what is explained in that link. You have to set it explicitly. Let me know if I'm misunderstanding what you are asking about.

**Comment by abdoelsayed2016** [comment] 2020-06-26 20:30
When i tired the tf.device 
I see the operation in the command line still using first gpu , and only training using second gpu 
![1593203381217](https://user-images.githubusercontent.com/27821589/85898483-d495b500-b7eb-11ea-8b4f-5c3937d285de.jpg)
If u see in the photo most of operations use the gpu:0

**Comment by nikitamaia** [comment] 2020-06-26 21:14
Ahh I see, looks like those VarHandleOp are being executed on GPU 0. It's difficult to say much more without a minimal reproducible example, but something else you might want to try is using [tf.config.set_visible_devices](https://www.tensorflow.org/api_docs/python/tf/config/set_visible_devices) to specify which devices are visible to the runtime. This will allow you to make only 1 of your 4 GPUs available for memory allocation and operations.

**Comment by abdoelsayed2016** [comment] 2020-06-27 13:47
@nikitamaia 
thank you for your solution last link work with me

**Comment by nikitamaia** [comment] 2020-07-02 20:31
Glad to hear it! Closing this issue now since a solution was found.

**Closed by nikitamaia** 2020-07-02 20:31 UTC
Labels: TF 2.1, comp:gpu, type:support
