### ISSUE TITLE
save preprocessor is too slow for large vocabulary size: 2500e4 lookup table size ~ 0.50 hour

### ISSUE THREAD

**Issue by cnglen** [tensorflow/tensorflow#57741] opened 2022-09-18 16:15 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

tf 2.10.0

### Custom Code

Yes

### Python version

3.8

### Current Behaviour?

It takes near **an hour(too long)** to save the preprocessor for a lookup size ~ 2500e4.

Maybe related to `saved_model/save.py: list_children()`. 

It seems like it iterate the lookup table for each of 2500e4 elements. (Not sure)

Any suggestions?

### Standalone code to reproduce the issue

```shell
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""demo of preprcoessing large layers
"""

# pylint:disable=no-member
import time
from typing import Dict

import tensorflow as tf


@tf.keras.utils.register_keras_serializable()
def split_vertical(x):
    """
    用于TextVectorization的split入参, split by `|`
    """
    return tf.strings.split(x, sep="|")


# 25242127 -> 3323 seconds
class TestPreprocessor(tf.keras.Model):
    def __init__(self, name="test_preprocessor", vocab_size: int = 100, **kwargs):
        super().__init__(name=name, trainable=False, **kwargs)
        self._lookup = {}
        self.vocab_size = vocab_size
        print(f"\nvocab_size={vocab_size}")

    def adapt(self):
        vocab = [str(i) for i in range(self.vocab_size)]

        tic = time.time()
        text_vectorizer = tf.keras.layers.TextVectorization(
            vocabulary=vocab,
            output_mode="int",
            split=split_vertical,
            standardize=None,
            output_sequence_length=7,
            name="text_vectorization_" + "faked_id",
        )
        toc = time.time()
        print(f"Construct TextVectorization: {toc - tic:.2f} seconds")
        self._lookup["faked_id"] = text_vectorizer

    def save(self, filepath: str = "/tmp/debug_large_vocab"):
        ds = tf.data.Dataset.from_tensor_slices({"faked_id": [str(e) for e in range(100)]}).batch(3).map(self)
        _ = next(iter(ds))
        tic = time.time()
        super().save(filepath)
        toc = time.time()
        print(f"Save TextVectorzation:       {toc-tic:.2f} seconds")

    def call(self, batch: Dict):
        ans = {}
        for f, lookup in self._lookup.items():
            ans[f] = lookup(batch[f])
        return ans


def main():
    vsize = [1000, 10000, 100000, 1000000, 25000000]
    for V in vsize:
        preprocessor = TestPreprocessor(vocab_size=V)
        preprocessor.adapt()
        preprocessor.save()


if __name__ == "__main__":
    main()
```

### Relevant log output

```shell
vocab_size=1000
Construct TextVectorization: 0.01 seconds
Save TextVectorzation:       0.29 seconds

vocab_size=10000
Construct TextVectorization: 0.04 seconds
Save TextVectorzation:       0.68 seconds

vocab_size=100000
Construct TextVectorization: 0.35 seconds
Save TextVectorzation:       5.58 seconds

vocab_size=1000000
Construct TextVectorization: 3.58 seconds
Save TextVectorzation:       57.34 seconds

vocab_size=25000000
Construct TextVectorization: 90.79 seconds
Save TextVectorzation:       1612.00 seconds
```
</details>

**Comment by cnglen** [comment] 2022-09-19 12:57
``` python
text_vectorizer._self_tracked_trackables.pop()
text_vectorizer._lookup_layer._self_tracked_trackables.pop()
```

It's caused by the large list member of:
- text_vectorizer._self_tracked_trackables
- text_vectorizer._lookup_layer._self_tracked_trackables

It's seems it's not necessary to add the huge list to ._self_tracked_tradckables(which is recursive traversal). Maybe The preprocess layers should disable _self_tracked_trackables.

**Comment by tiruk007** [comment] 2022-09-20 11:48
@cnglen 
This issue seems to be Keras issue. Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) All issues and PRs related to keras will be addressed in that repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999.

Thank you!

**Comment by cnglen** [comment] 2022-09-21 08:46
You can change 'vsize = [1000, 10000, 100000, 1000000, 25000000]' to 'vsize = [1000, 10000, 100000, 1000000]'

It takes too much time to save the huge preprocessor with 2500e4 vocab size.

**Comment by tiruk007** [comment] 2022-09-21 10:17
@gadagashwini 
I was able to reproduce the issue on Colab by using the latest TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/bac132fab33868e00cf0fb4a0cc2f27e/57741.ipynb) for reference.
Thank you!

**Comment by gowthamkpr** [comment] 2022-10-04 19:46
@cnglen I agree with [this](https://github.com/tensorflow/tensorflow/issues/57741#issuecomment-1250984750). But development of keras has been moved to a different repo. Can you please create an issue in [keras-team/keras](https://github.com/keras-team/keras/issues/new/choose). Thanks!!!

**Closed** 2022-10-18 20:26 UTC
Labels: stat:awaiting response, stalled, comp:keras, type:performance, TF 2.10
