### ISSUE TITLE
AttributeError: 'RefVariable' object has no attribute 'ref'

### ISSUE THREAD

**Issue by debadityamandal** [tensorflow/tensorflow#32340] opened 2019-09-09 05:38 UTC
with tf.device('/cpu:0'):
  activations = tf.Variable(tf.zeros([ACT_LEN, FLAGS.wvs, 1], FTYPE), name='activations',
                            trainable=False)
logits = batch_logits(i_ss, activations.ref())
AttributeError: 'RefVariable' object has no attribute 'ref'

**Comment by oanush** [comment] 2019-09-10 09:32
@debadityamandal ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Can you share a simple and standalone code to reproduce the issue?Thanks!

**Comment by debadityamandal** [comment] 2019-09-10 10:29
@oanush ,
I am executing the code in google colab and tensorflow version is 1.14.0.This is the code snippet.
Thank You

**Comment by oanush** [comment] 2019-09-10 11:02
@debadityamandal ,
Thank you for the response,but I don't see the code attached.

**Comment by oanush** [comment] 2019-09-18 06:56
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-09-18 06:56 UTC
Labels: TF 1.14, comp:ops, stat:awaiting response
