### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute '_datatype_enum'

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#35949] opened 2020-01-16 16:32 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X Catalina (10.15.2)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7.5
- GPU model and memory: Intel Iris Pro 1536 MB

**Describe the current behavior**

I get the errors

> tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

then 

> AttributeError: 'Tensor' object has no attribute '_datatype_enum'

and then

> AttributeError: 'ProgbarLogger' object has no attribute 'log_values'

when I add the following callback to the list of callbacks of `my_model.fit`

```
my_callback = tf.keras.callbacks.LambdaCallback(on_batch_begin=lambda batch, logs: tf.print(my_model.losses))
```

**Describe the expected behavior**

No error.

**Code to reproduce the issue**

```
import tensorflow as tf


def get_model():
    inp = tf.keras.layers.Input(shape=(1,))
    x = tf.keras.layers.Dense(8, activity_regularizer=tf.keras.regularizers.l1(0.01))(inp)
    x = tf.keras.layers.Dense(16, activity_regularizer=tf.keras.regularizers.l1(0.01))(x)
    out = tf.keras.layers.Dense(1)(x)
    model = tf.keras.Model(inputs=inp, outputs=out)
    return model


def train():
    my_model = get_model()
    my_model.compile(optimizer="adam", loss="mse")
    my_callback = tf.keras.callbacks.LambdaCallback(on_batch_begin=lambda batch, logs: tf.print(my_model.losses))
    my_model.fit([1, 2, 3, 4], [0.1, 0.2, 0.4, 0.2], callbacks=[my_callback])


if __name__ == '__main__':
    train()
```

This issue may be related to https://github.com/tensorflow/tensorflow/issues/28924 and https://github.com/tensorflow/tensorflow/issues/29931. Note that, if I don't use any regulariser, `tf.print` prints an empty list and no error occurs.

**Comment by oanush** [comment] 2020-01-17 09:07
Issue replicating for 2.0 and [tf-nightly](https://colab.sandbox.google.com/gist/oanush/f48bb5fa2028ece28e5fcee88551e852/35949.ipynb).Thanks!

**Comment by ymodak** [comment] 2020-01-17 19:24
You may use `print` instead of `tf.print` in `LambdaCallback` like,
```python
my_callback = tf.keras.callbacks.LambdaCallback(on_batch_begin=lambda batch, logs: print(my_model.losses))
```

**Comment by nbro** [comment] 2020-01-17 19:32
@ymodak In the example I provided above, I am trying to print the `losses` property, but, actually, I wanted to print the output of a layer, so I had tried something like

```
cb = tf.keras.callbacks.LambdaCallback(on_batch_begin=lambda batch, logs: 
tf.print(my_model.get_layer("my_layers_name").output))
```
which produces the error mentioned in the issue above.

**Comment by nbro** [comment] 2020-01-18 02:04
@ymodak The documentation of `tf.print` says

> A TensorFlow operator that prints the specified inputs to a desired output stream or logging level. The inputs may be **dense** or **sparse Tensors**, **primitive python objects**, **data structures that contain tensors**, and **printable Python objects**. Printed tensors will recursively show the first and last elements of each dimension to summarize.

So are outputs of layers considered either dense tensors or dense tensors? They should not be considered primitive Python objects, data structures that contain tensors or printable Python objects. 

Anyway, my main goal is to be able to print out the activations for each layer of a model at the end of the mini-batch (thus while training the model). See also https://stackoverflow.com/q/59789526/3924118.

**Comment by Apsylem** [comment] 2020-03-01 11:54
same issue with minimal example:

ar0 = Input(shape=(2,8,8,),name='ar0')
tf.print(ar0)

**Comment by PeterBrummer** [comment] 2020-04-14 13:34
@Apsylem 
I had probably the same issue as you.
The reason IMHO is that the statement "tf.print(ar0)" is being executed. in the declaration phase of the tensorflow graph and not when the graph itself is being executed. In the declaration phase the tensors are not completely defined, they  have no real content.

I came over this by creating a small Print-Layer and attaching it to the graph.
You could do something like this:

`
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Layer, Input

#The Printer-Layer class
class Print(Layer):
  verbose=True

  def __init__(self,message="", fn=lambda arg: arg,**kwargs):
    super(Print, self).__init__(**kwargs)
    self.message=message
    self.fn=fn

  def call(self, inputs, *args, **kwargs):
    super(Print, self).call(inputs, *args, **kwargs)
    if Print.verbose:
      tf.print(self.message,self.fn(inputs))
    return inputs

#somewhere where you define your model :
def defineModel():
  ar0 = Input(shape=(2,8,8,),name='ar0')
  ar0Intermediate = Print("shape of ar0 =",fn=lambda x: tf.shape(x) )(ar0) #show the shape of ar0
  ar0Intermediate = Print("Content of ar0 = " )(ar0Intermediate) #show the content of ar0
  out = tf.keras.layers.Dense(1)(ar0Intermediate)
  model = tf.keras.Model(inputs=ar0, outputs=out)
  return model
  
def train():
    trainData=np.random.uniform(low=0,high=15.0,size=(4,2,8,8))
    testData=np.random.uniform(low=0,high=10.0,size=(4,2,8,8))

    my_model = defineModel()
    my_model.compile(optimizer="adam", loss="mse")
    my_model.fit(trainData, testData)

if __name__ == '__main__':
  Print.verbose=True #False
  train()
`

**Comment by cgebe** [comment] 2020-06-06 18:05
Is there a solution to this issue?

Same problem here in tensorflow 2.2.0. I'm not able to print the values of a tensor in my loss function used within a keras model.

**Comment by saberkun** [comment] 2020-06-09 07:58
@omalleyt12 We might expect tf.print to be wrapped by TensorFlowOpLayer?

**Comment by ravikyram** [comment] 2020-06-16 06:38
I have tried in colab with TF version 2.2, nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/cf46faed2315a686d2c7aa5789b4626c/untitled26.ipynb).Thanks!

**Comment by omalleyt12** [comment] 2020-06-16 07:16
@tomerk this is likely something `KerasTensor`s fixes

**Comment by tomerk** [comment] 2020-06-22 18:37
So, some context on what's happening here:
`tf.print` is meant to mimic python printing, and does not return values.
If you do `x = print(...)` x holds no value. `x = tf.print(...)` acts the same way. If there was meant to be a return value it would be very ambiguous whether the returned value should be the inputs, or the printed string.

So, if you do:
```
a = tf.keras.Input(...)
b = layer(a)
c = tf.print(b)
```
`c` will not hold any value. So, putting `tf.print` in the middle of your functional api construction won't automatically turn it into a "printing layer". We don't plan to change this because printing is not an identity operation, and thinking of printing as an identity is an anti-pattern. More context on the design of `tf.print` can be found here: https://github.com/tensorflow/community/blob/master/rfcs/20180824-tf-print-v2.md

During functional model construction `tf.print` will act like `print` and try to print the python object that symbolically represents that intermediate output.


If you want to observe intermediate values during the model call, and you're using functional model construction, then you have a few options:
1. Use a keras lambda layer to run a function that tf.prints the inputs and then returns them
2. Write a custom `Printer` layer that prints the inputs
3. include the intermediate outputs you want to inspect in the outputs of your functional model. You can then directly inspect them programmatically after calling your model

---------------------------------------------
I'm closing the issue because the discussion has veered off from the initial `AttributeError` report. and it won't be easy to find for people who are looking for info about printing in Keras.

But, if the above three options don't meet your needs we encourage you to open a feature request specifically around extending the mechanisms for printingdebugging intermediate activations in Keras layers.

Some extra context about your needs when you open the feature request would also be useful, so we can understand why the correct solutions don't meet them.

E.g.
Are you looking to interactively debug the activations?
Would you like the model to *always* print?
Do you want printing/debugging to happen during actual fitting, or just when interacting with a model object batch by batch?
Do you need sporadic logging of intermediate activations that don't happen at each batch?

**Closed by tomerk** 2020-06-22 18:37 UTC
Labels: TF 2.2, comp:keras, type:bug
