### ISSUE TITLE
Autotune seems not improve performance

### ISSUE THREAD

**Issue by chengmengli06** [tensorflow/tensorflow#31994] opened 2019-08-27 03:29 UTC
How autotune is implemented? it seems not improve performance, the dataset is still the bottleneck.

**Comment by oanush** [comment] 2019-08-28 08:46
@chengmengli06 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by chengmengli06** [comment] 2019-08-28 09:03
I use tf 1.12, installed from binary, redhat system with 500G memory, 96 core CPU. The tfrecord is stored in a network file system(OSS), the pipeline looks that this:
read from oss
parse by TFRecord
prefetch
shuffle
decoding
prefetch
batch
The last batch step is autotuned, while the previous steps are not autotuned.

**Comment by oanush** [comment] 2019-08-29 08:55
@chengmengli06 ,
Thank you for the information, In order to expedite the trouble-shooting process, please provide code snippet to reproduce the issue reported here.

**Comment by chengmengli06** [comment] 2019-09-03 08:18
I cannot provide the code, my code access oss, which runs on PAI, and could not run locally.

**Comment by jsimsa** [comment] 2019-09-04 17:18
Without a reproducible example, there is not much we can do to help.

Autotuning will provide performance that should be close the performance of hand-tuned input pipeline. If you have already hand-tuned your input pipeline, autotuning is not expected to improve your performance further. The main benefit of autotuning is that it avoids the need for users to hand-tuned their input pipelines.

**Comment by gowthamkpr** [comment] 2020-03-30 20:46
Closing this issue as it is not reproducible. Please add additional comments so that we can open this issue again. Thanks!

**Closed by gowthamkpr** 2020-03-30 20:46 UTC
Labels: TF 1.12, comp:data, type:support
