### ISSUE TITLE
Incompatibility between keras and tf.keras for layer.build

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/tensorflow#25790] opened 2019-02-15 19:47 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.13.0rc1
- Python version: 3.6
- Bazel version (if compiling from source): No
- GCC/Compiler version (if compiling from source): No
- CUDA/cuDNN version: No
- GPU model and memory: No

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

Here is the code below which should work (it works with keras-team/keras).

**Describe the expected behavior**

The code should run as expected, instead, we get the error message below. Note that changing the flag at the begining of the script makes the code work.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
use_tf_keras = True
if use_tf_keras:
    from tensorflow.keras.layers import Layer, Dense
    from tensorflow.keras import backend as K
    from tensorflow.keras import Sequential
else:
    from keras.layers import Layer, Dense
    from keras import backend as K
    from keras import Sequential


class MyLayer(Layer):

  def build(self, input_shape):
    print(type(input_shape))
    input_dim = input_shape[-1]
    output_dim = input_shape[-1] / 2

    self.kernel = self.add_weight(shape=(input_dim, output_dim),
                                  name='kernel',
                                  initializer='ones')
    super().build(input_shape)

  def call(self, inputs):
    return K.dot(inputs, self.kernel)

  def compute_output_shape(self, input_shape):
    input_shape = list(input_shape)
    input_shape[-1] = input_shape[-1] // 2
    return input_shape

model = Sequential()
model.add(Dense(8, input_shape=(20, 20)))
model.add(MyLayer())
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
<class 'tensorflow.python.framework.tensor_shape.TensorShapeV1'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-255eda5c5005> in <module>()
     32 model = Sequential()
     33 model.add(Dense(8, input_shape=(20, 20)))
---> 34 model.add(MyLayer())

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpointable/base.py in _method_wrapper(self, *args, **kwargs)
    440     self._setattr_tracking = False  # pylint: disable=protected-access
    441     try:
--> 442       method(self, *args, **kwargs)
    443     finally:
    444       self._setattr_tracking = previous_value  # pylint: disable=protected-access

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py in add(self, layer)
    178       # If the model is being built continuously on top of an input layer:
    179       # refresh its output.
--> 180       output_tensor = layer(self.outputs[0])
    181       if isinstance(output_tensor, list):
    182         raise TypeError('All layers in a Sequential model '

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    536       if not self.built:
    537         # Build layer if applicable (if the `build` method has been overridden).
--> 538         self._maybe_build(inputs)
    539         # We must set self.built since user defined build functions are not
    540         # constrained to set self.built.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   1601     # Only call `build` if the user has manually overridden the build method.
   1602     if not hasattr(self.build, '_is_default'):
-> 1603       self.build(input_shapes)
   1604 
   1605   def __setattr__(self, name, value):

<ipython-input-2-255eda5c5005> in build(self, input_shape)
     15     print(type(input_shape))
     16     input_dim = input_shape[-1]
---> 17     output_dim = input_shape[-1] / 2
     18 
     19     self.kernel = self.add_weight(shape=(input_dim, output_dim),

TypeError: unsupported operand type(s) for /: 'Dimension' and 'int'
```

if using keras-team/keras, we get:
```
<class 'tuple'>
```

**Comment by yongtang** [comment] 2019-02-17 23:31
The issue is that `Dimension` only defines a `__div__`, not `__rdiv__` (or `__truediv__`/`__rtruediv__`):
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/tensor_shape.py#L455

I think adding `__rdiv__` will fix the issue of `TypeError: unsupported operand type(s) for /`.

However, in the above code in tensorflow, it also mentioned that `__div__` is deprecated (in favor of `__floordiv__` or `//`). Actually, changing:
`output_dim = input_shape[-1] / 2` to `output_dim = input_shape[-1] // 2` works.

I think it probably makes sense to change `/` to `//`?

Or, maybe it also makes sense to explicitly thrown out a better error message in `__div__`/`__rdiv__`?

**Comment by yongtang** [comment] 2019-02-18 00:40
Created a PR #25821 to print a better error message in case the operation is not supported.

**Comment by ymodak** [comment] 2019-07-25 21:59
Closing this issue since the associated PR has been merged. 
Also can see clear error message with latest TF (tested with tf-nightly 1.15.0-dev201907250)
Thanks!

**Closed by ymodak** 2019-07-25 21:59 UTC
Labels: comp:keras, type:bug
