### ISSUE TITLE
Check for Xcode 7.3 fails in compile_ios_tensorflow.sh

### ISSUE THREAD

**Issue by davlhd** [tensorflow/tensorflow#3081] opened 2016-06-28 16:31 UTC
```
++ xcodebuild -version
++ head -n 1
++ sed 's/Xcode //'
+ ACTUAL_XCODE_VERSION=7.3
+ REQUIRED_XCODE_VERSION=7.3.0
+ '[' 73 -lt 730 ']'
+ echo 'error: Xcode 7.3.0 or later is required.'
error: Xcode 7.3.0 or later is required.
```

This should be easy to fix :)

**Comment by andydavis1** [comment] 2016-06-28 16:59
Can you please provide the information from the template that is presented when you created the issue?

GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from sources, provide the commit hash:

### Steps to reproduce
1.
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by aselle** [comment] 2016-07-09 03:33
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.

**Closed by aselle** 2016-07-09 03:33 UTC
Labels: awaiting response, need more information, triaged
