### ISSUE TITLE
error reported while using TensorForestEstimator. tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'FertileStatsResourceHandleOp' in binary running on...

### ISSUE THREAD

**Issue by sanjayraojjn** [tensorflow/tensorflow#16855] opened 2018-02-08 06:12 UTC
Have I written custom code - Yes, but provided code in link also has same problem
OS Platform and Distribution - Windows 7
TensorFlow installed from - PIP install
TensorFlow version - 1.4 and 1.5 both on CPU
Bazel version - No bazel version used
CUDA/cuDNN version - N/A
GPU model and memory - N/A
Exact command to reproduce - provided a link to python script below to reproduce this issue

I am trying to use "TensorForestEstimator" defined in "tensorflow.contrib.tensor_forest.client.random_forest". I get following error.

Same error is reported when I run this script
https://www.kaggle.com/biscuitlickz/iris-predictions-using-tensorflow/code

Traceback (most recent call last):
  File "titanic_random_forest.py", line 201, in <module>
    app.run(main=main)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 124, in run
    _sys.exit(main(argv))
  File "titanic_random_forest.py", line 136, in main
    est.fit(input_fn=train_input_fn, steps=TRAIN_STEPS)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 480, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 985, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1201, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1165, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\tensor_forest\client\random_forest.py", line 168, in _model_fn
    device_assigner=dev_assn)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 376, in __init__
    tree_variables_class=tree_variables_class)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 350, in __init__
    self.variables.append(tree_variables_class(params, i, training))
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\tensor_forest\python\tensor_forest.py", line 318, in __init__
    params, '', self.get_tree_name('stats', tree_num))
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops\stats_ops.py", line 102, in fertile_stats_variable
    container, shared_name=name, name=name)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\tensor_forest\python\ops\gen_stats_ops.py", line 141, in fertile_stats_resource_handle_op
    shared_name=shared_name, name=name)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "F:\programs-all\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'FertileStatsResourceHandleOp' in binary running on ATWOOD_SRAO. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by tensorflowbutler** [comment] 2018-02-08 19:17
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by sanjayraojjn** [comment] 2018-02-09 06:48
required details updated above.

**Comment by deathmantim** [comment] 2018-02-22 15:45
The same is happening for me on windows 10, same version installed from pip CPU only

**Comment by bignamehyp** [comment] 2018-02-23 08:52
@caisq can you please take a look?

**Comment by tensorflowbutler** [comment] 2018-03-10 13:10
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by rohanag12** [comment] 2018-03-23 23:46
Hi, any updates on this issue? I am facing the same issue when trying to import a saved model using Python as well as Java bindings.

**Comment by shivaniag** [comment] 2018-03-30 17:54
@gilberthendry, @thomascolthurst could you also take a look into this?

**Comment by ThomasColthurst** [comment] 2018-03-30 18:00
@nataliaponomareva

**Comment by Avtarsingh127** [comment] 2018-04-03 06:24
any update on this? I am getting same error.

  File "load_grph.py", line 20, in load_graph
    tf.import_graph_def(graph_def, name="prefix")
  File "/home/neva/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)

**Comment by tkoeppe** [comment] 2018-04-03 15:54
There may be a dependency we deleted accidentally. Could you try adding `:stats_ops_py` to `tensorflow/contrib/tensor_forest:model_ops_py`?

**Comment by tkoeppe** [comment] 2018-04-03 16:59
No, never mind, that dependency is already present there.

**Comment by rainlei2001** [comment] 2018-04-09 13:08
I ran into the same issue.

**Comment by bexvan** [comment] 2018-04-18 05:47
I am getting same error.

**Comment by gavintgh** [comment] 2018-04-22 03:39
I am getting the same issue

**Comment by tensorflowbutler** [comment] 2018-05-06 18:29
Nagging Assignee @caisq: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by nataliaponomareva** [comment] 2018-05-07 16:12
+@yupbank

**Comment by yupbank** [comment] 2018-05-07 16:52
hi... sorry for not the late reply, the ` Op type not registered '*' in binary` is a know issue in java land, since by default  tf.contrib project `.so` didn't get package within the java distribution can be addessed by `TensorFlow.loadLibrary()` https://github.com/tensorflow/tensorflow/issues/10454#issuecomment-344139462

Meanwhile, for the tensorflow in python having this kind of error could be soemthing to do with misconfiguration with bazel? i'll have to spend more time into reproduce the error to achieve a conclusion

**Comment by lanahra** [comment] 2018-05-08 20:45
Hello @yupbank, I'm also having the same problem, I wrote a minimum script that reproduces the error:

```python
import pandas as pd
import tensorflow as tf
from tensorflow.contrib.tensor_forest.python import tensor_forest
from tensorflow.contrib.tensor_forest.client import random_forest 

def main():
    model_dir = './model'

    params = tensor_forest.ForestHParams(
        num_features=1,
        num_classes=2,
        num_trees=100,
        max_nodes=1000,
    ).fill()

    classifier = random_forest.TensorForestEstimator(
        params,
        model_dir=model_dir
    )

    data = pd.DataFrame(data={'x':[2, 3], 'y': [0, 1]})

    x_train, y_train = data, data.pop('y')

    input_fn_train = tf.estimator.inputs.pandas_input_fn(
        x=x_train,
        y=y_train,
        batch_size=1,
        num_epochs=100,
        shuffle=True,
        target_column='y'
    )
    
    classifier.fit(input_fn=input_fn_train)

if __name__ == '__main__':
    main()
```

**Comment by yupbank** [comment] 2018-05-08 20:59
Thank you @lanahra  !! can you have do this 
```
You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

**Comment by lanahra** [comment] 2018-05-08 22:55
Unfortunately I'm running on a Windows machine, so I cannot run the environment capture script.

Here is the second one:
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

C:\Users\%USER%\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36:
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is
deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
b'v1.8.0-0-g93bc2e2072' 1.8.0
```

**Comment by yupbank** [comment] 2018-05-09 01:45
sorry guys... according to the latest changes to tensor_forest BUILD file.
https://github.com/tensorflow/tensorflow/commit/38e0139329482d8e44629dea2e87853808eacd0d#diff-894ca5f2ae1e390cc3eba58d9e4052ed 

windows support is not being added for now i guess... 

tf.contrib projects are not officially supported, and may change or be removed at any time without notice.

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib#tensorflow-contrib

**Comment by yupbank** [comment] 2018-05-09 01:52
![image](https://user-images.githubusercontent.com/741544/39791504-0c2194c4-530a-11e8-8a40-0c555422c19a.png)
![image](https://user-images.githubusercontent.com/741544/39791510-1142c89c-530a-11e8-9fc1-cd7693162281.png)
dll missing from the folder

**Comment by yupbank** [comment] 2018-05-09 22:25
i'll close this issue for now, and will try to make more priority to add windows support for tensor_forest

**Closed by yupbank** 2018-05-09 22:25 UTC

**Comment by Milkve** [comment] 2021-05-17 03:33
@yupbank I found the same issue on ubuntu18.04 while trying to read the node info from `.pb` model file in TF 1.14.0, and this error is caused by compilation with Bazel(I tried to fix it, and I found in `tensorflow\contrib\tensor_forest\python\ops\_stats_ops.so` the so-called `FertileStatsResourceHandleOp` is already existed), so I guess that your team has fixed that problem on Ubuntu whereas `.dll` problem is still in suspensory status and to make the error messages sync among platforms, however, the same error reported on Ubuntu has solutions. Thus, I worked it out with 
```  python
import tensorflow as tf
from tensorflow.contrib.tensor_forest.python import tensor_forest
from tensorflow.python.ops import resources
```
and this solution is inspired by https://github.com/aymericdamien/TensorFlow-Examples/issues/212#issuecomment-743026970
In brief words, if anybody has the same problem (in TF 1) on Win10, they can avoid these errors by using Ubuntu and import proper modules in `tf.contrib`.
