### ISSUE TITLE
tf.image.per_image_standardization unexpected behavior with unsigned integer input

### ISSUE THREAD

**Issue by Engineero** [tensorflow/tensorflow#44983] opened 2020-11-18 15:52 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.4
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): v2.2.0-57-g25fba035f3 2.2.1
- Python version: 3.7.7
- CUDA/cuDNN version: 10.1.243
- GPU model and memory: Nvidia Tesla V100-DGXS-32GB, 

**Describe the current behavior**
`tf.image.per_image_standardization` has no special handling for unsigned integers but still converts back to unsigned before returning. Thus uint inputs get saturated at zero (fully half of the data!) and at their maximum value. Currently no explanation of uint behavior is given in the docstring, and no warning or other indication that behavior might be unexpected is shown.

**Describe the expected behavior**
In previous versions of TensorFlow (I believe changed after 1.14), `per_image_standardization` just returned a float rather than converting back to the original datatype, so it didn't have this problem. I would expect something safe like that, leaving it up to the developer to decide how they want this conversion handled, or at least a warning printed in the event a uint input is given. Some documentation specifying that uints are not handled differently and will be saturated might be nice too.

**Standalone code to reproduce the issue**
[Colab notebook link][0].

**Other info / logs** 
No tracebacks or logs because it doesn't throw an error. I would call this a failure mode, but it fails silently. I suspect it's an edge case that isn't tested.

[0]: https://colab.research.google.com/drive/1PqjTWtgLPE7hb5Dza2fZdFNbhlyW3mKl?usp=sharing

**Comment by ravikyram** [comment] 2020-11-19 02:47
@Engineero 

Please, grant me access to colab link. Thanks!

**Comment by Engineero** [comment] 2020-11-19 02:49
Sorry, haven't used colab much. It should be fixed now.

**Comment by ravikyram** [comment] 2020-11-19 03:26
I have tried in colab with TF version 2.3 and nightly version(`2.5.0-dev20201118`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/88120ddb0fd04644a3d2d4075ca97f7f/untitled524.ipynb). Thanks!

**Comment by Engineero** [comment] 2020-11-19 03:28
For the record, I think the behavior changed between 1.14 and 1.15, which is why I suspect an untested edge case. I had a use case where this affected training, and while it's certainly not backwards-incompatible (doesn't error out anyway), it is a surprise.

**Comment by mixxen** [comment] 2020-11-19 06:17
@engineero, related issue:

https://github.com/tensorflow/tensorflow/issues/33892

**Comment by mixxen** [comment] 2020-11-19 06:21
Here is the offending commit:

906e0e3

**Comment by Engineero** [comment] 2020-11-19 06:24
Oh, hey @mixxen! Good find, thanks!

**Comment by Engineero** [comment] 2020-12-04 15:33
It looks like simply *casting* (not with `convert_image_dtype`, just `tf.cast`) to float prior to `per_image_normalization` prevents information loss. I'd create a pull request, but I think the bigger question is what is the intended behavior when given unsigned integer input and how should that be communicated? Also covering this edge case with tests.

**Comment by hyeygit** [comment] 2020-12-20 21:05
Thank you for reporting the issue @Engineero and identifying the offending commit @mixxen.

The changes in https://github.com/tensorflow/tensorflow/commit/906e0e3bc0dfe12db19afa261e4d793b73cb64ec appears to have changed the behavior of `per_image_standardization` unintentionally and should be reverted back in my opinion. It especially does not make sense for unsigned integer data types because images that have zero-mean will consist of negative and positive values (unless all values are 0). The API function has been working with `uint` dtypes (until the breaking change) and should continue to do so. I'll get a fix in shortly.

**Comment by hyeygit** [comment] 2020-12-25 03:56
Here is a [colab](https://colab.research.google.com/drive/1nqzU22tZ0RVAaDm6drWPkfGV8cc7A_3x?usp=sharing) verifying the fix with `tf-nightly`. Closing the issue; please feel free to reopen if you encounter additional issues.

**Closed by hyeygit** 2020-12-25 03:56 UTC
Labels: TF 2.2, comp:ops, stat:awaiting tensorflower, type:bug
