### ISSUE TITLE
[TF 2.0 alpha] Tutorial "Using TFRecords and tf.Example" can't run on GPU

### ISSUE THREAD

**Issue by shaolinkhoa** [tensorflow/tensorflow#27181] opened 2019-03-27 06:45 UTC
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: Tensorflow 2.0 alpha
- Doc Link: [Using TFRecords and tf.Example](https://www.tensorflow.org/alpha/tutorials/load_data/tf_records)

**Describe the documentation issue**
I don't know why this tutorial only works for tensorflow CPU version.
If I run on GPU I will have an error in the cell:
`tf_serialize_example(f0,f1,f2,f3)`

```
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-14-406ee79a7f52> in <module>
----> 1 tf_serialize_example(f0,f1,f2,f3)

<ipython-input-13-3eb13f28c327> in tf_serialize_example(f0, f1, f2, f3)
      3     serialize_example,
      4     (f0,f1,f2,f3),  # pass these args to the above function.
----> 5     tf.string)      # the return type is `tf.string`.
      6   return tf.reshape(tf_string, ()) # The result is a scalar

D:\Anaconda\envs\tf2\lib\site-packages\tensorflow\python\ops\script_ops.py in eager_py_func(func, inp, Tout, name)
    387     if `func` returns None.
    388   """
--> 389   return _internal_py_func(func=func, inp=inp, Tout=Tout, eager=True, name=name)
    390 
    391 

D:\Anaconda\envs\tf2\lib\site-packages\tensorflow\python\ops\script_ops.py in _internal_py_func(func, inp, Tout, stateful, eager, is_grad_func, name)
    276   if eager:
    277     result = gen_script_ops.eager_py_func(
--> 278         input=inp, token=token, Tout=Tout, name=name)
    279   else:
    280     if stateful:

D:\Anaconda\envs\tf2\lib\site-packages\tensorflow\python\ops\gen_script_ops.py in eager_py_func(input, token, Tout, name)
     64       else:
     65         message = e.message
---> 66       _six.raise_from(_core._status_to_exception(e.code, message), None)
     67   # Add nodes to the TensorFlow graph.
     68   token = _execute.make_str(token, "token")

~\AppData\Roaming\Python\Python36\site-packages\six.py in raise_from(value, from_value)

UnknownError: RuntimeError: Error copying tensor to device: CPU:0. Can't copy 37 bytes of a tensor into another with 32 bytes buffer.
Traceback (most recent call last):

  File "D:\Anaconda\envs\tf2\lib\site-packages\tensorflow\python\ops\script_ops.py", line 205, in __call__
    return func(device, token, args)

  File "D:\Anaconda\envs\tf2\lib\site-packages\tensorflow\python\ops\script_ops.py", line 107, in __call__
    ret = self._func(*args)

  File "<ipython-input-7-60a59d21d73e>", line 10, in serialize_example
    'feature2': _bytes_feature(feature2),

  File "<ipython-input-3-8047e5ac1b09>", line 7, in _bytes_feature
    value = value.numpy() # BytesList won't unpack a string from an EagerTensor.

  File "D:\Anaconda\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 732, in numpy
    return self._cpu_nograd()._numpy()  # pylint: disable=protected-access

  File "D:\Anaconda\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 899, in _cpu_nograd
    return self._copy_nograd(context.context(), "CPU:0")

  File "D:\Anaconda\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py", line 847, in _copy_nograd
    new_tensor = self._copy_to_device(context=ctx._handle, device=device_name)

RuntimeError: Error copying tensor to device: CPU:0. Can't copy 37 bytes of a tensor into another with 32 bytes buffer.

 [Op:EagerPyFunc]
```

Does it have a specific thing only for CPU? 

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by ymodak** [comment] 2019-03-29 00:11
@shaolinkhoa The tutorial works fine when executed on cpu as well as gpu. Can you please try using [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true) and confirm? Thanks!

**Comment by shaolinkhoa** [comment] 2019-03-29 04:33
@ymodak Currently, the tutorial is using tensorflow for cpu as you can see in the code `install tensorflow==2.0.0-alpha0` so It runs perfectly on cpu.
If I change to `!pip install tensorflow-gpu==2.0.0-alpha0` ( I also change the setting to GPU) then I get the error at this line `tf_serialize_example(f0,f1,f2,f3)`

```
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-14-406ee79a7f52> in <module>()
----> 1 tf_serialize_example(f0,f1,f2,f3)

<ipython-input-13-3eb13f28c327> in tf_serialize_example(f0, f1, f2, f3)
      3     serialize_example,
      4     (f0,f1,f2,f3),  # pass these args to the above function.
----> 5     tf.string)      # the return type is `tf.string`.
      6   return tf.reshape(tf_string, ()) # The result is a scalar

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py in eager_py_func(func, inp, Tout, name)
    387     if `func` returns None.
    388   """
--> 389   return _internal_py_func(func=func, inp=inp, Tout=Tout, eager=True, name=name)
    390 
    391 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py in _internal_py_func(func, inp, Tout, stateful, eager, is_grad_func, name)
    276   if eager:
    277     result = gen_script_ops.eager_py_func(
--> 278         input=inp, token=token, Tout=Tout, name=name)
    279   else:
    280     if stateful:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_script_ops.py in eager_py_func(input, token, Tout, name)
     63       else:
     64         message = e.message
---> 65       _six.raise_from(_core._status_to_exception(e.code, message), None)
     66   # Add nodes to the TensorFlow graph.
     67   token = _execute.make_str(token, "token")

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

UnknownError: RuntimeError: Error copying tensor to device: CPU:0. Can't copy 15 bytes of a tensor into another with 8 bytes buffer.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 205, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 107, in __call__
    ret = self._func(*args)

  File "<ipython-input-7-60a59d21d73e>", line 10, in serialize_example
    'feature2': _bytes_feature(feature2),

  File "<ipython-input-3-56a99c09a572>", line 5, in _bytes_feature
    value = value.numpy() # BytesList won't unpack a string from an EagerTensor.

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 732, in numpy
    return self._cpu_nograd()._numpy()  # pylint: disable=protected-access

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 899, in _cpu_nograd
    return self._copy_nograd(context.context(), "CPU:0")

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 847, in _copy_nograd
    new_tensor = self._copy_to_device(context=ctx._handle, device=device_name)

RuntimeError: Error copying tensor to device: CPU:0. Can't copy 15 bytes of a tensor into another with 8 bytes buffer.

 [Op:EagerPyFunc]
```

**Comment by ymodak** [comment] 2019-04-11 22:27
@shaolinkhoa Apologies for the delay in response. Thanks for trying TF 2.0 alpha. I was able to reproduce reported behavior using TF 2.0 alpha gpu in google colab gpu environment.

**Comment by Ayush517** [comment] 2019-04-12 01:05
@ymodak I was also able to reproduce the issue. Looking into it.
In the meantime, I found another one like this #26951

**Comment by tensorflowbutler** [comment] 2019-04-26 13:04
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by shaolinkhoa** [comment] 2019-04-26 16:55
@tensorflowbutler I just tested on google colab with tensorflow-gpu. 
It works fine. 
When did you guys fix this? 
Do you know what is the problem?

**Comment by ymodak** [comment] 2019-04-30 21:17
Closing this issue since its resolved. Thanks!

**Closed by ymodak** 2019-04-30 21:17 UTC
Labels: 2.0.0-alpha0, type:bug/performance, type:docs

**Comment by suwoncjh** [comment] 2019-08-08 11:34
I also have the same problem in tensorflow-gpu==2.0.0-beta
