### ISSUE TITLE
Weights mismatch in model.load_weights does not rise a ValueError

### ISSUE THREAD

**Issue by ramonpeter** [tensorflow/tensorflow#38832] opened 2020-04-23 11:51 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Mojave 10.14.6
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7

**Describe the current behavior**
I constructed a model using the Keras API and save the weights of the model using
the function model.save_weight for later usage.

Later I rebuilt the model and loaded the weights using model.load_weights.
If during re-building the model I change parts of the architecture, for instance the number of layers. When trying to load the weights I get the reasoble error:

    ValueError: You are trying to load a weight file containing 4 layers into a model with 5 layers.

However, when I change the number of units, no ValueError is prompted.
Note, that this only happens if I have eager mode disabled with:

    tf.compat.v1.disable_eager_execution()

If eager mode is on it correctly outputs an error.
The question is, what does TensorFlow do if there is no error prompted? How does it deal with the mismatch of weights then?

**Standalone code to reproduce the issue**

    import tensorflow as tf
     tf.compat.v1.disable_eager_execution()
     from tensorflow.keras.models import Model
     from tensorflow.keras.layers import Input, Dense, LeakyReLU

    def DenseBlock(inputs, units, layers):
        x = inputs
        for i in range(layers):
                x = Dense(units)(x)
                x = LeakyReLU()(x)
        return x

    def model_1():
            # Input
            g_input = Input(shape=(10,))

            # Dense block
            x = DenseBlock(g_input, 12, 3)

            # Final layer
            g_output = Dense(1)(x)

            G = Model(g_input, g_output, name='Model_1')
            return G

    def model_2():
            # Input
            g_input = Input((10,))

            # Dense block
            x = DenseBlock(g_input, 10, 3)

            # Final layer
            g_output = Dense(1)(x)

            G = Model(g_input, g_output, name='Model_2')
            return G

    Model1 = model_1()
    Model2 = model_2()

    Model1.save_weights("weights_test.h5")
    Model2.load_weights("weights_test.h5")

Note that if you instead change the number of layers from 3 to 4 in model_2 then you get the expected ValueError:

    ValueError: You are trying to load a weight file containing 4 layers into a model with 5 layers.

 Also If you comment out disabling eager mode it also gives you the expected error:

    ValueError: Shapes (10, 10) and (10, 12) are incompatible

**Comment by ravikyram** [comment] 2020-04-24 07:09
@ramonpeter 

I have tried in colab with TF version 2.1.0 ,2.2.0-rc3 and was able to reproduce the issue.Please, find the [gist](https://colab.sandbox.google.com/gist/ravikyram/c6bf3e4c844abe7c40c9cd3e0dab93af/untitled814.ipynb) for changing layers from 3 to 4 in model_2 & [gist ](https://colab.sandbox.google.com/gist/ravikyram/273a64282b40630b6668d454382c6775/untitled815.ipynb) for disabling eager mode. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-04-25 05:18
@ramonpeter Agree that code is not throwing an error in eager mode when there is a mismatch in the number of nodes between `Model1` and `Model2`. However, it is an intended behavior. If you want the code to throw an error, then you can select `skip_mismatch` as follows. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/ef7dcbeb4dfd467889296ca9f0823b38/untitled815.ipynb).
`Model2.load_weights("weights_test.h5",skip_mismatch=True)`

In eager mode (static and dynamic shapes are same), shape check happens and throws the following error 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-a4a39fa80210> in <module>()
     41 
     42 Model1.save_weights("weights_test.h5")
---> 43 Model2.load_weights("weights_test.h5",skip_mismatch=False)

5 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
   1126     """
   1127     if not self.is_compatible_with(other):
-> 1128       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
   1129 
   1130   def most_specific_compatible_shape(self, other):

ValueError: Shapes (10, 10) and (10, 12) are incompatible
```
However, in graph mode (static and dynamic shapes are different), and there won't be any mismatch with the static shape. Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by ramonpeter** [comment] 2020-04-26 13:08
Okey. But how are the weights then loaded into the model? Obviously the number of weights disagree. So what is TensorFlow doing when I try to load the weights?

Thanks

**Comment by sachinprasadhs** [comment] 2021-05-26 14:33
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210526, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/1cd30cfe913150eac3aabf5d4c7e98e1/38832.ipynb). Thanks!

**Comment by tensorflowbutler** [comment] 2021-12-14 23:11
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Closed** 2022-01-11 17:46 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:keras, TF 2.1
