### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by ChaoYue0307** [tensorflow/tensorflow#27084] opened 2019-03-24 19:06 UTC
Just cannot import from tensorflow.contrib in 1.13.xx, where do the packages be moved to? Thanks

**Comment by shashvatshahi1998** [comment] 2019-03-25 05:55
Try to reinstall your tensorflow (prefer higher versions while installing it again).

**Comment by jvishnuvardhan** [comment] 2019-03-28 00:04
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-04-03 21:35
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-03 21:35 UTC
Labels: stat:awaiting response, type:build/install

**Comment by feistar** [comment] 2019-08-06 13:01
I have the same problem...tried reinstall but not working
