### ISSUE TITLE
non_max_suppression is on CPU?

### ISSUE THREAD

**Issue by MaskVulcan** [tensorflow/tensorflow#16148] opened 2018-01-16 08:21 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
     Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
      Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
      binary(By pip)
- **TensorFlow version (use command below)**:
      1.4.1
- **Python version**: 
      3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
    8.0.61/6.0.21
- **GPU model and memory**:
    GTX 1080 Ti, 11172MiB
- **Exact command to reproduce**:
     python main.py

### Describe the problem
    
I train my RFCN by tensorflow. My project need very high speed. So I use the profile and I find that non_max_suppression is on CPU? Is there a GPU version?I think if you calculate all pairs of boxes IOU first, then just for-loop once will ultimately boost speed, there have some trick in it, just see the source code in [https://github.com/rbgirshick/py-faster-rcnn/tree/master/lib/nms](https://github.com/rbgirshick/py-faster-rcnn/tree/master/lib/nms). I think cuda version of NMS is faster than CPU version.

**Comment by qmick** [comment] 2018-01-16 13:30
Currently TensorFlow has only CPU version NMS, see #7511.

**Comment by poxvoculi** [comment] 2018-01-16 19:33
closing as duplicate of #7511

**Closed by poxvoculi** 2018-01-16 19:33 UTC
