### ISSUE TITLE
keras and tf.keras behave differently with custom loss function and fit_generator

### ISSUE THREAD

**Issue by jutanke** [tensorflow/tensorflow#25779] opened 2019-02-15 11:49 UTC
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0
- Python version: 3.7.1
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0 / 7.4.2
- GPU model and memory: GTX 1080 ti
- Keras version: 2.2.4

**Describe the current behavior**
I am using Keras bundled with tensorflow. When I apply my own (rather obscure) loss I get a **NotFoundError**:
```
NotFoundError: Resource __per_step_7/_tensor_arraysloss/reshape_loss/map/TensorArray_1_1/N10tensorflow11TensorArrayE does not exist.
	 [[{{node training/Adam/gradients/loss/reshape_loss/map/while/TensorArrayReadV3_1_grad/TensorArrayGrad/TensorArrayGradV3}}]]
	 [[training/Adam/gradients/b_count_6/_233]]
```
when I use `fit_generator`, but when I use `fit` everything works ok. However, when I use vanilla Keras, both methods work just fine.

As a side question: my loss is rather slow, can someone give me some pointers in how to improve performance?

**Describe the expected behavior**
I would expect `fit_generator` to work just the same as in the vanilla-keras version or in the normal `fit` version.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
``` python
import numpy as np
import tensorflow as tf
# from tensorflow.keras import Input, Model
# from tensorflow.keras.layers import Dense, Flatten, Reshape
from keras import Input, Model
from keras.layers import Dense, Flatten, Reshape


def get_limb_lengths(person, limbs):
    """
    :param person: [ J * 3 ]
    :param limbs: {tf.constant} [ (a, b), (b, c), ... ]
    :return:
    """
    person = tf.reshape(person, (-1, 3))
    distances = tf.map_fn(
        lambda limb: tf.sqrt(
            tf.reduce_sum(
                tf.square(person[limb[0]] - person[limb[1]]))),
        limbs,
        dtype=tf.float32
    )
    return distances


def mean_limb_length_per_sequence(y_true, y_pred, limbs):
    """
    :param y_true: (n_frames, x J * 3)
    :param y_pred: (n_frames, x J * 3)
    :param limbs: {tf.constant}
    :return:
    """
    diff = tf.map_fn(
        lambda x:
        tf.reduce_mean(
            tf.abs(get_limb_lengths(x[0], limbs) -
                   get_limb_lengths(x[1], limbs))),
        (y_true, y_pred),
        dtype=tf.float32
    )
    return diff


def mean_limb_length_on_batch(y_true, y_pred, limbs):
    """ This one is optimized for CMU-MoCap
    :param y_true: (batchsize x n_frames x J * 3)
    :param y_pred: (batchsize x n_frames x J * 3)
    :return:
    """
    loss = tf.map_fn(
        lambda x: tf.reduce_mean(
            mean_limb_length_per_sequence(x[0], x[1], limbs)),
        (y_true, y_pred),
        dtype=tf.float32
    )
    return tf.reduce_mean(loss)


def mean_limb_length(y_true, y_pred):
    """ This one is optimized for CMU-MoCap
    :param y_true: (batchsize x n_frames x J * 3)
    :param y_pred: (batchsize x n_frames x J * 3)
    :return:
    """
    limbs = tf.constant([
        (0, 1), (1, 2), (2, 3), (3, 4)
    ])
    return mean_limb_length_on_batch(y_true,
                                     y_pred,
                                     limbs)


bs = 512
f1 = 20
f2 = 2
J = 5
dim = 3
X = np.random.random((bs, f1, J * dim))
Y = np.random.random((bs, f2, J * dim))

def create_gen():
    while True:
        yield X, Y

gen = create_gen()

inputs = Input(shape=X.shape[1:])
x = Flatten()(inputs)
x = Dense(f2 * J * dim)(x)
x = Reshape((f2, J, dim))(x)

model = Model(inputs=inputs, outputs=x)
model.summary()

optimizer = 'adam'

model.compile(loss=mean_limb_length,
              metrics=[mean_limb_length],
              optimizer=optimizer)

# model.fit(X, Y)
model.fit_generator(generator=gen,
                    validation_data=gen,
                    steps_per_epoch=10,
                    validation_steps=3,
                    epochs=5)
```

**Other info / logs**
Error message:
```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-3-1232392e144b> in <module>
    104                     steps_per_epoch=10,
    105                     validation_steps=3,
--> 106                     epochs=5)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1500         use_multiprocessing=use_multiprocessing,
   1501         shuffle=shuffle,
-> 1502         initial_epoch=initial_epoch)
   1503 
   1504   def evaluate_generator(self,

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, **kwargs)
    191       progbar.on_batch_begin(step, batch_logs)
    192 
--> 193       batch_outs = batch_function(*batch_data)
    194       if not isinstance(batch_outs, list):
    195         batch_outs = [batch_outs]

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight, reset_metrics)
   1259       else:
   1260         self._make_fit_function()
-> 1261         outputs = self._fit_function(ins)  # pylint: disable=not-callable
   1262 
   1263     if reset_metrics:

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py in __call__(self, inputs)
   3080 
   3081     fetched = self._callable_fn(*array_vals,
-> 3082                                 run_metadata=self.run_metadata)
   3083     self._call_fetch_callbacks(fetched[-len(self._fetches):])
   3084     return nest.pack_sequence_as(self._outputs_structure,

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1438           ret = tf_session.TF_SessionRunCallable(
   1439               self._session._session, self._handle, args, status,
-> 1440               run_metadata_ptr)
   1441         if run_metadata:
   1442           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    542             None, None,
    543             compat.as_text(c_api.TF_Message(self.status.status)),
--> 544             c_api.TF_GetCode(self.status.status))
    545     # Delete the underlying status object from memory otherwise it stays alive
    546     # as there is a reference to status from this from the traceback due to
NotFoundError: Resource __per_step_7/_tensor_arraysloss/reshape_loss/map/TensorArray_1_1/N10tensorflow11TensorArrayE does not exist.
	 [[{{node training/Adam/gradients/loss/reshape_loss/map/while/TensorArrayReadV3_1_grad/TensorArrayGrad/TensorArrayGradV3}}]]
	 [[training/Adam/gradients/b_count_6/_233]]
```

**Comment by ymodak** [comment] 2019-02-15 19:22
I was able to execute your code snippet using ```fit_generator``` successfully using tf.keras and keras in TF 1.13.0-rc1 and TF 1.12.0
Can you please execute your code using [google.colab.sandbox](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true) and confirm?
Thanks!

**Comment by jutanke** [comment] 2019-02-18 07:41
Thank you for your help, the code works fine in the colab.sandbox. I compiled tf myself so that I can use it with Cuda 10 and Python 3.7 so I assume something goes wrong there. I will investigate my setup and report back in case something shows up.

**Comment by ymodak** [comment] 2019-02-19 22:10
You are welcome. I would like to tell you that TensorFlow 1.13.0-rc2 has been released!
It comes with GPU binaries built with CUDA 10 and also supports Python 3.7 
You may want to give it a try. I will close this issue since we cannot reproduce it and works fine with colab. Feel free to reopen if have any further problems. Thanks!

**Closed** 2019-02-19 22:11 UTC
Labels: comp:keras
