### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tensorflow#4200] opened 2016-09-05 08:29 UTC
The module is `models/rnn/translate`
I'm running

```
$ python -c 'import tensorflow as tf; print tf.__version__'
0.10.0rc0
```

I did the training:

```
python translate.py --data_dir /mnt/ft1/translate/ --train_dir /mnt/ft1/translate/ --size=256 --num_layers=2 --steps_per_checkpoint=50
```

and then run

```
python translate.py --decode --data_dir /mnt/ft1/translate/ --train_dir /mnt/ft1/translate/
```

```
Traceback (most recent call last):
  File "translate.py", line 290, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 285, in main
    decode()
  File "translate.py", line 222, in decode
    model = create_model(sess, True)
  File "translate.py", line 131, in create_model
    dtype=dtype)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

My data dir looks like

```
-rw-rw-r-- 1 ubuntu ubuntu   21393583 Aug 31 15:21 dev-v2.tgz
-rw-rw-r-- 1 ubuntu ubuntu 3789873031 Aug 31 15:21 giga-fren.release2.en
lrwxrwxrwx 1 ubuntu ubuntu         30 Aug 31 15:17 giga-fren.release2.en.gz -> giga-fren.release2.fixed.en.gz
-rw-rw-r-- 1 ubuntu ubuntu 1214224978 Aug 30 19:55 giga-fren.release2.fixed.en.gz
-rw-rw-r-- 1 ubuntu ubuntu 1380871453 Aug 29 21:43 giga-fren.release2.fixed.fr.gz
-rw-rw-r-- 1 ubuntu ubuntu 4565271815 Aug 31 15:19 giga-fren.release2.fr
lrwxrwxrwx 1 ubuntu ubuntu         30 Aug 31 15:13 giga-fren.release2.fr.gz -> giga-fren.release2.fixed.fr.gz
-rw-rw-r-- 1 ubuntu ubuntu 2380084216 Sep  2 11:29 giga-fren.release2.ids40000.en
-rw-rw-r-- 1 ubuntu ubuntu 1222033408 Aug 31 17:17 giga-fren.release2.ids40000.fr
-rw-r--r-- 1 ubuntu ubuntu     332974 Dec 13  2013 newstest2013.en
-rw-r--r-- 1 ubuntu ubuntu     393465 Dec 13  2013 newstest2013.fr
-rw-rw-r-- 1 ubuntu ubuntu     231941 Sep  2 11:29 newstest2013.ids40000.en
-rw-rw-r-- 1 ubuntu ubuntu     268151 Sep  2 11:29 newstest2013.ids40000.fr
-rw-rw-r-- 1 ubuntu ubuntu 2595102720 Aug 31 10:53 training-giga-fren.tar
-rw-rw-r-- 1 ubuntu ubuntu     343512 Aug 31 16:54 vocab40000.en
-rw-rw-r-- 1 ubuntu ubuntu     380736 Aug 31 16:11 vocab40000.fr
```

The `symlink` in the `data_dir` are due to https://github.com/tensorflow/tensorflow/issues/4122

**Comment by tatatodd** [comment] 2016-09-07 03:56
Somehow you've ended up with inconsistent versions of (at least) these two files:
```
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/seq2seq_model.py
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/translate.py
```

Note the following commit on Aug 10, which added the dtype argument to the seq2seq_model.Seq2SeqModel constructor:
https://github.com/tensorflow/tensorflow/commit/0e91b8b4db9c40bc8c45bcc69dd18e03d9f898a3

Based on the stack trace and error, it seems that your version of `translate.py` is after the Aug 10 commit, while your version of `seq2seq_model.py` is before the Aug 10 commit.  Note that version 0.10 was before the Aug 10 commit; I'm not sure how your files got out-of-sync.

Please re-open if this doesn't resolve your problem!

**Comment by gaurav5670** [comment] 2016-09-21 06:00
Hello,

I took latest code from github and still I am getting this error,

Preparing WMT data in /tmp
Creating 3 layers of 1024 units.
Traceback (most recent call last):
  File "translate.py", line 290, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 287, in main
    train()
  File "translate.py", line 152, in train
    model = create_model(sess, False)
  File "translate.py", line 131, in create_model
    dtype=dtype)
TypeError: __init__() got an unexpected keyword argument 'dtype'

As per your previous comments, I cross check my seq2seq_model.py and translate.py, both files are latest and have required changes to avoid this error.

Still I am facing this issue, can you look into this issue and re-open it?

**Comment by loretoparisi** [comment] 2016-09-21 07:27
@gaurav5670 I think it' the same error I get in my tests.

**Comment by gaurav5670** [comment] 2016-09-21 08:22
@loretoparisi , yes it is the same error, I commented "dtype=dtype" at line 131 in translate.py file, 
the error is gone, I am still running the tests. Will update again if I face any issues.

if you open seq2seq_model.py and check in construtor of Seq2SeqModel, it assign a default value to dtype at line number 59, 
def __init__(self,
               source_vocab_size,
               target_vocab_size,
               buckets,
               size,
               num_layers,
               max_gradient_norm,
               batch_size,
               learning_rate,
               learning_rate_decay_factor,
               use_lstm=False,
               num_samples=512,
               forward_only=False,
               dtype=tf.float32):

@tatatodd, can you please reopen this issue? As it persists with latest tensorflow github code also.

**Comment by tatatodd** [comment] 2016-09-21 16:46
@loretoparisi @gaurav5670 Can you provide the git commit hash of your sources?  `git rev-parse HEAD`

**Comment by gaurav5670** [comment] 2016-09-22 05:28
@tatatodd my git commit hash is ca1aa4ad2d4e011e8479319e10d73281a50f7560

**Comment by gaurav5670** [comment] 2016-09-22 05:56
@tatatodd I have tested with git commit hash ca1aa4ad2d4e011e8479319e10d73281a50f7560 and still the problem is present. Getting the same error.

**Comment by tatatodd** [comment] 2016-09-23 17:05
@loretoparisi @gaurav5670

I believe this is the problem.  You've installed tensorflow from source in some location (say dir A), but you also have a default version of tensorflow installed under some other location (say dir B).  Then you run translate.py directly from the sources under A, but imports are being resolved from B.  Your sources under A are up-to-date, but the default installation under B has old code, which causes the failure.

This line from each of your stacktraces is the reason for my suspicion:
```
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
```

So your default installation B is under `/usr/local/lib/python2.7/dist-packages/tensorflow/...`, which is different from where you installed your sources.

To confirm, you can look at the following file.  I'm suspecting you'll see an old file, that doesn't include `dtype` in the `__init__` function.
```
/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/seq2seq_model.py
```

I am not a python expert, but I believe you can fix this via the PYTHONPATH environment variable.  Just set it to point at your sources (i.e. dir A), so that imports will be resolved via A instead of B.
https://docs.python.org/2/using/cmdline.html#envvar-PYTHONPATH

Let me know if that helps.

**Comment by gaurav5670** [comment] 2016-09-28 05:18
@tatatodd, PYTHONPATH is a export variable where python looks for all module files. If I export this to my tensorflow src folder path then I start getting error for all other python modules like numpy etc.
So, this can't work because it will change the default path where python looks for other modules.

**Comment by tatatodd** [comment] 2016-09-28 05:31
@gaurav5670 First off, did you confirm that the following file to confirm the code-mismatch issue?
```
/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/translate/seq2seq_model.py
```

If this is indeed the problem, it seems to me that you can set PYTHONPATH as follows:
```
# 1) Try this first
export PYTHONPATH=/path/to/your/sources:$PYTHONPATH

# 2) If the above doesn't work, try setting dist-packages explicitly, *after* your sources.
export PYTHONPATH=/path/to/your/sources:/usr/local/lib/python2.7/dist-packages:$PYTHONPATH
```

With (1) we're telling python to first resolve imports from your sources, falling back on whatever your original PYTHONPATH was set to.  With (2) we're telling python to first resolve from your sources, then from dist-packages, and finally from whatever your original PYTHONPATH was set to.

We're basically trying to set things up so that your sources take precedence over everything else.

**Comment by gaurav5670** [comment] 2016-09-28 08:08
@tatatodd  following is the list of files in my /usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/

/usr/local/lib/python2.7/dist-packages/tensorflow/models/rnn/
├── __init__.py
├── __init__.pyc
├── linear.py
├── linear.pyc
├── rnn_cell.py
├── rnn_cell.pyc
├── rnn.py
├── rnn.pyc
├── seq2seq.py
└── seq2seq.pyc

0 directories, 10 files

By default, on a new terminal environment on my ubuntu 16.04, PYTHONPATH is empty.
I tried setting export PYTHONPATH =  /usr/local/lib/python2.7/dist-packages/tensorflow/:$PYTHONPATH
and 
export PYTHONPATH =  /path/to/mysoruces/tensorflow/:$PYTHONPATH, where tensorflow is my sources directory head.

I am guessing that this might be problem with tensorflow binary release which I have downloaded from 
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#test-the-tensorflow-installation

And my machine does not have a GPU so I downloaded a non-GPU version of tensorflow using following commands,

export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl
sudo pip install --upgrade $TF_BINARY_URL

**Comment by tatatodd** [comment] 2016-10-07 00:47
@loretoparisi @gaurav5670 
The files to look at are these:
```
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/seq2seq_model.py
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/translate.py
```

These files seem to be out-of-sync somehow.  Perhaps the easiest thing to do is to uninstall everything, and install the latest version of TensorFlow:
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#download-and-setup

Let me know if you still have issues.

**Comment by loretoparisi** [comment] 2016-10-12 14:31
@tatatodd thank you please wait let me check again the whole process.

**Comment by gaurav5670** [comment] 2016-10-13 17:30
@loretoparisi with latest version of tensorflow i.e r0.11 the error is gone.
I could not reproduce this error now. Thanks for your support. You can close this bug now.

**Comment by jart** [comment] 2016-10-15 08:55
The TensorFlow is happy to be of service.

**Closed by jart** 2016-10-15 08:55 UTC

**Comment by loretoparisi** [comment] 2016-10-17 07:33
@jart thanks a lot!

**Comment by chitro** [comment] 2016-12-29 03:17
I'm seeing a similar issue with TF on native Windows 10 (TF 0.12) for dense_shape while running the wide_n_deep_tutorial shipped with the package. I pulled the latest version of TF as well but still didn't resolve the problem:

TypeError: __init__() got an unexpected keyword argument 'dense_shape'

Cannot comment whether this happens on Unix also. I've python 3.5.2 installed. Any ideas?

**Comment by jart** [comment] 2016-12-29 04:46
I recommend opening a new issue so it can go through triage. Windows support is very new.

**Comment by chitro** [comment] 2016-12-29 15:58
Ok thanks.
