### ISSUE TITLE
pip missing all versions beyond 1.13.1

### ISSUE THREAD

**Issue by Directory** [tensorflow/tensorflow#33838] opened 2019-10-30 04:08 UTC
- Rasbian 9 buster
- TensorFlow installed from binary
- TensorFlow version: 1.14.1
- Python version: 3.7
- Installed using pip

I need tensorflow version 1.14.0 specifically. Windows has the version I'm looking for. But when i run it on my pi pip says that 1.14.0 is missing and it only lists possible version numbers of 1.11.0, 1.12.0, and 1.13.1.

**sudo python3.7 -m pip install tensorflow==1.14.0**

**Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: 0.11.0, 1.12.0, 1.13.1)
ERROR: No matching distribution found for tensorflow==1.14.0**

**Comment by nikochiko** [comment] 2019-10-30 07:09
I tried it in my ubuntu wsl. 
It started installing with the command ```pip install tensorflow==1.14.0```
I got the following when I tried your syntax.

```python -m pip install tensorflow==1.14.0
Collecting tensorflow==1.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.14.0```

**Comment by nikochiko** [comment] 2019-10-30 07:14
I am able to install successfully with the command ```python3 -m pip install tensorflow==1.14.0``` in my ubuntu1804 wsl. I will try in raspbian.

**Comment by nikochiko** [comment] 2019-10-30 07:20
Try running the command ```python -m pip search tensorflow``` from your raspbian.

**Comment by Directory** [comment] 2019-10-30 17:47
> Try running the command `python -m pip search tensorflow` from your raspbian.
> It should probably be some sort of compatibility issues.
> Are you able to install from the links provided in https://www.tensorflow.org/install/pip at the bottom of the page?
> 
> Python 3, Pi0 or Pi1	https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-1.14.0-cp34-none-linux_armv6l.whl
> Python 3, Pi2 or Pi3	https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-1.14.0-cp34-none-linux_armv7l.whl

Do these precompiled wheels work for python 3.7? It says 34

**Comment by mihaimaruseac** [comment] 2019-10-30 18:25
Official python 3.7 support was added only in 1.13 and later.

**Comment by Directory** [comment] 2019-10-30 21:11
im getting this error when running `sudo python3 -m pip install https://storage.googleapis.com/tensorflow/raspberrypi/tensorflow-1.14.0-cp34-none-linux_armv7
l.whl`:


`ERROR: tensorflow-1.14.0-cp34-none-linux_armv7l.whl is not a supported wheel on this platform.`

**Comment by mihaimaruseac** [comment] 2019-10-30 21:17
Doe `cp34-none-linux_armv71` show up in `pip debug --verbose`?

**Comment by Directory** [comment] 2019-10-30 21:28
this was what was printed. Something similar but not exactly.

`pip debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 19.3.1 from /home/pi/.local/lib/python3.7/site-packages/pip (python 3.7)
sys.version: 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0]
sys.executable: /usr/bin/python3.7
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
Compatible tags: 29
  cp37-cp37m-manylinux2014_armv7l
  cp37-cp37m-linux_armv7l
  cp37-abi3-manylinux2014_armv7l
  cp37-abi3-linux_armv7l
  cp37-none-manylinux2014_armv7l
  cp37-none-linux_armv7l
  cp36-abi3-manylinux2014_armv7l
  cp36-abi3-linux_armv7l
  cp35-abi3-manylinux2014_armv7l
  cp35-abi3-linux_armv7l
  cp34-abi3-manylinux2014_armv7l
  cp34-abi3-linux_armv7l
  cp33-abi3-manylinux2014_armv7l
  cp33-abi3-linux_armv7l
  cp32-abi3-manylinux2014_armv7l
  cp32-abi3-linux_armv7l
  py3-none-manylinux2014_armv7l
  py3-none-linux_armv7l
  cp37-none-any
  cp3-none-any
  py37-none-any
  py3-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any`

**Comment by mihaimaruseac** [comment] 2019-10-30 22:02
This means that that specific pip won't be able to load/install. Due to toolchain differences.

You might need to compile from source

**Comment by Directory** [comment] 2019-10-30 22:05
if i compile from source, wouldn't that just give me the same .whl that is downloadable from the links in the website? What difference would it make?

**Comment by Directory** [comment] 2019-10-31 08:43
i have been able to install it by simply wget'ing the whl and renaming from tensorflow-1.14.0-cp34-none-linux_armv7l.whl to tensorflow-1.14.0-cp37-none-linux_armv7l.whl. with the only needed difference being the python version in the filename, as it would comply with pip. But I'm now experiencing a new issue when importing that i will make a separate issue on. #33872

**Comment by mihaimaruseac** [comment] 2019-10-31 15:36
The tags in the filename specify C++ ABI compatibility. Compiling from source will ensure you get all binaries that will run on your system.

Yes, you can install it (that is, unzip the files in the wheel) if you rename. But you can't use it without crashes and errors.

**Comment by Directory** [comment] 2019-10-31 17:11
https://github.com/tensorflow/tensorflow/issues/33872#issuecomment-548476622

**Comment by emimarz** [comment] 2019-12-17 01:09
I have mac and I doing a fresh install and I have the same error
```
pip3  install tensorflow==1.14
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14 (from versions: none)
ERROR: No matching distribution found for tensorflow==1.14

pip3 install --upgrade pip
Requirement already up-to-date


```

**Comment by mihaimaruseac** [comment] 2019-12-17 01:47
We haven't released any pip package for 3.8

**Comment by tensorflowbutler** [comment] 2021-02-01 14:10
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Comment by KopfKrieg** [comment] 2021-02-01 14:57
The issue is still relevant since there are no working Tensorflow 2.x builds for Python 3.7 (or newer) on the Raspberry Pi.

**Comment by mihaimaruseac** [comment] 2021-02-01 16:09
Please open a new issue for that. At the moment we no longer have anyone working on the RPi builds, instead we recommend using TFLite.

Closing this issue as it seems to have been caused by a very old `pip` and is old.

**Closed by mihaimaruseac** 2021-02-01 16:09 UTC
Labels: TF 1.14, subtype: raspberry pi, type:build/install
