### ISSUE TITLE
Exponential decay - missing argument step()

### ISSUE THREAD

**Issue by PN12** [tensorflow/tensorflow#34128] opened 2019-11-09 21:33 UTC
I am facing the below error while using the exponential decay in Adam optimizer - 

**Code** 

`lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate = 0.0001,
    decay_steps=100000,
    decay_rate=0.96,
    staircase=True)

model = sm.Unet(
    'resnet50', 
    classes=4,
    input_shape=(320, 480, 3),
    activation='sigmoid'
)
model.compile(optimizer = Adam(lr = lr_schedule) ,  loss      = bce_dice_loss, metrics   = [dice_coef])
`

**Error** 
TypeError: __call__() missing 1 required positional argument: 'step'

What am I missing?
Please suggest.

**Comment by DarkGeekMS** [comment] 2019-11-10 15:04
Not sure which TF version you are using, but I think the problem is with the "lr" parameter in Adam optimizer.
The lr parameter is only there for backward compatibility and it doesn't support learning rate schedule.

You should use learning_rate parameter instead as follows:

`model.compile(optimizer = Adam(learning_rate = lr_schedule) , loss = bce_dice_loss, metrics = [dice_coef])`

Hope this works!

**Comment by PN12** [comment] 2019-11-10 22:22
Okay, thanks. 
For the moment, I have found an alternative , but this error is within function ExponentialDecay - 
I dig deeper into its documentation and there is an argument **Step** which is causing this error.
Unfortunately, I could not understand it from the documentation.
Thanks

**Comment by DarkGeekMS** [comment] 2019-11-10 23:32
**Step** argument is the number of global steps of the optimizer, it's passed to the **call** method of the learning rate schedule to calculate the current learning rate.
It's supposed to be done implicitly by the optimizer during training, however good thing you find an alternative to your problem.

**Comment by PN12** [comment] 2019-11-11 01:25
Yes, this is the doubt here - **Step** is an implicit argument, then how do we alter it to get the execution correct.

**Comment by ravikyram** [comment] 2019-11-11 08:08
@PN12 

Which TensorFlow version you are using?.Thanks!

**Comment by PN12** [comment] 2019-11-11 12:23
Version is '1.15.0'

**Comment by jvishnuvardhan** [comment] 2019-11-13 23:10
@PN12 Can you please share a simple standalone code to reproduce the issue? Thanks!

**Comment by PN12** [comment] 2019-11-16 18:10
Okay, I will share the same, at the moment an alternative has been used as a fix.

**Comment by jvishnuvardhan** [comment] 2019-12-03 20:19
@PN12 Can you please share a simple standalone code to reproduce the issue? Thanks!

Please close the issue If the issue was already resolved. Thanks!

**Comment by PN12** [comment] 2019-12-04 07:12
@jvishnuvardhan 

Closing the issue at the moment.

Thanks.

**Closed** 2019-12-04 18:24 UTC
Labels: TF 1.15, comp:keras, type:support

**Comment by rzou15** [comment] 2020-06-09 04:31
How did you solve this? What is your alternative? I met the exactly same error.

**Comment by AndreyStille** [comment] 2021-02-17 00:06
> @ghost
> How did you solve this? What is your alternative? I met the exactly same error.
> 
> > Okay, thanks.
> > For the moment, I have found an alternative , but this error is within function ExponentialDecay -
> > I dig deeper into its documentation and there is an argument **Step** which is causing this error.
> > Unfortunately, I could not understand it from the documentation.
> > Thanks

Hi, have you found the solution? I have same error.

**Comment by JiaqingFu** [comment] 2022-04-06 07:23
I have the same problem

**Comment by 3g0r** [comment] 2023-08-30 02:03
@AndreyStille @JiaqingFu

Try this
```
from tensorflow.python.keras.optimizers import adam_v2
learning_rate_fn = adam_v2.optimizer_v2.learning_rate_schedule.ExponentialDecay(
      initial_learning_rate=initial_learning_rate,
      decay_steps=decay_steps,
      decay_rate=decay_rate,
)
```

it works for tensorflow 2.12.0
