### ISSUE TITLE
Camera is showing as half screen while running the application (Android)

### ISSUE THREAD

**Issue by prasanna532** [tensorflow/tensorflow#21447] opened 2018-08-07 14:16 UTC
Android - Oneplus 3

**Comment by tensorflowbutler** [comment] 2018-08-08 01:52
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by prasanna532** [comment] 2018-08-08 04:36
OS Platform and Distribution - Windows
TensorFlow installed from - https://github.com/tensorflow/tensorflow.git
TensorFlow version - 1.10.0rc
Bazel version - NA
CUDA/cuDNN version - NA
GPU model and memory -NA
Exact command to reproduce - NA
Mobile device - OnePlus3, Mi, Samsung J6, Samung J7

**Comment by rohan100jain** [comment] 2018-08-09 01:26
Can you please elaborate and provide explicit details of the problem you're facing. Explain to us what you tried to do, what the issue was and some error logs etc.

**Comment by prasanna532** [comment] 2018-08-09 08:09
@rohan100jain , There are no errors actually when i open the app application to detect camera is showing only 70 percent to the screen, like camera is not opening with fullscreen

**Comment by prasanna532** [comment] 2018-08-14 09:34
Please see the screenshot below 

![screenshot_20180814-150028](https://user-images.githubusercontent.com/25867821/44084022-38a6fd52-9fd3-11e8-8ff2-089f572f0064.jpg)

**Comment by prasanna532** [comment] 2018-08-14 09:35
Black screen is appearing like in the image.

**Comment by tensorflowbutler** [comment] 2018-08-31 15:02
Nagging Assignee @rohan100jain: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-16 02:28
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:49
Nagging Assignee @rohan100jain: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rohan100jain** [comment] 2018-10-21 20:30
Which app are you running? I'm not sure what you mean by "the application" here

**Comment by tensorflowbutler** [comment] 2018-11-05 18:58
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by harshini-gadige** [comment] 2018-11-14 22:01
Closing this since we didn't get any response from the user. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2018-11-14 22:01 UTC
Labels: stat:awaiting response, type:support

**Comment by Musasshi90** [comment] 2019-02-13 04:27
@rohan100jain ,he is referring to TFLite Demo app. In this app, he wants the camera to cover full screen and don't want the blank space at the bottom of the camera.

**Comment by true21** [comment] 2019-08-19 12:04
@prasanna532 Did you find any solution?

**Comment by prasanna532** [comment] 2019-08-19 17:01
@true21 ya i had found the solution you need to increase the pixel then it is coming full screen but the problem it not finding the  objects quickly and it is hanging some times.
