### ISSUE TITLE
New project inquiries

### ISSUE THREAD

**Issue by inoxstasy** [tensorflow/tensorflow#38318] opened 2020-04-07 15:13 UTC
Hello :) 

I am totally new at programming, and wanted some advice. 
I want to create a program using the google maps api. 

Is Python the adequate programming language to use? 

Thanks in advance for your answer :)

**Comment by tomasvr** [comment] 2020-04-07 23:37
Hey inoxstasy, you are currently posting on a platform that is solely for issues related to the TensorFlow application and not at all meant for general programming questions like this. Try posting your question on https://www.reddit.com/r/learnprogramming/ or https://stackoverflow.com/. Good luck with your project.

**Comment by Saduf2019** [comment] 2020-04-08 04:40
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Hence moving this to closed status.

**Closed by Saduf2019** 2020-04-08 04:40 UTC
Labels: type:docs
