### ISSUE TITLE
time to restore saved model increases over time 

### ISSUE THREAD

**Issue by abieler** [tensorflow/tensorflow#14155] opened 2017-11-01 15:22 UTC
### System information
- Manjaro Linux
- TensorFlow installed with pip:
- TensorFlow version: v1.3.0-rc2-20-g0787eee 1.3.0:
- Python version: 3.6.2 
- CUDA/cuDNN version: 8.0.61-3 / 7.0.3-1
- GPU model and memory: GeForce GTX 1080 (8 GB)

### Describe the problem
Executing the code below in a loop slows down linearly with
number of iteration as can be seen in the figures below.
(The use case being a long running app where different models
are loaded (multiple times) depending on user inputs) 

```python
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.25)
config = tf.ConfigProto(gpu_options=gpu_options)

with tf.Session(config=config) as sess:
    saver = tf.train.import_meta_graph(modelname)
    saver.restore(sess, tf.train.latest_checkpoint("./"))
```

### Source code / logs
Reproducible code and plots of the time increase can be found here:
[https://www.dropbox.com/s/rgbqp9z3m5vnr9d/test.zip?dl=1](url)

To reproduce do the following from withing the extracted zip archive:
```
python train_model.py
python test_a.py
```

![import_metagraph](https://user-images.githubusercontent.com/7083141/32281142-4b2c3eec-bf1e-11e7-85f0-5da5af5e4135.png)

![saver_restore](https://user-images.githubusercontent.com/7083141/32281147-4f1244d4-bf1e-11e7-8126-28eb01df3c8a.png)

**Comment by jart** [comment] 2017-11-01 15:48
I really love it when people take the time to make these plots to demonstrate performance issues. Thank you. The dropbox link seems broken. Is there any chance you could just copy and paste the whole script into a comment here?

**Comment by abieler** [comment] 2017-11-01 16:00
It is not a single script unfortunately. The link above works for me if I copy/paste it into my browsers address bar. When clicking on it it seems dead, as you said. Can you try the copy/paste approach with the link?

**Comment by jart** [comment] 2017-11-01 16:16
OK that works. But this is so much code. Is there any way you could make this more digestible? Also is there any chance the growth is due to writing a whole bunch of files being written and latest_checkpoint needs to crawl the whole directory?

**Comment by abieler** [comment] 2017-11-01 16:26
Ok, condensed it down to one script. There is only one checkpoint. So no dir crawling.


```python
import time
import tensorflow as tf
import numpy as np

def rebuild_model(modelname):
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction = 0.25)
    config = tf.ConfigProto(gpu_options=gpu_options)
    with tf.Session(config=config) as sess:
        saver = tf.train.import_meta_graph(modelname + ".meta")
        saver.restore(sess, tf.train.latest_checkpoint("./"))
        a = 1 + np.random.randn()
        

nVars = 10 
nExamples = 100
nClasses = 2
nEpochs = 100 

X = np.random.randn(nExamples, nVars)
y = np.random.randint(0, nClasses, nExamples)

nHidden1 = 50 
nHidden2 = 20


# Build model
graph = tf.Graph()
with graph.as_default():
    x_tf = tf.placeholder(tf.float32, shape=(None, nVars), name="x_tf")
    y_tf = tf.one_hot(y, nClasses, name="y_tf")

    w1 = tf.Variable(tf.random_normal([nVars, nHidden1]))
    b1 = tf.Variable(tf.zeros(nHidden1))
    a1 = tf.nn.relu(tf.matmul(x_tf, w1) + b1)

    w2 = tf.Variable(tf.random_normal([nHidden1, nHidden2]))
    b2 = tf.Variable(tf.zeros(nHidden2))
    a2 = tf.nn.relu(tf.matmul(a1, w2) + b2)

    w_out = tf.Variable(tf.random_normal([nHidden2, nClasses]))
    b_out = tf.Variable(tf.zeros(nClasses))
    logits = tf.add(tf.matmul(a2, w_out), b_out, name="logits")
    yhat = tf.nn.softmax(logits, name="yhat")


    loss = tf.reduce_mean(
           tf.nn.softmax_cross_entropy_with_logits(
           labels=y_tf, logits=logits))

    optimizer = tf.train.GradientDescentOptimizer(0.05).minimize(loss)
    saver = tf.train.Saver()

# Train model
with tf.Session(graph=graph) as sess:
    tf.global_variables_initializer().run()

    for step in range(nEpochs+1):
        _, current_loss, prediction, logi = sess.run([optimizer, loss, yhat, logits], feed_dict={x_tf:X})
        if (step % 10 == 0):
            accuracy = np.mean(tf.equal(tf.argmax(prediction, 1), y).eval())
            print(" - %i\tLoss: %.4f\tAccuracy: %.4f" %(step, current_loss, accuracy))

    save_path = saver.save(sess, "feedforward.ckpt")


# loop 
dt = []
for i in range(100):
    t0 = time.time()
    result = rebuild_model("feedforward.ckpt")
    t1 = time.time()
    print(t1 - t0)
    dt.append(t1 - t0)


plt.figure()
plt.plot(dt)
plt.ylabel("execution time [s]")
plt.xlabel("iteration")
plt.title("saver.restore()")

plt.show()
input()

```

**Comment by jart** [comment] 2017-11-01 17:23
I see the problem. You need to call `tf.reset_default_graph()` before importing the meta graph again. This behavior is non-obvious and surprising, I agree. It's one of those things where we wish we could go back in time and change.

I'm closing this issue out because I think the problem is resolved. However I would like to discuss a little more about what we could have done better. Maybe we could update the doc for tf.train.import_meta_graph? Maybe there's some way we could display a warning? It might help if you could share more information about what you're trying to accomplish with this technique.

**Closed by jart** 2017-11-01 17:23 UTC
Labels: stat:awaiting response

**Comment by abieler** [comment] 2017-11-01 17:45
Thanks! I stumbled upon this when writing unit tests, where each test rebuilds the (a) graph from disk.

**Comment by jart** [comment] 2017-11-01 18:02
That's great that you're testing the boundaries of TensorFlow for us. If you discover anything else in the future, please bring it to our attention. We're always looking for opportunities to make TensorFlow better.

**Comment by abieler** [comment] 2017-11-01 18:16
I do have another problem with unittests and tensorflow. Every unit test by itself runs successfully, but when using pytest to run them all I get errors. It is quite a lot of code though, when I condensed it down to a somewhat manageable amount I ll open a separate issue. Thanks for the very quick response!

**Comment by jart** [comment] 2017-11-01 19:04
That might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). I usually run tests using Bazel. For example `bazel test //tensorflow/python/...`
