### ISSUE TITLE
`vectorized_map` does not support `IndexedSlices`

### ISSUE THREAD

**Issue by JiahaoYao** [tensorflow/tensorflow#29984] opened 2019-06-20 00:33 UTC
I am trying to use `tf.vectorized_map`. But, in my network, I have some weights for `tf.nn.embedding_lookup`. I find when one tries to get the gradient, the gradients for `embedding` parts become `IndiceSlices`. 

When the code meets this: `                batch_grad = tf.vectorized_map(lambda x: tf.gradients(x, network_variables), loss)
`, it is stuck there and have the error.

```
    batch_grad = tf.vectorized_map(lambda x: tf.gradients(x, network_variables), loss)
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 338, in vectorized_map
    return pfor(loop_fn, batch_size)
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 164, in pfor
    return f()
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 161, in f
    return _pfor_impl(loop_fn, iters, parallel_iterations=parallel_iterations)
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/control_flow_ops.py", line 214, in _pfor_impl
    outputs.append(converter.convert(loop_fn_output))
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1175, in convert
    output = self._convert_helper(y)
  File "/anaconda3/envs/dl/lib/python3.7/site-packages/tensorflow/python/ops/parallel_for/pfor.py", line 1208, in _convert_helper
    assert isinstance(y, ops.Tensor), y
AssertionError: IndexedSlices(indices=Tensor("compute_gradients/loop_body/gradients/predict_actions/network/embeddings/embedding_lookup_grad/Reshape_1:0", shape=(?,), dtype=int32), values=Tensor("compute_gradients/loop_body/gradients/predict_actions/network/embeddings/embedding_lookup_grad/Reshape:0", shape=(?, 10), dtype=float32), dense_shape=Tensor("compute_gradients/loop_body/gradients/predict_actions/network/embeddings/embedding_lookup_grad/Cast:0", shape=(2,), dtype=int32))
```

I think the error here is because `IndexedSlices` is not `tf.Tensor`. Then, how can I still use this `tf.vectorized_map`?

**Comment by JiahaoYao** [comment] 2019-06-20 05:35
Or if there is any way to let the output of `tf.gradients` to be `Tensor`, not `IndexedSlices`?

**Comment by gadagashwini** [comment] 2019-06-20 13:33
@JiahaoYao Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment] 2019-06-27 05:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-27 05:27 UTC
Labels: comp:ops, stat:awaiting response, type:support

**Comment by agarwal-ashish** [comment] 2019-07-11 02:41
Please see https://github.com/tensorflow/tensorflow/commit/4136a6a3ea5796c86054b4a616a821211ad2ef31#diff-56422f894d9046679f64b2f8179aa17c for the support added for IndexedSlices.

Note that this currently makes the gradients dense. Alternatively, one could flatten out the IndexedSlices returned from the gradients call into its components and then unflatten it post vectorization by vectorized_map.

**Comment by JiahaoYao** [comment] 2019-07-11 05:55
Appreciated!
