### ISSUE TITLE
Cryptic error message when assigning to a variable in a tf.function

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#30768] opened 2019-07-16 19:04 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MacOSX 10.13.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
VERSION=2.0.0-dev20190716
GIT_VERSION=v1.12.1-6367-gb51a1b258b
- Python version:
3.6.8
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
When assigning to a TF variable with the `=` operator in a TF Function, I get a really cryptic error message.
This issue is about the error message, not the error itself (I should have called the variable's assign() method).

**Describe the expected behavior**
I was hoping for a more explicit error message.

**Code to reproduce the issue**

```python
import tensorflow as tf

v = tf.Variable(0.)

@tf.function
def f(x):
    global v
    v = v + x  # no problem if use v.assign(v + x)
    return v

f(42.0)
```

**Other info / logs**
```
2019-07-16 21:02:26.141110: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-16 21:02:26.154309: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe6734a6e50 executing computations on platform Host. Devices:
2019-07-16 21:02:26.154329: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-16 21:02:26.222272: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1558] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2019-07-16 21:02:26.223137: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Failed precondition: Error while reading resource variable _AnonymousVar0 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar0/N10tensorflow3VarE does not exist.
	 [[{{node ReadVariableOp}}]]
---------------------------------------------------------------------------
FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-1-a1cd73b43975> in <module>
      9     return v
     10
---> 11 f(42.0)

~/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    433               *args, **kwds)
    434       # If we did not create any variables the trace we have is good enough.
--> 435       return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
    436
    437     def fn_with_cond(*inner_args, **inner_kwds):

~/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in _filtered_call(self, args, kwargs)
    633          if isinstance(t, (ops.Tensor,
    634                            resource_variable_ops.BaseResourceVariable))),
--> 635         self.captured_inputs)
    636
    637   def _call_flat(self, args, captured_inputs):

~/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in _call_flat(self, args, captured_inputs)
    743     # Only need to override the gradient in graph mode and when we have outputs.
    744     if context.executing_eagerly() or not self.outputs:
--> 745       outputs = self._inference_function.call(ctx, args)
    746     else:
    747       self._register_gradient()

~/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py in call(self, ctx, args)
    457             attrs=("executor_type", executor_type,
    458                    "config_proto", config),
--> 459             ctx=ctx)
    460       # Replace empty list with None
    461       outputs = outputs or None

~/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~/miniconda3/envs/tf2/lib/python3.6/site-packages/six.py in raise_from(value, from_value)

FailedPreconditionError:  Error while reading resource variable _AnonymousVar0 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar0/N10tensorflow3VarE does not exist.
	 [[node ReadVariableOp (defined at /Users/ageron/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1657) ]] [Op:__inference_f_15]

Function call stack:
f
```

**Comment by anush-o** [comment] 2019-07-17 11:38
I was able to replicate the issue with TF VERSION=2.0.0-dev20190716. Take a look at the Gist of [Colab link](https://colab.research.google.com/drive/1398dDTnZa2U3EDSYZQ3Zp5vwjR_mwe5i) .Thanks!

**Comment by ymodak** [comment] 2019-07-17 18:50
The code snippet works with TF 1.14

**Comment by mdanatg** [comment] 2019-07-18 14:33
@ageron Unfortunately, `tf.Variable` does not override arithmetic operators and in effect `v = v + x` will replace the `Variable` `v` with a `Tensor` - is this what you expected?

@alextp @jaingaurav  I suspect the root cause here is that `tf.function` captures a weak reference to the variable, which is then deallocated. If that's indeed the case, then this example shows that the weakref should in fact be a strong reference and be tied to the graph that relies on it.

Note: this error is unrelated to autograph; the snippet below throws the same error:

```
v = tf.Variable(0.)

@tf.function(autograph=False)
def f(x):
    global v
    v = v + x  # no problem if use v.assign(v + x)
    return v

f(42.0)
```

**Comment by alextp** [comment] 2019-07-18 14:58
The issue is that `v = v + x` doesn't assign to the variable, it throws the variable away (deleting it) and then assigns a tensor internal to the function (v+x) to the name `v`.

Because you threw the variable away and you're trying to execute a graph which reads the value of the variable (so it can compute `v+x`, which translates internally as `add(read_variable(v), x)`) we fail.

The error message could be better, but the behavior is WAI.

**Comment by ageron** [comment] 2019-07-21 09:38
Thanks @alextp, I know it is WAI, this issue is about the error message, as I wrote earlier:
"This issue is about the error message, not the error itself (I should have called the variable's assign() method)."

**Comment by amahendrakar** [comment] 2020-04-24 06:01
Was able to reproduce the issue with [TF v2.2.0-rc3](https://colab.research.google.com/gist/amahendrakar/f198bc025239bf602f192a49c57f260e/30768-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/e459e9dbfcc52cd023047787bf0960d6/30768-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by sushreebarsa** [comment] 2021-06-24 17:51
Was able to replicate the issue with TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/2f660e1ebe6fa9968f9893a8e93b85ba/30768-tf-nightly.ipynb) ..Thanks!

**Comment by mohantym** [comment] 2021-09-06 12:05
Hi @ageron , Values can be  only added to variable using  **assign_add/assign** operations .For other variable operations  please refer to [this](https://www.tensorflow.org/api_docs/python/tf/Variable#methods_2) .  providing [gist](https://colab.research.google.com/gist/mohantym/07746dd82f590aee71dfae32c898f3b2/30768-tf-nightly.ipynb#scrollTo=JvDCJ6Cj_Kmt) for reference.

**Comment by ageron** [comment] 2021-09-14 21:14
@mohantym , yes of course, that's why I wrote this: "_This issue is about the error message, not the error itself (I should have called the variable's assign() method)._". The error message is just as cryptic today with TF 2.6 as it was with TF 2.0.

**Comment by mdanatg** [comment] 2021-09-14 21:25
Quick note that we're still tracking this issue and intend to fix it, so it should stay open.

It might ultimately be easier do what'd be normally expected and use assign instead of raising an error.

**Closed** 2022-02-21 20:22 UTC
Labels: stat:awaiting response, type:bug, comp:eager, comp:ops, TF 2.5
