### ISSUE TITLE
convert yolov3 model to tflite

### ISSUE THREAD

**Issue by vainaijr** [tensorflow/tensorflow#25776] opened 2019-02-15 08:26 UTC
not able to convert yolov3 model to tflite format

converted the weights file to pb format

then

./bazel-bin/tensorflow/lite/toco/toco --input_file=yolov3_finale_manga109.pb --output_file=foo.tflite --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --input_arrays=input --input_shapes=1,406,406,3 --output_arrays=output --allow_nonexistent_arrays

got error

2019-02-15 17:23:48.560625: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 2044 operators, 2743 arrays (0 quantized)
2019-02-15 17:23:48.601097: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] After Removing unused ops pass 1: 0 operators, 2 arrays (0 quantized)
2019-02-15 17:23:48.601134: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:136] Model is empty!!!
2019-02-15 17:23:48.601217: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 0 operators, 2 arrays (0 quantized)
2019-02-15 17:23:48.601228: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:136] Model is empty!!!
2019-02-15 17:23:48.601237: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Group bidirectional sequence lstm/rnn: 0 operators, 2 arrays (0 quantized)
2019-02-15 17:23:48.601243: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:136] Model is empty!!!
2019-02-15 17:23:48.601249: W tensorflow/lite/toco/tooling_util.cc:1263] Fixing constant output array output by inserting a copy. This is not optimal.
2019-02-15 17:23:48.601260: F ./tensorflow/lite/toco/model.h:2134] Check failed: has_shape()

**Comment by jvishnuvardhan** [comment] 2019-02-16 00:51
@vainaijr Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-02-22 23:16
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-02-22 23:16 UTC
Labels: comp:lite, stat:awaiting response, type:bug/performance

**Comment by peace195** [comment] 2019-10-20 15:51
@vainaijr  I did it here: https://github.com/peace195/tensorflow-lite-yolo-v3

Please try it. I would appreciate if you give me a star for this project :+1:

**Comment by phanxuanduc1996** [comment] 2020-05-01 09:50
You can see at here. I tried it and success.
https://github.com/phanxuanduc1996/convert_yolo_weights
