### ISSUE TITLE
tf.train.import_meta_graph raise ValueError(str(e)) ValueError: Cannot add function '__inference_Dataset_flat_map_read_one_file_11' because a different function with the same name already exists.

### ISSUE THREAD

**Issue by Gzzgz** [tensorflow/tensorflow#32689] opened 2019-09-20 14:28 UTC
Traceback (most recent call last):
  File "test.py", line 121, in <module>
    test()
  File "test.py", line 67, in test
    saver = tf.train.import_meta_graph('checkpoint/-301.meta')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1449, in import_meta_graph
    **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1473, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/meta_graph.py", line 857, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/importer.py", line 431, in import_graph_def
    raise ValueError(str(e))
ValueError: Cannot add function '__inference_Dataset_flat_map_read_one_file_11' because a different function with the same name already exists.

using tensorflow version 1.14

？？？ why? how?

**Comment by gadagashwini** [comment] 2019-09-23 05:52
@Gzzgz,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-10-07 11:11
@Gzzgz, Please provide the standalone code to reproduce the issue. Thanks!

**Comment by gadagashwini** [comment] 2019-10-16 09:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-10-16 09:36 UTC
Labels: TF 1.14, comp:data, stat:awaiting response, type:support
