### ISSUE TITLE
Gast 0.2.2 working, 0.3.3 not working

### ISSUE THREAD

**Issue by MayhemGang** [tensorflow/tensorflow#34933] opened 2019-12-07 22:38 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes, but tested for both
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Conda
- TensorFlow version (use command below): 1.14, 1.15
- Python version: 3.6,3.7,3.8
- CUDA/cuDNN version: Conda
- GPU model and memory: Geforce GTX 1070 & 1080ti, 8GB/11GB respectivelyl

**Describe the current behavior**
Using Gast 0.3.3, what happens is that the training will hang randomly when using tensorflow-gpu. This can be fixed by pip install gast==0.2.2
**Describe the expected behavior**
Training and not hanging
**Code to reproduce the issue**
All ML training that utilizes gpu

This issue still hasn't been dealt with.

**Comment by MayhemGang** [comment] 2019-12-08 00:15
training still seems to hang even using gast 0.2.2. This was momentarily fixed.

**Comment by oanush** [comment] 2019-12-09 10:39
@MayhemGang ,
Please note that  tensorflow 1.15.0 has requirement `gast==0.2.2` , `gast 0.3.2` is incompatible. Thanks!

**Comment by MayhemGang** [comment] 2019-12-09 21:42
I know, I had to install gast 0.2.2 manually. However, even with gast 0.2.2, the training halts. No limits, no logging, just image saving.

**Comment by oanush** [comment] 2019-12-10 05:10
@MayhemGang ,
Can you provide a standalone code to reproduce the error reported here?Thanks!

**Comment by MayhemGang** [comment] 2019-12-10 19:41
Unable as my code mostly draws on datasets. Would an entire zip file help?

**Comment by mihaimaruseac** [comment] 2019-12-10 20:12
Unfortunately no. You need to provide a minified example, not a full code, to help developers narrow down the problem. It's similar to finding a spelling mistake in a page versus finding it in all the books in a city.

**Comment by MayhemGang** [comment] 2019-12-11 03:42
Sigh, I will integrate Mnist I guess

**Comment by MayhemGang** [comment] 2019-12-11 03:42
Will be updated in like a few days, anyone else has hanging issues meanwhile?

**Comment by geometrikal** [comment] 2019-12-13 01:25
@MayhemGang yea hanging issues on 1.14 on one computer. Tried multiple reinstalls but no luck. NVIDIA Titan X (pascal)

**Comment by mihaimaruseac** [comment] 2019-12-13 01:37
Can you please try TF 1.15 or TF 2.0 or the release candidate for TF 2.1 or the master's `tf-nightly`? I would recommend testing them all if minified example is hard to provide (and especially not clinging to 1.14 as that is extremely hard to patch now as it has been more than 6 months since it was released)

We really need a way to debug this, so please try to provide a minified example.

**Comment by geometrikal** [comment] 2019-12-13 02:19
@mihaimaruseac 

For me (on Windows), I can't do 1.15 because I get some error about pxtas (https://github.com/tensorflow/models/issues/7640) and I notice keras model.predict is slow (like it is running on CPU) and the times to do an epoch vary wildly (e.g. up to 5 x times variation).

I can't do v.2.X because tf.contrib.image (which I need) got moved to tf.addons but isn't implemented for windows yet.

OT: but my problems are weird - one computer with Titan X (pascal) and one with RTX 2080 Ti. Since 1.14, the TITAN X pascal computer trains as though it is on CPU, even though it generates all the normal GPU messages. nvidia-cpu shows the GPU memory is occupied, but GPU utilization is 0. It would also randomly just freeze. Same on 1.15. Also training of a simple two layer network with model.fit is taking almost as long as a 13 layer CNN, although that is with model.fit_generator. Reverting to 1.13.1 seems to have fixed it. The RTX 2080 trains fine.

Anyway I know that story is not really helpful to you, but I'm currently troubleshooting by changing everything to tf.multiply / tf.add / tf.subtract etc to check if it is autograph, as well a few other things, and try to isolate the problem for a minified version.

**Comment by MayhemGang** [comment] 2019-12-14 06:20
Exactly same as your issue @geometrikal, haven't been able to replicate with a stand out model yet.  I don't get any errors, and the training literally just halts. Ofc I have quick edit disabled, and GPU memory is being used, while usage is 0%, and CPU is not even being used.

**Comment by MayhemGang** [comment] 2019-12-25 11:23
Very strange behavior detected. This run seems to train fine. but no images are saving. Perhaps the images saved are causing the hanging?

**Comment by MayhemGang** [comment] 2019-12-25 11:37
In fact, with even Image saving fixed, the training is going perfectly. This is a rare occurence.
The only things I have changed are the config options,
config = tf.ConfigProto(allow_soft_placement=True)
config.gpu_options.allow_growth = True
config.gpu_options.polling_inactive_delay_msecs = 10

It seems the polling delay fixes the issue. I am using dual xeon x5690s, which are of a very old architecture, and that may be causing the issue in the first place.

**Comment by geometrikal** [comment] 2019-12-25 11:40
@MayhemGang Just a reminder, you haven't shared your code so it's not clear what you are referring to.

**Comment by ymodak** [comment] 2020-03-18 21:32
Closing this issue since we cannot reproduce the reported behavior. Feel free to reopen when new information is available. Thanks!

**Closed by ymodak** 2020-03-18 21:32 UTC
Labels: TF 1.15, comp:ops, type:support
