### ISSUE TITLE
Request for computation of hessian wrt tensor of shape 1 x n

### ISSUE THREAD

**Issue by iramusa** [tensorflow/tensorflow#12330] opened 2017-08-16 14:01 UTC
There currently exists tf.hessians function which returns 2nd order *y* derivatives w.r.t. to a specified tensor *x*. Currently *x* has to be one dimensional.

In my application, I need to differentiate with respect to a tensor that has dimensions batch_size x layer_width. (I am interested in second derivative of output from neural net with respect to a particular layer.) I can bring dimensionality down to 1 x layer_width, by setting batch_size to 1. Unfortunately, this still does not let me use tf.hessian.

Would it be possible to add functionality where hessian w.r.t. *effectively* one-dimensional tensors can be computed? So that, for example tensors of shape 1 x n (or 1 x 1 x n) can be used. It feels like it shouldn't be a hard problem, but I'm completely lost when I look at tf.gradients code.

Thanks

**Comment by reedwm** [comment] 2017-08-16 18:53
@vrv what do you think of this proposal?

@iramusa As a workaround, you can [tf.squeeze](https://www.tensorflow.org/api_docs/python/tf/squeeze) on x, to change its shape from `[1, layer_width]` to `[layer_width]`, which would allow you to pass it to `tf.hessians`.

**Comment by vrv** [comment] 2017-08-16 21:02
@Sohl-Dickstein might have some opinions or ideas (I might appear to be the author but I am not) . :)

**Comment by Sohl-Dickstein** [comment] 2017-08-17 01:49
I think calling tf.squeeze() sounds like an excellent approach. You can call tf.reshape() on the resulting Hessian if you need it to be a different shape.

Note that this also lets you compute the Hessian for your original full matrix. Just flatten x by tf.reshape(x (-1,)).

**Comment by iramusa** [comment] 2017-08-17 16:44
@reedwm @Sohl-Dickstein 

Thank you for suggestion to use tf.squeeze(). Unfortunately this doesn't solve the issue for me.

Let me be more concrete. This is what I'm trying to do. First I build a network:

```
x = Input(batch_shape=(1, 10))
v = Dense(10)(x)
y = Dense(10)(v)
net = Model(x, y)
```

Then I train it, etc. Then I'm interested in hessian of `y` wrt `v`. `tf.gradients(y, v)` works perfectly fine.

What I attempted:

(1) Naive: `tf.hessians(y, v)` throws:
```
ValueError: Computing hessians is currently only supported for one-dimensional tensors. Element number 0 of `xs` has 2 dimensions.
```

(2) Using `tf.squeeze` to force the right shape of `v` does not help. I think that's because in the computation graph is `v` copied into a new tensor and there is no differentiable connection between `v` and `y`. What I observe is that
```
v_flat = tf.squeeze(v);
tf.gradients(y, v_flat)
```
returns `[None]`

(3) I can modify my original network the following way:
```
x = Input(batch_shape=(1, 10))
v = Dense(10)(x)

v_flat = tf.squeeze(v)  # added
v_non_flat = tf.reshape(v_flat, (1, 10))   # added

y = Dense(10)(v_non_flat)
net = Model(x, y)
```
Then, I hope to be able to call `tf.hessians(y, v_flat)`. Unfortunately, I cannot test that because the above code halts with error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-14-68462b8d53de> in <module>()
      7 
      8 y = Dense(10)(v_non_flat)
----> 9 net = Model(x, y)
     10 net.compile(optimizer='adam', loss='mse')
     11 

/home/ira/code/envs/flexi/lib/python3.5/site-packages/keras/engine/topology.py in __init__(self, input, output, name)
   1814                 cls_name = self.__class__.__name__
   1815                 raise TypeError('Output tensors to a ' + cls_name + ' must be '
-> 1816                                 'Keras tensors. Found: ' + str(x))
   1817         # Build self.output_layers:
   1818         for x in self.outputs:

TypeError: Output tensors to a Model must be Keras tensors. Found: Tensor("add_5:0", shape=(1, 10), dtype=float32)
```

Do you have any further suggestions? Possibly solving the issue from (3) could bring me on track.

**Comment by reedwm** [comment] 2017-08-17 17:16
You're right that my `tf.squeeze` suggestion does not work, because there is no path from the `tf.squeeze` tensor to `y`. 

(3) is quite clever. I do not know Keras so I do not know what the problem is. @fchollet, do you know how to resolve (3)? @iramusa, you can also ask on StackOverflow to get help with (3).

Marking as contributions welcome if anyone wants to add support for effectively 1D Tensors to `tf.hessians`.

**Comment by iramusa** [comment] 2017-08-17 18:57
Thanks

@tillahoffmann Do you have an idea on how to solve this?

**Comment by tillahoffmann** [comment] 2017-08-17 22:03
@iramusa, you could approach the problem the other way round: Start with a 1D tensor which you reshape to the desired shape. Then you can compute the hessian of some function of your tensor with respect to the 1D tensor and reshape the hessian to match the desired shape. But examples are better than theory:

```python
shape = (3, 5)

with tf.Graph().as_default():
    x_flat = tf.constant(np.random.normal(0, 1, np.prod(shape)))
    x = tf.reshape(x_flat, shape)
    y = x * x
    hessian_flat, = tf.hessians(y, x_flat)
    hessian = tf.reshape(hessian_flat, shape + shape)
```

**Comment by wbaek** [comment] 2017-12-13 04:35
@reedwm  I try to fix this issue. 
Plz check and review my PR https://github.com/tensorflow/tensorflow/pull/15308

**Comment by wt-huang** [comment] 2018-11-08 15:29
Closing as this is resolved

**Closed by wt-huang** 2018-11-08 15:29 UTC
Labels: stat:contributions welcome
