### ISSUE TITLE
I can't compile tensorflow on Ubuntu 16.10 

### ISSUE THREAD

**Issue by mustafaxfe** [tensorflow/tensorflow#8346] opened 2017-03-13 09:59 UTC
I have given these commands to compile tensorflow:
`sudo apt-get install python-numpy python-dev python-pip python-wheel`

`sudo apt-get install python3-numpy python3-dev python3-pip python3-wheel`

`git clone https://github.com/tensorflow/tensorflow `

`cd tensorflow/`

`git checkout r1.0`

`./configure`

`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package --verbose_failures`

It gives this error:

> ERROR: /home/raspberry/tensorflow/tensorflow/core/kernels/BUILD:2468:1: C++ compilation of rule '//tensorflow/core/kernels:bias_op' failed: gcc failed: error executing command 
  (cd /home/raspberry/.cache/bazel/_bazel_raspberry/e683ea6480b94d5dcdb0f13cb220eff8/execroot/tensorflow && \
  exec env - \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-march=native' '-std=c++0x' '-march=native' -MD -MF bazel-out/local-py3-opt/bin/tensorflow/core/kernels/_objs/bias_op/tensorflow/core/kernels/bias_op.pic.d '-frandom-seed=bazel-out/local-py3-opt/bin/tensorflow/core/kernels/_objs/bias_op/tensorflow/core/kernels/bias_op.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DTENSORFLOW_USE_JEMALLOC -iquote . -iquote bazel-out/local-py3-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local-py3-opt/genfiles/external/bazel_tools -iquote external/eigen_archive -iquote bazel-out/local-py3-opt/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local-py3-opt/genfiles/external/local_config_sycl -iquote external/jemalloc -iquote bazel-out/local-py3-opt/genfiles/external/jemalloc -iquote external/protobuf -iquote bazel-out/local-py3-opt/genfiles/external/protobuf -iquote external/gif_archive -iquote bazel-out/local-py3-opt/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local-py3-opt/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local-py3-opt/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local-py3-opt/genfiles/external/farmhash_archive -iquote external/highwayhash -iquote bazel-out/local-py3-opt/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local-py3-opt/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local-py3-opt/genfiles/external/zlib_archive -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/eigen_archive -isystem bazel-out/local-py3-opt/genfiles/external/eigen_archive -isystem external/jemalloc/include -isystem bazel-out/local-py3-opt/genfiles/external/jemalloc/include -isystem external/protobuf/src -isystem bazel-out/local-py3-opt/genfiles/external/protobuf/src -isystem external/gif_archive/lib -isystem bazel-out/local-py3-opt/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local-py3-opt/genfiles/external/farmhash_archive/src -isystem external/highwayhash -isystem bazel-out/local-py3-opt/genfiles/external/highwayhash -isystem external/png_archive -isystem bazel-out/local-py3-opt/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local-py3-opt/genfiles/external/zlib_archive -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare -fno-exceptions -pthread -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/core/kernels/bias_op.cc -o bazel-out/local-py3-opt/bin/tensorflow/core/kernels/_objs/bias_op/tensorflow/core/kernels/bias_op.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 15812.554s, Critical Path: 15700.39s

Version of bazel:

Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261

**Comment by leigaoyi** [comment] 2017-03-14 06:55
I use ubuntu 16.04 , and in tensorflow's official website, ubuntu 14.04 and ubuntu 16.04 are supported. How about using these command:
**sudo pip install tensorflow**

**Comment by drpngx** [comment] 2017-03-14 13:07
I'm afraid that's a bug in gcc. Can you print `gcc --version`?

@rmlarsen @benoitsteiner maybe it's related to eigen?
@gunan if this is the stock gcc coming with ubuntu 16, we should probably try to have a workaround.

**Comment by gunan** [comment] 2017-03-14 17:56
Looks like gcc crashed when compiling `tensorflow/core/kernels/bias_op.cc`
I agree that we need to have TF building on stock compilers. So I am happy to accept a workaround (currently busy with other things, so I wont be able to debug this myself).

**Comment by mustafaxfe** [comment] 2017-03-15 21:26
I've found a solution for this issue. I have increased memory of virtualbox virtual machine. I made it 5gb. So then I compiled tensorflow without problem.

**Comment by drpngx** [comment] 2017-03-15 21:51
Oh, good to know. Definitely a template expansion artifact.

I'm closing this issue since we found the root cause. Thanks for reporting.

**Closed** 2017-03-15 21:51 UTC

**Comment by avielas** [comment] 2020-04-11 16:56
> I've found a solution for this issue. I have increased memory of virtualbox virtual machine. I made it 5gb. So then I compiled tensorflow without problem.

it works for me. thanks!
