### ISSUE TITLE
bazel error: name 'http_archive' is not defined

### ISSUE THREAD

**Issue by 307509256** [tensorflow/tensorflow#27189] opened 2019-03-27 09:26 UTC
I want to build libtensorflowLite.so for Android
```
git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git -b r1.12
cd tensorflow
vim WORKSPACE 
```
# 1. modify WORKSPACE:
```
android_sdk_repository(
   name = "androidsdk",
   api_level = 29,
   build_tools_version = "29.0.0",
   path = "/Users/gongjia/Library/Android/sdk",
)

# Android NDK r12b is recommended (higher may cause issues with Bazel)
android_ndk_repository(
   name="androidndk",
   # path="/Users/gongjia/Library/Android/sdk/ndk-bundle",
   path="/Users/gongjia/Library/Android/sdk/android-ndk-r14b",
   api_level=21
)
```
# 2. add in tensorflow/contrib/lite/BUILD
```
cc_binary(
    name = "libtensorflowLite.so",
    linkopts = ["-shared", "-Wl,-soname=libtensorflowLite.so"],
    visibility = ["//visibility:public"],
    linkshared = 1,
    copts = tflite_copts(),
    deps = [
        ":framework",
        "//tensorflow/contrib/lite/kernels:builtin_ops",
    ],
)
```
# 3. exec: 
```
bazel build -c opt //tensorflow/contrib/lite:libtensorflowLite.so   --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cxxopt="-std=c++11" --verbose_failures
```

# 4. result:
```
ERROR: /Users/gongjia/Documents/github/tensorflow/WORKSPACE:3:1: name 'http_archive' is not defined
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.082s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

# 5. Info:
tensorflow: r1.12
configure: default
macOS Mojave 10.14.3
python:2.7
bazel: 0.24.0

**Comment by muddham** [comment] 2019-03-28 13:58
@307509256 Request you to please fill the template with infrastructure details so that we can suggest you the solution

**Comment by mihaimaruseac** [comment] 2019-03-29 16:44
What is the bazel version?

**Comment by SefaZeng** [comment] 2019-04-12 08:36
Meet the same error with bazel 0.24.1

**Comment by mihaimaruseac** [comment] 2019-04-12 18:01
Including all the workspace modifications? Or from a pristine fork of the repo?

**Comment by 307509256** [comment] 2019-04-16 03:07
> What is the bazel version?

0.24.0

**Comment by 307509256** [comment] 2019-04-16 07:06
> Including all the workspace modifications? Or from a pristine fork of the repo?

git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git -b r1.12
is ok?

**Comment by mihaimaruseac** [comment] 2019-04-16 14:24
Can you try building first with no modifications to the code after cloning?

**Comment by 307509256** [comment] 2019-04-17 02:41
> Can you try building first with no modifications to the code after cloning?

yes, I have try it, fail also

**Comment by mihaimaruseac** [comment] 2019-04-17 15:27
Can you try with r1.13 branch instead? Or, if you want r1.12, can you try downgrading bazel to 0.19?

**Comment by jvishnuvardhan** [comment] 2019-04-17 21:25
@307509256 Please check the tested build config [here](https://www.tensorflow.org/install/source#cpu). For TF1.12, you need to downgrade Bazel to 0.15.0. For TF1.13.1, you need to use Bazel 0.19.2. Thanks!

**Comment by 307509256** [comment] 2019-04-18 08:53
> @307509256 Please check the tested build config [here](https://www.tensorflow.org/install/source#cpu). For TF1.12, you need to downgrade Bazel to 0.15.0. For TF1.13.1, you need to use Bazel 0.19.2. Thanks!

The problem is solved, thank you!
another question , I build success， the size of file 
“bazel-bin/tensorflow/contrib/lite/libtensorflowLite.so” is  49M，
 but I download from maven is 2.3M
url： http://jcenter.bintray.com/org/tensorflow/tensorflow-lite/1.12.0/

**Comment by mihaimaruseac** [comment] 2019-04-18 14:32
Size difference can be caused by the compile options (if you have debug info, etc.). You can also try `strip` on the `.so` file to get rid of some of the symbols.

**Comment by jvishnuvardhan** [comment] 2019-05-01 21:31
Closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Please open a new issue for other questions as it will help the community. Thanks!

**Closed by jvishnuvardhan** 2019-05-01 21:31 UTC
Labels: comp:lite, type:build/install

**Comment by AmmarkoV** [comment] 2019-06-20 12:46
Just had the same issue, thank you guys for making our life difficult with your magic build system..
I have to swap build system versions to build different library versions.. This is great..!

**Comment by mihaimaruseac** [comment] 2019-06-20 14:05
The issue is that bazel 0.* is unstable and changes wildly. Soon we will have a bazel 1.0 release which is going to be much stable.

**Comment by tispratik** [comment] 2020-02-13 01:17
What bazel version should I downgrade to for TF 1.10.0 ?

**Comment by mihaimaruseac** [comment] 2020-02-13 17:14
Pleae see table at https://www.tensorflow.org/install/source#tested_build_configurations
