### ISSUE TITLE
[Bug] tf version 1.2 , dropout layer reject tensor type rate

### ISSUE THREAD

**Issue by abelxie** [tensorflow/tensorflow#11005] opened 2017-06-23 09:09 UTC
version 1.2

The following code:

```python
tf.contrib.layers.dropout(tf.zeros((100,10)), keep_prob=tf.placeholder_with_default(0.9,(),'dp'))
```

or 

```python
tf.layers.dropout(tf.zeros((100,10)), 1 - tf.placeholder_with_default(0.9,(),'dp'))
```

will fail with following error:

```txt
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-e27328ef830a> in <module>()
----> 1 tf.contrib.layers.dropout(tf.zeros((100,10)), keep_prob=tf.placeholder_with_default(0.9,(),'dp'))

~/miniconda3/envs/t12/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    179       current_args = current_scope[key_func].copy()
    180       current_args.update(kwargs)
--> 181     return func(*args, **current_args)
    182   _add_op(func)
    183   setattr(func_with_args, '_key_op', _key_op(func))

~/miniconda3/envs/t12/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py in dropout(inputs, keep_prob, noise_shape, is_training, outputs_collections, scope)
   1214                                 noise_shape=noise_shape,
   1215                                 name=sc.name,
-> 1216                                 _scope=sc)
   1217     outputs = layer.apply(inputs, training=is_training)
   1218     return utils.collect_named_outputs(

~/miniconda3/envs/t12/lib/python3.6/site-packages/tensorflow/python/layers/core.py in __init__(self, rate, noise_shape, seed, name, **kwargs)
    245                **kwargs):
    246     super(Dropout, self).__init__(name=name, **kwargs)
--> 247     self.rate = min(1., max(0., rate))
    248     self.noise_shape = noise_shape
    249     self.seed = seed

~/miniconda3/envs/t12/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in __bool__(self)
    562       `TypeError`.
    563     """
--> 564     raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
    565                     "Use `if t is not None:` instead of `if t:` to test if a "
    566                     "tensor is defined, and use TensorFlow ops such as "

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-e27328ef830a> in <module>()
----> 1 tf.contrib.layers.dropout(tf.zeros((100,10)), keep_prob=tf.placeholder_with_default(0.9,(),'dp'))

~/miniconda3/envs/t12/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py in func_with_args(*args, **kwargs)
    179       current_args = current_scope[key_func].copy()
    180       current_args.update(kwargs)
--> 181     return func(*args, **current_args)
    182   _add_op(func)
    183   setattr(func_with_args, '_key_op', _key_op(func))

~/miniconda3/envs/t12/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py in dropout(inputs, keep_prob, noise_shape, is_training, outputs_collections, scope)
   1214                                 noise_shape=noise_shape,
   1215                                 name=sc.name,
-> 1216                                 _scope=sc)
   1217     outputs = layer.apply(inputs, training=is_training)
   1218     return utils.collect_named_outputs(

~/miniconda3/envs/t12/lib/python3.6/site-packages/tensorflow/python/layers/core.py in __init__(self, rate, noise_shape, seed, name, **kwargs)
    245                **kwargs):
    246     super(Dropout, self).__init__(name=name, **kwargs)
--> 247     self.rate = min(1., max(0., rate))
    248     self.noise_shape = noise_shape
    249     self.seed = seed

~/miniconda3/envs/t12/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in __bool__(self)
    562       `TypeError`.
    563     """
--> 564     raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
    565                     "Use `if t is not None:` instead of `if t:` to test if a "
    566                     "tensor is defined, and use TensorFlow ops such as "

TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
```

The same code run successfully on tf version 1.1.0,

I check the documents are not changed : 
[https://www.tensorflow.org/api_docs/python/tf/contrib/layers/dropout](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/dropout)

        keep_prob: A scalar Tensor with the same type as x. The probability that each element is kept.

It accepts tensor, so I guess this should be a bug.

**Comment by tatatodd** [comment] 2017-06-23 19:56
@abelxie Thanks for filing the issue!  I've reproduced the problem, and agree that this looks like a bug.

@fchollet Can you take a look or suggest someone to fix this?  Also marking "contributions welcome", in case anyone in the community would like to contribute to fix this.

**Comment by simonkamronn** [comment] 2017-06-26 08:48
The error seems caused by using Python `min()` and `max()` on a Tensor. I also get he error in TF 1.2 but it is not in the current master as of c98dab03f0de724da81dac8218757207996d1505

Do you know if we can expect an updated official version soon or do we need to build ourselves?

**Comment by tatatodd** [comment] 2017-06-26 17:46
@simonkamronn Thanks for tracking down the PR that fixed this!

@av8ramit Probably knows the schedule for TF 1.3.  In the meantime you'll either need to pull the nightly releases, or build from source yourself.

**Comment by av8ramit** [comment] 2017-06-26 20:12
@simonkamronn the next official release will be sometime in July. Please pull the nightly release for a fix! Thanks for bringing this to our attention.

**Comment by tatatodd** [comment] 2017-06-26 20:46
Thanks for the info @av8ramit!

Closing this out, since the underlying problem has already been fixed.

**Closed by tatatodd** 2017-06-26 20:46 UTC
Labels: stat:awaiting tensorflower, type:bug/performance
