### ISSUE TITLE
Tensorflow2.0 distributed training gives error :- A non-DistributedValues value 8 cannot be reduced with the given reduce op ReduceOp.SUM.

### ISSUE THREAD

**Issue by akanyaani** [tensorflow/tensorflow#31852] opened 2019-08-21 18:23 UTC
<em> **Getting the error when i am running distributed training**  as described in this tutorial (https://colab.research.google.com/github/tensorflow/docs/blob/r2.0rc/site/en/r2/guide/distribute_strategy.ipynb#scrollTo=IlYVC0goepdk)</em>

**System information**
- OS Platform: - Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0-beta
- Python version: 3.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.01
- GPU model and memory: p100, 16GB

```
@tf.function
def train_step(dist_inputs):
    def step_fn(inputs):
        features, labels = inputs

        with tf.GradientTape() as tape:
            logits = model(features)
            #print(logits)
            cross_entropy = tf.nn.softmax_cross_entropy_with_logits(
                        logits=logits, labels=labels)
            loss = tf.reduce_sum(cross_entropy) * (1.0 / global_batch_size)
        grads = tape.gradient(loss, model.trainable_variables)
        optimizer.apply_gradients(list(zip(grads, model.trainable_variables)))
        return cross_entropy

    per_example_losses = mirrored_strategy.experimental_run_v2(
            step_fn, args=(dist_inputs,))
    mean_loss = mirrored_strategy.reduce(
            tf.compat.v2.distribute.ReduceOp.MEAN, per_example_losses, axis=0)
    return mean_loss
```
I am getting this error while running abobe distributed code.
`ValueError: A non-DistributedValues value 8 cannot be reduced with the given reduce op ReduceOp.SUM.

**But it works when I use tf.distribute.ReduceOp.SUM instead of tf.distribute.ReduceOp.MEAN** 
`

**Comment by gadagashwini** [comment] 2019-08-22 09:27
@akanyaani I tried executing the colab with ReduceOp.SUM and ReduceOp.MEAN but i didn't get any error. Please can you try once and let us know if issue still persists. Thanks!

**Comment by akanyaani** [comment] 2019-08-22 10:07
Hi @gadagashwini 

It works on colab because you are not running on multiple GPU, 
ReduceOp.MEAN is working when I am running on GPU, but not working when I am running on multiple GPU.

**Comment by gadagashwini** [comment] 2019-08-22 11:08
@akanyaani Thanks for the update.

**Comment by reuben** [comment] 2019-08-30 14:30
FWIW, I'm running into the same problem (on 2.0.0-rc0), but changing it to `ReduceOp.SUM` does not help.

**Comment by akanyaani** [comment] 2019-09-10 09:33
Hi, @reuben You can still train your model on distributed GPU, I am able to train using ReduceOp.SUM only but after that, you have to divide by global batch size you will get the same value which ReduceOp.mean would give.

```
reduce_sum_out = self.mirrored_strategy.reduce(
            tf.distribute.ReduceOp.SUM, per_example_losses, axis=0)

loss  = reduce_sum_out / global_batch_size
```
But I am not 100 percent sure that weather I doing it correctly on not.

**Comment by reuben** [comment] 2019-09-10 09:42
@akanyaani I get the same error even if I use ReduceOp.SUM.

**Comment by akanyaani** [comment] 2019-09-10 09:51
Hi, @reuben can you share the stack trace because I am able to train on multiple GPU using above code.

**Comment by reuben** [comment] 2019-09-10 10:03
I can't get it easily because I've deleted the virtualenv I was using for experimenting with TF2.0.

**Comment by reuben** [comment] 2019-10-02 16:14
I can still reproduce this with TF 2.0 stable: https://colab.research.google.com/drive/1HiablUdEyJECtClfyMr7JtV3ftIbta_M (this is just a copy of https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/distributed_training.ipynb but with code to add two virtual GPUs).

**Comment by akanyaani** [comment] 2019-10-10 09:16
Hi, @reuben Yes this bug is still there.

**Comment by samuelmat19** [comment] 2019-11-14 01:47
I also have this bug. Anyone gets proper solution or fixes yet?

**Comment by akanyaani** [comment] 2019-11-14 05:59
Hi, @samuelmat19  You can still train your model on distributed GPU, I am able to train using ReduceOp.SUM only but after that, you have to divide by global batch size you will get the same value which ReduceOp.mean would give.

```
reduce_sum_out = self.mirrored_strategy.reduce(
            tf.distribute.ReduceOp.SUM, per_example_losses, axis=0)

loss  = reduce_sum_out / global_batch_size
```

**Comment by Char-Aznable** [comment] 2019-11-28 02:04
I also hit this bug and switching to `ReduceOp.SUM` can get around it. Hope someone can fix this!

**Comment by kazimuth** [comment] 2019-12-05 18:18
I wonder if this is due to ReduceOp.MEAN trying to reduce the lengths of the cross-replica batches, but those aren't stored distributed in eager mode for some reason?

**Comment by Shmily-YH** [comment] 2019-12-28 03:04
it seems that MEAN and SUM do not work like tf.reduce_mean and tf.reduce_sum
for example,my step_fn return result with shape [batch,512,512],if i ues SUM and set axis = 0,the SUM operation just return [512,512],so i think everyone should notice that.
so for MEAN,i think it also differnt from tf.reduce_mean

**Comment by CheungZeeCn** [comment] 2020-02-22 07:00
I have the same issue.
 
 TF 2.0.0;  ananconda python 3.73 ;linux ubuntu LTS 16.04;  GPU: 1080Ti 11G * 2

`
import tensorflow as tf
import numpy as np
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']
get_available_gpus()


output:  ['/device:GPU:0', '/device:GPU:1']


global_batch_size=20
mirrored_strategy = tf.distribute.MirroredStrategy()
with mirrored_strategy.scope():
  model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
  optimizer = tf.keras.optimizers.SGD()
dataset = tf.data.Dataset.from_tensors(([1.], [1.])).repeat(1000).batch(
    global_batch_size)
dist_dataset = mirrored_strategy.experimental_distribute_dataset(dataset)

@tf.function
def train_step(dist_inputs):
  def step_fn(inputs):
    features, labels = inputs

    with tf.GradientTape() as tape:
      # training=True is only needed if there are layers with different
      # behavior during training versus inference (e.g. Dropout).
      logits = model(features, training=True)
      cross_entropy = tf.nn.softmax_cross_entropy_with_logits(
          logits=logits, labels=labels)
      loss = tf.reduce_sum(cross_entropy) * (1.0 / global_batch_size)
      #print("loss", loss)

    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(list(zip(grads, model.trainable_variables)))
    return cross_entropy

  per_example_losses = mirrored_strategy.experimental_run_v2(
      step_fn, args=(dist_inputs,))
  
  mean_loss = mirrored_strategy.reduce(
      tf.distribute.ReduceOp.MEAN, per_example_losses, axis=0)
  #print("mean_loss", mean_loss)
  return mean_loss

with mirrored_strategy.scope():
  for inputs in dist_dataset:
    print(train_step(inputs))

`

output:

`

INFO:tensorflow:batch_all_reduce: 2 all-reduces with algorithm = nccl, num_packs = 1, agg_small_grads_max_bytes = 0 and agg_small_grads_max_group = 10
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-3472ab066f79> in <module>
      1 with mirrored_strategy.scope():
      2   for inputs in dist_dataset:
----> 3     print(train_step(inputs))

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
    501       # This is the first call of __call__, so we have to initialize.
    502       initializer_map = object_identity.ObjectIdentityDictionary()
--> 503       self._initialize(args, kwds, add_initializers_to=initializer_map)
    504     finally:
    505       # At this point we know that the initialization is complete (or less

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    406     self._concrete_stateful_fn = (
    407         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 408             *args, **kwds))
    409 
    410     def invalid_creator_scope(*unused_args, **unused_kwds):

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   1846     if self.input_signature:
   1847       args, kwargs = None, None
-> 1848     graph_function, _, _ = self._maybe_define_function(args, kwargs)
   1849     return graph_function
   1850 

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2148         graph_function = self._function_cache.primary.get(cache_key, None)
   2149         if graph_function is None:
-> 2150           graph_function = self._create_graph_function(args, kwargs)
   2151           self._function_cache.primary[cache_key] = graph_function
   2152         return graph_function, args, kwargs

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2039             arg_names=arg_names,
   2040             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2041             capture_by_value=self._capture_by_value),
   2042         self._function_attributes,
   2043         # Tell the ConcreteFunction to clean up its graph once it goes out of

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    913                                           converted_func)
    914 
--> 915       func_outputs = python_func(*func_args, **func_kwargs)
    916 
    917       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    356         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    357         # the function a weak reference to itself to avoid a reference cycle.
--> 358         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    359     weak_wrapped_fn = weakref.ref(wrapped_fn)
    360 

~/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in wrapper(*args, **kwargs)
    903           except Exception as e:  # pylint:disable=broad-except
    904             if hasattr(e, "ag_error_metadata"):
--> 905               raise e.ag_error_metadata.to_exception(e)
    906             else:
    907               raise

ValueError: in converted code:

    <ipython-input-6-5b7f112175aa>:22 train_step  *
        mean_loss = mirrored_strategy.reduce(
    /home/ana/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py:852 reduce
        denom = self._extended._reduce(reduce_util.ReduceOp.SUM, denom)  # pylint: disable=protected-access
    /home/ana/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/distribute_lib.py:1436 _reduce
        device_util.current() or "/device:CPU:0"))[0]
    /home/ana/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/mirrored_strategy.py:701 _reduce_to
        reduce_op, self._device_map, value, destinations)
    /home/ana/data1/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/distribute/cross_device_ops.py:102 reduce_non_distributed_value
        "the given reduce op %s." % (value, reduce_op))

    ValueError: A non-DistributedValues value 10 cannot be reduced with the given reduce op ReduceOp.SUM.

`

**Comment by sentosajie** [comment] 2020-03-11 03:15
I have the same error

**Comment by HX1079299660** [comment] 2020-04-07 10:43
I have the same problem

**Comment by kamalkraj** [comment] 2020-04-24 15:22
@CheungZeeCn @akanyaani

The above code run perfectly in `3`-GPU configuration 
The code fails when the `global_batch_size` is perfectly dividable by no.of GPUs.

For example, if the no. of GPUs is 4. with global_batch_size 20. Each replica will have batch size of 5 each. This will fail with error  ` ValueError: A non-DistributedValues value 5 cannot be reduced with the given reduce op ReduceOp.SUM.`

If 3-GPU batch size across replicas is 7, 7, 6. which will train perfectly
<img width="1012" alt="Screenshot 2020-04-24 at 8 41 30 PM" src="https://user-images.githubusercontent.com/17096858/80227920-fcda2980-866b-11ea-83a6-416140a5a835.png">

Screenshot of code running in 3 and 4 GPU configuration
`3-GPU`
![screencapture-localhost-8080-notebooks-testing-multigpu-ipynb-2020-04-24-20_44_13](https://user-images.githubusercontent.com/17096858/80228761-129c1e80-866d-11ea-9d8d-279a72909453.png)
`4-GPU`
![screencapture-localhost-8080-notebooks-testing-multigpu-ipynb-2020-04-24-20_45_53](https://user-images.githubusercontent.com/17096858/80228875-3d867280-866d-11ea-95d2-0d4f67159237.png)

**Comment by sushreebarsa** [comment] 2021-08-01 14:41
@akanyaani  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-15 15:05 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:dist-strat, TF 2.0
