### ISSUE TITLE
Random test failures in tflite/xnnpack due to precision error

### ISSUE THREAD

**Issue by itmo153277** [tensorflow/tensorflow#54342] opened 2022-02-11 09:08 UTC
**System information**
- OS Platform and Distribution: WSL2 `tensorflow/tensorflow:devel-gpu`
- TensorFlow installed from source
- TensorFlow version: master

Tests `tensorflow/lite/delegates/xnnpack/...` can randomly fail due to precision error.

This issue caused my PR to be blocked from merging: https://github.com/tensorflow/tensorflow/pull/53864

The reason why it can fail is because the test data is generated randomly with seeding directly from `std::random_device`. The seeds are not logged when tests fail, so it is hard to reproduce a failure when it happens.

After the tests failed during pre-merge checks in my PR, I tried to reproduce it in my local environment inside `tensorflow/tensorflow:devel-gpu` docker. But on my machine the tests always passed.

However, I did find a way to get a consistent failure on `tensorflow/lite/delegates/xnnpack/softmax_test` (a different one from what failed in my PR). When compiled in `tensorflow/tensorflow:devel-gpu` with `copt` flags set to `-march=haswell -mtune=haswell -ffast-math` it always fails.

I think the tests should be improved to avoid random failures in the future:

- make the tests deterministic
- use gtest's `random_seed` for seeding
- log seeds when tests fail
- reconsider precision threshold

**Comment by tilakrayal** [comment] 2022-02-14 04:03
@itmo153277 ,
In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thanks!

**Comment by tilakrayal** [comment] 2022-02-14 08:45
@itmo153277 ,
In order to expedite the trouble-shooting process, could you please provide the complete code and tensorflow version to reproduce the issue reported here.

**Comment by itmo153277** [comment] 2022-02-14 11:02
@tilakrayal 
I was not able to reproduce the same failure that I got in my PR. If you have access to the test logs from that pre-merge build, you have better luck reproducing it.

How to reproduce `softmax_test` failure:

1. Start shell in `tensorflow/tensorflow:devel-gpu` docker
2. Clone `master` branch
3. Set `--config=opt` to `-march=haswell -mtune=haswell -ffast-math`
4. Run tests: `bazel test --config=opt -k tensorflow/lite/delegates/xnnpack/...`

Example session: [tf-test-fail.log](https://github.com/tensorflow/tensorflow/files/8060086/tf-test-fail.log)

**Comment by sachinprasadhs** [comment] 2022-02-17 01:18
@itmo153277 , I see that your PR is manually merged, is this issue good to close?. Thanks!

**Comment by itmo153277** [comment] 2022-02-17 02:08
I believe the issue itself has not been resolved, If the tensorflow team has decided that the issue is not worth fixing, feel free to close it.

**Comment by sachinprasadhs** [comment] 2022-02-23 00:48
I checked this PR internally and this got merged without any error, you can close the issue. Thanks!

**Comment by itmo153277** [comment] 2022-02-24 06:45
Sorry, I don't understand what you mean. If the PR was merged without errors it only confirms the issue, doesn't it?

I opened this issue not because my PR was blocked from merging but because I believe the tests should be improved.

**Comment by Venkat6871** [comment] 2024-10-22 04:23
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Closed** 2024-10-22 04:25 UTC
Labels: stat:awaiting response, type:build/install, subtype:bazel, comp:lite-xnnpack, wsl2
