### ISSUE TITLE
Custom Constraint not working

### ISSUE THREAD

**Issue by OnlyBelter** [tensorflow/tensorflow#42505] opened 2020-08-20 03:11 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
If I use custom constraint as `kernel_constraint` when I create a model:

    model = keras.Sequential([keras.layers.Dense(y.shape[1], activation='softplus',
                                                 kernel_constraint=SumConstraint(axis=0),
                                                 # kernel_constraint=keras.constraints.MinMaxNorm(),
                                                 bias_constraint=keras.constraints.MinMaxNorm(min_value=-100,
                                                                                              max_value=100),
                                                 input_shape=[x.shape[1]])])

I always got this `ValueError: Unknown constraint: SumConstraint`.

Even if I use the same class as @ymodak showed or use the example in document https://keras.io/api/layers/constraints/.

refer to: https://github.com/tensorflow/tensorflow/issues/39009
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2020-08-20 06:34
@OnlyBelter 

Request you to share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by OnlyBelter** [comment] 2020-08-20 08:30
It seems like both v2.2 and v2.3 can work well on [colab](https://colab.research.google.com/gist/OnlyBelter/31fc0f61dd94117d170111bb50236197), but both versions cannot work on windows 10.

So I think this may a problem depends on operation system.

**Comment by OnlyBelter** [comment] 2020-08-20 09:48
I find this error showed when I try to load model instead of create model:

```
model = keras.models.load_model('model_reg.h5', compile=False)
```

Even if I set `compile` to False or pass `custom_objects` like this [issue](https://github.com/keras-team/keras/issues/5916) said or this question https://stackoverflow.com/a/57985788/2803344.

**Comment by janapativishnu** [comment] 2020-08-20 19:32
@OnlyBelter I ran your code in Windows10, and I see the following output. It didn't throw any error as you mentioned. Thanks!
```
(10, 1)
2020-08-20 12:27:10.424721: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-08-20 12:27:10.443085: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-20 12:27:10.464796: I tensorflow/compiler/jit/xla_cpu_device.cc:54] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-08-20 12:27:11.785275: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:118] None of the MLIR optimization passes are enabled (registered 1)
Epoch 1/20
2/2 [==============================] - 1s 736ms/step - loss: 72.3553 - mae: 7.1552
Epoch 2/20
2/2 [==============================] - 0s 999us/step - loss: 50.0566 - mae: 5.4311
Epoch 3/20
2/2 [==============================] - 0s 997us/step - loss: 32.1105 - mae: 4.1114
Epoch 4/20
2/2 [==============================] - 0s 3ms/step - loss: 31.2048 - mae: 4.0403
Epoch 5/20
2/2 [==============================] - 0s 997us/step - loss: 30.0318 - mae: 4.1776
Epoch 6/20
2/2 [==============================] - 0s 997us/step - loss: 32.6021 - mae: 4.0476
Epoch 7/20
2/2 [==============================] - 0s 996us/step - loss: 25.2929 - mae: 3.4210
Epoch 8/20
2/2 [==============================] - 0s 984us/step - loss: 30.3775 - mae: 4.2098
Epoch 9/20
2/2 [==============================] - 0s 2ms/step - loss: 31.6408 - mae: 3.9248
Epoch 10/20
2/2 [==============================] - 0s 997us/step - loss: 29.7707 - mae: 3.9027
Epoch 11/20
2/2 [==============================] - 0s 1ms/step - loss: 32.0798 - mae: 3.9232
Epoch 12/20
2/2 [==============================] - 0s 997us/step - loss: 34.9411 - mae: 3.9599
Epoch 13/20
2/2 [==============================] - 0s 998us/step - loss: 35.0551 - mae: 4.0664
Epoch 14/20
2/2 [==============================] - 0s 997us/step - loss: 23.1408 - mae: 3.3541
Epoch 15/20
2/2 [==============================] - 0s 487us/step - loss: 29.1516 - mae: 4.7043
Epoch 16/20
2/2 [==============================] - 0s 997us/step - loss: 26.7001 - mae: 3.8203
Epoch 17/20
2/2 [==============================] - 0s 997us/step - loss: 29.6401 - mae: 4.4714
Epoch 18/20
2/2 [==============================] - 0s 997us/step - loss: 28.8710 - mae: 4.7452
Epoch 19/20
2/2 [==============================] - 0s 997us/step - loss: 30.0289 - mae: 3.7971
Epoch 20/20
2/2 [==============================] - 0s 1ms/step - loss: 32.4385 - mae: 4.4056
```

**Comment by jvishnuvardhan** [comment] 2020-08-20 19:34
@OnlyBelter As mentioned above, I cannot reproduce the error in my Windows10 desktop. Thanks!

Please verify and close the issue if this was already resolved for you. Thanks!

**Comment by janapativishnu** [comment] 2020-09-01 23:53
@OnlyBelter I was able to load the saved model after adding `custom_objects` argument as shown below

```
# saved model as follows
model.save('model_reg.h5',save_format='h5')

# loaded the model as shown below
model = keras.models.load_model('model_reg.h5', compile=False,custom_objects={'SoftMax':SoftMax})
```
It runs in Windows10 as well as in colab. 

Please verify once and close the issue. Thanks!

**Closed** 2020-09-11 22:19 UTC
Labels: TF 2.2, comp:keras, stalled, stat:awaiting response, type:bug
