### ISSUE TITLE
can't seem to find the urls to your provided binary packages

### ISSUE THREAD

**Issue by Tcll** [tensorflow/tensorflow#1516] opened 2016-03-15 17:53 UTC
I was expecting to download a portable package (.whl or .egg) and use it as such:

    import sys; sys.path.append( '/extensions/TensorFlow...win32.egg' )
    import tensorflow # if this line doesn't work, the egg/whl is not portable.
    # ...

when you say "provided binary packages" that just means I expect .pyd files within the egg or whl.

for an example of a portable egg, just look at pillow ;)

**Comment by mrry** [comment] 2016-03-15 18:40
Are you asking about Windows support? (If I understand correctly, `.pyd` files are Windows DLLs.)

We don't currently support Windows. See issue #17 for a tracking bug for Windows support.

**Comment by Tcll** [comment] 2016-03-15 18:46
ah alright, well just keep that method in mind then, I'll be watching ;)

**Comment by mrry** [comment] 2016-03-15 18:49
Closing this as a duplicate of #17. Hopefully it won't be too much effort to support that usage model as well!

**Closed by mrry** 2016-03-15 18:49 UTC
