### ISSUE TITLE
How can I use tensorflow2.0 beta1 multiple GPUs one computer to write a GAN code?

### ISSUE THREAD

**Issue by YonghuiXu** [tensorflow/tensorflow#31642] opened 2019-08-15 11:27 UTC
def main():
    def G_D_fn(train_data):  
        with tf.GradientTape() as tape:
            generates = G(train_data)  
            print(generates) 
            print("!!!!!!!!!!!!!!!!!")
            logits_fake = D(generates)   #error here, but if I do not use multiple GPUs, the program is normal.

 with strategy.scope():
      # obtain models
      G = get_G((batch_size, None, None, 3)) #(batch_size, 128, 128, 3)
      D = get_D((batch_size, None, None, 3)) 
      train_dataset = get_data()
      train_dist_dataset = strategy.experimental_distribute_dataset(train_dataset)
     for epoch in range(10):
          for one_batch in train_dist_dataset:
              per_loss = strategy.experimental_run_v2(G_D_fn, args=(epoch, batch_data, ))

Traceback (most recent call last):
  File "train.py", line 680, in <module>
    train()
  File "train.py", line 319, in train
    per_d_loss, per_g_loss, per_d_loss1, per_d_loss2, per_g_gan_loss, per_mse_loss, per_vgg_loss, per_style_loss = strategy.experimental_run_v2(G_D_fn, args=(epoch, batch_data, ))
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 708, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1710, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 708, in _call_for_each_replica
    fn, args, kwargs)
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 195, in _call_for_each_replica
    coord.join(threads)
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 189, in _call_for_each_replica
    **merge_kwargs)
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/training/moving_averages.py", line 105, in merge_fn
    return update(strategy, v, value)
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/training/moving_averages.py", line 96, in update
    return strategy.extended.update(v, update_fn, args=(value,))
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1458, in update
    return self._update(var, fn, args, kwargs, group)
  File "/home/dongwen/anaconda3/envs/tf2/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 758, in _update
    assert isinstance(var, values.DistributedVariable)
AssertionError

**Comment by esslushy** [comment] 2019-08-15 13:53
In reference to the gpu tutorial found [here](https://www.tensorflow.org/beta/guide/using_gpu#using_multiple_gpus) you can run multiple gpus by wrapping each individual model call in their own tf.device('gpu:x'): setup. For example:
```
with tf.device('gpu:0'):
    generator(noise)
with tf.device('gpu:1'):
    discriminator(images)
```
This is a rough example, but is how you would do it. I don't know if mirrored strategy works right now with a custom loop, but also take a look at that.

**Comment by YonghuiXu** [comment] 2019-08-16 03:41
I just tried it. The error is as follows:
        with tf.GradientTape(persistent=True) as tape:
            with tf.device('/gpu:0'):
                generates = G(train_data) 
            with tf.device('/gpu:1'): 
                logits_fake = D(generates) 
2019-08-16 10:55:59.977308: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at nccl_ops.cc:100 : Unknown: Error invoking NCCL: unhandled cuda error
2019-08-16 10:55:59.977378: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Error invoking NCCL: unhandled cuda error
	 [[{{node NcclAllReduce}}]]

My code as follows:
    def G_D_fn(epoch, batch_data):
       train_data = batch_data   
        with tf.GradientTape(persistent=True) as tape:
            with tf.device('/gpu:0'):
                generates = G( train_data) 
            with tf.device('/gpu:1'): 
                logits_fake = D(generates) 
       ##logits_fake = D(generates)
            feature_fake = VGG((generates+1)/2.)   #If I use vgg, it works normal. If I use D, it has error.
            d_loss = tl.cost.sigmoid_cross_entropy(logits, tf.ones_like(logits_fake))
            g_gan_loss = 1e-3 * tl.cost.sigmoid_cross_entropy(logits_fake, tf.ones_like(logits_fake))
        grad = tape.gradient(g_loss, G.trainable_weights)
        g_optimizer.apply_gradients(zip(grad, G.trainable_weights))
     
        grad = tape.gradient(d_loss, D.trainable_weights)
        d_optimizer.apply_gradients(zip(grad, D.trainable_weights))
        return d_loss, g_gan_loss


    print("Begin training...")
    devices = ['/device:GPU:{}'.format(i) for i in range(num_gpu)] 
    strategy = tf.distribute.MirroredStrategy(devices)
    with strategy.scope():
        train_log_dir = 'logs/gradient_tape/train'
        train_summary_writer = tf.summary.create_file_writer(train_log_dir)
        # obtain models
        G = get_G((batch_size, None, None, 3))
        D = get_D((batch_size, None, None, 3)) 
        VGG = tl.models.vgg19(pretrained=True, mode='static') 
        lr_v = tf.Variable(lr_init)
        g_optimizer_init = tf.optimizers.Adam(lr_v, beta_1=beta1)
        g_optimizer = tf.optimizers.Adam(lr_v, beta_1=beta1)
        d_optimizer = tf.optimizers.Adam(lr_v, beta_1=beta1)
    
        G.train()
        D.train()
        VGG.train()
    
        train_ds = get_train_data()
        dist_train_ds = strategy.experimental_distribute_dataset(train_ds)

        n_batch_epoch = round(n_epoch // batch_size)  
        for epoch in range(n_epoch):    
            total_mse_loss = 0.0
            batch = 0
            for batch_data in dist_train_ds:
                batch += 1                 
                per_d_loss, per_g_gan_loss = strategy.experimental_run_v2(G_D_fn, args=(epoch, batch_data, ))
                total_d_loss += strategy.reduce(tf.distribute.ReduceOp.SUM, per_d_loss, axis = 0)
                total_g_gan_loss += strategy.reduce(tf.distribute.ReduceOp.SUM, per_g_gan_loss, axis = 0)
    
            d_loss = total_d_loss/batch
            g_gan_loss = total_g_gan_loss/batch

            print("g_gan:{:.6f}, d_loss: {:.9f}".format(g_gan_loss, d_loss))

**Comment by gadagashwini** [comment] 2019-08-16 09:21
@YonghuiXu Will it be possible to provide the complete and proper indent code to reproduce the reported issue. Thanks!

**Comment by YonghuiXu** [comment] 2019-08-16 09:38
Is it not possible to calculate the logits_fake and logits_real here for Tensorflow 2.0 beta?




------------------ 原始邮件 ------------------
发件人: "gadagashwini"<notifications@github.com>; 
发送时间: 2019年8月16日(星期五) 下午5:28
收件人: "tensorflow/tensorflow"<tensorflow@noreply.github.com>; 
抄送: "姐妹的海洋"<2259949930@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tensorflow/tensorflow] How can I use tensorflow2.0 beta1multiple GPUs one computer to write a GAN code? (#31642)




@YonghuiXu Will it be possible to provide the complete and proper indent code to reproduce the reported issue. Thanks!

**Comment by YonghuiXu** [comment] 2019-08-16 12:49
Hi,@gadagashwini @Slushy. I have find the problem.There are BatchNorm layers in my discriminator. When I delete them, the program can work. Or when I didn't use tf.distribute.MirroredStrategy, the program can work. Do tf.distribute.MirroredStrategy permit batch norm ?

**Comment by gadagashwini** [comment] 2019-08-19 04:54
@YonghuiXu Please Provide us the reproducible code. It will indeed help us to move faster.

**Comment by gadagashwini** [comment] 2019-08-26 08:43
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-08-26 08:43 UTC
Labels: 2.0.0-beta0, comp:dist-strat, stat:awaiting response, type:support
