### ISSUE TITLE
TF 1.15.2 Memory Leak 

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/tensorflow#37960] opened 2020-03-27 03:53 UTC
**System information** 

- OS Platform and Distribution : macOS Catalina 10.15.3

- TensorFlow installed from : binary

- TensorFlow version : 1.15.2
- Python version: 3.7.3

**Describe the current behavior**

I am running simple tensorflow  sess.run as below -

`from tensorflow.python.framework import ops`
`import gc`
`import psutil`
`process = psutil.Process(os.getpid())`

`N_REPS = 10000`
`sess = tf.Session(graph=tf.Graph())`
`tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], saved_model_path)`
`for i in range(N_REPS):`
        &nbsp;&nbsp;&nbsp;&nbsp;`sess.graph.finalize()`
	&nbsp;&nbsp;&nbsp;&nbsp;`tf.reset_default_graph()`
        &nbsp;&nbsp;&nbsp;&nbsp;`with tf.Graph().as_default() as graph:`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`tf.get_default_graph().finalize()`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`scores = self.sess.run(['<loss>'], feed_dict={'k':v})`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`memoryUsed = process.memory_info().rss`
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`del v`
	&nbsp;&nbsp;&nbsp;&nbsp;`gc.collect()`

The memory is increasing from 0th iteration till i reach 10000 iteration.

I also tried to see if any operation is added to graph by using `self.sess.graph.finalize()` and it run perfectly well without throwing error which means no new operation is added to graph .

**Describe the expected behavior**

I expect memory to be constant. 

How to solve this memory issue ?

**Comment by 17patelumang** [comment] 2020-03-27 15:33
any updates ?

**Comment by gowthamkpr** [comment] 2020-03-30 17:49
@17patelumang Looks like the code is incomplete. Can you please share the complete code with saved model file for us to reproduce this issue. Thanks!

**Comment by 17patelumang** [comment] 2020-03-30 18:11
@gowthamkpr I cannot unfortunately share the saved mode, but for the code the saved model we have TF api ported  inside saved model

**Comment by gowthamkpr** [comment] 2020-03-30 18:18
Can you share a dummy simple code for us to reproduce this issue as it it hard to look into it if we cannot reproduce it. Thanks!

**Comment by 17patelumang** [comment] 2020-03-30 18:45
@gowthamkpr thank you for reply below is the code


`import tensorflow as tf`
`from tensorflow.python.framework import ops`
`import gc`
`import psutil`
`process = psutil.Process(os.getpid())`

`N_REPS = 1000`
`sess = tf.Session(graph=tf.Graph())`
`tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], saved_model_path)`
`text="this is dummy string"`

`for i in range(N_REPS):`
    `sess.graph.finalize()`
    `tf.reset_default_graph()`
    `with tf.Graph().as_default() as graph:`
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`tf.get_default_graph().finalize()`
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`scores = sess.run(['loss/Sigmoid:0'], feed_dict={'text':text})`
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`memoryUsed = process.memory_info().rss`
    `del text`
    `gc.collect()`

**Comment by gowthamkpr** [comment] 2020-03-30 19:04
I am not able to reproduce the issue using the above code @17patelumang. `saved_model_path` is still missing.

**Comment by 17patelumang** [comment] 2020-03-30 21:42
how to share dummy saved_model ?

**Comment by gowthamkpr** [comment] 2020-03-31 17:33
Can you please share a saved model with which I can reproduce this issue. Thanks!

**Comment by mitsuix** [comment] 2020-04-10 07:08
@17patelumang 
I also met this problem. 
How did you sovle this problem? Thanks a lot

**Comment by 17patelumang** [comment] 2020-04-12 06:18
@mitsuix  1. I checked if i was adding any ops to metagraph every time i do iteration
2. I was finalizing graph after every iteration  `sess.graph.finalize()` 

I was not able to solve it fully however i mitigated it ? , if you can share the code and savedmodel (which i cannot) it would be helpful .

**Comment by gowthamkpr** [comment] 2020-06-04 19:44
@mitsuix @17patelumang Without reproducing the issue, its hard to find the root cause. I would recommend you guys to please share a colab notebook that reproduces the problem. Thanks!

**Comment by gowthamkpr** [comment] 2020-06-12 13:30
Closing this issue as it is not reproducible. Please add additional comments for us to open this issue again. Thanks!

**Closed by gowthamkpr** 2020-06-12 13:30 UTC
Labels: TF 1.15, stalled, stat:awaiting response, type:performance

**Comment by hoyden** [comment] 2021-11-12 03:53
@lichengcheng5945 I met the same problem! Did you solve it ?
