### ISSUE TITLE
Bazel command to get dependency graph fails

### ISSUE THREAD

**Issue by dzorwulu** [tensorflow/tensorflow#53145] opened 2021-11-20 22:46 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.7
- Python version:  3.7
- Installed using virtualenv? pip? conda?: n/a
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): MSVS 2019
- CUDA/cuDNN version: 11.5
- GPU model and memory: NVid
[error.log](https://github.com/tensorflow/tensorflow/files/7575460/error.log)
ia Geforce 940MX 

**Describe the problem**
Cannot generate dependency graph text with:
bazel query --notool_deps --noimplicit_deps "deps(tensorflow:tensorflow_cc)" --output graph
The following errors might be the problem:
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/43d6991c2a4cc2ac374e68c029634f2b59ffdfdf.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/64c92c8013b557087351c91b5423b6046d10f206.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

**Provide the exact sequence of commands / steps that you executed before running into the problem**
git clone https://github.com/tensorflow/tensorflow.git .
git checkout r2.7
Added startup --output_user_root=C:/tmp   to bazelrc file 
bazel query --notool_deps --noimplicit_deps "deps(tensorflow:tensorflow_cc)" --output graph

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

=========
F:\workdir\units\unit_1_asa\ai\project\c++\ml\dl\software\tensorflow\tf>bazel query --notool_deps --noimplicit_deps "deps(tensorflow:tensorflow_cc)" --output graph
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/43d6991c2a4cc2ac374e68c029634f2b59ffdfdf.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/64c92c8013b557087351c91b5423b6046d10f206.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: Repository llvm-project instantiated at:
  F:/workdir/units/unit_1_asa/ai/project/c++/ml/dl/software/tensorflow/tf/WORKSPACE:15:14: in <toplevel>
  F:/workdir/units/unit_1_asa/ai/project/c++/ml/dl/software/dl-tool/bazel/.bazel/6iwvpnw5/external/llvm-raw/utils/bazel/overlay_directories.py --src F:/workdir/units/unit_1_asa/ai/project/c++/ml/dl/software/dl-tool/bazel/.bazel/6iwvpnw5/external/llvm-raw --overlay F:/workdir/units/unit_1_asa/ai/project/c++/ml/dl/software/dl-tool/bazel/.bazel/6iwvpnw5/external/llvm-raw/utils/bazel/llvm-project-overlay --target .'
Exited with code 1
stdout:

[error.log](https://github.com/tensorflow/tensorflow/files/7575461/error.log)

**Comment by tilakrayal** [comment] 2021-11-22 07:40
@dzorwulu ,
Looks like this is duplicate of issue #53109.Can you please close this issue, since it is already being tracked there? Thanks!

**Closed** 2021-11-22 07:56 UTC
Labels: stat:awaiting response, type:build/install, subtype:bazel, TF 2.7

**Comment by dzorwulu** [comment] 2021-11-22 07:58
Similar to error outlined in issue  #53109.
