### ISSUE TITLE
    .pb Model in android is not detecting images

### ISSUE THREAD

**Issue by Shazuka** [tensorflow/tensorflow#20449] opened 2018-07-01 07:33 UTC
Using Window 10
Tensoflow installed from its main site.
2.0 version
Using Android studio
No Bazel
I am using following code to train my dataset. The code first downloads the requested model and then create .pb file with label text file. The link is as follows:
https://github.com/loicmarie/sign-language-alphabet-recognizer
After converting my model into .pb file and getting labels, I loaded my model into following android code:
https://github.com/Nilhcem/tensorflow-classifier-android
Then I make little changes to code according to my model.
![screenshot 92](https://user-images.githubusercontent.com/32578887/42205475-0617f714-7ebe-11e8-9390-a5248d8362fd.png)
Please, where I am wrong what I need to make image detection possible. As it is not giving labels...

**Comment by tensorflowbutler** [comment] 2018-07-01 18:36
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by aselle** [comment] 2018-07-23 16:42
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by aselle** 2018-07-23 16:42 UTC
Labels: stat:awaiting response
