### ISSUE TITLE
num_replicas_in_sync not equel to my gpus.

### ISSUE THREAD

**Issue by jkkj1630** [tensorflow/tensorflow#37618] opened 2020-03-15 20:17 UTC
strategy = tf.distribute.MirroredStrategy()
print('Number of devices: {}'.format(strategy.num_replicas_in_sync))

i have 4x2080Ti
but when i run this code, i got :
Number of devices: 1

and training a model have warning:
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.

and no gpu in used

tensorflow 2.1.0
keras 2.3.1

**Comment by amahendrakar** [comment] 2020-03-16 08:51
@jkkj1630,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by 372046933** [comment] 2020-03-18 10:45
@amahendrakar , in `MultiworkerMirroredStrategy`, does `num_replicas_in_sync` return the number of replicas per worker or total number of replicas in `TF_CONFIG`

**Comment by mrh335** [comment] 2020-03-25 15:41
I am having the same issue. Using a Gcloud compute instance. The complete code to reproduce the issue is below. I have 4 x T4 GPUs on the machine.

import tensorflow as tf
strategy = tf.distribute.MirroredStrategy()

results in the following message
WARNING:tensorflow:There are non-GPU devices in `tf.distribute.Strategy`, not using nccl allreduce.
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)

**Comment by amahendrakar** [comment] 2020-03-27 16:46
> @jkkj1630,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

Any updates regarding the reproducible code?

@mrh335,
Could you please submit a new issue using [this](https://github.com/tensorflow/tensorflow/issues/new/choose) link so that we can track it there.

 Thanks!

**Comment by amahendrakar** [comment] 2020-04-03 16:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-03 16:45 UTC
Labels: TF 2.1, comp:dist-strat, stat:awaiting response, type:support
