### ISSUE TITLE
Show responsible nodes when ValueError: No gradients provided for any variable

### ISSUE THREAD

**Issue by kmader** [tensorflow/tensorflow#1768] opened 2016-04-04 14:37 UTC
The error message 
```
ValueError: No gradients provided for any variable
```
Is not particularly informative and it would be nice to see if there is a node preventing the gradient calculation (ie Gradient Cannot be calculated for ```Cast``` or ```ResizeBilinear``` operation) or if there is simply no connection (the variable is not connected to the loss function in any way.)

Both of the following issues dealt with this and debugging would be easier if the error message was more explicit. 
- Shows a specific example where the Inception network has nodes which are not differentiable: https://github.com/tensorflow/tensorflow/issues/1758
- A more obscure but related issue: https://github.com/tensorflow/tensorflow/issues/1511

**Comment by itsmeolivia** [comment] 2016-05-16 16:58
I looked into the code base for when that error is raised and the only place is in the optimizer.py code that was referenced in #1758 which does show the nodes responsible.  I'm closing this because the uninformative error message is not reproducible.  Feel free to reopen if you can provide more details.

**Closed by itsmeolivia** 2016-05-16 16:58 UTC
Labels: contributions welcome, enhancement

**Comment by rlrs** [comment] 2016-07-19 12:13
The error in optimizer.py prints the Variable object, which is shown as e.g. `<tensorflow.python.ops.variables.Variable object at 0x7ff7ed095350>`, not very informative. It should probably display `Variable.name`.

**Comment by jstaker7** [comment] 2016-08-05 19:44
I agree with rlrs. I have no easy way to know which variables are causing the failure.

**Comment by keven425** [comment] 2016-09-23 07:11
I agree. This error `No gradients provided for any variable` is not informative. Would be ideal to show the node that caused the error.

**Comment by sjtusmartboy** [comment] 2021-08-05 11:45
I agree. This error No gradients provided for any variable is not informative. Would be ideal to show the node that caused the error.
