### ISSUE TITLE
JSON serializable issue at RemoteMonitor

### ISSUE THREAD

**Issue by Telcoltar** [tensorflow/tensorflow#32192] opened 2019-09-03 21:25 UTC
The Tensorflow implementation of RemoteMonitor callback raises the error
`Object of type float32 is not JSON serializable.`

Keras own implementation works fine with the same code.

I think the relevant code difference is 
    
```
for k, v in logs.items():
      send[k] = v

```
in the Tensorflow implementation and

```
for k, v in logs.items():
            if isinstance(v, (np.ndarray, np.generic)):
                send[k] = v.item()
            else:
                send[k] = v
```

in the Keras implementation.

**Comment by ravikyram** [comment] 2019-09-04 06:08
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the minimal code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Telcoltar** [comment] 2019-09-04 12:08
My description above was a little bit short. It was meant as a short notice that the tensorflow.keras RemoteMonitor class has a bug which the Keras RemoteMonitor class does not have. Let me explain it with a little bit more detail.

I have made a quick example which shows the error.

```
import tensorflow as tf
import numpy as np
import tensorflow.keras as keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Activation, BatchNormalization, MaxPool2D
from tensorflow.keras.optimizers import Adam, Adadelta
import tensorflow.keras.losses as losses
import tensorflow.keras.metrics as metrics
from tensorflow.keras.callbacks import RemoteMonitor, LambdaCallback, Callback

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

x_train = x_train.reshape(-1,28,28,1) / 255
x_test = x_test.reshape(-1,28,28,1) / 255

y_train = y_train.astype(np.int32)
y_test = y_test.astype(np.int32)

remote_cb = RemoteMonitor(root="http://localhost:9000", path="/publish/epoch/end/", send_as_json=True)

model = Sequential()
model.add(Conv2D(64,(3,3), activation="relu", input_shape=(28,28,1)))
model.add(MaxPool2D((2,2)))
model.add(BatchNormalization())
model.add(Flatten())
model.add(Dense(256, activation="relu"))
model.add(Dense(10, activation="softmax"))

model.compile(loss=losses.sparse_categorical_crossentropy, optimizer=Adam(),
              metrics = ["accuracy"])

model.fit(x_train[:3000], y_train[:3000], epochs=5, batch_size=64, callbacks=[remote_cb])
```

This code gives a error 
`Object of type float32 is not JSON serializable`.

But when delete the Tensorflow from the imports, so using the keras implementation, then the above code works fine.

So I looked at the tensorflow.keras  [RemoteMonitor class](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/callbacks.py#L1264-L1316) and compared it to the [Remote Monitor class](https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L847) from keras.

As stated above the relevant difference is

```
for k, v in logs.items():
      send[k] = v
```

in the Tensorflow.keras and 

```
for k, v in logs.items():
            if isinstance(v, (np.ndarray, np.generic)):
                send[k] = v.item()
            else:
                send[k] = v
```

in the keras implementation.

I have also tried to replace the lines in the Tensorflow.keras callback.py file with the lines from the keras callbacks.py file and then the code works with the Tensorflow imports.

**Comment by ravikyram** [comment] 2019-09-05 12:29
I have tried on colab with 2.0.0-rc0 and was able to reproduce the issue.Please,find the [gist ](https://colab.sandbox.google.com/gist/ravikyram/bf10dde754b4e8d73d8c021e4e014120/untitled156.ipynb) here.Please, let us know which TensorFlow version you are using?.Thanks!

**Comment by Telcoltar** [comment] 2019-09-05 12:43
I have used 1.14.0, but the class RemoteMonitor is in 1.14.0 and 2.0.0-rc0 identical.

**Comment by ravikyram** [comment] 2019-09-06 12:40
I have tried on colab with 2.0.0-rc0,1.14,TF nightly versions and was able to reproduce the issue.Please,find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/1be5308bed758dc9cedb42e2a866983b/untitled156.ipynb).Thanks!

**Comment by ashahab** [comment] 2019-09-23 18:21
Hi, I would like to work on fixing this.

**Comment by yhliang2018** [comment] 2020-03-26 18:50
As the PR has been merged, close the bug for now. Feel free to reopen it if needed.

**Closed by yhliang2018** 2020-03-26 18:50 UTC
Labels: TF 1.14, comp:keras, stat:awaiting tensorflower, type:bug

**Comment by vinayentc** [comment] 2020-04-22 13:57
Is this issue resolved, which build has this issue resolved?
