### ISSUE TITLE
I am getting  the compilation error as 'tensorflow/lite/kernels/register.h' file not found in example cameraxcworkspace

### ISSUE THREAD

**Issue by nihp** [tensorflow/tensorflow#23706] opened 2018-11-13 07:05 UTC
I am trying to build the example camera from the tensorflow. But it shows the error as 'tensorflow/lite/kernels/register.h' file not found in my Xcode. 
![screen shot 2018-11-13 at 12 34 51 pm](https://user-images.githubusercontent.com/36992338/48396490-9c3d8200-e740-11e8-8cdd-008887ec5880.png)

**Comment by nihp** [comment] 2018-11-14 05:09
I have tried to run the example app of tensor flow by following the document. https://www.tensorflow.org/lite/demo_ios


I have set up as mentioned all, while I am hitting the run button I am getting the error 'tensorflow/lite/kernels/register.h'

Kindly clarify as soon as possible.

**Comment by jakublipinski** [comment] 2018-11-15 14:52
@nihp  you should add `tensorflow/tensorflow` folder to your `Header Search Paths` in project `Build Settings`

**Comment by wt-huang** [comment] 2018-11-15 21:20
First check the file is indeed there, make sure location is set to "Relative to Project"
Go to the menu bar then Product select Clean, hold option key then go to Product select Clean Build Folder

You can fill out the issue template:

**System information**

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version (use command below):
Python version:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:

**Comment by lyycfairy** [comment] 2018-11-22 13:42
@miaout17 It works! thanks

**Comment by jakublipinski** [comment] 2018-11-28 15:36
Thank you @miaout17 ! It also helped me a bit but I'm still struggling with [a related issue](https://stackoverflow.com/questions/53364001/tensorflow-lite-ios-camera-example-does-not-work-with-retrained-mobilenet-model). Could you please take a look? Thanks.

**Comment by nihp** [comment] 2018-12-04 13:17
@miaout17 I am getting Thread 1: signal SIGABRT while trying to run the tflite_camera_example.xcworkspace  project. 

@miaout17  Compilation error gone! Thanks

**Comment by shashishekhar** [comment] 2019-01-29 20:17
Looks like the issue is resolved, closing this.

**Closed by shashishekhar** 2019-01-29 20:17 UTC
Labels: comp:lite
