### ISSUE TITLE
cannot import a pretrained mobilenet multiple times

### ISSUE THREAD

**Issue by Nitinsiwach** [tensorflow/tensorflow#29140] opened 2019-05-29 18:36 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):1.12
- Python version:2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1.105
- GPU model and memory: m60, 8gb

I am trying to use a pre-trained MobileNet for transfer learning however i am running into a problem when i am trying to run the same command the second time

    import tensorflow as tf
    try:
        del g1
    except:
        pass
    tf.reset_default_graph()
    g1 = tf.Graph() #or g1 = tf.get_default_graph() both result in same behavior
    with g1.as_default():
        base_model = tf.keras.applications.MobileNetV2(input_shape=(160,160,3),
                                                           include_top=False,
                                                           weights='imagenet')
I can run this cell in jupyter alright the first time but the second time i try to run this i get 
`TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder_207:0", shape=(160,), dtype=float32) is not an element of this graph.`
However, I can run this cell multiple times perfectly fine

    base_model = tf.keras.applications.MobileNetV2(input_shape=(160,160,3),
                                                           include_top=False,
                                                           weights='imagenet')

**Comment by gadagashwini** [comment] 2019-05-30 06:40
I was able to reproduce the mentioned issue on Tensorflow 1.12.

**Comment by Nitinsiwach** [comment] 2019-06-07 13:26
Any updates on this?

**Comment by jvishnuvardhan** [comment] 2019-06-10 23:59
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by Nitinsiwach** [comment] 2019-06-11 09:18
How is this not a Bug?

**Comment by jvishnuvardhan** [comment] 2019-10-22 00:08
@Nitinsiwach Sorry for the delay in my response. I ran your code in `TF1.15.0` and I don't see the issue. That particular block I ran 7 times without any issue. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/e2439a3866424044d428d3e9567cea1f/untitled588.ipynb). Thanks

**Comment by jvishnuvardhan** [comment] 2019-11-02 14:54
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-11-02 14:54 UTC
Labels: TF 1.12, comp:model, stat:awaiting response, type:bug
