### ISSUE TITLE
Feature request: classifier deallocation

### ISSUE THREAD

**Issue by alltom** [tensorflow/tensorflow#13821] opened 2017-10-18 22:13 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12.6
- **TensorFlow installed from (source or binary)**: Binary? (pip)
- **TensorFlow version (use command below)**: ('v1.3.0-rc2-20-g0787eee', '1.3.0') (tensorflow)
- **Python version**: 2.7.8
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: https://gist.github.com/alltom/75f3c0e62cd679c5e8af368bb49370c6

### Describe the problem
[DNNClassifier](https://www.tensorflow.org/api_docs/python/tf/estimator/DNNClassifier) doesn't appear to have any methods for freeing its resources, and that doesn't seem to occur automatically if I let the classifier go out of scope.

In [the gist linked above](https://gist.github.com/alltom/75f3c0e62cd679c5e8af368bb49370c6), I train, evaluate, and throw away DNNClassifiers as part of a genetic algorithm for feature selection, but after training a little more than a hundred models, it fails:

`InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./model_2017-10-18-21:41:26/125/model.ckpt-4000: Resource exhausted: ./model_2017-10-18-21:41:26/125`

### Source code / logs
https://gist.github.com/alltom/75f3c0e62cd679c5e8af368bb49370c6

**Comment by drpngx** [comment] 2017-10-18 23:55
Thank you for the report! Appreciate the effort to create a repro case.

@roumposg any clue?

**Comment by roumposg** [comment] 2017-10-19 05:44
I don't see why DNNClassifier should free up resources when it goes out of scope. Python does not have variable scopes like c++. To me, this looks like it is working as intended. @xiejw what do you think?

Why do you need to create a new DNNClassifier in every iteration? Can't you just have one and keep training.

**Comment by roumposg** [comment] 2017-10-19 16:37
We tried to reproduce your error, but we are missing the training.csv and test.csv files. Can you provide those files, or edit your code to not depend on them?

Also, it is not clear if the error message is due to memory exceeded or disk exceeded. Can you monitor memory and disk usage while your program is running? That will help us debug, thanks.

**Comment by alltom** [comment] 2017-10-19 19:15
I ran it again, but memory and disk usage remained stable (save for the tiny model files the DNNClassifiers were saving, and nowhere near full), so my guess it's file handle exhaustion.

I added a call to `gc.collect()` right before every time a new model is trained, and this time instead of failing with the "resource exhausted" error, it failed with `Segmentation fault: 11` at the same part (~125 models trained). For whatever that's worth. :)

**Comment by drpngx** [comment] 2017-10-21 18:59
SIGSEGV is definitely a problem.

**Comment by yaroslavvb** [comment] 2017-10-24 21:27
to get sigserv stack trace:

ulimit -Sc unlimited
<crash things>
gdb python
core core

<paste stack trace>

**Comment by roumposg** [comment] 2017-10-24 23:23
Thanks for uploading the files. I modified train.py to add a counter for counting how many candidates have been constructing in total, and ran it in ubuntu (Tensorflow 1.3 installed with virtualenv). It produced ~1000 candidates so far without problems before I stopped the script.

Perhaps this is something mac-specific, so I will try running it on macOS.

Tom, can you paste the full error message / stack trace? Thanks.

**Comment by alltom** [comment] 2017-10-27 05:33
@yaroslavvb I don't have gdb installed, so I can't get a core dump that way. :(

@roumposg I added a complete stack trace to the gist.

**Comment by roumposg** [comment] 2017-11-02 15:48
I was not able to reproduce the problem. It seems like it is mac-specific, and I am not an expert in that, so I am unassigning myself.

For the record, I attach the modified file I used, which counts the number of models created (rename from train.txt to train.py to use the file).
[train.txt](https://github.com/tensorflow/tensorflow/files/1438398/train.txt)

**Comment by alltom** [comment] 2017-11-06 04:07
The problem doesn't seem to be specific to training…

To bypass the issue in this thread, I picked parameters by hand. Then I launched a tensorflow-serving instance with the trained model, also on macOS. After a few thousand calls to Predict, the tensorflow-serving server dies with its own resource exhaustion errors:

```
E1105 19:59:59.686989000 123145381662720 wakeup_fd_pipe.c:37]          pipe creation failed (24): Too many open files
E1105 19:59:59.687045000 123145381662720 ev_poll_posix.c:875]          pollset_work: {"created":"@1509940799.687023000","description":"OS Error","errno":24,"file":"external/grpc/src/core/lib/iomgr/wakeup_fd_pipe.c","file_line":38,"os_error":"Too many open files","syscall":"pipe"}
E1105 19:59:59.687055000 123145381662720 completion_queue.c:1131]      Completion queue pluck failed: {"created":"@1509940799.687023000","description":"OS Error","errno":24,"file":"external/grpc/src/core/lib/iomgr/wakeup_fd_pipe.c","file_line":38,"os_error":"Too many open files","syscall":"pipe"}
E1105 19:59:59.687060000 123145413857280 wakeup_fd_pipe.c:37]          pipe creation failed (24): Too many open files
E1105 19:59:59.687076000 123145381662720 wakeup_fd_pipe.c:37]          pipe creation failed (24): Too many open files
E1105 19:59:59.687091000 123145413857280 ev_poll_posix.c:875]          pollset_work: {"created":"@1509940799.687069000","description":"OS Error","errno":24,"file":"external/grpc/src/core/lib/iomgr/wakeup_fd_pipe.c","file_line":38,"os_error":"Too many open files","syscall":"pipe"}
E1105 19:59:59.687094000 123145381662720 ev_poll_posix.c:875]          pollset_work: {"created":"@1509940799.687083000","description":"OS Error","errno":24,"file":"external/grpc/src/core/lib/iomgr/wakeup_fd_pipe.c","file_line":38,"os_error":"Too many open files","syscall":"pipe"}
E1105 19:59:59.687131000 123145413857280 completion_queue.c:1131]      Completion queue pluck failed: {"created":"@1509940799.687069000","description":"OS Error","errno":24,"file":"external/grpc/src/core/lib/iomgr/wakeup_fd_pipe.c","file_line":38,"os_error":"Too many open files","syscall":"pipe"}
E1105 19:59:59.687139000 123145406881792 wakeup_fd_pipe.c:37]          pipe creation failed (24): Too many open files
E1105 19:59:59.687147000 123145381662720 completion_queue.c:1131]      Completion queue pluck failed: {"created":"@1509940799.687083000","description":"OS Error","errno":24,"file":"external/grpc/src/core/lib/iomgr/wakeup_fd_pipe.c","file_line":38,Segmentation fault: 11
```

Why does TensorFlow open so many pipes without closing them? Should I open a new issue for this?

**Comment by drpngx** [comment] 2017-12-05 17:26
Closing since it's hard to repro.

**Closed by drpngx** 2017-12-05 17:26 UTC
