### ISSUE TITLE
sparse_image_warp don't accept the tensor with dynamic shape.

### ISSUE THREAD

**Issue by cahuja1992** [tensorflow/tensorflow#28431] opened 2019-05-06 08:55 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04)
- TensorFlow installed from (binary)
- TensorFlow version (1.13.1)
- Python version

**Describe the current behavior**
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/image/python/ops/sparse_image_warp.py", line 179, in sparse_image_warp
    grid_locations = _get_grid_locations(image_height, image_width)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/image/python/ops/sparse_image_warp.py", line 34, in _get_grid_locations
    y_range = np.linspace(0, image_height - 1, image_height)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Describe the expected behavior**
No error: should return the warped image

**Code to reproduce the issue**
image_placeholder = tf.placeholder(dtype=tf.float32, shape=[1, None, None, 1])
src_pts = tf.constant([10, 10])
dest_pts = tf.constant([100, 100])
tf.contrib.image.sparse_image_warp(image_placeholder,
                                                        source_control_point_locations = src_pts,
                                                         dest_control_point_locations = dest_pts,
                                                         interpolation_order = 2,
                                                         regularization_weight = 0,
                                                         num_boundary_points = 1
                                                         ) 
**Other info / logs**
None.

**Comment by cahuja1992** [comment] 2019-05-06 09:07
After having a look at
https://github.com/tensorflow/tensorflow/blob/6096a8f9088f4da725db4a15684a961724943eb8/tensorflow/contrib/image/python/ops/sparse_image_warp.py#L175

Found that as this functionality is currently being provided using numpy which requires the static shape of the shape.

**Comment by gadagashwini** [comment] 2019-07-12 11:57
@cahuja1992 Can you please tell us is this still an issue? Thanks!

**Comment by gadagashwini** [comment] 2019-07-17 04:48
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-17 04:48 UTC
Labels: comp:ops, stat:awaiting response, type:bug/performance

**Comment by spencerfrei** [comment] 2019-09-27 01:00
Hi, I've run into this issue as well.  In order to use sparse_image_warp() in a custom Keras layer, it throws an error because it is expecting numbers rather than dynamic tensor shapes (i.e. "None").  The error I received came from a similar chain:

  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/sparse_image_warp.py", line 185, in sparse_image_warp
    _expand_to_minibatch(flattened_grid_locations, batch_size), image.dtype)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/contrib/image/python/ops/sparse_image_warp.py", line 43, in _expand_to_minibatch
    return np.tile(np.expand_dims(np_array, 0), tiles)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 1236, in tile
    shape_out = tuple(s*t for s, t in zip(c.shape, tup))
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 1236, in <genexpr>
    shape_out = tuple(s*t for s, t in zip(c.shape, tup))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by gadagashwini** [comment] 2019-09-27 04:44
@spencerfrei , Please post a new issue and provide all the information asked by the [template](https://github.com/tensorflow/tensorflow/issues/new/choose). The reason for this is we can focus on your specific configuration and problem since the root cause can be unrelated even though the error messages are similar. Thanks!
