### ISSUE TITLE
Messy in Python API Docs - state_ops.html#constant_initializer

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#4969] opened 2016-10-14 15:12 UTC
https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#constant_initializer

On Constant Initializer  -> Examples:

The very large gray box contains the html of other initializer docs. Hope it can be fixed.

**Comment by Haroenv** [comment] 2016-10-14 17:32
Error is because https://github.com/tensorflow/tensorflow/blob/d44d271c9da4d244ce4b2ffaf808adbe4cff759d/tensorflow/python/ops/init_ops.py#L142 isn't closing the code block I think.

**Comment by jart** [comment] 2016-10-15 00:32
This is a duplicate of #4849 which has been corrected at HEAD. The site will be updated shortly.

**Comment by gunan** [comment] 2016-12-21 09:37
This is fixed at master and r0.12
We will not merge the fix back to 0.11, therefore closing the issue.

**Closed by gunan** 2016-12-21 09:37 UTC
Labels: duplicate
