### ISSUE TITLE
Unable to import tensorrt on macOS

### ISSUE THREAD

**Issue by nehaljwani** [tensorflow/tensorflow#21818] opened 2018-08-23 03:25 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS, 10.13.6
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: N/A
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.0
- **Python version**: 2.7.15
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:  `python -c 'from tensorflow.contrib import tensorrt as trt'`

### Describe the problem
Unable to import tensorrt

### Source code / logs
```
(/private/tmp/scratch.nwani/1534993632/dev) ➜  1534993632 python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.contrib import tensorrt as trt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/scratch.nwani/1534993632/dev/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/__init__.py", line 25, in <module>
    from tensorflow.contrib.tensorrt.python import *
  File "/private/tmp/scratch.nwani/1534993632/dev/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.tensorrt.python.trt_convert import calib_graph_to_infer_graph
  File "/private/tmp/scratch.nwani/1534993632/dev/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/python/trt_convert.py", line 23, in <module>
    from tensorflow.contrib.tensorrt.wrap_conversion import calib_convert
  File "/private/tmp/scratch.nwani/1534993632/dev/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/wrap_conversion.py", line 28, in <module>
    _wrap_conversion = swig_import_helper()
  File "/private/tmp/scratch.nwani/1534993632/dev/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/wrap_conversion.py", line 24, in swig_import_helper
    _mod = imp.load_module('_wrap_conversion', fp, pathname, description)
ImportError: dynamic module does not define init function (init_wrap_conversion)
>>>
```

**Comment by nehaljwani** [comment] 2018-08-23 04:55
At the same time, this is succeeding:
```
python -c 'from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco'
```
So I thought to compare the symbols.
```
(/private/tmp/scratch.nwani/1534993632/dev) ➜  1534993632 nm .//dev/lib/python2.7/site-packages/tensorflow/contrib/lite/toco/python/_tensorflow_wrap_toco.so | grep tensorflow_wrap_toco
0000000000003230 T _init_tensorflow_wrap_toco
                 U init_tensorflow_wrap_toco
                 I init_tensorflow_wrap_toco (indirect for init_tensorflow_wrap_toco)

(/private/tmp/scratch.nwani/1534993632/dev) ➜  1534993632 nm /private/tmp/scratch.nwani/1534993632/dev/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/_wrap_conversion.so  | grep wrap_conversion
0000000000003670 t _init_wrap_conversion <---------- small 't' :(
                 U init_wrap_conversion
                 I init_wrap_conversion (indirect for init_wrap_conversion)
```
Then, I went on to build from source to see what is going on. Looking at the object files, I saw that both are capital 'T':
```
some-mac-box:~ nwani$ nm /private/var/tmp/_bazel_nwani/c8db850cfe278c8297aabaa8ebedf47a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/contrib/tensorrt/_objs/_wrap_conversion.so/tensorflow/contrib/tensorrt/wrap_conversion.pic.o  | grep init_
00000000000005d0 T _init_wrap_conversion
some-mac-box:~ nwani$ nm /private/var/tmp/_bazel_nwani/c8db850cfe278c8297aabaa8ebedf47a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/contrib/lite/toco/python/_objs/_tensorflow_wrap_toco.so/tensorflow/contrib/lite/toco/python/tensorflow_wrap_toco.pic.o | grep init_
0000000000000000 T _init_tensorflow_wrap_toco
```

But then in the genereated DSOs, I found that the trouble some one hides the init symbol :(
```
some-mac-box:~ nwani$ nm /private/var/tmp/_bazel_nwani/c8db850cfe278c8297aabaa8ebedf47a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/tools/pip_package/simple_console.runfiles/org_tensorflow/tensorflow/contrib/lite/toco/python/_tensorflow_wrap_toco.so | grep init_tensor
0000000000002150 T _init_tensorflow_wrap_toco
                 I init_tensorflow_wrap_toco (indirect for init_tensorflow_wrap_toco)
                 U init_tensorflow_wrap_toco
some-mac-box:~ nwani$ nm /private/var/tmp/_bazel_nwani/c8db850cfe278c8297aabaa8ebedf47a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/contrib/tensorrt/_wrap_conversion.so | grep init_wra
0000000000002e20 t _init_wrap_conversion
                 I init_wrap_conversion (indirect for init_wrap_conversion)
                 U init_wrap_conversion
```
Surprisingly, the versions scripts are identical:
```
some-mac-box:~ nwani$ diff /private/var/tmp/_bazel_nwani/c8db850cfe278c8297aabaa8ebedf47a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/contrib/lite/toco/python/tensorflow_wrap_toco_versionscript.lds /private/var/tmp/_bazel_nwani/c8db850cfe278c8297aabaa8ebedf47a/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/contrib/tensorrt/wrap_conversion_versionscript.lds
2c2
< init_tensorflow_wrap_toco
---
> init_wrap_conversion
```

**Comment by nehaljwani** [comment] 2018-08-23 16:26
Okay, I think I know what is happening. In the generated lds scripts, `_tensorflow_wrap_toco.so` exports the required symbol because of `*tensorflow*` and not because of `init_tensorflow_wrap_toco` because the actual symbol started with an underscore: `_init_tensorflow_wrap_toco` . None of the patterns listed in the lds scripts match for `_wrap_conversion.so` and hence the symbol `_init_wrap_conversion` remains non-exposed.

**Comment by aselle** [comment] 2018-08-23 18:07
Where is the linker script you are looking at? Is it part of the gen rule for the swig wrapper?

**Comment by nehaljwani** [comment] 2018-08-23 18:15
The scripts are:
```
/xxx/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/contrib/tensorrt/wrap_conversion_versionscript.lds
/xxx/execroot/org_tensorflow/bazel-out/darwin-opt/bin/tensorflow/python/pywrap_tensorflow_internal_versionscript.lds
```
Probably generated by: https://github.com/tensorflow/tensorflow/blob/4a00a658050e105fca6304f4e73d15b383f472c7/tensorflow/tensorflow.bzl#L1388-L1427

**Comment by nehaljwani** [comment] 2018-08-23 21:15
FWIW, I applied the following patch and then rebuilt tensorflow and the problem went away.

```patch
diff --git a/tensorflow/tensorflow.bzl b/tensorflow/tensorflow.bzl
index 301b59a20d..41d9430dd0 100644
--- a/tensorflow/tensorflow.bzl
+++ b/tensorflow/tensorflow.bzl
@@ -1398,7 +1398,7 @@ def _append_init_to_versionscript_impl(ctx):
       template=ctx.file.template_file,
       output=ctx.outputs.versionscript,
       substitutions={
-        "global:":"global:\n     init_%s;\n     PyInit_*;"%(mod_name),
+        "global:":"global:\n     init_%s;\n     _init_%s;\n     PyInit_*;\n     _PyInit_*"%(mod_name, mod_name),
       },
       is_executable=False,
     )
@@ -1407,7 +1407,7 @@ def _append_init_to_versionscript_impl(ctx):
       template=ctx.file.template_file,
       output=ctx.outputs.versionscript,
       substitutions={
-        "*tensorflow*":"*tensorflow*\ninit_%s\nPyInit_*\n"%(mod_name),
+        "*tensorflow*":"*tensorflow*\ninit_%s\n_init_%s\nPyInit_*\n_PyInit_*\n"%(mod_name, mod_name),
       },
       is_executable=False,
     )
--
```

**Comment by tensorflowbutler** [comment] 2018-09-07 18:55
Nagging Assignee @miaout17: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tofulawrence** [comment] 2018-09-13 18:05
Great! I'm glad that this is resolved.

**Comment by nehaljwani** [comment] 2018-09-13 20:14
@tofulawrence  Wait, how is this resolved? I applied that patch locally. It is not part of tensorflow yet. The official build of tensorflow on PyPI still faces this issue.

**Comment by tofulawrence** [comment] 2018-09-13 20:56
Sorry, @nehaljwani. I misread the comment. I'll reopen.

**Comment by gunan** [comment] 2018-09-24 06:35
On macos, we have no official support for GPUs.
TensorRT is an nvidia library that accelerates inference on GPUs.

So I would say this is a strictly unsupported feature you are trying to use.
We will not be actively trying to patch this, or create a patch release for this. But it will be available when the patch ends up in the release.
Marking as community support.

**Comment by gadagashwini** [comment] 2022-05-31 07:18
Hi @nehaljwani, I could able to import tensorrt on Mac os.
Install TensorRT
`!python3 -m pip install --upgrade nvidia-tensorrt`
```
import tensorrt
print(tensorrt.__version__)
```
`>>>8.4.0.6`

Associated PR [#22792](https://github.com/tensorflow/tensorflow/pull/22792) also got merged. Could you move this to closed status, if the issue is resolved. Thank you!

**Closed** 2022-05-31 11:51 UTC
Labels: stat:awaiting response
