### ISSUE TITLE
tf.function fails with tf.ragged.boolean_mask

### ISSUE THREAD

**Issue by PistaSaki** [tensorflow/tensorflow#33012] opened 2019-10-03 10:17 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution: Windows 10
- TensorFlow version: v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: 3.7.4
- CUDA/cuDNN version: None
- GPU model and memory: NO GPU

**Describe the current behavior**
A function containing `tf.ragged.boolean_mask` and decorated with `tf.function` works on first execution but fails when executed with different inputs. Setting `experimental_relax_shapes=True` does not help.

**Code to reproduce the issue**
```python
import tensorflow as tf

## Define some RaggedTensors
print("`a2` and `b2` are ragged tensors with batch-length = 2")
a2 = tf.ragged.constant([[1, 2, 3], [4, 5]], dtype=tf.float32, 
                       ragged_rank=1, inner_shape=tuple())
print("a2 =", a2)

b2 = tf.ragged.constant([[1], [2, 3]], dtype=tf.float32, 
                       ragged_rank=1, inner_shape=tuple())
print("b2 =", b2)

print("`a3` and `b3` are ragged tensors with batch-length = 3")
a3 = tf.ragged.constant([[1, 2, 3], [4, 5], [3]], dtype=tf.float32, 
                       ragged_rank=1, inner_shape=tuple())
print("a3 =", a3)

b3 = tf.ragged.constant([[1], [2, 3], [5]], dtype=tf.float32, 
                       ragged_rank=1, inner_shape=tuple())
print("b3 =", b3)

## Define a function
print("We define a function `fun` with `tf.ragged.boolean_mask`.")
def fun(x):
    maximums = tf.reduce_max(x, axis=1)
    mask = maximums > 4
    selection = tf.ragged.boolean_mask(x, mask)
    return tf.reduce_sum(selection)

## Run the function in eager-mode
print("Running in eager-mode.")
print("fun(a2) =", fun(a2))
print("fun(a3) =", fun(a3))
print("fun(b2) =", fun(b2))
print("fun(b3) =", fun(b3))

## Now running the same in graph-mode
fun = tf.function(fun, experimental_relax_shapes=True)

print("Running in graph-mode.")
print("fun(a2) =", fun(a2))
print("fun(a3) =", fun(a3))
print("fun(b2) =", fun(b2))
print("fun(b3) =", fun(b3))
```
**Output of the code**
```
`a2` and `b2` are ragged tensors with batch-length = 2
2019-10-04 10:19:32.835325: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
a2 = <tf.RaggedTensor [[1.0, 2.0, 3.0], [4.0, 5.0]]>
b2 = <tf.RaggedTensor [[1.0], [2.0, 3.0]]>
`a3` and `b3` are ragged tensors with batch-length = 3
a3 = <tf.RaggedTensor [[1.0, 2.0, 3.0], [4.0, 5.0], [3.0]]>
b3 = <tf.RaggedTensor [[1.0], [2.0, 3.0], [5.0]]>
We define a function `fun` with `tf.ragged.boolean_mask`.
Running in eager-mode.
fun(a2) = tf.Tensor(9.0, shape=(), dtype=float32)
fun(a3) = tf.Tensor(9.0, shape=(), dtype=float32)
fun(b2) = tf.Tensor(0.0, shape=(), dtype=float32)
fun(b3) = tf.Tensor(5.0, shape=(), dtype=float32)
Running in graph-mode.
fun(a2) = tf.Tensor(9.0, shape=(), dtype=float32)
fun(a3) = tf.Tensor(9.0, shape=(), dtype=float32)
2019-10-04 10:19:33.187674: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: Input to reshape is a tensor with 3 values, but the requested shape has 5
         [[{{node RaggedMask/RaggedMask/boolean_mask/Reshape}}]]
Traceback (most recent call last):
  File "Bug in tensorflow tf-function on ragged-boolean_mask.py", line 43, in <module>
    print("fun(b2) =", fun(b2))
  File "D:\python_projects\workon_hrab2\WPy64-3740\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "D:\python_projects\workon_hrab2\WPy64-3740\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 494, in _call
    results = self._stateful_fn(*args, **kwds)
  File "D:\python_projects\workon_hrab2\WPy64-3740\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\eager\function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "D:\python_projects\workon_hrab2\WPy64-3740\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\eager\function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "D:\python_projects\workon_hrab2\WPy64-3740\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "D:\python_projects\workon_hrab2\WPy64-3740\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)
  File "D:\python_projects\workon_hrab2\WPy64-3740\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Input to reshape is a tensor with 3 values, but the requested shape has 5
         [[node RaggedMask/RaggedMask/boolean_mask/Reshape (defined at D:\python_projects\workon_hrab2\WPy64-3740\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]] [Op:__inference_fun_1126]

Function call stack:
fun

```

**Comment by ravikyram** [comment] 2019-10-04 08:34
I have tried on colab with TF version 2.0.0-rc2, 2.0.0-dev20191002 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/2229ff515d40f06a322a1df614c564e7/untitled246.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-12-20 17:54
@PistaSaki Looks like this was resolved in `tf-nightly`. I was not able to reproduce the issue with `tf-nightly`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/129fd452f492f59d3789779155dbbc6d/untitled246.ipynb). Thanks!

I am closing this issue. Please feel free to reopen if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2019-12-20 17:54 UTC
Labels: TF 2.0, comp:autograph, comp:ops, type:bug
