### ISSUE TITLE
[DOC 1.x] save_keras_model requires eager mode

### ISSUE THREAD

**Issue by slapersonne** [tensorflow/tensorflow#27465] opened 2019-04-03 14:01 UTC
**System information**
- TensorFlow version: 1.13.1
- Doc Link: https://www.tensorflow.org/api_docs/python/tf/contrib/saved_model/save_keras_model?hl=en

**Describe the documentation issue**
I followed [this tutorial](https://www.tensorflow.org/tutorials/keras/save_and_restore_models) and this [API reference page](https://www.tensorflow.org/api_docs/python/tf/contrib/saved_model/save_keras_model?hl=en) to save a trained Keras model as a SavedModel, which in my use case is required to upload it to GCP ML Engine.
But I encounter a non documented `AssertionError` specifying I should use eager mode.
This seems related to [this commit](https://github.com/tensorflow/tensorflow/commit/6603c69fa71d6ebdee717863079ca34308c9ddb1).
Did I understand something wrong or should this compatibility requirements also be documented for `save_keras_model` (at least with `serving_only` set to `True`) ?

**Comment by muddham** [comment] 2019-04-04 13:30
@slapersonne In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by slapersonne** [comment] 2019-04-04 14:21
Sure, here is a simplified snippet : 

```python
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout

print(tf.__version__)


def train_model(
        training_features,
        prediction_features
):
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=([len(training_features)])))
    model.add(Dense(len(prediction_features), activation='sigmoid'))

    model.summary()

    tf.contrib.saved_model.save_keras_model(model, "./saved_models", serving_only=True)
```

And here is the output I get when running this snippet : 

```
Using TensorFlow backend.
1.13.1
WARNING:tensorflow:From /my_venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 64)                2304
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 130
=================================================================
Total params: 2,434
Trainable params: 2,434
Non-trainable params: 0
_________________________________________________________________

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/my_project/trainer/task.py", line 75, in <module>
    model = model.train_model(training_features, prediction_features)
  File "/my_project/trainer/model.py", line 18, in train_model
    tf.contrib.saved_model.save_keras_model(model, "./saved_models", serving_only=True)
  File "/my_venv/lib/python3.6/site-packages/tensorflow/contrib/saved_model/python/saved_model/keras_saved_model.py", line 136, in save_keras_model
    signatures=training_utils.trace_model_call(model, input_signature))
  File "/my_venv/lib/python3.6/site-packages/tensorflow/python/saved_model/save.py", line 711, in save
    "tf.saved_model.save is not supported when graph building. "
AssertionError: tf.saved_model.save is not supported when graph building. tf.enable_eager_execution() must run first when calling it from TensorFlow 1.x.
```

For information, please note that when I set `serving_only` to False, I get an other error : 
```
  File "/my_project/trainer/model.py", line 18, in train_model
    tf.contrib.saved_model.save_keras_model(model, "./saved_models", serving_only=False)
  File "/my_venv/lib/python3.6/site-packages/tensorflow/contrib/saved_model/python/saved_model/keras_saved_model.py", line 138, in save_keras_model
    _save_v1_format(model, export_dir, custom_objects, as_text, input_signature)
  File "/my_venv/lib/python3.6/site-packages/tensorflow/contrib/saved_model/python/saved_model/keras_saved_model.py", line 190, in _save_v1_format
    checkpoint_path = _export_model_variables(model, path)
  File "/my_venv/lib/python3.6/site-packages/tensorflow/contrib/saved_model/python/saved_model/keras_saved_model.py", line 162, in _export_model_variables
    model.save_weights(checkpoint_prefix, save_format='tf', overwrite=True)
TypeError: save_weights() got an unexpected keyword argument 'save_format'
```

**Comment by jvishnuvardhan** [comment] 2019-04-19 23:09
@slapersonne I ran it in Google colab with TF1.13.1 and TF-nightly without any error. Could you try running it in colab and then on upgrade TF on your system to TF1.13.1 and run again.
```
!pip install tensorflow==1.13.1
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

print(tf.__version__)


def train_model(
        training_features,
        prediction_features
):
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=([len(training_features)])))
    model.add(Dense(len(prediction_features), activation='sigmoid'))

    model.summary()

    tf.contrib.saved_model.save_keras_model(model, "./saved_models", serving_only=True)
```

You could also try with the tf-nightly by replacing !pip install tensorflow==1.13.1 with !pip install tf-nightly in the first line. 

Please let me know how it progresses. Thanks!

**Comment by slapersonne** [comment] 2019-04-23 09:32
Hello @jvishnuvardhan , thank you for your answer.
I tried it on Google colab, but I still encounter the above AssertionError when calling the `train_model` function : https://colab.research.google.com/drive/1yYCJF_nTwjikxF6Ym0G6xcjg7yDXk-Wc

**Comment by jvishnuvardhan** [comment] 2019-04-23 19:39
@slapersonne model is not complete with all the components. Please follow the tutorial and post any queries on Stackoverflow. 

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by slapersonne** [comment] 2019-04-24 07:59
@jvishnuvardhan yes, this is a simplified sample to expose the problem, not the one I am using.
I am not stuck with this as I found an other way to save my model (through a `SavedModelBuilder`).
But as mentioned in the issue title and description, I think this is a documentation issue because there is no mention of this `AssertionError`, or of any incompatibility when not in eager mode and `serving_only` is set to `True`.
In the above tutorial you linked, we get the `AssertionError` when adding `serving_only=True` : 

<img width="1064" alt="Screen Shot 2019-04-24 at 09 50 14" src="https://user-images.githubusercontent.com/11258206/56641935-add37000-6676-11e9-8f04-f65e9ce054e8.png">

If this an expected behavior which does not have to be documented, I am sorry for the inconvenience and I would be glad to close the issue.

**Comment by jvishnuvardhan** [comment] 2019-09-22 00:08
@slapersonne This is a stale issue. Is this still an issue? Could you please check and let us know. If this was resolved, please close the issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-10 22:26
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-10-10 22:26 UTC
Labels: comp:keras, stat:awaiting tensorflower, type:docs
