### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by alexshade15** [tensorflow/tensorflow#33204] opened 2019-10-10 11:17 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.0.0-beta1
- Python version: Python 3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA Version 10.1 
- GPU model and memory: GeForce GTX 1080 Ti

**Describe the current behavior**
I'm using GridSearchCV from sklearn
When I start the training process finishes with `TypeError: can't pickle _thread.RLock objects`

**Describe the expected behavior**
No error, working `grid.fit(train_X, train_Y)`

**Code to reproduce the issue**
```
import tensorflow
from tensorflow.compat.v2.keras.layers import *
from tensorflow.compat.v2.keras.models import Model
from tensorflow.compat.v2.keras.optimizers import *
from tensorflow.compat.v2.keras.preprocessing import image
from tensorflow.compat.v2.keras.wrappers.scikit_learn import KerasClassifier
import numpy as np
from sklearn.model_selection import GridSearchCV

def loadImages(path):
    data = []
    for img_name in os.listdir(path):
        img = image.load_img(path + img_name, target_size=(512, 512, 1))
        img = image.img_to_array(img)
        img = img / 255
        data.append(img)
    return np.array(data)

if __name__ == "__main__":
    batch_size = 4
    train_frame_path = '/data/segmentation/train_frames/'
    train_mask_path = '/data/segmentation/train_masks/'
[segmentation_training.txt]

    train_X = loadImages(train_frame_path)
    train_Y = loadImages(train_mask_path)

    m = unet()
    model = KerasClassifier(build_fn=m, epochs=25, batch_size=batch_size, verbose=0)

    optimizer = ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']
    param_grid = dict(optimizer=optimizer)
    grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3)
    grid_result = grid.fit(train_X, train_Y)
```

Here there is the full code [segmentation_training.txt](https://github.com/tensorflow/tensorflow/files/3712133/segmentation_training.txt)

**Other info / logs**
```


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vlongoba/singularity/testForRadio/jackzen.py", line 120, in gridSearch
    grid_result = grid.fit(train_X, train_Y)
  File "/home/vlongoba/singularity/.local/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 633, in fit
    base_estimator = clone(self.estimator)
  File "/home/vlongoba/singularity/.local/lib/python3.6/site-packages/sklearn/base.py", line 64, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/home/vlongoba/singularity/.local/lib/python3.6/site-packages/sklearn/base.py", line 55, in clone
    return copy.deepcopy(estimator)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

```

**Comment by Nephalen** [comment] 2019-10-10 18:01
Do you know what the model architecture is defined in unet()?

I'm not 100% sure about sklearn's gridsearch algorithm, but usually this kind of algorithm involves saving temporary best model to disk. However, tensorflow does't support saving Keras' Lambda Layer at the moment. So if unet() includes a Lambda layer, the error will be raised.

**Comment by gadagashwini** [comment] 2019-10-11 08:37
@alexshade15, Please provide the necessary supporting files to reproduce the reported issue.  Thanks!

**Comment by alexshade15** [comment] 2019-10-11 12:39
> Do you know what the model architecture is defined in unet()?
> 
> I'm not 100% sure about sklearn's gridsearch algorithm, but usually this kind of algorithm involves saving temporary best model to disk. However, tensorflow does't support saving Keras' Lambda Layer at the moment. So if unet() includes a Lambda layer, the error will be raised.

This is the unet() model, there are no Lambda Layers:
```
def unet(pretrained_weights=None, input_size=(512, 512, 1)):
    inputs = Input(input_size)
    conv1 = Conv2D(64, 3, activation='relu', padding='same', kernel_initializer='he_normal')(inputs)
    conv1 = Conv2D(64, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv1)
    pool1 = MaxPooling2D(pool_size=(2, 2))(conv1)
    conv2 = Conv2D(128, 3, activation='relu', padding='same', kernel_initializer='he_normal')(pool1)
    conv2 = Conv2D(128, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv2)
    pool2 = MaxPooling2D(pool_size=(2, 2))(conv2)
    conv3 = Conv2D(256, 3, activation='relu', padding='same', kernel_initializer='he_normal')(pool2)
    conv3 = Conv2D(256, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv3)
    pool3 = MaxPooling2D(pool_size=(2, 2))(conv3)
    conv4 = Conv2D(512, 3, activation='relu', padding='same', kernel_initializer='he_normal')(pool3)
    conv4 = Conv2D(512, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv4)
    drop4 = Dropout(0.5)(conv4)
    pool4 = MaxPooling2D(pool_size=(2, 2))(drop4)
    conv5 = Conv2D(1024, 3, activation='relu', padding='same', kernel_initializer='he_normal')(pool4)
    conv5 = Conv2D(1024, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv5)
    drop5 = Dropout(0.5)(conv5)
    up6 = Conv2D(512, 2, activation='relu', padding='same', kernel_initializer='he_normal' (UpSampling2D(size=(2, 2))(drop5))
    merge6 = concatenate([drop4, up6], axis=3)
    conv6 = Conv2D(512, 3, activation='relu', padding='same', kernel_initializer='he_normal')(merge6)
    conv6 = Conv2D(512, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv6)
    up7 = Conv2D(256, 2, activation='relu', padding='same', kernel_initializer='he_normal')(UpSampling2D(size=(2, 2))(conv6))
    merge7 = concatenate([conv3, up7], axis=3)
    conv7 = Conv2D(256, 3, activation='relu', padding='same', kernel_initializer='he_normal')(merge7)
    conv7 = Conv2D(256, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv7)
    up8 = Conv2D(128, 2, activation='relu', padding='same', kernel_initializer='he_normal')(UpSampling2D(size=(2, 2))(conv7))
    merge8 = concatenate([conv2, up8], axis=3)
    conv8 = Conv2D(128, 3, activation='relu', padding='same', kernel_initializer='he_normal')(merge8)
    conv8 = Conv2D(128, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv8)
    up9 = Conv2D(64, 2, activation='relu', padding='same', kernel_initializer='he_normal')(UpSampling2D(size=(2, 2))(conv8))
    merge9 = concatenate([conv1, up9], axis=3)
    conv9 = Conv2D(64, 3, activation='relu', padding='same', kernel_initializer='he_normal')(merge9)
    conv9 = Conv2D(64, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv9)
    conv9 = Conv2D(2, 3, activation='relu', padding='same', kernel_initializer='he_normal')(conv9)
    conv10 = Conv2D(1, 1, activation='sigmoid')(conv9)
    m = Model(inputs=inputs, outputs=conv10)
    m.compile(optimizer=SGD(lr=0.015), loss='binary_crossentropy', metrics=['accuracy'])
    return m
```

**Comment by alexshade15** [comment] 2019-10-11 12:43
> @alexshade15, Please provide the necessary supporting files to reproduce the reported issue. Thanks!

Here there is the dataset that I've used 
https://drive.google.com/file/d/1rGOUBJIvNp03x7qJP_PtsLNXtMLWYo6X/view?usp=sharing

**Comment by gadagashwini** [comment] 2019-10-14 10:30
@alexshade15, Thanks for the complete code. I could replicate the issue on Colab. Please see the [gist](https://colab.sandbox.google.com/gist/gadagashwini/0c02bf54f77e41d7833ec5c563e9447d/untitled196.ipynb). Looks like issue is more related to scikit learn gridsearch. Can you confirm. Thanks!

**Comment by alexshade15** [comment] 2019-10-14 12:24
Yes, the issue is the same and it seems to be related to scikit learn gridsearch. Thank you.

**Comment by gadagashwini** [comment] 2019-10-15 06:16
@alexshade15, Can you post this issue in relevant repo for better and faster resolution. We can close this issue. Thanks!

**Comment by tensorflowbutler** [comment] 2019-10-29 12:36
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gadagashwini** [comment] 2019-10-30 06:05
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-10-30 06:05 UTC
Labels: TF 2.0, comp:keras, stat:awaiting response, type:support

**Comment by iegorval** [comment] 2020-01-12 14:14
I am having the same issue with
```
def build_model():
    model = keras.Sequential([
        layers.Dense(24, activation='relu', input_shape=[len(features)]),
        layers.Dense(12, activation='relu'),
        layers.Dense(1)
    ])
    optimizer = tf.keras.optimizers.RMSprop(0.001)
    model.compile(loss='mse',
                    optimizer=optimizer,
                    metrics=['mae', 'mse'])
    return model

model = KerasRegressor(build_model())

pipeline = Pipeline(steps=[ ('nn', model)])

gs = GridSearchCV(estimator=pipeline, param_grid=params,
                  n_jobs=1, return_train_score=True, scoring='r2');
```

**Comment by gadagashwini** [comment] 2020-01-13 06:09
@iegorval, Can you open new issue and provide the information asked in template. Thanks!

**Comment by dmsfabiano** [comment] 2020-05-08 23:35
It's crazy this is still an issue, still cannot perform any kind of gridsearchcv on AWS ubuntu.

Not even with n_jobs=1

**Comment by badjano** [comment] 2020-08-27 02:28
I can´t believe there is no fix for this anywhere... I´m almost doing my own implementation of grid search... I can´t believe how much time I already wasted trying to fix it

**Comment by badjano** [comment] 2020-08-27 03:03
I just figured it out, the build_fn can´t be a method from an instance, but I don´t know why, probably a pickle serialization issue

**Comment by shakewingo** [comment] 2020-09-15 15:42
> I just figured it out, the build_fn can´t be a method from an instance, but I don´t know why, probably a pickle serialization issue

I am having the same issue. Can you please elaborate how you fix it?

**Comment by badjano** [comment] 2020-09-15 22:59
The method that creates the model that I was passing to the gridsearch was inside a class, it cannot be ( apparently ) so I made a method outside the class and it worked... But I have no idea why this happened, I just figured I should try a method outside of a class and it worked 🤷

**Comment by chafikblm** [comment] 2020-09-16 13:51
@badjano 
I am having the same issue. Can you please elaborate on how you fix it?
on this collab notebook :
https://colab.research.google.com/gist/gadagashwini/0c02bf54f77e41d7833ec5c563e9447d/untitled196.ipynb

**Comment by shakewingo** [comment] 2020-09-16 13:54
> @badjano
> I am having the same issue. Can you please elaborate on how you fix it?
> on this collab notebook :
> https://colab.research.google.com/gist/gadagashwini/0c02bf54f77e41d7833ec5c563e9447d/untitled196.ipynb

Thank you!! I got that work too!

**Comment by chafikblm** [comment] 2020-09-16 13:59
@shakewingo  thank you so much.

**Comment by wangxiaoshuai223** [comment] 2020-09-17 08:34
I had the same question，maybe you can try to You can try to replace 
model = KerasClassifier(build_fn=m, epochs=25, batch_size=batch_size, verbose=0)
with
model = KerasClassifier(build_fn=unet, epochs=25, batch_size=batch_size, verbose=0)，
this work for me

**Comment by chafikblm** [comment] 2020-09-17 15:18
@wangxiaoshuai223  thanks so much  you are right

**Comment by asokraju** [comment] 2021-02-04 06:51
I encountered the same error while using `from multiprocessing.dummy import Pool as ThreadPool`

This can be reproduced using:
import tensorflow as tf
from tensorflow import keras
import numpy as np


from multiprocessing import Pool
from multiprocessing.dummy import Pool as ThreadPool
from functools import partial

def simple_model():
    model = keras.models.Sequential([
        keras.layers.Dense(units = 10, input_shape = [1]),
        keras.layers.Dense(units = 1, activation = 'sigmoid')
    ])
    model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
    return model

def clone_model(model):
    model_clone = tf.keras.models.clone_model(model)
    model_clone.set_weights(model.get_weights())
    return model_clone

def work(model, seq):
    return model.predict(seq)

def worker(model, n = 4):
    seqences = np.arange(0,100).reshape(n, -1)
    pool = Pool()
    # model_list = [clone_model(model) for _ in range(n)]
    # results = pool.map(work, zip(model_list,seqences))
    partial_work = partial(work, model=model)
    results = pool.map(partial_work, seqences)
    pool.close()
    pool.join()
    
    return np.reshape(results, (-1, ))



if __name__ == '__main__':
    model = simple_model()
    out = worker(model, n=4)
    print(out)
