### ISSUE TITLE
InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by {{node cu_dnnlstm/CudnnRNN}}with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", is_training=true, seed2=0]

### ISSUE THREAD

**Issue by connect2robiul** [tensorflow/tensorflow#26600] opened 2019-03-12 08:13 UTC
I am user macintosh  

code 

```
`import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM #, CuDNNLSTM


mnist = tf.keras.datasets.mnist  # mnist is a dataset of 28x28 images of handwritten digits and their labels
(x_train, y_train),(x_test, y_test) = mnist.load_data()  # unpacks images to x_train/x_test and labels to y_train/y_test

x_train = x_train/255.0
x_test = x_test/255.0

print(x_train.shape)
print(x_train[0].shape)

model = Sequential()


model.add(LSTM(128, input_shape=(x_train.shape[1:]), activation='relu', return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(128, activation='relu'))
model.add(Dropout(0.1))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(10, activation='softmax'))

opt = tf.keras.optimizers.Adam(lr=0.001, decay=1e-6)

# Compile model
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=opt,
    metrics=['accuracy'],
)

model.fit(x_train,
          y_train,
          epochs=3,
          validation_data=(x_test, y_test))`
```

output 

```
`(60000, 28, 28)
(28, 28)
Train on 60000 samples, validate on 10000 samples
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1316       # Ensure any changes to the graph are reflected in the runtime.
-> 1317       self._extend_graph()
   1318       return self._call_tf_sessionrun(

/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _extend_graph(self)
   1351     with self._graph._session_run_lock():  # pylint: disable=protected-access
-> 1352       tf_session.ExtendSession(self._session)
   1353 

InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by {{node cu_dnnlstm/CudnnRNN}}with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", is_training=true, seed2=0]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

	 [[{{node cu_dnnlstm/CudnnRNN}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-7-d1c9ab123f67> in <module>
     41           y_train,
     42           epochs=3,
---> 43           validation_data=(x_test, y_test))

/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, max_queue_size, workers, use_multiprocessing, **kwargs)
    878           initial_epoch=initial_epoch,
    879           steps_per_epoch=steps_per_epoch,
--> 880           validation_steps=validation_steps)
    881 
    882   def evaluate(self,

/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, mode, validation_in_fit, **kwargs)
    249     # Setup work for each epoch
    250     epoch_logs = {}
--> 251     model.reset_metrics()
    252     callbacks.on_epoch_begin(epoch, epoch_logs, mode=mode)
    253     progbar.on_epoch_begin(epoch, epoch_logs)

/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in reset_metrics(self)
   1117     if hasattr(self, 'metrics'):
   1118       for m in self.metrics:
-> 1119         m.reset_states()
   1120       if self._distribution_strategy:
   1121         training_distributed._reset_metrics(self)  # pylint: disable=protected-access

/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py in reset_states(self)
    458     """
    459     for v in self.variables:
--> 460       K.set_value(v, 0)
    461 
    462   @abc.abstractmethod

/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py in set_value(x, value)
   2845         x._assign_placeholder = assign_placeholder
   2846         x._assign_op = assign_op
-> 2847       get_session().run(assign_op, feed_dict={assign_placeholder: value})
   2848 
   2849 

/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py in get_session()
    480   if not _MANUAL_VAR_INIT:
    481     with session.graph.as_default():
--> 482       _initialize_variables(session)
    483   return session
    484 

/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py in _initialize_variables(session)
    756     # marked as initialized.
    757     is_initialized = session.run(
--> 758         [variables_module.is_variable_initialized(v) for v in candidate_vars])
    759     uninitialized_vars = []
    760     for flag, v in zip(is_initialized, candidate_vars):

/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

/anaconda3/lib/python3.7/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' used by node cu_dnnlstm/CudnnRNN (defined at <ipython-input-6-3c5692df850b>:19) with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", is_training=true, seed2=0]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

	 [[node cu_dnnlstm/CudnnRNN (defined at <ipython-input-6-3c5692df850b>:19) ]]

Caused by op 'cu_dnnlstm/CudnnRNN', defined at:
  File "/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/anaconda3/lib/python3.7/asyncio/base_events.py", line 528, in run_forever
    self._run_once()
  File "/anaconda3/lib/python3.7/asyncio/base_events.py", line 1764, in _run_once
    handle._run()
  File "/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/anaconda3/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-3c5692df850b>", line 19, in <module>
    model.add(CuDNNLSTM(128, input_shape=(x_train.shape[1:]), return_sequences=True))
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 164, in add
    layer(x)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py", line 701, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/cudnn_recurrent.py", line 111, in call
    output, states = self._process_batch(inputs, initial_state)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/cudnn_recurrent.py", line 501, in _process_batch
    is_training=True)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 142, in cudnn_rnn
    seed2=seed2, is_training=is_training, name=name)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNN' used by node cu_dnnlstm/CudnnRNN (defined at <ipython-input-6-3c5692df850b>:19) with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", is_training=true, seed2=0]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

	 [[node cu_dnnlstm/CudnnRNN (defined at <ipython-input-6-3c5692df850b>:19) ]]`
```

**Comment by qlzh727** [comment] 2019-03-12 18:48
What version of Tensorflow are u currently using? Also do u have gpu on your local machine?

**Comment by ritdubal3011** [comment] 2019-03-13 09:18
Hi,
I'm also facing the same issue.
I'm using tensorflow-gpu==1.12.0 with cuda-9.0 and cudnn=7.0.5. GPU Tesla C2075.

**Comment by connect2robiul** [comment] 2019-03-13 09:25
I am using MacBook pro early Early 2015. Tensorflow version is 1.13.1 @qlzh727

**Comment by ritdubal3011** [comment] 2019-03-13 09:27
Hi,
I'm also facing same issue.
I'm using,
ubuntu 16.04
tensorflow==1.12.0
cuda-9.0
cudnn=7.0.5
GPU Tesla C2075
 
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU,XLA_CPU,XLA_GPU], Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]

	 [[node bidirectional_1/CudnnRNN (defined at /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py:922)  = CudnnRNN[T=DT_FLOAT, direction="unidirectional", dropout=0, input_mode="linear_input", is_training=true, rnn_mode="lstm", seed=87654321, seed2=0](bidirectional_1/transpose, bidirectional_1/ExpandDims_1, bidirectional_1/ExpandDims_2, bidirectional_1/concat)]]

**Comment by qlzh727** [comment] 2019-03-13 17:04
This seems to be quite weird, since the code snippet does not specify cudnn kernel at all. Btw, do u have tensorflow-alpha release installed? Can u run "pip list" and show all installed tf package/version here?

**Comment by kalisgd** [comment] 2019-04-01 11:33
Hi,
I faced the same error after GPU swap between servers. The problem was that Tensorflow was compiled with higher compute capability then the GPUs that were put in.

**Comment by qlzh727** [comment] 2019-04-02 14:21
I still having trouble to reproduce this issue with the code above. The cudnnLSTM import was commented out above and the model shouldn't use any cudnn kernel.

For anyone who experience the same issue, can u post the code snippet to reproduce the issue? Please also include the TF version you installed.

**Comment by Nick-Lucas** [comment] 2019-04-03 14:33
I'm getting the same problem as @ritdubal3011 

* Ubuntu 18.04, nvidia drivers installed using instructions [here](https://www.tensorflow.org/install/gpu)
* NVIDIA GTX 1080

Python modules:

```
# Installed in anaconda

tensorboard               1.12.2           py36he6710b0_0  
tensorflow                1.12.0          gpu_py36he74679b_0  
tensorflow-base           1.12.0          gpu_py36had579c0_0  
tensorflow-gpu            1.12.0               h0d30ee6_0  

# These also seem relevant modules
cudatoolkit               9.2                           0  
cudnn                     7.3.1                 cuda9.2_0  
```

I've got a pretty self-contained reproduction here, thought I certainly imagine it's either user error or a drivers issue, as I'm currently learning TF and have it set up for the first time.

```python
# %%

import tensorflow as tf
import numpy as np

data = list(map(lambda n: n / 10000, range(0, 10000+1)))

# %%

sequences = list(zip(data, data[1:], data[2:], data[3:], data[4:], data[5:]))
train_x = np.array(list(map(
    lambda seq: seq[:-1], sequences))).reshape(len(sequences), len(sequences[0])-1, 1)
train_y = np.array(
    list(map(lambda seq: seq[-1], sequences)))

model = tf.keras.Sequential([
    tf.keras.layers.CuDNNLSTM(
        3,
        return_sequences=False),
    tf.keras.layers.Dense(1)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.1, decay=0.003), 
    loss=tf.keras.losses.mse)

# %%

model.fit(train_x, train_y, epochs=100, validation_split=0, shuffle=False)
```

```
InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNN' with these attrs.  Registered devices: [CPU,XLA_CPU,XLA_GPU], Registered kernels:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
```

**Comment by Nick-Lucas** [comment] 2019-04-03 19:00
Running the following seems to confirm what I'm suspecting.

My GPU doesn't seem to be getting picked up despite having gone through all the instructions perfectly before, and verifying it was working using the test code [here](https://www.tensorflow.org/guide/using_gpu)

* sigh *... Linux...

```
tf.test.is_gpu_available(
    cuda_only=False,
    min_cuda_compute_capability=None
)
```

**Comment by qlzh727** [comment] 2019-04-04 21:56
@Nick-Lucas, does the tf.test.is_gpu_available return False? If that's the case, then it definitely means the GPU is not configured correctly. 

Also, the error message somehow indicating that the GPU device is not there:

Registered devices: [CPU,XLA_CPU,XLA_GPU]

XLA_GPU is not same as GPU.

**Comment by qlzh727** [comment] 2019-04-04 21:59
Adding @gunan who is the expert of build/packaging. When user installed both tf and tf-gpu, which kernel will the runtime pickup?

**Comment by Nick-Lucas** [comment] 2019-04-04 22:31
> XLA_GPU is not same as GPU.

This is useful to know for next time.

So in my case I ended up rebooting the machine and it suddenly started working fine. I imagine the drivers got into a bad state but it wasn't being reported. Sorry I meant to update the thread but forgot.

Something which was interesting and might help others above though. When running in a jupyter instance the error would hang around until I restarted the kernel manually. ie. I run with CudNNLSTM and get the error, then change it out to a CPU LSTM layer, and continue to get exactly the same error. Basically the code above where the CuDNN variant is commented out may have still been erroring if @connect2robiul was running in a jupyter instance.

**Comment by qlzh727** [comment] 2019-04-11 18:19
Thanks for the information, closing this issue now.

**Closed by qlzh727** 2019-04-11 18:19 UTC
Labels: stat:awaiting response

**Comment by sunnysinghnitb** [comment] 2019-05-07 21:06
I had the same issue. On shifting to "GPU" option, the error disappeared and the code started working. In the "Runtime" menu, change "Change Runtime Types" to "GPU".

**Comment by thirdlastletter** [comment] 2019-05-24 08:35
> I had the same issue. On shifting to "GPU" option, the error disappeared and the code started working. In the "Runtime" menu, change "Change Runtime Types" to "GPU".

How do I change to GPU? Where do I find a runtime menu?

**Comment by bestpredicts** [comment] 2019-05-28 06:52
I have same error  when  I train and save a model in  local machine, but when I load my model in  server,it get this error

**Comment by msaitkulov** [comment] 2019-07-19 15:55
Had same problem, 
Installing tensorflow-gpu compatible with CUDA solved the problem..
Try to search "cuda tensorflow gpu compatibility"

**Comment by alphamuth** [comment] 2019-10-07 10:46
I solved this issue by choosing GPU on colab through change runtime and it will through same error if you will not have gpu in your local system.

**Comment by talhaanwarch** [comment] 2020-01-08 08:03
> I solved this issue by choosing GPU on colab through change runtime and it will through same error if you will not have gpu in your local system.

same, i forget to switch to gpu in colab

**Comment by AI-Man-gr** [comment] 2020-01-13 09:39
I had the same problem even with a TPU execution on colab. It's solved only by switching to a GPU execution

**Comment by michaelarfreed** [comment] 2020-02-20 19:54
I am getting a very similar error, but it is in a very specific set of circumstances.

I have 2 models, let's call them model_A and model_B. model_A was trained on a CPU machine and has no GPU layers, only LSTM/Dense layers. model_B was trained on a GPU machine and has CuDNNGRU layers. I can almost always load model_A on a machine with no GPU, and I cannot load model_B on a machine with no GPU (as expected). The weird behavior is this: I spin up a new terminal on a machine with no GPUs. I load model_A on my machine, with no issues (as expected). I try to load model_B on my machine, and I get this error (as expected). I try to re-load model_A on my machine, and I get this error (not expected, model_A has no GPU dependent layers). I have to restart my terminal window to be able to load model_A. I can repeat this behavior when substituting any non-GPU model for model_A, and when substituting any GPU model for model_B. 

The  error is slightly different, it is CudnnRNNV2 instead of CudnnRNN: `InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNV2' used by node cu_dnngru_2/CudnnRNNV2 (defined at /my/conda/env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [input_mode="linear_input", T=DT_FLOAT, direction="unidirectional", rnn_mode="gru", is_training=true, seed2=0, seed=0, dropout=0]`.

**Comment by etatbak** [comment] 2020-05-10 12:48
I had the same issue, installing correct version of cuda- cudnn solved my problem.

**Comment by Malithi-gif** [comment] 2020-12-09 06:52
Registered devices: [CPU]
Registered kernels:
  <no registered kernels>

         [[cu_dnnlstm_1/CudnnRNN]]

Errors may have originated from an input operation.
Input Source operations connected to node cu_dnnlstm_1/CudnnRNN:
 cu_dnnlstm_1/transpose (defined at C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\layers\cudnn_recurrent.py:484)
 cu_dnnlstm_1/ExpandDims_2 (defined at C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\layers\cudnn_recurrent.py:488)
 cu_dnnlstm_1/ExpandDims_1 (defined at C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\layers\cudnn_recurrent.py:487)
 cu_dnnlstm_1/concat_1 (defined at C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\layers\cudnn_recurrent.py:60)

Can anyone help me?

**Comment by xuwei1111** [comment] 2022-03-23 02:06
I uninstall tensorflow-cpu==1.15.2 and tensorflow-gpu==1.15.2 completely, and then reinstall tensorflow-gpu==1.15.2 only. It works!

**Comment by Zaibali9999** [comment] 2022-07-25 09:58
For CPU
bilstm_1 = Bidirectional(LSTM(int(self.dnn_size/2), activation='tanh', return_sequences=True), merge_mode='concat')(sharable_embedding) # The default activation is 'tanh',

For GPU
bilstm_1 = Bidirectional(CuDNNLSTM(self.rnn_size, return_sequences=True))(sharable_embedding)

**Comment by HasterZ** [comment] 2022-12-03 11:11
I'm Newbi so may be my solution is wrong, but i have same error "No OpKernel was registered to support Op 'CudnnRNNV2' used by {{node sequential/bidirectional/forward_cu_dnnlstm/CudnnRNNV2}}with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", is_training=true, seed2=0]
Registered devices: [CPU]" or something like that.
I solve problem by using this instruction
https://www.tensorflow.org/install/pip?hl=en&%3Bauthuser=7&authuser=7#windows-native_1

**Comment by cmjj0011** [comment] 2024-04-16 11:46
Hi,
I'm also facing same issue.
I'm using,
windows10
tensorflow==1.14.0
cuda-10.0
cudnn=7.4.2
GPU==NVIDIA GeForce RTX 4060 Ti
