### ISSUE TITLE
Different scatter_nd behaviours with int and float

### ISSUE THREAD

**Issue by worm004** [tensorflow/tensorflow#18198] opened 2018-04-03 09:40 UTC
I am using tensorflow 1.4.1.
scatter_nd seems not check the index validation with float, because following codes generate no error. 

```
a = tf.scatter_nd( [[0,99,0,0]], [[1.0 for i in range(16)]], [100, 8, 100, 100, 16])
with tf.Session() as sess:
    print(sess.run(a))
```
If the 1.0 is changed to 1, the codes generate errors:

```
a = tf.scatter_nd( [[0,99,0,0]], [[1 for i in range(16)]], [100, 8, 100, 100, 16])
with tf.Session() as sess:
    print(sess.run(a))
```
Is this designed for some purpose or a bug?

**Comment by tensorflowbutler** [comment] 2018-04-04 00:37
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by worm004** [comment] 2018-04-04 09:01
I am glad to update the question with your suggestion : )

OS Platform and Distribution: 
I am using ubuntu 16.04 with the kernel 4.13.0-37-generic

TensorFlow installed from:
tensorflow is installed from pip with the script.
`pip3 install tensorflow-gpu==1.4.1`

TensorFlow version
I double checked it with the following script.
` python3 -c 'import tensorflow; print (tensorflow.__version__)'`

Exact command to reproduce
Try following two code snippets.
```
a = tf.scatter_nd( [[0,99,0,0]], [[1 for i in range(16)]], [100, 8, 100, 100, 16])
with tf.Session() as sess:
    print(sess.run(a))
```

```
a = tf.scatter_nd( [[0,99,0,0]], [[1.0 for i in range(16)]], [100, 8, 100, 100, 16])
with tf.Session() as sess:
    print(sess.run(a))
```

**Comment by facaiy** [comment] 2018-04-07 03:30
@worm004 Could you test it on the latest version 1.7?

**Comment by michaelisard** [comment] 2018-04-24 23:30
Were you able to test it on a recent version of TF?

**Comment by worm004** [comment] 2018-04-26 10:51
@michaelisard @facaiy Sorry for replying late, I was so busy these days : ( Currently I am not able to test it on 1.7.

**Comment by tensorflowbutler** [comment] 2018-05-11 18:45
Nagging Assignee @michaelisard: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by michaelisard** [comment] 2018-05-17 21:53
Closing for now, but please reopen if the problem is still present on a recent version.

**Closed by michaelisard** 2018-05-17 21:53 UTC
