### ISSUE TITLE
LoggingTensorHook used with TPUEstimator cause 'marked as not fetchable' exception.

### ISSUE THREAD

**Issue by wysohn** [tensorflow/tensorflow#29678] opened 2019-06-12 07:23 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
N/A
- TensorFlow installed from (source or binary):
N/A (GCP)
- TensorFlow version (use command below):
b'v1.13.0-rc0-0-g6ce86799c8' 1.13.0-rc0
- Python version:
Python 3.5.3
- Bazel version (if compiling from source):
N/A
- GCC/Compiler version (if compiling from source):
N/A
- CUDA/cuDNN version:
N/A
- GPU model and memory:
N/A

**Describe the current behavior**
With use_tpu set to True, and LoggingTensorHook is used by uncommenting the commented part (see the code below), training on GCP with TPU fails with 'marked as not fetchable' exception.

**Describe the expected behavior**
The behavior goes away and works without problem if I comment out the LoggingTensorHook parts, yet I have no idea what's the relevant issue.

The training fails with a very vague exception, which only says that the last op(tf.reduce_mean() in my case) has been marked as not fetchable, and no other useful information provided.

It makes it almost impossible to find the actual cause of the problem since the exception points to the wrong op, the reduce_mean(), which was actually not the problem.

**Code to reproduce the issue**
Uncommenting the commented parts reproduce the problem.

This is just a sample. With any model with the LoggingTensorHook provided as the hooks parameter, it throws an exception when trained with TPUs.
```
    def model_fn(features, labels, mode, params):
        del params

        char_embedding = CharacterAwareEmbedding(
            word_length=word_length,
            embedding_size=FLAGS.embedding_size,
            conv_size=FLAGS.conv_size,
            output_unit=FLAGS.output_unit,
        )

        target = features["input_target"]
        target = char_embedding(target)

        if mode == tf.estimator.ModeKeys.PREDICT:
            predictions = {
                'vectorized': target,
                'word': features["word"]
            }
            return tf.contrib.tpu.TPUEstimatorSpec(
                mode=mode,
                predictions=predictions)

        context = features["input_context"]
        context = char_embedding(context)

        cossim = cossim_similarity(target, context)

        loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=tf.cast(labels, tf.float32), logits=cossim))
        optimizer = tf.train.RMSPropOptimizer(learning_rate=0.001)

        # hook = tf.train.LoggingTensorHook({"loss": loss}, every_n_iter=100)

        if mode == tf.estimator.ModeKeys.TRAIN:
            if FLAGS.use_tpu:
                optimizer = tf.contrib.tpu.CrossShardOptimizer(optimizer)

            return tf.contrib.tpu.TPUEstimatorSpec(
                mode=mode,
                loss=loss,
                #training_hooks=[hook],
                train_op=optimizer.minimize(loss, tf.train.get_global_step()))

        if mode == tf.estimator.ModeKeys.EVAL:
            return tf.contrib.tpu.TPUEstimatorSpec(
                mode=mode,
                loss=loss,
                #training_hooks=[hook],
                eval_metrics=(metric_fn, [labels, cossim]))
```
**Other info / logs**

**Comment by ravikyram** [comment] 2019-06-20 07:21
Looks like the code is incomplete.Can you please provide full code snippet to reproduce it on our environment.Thanks

**Comment by RuibinMa** [comment] 2019-06-22 01:02
Same problem.

**Comment by ravikyram** [comment] 2019-06-28 06:34
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-06-28 06:34 UTC
Labels: TF 1.13, comp:tpus, stat:awaiting response, type:support
