### ISSUE TITLE
build error: undefined reference to `clock_gettime'

### ISSUE THREAD

**Issue by tonybaigang** [tensorflow/tensorflow#15129] opened 2017-12-05 14:19 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux CentOS 6.9
- **TensorFlow installed from (source or binary)**:
source 
- **TensorFlow version (use command below)**:
master branch: the latest version
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.8.0
- **GCC/Compiler version (if compiling from source)**:
4.8.2
- **CUDA/cuDNN version**:
No
- **GPU model and memory**:
No
- **Exact command to reproduce**:
bazel build --linkopt=-lrt -c opt --verbose_failures //tensorflow:libtensorflow_cc.so

### Describe the problem
I tried to build the tensor flow c++ lib from the source code, but it failed. 

### Source code / logs
ERROR: /home/baigang/Projects/xylib/thirdparty/tenserflow/package/tensorflow/tensorflow/cc/BUILD:422:1: Linking of rule '//tensorflow/cc:ops/random_ops_gen_cc' failed (Exit 1): gcc failed: error executing command 
  (cd /home/baigang/.cache/bazel/_bazel_baigang/d3e5550086b82aa173767408d0f485e7/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/baigang/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -o bazel-out/host/bin/tensorflow/cc/ops/random_ops_gen_cc '-Wl,-rpath,$ORIGIN/../../../_solib_k8/_U_S_Stensorflow_Scc_Cops_Srandom_Uops_Ugen_Ucc___Utensorflow' -Lbazel-out/host/bin/_solib_k8/_U_S_Stensorflow_Scc_Cops_Srandom_Uops_Ugen_Ucc___Utensorflow '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..,-rpath,$ORIGIN/../..' -pthread -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/tensorflow/cc/ops/random_ops_gen_cc-2.params)
bazel-out/host/bin/_solib_k8/_U_S_Stensorflow_Scc_Cops_Srandom_Uops_Ugen_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
Target //tensorflow:libtensorflow_cc.so failed to build
INFO: Elapsed time: 418.738s, Critical Path: 35.11s
FAILED: Build did NOT complete successfully

**Comment by reedwm** [comment] 2017-12-05 18:58
/CC @gunan, do you know what could be causing this issue?

**Comment by gunan** [comment] 2017-12-05 19:15
Looks like this is an issue caused by centos 6.9
A quick google search found these similar issues, and potential solution here:
https://stackoverflow.com/questions/17150075/undefined-reference-to-clock-gettime-although-lrt-is-given

Closing, as this issue is definitely caused by OS version of the user.

**Closed by gunan** 2017-12-05 19:15 UTC
Labels: stat:awaiting tensorflower

**Comment by tonybaigang** [comment] 2017-12-06 02:55
It's not the same issue as the one in stackoverflow.com. 
Actually, you will find tensorflow already defined " -pthread -Wl,-no-as-needed" in the build script. I think this issue is caused by tensorflow did not add -lrt in the build script.

**Comment by gunan** [comment] 2017-12-06 05:50
You did add `-lrt` in your build command, so it may be an issue when bazel needs to propagate this flag properly. 
@damienmg may want to take a look, but centos is not an OS we officially support, or we test/experiment on.

**Comment by rezwan16** [comment] 2017-12-08 04:55
I am also facing same issue here when I try to build Tensorflow for CPU from source.   
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Red Hat Enterprise Linux Server release 6.9 (Santiago)
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: master branch the latest version
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**: 0.5.4
- **GCC/Compiler version (if compiling from source)**: 4.9.2
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: 
bazel build --config=opt --verbose_failures --linkopt=-lrt //tensorflow/tools/pip_package:build_pip_package
### Source code / logs
```
ERROR: /home/user/tensorflow/tensorflow/contrib/cloud/BUILD:36:1: Linking of rule '//tensorflow/contrib/cloud:gen_gen_bigquery_reader_ops_py_wrappers_cc' failed (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_user/88f96db14f5044a661b2d9ab97596b51/execroot/org_tensorflow && \
  exec env - \
    PATH=/opt/jdk1.8.0_144/bin:/home/aniruddh/bazel-0.5.4-dist/output/:/usr/local/MATLAB/R2016a/bin:/usr/local/bin:/usr/local/netscape:/usr/sbin:/usr/bin:/usr/lib:/bin:/sbin:/etc:/opt/lumerical/fdtd/bin:/lib:.:/root/bin \
    PWD=/proc/self/cwd \
  /usr/bin/gcc -o bazel-out/host/bin/tensorflow/contrib/cloud/gen_gen_bigquery_reader_ops_py_wrappers_cc '-Wl,-rpath,$ORIGIN/../../../_solib_k8/_U_S_Stensorflow_Scontrib_Scloud_Cgen_Ugen_Ubigquery_Ureader_Uops_Upy_Uwrappers_Ucc___Utensorflow' -Lbazel-out/host/bin/_solib_k8/_U_S_Stensorflow_Scontrib_Scloud_Cgen_Ugen_Ubigquery_Ureader_Uops_Upy_Uwrappers_Ucc___Utensorflow '-Wl,-rpath,$ORIGIN/,-rpath,$ORIGIN/..,-rpath,$ORIGIN/../..' -pthread -Wl,-no-as-needed -Wl,-z,relro,-z,now -B/usr/bin -B/usr/bin -pass-exit-codes -Wl,--gc-sections -Wl,-S -Wl,@bazel-out/host/bin/tensorflow/contrib/cloud/gen_gen_bigquery_reader_ops_py_wrappers_cc-2.params).
bazel-out/host/bin/_solib_k8/_U_S_Stensorflow_Scontrib_Scloud_Cgen_Ugen_Ubigquery_Ureader_Uops_Upy_Uwrappers_Ucc___Utensorflow/libtensorflow_framework.so: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 110.105s, Critical Path: 44.90s
```

**Comment by AleksTk** [comment] 2017-12-08 14:05
Exactly same issue on Red Hat Enterprise Linux release 6.3 (Carbon). Looks like linker option '--linkopt=-lrt' does not propagate to gcc.

**Comment by zwergon** [comment] 2018-01-23 12:52
I had the same issue. To compile under one older linux Centos 6.7, i edited the tensorflow.bzl file and added manually at some linkopts field -lrt near -lm. Then compilation was successfull. Hope this help.

**Comment by shmilyhh** [comment] 2018-02-02 18:50
@zwergon Can you tell me how you add the "-lrt" field? Thanks.

**Comment by acaprez** [comment] 2018-02-02 23:40
I had the same error on CentOS 6.9, but was able to get it to build successfully by adding `-lrt`  to the linking options on lines 267 and 1267 in `tensorflow.bzl`.   A small patch file with the changes is  [here](https://github.com/tensorflow/tensorflow/files/1691141/librt.txt).

**Comment by shmilyhh** [comment] 2018-02-04 17:35
@acaprez Thanks.

**Comment by wookietreiber** [comment] 2018-07-02 13:32
We just ran into the same issue, also using CentOS 6 and GCC 4.x on our HPC cluster. It seems, there is still a lot of demand for official support for these aging distros / compilers.

**Note:** This might not be a CentOS 6 only problem, I suppose, this might as well be pinned to GCC 4.x or GCC < 6, not necessarily exclusive to CentOS 6. Not sure, though.

I don't see a `.travis.yml`. If you would set up Travis CI or CI framework of your choice, I suppose, the community would even pitch in and contribute the CentOS 6 testing without too much effort on your part.

**Comment by gunan** [comment] 2018-07-02 17:24
Our build is too heavy for travis(would take hours), so we use a different CI for our official builds.
Since on our side, we exclusively use debian based distros, we keep it working for these but centos issues are invisible to us.
However, if anyone would like to maintain a centos build (non merge blocking) I am happy to help you setup webhooks from TF repo, and I am happy to expedite review of fixes on rhel/centos

**Comment by jinglingzhua** [comment] 2018-12-23 02:57
same problem. I've tried adding "-lrt" as much as possible, but still not work.
finally I switched to docker, as https://www.tensorflow.org/install/source#docker_linux_builds says, "TensorFlow's Docker development images are an easy way to set up an environment to build Linux packages from source."
use docker image tensorflow1.12.0-devel, and some modification to .bzl files according to 
 https://stackoverflow.com/questions/39032329/is-there-any-way-to-build-tensorflow-from-source-without-having-internet.
finally it's done

**Comment by joshpencheon** [comment] 2019-03-01 15:56
For those arriving via Google in future, the following `-lrt` additions allowed tensorflow r1.12 to build for me on CentOS7: https://gist.github.com/joshpencheon/bd4299223c26.

**Comment by gunan** [comment] 2019-03-01 19:46
Thanks for debugging this @joshpencheon 
If you like to contribute a pull request with your fix, I would be happy to review and merge your change!

**Comment by shubhamn94** [comment] 2019-05-11 12:56
> For those arriving via Google in future, the following `-lrt` additions allowed tensorflow r1.12 to build for me on CentOS7: https://gist.github.com/joshpencheon/bd4299223c26.

Hello, 
I am facing the similar issue but the link you provided above land me to "page not found". Could you please help provide the command?
Thanks!!
