### ISSUE TITLE
tf.distributions.Uniform does not produce unique samples

### ISSUE THREAD

**Issue by meereeum** [tensorflow/tensorflow#22551] opened 2018-09-26 21:05 UTC
### System information

- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: debian 9 (stretch)
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: n/a
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.9.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: n/a
- **GCC/Compiler version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: see below (short version: `N=int(1e4); assert len(tf.unique(tf.distributions.Uniform().sample(N)).y.eval()) == N`)

### Describe the problem

Traced subtle bug in my code back to the fact that the TF Uniform distribution (maybe others?) does not produce unique samples.. This is bad.

```
N = int(1e4)

len(np.unique(np.random.rand(N))) # 10000

tf.InteractiveSession()
len(tf.unique(tf.distributions.Uniform().sample(N)).y.eval()) # 9993
```

**Comment by facaiy** [comment] 2018-09-27 06:13
If I understand correctly, uniform is a distribution. It makes sense that we might get duplication values from sample method.

**Comment by harshini-gadige** [comment] 2018-09-27 17:48
@meereeum @facaiy   Can this be closed ?

**Comment by meereeum** [comment] 2018-09-27 18:55
Sure, it's a distribution! But, computationally speaking, there are >2^24 possible 32-bit floats between 0 and 1, at a low estimate (see e.g. https://lemire.me/blog/2017/02/28/how-many-floating-point-numbers-are-in-the-interval-01 ). So - even accounting for bias in generating randomness - there should not be ~7 conflicts / 10000. (Probability theory-wise, we would draw two identical samples with probability 0.)

At the very least, it should be noted in the docs that TF uses less entropy for random number generation than other libraries (if this is the source of the issue), since this behavior deviates from user expectations.

**Comment by axch** [comment] 2018-09-28 16:31
Actually, you _would_ expect about that many collisions in 10,000 draws from a space of 2^23 possibilities, because of the "[birthday paradox](https://en.wikipedia.org/wiki/Birthday_problem)".  For instance,

```
N = int(1e4)
len(np.unique(np.random.randint(low=0, high=2**23, size=N)))
9993
```

There are 2^23 32-bit floats between 1.0 and 2.0.  In that range, the behavior of numpy and of TensorFlow agree (once you correct for numpy's default floating point precision being 64 bits):
```
len(np.unique(np.random.uniform(low=1., high=2., size=N).astype(np.float32)))
9992
len(np.unique(tf.distributions.Uniform(low=1., high=2.).sample(N).eval()))
9994
```

The range 0.0 to 1.0 is more interesting, because floating-point precision increases exponentially near 0.  There are ~2^30 32-bit floats between 0.0 and 1.0, but, of course, the continuous-uniform distribution on [0.0, 1.0) does not map into the discrete-uniform distribution on those 2^30 floats, because the floats near 0 are denser and thus lower probability.  Here TensorFlow and numpy disagree somewhat: In the interest of speed, TensorFlow loses precision near 0 (internally, it actually generates a float between 1.0 and 2.0, and then subtracts 1).  Numpy goes to greater lengths to conserve this precision, but even that doesn't defeat the brithday attack completely: there are 2^23 32-bit floats between 0.5 and 1.0, so that space is sparse enough to generate collisions by itself regardless of how careful one is at 0:

```
for _ in range(10):
  print(len(np.unique(np.random.uniform(low=0., high=1., size=N).astype(np.float32))))
10000
9999
9999
9998
9996
9995
9998
9999
9996
10000
```

**Comment by axch** [comment] 2018-09-28 17:16
If uniqueness is important in your application, you could increase precision to 64 bits:
```
for _ in range(10):
  print(len(np.unique(tf.distributions.Uniform(
    low=np.float64(0.), high=np.float64(1.)).sample(N).eval())))
10000
10000
10000
10000
10000
10000
10000
10000
10000
10000
```
or, of course, detect duplicates explicitly.

If you really need a floating-point uniform distribution in TensorFlow with high precision near 0, please file a feature request for that.  It's likely to be enough slower to be a separate code path, and probably is a better fit for [TensorFlow Probability](https://github.com/tensorflow/probability) than for TensorFlow proper. Closing this issue as "intended behavior".

**Closed by axch** 2018-09-28 17:16 UTC

**Comment by meereeum** [comment] 2018-09-29 00:01
@axch interesting, and great catch - thanks for the thorough response.
also, I hadn't realized it was possible to generate 64-bit uniforms by modifying the default params.

for posterity, the chance of having no collisions with 10,000 samples & 2^23 slots - as per default TF uniform sampling on [0,1) - is:
```
from scipy.special import gammaln

log_factorial = lambda x: gammaln(x+1)
logprob_unique = lambda n, k: log_factorial(n) - (k * np.log(n) + log_factorial(n-k))

1 - np.exp(logprob_unique(2**23, 10**4)) # 0.997425855296802
```
