### ISSUE TITLE
math floordiv function gives incorrect result

### ISSUE THREAD

**Issue by mattbarrett98** [tensorflow/tensorflow#56130] opened 2022-05-17 09:29 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### Current Behaviour?

```shell
The code 

import tensorflow as tf
x = tf.constant([1e-37], dtype=tf.float32)
y = tf.constant([-2.0], dtype=tf.float32)
tf.math.floordiv(x, y)
```
works as expected, giving 
```<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-1.], dtype=float32)>```.

However
```
import tensorflow as tf
x = tf.constant([1e-38], dtype=tf.float32)
y = tf.constant([-2.0], dtype=tf.float32)
tf.math.floordiv(x, y)
```
gives 
```<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-0.], dtype=float32)>```.

Any idea why when x gets small enough it starts to output `-0.` rather than `-1.`. `1e-38` is still in range for float32 I believe so I think it should still work?
```


### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1J583b0h11hee3UItK6l4VyaJ_hG7J4AT#scrollTo=c4-4DQ72QPZy
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment] 2022-05-18 10:43
@chunduriv I was able to replicate the issue on colab , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/2f7452755c7a7ea18becaa40bcf0d781/56130.ipynb) for your reference.
Thank you!

**Comment by chunduriv** [comment] 2022-06-16 11:38
@mattbarrett98,

This is an intended behavior and the same can also be seen in all cases mentioned below

Using `TF` without `dtype`
```
import tensorflow as tf
x = tf.constant([1e-38])
y = tf.constant([-2.0])
print(tf.math.floordiv(x, y))
```
Output:

`tf.Tensor([-0.], shape=(1,), dtype=float32)
`

Using `math` module

```
import tensorflow as tf
from math import floor
x2 = tf.constant([1e-38], dtype=tf.float32)
y2 = tf.constant([-2.0], dtype=tf.float32)
print(floor(x2/y2))
```
Output:
```
0
````

Using `Python`

````
x3 = tf.constant([1e-38], dtype=tf.float32)
y3 = tf.constant([-2.0], dtype=tf.float32)
print(x3//y3)
````

`tf.Tensor([-0.], shape=(1,), dtype=float32)
`

Thank you.

**Comment by mattbarrett98** [comment] 2022-06-16 12:04
I see, thanks for your help!

**Comment by chunduriv** [comment] 2022-06-16 15:35
@mattbarrett98,

Please feel free to close the issue if it is resolved? Thank you.

**Closed** 2022-06-16 15:49 UTC
Labels: stat:awaiting response, type:bug, comp:ops, TF 2.8
