### ISSUE TITLE
Difference in higher order tf.gradients()

### ISSUE THREAD

**Issue by GJBoth** [tensorflow/tensorflow#23128] opened 2018-10-20 12:44 UTC
**System information**

- OS: OS X 10.13.6
- TensorFlow installed from (source or binary): Anaconda
- TensorFlow version (use command below): 1.11
- Python version: 3.6.6
- Have I written custom code: No
- Bazel version: N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
- Exact command to reproduce: See below.
- Mobile device: N/A

**Describe the current behavior**
I have a cost function based on the derivative of the output of the network c w.r.t to the inputs of the network x and t.  I wish to replace x and t by one input tensor X=[x,t]. To test my code, I have the written the following function which returns the gradients:

`def cost_diffusion_test(x, t, X ,c):
    c_t = tf.gradients(c, t)[0]
    c_x = tf.gradients(c, x)[0]
    c_xx = tf.gradients(c_x, x)[0]

    dc = tf.gradients(c, X)[0]
    d2c = tf.gradients(dc[:, 0:1], X)[0]

    return c_t, c_x, c_xx, dc, d2c`

c_t and dc[:,1:2], c_x and dc[:,0:1] are the same as expected through np.array_equal(). c_xx and d2c[:,0:1] are not. When I study the difference d2c[:,0:1]-c_xx the I observe many zeros and a few terms on the order of e-08. Intriguingly, the maximum and minimum difference is 5.9604645e-08. If this would be a tensorflow-> numpy error, why is the first order derivative correct?

**Describe the expected behavior**
np.array_equal(d2c[:,0:1], c_xx)==True

**Comment by ymodak** [comment] 2018-10-24 16:54
In order to expedite the trouble-shooting process, please provide a minimum example to reproduce the issue reported here so that we can quickly identify the source. Thanks!

**Comment by ymodak** [comment] 2018-11-06 18:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-11-06 18:39 UTC
Labels: comp:ops, stat:awaiting response
