### ISSUE TITLE
keras preprocessing data_utils.py not working for non-'inferred' labels

### ISSUE THREAD

**Issue by mabhags** [tensorflow/tensorflow#44516] opened 2020-11-02 09:54 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/5473994/tf_env.txt)

You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
data_utils works for labels= 'inferred', but not for any provided list of labels

**Describe the expected behavior**

It should work. I changed it as per:

[data_utils.txt](https://github.com/tensorflow/tensorflow/files/5474032/data_utils.txt)
which works as far as I can tell.
If this hasn't already been fixed in a later version, and if the changes meet with whatever standards you have, feel free to adopt any part of it for future versions.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment] 2020-11-02 16:36
@mabhags,
In order to expedite the trouble-shooting process, could you please provide the TensorFlow version, the complete code and the exact sequence of commands that you executed before running into the problem. Thanks!

**Comment by mabhags** [comment] 2020-11-03 11:33
I attached the output from script above - detailing my site config.

Here:

[test_pp.txt](https://github.com/tensorflow/tensorflow/files/5480819/test_pp.txt)
is a test file to see problem
here:
![Screenshot from 2020-11-03 22-08-08](https://user-images.githubusercontent.com/73822769/97978581-db7ba680-1e21-11eb-8433-b0a50f5b8d6b.png)
is a picture of the test data directory structure and contents - basically just 4 jpegs in the directory itself and another 4 ineach of two sub-directories
here:
Tensorflow version: 2.3.0
Test using  labels='inferred'
Found 8 files belonging to 2 classes.

Test using label=[<list of class labels>]
Traceback (most recent call last):

  File "/home/mark/Documents/kaggle/input/test_pp.py", line 38, in <module>
    shuffle=False)

  File "/home/mark/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/preprocessing/image_dataset.py", line 182, in image_dataset_from_directory
    follow_links=follow_links)

  File "/home/mark/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/preprocessing/dataset_utils.py", line 98, in index_directory
    len(labels), len(filenames), directory))

ValueError: Expected the lengths of `labels` to match the number of files in the target directory. len(labels) is 12 while we found 8 files in ./samplesplit.
: are the results of running with the dataset_utils.py
here:
[dataset_utils.txt](https://github.com/tensorflow/tensorflow/files/5480854/dataset_utils.txt)
is the adjusted dataset_utils I used (apologies but I attached the wrong file last night).
here:
Tensorflow version: 2.3.0
Test using  labels='inferred'
Found 8 files belonging to 2 classes.

Test using label=[<list of class labels>]
Found 12 files belonging to 5 classes.
: are the results of running with this - which is what I would expect to get based on the input data to the call to image_dataset_from_directory.

The inferred results are the same in both cases. 

The labels with list of classes results are not.
The main problem is the current dataset_utils is failing to read files from the parent directory - because the subdirs list compiled does not include the parent directory - which I believe it should - because potentially, if using a provided list of labels (and *not* 'inferred') there would be no subdirectories, just files in the (single) parent directory, although handling subdirecttoies too is a bonus just in case.

Thx - I hope this is enough to allow you to investigate now.
Cheers, Mark

**Comment by mabhags** [comment] 2020-11-03 11:46
oh - yes I know the REALs and FAKEs would not match between the two calls because of sorted subdir order - it doesn't matter for this test case.

**Comment by mabhags** [comment] 2020-11-03 11:47
oops - now I know what Close with comment does...

**Comment by amahendrakar** [comment] 2020-11-16 10:41
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/2c92d5d9eb037ecd1833a59c7506d60f/44516.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/24cb18f80813d722532e220a78c08fc7/44516-tf-nightly.ipynb#scrollTo=TTmjGpjrkF5m). Please find the attached gist. Thanks!

**Comment by rmothukuru** [comment] 2020-11-17 14:49
@mabhags,
As per the `labels` argument mentioned in the  [Arguments Section of image_dataset_from_directory](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory#arguments), it is mentioned as : 


> labels | Either "inferred" (labels are generated from the directory structure), or **a list/tuple of integer labels of the same size as the number of image files found in the directory**. Labels should be sorted according to the alphanumeric order of the image file paths (obtained via **os.walk(directory)** in Python).

The code works fine if we replace the line of code,

`validation_labels = ['a','b','b','d','REAL','REAL','REAL','REAL','FAKE','FAKE','FAKE','FAKE']` 

with

`validation_labels = ['REAL','REAL','REAL','REAL','FAKE','FAKE','FAKE','FAKE']`
 
It is because, when we execute **`os.walk(val_dir)`** (as mentioned above):

```python
import os

for EachFile in os.walk(val_dir):
  print(EachFile)
```
It will not list the Image Files which are not in Sub Folders. and will only shows the Image Files which are in the Sub Folders. It is shown below:

```python
('./samplesplit', ['REAL', 'FAKE'], ['test_image4.jpg', 'test_image2.jpg', 'test_image3.jpg', 'test_image1.jpg'])
('./samplesplit/REAL', [], ['real_image3.jpg', 'real_image1.jpg', 'real_image4.jpg', 'real_image2.jpg'])
('./samplesplit/FAKE', [], ['fake_image1.jpg', 'fake_image4.jpg', 'fake_image3.jpg', 'fake_image2.jpg'])
```
Please find the [Gist of the Complete working code](https://colab.research.google.com/gist/rmothukuru/c4c1e1a7a9e39ca9bf0a7def05087d5e/44516.ipynb).

Hope it is clear now. Thanks!

**Comment by rmothukuru** [comment] 2020-11-24 13:22
@mabhags,
Can you please respond to the above comment. Thanks!

**Comment by mabhags** [comment] 2020-11-25 09:00
My interpretation of the documentation, and of the way os.walk works is that for the non-inferred option, all files in the specified directory are traversed, regardless of subdirectories. In a likely scenario of having source images not distributed into a set of class directories - which happens to be my situation - there is no reason for any directory structure beyond a single level. So in this case all 12 images would likely all be at the same directory level, there would be no REAL or FAKE subdirs - and the preprocessor as it stands would then pick up zero files - which is what happened at my first attempt - I only added the subdirs to try and figure out what it was up to.

**Comment by rmothukuru** [comment] 2020-11-25 11:37
@mabhags,
Unfortunately, that is not how it is designed. In your case, you can create a `Dataframe` with the 

1. `Paths of Images` as one Column and 
2. `Labels` as another column 

and then you can use **`ImageDataGenerator.flow_from_dataframe`**. 

Thanks!

**Comment by mabhags** [comment] 2020-11-26 10:26
OK, but either the documentation, or the code needs to change because currently they do not match each other.

**Comment by rmothukuru** [comment] 2021-02-10 10:35
@mabhags,
Can you please let us know what exactly in the documentation needs to be changed so that we can do it and close this issue? Thanks!

**Closed** 2021-02-24 11:52 UTC
Labels: TF 2.3, comp:keras, stalled, stat:awaiting response, type:bug, type:docs-bug
