### ISSUE TITLE
Upgrade Tensorflow-1.0.0rc2-cp35-cp35m-win_amd64.whl on Windows and get warning

### ISSUE THREAD

**Issue by huangying1201** [tensorflow/tensorflow#7716] opened 2017-02-21 01:07 UTC
I upgrade Tensorflow-1.0.0rc2-cp35-cp35m-win_amd64.whl, CPU version on Windows server 2012 R2

pip install --upgrade   
http://ci.tensorflow.org/view/Nightly/job/nightly-win/85/DEVICE=cpu,OS=windows/artifact
/cmake_build/tf_python/dist/tensorflow-1.0.0rc2-cp35-cp35m-win_amd64.whl

It shows 
"Successfully installed tensorflow-1.0.0rc2 werkzeug-0.11.15"

But I get the following warning when I run the hello example, please advise what's the problem.

>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow')
>>> sess = tf.Session()
2017-02-20 16:53:15.825086: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE instructions, but these are available on your m
achine and could speed up CPU computations.
2017-02-20 16:53:15.826037: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE2 instructions, but these are available on your
machine and could speed up CPU computations.
2017-02-20 16:53:15.827289: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE3 instructions, but these are available on your
machine and could speed up CPU computations.
2017-02-20 16:53:15.828478: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.1 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-02-20 16:53:15.829644: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use SSE4.2 instructions, but these are available on you
r machine and could speed up CPU computations.
2017-02-20 16:53:15.830997: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use AVX instructions, but these are available on your m
achine and could speed up CPU computations.
2017-02-20 16:53:15.832161: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use AVX2 instructions, but these are available on your
machine and could speed up CPU computations.
2017-02-20 16:53:15.833336: W c:\tf_jenkins\home\workspace\nightly-win\device\cp
u\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow li
brary wasn't compiled to use FMA instructions, but these are available on your m
achine and could speed up CPU computations.
>>> print(sess.run(hello))
b'Hello, TensorFlow'

**Comment by poxvoculi** [comment] 2017-02-21 20:24
I'm not very knowledgeable on installation, but I believe that a pip install uses a pre-compiled binary rather than building one specific to your machine characteristics.  The warning messages you see just warn that the binary is not fully optimized for the instructions available.  To build a better binary you may need to invoke bazel.  Perhaps this stackoverflow thread may help you:  
http://stackoverflow.com/questions/41293077/how-to-compile-tensorflow-with-sse4-2-and-avx-instructions

**Comment by Carmezim** [comment] 2017-02-21 21:45
Just adding on top of what @poxvoculi already said, those are just warnings informing if you build TensorFlow from source its performance can be optimized and become faster on your machine.

**Comment by gunan** [comment] 2017-03-02 05:56
What @poxvoculi and @Carmezim stated is correct.
We build and distribute binaries that can run on all/most available hardware.
However, if you have a newer CPU, you can build TF from sources.

Closing the issue as Working as Intended.

**Closed by gunan** 2017-03-02 05:56 UTC
Labels: stat:awaiting response

**Comment by davtalab** [comment] 2017-04-19 23:10
I installed Tensorflow on Windows10 and when testing in Python I get the following error:

`C:\Python35\python.exe C:/Users/loc/PycharmProjects/Practice/tensorflow_test.py
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
b'Hello, TensorFlow!'`

Can anyone let me know what else should I do to resolve this issue?

**Comment by Carmezim** [comment] 2017-04-19 23:26
@davidbrai download the respective wheel from https://pypi.python.org/pypi/tensorflow after uninstalling TF and install it again. This error is harmless and resolved on 1.1.0r.

**Comment by davtalab** [comment] 2017-04-19 23:40
I updated my TF to tensorflow-1.1.0rc2 version. Now I am getting the following warnings:

`2017-04-19 16:35:22.533979: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:35:22.534756: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:35:22.535027: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:35:22.535245: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:35:22.535462: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:35:22.535680: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:35:22.536664: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:35:22.536925: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
b'Hello, TensorFlow!'`

Any idea how to solve it?

**Comment by Carmezim** [comment] 2017-04-20 00:58
That is intended behavior.
http://stackoverflow.com/questions/43335531/how-to-use-sse4-1-instructions-without-install-tensorflow-from-source/43335630#43335630

**Comment by davtalab** [comment] 2017-04-20 01:07
@Carmezim Thanks a lot! That helped to silence the warnings.
