### ISSUE TITLE
AutoGraph returns an empty array when I use a for-loop and TensorArray

### ISSUE THREAD

**Issue by Rendok** [tensorflow/tensorflow#33193] opened 2019-10-10 04:09 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14.6
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.6.x
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: - 
- GPU model and memory: -

Hello! Here is a sniped of code:
```python
a = np.array([1, 2, 3], np.int32)

@tf.function  # works without the decorator
def foo(a):
  b = tf.TensorArray(tf.string, 4)
  b.write(0, "test")
  for i in tf.range(3):
    if a[i] == 2:
      b.write(i, "fuzz")
    elif a[i] == 3:
      b.write(i, "buzz")
  return b.stack()

print(foo(a))
```
With the decorator, the AutoGraph returns an empty array:
`tf.Tensor([b'' b'' b'' b''], shape=(4,), dtype=string)`

However, it shoud return:
`tf.Tensor([b'test' b'fuzz' b'buzz' b''], shape=(4,), dtype=string)`

**Comment by gadagashwini** [comment] 2019-10-10 12:01
@Rendok, This works for me,
```
import tensorflow as tf
import numpy as np
a = np.array([1, 2, 3], np.int32)

@tf.function  # works without the decorator
def foo(a):
  b = tf.TensorArray(tf.string, 4)
  b = b.write(0, "test")
  for i in tf.range(3):
    if a[i] == 2:
      b = b.write(i, "fuzz")
    elif a[i] == 3:
      b = b.write(i, "buzz")
  return b.stack()

print(foo(a))
```
It return:
`tf.Tensor([b'test' b'fuzz' b'buzz' b''], shape=(4,), dtype=string)`

**Comment by Rendok** [comment] 2019-10-11 00:17
Hi @gadagashwini,

It doesn't work on my side after a clean install of TF 2.0. Here is a [colab](https://colab.research.google.com/drive/17KHUJS9PWC_vh8Tj56eGQwTPfkSDE_eS) for reproducibility. Probably, one of the dependencies is too fresh.

**Comment by gadagashwini** [comment] 2019-10-11 06:09
@Rendok, 
Its strange, When I tried on Colab with TF 2.0.0, I got the expected result. Please see the [gist here](https://colab.sandbox.google.com/gist/gadagashwini/1cbece92b179923ab9b2c34361a03176/untitled191.ipynb). Thanks!

**Comment by Rendok** [comment] 2019-10-11 06:42
It's strange, but it now works on my side too. The only difference that I have updated my macOS.

Thanks!

**Comment by mdanatg** [comment] 2019-10-23 14:09
@kkimdev FYI

Indeed, this is a known consistency that has caused quite a bit of confusion. We are looking into ways to make the two behaviors consistent: either by making `ta.write(i, value)` work in graph or by raising an error when it's used in eager.

Until this is resolved, the workaround is to write `ta = ta.write(i, value)`, as you pointed out.

**Comment by gadagashwini** [comment] 2020-04-03 10:28
@Rendok, This issue is fixed in Tf2.2rc2, Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/4e36bcd6d355ca7853d94e8e77b11a8f/33193.ipynb). Thanks

**Comment by amahendrakar** [comment] 2020-06-23 19:05
Was able to reproduce the issue with TF v2.2 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/89651333269bdf262dff0ead45c7e05d/33193.ipynb). Thanks!

**Comment by sachinprasadhs** [comment] 2021-05-19 13:56
@Rendok I was able to run the code without any error in the recent Tensorflow version 2.5, please find the gist [here](https://colab.research.google.com/gist/googly789/babde65dbbd022be58fdbf9ada6f7aff/203.ipynb).

**Closed** 2021-05-20 10:51 UTC
Labels: TF 2.2, comp:autograph, comp:core, type:bug
