### ISSUE TITLE
Running two Models in two GPUs for prediction in c++

### ISSUE THREAD

**Issue by kerolos** [tensorflow/tensorflow#18861] opened 2018-04-25 12:45 UTC
### System information
- **Have I written custom code  (as opposed to using a stock example script provided in TensorFlow): N/A
- **OS Platform and Distribution (e.g., Debian 9.1):
- **TensorFlow installed from (source bazel):
- **TensorFlow version (use command below) 1.7:
- **Python version 3.6: 
- **Bazel version (if compiling from source) 0.11:
- **GCC/Compiler version (if compiling from source GCC)6.3:
- **CUDA/cuDNN version 9.1. cudnn 7.1:
- **GPU model and memory 2 GPU GTX 1080 TI, 11GB:
- **Exact command to reproduce: compiling by c++  

### Describe the problem
   i would like to use two gpus at the same time for make a preduction of two models by using this of code: session_options.config.mutable_gpu_options()->set_visible_device_list("0"); unfortunatlly i got this error (Invalid allocator type: 0):
2018-04-25 14:35:17.895671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
2018-04-25 14:35:17.895717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-25 14:35:17.895722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-04-25 14:35:17.895727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-04-25 14:35:17.895961: E tensorflow/core/common_runtime/gpu/process_state.cc:125] Invalid allocator type: 0
2018-04-25 14:35:17.895977: E tensorflow/core/common_runtime/direct_session.cc:167] Internal: Failed to get memory allocator for TF GPU 0 with 10913103872 bytes of memory.

### Source code / logs
    session_options.config.mutable_gpu_options()->set_visible_device_list("0");   --->error is here
    session_options.config.mutable_gpu_options()->set_allow_growth(true);
    session.reset(tensorflow::NewSession(tensorflow::SessionOptions(session_options)));

**Comment by tensorflowbutler** [comment] 2018-04-26 01:27
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by asimshankar** [comment] 2018-05-01 06:43
Unfortunately, though `visible_deivces_list` is included in `ConfigProto`, it is actually a per-process setting. In fact, this is true of almost all options inside the [`GPUOptions`](https://github.com/tensorflow/tensorflow/blob/r1.8/tensorflow/core/protobuf/config.proto#L123) protocol buffer. 

Apologies for that.

In the mean time, a possible work around is to have the models themselves explicitly use different GPUs. You can do so by explicitly constructing the models as so (e.g.., using `with tf.device('/gpu:1')` when creating the graph in a Python program), or editing the graph before creating the session (a similar workaround [in Java was suggested on StackOverflow](https://stackoverflow.com/a/47915987/6708503)).

Hope that helps in the short term.

Assigning to @yifeif - who is looking into at least making this subtlety more explicit and then perhaps even overcoming this limitation.

Also CCing @akshayka who was looking into more dynamic assignment of devices to models at runtime.

**Comment by kerolos** [comment] 2018-05-04 09:32
thanks a lot, @asimshankar for your answer. I will try to do something similar to Java.

**Comment by asimshankar** [comment] 2018-05-05 17:52
@rundembear : To confirm, are you saying that the mechanism suggested in https://github.com/tensorflow/tensorflow/issues/18861#issuecomment-385610497 works fine in 1.3 and 1.5, but not 1.6?

If so, what fails in 1.6? Could you add some detail here? Ideally a [minimal, complete, verifiable](https://stackoverflow.com/help/mcve) snippet if possible.

**Comment by rundembear** [comment] 2018-05-05 19:41
I entered a separate ticket for this, sorry, should have had this link in my comment. This is via python, but it is, I believe, the same mechanism. I am trying to do this with multiple copies of the same model, but still essentially the same issue. This includes a very small code snippet which runs fine on 1.3 and 1.5. and crashes from 1.6 onwards.

https://github.com/tensorflow/tensorflow/issues/19083


import tensorflow as tf
G =tf.Graph()
sess1 = tf.Session(graph=G, config=tf.ConfigProto(log_device_placement=False,gpu_options=tf.GPUOptions(allow_growth=True,visible_device_list='0')))
sess2 = tf.Session(graph=G, config=tf.ConfigProto(log_device_placement=False,gpu_options=tf.GPUOptions(allow_growth=True,visible_device_list='1')))

**Comment by rundembear** [comment] 2018-05-10 08:54
@asimshankar Just a bump on this, it is still tagged 'awaiting response' although I responded five days ago. Thanks!

**Comment by asimshankar** [comment] 2018-05-11 17:37
@rundembear : Sorry, I missed your update somehow.
Anyway, I see that it crashes with an unhelpful message to the user, which should be fixed.

However, I don't think it quite worked in 1.3 either - in that it wouldn't crash, but it would basically end up ignoring the `visible_device_list` the second time around. I'll dig in further (don't have a multi-GPU machine handy at the moment), but could you verify that in 1.3 it wasn't actually using two GPUs?

Also CCing @yifeif who is working to make these error messages clearer.

**Comment by rundembear** [comment] 2018-05-11 18:39
@asimshankar and @yifeif  I have just run a very simple test using our production code. I logged into a machine with 8 GPUs and ran a command which allows me to run my graph, one thread per GPU (but all in the same process). If I use 'visible_device_list' to map the correct GPU for each thread to be 0 at that thread, I see load distributed across all 8 GPUs (using nvidia-smi) and I can execute a typical request in 2 seconds. If I comment out the 'visible_device_list' (and this is the only change) I see load only on GPU 0 and the same request takes 8.2 seconds. Which sounds about right as our code currently only hits about 50% GPU utilization at each GPU (trust me, I'm working on that). 
So I feel fairly strongly that this is working as expected in 1.3.

**Comment by asimshankar** [comment] 2018-05-11 18:54
Thanks @rundembear 

@aaroey : Is it possible that the changes to support virtual devices broke this?
I see that [in the r1.5 branch](https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/core/common_runtime/gpu/gpu_device.cc#L756, we're creating `Device*` objects based on the `visible_devices_list` value.

But by the [1.6 branch](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/core/common_runtime/gpu/gpu_device.cc#L930) we've started check-failing when [there is a mapping change between `TfGpuId` and `CudaGpuId`](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/core/common_runtime/gpu/gpu_id_utils.cc#L67)

So I suspect this was indeed broken by https://github.com/tensorflow/tensorflow/commit/14cb8e14a8fb1e78e2ce623e4198972762e6e253

Sorry for the trouble @rundembear - I was mistaken about which fields were process-global in 1.3.

**Comment by rundembear** [comment] 2018-05-11 19:07
@asimshankar No trouble at all. I appreciate the need to be sure before spending too much time on such things. Thanks!

**Comment by rundembear** [comment] 2018-05-15 17:43
@aaroey Thank you very much for your explanation. I don't feel like our language is quite lining up so I'm not sure whether your concern is warranted.  I am not doing anything to 'rename' the GPUs. As far as I know /gpu:3 is still /gpu:3 but I have created a tensorflow session in which reference to /gpu:0 will be redirected to /gpu:3. So if this mechanism were working as described the problem you raise would be a non-issue. If the graph has been optimized so that all of the operations are efficiently scheduled to run on /gpu:0, but within a session this is remapped then I should still be running the same graph on all GPUs. 

I have a feeling that what you are saying is that this mechanism should never have existed and there isn't actually a use case for which it makes sense, but perhaps I am missing something?

Or are you saying that there are operations that occur outside of any sessions that see all of the GPUs, and thus might do the wrong thing? But is this really a problem if the entire graph is assigned to GPU 0?

Let me clarify what our use case is to explain why this not being supported is rather unfortunate. We are carrying out Bayesian Inference and distributing our sampling across multiple GPUs. The thing is, we are running exactly the same graph on every GPU. If we do things as you suggest then I need to actually create N copies of the graph with each graph being run on a different GPU. Alternatively I can rearchitect my code into a master/servant model using multiprocessing and have each process manipulate CUDA_VISIBLE_DEVICES so that it can only see one GPU. While you may have decided that this is not something that you want to support this is exactly what the documentation says this mechanism is for.

**Comment by aaroey** [comment] 2018-05-15 23:00
Hi @rundembear,

Sorry for the confusion, let me clarify:
1. it's totally fine to use different configs in different process, there is no restriction on that. For example, you may set CUDA_VISIBLE_DEVICES=1 in one process and 2 in another, you may also set visible_gpu_device or any other ConfigProto options differently.
1. in the same process, if possible, we should use same [GPUOptions](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L16) for all sessions, as most of the options inside GPUOptions are process-wide (AFAIK, per_process_gpu_memory_fraction, allocator_type, allow_growth, visible_device_list, experimental are all process-wide options). If we use different GPUOptions for different sessions, unexpected behavior may/would occur, depending on which options you set differently.

In your case, specifically for the code:
```
G =tf.Graph()
sess1 = tf.Session(graph=G, config=tf.ConfigProto(log_device_placement=False,gpu_options=tf.GPUOptions(allow_growth=True,visible_device_list='0')))
sess2 = tf.Session(graph=G, config=tf.ConfigProto(log_device_placement=False,gpu_options=tf.GPUOptions(allow_growth=True,visible_device_list='1')))
```

`sess1` and `sess2` are in same process and using same graph but different GPUOptions options (visible_device_list is different).

- For `sess1`, a `BaseGPUDevice` will be created with name '/gpu:0' and pointing to **physical gpu 0**
- For `sess2`, a `BaseGPUDevice` will be created with name '/gpu:0' but pointing to **physical gpu 1**.

Note that both device have same name '/gpu:0', so any code that use only the device name (not the BaseGPUDevice object itself) to access the physical gpu will be directed to physical gpu 0, this is what I called 'unexpected behavior'. For example, assume that `G` has a node placed in '/gpu:0', grappler will use the information from physical gpu 0 to optimize your graph in `sess2` which is not what we want.

In order to apply the same graph to different gpu, we can use `with tf.device()` with different device name when building/importing the graph.

Thanks.

**Comment by rundembear** [comment] 2018-05-16 09:49
@aaroey Thank you so much for the clarification. In theory, as our current system is set up in a SIMD-like way, what we are doing quite possibly is fine, but I understand that that is by accident rather than design and that there may well be side-effects which at some point will bite us. It also sounds as if we would be best-advised to rework our code to behave in a supported way. 

You have definitely given me enough to go on in terms of things to try and changes that will definitely work.

Thanks again for your time and patience!

**Comment by aaroey** [comment] 2018-05-16 13:34
Thanks @rundembear for understanding. :)

**Comment by aaroey** [comment] 2018-05-16 13:36
I'm closing this issue, feel free to reopen if there are any other questions.

**Closed by aaroey** 2018-05-16 13:36 UTC
Labels: stat:awaiting response

**Comment by rundembear** [comment] 2018-05-16 15:01
@aaroey  One more question. I just tried reading multiple copies of my graph using this:

        with open(graphfile, 'rb') as f:
            graph_text = f.read()

        for g in range(len(graph_object.devices)):
            graph_object.graphs.append(tf.Graph())
            with tf.device(graph_object.devices[g]):
                graph_def = tf.GraphDef()
                graph_def.ParseFromString(graph_text)
                with graph_object.graphs[g].as_default():
                    tf.import_graph_def(graph_def, name='')


I ran this on 3 GPUs, so the devices list was:  ['/gpu:0', '/gpu:1', '/gpu:2']

Doing this places all of the load onto GPU 0. 

So when you said this: 

"In order to apply the same graph to different gpu, we can use with tf.device() with different device name when building/importing the graph."

either I am misunderstanding what you meant, or this mechanism does not work as you had hoped. 

If I am missing something, please correct what I am doing wrong; Otherwise it looks like the only way to accomplish what I want to do is to use multi-processing. That certainly is an option, just wanted to try this idea first. 

BTW, I also tried using the 'with tf.device()' when I created the session and when I ran the session. Still sends everything to GPU 0. Sigh.

**Comment by aaroey** [comment] 2018-05-16 15:46
Hi @rundembear,

I think we need to put `with graph_object.graphs[g].as_default():` before `with tf.device(graph_object.devices[g]):`, as `tf.device()` use [`get_default_graph().device()`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4991).

I tested the following code and the printed graphdef has the correct device assigned (I haven't run the graph though):
```
from google.protobuf import text_format
import tensorflow as tf

hello = tf.constant('Hello, TensorFlow!')
tf.train.write_graph(tf.get_default_graph(), '/tmp', 'g1')

with open('/tmp/g1', 'rb') as f:
  graph_text = f.read()
print(graph_text)
print('-' * 100)

graphs = []
for g in range(2):
  graphs.append(tf.Graph())
  with graphs[g].as_default():
    graph_def = tf.GraphDef()
    text_format.Merge(graph_text, graph_def)
    with tf.device('/gpu:' + str(g)):
      tf.import_graph_def(graph_def, name='')
    print(tf.get_default_graph().as_graph_def())
    print('-' * 100)
```

Thanks.

**Comment by rundembear** [comment] 2018-05-16 16:29
@aaroey You rock!!! That does the trick! Thank you so much for all of your help.

**Comment by aaroey** [comment] 2018-05-16 16:41
@rundembear You're very welcome, and I'm glad that we can help. Let me know if you have any other questions. :)

**Comment by nikkymen** [comment] 2018-05-31 13:49
In c++ this can be done with graph modification before creation the session, something like this:

```
void load_graph(const std::string &path, tensorflow::Session *session, const std::string &device = std::string())
{
    tensorflow::GraphDef graph_def;
    tensorflow::ReadBinaryProto(tensorflow::Env::Default(), path, &graph_def);

    if(!device.empty())
    {
        for(int i = 0; i < graph_def.node_size(); ++i)
        {
            graph_def.mutable_node(i)->set_device(device);
        }
    }

    tensorflow::NewSession(tensorflow::SessionOptions(), &session);
    session->Create(graph_def);
}

...

tensorflow::Session *session_gpu_0;
load_graph(graph_file_path, session_gpu_0, "/gpu:0");

tensorflow::Session *session_gpu_1;
load_graph(graph_file_path, session_gpu_1, "/gpu:1");

```

**Comment by nikkymen** [comment] 2018-06-16 12:18
@x10000year 
It seems to me that this is impossible.

You can try to modify the implementation of tf::LoadSavedModel from 
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/cc/saved_model/loader.cc](url)

With the modification of `GraphDef` from my post, before the session is created, you should get what you intended.

**Comment by Rongnian** [comment] 2018-07-06 03:40
@nikkymen 
Thanks for your solution, but is this only suit for Linux? I tried on windows and an error occurs:
"Invalid argument: No attr with name 'gpu:0 for input 'input'"

**Comment by nikkymen** [comment] 2018-07-07 08:31
@Rongnian 
I tested it on Linux, but I see no reason that it does not work under Windows. Probably, under Windows other identifiers for devices are necessary.

**Comment by knighthappy** [comment] 2018-07-18 08:41
my solution:
tensorflow1.8
c++

https://blog.csdn.net/cdknight_happy/article/details/81100554

**Comment by Franziska-Mueller** [comment] 2018-10-31 16:59
@Rongnian 
I don't know if this is still an issue for you but I experienced the same error today. I found a solution that worked for me: only set the device for nodes where the device string is non-empty.

```
for(int i = 0; i < graph_def.node_size(); ++i)
{
      if (graph_def.mutable_node(i)->device().empty() == false)
            graph_def.mutable_node(i)->set_device(device);
}
```

**Comment by ziyuang** [comment] 2019-02-12 15:33
> Hi @rundembear,
> 
> I think we need to put `with graph_object.graphs[g].as_default():` before `with tf.device(graph_object.devices[g]):`, as `tf.device()` use [`get_default_graph().device()`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4991).
> 
> I tested the following code and the printed graphdef has the correct device assigned (I haven't run the graph though):
> 
> ```
> from google.protobuf import text_format
> import tensorflow as tf
> 
> hello = tf.constant('Hello, TensorFlow!')
> tf.train.write_graph(tf.get_default_graph(), '/tmp', 'g1')
> 
> with open('/tmp/g1', 'rb') as f:
>   graph_text = f.read()
> print(graph_text)
> print('-' * 100)
> 
> graphs = []
> for g in range(2):
>   graphs.append(tf.Graph())
>   with graphs[g].as_default():
>     graph_def = tf.GraphDef()
>     text_format.Merge(graph_text, graph_def)
>     with tf.device('/gpu:' + str(g)):
>       tf.import_graph_def(graph_def, name='')
>     print(tf.get_default_graph().as_graph_def())
>     print('-' * 100)
> ```
> Thanks.

I wonder how to integrate this with `tf.contrib.predictor.from_saved_model`: for the same reason I cannot set different devices in different `tf.predictor.from_saved_model(<model_folder>, config=tf.ConfigProto(gpu_options=tf.GPUOptions(visible_device_list='<devices>')))`

**Comment by ttdd11** [comment] 2019-03-25 17:52
@nikkymen Have you tried the c++ fix in a recent tensorflow build? Setting devices using your code doesn't seem to work for me because of libprotobuf string issues. Any suggestions?

**Comment by shodow** [comment] 2019-04-08 08:04
@nikkymen i use your code,but it's still running in device 0
```c++
int main(int argc, char* argv[]) {
    std::string graph_file_path = "frozen_inference_graph.pb";
    tensorflow::Session *session_gpu_0 = load_graph(graph_file_path, "/gpu:0");
    tensorflow::Session *session_gpu_1 = load_graph(graph_file_path, "/gpu:1");
    Mat img = imread("1.bmp");
    int num = 0;
    while(num < 100) {
        Detect(img, session_gpu_0);
        Detect(img, session_gpu_1);
        num++;
    }
    getchar();
    return 0;
}
```
![image](https://user-images.githubusercontent.com/17686184/55708170-d1ac7a00-5a17-11e9-81e3-11d126798473.png)

**Comment by jlzhann** [comment] 2019-05-20 13:47
hi all,  I find a solutions for using multiple session with multiple gpu cards, follow are some main steps, 
1. if you build libtensorflow_cc.so with monolithic configure, please add protobuf in tf_version_script.lds
2. if you want to bind a gpu card with multiple session, you can use virtual_devices to split gpu memory
`
  // session options are process level configure
  tensorflow::SessionOptions options;
  tensorflow::ConfigProto &config = options.config;
  config.mutable_gpu_options()->set_visible_device_list("0,1");
  config.mutable_gpu_options()->set_allow_growth(false);
  // config.mutable_gpu_options()->set_per_process_gpu_memory_fraction(0.8);
  auto vd1 = config.mutable_gpu_options()->mutable_experimental()->add_virtual_devices();
  vd1->add_memory_limit_mb(3000.0);
  vd1->add_memory_limit_mb(6000.0);

  auto vd2 = config.mutable_gpu_options()->mutable_experimental()->add_virtual_devices();
  vd2->add_memory_limit_mb(2000.0);
  vd2->add_memory_limit_mb(5000.0);
`
3. bind a session to a graph with compute on the given virtual device,
`
// modify the graph def
for(int i = 0; i < graph_def.node_size(); ++i) {
   graph_def.mutable_node(i)->set_device(device);
}
`

**Comment by sorny92** [comment] 2019-06-06 14:55
@jlzhann That sounds really interesting. I will give it a try!  
Thanks for your help

**Comment by hillin** [comment] 2019-06-27 03:10
@nikkymen  @jlzhann  @sorny92 
In C++ you can set device for a graph when loading it with  [`TF_ImportGraphDefOptionsSetDefaultDevice`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h#L722) (or its C++ equivalent, I'm not on the TF C++ stack, just casually P/Invoking the API in C#).

**Comment by bit-ghost** [comment] 2019-07-04 12:32
have you run two models in two GPUs successfully in C++? I have tried with many method as is mentioned above, but failed to run.

**Comment by bit-ghost** [comment] 2019-07-04 12:33
have you run two models in two GPUs successfully in C++? I have tried with many method as is mentioned above, but failed to run.

**Comment by hillin** [comment] 2019-07-05 02:00
@bit-ghost be sure to [allow soft placement](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L424) in ConfigProto

**Comment by bit-ghost** [comment] 2019-07-05 02:57
@hillin 
thanks for your help! It succeeded. and sorry for disturbing you because i'm not familiar with tensorflow.
Additionally, we can use `tensorflow::graph::SetDefaultDevice("/device:GPU:1", pgraph_def);` to bind specific GPU device with a graph

**Comment by anshkumar** [comment] 2020-08-06 18:12
In python it can be done as follows:

```
def get_frozen_graph(graph_file):
    """Read Frozen Graph file from disk."""
    with tf.gfile.GFile(graph_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    return graph_def

trt_graph1 = get_frozen_graph('/home/ved/ved_1/frozen_inference_graph.pb')

with tf.device('/gpu:1'):
    [tf_input_l1, tf_scores_l1, tf_boxes_l1, tf_classes_l1, tf_num_detections_l1, tf_masks_l1] = tf.import_graph_def(trt_graph1, 
                    return_elements=['image_tensor:0', 'detection_scores:0', 
                    'detection_boxes:0', 'detection_classes:0','num_detections:0', 'detection_masks:0'])
    
tf_sess1 = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))

trt_graph2 = get_frozen_graph('/home/ved/ved_2/frozen_inference_graph.pb')

with tf.device('/gpu:0'):
    [tf_input_l2, tf_scores_l2, tf_boxes_l2, tf_classes_l2, tf_num_detections_l2] = tf.import_graph_def(trt_graph2, 
                    return_elements=['image_tensor:0', 'detection_scores:0', 
                    'detection_boxes:0', 'detection_classes:0','num_detections:0'])
    
tf_sess2 = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
```

**Comment by JackHsiung** [comment] 2021-05-28 02:02
> @nikkymen
> 
> I'm using tf::LoadSavedModel to load the model. How can I specify the gpu divice with this c++ API?

  tensorflow::RunOptions run_options;
  //run_options.set_timeout_in_ms(100);
  std::string tf_model_path = path_prefix + "/" + name_prefix;
  tensorflow::Status status = tensorflow::LoadSavedModel(options, run_options, tf_model_path, tags, _bundle_wrapper->_bundle.get());
  if (!status.ok()) {
    printf("Loading tf model failed. dir[ %s ], status[ %s ]\n", tf_model_path.c_str(), status.ToString().c_str());
    return -1;
  }
  printf("Loading tf model success. dir[ %s ], status[ %s ]\n", tf_model_path.c_str(), status.ToString().c_str());

  tensorflow::MetaGraphDef graph_def = _bundle_wrapper->_bundle->meta_graph_def;
  std::unique_ptr<tensorflow::Session>& session = _bundle_wrapper->_bundle->session;

  tensorflow::graph::SetDefaultDevice("/gpu:0", &graph_def.graph_def());
  session->Create(graph_def.graph_def());

**Comment by isra60** [comment] 2021-09-16 09:55
> > @nikkymen
> > I'm using tf::LoadSavedModel to load the model. How can I specify the gpu divice with this c++ API?
> 
> tensorflow::RunOptions run_options;
> //run_options.set_timeout_in_ms(100);
> std::string tf_model_path = path_prefix + "/" + name_prefix;
> tensorflow::Status status = tensorflow::LoadSavedModel(options, run_options, tf_model_path, tags, _bundle_wrapper->_bundle.get());
> if (!status.ok()) {
> printf("Loading tf model failed. dir[ %s ], status[ %s ]\n", tf_model_path.c_str(), status.ToString().c_str());
> return -1;
> }
> printf("Loading tf model success. dir[ %s ], status[ %s ]\n", tf_model_path.c_str(), status.ToString().c_str());
> 
> tensorflow::MetaGraphDef graph_def = _bundle_wrapper->_bundle->meta_graph_def;
> std::unique_ptrtensorflow::Session& session = _bundle_wrapper->_bundle->session;
> 
> tensorflow::graph::SetDefaultDevice("/gpu:0", &graph_def.graph_def());
> session->Create(graph_def.graph_def());

When trying to use this method I have the following error 

```
2021-09-16 09:52:20.248610: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:801] function_optimizer failed: Invalid argument: Converting GraphDef to Graph has failed with an error: 'Cannot add function '__inference__traced_restore_73624' because a different function with the same name already exists.' The binary trying to import the GraphDef was built when GraphDef version was 808. The GraphDef was produced by a binary built when GraphDef version was 838. The difference between these versions is larger than TensorFlow's forward compatibility guarantee, and might be the root cause for failing to import the GraphDef.
2021-09-16 09:52:20.282896: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:801] layout failed: Not found: No attr named '/gpu:2' in NodeDef:
         [[{{node Conv1/kernel}}]]
2021-09-16 09:52:20.319407: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:801] function_optimizer failed: Invalid argument: Converting GraphDef to Graph has failed with an error: 'Cannot add function '__inference__traced_restore_73624' because a different function with the same name already exists.' The binary trying to import the GraphDef was built when GraphDef version was 808. The GraphDef was produced by a binary built when GraphDef version was 838. The difference between these versions is larger than TensorFlow's forward compatibility guarantee, and might be the root cause for failing to import the GraphDef.
Segmentation fault (core dumped)
```
Are there any updates with the LoadSavedModel c++ API to use multiple GPU???

**Comment by lisheng89** [comment] 2022-06-28 06:36
>  try this method, my tensorflow environment is 1.15.2
 

int init(const std::string& model_path, int device_id) {
    tensorflow::SessionOptions sessionOptions;
    tensorflow::RunOptions runOptions;
    // some nodes could place in cpu
    sessionOptions.config.set_allow_soft_placement(true);
    // specify gpu device id (check `tensorflow/cc/saved_model/loader.cc` LoadSavedModelInternal)
    sessionOptions.config.mutable_gpu_options()->set_allocator_type("/gpu:" + std::to_string(device_id)); 
    sessionOptions.config.mutable_gpu_options()->set_per_process_gpu_memory_fraction(0.1);
    sessionOptions.config.mutable_gpu_options()->set_allow_growth(true);
    tensorflow::Status status;
    status = tensorflow::LoadSavedModel(sessionOptions, runOptions, model_path,
            {tensorflow::kSavedModelTagServe}, &_bundle);
    if (!status.ok()) {
        std::string error_string = status.ToString();
        std::cerr << error_string << std::endl;
        return -1;
    }
    return 0;
}
