### ISSUE TITLE
bug issue

### ISSUE THREAD

**Issue by mekhaaa** [tensorflow/tensorflow#38145] opened 2020-04-01 22:15 UTC
Traceback (most recent call last):
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate_tfrecord.py", line 17, in <module>
    import tensorflow as tf
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 50, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 69, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\ahmed\miniconda3\envs\tensorflow1\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by tensorflowbutler** [comment] 2020-04-01 22:34
From the template it looks like you are installing **TensorFlow** (TF) prebuilt binaries:

* For TF-GPU - See point 1
* For TF-CPU - See point 2

-----------------------------------------------------------------------------------------------

**1. Installing **TensorFlow-GPU** (TF) prebuilt binaries**

*TF Version >= 1.13 requires CUDA 10.0 and TF Version < 1.13 (till TF 1.5) requires CUDA 9.0.*

* If you have above configuration and using _**Windows**_ platform -
  * Try adding the CUDA, CUPTI, and cuDNN installation directories to the %PATH% environment variable.
  * Refer [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup).
* If you have above configuration and using _**Ubuntu/Linux**_ platform -
  * Try adding the CUDA, CUPTI, and cuDNN installation directories to the $LD_LIBRARY_PATH environment variable.
  * Refer [linux setup guide](https://www.tensorflow.org/install/gpu#linux_setup).
* If error still persists then, apparently your CPU model does not support AVX instruction sets.
  * Refer [hardware requirements](https://www.tensorflow.org/install/pip#hardware-requirements).

-----------------------------------------------------------------------------------------------

**2. Installing **TensorFlow** (TF) CPU prebuilt binaries**

*TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.*

 Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.
Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:

* Try Google Colab to use TensorFlow.
  * The easiest way to use TF will be to switch to [google colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb#recent=true).You get pre-installed latest stable TF version. Also you can use```pip install``` to install any other preferred TF version.
  * It has an added advantage since you can you easily switch to different hardware accelerators (cpu, gpu, tpu) as per the task.
  * All you need is a good internet connection and you are all set.
* Try to build TF from sources by changing CPU optimization flags.

*Please let us know if this helps.*

**Comment by amahendrakar** [comment] 2020-04-02 04:26
@mekhaaa,
Could you please check [this](https://github.com/tensorflow/tensorflow/issues/36167#issuecomment-577886156) comment on a similar issue and let us know if it helps. Thanks!

**Comment by mekhaaa** [comment] 2020-04-02 15:55
i am creating tfrecords by running this command: 
python generate_tfrecord.py --csv_input=data\train_labels.csv --image_dir=images\train --output_path=train.record 
but it didn't work

**Comment by amahendrakar** [comment] 2020-04-03 17:12
@mekhaaa,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here along with the supporting files and also the TensorFlow version you are using.

Also, please check if you are able to run the below code snippet 
```
import tensorflow as tf
floating = tf.Variable(3.14159265359, tf.float64)
```

Thanks!

**Comment by amahendrakar** [comment] 2020-04-10 14:06
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-20 06:00
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-20 06:00 UTC
Labels: stat:awaiting response, subtype:windows, type:build/install
