### ISSUE TITLE
WARNING:tensorflow:Entity <bound method Customized_DenseLayer.call of <__main__.Customized_DenseLayer object at 0x00000262A54DA488>> could not be transformed and will be executed as-is.

### ISSUE THREAD

**Issue by sakurakatana** [tensorflow/tensorflow#34271] opened 2019-11-14 12:50 UTC
TensorFlow installed from binary
TensorFlow version 2.0.0
Python version 3.7.4
Cuda compilation tools, release 10.0, V10.0.130
cudnn version 7.6.4
GPU model and memory: GTX1060 6G

**Code to reproduce the issue**
class Customized_DenseLayer(tf.keras.layers.Layer):
    def __init__(self, units, activation = None, **kwargs):
        self.units = units
        self.activation = tf.keras.layers.Activation(activation)
        super(Customized_DenseLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.kernel = self.add_weight(name = 'kernel',
                                      shape = (input_shape[-1], self.units),
                                      dtype = tf.float32,
                                      initializer = 'uniform',
                                      trainable = True)
        self.bias = self.add_weight(name = 'bias',
                                    shape = (self.units,),
                                    dtype = tf.float32,
                                    initializer = 'zeros',
                                    trainable = True)
        super(Customized_DenseLayer, self).build(input_shape)

    def call(self, inputs):
        return self.activation(inputs @ self.kernel + self.bias)

housing = fetch_california_housing()
x_train_all, x_test, y_train_all, y_test = train_test_split(
    housing.data, housing.target, random_state = 7)
x_train, x_valid, y_train, y_valid = train_test_split(
    x_train_all, y_train_all, random_state = 11)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_valid_scaled = scaler.transform(x_valid)
x_test_scaled = scaler.transform(x_test)

print(x_train_scaled.shape, y_train.shape)
print(x_valid_scaled.shape, y_valid.shape)
print(x_test_scaled.shape, y_test.shape)
print(x_train_scaled.shape[1:])
print(x_train.shape[1:])

model = tf.keras.models.Sequential()
model.add(Customized_DenseLayer(units = 30, input_shape = (8, ), activation = 'relu'))
model.add(Customized_DenseLayer(units = 1))

print(model.summary())

**Other info / logs**
WARNING:tensorflow:Entity <bound method Customized_DenseLayer.call of <__main__.Customized_DenseLayer object at 0x00000262FB272888>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Unable to locate the source code of <bound method Customized_DenseLayer.call of <__main__.Customized_DenseLayer object at 0x00000262FB272888>>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code

**Comment by oanush** [comment] 2019-11-15 09:30
@sakurakatana ,
When tried running the given code i got the error 
`NameError: name 'fetch_california_housing' is not defined` can you please provide us the complete code to reproduce the error faced here?Thanks!

**Comment by sakurakatana** [comment] 2019-11-15 10:46
> @sakurakatana ,
> When tried running the given code i got the error
> `NameError: name 'fetch_california_housing' is not defined` can you please provide us the complete code to reproduce the error faced here?Thanks!

Complete code：
'''
@Author:   MaoZi_Sakura
@Contact:  zhang132412sakura@outlook.com
'''

'''
@Author:   MaoZi_Sakura
@Contact:  zhang132412sakura@outlook.com
'''

# %%
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import os, sys, time


#%%


class Customized_DenseLayer(tf.keras.layers.Layer):
    def __init__(self, units, activation = None, **kwargs):
        self.units = units
        self.activation = tf.keras.layers.Activation(activation)
        super(Customized_DenseLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.kernel = self.add_weight(name = 'kernel',
                                      shape = (input_shape[-1], self.units),
                                      dtype = tf.float32,
                                      initializer = 'uniform',
                                      trainable = True)
        self.bias = self.add_weight(name = 'bias',
                                    shape = (self.units,),
                                    dtype = tf.float32,
                                    initializer = 'zeros',
                                    trainable = True)
        super(Customized_DenseLayer, self).build(input_shape)

    def call(self, inputs):
        return self.activation(inputs @ self.kernel + self.bias)


# %%
housing = fetch_california_housing()
x_train_all, x_test, y_train_all, y_test = train_test_split(
    housing.data, housing.target, random_state = 7)
x_train, x_valid, y_train, y_valid = train_test_split(
    x_train_all, y_train_all, random_state = 11)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_valid_scaled = scaler.transform(x_valid)
x_test_scaled = scaler.transform(x_test)

print(x_train_scaled.shape, y_train.shape)
print(x_valid_scaled.shape, y_valid.shape)
print(x_test_scaled.shape, y_test.shape)
print(x_train_scaled.shape[1:])
print(x_train.shape[1:])

# %%

model = tf.keras.models.Sequential()
model.add(Customized_DenseLayer(units = 30, input_shape = (8, ), activation = 'relu'))
model.add(Customized_DenseLayer(units = 1))

print(model.summary())

# %%
model.compile(optimizer = tf.keras.optimizers.SGD(0.005), loss = 'mean_squared_error')

callbacks = [tf.keras.callbacks.EarlyStopping(min_delta = 0.01, patience = 5)]

history = model.fit(x_train_scaled, y_train, epochs = 100,
                    validation_data = (x_valid_scaled, y_valid),
                    callbacks = callbacks)

print(history.history)

# %%
pd.DataFrame(history.history).plot(figsize = (8, 5))
plt.grid(True)
plt.gca().set_ylim(0, 1)
plt.show()

result = model.evaluate(x_test_scaled, y_test)

**Comment by sakurakatana** [comment] 2019-11-15 10:51
At the same time, I encountered a similar problem again.

Other info / logs
WARNING:tensorflow:Entity <function <lambda> at 0x00000207ACE9BBF8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Unable to locate the source code of <function <lambda> at 0x00000207ACE9BBF8>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code

The code：

import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import os, sys, time

dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))
dataset = dataset.repeat(3).batch(7)
data = dataset.interleave(map_func = lambda x: tf.data.Dataset.from_tensor_slices(x),
                          cycle_length = 5,
                          block_length = 1)
for item in data:
    print(item)

**Comment by oanush** [comment] 2019-11-20 08:42
@sakurakatana ,
Hi,when tried running the given code I got  `TypeError: ('Keyword argument not understood:', 'units') `kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/d0d8cf9fc6b053c40b76463b88c5087b/34271.ipynb) of colab for reference. Thanks!

**Comment by sakurakatana** [comment] 2019-11-20 09:26
> @sakurakatana ,
> Hi,when tried running the given code I got `TypeError: ('Keyword argument not understood:', 'units') `kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/d0d8cf9fc6b053c40b76463b88c5087b/34271.ipynb) of colab for reference. Thanks!

In the previous code, part of the content I copied incorrectly. I'm so sorry about that. I hope you can test it again. Thanks!

the code:
`# %%
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import os, sys, time

# %%
class Customized_DenseLayer(tf.keras.layers.Layer):
    def __init__(self, units, activation = None, **kwargs):
        self.units = units
        self.activation = tf.keras.layers.Activation(activation)
        super(Customized_DenseLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.kernel = self.add_weight(name = 'kernel',
                                      shape = (input_shape[-1], self.units),
                                      dtype = tf.float32,
                                      initializer = 'uniform',
                                      trainable = True)
        self.bias = self.add_weight(name = 'bias',
                                    shape = (self.units,),
                                    dtype = tf.float32,
                                    initializer = 'zeros',
                                    trainable = True)
        super(Customized_DenseLayer, self).build(input_shape)

    def call(self, inputs):
        return self.activation(inputs @ self.kernel + self.bias)

# %%
housing = fetch_california_housing()
x_train_all, x_test, y_train_all, y_test = train_test_split(
    housing.data, housing.target, random_state = 7)
x_train, x_valid, y_train, y_valid = train_test_split(
    x_train_all, y_train_all, random_state = 11)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_valid_scaled = scaler.transform(x_valid)
x_test_scaled = scaler.transform(x_test)

#%%
model = tf.keras.models.Sequential()
model.add(Customized_DenseLayer(units = 30, input_shape = (8,), activation = 'relu'))
model.add(Customized_DenseLayer(units = 1))

print(model.summary())

model.compile(optimizer = tf.keras.optimizers.SGD(0.005), loss = 'mean_squared_error')

callbacks = [tf.keras.callbacks.EarlyStopping(min_delta = 0.01, patience = 5, verbose = 1)]

history = model.fit(x_train_scaled, y_train, epochs = 100,
                    validation_data = (x_valid_scaled, y_valid),
                    callbacks = callbacks, verbose = 1)

print(history.history)
#%%
pd.DataFrame(history.history).plot(figsize = (8, 5))
plt.grid(True)
plt.gca().set_ylim(0, 1)
plt.show()

result = model.evaluate(x_test_scaled, y_test)`

**Comment by sakurakatana** [comment] 2019-11-20 09:48
@oanush,
Because I am not familiar with the way github text is edited, causing some code to change after uploading, resulting in code error. I'm so sorry about that. I hope you can test it again, Thanks!

the new code：
```
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import os, sys, time


class Customized_DenseLayer(tf.keras.layers.Layer):
    def __init__(self, units, activation = None, **kwargs):
        self.units = units
        self.activation = tf.keras.layers.Activation(activation)
        super(Customized_DenseLayer, self).__init__(**kwargs)
    def build(self, input_shape):
        self.kernel = self.add_weight(name = 'kernel',
                                      shape = (input_shape[-1], self.units),
                                      dtype = tf.float32,
                                      initializer = 'uniform',
                                      trainable = True)
        self.bias = self.add_weight(name = 'bias',
                                    shape = (self.units,),
                                    dtype = tf.float32,
                                    initializer = 'zeros',
                                    trainable = True)
        super(Customized_DenseLayer, self).build(input_shape)
    def call(self, inputs):
        return self.activation(inputs @ self.kernel + self.bias)


housing = fetch_california_housing()
x_train_all, x_test, y_train_all, y_test = train_test_split(
    housing.data, housing.target, random_state = 7)
x_train, x_valid, y_train, y_valid = train_test_split(
    x_train_all, y_train_all, random_state = 11)

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_valid_scaled = scaler.transform(x_valid)
x_test_scaled = scaler.transform(x_test)

model = tf.keras.models.Sequential()
model.add(Customized_DenseLayer(units = 30, input_shape = (8,), activation = 'relu'))
model.add(Customized_DenseLayer(units = 1))

print(model.summary())

model.compile(optimizer = tf.keras.optimizers.SGD(0.005), loss = 'mean_squared_error')

callbacks = [tf.keras.callbacks.EarlyStopping(min_delta = 0.01, patience = 5, verbose = 1)]

history = model.fit(x_train_scaled, y_train, epochs = 100,
                    validation_data = (x_valid_scaled, y_valid),
                    callbacks = callbacks, verbose = 1)

print(history.history)

pd.DataFrame(history.history).plot(figsize = (8, 5))
plt.grid(True)
plt.gca().set_ylim(0, 1)
plt.show()

result = model.evaluate(x_test_scaled, y_test)
```

**Comment by oanush** [comment] 2019-11-26 13:34
@sakurakatana ,
When tried executing the given code I did not face any error, kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/fd40435368099ac1ccfb9acc1a0b9f68/34271.ipynb) of the colab.Thanks!

**Comment by oanush** [comment] 2019-12-03 10:47
@sakurakatana ,
Any update on the issue ?Thanks!

**Comment by oanush** [comment] 2019-12-09 10:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-12-09 10:25 UTC
Labels: TF 2.0, comp:keras, type:support
