### ISSUE TITLE
profiler add_step make import_meta_graph error

### ISSUE THREAD

**Issue by hxsnow10** [tensorflow/tensorflow#20337] opened 2018-06-27 09:13 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Centos 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 
- **Python version**: 
tf.VERSION = 1.8.0
tf.GIT_VERSION = v1.8.0-0-g93bc2e2072
tf.COMPILER_VERSION = v1.8.0-0-g93bc2e2072
- **GPU**：**as i test, （gpu-tf, gpu-sess）or (cpu-tf,cpu-sess)，    this error will always occur.**

### Produce
1. prepare data
cp ner_data /ceph_ai/xiahong/data/ -rf
2. python train.py -i example_configs/ner_config.py
notice MODEL_PATH
3. test follow 2 commands
-* python predict.py -i {MODEL_PATH}-0
-* python predict.py -i {MODEL_PATH}-34   (should fail load model if run add step, else works)

comments train.py 86 "profiler.add_step(step=step, run_meta=run_metadata)" and try 2,3 again.

### Describe the problem
after run profiler add_step, 
the saver.save file cannot import_meta_graph 

### Source code / logs
```
Traceback (most recent call last):
  File "predict.py", line 126, in <module>
    tag_model=Classifier(args.model_path)
  File "predict.py", line 50, in __init__
    self.tf_model=TFModel(sess,model_path,inputs,outputs)
  File "/dockerdata/xiahong/tf_text_modeling-master/text_modeling/tf_utils/predict.py", line 8, in __init__
    saver = tf.train.import_meta_graph("{}.meta".format(model_path), clear_devices=True)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1955, in import_meta_graph
    **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 743, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 493, in import_graph_def
    raise ValueError(str(e))
ValueError: Can not squeeze dim[1], expected a dimension of 1, got 200 for 'cond_2/Squeeze' (op: 'Squeeze') with input shapes: [500,200,19].
```
 without train.py line 86, it works well.

[ner_data.zip](https://github.com/tensorflow/tensorflow/files/2140517/ner_data.zip)
[text_modeling.zip](https://github.com/tensorflow/tensorflow/files/2140519/text_modeling.zip)

**Comment by tensorflowbutler** [comment] 2018-06-27 18:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by hxsnow10** [comment] 2018-07-02 06:08
@tensorflowbutler related-info had been added.

**Comment by tensorflowbutler** [comment] 2018-08-01 18:54
Nagging Assignee @cy89: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cy89** [comment] 2018-08-10 23:51
@hxsnow10 is predict.py your code? If so, could you please provide it?

**Comment by tensorflowbutler** [comment] 2018-08-31 08:06
It has been 20 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-15 18:45
It has been 35 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-28 21:19
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 21:19 UTC
Labels: stat:awaiting response
