### ISSUE TITLE
GPU is idle even when there are operations ready to be executed

### ISSUE THREAD

**Issue by xilenteyex** [tensorflow/tensorflow#25724] opened 2019-02-13 18:09 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.1 LTS
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12.0
- Python version: Python 2.7.15rc1
- Bazel version (if compiling from source): 0.21
- GCC/Compiler version (if compiling from source): (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: 10.0/7.4.2
- GPU model and memory: NVIDIA Corporation GP100GL [Tesla P100 PCIe 12GB] (2 GPUs)

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
I am running a toy matrix multiplication example ([code here ](https://gist.github.com/xilenteyex/f569b0e0984808e1fb3a284c03b99984)and [timeline can be found here](https://gist.github.com/xilenteyex/c9565c20f32ea73383de96a484d6eae9)). If u look at the timeline, operations named **MatMul_1** and **MatMul_2** are placed on GPU1 while all other matrix multiplications are placed on GPU0. Operation named **MatMul_2** takes input from operations named **MatMul** and **MatMul_1**. **MatMul** and **MatMul_1** are completed almost at the same time while there is a large gap after completion of these operations before the execution of **MatMul_2** starts. I am not sure why is this gap there ? 

**Describe the expected behavior**
Expected behavior according to my understanding is that as soon as **MEMCPYPtoP** has completed (Op named **MatMul** is placed on GPU0), excution of MatMul_2 should be started. Is this a performance issue or am I missing something here ? 

**Code to reproduce the issue**
[toy_matmul code](https://gist.github.com/xilenteyex/f569b0e0984808e1fb3a284c03b99984)

**Other info / logs**
[timeline for toy_matmul](https://gist.github.com/xilenteyex/c9565c20f32ea73383de96a484d6eae9)
Following is the snapshot of the timeline using chrome-tracing visualizer.
![screen shot 2019-02-13 at 1 02 32 pm](https://user-images.githubusercontent.com/10864603/52733046-b4b37780-2f8f-11e9-9ab3-1ea51c7e2e14.png)

**Comment by guptapriya** [comment] 2019-02-18 08:49
Un-assigning myself as this does not seem related to distribution strategy. Perhaps someone on the GPU team can look into it.

**Comment by qqfish** [comment] 2019-02-27 00:40
Can it be reproduced? I tried your script on GCE and it is executed as you expected
![image](https://user-images.githubusercontent.com/1269299/53456952-391ce600-39e5-11e9-9d33-b11c35e87585.png)

**Comment by xilenteyex** [comment] 2019-02-27 14:45
In this execution, it looks like [this control dependency ](https://gist.github.com/xilenteyex/f569b0e0984808e1fb3a284c03b99984#file-toy_matmul_cdep-py-L37)is ignored. Not sure why. Can you please explain this behavior ?
Thanks!

**Comment by qqfish** [comment] 2019-03-06 01:54
Sorry for delay.

First for the control dependency, I think it is expected. The control dependency is created on placeholder. When you call session.run, you already fulfilled the placeholder. So the ops depends on it is ready to run as well. 

To fix it, you should move line 38 and 41 out from the control_dependency context.

And back to the original issue, it is actually caused by the profiler. In order to record the runtime of each kernel, our profiler calls cuCtxSynchronize to synchronize CPU and GPU. Unfortunately, right now we call this on the main thread, which blocks scheduling. This issue should go away if you turn off profiling.

We have an experimental feature that create private threads for scheduling, which can fix this issue as well. To turn it on, you need to set two environment variable before executing tf:
`
export TF_GPU_THREAD_MODE=gpu_private
export TF_GPU_THREAD_COUNT=2
`

This is the timeline I generated after setting these two variables:
![image](https://user-images.githubusercontent.com/1269299/53850261-73e7c680-3f6f-11e9-91db-4bcbb887ff1c.png)

**Comment by qqfish** [comment] 2019-03-06 19:45
I am still investigating the gap between MatMul and memcpy.

**Comment by xilenteyex** [comment] 2019-03-06 21:41
Hi @qqfish thanks for your input. I moved the lines outside the control_dependency context and set the environment variables as you suggested. It appears to be working fine for me now (Not sure why are you still seeing a gap in your execution) as shown in the timeline below:
[timeline JSON file can be found here](https://gist.github.com/xilenteyex/d6606ddcb7a6bc3edba95d1e531cf403)
[Updated toy_matmul_code can be found here](https://gist.github.com/xilenteyex/47c0810ec447d87f26cf3ce419f6efb8)



![image](https://user-images.githubusercontent.com/10864603/53915020-069a6b00-402d-11e9-9ab4-bd59a952e6c2.png)

 
Next step for my use-case is to try similar settings for larger real models e.g. [RRNLM (Recurrent Neural Network for Language Modeling)](https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb), [Inception, ResNet etc.](https://github.com/tensorflow/models/tree/master/research/slim) Do you think these environment variable settings are safe to use for those bigger and more complicated control flow graphs as well ?

**Comment by qqfish** [comment] 2019-03-07 19:09
Yes, it should be safe. We may turn this feature on by default recently.

Previous we use one thread on GPU to compute CPU ops and schedule kernels on GPU. These variables create a private scheduling thread for each GPU. Then we don't need to do everything in one thread.

There are two gap in the original timeline: (1) between MatMul and MemCPYPtoP (2) between MemCPYPtoP and MatMul_2. The environment variables should address gap (2). However, (1) is non-deterministic

I am working on a fix to address (1).

**Comment by xilenteyex** [comment] 2019-03-08 06:42
Hi @qqfish 
for variable `TF_GPU_THREAD_COUNT`. Value should be equal to number of GPUs or it should always be 2 ?
Also, after setting both the environment variables, for execution on my local machine 'both the gaps' [(1) and (2) in your last comment] are gone, but not for your case ?
Do you think for me GAP has disappeared by chance ? Like it may appear if I try to run the same thing again  or try to run a different example ?

**Comment by qqfish** [comment] 2019-03-08 21:28
If you set `TF_GPU_THREAD_MODE=gpu_private` then `TF_GPU_THREAD_COUNT` should always be 2. It means each GPU will have 2 private threads to launch ops. 

Yes, I think gap (1) disappear in your case by change. If you rerunning the same thing, it will not appear. But the gap may appear again if running a different example.

**Comment by xilenteyex** [comment] 2019-03-08 22:23
@qqfish Thanks for the explanation. I will wait for your fix then before I try the other larger models. If I can be helpful in anyway, let me know.
Thanks!

**Comment by qqfish** [comment] 2019-03-14 00:00
Fixing this issue requires a much bigger change than I originally thought. I cannot find a easy workaround works for all cases. This may require to re-design op scheduling of TF to fully support this kind of fine-grained dependency.

The good news is, someone in our team has already started working on fine-grained dependency support. But it may take a while.

**Comment by xilenteyex** [comment] 2019-03-14 00:14
@qqfish Thanks for the update. Do we know approximately how much time will it take ?

Regards,
Ubaid

**Comment by qqfish** [comment] 2019-03-14 01:04
I am not sure as well. It is part of a larger project that is still in its early stage. So please stay tuned.

**Comment by xilenteyex** [comment] 2019-04-03 19:20
any updates ?

**Comment by qqfish** [comment] 2019-04-05 01:30
Sorry, not much yet. We are still working on it.

**Comment by xilenteyex** [comment] 2019-05-13 19:40
Just checking if there are any updates yet?

**Comment by jw447** [comment] 2019-07-19 18:10
Can someone explain why TF_GPU_THREAD_COUNT should be 2 when gpu_thread_mode is private? Why not larger numbers?

Also, how about when thread_mode is shared? Shall I have larger TF_GPU_THREAD_COUNT be larger? 

Thanks!

**Comment by haoyuz** [comment] 2019-07-19 19:04
> Can someone explain why TF_GPU_THREAD_COUNT should be 2 when gpu_thread_mode is private? Why not larger numbers?

When `TF_GPU_THREAD_MODE` is set to `gpu_private`, then `TF_GPU_THREAD_COUNT` is the number of threads **per GPU** for kernel launching. For some reference / benchmark models we find using 1 or 2 threads per GPU perform well. You can customize it to larger numbers, but be aware of contention if the total number of GPU private threads, data processing threads, and other CPU computation threads.

> Also, how about when thread_mode is shared? Shall I have larger TF_GPU_THREAD_COUNT be larger?

When set to shared, it will be the total number of threads for kernel launching on all GPUs. It's supposed to be a larger number (for example, 2 * num_gpus).

**Comment by jw447** [comment] 2019-07-19 21:00
Hi @Haoyuz, 

Thanks. Is this TF_GPU_THREAD_COUNT thread pool for computation? I'm not very familiar with tensorflow runtime, when you said "kernel launching", do you mean a single GPU can only use 2 threads for computation?

**Comment by haoyuz** [comment] 2019-07-19 21:36
> Is this TF_GPU_THREAD_COUNT thread pool for computation?

Thread pool is for CPU, and this number is controlling how many CPU threads you want to schedule GPU kernels. You do not have to worry about the number of "threads" on GPU (technically GPU has different concepts controlling different levels of parallelism, and a single GPU stream running ops with a large enough batch size can usually saturate the GPU).

**Comment by xilenteyex** [comment] 2019-08-08 19:43
@qqfish, just checking, any updates yet ?

**Comment by qqfish** [comment] 2019-08-08 19:50
Sorry, there is still not much yet. I think you shouldn't be blocked by this issue.

**Comment by xilenteyex** [comment] 2019-08-12 18:32
Hi @qqfish,
I am trying to create a framework for speeding up TensorFlow programs using model parallelism. When one of the GPUs stays idle for sometime even when there are operations ready to be executed, performance improvement is not as expected and is sometimes worse than the CPU, negatively impacting the performance of my framework.
If you can share a temporary workaround for now. That will be helpful as well.
Thanks!

**Comment by qqfish** [comment] 2019-08-14 16:48
First, I think `TF_GPU_THREAD_MODE` is good enough. In our multi-gpu benchmark, we don't see any performance issues causing by this.

If you find any gap causing by this issue in timeline, I think you can use control dependency to work it around. You can add a tf.Identity with control dependency to make sure the Memcpy is scheduled before other heavy gpu ops.

**Comment by xilenteyex** [comment] 2019-08-19 17:24
@qqfish, Can you please elaborate this? I am not an expert in TensorFlow yet, sorry :( .
(If you can give a small toy example that will help a lot!)

> If you find any gap causing by this issue in timeline, I think you can use control dependency to work it around. You can add a tf.Identity with control dependency to make sure the Memcpy is scheduled before other heavy gpu ops.

Thanks!

**Comment by qqfish** [comment] 2019-08-19 19:26
Let say you have a graph like this:

```
with tf.device('cpu:0'):
  X0 = tf.random_uniform([dim, dim], 0, 10)

with tf.device('gpu:0'):
  Y0 = tf.matmul(X0, X0)

with tf.device('gpu:1'):
  X1 = tf.random_uniform([dim, dim], 0, 10)
  with tf.control_dependencies([X0]):
    Y1 = tf.matmul(X1, X1)
```

If you notice memory copy is execute after `Y1` on gpu, you can work around by adding following control dependency:

```
with tf.device('cpu:0'):
  X0 = tf.random_uniform([dim, dim], 0, 10)
  X0_ = tf.identity(X0)

with tf.device('gpu:0'):
  Y0 = tf.matmul(X0, X0)

with tf.device('gpu:1'):
  X1 = tf.random_uniform([dim, dim], 0, 10)
  with tf.control_dependencies([X0_]):
    Y1 = tf.matmul(X1, X1)
```

or:
```
with tf.device('cpu:0'):
  X0 = tf.random_uniform([dim, dim], 0, 10)

with tf.device('gpu:0'):
  Y0 = tf.matmul(X0, X0)

with tf.device('gpu:1'):
  with tf.control_dependencies([X0]):
    X1 = tf.random_uniform([dim, dim], 0, 10)
    Y1 = tf.matmul(X1, X1)
```
But like I said, it is a very rare issue, you don't need to worry about it too much.

**Comment by sanjoy** [comment] 2020-01-02 18:12
Closing as per https://github.com/tensorflow/tensorflow/issues/25724#issuecomment-522719673: this is a rare issue that has a workaround.

**Closed by sanjoy** 2020-01-02 18:12 UTC
Labels: comp:gpu, stat:ds-triaged, type:bug
