### ISSUE TITLE
tf.numpy_function throws error when encounter np.transpose

### ISSUE THREAD

**Issue by SumNeuron** [tensorflow/tensorflow#31235] opened 2019-08-01 13:11 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): kinda
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04LTS Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/a
- TensorFlow installed from (source or binary): conda forge
- TensorFlow version (use command below): 1.14.0
- Python version: 2.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 9
- GPU model and memory: Quadrao 16GB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to move some of Keras's image [transformation functions](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/affine_transformations.py) into my dataset constructor function, e.g. 

```python
# inside my function that makes a dataset
filenames = [...]

preprocess_fn = lambda p: preprocess_image(p, some, default, arguments)

# workaround as shown by @mrry in https://github.com/tensorflow/tensorflow/issues/12396
tf_preproc_fn = lambda p: tf.numpy_function(preprocess_fn, [p], tf.float32)

path_ds = tf.data.Dataset.from_tensor_slices(fullpaths)
imgs_ds = path_ds.map(tf_preproc_fn, num_parallel_calls=AUTOTUNE)


```
where  at somepoint in `preprocess_fn` `np.rollaxis` is called, which in turns calls `np.transpose`. this throws:

```

  File "/home/user/anaconda3/envs/tf/lib/python3.6/site-packages/numpy/core/numeric.py", line 1554, in rollaxis
    return a.transpose(axes)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'transpose'


	 [[{{node PyFunc}}]] [Op:IteratorGetNextSync]
```

**Describe the expected behavior**

That `tf.numpy_function` just "works". Already had to use `tf.cast(tensor.shape[0], tf.float32)` to prevent some errors.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```python
# from keras
def apply_channel_shift(x:list, intensity:float, channel_axis:int=0)->list:
    '''
    Performs a channel shift.

    Arguments
        x (np.ndarray): Input tensor. Must be 3D.
        intensity (float): Transformation intensity.
        channel_axis (int): Index of axis for channels in the input tensor.

    Returns
        Numpy image tensor.
    '''
    x = np.rollaxis(x, channel_axis, 0)
    min_x, max_x = np.min(x), np.max(x)
    channel_images = [
        np.clip(x_channel + intensity,
                min_x,
                max_x)
        for x_channel in x]
    x = np.stack(channel_images, axis=0)
    x = np.rollaxis(x, 0, channel_axis + 1)
    return x

_fn = lambda img_tnsr : apply_channel_shift(img_tnsr, 1, 3)
tf_fn = tf.numpy_function(lambda i: _fn(i), [i], [tf.float32])

path_ds.map(tf_fn)
```
**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2019-08-02 09:23
@SumNeuron 

In order to expedite the trouble-shooting process, please provide full code snippet to reproduce it on our environment.Thanks

**Comment by SumNeuron** [comment] 2019-08-02 11:39
@ravikyram ask and you shall receive, link to colab where you can recreate the error:

https://colab.research.google.com/drive/1TDYeqKE16jcAdnAAeFT4KYyESisizibq

**Comment by ravikyram** [comment] 2019-08-02 13:52
I have tried on colab with TF version 1.14 ,TF-nightly and 2.0.0.dev20190731 was able to reproduce the issue. Please, find the [gist](https://colab.research.google.com/drive/1a_GykZMBHIn7wE9O4lKOvPmzOUIL0My_) here.Thanks!

**Comment by meysamsadeghi** [comment] 2019-11-29 12:32
Is there any update/solution on this?

**Comment by jvishnuvardhan** [comment] 2020-05-30 06:16
@SumNeuron Sorry for missing this issue. I ran it with `TF1.15.3` and I cannot reproduce the issue. I think it was resolved in recently updated `TF1.15.3`. PTAL at this [gist](https://colab.research.google.com/gist/jvishnuvardhan/b920183b618e9f91e3866fdeb51ae7d0/tf-issue-31235.ipynb). Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Closed** 2020-06-13 07:09 UTC
Labels: TF 1.14, comp:ops, stalled, stat:awaiting response, type:bug
