### ISSUE TITLE
`tf.keras.layers.Bidirectional` does not work under eager execution mode

### ISSUE THREAD

**Issue by huan** [tensorflow/tensorflow#23299] opened 2018-10-26 15:49 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X 10.12.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): BINARY
- TensorFlow version (use command below): v1.12.0-rc0-17-g7b08198113 1.12.0-rc1
- Python version: 3.6.5
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**

A very simple model with `Bidirectional` layer will stop work after we enable the eager execution mode.

**Describe the expected behavior**

Code should work with eager execution mode.

**Code to reproduce the issue**

The following code will be able to reprorduce this problem:

```py
import tensorflow as tf
import numpy as np

tf.enable_eager_execution()

x = tf.keras.layers.Input(shape=(2, 1))
y = tf.keras.layers.Bidirectional(
    tf.keras.layers.LSTM(1, return_state=True)
)(x)

model = tf.keras.Model(inputs=x, outputs=y)

data = np.array([0.1, 0.2]).reshape((1, -1, 1))
print(model.predict(data))
```
However, if we comment out the `tf.enable_eager_execution()`, then it will work as expected:

**Other info / logs**

The error message(with eager execution enabled) is:

```
Traceback (most recent call last):
  File "src/t.py", line 11, in <module>
    )(x)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/layers/wrappers.py", line 473, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 769, in __call__
    output_shapes = self.compute_output_shape(input_shapes)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 149, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/layers/wrappers.py", line 444, in compute_output_shape
    input_shape).as_list())
AttributeError: 'list' object has no attribute 'as_list'
```

After we disable the eager execution, then the above code works as expected.

```
[array([[0.01535364, 0.04371894]], dtype=float32), array([[0.01535364]], dtype=float32), array([[0.03121366]], dtype=float32), array([[0.04371894]], dtype=float32), array([[0.09061633]], dtype=float32)]
```

**Comment by zixia** [comment] 2018-10-26 18:09
### Update

It's related with the following code:

https://github.com/tensorflow/tensorflow/blob/47c84f6053faebf0c9e3b5fb54da315e89ad37ec/tensorflow/python/keras/layers/wrappers.py#L223-L224

When in eager execution mode, the `child_input_shape` is a `list` already.

**Comment by feihugis** [comment] 2018-11-01 23:43
@zixia @alextp I submitted a [PR](https://github.com/tensorflow/tensorflow/pull/23441) to fix this issue. Could you help review it?

**Comment by zixia** [comment] 2018-11-02 00:06
@feihugis awesome, it seems should work. 

LGTM, and thank you very much!

**Comment by qlzh727** [comment] 2018-11-19 17:16
Hi @zixia, I think the issue has been recently fixed on tensorflow side, and I cannot reproduce the error with latest nightly build.

Can u try "pip install -U tf-nightly" or "pip install -U tf-nightly-gpu" to verify that the error has been fixed?

**Comment by zixia** [comment] 2018-11-20 08:12
@qlzh727 Thank you for pointing out that, I can confirm that this issue had been fixed with the `tensorflow/tensorflow:nightly-devel-gpu-py3` docker image.

I think we have another repository inside Google and the latest code is not synced with GitHub in time, am I right?

If so, I'd like to suggest that we should keep them automatic in sync so that we can see the latest code.

Have a nice day!

**Comment by qlzh727** [comment] 2018-11-20 17:18
Hi @huan, the repository within google is fully synced with github. The issue here is the fix is only available in the latest nightly and has not reach the release yet.

**Closed** 2018-11-20 17:19 UTC
Labels: comp:eager, type:bug/performance

**Comment by huan** [comment] 2018-11-21 01:38
@qlzh727 It's great that we had fully synced. Thanks for the clarification!
