### ISSUE TITLE
Casting from float32 to uint8 results in wrong value despite being from 0 to 255

### ISSUE THREAD

**Issue by py4** [tensorflow/tensorflow#38381] opened 2020-04-09 08:52 UTC
I'm using tensorflow-gpu 1.14 with Cuda 10 on Ubuntu 18.04. I'm running tf in **eager mode**.

I'm training a model using Trax. In my input processing pipeline, I read a batch of uint8 images (3-channel each value from 0 to 255) and resize them using `tf.image.resize_images` which results in `float32` but values are still from 0 to 255. Then I cast the `float32` values to `uint8` :

```
 print("==================")
 print("0,0,0 before cast:  ", image_target_before_cast[0][0][0])
 image_target = tf.cast(image_target_before_cast, dtype=tf.dtypes.uint8)
 print("0,0,0 after cast:  ", image_target[0][0][0])
 print("==================")
```

 On first batch of data (16 prints but i'm bringing only one of them) everything is fine:
```
==================
0,0,0 before cast:   tf.Tensor(146.21089, shape=(), dtype=float32)
0,0,0 after cast:   tf.Tensor(146, shape=(), dtype=uint8)
==================
```

Now here is the weird part. From the second batch of images the problem happens:
```
==================
0,0,0 before cast:   tf.Tensor(139.61038, shape=(), dtype=float32)
0,0,0 after cast:   tf.Tensor(115, shape=(), dtype=uint8)
==================
```

I also tried to conver the tensor to numpy array and then cast it using ` image_target_before_cast[0][0][0].numpy().astype(np.uint8)` and it worked. But still don't know what is wrong with the tf cast.

Any idea what might be the issue?

**Comment by Saduf2019** [comment] 2020-04-09 10:43
@py4 
please provide us with a simple stand alone ode for us to replicate the issue.

please refer to this [link](https://stackoverflow.com/questions/46689428/convert-np-array-of-type-float64-to-type-uint8-scaling-values) for reference #[link2](https://github.com/tensorflow/tensorflow/issues/19691)

**Comment by py4** [comment] 2020-04-09 23:05
@Saduf2019 It's in the middle of a project. I think I cannot provide a stand alone code to replicate issue...
I already had seen those links but I'm not using `convert_image_dtype` to scale the values. the `image_target_before_cast` is a float32 and all elements are between 0 to 255. So I expect to `tf.cast` to be able to cast to `uint8` properly.

**Comment by jvishnuvardhan** [comment] 2020-04-13 17:16
@py4 Standalone code helps us to resolve the issue faster. May be you can use some public data to demonstrate the issue. I tried to mimic your issue with `tf.cast` and I don't see any issue. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/b79a6df14e95f8619dfae0912e16f578/untitled82.ipynb). 

Can you please play with the gist and update it to reproduce your issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-04-19 17:49
@py4 Can you please verify and close if this was resolved for you. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-04-26 20:20
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2020-04-26 20:20 UTC
Labels: TF 1.14, comp:ops, stalled, stat:awaiting response, type:bug
