### ISSUE TITLE
Cannot get model to work

### ISSUE THREAD

**Issue by JSunRae** [tensorflow/tensorflow#37220] opened 2020-03-02 05:50 UTC
It currently fails when trying to fit the model. The 'train_ds' seems to cause it to fail because it is a Batchdataset and not a numpty array. When I convert this to an np.array it fails because it is expecting a "dense_1_input to have 2 dimensions, but got array with shape ()". but I have no idea what this means.

`from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

from tensorflow import keras

from keras import layers
from keras import regularizers

#maybe not needed
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers import LSTM

import tensorflow_docs as tfdocs
import tensorflow_docs.modeling
import tensorflow_docs.plots

from  IPython import display
from matplotlib import pyplot as plt

import numpy as np

import pathlib
import shutil
import tempfile

logdir = pathlib.Path(tempfile.mkdtemp())/"tensorboard_logs"
shutil.rmtree(logdir, ignore_errors=True)

gz = tf.keras.utils.get_file('HIGGS2.csv.gz', 'https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz')

FEATURES = 28

ds = tf.data.experimental.CsvDataset(gz,[float(),]*(FEATURES+1), compression_type="GZIP")

def pack_row(*row):
  label = row[0]
  features = tf.stack(row[1:],1)
  return features, label

packed_ds = ds.batch(10000).map(pack_row).unbatch() #think this does (none, none) but not sure what this means

for features,label in packed_ds.batch(1000).take(1):
  print(features[0])
  plt.hist(features.numpy().flatten(), bins = 101)
print(features[0].shape)

N_VALIDATION = int(1e3)
N_TRAIN = int(1e4)
BUFFER_SIZE = int(1e4)
BATCH_SIZE = 500
STEPS_PER_EPOCH = N_TRAIN//BATCH_SIZE

validate_ds = packed_ds.take(N_VALIDATION).cache()
train_ds = packed_ds.skip(N_VALIDATION).take(N_TRAIN).cache()

print(train_ds)

validate_ds = validate_ds.batch(BATCH_SIZE)
#validate_ds = np.array(validate_ds) #model.fit expects x and y to be numpy array. Seems like you pass a list, it tried to get shape of input by reading ndim attribute of numpy array and failed
train_ds = train_ds.shuffle(BUFFER_SIZE).repeat().batch(BATCH_SIZE)
#train_ds = np.array(train_ds) #model.fit expects x and y to be numpy array. Seems like you pass a list, it tried to get shape of input by reading ndim attribute of numpy array and failed

print(train_ds)

lr_schedule = tf.keras.optimizers.schedules.InverseTimeDecay(
  0.001,
  decay_steps=STEPS_PER_EPOCH*1000,
  decay_rate=1,
  staircase=False)

def get_optimizer():
  return tf.keras.optimizers.Adam(lr_schedule)

step = np.linspace(0,100000)
lr = lr_schedule(step)
plt.figure(figsize = (8,6))
plt.plot(step/STEPS_PER_EPOCH, lr)
plt.ylim([0,max(plt.ylim())])
plt.xlabel('Epoch')
_ = plt.ylabel('Learning Rate')
#plt.show(block=True)

def get_callbacks(name):
  return [
    tfdocs.modeling.EpochDots(),
    keras.callbacks.EarlyStopping(monitor='val_binary_crossentropy', patience=200),
    keras.callbacks.TensorBoard(logdir/name),
  ]
def compile_and_fit(model, name, optimizer=None, max_epochs=10000):
  if optimizer is None:
    optimizer = get_optimizer()
  model.compile(optimizer=optimizer,
                loss=keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=[
                  keras.losses.BinaryCrossentropy(
                      from_logits=True, name='binary_crossentropy'),
                  'accuracy'])

  model.summary()
  
  history = model.fit(
    np.array(train_ds), #model.fit expects x and y to be numpy array. Seems like you pass a list, it tried to get shape of input by reading ndim attribute of numpy array and failed
    steps_per_epoch = STEPS_PER_EPOCH,
    epochs=max_epochs,
    validation_data=validate_ds,
    callbacks=get_callbacks(name),
    verbose=0)
  return history

size_histories = {}

plotter = tfdocs.plots.HistoryPlotter(metric = 'binary_crossentropy', smoothing_std=10)
#plotter.plot(size_histories)
#plt.ylim([0.5, 0.7])

small_model = Sequential([
    # `input_shape` is only required here so that `.summary` works.
    layers.Dense(16, activation='elu', input_shape=(28,)),
    layers.Dense(16, activation='elu'),
    layers.Dense(1)
])

size_histories['Small'] = compile_and_fit(small_model, 'sizes/Small')`

raceback (most recent call last):
  File "/Users/jasonrae/.vscode/extensions/ms-python.python-2020.3.64983-dev/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/Users/jasonrae/.vscode/extensions/ms-python.python-2020.3.64983-dev/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/Users/jasonrae/.vscode/extensions/ms-python.python-2020.3.64983-dev/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jasonrae/Documents/Python Files/Higgs1.py", line 145, in <module>
    size_histories['Small'] = compile_and_fit(small_model, 'sizes/Small')
  File "/Users/jasonrae/Documents/Python Files/Higgs1.py", line 120, in compile_and_fit
    verbose=0)
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training.py", line 1154, in fit
    batch_size=batch_size)
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training_utils.py", line 135, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected dense_1_input to have 2 dimensions, but got array with shape ()
Exception ignored in: <function _MemoryCacheDeleter.__del__ at 0x13e9554d0>
Traceback (most recent call last):
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2944, in __del__
AttributeError: 'NoneType' object has no attribute 'device'
Exception ignored in: <function _MemoryCacheDeleter.__del__ at 0x13e9554d0>
Traceback (most recent call last):
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 2944, in __del__
AttributeError: 'NoneType' object has no attribute 'device'
Exception ignored in: <function _RandomSeedGeneratorDeleter.__del__ at 0x13e9557a0>
Traceback (most recent call last):
  File "/Users/jasonrae/opt/miniconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3009, in __del__
AttributeError: 'NoneType' object has no attribute 'device'

**Comment by ravikyram** [comment] 2020-03-02 06:12
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 
Please, share colab link or simple standalone code with proper indentation to reproduce the issue in our environment. It helps us in localizing the issue faster.
Please, fill  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by JSunRae** [comment] 2020-03-02 08:25
Hi Ravikyram. No worries. Is this what you need?

== check python ===================================================
python version: 3.7.4
python branch: 
python build version: ('default', 'Aug 13 2019 15:17:50')
python compiler version: Clang 4.0.1 (tags/RELEASE_401/final)
python implementation: CPython


== check os platform ===============================================
os: Darwin
os kernel version: Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64
os release version: 19.3.0
os platform: Darwin-19.3.0-x86_64-i386-64bit
linux distribution: ('', '', '')
linux os distribution: ('', '', '')
mac version: ('10.15.3', ('', '', ''), 'x86_64')
uname: uname_result(system='Darwin', node='Jasons-MBP', release='19.3.0', version='Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64', machine='x86_64', processor='i386')
architecture: ('64bit', '')
machine: x86_64


== are we in docker =============================================
No

== compiler =====================================================
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

== check pips ===================================================
numpy                  1.18.1    
tensorflow-docs        0.0.0     

== check for virtualenv =========================================
False

== tensorflow import ============================================
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
-bash: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 7, 4, 'final', 0)

== bazel version  ===============================================

**Comment by JSunRae** [comment] 2020-03-02 08:28
Here is the code in txt:
[Higgs1.txt](https://github.com/tensorflow/tensorflow/files/4274220/Higgs1.txt)

**Comment by ravikyram** [comment] 2020-03-03 09:17
@JSunRae 

I have tried in colab with TF 2.1.0 and i am seeing `IndexError ` .Only change is I have replaced with tensorflow.keras in place of keras while importing.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/8a5eb39a0b42ab141b99df254b098702/untitled699.ipynb). Please, help me with reproducing the issue .Thanks!

**Comment by ravikyram** [comment] 2020-03-20 10:40
@JSunRae 

Any update on this issue please. Thanks!

**Comment by JSunRae** [comment] 2020-03-22 22:41
still having so many issues with getting it to run sorry. Its now saying

AttributeError: 'DatasetV1Adapter' object has no attribute 'unbatch'.

**Comment by ravikyram** [comment] 2020-03-23 03:29
@JSunRae 

Will it be possible to share the colab link or simple standalone code to reproduce the issue in our environment. It helps in localizing the issue for faster resolution.Thanks!

**Comment by ravikyram** [comment] 2020-04-03 11:11
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-04-03 11:11 UTC
Labels: TF 2.1, comp:keras, type:support
