### ISSUE TITLE
request to add DepthToSpace Spilt and conv2d_transpose operation in post training quantization(full integer quantization))

### ISSUE THREAD

**Issue by wujiexiaowugui** [tensorflow/tensorflow#38189] opened 2020-04-03 08:34 UTC
****System information****
-  Linux Ubuntu 16.04:
- TensorFlow installed from binary:
- TensorFlow version 1.15.0:

**Provide the text output from tflite_convert**

```
RuntimeError: Quantization not yet supported for op: SPLIT

```

**Comment by gadagashwini** [comment] 2020-04-03 10:07
@wujiexiaowugui, Could you share the standalone code to reproduce the reported issue. Thanks!

**Comment by wujiexiaowugui** [comment] 2020-04-03 10:48
> @wujiexiaowugui, Could you share the standalone code to reproduce the reported issue. Thanks!

import tensorflow.compat.v1 as tf
#Eager Mode is essential!
tf.enable_eager_execution()

import sys
import glob
if sys.version_info.major >= 3:
    import pathlib
else:
    import pathlib2 as pathlib
import random
import cv2
import numpy as np

tf.logging.set_verbosity(tf.logging.DEBUG)
pb_file='model.pb'
input_arrays=['net_input']
output_arrays=['net_output']
input_shapes=[1, 128, 128, 3]

sample_img_dir='/tmp'


converter =  tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file=pb_file,
                                                       input_arrays=input_arrays,
                                                       output_arrays=output_arrays,
                                                       input_shapes={input_arrays[0]:input_shapes})
converter.allow_custom_ops=True
tflite_model = converter.convert()

tflite_models_dir = pathlib.Path("./tmp/tflite_models/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)

tflite_model_file = tflite_models_dir/"model.tflite"
tflite_model_file.write_bytes(tflite_model)

tf.logging.set_verbosity(tf.logging.DEBUG)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

def preprocess_img(img):
    # preprocess
    img = cv2.resize(img, (128, 128))
    # FLOAT32
    img = img.astype(np.float32)
    # img=(img/128.)-1.
    img = img - 128.
    return img

def create_datastream_from_imgs(img_dir):

    img_path_list=glob.glob(img_dir+'/*.jpg')
    random.shuffle(img_path_list)
    img_path_list=img_path_list[:200]
    imgs_list=[]
    for path in img_path_list:
        img=cv2.imread(path)
        img=preprocess_img(img)
        imgs_list.append(img)
    imgs=np.stack(imgs_list,axis=0)
    return tf.data.Dataset.from_tensor_slices((imgs)).batch(1)


ds=create_datastream_from_imgs(sample_img_dir)

def representative_data_gen():
  for input_value in ds.take(20):
    yield [input_value]

converter.representative_dataset = representative_data_gen
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
tflite_quant_model = converter.convert()
tflite_model_quant_file = tflite_models_dir/"model_quant.tflite"
tflite_model_quant_file.write_bytes(tflite_quant_model)

**Comment by gadagashwini** [comment] 2020-04-08 06:51
@wujiexiaowugui, I tried reproducing the error but looks like some files are missing.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/dd4525cf55c01d33ac2313923ad38461/untitled491.ipynb) and provide the more information to reproduce the issue. Thanks

**Comment by wujiexiaowugui** [comment] 2020-04-08 08:47
> @wujiexiaowugui, I tried reproducing the error but looks like some files are missing.
> Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/dd4525cf55c01d33ac2313923ad38461/untitled491.ipynb) and provide the more information to reproduce the issue. Thanks

You can download the model in under link to replace model.pb.
http://mcml.yonsei.ac.kr/files/srzoo/eusr_x2.pb

The error is :
RuntimeError: Quantization not yet supported for op: **DepthToSpace**

**Comment by gadagashwini** [comment] 2020-04-14 12:14
@wujiexiaowugui, Please take a look at [gist](https://colab.sandbox.google.com/gist/gadagashwini/e131278e0fbf20345d4c026bf155a28b/untitled504.ipynb) and confirm the issue. Thanks

**Comment by wujiexiaowugui** [comment] 2020-04-16 03:11
> @wujiexiaowugui, Please take a look at [gist](https://colab.sandbox.google.com/gist/gadagashwini/e131278e0fbf20345d4c026bf155a28b/untitled504.ipynb) and confirm the issue. Thanks

if you use the "eusr_x2.pb" , the input_arrays=['sr_input']  and  output_arrays=['sr_output']

**Comment by Saduf2019** [comment] 2020-04-24 10:41
@wujiexiaowugui, 
as per above update, i ran the code shared, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/aa894a3b5b648efecd07e71c06cd738e/38189.ipynb)

**Comment by amahendrakar** [comment] 2020-04-29 07:11
@wujiexiaowugui,
Could you please add the below two lines to your code before converting the model.
```
converter.experimental_new_converter = True
converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 
```
I was able to convert the model without any issues after adding these lines. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/83cb6168fd3eff26bb8f92ef6d2685b4/38189.ipynb). Thanks!

**Comment by amahendrakar** [comment] 2020-05-06 04:43
@wujiexiaowugui,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-05-14 11:34
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by wujiexiaowugui** [comment] 2020-05-15 05:13
> @wujiexiaowugui,
> Any updates regarding this issue? Thanks!

When I added two lines to my code , there is another error occurred:
**RuntimeError: Unsupported output type UINT8 for output tensor 90 of type FLOAT32.**

**Comment by wujiexiaowugui** [comment] 2020-05-15 05:46
> @wujiexiaowugui,
> Could you please add the below two lines to your code before converting the model.
> 
> ```
> converter.experimental_new_converter = True
> converter.target_spec.supported_ops =[tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 
> ```
> 
> I was able to convert the model without any issues after adding these lines. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/83cb6168fd3eff26bb8f92ef6d2685b4/38189.ipynb). Thanks!

> Any updates regarding this issue? Thanks!

When I added two lines to my code , there is another error occurred:
**RuntimeError: Unsupported output type UINT8 for output tensor 90 of type FLOAT32.**

You can set "output_arrays=['DepthToSpace']". Then you will get the same error.
I think it is because that "DepthToSpace" layer still can't be quantized to int8.

**Comment by amahendrakar** [comment] 2020-05-15 09:03
> You can set "output_arrays=['DepthToSpace']". Then you will get the same error.
> I think it is because that "DepthToSpace" layer still can't be quantized to int8.

Was able to reproduce the issue with [TF v1.5](https://colab.research.google.com/gist/amahendrakar/e67f099245873bd8fdb117893c538942/38189.ipynb), [TF v2.2](https://colab.research.google.com/gist/amahendrakar/baa57e83ea6d1f881bf74445f2099944/38189-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/bbbd505f1f3687850022ee74b04f37ee/38189-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by wujiexiaowugui** [comment] 2020-05-15 09:17
> > You can set "output_arrays=['DepthToSpace']". Then you will get the same error.
> > I think it is because that "DepthToSpace" layer still can't be quantized to int8.
> 
> Was able to reproduce the issue with [TF v1.5](https://colab.research.google.com/gist/amahendrakar/e67f099245873bd8fdb117893c538942/38189.ipynb), [TF v2.2](https://colab.research.google.com/gist/amahendrakar/baa57e83ea6d1f881bf74445f2099944/38189-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/bbbd505f1f3687850022ee74b04f37ee/38189-tf-nightly.ipynb). Please find the attached gist. Thanks!

Yeah, I met the same issues when using TFv1.5, TFv2.2 and TF-nightly.
So, will you support this "DepthToSpace" op in later tensorflow version?

**Comment by jvishnuvardhan** [comment] 2020-05-15 13:48
@wujiexiaowugui One of the attribute(`block_size`) of `DepthToSpace` has dtype of `int64` which is not supported. Can you please change it to `int32` and create the .pb? Thanks!

**Comment by wujiexiaowugui** [comment] 2020-05-18 01:59
> @wujiexiaowugui One of the attribute(`block_size`) of `DepthToSpace` has dtype of `int64` which is not supported. Can you please change it to `int32` and create the .pb? [here](https://colab.research.google.com/gist/jvishnuvardhan/400b6fe933154506ea1183c5fba59051/38189-tf-nightly.ipynb) is a gist for our reference. Thanks!

@jvishnuvardhan  I changed my code in upsampling section:
`scale = 2
scale = np.asarray(scale, dtype=np.int32)
out = tf.depth_to_space(input, scale)`
But, I still met the error as before.

**Comment by jvishnuvardhan** [comment] 2020-05-18 02:16
@wujiexiaowugui 

> One of the attribute(block_size) of DepthToSpace has dtype of int64 which is not supported. Can you please change it to int32 and create the .pb?
did you check `block_size`? Can you do `tf.cast` to cast it to int32? Please let us know if you have any doubts?  Can you share the updated *.pb after `tf.cast` of `block_size` to `tf.int32`. Thanks!

**Comment by wujiexiaowugui** [comment] 2020-05-18 02:26
> @wujiexiaowugui
> 
> > One of the attribute(block_size) of DepthToSpace has dtype of int64 which is not supported. Can you please change it to int32 and create the .pb?
> > did you check `block_size`? Can you do `tf.cast` to cast it to int32? Please let us know if you have any doubts?  Can you share the updated *.pb after `tf.cast` of `block_size` to `tf.int32`. Thanks!

@jvishnuvardhan  When I set:
`scale = tf.cast(scale, tf.int32)`
There is an error occurred:
**TypeError: Expected int for argument 'block_size' not <tf.Tensor 'generator/WDSR/Cast/x:0' shape=() dtype=int32>.**

**Comment by wujiexiaowugui** [comment] 2020-05-18 05:13
> > @wujiexiaowugui
> > > One of the attribute(block_size) of DepthToSpace has dtype of int64 which is not supported. Can you please change it to int32 and create the .pb?
> > > did you check `block_size`? Can you do `tf.cast` to cast it to int32? Please let us know if you have any doubts?  Can you share the updated *.pb after `tf.cast` of `block_size` to `tf.int32`. Thanks!
> 
> @jvishnuvardhan When I set:
> `scale = tf.cast(scale, tf.int32)`
> There is an error occurred:
> **TypeError: Expected int for argument 'block_size' not <tf.Tensor 'generator/WDSR/Cast/x:0' shape=() dtype=int32>.**

@jvishnuvardhan 
`block_size = 2
block_size = tf.cast(block_size, tf.int32)
out = tf.depth_to_space(input, block_size)`
An error occurred:
**TypeError: Expected int for argument 'block_size' not <tf.Tensor 'generator/WDSR/Cast/x:0' shape=() dtype=int32>.**

**Comment by p98-ai** [comment] 2020-06-06 15:56
Hey! Is the DepthToSpace support added now?

**Comment by wujiexiaowugui** [comment] 2020-06-09 05:49
> Hey! Is the DepthToSpace support added now?

I think DepthToSpace is still not suppored.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:14
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:52 UTC
Labels: TF 1.15, comp:lite, stat:awaiting tensorflower, type:support
