### ISSUE TITLE
[TF.1.14] Cannot load weights under bfloat16 using tf.keras

### ISSUE THREAD

**Issue by nsantavas** [tensorflow/tensorflow#32617] opened 2019-09-18 11:47 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14
- Python version: 3
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):-
- CUDA/cuDNN version:-
- GPU model and memory: Using TPU

I ve trained a custom CNN with TF 1.14 using keras, and trained under TPU strategy scope and by settting:  
```
K.set_floatx('float16')
keras.backend.set_epsilon(1e-4)
```
For traininng with fp16. The training procedure was allright, since I would like to stop and load the trained weights. I compile the model under tpu_strategy.scope, and when trying to load weights using model.load_weigths, reaises the following error 

```
WARNING: Logging before flag parsing goes to stderr.
W0918 11:36:24.372959 139742800717568 deprecation.py:506] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0918 11:37:32.353564 139742800717568 deprecation_wrapper.py:119] From 6dense_inv_frp16.py:326: The name tf.losses.mean_squared_error is deprecated. Please use tf.compat.v1.losses.mean_squared_error instead.

W0918 11:37:32.370291 139742800717568 deprecation.py:323] From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/losses/losses_impl.py:121: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "6dense_inv_frp16.py", line 364, in <module>
    model.load_weights(filepath)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 759, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/backend.py", line 3058, in batch_set_value
    value = np.asarray(value, dtype=dtype(x))
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

**Comment by oanush** [comment] 2019-09-19 06:13
@nsantavas ,
Thank you for reporting the issue, can you please provide a simple and standalone code to reproduce the issue? meanwhile you can also refer these links [1](https://stackoverflow.com/questions/56116628/how-to-use-tf-keras-with-bfloat16) and [2](https://stackoverflow.com/questions/4674473/valueerror-setting-an-array-element-with-a-sequence) let us know if it can help resolving your issue.Thanks!

**Comment by tensorflowbutler** [comment] 2019-10-03 12:32
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by oanush** [comment] 2019-10-09 08:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-10-09 08:26 UTC
Labels: TF 1.14, comp:keras, stat:awaiting response, type:support
