### ISSUE TITLE
Error in tf.contrib.distributions.fill_triangular_inverse

### ISSUE THREAD

**Issue by mbrubake** [tensorflow/tensorflow#22349] opened 2018-09-18 16:36 UTC
### System information
** TF Env Info: **
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/2393567/tf_env.txt)

** TF Version: **
```
$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
/home/mab/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype
from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
v1.10.1-0-g4dcfddc5d1 1.10.1
```

### Describe the problem
The function ```fill_triangular_inverse``` actually uses the upper triangular portion of the matrices when constructing the transformation.  This can be seen with the above code where a vector is converted to a lower triangular matrix with ```fill_triangular``` and then back to a vector with ```fill_triangular_inverse```.  This works fine and reproduces the original vector unless there are non-zero entries added to the upper triangular portion of the intervening matrix.

The fix for this should be relatively easy and include a call to ```tf.matrix_band_part``` at the beginning of ```fill_triangular_inverse```.

### Source code / logs
Source to reproduce the issue:
```
import numpy as np
import tensorflow as tf
import tensorflow.contrib.distributions as tfdist

d = 5
par_d = d*(d+1)//2
vec = tf.constant(np.random.randn(1,par_d))
M_orig = tfdist.fill_triangular(vec)
M = M_orig + tf.constant(np.triu(np.random.randn(d,d),1).reshape([1,d,d]))
vec2 = tfdist.fill_triangular_inverse(M)
vec3 = tfdist.fill_triangular_inverse(M_orig)

with tf.Session() as sess:
    [vec_val,vec2_val,vec3_val] = sess.run([vec,vec2,vec3])

    print("d = {}, w/upper error = {}, w/o upper error = {}".format(d,np.linalg.norm(vec_val-vec2_val),np.linalg.norm(vec_val-vec3_val)))
```

Output on local installation:
```
d = 5, w/upper error = 2.6202726540863606, w/o upper error = 0.0
```

**Comment by wt-huang** [comment] 2018-09-18 21:04
@mbrubake if you would like to contribute PR are always welcome!

**Comment by brianwa84** [comment] 2018-09-25 16:20
@jvdillon fyi

**Comment by jvdillon** [comment] 2018-09-25 16:48
Hi Marcus. Thanks for your feedback.

This is actually by design; TFP tries to incur as little overhead as possible by assuming the input is "correct." That said, fill_triangular_inverse is idiomatically inconsistent with distributions in that it doesnt have a validate_args. If it did, then validate_args=True should produce an error in the case you describe.

Given this this I see two fixes we should make:
1) update the documentation to warn users that we expect the triu to be zeroed.
2) add validate_args logic which verifies this requirement.

Marcus, would you be interested in making this change? You could use validate_args from MVNTril as a template.

**Comment by tensorflowbutler** [comment] 2018-10-10 12:41
Nagging Assignee @wt-huang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment] 2018-10-12 17:01
Will close this issue soon, @mbrubake feel free to submit PR per recommendations from @jvdillon.

**Closed** 2018-10-13 02:04 UTC
Labels: type:enhancement
