### ISSUE TITLE
Incorrect behaviour creating constants from complex arrays of length >=64

### ISSUE THREAD

**Issue by charmasaur** [tensorflow/tensorflow#32944] opened 2019-10-01 07:59 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: Intel Iris Plus Graphics 640 1536 MB

**Describe the current behavior**
The following code produces an array of zeros after running several times (for me it seems to reliably be on the fourth run):
```tf.Session().run(tf.constant(1j*np.arange(64))```

**Describe the expected behavior**
That code should produce an array `[0j, 1j, 2j, ...]` no matter how many times it's run.

**Code to reproduce the issue**
```
import numpy as np
import tensorflow as tf
session = tf.Session()
for _ in range(4):
    print(session.run(tf.constant(1j*np.arange(64))))
```
Also see Colab notebook here: https://colab.research.google.com/drive/1Ci-bqoMpgK4JfCt0s2eUFjHR0vgOo_PF

**Other info / logs**
I have no idea what's happening, but some observations:
 - only occurs for arrays >=64 in length
 - also occurs if we construct the list manually instead of with numpy (e.g. `session.run(tf.constant([0] + [1j]*63))`)
 - doesn't occur if `1j` is replaced by `1+1j`
 - doesn't occur if the constant is created first, then multiplied by `1j` (e.g. `session.run(1j*tf.constant(np.arange(64).astype(np.complex128)))` is fine)

**Comment by gadagashwini** [comment] 2019-10-03 05:57
I could reproduce this issue with Tf 1.15.0rc1. Please see the [gist here](https://colab.sandbox.google.com/gist/gadagashwini/ee529a96c94b3e9a5aa5b22303ceeae1/untitled173.ipynb#scrollTo=CQh69Vy8KtmP). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-03 22:05
I could reproduce the issue with `TF1.15.0rc2` also. However, `TF2.0` works as expected. Please check [the gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/96c7fa6462f94cb421a9c2fa2684d9f1/untitled173.ipynb) with `TF2.0`. Thanks!

**Comment by charmasaur** [comment] 2019-10-03 23:22
I could reproduce with `TF2.0` when disabling eager execution, [gist here](https://colab.research.google.com/drive/1hgzD_W_PfSNwCGOrNnhMk89u12gy3ISP).

**Comment by jvishnuvardhan** [comment] 2019-10-09 17:40
@charmasaur I agree. This works well upto 63 (as in np.arange(63)).  I could reproduce the issue in 1.15.0rc3. However, I am not sure why you want to initialize and print a tensor inside a for loop. When I change your code to the following, everything worked as expected. Thanks!

```
import numpy as np
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
a = tf.constant(1j*np.arange(64))
session = tf.compat.v1.Session()
for _ in range(4):
    print(session.run(a))
```

**Comment by charmasaur** [comment] 2019-10-09 20:54
I get the same type of issue when building a larger graph "normally" (i.e. not building or running in a for loop), I was just using the loop to give a minimal example showing the issue.

Thanks for investigating, I'd be very interested to know what's going on here.

**Comment by rmlarsen** [comment] 2019-10-10 20:19
I have identified the bug in constant tensor compression and a fix should be submitted shortly.

**Comment by jvishnuvardhan** [comment] 2019-11-22 17:20
@charmasaur  I cannot reproduce the issue when I ran your code in `tf-nightly`. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/a0be9e53419c37cf63d4d090aededd23/untitled1.ipynb). Thanks!

This issue was fixed by @rmlarsen fix. It is available in `tf-nightly`.

I am closing the issue as it was resolved. Please feel to open the issue if the issue persists again. Thanks!

**Closed by jvishnuvardhan** 2019-11-22 17:20 UTC
Labels: TF 1.14, comp:ops, stat:awaiting tensorflower, type:bug

**Comment by charmasaur** [comment] 2019-11-24 21:44
Yep, that looks to be fixed, thanks! Any chance the fix could be linked here? I'd be keen to see what was going wrong.
