### ISSUE TITLE
FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by XDSwang** [tensorflow/tensorflow#50356] opened 2021-06-19 01:52 UTC
I'm using a tested environment in Win10

tensorflow-2.2.0 | 3.5-3.8 | MSVC 2019 | Bazel 2.0.0
-- | -- | -- | --
error occurred
...\_bazel_dswxxxxx\evzptwex\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1028): error C2061: 语
法错误: 标识符“Kind”
.../_bazel_dswxxxxx\evzptwex\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1134): note: 请参阅对
要编译的类 模板 的实例化“Eigen::internal::StridedLinearBufferCopy<Scalar,IndexType>”的引用
...\_bazel_dswxxxxx\evzptwex\execroot\org_tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/Tensor/TensorBlock.h(1037): error C2061: 语
法错误: 标识符“Kind”

why?

**Comment by XDSwang** [comment] 2021-06-19 13:40
tensorflow/python/lib/core/bfloat16.cc(654): error C2664: “bool tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf
61205e9403a18f850441a>::operator ()(const char *,PyUFuncGenericFunction,const std::array<int,3> &) const”: 无法将参数 2 从“void (
__cdecl *)(char **,npy_intp *,npy_intp *,void *)”转换为“PyUFuncGenericFunction”
tensorflow/python/lib/core/bfloat16.cc(654): note: 在匹配目标类型的范围内没有具有该名称的函数
tensorflow/python/lib/core/bfloat16.cc(629): note: 参见“tensorflow::`anonymous-namespace'::Initialize::<lambda_8175a7cc6bf61205e94
03a18f850441a>::operator ()”的声明
Target //tensorflow/tools/pip_package:build_pip_package failed to build

All environments were reset and a new error occurred
The environment version is tested

**Comment by tilakrayal** [comment] 2021-06-21 08:54
@XDSwang ,

Looks like this is duplicate of issue #50369.Can you please close this issue, since it is already being tracked there? Thanks!

**Closed** 2021-06-21 12:56 UTC
Labels: TF 2.2, stat:awaiting response, subtype:windows, type:bug, type:build/install
