### ISSUE TITLE
tf.SparseTensorSpec in input_signature of tf.function does not take effect

### ISSUE THREAD

**Issue by llan-ml** [tensorflow/tensorflow#45565] opened 2020-12-10 04:57 UTC
**Describe the current behavior**
When we define a `tf.SparseTensorSpec` with some specific shape in the `input_signature` of `tf.function`, we still can pass a `tf.SparseTensor` with any arbitrary shape into the decorated function.

Related to #29198. For now, the shape of input sparse tensor is always `None` inside tf.function, which I think contradicts with the purpose of `input_signature`.

**Describe the expected behavior**
Like `tf.TensorSpec`, it should raise an error when the input `tf.SparseTensor` is not compatible with the `tf.SparseTensorSpec`.

**Standalone code to reproduce the issue**
See [this notebook](https://colab.research.google.com/drive/1ArjLQqS6VufIla_IN0JykHSPpYUEG7gW?usp=sharing).

**Comment by ravikyram** [comment] 2020-12-10 10:58
@llan-ml 

 have tried n colab with TF 2.3, nightly verson(`2.5.0-dev20201210`)  and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/7530ff249cd234b8d881ec726476cfac/untitled573.ipynb).Thanks!

**Comment by rmothukuru** [comment] 2020-12-14 11:09
@llan-ml,
As this error is Originating because of  **`None Shape`** from **`Sparse Tensor`**, as you rightly specified in #29198, can you please confirm if we can close this issue to avoid redundancy, and track this issue in #29198? Thanks!

**Closed** 2020-12-14 12:44 UTC
Labels: TF 2.3, comp:ops, stat:awaiting response, type:bug
