### ISSUE TITLE
`math_grad._ProdGrad` fails to handle cases where reduction_indices is scalar

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#4147] opened 2016-09-01 08:53 UTC
```
x = tf.zeros([10])
tf.gradients(tf.reduce_prod(x, 0), [x])
```
Gives
```
more traceback

/home/***/.local/lib/python2.7/site-packages/tensorflow/python/ops/math_grad.pyc in _ProdGrad(op, grad)
    128   reduced = math_ops.cast(op.inputs[1], dtypes.int32)
    129   idx = math_ops.range(0, array_ops.rank(op.inputs[0]))
--> 130   other, _ = array_ops.listdiff(idx, reduced)
    131   perm = array_ops.concat(0, [reduced, other])
    132   reduced_num = math_ops.reduce_prod(array_ops.gather(input_shape, reduced))

more traceback
```

In line 128, `op.inputs[1]` could be a scalar, which will cause a shape mismatch when passed to `array_ops.listdiff` in line 130.

TF version: master branch a week ago

**Comment by mrry** [comment] 2016-09-01 15:19
I think this is a duplicate of #3815, which is being fixed by #3858.

**Closed** 2016-09-01 15:47 UTC
Labels: duplicate
