### ISSUE TITLE
Tensorboard does not show any scalers or graphs 

### ISSUE THREAD

**Issue by MMCMA** [tensorflow/tensorflow#9701] opened 2017-05-05 20:01 UTC
System information

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
    TensorFlow installed from (source or binary): binary, installed via pip
    TensorFlow version (use command below): 1.1.0
    Bazel version (if compiling from source):na
    CUDA/cuDNN version: na
    GPU model and memory: na
    Exact command to reproduce:?

### Describe the problem
Initially I was working with tensorflow 1.0.0 and tensorboard seemed to work just fine. I have updated to 1.1.0 and now it appears it does not display anything anymore. However, I get the warning 'WARNING:tensorflow:path ../external\data/plugin/text/runs not found, sending 404'. I have also downgraded tensorflow to 1.0.0 and now it also stopped working. 

### Source code / logs
```
tensorboard --inspect --logdir=model_dir
Found event files in: model_dir

These tags are in model_dir:
audio -
histograms
   dnn/dnn/hiddenlayer_0_activation
   dnn/dnn/hiddenlayer_10_activation
   dnn/dnn/hiddenlayer_11_activation
   dnn/dnn/hiddenlayer_1_activation
   dnn/dnn/hiddenlayer_2_activation
   dnn/dnn/hiddenlayer_3_activation
   dnn/dnn/hiddenlayer_4_activation
   dnn/dnn/hiddenlayer_5_activation
   dnn/dnn/hiddenlayer_6_activation
   dnn/dnn/hiddenlayer_7_activation
   dnn/dnn/hiddenlayer_8_activation
   dnn/dnn/hiddenlayer_9_activation
   dnn/dnn/logits_activation
images -
scalars
   dnn/dnn/hiddenlayer_0_fraction_of_zero_values
   dnn/dnn/hiddenlayer_10_fraction_of_zero_values
   dnn/dnn/hiddenlayer_11_fraction_of_zero_values
   dnn/dnn/hiddenlayer_1_fraction_of_zero_values
   dnn/dnn/hiddenlayer_2_fraction_of_zero_values
   dnn/dnn/hiddenlayer_3_fraction_of_zero_values
   dnn/dnn/hiddenlayer_4_fraction_of_zero_values
   dnn/dnn/hiddenlayer_5_fraction_of_zero_values
   dnn/dnn/hiddenlayer_6_fraction_of_zero_values
   dnn/dnn/hiddenlayer_7_fraction_of_zero_values
   dnn/dnn/hiddenlayer_8_fraction_of_zero_values
   dnn/dnn/hiddenlayer_9_fraction_of_zero_values
   dnn/dnn/logits_fraction_of_zero_values
   loss
tensor -
======================================================================

Event statistics for model_dir:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms
   first_step           1
   last_step            1
   max_step             1
   min_step             1
   num_steps            1
   outoforder_steps     []
images -
scalars
   first_step           1
   last_step            1
   max_step             1
   min_step             1
   num_steps            1
   outoforder_steps     []
sessionlog:checkpoint
   first_step           1
   last_step            1
   max_step             1
   min_step             1
   num_steps            1
   outoforder_steps     []
sessionlog:start
   outoforder_steps     []
   steps                [1]
sessionlog:stop -
tensor -
======================================================================


tensorboard --logdir=model_dir --host=127.0.0.1
Starting TensorBoard b'47' at http://127.0.0.1:6006
(Press CTRL+C to quit)
WARNING:tensorflow:path ../external\data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external\data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external\data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external\data/plugin/text/runs not found, sending 404

```

**Comment by drpngx** [comment] 2017-05-06 18:46
Just checking that it's not a windows issue, @guschmue @vit-stepanovs do you guys run tensorboard on windows and is it working well for you?

**Comment by guschmue** [comment] 2017-05-07 01:07
Works fine on master and 1.1 as far I can tell. 
Above log shows tensorboard finds one 1 scalar,  maybe the data in the scalar is not valid ?

**Comment by MMCMA** [comment] 2017-05-07 17:18
I have tried  the same for a different dir which used to work but no longer returns anything. here is the log of inspect:

```
C:\Users\T430MM>tensorboard --inspect --logdir=model_dir
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
model_dir
model_dir\eval

These tags are in model_dir:
audio -
histograms
   dnn/hiddenlayer_0_activation
   dnn/hiddenlayer_1_activation
   dnn/hiddenlayer_2_activation
   dnn/hiddenlayer_3_activation
   dnn/logits_activation
images -
scalars
   dnn/hiddenlayer_0_fraction_of_zero_values
   dnn/hiddenlayer_1_fraction_of_zero_values
   dnn/hiddenlayer_2_fraction_of_zero_values
   dnn/hiddenlayer_3_fraction_of_zero_values
   dnn/logits_fraction_of_zero_values
   global_step/sec
   loss
tensor -
======================================================================

Event statistics for model_dir:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms
   first_step           1
   last_step            9901
   max_step             9901
   min_step             1
   num_steps            100
   outoforder_steps     []
images -
scalars
   first_step           1
   last_step            9901
   max_step             9901
   min_step             1
   num_steps            100
   outoforder_steps     []
sessionlog:checkpoint
   first_step           1
   last_step            10000
   max_step             10000
   min_step             1
   num_steps            2
   outoforder_steps     []
sessionlog:start
   outoforder_steps     []
   steps                [1]
sessionlog:stop -
tensor -
======================================================================

These tags are in model_dir\eval:
audio -
histograms -
images -
scalars
   loss
tensor -
======================================================================

Event statistics for model_dir:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms -
images -
scalars
   first_step           10000
   last_step            10000
   max_step             10000
   min_step             10000
   num_steps            1
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================
```

The browser loads the tensorboard page, but it displays the following error under the scalar tab:

>  No scalar data was found.
> 
> Probable causes:
> 
>You haven't written any scalar data to your event files.
>TensorBoard can't find your event files.
> 
> If you're new to using TensorBoard, and want to find out how to add data and set up your event files, check out the README and perhaps the TensorBoard tutorial .
> 
> If you think TensorBoard is configured properly, please see the section of the README devoted to missing data problems and consider filing an issue on GitHub. 
>

**Comment by Yilong94** [comment] 2017-05-08 03:50
Facing the same issue as well. I am not sure if it is because of the logdir path such that it is unable to identify the Event file.

**Comment by guschmue** [comment] 2017-05-08 18:15
does a simple app like https://gist.github.com/guschmue/fef2018cefb327c45f7619e26f530837 this works?

**Comment by MMCMA** [comment] 2017-05-08 19:53
no, not for me. The dir is not empty, I see the tfevents file in there, but once more the same error log in the browser.

**Comment by Ipaulsen** [comment] 2017-05-10 17:30
I am also seeing the same thing :(
`Starting TensorBoard 47 at http://0.0.0.0:6006
(Press CTRL+C to quit)
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404`
I see the tensorBoard at http://0.0.0.0:6006
no event data though

**Comment by Ipaulsen** [comment] 2017-05-10 19:08
Looks like this known issue it was fix in a later version. Got mine working by -
`pip uninstall tensorflow`
then
`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl`

**Comment by MMCMA** [comment] 2017-05-10 19:24
well, I am not sure if downgrading to tf.__version__ <1.0.0 is the solution here.

**Comment by Ipaulsen** [comment] 2017-05-11 20:55
Your probably right cherry picking the patch is better until next release.

**Comment by MMCMA** [comment] 2017-05-12 15:53
I just want this issue to be resolved, going forward it should be in the interest of everyone to achieve a more permanent fix. In the mean time #9854 has a fix for getting tensorboard working for version1.1.0.  
`tensorboard --logdir==training:model_dir --host=127.0.0.1`

**Comment by npuliyang** [comment] 2017-05-13 08:09
My tensorboard has the same questions, and it said the 
```
----------------------------------------
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
```
and it is useless using the "training:model_dir" in the command line.

**Comment by dineshgit** [comment] 2017-05-15 04:23
I'm also facing this same error:
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404

I'm using TFlearn on Windows 10. Tensorflow 1.1.0 (I have CUDA and all the necessary libraries installed).
 But my Tensorboard isn't capturing the model I built on Tflearn well. I instead get this error messages:

WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404

**Comment by weiliu620** [comment] 2017-05-16 14:02
I've upgraded to TF 1.1.0 64 bit but also has this error and tensorboard show nothing. (Ubuntu 14.04 64bit, python 3.4)

**Comment by jingw222** [comment] 2017-05-17 04:54
Same here.
```
[WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
```

**Comment by kujta1** [comment] 2017-05-17 10:29
Also i have this problem(ubuntu 16.04)

WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404

**Comment by DSP209** [comment] 2017-05-18 15:35
Also having same issue. Win 10 64bit

**Comment by christabella** [comment] 2017-05-18 18:37
Same issue, on Docker tensorflow image (Ubuntu)

**Comment by minhnhat93** [comment] 2017-05-19 16:06
I too have this issue. Ubuntu 14.04 64 bit, python 2.7. Using firefox over an ssh connection.

**Comment by arundasan91** [comment] 2017-05-22 21:08
Faced this issue today but was able to correct it by changing the log directory to the base directory of my project instead of the checkpoint directory (another folder inside the project folder).

Basically changed from:
`tensorboard --logdir=/home/cc/Emotion/Emotion_checkpoints/` 
to
`tensorboard --logdir=/home/cc/Emotion/`

**Comment by d8sconz** [comment] 2017-05-24 08:32
Same issue - windows10, anaconda3, python3.5, tensorflow-gpu 1.1. None of the suggested workarounds have any effect.

**Comment by dartdog** [comment] 2017-05-28 18:01
Having same issue using Keras callbacks to generate the TB file I see the events file  in my logs dir and it seems to have a bunch in it (using vim to look at it)  but get nothing on TB 
(py36) tom@tomServal:~/Documents/InfluenceH/Working_copies/Cond_fcast_wkg$ $ tensorboard --logdir==./logs --host=127.0.0.1
Starting TensorBoard b'47' at http://127.0.0.1:6006
(Press CTRL+C to quit)
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404
WARNING:tensorflow:path ../external/data/plugin/text/runs not found, sending 404

Ubuntu 16.04 TF 1.1.0, 64 bit GPU installed using Pip into a Python 3.6 env on anaconda using the versions of Keras and Tensorboard in the Main Tensorflow distribution

**Comment by steven-hh-ding** [comment] 2017-06-01 03:42
`tensorboard --logdir==training:log_dir --host=127.0.0.1`
works for me (1.2.0rc1)

**Comment by oxinabox** [comment] 2017-06-03 04:30
Same here,
I solved by renaming directory from `2017-06-02T07:5:28.864_sib0.5/logs/`
to `arun/logs`

**Comment by kilgore92** [comment] 2017-06-03 18:43
I had the same problem. Steven's suggestion of specifying the host explicitly works for me ! Thanks :)

**Comment by jhonsonlaid** [comment] 2017-06-05 06:59
@steven-hh-ding , your suggestion exactly works for me, too! Thanks.

**Comment by BrambleXu** [comment] 2017-06-06 13:24
Same issue, mac 10.11, python3.5, TF 1.1.0. 
No working solution

**Comment by yashsharan** [comment] 2017-06-08 18:01
Even i had the same issue and i finally understood where i was wrong.
In my case I was using ubuntu and the log folder was stored inside my project directory itself.
So just navigate to the project directory from the terminal and type
tensorboard --logdir=log

**Comment by captainst** [comment] 2017-06-11 12:54
@dartdog 
I have the exact software setup as you did, and exactly the same problem. Have you managed to figureout ? Many thanks.

**Comment by steven-hh-ding** [comment] 2017-06-11 14:46
Moving from 1.2.0rc1 to rc2 the problem is gone (windows 10, windows server). No need to specify host name anymore. The `WARNING:tensorflow:Error encountered when serializing LAYER_NAME_UIDS` warning is gone as well.

**Comment by dandelionmane** [comment] 2017-06-16 19:13
Hi all,

This issue looks like it's encompassing a few different problems, some of which are workflow issues, some of which are bugs that are fixed in latest TensorBoard. So I'm going to close it.

You can pip install the latest tensorboard via `pip install tensorflow-tensorboard`.
If afterwards you still have issues, please open an issue at https://github.com/tensorflow/tensorboard.

**Closed by dandelionmane** 2017-06-16 19:13 UTC

**Comment by bitcurian** [comment] 2017-08-06 21:24
@BrambleXu 
I presume you've set the path relative to the location of the terminal. The path needs to be absolute. That may be why your fix worked.

**Comment by HRadmard** [comment] 2017-08-13 10:19
**BrumbleXu**, 's solution worked for me!
Many thanks, I think that the issue is with addressing the directory in Windows.
Just log in to your directory (one dir before your tensorboard dir) and address that directory.

**Comment by HaNgocLong** [comment] 2017-09-02 08:07
Just move directly to the summary files' directory and then type 
`python -m tensorflow.tensorboard --logdir={yours directory}`

It works

**Comment by Bazman76** [comment] 2017-09-12 15:30
Run the code in cells 19 & 23 below to import and pre-process the data.

https://github.com/ageron/handson-ml/blob/master/09_up_and_running_with_tensorflow.ipynb

Then lines 59-64 are run to solve a linear least squares problem, whilst saving the training data for use with tensorboard.

I then use Anaconda prompt to do to the directory where the log files are kept:
I then use Anaconda prompt to run: tensorboard --logdir=\tf_logs
It gives the message Starting TensorBoard b'54' at http://NW1:6006

But when I try to paste that address into a browser it doesn't work?

I've tried various combinations of absolute path names etc, and other solutions suggested in this thread, such as specifying the host as 127.0.0.1, but nothing seems to work. 

tensorboard --logdir=\tf_logs --host=127.0.0.1

But nothing seems to work! The webpage is completely blank.

I'm running windows 8.1
Internet Explorer 11
Anaconda 3
Python3.5
Tensorflow 1.1

Everything was installed fresh today so should be up to date

**Comment by luoping1004** [comment] 2017-11-03 01:44
steven-hh-ding's suggestion works for me too. Thanks!

**Comment by Jatik** [comment] 2017-11-14 18:38
In my case the problem was that I created the virtual environment, and I had to run tensorboard from there!

**Comment by wkolasa** [comment] 2017-11-17 16:54
BrambleXu's suggestion / solution worked for me!  Thank you very much.  That was frustrating.  Now, if I could only get the histogram error to go away (File "C:\ProgramData\Anaconda3\lib\site-packages\keras\callbacks.py", line 751, in on_epoch_end
    raise ValueError('If printing histograms, validation_data must be '
ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.)

**Comment by EarlitoW** [comment] 2017-11-21 23:01
Try Firefox. I t worked for me ! ! !
On Chrome and IE, TensorBoard would not display Graphs, Histograms or Embeddings.
However, FireFox 55.0.0 displayed everything.
My Chrome is at 62.0.3202.94
My IE is at 11.0x
On Windows 7

BTW: This issue might me the same as #10611

**Comment by apodemakeles** [comment] 2017-11-23 01:01
same issue,  tensorflow 1.4, tensorboard 0.4.0rc, windows 7, anaconda, py3.6
tensorboard --logdir==training:log_dir --host=127.0.0.1
works

**Comment by PaulGitt** [comment] 2017-12-17 00:44
Just update the tensorflow version or try to open tensorboard in your logdir 
tensorboard --logdir=your_log_dir/your_speciafy_log_dir 
or open tensorboard in your specific logdir 
tensorboard --logdir=your_specific_log_dir
these two type can works, because the it depends on which path you open tensorboard

**Comment by slideWXY** [comment] 2017-12-22 15:01
replace " space " in your path location by renaming directories
That's work really well 

Hope that will work for you guys :+1:

**Comment by alberduris** [comment] 2018-03-14 13:05
I get this problem eventually. I don't know why sometimes it works and sometimes doesn't, but the work around is opening it with Firefox.

I can't really understand how a Google Product like Tensorboard doesn't work on Chrome and does it on Firefox, but that's it.

Same as #10611

**Comment by Carolzheng** [comment] 2018-04-19 09:12
Same issue. And it was working properly this morning until suddenly I get this error. I'm on Ubuntu 16.04 with python 3.6 and tensorflow 1.7.0, GPU version.
tensorboard --logdir==training:log_dir --host=127.0.0.1 worked for me.  But absolutely no idea why it didn't work and why it worked.

**Comment by toiara** [comment] 2018-04-22 05:13
Faced the same issue. I'm on Win10 with python 3.6 and tensorflow 1.6 GPU.
I found the work around. 
It is opening GRAPHS with Edge.

**Comment by alaakh42** [comment] 2018-04-30 11:34
I was facing this problem on a Linux machine, 
I discovered that this happened because I was in the directory of logs folder and by going back to the parent directory, and then issuing the command 
`tensorboard --logdir==training:path_to_logs/logs_folder_name --host=127.0.0.1 --port=6007 `
It worked fine.

**Comment by diegovalenzuelaiturra** [comment] 2018-07-10 20:34
I've done this :) and it works for me 

https://stackoverflow.com/questions/48684755/tensorboard-doesnt-show-scalars-anymore

**Comment by kirankumarkv** [comment] 2019-02-04 11:45
Had the same problem of graphs not populating with 
tensorboard --logdir=training:log_dir --host=127.0.0.1
Hence specified just the directory which contains training information
tensorboard --logdir=training --host=127.0.0.1
