### ISSUE TITLE
[Bug] max_pool_with_argmax has different behaviour on CPU and GPU

### ISSUE THREAD

**Issue by mpaillassa** [tensorflow/tensorflow#22025] opened 2018-09-03 10:31 UTC
The function ``max_pool_with_argmax`` has different behaviour concerning the returned indices depending on the GPU or CPU backend.

- On GPU, returned indices do not take into account batch dimension. 
It returns indices such that `[b, y, x, c] -> (y * width + x) * channels + c `
- On CPU, returned indices take into account batch dimension.
It returns indices such that `[b, y, x, c] -> ((b * height + y) * width + x) * channels + c `

Isn't it a problem if one wants to run models with the same graph including this op both on CPU and GPU ?

Here is an example to show the problem:
``` python
import numpy as np
import tensorflow as tf 

i = tf.placeholder(tf.float32, [None, 4, 4, 1])
p, ind = tf.nn.max_pool_with_argmax(i, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

with tf.Session() as sess:
    a = np.random.randint(10, size=(2, 4, 4, 1))
    print a[:,:,:,0]
    print sess.run(p, {i: a})[:,:,:,0]
    print sess.run(ind, {i: a})[:,:,:,0]
```
Which results in something like this on CPU:
```
[[[0 3 0 0]
  [4 0 4 8]
  [7 8 4 5]
  [2 3 4 5]]

 [[2 5 2 7]
  [4 3 4 6]
  [8 3 2 0]
  [7 5 9 3]]]
[[[4. 8.]
  [8. 5.]]

 [[5. 7.]
  [8. 9.]]]
[[[ 4  7]
  [ 9 11]]

 [[17 19]
  [24 30]]]
```
And something like this on GPU:
```
[[[8 3 5 5]
  [0 0 0 3]
  [6 9 4 1]
  [2 0 8 8]]

 [[4 6 6 5]
  [5 7 9 3]
  [7 6 1 3]
  [1 6 1 0]]]
[[[8. 5.]
  [9. 8.]]

 [[7. 9.]
  [7. 3.]]]
[[[ 0  2]
  [ 9 14]]
 [[ 5  6]
  [ 8 11]]]
```
This was obtained with 1.9 CPU/GPU tensorflow versions.
I think it would be more convenient to have the same behaviour on CPU and GPU, isn't it ?

**Comment by tensorflowbutler** [comment] 2018-09-03 18:36
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by mpaillassa** [comment] 2018-09-04 07:42
Have I written custom code: yes 
OS Platform: Ubuntu 16.04 LTS for CPU install and centOS 7 for GPU install

But I don't think these informations are necessary ? 
The problem is really that the behaviour of the function is different for tensorflow 1.9 CPU and tensorflow 1.9 GPU.

**Comment by poxvoculi** [comment] 2018-09-11 23:37
@qlzh727 Could you take a look at this?  Is it expected behavior?

**Comment by qlzh727** [comment] 2018-09-11 23:48
Not sure why I am cc'ed here, if I was showing up from the change history, I guess that was because I was on sync rotation for PRs. Probably should find someone who is the real owner of maxpooling_op.cc

**Comment by poxvoculi** [comment] 2018-09-12 18:03
OK, looks like this code is kind of old, with no real maintainer.  @rmlarsen do you know what's expected here?  I don't see any notice in the documentation that CPU/GPU behavior should differ.

**Comment by mpaillassa** [comment] 2018-09-25 13:18
Any news about this ?

I do not know if this can help but in fact the documentation of the function is correct for the CPU behaviour, Plus, the function has been available first on GPU and on a later TF version for CPU.
I guess that there was a wrong doc when the function was available only for GPU, and that when it has been later implemented for CPU, it has been inspired from the doc, leading to two different behaviours.

**Comment by facaiy** [comment] 2018-10-12 23:54
I'm looking into the issue and I'll try to fix it later. Thanks for @mpaillassa 's detailed feedback :-)

**Comment by facaiy** [comment] 2018-10-19 11:49
@mpaillassa Hi, would you mind taking a test on nightly version? `pip install tf-nightly-gpu`

**Comment by mpaillassa** [comment] 2018-10-21 13:33
@facaiy Hi, I tried the code of my first post on CPU with `pip install tf-nightly` and on GPU with `pip install tf-nightly-gpu`. Both on Ubuntu 16.04 and with CUDA 9.0 and cuDNN 7.3.1 for GPU.
But I still get the same behaviours: CPU takes into account the batch dimension in the returned indices while GPU does not.  
Did I do something wrong ?

**Comment by facaiy** [comment] 2018-10-22 11:55
@mpaillassa Thanks for your feedback. Don't worry. I will update this thread later, sorry that I'm a little busy this week.

**Comment by facaiy** [comment] 2018-11-08 04:02
Thank @mpaillassa for your report, I can reproduce the bug in my experimental PR #23370. 

Unfortunately, there is something wrong with my working station environment, and I cannot find an alternative recently. So I'd like to mark the issue as "Contributions Welcome", and feel free to take over it and go head if anyone is interested :-)

**Comment by facaiy** [comment] 2018-11-27 09:54
I create the PR #23993 to fix the issue, please take a look, thanks :-)

**Comment by bono1567** [comment] 2019-02-27 16:05
Hello, I am new to the tensorflow community. Is this a good issue to get familiar with the tensorflow open-source?

**Comment by facaiy** [comment] 2019-02-27 22:46
Welcome, @bono1567! As you see, PR #25241 and #23993 have been in the process to fix the issue. I'll update here when they are merged.

**Closed** 2019-03-12 23:00 UTC
Labels: stat:contributions welcome, type:bug/performance
