### ISSUE TITLE
UnicodeDecodeError when reading from tfrecords

### ISSUE THREAD

**Issue by CRSilkworth** [tensorflow/tensorflow#5676] opened 2016-11-17 20:50 UTC
All I'm really trying to do is read a large array from a tfrecords file. I can do it so long that it's below a 8million ints but above that I get a unicode error, which doesn't seem to make much sense to me. Also, it worth noting that this script works using r0.9. I have about 64GB of ram on my computer so I doubt it's a memory issue. 

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System:
Linux Mint 18 Sarah (GNU/Linux 4.4.0-47-generic x86_64)

Installed version of CUDA and cuDNN: 
not installed

If installed from binary pip package, provide:

1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
python -c "import tensorflow; print(tensorflow.__version__)"

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
import tensorflow as tf
import numpy as np

dim_size = 9000000

# Create the array
array = np.zeros([dim_size], dtype=int)

example = tf.train.Example(
    features = tf.train.Features(
        feature = {
            'array': tf.train.Feature(
                bytes_list= tf.train.BytesList(value=[array.tostring()])
            )
        }
    )
)

# Write the example to disk
writer = tf.python_io.TFRecordWriter('temp.tfrecords')
writer.write(example.SerializeToString())
writer.close()

# Define input pipeline
queue = tf.train.string_input_producer(['temp.tfrecords'], shuffle=False, num_epochs=1)
reader = tf.TFRecordReader()
_, se = reader.read(queue)

#Define the parsed dict
parsed = tf.parse_single_example(
    serialized=se,
    features={
        "array":tf.FixedLenFeature([], tf.string),
    }
)

# Decode the example
tens = tf.decode_raw(parsed['array'], tf.int64)

# Define the init op.
init_op = tf.group(
    tf.initialize_all_variables(),
    tf.initialize_local_variables()
)
with tf.Session() as sess:
    sess.run(init_op)
    # Define coordinator and threads
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord, sess=sess)

    # Run the reading operation
    print sess.run([tens])
    coord.request_stop()
    coord.join(threads)
```

### What other attempted solutions have you tried?
This works using r0.9 and it also works if you lower the dim_size below 800000. So it seems to be an issue with the size and r0.11. I also get the same results if I use a float array as opposed to an int. 

### Logs or other output that would be helpful
```
W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Could not parse example input, value: '
?Ī"
?Ī"
array?Ī"
?Ī"
?Ī"
Traceback (most recent call last):
  File "temp.py", line 52, in <module>
    print sess.run([tens])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 972, in _do_call
    return fn(*args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 954, in _run_fn
    status, run_metadata)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 462, in raise_exception_on_not_ok_status
    compat.as_text(pywrap_tensorflow.TF_Message(status)),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 82, in as_text
    return bytes_or_text.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9b in position 40: invalid start byte
```

**Comment by girving** [comment] 2016-11-18 16:10
@mrry Should we be escaping strings in error messages?  I vaguely recall having part of that discussion before.

@CRSilkworth The unicode error is secondary.  Your immediate problem is the `Could not parse example input` error.  @martinwicke Is this the dreaded protobuf limit?  The error is from https://github.com/tensorflow/tensorflow/blob/dfc5cd48a095b133ece9caff663e3cc512e8a268/tensorflow/core/kernels/example_parsing_ops.cc#L326.

**Comment by mrry** [comment] 2016-11-18 18:52
@girving Yes, I think we should be escaping strings here. I don't remember what the outcome of the earlier discussion was (in particular, where the encoding should happen) but it seems like we use `str_util::CEscape(binary_string)` in a few kernels, so perhaps we should use it here?

**Comment by girving** [comment] 2016-11-18 19:12
@ebrevdo Care to add escaping to that error message?  Assigning to you for now.

**Comment by ebrevdo** [comment] 2016-11-19 16:49
Yes on Monday.

**Comment by CRSilkworth** [comment] 2016-11-23 12:59
Did we ever determine if the real issue is this protobuf limit? Am I able to avoid this some how or will I have to revert back to 0.9?

**Comment by martinwicke** [comment] 2016-11-23 16:37
I don't know why there would be a difference between 0.9 and 0.11 then.
Otherwise it looks plausible. Sadly the real error is hidden by the Unicode
problem. Did you install the >64MB version of protobuf? Assuming that that
is used and nothing else (hard to tell), the limit shouldn't trigger at 8M
ints.

**Comment by CRSilkworth** [comment] 2016-11-25 12:20
Hmm I'm not sure if my protobuf version is > 64MB, I just installed the one that tensorflow as a dependency (protobuf==3.0.0). 

Is there anything I can do to help out in tracking this down?

**Comment by martinwicke** [comment] 2016-12-07 17:24
There's a protobuf version on our website with the 64MB limit removed: 
https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#protobuf-library-related-issues

Can you try installing one of those packages? Make sure to uninstall protobuf beforehand.

**Comment by jonasrauber** [comment] 2017-02-07 16:25
I have the same problem. Using the other protobuf library doesn't help.

**Comment by martinwicke** [comment] 2017-03-27 18:17
Is this still an issue in current TF? 

@ebrevdo did you ever fix the error message?

**Comment by ebrevdo** [comment] 2017-03-27 23:36
Replicated only part of the error in python3:

```
with open('temp.tfrecords', 'rb') as v:
    s = v.read()
z = tf.parse_single_example(serialized=s, features={

        "array":tf.FixedLenFeature([], tf.string),
    })
s = tf.Session()
s.run(z)
```

returns

```
2017-03-27 16:35:53.868045: W tensorflow/core/framework/op_kernel.cc:1150]
Invalid argument: Could not parse example input, value: ' �J
ERROR - failed to write data to stream: <_io.TextIOWrapper name='<stdout>'
mode='w' encoding='UTF-8'>
```

**Comment by ebrevdo** [comment] 2017-03-27 23:47
That said, running:


returns

DecodeError: Unexpected end-group tag.

in other words, looks like the proto is invalid once written?  weird.
 looks like an error by the TFRecordWriter?

this works just fine:

```
sess.run(
  tf.parse_single_example(serialized=example.SerializeToString(),
    features={

        "array":tf.FixedLenFeature([], tf.string),
    })
```

so looks like the issue is somewhere in the TFRecordWriter or
TFRecordReader.

**Comment by martinwicke** [comment] 2017-06-06 15:19
@saxenasaurabh I saw you were working on the reader/writer a bit, can you take a look at this?

**Comment by glhfgg1024** [comment] 2017-08-15 15:16
I also have this problem. I generated the tfrecords on Windows system, and the problem is occured. But it's fine to parse on Ubuntu system using the same parsing code.

**Comment by bodokaiser** [comment] 2017-10-07 08:27
@martinwicke Are there any updates on this? The problem still occurs on windows.

**Comment by bodokaiser** [comment] 2017-10-22 07:39
@martinwicke Can it be that #5676 #7311 and #13575 are all relating to the same issue which is still present on windows?

**Comment by tensorflowbutler** [comment] 2017-12-22 07:39
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:09
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:23
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-08 19:28
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:06
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by saxenasaurabh** [comment] 2018-02-28 20:50
Closing as this looks like a duplicate of [#13575](https://github.com/tensorflow/tensorflow/issues/13575) which I have been unable to reproduce. Please re-try and re-open [#13575](https://github.com/tensorflow/tensorflow/issues/13575) if this is still an issue.

**Closed by saxenasaurabh** 2018-02-28 20:50 UTC
Labels: stat:awaiting response, type:bug/performance
