### ISSUE TITLE
Tensorflow "devel-gpu-py3" docker image is stale, has not been updated for 2 months

### ISSUE THREAD

**Issue by RafayAK** [tensorflow/tensorflow#35492] opened 2019-12-30 08:02 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): Docker image
- TensorFlow version: 2.0
- Python version: 3
- Installed using virtualenv? pip? conda?: Docker
- Bazel version (if compiling from source): default from the docker image
- GCC/Compiler version (if compiling from source): default from the docker image
- CUDA/cuDNN version: 10.0
- GPU model and memory: Nvidia gt750m

**Describe the problem**

I have been trying to create the TensorFlow-GPU wheel for my legacy hardware for which I need to build Tensorflow 2.0 with CUDA compute 3.0. The docker image for building a TensorFlow-GPU wheel is stale and has not been updated for [2 months](https://hub.docker.com/layers/tensorflow/tensorflow/devel-gpu-py3/images/sha256-2c17ae6134fc0abbc8128c62d74efd4d9312a04f92483c8f31279f630d5a5800). 

For the sake of reducing redundancy, I'll link the previous issue:
https://github.com/tensorflow/tensorflow/issues/34719

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by angerson** [comment] 2019-12-30 18:27
Thanks for isolating this into a new issue. Our previous expert on building in Docker departed a couple months ago, just before TensorFlow started using CUDA 10.1, and I've been trying to get the images fixed since then.

With recent commits to the dockerfiles/ directory, I believe the build issues are now resolved, and our CI should pick them up and deploy by December 31.

**Comment by RafayAK** [comment] 2020-01-04 15:02
Hey @angerson seems like they're still not up

**Comment by settle** [comment] 2020-02-12 01:32
I just tested the latest-devel-gpu image from DockerHub, aka 2.1.0-devel-gpu, and ran into an error that when these Dockerfiles are updated should be addressed.  The fastest way to reproduce the error is to simply try running nvidia-smi from the command line.  When I ran it, it reports "CUDA Version: ERR!".  Running that from the latest-gpu image it returns "CUDA Version: 10.1".  Diff'ing the following two files points to an LD_LIBRARY_PATH issue including "/usr/local/cuda/lib64/stubs" in the devel image:
- tensorflow/tensorflow/tools/dockerfiles/partials/ubuntu/devel-nvidia.partial.Dockerfile
- tensorflow/tensorflow/tools/dockerfiles/partials/ubuntu/nvidia.partial.Dockerfile

If I export LD_LIBRARY_PATH in the devel image like in the non-devel image, then nvidia-smi reports the correct CUDA Version.

**Comment by settle** [comment] 2020-02-12 01:48
Hi @angerson,

I forgot to mention that I had to change "ENV TF_NEED_TENSORRT 1" to "ENV TF_NEED_TENSORRT 0" in order to successfully bazel build inside latest-devel-gpu.  Sorry, I didn't hunt down why that was necessary.

Oh, the above LD_LIBRARY_PATH issue didn't affect bazel build, just when I went to test `python -c "import tensorflow as tf ; physical_devices = tf.config.list_physical_devices('GPU') ; print('Num GPUs:', len(physical_devices))"`, which showed more details regarding the missing libraries and hinted to me to investigate LD_LIBRARY_PATH.

**Comment by angerson** [comment] 2020-02-27 01:34
@settle thanks for reporting that; you saved me some time when investigating https://github.com/tensorflow/tensorflow/issues/36974. Since this current issue is resolved (containers are now available), I'll close it in favor of the other issue to track the CUDA problem. Thanks!

**Closed by angerson** 2020-02-27 01:34 UTC
Labels: TF 2.0, subtype: ubuntu/linux, type:build/install
