### ISSUE TITLE
NullPointerException when trying to access Classifier.Recognition / result.getLocation()

### ISSUE THREAD

**Issue by dfvr1994** [tensorflow/tensorflow#35827] opened 2020-01-13 18:52 UTC
**Setup:** 
I've used Google's Cloud AutoML Vision Object Detection platform to create a custom model for object recognition using this tutorial:

https://cloud.google.com/vision/automl/object-detection/docs/edge-quickstart

Then added the model to the following app template:

https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

Then I overcame the following two errors: 

1) `Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 270000 bytes.` I modified TF_OD_API_INPUT_SIZE accordingly. 

2) ` tflite ml google [1, 20, 4] and a Java object with shape [1, 10, 4]. ` I modified NUM_DETECTIONS according to my custom model.

Finally got the model working. 

Now I want to send the box locations using Bluetooth to a HC-05. I added two public classes: BluetoothArduinoBridge, and LocationSender. Both of them attached as txt files.

**Problem**
App crashes when objects are recognized. 

**Code to reproduce the issue**
I modified the code at DetectorActivity.java, lines 203-218 to this: 

```
            for (final Classifier.Recognition result : results) {
              final RectF location = result.getLocation();
              if (location != null && result.getConfidence() >= minimumConfidence) {
                canvas.drawRect(location, paint);

                cropToFrameTransform.mapRect(location);

                result.setLocation(location);
                mappedRecognitions.add(result);

                //----------------------------------------
                mLocationSender.send_location((location.bottom),(location.left),(location.right)
                ,(location.top));
                //----------------------------------------
              }
            }

```
**Other info / logs**
```
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 16690
    java.lang.NullPointerException: Attempt to invoke virtual method 'void org.tensorflow.lite.examples.detection.LocationSender.send_location(float, float, float, float)' on a null object reference
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:213)
```

**Question**
How can I send the box locations using mLocationSender.send_location???

**Note**
I'm quite new to Android so this might probably be a dumb question. Please be gentle. 
[LocationSender.txt](https://github.com/tensorflow/tensorflow/files/4055214/LocationSender.txt)
[BluetoothArduinoBridge.txt](https://github.com/tensorflow/tensorflow/files/4055215/BluetoothArduinoBridge.txt)

**Comment by lintian06** [comment] 2020-02-22 01:49
Hi dfvr1994, 

It seems that mLocationSender is null in your modified code, you should check when it is assigned a new object.

I am glad to hear that you overcame the adaption to your custom model.

As this is not a bug from original code and for https://github.com/tensorflow/examples in particular, I will close this bug.

**Closed** 2020-02-22 01:50 UTC
Labels: comp:lite, stat:awaiting tensorflower, type:support
