### ISSUE TITLE
problem in tf.data.TFRecordDataset

### ISSUE THREAD

**Issue by haddis3** [tensorflow/tensorflow#19856] opened 2018-06-08 13:02 UTC
**Describe the problem**
I use the tf.data.TFRecordDataset API to read the tfrecord file. Everything is ok when batch_size is set to 1, but when the batch_size is greater than 1, the code is crashed. the error is below:

_Traceback (most recent call last):
  File "F:/kaggle/JD_Fashion_AI/train.py", line 125, in <module>
    main()
  File "F:/kaggle/JD_Fashion_AI/train.py", line 122, in main
    run_training()
  File "F:/kaggle/JD_Fashion_AI/train.py", line 98, in run_training
    sess.run(label)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "D:\python\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 200704 values, but the requested shape has 150528
	 [[Node: Reshape = Reshape[T=DT_UINT8, Tshape=DT_INT32](DecodeRaw, Reshape/shape)]]
	 [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,224,224,3], [?,?], [?]], output_types=[DT_UINT8, DT_UINT8, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]]
_

note: i have totally 50000 images, i originally set batch_size to 16, so the num_per_epoch is 3125.

**Source code**
`def _parse_function(record):

    features = {'image': tf.FixedLenFeature([], tf.string), 'label': tf.FixedLenFeature([], tf.string),
                'id': tf.FixedLenFeature([], tf.string)}
    example = tf.parse_single_example(record, features=features)
    image = tf.decode_raw(example['image'], tf.uint8)
    image = tf.reshape(image, [224, 224, 3])
    label = tf.subtract(tf.decode_raw(example['label'], tf.uint8), 48)
    id = tf.cast(example['id'], tf.string)

    return image, label, id

def run_training():

    # learning_rate = tf.placeholder(dtype=tf.float32)
    train_filenames = ['I:/JD_fashion_AI/train_tfrecords/train.tfrecords']
    validation_filenames = ['I:/JD_fashion_AI/valid_tfrecords/valid.tfrecords']
    train_datasets = tf.data.TFRecordDataset(filenames=train_filenames)
    validation_datasets = tf.data.TFRecordDataset(filenames=validation_filenames)
    train_datasets = train_datasets.map(_parse_function).shuffle(buffer_size=1000).batch(16).repeat()
    validation_datasets = validation_datasets.map(_parse_function).batch(1).repeat(1)
    iterator = tf.data.Iterator.from_structure(train_datasets.output_types,
                                               train_datasets.output_shapes)
    image, label, id = iterator.get_next()
    training_init_op = iterator.make_initializer(train_datasets)
    validation_init_op = iterator.make_initializer(validation_datasets)

    init = tf.global_variables_initializer()

    with tf.Session() as sess:

        sess.run(init)
        step = 0
        for _ in range(18):
            sess.run(training_init_op)  # must initialize the iterator to read the data flow
            for _ in range(3125):
                
                sess.run(label)
                print(step)
`
anyone else know what happened ?

**Comment by tensorflowbutler** [comment] 2018-06-09 00:38
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by haddis3** [comment] 2018-06-10 11:45
I have solved my problem. There is something wrong with my training data. The depth of normal image is 3, but there exist several images with depth of 4. Hence, input tensor is not match  with my default size 150528 (150528 = 224 x 224 x 3).

**Comment by angersson** [comment] 2018-06-21 19:28
Looks like this issue is resolved, so I'll close it. Thanks for posting an update!

**Closed by angersson** 2018-06-21 19:28 UTC
