### ISSUE TITLE
building from source failed 

### ISSUE THREAD

**Issue by ThisIsIsaac** [tensorflow/tensorflow#29053] opened 2019-05-27 09:53 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: latest master from github
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: virtualenv
- Bazel version (if compiling from source): 0.25.3
- GCC/Compiler version (if compiling from source): gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
- CUDA/cuDNN version: CUDA 10/ cuDNN 7
- GPU model and memory:V100 32G

**Describe the problem**
when I run: `bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`, I get error:
```
WARNING: The following configs were expanded more than once: [cuda, using_cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=129
INFO: Reading rc options for 'build' from /home/minds/isaac/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include
INFO: Reading rc options for 'build' from /home/minds/isaac/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/minds/.virtualenvs/venv_tf/bin/python --action_env PYTHON_LIB_PATH=/home/minds/.virtualenvs/venv_tf/lib/python3.6/site-packages --python_path=/home/minds/.virtualenvs/venv_tf/bin/python --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda --action_env TF_CUDA_COMPUTE_CAPABILITIES=7.0,7.0 --action_env GCC_HOST_COMPILER_PATH=/bin/gcc --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:cuda in file /home/minds/isaac/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/minds/isaac/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Found applicable config definition build:opt in file /home/minds/isaac/tensorflow/.tf_configure.bazelrc: --copt=-march=native --copt=-Wno-sign-compare --host_copt=-march=native --define with_default_optimizations=true
INFO: Found applicable config definition build:cuda in file /home/minds/isaac/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/minds/isaac/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: An error occurred during the fetch of repository 'io_bazel_rules_docker'
INFO: Call stack for the definition of repository 'io_bazel_rules_docker':
 - /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - /home/minds/isaac/tensorflow/WORKSPACE:29:1
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
	File "/home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
		_clone_or_update(ctx)
	File "/home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external
+ rm -rf /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker
+ git clone '' https://github.com/bazelbuild/rules_docker.git /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker
Too many arguments.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

+ git clone https://github.com/bazelbuild/rules_docker.git /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker
+ git -C /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker reset --hard 251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker fetch '' origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker fetch origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
	File "/home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
		_clone_or_update(ctx)
	File "/home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
error cloning io_bazel_rules_docker:
+ cd /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external
+ rm -rf /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker
+ git clone '' https://github.com/bazelbuild/rules_docker.git /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker
Too many arguments.

usage: git clone [options] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository

+ git clone https://github.com/bazelbuild/rules_docker.git /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker
+ git -C /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker reset --hard 251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker fetch '' origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
+ git -C /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/io_bazel_rules_docker fetch origin 251f6a68b439744094faff800cd029798edf9faa:251f6a68b439744094faff800cd029798edf9faa
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
INFO: Elapsed time: 7.123s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Provide the exact sequence of commands / steps that you executed before running into the problem**
followed this [guide](https://www.tensorflow.org/install/source), until I faced the issue

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment] 2019-05-28 16:23
What is the output of `git --version`?

**Comment by ThisIsIsaac** [comment] 2019-05-29 04:39
git version 1.8.3.1

**Comment by mihaimaruseac** [comment] 2019-05-29 14:45
It is a different error now.

**Comment by ThisIsIsaac** [comment] 2019-06-02 04:58
I understand. Could you help me out?

**Comment by mihaimaruseac** [comment] 2019-06-03 15:15
Can't reproduce. Can you try recloning the repo on a different directory and recompiling from scratch?

**Comment by ThisIsIsaac** [comment] 2019-06-05 06:24
I have tried building again and failed with a different error:
```
ERROR: /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/protobuf_archive/BUILD:91:1: undeclared inclusion(s) in rule '@protobuf_archive//:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'external/protobuf_archive/src/google/protobuf/stubs/statusor.cc':
  '/include/c++/4.8.5/new'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++config.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/os_defines.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/cpu_defines.h'
  '/include/c++/4.8.5/exception'
  '/include/c++/4.8.5/bits/atomic_lockfree_defines.h'
  '/include/c++/4.8.5/bits/exception_ptr.h'
  '/include/c++/4.8.5/bits/exception_defines.h'
  '/include/c++/4.8.5/bits/nested_exception.h'
  '/include/c++/4.8.5/string'
  '/include/c++/4.8.5/bits/stringfwd.h'
  '/include/c++/4.8.5/bits/memoryfwd.h'
  '/include/c++/4.8.5/bits/char_traits.h'
  '/include/c++/4.8.5/bits/stl_algobase.h'
  '/include/c++/4.8.5/bits/functexcept.h'
  '/include/c++/4.8.5/bits/cpp_type_traits.h'
  '/include/c++/4.8.5/ext/type_traits.h'
  '/include/c++/4.8.5/ext/numeric_traits.h'
  '/include/c++/4.8.5/bits/stl_pair.h'
  '/include/c++/4.8.5/bits/move.h'
  '/include/c++/4.8.5/bits/concept_check.h'
  '/include/c++/4.8.5/type_traits'
  '/include/c++/4.8.5/bits/stl_iterator_base_types.h'
  '/include/c++/4.8.5/bits/stl_iterator_base_funcs.h'
  '/include/c++/4.8.5/debug/debug.h'
  '/include/c++/4.8.5/bits/stl_iterator.h'
  '/include/c++/4.8.5/bits/postypes.h'
  '/include/c++/4.8.5/cwchar'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/include/c++/4.8.5/cstdint'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h'
  '/include/c++/4.8.5/bits/allocator.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++allocator.h'
  '/include/c++/4.8.5/ext/new_allocator.h'
  '/include/c++/4.8.5/bits/localefwd.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++locale.h'
  '/include/c++/4.8.5/clocale'
  '/include/c++/4.8.5/iosfwd'
  '/include/c++/4.8.5/cctype'
  '/include/c++/4.8.5/bits/ostream_insert.h'
  '/include/c++/4.8.5/bits/cxxabi_forced.h'
  '/include/c++/4.8.5/bits/stl_function.h'
  '/include/c++/4.8.5/backward/binders.h'
  '/include/c++/4.8.5/bits/range_access.h'
  '/include/c++/4.8.5/bits/basic_string.h'
  '/include/c++/4.8.5/ext/atomicity.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/gthr.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/gthr-default.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/atomic_word.h'
  '/include/c++/4.8.5/initializer_list'
  '/include/c++/4.8.5/ext/string_conversions.h'
  '/include/c++/4.8.5/cstdlib'
  '/include/c++/4.8.5/cstdio'
  '/include/c++/4.8.5/cerrno'
  '/include/c++/4.8.5/bits/functional_hash.h'
  '/include/c++/4.8.5/bits/hash_bytes.h'
  '/include/c++/4.8.5/bits/basic_string.tcc'
  '/include/c++/4.8.5/utility'
  '/include/c++/4.8.5/bits/stl_relops.h'
  '/include/c++/4.8.5/algorithm'
  '/include/c++/4.8.5/bits/stl_algo.h'
  '/include/c++/4.8.5/bits/algorithmfwd.h'
  '/include/c++/4.8.5/bits/stl_heap.h'
  '/include/c++/4.8.5/bits/stl_tempbuf.h'
  '/include/c++/4.8.5/bits/stl_construct.h'
  '/include/c++/4.8.5/ext/alloc_traits.h'
  '/include/c++/4.8.5/bits/alloc_traits.h'
  '/include/c++/4.8.5/bits/ptr_traits.h'
  '/include/c++/4.8.5/random'
  '/include/c++/4.8.5/cmath'
  '/include/c++/4.8.5/limits'
  '/include/c++/4.8.5/bits/random.h'
  '/include/c++/4.8.5/vector'
  '/include/c++/4.8.5/bits/stl_uninitialized.h'
  '/include/c++/4.8.5/bits/stl_vector.h'
  '/include/c++/4.8.5/bits/stl_bvector.h'
  '/include/c++/4.8.5/bits/vector.tcc'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/opt_random.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/x86intrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/ia32intrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/mmintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/xmmintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/mm_malloc.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/emmintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/pmmintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/tmmintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/smmintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/popcntintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/wmmintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/immintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/avxintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/avx2intrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/lzcntintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/bmiintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/bmi2intrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/fmaintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/f16cintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/rtmintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/xtestintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/rdseedintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/prfchwintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/fxsrintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/xsaveintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/xsaveoptintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/adxintrin.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/pkuintrin.h'
  '/include/c++/4.8.5/bits/random.tcc'
  '/include/c++/4.8.5/numeric'
  '/include/c++/4.8.5/bits/stl_numeric.h'
  '/include/c++/4.8.5/functional'
  '/include/c++/4.8.5/typeinfo'
  '/include/c++/4.8.5/tuple'
  '/include/c++/4.8.5/array'
  '/include/c++/4.8.5/stdexcept'
  '/include/c++/4.8.5/bits/uses_allocator.h'
  '/include/c++/4.8.5/iostream'
  '/include/c++/4.8.5/ostream'
  '/include/c++/4.8.5/ios'
  '/include/c++/4.8.5/bits/ios_base.h'
  '/include/c++/4.8.5/bits/locale_classes.h'
  '/include/c++/4.8.5/bits/locale_classes.tcc'
  '/include/c++/4.8.5/streambuf'
  '/include/c++/4.8.5/bits/streambuf.tcc'
  '/include/c++/4.8.5/bits/basic_ios.h'
  '/include/c++/4.8.5/bits/locale_facets.h'
  '/include/c++/4.8.5/cwctype'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/ctype_base.h'
  '/include/c++/4.8.5/bits/streambuf_iterator.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/ctype_inline.h'
  '/include/c++/4.8.5/bits/locale_facets.tcc'
  '/include/c++/4.8.5/bits/basic_ios.tcc'
  '/include/c++/4.8.5/bits/ostream.tcc'
  '/include/c++/4.8.5/istream'
  '/include/c++/4.8.5/bits/istream.tcc'
  '/include/c++/4.8.5/map'
  '/include/c++/4.8.5/bits/stl_tree.h'
  '/include/c++/4.8.5/bits/stl_map.h'
  '/include/c++/4.8.5/bits/stl_multimap.h'
  '/include/c++/4.8.5/memory'
  '/include/c++/4.8.5/bits/stl_raw_storage_iter.h'
  '/include/c++/4.8.5/ext/concurrence.h'
  '/include/c++/4.8.5/bits/unique_ptr.h'
  '/include/c++/4.8.5/bits/shared_ptr.h'
  '/include/c++/4.8.5/bits/shared_ptr_base.h'
  '/include/c++/4.8.5/backward/auto_ptr.h'
  '/include/c++/4.8.5/set'
  '/include/c++/4.8.5/bits/stl_set.h'
  '/include/c++/4.8.5/bits/stl_multiset.h'
  '/include/c++/4.8.5/cstddef'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/include/c++/4.8.5/unordered_map'
  '/include/c++/4.8.5/bits/hashtable.h'
  '/include/c++/4.8.5/bits/hashtable_policy.h'
  '/include/c++/4.8.5/bits/unordered_map.h'
  '/include/c++/4.8.5/unordered_set'
  '/include/c++/4.8.5/bits/unordered_set.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 17.327s, Critical Path: 1.23s
INFO: 4 processes: 4 local.
FAILED: Build did NOT complete successfully
```

**Comment by mihaimaruseac** [comment] 2019-06-05 15:50
It seems that your toolchain is incomplete

**Comment by byronyi** [comment] 2019-06-05 16:01
I will suggest you to use a Docker container to build TF. Your toolchain seems a little bit..strange.

**Comment by ThisIsIsaac** [comment] 2019-06-05 16:03
I have used docker but that failed as well.

**Comment by gunan** [comment] 2019-06-05 16:08
I have seen this problem when the compiler changes after running `./configure`.
Could you run `bazel clean --expunge`, then retry building?

**Comment by ThisIsIsaac** [comment] 2019-06-05 16:19
@gunan 
I have done so:
```
bazel clean --expunge
./configure
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

but it failed again. I wonder if it is because I am using default compiler -- `gcc` -- as my `nvcc` compiler. 

## Error message
```
ERROR: /home/minds/.cache/bazel/_bazel_minds/7c1f2bd7870d1ecc8754a91ebff0746c/external/com_googlesource_code_re2/BUILD:26:1: undeclared inclusion(s) in rule '@com_googlesource_code_re2//:re2':
this rule is missing dependency declarations for the following files included by 'external/com_googlesource_code_re2/re2/unicode_groups.cc':
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h'
  '/include/c++/4.8.5/string'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++config.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/os_defines.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/cpu_defines.h'
  '/include/c++/4.8.5/bits/stringfwd.h'
  '/include/c++/4.8.5/bits/memoryfwd.h'
  '/include/c++/4.8.5/bits/char_traits.h'
  '/include/c++/4.8.5/bits/stl_algobase.h'
  '/include/c++/4.8.5/bits/functexcept.h'
  '/include/c++/4.8.5/bits/exception_defines.h'
  '/include/c++/4.8.5/bits/cpp_type_traits.h'
  '/include/c++/4.8.5/ext/type_traits.h'
  '/include/c++/4.8.5/ext/numeric_traits.h'
  '/include/c++/4.8.5/bits/stl_pair.h'
  '/include/c++/4.8.5/bits/move.h'
  '/include/c++/4.8.5/bits/concept_check.h'
  '/include/c++/4.8.5/type_traits'
  '/include/c++/4.8.5/bits/stl_iterator_base_types.h'
  '/include/c++/4.8.5/bits/stl_iterator_base_funcs.h'
  '/include/c++/4.8.5/debug/debug.h'
  '/include/c++/4.8.5/bits/stl_iterator.h'
  '/include/c++/4.8.5/bits/postypes.h'
  '/include/c++/4.8.5/cwchar'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/include/c++/4.8.5/cstdint'
  '/include/c++/4.8.5/bits/allocator.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++allocator.h'
  '/include/c++/4.8.5/ext/new_allocator.h'
  '/include/c++/4.8.5/new'
  '/include/c++/4.8.5/exception'
  '/include/c++/4.8.5/bits/atomic_lockfree_defines.h'
  '/include/c++/4.8.5/bits/exception_ptr.h'
  '/include/c++/4.8.5/bits/nested_exception.h'
  '/include/c++/4.8.5/bits/localefwd.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/c++locale.h'
  '/include/c++/4.8.5/clocale'
  '/include/c++/4.8.5/iosfwd'
  '/include/c++/4.8.5/cctype'
  '/include/c++/4.8.5/bits/ostream_insert.h'
  '/include/c++/4.8.5/bits/cxxabi_forced.h'
  '/include/c++/4.8.5/bits/stl_function.h'
  '/include/c++/4.8.5/backward/binders.h'
  '/include/c++/4.8.5/bits/range_access.h'
  '/include/c++/4.8.5/bits/basic_string.h'
  '/include/c++/4.8.5/ext/atomicity.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/gthr.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/gthr-default.h'
  '/include/c++/4.8.5/x86_64-redhat-linux/bits/atomic_word.h'
  '/include/c++/4.8.5/initializer_list'
  '/include/c++/4.8.5/ext/string_conversions.h'
  '/include/c++/4.8.5/cstdlib'
  '/include/c++/4.8.5/cstdio'
  '/include/c++/4.8.5/cerrno'
  '/include/c++/4.8.5/bits/functional_hash.h'
  '/include/c++/4.8.5/bits/hash_bytes.h'
  '/include/c++/4.8.5/bits/basic_string.tcc'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 26.030s, Critical Path: 2.50s
INFO: 15 processes: 15 local.
FAILED: Build did NOT complete successfully
```

**Comment by gunan** [comment] 2019-06-05 16:38
@meteorcloudy @hlopko in case they have any ideas.
@av8ramit in case he ran into similar issues on centos.

**Comment by av8ramit** [comment] 2019-06-05 16:57
My issue was slightly different, it couldn't find the linker so I needed to manually provide the crosstool.

**Comment by ThisIsIsaac** [comment] 2019-06-12 02:35
I am waiting to make a PR but but I cant test out my code. It would be really great if we I can find a way to build from source or using docker.

Thanks again!

**Comment by mihaimaruseac** [comment] 2019-06-12 15:38
Are you by any chance on a 32 bit system?

**Comment by ThisIsIsaac** [comment] 2019-06-12 15:46
No

**Comment by mihaimaruseac** [comment] 2019-06-14 17:16
Cannot reproduce at all, sorry

**Comment by gunan** [comment] 2019-11-08 16:58
As far as I can see, this is a purely bazel issue, where bazel has a problem autodetecting the toolchain on the system.
However, I have no direct solution for it.
Please try reaching out to bazel team, or the sommunity on stackoverflow may have some ideas.

**Comment by gunan** [comment] 2019-11-20 00:25
Closing the issue, as this is a bazel toolchain autodetection problem, on an operating system not supported by us.
You can reach out to bazel team, or try getting help through stackoverflow.

**Closed by gunan** 2019-11-20 00:25 UTC
Labels: subtype:bazel, subtype:centos, type:build/install
