### ISSUE TITLE
TensorFlow 2.x: Model Training Indefinitely in Graph Mode

### ISSUE THREAD

**Issue by jainmilan** [tensorflow/tensorflow#50466] opened 2021-06-25 21:46 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **N/A**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **pip install tensorflow**
- Python version: **python 3.9.5**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am training the model in both the eager execution mode and the graph mode. The model is training well in the eager execution mode, however running for indefinitely in the graph mode. I tried to debug in multiple way with no success.

**Describe the expected behavior**
The model should train in the same way in both eager execution and graph mode. 

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
import numpy as np
import tensorflow as tf

tf.compat.v1.disable_eager_execution() # comment to enable eager execution mode
print("[INFO] Eager mode: ", tf.executing_eagerly()) # For easy reset of notebook state.

class CustomModelV2(tf.keras.Model):
    def __init__(self):
        super(CustomModelV2, self).__init__()
        self.encoder = Encoder(32)
        self.encoder.build(input_shape=(None, 32))
        self.loss_tracker = tf.keras.metrics.Mean(name="loss")
        
    def call(self, inputs, training):
        return self.encoder(inputs, training)
        
    @property
    def metrics(self):
        # We list our `Metric` objects here so that `reset_states()` can be
        # called automatically at the start of each epoch
        # or at the start of `evaluate()`.
        # If you don't implement this property, you have to call
        # `reset_states()` yourself at the time of your choosing.
        return [self.loss_tracker]

    @tf.function
    def train_step(self, data):
        # Unpack the data. Its structure depends on your model and
        # on what you pass to `fit()`.
        x, y = data

        with tf.GradientTape() as tape:
            y_pred = self.call(x, training=True)  # Forward pass

            # Compute the loss value
            # (the loss function is configured in `compile()`)
            r_loss = tf.keras.losses.mean_squared_error(y, y_pred)
            loss = r_loss 

        # Compute gradients
        trainable_vars = self.trainable_variables
        gradients = tape.gradient(loss, trainable_vars)
        
        # Update weights
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
        
        # Update metrics (includes the metric that tracks the loss)
        self.loss_tracker.update_state(loss)
        
        # Return a dict mapping metric names to current value
        return {"loss": self.loss_tracker.result()}

class Encoder(tf.keras.Model):
    def __init__(self, input_size):
        super(Encoder, self).__init__(name = 'Encoder')
        self.input_layer   = DenseLayer(128, input_size, 0.0, 0.0, 'float32')
        self.hidden_layer1 = DenseLayer(128, 128, 0.001, 0.0, 'float32')
        self.dropout_laye1 = tf.keras.layers.Dropout(0.2)
        self.hidden_layer2 = DenseLayer(64, 128, 0.001, 0.0, 'float32')      
        self.dropout_laye2 = tf.keras.layers.Dropout(0.2)
        self.hidden_layer3 = DenseLayer(64, 64, 0.001, 0.0, 'float32')
        self.dropout_laye3 = tf.keras.layers.Dropout(0.2)           
        self.output_layer  = LinearLayer(64, 64, 0.001, 0.0, 'float32')
        
    def call(self, input_data, training):
        fx = self.input_layer(input_data)        
        fx = self.hidden_layer1(fx)
        if training:
            fx = self.dropout_laye1(fx)     
        fx = self.hidden_layer2(fx)
        if training:
            fx = self.dropout_laye2(fx) 
        fx = self.hidden_layer3(fx)
        if training:
            fx = self.dropout_laye3(fx) 
        return self.output_layer(fx)

class LinearLayer(tf.keras.layers.Layer):

    def __init__(self, units, input_dim, weights_regularizer, bias_regularizer, d_type):
        super(LinearLayer, self).__init__()
        self.w = self.add_weight(name='w_linear',
                                shape = (input_dim, units), 
                                initializer = tf.keras.initializers.RandomUniform(
                                    minval=-tf.cast(tf.math.sqrt(6/(input_dim+units)), dtype = d_type), 
                                    maxval=tf.cast(tf.math.sqrt(6/(input_dim+units)), dtype = d_type), 
                                    seed=16751),                                                                   
                                regularizer = tf.keras.regularizers.l1(weights_regularizer), 
                                trainable = True)
        self.b = self.add_weight(name='b_linear',
                                 shape = (units,),    
                                 initializer = tf.zeros_initializer(),
                                 regularizer = tf.keras.regularizers.l1(bias_regularizer),
                                 trainable = True)

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

class DenseLayer(tf.keras.layers.Layer):

    def __init__(self, units, input_dim, weights_regularizer, bias_regularizer, d_type):
        super(DenseLayer, self).__init__()
        self.w = self.add_weight(name='w_dense',
                                 shape = (input_dim, units), 
                                 initializer = tf.keras.initializers.RandomUniform(
                                     minval=-tf.cast(tf.math.sqrt(6.0/(input_dim+units)), dtype = d_type),  
                                     maxval=tf.cast(tf.math.sqrt(6.0/(input_dim+units)), dtype = d_type),  
                                     seed=16751), 
                                 regularizer = tf.keras.regularizers.l1(weights_regularizer), 
                                 trainable = True)
        self.b = self.add_weight(name='b_dense',
                                 shape = (units,),    
                                 initializer = tf.zeros_initializer(),
                                 regularizer = tf.keras.regularizers.l1(bias_regularizer),
                                 trainable = True)

    def call(self, inputs):
        x = tf.matmul(inputs, self.w) + self.b
        return tf.nn.elu(x)

# Just use `fit` as usual
x = tf.data.Dataset.from_tensor_slices(np.random.random((5000, 32)))

y_numpy = np.random.random((5000, 1))
y_numpy[:, 3:] = None
y = tf.data.Dataset.from_tensor_slices(y_numpy)

x_window = x.window(30, shift=10, stride=1)
flat_x = x_window.flat_map(lambda t: t)
flat_x_scaled = flat_x.map(lambda t: t * 2)

y_window = y.window(30, shift=10, stride=1)
flat_y = y_window.flat_map(lambda t: t)
flat_y_scaled = flat_y.map(lambda t: t * 2)

z = tf.data.Dataset.zip((flat_x_scaled, flat_y_scaled)).batch(32).cache().shuffle(buffer_size=32).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

# Stopping criteria if the training loss doesn't go down by 1e-3
early_stop_cb = tf.keras.callbacks.EarlyStopping(
    monitor='loss', min_delta = 1e-3, verbose = 1, mode='min', patience = 3, 
    baseline=None, restore_best_weights=True)

# Construct and compile an instance of CustomModel
model = CustomModelV2()


  
model.compile(optimizer=tf.optimizers.Adagrad(0.01))

history = model.fit(z, epochs=3, callbacks=[early_stop_cb])
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Output in Graph Mode: 
```
WARNING:tensorflow:Output output_1 missing from loss dictionary. We assume this was done on purpose. The fit and evaluate APIs will not be expecting any data to be passed to output_1.
WARNING:tensorflow:From C:\Users\jain432\Anaconda3\envs\tf\lib\site-packages\tensorflow\python\keras\optimizer_v2\adagrad.py:87: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Train on None steps
Epoch 1/3
 479916/Unknown - 667s 1ms/step - batch: 239957.5000 - size: 1.0000 - loss: 2.1716e-04
```

Output in Eager Mode: 
```
Epoch 1/3
468/468 [==============================] - 2s 3ms/step - loss: 0.4173
Epoch 2/3
468/468 [==============================] - 1s 3ms/step - loss: 0.3695
Epoch 3/3
468/468 [==============================] - 1s 3ms/step - loss: 0.3608
```

**Comment by tilakrayal** [comment] 2021-06-28 10:22
@Saduf2019 ,
I was able to reproduce the issue in tv v2.4,v2.5 and nightly.Please find the gist.[Gist1](https://colab.research.google.com/gist/tilakrayal/fefe01827d64a8748282f13088667051/untitled50466.ipynb),[Gist2](https://colab.research.google.com/gist/tilakrayal/10b92d7f7cb04c82b5b677574f99fd80/50466.ipynb)

**Comment by Saduf2019** [comment] 2021-06-30 17:47
@jainmilan 
Can you please refer to [this link](https://stackoverflow.com/questions/60141916/errorrootinternal-python-error-in-the-inspect-module-while-installing-tensorfl) and let us know.

**Comment by jainmilan** [comment] 2021-07-08 06:12
Thanks @Saduf2019 for the response. The link you shared discuss a totally different issue. Do you think it is because of the TensorFlow version and it was supported in the previous version?

**Comment by Saduf2019** [comment] 2021-07-14 15:03
@jainmilan 
You would  need to define steps_per_epoch in model.fit as dataset runs indefinitely

**Comment by jainmilan** [comment] 2021-07-14 15:37
The steps_per_epoch limits the training but don’t you think it is an inconsistent behavior? Also, to do an indefinite training it might be applying a repeat over the dataset which I didn’t use and that changes the data too.

**Comment by Saduf2019** [comment] 2021-07-15 05:05
@jainmilan 
This does not seem like a tensorflow bug, it coding related issue, can you open this in discussion forum or stackover flow as there is a bigger community to answer there.

**Comment by Saduf2019** [comment] 2021-08-05 11:28
Moving this to closed status due to lac of activity.

**Closed by Saduf2019** 2021-08-05 11:28 UTC
Labels: comp:apis, type:bug

**Comment by jainmilan** [comment] 2021-08-05 14:28
@Saduf2019: I don’t see any resolution there. The code should ideally output the same thing in both the graph mode and the eager mode. I have already shared a minimal working example that can replicate the issue.
