### ISSUE TITLE
Faild to build a pip package for TensorFlow with GPU

### ISSUE THREAD

**Issue by bkovalev** [tensorflow/tensorflow#9417] opened 2017-04-24 15:35 UTC
TF master - 24/2/2017

When I build a pip package for TensorFlow with GPU support by invoke the following command:
$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

I see following error;

ERROR: /root/tensorflow/tensorflow/contrib/verbs/BUILD:61:1: C++ compilation of rule '//tensorflow/contrib/verbs:grpc_verbs_service' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 151 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.                                                   
In file included from ./tensorflow/contrib/verbs/grpc_verbs_service.h:25:0,                                       
                 from tensorflow/contrib/verbs/grpc_verbs_service.cc:22:                                          
./tensorflow/core/distributed_runtime/rpc/grpc_call.h:74:28: error: 'core' has not been declared                  
 class UntypedCall : public core::RefCounted {                                                                    
                            ^                                                                                     
./tensorflow/core/distributed_runtime/rpc/grpc_call.h:74:34: error: expected '{' before 'RefCounted'              
 class UntypedCall : public core::RefCounted {                                                                    
                                  ^                                                                               
./tensorflow/core/distributed_runtime/rpc/grpc_call.h:75:2: error: expected primary-expression before 'public'    
  public:                                                                                                         
  ^                                                                                                               
./tensorflow/core/distributed_runtime/rpc/grpc_call.h:75:2: error: expected '}' before 'public'

**Comment by drpngx** [comment] 2017-04-24 16:13
Could you give us more information about gcc versions etc?

/CC @poxvoculi @junshi15 @caisq

**Comment by aselle** [comment] 2017-04-24 16:47
Also, please specify what platform (and linux distribution)

**Comment by caisq** [comment] 2017-04-24 16:54
The date "24/2/2017" in @bkovalev 's description looks like a typo? contrib/verbs wasn't added until very recently.

**Comment by bkovalev** [comment] 2017-04-24 18:58
I installed two day ago same server without any problem.
I am running on Ubuntu 16.04 with gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, Cuda compilation tools, release 8.0, V8.0.61, TF Master,nVidia Version: 375.51, Bazel 0.4.5.

Thanks

**Comment by bkovalev** [comment] 2017-04-24 19:13
I fixed the CROSSTOOL file ( know issue) by edit the text file tensorflow/third_party/gpus/crosstool/CROSSTOOL. 
$ vim ~/tensorflow/third_party/gpus/crosstool/CROSSTOOL.tpl 
b.	Add cxx_builtin_include_directory: "%{cuda_include_path}" (line 125) as below.
cxx_builtin_include_directory: "/usr/lib/gcc/"
cxx_builtin_include_directory: "/usr/local/include"
cxx_builtin_include_directory: "/usr/include"
cxx_builtin_include_directory: "/usr/local/cuda-8.0/include"
tool_path { name: "gcov" path: "/usr/bin/gcov" }

But still have the error

**Comment by aselle** [comment] 2017-04-24 19:41
@jart, do you have any idea if anything we added recently could have caused this?

**Comment by drpngx** [comment] 2017-04-24 20:47
For context, RDMA was introduced here: https://github.com/tensorflow/tensorflow/pull/8943
so it's pretty recent. It worked on Jenkins, and it looks from @bkovalev 's comment that it should have also worked.

It looks like it's a simple include missing that we used to get from transitive includes.

**Comment by drpngx** [comment] 2017-04-24 20:49
You should include `tensorflow/core/lib/core/refcount.h`.

@bkovalev do you mind sending a PR for that?

**Comment by jart** [comment] 2017-04-24 21:15
Would it work if you used GCC 4.x? It comes with Ubuntu. I've seen a lot of problems introduced by GCC 5.x here and there.

**Comment by junshi15** [comment] 2017-04-25 02:01
I can reproduce the issue with gcc 4.8.4.  

refcount.h is here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/verbs/grpc_verbs_service.h#L26

It looks like something else is missing. Looking into it...

**Comment by drpngx** [comment] 2017-04-25 02:25
@bkovalev it needs to be in `grpc_call.h`. That's an error in the code.

**Comment by llhe** [comment] 2017-04-25 02:48
I had the same problem when building RDMA support. Agree with @drpngx .
```
diff --git a/tensorflow/core/distributed_runtime/rpc/grpc_call.h b/tensorflow/core/distributed_runtime/rpc/grpc_call.h
index 35f849c..3b45e7e 100644
--- a/tensorflow/core/distributed_runtime/rpc/grpc_call.h
+++ b/tensorflow/core/distributed_runtime/rpc/grpc_call.h
@@ -16,6 +16,7 @@ limitations under the License.
 #ifndef THIRD_PARTY_TENSORFLOW_CORE_DISTRIBUTED_RUNTIME_RPC_GRPC_CALL_H_
 #define THIRD_PARTY_TENSORFLOW_CORE_DISTRIBUTED_RUNTIME_RPC_GRPC_CALL_H_
 
+#include "tensorflow/core/lib/core/refcount.h"
 #include "tensorflow/core/platform/macros.h"
 
 #include "grpc++/grpc++.h"
```

**Comment by junshi15** [comment] 2017-04-25 02:52
The code compiled fine at commit dd40e9840da886c2a8b296146c709907c0dd3d85, where PR#8943 was merged. But it does not compile at the top of the branch as of now.

**Comment by drpngx** [comment] 2017-04-25 03:03
@llhe did that work for you? If so, could you send a PR?

**Comment by llhe** [comment] 2017-04-25 03:03
@junshi15 This issue is not caused by PR#8934, but an error in `grpc_call.h` which should include `refcount.h`. However, `refcount.h` was luckly included before `grpc_call.h` in `grpc_verbs_service` target (and also other targets). And there should a recent change which removed this indirect include which leads to this compile error.

**Comment by llhe** [comment] 2017-04-25 03:04
@drpngx I made the change and I can submit a PR.

**Comment by drpngx** [comment] 2017-04-25 03:08
@llhe that would be nice! If that fixes the problem, please put `Fixes #9417` in the description. Thanks!

**Closed** 2017-04-25 04:22 UTC
Labels: stat:awaiting response, type:build/install

**Comment by bkovalev** [comment] 2017-04-25 06:31
Thanks a lot!

**Comment by shamoya** [comment] 2017-04-25 09:08
As @llhe said, refcount.h was included before grpc_call.h in #8493

+#include "tensorflow/core/lib/core/refcount.h"
+#include "tensorflow/core/distributed_runtime/rpc/grpc_call.h"

And in #9384

-#include "tensorflow/core/lib/core/refcount.h"
  #include "tensorflow/core/distributed_runtime/rpc/grpc_call.h"
 +#include "tensorflow/core/lib/core/refcount.h"

Not sure I understand why in #9384 the merge operation show conflicts of ~260 files, that were not relevant to the specific pull request.
Working with rebase would have the same effect here ?
