### ISSUE TITLE
Android example using CMake on Windows not working

### ISSUE THREAD

**Issue by vincentbecker** [tensorflow/tensorflow#9049] opened 2017-04-07 17:08 UTC
I installed CPU-only Tensorflow version 1.0 on Windows using the pip installer. I am trying to get the Android example to run using CMake as explained in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android/cmake. I cloned the newest version of the tensorflow repository and created a new Android studio project and followed the instructions from the webpage above by modifying the gradle files.  I already found out that it should be 
`debugCompile project(path: ':TensorFlow-Android-Inference', configuration: 'debug')
releaseCompile project(path: ':TensorFlow-Android-Inference', configuration: 'release')`
instead of 
`debugCompile project(path: ':tensorflow_inference', configuration: 'debug')
releaseCompile project(path: ':tensorflow_inference', configuration: 'release')`
Now, however, I get a build error stating "Error:Project :app declares a dependency from configuration 'releaseCompile' to configuration 'release' which is not declared in the descriptor for project :TensorFlow-Android-Inference."
Has anyone tried this or could anyone point me to a proper explanation of how to use cMake to build the project. 
Any help would be very much appreciated. Thanks.

**Comment by asimshankar** [comment] 2017-04-07 22:22
@andrewharp : Any comments?

**Comment by andrewharp** [comment] 2017-04-07 22:55
@vincentbecker The specific error you're getting here sounds like a Gradle problem. Different versions expose or don't expose default build rules from Android Studio differently. I think for current versions of Gradle the same pattern as in tensorflow/examples/android/build.gradle needs to be followed, so we should probably fix that.

However, even if this is corrected you won't be able to build Android TF on Windows via this approach. The cmake solution actually has to use make internally and so will not actually work on Windows.

We plan to eventually support a 100% cmake build solution. Until then see https://github.com/tensorflow/tensorflow/issues/6385#issuecomment-285208600 for a bash for Windows workaround and also instructions on using prebuilt binaries.

**Comment by asimshankar** [comment] 2017-04-08 01:10
Closing this as a duplicate of #6385

**Comment by andrewharp** [comment] 2017-04-10 20:39
We'll still need to fix whatever the issue is with contrib/android/cmake/ causing the specific error given here, so reopening to track.

**Comment by itsmeolivia** [comment] 2017-06-16 19:10
hey andrew, are you still actively working on this?

**Comment by tensorflowbutler** [comment] 2017-12-22 07:46
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:12
Nagging Assigneee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-23 23:13
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tensorflowbutler** [comment] 2018-02-07 13:48
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by CorvetteCole** [comment] 2018-02-26 04:19
Hey @andrewharp I'm running in this issue while trying to build using CMake on Ubuntu 16.04. I am making progress on this issue but I've gotten sort of stuck so I'd appreciate it if you would take another look. Thanks!

**Comment by tensorflowbutler** [comment] 2018-03-12 13:47
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-28 00:52
Nagging Assignee @andrewharp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-11 18:47
Nagging Assignee @andrewharp: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:08
Nagging Assignee @andrewharp: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:36
Nagging Assignee @andrewharp: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:03
Nagging Assignee @andrewharp: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 18:55
Nagging Assignee @andrewharp: It has been 134 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:51
Nagging Assignee @andrewharp: It has been 149 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 12:55
Nagging Assignee @andrewharp: It has been 164 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:38
Nagging Assignee @andrewharp: It has been 179 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:34
Nagging Assignee @andrewharp: It has been 194 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:41
Nagging Assignee @andrewharp: It has been 209 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:42
Nagging Assignee @andrewharp: It has been 224 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-23 12:45
Nagging Assignee @andrewharp: It has been 239 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment] 2018-10-26 21:13
Automatically closing due to lack of recent activity. Please open a new issue if this persist with the latest tensorflow version by provinding all the information requested in this template.Thanks!

**Closed** 2018-10-26 21:14 UTC
Labels: type:build/install
