### ISSUE TITLE
Error with name of 'op'?

### ISSUE THREAD

**Issue by Narukamiko** [tensorflow/tensorflow#8185] opened 2017-03-08 07:44 UTC
```
Traceback (most recent call last):
  File "AI_control_4layer.py", line 218, in <module>
    writer)
  File "/home/longfei/Repository/drl_navigation/saved_neural_qlearning.py", line 61, in __init__
    self.create_variables()
  File "/home/longfei/Repository/drl_navigation/saved_neural_qlearning.py", line 148, in create_variables
    self.train_op = self.optimizer.apply_gradients(gradients)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 412, in apply_gradients
    self._create_slots(var_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/rmsprop.py", line 101, in _create_slots
    self._get_or_make_slot(v, val_rms, "rms", self._name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/optimizer.py", line 639, in _get_or_make_slot
    named_slots[var] = slot_creator.create_slot(var, val, op_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 101, in create_slot
    return _create_slot_var(primary, val, '')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/slot_creator.py", line 55, in _create_slot_var
    slot = variable_scope.get_variable(scope, initializer=val, trainable=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 684, in _get_single_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 226, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 322, in _init_from_args
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/state_ops.py", line 178, in variable_op_v2
    shared_name=shared_name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 708, in _variable_v2
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2398, in create_op
    self._add_op(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2099, in _add_op
    "is already used" % op.name)
ValueError: cannot add op with name q_network/W_conv1/RMSProp as that name is already used
```

**Comment by prb12** [comment] 2017-03-08 17:43
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version and the code/steps necessary to reproduce your problem. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by xiaop1987** [comment] 2017-03-10 02:05
I think this problem is coursed by duplicated name of Variables.

**Comment by prb12** [comment] 2017-03-10 02:09
@xiaop1987 Looks very likely, but hard to tell from the scant information in the original problem report.  It does seem unlikely to be a bug.

**Comment by Kai-Gao** [comment] 2017-03-29 19:53
I've just encountered the same erro ,  so I was wondering did you fixed the bug? Thx!

**Comment by aselle** [comment] 2017-04-27 20:10
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by aselle** 2017-04-27 20:10 UTC
Labels: stat:awaiting response
