### ISSUE TITLE
Op type not registered 'CudnnRNNParamsSize' in binary

### ISSUE THREAD

**Issue by tadas-subonis** [tensorflow/tensorflow#12730] opened 2017-08-31 13:28 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10 64bit
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.6
- **CUDA/cuDNN version**: Cude - 8.0, cuDNN - 6.0
- **GPU model and memory**: M1000M
- **Exact command to reproduce**: 

### Describe the problem
The tutorial RNN model fails due to: "Op type not registered 'CudnnRNNParamsSize' in binary"

### Source code / logs
https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py

```
b'unknown' 1.3.0
2017-08-31 16:25:32.021526: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-31 16:25:32.021822: W C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-31 16:25:32.959216: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:955] Found device 0 with properties: 
name: Quadro M1000M
major: 5 minor: 0 memoryClockRate (GHz) 1.0715
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.65GiB
2017-08-31 16:25:32.959478: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:976] DMA: 0 
2017-08-31 16:25:32.959642: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:986] 0:   Y 
2017-08-31 16:25:32.959848: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro M1000M, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "C:/Work/Projects/tensorflow-models/tutorials/rnn/ptb/ptb_word_lm.py", line 526, in <module>
    tf.app.run()
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "C:/Work/Projects/tensorflow-models/tutorials/rnn/ptb/ptb_word_lm.py", line 470, in main
    m = PTBModel(is_training=True, config=config, input_=train_input)
  File "C:/Work/Projects/tensorflow-models/tutorials/rnn/ptb/ptb_word_lm.py", line 135, in __init__
    output, state = self._build_rnn_graph(inputs, config, is_training)
  File "C:/Work/Projects/tensorflow-models/tutorials/rnn/ptb/ptb_word_lm.py", line 174, in _build_rnn_graph
    return self._build_rnn_graph_cudnn(inputs, config, is_training)
  File "C:/Work/Projects/tensorflow-models/tutorials/rnn/ptb/ptb_word_lm.py", line 186, in _build_rnn_graph_cudnn
    params_size_t = self._cell.params_size()
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\python\ops\cudnn_rnn_ops.py", line 597, in params_size
    direction=self._direction)[0]
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\contrib\cudnn_rnn\ops\gen_cudnn_rnn_ops.py", line 283, in cudnn_rnn_params_size
    name=name)
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2632, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1911, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 654, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\Programs\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "C:\Programs\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'CudnnRNNParamsSize' in binary running on ULTRALISK. Make sure the Op and Kernel are registered in the binary running in this process.
```

**Comment by quaeler** [comment] 2017-08-31 16:35
I can confirm that the Op exists in the `build_pip_package.runfiles/org_tensorflow/tensorflow/contrib/cudnn_rnn/python/ops/_cudnn_rnn_ops.so` built from the head of master (yesterday), so perhaps this is an issue that has been fixed and will be in the 1.4 release.

**Comment by michaelisard** [comment] 2017-09-01 18:23
It looks as if that tutorial was not present in 1.3 so it is possible it won't work unless you use a more recent version. Can you try that?

**Comment by yangyixiaof** [comment] 2017-09-14 15:51
I have the answer, this seems a bug when using cuDnn. The parameter --model=... in your command line must be small. In another word, you must run this tutorial using the command like: "python ptb_word_lm.py --data_path=... --model=small". Through reading the code, I found that if I do not use cuDnn which means I type the following command: "python ptb_word_lm.py --data_path=... --model=**medium**" or "python ptb_word_lm.py --data_path=... --model=**large**", such errors will be eliminated. Hope this will help.

**Comment by sfailsthy** [comment] 2017-10-14 06:26
I also encounter this issue.I also use the Win 10,but I installed Tensorflow-GPU from pip,and the version of tensorflow is also 1.3.0 . As @yangyixiaof  sayed , this issue is eliminated when I try to set "the model" as medium".

**Comment by traveller59** [comment] 2017-10-19 15:07
After install tf_nightly_gpu-1.5.0.dev, this problem is solved.

**Comment by tensorflowbutler** [comment] 2017-12-20 01:19
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:16
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-18 19:18
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-06 07:41
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by michaelisard** [comment] 2018-02-06 16:32
Closing due to lack of activity, and because the most recent comment indicates the problem was solved.

**Closed by michaelisard** 2018-02-06 16:32 UTC
Labels: stat:awaiting response

**Comment by devharsh** [comment] 2018-07-16 19:16
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-5-0e97fbc26e6d> in <module>()
      5     serialized_graph = fid.read()
      6     od_graph_def.ParseFromString(serialized_graph)
----> 7     tf.import_graph_def(od_graph_def, name='')

C:\Users\310211146\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py in new_func(*args, **kwargs)
    430                 'in a future version' if date is None else ('after %s' % date),
    431                 instructions)
--> 432       return func(*args, **kwargs)
    433     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    434                                        _add_deprecated_arg_notice_to_docstring(

C:\Users\310211146\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    487         try:
    488           results = c_api.TF_GraphImportGraphDefWithResults(
--> 489               graph._c_graph, serialized, options)  # pylint: disable=protected-access
    490           results = c_api_util.ScopedTFImportGraphDefResults(results)
    491         except errors.InvalidArgumentError as e:

NotFoundError: Op type not registered 'NonMaxSuppressionV3' in binary running on YY041775. Make sure the Op and Kernel are registered in the binary running in this process.
