### ISSUE TITLE
Tensorflow v2 tensorflow.python.ops.linalg_ops.svd hangs

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#28518] opened 2019-05-08 11:31 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0a-gpu
- Python version: 3.7.3
- CUDA/cuDNN version: 10.0
- GPU model and memory: RTX 2060

**Describe the current behavior**
```python
import tensorflow as tf
from tensorflow.python.ops import linalg_ops

mat = tf.random.uniform([2048, 2048])

s, u, v = linalg_ops.svd(mat)
```
When running this example with my tensorflow-gpu installation it hangs (until I cancel with ctrl+c, which takes very long):
```
2019-05-08 13:20:05.994717: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-05-08 13:20:06.002398: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-05-08 13:20:06.250271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1467] Found device 0 with properties:
name: GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.71
pciBusID: 0000:1f:00.0
totalMemory: 6.00GiB freeMemory: 4.89GiB
2019-05-08 13:20:06.256846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1546] Adding visible gpu devices: 0
2019-05-08 13:20:06.803341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1015] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-08 13:20:06.806295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021]      0
2019-05-08 13:20:06.810187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1034] 0:   N
2019-05-08 13:20:06.812341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1149] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4618 MB memory) -> physical GPU (device: 0,
name: GeForce RTX 2060, pci bus id: 0000:1f:00.0, compute capability: 7.5)
2019-05-08 13:20:07.023250: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles
for stream 000001C2BFA888A0
Traceback (most recent call last):
  File ".\svd_check.py", line 6, in <module>
    s, u, v = linalg_ops.svd(mat)
  File "C:\Progams\Miniconda\envs\tf2-gpu\lib\site-packages\tensorflow\python\ops\linalg_ops.py", line 418, in svd
    tensor, compute_uv=compute_uv, full_matrices=full_matrices, name=name)
  File "C:\Progams\Miniconda\envs\tf2-gpu\lib\site-packages\tensorflow\python\ops\gen_linalg_ops.py", line 2409, in svd
    "full_matrices", full_matrices)
KeyboardInterrupt
```
On tensorflow most recent v1 version it just works.

Also, when running the following it works as well:
```python
import tensorflow as tf
from tensorflow.python.ops import linalg_ops

mat = tf.random.uniform([2048, 2048])

with tf.device('/device:CPU:0'):
    s, u, v = linalg_ops.svd(mat)
```

**Comment by achandraa** [comment] 2019-05-10 04:43
I tried running the two snippet on Colab using TensorFlow GPU version 2.0.0-alpha0 and noticed that both ran without error but there was difference in execution time.

**Comment by sleighsoft** [comment] 2019-05-10 10:33
Hmm, strange. I don't know if it helps: Nvidia Driver Version 419.67

**Comment by ymodak** [comment] 2019-05-13 17:39
@sleighsoft  You mentioned that it worked in most recent v1 version, Can you please confirm the version you used? Also, It was tf-gpu installation correct? In addition to that can you please upgrade your [nvidia driver version](https://www.nvidia.com/Download/index.aspx?lang=en-us#O) and test again. Thanks!

**Comment by sleighsoft** [comment] 2019-05-13 20:06
Working on: tensorflow-gpu==1.13.1

Updated NVIDIA driver to 430.64 still not working

**Comment by aaroey** [comment] 2019-05-13 21:58
I cannot reproduce. What I did is `pip install tf-nightly-gpu-2.0-preview` then run the python script mentioned above, it took some time to run but it did return.

**Comment by sleighsoft** [comment] 2019-05-21 09:50
@aaroey I did some more testing. Indeed, it finishes.
But there is a huge time difference between running SVD on CPU vs GPU.

Tested on Titan X Pascal
- On CPU: 2.8 seconds
- On GPU: 60 seconds

**Comment by aaroey** [comment] 2019-05-22 00:46
@smit-hinsu would you please help to take a look?

**Comment by smit-hinsu** [comment] 2019-05-22 01:45
SVD GPU kernel is known to be slower compared to the CPU version.
See https://github.com/tensorflow/tensorflow/issues/13603#issuecomment-418153277

Still, it makes sense to see if there was any further regression between graph mode and eager mode or TF version 1.13 and 1.14.

**Comment by smit-hinsu** [comment] 2019-06-09 23:32
Duplicate of #13603

I don't see any difference in runtime between eager and graph mode or between TensorFlow versions 1.13 and 1.14. All take around 63 seconds. However, I see a regression between versions 1.12 and 1.13. I will update the other bug.

**Closed by smit-hinsu** 2019-06-09 23:32 UTC
Labels: 2.0.0-alpha0, comp:gpu, comp:ops, type:bug/performance
