### ISSUE TITLE
Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed

### ISSUE THREAD

**Issue by lion-wang** [tensorflow/tensorflow#15172] opened 2017-12-07 01:52 UTC
ERROR: /Users/lion/Documents/opensoft/tensorflow/tensorflow/python/BUILD:2749:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed: link_dynamic_library.sh failed: error executing command external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o ... (remaining 573 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lgomp

**Comment by tensorflowbutler** [comment] 2017-12-07 13:34
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2017-12-22 19:00
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue? Please update the label and/or status accordingly.

**Comment by sxhysj** [comment] 2018-01-04 14:08
It is still an issue. I follow the guide: https://gist.github.com/smitshilu/53cf9ff0fd6cdb64cca69a7e2827ed0f

Have I written custom code?
I removed all align(sizeof(T)) from following files:
tensorflow/core/kernels/depthwise_conv_op_gpu.cu.cc
tensorflow/core/kernels/split_lib_gpu.cu.cc
tensorflow/core/kernels/concat_lib_gpu.impl.cu.cc

OS Platform and Distribution
Mac OS X 10.13.2

TensorFlow installed from
source 1.4, date: 20180104

TensorFlow version
1.4

Bazel version
0.9.0-homebrew

CUDA/cuDNN version
9.1/7.0

GPU model and memory
GTX 1080Ti, 11GB

Exact command to reproduce
bazel build --config=cuda --config=opt --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH //tensorflow/tools/pip_package:build_pip_package

**Comment by Jovonni** [comment] 2018-01-05 16:56
Interested in this as well, as I am getting:

![screen shot 2018-01-05 at 11 53 41 am](https://user-images.githubusercontent.com/4885245/34619146-2bfbc582-f20f-11e7-8051-3b15c8bce044.png)

I am running:

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures

on ubuntu 1404 as well @tensorflowbutler

**Comment by JCBrouwer** [comment] 2018-01-17 17:17
Also seeing the same issue:

Slightly different versions from @sxhysj 

Have I written custom code?
I removed all align(sizeof(T)) from following files:
tensorflow/core/kernels/depthwise_conv_op_gpu.cu.cc
tensorflow/core/kernels/split_lib_gpu.cu.cc
tensorflow/core/kernels/concat_lib_gpu.impl.cu.cc

OS Platform and Distribution
Mac OS X 10.12

TensorFlow version
1.5

Bazel version
0.5.4

CUDA/cuDNN version
9.0/7.0

GPU model and memory
GTX 1080Ti, 11GB

**Comment by JCBrouwer** [comment] 2018-01-18 15:31
Solution was to comment 

`linkopts = [“-lgomp”]`

in tensorflow/third_party/gpus/cuda/BUILD.tpl.

Via: https://metakermit.com/2017/compiling-tensorflow-with-gpu-support-on-a-macbook-pro/

**Comment by tensorflowbutler** [comment] 2018-02-06 07:31
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-20 19:34
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-07 13:12
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-25 01:00
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by asimshankar** [comment] 2018-04-03 06:17
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

@JCBrouwer : Thanks for the update, hopefully that helps others. Note that the guide linked to isn't owned by TensorFlow team and in general for GPU support on macOS (which I'm guessing is being used here, but can't be sure since the template wasn't filled out) we rely on community support.

**Closed by asimshankar** 2018-04-03 06:17 UTC
Labels: stat:awaiting response

**Comment by Carix0n** [comment] 2018-08-30 11:08
@Jovonni did you resolve the issue?

**Comment by legatoo** [comment] 2019-02-18 04:03
> Interested in this as well, as I am getting:
> 
> ![screen shot 2018-01-05 at 11 53 41 am](https://user-images.githubusercontent.com/4885245/34619146-2bfbc582-f20f-11e7-8051-3b15c8bce044.png)
> 
> I am running:
> 
> bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
> 
> on ubuntu 1404 as well @tensorflowbutler

same issue. did you resolve it?

**Comment by ralpha** [comment] 2020-03-24 23:37
> Solution for me was to comment
> 
> `linkopts = [“-lgomp”]`
> 
> in tensorflow/third_party/gpus/cuda/BUILD.tpl. I now have a working build :)
> 
> Via: https://metakermit.com/2017/compiling-tensorflow-with-gpu-support-on-a-macbook-pro/

This fixed the problem for me.
Changed line 160 in the file tensorflow/third_party/gpus/cuda/BUILD.tpl in the section `cc_library(name = "cusparse",` from:
`linkopts = ["-lgomp"],` to
`#linkopts = ["-lgomp"],`
And recompiled/continued compiling the build. Build completed successfully. :D

**Comment by IrisDinge** [comment] 2020-12-21 09:11
@ralpha OMG u really save me!
Thks a lotttttttt!

**Comment by jung-youjin** [comment] 2023-03-03 06:38
@Jovonni Did you manage to solve your issue?
