### ISSUE TITLE
UnboundLocalError: local variable `packed` referenced before assignment

### ISSUE THREAD

**Issue by gehring** [tensorflow/tensorflow#32506] opened 2019-09-13 17:29 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.7.3

**Describe the current behavior**
Some specific set of circumstances skip over assigning `packed` to a value.

https://github.com/tensorflow/tensorflow/blob/551b67c8dff2d3656cb1858f1cb11beb049dafaf/tensorflow/python/util/nest.py#L472

**Describe the expected behavior**
The local variable `packed` should have a value set.

**Code to reproduce the issue**
Throw an `IndexError` in [this call](https://github.com/tensorflow/tensorflow/blob/551b67c8dff2d3656cb1858f1cb11beb049dafaf/tensorflow/python/util/nest.py#L461) and make sure the [if statement](https://github.com/tensorflow/tensorflow/blob/551b67c8dff2d3656cb1858f1cb11beb049dafaf/tensorflow/python/util/nest.py#L467) is not entered.

I wish I had a portable example for you but I'm not quite sure why my code triggering this path and I don't have much time to investigate the root cause, but I can confirm that is an error that I have encountered naturally. It isn't just hypothetical.

**Other info / logs**
TF portion of the stack trace:
```
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 516, in map_structure
    expand_composites=expand_composites)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/nest.py", line 450, in pack_sequence_as
    return _sequence_like(structure, packed)
UnboundLocalError: local variable 'packed' referenced before assignment
```

**Comment by ravikyram** [comment] 2019-09-16 10:24
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here. Thanks!

**Comment by tensorflowbutler** [comment] 2019-10-01 12:32
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ravikyram** [comment] 2019-10-03 13:38
@gehring 
Please, let us know is this still an issue?. If so please provide a minimal standalone code to reproduce the issue reported here.Thanks!

**Comment by ravikyram** [comment] 2019-10-11 11:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-10-11 11:39 UTC
Labels: TF 1.14, stat:awaiting response, type:support
