### ISSUE TITLE
TensorflowDebugger does not dump Stack/Pack/Concat nodes

### ISSUE THREAD

**Issue by blake-varden** [tensorflow/tensorflow#10303] opened 2017-05-30 21:37 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
1.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0/5.1.5
- **GPU model and memory**:
Titan X Pascal
- **Exact command to reproduce**:
```
import sys
import tensorflow as tf
from tensorflow.python import debug as tf_debug

base = tf.ones([10], dtype=tf.float32, name='base')
stacked = tf.stack([base, base], name='stacked')
concat = tf.concat([[base], [base]], axis=0, name='concat')

session = tf.Session()
session = tf_debug.LocalCLIDebugWrapperSession(session)

with session.as_default():
    res = session.run([ stacked, concat])
print res
```

### Describe the problem

When using the TensorflowDebugger with stacked/concated, the stacked/concated nodes do not appear in the set of dumped nodes once a run has completed.  In addition nodes that fed into these nodes are not dumped.

**Comment by asimshankar** [comment] 2017-05-31 00:00
@caisq : Mind taking a look?

**Comment by caisq** [comment] 2017-05-31 00:36
@blake-varden This is not a bug. The reason why you see no data dumped is because every node is constant folded in the graph set up by your code. `tf.ones` defines a TF constant. So all the downstream tensors like `stacked` and `concat` are effectively constant. TF's graph optimization knows that and folds all nodes into one. 

If you replace `tf.ones` with a `tf.Variable`, you'll see the data dumped:

```python
import numpy as np
import tensorflow as tf
from tensorflow.python import debug as tf_debug

base = tf.Variable(np.ones([10]), dtype=tf.float32, name="base")
stacked = tf.stack([base, base], name='stacked')
concat = tf.concat([[base], [base]], axis=0, name='concat')

session = tf.Session()
session.run(tf.global_variables_initializer())

session = tf_debug.LocalCLIDebugWrapperSession(session)
res = session.run([ stacked, concat])
```

This behavior is documented in a relatively obscure placed:
https://www.tensorflow.org/api_docs/python/tfdbg/watch_graph

> N.B.: 1. Under certain circumstances, the Tensor may not get actually watched (e.g., if the node of the Tensor is constant-folded during runtime). 

For more on constant folding in TF, see:
https://www.tensorflow.org/api_docs/python/tf/OptimizerOptions

TFDBG is working as intended as I just checked in the `tensorflow/tensorflow:nightly` docker image.

**Comment by caisq** [comment] 2017-05-31 00:42
Re-opening the issue as a doc bug. I plan to add a Q&A item for this behavior.

**Closed** 2017-06-14 03:56 UTC
Labels: type:docs
