### ISSUE TITLE
Request to support ERF function for TFL

### ISSUE THREAD

**Issue by Jerry-Ge** [tensorflow/tensorflow#60663] opened 2023-05-22 21:02 UTC
`tf.math.erf` is supported here: https://www.tensorflow.org/api_docs/python/tf/math/erf

TFLite is missing the erf implementation: https://www.tensorflow.org/mlir/tfl_ops#tfllstm_mlirtfllstmop

**Comment by pkgoogle** [comment] 2023-06-07 21:24
Hi @Jerry-Ge,

I believe you can use it now as a Select TF Operator, please review: https://www.tensorflow.org/lite/guide/ops_select. However you need to add "tf.lite.OpsSet.SELECT_TF_OPS" to your converter.target_spec.supported_ops list, as in the example in the link:
```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops. <-- Add this line
]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

Let us know if this resolves your issue.

**Comment by Jerry-Ge** [comment] 2023-06-07 21:28
cool, thansk @pkgoogle , let us try. 

cc @wonjeon

**Comment by Jerry-Ge** [comment] 2023-06-07 21:49
Still not working with the following errors I got: 

`RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you invoke the Flex delegate before inference.Node number 0 (Flex) failed to prepare.`

I'm using ` tf.lite.TFLiteConverter.from_concrete_functions` which is not `from_saved_model`

**Comment by pkgoogle** [comment] 2023-06-07 22:11
Hi @Jerry-Ge, what platform/OS are you creating the interpreter on?

**Comment by Jerry-Ge** [comment] 2023-06-07 22:12
> 

 Ubuntu 18.04.6 LTS

**Comment by pkgoogle** [comment] 2023-06-07 22:14
Are you doing it in Python, C++, something else? Are you using the benchmark tool? (Do you have the source code/context around your interpreter available?)

**Comment by Jerry-Ge** [comment] 2023-06-07 22:18
> Are you doing it in Python, C++, something else? Are you using the benchmark tool? (Do you have the source code/context around your interpreter available?)

I'm using Python. No benchmark tool is used. 

The interpreter being used is similar to this: 
```
interpreter = tf.lite.Interpreter(model_path=some_path)
interpreter.allocate_tensors() // This line is causing the above errors. 
```

**Comment by pkgoogle** [comment] 2023-06-07 22:23
Per this section: https://www.tensorflow.org/lite/guide/ops_select#python

It should be installed when installing the TF package, how did you install Tensorflow or Tensorflow Lite? (If you installed TF Lite only, you need to install TF as well), it is probably worth trying it out in a fresh environment/venv/conda env/docker and see if that helps.

**Comment by Jerry-Ge** [comment] 2023-06-07 22:28
I think my Tensorflow installation should be good. 

Besides TFL, the TF dialect for the erf function is also not supported: 
```
## Error: Results INVALID_MLIR test_erf_1_f32: Error 1 running command:
/tensorflow/bazel-bin/tensorflow/compiler/mlir/tf-mlir-translate --graphdef-to-mlir --tf-enable-shape-inference-on-import --tf-output-arrays=result erf/test_erf_1_f32/model.pb -o erf/test_erf_1_f32/test_tf.preopt.mlir --tf-input-arrays placeholder_0 --tf-input-shapes 1,
```

**Comment by pkgoogle** [comment] 2023-06-07 22:33
Let's table the discussion on the TF dialect (might need to be a separate issue). Erf is in the allowlist: https://www.tensorflow.org/lite/guide/op_select_allowlist. From my perspective it looks like an install issue, can you upload the .lite model? A toy example which reproduces the issue is fine, any code used to make/convert the model will also help w/ context. Thanks!

**Comment by Jerry-Ge** [comment] 2023-06-07 22:47
> Let's table the discussion on the TF dialect (might need to be a separate issue). Erf is in the allowlist: https://www.tensorflow.org/lite/guide/op_select_allowlist. From my perspective it looks like an install issue, can you upload the .lite model? A toy example which reproduces the issue is fine, any code used to make/convert the model will also help w/ context. Thanks!

Yes, for sure. Thanks for the help, you can find a dummy model here: https://github.com/Jerry-Ge/tfl_models/blob/main/erf_model.tflite

**Comment by Jerry-Ge** [comment] 2023-06-07 23:09
Thanks for the support! I found the interpreter issue: 

I'm adding the additional `experimental_op_resolver_type=OpResolverType.BUILTIN_REF,` when instantiate that. Removing that solves the interpreter issues. 

However, as I mentioned above, the overall support for ERF is still missing with more details in this ticket: https://github.com/tensorflow/tensorflow/issues/60809

**Comment by pkgoogle** [comment] 2023-06-07 23:30
Thanks @Jerry-Ge, please feel free to close this issue as we can track the other issue in the other case instead.

**Closed** 2023-06-08 01:18 UTC
Labels: type:feature, type:support, comp:lite
