### ISSUE TITLE
Compiling a custom Op - Eigen including-loop

### ISSUE THREAD

**Issue by idofr** [tensorflow/tensorflow#9042] opened 2017-04-07 11:36 UTC
### System Info.
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: Yes
- *TensorFlow installed from (source or binary)?*: binary
- *TensorFlow version*: latest
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*: 8.0/5.1
- *GPU Model and Memory*: Quadro k1100m
- *Exact command to reproduce*: trying to build

### The problem

I'm tyring to build the code in
https://github.com/davidstutz/tensorflow-cpp-op-example
for Windows. The Windows version of Tf does not install with the source code so I cloned the repo and added the path to CMake. I then executed CMake as described in
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake
Yet the problem seems to be that the Eigen files don't do anything but re-including themselves. 

Were they not meant to be included? Am I using some wrong flags that result in those imports? Other ideas? suggestions?

Cheers,

**Comment by blowtorch55** [comment] 2017-04-07 12:01
hi im new to this stuff not sure what im doing


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by asimshankar** [comment] 2017-04-07 17:27
@idofr : I'm not sure I udnerstand what you mean by "Yet the problem seems to be that the Eigen files don't do anything but re-including themselves." Could you please elaborate on what the problem is and the exact sequence of steps to reproduce it?

Separately, @gunan @av8ramit @mrry : Seems like the Windows pip package doesn't include the header files so the technique in https://www.tensorflow.org/extend/adding_an_op doesn't apply. Should we be including the header files now (or in release 1.2 onwards) since it seems that #8217 allows custom op libraries to be loaded in Windows?

**Comment by mrry** [comment] 2017-04-07 17:58
@asimshankar That would make sense. Is there a canonical list of what header files are included? Given a list of filenames or globs, it should be fairly easy to add them to the PIP directory.

/cc @guschmue FYI.

**Comment by guschmue** [comment] 2017-04-07 18:16
sure, totally for this. I think the list of header files should be the same as the one in the linux pip.
There is maybe one more thing needed: building the dll makes a few compiler flags/defines and I wonder if we should **generate** a build.bat or a CMakeLists.txt template that we include in the pip so people don't need to deal with it ... should not be very hard to create this.

**Comment by gunan** [comment] 2017-04-07 18:29
@avr8amit lets block 1.1 on the addition of missing headers into windows
pip package.

On Apr 7, 2017 11:17 AM, "Guenther Schmuelling" <notifications@github.com>
wrote:

sure, totally for this. I think the list of header files should be the same
as the one in the linux pip.
There is maybe one more thing needed: building the dll makes a few compiler
flags/defines and I wonder if we should *generate* a build.bat or a
CMakeLists.txt template that we include in the pip so people don't need to
deal with it ... should not be very hard to create this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/9042#issuecomment-292612639>,
or mute the thread

**Comment by asimshankar** [comment] 2017-04-07 19:40
@mrry, @av8ramit : The list of header files to include would be defined by the bazel target [`//tensorflow/tools/pip_package:include_headers`](https://github.com/tensorflow/tensorflow/blob/63b2f99/tensorflow/tools/pip_package/BUILD#L28). 

Perhaps we'll have to generate the list for CMakeLists.txt once and have some bazel test that checks that the two are always in sync.

**Comment by idofr** [comment] 2017-04-09 10:51
Hi, sorry for the late respnose.

Thank you all so much for the replies, and yes, including the headers in the pip package would eventually save a lot of time, since the compilation takes a while. It would also probably make life a bit easier for everyone, as it would make sure that the same flags and configs are used in build builds.

@asimshankar 
I mean something similar to 
third_party/eigen3/unsupported/Eigen/CXX11/Tensor
( https://raw.githubusercontent.com/tensorflow/tensorflow/master/third_party/eigen3/unsupported/Eigen/CXX11/Tensor )

It does some minimal definitions and mostly just re-includes itself.

@vit-stepanovs was kind enough to reply to my email and shared the following link with me
https://gist.github.com/guschmue/2908e4411edc2faef6ddfe87a2ce4a1d
This seems to be exactly what I need (thanks @guschmue). Cmakes manages to create the VS project now and I'll compile either later on today or tomorrow at some point. I'll let you know how it went.
In case it's working though, it'd probably be a good idea to include this additional file into the main repo (assuming @guschmue won't mind)

**Comment by guschmue** [comment] 2017-04-10 14:47
Ah, the equivalent of 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/adding_an_op/BUILD
for cmake ... sure. We eed to figure if this should be a version that depends on the source tree or if this should be standalone version that only depends on the python package once the header files are include in the python wheel.

For your https://raw.githubusercontent.com/tensorflow/tensorflow/master/third_party/eigen3/unsupported/Eigen/CXX11/Tensor issue: there should be a ifdef to prevent recursion but I think the main issue is that it is trying to include another Tensor from external/eigen_archive/unsupported/Eigen/CXX11/Tensor which is extracted during build. Maybe that 2nd Tensor file is not there, for example the tree wasn't build.

**Comment by idofr** [comment] 2017-04-10 14:54
That Tensor issue was actually the reason I guessed to begin with that my flags were wrong. It basically seems like the file should not be included anyways. But yeah, I also added a few ifdef's there, just didn't submit a pull request for such a minor issue which probably doesn't affect the community anyways.

**Comment by idofr** [comment] 2017-04-11 11:40
Is there anything special to do after the compilation to include the new Op?
I'm using the Ackermann_ops example, compiled the headers and then the Op and then tried to run the ackermann_test.py script.
It returns the following error though

`
ERROR: testBasic (__main__.AckermannTest)

Traceback (most recent call last):
  File "C:/tf_compile/tensorflow/tensorflow/user_ops/ackermann_test.py", line 30, in testBasic
    ackermann = tf.load_op_library(library_filename)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: C:\tf_compile\tensorflow\tensorflow\user_ops\ackermann_ops.so not found
`

The actual Tf version I'm using was installed directly from the pip package

**Comment by guschmue** [comment] 2017-04-11 17:32
just tried this on my box and had the same issue. Silly mistake: 
my example cmake copied to ackermann_ops.so where the test app was looking for ackermann_op.so. After fixing that it works on my box.

**Comment by idofr** [comment] 2017-04-11 21:38
That was the first thing I've noticed but it didn't make a difference.
Do you link the entire path or just the file name?

**Comment by guschmue** [comment] 2017-04-12 14:37
just tried this on a fresh master. After the the normal build is done, I build with user op with
MSBuild /p:Configuration=RelWithDebInfo /p:BuildProjectReferences=false ackermann_ops.vcxproj

python \src\tensorflow\tensorflow\user_ops\ackermann_test.py
and
cd python \src\tensorflow\tensorflow\user_ops\
python ackermann_test.py

both work ok.

**Comment by asimshankar** [comment] 2017-04-14 17:48
@idofr : Are you able to build with the instructions from @guschmue ?

**Comment by idofr** [comment] 2017-04-14 18:29
Building was not the problem, including the .so file was the issue

**Comment by drpngx** [comment] 2017-04-17 17:28
@idofr Did you use the resource loader? Did you try to load it by hand?

**Comment by itsmeolivia** [comment] 2017-06-16 21:09
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Closed by itsmeolivia** 2017-06-16 21:09 UTC
Labels: stat:awaiting response, type:build/install

**Comment by av8ramit** [comment] 2017-06-16 21:15
I have added the functionality to include headers in the cmake build.
