### ISSUE TITLE
Cached augmentation and BATCH_SIZE not used in CycleGAN tutorial 

### ISSUE THREAD

**Issue by kaosdev** [tensorflow/tensorflow#48826] opened 2021-04-29 16:34 UTC
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/generative/cyclegan

## Description of issue (what needs changing):

Seems like the data pipeline for the CycleGAN is using cache after augmenting the data.
Is this intentional? Doesn't that make augmentation useless?

Another "problem" in the data pipeline: a batch size of 1 is used even if there is a 'BATCH_SIZE' variable at the start of the tutorial.

**Comment by bhack** [comment] 2021-04-29 23:48
@nikitamaia @lamberta @MarkDaoust We have two Official cyclegan tutorial for the community:
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/generative/cyclegan.ipynb
https://github.com/keras-team/keras-io/blob/master/examples/generative/cyclegan.py

**Comment by bhack** [comment] 2021-04-29 23:56
The Web renderings are:
https://keras.io/examples/generative/cyclegan/
https://www.tensorflow.org/tutorials/generative/cyclegan

**Comment by lamberta** [comment] 2021-04-29 23:56
The Keras project maintains a separate documentation site at https://keras.io/

We import some of their guide docs [here on tf.org](https://www.tensorflow.org/guide/keras/sequential_model) but not their community examples/tutorials.

**Comment by bhack** [comment] 2021-04-30 00:11
Yes I know but in cases like this one I think that it could be a little bit confusing for users when we have almost the same content (with the same potential question). Also, cause there is any specific claim that one documentation is community best effort maintained and the other one is  TensorFlow maintained.

**Comment by lamberta** [comment] 2021-04-30 00:21
Happy to help merge changes to [tutorial](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/generative/cyclegan.ipynb) in tensorflow/docs. For the Keras project, you'll have to work over there :)

We maintain the tensorflow/docs repo for official tensorflow.org tutorials. But we don't see an issue if the Keras project maintains Keras-specific docs.

**Comment by bhack** [comment] 2021-04-30 00:32
Ok I understand. Just to note that If there is something interesting in this ticket you will need two issues, two PRs, two reviews on both the repositories.

**Comment by Saduf2019** [comment] 2021-05-24 16:17
@kaosdev 
Can you please confirm if the issue is resolved and  move this to closed status as the pr is merged.

**Comment by kaosdev** [comment] 2021-05-24 16:26
I can confirm the issue with the BATCH_SIZE is resolved.

I can't see any change about the cached augmentation.

I don't know if it's planned to fix also this issue or not.

**Closed** 2021-08-05 22:22 UTC
Labels: type:docs-bug, stat:awaiting tensorflower, comp:keras
