### ISSUE TITLE
[TensorFlow 2.0] Taking a slice of a Keras Input layer gives a tensor with unknown shape

### ISSUE THREAD

**Issue by xlambein** [tensorflow/tensorflow#29917] opened 2019-06-18 16:21 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Mac OS X 10.14.5**
- TensorFlow installed from (source or binary): **binary**
- TensorFlow version (use command below): **v2.0.0-beta0-16-g1d91213fe7 2.0.0-beta1**
- Python version: **3.6.8**
- CUDA/cuDNN version: **don't have a GPU**
- GPU model and memory: **don't have a GPU**

**Describe the current behavior**

If I create an input layer with Keras and take a slice of it, the slice has unknown shape:

```python
>>> inputs = tf.keras.Input((10, 10))
>>> inputs.shape
TensorShape([None, 10, 10])
>>> slice = inputs[:,:,:5]
>>> slice.shape
TensorShape(None)
```

This is a problem when I want to use this slice in something else, e.g. here with a softmax:

```python
>>> tf.keras.activations.softmax(slice)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[path_to_my_env]/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 66, in softmax
    elif ndim > 2:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Describe the expected behavior**

I'd expect `slice` to have shape `TensorShape([None, 10, 5])`.

**Code to reproduce the issue**

```python
import tensorflow as tf

inputs = tf.keras.Input((10, 10))
assert inputs.shape.as_list() == [None, 10, 10]  # This works
assert inputs[:,:,:5].shape.as_list() == [None, 10, 5]  # Raises ValueError
```

**Comment by gadagashwini** [comment] 2019-06-19 10:08
I was able to reproduce the above mentioned issue on Colab with Tensorflow 2.0.0.beta1. Thanks!

**Comment by aaronlyt** [comment] 2019-06-21 06:51
I have the problem, any solution?

**Comment by xlambein** [comment] 2019-06-21 07:15
@aaronlyt I found a temporary fix to get my code running.  You can call `set_shape` on a tensor to enforce a specific shape on it.  In my example it would look like this:
```python
>>> inputs = tf.keras.Input((10, 10))
>>> slice = inputs[:,:,:5]
>>> slice.shape
TensorShape(None)
>>> slice.set_shape(inputs.shape[:-1].concatenate(5))
>>> slice.shape
TensorShape([None, 10, 5])
```

**Comment by aaronlyt** [comment] 2019-06-21 07:31
Thanks, it works

**Comment by martinwicke** [comment] 2019-06-21 23:05
I believe the object returned from Input is simply a Tensor -- so this looks like a bug or missing feature in the slide shape function? @aselle is this known?

**Comment by ymodak** [comment] 2019-06-28 23:37
The code snippet works in TF 1.14 .  However fails with TF 2.0 nightly (2.0.0-dev20190628)

**Comment by ymodak** [comment] 2019-08-09 18:23
This is fixed with latest tf 2.0 nightly version '2.0.0-dev20190809'. Thanks!

**Comment by martinwicke** [comment] 2019-08-09 18:32
@omalleyt12 was the fixing commit before or after 2.0 branch cut? I'd like to make sure the release has the fix.

**Comment by omalleyt12** [comment] 2019-08-09 20:23
@martinwicke oops sorry for not updating this, this (and other related loss-of-shape bugs) were fixed before the cut

**Closed by omalleyt12** 2019-08-09 20:23 UTC
Labels: 2.0.0-beta0, comp:keras, stat:awaiting tensorflower, type:bug
