### ISSUE TITLE
opcode 'SUB' version '3' in tfllite_runtime on Windows

### ISSUE THREAD

**Issue by nfisdnf986** [tensorflow/tensorflow#44237] opened 2020-10-22 18:46 UTC
**System information**
- Ubuntu 18.04, Nvidia driver 430.4, CUDA 10.1
- tf-nightly: 2.4.0-dev20201022, and
- **tflite_runtime: 2.1.0.post1**

Converted keras-model with tf-nightly. This seems to be incompatible with tflite_runtime.

Inference test script:

```
import numpy as np
import tensorflow as tf
from tflite_runtime.interpreter import Interpreter

# interpreter = tf.lite.Interpreter(model_path="<path_to_wts_file>.tflite")
interpreter = Interpreter(model_path="<path_to_wts_file>.tflite")

input_details = interpreter.get_input_details()

interpreter.resize_tensor_input(input_details[0]['index'], (1, 64, 64, 64, 1))
input_details = interpreter.get_input_details()

interpreter.allocate_tensors()

input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)

interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()

output_details = interpreter.get_output_details()
output_data = interpreter.get_tensor(output_details[0]['index'])
```

The above works fine when using tf-nightly with:
```
import tensorflow as tf
interpreter = tf.lite.Interpreter(model_path="<path_to_wts_file>.tflite")
```

When trying to execute the same with **tflite_runtime**, it fails to load the model:
```
from tflite_runtime.interpreter import Interpreter
interpreter = Interpreter(model_path="<path_to_wts_file>.tflite")
```

Error:
```
Traceback (most recent call last):
  File "tfliteTest.py", line 13, in <module>
    interpreter = Interpreter(model_path="_<path_to_wts_file>_.tflite")
  File "/home/venv/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
ValueError: Didn't find op for builtin opcode 'SUB' version '3'
Registration failed.
```
Is there a nightly build of tflite_runtime?

**Comment by ymodak** [comment] 2020-10-30 18:10
You are required to use TF Lite runtime that supports `Select TF Ops`.
You can try updating build.gradle dependencies with
`
dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly'
}
`
See https://www.tensorflow.org/lite/guide/ops_select#run_inference

**Comment by nfisdnf986** [comment] 2020-11-02 21:52
This option isn't applicable for the  [TensorFlow Lite Interpreter pip package](https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter) version, right? Which version of TF Lite Runtime supports `Select TF Ops` ?

**Comment by pourfard** [comment] 2020-11-28 16:31
when i run this command :

`CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh windows`

there is an error:

```
ERROR: C:/porsapp/tensorflow/tensorflow/tensorflow/core/common_runtime/BUILD:1651:1: Illegal ambiguous match on configurable attribute "deps" in //tensorflow/core/common_runtime:core_cpu_internal:
//tensorflow:windows
//tensorflow:no_gcp_support
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//tensorflow/lite/python/interpreter_wrapper:_pywrap_tensorflow_interpreter_wrapper' failed; build aborted:
```

but when i run this:

`tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh`

there is no error.

I've checked out Tensorflow r.2.4. Do you know what the problem is?

@nfisdnf986

**Comment by pourfard** [comment] 2020-12-03 15:14
I finally build tflite_runtime successfully by removing `--config=noaws --config=nogcp --config=nohdfs --config=nonccl` options from `build_pip_package_with_bazel.sh`. The result file is about 26MB but still I got this error:

```
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 0 (FlexFusedBatchNormV3) failed to prepare.
Node number 1 (IF) failed to prepare.
```

I think 'CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true' does not work. Because when I build the original tensorflow package and use `tensorflow.lite.python.interpreter` there is no error.

**Comment by abattery** [comment] 2020-12-03 23:10
This is expected. The newer version of the TFLite converter assumes that the model will be used at the same version or the future version. So, at least, you need to use the TF 2.4.0 runtime for your model.

**Comment by abattery** [comment] 2020-12-03 23:13
@terryheo could you take a look at this issue?  It is related to build TFLite + Flex runtime at head.

**Comment by terryheo** [comment] 2020-12-07 09:35
Verified the issue. Working on making a fix.

**Comment by nfisdnf986** [comment] 2020-12-15 18:28
Sorry about the delayed reply. @pourfard Did the above fix work for you?

@terryheo Thanks for adding that change. I haven't been able to build master branch on Windows, r.2.3 and r2.4 build fine.

Any suggestions for the following error?

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\complex(354): error C2039: 'copysign': is not a member of '`global namespace''
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\complex(354): error C3861: 'copysign': identifier not found
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by pourfard** [comment] 2020-12-17 14:11
It did not work again:

1- I clone tensorflow repository
2- I run `python ./configure.py`
3- I run `CUSTOM_BAZEL_FLAGS="--define=tflite_pip_with_flex=true" tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh windows`
*- here is the generated whl file ( It is about 26MB which I think it means it is compiled with FlexDelegate, without it, the wheel file is about 1-2MB)
4- I run `pip3.6.exe install .\tflite_runtime-2.5.0-cp36-cp36m-win_amd64.whl`
5- I got the same error:

```
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 0 (FlexFusedBatchNormV3) failed to prepare.
Node number 1 (IF) failed to prepare.
```
 
@terryheo

**Comment by pourfard** [comment] 2020-12-17 14:14
@nfisdnf986  Yes, it works now,

Thanks a lot, @terryheo

**Comment by nfisdnf986** [comment] 2020-12-18 23:47
Thank you for the wheel @pourfard. When I try to build with the same command `build_pip_package_with_bazel.sh windows`, it starts the script in MSYS and gets stuck at `setup_with_bazel.py`. Did you make any changes other than the `--config` ones mentioned about to the shell script? 

```
INFO: Found 1 target...
INFO: Deleting stale sandbox base C:/users//_bazel_/hya7usi5/sandbox
[4 / 231] [Prepa] BazelWorkspaceStatusAction stable-status.txt
Target //tensorflow/lite/python/interpreter_wrapper:_pywrap_tensorflow_interpreter_wrapper up-to-date (nothing to build)
INFO: Elapsed time: 11.714s, Critical Path: 0.81s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
+ cp /c/Users//Desktop/temp/build-from-src/tensorflow/tensorflow/lite/tools/pip_package/../../../../bazel-bin/tensorflow/lite/python/interpreter_wrapper/_pywrap_tensorflow_interpreter_wrapper.pyd /c/Users//Desktop/temp/build-from-src/tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/tflite_runtime
+ chmod u+w /c/Users//Desktop/temp/build-from-src/tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.pyd
+ cd /c/Users//Desktop/temp/build-from-src/tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3
+ case "${TENSORFLOW_TARGET}" in
+ [[ -n windows ]]
+ [[ -n '' ]]
+ python3 setup_with_bazel.py bdist bdist_wheel


```

**Comment by Termina1** [comment] 2021-01-11 21:31
> Sorry about the delayed reply. @pourfard Did the above fix work for you?
> 
> @terryheo Thanks for adding that change. I haven't been able to build master branch on Windows, r.2.3 and r2.4 build fine.
> 
> Any suggestions for the following error?
> 
> ```
> 
> ERROR: C:/users//desktop/build-from-src/tensorflow/tensorflow/python/BUILD:5259:1: C++ compilation of rule '//tensorflow/python:_tf_stack.so' failed (Exit 2): cl.exe failed: error executing command
>   cd C:/users//_bazel_/poa7uci7/execroot/org_tensorflow
> ...
> ...
> ...
> cl : Command line warning D9035 : option 'experimental:preprocessor' has been deprecated and will be removed in a future release
> cl : Command line warning D9036 : use 'Zc:preprocessor' instead of 'experimental:preprocessor'
> cl : Command line warning D9002 : ignoring unknown option '-fno-strict-aliasing'
> cl : Command line warning D9002 : ignoring unknown option '-fexceptions'
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\complex(354): error C2039: 'copysign': is not a member of '`global namespace''
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\complex(354): error C3861: 'copysign': identifier not found
> Target //tensorflow/tools/pip_package:build_pip_package failed to build
> ```

Having the same issue trying to build tensorflow from master on windows. The problem seems to be about <complex> library, but I don't understand what's wrong. I have exactly the same error with the same version of MSVC.

**Comment by mihaimaruseac** [comment] 2021-02-17 16:14
The `copysign` issue is caused by MSVC. See #46902, https://www.gitmemory.com/issue/OpenImageIO/oiio/2799/752372181, https://github.com/python/cpython/pull/23326

**Comment by tilakrayal** [comment] 2022-06-14 12:32
@nfisdnf986,
This issue was addressed in this MSVC repo issue. Could you take a look at this [issue](https://github.com/microsoft/vcpkg/issues/15369) and let us know if the issue still persists. Thank you!

**Closed** 2022-06-28 13:48 UTC
Labels: stat:awaiting response, type:support, stalled, comp:lite
