### ISSUE TITLE
Bazel stuck during build tensorflow.

### ISSUE THREAD

**Issue by onlymeal** [tensorflow/tensorflow#717] opened 2016-01-07 11:33 UTC
mlds-ws2@mldsws2-ThinkStation-P500:~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
.......
INFO: Loading package: 

-----------------------------------------------------------------------------------
And stop. After 1~2 hours, doesn't work anything.
I have 3 computer. 
1 is server. 2 CPU and TITAN X 3EA. -> This machine does work well.
But 2, 3 are desktop. 1 CPU and TITAN X or GTX 980 1EA -> Stuck while build tensorflow.
I did format and reinstall ubuntu and necessary program, 3 times. Results are same.
Please help me.

**Comment by skearnes** [comment] 2016-01-07 15:32
I've had some strange java-related issues with Ubuntu that caused similar behavior. Doing a complete shutdown (not a restart) and then rebooting after waiting 10-15 seconds seems to work for me (no idea why).

**Comment by wchan** [comment] 2016-01-07 16:17
possible duplicate of: https://github.com/tensorflow/tensorflow/issues/628

did u try the fix in that thread? remove tensorboard from the BUILD

**Comment by onlymeal** [comment] 2016-01-08 02:44
Thnks skearnes. I solved this problem through cold starting.

**Comment by wchan** [comment] 2016-01-08 20:36
can confirm... weirdiest bug, cold start fixes problem but reboot does not....

**Comment by vrv** [comment] 2016-01-12 05:48
@lberki, @davidzchen, @damienmg in case they know the cause of these hangs, or at least are aware of them.

**Comment by damienmg** [comment] 2016-01-12 09:00
Can we have the full log of such a problem? Maybe with -s?
Also `bazel info` and more information about the system (e.g. number of execution unit, amount of RAM, system version) would be useful.

**Comment by martinwicke** [comment] 2016-01-28 03:31
Closing since this affects an older version of bazel. If it persists, please file a bug with bazel including debug information.

**Closed by martinwicke** 2016-01-28 03:31 UTC

**Comment by igor0** [comment] 2017-07-17 07:07
I hit bazel hangs on Ubuntu that looked similar. In my case, there were a bunch of "linux-sandbox" processes that were in uninterruptible sleep ('D' state shown in ps). Looking at stack traces, the linux-sandbox processes were hung in the kernel in the NFS client.

I had a stale NFS mount pointed at a server that was no longer live. I've had the system in this state for weeks, but it didn't impact anything I was doing. I brought up an NFS server on the IP address where NFS mount was pointed to, and this allowed me to unmount. After that, bazel started running without issues.

I didn't investigate further after resolving my issue, but I suspect that as a part of creating the sandbox, user namespace creation enumerates the mounts. If the system has a hung mount, this will hang bazel. This was surprising to me (the user) because the hung mount had no relation to the directory where I was running bazel.
