### ISSUE TITLE
"The tensorboard module is not an IPython extension." in Google Colab

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#28554] opened 2019-05-09 14:24 UTC
I am running the `image_summaries.ipynb` notebook from this [tutorial](https://www.tensorflow.org/tensorboard/r2/image_summaries) on Colab. Even on Colab, `%load_ext tensorboard` is not working and the message is - 

`The tensorboard module is not an IPython extension.`

TensorFlow version:  2.0.0-dev20190509

**Comment by achandraa** [comment] 2019-05-10 08:45
I tried running the tutorial on Colab but was not able to reproduce the issue. However while running it on jupyter notebook, I do hit it.

**Comment by sayakpaul** [comment] 2019-05-10 10:50
Okay.

**Comment by valb21** [comment] 2019-05-10 13:33
I think that you can try it :  %load_ext tensorboard.notebook

**Comment by sayakpaul** [comment] 2019-05-10 15:00
That worked @valb21. Thanks

**Comment by Shivanshmundra** [comment] 2019-05-20 13:04
@sayakpaul Now since ```tensorboard.notebook``` is depreciated, this error still pops up.

**Comment by sayakpaul** [comment] 2019-05-21 15:24
Cc: @ymodak

**Comment by ymodak** [comment] 2019-05-21 20:53
@sayakpaul I was able to execute the colab successfully in latest tf nightly build.(TensorFlow version:  2.0.0-dev20190520) Can you please confirm? Thanks!

**Comment by sayakpaul** [comment] 2019-05-22 09:37
> @sayakpaul Now since `tensorboard.notebook` is depreciated, this error still pops up.
@Shivanshmundra I am on `2.0.0-alpha0` locally and hence I am able to use the `tensorboard.notebook`.

**Comment by sayakpaul** [comment] 2019-05-22 09:41
@ymodak on Colab, it runs. But locally, I did not check with `tf-nightly` since I use the local setup for work. However, the `tensorboard.notebook` works just fine locally.

**Comment by ymodak** [comment] 2019-05-22 17:44
With ```tf-nightly``` it should work on your local as well since on colab we use ```tf-nightly```. I will close this issue now, feel free to reopen if you still have problems. Thanks!

**Closed by ymodak** 2019-05-22 17:44 UTC
Labels: 2.0, comp:tensorboard, stat:awaiting response, type:support

**Comment by nikolaosmparoutis** [comment] 2019-06-04 21:19
If with   tf-nightly and %load_ext tensorboard still throws the exception as it happened to me
Runtime -> Restart and Run all 
solves it

**Comment by Laobiz** [comment] 2019-06-24 08:03
I still run into this issue even with restarting the runtime. I am not able to use %load_ext tensorboard.notebook.

**Comment by vjpr** [comment] 2021-11-10 18:28
Here is the code that is called when running `%load_ext tensorboard`. It is handled by IPython.

It basically looks in your venv site-packages for `tensorboard`, and if it finds it, then it calls `load_ipython_extension` in that module.

For `tensorboard@2.7` `load_ipython_extension` does not exist. This is the problem.

```python
    def load_extension(self, module_str):
        """Load an IPython extension by its module name.

        Returns the string "already loaded" if the extension is already loaded,
        "no load function" if the module doesn't have a load_ipython_extension
        function, or None if it succeeded.
        """
        if module_str in self.loaded:
            return "already loaded"

        from IPython.utils.syspathcontext import prepended_to_syspath

        with self.shell.builtin_trap:
            if module_str not in sys.modules:
                with prepended_to_syspath(self.ipython_extension_dir):
                    mod = import_module(module_str)
                    if mod.__file__.startswith(self.ipython_extension_dir):
                        print(("Loading extensions from {dir} is deprecated. "
                               "We recommend managing extensions like any "
                               "other Python packages, in site-packages.").format(
                              dir=compress_user(self.ipython_extension_dir)))
            mod = sys.modules[module_str]
            if self._call_load_ipython_extension(mod):
                self.loaded.add(module_str)
            else:
                return "no load function"
```

**Comment by vjpr** [comment] 2021-11-10 18:42
Here is the commit that broke it: https://github.com/tensorflow/tensorboard/commit/d9092143511cb04e4bfc904820305f1be45c67b3#diff-9e231460ca998d6884f936ea1c13c1eef8ef7164479999a472373c6ee210cb50

@wchargin 

It looks like the function was relocated to `tensorboard/__init__.py` which is not in the published python package (I can't see it in my `site-packages`).
