### ISSUE TITLE
TensorFlow Android demo crashes on start

### ISSUE THREAD

**Issue by PatrickGuo** [tensorflow/tensorflow#3319] opened 2016-07-14 20:27 UTC
I installed the TensorFlow on my mac and tried the Android demo. It is confusing that it's all fine with compiling to .apk, but the application crashes as soon as it starts on my Nexus5 cellphone.

### Environment info
Operating System: Mac OS X
Android SDK: 24.0.0
Android NDK: r10e (will encounter problems when building with bazel if using latest v12)
Bazel: 0.1.4
Cellphone OS: Android 6

I tried using adb to install the application, and everything seems perfectly fine until I launched the application. Before that, I have already checked that the camera permission is fine. As soon as I open the application, it will immediately crash. I grabbed the log from my device. Besides, I also compared the log with those generated by a successfully running demo. The main difference starts from:
 **07-14 14:00:46.044  2754  2754 E tensorflow: CameraConnectionFragment: Couldn't find any suitable preview size**
Could anyone help me on finding out what cause this problem? The complete log is attached below.

### Logs or other output that would be helpful
07-14 14:00:45.722   773  1502 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.tensorflow.demo/.CameraActivity (has extras)} from uid 10022 on display 0
07-14 14:00:45.735   202   811 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
07-14 14:00:45.767   202   811 D AudioFlinger: mixer(0xb4100000) throttle end: throttle time(9)
07-14 14:00:45.767  2754  2754 I art     : Late-enabling -Xcheck:jni
07-14 14:00:45.768   773   947 I ActivityManager: Start proc 2754:org.tensorflow.demo/u0a84 for activity org.tensorflow.demo/.CameraActivity
07-14 14:00:45.800  2734  2734 W System  : ClassLoader referenced unknown path: /system/priv-app/MediaProvider/lib/arm
07-14 14:00:45.815  2734  2734 W System  : ClassLoader referenced unknown path: /system/priv-app/DownloadProvider/lib/arm
07-14 14:00:45.858  2754  2754 W linker  : /data/app/org.tensorflow.demo-1/lib/arm/libtensorflow_demo.so: unused DT entry: type 0x1d arg 0x10ff60a
07-14 14:00:45.871  1146  1929 D GCM     : GcmService start Intent { act=com.google.android.checkin.CHECKIN_COMPLETE flg=0x10 cmp=com.google.android.gms/.gcm.GcmService (has extras) } com.google.android.checkin.CHECKIN_COMPLETE
07-14 14:00:45.875  1566  1566 D ChimeraCfgMgr: Loading module com.google.android.gms.kids from APK com.google.android.gms
07-14 14:00:45.876  1566  1566 I Kids    : [GCoreUtils] Current gmscore version, 8186438 is smaller than the required version 8400000
07-14 14:00:45.907  1385  1385 V UserPresentBroadcastReceiver: Received Intent { act=android.intent.action.USER_PRESENT flg=0x24000010 cmp=com.google.android.gms/.auth.trustagent.UserPresentBroadcastReceiver }.
07-14 14:00:45.937  2754  2788 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
07-14 14:00:45.979  1408  1408 W LocationOracleImpl: Not started: ignore location
07-14 14:00:45.981  1408  1408 E LocationReceiver: Received bad location: null
07-14 14:00:45.984  1408  1408 E LocationReceiver: Received bad location: null
07-14 14:00:45.990  2754  2788 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
07-14 14:00:45.994  2754  2788 I OpenGLRenderer: Initialized EGL, version 1.4
07-14 14:00:46.025  1258  1258 I Keyboard.Facilitator: onFinishInput()
07-14 14:00:46.026  2754  2754 I CameraManagerGlobal: Connecting to camera service
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 3264x2448
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 3200x2400
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 2592x1944
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 2048x1536
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 1920x1080
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 1600x1200
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 1280x960
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 1280x768
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 1280x720
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 1024x768
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 800x600
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 800x480
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 720x480
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 640x480
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 352x288
07-14 14:00:46.043  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 320x240
07-14 14:00:46.044  2754  2754 I tensorflow: CameraConnectionFragment: Not adding size: 176x144
07-14 14:00:46.044  2754  2754 E tensorflow: CameraConnectionFragment: Couldn't find any suitable preview size
07-14 14:00:46.049   202   887 I CameraService: CameraService::connect call (PID 2754 "org.tensorflow.demo", camera ID 0) for HAL version default and Camera API version 2
07-14 14:00:46.052   202   887 I CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=0
07-14 14:00:46.052   202   887 I Camera2ClientBase: Camera 0: Opened. Client: org.tensorflow.demo (PID 2754, UID 10084)
07-14 14:00:46.052   202   887 I CameraDeviceClient: CameraDeviceClient 0: Opened
07-14 14:00:46.057   202   887 D mm-camera-intf: mm_camera_open: dev name = /dev/video1, cam_idx = 1
07-14 14:00:46.061   217   217 I mm-camera-sensor: module_sensor_start_session:584 session 1
07-14 14:00:46.074  2696  2732 I MediaStoreImporter: Update: incremental Added music: 0 Updated music: 0 Deleted music: 0 Created playlists: 0 Updated playlists: 0 Deleted playlists: 0 Inserted playlist items: 0 Deleted playlist items: 0 Removed orphaned playlist items: 0
07-14 14:00:46.075  2696  2696 D MusicLifecycle: com.google.android.music.store.MediaStoreImportService generated event: Service destroyed
07-14 14:00:46.076   773  1275 I ActivityManager: Killing 2280:com.google.android.configupdater/u0a27 (adj 15): empty #17
07-14 14:00:46.102   217   217 I mm-camera: gyro_module_start_session: Enter
07-14 14:00:46.102   217   217 I mm-camera: gyro_module_start_session: Init DSPS
07-14 14:00:46.103   217   217 E mm-camera: Failed to open sensor1 port
07-14 14:00:46.103   217   217 I mm-camera: gyro_module_start_session: dsps_proc_init() failed
07-14 14:00:46.103   217   217 I mm-camera: gyro_module_get_port: Exit failure
07-14 14:00:46.103   217   217 I mm-camera: cpp_module_start_session:352, info: starting session 1
07-14 14:00:46.113   773  1275 I ActivityManager: Killing 2255:com.google.android.apps.gcs/u0a25 (adj 15): empty #18
07-14 14:00:46.122   217  2793 I mm-camera: cpp_thread_func:55: cpp_thread entering the polling loop...
07-14 14:00:46.122   217   217 I mm-camera: cpp_module_start_session:433, info: cpp_thread created.
07-14 14:00:46.122   217   217 I mm-camera: cpp_module_start_session:436, info: session 1 started.
07-14 14:00:46.122   217   217 I mm-camera: c2d_module_start_session:246, info: starting session 1
07-14 14:00:46.122   217   217 I mm-camera: c2d_module_start_session:284, info: c2d_thread created.
07-14 14:00:46.122   217  2794 I mm-camera: c2d_thread_func:39: c2d_thread entering the polling loop...
07-14 14:00:46.124   217   217 I mm-camera: c2d_module_start_session:306, info: session 1 started.
07-14 14:00:46.125   217   217 I mm-camera-sensor: module_module_set_session_data:2667 max delay 2 report dSelay 1
07-14 14:00:46.125   217   217 D mm-camera: module_faceproc_set_session_data:1987] Per frame control 2 1
07-14 14:00:46.125   202   887 D mm-camera-intf: mm_camera_open:  opened, break out while loop
07-14 14:00:46.125  1872  1878 E ANDR-PERF-LOCK: Failed to apply optimization for resource: 4 level: 0
07-14 14:00:46.131  2754  2786 I tensorflow: CameraConnectionFragment: Opening camera preview: 3264x2448
07-14 14:00:46.139   202   887 W CameraDeviceClient: createStream: Camera 0: Forcing asynchronous mode for stream
07-14 14:00:46.139   202   887 W CameraDeviceClient: createStream: Camera 0: Overriding format 0x1 to IMPLEMENTATION_DEFINED
07-14 14:00:46.140   202  2542 E CameraDeviceClient: createStream: bufferProducer must not be null
--------- beginning of crash
07-14 14:00:46.141  2754  2786 E AndroidRuntime: FATAL EXCEPTION: CameraBackground
07-14 14:00:46.141  2754  2786 E AndroidRuntime: Process: org.tensorflow.demo, PID: 2754
07-14 14:00:46.141  2754  2786 E AndroidRuntime: java.lang.IllegalArgumentException: Bad argument passed to camera service
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:114)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at $Proxy1.createStream(Unknown Source)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.hardware.camera2.impl.CameraDeviceImpl.configureStreamsChecked(CameraDeviceImpl.java:429)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(CameraDeviceImpl.java:561)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:476)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment.createCameraPreviewSession(CameraConnectionFragment.java:471)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment.access$400(CameraConnectionFragment.java:63)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment$2.onOpened(CameraConnectionFragment.java:144)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-14 14:00:46.141  2754  2786 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-14 14:00:46.159   773   792 I ActivityManager: Displayed org.tensorflow.demo/.CameraActivity: +404ms
07-14 14:00:46.162   773  1503 W ActivityManager:   Force finishing activity org.tensorflow.demo/.CameraActivity

**Comment by andrewharp** [comment] 2016-07-14 22:24
Hi, could you please update to hazel 0.3.0 and try again?

The demo should definitely work on a stock nexus 5. Have you made any changes to the code at all, like modifying the model parameters? It uses the input size to pick preview size.

**Comment by PatrickGuo** [comment] 2016-07-14 23:30
I used to build with bazel 0.3.0, but it tells me that `ERROR: /tensorflow/WORKSPACE:70:1: new_git_repository rule //external:iron-ajax' s name field must be a legal workspace name.`. According to issue [#1047](https://github.com/tensorflow/tensorflow/issues/1047), I switched back to bazel 0.1.4.

**Comment by PatrickGuo** [comment] 2016-07-14 23:35
By the way my TensorFlow version is: 0.9.0 mac os x CPU only. I installed using python: `# Mac OS X, CPU only, Python 2.7:
(tensorflow)$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0-py2-none-any.whl`

**Comment by PatrickGuo** [comment] 2016-07-15 02:17
Just git clone the master branch from TensorFlow, and upgrade Bazel to 0.3.0, NDK to v12. The building is still fine without previously appeared errors. However, the app still crash on the phone for a different reason. Attached is the log:

07-14 22:07:56.070  2364  2382 I tensorflow: CameraConnectionFragment: Getting assets.
07-14 22:07:56.072  2364  2382 E art     : No implementation found for int org.tensorflow.demo.TensorflowClassifier.initializeTensorflow(android.content.res.AssetManager, java.lang.String, java.lang.String, int, int, int, float, java.lang.String, java.lang.String) (tried Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow and Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow__Landroid_content_res_AssetManager_2Ljava_lang_String_2Ljava_lang_String_2IIIFLjava_lang_String_2Ljava_lang_String_2)
--------- beginning of crash
07-14 22:07:56.073  2364  2382 E AndroidRuntime: FATAL EXCEPTION: ImageListener
07-14 22:07:56.073  2364  2382 E AndroidRuntime: Process: org.tensorflow.demo, PID: 2364
07-14 22:07:56.073  2364  2382 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for int org.tensorflow.demo.TensorflowClassifier.initializeTensorflow(android.content.res.AssetManager, java.lang.String, java.lang.String, int, int, int, float, java.lang.String, java.lang.String) (tried Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow and Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow__Landroid_content_res_AssetManager_2Ljava_lang_String_2Ljava_lang_String_2IIIFLjava_lang_String_2Ljava_lang_String_2)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at org.tensorflow.demo.TensorflowClassifier.initializeTensorflow(Native Method)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at org.tensorflow.demo.TensorflowImageListener.initialize(TensorflowImageListener.java:84)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment.createCameraPreviewSession(CameraConnectionFragment.java:540)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment.access$400(CameraConnectionFragment.java:63)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at org.tensorflow.demo.CameraConnectionFragment$2.onOpened(CameraConnectionFragment.java:155)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:134)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-14 22:07:56.073  2364  2382 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pkpp1233** [comment] 2016-07-15 07:52
I'm seeing the same issue except on a stock Nexus 5x. Only difference is I'm using bazel 2.0.

**Comment by andrewharp** [comment] 2016-07-15 12:17
@PatrickGuo initializeTensorflow() is a native method; can you tell if Bazel is building the native libs? Try `unzip -v bazel-bin/tensorflow/examples/android/tensorflow_demo.apk | grep libtensorflow_demo.so` and you should see output like:
` 5163140  Defl:N  1753712  66% 1980-01-01 00:00 7b8de845  lib/armeabi-v7a/libtensorflow_demo.so`

Also can you build with `-s --verbose_failures` and attach the build log please?

@pkpp1233 Are you seeing the preview size error or the no implementation error?

**Comment by PatrickGuo** [comment] 2016-07-15 14:39
@andrewharp Attached is the building log. I also tried the `unzip | grep` command and the output is pretty the same as yours `14545924  Defl:N  3554961  76%  01-01-80 00:00  27d80c72  lib/armeabi-v7a/libtensorflow_demo.so`. 
[build-log.txt](https://github.com/tensorflow/tensorflow/files/366201/build-log.txt)

**Comment by andrewharp** [comment] 2016-07-15 15:13
@PatrickGuo Strange, it seems like it's building the native libs just fine. I'd also expect it to fail on the static loadLibrary call if there was a problem loading the .so itself, but it doesn't seem to be doing that.

Have you made any changes at all to the code? Changing package names or method signatures?

**Comment by kokozaurz** [comment] 2016-07-15 19:29
Having the same issue.…

**Comment by andrewharp** [comment] 2016-07-15 19:33
@kokozaurz Which issue, are you seeing the preview size error or the no implementation error?

**Comment by kokozaurz** [comment] 2016-07-15 19:39
It is adding size fine… Samsung Galaxy Tab A6, Android 5.1.1, building with bazel version 0.3.0

The Crash starts here- 

...

```
E/AndroidRuntime(26848): FATAL EXCEPTION: ImageListener
E/AndroidRuntime(26848): Process: org.tensorflow.demo, PID: 26848
E/AndroidRuntime(26848): java.lang.UnsatisfiedLinkError: No implementation found for int org.tensorflow.demo.TensorflowClassifier.initializeTensorflow(android.content.res.AssetManager, java.lang.String, java.lang.String, int, int, int, float, java.lang.String, java.lang.String) (tried Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow and Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow__Landroid_content_res_AssetManager_2Ljava_lang_String_2Ljava_lang_String_2IIIFLjava_lang_String_2Ljava_lang_String_2)
E/AndroidRuntime(26848): 	at org.tensorflow.demo.TensorflowClassifier.initializeTensorflow(Native Method)
E/AndroidRuntime(26848): 	at org.tensorflow.demo.TensorflowImageListener.initialize(TensorflowImageListener.java:84)
E/AndroidRuntime(26848): 	at org.tensorflow.demo.CameraConnectionFragment.createCameraPreviewSession(CameraConnectionFragment.java:540)
E/AndroidRuntime(26848): 	at org.tensorflow.demo.CameraConnectionFragment.access$400(CameraConnectionFragment.java:63)
E/AndroidRuntime(26848): 	at org.tensorflow.demo.CameraConnectionFragment$2.onOpened(CameraConnectionFragment.java:155)
E/AndroidRuntime(26848): 	at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:118)
E/AndroidRuntime(26848): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(26848): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(26848): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(26848): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/ActivityManager(  735):   Force finishing activity 1 org.tensorflow.demo/.CameraActivity
D/FocusedStackFrame(  735): Set to : 0
D/InputDispatcher(  735): Focused application set to: xxxx
D/InputDispatcher(  735): Focus left window: 26848
D/PointerIcon(  735): setMouseIconStyle1 pointerType: 1001 iconType:101 flag:0 pid:735 uid:1000
I/ActivityManager(  735): Skip updateThumbnail for r=ActivityRecord{59212fe u0 org.tensorflow.demo/.CameraActivity t83 f}
D/PointerIcon(  735): setMouseCustomIcon IconType is same.101
E/android.os.Debug(  735): ro.product_ship = true
E/android.os.Debug(  735): ro.debug_level = 0x4f4c
I/ShotCommon(  177): disableMsgType (0x10)
I/SprdCameraHardware(  177): 'mLock:disableMsgType E.
I/SprdCameraHardware(  177): 'mLock:disableMsgType X.
I/ShotCommon(  177): disableMsgType (0xffffffff)
I/SprdCameraHardware(  177): 'mLock:disableMsgType E.
I/SprdCameraHardware(  177): 'mLock:disableMsgType X.
I/ShotSingle(  177): stopPreview E
```
....

**Comment by andrewharp** [comment] 2016-07-15 19:41
@kokozaurz Have you checked that the native lib is getting built and put into the APK as well?

**Comment by kokozaurz** [comment] 2016-07-15 19:48
built as mentioned above with -s --verbose_failures and this is the log. Interesting enough it's way smaller than previously attached log by @PatrickGuo 

Is something missing there?

[buildlog.txt](https://github.com/tensorflow/tensorflow/files/366735/buildlog.txt)

**Comment by kokozaurz** [comment] 2016-07-15 20:33
Also just tried on LG G4 Android 6.0.0 - the same error.

**Comment by pkpp1233** [comment] 2016-07-15 20:53
@andrewharp no implementation error for me. Here's the log

```
07-15 13:50:35.966 20777 20791 E art     : No implementation found for int org.tensorflow.demo.TensorflowClassifier.initializeTensorflow(android.content.res.AssetManager, java.lang.String, java.lang.String, int, int, int, float, java.lang.String, java.lang.String) (tried Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow and Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow__Landroid_content_res_AssetManager_2Ljava_lang_String_2Ljava_lang_String_2IIIFLjava_lang_String_2Ljava_lang_String_2)
07-15 13:50:35.967 20777 20791 E AndroidRuntime: FATAL EXCEPTION: ImageListener
07-15 13:50:35.967 20777 20791 E AndroidRuntime: Process: org.tensorflow.demo, PID: 20777
07-15 13:50:35.967 20777 20791 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for int org.tensorflow.demo.TensorflowClassifier.initializeTensorflow(android.content.res.AssetManager, java.lang.String, java.lang.String, int, int, int, float, java.lang.String, java.lang.String) (tried Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow and Java_org_tensorflow_demo_TensorflowClassifier_initializeTensorflow__Landroid_content_res_AssetManager_2Ljava_lang_String_2Ljava_lang_String_2IIIFLjava_lang_String_2Ljava_lang_String_2)
```

**Comment by andrewharp** [comment] 2016-07-15 21:14
@pkpp1233 @kokozaurz @PatrickGuo 

Ok, the problem is that a recent global renaming for Tensorflow to Tensor**F**low caught the native identifier in [tensorflow_jni.h](https://github.com/tensorflow/tensorflow/blob/aedd2173deef51661ab0cabcb9009d249e744e31/tensorflow/examples/android/jni/tensorflow_jni.h#L31)  but did not correspondingly rename [TensorflowClassifier.java](https://github.com/tensorflow/tensorflow/blob/060484b39d0813a5e209f90d9de81413da310cac/tensorflow/examples/android/src/org/tensorflow/demo/TensorflowClassifier.java).

Either s/TensorFlow/Tensorflow/ in tensorflow_jni.h, or rename and change the class of TensorflowClassifier.java to TensorFlowClassifier. I'll submit a fix to do the latter soon.

**Comment by pkpp1233** [comment] 2016-07-16 02:09
@andrewharp hehe this does look like a losing battle (https://github.com/tensorflow/tensorflow/commit/c87a7ca3113c95aaf52de7a094773feb2dba2fa1).

I started heading down the route of renaming https://github.com/tensorflow/tensorflow/blob/060484b39d0813a5e209f90d9de81413da310cac/tensorflow/examples/android/src/org/tensorflow/demo/TensorflowClassifier.java but then get an error to rename https://github.com/tensorflow/tensorflow/blob/060484b39d0813a5e209f90d9de81413da310cac/tensorflow/examples/android/src/org/tensorflow/demo/TensorflowImageListener.java#L64. After changing that, I keep going down the rabbithole.

```
07-15 19:05:50.242 13826 13859 E art     : No implementation found for int org.tensorflow.demo.TensorFlowClassifier.initializeTensorflow(android.content.res.AssetManager, java.lang.String, java.lang.String, int, int, int, float, java.lang.String, java.lang.String) (tried Java_org_tensorflow_demo_TensorFlowClassifier_initializeTensorflow and Java_org_tensorflow_demo_TensorFlowClassifier_initializeTensorflow__Landroid_content_res_AssetManager_2Ljava_lang_String_2Ljava_lang_String_2IIIFLjava_lang_String_2Ljava_lang_String_2)
07-15 19:05:50.244 13826 13859 E AndroidRuntime: FATAL EXCEPTION: ImageListener
```

Is it compiling for you?

**Comment by pkpp1233** [comment] 2016-07-16 02:51
Easy fix, see commit on my fork - https://github.com/pkpp1233/tensorflow/commit/13be44b9c8fe212ea2408a4c27b21f4092b5437d

**Comment by PatrickGuo** [comment] 2016-07-16 03:59
@andrewharp Ok, such a tricky one. @pkpp1233 Thanks for your note. Now it works perfectly fine on my android devices.

**Comment by andrewharp** [comment] 2016-07-16 09:57
Fixed in https://github.com/tensorflow/tensorflow/pull/3336/commits/194efde51895e0251d39c72c969dff1a50b67d35. Thanks for the reports!

**Closed by andrewharp** 2016-07-16 09:57 UTC

**Comment by erotavlas85** [comment] 2016-11-13 08:07
@andrewharp I have a similar issue, but I cannot figure out how to solve it [gist](https://gist.github.com/erotavlas85/a6adc607f13d6e4a540f5e6da1ec8b2b). Is there any precompiled apk? I'm using the apk found on this blog https://jalammar.github.io/ on cyanogenmod 13 aka android 6.0.1 on samsung s2
Thank you

**Comment by andrewharp** [comment] 2016-11-13 23:51
@erotavlas85 You can find automated builds of the demo apk on the [TF Android Jenkins](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-android/). Here's a [direct link](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-android/TF_BUILD_CONTAINER_TYPE=ANDROID,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=NO_PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=android-slave/lastSuccessfulBuild/artifact/bazel-out/local_linux/bin/tensorflow/examples/android/tensorflow_demo.apk) to the latest APK.

I don't see any errors in your gist -- everything seems to be working normally up to the point the log ends. What issues are you experiencing?

**Comment by erotavlas85** [comment] 2016-11-15 09:13
@andrewharp Thank you for the link. I tried with another smartphone and it worked. So there should be a problem with my old s2. The application starts well, but it stops and exits automatically. Is there any problem with cyanogenmod? I do not think so.
