### ISSUE TITLE
Problems in TensorFlow Linear Model Tutorial

### ISSUE THREAD

**Issue by tiagonj** [tensorflow/tensorflow#3777] opened 2016-08-12 19:43 UTC
I believe the [TensorFlow Linear Model tutorial](https://www.tensorflow.org/versions/r0.10/tutorials/wide/index.html) incorrectly points to [wide_n_deep_tutorial.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py) code. For example that code does not put in place the [L1 and L2 regularization](https://www.tensorflow.org/versions/r0.10/tutorials/wide/index.html#adding-regularization-to-prevent-overfitting) that is mentioned (and for which the code is shown) in the tutorial text.

I assume the tutorial was written up based on a different python script?

Also, [wide_n_deep_tutorial.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py) will not work on Python 3 as it calls `urllib.urlretrieve` directly. Perhaps it should use the `maybe_download` function from `tensorflow.contrib.learn.python.learn.datasets.base`?

**Comment by prb12** [comment] 2016-08-22 16:20
@xmbrst Could you please take a look at this?

**Comment by xmbrst** [comment] 2016-08-22 16:56
Both the Linear Model and the Wide and Deep tutorials use wide_n_deep_tutorial.py. You use flags, like " --model_type=wide", to switch between the two types of models. I'll take a look at the regularization issue.

I've a filed a separate issue, #3956, about the Python 3 problem.

**Comment by chitro** [comment] 2016-12-29 20:46
Has this issue been resolved? I'm seeing problems with wide_n_deep in TF 0.12.0 also in Windows 10 (new  version)

**Comment by xmbrst** [comment] 2017-01-06 17:19
@chitro, do you think your Windows 10 issue is related to the Python 3 problem described by @tiagonj? If so, please update #3956 with a description of the problem. Otherwise, you might want to create a new issue.

I'm closing this issue about the text of the tutorial, which is working as intended. (The regularization code is framed in the text as a modification you can make to the existing code.)

**Closed by xmbrst** 2017-01-06 17:19 UTC
Labels: awaiting googler
