### ISSUE TITLE
When I try to run a python program after importing Tensorflow library I get this message

### ISSUE THREAD

**Issue by prajjwalin** [tensorflow/tensorflow#8234] opened 2017-03-09 07:47 UTC
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.

**Comment by AFAgarap** [comment] 2017-03-09 13:24
You're using the CPU version of TensorFlow, right? If you use the GPU version, you'll have a different output message. You'll have one like this:

```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
```

You may ignore it, but if you want faster computation, use the GPU, and you'll have an output message like the one I posted above.

**Comment by prb12** [comment] 2017-03-09 17:16
These warnings are harmless, and can safely be ignored. 

They are there as a gentle reminder to people who are benchmarking TensorFlow that it is possible to generate faster CPU code if various processor specific build options are enabled.  (In generic binary builds are unable to turn on these options.)

Closing since this is not a bug/issue and really a general usage question. (which are best sent to StackOverflow for future reference!)

**Closed by prb12** 2017-03-09 17:16 UTC
