### ISSUE TITLE
Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on

### ISSUE THREAD

**Issue by botev** [tensorflow/tensorflow#17507] opened 2018-03-07 12:12 UTC
The error occurs when I have trained on one system and used `tf.Saver` to save a model and then I copied the saved model on  a second system and used the same code to restore the model. However, the absolute paths of the directories in which the code is executed are different. Hence I got this error:
```
2018-03-07 12:08:17.897739: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-07 12:08:41.813649: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
2018-03-07 12:08:41.813663: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
2018-03-07 12:08:41.813680: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
2018-03-07 12:08:41.813700: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
2018-03-07 12:08:41.813724: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
2018-03-07 12:08:41.813769: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
2018-03-07 12:08:41.813784: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
2018-03-07 12:08:41.813802: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
2018-03-07 12:08:41.813819: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/opt/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-2017.3.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alex/work/python/bayes-test/bin/train.py", line 165, in <module>
    main(**vars(parser.parse_args()))
  File "/home/alex/work/python/bayes-test/bin/train.py", line 97, in main
    tu.load_parameters(saver, sess, data_folder)
  File "/home/alex/work/python/tensorflow_utils/tensorflow_utils/printing.py", line 13, in load_parameters
    saver.restore(session, ckpt.model_checkpoint_path)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]

Caused by op 'save/RestoreV2_1', defined at:
  File "/opt/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/opt/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2017.3.3/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-2017.3.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/alex/work/python/bayes-test/bin/train.py", line 165, in <module>
    main(**vars(parser.parse_args()))
  File "/home/alex/work/python/bayes-test/bin/train.py", line 87, in main
    saver = tf.train.Saver(params)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/opt/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen/model.ckpt: Not found: /mnt/workspace/work/python/bayes-test/bin//results/not_centered/gen; No such file or directory
	 [[Node: save/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_1/tensor_names, save/RestoreV2_1/shape_and_slices)]]
```
Isn't the saver suppose to save a somewhat system agnostic version of the tensors? The fact that there is hardcoded absolute paths make me very suspicous?

**Comment by tensorflowbutler** [comment] 2018-03-08 02:28
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by botev** [comment] 2018-03-08 04:30
Have I written custom code: No
OS Platform and distribution: Ubuntu 16.04 LTS
Tensorflow installed from Anaconda 
Tensorflow version: 1.4
Bazel version: Don't have bazel installed
CUDA/cuDNN version: On the cluster - CUDA 9.0/cudnnv8, the other machine is CPU only
GPU model and memory: V100 (P3 AWS instance)
Exact command:
```
def load_parameters(saver, session, load_dir, force_delete=False):
    if tf.gfile.Exists(load_dir):
        ckpt = tf.train.get_checkpoint_state(load_dir)
        if ckpt and ckpt.model_checkpoint_path:
            saver.restore(session, ckpt.model_checkpoint_path)
        elif force_delete:
            shutil.rmtree(load_dir)
            tf.gfile.MakeDirs(load_dir)
    else:
        tf.gfile.MakeDirs(load_dir)
```
This is called with absolute paths for `load_dir` on the cluster machine and on the desktop machine.

**Comment by tensorflowbutler** [comment] 2018-03-25 00:52
Nagging Assignee @jart: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jart** [comment] 2018-03-25 01:06
Have you tried passing these libraries a relative path? Maybe it's storing an absolute path because an absolute path was provided.

**Comment by tensorflowbutler** [comment] 2018-04-08 18:30
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-23 18:43
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-05-10 01:01
It has been 45 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jart** [comment] 2018-05-10 05:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jart** 2018-05-10 05:32 UTC
Labels: stat:awaiting response

**Comment by Roc-J** [comment] 2018-08-16 01:46
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/deeplearning/projects/Google/tensorflow/models/research/object_detection/training/model.ckpt-98472

HI , anyone ,i met the same problem. the reason is that the program is stop and i restart, the problem is occur. but the files is all here:
![image](https://user-images.githubusercontent.com/16716182/44182351-376e8d80-a139-11e8-8b5c-03b27c0204a9.png)

please tell me why?thanks a lot
