### ISSUE TITLE
What is quantized data type? For instance qint8, quint8, qint32

### ISSUE THREAD

**Issue by Nianzu** [tensorflow/tensorflow#494] opened 2015-12-12 22:35 UTC
In tensorflow document of class tf.DType: https://www.tensorflow.org/versions/master/api_docs/python/framework.html#DType
 
There are three types:
tf.qint8: Quantized 8-bit signed integer.
tf.quint8: Quantized 8-bit unsigned integer.
tf.qint32: Quantized 32-bit signed integer.

And also related method about quantized data type. I searched online, but did not find useful resource about it. 
Could you add some explanation in the document?

**Comment by vrv** [comment] 2015-12-12 22:35
Duplicate of https://github.com/tensorflow/tensorflow/issues/15

**Closed by vrv** 2015-12-12 22:35 UTC
