### ISSUE TITLE
Always same random values in eager mode

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#28695] opened 2019-05-14 09:12 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS X 10.14
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.14.1-dev20190513
- Python version: 3.6.5
- Bazel version (if compiling from source): no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version: no
- GPU model and memory: no

**Describe the current behavior**
Random output should be different on each call.
That is true for graph mode, but not for eager one.

**Describe the expected behavior**
Random output should be different on each call in both graph and eager modes.

**Code to reproduce the issue**
```python
# Graph mode
import tensorflow as tf

x = tf.random.normal([5], seed=1)

with tf.Session() as sess:
    for i in range(3):
        print(sess.run(x))

# Output
# [-0.8113182   1.4845988   0.06532937 -2.4427042   0.0992484 ]
# [-0.36332107 -0.07205155 -0.5527937   0.10289733 -0.39558855]
# [-0.666205   -0.416783    1.8211031   0.680353   -0.26143482]
```

```python
# Eager mode
import tensorflow as tf

tf.enable_eager_execution()
x = tf.random.normal([5], seed=1)

for i in range(3):
    print(x.numpy())

# Output
# [-0.8113182   1.4845988   0.06532937 -2.4427042   0.0992484 ]
# [-0.8113182   1.4845988   0.06532937 -2.4427042   0.0992484 ]
# [-0.8113182   1.4845988   0.06532937 -2.4427042   0.0992484 ]
```

**Comment by grzegorz700** [comment] 2019-05-14 09:35
When you use the seed parameter, It's the correct behaviour. Please remove the 'seed' argument to get different result each time.
Please close this thread.

**Comment by shkarupa-alex** [comment] 2019-05-14 09:46
Same behaviour without seed.

**Comment by allenlavoie** [comment] 2019-05-14 16:39
x.numpy() doesn't re-run the operation, it just copies the existing result to a numpy array. Try moving the normal() call into the loop.

**Comment by shkarupa-alex** [comment] 2019-05-14 18:10
Ok, let me explain the source of my report.
I've got a custom TF-based code with randomness inside. For simplicity in example below i replaced that code with  `tf.random.normal`. 
And i've got a unit test. It looks near like this:
```Python
import tensorflow as tf
from tensorflow.python.framework import test_util

@test_util.run_all_in_graph_and_eager_modes
class DownSampleTest(tf.test.TestCase):
    def testRand(self):
        x = tf.random.normal([5], seed=1)
        y1 = self.evaluate(x)
        y2 = self.evaluate(x)
        # ... check that y1 not equals y2
```
In test i want to check that x changes on each call.
That is true for graph-mode and not true for eager mode.

As result, i can't test my code working as expected in both modes.

**Comment by allenlavoie** [comment] 2019-05-14 20:35
I sometimes use functools.partial here. So x_func = functools.partial(tf.random.normal, args...), then run self.evaluate on x_func() a few times.

**Comment by achandraa** [comment] 2019-05-15 13:38
Please have a look on @allenlavoie's suggestion and let us know if you are stuck. Thanks!

**Comment by shkarupa-alex** [comment] 2019-05-15 14:00
It works as workaround, but makes testing for both graph and eager modes messy.

**Comment by achandraa** [comment] 2019-05-16 08:20
Good to know the issue is resolved. Will close this for now. If you are stuck anywhere, feel free to open separate ticket. We will be happy to help. Thanks!

**Closed by achandraa** 2019-05-16 08:20 UTC
Labels: comp:ops, type:support
