### ISSUE TITLE
Tensorflow >=2.10 windows - model.load_weights file handling issue

### ISSUE THREAD

**Issue by twerkmeister** [tensorflow/tensorflow#58740] opened 2022-11-30 09:21 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10 and 2.11

### Custom Code

No

### OS Platform and Distribution

Windows Server 2019

### Python version

3.9

### Current Behaviour?

After loading a model with `model.load_weights` something is off with the directory that the weights were loaded from:
1. Savings weights to that directory again fails
2. Removing that directory fails as well

Edit: This does not happen on Linux. However, on windows systems, our CI crashes with the provided errors when fine tuning models or when temporary directories are cleaned up after loading models from them. The provided snippets represent minimal examples of what I was able to trace down would lead to crashes on windows.

#### test code 1 (saving weights again)
```python

import tensorflow as tf
from pathlib import Path

inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

tf_model_file = Path("model") / "my_model.tf_model"

model.save_weights(tf_model_file, overwrite=True, save_format="tf")

model.load_weights(tf_model_file)
model.save_weights(tf_model_file, overwrite=True, save_format="tf")

```

#### test code 2 (removing directory)
```python

import tensorflow as tf
from pathlib import Path
import shutil

inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

tf_model_file = Path("model") / "my_model.tf_model"

model.save_weights(tf_model_file, overwrite=True, save_format="tf")

model.load_weights(tf_model_file)

shutil.rmtree("model")
```

#### Output for test 1
```shell
2022-11-30 09:18:57.932686: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-30 09:18:58.186560: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at save_restore_v2_ops.cc:286 : UNKNOWN: Failed to rename: model\my_model.tf_model_temp/part-00000-of-00001.data-00000-of-00001 to: model\my_model.tf_model.data-00000-of-00001 : Cannot create a file when that file already exists.
; Unknown error
Traceback (most recent call last):
  File "C:\Users\thomas\Desktop\model-test\model-test.py", line 14, in <module>
    model.save_weights(tf_model_file, overwrite=True, save_format="tf")
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\keras\engine\training.py", line 2917, in save_weights
    self._checkpoint.write(filepath, options=options)
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\checkpoint\checkpoint.py", line 2287, in write
    return self._write(file_prefix, options)
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\checkpoint\checkpoint.py", line 2305, in _write
    output = self._saver.save(
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\checkpoint\checkpoint.py", line 1351, in save
    save_path, new_feed_additions = self._save_cached_when_graph_building(
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\checkpoint\checkpoint.py", line 1294, in _save_cached_when_graph_building
    return _run_save()
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\checkpoint\checkpoint.py", line 1246, in _run_save
    save_op = saver.save(file_prefix, options=options)
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\checkpoint\functional_saver.py", line 407, in save
    return save_fn()
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\checkpoint\functional_saver.py", line 393, in save_fn
    return gen_io_ops.merge_v2_checkpoints(
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 547, in merge_v2_checkpoints
    return merge_v2_checkpoints_eager_fallback(
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 582, in merge_v2_checkpoints_eager_fallback
    _result = _execute.execute(b"MergeV2Checkpoints", 0, inputs=_inputs_flat,
  File "C:\Users\thomas\AppData\Local\pypoetry\Cache\virtualenvs\rasa-_GmHtu1y-py3.9\lib\site-packages\tensorflow\python\eager\execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__MergeV2Checkpoints_device_/job:localhost/replica:0/task:0/device:CPU:0}} Failed to rename: model\my_model.tf_model_temp/part-00000-of-00001.data-00000-of-00001 to: model\my_model.tf_model.data-00000-of-00001 : Cannot create a file when that file already exists.

```
#### Output of error 2
```shell
2022-11-30 09:20:47.815422: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\thomas\Desktop\model-test\model-delete-test.py", line 16, in <module>
    shutil.rmtree("model")
  File "C:\Users\thomas\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\thomas\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 633, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\thomas\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 631, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'model'
```
</details>

**Comment by mohantym** [comment] 2022-11-30 12:11
Hi @twerkmeister !
I was able to run above code by changing folder paths as below.

> my_model.tf_model

with 

> mymodel

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/06d1de7c966060c8739e84c12dda2a1f/git_58740.ipynb#scrollTo=5UyeP_2XX-rs) for reference.

Could you give us an update from your side.

Thank you!

**Comment by twerkmeister** [comment] 2022-11-30 15:07
I know it works fine on Linux 👍 and it even runs without your proposed change. However, **on windows**  our CI crashes with the provided errors when fine tuning models or when temporary directories are cleaned up after loading models from them. The provided snippets represent what I was able to trace down would lead to crashes **on windows**.

**Comment by twerkmeister** [comment] 2022-11-30 15:10
I might have misunderstood, sorry, let me test the provided change on windows.

**Comment by twerkmeister** [comment] 2022-11-30 15:20
I tested the proposed change on windows, and I am getting the same error as before. 

All the provided snippets work on linux. On windows, however, the `model.load_weights(tf_model_file)` makes the operations that follow it fail.

**Comment by mohantym** [comment] 2022-12-01 08:58
Hi @twerkmeister !
I found a different error "NoneType is not callable" in my local windows machine.
I think issue is how mode.save_weights statement. It should pass the checkpoint folder path only.

 "save_format="tf" " is used when you are saving complete model manually.

Attached relevant [thread](https://www.tensorflow.org/tutorials/keras/save_and_load#manually_save_weights) for reference.

Seems a valid bug to me.

Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues) for further assistance.
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thank you!

**Comment by twerkmeister** [comment] 2022-12-01 10:44
Hi, @mohantym, thanks for looking into this!

Unfortunately, I struggle to follow your explanation. Also, I am not sure this pertains to keras only. I looked into what happens in the `save_weights` and `load_weights` methods and was able to reproduce it with checkpoints only using a single tf variable. The issue is with the `root` key when creating checkpoint objects, which keras uses in it's models. Have a look:

#### This crashes with the same error as before
```python 
import tensorflow as tf

ckpt = tf.train.Checkpoint(root=tf.Variable(1.))
path = ckpt.write('my_checkpoint')
ckpt.read(path)
ckpt.write("my_checkpoint")
```

#### while this works (changed the name of the variable in the checkpoint from `root` to `v`)
```python 
import tensorflow as tf

ckpt = tf.train.Checkpoint(v=tf.Variable(1.))
path = ckpt.write('my_checkpoint')
ckpt.read(path)
ckpt.write("my_checkpoint")
```


#### Similarly this crashes with the error
```python
import tensorflow as tf

inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

ckpt = tf.train.Checkpoint(root=model)
path = ckpt.write('my_checkpoint')
ckpt.read(path)
ckpt.write("my_checkpoint")
```

#### And this works (changed the name from root to something else)
```python
import tensorflow as tf

inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

ckpt = tf.train.Checkpoint(model=model)
path = ckpt.write('my_checkpoint')
ckpt.read(path)
ckpt.write("my_checkpoint")
```

**Comment by mohantym** [comment] 2022-12-01 10:57
Ok @twerkmeister !
Thanks for sharing your observations

@SuryanarayanaY !
Could you look at this issue. 

Thank you!

**Comment by twerkmeister** [comment] 2022-12-12 09:12
Hey @SuryanarayanaY, any news on this? Can I provided any additional context?

**Comment by SuryanarayanaY** [comment] 2022-12-18 11:33
Hi @twerkmeister ,

Sorry for the delay due to Windows OS issues.

Since you are not mentioned GPU, I have tried with `!pip install tensorflow-cpu==2.10` and could not found any error.
Please refer attachment below.

http://localhost:8889/nbconvert/html/58740-cpu.ipynb?download=false

As your are using Windows OS TF 2.11V wont be supported on windows native. Please refer [source](https://www.tensorflow.org/install/pip) doc here.

Please confirm exact TF installation command you are using for 2.10V and Environment you are using for 2.11V.

**Comment by twerkmeister** [comment] 2022-12-19 10:26
Hey @SuryanarayanaY, this seems indeed to be limited to windows server 2019, which is what I tested on initially and the system we at rasa run our CI for windows. I just created a fresh windows server 2022 instance on gcloud and it didn't have the error. I also tested again on the Windows server 2019 instance installing with pip tensorflow-cpu==2.10.0 as you did, and I got the same error again.

**Comment by SuryanarayanaY** [comment] 2022-12-19 14:03
Hi @twerkmeister ,
Thanks for the response. So can we conclude that the error exists on Windows 2019 server and upgrading to Windows server 2022 resolves this issue. It might be due to recent changes w.r.t windows support. Can we consider it as resolved?

**Comment by twerkmeister** [comment] 2022-12-20 09:48
Hey @SuryanarayanaY, in the end it's not about making our CI pass, but having our software run properly on our client's machines. [Tensorflow's install docs](https://www.tensorflow.org/install) says it's supported on Windows 7 or later which should include Windows Server 2019. Also, Windows server 2019 is officially supported until Jan 2024, so I suppose people would still be using it.

**Comment by sachinprasadhs** [comment] 2023-01-10 04:06
Thanks for reporting the issue, in order to find the root cause of the issue, could you please help us by trying with below  and let us know if you still find an issue.

- Try with the Sequential model by replacing functional API.
- Try providing absolute path instead of relative path.
- Could you also try saving with Keras H5 format.

**Comment by twerkmeister** [comment] 2023-01-16 15:06
Hey @sachinprasadhs, thanks for reaching out.

We solved this issue by now for us by subclassing the keras model and using the learnings from this [comment](https://github.com/tensorflow/tensorflow/issues/58740#issuecomment-13335661380), so that the checkpoint is not using the `root` keyword. The same comment also shows that the issue comes from the `root` keyword in checkpoints and that it  fails even with a single variable, no model needed. So it looks to me that this is definitely a problem in TF for win server 2019, for whatever reason... It happens in our github CI machines with win server 2019 and it also happens in fresh vm instances on google cloud.

Unfortunatley, I can't devote more time to tracking this down, but I think there is plenty of info here in this thread already if you think this is an issue worth digging into.

**Comment by learning-to-play** [comment] 2023-01-27 04:50
@intel-tf-windows Could you please take a look?

**Comment by mraunak** [comment] 2023-01-28 01:10
@learning-to-play yeah working on it. It seems to be related to https://github.com/keras-team/keras/pull/13048

**Comment by k-w-w** [comment] 2023-06-20 18:33
Hi, is this still an issue?

**Comment by mraunak** [comment] 2023-06-21 17:44
Hi @k-w-w, I had a fix for this issue through a PR https://github.com/tensorflow/tensorflow/pull/59633.
However, I was not able to create a PR to Keras GitHub to fix this issue due to the build failure of Keras on my local Windows machine.

**Comment by k-w-w** [comment] 2023-07-05 22:07
Hi @nkovela1 Could you take a look at the PR #59633 and see if it can be added to `Model.save_weights`?

**Comment by nkovela1** [comment] 2023-07-06 00:51
@k-w-w The PR can be added to `Model.save_weights` but it appears to be redundant.
The current `save_weights` implementation uses `with h5py.File(filepath, "r") as f:` which should automatically open and close the associated H5 file.  Do we have a reason for why this extra `close` statement within the file scope is necessary?

**Comment by mraunak** [comment] 2023-07-06 03:25
Hi @nkovela1, thank you for looking into it. Could you please replicate the issue on your end and confirm if the issue does not occur without the PR?

**Comment by nkovela1** [comment] 2023-07-07 17:33
@mraunak Just reproduced the issue on my side and the code passes without errors, thanks!

**Comment by mraunak** [comment] 2023-07-07 19:50
Hi @k-w-w. I believe this issue is resolved for the latest TF version. Hence, it can be closed

**Comment by k-w-w** [comment] 2023-07-07 20:18
Thanks @mraunak and @nkovela1!

**Closed by k-w-w** 2023-07-07 20:18 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:keras, subtype:windows, TF 2.10
