### ISSUE TITLE
Crash during folder creation from Estimator exporter.py in Python 3.6

### ISSUE THREAD

**Issue by apacha** [tensorflow/tensorflow#21403] opened 2018-08-06 10:08 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8.0 and 1.9.0
- **Python version**: 3.6
- **GPU model and memory**: GTX 1080 Ti
- **Exact command to reproduce**: See [here](https://github.com/tensorflow/models/issues/4996#issue-347431961)

### Describe the problem
When exporting of a snapshot during training with Estimator, [`export.py`](https://github.com/tensorflow/tensorflow/blob/e70f94ee089abbb9eb70361b5cdef55aa9beb18b/tensorflow/python/estimator/export/export.py#L600) creates an invalid path with Python 3.6, due to handling of strings as bytes (!!!). 

In [`estimator.py`](https://github.com/tensorflow/tensorflow/blob/e70f94ee089abbb9eb70361b5cdef55aa9beb18b/tensorflow/python/estimator/estimator.py#L779), the following string is generated for the variable `export_dir`: `b'C:/Users/Alex/pet-train\\export\\Servo\\1533549311'`, which is afterwards corrupted by the `get_temp_export_dir` command, which defaces it into `b"C:/Users/Alex/pet-train\\export\\Servo\\temp-b'1533549311'"` which further down the road causes the program to crash with the following exception:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.1.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Alex/Repositories/MusicObjectDetector-TF2/research/object_detection/model_main.py", line 101, in <module>
    tf.app.run()
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:/Users/Alex/Repositories/MusicObjectDetector-TF2/research/object_detection/model_main.py", line 97, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\estimator\training.py", line 439, in train_and_evaluate
    executor.run()
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\estimator\training.py", line 518, in run
    self.run_local()
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\estimator\training.py", line 657, in run_local
    eval_result = evaluator.evaluate_and_export()
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\estimator\training.py", line 858, in evaluate_and_export
    self._export_eval_result(eval_result, is_the_final_export)
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\estimator\training.py", line 889, in _export_eval_result
    is_the_final_export=is_the_final_export)
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\estimator\exporter.py", line 177, in export
    is_the_final_export)
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\estimator\exporter.py", line 123, in export
    strip_default_attrs=self._strip_default_attrs)
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\estimator\estimator.py", line 644, in export_savedmodel
    builder = saved_model_builder.SavedModelBuilder(temp_export_dir)
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\saved_model\builder_impl.py", line 92, in __init__
    file_io.recursive_create_dir(self._export_dir)
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 374, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "C:\Programmieren\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a directory: C:/Users/Alex/pet-train\export\Servo\temp-b'1533549311'; No such file or directory

Process finished with exit code -1
```

**Comment by apacha** [comment] 2018-08-06 10:27
Ok, I guess - despite being ugly - the path is actually valid on Windows. Then the problem seems to be caused by the implementation of `RecursivelyCreateDir`. Why not using the good old [`os.makedirs`](https://docs.python.org/3.6/library/os.html#os.makedirs) command?

**Comment by yongtang** [comment] 2018-08-07 02:47
I think the `compat.as_bytes` was intended to make the function compatible with both python 2 and python 3, but `compat.as_bytes` was missing when adding `"temp-"`.

Added a PR #21426 to try to fix the issue.

**Comment by rohan100jain** [comment] 2018-08-07 19:37
Can someone confirm that this small fix fixes the problem?

**Comment by apacha** [comment] 2018-08-13 12:56
Thanks @Wuppus for clarifying this again (as I've note already above): The problem apparently is the `pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)` command. The old path seemed ugly and not what it was intended to be, but it is not the cause of the problem.

Why wouldn't you use the Python standard `os.makedirs()` command anyway?

**Comment by tensorflowbutler** [comment] 2018-08-31 15:02
Nagging Assignee @rohan100jain: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-16 02:28
Nagging Assignee @rohan100jain: It has been 33 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 12:58
Nagging Assignee @rohan100jain: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-15 12:58
Nagging Assignee @rohan100jain: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-30 12:51
Nagging Assignee @rohan100jain: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-14 19:09
Nagging Assignee @rohan100jain: It has been 93 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by apacha** [comment] 2018-12-03 17:34
Seems like the only one who gets nagged by the tensorflowbutler is me... 
Never mind this issue, I'm switching to PyTorch now.

**Comment by Wuppus** [comment] 2018-12-10 09:04
@apacha Indeed! I got a new machine over the weekend, installed latest TF and didn't think to check this line. Overnight run failed with the same issue. I moved to using estimators because Keras doesn't keep up with changes, maybe I need to look outside the Tensorflow world too!

**Comment by austinmw** [comment] 2019-04-09 04:06
@apacha do you happen to remember how to fix this issue?

**Comment by Wuppus** [comment] 2019-04-09 07:03
@austinmw Glad it worked for you - I've just experienced this issue again this morning having installed the latest Tensorflow-gpu. Only change seems to be the substitution of 'path' for 'dirname'. Someone went to the trouble of creating another decorator and just referenced the same faulty code...

**Comment by austinmw** [comment] 2019-04-09 07:09
Sigh.. I feel like there's 10 different versions of python scattered through this api.

**Comment by GSonderling** [comment] 2019-07-27 08:43
Any changes to this issue? Or does it still require you to rewrite basic tensorflow functions?

**Comment by sushreebarsa** [comment] 2021-07-09 16:01
@apacha We see that you are using old version of tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Hence moving this to closed status.Thanks!

**Closed by sushreebarsa** 2021-07-09 16:01 UTC
Labels: comp:apis, type:bug
