### ISSUE TITLE
TF Lite issue when loading a saved TF Lite model on platforms with different endianness

### ISSUE THREAD

**Issue by skribm9** [tensorflow/tensorflow#45009] opened 2020-11-19 14:46 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): UB18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.1
- Python version: 3.6.9
- Bazel version (if compiling from source): bazel 2.0.0- (@non-git)
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
This issue is created for tracking purposes in respect to the discussion done in PR request #44063 
@jdduke Thank you for offering to look into this issue and letting me tag you here.

The problem is that the TfLite saved models only support Little Endian format by default. When loading these model, flatbuffer is not able to handle some non-native data types like Tensor. We need some extra efforts on both the saving side and loading side to manually do the byte-swap on Big-Endian machine. 

**Describe the expected behavior**
We should be able to address the endianness issue while keeping the saved model in Little-Endian format.

**Comment by jdduke** [comment] 2020-11-19 20:00
Thanks for the report! I've filed an internal tracking bug to figure out next steps, will keep you posted on progress.

**Comment by Sidong-Wei** [comment] 2020-12-07 15:58
Hi @jdduke, I think I just got some useful information in addressing this issue.
Based on my investigation, the issue here is not limited to serialize and deserialize tflite flatbuffer models, because I also identified this issue when using the experimental `mlir_quantizier`, in which case the flatbuffer model is converted into a mlir module then quantized and converted back.
I believe the major issue is related to the `buffers` field as defined in the [schema](https://github.com/tensorflow/tensorflow/blob/47764eaf7473224cd3fe3cfb34706cfd219c532c/tensorflow/lite/schema/schema.fbs#L1154). The `Buffer` data type is 1 byte long but they actually represent data of longer bytes like `int` or `float`, which may cause the data in the `buffers` field not to be stored in little-endian, while flatbuffer objects should always be stored in little-endian.
When the `buffers` field of the model is populated, it is using methods similar to `memcpy`, like in the old tflite toco converter [here](https://github.com/tensorflow/tensorflow/blob/47764eaf7473224cd3fe3cfb34706cfd219c532c/tensorflow/lite/toco/tflite/export.cc#L227) and in the new mlir converter [here](https://github.com/tensorflow/tensorflow/blob/47764eaf7473224cd3fe3cfb34706cfd219c532c/tensorflow/compiler/mlir/lite/flatbuffer_export.cc#L694). As a result, the underlying data in the `buffers` field is in host machine native endianness rather than little-endian.
In comparison, other fields in the schema like `quantization_parameters` or `shape` are all typed values, so when populating them in the model, flatbuffer compiler will handle the endianness automatically (i.e. always store them in little endian, byteswap when needed).

The issue with the `buffers` field is a fundamental thing that needs to be fixed for big-endian machines to use tflite properly, but currently, it is not entirely broken because of the following reasons:
1. Both write and read to `buffers` field is using host endianness, so the issue will not emerge if the flatbuffer model is untouched - it only emerges when the flatbuffer model is exported or converted, like serialized into a `.tflite` file and being read on another machine, or being converted into a mlir module as I mentioned above.
2. I am not sure about this one but the `buffers` field seems only being used for constant operator tensors. It looks like those tensors are the only tensors whose values are stored in the model `buffers`. So the tensors whose values are calculated after model evaluation will not have this issue.

Due to the schema definition, we could not rely on any flatbuffer API changes to fix this issue. I think to fix this, we need to deal with the endianness manually whenever we try to populate the `buffers` field in the tflite model (like in the two converters I mentioned above) or read the `buffers` field of a finished model (like in `InterpreterBuilder` and maybe somewhere else). It looks to me that we need to do a case split for the data type every single time when `buffers` field is accessed, which is a bit annoying to be honest. I hope you guys could come up with something more element to deal with this issue, and please let me know if there is anything I could help, thanks.

**Comment by jdduke** [comment] 2020-12-09 19:59
You're right, that does leave us in a tricky situation.

For my own understanding, are you most interested in supporting the (big endian) -> (big endian) path, where both the conversion and execution take place on a big-endian machine? Or all potential permutations of little/big endian conversion and deployment?

**Comment by Sidong-Wei** [comment] 2020-12-09 21:51
For me, it will be best if we could settle this once and for all - i.e. make sure it is consistent across all platforms so that the entire flatbuffer models will work seamlessly across different machines and converters. So I think the second approach would be more preferred (while the first approach could be a temporary workaround for us).
My ideal solution on this would be implementing something similar to [byte_swap.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/tensor_bundle/byte_swap.cc) or other flatbuffer native method like EndianScalar at all the places where the `buffers` field is read or write (I hope there are not too many places besides the 2 converts and the `ParseTensors` call in `interpreter_builder.cc`). But I'm afraid it has to be more complicated as we will have to enumerate through the buffer vector to implement the byte-swap so we could not use those straightforward methods like `memcpy` anymore.

**Comment by jdduke** [comment] 2020-12-09 22:58
> For me, it will be best if we could settle this once and for all

Agreed, my question is more toward determining next steps and ordering. There could be a few simple tweaks we could make to get big -> big working, on the way toward full generality, if that is a blocker for any specific use-cases or project you're working on. If not, then the order of work doesn't necessarily matter and we can focus on the general solution.

**Comment by Sidong-Wei** [comment] 2020-12-10 00:28
Sure, thanks for being so thoughtful! I think the big -> big route does not have a general blocker right now. As mentioned before, to save and load `.tflite` binary model on the same machine does not have any issues.
What I did notice that may require a bit of tweaks is [here](https://github.com/tensorflow/tensorflow/blob/fcc4b966f1265f466e82617020af93670141b009/tensorflow/compiler/mlir/lite/flatbuffer_import.cc#L269). In this function and some lines below we are trying to access the buffer data in little-endian format. This method is taking endianness into consideration but unfortunately, they will retrieve the wrong data on big-endian machines right now. Do you think it will be necessary if we change this code into reading host endianness as a workaround and then change it back once we fix the `buffer` issue?

**Comment by terryheo** [comment] 2020-12-10 02:52
According to this,
https://google.github.io/flatbuffers/md__internals.html
`A FlatBuffer is a binary file and in-memory format consisting mostly of scalars of various sizes, all aligned to their own size. Each scalar is also always represented in little-endian format, as this corresponds to all commonly used CPUs today. FlatBuffers will also work on big-endian machines, but will be slightly slower because of additional byte-swap intrinsics.`

So, it looks like we'd better use little-endian for `buffers` for consistency.

**Comment by Sidong-Wei** [comment] 2020-12-10 03:58
> According to this,
> https://google.github.io/flatbuffers/md__internals.html
> `A FlatBuffer is a binary file and in-memory format consisting mostly of scalars of various sizes, all aligned to their own size. Each scalar is also always represented in little-endian format, as this corresponds to all commonly used CPUs today. FlatBuffers will also work on big-endian machines, but will be slightly slower because of additional byte-swap intrinsics.`
> 
> So, it looks like we'd better use little-endian for `buffers` for consistency.

Yes, that is true, and I think this is basically what we intend to achieve at last. Currently, all the other fields defined in the schema (which have types) are working properly except `buffers`, so it would make sense to fix `buffers` to use little-endian.


On the other hand, for those fields that are correctly stored in little-endian format, there do exists some places in the codebase where the access to these flatbuffer data is a bit careless, like the issue you are mentioning. It will be better to access data only using flatbuffer methods rather than the raw data pointer because flatbuffer methods will handle the endianness automatically. I am working on a PR for this particular issue and I will also keep an eye on any other similar issue related to flatbuffer endianness.

**Comment by Sidong-Wei** [comment] 2020-12-11 20:43
A short update:  I forgot to mention this before, that the `CustomQuantization` field and `custom_options` field may also require similar fixes as `buffers` field as per [schema definition](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs). I did not encounter these two fields frequently but theoretically they have the same issue as `buffers` field as they are also `ubyte` typed.

**Comment by kun-lu20** [comment] 2021-06-23 19:02
I think I also encountered similar issues when I ran the test case `//tensorflow/lite/tools/optimize:quantize_model_test` on BE machines.

The `LSTM` related tests in this test case would fail on BE platforms due to the following reasons:
1. `LSTM` related binary model files are not loaded correctly on BE machines since the tensor data is stored in LE format.
2. In certain quantization process, values should be copied into buffers from the tail on BE machines but actually they are not.

I made the code changes below to make this test case pass on BE machines:
1. Swap the buffer data once the binary model files are loaded.
2. Fill the buffers from the tail in two quantization related functions: `SymmetricQuantizeFloatsToInt16()` (in `tensorflow/lite/tools/optimize/quantization_utils.cc`) and `PortableSymmetricQuantizeFloats()` (in `tensorflow/lite/kernels/internal/reference/portable_tensor_utils.cc`) .

The code change would make this test case pass. However, it would cause regression on test cases like  `//tensorflow/lite/kernels:lstm_test` and `//tensorflow/lite/kernels:svdf_test`. 

I believe the reason of this regression is that there are other code snippets in the execution path of these TCs which also need to be updated, so that the buffer loading (filling) behaviour on BE machines would become consistent, just as @Sidong-Wei mentioned in https://github.com/tensorflow/tensorflow/issues/45009#issuecomment-740008230.

It looks like this flatbuffer endianness issue still needs an overall solution. @jdduke @terryheo Any updates from internal tracking? Thank you very much!

**Comment by Sidong-Wei** [comment] 2022-02-23 14:16
Hi @karimnosseir @terryheo, I wonder is there any update here? Thank you.

**Comment by kun-lu20** [comment] 2022-02-23 16:33
Hi @jdduke @terryheo , hope all is well.

Wonder if you have any updates reg this issue? Thanks!

**Comment by rposts** [comment] 2022-06-22 17:29
@terryheo @karimnosseir Wanted to follow-up on this issue - is there something we could do to assist with debugging it further?

Thanks!

**Comment by rposts** [comment] 2022-06-24 12:57
Thanks @terryheo - I understand that an internal tracking bug already exists for this issue.  Presumably it is a matter of prioritizing this task. Failing any immediate contributions do you have any rough idea when will this happen?

**Comment by kun-lu20** [comment] 2023-03-17 12:32
This issue could be closed since it has been addressed by PR #58494.

**Comment by pjpratik** [comment] 2023-04-10 14:59
Hi @skribm9 

As this [comment](https://github.com/tensorflow/tensorflow/issues/45009#issuecomment-1473762657) suggests, can you please confirm if this issue is addressed with the PR [#58494](https://github.com/tensorflow/tensorflow/pull/58494) ?

Thanks.

**Closed** 2023-04-12 06:10 UTC
Labels: stat:awaiting response, type:bug, comp:lite, TF 2.2
