### ISSUE TITLE
TypeError: Object of type float32 is not JSON serializable

### ISSUE THREAD

**Issue by nbro** [tensorflow/tensorflow#36801] opened 2020-02-16 23:32 UTC
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution: Mac OS Catalina (Version: 10.15.3)
- TensorFlow installed from: binary
- TensorFlow version: 2.1
- Python version: 3.7.5
- GPU model and memory: Intel Iris Pro 1536 MB

**Describe the current behavior**

I get the following error

> TypeError: Object of type float32 is not JSON serializable

when I try to save the state of the optimizer **after** having trained the model. Before training the model, I can save the state of the optimizer without getting any error.

**Describe the expected behavior**

No error.

**Code to reproduce the issue** 

```
import json

import tensorflow as tf


def get_model(input_shape=(1,)):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Input(shape=input_shape))
    model.add(tf.keras.layers.Dense(8, activation="relu"))
    model.add(tf.keras.layers.Dense(1))
    model.summary()
    model.compile(loss="mse", optimizer="adam")
    return model


def write_config(model, optimizer_file_path="optimizer.json"):
    with open(optimizer_file_path, "w") as f:
        json.dump(model.optimizer.get_config(), f, indent=4, sort_keys=True)


def get_data(n=100):
    import numpy as np
    data_x = np.random.rand(n, 1)
    data_y = np.asarray([1 if x > 0.5 else 0 for x in data_x]).reshape(data_x.shape)
    return data_x, data_y


if __name__ == '__main__':
    model = get_model()

    x, y = get_data()

    # No error before fitting.
    # write_config(model)

    model.fit(x, y, epochs=2)

    # Error after fitting.
    write_config(model)
```

**Other**

Note that [the documentation of `model.optimizer.get_config()` says that the returned value is serializable](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer#get_config)

> An optimizer config is a Python dictionary (serializable) containing the configuration of an optimizer.

**Comment by Saduf2019** [comment] 2020-02-18 06:51
@nbro can you please confirm if the issue faced is similar to [link](https://github.com/tensorflow/tensorflow/issues/28799).

**Comment by nbro** [comment] 2020-02-18 13:06
@Saduf2019 Have you read my issue above? In my case, the thing that isn't apparently serializable is a float32, while in the other issue a `Variable` isn't serializable. Furthermore, I am not using `save_model` or any similar method (because I can't use them and then load models from those save files with TFP).

**Comment by gowthamkpr** [comment] 2020-02-26 22:49
@nbro As mentioned in the issue [here](https://stackoverflow.com/questions/53082708/typeerror-object-of-type-float32-is-not-json-serializable) converting the optimizer value to string will not result in any error. Heres the [gist](https://colab.sandbox.google.com/gist/gowthamkpr/eef2fcd8bc3bda8c3eb46304a0404c42/untitled22.ipynb).

**Comment by nbro** [comment] 2020-02-26 22:52
@gowthamkpr Yes, I had also tried that. However, I don't want to save a string, but a dictionary! If I do what you're suggesting, I will have a file whose contents have quotes.

**Comment by gowthamkpr** [comment] 2020-02-28 02:03
I have serialized the optimizer using `tf.keras.optimizers.serialize()` 
Please find the gist [here](https://colab.sandbox.google.com/gist/gowthamkpr/639b68e7b04130b81a98cb18fa4b0ece/untitled22.ipynb)

**Comment by nbro** [comment] 2020-02-29 21:22
@gowthamkpr I still get the initial error with my actual code and not your gist or the example above.

**Comment by gowthamkpr** [comment] 2020-03-04 01:15
I am unable to reproduce your error @nbro. I am going to close this issue now as it not a bug. Please post your question in stackoverflow. Thanks!

**Comment by nbro** [comment] 2020-03-04 03:23
@gowthamkpr How do you know it's not a bug?

**Comment by gowthamkpr** [comment] 2020-03-04 18:47
Sorry for closing it abruptly @nbro

**Comment by tensorflowbutler** [comment] 2020-03-20 01:13
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gowthamkpr** [comment] 2020-03-30 17:04
Closing this issue as it has been inactive for more than 4 weeks . Please add additional comments and we can open this issue again. Thanks!

**Closed by gowthamkpr** 2020-03-30 17:04 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:support

**Comment by serg-bloim** [comment] 2023-07-24 19:09
Please look into this example, `tf.keras.optimizers.serialize()` doesn't work.
https://colab.research.google.com/gist/serg-bloim/3d4ade3e3ef356b4d0345d4ae9733fe1/untitled22.ipynb#scrollTo=s79XwQeXlmeU
The documentation says the method 'Serialize the optimizer configuration to JSON compatible python dict.'
https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/serialize
But when I get the result and trying to serialize it into a json, it fails due to numpy.float32 fields inside of the config.
https://colab.research.google.com/gist/serg-bloim/3d4ade3e3ef356b4d0345d4ae9733fe1/untitled22.ipynb#scrollTo=s79XwQeXlmeU
@gowthamkpr recommended to wrap a result into a str, but that's not json-compatible.
