### ISSUE TITLE
TPU Distribution not working for r1.13

### ISSUE THREAD

**Issue by jinamshah** [tensorflow/tensorflow#30429] opened 2019-07-05 08:44 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No, I have used XLNet training
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.1
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I tried to use TPUDistribution Strategy to use TPUv2 pods for training XLNet, but it gave me error(mentioned in logs below)
**Describe the expected behavior**
TPU Distribution Strategy should be able to implement this
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

NUM_TPUS = 4
tpu_cluster_resolver = tf.contrib.cluster_resolver.TPUClusterResolver([os.environ['TPU_NAME']], zone=os.environ['TPU_ZONE'], project=os.environ['GCE_PROJECT_NAME'])
tpu_strategy = tf.contrib.tpu.TPUDistributionStrategy(tpu_cluster_resolver)
run_config = tf.contrib.tpu.RunConfig(
    cluster=tpu_cluster_resolver,
    model_dir=OUTPUT_DIR,
    save_checkpoints_steps=1000,
    tpu_config=tf.contrib.tpu.TPUConfig(
        iterations_per_loop=1000,
        num_shards=8 * NUM_TPUS,
        per_host_input_for_training=tf.contrib.tpu.InputPipelineConfig.PER_HOST_V2),
    keep_checkpoint_max=5,
    train_distribute=tpu_strategy
)

xlnet_config = xlnet.XLNetConfig(json_path=os.path.join(XLNET_PRETRAINED_DIR, 'xlnet_config.json'))
xlnet_model = run_classifier.get_model_fn(num_classes)
estimator = tf.contrib.tpu.TPUEstimator(
        use_tpu=True,
        model_fn=xlnet_model,
        config=run_config,
        params=None,
        train_batch_size=TRAIN_BATCH_SIZE,
        predict_batch_size=PREDICT_BATCH_SIZE,
        eval_batch_size=EVAL_BATCH_SIZE)

train_input_fn = run_classifier.file_based_input_fn_builder(
    input_file="gs://input_file.tfrecord",
    seq_length=MAX_SEQ_LENGTH,
    is_training=True,
    drop_remainder=True)

estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
I0705 07:33:40.742511 139772774643520 tpu_system_metadata.py:59] Querying Tensorflow master (grpc://a.b.c.d:8470) for TPU system metadata.

INFO:tensorflow:Found TPU system:

I0705 07:33:40.888471 139772774643520 tpu_system_metadata.py:120] Found TPU system:

INFO:tensorflow:*** Num TPU Cores: 32

I0705 07:33:40.890206 139772774643520 tpu_system_metadata.py:121] *** Num TPU Cores: 32

INFO:tensorflow:*** Num TPU Workers: 4

I0705 07:33:40.895273 139772774643520 tpu_system_metadata.py:122] *** Num TPU Workers: 4

INFO:tensorflow:*** Num TPU Cores Per Worker: 8

I0705 07:33:40.898422 139772774643520 tpu_system_metadata.py:124] *** Num TPU Cores Per Worker: 8

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, -1, 4144468757051904050)

I0705 07:33:40.905382 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, -1, 4144468757051904050)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 8307488279136102617)

I0705 07:33:40.907173 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 8307488279136102617)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 15853259856546976898)

I0705 07:33:40.908568 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 15853259856546976898)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 15507240626127054220)

I0705 07:33:40.909704 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 15507240626127054220)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 9584144648126289353)

I0705 07:33:40.910813 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 9584144648126289353)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 1596766444393261122)

I0705 07:33:40.911922 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 1596766444393261122)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 107997388316727553)

I0705 07:33:40.913051 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 107997388316727553)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 5933300785999976036)

I0705 07:33:40.914163 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 5933300785999976036)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 17288917258161835028)

I0705 07:33:40.915283 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 17288917258161835028)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 10754988339652322123)

I0705 07:33:40.916407 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 10754988339652322123)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 15827474055072985247)

I0705 07:33:40.917562 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 15827474055072985247)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:CPU:0, CPU, -1, 17772760716915846644)

I0705 07:33:40.918668 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:CPU:0, CPU, -1, 17772760716915846644)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:XLA_CPU:0, XLA_CPU, 17179869184, 1079066005188293108)

I0705 07:33:40.919769 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:XLA_CPU:0, XLA_CPU, 17179869184, 1079066005188293108)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:0, TPU, 17179869184, 8833670584752429122)

I0705 07:33:40.920902 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:0, TPU, 17179869184, 8833670584752429122)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:1, TPU, 17179869184, 9749399796990995666)

I0705 07:33:40.922011 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:1, TPU, 17179869184, 9749399796990995666)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:2, TPU, 17179869184, 4972353230220870757)

I0705 07:33:40.923123 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:2, TPU, 17179869184, 4972353230220870757)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:3, TPU, 17179869184, 513286311176106128)

I0705 07:33:40.924228 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:3, TPU, 17179869184, 513286311176106128)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:4, TPU, 17179869184, 14096714381964779427)

I0705 07:33:40.925353 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:4, TPU, 17179869184, 14096714381964779427)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:5, TPU, 17179869184, 11601778884065416558)

I0705 07:33:40.926468 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:5, TPU, 17179869184, 11601778884065416558)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:6, TPU, 17179869184, 5715109243185029245)

I0705 07:33:40.927602 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:6, TPU, 17179869184, 5715109243185029245)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:7, TPU, 17179869184, 293318216316046063)

I0705 07:33:40.928760 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU:7, TPU, 17179869184, 293318216316046063)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 5955036069992402374)

I0705 07:33:40.929885 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:2/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 5955036069992402374)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:CPU:0, CPU, -1, 6513862482907012835)

I0705 07:33:40.930993 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:CPU:0, CPU, -1, 6513862482907012835)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:XLA_CPU:0, XLA_CPU, 17179869184, 7175494438094722165)

I0705 07:33:40.932108 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:XLA_CPU:0, XLA_CPU, 17179869184, 7175494438094722165)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:0, TPU, 17179869184, 14689466335568240094)

I0705 07:33:40.933240 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:0, TPU, 17179869184, 14689466335568240094)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:1, TPU, 17179869184, 2413636980211343743)

I0705 07:33:40.934341 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:1, TPU, 17179869184, 2413636980211343743)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:2, TPU, 17179869184, 8959053062706485002)

I0705 07:33:40.935440 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:2, TPU, 17179869184, 8959053062706485002)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:3, TPU, 17179869184, 13668243215792653265)

I0705 07:33:40.936621 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:3, TPU, 17179869184, 13668243215792653265)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:4, TPU, 17179869184, 916241737357705146)

I0705 07:33:40.937787 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:4, TPU, 17179869184, 916241737357705146)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:5, TPU, 17179869184, 9081936198773042571)

I0705 07:33:40.938918 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:5, TPU, 17179869184, 9081936198773042571)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:6, TPU, 17179869184, 17137058361537129430)

I0705 07:33:40.940040 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:6, TPU, 17179869184, 17137058361537129430)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:7, TPU, 17179869184, 9871713588844769915)

I0705 07:33:40.941166 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU:7, TPU, 17179869184, 9871713588844769915)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 13242834065860745167)

I0705 07:33:40.942301 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:1/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 13242834065860745167)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:CPU:0, CPU, -1, 14166663181551736188)

I0705 07:33:40.943438 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:CPU:0, CPU, -1, 14166663181551736188)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:XLA_CPU:0, XLA_CPU, 17179869184, 2214898881771697800)

I0705 07:33:40.944600 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:XLA_CPU:0, XLA_CPU, 17179869184, 2214898881771697800)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:0, TPU, 17179869184, 17428311216696528109)

I0705 07:33:40.945710 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:0, TPU, 17179869184, 17428311216696528109)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:1, TPU, 17179869184, 5022423960481121783)

I0705 07:33:40.946825 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:1, TPU, 17179869184, 5022423960481121783)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:2, TPU, 17179869184, 3367013141681705422)

I0705 07:33:40.947974 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:2, TPU, 17179869184, 3367013141681705422)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:3, TPU, 17179869184, 11677911886123920679)

I0705 07:33:40.949125 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:3, TPU, 17179869184, 11677911886123920679)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:4, TPU, 17179869184, 8941627580085686113)

I0705 07:33:40.950233 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:4, TPU, 17179869184, 8941627580085686113)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:5, TPU, 17179869184, 3622957282534488438)

I0705 07:33:40.951513 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:5, TPU, 17179869184, 3622957282534488438)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:6, TPU, 17179869184, 11366405219786765949)

I0705 07:33:40.952693 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:6, TPU, 17179869184, 11366405219786765949)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:7, TPU, 17179869184, 4659665062672917141)

I0705 07:33:40.953825 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU:7, TPU, 17179869184, 4659665062672917141)

INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 16417307345580175404)

I0705 07:33:40.955019 139772774643520 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:3/device:TPU_SYSTEM:0, TPU_SYSTEM, 8589934592, 16417307345580175404)

INFO:tensorflow:Error recorded from training_loop: 'TPUDistributionStrategy' object has no attribute 'configure'

I0705 07:33:40.956579 139772774643520 error_handling.py:70] Error recorded from training_loop: 'TPUDistributionStrategy' object has no attribute 'configure'

INFO:tensorflow:training_loop marked as finished

I0705 07:33:40.957767 139772774643520 error_handling.py:93] training_loop marked as finished

WARNING:tensorflow:Reraising captured error

W0705 07:33:40.958972 139772774643520 tf_logging.py:161] Reraising captured error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

/home/jinamshah/venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
   2455     finally:
   2456       rendezvous.record_done('training_loop')
-> 2457       rendezvous.raise_errors()
   2458 
   2459   def evaluate(self,

/home/jinamshah/venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py in raise_errors(self, timeout_sec)
    126       else:
    127         logging.warn('Reraising captured error')
--> 128         six.reraise(typ, value, traceback)
    129 
    130     for k, (typ, value, traceback) in kept_errors:

/home/jinamshah/venv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/home/jinamshah/venv/lib/python3.6/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
   2450           steps=steps,
   2451           max_steps=max_steps,
-> 2452           saving_listeners=saving_listeners)
   2453     except Exception:  # pylint: disable=broad-except
   2454       rendezvous.record_error('training_loop', sys.exc_info())

/home/jinamshah/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in train(self, input_fn, hooks, steps, max_steps, saving_listeners)
    356 
    357       saving_listeners = _check_listeners_type(saving_listeners)
--> 358       loss = self._train_model(input_fn, hooks, saving_listeners)
    359       logging.info('Loss for final step: %s.', loss)
    360       return self

/home/jinamshah/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model(self, input_fn, hooks, saving_listeners)
   1120   def _train_model(self, input_fn, hooks, saving_listeners):
   1121     if self._train_distribution:
-> 1122       return self._train_model_distributed(input_fn, hooks, saving_listeners)
   1123     else:
   1124       return self._train_model_default(input_fn, hooks, saving_listeners)

/home/jinamshah/venv/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py in _train_model_distributed(self, input_fn, hooks, saving_listeners)
   1181       return self
   1182     else:
-> 1183       self._config._train_distribute.configure(self._config.session_config)
   1184       return self._actual_train_model_distributed(
   1185           self._config._train_distribute, input_fn, hooks, saving_listeners)

AttributeError: 'TPUDistributionStrategy' object has no attribute 'configure'

**Comment by gadagashwini** [comment] 2019-07-11 05:04
@jinamshah Can you give us the complete code to reproduce the issue on our end. Thanks!

**Comment by jinamshah** [comment] 2019-07-12 05:56
@gadagashwini the rest of the code is proprietary. If you can tell me which part you need, I can help with that, but giving you the full code would not possible for me

**Comment by gadagashwini** [comment] 2019-07-12 09:32
@jinamshah I understand the privacy. Will it be possible to provide minimal code with which we can reproduce the mentioned issue. It will indeed help us to move faster. Thanks!

**Comment by gadagashwini** [comment] 2019-07-18 04:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-18 04:49 UTC
Labels: TF 1.13, comp:tpus, stat:awaiting response, type:bug/performance
