### ISSUE TITLE
Windows does not build tflite: No module named 'tensorflow.contrib.lite.toco.python'

### ISSUE THREAD

**Issue by Azureum** [tensorflow/tensorflow#16374] opened 2018-01-24 19:26 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Build 16299.192  and Windows 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.5.0rc1 and tf-nightly  1.6.0.dev20180124
- **Python version**: 3.6.2 and 3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: Nvidia GT 740M 2GB
- **Exact command to reproduce**: toco --help

### Describe the problem
I am trying to run the codelab tutorial of tensorflow lite. After installing tf-nightly, when I try to run the command "toco --help", I get the error ModuleNotFoundError: No module named 'tensorflow.contrib.lite.toco.python'.

I have tried this on 3 computers( all Windows) and the same problem persists.

### Source code / logs
C:\Users\HP\Downloads>toco --help
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\toco.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'tensorflow.contrib.lite.toco.python'

**Comment by ushnish** [comment] 2018-01-25 19:35
Did you build the toco library using bazel? What worked for me is (from within the TF repo folder)

`bazel build tensorflow/contrib/lite/toco:toco`

`bazel-bin/tensorflow/contrib/lite/toco/toco --help`

**Comment by Azureum** [comment] 2018-01-25 21:03
No, I didn't build the tensorflow repository but installed tf-nightly from pip.
I tried to build toco using bazel, but the build failed. Here's the traceback:

```
ERROR: C:/users/hp/documents/tensorflow/tensorflow/contrib/lite/toco/BUILD:151:1: C++ compilation of rule '//tensorflow/contrib/lite/toco:toco_port' failed (Exit 2)
tensorflow/contrib/lite/toco/toco_port.cc(164): error C3861: 'open': identifier not found
tensorflow/contrib/lite/toco/toco_port.cc(173): error C3861: 'read': identifier not found
tensorflow/contrib/lite/toco/toco_port.cc(176): error C3861: 'close': identifier not found
tensorflow/contrib/lite/toco/toco_port.cc(180): error C3861: 'close': identifier not found
tensorflow/contrib/lite/toco/toco_port.cc(193): error C3861: 'open': identifier not found
tensorflow/contrib/lite/toco/toco_port.cc(201): error C3861: 'write': identifier not found
tensorflow/contrib/lite/toco/toco_port.cc(203): error C3861: 'close': identifier not found
tensorflow/contrib/lite/toco/toco_port.cc(208): error C3861: 'close': identifier not found
Target //tensorflow/contrib/lite/toco:toco failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.826s, Critical Path: 0.94s
FAILED: Build did NOT complete successfully
```

**Comment by ushnish** [comment] 2018-01-25 21:23
I'd suggest instead of doing pip install, git clone the TF repo and run the bazel build toco command from the root of the TF repo. If there are no issues it takes about 10-15 min to build the binary.

**Comment by Azureum** [comment] 2018-01-25 21:35
Yes, I would certainly like to do that, but building tensorflow from source on Windows gives a lot of errors (with Visual Studio and Bazel) like the one above. I would try to do it in a linux environment at a later date.

**Comment by aselle** [comment] 2018-02-08 00:53
Sorry the issue is that toco is currently not supported on Windows build for cmake. I will look into adding this.

**Comment by tensorflowbutler** [comment] 2018-02-22 13:07
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by SanthoshMKunthe** [comment] 2018-02-26 12:03
Am geetting TOCO_CONVERT error. . .Kindlyhelp. . .

**AttributeError: module 'tensorflow.contrib.lite.python.lite' has no attribute 'toco_convert'**
_see last two  lines for error causing code_
//=================================
import tensorflow  as tf
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as lib

from tensorflow.python.tools import freeze_graph
from tensorflow.python.tools import optimize_for_inference_lib


print(tf.__version__)
data=pd.read_csv('C:\ml\irisInAndroid\iris.data',names=['f1','f2','f3','f4','f5'])

s=np.asarray([1,0,0])
ve=np.asarray([0,1,0])
vi=np.asarray([0,0,1])

data['f5']=data['f5'].map({'Iris-setosa':s,'Iris-versicolor':ve,'Iris-virginica':vi})


data=data.iloc[np.random.permutation(len(data))]

print(data)

data=data.reset_index(drop=True)

trainFeats=data.ix[0:105,['f1','f2','f3','f4']]
temp=data['f5']
trainlabels=temp[0:106]

y=tf.placeholder(tf.float32,shape=[None, 3])

m=tf.Variable(tf.zeros([4,3]))
x=tf.placeholder(tf.float32,shape=[None,4],name="Input")
c=tf.Variable(tf.zeros([3]))

mxc = tf.nn.softmax((tf.matmul(x, m) + c) ,name="output")

loss = tf.reduce_mean(-tf.reduce_sum(y * tf.log(mxc), reduction_indices=[1]))

train_step = tf.train.AdamOptimizer(0.01).minimize(loss)

sess = tf.InteractiveSession()
init = tf.initialize_all_variables()
sess.run(init)




epoch=2000
for step in range(epoch):
  print(sess.run([train_step,loss], feed_dict={x: trainFeats, y:[t for t in trainlabels.as_matrix()]}))

testData=data.ix[130,['f1','f2','f3','f4']]
testDataInFrormat=testData.reshape(1,4)
print(sess.run(tf.argmax(mxc),feed_dict={x:testDataInFrormat}))

tf.train.write_graph(sess.graph_def,'pbtxtFiles/','savegraph.pbtxt',as_text=True)

tf.train.Saver().save(sess,'pbtxtFiles/model.ckpt')

MODEL_NAME = 'iris'
input_graph_path = 'pbtxtFiles/savegraph.pbtxt'
checkpoint_path = 'pbtxtFiles/model.ckpt'
input_saver_def_path = ""
input_binary = False
output_node_names = "output"
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"
output_frozen_graph_name = 'pbtxtFiles/frozen_model_'+MODEL_NAME+'.pb'
output_optimized_graph_name = 'pbtxtFiles/optimized_inference_model_'+MODEL_NAME+'.pb'
clear_devices = True

freeze_graph.freeze_graph(input_graph_path, input_saver_def_path,
                          input_binary, checkpoint_path, output_node_names,
                          restore_op_name, filename_tensor_name,
                          output_frozen_graph_name, clear_devices, "")


output_graph_def = optimize_for_inference_lib.optimize_for_inference(
        sess.graph_def,
        ["Input"], # an array of the input node(s)
        ["output"], # an array of output nodes
        tf.float32.as_datatype_enum)

tflite_model=tf.contrib.lite.toco_convert(sess.graph_def,[x],[mxc])
open("wow.tflite","w").write(tflite_model)

@Azureum @ushnish @aselle @tensorflowbutler @tatianashp @d0k @e-lin @fabriciojoc @gaohuazuo @HaebinShin @iamaziz @JacksonKontny @k-w-w @lahwran @m-colombo @n3011 @oahziur @paderijk @qbx2 @rachellim @saeta @t13m @ucdmkt @vade @wagonhelm @xiaoyaozhuzi @yacoder @zackchase 
am getting .pb abd .ckpt

**Comment by StarOverSeas** [comment] 2018-03-01 02:34
has this problem been solved ?

**Comment by SanthoshMKunthe** [comment] 2018-03-01 12:09
nope @StarOverSeas . . . it works fine in Ubuntu but sucks in windows. . .

**Comment by lahwran** [comment] 2018-03-01 17:17
why was I mentioned on this issue?

**Comment by SanthoshMKunthe** [comment] 2018-03-02 02:12
Sorry Lawren. . . Accept my humble apologies. . . If possible kindly look
at this issue. . . https://github.com/tensorflow/tensorflow/issues/17349
and help me if possible. . .

**Comment by sdsouza33** [comment] 2018-03-02 06:34
when will this be solved ?

**Comment by lahwran** [comment] 2018-03-02 23:15
While I have previously contributed code to tensorflow, I am not an ongoing team member; I work for an unrelated company doing unrelated things, and my contributions to tensorflow have been trivial fixes to issues I noticed in my spare time. Please give the tensorflow team time to see this thread and work through the issue, and be aware that if you found me to ping, you probably also pinged other people who are not core team members.

**Comment by VenturingVenturer** [comment] 2018-03-08 03:44
Any idea when will this be solved?  Is there any temporary workaround that we could use?

**Comment by sdsouza33** [comment] 2018-03-09 02:02
Guys I've got mine running on Linux. I don't think windows as of now supports Toco but Linux does. So just use it on Linux, problem solved for now

**Comment by VenturingVenturer** [comment] 2018-03-09 03:28
Thank you sdsouza33. I also started looking into running it on Linux because there is no info on when it will be supported on Windows

**Comment by tensorflowbutler** [comment] 2018-03-25 03:43
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by clone2code** [comment] 2018-04-06 14:25
@aselle any update on how to get this working ??
@ushnish Hi does git cloning the TF repo and running the bazel build toco command from the root of the TF repo work for you ??

**Comment by tensorflowbutler** [comment] 2018-04-21 18:27
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-06 18:29
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ZZANZU** [comment] 2018-05-11 11:04
ㅠㅠ

**Comment by tensorflowbutler** [comment] 2018-05-27 03:03
Nagging Assignee @aselle: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:50
Nagging Assignee @aselle: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:13
Nagging Assignee @aselle: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ushnish** [comment] 2018-06-25 19:30
I think we can close this

**Comment by tensorflowbutler** [comment] 2018-07-10 19:05
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by MauryaRitesh** [comment] 2018-07-20 05:37
Using Linux is not an ultimate solution

**Comment by jdduke** [comment] 2018-08-01 18:43
Duplicate of #20975.

**Closed by jdduke** 2018-08-01 18:43 UTC
Labels: comp:lite, stat:awaiting tensorflower, type:build/install

**Comment by AliceDinh** [comment] 2018-08-02 07:50
@ushnish hi, I am following the instructions at:
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets-2-tflite/#2
For CentOS, I have installed Bazel successfully when using your suggestions:
```
bazel build tensorflow/contrib/lite/toco:toco
bazel-bin/tensorflow/contrib/lite/toco/toco --help
```
but when I run the command to convert model to TFLite:
```
IMAGE_SIZE=224
toco \
  --input_file=tf_files/retrained_graph.pb \
  --output_file=tf_files/optimized_graph.lite \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --input_shape=1,${IMAGE_SIZE},${IMAGE_SIZE},3 \
  --input_array=input \
  --output_array=final_result \
  --inference_type=FLOAT \
  --input_data_type=FLOAT
```
I got error: 

```
[nhandt@dev-bigdata02 tensorflow]$ toco \
>   --input_file=retrained_graph.pb \
>   --output_file=optimized_graph.lite \
>   --input_format=TENSORFLOW_GRAPHDEF \
>   --output_format=TFLITE \
>   --input_shape=1,${IMAGE_SIZE},${IMAGE_SIZE},3 \
>   --input_array=input \
>   --output_array=final_result \
>   --inference_type=FLOAT \
>   --input_data_type=FLOAT
/home/nhandt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
TOCO from pip install is currently not working on command line.
Please use the python TOCO API or use
bazel run tensorflow/contrib/lite:toco -- <args> from a TensorFlow source dir.
```
Then I changed to run toco from source dir:

```
[nhandt@dev-bigdata02 tensorflow]$ IMAGE_SIZE=224
[nhandt@dev-bigdata02 tensorflow]$ bazel run tensorflow/contrib/lite:toco \
>   --input_file=retrained_graph.pb \
>   --output_file=optimized_graph.lite \
>   --input_format=TENSORFLOW_GRAPHDEF \
>   --output_format=TFLITE \
>   --input_shape=1,${IMAGE_SIZE},${IMAGE_SIZE},3 \
>   --input_array=input \
>   --output_array=final_result \
>   --inference_type=FLOAT \
>   --input_data_type=FLOAT
```
**ERROR: Unrecognized option: --input_file=retrained_graph.pb**
retrained_graph.pb is under tensorflow directory: tensorflow/retrained_graph.pb
Please advise me how to run this script with toco. Thanks

**Comment by jdduke** [comment] 2018-08-02 15:36
Hi @AliceDinh, when you execute a binary via `bazel run`, you need to insert `--` before any command-line arguments you want to pass to the target binary. Try changing

`bazel run tensorflow/contrib/lite:toco --input_file=...`

to

`bazel run tensorflow/contrib/lite:toco -- --input_file=...`

**Comment by cjr0106** [comment] 2018-09-27 14:18
@aselle  hi, wheather the toco is currently  supported on Windows ? i still met the wrong on Windows.
RuntimeError: TOCO failed see console for info.
b'e:\\anaconda3\\lib\\site-packages\\h5py\\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.\r\n  from ._conv import register_converters as _register_converters\r\nTraceback (most recent call last):\r\n  File "e:\\anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 18, in swig_import_helper\r\n    fp, pathname, description = imp.find_module(\'_tensorflow_wrap_toco\', [dirname(__file__)])\r\n  File "e:\\anaconda3\\lib\\imp.py", line 297, in find_module\r\n    raise ImportError(_ERR_MSG.format(name), name=name)\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "e:\\anaconda3\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "e:\\anaconda3\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "E:\\Anaconda3\\Scripts\\toco_from_protos.exe\\__main__.py", line 5, in <module>\r\n  File "e:\\anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\toco_from_protos.py", line 22, in <module>\r\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\r\n  File "e:\\anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 28, in <module>\r\n    _tensorflow_wrap_toco = swig_import_helper()\r\n  File "e:\\anaconda3\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 20, in swig_import_helper\r\n    import _tensorflow_wrap_toco\r\nModuleNotFoundError: No module named \'_tensorflow_wrap_toco\'\r\n'
None

**Comment by thangvip4321** [comment] 2018-10-16 06:03
@cjr0106 same problem here. How can we fix this problem?
`Traceback (most recent call last):
  File "E:\adwqe.py", line 22, in <module>
    tflite_model = converter.convert()
  File "C:\Users\thang\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\lite\python\lite.py", line 439, in convert
    **converter_kwargs)
  File "C:\Users\thang\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\lite\python\convert.py", line 309, in toco_convert_impl
    input_data.SerializeToString())
  File "C:\Users\thang\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\lite\python\convert.py", line 109, in toco_convert_protos
    (stdout, stderr))
RuntimeError: TOCO failed see console for info.
b'Traceback (most recent call last):\r\n  File "c:\\users\\thang\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 18, in swig_import_helper\r\n    fp, pathname, description = imp.find_module(\'_tensorflow_wrap_toco\', [dirname(__file__)])\r\n  File "c:\\users\\thang\\appdata\\local\\programs\\python\\python35\\lib\\imp.py", line 296, in find_module\r\n    raise ImportError(_ERR_MSG.format(name), name=name)\r\nImportError: No module named \'_tensorflow_wrap_toco\'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File "c:\\users\\thang\\appdata\\local\\programs\\python\\python35\\lib\\runpy.py", line 193, in _run_module_as_main\r\n    "__main__", mod_spec)\r\n  File "c:\\users\\thang\\appdata\\local\\programs\\python\\python35\\lib\\runpy.py", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File "C:\\Users\\thang\\AppData\\Local\\Programs\\Python\\Python35\\Scripts\\toco_from_protos.exe\\__main__.py", line 5, in <module>\r\n  File "c:\\users\\thang\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\toco_from_protos.py", line 22, in <module>\r\n    from tensorflow.contrib.lite.toco.python import tensorflow_wrap_toco\r\n  File "c:\\users\\thang\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 29, in <module>\r\n    _tensorflow_wrap_toco = swig_import_helper()\r\n  File "c:\\users\\thang\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\tensorflow\\contrib\\lite\\toco\\python\\tensorflow_wrap_toco.py", line 21, in swig_import_helper\r\n    import _tensorflow_wrap_toco\r\nImportError: No module named \'_tensorflow_wr`

**Comment by homandiy** [comment] 2019-01-22 10:05
To use toco in windows 10:
```
c:\tensorflow>bazel build tensorflow/contrib/lite/toco:toco
...
INFO: Elapsed time: 362.227s, Critical Path: 143.59s
INFO: 1138 processes: 1138 local.

INFO: Build completed successfully, 1149 total actions
```

6.5 minutes later, it's done. Let's test it.

```
c:\tensorflow>bazel run tensorflow/contrib/lite/toco
WARNING: Option 'experimental_shortened_obj_file_path' is deprecated
INFO: Analysed target //tensorflow/contrib/lite/toco:toco (0 packages loaded).
INFO: Found 1 target...
Target //tensorflow/contrib/lite/toco:toco up-to-date:
  C:/users/homan/_bazel_homan/xv6zejqw/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tensorflow/contrib/lite/toco/toco
INFO: Elapsed time: 1.369s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: C:/users/homan/_bazel_homan/xv6zejqw/execroot/org_tensorflow/bazel-out/x64_windows-opt/bin/tINFO: Build completed successfully, 1 total action
usage: C:\users\homan\_bazel_homan\xv6zejqw\execroot\org_tensorflow\bazel-out\x64_windows-opt\bin\tensorflow\contrib\lite\toco\toco

Flags:...

```
