### ISSUE TITLE
Error when using tf.keras.backend.function() in 1.14.0-rc0/1.14.0

### ISSUE THREAD

**Issue by bmiwcy** [tensorflow/tensorflow#29952] opened 2019-06-19 08:39 UTC
```
def input_derivative(model, x, goal):
  """ Calculate derivatives wrt the intputs """
  y_true = Input(shape=(10,))
  ce = categorical_crossentropy(y_true, model.output)
  grad_ce = tf.keras.backend.gradients(ce, model.inputs)
  func = tf.keras.backend.function(model.inputs + [y_true], grad_ce)
  output = func([x, goal])
  return output
```

Here is my code try to calculate gradients.
It is work in tensorflow1.13.1
but get error message at tensorflow1.14.0-rc0 like the following
```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Expected size[0] in [0, 0], but got 1
	 [[{{node softmax_cross_entropy_with_logits/Slice_1}}]]
	 [[gradients/conv2d/Conv2D_grad/Conv2DBackpropInput/_101]]
  (1) Invalid argument: Expected size[0] in [0, 0], but got 1
	 [[{{node softmax_cross_entropy_with_logits/Slice_1}}]]
0 successful operations.
0 derived errors ignored.
```

**Comment by bananabowl** [comment] 2019-06-19 21:57
As 1.14.0 is now released, please try running your code with it and let me know if you're still seeing issues.

**Comment by bmiwcy** [comment] 2019-06-20 01:22
> As 1.14.0 is now released, please try running your code with it and let me know if you're still seeing issues.

I just tried 1.14.0 and got the same issues.

**Comment by achandraa** [comment] 2019-06-27 08:02
Please provide details about what platform you are using (operating system, architecture).  Also, did you compile from source or install a binary?

Make sure you also include the exact code snippet to reproduce the issue included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment] 2019-07-01 10:05
I am able to reproduce the issue on colab with tensorflow 1.14.0. Thanks!

**Comment by bmiwcy** [comment] 2019-07-04 04:37
> Please provide details about what platform you are using (operating system, architecture). Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact code snippet to reproduce the issue included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

i tried on https://colab.research.google.com and ubuntu. Installed by pip install

**Comment by gadagashwini** [comment] 2019-10-18 04:08
@bmiwcy, Is this still issue? Would you like try latest Tf 1.15.0 version. Let us know how it progresses. Thanks!

**Comment by tensorflowbutler** [comment] 2019-11-01 12:27
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gadagashwini** [comment] 2019-11-04 08:44
@bmiwcy, Is this still an issue!

**Comment by tensorflowbutler** [comment] 2019-11-19 12:32
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2019-12-04 12:37
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by gadagashwini** [comment] 2019-12-05 05:06
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-12-05 05:06 UTC
Labels: comp:keras, stat:awaiting response, type:bug
