### ISSUE TITLE
Error when running gmake for Tensorflow Lite Micro

### ISSUE THREAD

**Issue by Shusuke-O** [tensorflow/tensorflow#35759] opened 2020-01-11 00:38 UTC
Hello. 
I have an issue similar to #29524.

I'm trying to generate a Keil project for the microcontroller I'm developing.
When I was following procedures in the following link, I got the error:

https://www.tensorflow.org/lite/microcontrollers/library

System informationOS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.2 (19C57)
TensorFlow installed from (source or binary): source
TensorFlow version: e689e24
GCC/Compiler version (if compiling from source): Apple clang version 11.0.0 (clang-1100.0.33.16)

Describe the problem
When running$ gmake -f tensorflow/lite/experimental/micro/tools/Makefile generate_projects results in the following error:

gmake: *** No rule to make target 'tensorflow/lite/micro/tools/make/gen/osx_x86_64/prj/micro_speech/make/tensorflow/lite/experimental/micro/examples/micro_speech/simple_features/simple_model_settings.h', needed by 'generate_micro_speech_make_project'.  Stop.

**Comment by k8rapps** [comment] 2020-01-20 19:23
I can confirm I'm seeing this exact behavior trying to build an mBed project.  I've tried on both Windows and a clean Ubuntu 19.10 VM

**Comment by sushreebarsa** [comment] 2021-08-01 14:33
@Shusuke-O  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-17 18:53 UTC
Labels: stat:awaiting response, stat:awaiting tensorflower, type:bug, stalled, comp:lite
