### ISSUE TITLE
Bug with tensorflow.random_normal() when using placeholders and last dimension is 1 

### ISSUE THREAD

**Issue by isabeaups** [tensorflow/tensorflow#3311] opened 2016-07-14 12:04 UTC
tensorflow.shape(x) gives ? for the last dimension when the last dimension is 1.
This is a problem if you have layers or inputs which are only one dimensional. 
### Environment info

Operating System: OSX
Tensorflow 0.9.0

Installed version of CUDA and cuDNN: 
problem not related to CUDA or cuDNN

**Edit:** thanks to @cwhipkey I noticed I mischaracterized the problem, edited version below.
### Steps to reproduce

`import tensorflow as tf`
`n=1`
`x = tf.placeholder(tf.float32, shape=(None, None, n), name='x')`
`shp = tf.shape(x)`

shp is (?,?,n)  as it should be.

But then if I use shp to create a random_normal tensor of the same shape, it will fail if n==1.

`noise = tf.random_normal(shp,mean=0,stddev=1)`

`print(noise.get_shape(noise))`
has output (?,?,n) if n>1 but output (?,?,?) if n==1.

This is a problem, because if I then do 
`xtilde= x+noise`

this will give me an error if n==1.
Specifically in my case:

>   File "/anaconda/envs/hrnn/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 630, in _dynamic_rnn_loop
>     "Input size (depth of inputs) must be accessible via shape inference, "
> ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.

when I feed this xtilde to dynamic_rnn
`rnn.dynamic_rnn(rnn, xtilde,
                                                       initial_state=self.hhat_combined_init,
                                                       scope='RNN')`
I get no such error if n>1.

**Comment by cwhipkey** [comment] 2016-07-14 18:33
What are you printing from shp to see the (?,?,1)?  Against the head version, I tried the following and could not reproduce it.  I also tried to run shp in my session, but that requires an actual value of the placeholder in order to run.

import tensorflow as tf
 n=1
 x = tf.placeholder(tf.float32, shape=(None, None, n), name='x')
 shp = tf.shape(x)
 print(str(shp))
 print(x.get_shape())

Output:
Tensor("Shape:0", shape=(3,), dtype=int32)
(?, ?, 1)

**Comment by isabeaups** [comment] 2016-07-15 08:20
Thank you for looking into it.
I'm seeing this in the PyCharm debugging mode.

I think you are right, I missidentified the problem. shp is actually ok, the problem occurs while using 
`tf.random_normal(shp,mean=0,stddev=1)`

This occures inside my _build_graph methode of a neural network.

I have the following line:

`xtilde = x + noise_level * tf.random_normal(tf.shape(x),
                                                                    mean=0.,
                                                                    stddev=1.)`

which fails because
while x.get_shape() = (?,?,1)
tf.random_normal(tf.shape(x),mean=0,stddev=1).get_shape() = (?,?,?)

and so the addition fails because the tensors are not of the same shape.

So the problem is that tensorflow.random_normal has fails to be correctly shaped when the last dimension is 1.

**Comment by cwhipkey** [comment] 2016-07-19 17:39
A ? in a shape output means "unknown dimenson value", and that is
considered compatible with a dimension with a known size.  So I'm not sure
it would give an error from that step.

Does it fail when running the model, or while setting up the model?  What
is the error message you get?

**Comment by isabeaups** [comment] 2016-07-20 06:35
It fails while setting up the model. 
As you can see in the above revised original issue post, doing
`xtilde = x +  tf.random_normal(tf.shape(x), mean=0., stddev=1.)`
 fails with error:

> File "/anaconda/envs/hrnn/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 630, in _dynamic_rnn_loop
"Input size (depth of inputs) must be accessible via shape inference, "
ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.

**Comment by cwhipkey** [comment] 2016-07-20 15:31
I used the test body below and get noise always as (?, ?, ?), regardless of n.  xtilde is (?, ?, ?) when n = 1, and (?, ?, 2) when n = 2.

This is because x + noise might broadcast x onto noise, and when the dim's value is 1 then the output dim could be 1 or the other side.  A fix is to use tf.add_n([x, noise]) - this ends up giving the right shape.   Does this workaround work for you?

It seems that "random_normal" does not infer the output shape no matter what the final dim value.  I think it's because of tensor_util.py's _ConstantValue, where tensor.op.type == "Shape" is handled.

    n = 1
    x = tf.placeholder(tf.float32, shape=(None, None, n), name='x')
    shp = tf.shape(x)
    noise = tf.random_normal(shp, mean=0, stddev=1)
    print("noise: ", noise.get_shape())
    xtilde = x + noise  # tf.add_n([x, noise])
    print("xtilde: ", xtilde.get_shape())

Output:

    # Output when n = 1
    noise:  (?, ?, ?)
    xtilde:  (?, ?, ?)

    # Output when n = 2
    noise:  (?, ?, ?)
    xtilde:  (?, ?, 2)

**Comment by isabeaups** [comment] 2016-07-21 07:01
I'm not sure I understand your explanation completely, but the workaround works and is good enough for my purposes. Thank you!

**Comment by canpeng78** [comment] 2017-07-12 20:01
I also encountered the same problem, tf.random_normal always return a tensor with unknown shape, even when the shape parameter is set to a fixed shape. Should this be classified as a bug?

**Comment by michaelisard** [comment] 2017-07-12 21:09
@cwhipkey I admit I didn't entirely follow your explanation above either. Would you clarify if this should be considered a bug or not?

**Comment by cwhipkey** [comment] 2017-07-13 14:40
Yes, it is something that could be improved in random normal.

The workaround is to do a reshape immediately after the call, or otherwise force the shape to become known.

**Comment by yongtang** [comment] 2017-10-21 15:49
I think the shape has been correctly inferred with the most recent master:
```
ubuntu@ubuntu:~/$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> n = 1
>>> x = tf.placeholder(tf.float32, shape=(None, None, n), name='x')
>>> shp = tf.shape(x)
>>> noise = tf.random_normal(shp, mean=0, stddev=1)
>>> print(noise.get_shape())
(?, ?, 1)
>>> n = 2
>>> x = tf.placeholder(tf.float32, shape=(None, None, n), name='x')
>>> shp = tf.shape(x)
>>> noise = tf.random_normal(shp, mean=0, stddev=1)
>>> print(noise.get_shape())
(?, ?, 2)
>>> 
```

Maybe this issue could be closed?

**Comment by cwhipkey** [comment] 2017-12-21 03:22
Closing this per comment from yongtang.

**Closed by cwhipkey** 2017-12-21 03:22 UTC
