### ISSUE TITLE
The pip upgrade in windows does not get up-to-date tensorflow codes on github

### ISSUE THREAD

**Issue by ybsave** [tensorflow/tensorflow#13318] opened 2017-09-26 15:46 UTC
Tensorflow version: 1.3
OS: Windows 10

When I use pip upgrade to get tensorflow, the codes I got did not reflect the newest updates in Github. For example, in "tensorflow/tensorflow/contrib/layers/python/layers/layers.py" the up-to-date batch_norm() function supports not None param_regularizers. However, the codes updated by pip still not support param_regularizers, as the codes are not up-to-date.

Is there any other way to get the most updated tensorflow in Windows? Thank you.

**Comment by aselle** [comment] 2017-09-26 15:51
run `pip list` and report the line for tensorflow.
run python and do
```
import tensorflow as tf
print (tf.GIT_VERSION)
```
and report that as well.

**Comment by ybsave** [comment] 2017-09-26 16:02
Pip list results:
bleach (1.5.0)
html5lib (0.9999999)
Markdown (2.6.9)
numpy (1.13.1)
pip (9.0.1)
protobuf (3.4.0)
setuptools (36.5.0)
six (1.11.0)
tensorflow-gpu (1.3.0)
tensorflow-tensorboard (0.1.6)
Werkzeug (0.12.2)
wheel (0.30.0)

The tf.GIT_VERSION shows: b'unknown'

**Comment by aselle** [comment] 2017-09-26 20:06
What about tf.VERSION?

**Comment by ybsave** [comment] 2017-09-26 20:13
tf.VERSION is '1.3.0'

**Comment by gunan** [comment] 2017-10-15 05:40
Amit, is it possible we uploaded a wrong binary for windows?

**Comment by av8ramit** [comment] 2017-10-16 21:08
So the reason for this is that the 1.3 branch was cut prior to that feature being updated.

Master: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L620

1.3: https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/layers/python/layers/layers.py#L548

Closing as designed.

**Closed by av8ramit** 2017-10-16 21:08 UTC
Labels: type:build/install
