### ISSUE TITLE
[Feature Request] Support S3 KMS client-side decryption when loading data

### ISSUE THREAD

**Issue by erikreppel** [tensorflow/tensorflow#20579] opened 2018-07-06 00:52 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.8
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: V100

### Describe the problem
It would be great to support S3 KMS client side decryption within TensorFlow, ideally transparently.

We use S3 with KMS to store sensitive data and decrypting it before loading it into a `tf.Dataset` can get really gross/be a major bottle neck, in part because AWS's boto3 [client library does not support client side KMS encryption](https://docs.aws.amazon.com/general/latest/gr/aws_sdk_cryptography.html) so decrypting data needs to be done manually ([example here](https://github.com/tedder/s3-client-side-encryption/blob/master/get.py)).

However the AWS C++ client does support KMS client-side decryption.

I'm not super familiar with TensorFlow's codebase but seems like there could be a couple of ways this could be added:

1) Another contrib `tf.Dataset` implementation ([example here of an existing Dataset contrib](https://github.com/tensorflow/tensorflow/pull/19712/files))
In which case an extra method would likely need to be added to [`s3_file_system.h`](https://github.com/tensorflow/tensorflow/blob/935d5d8550ad06bc77e41e9a3d987658d3731be9/tensorflow/core/platform/s3/s3_file_system.h) that uses the C++ client for decryption, or handle the envelope encryption as part of how the Python Dataset class loads data

or

2) From what I can tell `tf.python.lib.io.file_io` uses [`NewRandomAccessFile`](https://github.com/tensorflow/tensorflow/blob/935d5d8550ad06bc77e41e9a3d987658d3731be9/tensorflow/core/platform/s3/s3_file_system.h#L30) from `s3_file_system.h` when loading datasets from S3 (as shown in the [s3 deploy docs](https://www.tensorflow.org/versions/r1.9/deploy/s3), correct me if I am wrong). 
Another envar could be added (`S3_KMS_ARN`) and if set the C++ S3 client would decrypt client side. To me this would seem like the better solution since no new datasets would need to be worried about, encrypted files in S3 would behave like regular files.

An example of the C++ S3 encryption client can be found [here](https://aws.amazon.com/blogs/developer/amazon-s3-encryption-client-is-now-available-for-c/).

### Exact command to reproduce
N/A

**Comment by tensorflowbutler** [comment] 2018-07-06 12:36
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by poxvoculi** [comment] 2018-07-10 16:48
@mrry This looks like a possible data pipeline feature.  Who could advise on this?

**Comment by yongtang** [comment] 2018-07-25 01:57
I gave it a try to enable kms support with s3, but got the following:
```
Range-Get Operations are not allowed with Strict Authenticated Encryption mode.
```
Not very familiar with AWS kms though. So I am wondering if it is possible to have range get with encryption at the the moment.

**Comment by tensorflowbutler** [comment] 2018-08-08 18:58
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-08-23 19:09
It has been 29 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-07 18:53
It has been 44 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-09-22 12:37
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by rthadur** [comment] 2021-09-28 17:05
This feature request has a more specific discussion here https://github.com/tensorflow/tensorflow/issues/48009 , which suggests the implementation , closing this request. Thank you

**Closed by rthadur** 2021-09-28 17:05 UTC
Labels: stat:contributions welcome, type:feature
