### ISSUE TITLE
Why Isn't TensorFlow Website Accessible from Iranian IP Addresses?

### ISSUE THREAD

**Issue by AlirezaAlipour** [tensorflow/tensorflow#33740] opened 2019-10-26 07:39 UTC
![Screenshot from 2019-10-26 10-34-20](https://user-images.githubusercontent.com/14098141/67616056-f9f79c80-f7e0-11e9-9499-fb4c3d008fee.png)

I'm Iranian, from Iranian IP address, TensorFlow.org is not accessible?

Now, I have the following questions:

- If I use TensorFlow in my projects, is it illegal? 
- Can you address the article that base on that you have prohibited access to TensorFlow.org for Iranian?
- Is it fair to prohibiting a project that the contributors all around the world are contributing to it?

**Comment by ymodak** [comment] 2019-10-28 22:24
Duplicate #18169
See https://github.com/tensorflow/tensorflow/issues/18169#issuecomment-378005528 to know more

**Comment by mihaimaruseac** [comment] 2019-10-29 16:41
Closing as duplicate. Please consul #18169 for reasons.

**Closed by mihaimaruseac** 2019-10-29 16:41 UTC
Labels: stat:awaiting response, type:others

**Comment by AlirezaAlipour** [comment] 2019-10-31 06:42
Firstly, my issue has three questions, are all questions of my issue duplicate?

Secondly, can you confirm that the reason of inaccessibility is hosting on Google Cloud Platform and not because of the field of activity? in other world, can you address an official document that confirm that all websites hosted on Google Cloud Platform are inaccessible from Iranian IP addresses? or can you address an official document that confirm that the reason is not because [TensorFlow.org](https://www.tensorflow.org/) has been sanctioned because of only the field of activity (i.e. artificial intelligence) ?

Above all, if you can't answers my question, please introduce me a channel to contact to Google.

**Comment by AlirezaAlipour** [comment] 2019-10-31 09:59
Dear @mihaimaruseac, please open my issue again.

**Comment by AlirezaAlipour** [comment] 2019-11-04 16:39
Dear @mihaimaruseac, please open my issue again.

**Comment by mihaimaruseac** [comment] 2019-11-04 17:17
Apologies for late response. However, I cannot further comment on your questions, beside marking this a duplicate of #18169.

**Comment by AlirezaAlipour** [comment] 2019-11-04 17:44
> Apologies for late response. However, I cannot further comment on your questions, beside marking this a duplicate of #18169.

Thank you very much.
