### ISSUE TITLE
TensorFlow variable initializers broken

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#13351] opened 2017-09-27 22:38 UTC
Three symptoms observed with models after upgrading tensorflow:
1. must feed placeholder error
or
2. things hang with 100% utilization inside python _build_initializer_expr
3. things succeed but sess.run call takes 100x slower than before

I believe this is due to this commit:
https://github.com/tensorflow/tensorflow/commit/07adc2ea910de715d31e16a019fcbcccb575e931

Because the following work-around restores good behavior:
```
from tensorflow.python.ops import variables
def passthrough(obj, value): return value
try:
  variables.Variable._build_initializer_expr=passthrough
except: # older versions of TF don't have this
  pass
```

Here's a self contained repro: https://github.com/yaroslavvb/stuff/blob/master/tf_initializer_bug_report.py

It works fine in tensorflow 1.2, or with the fix, in latest version is throws 

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a va
lue for placeholder tensor 'Wf_holder' with dtype float and shape [307328]
         [[Node: Wf_holder = Placeholder[dtype=DT_FLOAT, shape=[307328], _device
="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```

Sorry I didn't make the repro smaller, I lost motivation after finding the quick fix :)

**Comment by yaroslavvb** [comment] 2017-09-27 22:39
cc @benoitsteiner @alextp

**Comment by yaroslavvb** [comment] 2017-09-27 22:40
@TimSalimans who is also affected

**Comment by tensorflowbutler** [comment] 2017-12-20 01:13
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by yaroslavvb** [comment] 2017-12-20 03:15
Just tested with tf nightly and it's still broken. I believe this bug is also responsible for deadlock during data-dependent init in tim's models.

To reproduce:
```
pip install tf-nightly
wget https://raw.githubusercontent.com/yaroslavvb/stuff/2c716e7abde25018ccfeeeff96c6397fef4f33ba/tf_initializer_bug_report.py

python tf_initializer_bug_report.py
...
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Wf_holder' with dtype float and shape [307328]
	 [[Node: Wf_holder = Placeholder[dtype=DT_FLOAT, shape=[307328], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

If you comment out the top block, which essentially reverts https://github.com/tensorflow/tensorflow/commit/07adc2ea910de715d31e16a019fcbcccb575e931 then things work again and you see following output

```
Running training.
Step 0 loss 35.58, target decrease -7.771, actual decrease, -4.621 ratio 0.59 grad norm: 22.97 pregrad norm: 77563.16
Step 3 loss 25.41, target decrease -0.841, actual decrease, -0.740 ratio 0.88 grad norm: 1.72 pregrad norm: 1541.23
Step 6 loss 23.99, target decrease -0.204, actual decrease, -0.189 ratio 0.93 grad norm: 0.43 pregrad norm: 295.30

```

**Comment by martinwicke** [comment] 2017-12-20 15:22
@asimshankar @joshl it's this issue again. Apparently it broke recently. I didn't know that.

**Comment by alextp** [comment] 2017-12-20 17:52
There is an internal bug for this which is being worked on

**Comment by josh11b** [comment] 2017-12-20 21:47
I agree with your analysis that https://github.com/tensorflow/tensorflow/commit/07adc2ea910de715d31e16a019fcbcccb575e931 is the culprit and that introduced likely multiple bugs.  The description of that commit "when a variable w is initialized with the value of another variable v, make sure that the initializer of v is run first." would have been fine, but the actual code change instead redirects references to v in w's initializer to v's initial value graph. This has at least a couple of problems:
* there are some bugs in the code, e.g. if there is a while loop it can follow the cycle in the graph forever
* if v was already initialized and has since been updated, w should get the new value not the original value

Ideally, we would rewrite the logic to be less buggy:
* scan w's initializer init_w for references to variables, being careful to avoid visiting nodes in a graph cycle more than once
* replace w's initialize_op with: if v has not been initialized, run v's initialization op; once that is done run "w = w's initialization expression" without changes (in particular, without the rewrite to use v's initial value)

**Comment by tensorflowbutler** [comment] 2018-01-04 19:06
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by djvisentin** [comment] 2018-01-05 12:25
I'm starting to push through changes to fix this. The first one is a refactoring to make subsequent changes easier as well as avoiding infinite recursion when the `initial_value` contains cycles (note that it also changes the name of `_build_initiazier_expr` to `_try_guard_against_uninitialized_depenencies` to clarify what it does). I'll now attempt to address more edge cases.

Here's what I believe is a minimal reproduction of the bad behaviour in this case:

```
p = tf.placeholder(dtype=tf.float32, shape=[])
v0 = tf.Variable(p)
v1 = tf.Variable(v0)
with tf.Session() as session:
  session.run(v0.initializer, feed_dict={p: 0})
  session.run(v1.initializer)  # InvalidArgumentError
```

The transformation done by `_build_initializer_expr` makes `v1` depend on `v0.initialized_value()` which is a `cond` of the form:

```
cond(
    is_variable_initialized(v0),
    v0.read_value,
    lambda: p)
```
Because `p` isn't actually created inside `false_fn` it will always be evaluated when the `cond` is -- which is inconsistent with the intended behaviour. If you were to run that `session.run(v1.initializer)` statement and feed `p` it would work (but we shouldn't expect the user to do that).

This adds to the list of edge cases (that I'm aware of) where `_build_initializer_expr` has behaves poorly:

1) This issues of extraneous propagation of placeholders.

2) Cyclic initializers (now "fixed" by having it ignore those graphs).

3) When TF functions are involved. For example:

```
@function.Defun(tf.float32, shape_func=lambda op: [op.inputs[0].get_shape()])
def increment(x):
  return x + tf.ones_like(x)

v0 = tf.Variable(tf.zeros(shape=[]))
a = increment(v0)
v = tf.Variable(a)  # NotFoundError: Op type not registered
```

4) With most stateful ops. For example:

```
# Graph rewriting results in wrong values when you have a variable initializer
# which depends on a non-determinstic op which depends on a variable. Note that
# we use random_uniform with integer types because the underlying op
# "RandomUniformInt" takes in the minval and maxval as tensors unlike, for
# example, random_normal with calls "RandomStandardNormal" and then transforms
# it with the mean/stdev (so the non-determinsitic part doesn't actually)
# depend on the variables and won't be rewritten.
minval = tf.Variable(0, dtype=tf.int32)
maxval = tf.Variable(1000000, dtype=tf.int32)
r = tf.random_uniform(shape=[], minval=minval, maxval=maxval, dtype=tf.int32)
v0 = tf.Variable(r)
v1 = tf.Variable(v0)  # Same results even if you use v0.initialized_value()
with tf.Session() as session:
  session.run([minval.initializer, maxval.initializer])
  session.run([v0.initializer, v1.initializer])
  print(session.run([v0, v1])) # Different values.

# _build_initializer_expr copies the random op so there will be two of them.
print(sum([op.type == 'RandomUniformInt'
           for op in tf.get_default_graph().get_operations()]))
```

5) If you have an initializer where there is an intermediate op X which takes an argument that must be a reference type, and that argument is a variable. This algorithm will turn the reference type into a value type and cause an error. For example:

```
v0 = tf.Variable(tf.zeros(shape=[]))
one = tf.ones_like(v0)
v0_plus_one = tf.assign(v0, v0.initialized_value() + one)
v1 = tf.Variable(v0_plus_one)
with tf.Session() as session:
  session.run(v1.initializer)  # InvalidArgumentError
```

6) Not a bug, as such, but the implementation will produce an exponentially large number of nodes given a diamond pattern dependency graph (now fixed by memoizing):

```
# Diamond pattern - exponential growth
# N => N + 2^N - 1 Add ops
N = 4
v0 = tf.Variable(tf.zeros(shape=[]))
x = v0
for i in range(N):
  x = tf.add(x, x)
v1 = tf.Variable(x)
print(sum([op.type == 'Add'
           for op in tf.get_default_graph().get_operations()]))
with tf.Session() as session:
  print(session.run(v1.initializer))
  print(session.run(v1))
```

7) The implementation completely ignores control dependencies. Any new ops created simply don't have them.

8) The implementation completely ignores control flow contexts. Any new ops created based on ops in a control flow context aren't added to that context.

9) The implementation will only be able to find a Variable's initialized_value method if that variable is present in the `GLOBAL_VARIABLES` or `LOCAL_VARIABLES` collection. This is a weird inconsistency to the end user. It's even possible it could find the wrong Variable (although you'd have to be working really hard to get it to do that).

10) The implementation relies on a hard-coded set of known variable ops. If new variable ops are added it won't recognize them without manual intervention.

11) Even if the caller explicitly passes in a .initialized_value() to a Variable's constructor the `_build_initializer_expr` will probably create a bunch of new nodes in the graph anyway.

12) It currently doesn't even do anything when the initial value depends on a ResourceVariable.

There are probably even more that I'm not currently aware.

I'll start working through these in the coming days. I'm working under the assumption that we can't just remove this transformation since there will already be a significant number of graphs which depend on it. That means most of the work will be to whitelist and/or blacklist the set of `initial_value` subgraphs for which we can safely apply the transformation.

**Comment by yaroslavvb** [comment] 2018-01-05 15:38
Working this feature into existing client code is complicated, I wonder if it would be much simpler to add it as new functionality. Since dependent initialization has never worked in TF, this can be a new op, like VariableV5, which can eventually replace Variable.

The example [here](https://gist.github.com/yaroslavvb/d592394c0cedd32513f8fbb87ca05938
) worked for our code in OpenAI, and the idea there was to make variable reads have control dependency on "safe-initializer". "Safe-initializer" is an assign op that only runs when variable has not been initialized. 

PS, motivation for the breaking commit is https://github.com/tensorflow/tensorflow/issues/4920

**Comment by tensorflowbutler** [comment] 2018-01-23 23:15
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by alextp** [comment] 2018-01-23 23:25
@djvisentin I think this is fixed, right?

**Comment by tensorflowbutler** [comment] 2018-02-07 13:45
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-22 13:06
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-09 13:38
Nagging Assignee @djvisentin: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 03:47
Nagging Assignee @djvisentin: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-08 18:36
Nagging Assignee @djvisentin: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-23 18:47
Nagging Assignee @djvisentin: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:14
Nagging Assignee @djvisentin: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:14
Nagging Assignee @djvisentin: It has been 122 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:42
Nagging Assignee @djvisentin: It has been 137 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Hoeze** [comment] 2018-06-10 22:48
Are there any updates on this?
I just tried depending variables, e.g.:

```
var = tf.Variable(some_placeholder)
var2 = tf.Variable(var.initialized_value())
```
which did not work.
After initialization, `sess.run(var)` gave me values, but `sess.run(var.initialized_value())` raised an error because of missing `some_placeholder`.

**Comment by Hoeze** [comment] 2018-06-14 18:38
That's not pretty, but simple.
Nevertheless, imho this should be solved. A dependency tree initializing variables would be much more pretty.

**Comment by tensorflowbutler** [comment] 2018-06-29 18:54
Nagging Assignee @djvisentin: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-14 18:39
Nagging Assignee @djvisentin: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-29 18:33
Nagging Assignee @djvisentin: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-15 02:51
Nagging Assignee @djvisentin: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-31 07:52
Nagging Assignee @djvisentin: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-15 18:31
Nagging Assignee @djvisentin: It has been 92 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-30 12:43
Nagging Assignee @djvisentin: It has been 107 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-15 12:44
Nagging Assignee @djvisentin: It has been 122 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-14 18:57
Nagging Assignee @djvisentin: It has been 152 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by alextp** [comment] 2018-11-14 20:46
If you use tf.function in tf v2 this will not be a problem, so this is how we plan on fully resolving this issue.

**Closed by alextp** 2018-11-14 20:46 UTC
Labels: stat:awaiting tensorflower, type:bug/performance
