### ISSUE TITLE
Severe lag due to GPU having no memory to allocate to

### ISSUE THREAD

**Issue by hunterwallace** [tensorflow/tensorflow#31544] opened 2019-08-12 13:52 UTC
Running tensorflow on my laptop through anaconda and the following popped up:

2019-08-12 09:32:41.378946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3048 MB memory) -> physical GPU (device: 0, name: Quadro M1000M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2019-08-12 09:33:14.804467: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.06GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

I am experiencing severe lag that I was originally not.

Any thoughts?

I used the following instructions to install my tensorflow: https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10

**Comment by ravikyram** [comment] 2019-08-13 09:08
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue.  If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by hunterwallace** [comment] 2019-08-13 13:55
**System information**
- Have I written custom code:
no

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10, 64-bit operating system, x64-based processor.

- TensorFlow installed from (source or binary):
C=Not sure if compiled from source or binary.... working through anaconda and the actual script is run with IDLE. Hope this helps.

- TensorFlow version (use command below):
Tensorflow 14.0

- Python version:
python 3.5.6

- Bazel version (if compiling from source):

- GCC/Compiler version (if compiling from source):
GCC 4.8

- CUDA/cuDNN version:
cuDNN64_7

- GPU model and memory:
WDDM 2.1
memory 3.9 GB

**Describe the current behavior**
Ran the following command:
(tensorflow1) C:\tensorflow1\models\research\object_detection>idle Object_detection_webcam.py
This opened a script which I selected 'run module'
Then the screen would appear and the object detection would begin.
**tensorflow would run but with extreme lag**

**Describe the expected behavior**
tensorflow runs with less lag

**Code to reproduce the issue**
(tensorflow1) C:\tensorflow1\models\research\object_detection>idle Object_detection_webcam.py

**Other info / logs**
Running tensorflow on my laptop through anaconda and the following popped up:

2019-08-12 09:32:41.378946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3048 MB memory) -> physical GPU (device: 0, name: Quadro M1000M, pci bus id: 0000:01:00.0, compute capability: 5.0)
2019-08-12 09:33:14.804467: W tensorflow/core/common_runtime/bfc_allocator.cc:237] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.06GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

**Comment by jvishnuvardhan** [comment] 2019-08-14 22:38
@hunterwallace Looks like you 3048 MB memory was allocated to the conda's virtual environment and the `object_detection model`  ran out of memory trying to allocate 3.06GiB. You need to increase memory or use smaller models that requires lower memory. I think there are ways to increase your memory upto 3.9 GB but still lab will be less if you have little more memory for that model. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-08-19 16:48
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-08-19 16:48 UTC
Labels: TF 1.14, comp:gpu, stat:awaiting tensorflower, type:performance
