### ISSUE TITLE
Can xla compile tf.estimator.DNNLinearCombinedEstimator?

### ISSUE THREAD

**Issue by patelprateek** [tensorflow/tensorflow#30820] opened 2019-07-17 19:15 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source 1.13
- TensorFlow version: 1.13
- Python version: 2.7
- Installed using virtualenv? pip? conda?: 
- Bazel version (if compiling from source): 0.19
- GCC/Compiler version (if compiling from source):4.8
- CUDA/cuDNN version: n/a
- GPU model and memory:n/a

**Describe the problem**
trying to AOT compile a model trained using XLA 
error :  {{node dnn/input_from_feature_columns/input_layer/xyz/axyz_embedding_weights/SparseReshape}}
	.  Registered:  <no registered kernels>
){{node dnn/input_from_feature_columns/input_layer/ad__ad_id_embedding/ad__ad_id_embedding_weights/SparseReshape}}

Is there any ETA on this being supported ? 

How can AOT xla compile : tf.estimator.DNNLinearCombinedEstimator , is this even possible with current support ?

**Provide the exact sequence of commands / steps that you executed before running into the problem**
bazel-bin/tensorflow/compiler/aot/tfcompile --graph=mygrapht.pb --config=graphv.config.pbtxt --cpp_class="mynamespace::MyComputation"

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by gadagashwini** [comment] 2019-07-18 10:36
@patelprateek Could you provide more details about the issue.Thanks!

**Comment by patelprateek** [comment] 2019-07-18 15:53
@gadagashwini : can you please elaborate what details you need ?

I took the DNNLinearCombinedEstimator code , trained a model and then tried xla AOT compilation.
Can't get that to compile because of the following error : 
error : {{node dnn/input_from_feature_columns/input_layer/xyz/axyz_embedding_weights/SparseReshape}}
. Registered: 
){{node dnn/input_from_feature_columns/input_layer/ad__ad_id_embedding/ad__ad_id_embedding_weights/SparseReshape}}

seem slike SparseReshape is not supported yet.

Please let me know what details are you looking for , because i belive the above information is enough to reproduce the problem as well ?
tf 1.12 bazel 0.19 gcc 4.8 python 2.7 ubuntu 16.04

**Comment by gadagashwini** [comment] 2019-07-19 08:11
@patelprateek Please provide the reproducible code to expedite the trouble-shooting process. Thanks!

**Comment by patelprateek** [comment] 2019-07-19 17:01
@gadagashwini : Please read my previous update , you can take DNNLinearCombinedEstimator provided by estimators api and try compiling with xla.
There is no need for me to share any code here (plus that is all internal code and would be hard to share , i already gave you enough information), i am talking about the pre built estimators
Also the error clearly shows what kind of feature is problematic.. i.e embedding 
I think this is sufficient to reproduce

**Comment by sanjoy** [comment] 2019-07-26 20:28
> Is there any ETA on this being supported ?

No, we're not investigating adding any sparse operations to XLA at this time.

I don't know enough about the TF ops to state whether they're even a good fit for XLA, but if they are a good fit for XLA I'd be fine reviewing a PR adding XLA support for these ops.

**Comment by patelprateek** [comment] 2019-07-27 04:21
@sanjoy : can you please provide me some pointers or documentation regarding "what is a good fit for xla". I am happy to contribute and add PRs but would need some guidance , can you point me to some example PRs that adds support for few ops , that would be very helpful for me to understand the different pieces that needs to go in for supporting a new op .

**Comment by sanjoy** [comment] 2019-07-29 16:34
Probably the easiest way to get started is to look at some example TF->XLA lowerings and try to find one that is close to `SparseReshape`.  All the TF->XLA lowerings are in tensorflow/compiler/tf2xla/kernels/.

For instance, this file contains the dense reshape operation: tensorflow/compiler/tf2xla/kernels/reshape_op.cc, although I suspect the implementation of `SparseReshape` is probably going to be very different from `Reshape`.

**Comment by ymodak** [comment] 2019-08-14 23:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-08-14 23:02 UTC
Labels: TF 1.13, comp:xla, type:bug
