### ISSUE TITLE
compile_ios_tensorflow.sh failing

### ISSUE THREAD

**Issue by randomiser** [tensorflow/tensorflow#2896] opened 2016-06-16 03:31 UTC
Hi there

I'm following the instructions on your website to build a version of tensor flow for iOS:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile

Unfortunately when I get to final step:

tensorflow/contrib/makefile/compile_ios_tensorflow.sh

It errors with:

 /Projects/ML/tensorflow/tensorflow/contrib/makefile/gen/lib/libtensorflow-core-armv7.a -arch armv7 -miphoneos-version-min=9.2 -Xlinker -S -Xlinker -x -Xlinker -dead_strip -all_load -L/Projects/ML/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib -lz -lstdc++ -lprotobuf -lm
Undefined symbols for architecture armv7:
  "tensorflow::shape_inference::InferenceContext::Merge(tensorflow::shape_inference::Shape const*, tensorflow::shape_inference::Shape const*, tensorflow::shape_inference::Shape const**)", referenced from:
      tensorflow::$_0::operator()(tensorflow::shape_inference::InferenceContext*) const in libtensorflow-core-armv7.a(math_ops.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Projects/ML/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1

**Comment by StephenOman** [comment] 2016-06-16 08:12
That problem is caused by the out-of-date tf_cc_files.txt file that is in the repo. That version doesn't include newer files such as shape_inference.cc, the source of the missing symbols in your error.

If you run ./gen_file_lists.sh from tensorflow/contrib/makefile it will generate a new tf_cc_files.txt for you. Then run the compile script again and see if it works.

Note that you have to remove "make/" from lines 26, 32, 38, 46, 52, and 58 in gen_file_list.sh in order to make the script put the files into the same directory as the Makefile. I forgot to raise this an issue when I found it.

**Comment by albhaf** [comment] 2016-06-16 20:52
Piggybacking on this issue (let me know if it's better suited as a separate one). I changed gen_file_list.sh, ran it and then attempted building again, now I'm instead getting the following:
```
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      tensorflow::io::ZlibOutputBuffer::Deflate(int) in zlib_outputbuffer.o
  "_deflateEnd", referenced from:
      tensorflow::io::ZlibOutputBuffer::Close() in zlib_outputbuffer.o
  "_deflateInit2_", referenced from:
      tensorflow::io::ZlibOutputBuffer::ZlibOutputBuffer(tensorflow::WritableFile*, int, int, tensorflow::io::ZlibCompressionOptions const&) in zlib_outputbuffer.o
  "_inflate", referenced from:
      tensorflow::io::ZlibInputBuffer::Inflate() in zlib_inputbuffer.o
  "_inflateEnd", referenced from:
      tensorflow::io::ZlibInputBuffer::~ZlibInputBuffer() in zlib_inputbuffer.o
  "_inflateInit2_", referenced from:
      tensorflow::io::ZlibInputBuffer::ZlibInputBuffer(tensorflow::RandomAccessFile*, unsigned long, unsigned long, tensorflow::io::ZlibCompressionOptions const&) in zlib_inputbuffer.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/albhaf/src/github.com/tensorflow/tensorflow/tensorflow/contrib/makefile/gen/host_bin/proto_text] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1
```

**Comment by StephenOman** [comment] 2016-06-16 21:37
@albhaf That looks like a different problem.

I had a quick look and I think that it's being caused by support being added in the main tensorflow build for reading compressed files. The download dependencies script in the makefile directory is now out of date, along with the Makefile.

A quick work-around should be to remove the two zlib references from your generated tf_cc_files.txt. I haven't checked that yet, but the iOS Camera Demo doesn't use zlib so it might be ok.

**Comment by petewarden** [comment] 2016-06-17 15:34
Apologies about the breakage! I'm working to make the update a bit less of a manual process.

I'll investigate how we can avoid the new zlib dependency (since we don't want additional libraries to link in), and hopefully have an answer soon.

**Comment by petewarden** [comment] 2016-06-17 21:58
Thanks everyone! I've tested this again and it should be fixed in #2936, so I'll close this. Comment or reopen if you're still hitting problems.

**Comment by albhaf** [comment] 2016-06-18 12:11
Thanks! Managed to successfully build with 582e6c8.

Recent changes in master (I suspect 7764e8f6 from a brief look), appears to have caused it to regress again if it's of any interest:
```
Undefined symbols for architecture x86_64:
  "tensorflow::PosixFileSystem::NewWritableFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tensorflow::WritableFile**)", referenced from:
      vtable for tensorflow::LocalPosixFileSystem in env.o
  "tensorflow::PosixFileSystem::NewAppendableFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tensorflow::WritableFile**)", referenced from:
      vtable for tensorflow::LocalPosixFileSystem in env.o
  "tensorflow::PosixFileSystem::NewRandomAccessFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tensorflow::RandomAccessFile**)", referenced from:
      vtable for tensorflow::LocalPosixFileSystem in env.o
  "tensorflow::PosixFileSystem::NewReadOnlyMemoryRegionFromFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, tensorflow::ReadOnlyMemoryRegion**)", referenced from:
      vtable for tensorflow::LocalPosixFileSystem in env.o
```

**Comment by vrv** [comment] 2016-06-18 18:05
Shoot, probably my fault, I'll send a fix.

**Comment by petewarden** [comment] 2016-06-18 18:09
I'm actually looking at it now too. It builds fine using the makefile on Linux, so it's not just a new file added. I'm running build_all_ios.sh to repro the problem, and I'll update with more details when I have them.

**Comment by vrv** [comment] 2016-06-18 18:11
Actually, I can't find any reference to those symbols -- my change removed the old APIs and converted to the new ones, so I'm not sure why we're seeing that.

**Comment by albhaf** [comment] 2016-06-18 18:28
Checking if I can reproduce it and making sure it's on a clean state, in case it was in an inconsistent one from jumping between refs.

**Comment by albhaf** [comment] 2016-06-18 19:01
It seemed like it was, I must have missed to clean in between checkouts.
I can build it from master now, sorry for the noise.

**Comment by petewarden** [comment] 2016-06-18 19:02
Great to hear, and no worries! Thanks for the update and the report.

**Closed by petewarden** 2016-06-18 19:02 UTC

**Comment by sashakid** [comment] 2016-12-09 12:17
Am I doing it right? I want to run ios examples and trying to compile lib in this way:
