### ISSUE TITLE
Multiple tensorflow devices created, then programs ends

### ISSUE THREAD

**Issue by JakeDahl** [tensorflow/tensorflow#23657] opened 2018-11-10 19:34 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Written
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:-
- TensorFlow installed from (source or binary): source(?) 1.12 from pip.
- TensorFlow version (use command below): 1.12
- Python version: 3.6
- Bazel version (if compiling from source):-
- GCC/Compiler version (if compiling from source):-
- CUDA/cuDNN version: 9.0
- GPU model and memory: GTX 1070Ti 8GB

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Originally was not an issue. Tensorflow now creates multiple devices, see log. I installed baseline for OpenAI and this started after that. I reinstalled tensorflow and the issue persists.

My scripts no longer execute because of this.

**Code to reproduce the issue**
All code results in the issue.

**Other info / logs**
2018-11-10 14:29:08.296852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-10 14:29:08.297012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-11-10 14:29:08.297107: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-11-10 14:29:08.297353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6393 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)

2018-11-10 14:29:08.577708: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-10 14:29:08.577917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-10 14:29:08.578069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-11-10 14:29:08.578162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-11-10 14:29:08.578303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 6393 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
_________________________________________________________________
2018-11-10 14:29:15.921961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-11-10 14:29:15.922125: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-11-10 14:29:15.922269: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-11-10 14:29:15.922362: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-11-10 14:29:15.922500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 6393 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)

**Comment by azaks2** [comment] 2018-11-26 17:03
Do you have a small example I can run to reproduce the issue?

**Comment by azaks2** [comment] 2019-01-15 17:46
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sanjoy** [comment] 2019-12-09 21:05
> Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

Ditto.

**Closed by sanjoy** 2019-12-09 21:05 UTC
Labels: comp:runtime
