### ISSUE TITLE
Cannot allocate tf_uniform_replay_buffer to GPU - No registered 'ResourceScatterUpdate' OpKernel for 'GPU' devices compatible with node

### ISSUE THREAD

**Issue by deeepwin** [tensorflow/tensorflow#48650] opened 2021-04-20 20:17 UTC
**System information**

tensorflow 2.4.1
tf-agents 0.7.1
Nvidia RTX 2080 Ti
Windows 10
Python 3.8

**Describe the current behavior**

I am trying to run the TFUniformReplayBuffer on the GPU based on the example outlined here:

[https://pathtopioneer.com/blog/2020/07/rl-3](https://pathtopioneer.com/blog/2020/07/rl-3)

When adding device='/device:CPU:0' to the initalisation of the replay buffer everything works. When specifying GPU device='/device:GPU:0', an error occurs. It appears there is no GPU op for ResourceScatterUpdate. But how can this be fixed?

Same error when running code on Colab with GPU enabled instead of my local machine.

**Describe the expected behavior**

Should give no error with GPU enabled.

**Standalone code to reproduce the issue**

```


import tensorflow as tf
from tf_agents.replay_buffers import tf_uniform_replay_buffer
import numpy as np

data_spec =  (
        tf.TensorSpec([1], tf.float32, 'action'),
        tf.TensorSpec([5], tf.float32, 'lidar'),
        tf.TensorSpec([3, 2], tf.float32, 'camera')
)

batch_size = 32
max_length = 1000

replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec,
    batch_size=batch_size,
    max_length=max_length,
    device='/device:GPU:0') # when using device='/device:CPU:0') everything works

action = tf.constant(1 * np.ones(
    data_spec[0].shape.as_list(), dtype=np.float32))
lidar = tf.constant(
    2 * np.ones(data_spec[1].shape.as_list(), dtype=np.float32))
camera = tf.constant(
    3 * np.ones(data_spec[2].shape.as_list(), dtype=np.float32))

values = (action, lidar, camera)
values_batched = tf.nest.map_structure(lambda t: tf.stack([t] * batch_size),
                                       values)

replay_buffer.add_batch(values_batched)

# Convert the replay buffer to a tf.data.Dataset and iterate through it
dataset = replay_buffer.as_dataset(
    sample_batch_size=4)

iterator = iter(dataset)
print("Iterator trajectories:")
trajectories = []
for _ in range(3):
  t, _ = next(iterator)
  trajectories.append(t)

print(tf.nest.map_structure(lambda t: t.shape, trajectories))
```

**Other info / logs**

Exception has occurred: NotFoundError
No registered 'ResourceScatterUpdate' OpKernel for 'GPU' devices compatible with node {{node ResourceScatterUpdate}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: Tindices=DT_INT64, dtype=DT_INT64
	.  Registered:  device='CPU'; dtype in [DT_UINT64]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_UINT64]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_UINT32]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_UINT32]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_BFLOAT16]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_BFLOAT16]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_STRING]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_STRING]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_BOOL]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT64]
  device='GPU'; dtype in [DT_HALF]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_HALF]; Tindices in [DT_INT64]
  device='GPU'; dtype in [DT_FLOAT]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_FLOAT]; Tindices in [DT_INT64]
  device='GPU'; dtype in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='GPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_BOOL]; Tindices in [DT_INT32]
  device='GPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT64]
 [Op:ResourceScatterUpdate]
  File "C:\Users\Martin\Documents\GitHub\rl-investing\helper\replay.py", line 31, in <module>
    replay_buffer.add_batch(values_batched)

**Comment by saikumarchalla** [comment] 2021-04-21 15:56
@deeepwin  I can able to reproduce the issue using GPU for TF 2.4.1 where as the issue is fixed in tf-nightly version. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/6c1e5b1a5eed9755998c7b3ed30c7485/untitled64.ipynb). Thanks!

**Comment by deeepwin** [comment] 2021-04-22 07:36
@saikumarchalla tested nightly build on my windows machine (Paython 3.7 and 3.8). But, still same error. On Colab it seems to work indeed. But, is Linux and Python 3.7.

**Comment by saikumarchalla** [comment] 2021-04-22 15:44
@deeepwin  Could you please provide your cuda/cuddn version?

**Comment by deeepwin** [comment] 2021-04-22 19:30
On Ubuntu:

cuda: 11.3 (NVIDIA-SMI 465.19.01    Driver Version: 465.19.01)
cudnn 8.1.1.33-1+cuda11.2

On Windows:

cuda 11.3
cudnn 8.2.0.53

**Comment by deeepwin** [comment] 2021-04-27 18:16
@saikumarchalla 

I have install nightly but unfortunately no success. Could you check it on cuda with higher version or am I doing something wrong?

Collecting tf-nightly
  Downloading tf_nightly-2.6.0.dev20210427-cp37-cp37m-manylinux2010_x86_64.whl (455.6 MB)

```
xception has occurred: NotFoundError
No registered 'ResourceScatterUpdate' OpKernel for 'GPU' devices compatible with node {{node ResourceScatterUpdate}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: Tindices=DT_INT64, dtype=DT_INT64
	.  Registered:  device='CPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_VARIANT]; Tindices in [DT_INT32]
  device='CPU'; dtype in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; dtype in [DT_BOOL]; Tindices in [DT_INT32]
...
device='GPU'; dtype in [DT_HALF]; Tindices in [DT_INT32]
 [Op:ResourceScatterUpdate]
  File "/home/martin/GitHub/rl-investing/tests/test_tf_uniform_replay_buffer.py", line 38, in <module>
    replay_buffer.add_batch(values_batched_tf)
```

**Comment by ymodak** [comment] 2021-05-06 18:55
Adding github [gist](https://colab.research.google.com/gist/ymodak/bf83ea272c11f180a3608a932e22dde1/untitled16.ipynb) that reproduces the reported error for next tensorflower.

**Comment by sanjoy** [comment] 2021-05-20 06:46
CC @atondwal

**Comment by atondwal** [comment] 2021-06-03 16:39
@deeepwin does this unblock your usecase?

**Comment by deeepwin** [comment] 2021-06-06 10:19
@atondwal works on my local machine with the nightly build. Great thank you!

**Closed** 2021-08-19 14:14 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:gpu, TF 2.4
