### ISSUE TITLE
[TF2.2] Mixed Ragged and tensors inputs breaks function tensors spec names

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#38872] opened 2020-04-24 15:51 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): tf2.2 rc3
- TensorFlow version (use command below):2.2 rc3 collab
- Python version: google collab
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I'm trying to save a model with two inputs:
- one ragged
- one tensor

both are embedded into a 3 dim vector and then summed up together. If we save that model it breaks because the tensors names are not well defined. 

```
inp_tensor = Input(shape=[], ragged=False, dtype=tf.int32)
inp_ragged = Input(shape=[None, ], ragged=True, dtype=tf.int32, name='test')

out = Embedding(10, 3)(inp_tensor)
out2 = Embedding(10, 3)(inp_ragged)
out2 = Lambda(tf.reduce_sum, arguments=dict(axis=1))(out2)
summed = Add()([out, out2])
m = Model([inp_tensor, inp_ragged], summed)
m.save('/tmp/test')
```
> ValueError: If specifying TensorSpec names for nested structures, either zero or all names have to be specified.

If we debug we find out that the non ragged tensor has a name while the two others have name=None. I tried to name the ragged_input to fix that but the issue stays the same. 
```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py(1196)_get_defun_inputs()
   1194     specified_names = [arg.name for arg in tensor_specs if arg.name]
   1195     if specified_names and len(specified_names) < len(tensor_specs):
-> 1196       raise ValueError("If specifying TensorSpec names for nested structures, "
   1197                        "either zero or all names have to be specified.")
   1198 

ipdb> specified_names
['inputs/0']
ipdb> tensor_specs
[TensorSpec(shape=(None,), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None,), dtype=tf.int32, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None)]
```
**Describe the expected behavior**
We should be able to save that model, the same model with two ragged inputs can be saved !

**Standalone code to reproduce the issue**
https://colab.research.google.com/gist/tanguycdls/200096266d1cb0c5a6c83cbb416c1279/untitled4.ipynb

**Comment by ravikyram** [comment] 2020-04-27 06:04
I tried in colab with TF 2.1 and i am not seeing any issue. However i am able to reproduce the issue in colab with TF 2.2.0-rc3. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/8e6c30bbab16d2929cae9652a30c87e7/untitled821.ipynb).Thanks!

**Comment by shkarupa-alex** [comment] 2020-05-14 08:46
Facing same issue with 2.2.0

**Comment by tanguycdls** [comment] 2020-05-18 13:59
@shkarupa-alex seems to be fixed in the latest tf-nightly :) !
https://colab.research.google.com/gist/tanguycdls/200096266d1cb0c5a6c83cbb416c1279/untitled4.ipynb#scrollTo=qWJanvalyxiJ 

I'm going to do some thorough tests to be sure.

**Comment by jvishnuvardhan** [comment] 2020-05-18 16:39
@shkarupa-alex Agree with @tanguycdls . Looks like this was resolved in `tf-nightly`. Please take a look at the [gist](https://colab.research.google.com/gist/jvishnuvardhan/fa7dabf593f61fb8bd76a5a46b7b789a/untitled4.ipynb). Thanks!

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by shkarupa-alex** [comment] 2020-05-19 05:12
Yes, it's working now

**Comment by jvishnuvardhan** [comment] 2020-05-19 05:31
I am closing this issue as this was resolved. Thanks for the confirmation.

**Closed by jvishnuvardhan** 2020-05-19 05:31 UTC
Labels: TF 2.2, comp:keras, comp:ops, regression issue, stat:awaiting response, type:bug

**Comment by tanguycdls** [comment] 2020-05-23 15:31
fyi closed by that commit: https://github.com/tensorflow/tensorflow/commit/d1a6976039c769423814f690661fd2c1b471b08c
