### ISSUE TITLE
BestExporter exporting multiple models.

### ISSUE THREAD

**Issue by msushkov** [tensorflow/tensorflow#25899] opened 2019-02-19 20:16 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
https://cloud.google.com/ml-engine/docs/tensorflow/runtime-version-list#1.10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
1.10
- Python version:
3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
Nvidia Tesla K80

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
Multiple (8) models are exported in `export/best_exporter` directory.

**Describe the expected behavior**
BestExporter exports single best model in `export/best_exporter` directory.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
https://github.com/conversationai/conversationai-models/pull/246
https://github.com/conversationai/conversationai-models/blob/6b383cfa6d8f3c42fc09d7c9496069a13fcad48d/experiments/tf_trainer/common/model_trainer.py#L226

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[ml_job_job_id_tf_trainer_tf_cnn_civil_comments_glove_msushkov_20190215_163340__logs__2019-02-15T08-04.log](https://github.com/tensorflow/tensorflow/files/2881829/ml_job_job_id_tf_trainer_tf_cnn_civil_comments_glove_msushkov_20190215_163340__logs__2019-02-15T08-04.log)

**Comment by ymodak** [comment] 2019-03-05 20:43
Apologies for the delay in response. I think this issue is better asked on conversationai repo since its not a bug/feature request on TF side.
Please post it on conversationai repo from [here](https://github.com/conversationai/conversationai-models/issues).

**Comment by msushkov** [comment] 2019-03-05 20:52
Thanks for the response, apologies for the confusion. Submitted the issue here because BestExporter does not exhibit the documented behavior (exports multiple models instead of one).

**Comment by ymodak** [comment] 2019-03-09 00:15
In order to expedite the trouble-shooting process, please provide a minimal code snippet to reproduce the issue reported here. Thanks!

**Comment by ymodak** [comment] 2019-03-22 00:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-22 00:02 UTC
Labels: comp:apis, stat:awaiting response, type:support
