### ISSUE TITLE
Add wheel for python3.8 on pypi

### ISSUE THREAD

**Issue by stevenleeS0ht** [tensorflow/tensorflow#35438] opened 2019-12-27 00:23 UTC
Currently, there is no wheel on pypi for python 3.8

I strongly hope that there will be support for latest python version.

**Comment by oanush** [comment] 2019-12-27 08:48
@stevenleeS0ht ,
Hello, We can expect python 3.8 support with TF 2.2.
Please check  [#33374 ](https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-562663993)Thanks!

**Comment by mihaimaruseac** [comment] 2019-12-27 16:38
Closing as duplicate of #33374

**Closed by mihaimaruseac** 2019-12-27 16:38 UTC
Labels: stat:awaiting response, type:build/install
