### ISSUE TITLE
Cannot remove all warnings

### ISSUE THREAD

**Issue by erikchwang** [tensorflow/tensorflow#27045] opened 2019-03-22 20:55 UTC
Run the following code:

```
import os, logging

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
logging.getLogger("tensorflow").setLevel(logging.CRITICAL)
logging.getLogger("tensorflow_hub").setLevel(logging.CRITICAL)

import tensorflow as tf
import tensorflow_hub as hub

print(tf.contrib.util.constant_value(tf.ones([1])))
```
Then you will get the following warnings:
```

WARNING: Logging before flag parsing goes to stderr.
W0322 16:52:19.971889 139848381953792 __init__.py:56] Some hub symbols are not available because TensorFlow version is less than 1.14

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

```

How can I remove these disgusting messages?

**Comment by mihaimaruseac** [comment] 2019-03-22 22:45
I don't think you can remove the `contrib` going away warning

**Comment by chwang85** [comment] 2019-03-22 22:49
users do not like warnings, please...

**Comment by jvishnuvardhan** [comment] 2019-03-27 23:27
@chwang85 Could try the solution provided [here](https://github.com/tensorflow/tensorflow/issues/8340#issuecomment-332212742). It is not showing any warning when I used it. Please let us know how it progresses. Thanks!

**Comment by chwang85** [comment] 2019-03-28 01:05
```
import logging, os

logging.disable(logging.WARNING)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"

import tensorflow as tf

print(tf.contrib.util.constant_value(tf.ones([1])))
```

**Comment by wookayin** [comment] 2019-04-08 05:42
A bit hacky, but this works for me.

```
import types
import tensorflow as tf
if type(tf.contrib) != types.ModuleType:  # if it is LazyLoader
    tf.contrib._warning = None
```

**Comment by mihaimaruseac** [comment] 2019-04-08 14:49
If you want, can you submit a PR to make it using logger instead of `print()`?

**Comment by ymodak** [comment] 2019-05-13 19:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-05-13 19:25 UTC
Labels: type:docs, type:support

**Comment by joshlk** [comment] 2019-07-22 10:26
It's caused by abseil instead of tensorflow: abseil/abseil-py#99

Workaround: 
```
import absl.logging
logging.root.removeHandler(absl.logging._absl_handler)
absl.logging._warn_preinit_stderr = False
```

https://github.com/dhalperi/pybatfish/blob/f8ddd3938148f9a5d9c14c371a099802c564fac3/pybatfish/client/capirca.py#L33-L50

**Comment by leimao** [comment] 2019-08-08 18:49
> It's caused by abseil instead of tensorflow: [abseil/abseil-py#99](https://github.com/abseil/abseil-py/issues/99)
> 
> Workaround:
> 
> ```
> import absl.logging
> logging.root.removeHandler(absl.logging._absl_handler)
> absl.logging._warn_preinit_stderr = False
> ```
> 
> https://github.com/dhalperi/pybatfish/blob/f8ddd3938148f9a5d9c14c371a099802c564fac3/pybatfish/client/capirca.py#L33-L50

Hmm, I tried your suggestions and it seems that this did not work.

**Comment by leimao** [comment] 2019-08-08 20:37
> @chwang85 Could try the solution provided [here](https://github.com/tensorflow/tensorflow/issues/8340#issuecomment-332212742). It is not showing any warning when I used it. Please let us know how it progresses. Thanks!

This does not work in TF 1.13.

**Comment by satwikk** [comment] 2019-09-10 06:54
This is not the right way to do it but it works, if you are irritated by the warnings while working on your code. Just redirect stderr to /dev/null

```python
f = open('/dev/null', 'w')
sys.stderr = f
```
Find the original post [here](https://stackoverflow.com/a/6735958).

**Comment by joshlk** [comment] 2019-09-10 11:01
@satwikk that's potentially quite dangerous as you won't see any errors as well as warnings

**Comment by sanket1012** [comment] 2019-11-11 20:43
[https://github.com/tensorflow/tensorflow/issues/8340#issuecomment-332212742](url)
