### ISSUE TITLE
Creating variables in a `while_loop`

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#8604] opened 2017-03-21 21:49 UTC
I understand why this fails given the way control inputs are inserted in non-Variable ops created in while loops, but maybe the limitations should be documented somewhere:

```python
import tensorflow as tf
i = tf.constant(0)
def body(i):
  w = tf.Variable(tf.constant(1))
  return [i+w]
loop = tf.while_loop(lambda i: tf.less(i,5), body, [i])
s = tf.Session()
s.run(tf.global_variables_initializer())
```  

```

InvalidArgumentError: The node 'while/w/Assign' has inputs from different frames. The input 'while/j' is in frame 'while/while/'. The input 'while/w' is in frame ''.
```

**Comment by skye** [comment] 2017-03-22 14:47
I'll try to improve this if I have spare cycles, but for now I'm gonna mark this contributions welcome. I imagine it should additionally be possible to improve the error message in this case.

**Comment by critiqjo** [comment] 2017-03-22 15:17
I haven't seen any docs describing the word "frame" in this sense. It would help a lot to describe what frames are and how they get created.

**Comment by jcaraban** [comment] 2017-03-29 09:26
Is there any real use case where defining variables inside while_loop would help?
Any plans of augmenting the functionality of while_loop? Are contributions welcomed here?

**Comment by critiqjo** [comment] 2017-03-29 09:35
@jcaraban Ah, I actually meant to say "updated" (for instance an RNN cell state). I am not sure if variables can be created inside a while_loop, or whether there would be any use for it.

**Comment by albertz** [comment] 2017-04-20 07:32
Note that there is also a bug with the name scope ("while/while/"), I guess because there might be some variable_scope/name_scope mixup. I see the same bug in the same situation (`InvalidArgumentError: The node 'output/rec/orth_embed/b/Assign' has inputs from different frames. The input 'output/rec/orth_embed/Const' is in frame 'output/rec/while/output/rec/while/'. The input 'output/rec/orth_embed/b' is in frame ''.`).

Is it possible to set the frame as a scope? Then the variable creation could look like this:
```
with tf.frame_scope(''):
  w = tf.Variable(tf.constant(1))
```

I don't see a reason why not to create the variables inside the loop. It can make some code easier (in my current case, I don't really see a good option to avoid that).

I guess the problem is only because of the Assign-Op and the Const-Op which are assigned to the while-frame?

**Comment by albertz** [comment] 2017-04-20 07:38
I think #4478 is related (or even the same bug) (as well as #3114).

**Comment by albertz** [comment] 2017-04-20 07:58
Note, for the given test-code in the initial post here, I get a slightly different error:
```
ValueError: Fetch argument <tf.Operation 'init' type=NoOp> cannot be interpreted as a Tensor. (Operation name: "init"
op: "NoOp"
input: "^while/Variable/Assign"
 is not an element of this graph.)
```

**Comment by albertz** [comment] 2017-04-20 08:08
Actually, this will make it work:

```
    with tf.control_dependencies(None):
      w = tf.Variable(tf.constant(1))
```

**Comment by yuanbyu** [comment] 2017-04-30 04:34
It is always a good idea to use `tf.get_variable`. `tf.Variable` doesn't work well with control dependency and control flow (cond and while_loop).  For your example, I would do something like this:

```
def body(i):
  w = tf.get_variable("w", shape=(), dtype=tf.int32,
                      initializer=tf.ones_initializer())
  return i+w
loop = tf.while_loop(lambda i: i < 5, body, [0])
s = tf.Session()
s.run(tf.global_variables_initializer())

s.run(loop)
```

**Closed** 2017-05-26 03:12 UTC
Labels: stat:contributions welcome, type:docs

**Comment by cooijmanstim** [comment] 2019-08-18 21:06
@yuanbyu wrote

> It is always a good idea to use `tf.get_variable`. `tf.Variable` doesn't work well with control dependency and control flow (cond and while_loop).

This advice needs an update now that `get_variable` is gone in Tensorflow 2. Can we just use `tf.Variable` from within cond/while_loop? If not, what exactly makes it not "work well with control dependency and control flow", and how can we guard against this?

(Apologies for thread necromancy, but I think it's important to have this information on this thread for the sake of people coming from Google search results.)
