### ISSUE TITLE
Tensor name "hiddenlayer_2/biases" not found in checkpoint files model

### ISSUE THREAD

**Issue by eymar** [tensorflow/tensorflow#4276] opened 2016-09-08 13:46 UTC
I have created my model on one machine and then sent the zipped folder 'model' by email to myself so I would be able to use this model on my second PC. 

Here is the code how I'm recreating a model:
```
feature_columns = learn.infer_real_valued_columns_from_input(x_train)
classifier = learn.DNNClassifier(feature_columns=feature_columns, hidden_units=[40, 80, 40], n_classes=3, model_dir='model')
```

As I understood, to reuse a model I need to make 'fit' 1-3 steps. (This fact I found here in TF issues)

`classifier.fit(x_train, y_train, steps=3)`

Then when I call `predicted = classifier.predict(x_test)` , it throws an exception:  
tensorflow.python.framework.errors.NotFoundError: Tensor name "hiddenlayer_2/biases" not found in checkpoint files model/model.ckpt-30015-?????-of-00001

This model is working well on the machine where it has been created. 
How can I make it work on any PC?

Thanks!

**Comment by tatatodd** [comment] 2016-09-09 19:20
@eymar I'd start by narrowing down the problem:
1. Are you running the same setup on both machines (OS / tensorflow version / python version / etc)?
2. Do things work when run on each machine individually?  So is the only problem the transfer of the model from one machine to the other?

**Comment by eymar** [comment] 2016-09-10 04:59
@tatatodd Sorry, I didn't mention that.  

1) The configuration of machines is almost identical. The difference is only in OS - first machine is Ubuntu 14.04, the second one is Ubuntu 12.04. The rest are the same: Python 2.7.6, tensorflow  - r0.10

2) Yes, when I run on each machine individually, everything work. The problem is transferring model from one machine to the other.

P.S. Actually, I'm using skflow, but seems people are posting skflow's issues here too.

**Comment by tatatodd** [comment] 2016-09-12 18:18
I'm not sure what problem you're running in to.  For reference you can take a look at the general howto regarding saving and restoring variables:
https://www.tensorflow.org/versions/r0.10/how_tos/variables/index.html
https://www.tensorflow.org/versions/r0.10/how_tos/variables/index.html#checkpoint-files

And use inspect_checkpoint to see whether the checkpoint looks valid before and after you've transferred to different machines:
https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/python/tools/inspect_checkpoint.py

Let me know if that helps!

**Closed** 2016-09-16 07:56 UTC
Labels: awaiting response

**Comment by STHSF** [comment] 2017-09-13 02:48
@eymar Does your problem solved？ recently, I meet the similar problem。when i use a pretrained model in another machine, there something wrong happened. 
the problem is :
`2017-09-13 10:10:03.396626: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 10:10:03.396681: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 10:10:03.396694: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 10:10:03.396705: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 10:10:03.396714: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-09-13 10:10:03.649258: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint
2017-09-13 10:10:03.691347: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam_1 not found in checkpoint
2017-09-13 10:10:03.691625: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_1/lstm_cell/bias/Adam_1 not found in checkpoint
2017-09-13 10:10:03.693400: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/bias/Adam_1 not found in checkpoint
2017-09-13 10:10:03.695818: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam_1 not found in checkpoint
2017-09-13 10:10:03.697568: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_1/lstm_cell/bias not found in checkpoint
2017-09-13 10:10:03.697820: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/kernel not found in checkpoint
2017-09-13 10:10:03.698046: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_1/lstm_cell/kernel not found in checkpoint
2017-09-13 10:10:03.698193: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_1/lstm_cell/bias not found in checkpoint
2017-09-13 10:10:03.698306: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_1/lstm_cell/kernel/Adam not found in checkpoint
2017-09-13 10:10:03.700091: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_1/lstm_cell/kernel/Adam not found in checkpoint
2017-09-13 10:10:03.700892: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
2017-09-13 10:10:03.701265: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam not found in checkpoint
2017-09-13 10:10:03.702148: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_1/lstm_cell/bias/Adam not found in checkpoint
2017-09-13 10:10:03.704113: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
2017-09-13 10:10:03.704663: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_1/lstm_cell/bias/Adam not found in checkpoint
2017-09-13 10:10:03.704809: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_1/lstm_cell/kernel/Adam_1 not found in checkpoint
2017-09-13 10:10:03.705010: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint
2017-09-13 10:10:03.705397: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_1/lstm_cell/kernel not found in checkpoint
2017-09-13 10:10:03.705792: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_1/lstm_cell/kernel/Adam_1 not found in checkpoint
2017-09-13 10:10:03.706879: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/bias/Adam_1 not found in checkpoint
2017-09-13 10:10:03.707018: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/kernel/Adam not found in checkpoint
2017-09-13 10:10:03.707096: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/kernel not found in checkpoint
2017-09-13 10:10:03.707426: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key bi_lstm/bidirectional_rnn/fw/multi_rnn_cell/cell_1/lstm_cell/bias/Adam_1 not found in checkpoint
`

**Comment by wantongtang** [comment] 2017-09-25 09:14
solved? 
`NotFoundError (see above for traceback): Key aconv1d_0/variance/Adam_1 not found in checkpoint
	 [[Node: save/RestoreV2_14 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_14/tensor_names, save/RestoreV2_14/shape_and_slices)]]
	 [[Node: save/RestoreV2_95/_497 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1926_save/RestoreV2_95", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]`

**Comment by STHSF** [comment] 2017-09-25 09:31
I have solved this problem, so you can reference to this[tensorflow.python.framework.errors_impl.NotFoundError](https://sthsf.github.io/wiki/Algorithm/DeepLearning/%E4%BD%BF%E7%94%A8Tensorflow%E7%88%AC%E8%BF%87%E7%9A%84%E5%9D%91/tensorflow.python.framework.errors_impl.NotFoundError.html). Hope it can help you!
