### ISSUE TITLE
TF 0.6.0 slower than 0.5.0 with the cifar10 example

### ISSUE THREAD

**Issue by JianbangZ** [tensorflow/tensorflow#552] opened 2015-12-19 03:46 UTC
With the tensorflow/model/image/cifar10 example. While I run cifar10_train.py, 
It used to be able to achieve around 400+ examples/sec with my single K40 GPU. Today I pulled the code and installed the latest version (0.6.0x), but it can only achieve 300 examples/sec or less sometimes. 

I see Alexnet benchmark performance gets improved, but this actually use case gets worse performance.

**Comment by JianbangZ** [comment] 2015-12-19 03:51
This issue is for the code at commit 8b5d9ed13f188662dde7cce75362cd2394bde40c. I haven't tried other earlier 0.6.0. but the old 0.5.0 is confirmed faster.

**Comment by benoitsteiner** [comment] 2015-12-21 23:32
This looks like a duplicate of issue 548: I'll take a look and confirm whether or not this is the case.

**Comment by benoitsteiner** [comment] 2016-01-12 17:23
I believe this is fixed: I am now getting about 600 samples per second with a GTX Titan. Please reopen if this is still a problem for you.

**Closed by benoitsteiner** 2016-01-12 17:23 UTC
