### ISSUE TITLE
tensorflow:AutoGraph could not transform

### ISSUE THREAD

**Issue by dynamor2019** [tensorflow/tensorflow#36921] opened 2020-02-20 08:20 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
Downloading and preparing dataset imdb_reviews (80.23 MiB) to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0...
Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incomplete7ZTMSY/imdb_reviews-train.tfrecord
Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incomplete7ZTMSY/imdb_reviews-test.tfrecord
Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incomplete7ZTMSY/imdb_reviews-unsupervised.tfrecord
Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0. Subsequent calls will reuse this data.
WARNING:tensorflow:AutoGraph could not transform <function _get_dataset_from_filename at 0x7f9503308d08> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:AutoGraph could not transform <function _get_dataset_from_filename at 0x7f9503308d08> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Num'
WARNING: AutoGraph could not transform <function _get_dataset_from_filename at 0x7f9503308d08> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:AutoGraph could not transform <bound method TopLevelFeature.decode_example of FeaturesDict({
    'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
    'text': Text(shape=(None,), dtype=tf.int64, encoder=<SubwordTextEncoder vocab_size=8185>),
})> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:AutoGraph could not transform <bound method TopLevelFeature.decode_example of FeaturesDict({
    'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
    'text': Text(shape=(None,), dtype=tf.int64, encoder=<SubwordTextEncoder vocab_size=8185>),
})> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
WARNING: AutoGraph could not transform <bound method TopLevelFeature.decode_example of FeaturesDict({
    'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
    'text': Text(shape=(None,), dtype=tf.int64, encoder=<SubwordTextEncoder vocab_size=8185>),
})> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:AutoGraph could not transform <function _get_dataset_from_filename at 0x7f9503308d08> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:AutoGraph could not transform <function _get_dataset_from_filename at 0x7f9503308d08> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Num'
WARNING: AutoGraph could not transform <function _get_dataset_from_filename at 0x7f9503308d08> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:AutoGraph could not transform <bound method TopLevelFeature.decode_example of FeaturesDict({
    'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
    'text': Text(shape=(None,), dtype=tf.int64, encoder=<SubwordTextEncoder vocab_size=8185>),
})> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:AutoGraph could not transform <bound method TopLevelFeature.decode_example of FeaturesDict({
    'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
    'text': Text(shape=(None,), dtype=tf.int64, encoder=<SubwordTextEncoder vocab_size=8185>),
})> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4
WARNING: AutoGraph could not transform <bound method TopLevelFeature.decode_example of FeaturesDict({
    'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=2),
    'text': Text(shape=(None,), dtype=tf.int64, encoder=<SubwordTextEncoder vocab_size=8185>),
})> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 3, expecting 4

**Comment by amahendrakar** [comment] 2020-02-20 10:08
@dynamor2019,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by dynamor2019** [comment] 2020-02-20 14:02
I just followed the tutorials of tensorflow @ tensorflow.google.cn,


i try to learn&nbsp;

Text classification with preprocessed text: Movie reviews
with colab,&nbsp;


after&nbsp;
try:
&nbsp;&nbsp;#&nbsp;%tensorflow_version&nbsp;only&nbsp;exists&nbsp;in&nbsp;Colab.
&nbsp;&nbsp;!pip&nbsp;install&nbsp;-q&nbsp;tf-nightly
except&nbsp;Exception:
&nbsp;&nbsp;pass
import&nbsp;tensorflow&nbsp;as&nbsp;tf


i can not get tf 2.2.0 but 2.1.0


except the bug i submit, there is another bug appeard,as following:


train_batches&nbsp;=&nbsp;(
&nbsp;&nbsp;&nbsp;&nbsp;train_data
&nbsp;&nbsp;&nbsp;&nbsp;.shuffle(BUFFER_SIZE)
&nbsp;&nbsp;&nbsp;&nbsp;.padded_batch(32))

test_batches&nbsp;=&nbsp;(
&nbsp;&nbsp;&nbsp;&nbsp;test_data
&nbsp;&nbsp;&nbsp;&nbsp;.padded_batch(32))




---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)"><ipython-input-41-9a5275a8cbf1&gt; in <module&gt;()      4     train_data      5     .shuffle(BUFFER_SIZE)----&gt; 6     .padded_batch(32))      7       8 test_batches = (TypeError: padded_batch() missing 1 required positional argument: 'padded_shapes'










------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"amahendrakar"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 晚上6:08
收件人:&nbsp;"tensorflow/tensorflow"<tensorflow@noreply.github.com&gt;;
抄送:&nbsp;"李晓亮"<9370611@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] tensorflow:AutoGraph could not transform (#36921)




@dynamor2019,
 In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by amahendrakar** [comment] 2020-02-24 06:43
@dynamor2019,
I was able to run the code from the tutorial without any issues, please find the Gist of it [here](https://colab.research.google.com/gist/amahendrakar/f55d81960b26817ca4e247f6632d3dee/36921.ipynb).

Regarding the TensorFlow version, looks like you have TF 2.1 installed. If you want to install TF 2.2, which is the nightly version, please use the command `pip install tf-nightly`.

Thanks!

**Comment by amahendrakar** [comment] 2020-03-02 14:06
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-03-11 14:35
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-03-11 14:35 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:bug

**Comment by Songjiyang-yang** [comment] 2021-06-04 08:08
I have tensorflow 2.4.1 ,I came with the same problem,but my problem hasn't been solved.
