### ISSUE TITLE
Error converting Mobilenet model using TFLiteConverter

### ISSUE THREAD

**Issue by ajax98** [tensorflow/tensorflow#37821] opened 2020-03-23 07:09 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 2.1.1

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
 model._set_inputs(x)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```

**Failure details**

When I convert a model using TFLiteConverter with the settings above, it seems to create a uint8 node. However, when I try to run the converted model on my microcontroller using the Tensorflow Lite Micro the input node of the graph still seems to be the float version. Is there any way I can access the graph being created by Tensorflow Lite Converter or possibly set the input to the uint8 node?

**Comment by amahendrakar** [comment] 2020-03-23 15:59
@ajax98,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by amahendrakar** [comment] 2020-03-30 10:35
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-07 12:55
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-07 12:55 UTC
Labels: TF 2.1, TFLiteConverter, comp:lite, stat:awaiting response, type:support
