### ISSUE TITLE
tf.layers uses wrong variable scope

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#14703] opened 2017-11-19 14:33 UTC
TF 1.4.
```python
import tensorflow as tf
def f(x):
    return tf.layers.conv2d(x, 30, 3)

x = tf.zeros([3, 20, 20, 1])

with tf.variable_scope('a'):
    print(f(x))
with tf.variable_scope('a', reuse=True):
    print(f(x)) # works

print(f(x))
with tf.variable_scope(tf.get_variable_scope(), reuse=True):
    print(f(x)) # failed with:
"""
ValueError: Variable conv2d_1/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
"""
```

From what I can see, tf.layers is trying to create the variables under a wrong variable scope name, making variable sharing impossible if used under the root scope.

I found that this works:
```python
with tf.variable_scope(tf.get_variable_scope()):
    print(f(x))
with tf.variable_scope(tf.get_variable_scope(), reuse=True):
    print(f(x)) # works
```
But the first line seems redundant and counter-intuitive.

//UPDATE:
It also works if I don't use tf.layers:
```python
def f(x):
    W = tf.get_variable('w', shape=[1])
    return x + W
```

**Comment by facaiy** [comment] 2017-11-22 09:23
Yes, I think the bug will be fixed when my PR  #14390 is merged, see the commit:  https://github.com/tensorflow/tensorflow/pull/14390/commits/c59e89ad2a523bfaf0143a945ccc0754a7975aa2

**Comment by ppwwyyxx** [comment] 2017-11-22 09:42
I'm not sure I understand how they are related. Just to clarify, in my case I don't care what name scope is used inside the variable scope -- it can be either a new name scope or the original one. I just want the correct variable name, which ideally should be independent of the surrounding name scope.

**Comment by facaiy** [comment] 2017-11-22 09:44
Oh, my bad. The commit mentioned above is to resolve `original_name_scope` bug with root scope. Perhaps it's unrelated.

**Comment by x10000year** [comment] 2017-11-22 10:21
I don't think this is a bug. You use variable_scope in a wrong way.

**Comment by ppwwyyxx** [comment] 2017-11-22 10:33
@x10000year Which part is wrong?

**Comment by facaiy** [comment] 2017-11-22 11:29
Let's clarify it: do you expect that `layer_2` is `layer_1`?

```python
layer_1 = tf.layers.conv2d(x, 30, 3)
with tf.variable_scope(tf.get_variable_scope(), reuse=True):
  layer_2 = tf.layers.conv2d(x, 30, 3)
```

**Comment by ppwwyyxx** [comment] 2017-11-22 12:55
I thought the expectation is obvious. To clarify, if I write the following __naive__ "add" layer:
```python
def f(x):
    W = tf.get_variable('w', shape=[1])
    return x + W
```
Then my snippet can run with my expected variable sharing behavior. But tf.layers is doing something different now.

**Comment by facaiy** [comment] 2017-11-23 00:44
I think tf.layer should act like a class, instead of a function. I mean that tf.layer should maintain its variable scope and name scope, which won't be effected by outside. So layer_1 and layer_2 should be different objects in my opinion, am I wrong, @fchollet?

**Comment by tatatodd** [comment] 2017-12-01 01:58
Yes perhaps @fchollet can describe what the expected behavior is.

**Comment by tensorflowbutler** [comment] 2017-12-20 01:24
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:08
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by facaiy** [comment] 2018-01-04 04:27
ping @fchollet .

**Comment by tensorflowbutler** [comment] 2018-02-06 07:47
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-20 19:43
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-24 01:21
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by fchollet** [comment] 2018-03-27 19:56
The definitive answer on this issue is:

- Yes, this is an issue.
- We cannot fix it without breaking backwards compatibility.
- We will fix soon in `tf.keras`. It will never be fixed in `tf.layers` (since it is necessary to maintain existing code working -- which is not the case in Keras). `tf.layers` will eventually be removed (in TF 2.0).

**Closed by fchollet** 2018-03-27 19:56 UTC
Labels: stat:awaiting tensorflower

**Comment by ybsave** [comment] 2018-07-06 03:57
If tf.layers would be removed later, what should I use in the future? Is there any Tensorflow based middle level package like slim but supported officially by Google in later versions? I mean "pure tensorflow package", but not Keras.

**Comment by facaiy** [comment] 2018-07-06 06:21
@ybsave If I'm not wrong, `tf.layers` will be replaced by `tf.keras.layers` in the future.

**Comment by ybsave** [comment] 2018-07-06 14:59
@facaiy Thank you for your quick response. Are there any official Tensorflow documents about using the Tensorboard under tf.keras? So far, I only found lots of instructions about using Tensorboard by Keras in a pre-defined way. But I want to personalized my own Tensorboard data, e.g., my own intermediate results, my own defined scalars or histograms; so far, I do not find any instructions about that. If there are not any, will Tensorflow people update the guidance later? Thank you.

**Comment by facaiy** [comment] 2018-07-06 21:55
I think you can use tf.keras.layer like tf.layer as before. It's not necessary to combine them with tf.keras.Model or Sequence.

**Comment by ybsave** [comment] 2018-07-07 23:33
Thank you for you response. For the tf.keras.layers, is there any way of sharing initialization parameters like the "arg_scope" in slim?

**Comment by zh794390558** [comment] 2018-10-31 06:54
@facaiy Does tf.keras.layers will work with tf.variable_scope?

**Comment by facaiy** [comment] 2018-11-01 05:50
tf.variable_scope will be removed in tf 2.0. You can find more details here: https://github.com/tensorflow/community/pull/11
