### ISSUE TITLE
undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

### ISSUE THREAD

**Issue by bgcgh** [tensorflow/tensorflow#47794] opened 2021-03-14 09:15 UTC
This is an issue reported earlier and it remains for the following versions of tensorflow and keras:

Successfully installed tensorflow-2.4.1

Successfully installed keras-2.4.3

When trying to execute previously well-functioning keras/tensorflow-pythoncode output is: 

tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

Are the above versions of tensorflow and keras incompatible? Is a downgrade of tensorflow requried, and if so to which version ?

**Comment by amahendrakar** [comment] 2021-03-15 15:58
Also, please try installing TensorFlow in a new virtual environment and check if it works. Thanks!

**Comment by bgcgh** [comment] 2021-03-15 16:20
Hello Abhilash,


thank you for looking into the issue. It causes a real problem because if a downgrade is necessary that involves a requirement of certain libraries (such as libcublas.so.10, libcusolver.so.10, libcusparse.so.10) from CUDA 10.


OS Ubuntu 20.04

Tensorflow 2.4.1 installed via pip3

Python 3.8

CUDA 11.1.1/cuDNN8

GPU GeForce GTX 1660 Super, 6 GB DDRAM


The python code has been working well with Tensorflow 2.3.1.


Best regards,

bgcgh






________________________________

**Comment by amahendrakar** [comment] 2021-03-23 18:58
> The python code has been working well with Tensorflow 2.3.1.

@bgcgh,
Could you please provide the code you are running, so that we can reproduce the issue on our end?

I was able to run a minimal code snippet using TensorFlow v2.4.1 and Keras v2.4.3. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/7c769d007fff52882e3cb7f81adfabea/47794.ipynb#scrollTo=4ONtdNs1cI0K). Thanks!

**Comment by bgcgh** [comment] 2021-03-24 06:43
Hello Abhilash,


thank you very much again for looking into this issue. I hope the most relevant part of my code for a multiclass, multilabel temporal sequence problem is of some assistance to you:



import keras
from keras import layers

model=keras.models.Sequential()
model.add(layers.LSTM(512,input_shape=(len_seq,span),return_sequences=True))
model.add(layers.LSTM(512))
model.add(layers.Dense(span,activation='sigmoid'))

model.summary()

optimizer=keras.optimizers.RMSprop(lr=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer,metrics=['acc'])

history=model.fit(train_in,train_out,batch_size=32,epochs=10,
                  validation_data=(valid_in,valid_out))


To be able to continue my work right now, I have had to downgrade to tensorflow 2.3 and install CUDA 10 in parallel with CUDA 11.1 for required libraries.


Best regards,

bgcgh

________________________________

**Comment by bgcgh** [comment] 2021-04-01 07:24
I provided the complete code defining the model for your investigation of possible model-dependence of the tensorboard problem reported. The program runs well with tensorboard 2.3.1 as I have reported, so there should be no problem with the code or dataset (which I regrettably am unable to distribute). Since I have been forced to downgrade to  tensorboard 2.3.1 as well as to CUDA 11, it is not possible for me to perform the proposed test under the required conditions. Apologies for not being able to meet all your requests.

________________________________

**Comment by amahendrakar** [comment] 2021-04-09 15:48
> so there should be no problem with the code or dataset (which I regrettably am unable to distribute)

Without a reproducible code, it would be difficult for us to debug the issue. In this case, you can provide a dummy dataset and code to reproduce the error.

 
> Also, please try installing TensorFlow in a new virtual environment and check if it works. Thanks!

Could you please confirm if you are facing the same issue in a virtual environment as well? Thanks!

**Comment by bgcgh** [comment] 2021-04-10 15:24
Since, due to the current problem, I have had to downgrade to tensorflow version 2.3.1 as well as to CUDA 11.1 (and CUDA 10 for certain libraries) it is regrettably not possible to perform the tests you propose. In my current configuration, everything (code and datasets) works fine, which is of course the reason I tentatively ascribed the problem to the 2.4.1 version of tensorflow. There is perhaps a chance that the problem will be gone in the next version of tensorflow.

________________________________

**Comment by amahendrakar** [comment] 2021-04-19 06:39
> Since, due to the current problem, I have had to downgrade to tensorflow version 2.3.1 as well as to CUDA 11.1 (and CUDA 10 for certain libraries) it is regrettably not possible to perform the tests you propose.

@bgcgh,
Thank you for the update. Can we close this issue for now?

Please let us know if you are facing the same error with the latest version of TensorFlow v2.5.0rc1 as well. Thanks!

**Comment by bgcgh** [comment] 2021-04-19 13:20
This seems to have been a problem for other people and for quite some time, it is really unfortunate that it still remains unresolved. I apologize that I could not provide more than the model that generates the issue.


Best regards,

bgcgh

________________________________

**Comment by amahendrakar** [comment] 2021-04-21 18:28
@bgcgh,
Closing the issue for now. Please feel free to re-open if you can share a reproducible code with us. Thanks!

**Closed by amahendrakar** 2021-04-21 18:28 UTC
Labels: TF 2.4, stat:awaiting response, subtype: ubuntu/linux, type:build/install

**Comment by xuy** [comment] 2021-05-12 21:00
You could just delete `tensorflow/core/kernels/libtfkernel_sobol_op.so` inside the site-package folder. This kernel op is unlikely to be used by a normal DNN. 

I am guessing that a proper fix for the TF team is to figure out what dynamic library `https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sobol_op.cc` is using, and why the particular cuda/linux distribution combo didn't have it, because from the first glance this code has nothing to do with CUDA and is purely CPU-based.

Ref: https://en.wikipedia.org/wiki/Sobel_operator

**Comment by bgcgh** [comment] 2021-05-13 05:16
Thank you very much xuy for kindly sharing your helpful conclusions! I will certainly apply your advice when having upgraded my system back again.

Best regards,
bgcgh
