### ISSUE TITLE
Readmea for tensorboard not on website

### ISSUE THREAD

**Issue by brando90** [tensorflow/tensorflow#2955] opened 2016-06-20 02:21 UTC
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Browser issue with readme tensorboard

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. not tensorproblem but website

If installed from sources, provide the commit hash:

### Steps to reproduce
1. Go to https://www.tensorflow.org/versions/r0.9/how_tos/summaries_and_tensorboard/index.html and click on the readme tensorboard. Give you 404 not found error.

### What have you tried?
1. nothing, its on the website

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

![screen shot 2016-06-19 at 10 20 53 pm](https://cloud.githubusercontent.com/assets/1855278/16181716/2cfc7cd4-366c-11e6-92e2-ed67906c95eb.png)

**Comment by prb12** [comment] 2016-06-20 16:42
Closing as duplicate of #2813

**Closed by prb12** 2016-06-20 16:42 UTC
Labels: docs, tensorboard
