### ISSUE TITLE
expected conv2d_input to have 4 dimensions with shape(1, 1)

### ISSUE THREAD

**Issue by 007fred50** [tensorflow/tensorflow#28622] opened 2019-05-11 10:38 UTC
after i fit my machinelerning i trying to predict a new one. as image named demo1.jpg

what i expected get new feature. into my library:

My detailts:
RTX 2080
Tensorflow  1.13.1
Cuda 10.0

Can some one help me? Thanks !!

I'm using tf.keras and I'm getting following error:

> ValueError: Error when checking input: expected conv2d_input to have 4 dimensions, but got array with shape (1, 1)

I got new error then i mode.predict a new (feature):

```
import tensorflow as tf
import numpy as np
import pickle
import cv2
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D

IMG_SIZE = 50

def prepare(file):
    img_array = cv2.imread(file, cv2.IMREAD_GRAYSCALE)
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))

    predictdata = tf.reshape(new_array, (1, 50, 50))
    predictdata = np.expand_dims(predictdata, -1)
    return predictdata


pickle_ind = open("x.pickle", "rb")
x = pickle.load(pickle_ind)
x = np.array(x, dtype=float)
x = np.expand_dims(x, -1)

pickle_ind = open("y.pickle", "rb")
y = pickle.load(pickle_ind)

n_batch = len(x)

model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(50, 50, 1)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Flatten())
model.add(Dense(1, activation='softmax'))

model.summary()

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(x, y, epochs=1, batch_size=n_batch)
prediction = model.predict([prepare('demo1.jpg')], batch_size=n_batch, steps=1, verbose=1)

print(prediction)
```

**Comment by muddham** [comment] 2019-05-13 12:05
@007fred50 In the earlier opened issue [link](https://github.com/tensorflow/tensorflow/issues/28442) , seems like you have got the stackoverflow link.Can you please refer this. As this is the custom code after I ran the code it says 'Errno 2] No such file or directory: 'x.pickle'.

**Comment by 007fred50** [comment] 2019-05-13 12:50
hello

you can download it here:
http://people8people.com/x.pickle
http://people8people.com/y.pickle

**Comment by 007fred50** [comment] 2019-05-14 12:31
can you test it ?

**Comment by muddham** [comment] 2019-05-17 11:10
@007fred50 Ran the code, Able to get the ouptut , please find the below details.
Layer (type) Output Shape Param # 
 conv2d (Conv2D) (None, 48, 48, 32) 320 
max_pooling2d (MaxPooling2D) (None, 24, 24, 32) 0 
 conv2d_1 (Conv2D) (None, 22, 22, 64) 18496 
 max_pooling2d_1 (MaxPooling2 (None, 11, 11, 64) 0 
conv2d_2 (Conv2D) (None, 9, 9, 64) 36928 
flatten (Flatten) (None, 5184) 0 
 dense (Dense) (None, 1) 5185 
Total params: 60,929 Trainable params: 60,929 Non-trainable params: 0

**Comment by 007fred50** [comment] 2019-05-17 11:29
Hello,

can you send me a code? i can't read that messages you gave me

**Comment by muddham** [comment] 2019-05-17 11:56
@007fred50 Ran the same code provided here, in jupyter notebook.

**Comment by 007fred50** [comment] 2019-05-17 12:19
Here is my jupyter notebook. with photo

<img width="976" alt="Screenshot 2019-05-17 at 14 18 06" src="https://user-images.githubusercontent.com/25218874/57927575-b8b4a580-78ae-11e9-997a-158db8934200.png">

**Comment by muddham** [comment] 2019-05-17 13:38
@007fred50 Seems like you have not received any error after executing in jupyter notebook.Please confirm if I can close this issue from my side

**Comment by 007fred50** [comment] 2019-05-17 14:26
I got this error then i don't use GPU:

```
24946/24946 [==============================] - 16s 631us/sample - loss: 7.6647 - acc: 0.5001
Traceback (most recent call last):
  File "test.py", line 67, in <module>
    prediction = model.predict([prepare('demo1.jpg')], batch_size=n_batch, steps=1, verbose=1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1080, in predict
    x, check_steps=True, steps_name='steps', steps=steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 2690, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_utils.py", line 377, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected conv2d_input to have 4 dimensions, but got array with shape (1, 1)
```

**Comment by muddham** [comment] 2019-05-27 08:16
@007fred50 I ran the code with GPU but no error message was displayed. This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by muddham** [comment] 2019-06-03 12:20
@007fred50 Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2019-06-03 12:21 UTC
Labels: TF 1.13, comp:ops, type:support
