### ISSUE TITLE
realtime bounding box 

### ISSUE THREAD

**Issue by cdragon2** [tensorflow/tensorflow#17457] opened 2018-03-06 00:42 UTC
i use tensorflow project for android

I trained my custom datsets by yolo and then i made pb file.

This detected bounding box where i used picture not realtime

But when i put yolo file  in the android project, this cannot detect.

So i screenshot the scene of android project and i trained this screenshot in pc by darkflow.

It detected well. I don't know why. I think option value is correct. plz help me T.T

**Comment by tensorflowbutler** [comment] 2018-03-06 13:48
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by andrewharp** [comment] 2018-03-15 20:12
I'm not clear what you're asking. Is this question about tracking or YOLO?

The realtime tracking is provided by libtensorflow_demo.so. You can double-check that it's packaged in the APK with `unzip -v tensorflow_demo.apk`. If it's not there, you'll just see stationary boxes for detections. Bazel builds of the demo will include it, but if you use the "none" buildType in build.gradle then you won't get it.

**Comment by tensorflowbutler** [comment] 2018-03-30 12:30
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-17 12:41
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by skye** [comment] 2018-04-18 19:42
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by skye** 2018-04-18 19:42 UTC
Labels: stat:awaiting response

**Comment by achraf-boussaada** [comment] 2018-05-17 14:07
is it possible to include the libtensorflow_demo.so manually and avoid building with bazel ? i downloaded the file from [here](http://ci.tensorflow.org/view/Nightly/job/nightly-android/lastStableBuild/) created a jniLibs in my project but still the ObjectTracker can't find the library. Any solutions ?
