### ISSUE TITLE
TensorBoard doesn't show Events on TensorFlow v0.10 RC

### ISSUE THREAD

**Issue by tomrunia** [tensorflow/tensorflow#3750] opened 2016-08-11 12:51 UTC
After a clean install of TensorFlow v0.10 (from `master`) my TensorBoard is suddenly broken. The scalar event plots do not show upon clicking (see screenshow below). While the logs in the terminal do not show any errors, the Chrome Developer console shows the following error upon opening a figure:

```
tf-tensorboard.html:1517 Uncaught Error: tf-chart-scaffold's content doesn't implement the required interfaceinsertBefore @ VM2478 polymer-mini.html:560
```

I am running Chrome Version 52.0.2743.116 (64-bit) on Linux Mint 17.

![TensorBoard](http://i.imgur.com/GnR46NL.png)

**Comment by girving** [comment] 2016-08-11 18:11
@danmane Can you take a look?  Looks like a dependency version problem.

**Comment by Jerryzcn** [comment] 2016-08-12 04:42
Got the same error. The server is on a ubuntu, and the client is a mac.

**Comment by tomrunia** [comment] 2016-08-12 07:52
I found a temporary fix. Replace the file `[...]/python2.7/site-packages/tensorflow/tensorboard/dist/tf-tensorboard.html` with the older version from TensorFlow v0.9. This version can be found here: https://raw.githubusercontent.com/tensorflow/tensorflow/r0.9/tensorflow/tensorboard/dist/tf-tensorboard.html. This way the plots will work again. Hopefully there will be a proper fix soon :-)

**Comment by RenatoUtsch** [comment] 2016-08-15 19:07
I can reproduce on the master branch, on r0.10 it is working properly.

**Comment by danmane** [comment] 2016-08-15 22:11
We've fixed this internally, and I've verified that a new opensource repo built from the fixed version has a working TensorBoard.

Once we sync the changes to GitHub, I'll merge the fix into the r0.10 branch.

**Comment by tomrunia** [comment] 2016-08-16 11:30
I can confirm that this bug is now fixed. Just did a `git pull` of the master and rebuild, TensorBoard events are now shown properly. 

https://github.com/tensorflow/tensorflow/commit/ccd431b20a82ba2ecb96a82fb6e2712f2b522a11

**Comment by RenatoUtsch** [comment] 2016-08-17 17:40
Great. As r0.10 was not broken, only master, I'll close this as it's been fixed.

**Closed by RenatoUtsch** 2016-08-17 17:40 UTC
Labels: bug, tensorboard

**Comment by danmane** [comment] 2016-08-18 18:05
(Also, I merged TB25 into r0.10 anyway :) )
