### ISSUE TITLE
Inference Accuracy Regression for Resnet50 and Densenet

### ISSUE THREAD

**Issue by mahmoud-abuzaina** [tensorflow/tensorflow#24029] opened 2018-11-28 23:09 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NA
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Centos 7.5
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): master branch, commit 0c1eb886 onward
- Python version: 2.7
- Bazel version (if compiling from source): 0.15.0
- GCC/Compiler version (if compiling from source): 6.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
Inference accuracy for Resnet50 and Densenet has dropped to zero on CPU. This commit https://github.com/tensorflow/tensorflow/commit/0c1eb8861624d6d17c797b70d25330711df5eb2f was found to be causing the regression.

**Describe the expected behavior**
Resnet50 inference accuracy should look something close to (Top1, Top5) = (0.7315, 0.9109).

**Comment by msymp** [comment] 2019-01-04 22:33
Hello @petermattson  , can you please check this resnet50 accuracy issue ? Thanks.

**Comment by petermattson** [comment] 2019-03-04 22:47
Hi mysymp, I'm not right person for one.

**Comment by jvishnuvardhan** [comment] 2019-03-11 22:33
@mahmoud-abuzaina Could you check and let us know whether the issue persists with latest TensorFlow2.0? Could you share a code to reproduce the bug? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-18 21:35
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-18 21:35 UTC
Labels: comp:model, stat:awaiting response, type:bug/performance
