### ISSUE TITLE
[Feature Request] Add tf.extract_image_patches support on 3D inputs

### ISSUE THREAD

**Issue by Fnjn** [tensorflow/tensorflow#17843] opened 2018-03-19 21:00 UTC
currently, [extract_image_patches](https://www.tensorflow.org/api_docs/python/tf/extract_image_patches) only support 2d image input(4d tensor) [batch, in_rows, in_cols, depth], I think it would be helpful to add 3d input support (ie 5d tensor [batch, in_rows, in_cols, in_higs, depth]. 

In recently months, 3D deep learning has become very popular. I think it's time to add 3D support on most tensorflow api.

OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from: N/A
TensorFlow version: 1.6
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment] 2018-03-20 08:33
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tatianashp** [comment] 2018-03-22 01:27
@kho Could you comment?

**Comment by kho** [comment] 2018-03-22 14:39
@gpapan

**Comment by tatianashp** [comment] 2018-03-28 23:04
We currently don't have anybody working on this. If you or somebody else could help us by implementing this it'd be great.  The code will be similar to that in core/kernels/extract_image_patches_op.* except that it should call to Eigen with extract_volume_patches instead of extract_image_patches. Let us know if you need further clarification. Thanks!

**Comment by hsgkim** [comment] 2018-08-10 13:54
@tatianashp Is anyone working on this or has finished this? If not, I'd like to contribute. Sorry for bumping up a pretty old issue, and thanks in advance!

**Comment by tatianashp** [comment] 2018-08-10 22:39
@hsgkim As far as I know, nobody has implemented this for 3D and your contributions will be very helpful. Adding a few other folks to make certain.
/cc @asimshankar @ezhulenev

**Comment by fcacarminati** [comment] 2018-08-11 07:04
Gentlepersons,
  thanks a lot for looking into this. I would be very glad if the 3D performance could be improved. Greetings from CERN (http://www.cern.ch)

**Comment by tatianashp** [comment] 2018-08-11 17:24
Reopened the issue to keep track of the progress on PR.

**Comment by hsgkim** [comment] 2018-08-12 11:34
@tatianashp Sorry, this is my first time ever contributing to TensorFlow, so I'm not quite sure where to place my files; should they be under `tensorflow/core/kernels` so that my op becomes `tf.extract_volume_patches`, or somewhere under `contrib`?

And it looks like Eigen for some reason designed `extract_volume_patches` in a way that does not let you pass the `rate`s (in a very straightforward way at least), i.e.
```c++
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
const TensorVolumePatchOp<Dynamic, Dynamic, Dynamic, const Derived>
extract_volume_patches(const Index patch_planes, const Index patch_rows, const Index patch_cols,
                       const Index plane_stride = 1, const Index row_stride = 1, const Index col_stride = 1,
                       const PaddingType padding_type = PADDING_SAME, const Scalar padding_value = Scalar(0)) const {
  return TensorVolumePatchOp<Dynamic, Dynamic, Dynamic, const Derived>(derived(), patch_planes, patch_rows, patch_cols, plane_stride, row_stride, col_stride, 1, 1, 1, 1, 1, 1, padding_type, padding_value);
}
```

cf) `extract_image_patches`
```c++
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
const TensorImagePatchOp<Dynamic, Dynamic, const Derived>
extract_image_patches(const Index patch_rows = 1, const Index patch_cols = 1,
                      const Index row_stride = 1, const Index col_stride = 1,
                      const Index in_row_stride = 1, const Index in_col_stride = 1,
                      const PaddingType padding_type = PADDING_SAME, const Scalar padding_value = Scalar(0)) const {
  return TensorImagePatchOp<Dynamic, Dynamic, const Derived>(derived(), patch_rows, patch_cols, row_stride, col_stride,
                                                             in_row_stride, in_col_stride, 1, 1, padding_type, padding_value);
}
```

Is it a must to keep the `rate` arguments or can I leave them out for volume patches?

**Comment by fcacarminati** [comment] 2018-08-15 08:28
@tatianashp Sorry for pinging... I am the concerned user :-) Could someone answer Kim? Thanks!

**Comment by ezhulenev** [comment] 2018-08-15 16:41
@hsgkim 1. That should be a new kernel under a core/kernels directory. 2. It would be nice to have api consistent with image patches, though I’m not sure how important to have rates for volume patches. It seems that omitting parameter from the kernel and using default value of 1 for row/col rates is ok. Rates can be added later and it should be backward compatible.

**Comment by hsgkim** [comment] 2018-08-19 15:50
@tatianashp @ezhulenev Thanks for the comments! I just made a pull request and I would appreciate your feedback.
/cc @fcacarminati

**Comment by fcacarminati** [comment] 2018-08-30 10:12
Hello, sorry again for pinging, I would be very interested to understand the progress on this matter. Sorry for the bother and best regards,

**Comment by hsgkim** [comment] 2018-08-30 12:49
You can track the PR status here: https://github.com/tensorflow/tensorflow/pull/21715

**Comment by tensorflowbutler** [comment] 2018-09-14 12:38
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by fcacarminati** [comment] 2018-10-02 11:08
@hsgkim I found a 2.5 improvement. When can we expect these changes in master? best

**Comment by hsgkim** [comment] 2018-10-02 11:53
@fcacarminati The PR has already been merged to master. Thanks!

**Comment by fcacarminati** [comment] 2018-10-02 12:39
@hsgkim Great!!! Checking now with the head.

**Comment by facaiy** [comment] 2018-10-05 01:15
Close it as #21715 has been merged. Thank @hsgkim for you work!

**Closed by facaiy** 2018-10-05 01:15 UTC
Labels: stat:contributions welcome, type:feature
