### ISSUE TITLE
sparse.to_dense don't work when used to dataset element

### ISSUE THREAD

**Issue by yiqingyang2012** [tensorflow/tensorflow#29594] opened 2019-06-10 11:54 UTC
`def _parse_function(example_proto):

  features = {"feature0":tf.io.VarLenFeature(tf.int64),
              "feature1": tf.io.FixedLenFeature([1], tf.int64)}
  parsed_features = tf.io.parse_single_example(example_proto, features)
  print(parsed_features['feature0'])
  return tf.sparse.to_dense(parsed_features['feature0']), parsed_features['feature1']

dataset = tf.data.TFRecordDataset(filename)
dataset = dataset.map(_parse_function)`

error like below
`  File "/home/yi/bin/Miniconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/sparse_ops.py", line 68, in _convert_to_sparse_tensor
    raise TypeError("Input must be a SparseTensor.")
TypeError: Input must be a SparseTensor.`

**Comment by jvishnuvardhan** [comment] 2019-06-18 00:35
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-24 23:56
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-06-24 23:56 UTC
Labels: comp:data, stat:awaiting response, type:bug/performance
