### ISSUE TITLE
Behavior change of tf.app.flags parsing boolean args

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#15503] opened 2017-12-20 07:22 UTC
tf version 1.5.0-dev20171219
for example below args
flags.DEFINE_boolean('pre_calc_image_feature', False, '')

when using tf 1.4.1 it is ok to do --pre_calc_image_feature 0
which got FLAGS.pre_calc_image_feature == False.
But for tf 1.5 you must use --pre_calc_image_feature=0 if you still use --pre_calc_image_feature 0
then you will get FLAGS.pre_calc_image_feature == True. 

Not sure if this is a bug or just by design but personally I think tf version 1.4.1 is better handling this case.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:27
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by chenghuige** [comment] 2017-12-23 06:47
ubuntu 16.04
pip install tensorflow-nightly-gpu
tf version 1.5.0-dev20171219
cuda 9.0 cudnn 7.0
gtx1080ti 11g

**Comment by tensorflowbutler** [comment] 2018-01-06 18:55
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-01-23 22:56
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by yilei** [comment] 2018-01-30 02:07
Looks like so, that's a subtle difference between previous `tf.flags` and `absl.flags`. In `absl.flags` boolean flags are specified with:

```
--pre_calc_image_feature
--nopre_calc_image_feature
--pre_calc_image_feature=true/false/1/0/t/f
```

The `0` in `--pre_calc_image_feature 0` is treated as a positional argument.

**Comment by reedwm** [comment] 2018-01-30 02:34
Closing since this behavior cannot be fixed.

**Closed by reedwm** 2018-01-30 02:34 UTC
Labels: stat:awaiting tensorflower

**Comment by martinwicke** [comment] 2018-02-01 21:19
This is regrettable. We never documented tf.flags other than its existence (we never committed to details). I wish we had never included it in tf -- everybody really should just use argparse (or whatever else).
