### ISSUE TITLE
looping over tf.range in tf.function is slower than looping over range

### ISSUE THREAD

**Issue by amitport** [tensorflow/tensorflow#40708] opened 2020-06-23 06:43 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
colab tensorflow 2

`v2.2.0-0-g2b96f3662b 2.2.0`
tested on both CPU and GPU (GPU is much worse!)

**Describe the current behavior**

when timing a simple tf.function that uses a loop, `tf.range` is much slower than using `range`.
BUT `tf.range` is recommended in the docs, moreover is says that looping over non-tensor will be rolled during tracing (which does not happen. normal `range` is being traced as a loop)

```
@tf.function(input_signature=[tf.TensorSpec(shape=[None], dtype=tf.float32)])
def test(x):
  for i in tf.range(100):
    x = x * tf.constant(1.1)
  return x
```

```
%%timeit
test(tf.range(1000, dtype='float32'))
```
prints `100 loops, best of 3: 2.12 ms per loop`
prints `10 loops, best of 3: 70.2 ms per loop` on GPU!
while using `range` or `np.arange` is about 300 micro seconds in both CPU and GPU

**Describe the expected behavior**

1 there is a documentation issue where it currently always recommends `tf.range`.
2 the documentation should specify when python loops are not rolled
3 tf.range performance should be the same as range when used in a traced loop
(also note the `np.arange` is faster than `tf.range` and comparable to `range`)

**Comment by amahendrakar** [comment] 2020-06-23 16:59
@amitport,
I was able to reproduce the issue with TF v2.2, however I see significant improvement with TF-nightly. Please check the below gist for reference. 

- TF v2.2 with [CPU](https://colab.research.google.com/gist/amahendrakar/05c67191e500e8ead961f721586ca9d4/40708-cpu.ipynb), TF v2.2 with [GPU](https://colab.research.google.com/gist/amahendrakar/82bed13091464f020491b09382600bc5/40708-gpu.ipynb)

- TF-nightly with [CPU](https://colab.research.google.com/gist/amahendrakar/e0962ea3f751c38cd7a19566dd056aa0/40708-cpu-tf-nightly.ipynb), TF-nightly with [GPU](https://colab.research.google.com/gist/amahendrakar/a7164d22b652dbdddfc9cc2b8052c811/40708-gpu-tf-nightly.ipynb)

Thanks!

**Comment by amitport** [comment] 2020-06-23 20:27
@amahendrakar thanks for looking at it. better but still
gpu tf.range:
 31.9 ms 
cpu tf.range:
 ~2ms

while np.range and range around 496 µs

seems weird, and in case range is being traced as a loop and not rolled is also a doc issue

**Comment by nikitamaia** [comment] 2020-07-03 16:57
Hi @amitport, can you link to the docs issue you're referring to?

**Comment by amitport** [comment] 2020-07-04 05:14
https://www.tensorflow.org/guide/function#looping_over_python_data

**Comment by nikitamaia** [comment] 2020-07-04 20:20
I tried calling the timeit function directly (on CPU), instead of using the magic function, I'm seeing very little difference for a small number of runs.

`timeit.timeit(lambda: test(tf.range(1000, dtype='float32')), number=10)`
`## 0.20558238199964762`

`timeit.timeit(lambda: test2(tf.range(1000, dtype='float32')), number=10)`
`## 0.22194579899996825`

If you increase the number to 100, then there is a notable difference. I'm wondering if python is doing some caching that is speeding range up in the long run.

**Comment by mdanatg** [comment] 2020-07-04 23:44
A few notes below. In summary:
 * `for i in range(100)` is unrolled, and that will influence measurement results
 * `for i in tf.range(100)` is currently slightly slower and `while i < tf.constant(100)` - we're working on workarounds
 * `tf.while_loop` is significantly slower on GPU than it is on CPU - that is likely because GPUs are not optimized for scalar computation, but worth investigating
 * using `tf.function(experimental_compile=True)` improves the performance and is recommended

### Unrolling of `for i in range(n)`
A for loop over a non-Tensor is being unrolled, that is, it's equivalent to writing:

```
x = x * tf.constant(1.1)
x = x * tf.constant(1.1)
... 98 more times ...
```

Normally, these multiplications by a constant will be further folded away, so in the end you benchmark `x = x * tf.constant(1.1 ** 100)`. So the results will not be apples-to-apples.

### Performance of `for i in tf.range(n)`
Especially on GPU, this is slower than an equivalent `tf.while_loop`. This is tracked in #40517, and will be partially fixed in TF 2.3 and fully fixed in 2.4. Expect this to be in nightly soon.

### Performance of `tf.while_loop` on GPU
It appears that `tf.while_loop` is about 10x slower on GPU than CPU, and that is worth having a closer look. It's very likely that the multiplication is just too small to run efficiently on GPU:

```
@tf.function
def test(x):
  i = 0
  while i < tf.constant(100):
    x = x * tf.constant(1.1)
    i += 1
  return x
```

```
%%timeit
test(tf.range(1000.0))
# 100 loops, best of 3: 11.6 ms per loop
```

And when pinned to the CPU:

```
@tf.function
def test(x):
  with tf.device('cpu'):
    i = 0
    while i < tf.constant(100):
      x = x * tf.constant(1.1)
      i += 1
    return x
```

```
%%timeit
with tf.device('cpu'):
  test(tf.range(1000.0))
# 1000 loops, best of 3: 852 µs per loop
```

### `experimental_compile=True` improves performance in all cases

The slowdown is mitigated when using `experimental_compile=True`, which is a good idea to apply in all cases if possible. Although some CPU-GPU differences remain:

```
@tf.function(experimental_compile=True)
def test(x):
  for i in tf.range(100):
    x = x * tf.constant(1.1)
  return x
```

```
%%timeit
test(tf.range(1000.0))
# 100 loops, best of 3: 2.1 ms per loop
```

```
@tf.function(experimental_compile=True)
def test(x):
  with tf.device('cpu'):
    for i in tf.range(100):
      x = x * tf.constant(1.1)
    return x
```

```
%%timeit
with tf.device('cpu'):
  test(tf.range(1000.0))
# 1000 loops, best of 3: 432 µs per loop
```

**Comment by amitport** [comment] 2020-07-05 06:28
Thanks @mdanatg your response and it explains a lot. as far as I'm concerned this issue can be closed though there is definitely a lot of room for improvement in tf.function documentation.

A lot of information is spread throughout the documentation site, but I think it is very hard to find and the API pages themselves (mainly https://www.tensorflow.org/api_docs/python/tf/function) are currently missing many crucial things. Also IMO, the response type of tf.function should have its own detailed API page presenting things like `get_concrete_function` and how to view the generated graph inherently. (right now, without looking at tutorials, it's not clear if things like `input_signature` are a public API or not)

**Comment by rmothukuru** [comment] 2021-06-03 09:25
Could reproduce the issue with **`Tensorflow Version 2.5`**. Please find the Gist of [CPU](https://colab.research.google.com/gist/rmothukuru/59edbb4b907a5c9806214c39a5f820d7/40708-cpu.ipynb) and [GPU](https://colab.research.google.com/gist/amahendrakar/82bed13091464f020491b09382600bc5/40708-gpu.ipynb).

**Comment by sushreebarsa** [comment] 2021-12-13 16:45
@amitport Could you please try on the latest stable TensorFlow Version 2.7.0 and let us know if it helps?Thanks!

**Comment by amitport** [comment] 2021-12-13 19:08
@sushreebarsa. this is still an issue with 2.7, you can just run the Gists from the previous comment (https://github.com/tensorflow/tensorflow/issues/40708#issuecomment-853726914)

**Comment by gadagashwini** [comment] 2022-08-01 02:07
Was able to reproduce the issue with `tf-nightly-2.11.0-dev20220731`. Please find the gist [CPU](https://colab.research.google.com/drive/1FY7aFGEGkyUcfznFXmZjXMRtC4bWUXUB?usp=sharing) and [GPU](https://colab.research.google.com/drive/1l-NopnTX-YPIgDqvg5ef_-RBnjIsVsJ0?usp=sharing). Thank you!

**Comment by sun51** [comment] 2022-11-14 23:57
Closing this bug since the reason is figured out. It is not a apple-to-apple comparison for the example provided due to the constant folding for range case. On GPU the example is not a good fit to run on GPU.  Meanwhile, we will improve the tf function documentation

**Closed by sun51** 2022-11-14 23:57 UTC
Labels: type:docs-bug, comp:runtime, comp:gpu, comp:autograph, type:performance, comp:core, TF 2.9
