### ISSUE TITLE
How to specify the original name of an image using summary.image? 

### ISSUE THREAD

**Issue by CharlesShang** [tensorflow/tensorflow#7964] opened 2017-03-01 07:23 UTC
I want to visualize detection results on images using `tf.summary.image` and record the original name of this image at the same time.
In the old version `tf.image_summary()`, I can pass a placeholder for an image name and feed the name in `sess.run`.  Like this,
```
log_image_data = tf.placeholder(tf.uint8, [None, None, 3])
log_image_name = tf.placeholder(tf.string)
log_image = tf.image_summary(log_image_name, tf.expand_dims(log_image_data, 0), max_images=1)
```
But the new version of api only allows to speficy a fixed `name` in string type instead of a placeholder when building the summry graph. 
 ```
tf.summary.image(name, tensor, max_outputs=3, collections=None) 
# Args: 
# name: A name for the generated node, which cannot be a placeholder
```

How can I name the visualized image on the fly?

**Comment by CharlesShang** [comment] 2017-03-01 07:44
A substitute solution is `gen_logging_ops._image_summary` 
```
log_image_data = tf.placeholder(tf.uint8, [None, None, 3])
log_image_name = tf.placeholder(tf.string)
from tensorflow.python.ops import gen_logging_ops
log_image = gen_logging_ops._image_summary(log_image_name, tf.expand_dims(log_image_data, 0), max_images=1)
```

**Comment by ppwwyyxx** [comment] 2017-03-02 10:12
duplicate of #5558

**Comment by tatatodd** [comment] 2017-03-02 22:14
Thanks for the note @ppwwyyxx .

I'm closing this out.  @CharlesShang please follow up on #5558

**Closed by tatatodd** 2017-03-02 22:14 UTC

**Comment by CharlesShang** [comment] 2017-03-03 04:41
Thank you
