### ISSUE TITLE
Feature Request:   Tensorflow for Python 3.6 

### ISSUE THREAD

**Issue by Moondra** [tensorflow/tensorflow#10252] opened 2017-05-27 16:21 UTC
Hi,

I was wondering if there are plans to release tensorflow for Python 3.6  and if so is there ETA?

Thank you.

**Comment by caisq** [comment] 2017-05-27 19:44
@Moondra, can you please clarify what operating system(s) you question is about? Thanks.

**Comment by Niu5056** [comment] 2017-05-28 05:33
I assume "cp36" refers to "python 3.6". If that's the case, it is already out.

**Comment by larcai** [comment] 2017-05-28 12:31
I cannot seem to find the TF on py3.6 on windows
I tried both CPU and GPU versions at https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.1.0-cp36-cp36m-win_amd64.whl

**Comment by caisq** [comment] 2017-05-28 14:16
@gunan

**Comment by gunan** [comment] 2017-05-28 16:25
It is not available yet.
Closing this issue as a duplicate of #6999

**Closed by gunan** 2017-05-28 16:25 UTC

**Comment by Moondra** [comment] 2017-05-28 23:47
@caisq  Hi, I was looking for the Windows version. Thank you.
