### ISSUE TITLE
InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero

### ISSUE THREAD

**Issue by alexmil2019** [tensorflow/tensorflow#30037] opened 2019-06-21 22:39 UTC
python 3.6
Ubuntu 16.04.6 LTS
tensorflow '1.13.1'
```
feat_width = 2048
gpu_num = 8

def create_cnn_model(feat_width, data_format='channels_last'):
   model = tf.keras.Sequential()
   model.add(
      tf.keras.layers.Conv2D(
        filters = 32,
        kernel_size  = (1,2),
        strides = (1,2),
        data_format = data_format,
        padding = 'same',
        activation='relu',
        input_shape = (2,feat_width,1)))
    model.add(
      tf.keras.layers.Conv2D(
        filters = 10,
        kernel_size  = (2,2),
        data_format = data_format,
        padding = 'same',
        activation = 'relu'))
    model.add(tf.keras.layers.MaxPool2D(pool_size=(2, 1), data_format=data_format))
    model.add(tf.keras.layers.Flatten(data_format=data_format))
    model.add(tf.keras.layers.Dense(units=10, activation='relu'))
    model.add(tf.keras.layers.Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))
    return model

def serving_input_fn():
        """Build the serving inputs."""
        inputs = {}
        inputs[keras_model.input_names[0]] = tf.placeholder(shape=(None, 2,feat_width,1), dtype=tf.float32)

        return tf.estimator.export.build_raw_serving_input_receiver_fn(inputs)

strategy = tf.contrib.distribute.MirroredStrategy(num_gpus=gpu_num)
estimator_config = tf.estimator.RunConfig(
        model_dir='../../model',
        tf_random_seed=0,
        save_summary_steps=256,
        save_checkpoints_steps=10000,
        train_distribute=strategy,
        keep_checkpoint_max=64,
        log_step_count_steps=256)

keras_model = create_cnn_model(feat_width)
keras_model = tf.keras.utils.multi_gpu_model(keras_model, gpus=gpu_num)
keras_model.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
estimator = tf.keras.estimator.model_to_estimator(keras_model=keras_model,config=estimator_config)
tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
```

using
```
 tf.contrib.predictor.from_saved_model(export_dir)
```
to do inference:
```
predictor =  tf.contrib.predictor.from_saved_model(export_dir=export_dir)
feed_tensor = list(predictor.feed_tensors.keys())[0]
fetch_tensor = list(predictor.fetch_tensors.keys())[0]
feat = np.random.rand(2*feat_width)
feat = np.reshape(feat,[ 2, feat_width, 1])
Y = predictor({feed_tensor: [feat]})
r = Y[fetch_tensor]
```
fails for multi gpu with error
```
InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[node sequential_1/flatten/Reshape ]]
	 [[node dense_2_1/concat ]]
```
if I don't use multi gpu the inference code works.

**Comment by alexmil2019** [comment] 2019-06-23 23:58
maybe it is related to this bug https://github.com/keras-team/keras/issues/11806

**Comment by gadagashwini** [comment] 2019-06-24 06:19
@alexmil2019 Please provide us the complete code to reproduce the issue. Thanks!

**Comment by alexmil2019** [comment] 2019-06-24 15:33
I have already attached the complete code for reproducing the bug.

**Comment by maxcrous** [comment] 2019-06-24 16:27
I am running into the same problem. 
I have a custom callback that tries to run a model inference at the end of each epoch for visualization purposes. 
When I run on a single GPU the inference succeeds, when I use multiple gpus I receive:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[{{node replica_0/model_1/reshape_1/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](replica_0/model_1/permute_1/transpose, replica_0/model_1/reshape_1/Reshape/shape)]]
	 [[{{node replica_1/model_1/permute_2/transpose/_1481}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device_incarnation=1, tensor_name="edge_1709_replica_1/model_1/permute_2/transpose", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by gadagashwini** [comment] 2019-06-26 05:24
@alexmil2019 I tried reproducing the issue but It looks some entities are not defined like `strategy`. Please help us reproduce the issue. Thanks!

**Comment by alexmil2019** [comment] 2019-06-27 16:36
I added definition for strategy.

**Comment by anj-s** [comment] 2019-06-29 05:33
@alexmil2019 You don't need to use multi_gpu_model since you are also using MirroredStrategy. Can you try using MirroredStrategy with native Keras APIs to train your model synchronously on multiple GPUs?
Here is a tutorial that demonstrates how you can use tf.distribute APIs: https://www.tensorflow.org/beta/tutorials/distribute/keras

Would this work for your use case?

**Comment by anj-s** [comment] 2019-07-16 18:19
Closing this bug for now. Please reopen if you run into issues when using MirroredStrategy.

**Closed by anj-s** 2019-07-16 18:19 UTC
Labels: TF 1.13, comp:dist-strat, type:bug/performance

**Comment by 1535966643** [comment] 2020-08-02 07:38
我是在bert的模型训练完之后预测时候遇到这个问题，我用的是keras_bert，我是这样解决的
word2vec, segment = tokenizer.encode(sen)
word2vec = np.expand_dims(word2vec, axis=0)
也就是说给生成的index添加一个维度，这一维度在充当batch
