### ISSUE TITLE
libtensorflow.dll leaks icu symbols on Windows

### ISSUE THREAD

**Issue by mika-fischer** [tensorflow/tensorflow#26084] opened 2019-02-25 11:01 UTC
**System information**
- OS Platform and Distribution: Windows 10
- TensorFlow installed from (source or binary): Self-compiled with bazel & from https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.12.0.zip
- TensorFlow version: 1.12.0 & 1.13.0-rc2

**Describe the problem**
`libtensorflow.dll` exports a ton of symbols from icu. They should be private to the dll.

**Any other info / logs**
```
C:\Users\mfischer\Desktop>dumpbin /exports tensorflow-1.12.0.dll
Microsoft (R) COFF/PE Dumper Version 14.16.27027.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file tensorflow-1.12.0.dll

File Type: DLL

  Section contains the following exports for libtensorflow.so

    00000000 characteristics
    5BDBAEF0 time date stamp Fri Nov  2 02:57:04 2018
        0.00 version
           1 ordinal base
        3078 number of functions
        3078 number of names

    ordinal hint RVA      name

          1    0 01841AA0 ??0?$MaybeStackArray@D$0CI@@icu_62@@AEAA@AEBV01@@Z
          2    1 023BC120 ??0?$MaybeStackArray@D$0CI@@icu_62@@QEAA@$$QEAV01@@Z
          3    2 023BC180 ??0?$MaybeStackArray@D$0CI@@icu_62@@QEAA@H@Z
          4    3 023BC200 ??0?$MaybeStackArray@D$0CI@@icu_62@@QEAA@XZ
          5    4 023C5F90 ??0Appendable@icu_62@@QEAA@AEBV01@@Z
          6    5 023C5F90 ??0Appendable@icu_62@@QEAA@XZ
          7    6 0245DC70 ??0BreakIterator@icu_62@@IEAA@AEBV01@@Z
          8    7 0245DCD0 ??0BreakIterator@icu_62@@IEAA@AEBVLocale@1@0@Z
          9    8 0245DD20 ??0BreakIterator@icu_62@@IEAA@XZ
         10    9 02399020 ??0ByteSink@icu_62@@QEAA@XZ
         11    A 02454B40 ??0BytesDictionaryMatcher@icu_62@@QEAA@AEBV01@@Z
         12    B 02454B70 ??0BytesDictionaryMatcher@icu_62@@QEAA@PEBDHPEAUUDataMemory@@@Z
         13    C 023CC750 ??0BytesTrie@icu_62@@AEAA@PEAXPEBX@Z
         14    D 023CC770 ??0BytesTrie@icu_62@@QEAA@AEBV01@@Z
         15    E 023CC7A0 ??0BytesTrie@icu_62@@QEAA@PEBX@Z
         16    F 0245BA10 ??0BytesTrieBuilder@icu_62@@QEAA@AEAW4UErrorCode@@@Z
         17   10 02458DB0 ??0CStr@icu_62@@QEAA@AEBVUnicodeString@1@@Z
         18   11 023D3F10 ??0CacheKeyBase@icu_62@@QEAA@AEBV01@@Z
         19   12 023D3F30 ??0CacheKeyBase@icu_62@@QEAA@XZ
         20   13 02459A80 ??0CanonicalIterator@icu_62@@QEAA@AEBVUnicodeString@1@AEAW4UErrorCode@@@Z
         21   14 02399030 ??0Char16Ptr@icu_62@@QEAA@$$T@Z
         22   15 02399030 ??0Char16Ptr@icu_62@@QEAA@PEAG@Z
         23   16 02399030 ??0Char16Ptr@icu_62@@QEAA@PEA_S@Z
         24   17 02399030 ??0Char16Ptr@icu_62@@QEAA@PEA_W@Z
         25   18 02459090 ??0CharString@icu_62@@QEAA@$$QEAV01@@Z
         26   19 023BC220 ??0CharString@icu_62@@QEAA@AEBV01@AEAW4UErrorCode@@@Z
         27   1A 023BC270 ??0CharString@icu_62@@QEAA@PEBDHAEAW4UErrorCode@@@Z
         28   1B 023BC2C0 ??0CharString@icu_62@@QEAA@VStringPiece@1@AEAW4UErrorCode@@@Z
         29   1C 023BC320 ??0CharString@icu_62@@QEAA@XZ
         30   1D 02459730 ??0CharacterIterator@icu_62@@IEAA@AEBV01@@Z
         31   1E 02459760 ??0CharacterIterator@icu_62@@IEAA@H@Z
         32   1F 02459790 ??0CharacterIterator@icu_62@@IEAA@HH@Z
...
```

**Comment by jvishnuvardhan** [comment] 2019-02-26 20:00
@mika-fischer Could you explain more details on the problem and its context? Thanks!

**Comment by mika-fischer** [comment] 2019-02-27 08:17
I'm not sure what to say. `libtensorflow.dll` exports symbols for applications to use. It should only export the `TF...` symbols. Instead it also exports all of the symbols of its internal(!) dependency libicu. This is almost certainly a mistake.

The status quo creates problems when trying to link `libtensorflow.dll` into an application that already uses libicu because then the icu symbols would be present twice.

The build process needs to be fixed to not export those symbols. Looking at http://userguide.icu-project.org/packaging#TOC-Link-to-ICU-statically all you have to do is most probably define the C preprocessor symbol: `U_STATIC_IMPLEMENTATION`...

**Comment by mrry** [comment] 2019-02-28 17:57
I think @hamatake did something to address this in 7e090f6a5412fd5f22b5b75ca7ae7844c3d025e9, but perhaps the fix didn't completely solve the problem?

**Comment by mika-fischer** [comment] 2019-03-01 11:18
Actually 7e090f6 should fix this issue. But it definitely is not fixed in https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.13.1.zip

Are there nightly master libtensorflow zips that I could check to see if it's fixed in master?

**Comment by mrry** [comment] 2019-03-01 16:35
I'm not sure if we publish nightlies for that build.

@av8ramit I noticed that you made a change internally (209826891) that caches artifacts for a libtensorflow CPU build on Windows, but do you know if these are published anywhere?

**Comment by mika-fischer** [comment] 2019-03-01 17:05
Well, it's easy enough to check: `dumpbin /exports tensorflow.dll` will print all exported symbols.

**Comment by av8ramit** [comment] 2019-03-01 23:31
@mrry that was for the release packages unfortunately.

**Comment by hamatake** [comment] 2019-03-07 22:31
Unfortunately that change was rolled back because it didn't actually fix
the build in question. This dropped off my radar for awhile but it's back
on. I've reproduced the link failure on a windows machine and am working on
a fix.

**Comment by hamatake** [comment] 2019-07-01 18:11
This should be fixed by https://github.com/tensorflow/tensorflow/commit/025aa34d77b0ba1c9035cfa7b3c7f98bcccb1435#diff-76ffb659afb259c45a6303f170a6613a

**Comment by mrry** [comment] 2019-07-01 20:42
Thanks @hamatake!

**Closed by mrry** 2019-07-01 20:42 UTC
Labels: subtype:windows, type:build/install
