### ISSUE TITLE
`TensorArray` objects used as `Dataset.reduce` state lose inferred shapes

### ISSUE THREAD

**Issue by mdanatg** [tensorflow/tensorflow#30685] opened 2019-07-13 18:49 UTC
**System information**
- TensorFlow version (use command below): 2.0
- Python version: 3

**Describe the current behavior**

`TensorArray` objects passed as accumulators to `Dataset.reduce` lose inferred shapes. Subsequent calls to `TensorArray.concat` returns a fully unknown shape.

**Describe the expected behavior**

The element shape of the `TensorArray` should be partially known, consistent with the behavior of an equivalent `tf.while_loop`.

**Code to reproduce the issue**
```
@tf.function
def compute():
    arr = tf.TensorArray(tf.float32, 1, dynamic_size=True)
    def body(i, arr):
        real_logits = tf.random.normal([5, 1])
        arr = arr.write(tf.cast(i, tf.int32), real_logits)
        i += 1
        return i, arr
    def cond(i, arr):
      return i < 10
    _, arr = tf.while_loop(cond, body, (0, arr))

    c = arr.concat()
    tf.print('TensortArray.concat() shape:', c.shape, 'rank:', c.shape.rank)
    return c

@tf.function
def compute_ds():
    arr = tf.TensorArray(tf.float32, 1, dynamic_size=True)
    def body(state, _):
        i, arr = state
        real_logits = tf.random.normal([5, 1])
        arr = arr.write(tf.cast(i, tf.int32), real_logits)
        i += 1
        return i, arr
    en_ds = tf.data.Dataset.range(10).enumerate()
    _, arr = en_ds.reduce((0, arr), body)

    c = arr.concat()
    tf.print('TensortArray.concat() shape:', c.shape, 'rank:', c.shape.rank)
    return c

print('*** With tf.while_loop')
_ = compute()
print()
print('*** With tf.Dataset.reduce')
_ = compute_ds()
```
```
*** With tf.while_loop
TensortArray.concat() shape: TensorShape([None, 1]) rank: 2

*** With tf.Dataset.reduce
TensortArray.concat() shape: TensorShape(None) rank: None
```

**Comment by mdanatg** [comment] 2019-07-13 18:56
@jsimsa could you triage the issue?

**Comment by jsimsa** [comment] 2019-07-22 17:40
@aaudiber could you please take a look?

**Comment by aaudiber** [comment] 2019-07-23 16:45
@mdanatg Thank you for reporting this and for including simple repro instructions!

The issue is with how we use `TensorArraySpec` to convert the `TensorArray` to/from `Tensor` components across the `reduce` boundary. I have a CL out to fix it.

**Comment by aaudiber** [comment] 2019-07-24 17:14
Now that 6cd69820a7ec68363647bf918d312b5d10e0e07a has merged, inferred `TensorArray` shapes will be preserved across all tf.data operations.

**Closed by aaudiber** 2019-07-24 17:14 UTC
Labels: 2.0, comp:data, type:bug
