### ISSUE TITLE
Tensorflow Website not working properly in Firefox

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#37478] opened 2020-03-10 13:35 UTC
## Description of issue (what needs changing):
Tensorflow website UI doesn't seem right when opened in Firefox. I'm not sure if it's happening only in my case or not...

### Request visuals, if applicable
![Screenshot_2020-03-10 tf keras callbacks TensorBoard TensorFlow Core v2 1 0](https://user-images.githubusercontent.com/29497701/76317231-de111500-6301-11ea-8654-03cd0d29eeb9.png)

**Comment by Kriyszig** [comment] 2020-03-10 17:50
This is a result of icons failing to load and being replaced by their `alt` tag. I'm not sure what is causing this in the reported case given TensorFlow logo and Github log being displayed correctly - I'm not able to reproduce this atm on Firefox 71

**Comment by Saduf2019** [comment] 2020-03-11 09:44
@ManishAradwad 
Please refer to the screenshot attached ,I have verified on Firefox version "68.5.0esr (64-bit)" and it displays as expected, could you please check your network and Firefox version due to which you would be facing this issue.
![37478](https://user-images.githubusercontent.com/59822926/76403465-f852fd80-63aa-11ea-870e-98b4151fd4e5.png)

**Comment by ManishAradwad** [comment] 2020-03-11 12:38
I'm using Firefox version 73.0.1 (64-bit), no network issues.

**Comment by ManishAradwad** [comment] 2020-03-11 12:54
It's working fine in private window

![Screenshot_2020-03-11 tf keras callbacks TensorBoard TensorFlow Core v2 1 0](https://user-images.githubusercontent.com/29497701/76418914-7c19e380-63c5-11ea-8ea5-78ee4e4d9655.png)

**Comment by Kriyszig** [comment] 2020-03-11 13:03
Did clearing cookie and cache help?
This seems like a problem with cached files - Firefox believes the image assets are cached but they aren't at the browser is falling back to the text in the alt tag

**Comment by Saduf2019** [comment] 2020-03-12 06:17
@ManishAradwad 
Please clear cache and set the Firefox settings to default settings this should help, is this the case with just tensor-flow website or other websites as well.

**Comment by ManishAradwad** [comment] 2020-03-12 13:03
@Saduf2019 It is now working properly. Thanks for looking into this!
You may close this issue, if it's fine.

**Comment by Saduf2019** [comment] 2020-03-16 09:09
Proceeding to close the issue as its resolved

**Closed by Saduf2019** 2020-03-16 09:09 UTC
Labels: TF 2.1, type:support
