### ISSUE TITLE
model.save() outputs unexpected files in SavedModel directory

### ISSUE THREAD

**Issue by Yu-Hang** [tensorflow/tensorflow#47933] opened 2021-03-19 22:50 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (use command below): '2.5.0-dev20210318'
- Python version: python 3.8
- CUDA/cuDNN version: cuda11.2; cudnn 8.x

**Describe the current behavior**

model.save() outputs an extra "keras_metadata.pb" file.

**Standalone code to reproduce the issue**
I wrote some code to load my maskRCNN model, and save it to a SavedModel.

this [link](https://drive.google.com/drive/folders/1qf3LaEhu16o6s7fu_X-6qf6M-Dg8Zq3W?usp=sharing) includes: 

1. Model weights: "mask_rcnn_nucleus_0040_thick_Pf.h5"
2. My code to load and save the model: "load_SavedModel.py"
3. Source code needed to load the maskRCNN model: Folder "mrcnn"
4. The SavedModel folder, which is the output of my code: "thick_Pf_model"

**Comment by Yu-Hang** [comment] 2021-03-23 02:13
@abattery Can you help me with this one? Sorry to @ you directly, but I don't know why this issue is not assigned.

**Comment by abattery** [comment] 2021-03-23 02:15
Sorry. I am looking at the TFLite product issues only.

**Comment by Yu-Hang** [comment] 2021-03-23 20:26
Can you look at this tensorflow lite [issue](https://github.com/tensorflow/tensorflow/issues/48025#issue-839067869)? @abattery

**Comment by Yu-Hang** [comment] 2021-03-24 21:42
@k-w-w Hello, are you investigating this issue?

**Comment by jvishnuvardhan** [comment] 2021-03-31 23:25
@Yu-Hang Yes, `keras_metadata.pb` is saved and is intended behavior. [Here](https://colab.research.google.com/gist/jvishnuvardhan/adacb23fc2ec9ba647a3e74089d1864e/untitled.ipynb) is a gist for your reference.

This is a recent addition to the functionality of `model.save`. If you try to save a model load a model without `keras_metadata.pb`, then it will throw a warning as shown below 

`
#### load saved model without `keras_metadata.pb`
loaded_model = tf.keras.models.load_model('MyModel')`

A warning will be thrown as shown below

`WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.`

So, `keras_metadata.pb` is intended and not an unexpected output. Thanks!

**Comment by Yu-Hang** [comment] 2021-04-01 16:52
@jvishnuvardhan I see. Thanks. Quick follow up questions:

1. Does the nightly version still require generating an intermediate SavedModel before converting to a .tflite model?
2. Are support for EfficientDet models included in the nightly version?

**Comment by jvishnuvardhan** [comment] 2021-04-01 20:32
@Yu-Hang I am not sure whether I understand your question completely.

Ans 

(1) You don't need to save (`model.save`) and load (`load_model`) the model for tflite conversion. You can train a keras model and pass that model to `tf-lite-converter`. If you ran a  large model in cluster or high end GPU, then you can save the model, load the model and use `tf.lite.TFLiteConverter.from_keras_model()` to convert the model.

(2) I think "Yes" but I am not an expert  about this model. 

Please close the issue. For further questions, please open a new issue with a standalone code to reproduce the issue. Thanks!

**Closed** 2021-04-01 20:55 UTC
Labels: TF 2.4, comp:keras, stat:awaiting response, type:bug
