### ISSUE TITLE
Unable to convert keras_model.h5 to .tflite

### ISSUE THREAD

**Issue by nitheeshmuthuraj** [tensorflow/tensorflow#21175] opened 2018-07-26 21:02 UTC
I enter this command : tflite_convert \ --output_file=/tmp/foo.tflite \ --keras_model_file=C:/Users/n.muthuraj/Desktop/cnn/02/dataset/ashik.h5

The Output is : Traceback (most recent call last):

 File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper return importlib.import_module(mname) File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\importlib_init_.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 986, in _gcd_import File "", line 969, in _find_and_load File "", line 958, in _find_and_load_unlocked File "", line 666, in _load_unlocked File "", line 577, in module_from_spec File "", line 906, in create_module File "", line 222, in _call_with_frames_removed ImportError: DLL load failed: The specified module could not be found. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in _pywrap_tensorflow_internal = swig_import_helper() File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper return importlib.import_module('pywrap_tensorflow_internal') File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\importlib_init.py", line 126, in import_module return _bootstrap.gcd_import(name[level:], package, level) ImportError: No module named 'pywrap_tensorflow_internal' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\runpy.py", line 184, in run_module_as_main "main", mod_spec) File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\runpy.py", line 85, in run_code exec(code, run_globals) File "C:\Users\n.muthuraj\AppData\Local\Programs\Python\Python35\Scripts\tflite_convert.exe_main.py", line 5, in File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow_init.py", line 22, in from tensorflow.python import pywrap_tensorflow # pylint: disable=unused-import File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python_init.py", line 49, in from tensorflow.python import pywrap_tensorflow File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in raise ImportError(msg) ImportError: Traceback (most recent call last): File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper return importlib.import_module(mname) File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\importlib_init.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 986, in _gcd_import File "", line 969, in _find_and_load File "", line 958, in _find_and_load_unlocked File "", line 666, in _load_unlocked File "", line 577, in module_from_spec File "", line 906, in create_module File "", line 222, in _call_with_frames_removed ImportError: DLL load failed: The specified module could not be found. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in from tensorflow.python.pywrap_tensorflow_internal import * File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in _pywrap_tensorflow_internal = swig_import_helper() File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper return importlib.import_module('pywrap_tensorflow_internal') File "c:\users\n.muthuraj\appdata\local\programs\python\python35\lib\importlib_init.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: No module named '_pywrap_tensorflow_internal' Failed to load the native TensorFlow runtime. See https://www.tensorflow.org/install/install_sources#common_installation_problems for some common reasons and solutions. Include the entire stack trace above this error message when asking for help.

I am not sure where i am going wrong

**Comment by tensorflowbutler** [comment] 2018-07-27 06:42
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by nitheeshmuthuraj** [comment] 2018-07-27 20:44
OS Platform and Distribution- win 10 
TensorFlow installed from -pip install & updated to 
TensorFlow version - 1.9.0
Bazel version -NA
CUDA/cuDNN version-NA
GPU model and memory - NA
Exact command to reproduce :python keras_to_tensorflow.py -input_model_file ashik.h5 -input_fld C:\Users\n.muthuraj\Desktop\cnn\02\dataset -output_node_prefix 'dense_6'
Mobile device- NA

**Comment by nitheeshmuthuraj** [comment] 2018-08-01 15:11
I was able to resolve it as i found out later that  toco is not supported on windows !!
I had another issue while i tried converting the model on linux system. I ran theano in the backend which was accepting the image data in (number , channel , height , width)- NCHW was the input for the model and the core was dumped while conversion. On the other hand when i ran Tensorflow in backend (number , height,width, channel)-NHWC format the model was converted to tflite format .
SO while conversion make sure that you are
1) running tensorflow in backend by:
from keras import backend as K
K.set_image_dim_ordering('tf'),
2) install tf_nightly
Hope it helps !!

**Comment by aselle** [comment] 2018-08-08 18:29
@nitheeshmuthuraj  Glad you got it to work. Thanks for reporting back solutions; we really appreciate help the community. Also, we're close to supporting windows, and we'll update this when it's fully working.

**Comment by jdduke** [comment] 2018-08-09 18:53
Duplicate of #20804.

**Comment by jdduke** [comment] 2018-08-09 18:55
Duplicate of #21085

**Comment by jdduke** [comment] 2018-08-15 17:17
The toco conversion utility should now run on Windows. It hasn't been put through exhaustive testing, though, due to some limitations with our testing infrastructure, so feel free to file bugs for any issues you encounter.

**Closed by jdduke** 2018-08-15 17:17 UTC
Labels: comp:lite
