### ISSUE TITLE
Cannot open https://www.tensorflow.org in Safari

### ISSUE THREAD

**Issue by feiyin01** [tensorflow/tensorflow#12498] opened 2017-08-22 16:33 UTC
As subject says, always error msg saying "Safari cannot open the page, because it cannot open make the secure connection with the server". Has anybody encountered the problem and can you share your experience how to fix ?
Opening the website from Firefox is OK.
System: Mac 10.12.6.

**Comment by quaeler** [comment] 2017-08-23 17:49
https://**www**.tensorflow.org/ opens without problem for me on Safari (same os version as you report)

https://tensorflow.org/ presents a warning panel which is due to the certificate having expired ( https://github.com/tensorflow/tensorflow/issues/12496 )

**Comment by quaeler** [comment] 2017-08-24 14:51
I thought maybe it was because i'd turned on the Developer menu, but turning that back off still displays the certificate warning for me.

Oddly, Firefox warns me too - ( on https://tensorflow.org )

That all being written, if you are having problems with https://www.tensorflow.org and not the www-less version, then i'm at a total loss as its certificate is valid. :- /

**Comment by srowen** [comment] 2017-08-25 08:50
The HTTPS cert is expired. Chrome says:

This server could not prove that it is tensorflow.org; its security certificate expired 57 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Friday, August 25, 2017. Does that look right? If not, you should correct your system's clock and then refresh this page.

**Comment by feiyin01** [comment] 2017-08-25 09:17
My system clock setting is right as I double-confirmed.

I thought there should be a warning dialogue for me but there isn't, it simply says the secure connection cannot be established :(

And, in my Safari the problem is valid for both www.tensorflow.org and tensorflow.org...

**Comment by ali01** [comment] 2017-08-28 04:03
This appears to be fixed now. Please reopen if it is still a problem.

**Comment by ali01** [comment] 2017-08-28 04:06
This is a duplicate of issue [12496](https://github.com/tensorflow/tensorflow/issues/12496). Closing here.

**Closed by ali01** 2017-08-28 04:06 UTC
