### ISSUE TITLE
TensorFlow grpc+gdr runtime error

### ISSUE THREAD

**Issue by ooyanglinoo** [tensorflow/tensorflow#15541] opened 2017-12-21 04:10 UTC
I have built tensorflow with gdr support following the [instruction](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/gdr)，but when I run tf_cnn_benchmarks I got a runtime error.
![image](https://user-images.githubusercontent.com/3050438/34240351-43330544-e648-11e7-9543-aaea5abadc48.png)

**Comment by tensorflowbutler** [comment] 2017-12-22 07:26
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by ooyanglinoo** [comment] 2017-12-22 07:43
thank you for the kindly reply, actually I was running tf-cnn-benchmark downloaded [there](https://github.com/tensorflow/benchmarks). nv_peer_memory has been installed.
My OS Platform and Distribution is Centos 7.1
My tensorflow is installed from master banch which version is 1.4.0
Bazel version is 0.7.0
CUDA/cuDNN are 8.0 and 6.0
GPU mode is K40c GPU and memory is 11439MiB

I also try grpc+verbs mode and it runs fine.

**Comment by byronyi** [comment] 2017-12-25 06:51
Hi @ooyanglinoo, it seems to be a gRPC error. Do you meet the same error running in pure `grpc` runtime?

**Comment by byronyi** [comment] 2017-12-25 07:27
Please attach the detailed logs with environment variables:
```
export TF_CPP_MIN_LOG_LEVEL=0
export TF_CPP_MIN_VLOG_LEVEL=2
export GRPC_POLL_STRATEGY=poll  # Try this and see if you could reproduce
```

**Comment by tensorflowbutler** [comment] 2018-01-08 19:03
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-01-23 22:56
The original poster has replied to this issue after the stat:awaiting response label was applied.

**Comment by tensorflowbutler** [comment] 2018-02-13 14:24
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-03 08:04
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-18 16:06
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-02 12:29
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by byronyi** [comment] 2018-04-17 13:28
@skye Shall we close this issue for now? It appears that I cannot reproducce the issue. 

@ooyanglinoo please let me know if you’ve met further problems. Thanks!

**Comment by skye** [comment] 2018-04-17 17:14
Sure, go ahead and close if this can't be repro'd anymore. Thanks.

**Comment by byronyi** [comment] 2018-04-18 07:46
@skye it seems only the owner or a member in TF team could close the issue :(

**Comment by skye** [comment] 2018-04-18 14:32
Didn't realize that, thanks!

**Closed by skye** 2018-04-18 14:32 UTC
Labels: stat:awaiting response

**Comment by aru132** [comment] 2018-08-26 15:15
I reproduced this.
Can anyone reopen this issue? I need help.

OS Platform and Distribution: CentOS 7.5
TensorFlow installed from: Download the source from this repo.
TensorFlow version: 1.10.0
Bazel version: 0.16.1
CUDA/cuDNN version: 9.2/7.2
GPU model and memory: NVIDIA P2000
Exact command to reproduce: run tf-cnn-benchmark. grpc mode and grpc+verbs mode seem to be fine.

I attach the log with the environmental variables (https://github.com/tensorflow/tensorflow/issues/15541?_pjax=%23js-repo-pjax-container#issuecomment-353841661).

[tf-log.txt](https://github.com/tensorflow/tensorflow/files/2321619/tf-log.txt)

**Comment by byronyi** [comment] 2018-08-26 23:17
I will take a look into this.

**Comment by aru132** [comment] 2018-08-29 04:53
Probably, I found the root cause of the error.
In my cluster, each node is connected with IB and ethernet.
When the program is passed ethernet IP addr as host addresses, the connection is failed as this issue.
(Despite the IB connection is linked up.)
When the program is passed IPoIB addr, the error is disappeared!
However, I wonder why the error is caused when not using IPoIB.

If my hypothesis is true, I suggest grpc+gdr mode (and grpc+verbs mode?) to display some warning when the connection does not use IPoIB.

**Comment by byronyi** [comment] 2018-08-29 07:01
@aru132 Thanks for your comments. Indeed, the GDR plugin is developed under RDMA over Converged Ethernet (RoCE) environment, and it assumes the IP address user passes to the GRPC server could also be used for RDMA.

Standalone IB without IPoIB fail to satisfy this condition. Btw, it would be much appreciated if you could contribute to the docs of GDR, as I currently have no access to any IB cluster.
