### ISSUE TITLE
extract_image_patches zeros out data for large images

### ISSUE THREAD

**Issue by shirriff** [tensorflow/tensorflow#5773] opened 2016-11-22 03:50 UTC
I'm reading a large image (7128x5097 pixels) and generating patches with extract_image_patches. Depending on the patch size, some or all of the resulting image is zeroed out. Is there a limit on tensor size that it hits?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
nothing relevant

### Environment info
Operating System: macOS Sierra 10.12.1

Installed version of CUDA and cuDNN: none

A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl
The output from python -c "import tensorflow; print(tensorflow.__version__)".
0.11.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

The following code generates a random image, scales it up by a factor of 5, pulls a single pixel out of each patch, and writes an image with the result.

Expected behavior: an image of random pixels.
Observed behavior: for small images it works. But for the 5097x7129 image, N=3 works, N=5 gives a completely blank image, and N=7 is blank after the first 998 rows. (It's kind of strange that 7 works better than 5.)

    from __future__ import absolute_import
    from __future__ import print_function
    import tensorflow as tf
    N = 5 # Can try other numbers
    def main(_):
      img = tf.random_uniform([1, 5097, 7129, 3], minval=0, maxval=255, dtype=tf.int32)
      img = tf.cast(img, tf.uint8)
      patches = tf.extract_image_patches(img, [1, N, N, 1], [1, N, N, 1],
        [1, 1, 1, 1], "SAME")
      data = patches[0, :, :, 0:3]
    
      f = open('/tmp/img.png', 'w')
      init_op = tf.initialize_all_variables()
      with tf.Session() as sess:
        sess.run(init_op)
        f.write(tf.image.encode_png(data).eval())
      f.close()
    
    if __name__ == "__main__":
      tf.app.run()

### What other attempted solutions have you tried?
This is a simplified version of a larger image learning system, and I've cut it down to the problematic code. I've checked the values to make sure the problem is in extract_image_patches and not image_encode_png. The problem seems to happen if the tensor is big, so there's probably some size limit somewhere.

**Comment by prb12** [comment] 2016-11-22 21:24
@gpapan Could you please take a look at this?

**Comment by skye** [comment] 2017-06-16 17:35
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by mzur** [comment] 2017-08-29 07:45
Can confirm that this issue still exists.

**Environment info**

System 1: Ubuntu 16.04.3, CUDA 8.0.61, cuDNN 4.0.7, TF v1.1.0
System 2: `tensorflow/tensorflow:latest-gpu` Docker container (with TF v1.3.0)
System 3: Ubuntu 16.04.3, TF v1.2.0 on CPU

**Minimal reproducible example**

```python
import tensorflow as tf

N = 13
img = tf.cast(tf.random_uniform([1, 5097, 7129, 1], minval=0, maxval=255, dtype=tf.int32), tf.uint8)
patches = tf.extract_image_patches(img, ksizes=[1, N, N, 1], strides=[1, 1, 1, 1], rates=[1, 1, 1, 1], padding='SAME')
encode_image = tf.image.encode_png(patches[0, :, :, 0:1])
write_file = tf.write_file('output.png', encode_image)
tf.Session().run(write_file)
```

Output:

![output](https://user-images.githubusercontent.com/2457311/29810001-811d25aa-8c9e-11e7-9afd-9a4403d5c785.png)


As @shirriff said the result should be an image with random pixel values but the result varies depending on the patch size `N` and the image size. @skye @gpapan Please reopen.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:40
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by sid-kap** [comment] 2018-01-11 21:24
@mzur isn't this expected behavior with padding type "SAME"? As I understand it, if you want no zeroed-out cells, you should set padding = "VALID".

**Comment by mzur** [comment] 2018-01-12 09:57
@sid-kap `SAME` padding may cause zeros at the borders (as described [here](https://stackoverflow.com/a/39371113/1796523)). But this issue is about zeroing out, i.e. the image is not "finished".

Let me illustrate this with a [large picture](https://commons.wikimedia.org/wiki/File:101_Raven.jpg) (scaled down to 4876x7000 pixels). I run this code, which reads the picture, splits it into patches, then merges the patches back together and writes it to a file:

```python
import tensorflow as tf

N = 13
img = [tf.image.decode_jpeg(tf.read_file('101_Raven.jpg'), 1)]
patches = tf.extract_image_patches(img, ksizes=[1, N, N, 1], strides=[1, 1, 1, 1], rates=[1, 1, 1, 1], padding='SAME')
encode_image = tf.image.encode_jpeg(patches[0, :, :, 0:1])
write_file = tf.write_file('output.jpg', encode_image)
tf.Session().run(write_file)
```

This results in the following image (note the black border due to `SAME` padding):

![output](https://user-images.githubusercontent.com/2457311/34869128-42ce5172-f786-11e7-9c05-622a706832b4.jpg)

The bottom part of the image is missing. If I increase the stride to `[1, 2, 2, 1]`, I get the [correct result](https://user-images.githubusercontent.com/2457311/34869317-cee28070-f786-11e7-8d8c-085e6d0b0657.jpg). The behavior is the same for `VALID` padding.

**Comment by sid-kap** [comment] 2018-01-12 16:56
@mzur I guess I misunderstood, apologies!

**Comment by tensorflowbutler** [comment] 2018-02-06 07:43
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by vrv** [comment] 2018-02-07 23:59
@gpapan Any help?  This bug is pretty old.  Do you think this is a bug in the EigenTensor implementation of extract_image_patches?

My guess is that there's some indexing overflow happening.

**Comment by vrv** [comment] 2018-02-08 00:02
Actually, it looks like this was already fixed in https://github.com/tensorflow/tensorflow/commit/d75d5529d569d8f72cb215d3696db1feb1d9f033#diff-42af759a17331c263b5c57f04f130aa5 possibly, so it may no longer be valid.

Given the information in the commit and the related internal bug report that this fixes, I'm going to assume this is now fixed.  Please reopen if this is not true and you are running a recent version of TF.

**Closed by vrv** 2018-02-08 00:02 UTC
Labels: stat:awaiting tensorflower

**Comment by mzur** [comment] 2018-02-11 10:23
I've tried the code above with TF 1.5.0 and it's working correctly now. Thanks!
