### ISSUE TITLE
FFT gradient over variables fails

### ISSUE THREAD

**Issue by el3ment** [tensorflow/tensorflow#3239] opened 2016-07-08 21:06 UTC
The following code fails with an error `ValueError: Shapes (3, 32, 28, 28) and () are not compatible`

```
import tensorflow as tf

filters = 32
width = 28
height = 28
channels = 3

x = tf.placeholder(tf.float32, shape=[None, height, width, channels])
w = tf.Variable(tf.truncated_normal([channels, filters, height, width], stddev=0.1))
b = tf.Variable(tf.constant(0.1, shape=[32]))

w_ifft = tf.real(tf.batch_ifft2d(tf.complex(w, 0.0)))
w_ifft_transpose = tf.transpose(w_ifft, [2, 3, 0, 1])

conv = tf.nn.conv2d(x, w_ifft_transpose, strides=[1, 1, 1, 1], padding='SAME')
output = tf.nn.bias_add(conv, b)

print tf.gradients(output, w)
```

Performing backprop of an FFT over a variable is important for reproducing the work found [https://hips.seas.harvard.edu/files/rippel-spectral-nips-2015.pdf](https://hips.seas.harvard.edu/files/rippel-spectral-nips-2015.pdf)

**Comment by aselle** [comment] 2016-07-09 00:53
Correct me if I'm wrong @vrv, but batch_ifft2d does not have a gradient on the cpu. I assume you are using a cpu build. If you want to do gradients of fft's you need to use a gpu. (assigning to @petewarden  as internal bug 29447493 is assigned to him)

**Comment by el3ment** [comment] 2016-07-09 06:07
Perhaps I am not doing it right -- but calling `tf.device(":gpu0"):` resulted in the same error

**Comment by el3ment** [comment] 2016-07-22 23:19
It did not work -- however, after diving into the code a bit, I realized the issue is in the tf.complex() call, changing the code from

`w_ifft = tf.real(tf.batch_ifft2d(tf.complex(w, 0.0)))`

to 

`w_ifft = tf.real(tf.batch_ifft2d(tf.complex(w, w * 0.0)))`

Results in a gradient and no error.

**Comment by michaelisard** [comment] 2016-07-25 22:41
@rryan is this intended behavior?

**Comment by rryan** [comment] 2016-07-26 01:40
Nope, I'll take a look.

**Comment by rryan** [comment] 2016-08-31 21:39
Hm, I think I misread this bug initially -- it's intended behavior that for `tf.complex(x, y)`, x and y must have the same shape. Instead of `w * 0.0` you could do `tf.zeros_like(w)` to get a zero tensor of the same shape/dtype as w.

**Closed** 2016-12-02 00:35 UTC
