### ISSUE TITLE
float16 constant readout doesn't match with it's original numpy array

### ISSUE THREAD

**Issue by youchangkim** [tensorflow/tensorflow#53260] opened 2021-12-01 00:23 UTC
I tried to create float16 constant from numpy array and read it back, but the returned array doesn't match with it's original numpy array. This seems to be happening only at M1 Macs.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.3.1 on M1 Mac mini
- TensorFlow installed from (source or binary): Binary (tensorflow-macos)
- TensorFlow version (use command below): unknown 2.5.0
- Python version: 3.8.12

**Standalone code to reproduce the issue**

```python
import numpy as np
import tensorflow.compat.v1 as tf

np.random.seed(0)
with tf.Graph().as_default(), tf.Session() as sess:
    x = np.random.sample([1, 1, 1, 1, 768]).astype(np.float16)
    y = tf.constant(x)

    x = np.ones([1, 1, 384, 1, 1], dtype=np.float16)
    y = tf.constant(x, name='97f6762f328ca2b7cceaf2851e0c01a6')
    z = y * 3

    t = sess.graph.get_tensor_by_name('97f6762f328ca2b7cceaf2851e0c01a6:0')
    v = sess.run(t, feed_dict={})

    #print(x.squeeze())
    #print(v.squeeze())
    assert np.array_equiv(x, v)
```

**Describe the current behavior**

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    assert np.array_equiv(x, v)
AssertionError
```

**Describe the expected behavior**

Two arrays should be equal.

**Comment by sanatmpa1** [comment] 2021-12-01 05:42
@youchangkim,

It is working fine when checked with TF `2.7.0` on colab. Here's the [gist](https://colab.sandbox.google.com/gist/sanatmpa1/f1630709d0bdf3db437a4fcd232be6f1/53260.ipynb). Since its not a bug from TF end and you also mentioned that the issue is with M1, Can you try posting your question in this [tf-metal developer forum](https://developer.apple.com/forums/tags/tensorflow-metal) of Apple? Thanks!

**Comment by youchangkim** [comment] 2022-03-09 01:25
@penpornk In the code below, it works fine when I comment out `@tf.function`. So it seems to be a problem with graph execution.

```python
import numpy as np
import tensorflow as tf

np.random.seed(0)

@tf.function
def my_func():
    print('tracing')

    x = np.ones([1, 1, 384, 1, 1], dtype=np.float16)
    y = tf.constant(x, name='97f6762f328ca2b7cceaf2851e0c01a6')
    z = y * 3

    return z, y

z, y = my_func()

print(y.numpy().squeeze())
assert np.array_equiv(y, np.ones(y.shape))
```

**Comment by everton1984** [comment] 2022-03-09 14:25
> @cfRod @everton1984 Have you seen similar issues before? Could you please help try this code on other Arm machines as well? I wonder if this is specific to M1.
> 
> @youchangkim Are these lines necessary in producing the error? (We don't have M1s so it's hard for us to test.)
> 
> ```
>     x = np.random.sample([1, 1, 1, 1, 768]).astype(np.float16)
>     y = tf.constant(x)
> ```
> 
> Also, do you see the same error in eager mode?

@penpornk It ran just fine on aarch64 with 2.6.0. I don't have a 2.5.0 binary easily available but I could try compiling my own if you think it's necessary.

**Comment by cfRod** [comment] 2022-03-09 15:46
Same outcome as @everton1984 on the aarch64 machine I have.

**Comment by penpornk** [comment] 2022-03-09 23:36
@everton1984 @cfRod Thank you very much for the help! I think 2.6.0 is fine. :)

@youchangkim Thank you for the quick reply! 
What is the output of `print(y.numpy().squeeze())`?
Could you please help check if the issue still persist with the latest TF (2.8.0)? (Just in case we are lucky.)

Can we try if removing each of the following still produces the error?
1. Remove `name='97f6762f328ca2b7cceaf2851e0c01a6'`
2. Removing both `print` statements.
3. Removing `np.random.seed(0)` or setting it to something else.

**Comment by youchangkim** [comment] 2022-03-10 00:07
@penpornk I was only able to try 2.7.0 since 2.8.0 requires macOS 12.3 but I'm currently using 11.3. I can try 2.8.0 after I upgrade my OS. Interestingly TF 2.5.0 and 2.7.0 produces different outputs but both are wrong.

TF 2.5.0
```
tracing
2022-03-09 15:56:44.089426: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
[6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08 6.e-08
 6.e-08 6.e-08 6.e-08 6.e-08]
Traceback (most recent call last):
  File "test3.py", line 19, in <module>
    assert np.array_equiv(y, np.ones(y.shape))
AssertionError
```

TF 2.7.0
```
tracing
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Traceback (most recent call last):
  File "test3.py", line 19, in <module>
    assert np.array_equiv(y, np.ones(y.shape))
AssertionError
```

Things you asked:

> 1. Remove name='97f6762f328ca2b7cceaf2851e0c01a6'

Fail both 2.5.0 and 2.7.0

> 2. Removing both print statements.

Fail both 2.5.0 and 2.7.0

> 3. Removing np.random.seed(0) or setting it to something else.

Fail both 2.5.0 and 2.7.0, and setting seed to 1 doesn't help

Applying 1, 2, and 3 at the same time also fails.
```python
import numpy as np
import tensorflow as tf

@tf.function
def my_func():
    x = np.ones([1, 1, 384, 1, 1], dtype=np.float16)
    y = tf.constant(x)
    z = y * 3

    return z, y

z, y = my_func()

assert np.array_equiv(y, np.ones(y.shape))
```

**Comment by penpornk** [comment] 2022-05-18 23:41
Quick update:
Worked with @youchangkim offline and narrowed down to grappler optimization passes. It seems the GraphDef representation of the const all-one fp16 tensor was changed from
```
I0331 20:22:16.951792 1635096 convert_attributes.cc:287] GraphDef attr value: tensor {
  dtype: DT_HALF
  tensor_shape {
    dim {
      size: 1
    }
    dim {
      size: 1
    }
    dim {
      size: 384
    }
    dim {
      size: 1
    }
    dim {
      size: 1
    }
  }
  half_val: 15360
}
```
to
```
I0331 20:22:16.951792 1635096 convert_attributes.cc:287] GraphDef attr value: tensor {
  dtype: DT_HALF
  tensor_shape {
    dim {
      size: 1
    }
    dim {
      size: 1
    }
    dim {
      size: 384
    }
    dim {
      size: 1
    }
    dim {
      size: 1
    }
  }
  half_val: 1
}
```
after the tfg_optimizer pass.

**Comment by mohantym** [comment] 2022-09-12 11:10
@youchangkim ! @penpornk !
I could replicate this in my mac M1 machine . It is not replicating in [Colab ](https://colab.sandbox.google.com/drive/1c5OMqus-QBVvaETWzMelBi2LFz90GNLy?resourcekey=0-ph0Yv_zdI-SHm9i2Mwcwyg#scrollTo=eu6lvroGVYAu)though.

**Comment by kulinseth** [comment] 2022-10-20 13:53
@penpornk any update on this ?
the FP16 correctness issue seems to be affecting lot of TF core tests when run on Apple Silicon. They all pass on x86 machine like:
```
    //tensorflow/python/math_grad_test_cpu:

    XdivyTest.testNonZeroValuesGrad 
    XdivyTest.testZeroYGrad 
    testNegOneYGrad 
    Xlog1pyTest.testNonZeroValuesGrad 
    XlogyTest.testNonZeroValuesGrad
    XlogyTest.testZeroYGrad
```

Similarly for mlir to Graph def tests its failing:

```
//tensorflow/core/ir/importexport/tests/roundtrip:test21.pbtxt.test
//tensorflow/core/ir/importexport/tests/roundtrip:negative_zero_constant.pbtxt.test 
//tensorflow/core/ir/importexport/tests/mlir_to_graphdef:negative_zero_constant.mlir.test
```
This makes sense as the GraphDef representation changed for Half changed after tfg pass.  
What I didn't follow is why its specific to arm64?

cc @yarri-oss , @nitins17 and @learning-to-play

**Comment by penpornk** [comment] 2022-12-12 15:58
@youchangkim @kulinseth Sorry for the delay! We have synced offline but I'll post the update here too.

This is where it went wrong:
https://github.com/tensorflow/tensorflow/blob/be3be938f3c349daf0b0ef4b717fc2fc7010a974/tensorflow/core/ir/importexport/convert_tensor.cc#L348
MLIR's `getSplatValue` is supposed to return 15360, but it returned 1. 
Here is a quick patch to work around this issue for now:
```
diff --git a/tensorflow/core/ir/importexport/convert_tensor.cc b/tensorflow/core/ir/importexport/convert_tensor.cc
index 2c6def949a1..a6aacc7a827 100644
--- a/tensorflow/core/ir/importexport/convert_tensor.cc
+++ b/tensorflow/core/ir/importexport/convert_tensor.cc
@@ -342,7 +342,14 @@ void ConvertFloatElementsAttr(const DenseElementsAttr attr,
 void ConvertHalfElementsAttr(const DenseElementsAttr attr,
                              RepeatedField<int>* output) {
   if (attr.isSplat()) {
+    // TODO(penporn): Find why Splat doesn't work with Half on MacOS.
+    // (Getting value = 1 instead of 15360 for a Half value of 1.)
+#if defined(__APPLE__) && defined(__MACH__)
+    auto value = *reinterpret_cast<const tensorflow::uint16*>(attr.getRawData().data());
+#else
     auto value = attr.getSplatValue<Eigen::half>().x;
+#endif  // __APPLE__ && __MACH__
+
     if (value != Eigen::half(0) || std::signbit(static_cast<float>(value)))
       output->Add(value);
   } else {
```

**Comment by penpornk** [comment] 2022-12-15 22:56
@cantonios just submitted a proper fix here: https://github.com/tensorflow/tensorflow/commit/d4ea582e285a940856e996d69252ed8dc6dbc3a0. 
Closing the issue now. Please feel free to reopen if it still isn't resolved on your side. :)

**Closed** 2022-12-15 22:57 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:ops, TF 2.9
