### ISSUE TITLE
bug of keras.metrics under @tf.function

### ISSUE THREAD

**Issue by tianran** [tensorflow/tensorflow#36511] opened 2020-02-06 13:14 UTC
**System information**
- TensorFlow installed from source
- TensorFlow version: v2.1.0-0-ge5bf8de410 2.1.0
- Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

The tf.keras.metrics.Mean() class is not performing correctly under @tf.function annotation. It looks like some control_dependencies issues and I suspect similar bugs for other metrics.

**Code to reproduce the issue**
The results of `func1()`, `func2()`, and `func3()` should be all the same (a series of numbers starting from 4.5) in the following. However, `func2()` produces different result (a series of numbers starting from 0).
```
import tensorflow as tf

eval_dataset = tf.data.Dataset.range(10)
metric = tf.keras.metrics.Mean(name='mean', dtype=tf.float32)

def func1():
    for step in range(100):
        if tf.equal(step % 5, 0):
            for y in eval_dataset:
                x = tf.cast(y + step, tf.float32)
                metric(x)
            print(metric.result().numpy())
            metric.reset_states()

func1()

@tf.function
def func2():
    for step in range(100):
        if tf.equal(step % 5, 0):
            for y in eval_dataset:
                x = tf.cast(y + step, tf.float32)
                metric(x)
            tf.print(metric.result())
            metric.reset_states()

func2()

@tf.function
def func3():
    for step in range(100):
        if tf.equal(step % 5, 0):
            total = metric.total.assign(0.0)
            count = metric.count.assign(0)
            for y in eval_dataset:
                x = tf.cast(y + step, tf.float32)
                with tf.control_dependencies([total, count]):
                    total = metric.total.assign_add(x)
                    count = metric.count.assign_add(1)
            result = tf.math.divide_no_nan(total, count)
            tf.print(result)

func3()
```

**Comment by tianran** [comment] 2020-02-06 22:43
This is a similar issue:
https://github.com/tensorflow/tensorflow/issues/31458

**Comment by gadagashwini** [comment] 2020-02-07 11:28
Was able to reproduce the issue with Tf 2.1.
Please find the gist [here](https://colab.research.google.com/gist/gadagashwini/ae1d5953733646431d7797d8c70b9a36/untitled380.ipynb). Thanks!

**Comment by gadagashwini** [comment] 2020-02-07 11:53
@tianran, This issue is fixed in latest tf-nightly version. 
Please take a look at [gist](https://colab.research.google.com/gist/gadagashwini/b88fcb61527e52da8feeb7ee50a64174/untitled381.ipynb). Thanks

**Comment by ymodak** [comment] 2020-02-11 19:20
Closing since its fixed. Thanks!

**Closed by ymodak** 2020-02-11 19:20 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:bug
