### ISSUE TITLE
tf2.0  dataset disable_eager_execution

### ISSUE THREAD

**Issue by yanmxiang** [tensorflow/tensorflow#55359] opened 2022-03-24 08:56 UTC
tf is 2.4.0
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
with tf.device('/cpu'):
    dataset = tf.data.Dataset.from_tensor_slices([1,3,4,5,6,7,8])

@tf.function(autograph=False)
def iter_funs(ds):
    iterator = iter(dataset)
    return iterator.get_next()

with tf.compat.v1.InteractiveSession().as_default():
    with tf.device('/cpu'):
        xx = iter_funs(dataset)
        print(xx.eval())
        print(xx.eval())

the output is always 1 ,xx not iterator.
so how can i do to iterator the data

**Comment by gadagashwini** [comment] 2022-03-25 06:45
@yanmxiang,
When we call function `iter_funs()`, it returns always first element in the list. When we print iterator.get_next() inside the function it shows values of the datalist. 

```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

dataset = tf.data.Dataset.from_tensor_slices([1,3,4,5,6,7,8])

@tf.function
def iter_funs(dataset):
  iterator = iter(dataset)
  print(iterator.get_next())
  return iterator.get_next()

with tf.compat.v1.InteractiveSession().as_default():
  xx = iter_funs(dataset)
  
print(xx.eval())

```
**Output**
```
Tensor("IteratorGetNext:0", shape=(), dtype=int32)
3
```
Print the 3rd element
```
import tensorflow as tf
tf.compat.v1.disable_eager_execution()

dataset = tf.data.Dataset.from_tensor_slices([1,3,4,5,6,7,8])

@tf.function
def iter_funs(dataset):
  iterator = iter(dataset)
  print(iterator.get_next())
  print(iterator.get_next())
  return iterator.get_next()


with tf.compat.v1.InteractiveSession().as_default():
  xx = iter_funs(dataset)
  
print(xx.eval())
```
**Output**
```
Tensor("IteratorGetNext:0", shape=(), dtype=int32)
Tensor("IteratorGetNext_1:0", shape=(), dtype=int32)
4
```

**Comment by yanmxiang** [comment] 2022-03-25 07:58
thank you very much answer my question.
another question is where to place the training process.
placed in&nbsp;&nbsp;iter_funs is error
placed outside of  iter_funs couldn't iterator
import tensorflow as tf tf.compat.v1.disable_eager_execution() dataset = tf.data.Dataset.from_tensor_slices([1,3,4,5,6,7,8]) @tf.function def iter_funs(dataset):   iterator = iter(dataset)   print(iterator.get_next())   print(iterator.get_next())   return iterator.get_next() with tf.compat.v1.InteractiveSession().as_default():   xx = iter_funs(dataset)  sess.run(model(xx))
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorflow/tensorflow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tensorflow/tensorflow] tf2.0  dataset disable_eager_execution (Issue #55359)





 
@yanmxiang,
 When we call function iter_funs(), it returns always first element in the list. When we print iterator.get_next() inside the function it shows values of the datalist.
 import tensorflow as tf tf.compat.v1.disable_eager_execution() dataset = tf.data.Dataset.from_tensor_slices([1,3,4,5,6,7,8]) @tf.function def iter_funs(dataset):   iterator = iter(dataset)   print(iterator.get_next())   return iterator.get_next() with tf.compat.v1.InteractiveSession().as_default():   xx = iter_funs(dataset)    print(xx.eval())  
Output
 Tensor("IteratorGetNext:0", shape=(), dtype=int32) 3  
Print the 3rd element
 import tensorflow as tf tf.compat.v1.disable_eager_execution() dataset = tf.data.Dataset.from_tensor_slices([1,3,4,5,6,7,8]) @tf.function def iter_funs(dataset):   iterator = iter(dataset)   print(iterator.get_next())   print(iterator.get_next())   return iterator.get_next() with tf.compat.v1.InteractiveSession().as_default():   xx = iter_funs(dataset)    print(xx.eval())  
Output
 Tensor("IteratorGetNext:0", shape=(), dtype=int32) Tensor("IteratorGetNext_1:0", shape=(), dtype=int32) 4

**Comment by gadagashwini** [comment] 2022-03-25 10:06
@yanmxiang, Glad that it answered your question. Will close this issue. 
Could you open new issue by filling the template , Since the title of the issue is resolved. Thanks!

**Closed** 2022-03-25 13:43 UTC
Labels: type:others, comp:ops
