### ISSUE TITLE
Cannot find libdevice.10.bc under /usr/local/cuda-8.0

### ISSUE THREAD

**Issue by roman-orekhov** [tensorflow/tensorflow#17801] opened 2018-03-17 22:35 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 LTS (GNU/Linux 4.4.38-rt49-tegra aarch64)
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.7.0-rc0, r1.7, master
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0-6ubuntu1~16.04.9
- **CUDA/cuDNN version**: 8.0/6
- **GPU model and memory**: name: GP106 major: 6 minor: 1 totalMemory: 3.75GiB (as reported by some previous version of Tensorflow on the other part of the same Drive PX2)
- **Exact command to reproduce**:
`git checkout v1.7.0-rc0`
`./configure`
`bazel build //tensorflow:libtensorflow_cc.so`

### Describe the problem
Same problem for all branches listed under **TensorFlow version**.
Build fails immediately with
`Cuda Configuration Error: Cannot find libdevice.10.bc under /usr/local/cuda-8.0`
It's strange because I explicitly answered 8.0 versions and libdevice.10.bc exists only in 9.0 AFAIK.

### Source code / logs
[error.log](https://github.com/tensorflow/tensorflow/files/1822159/error.log)

[configure.log](https://github.com/tensorflow/tensorflow/files/1822155/configure.log)

[tf_configure.txt](https://github.com/tensorflow/tensorflow/files/1822157/tf_configure.txt)

**Comment by PumayHui** [comment] 2018-03-20 09:14
I met the same problem, hope someone can help me. Thanks so much!
Bazel version (if compiling from source): 0.10.0

**Comment by HwangIkHwan** [comment] 2018-03-20 15:28
I met the same problem, finally, i solved it. 
we make a file link libdevice.compute_50.10.bc to libdevice.10.bc.
It solved the problem.
tip:if you want change name easily, you should use this code:sudo nautilus

**Comment by kkktch** [comment] 2018-03-21 15:03
sorry,I don't understand.
Shall we make a new file under /usr/local/cuda-8.0 named libdevice.10.bc
Or we move the libdevice.compute_50.10.bc under /usr/local/cuda&cuda-8.0/nvvm/libdevice and renamed libdevice.10.bc

**Comment by kkktch** [comment] 2018-03-21 15:08
sorry,I don't understand.
Shall we make a new file under /usr/local/cuda-8.0 named libdevice.10.bc
Or we move the libdevice.compute_50.10.bc under /usr/local/cuda&cuda-8.0/nvvm/libdevice to /usr/local/cuda-8.0 and rename it  libdevice.10.bc

**Comment by HwangIkHwan** [comment] 2018-03-21 15:23
In my case, I solved, just change the file name(libdevice.compute_50.10.bc--->libdevice.10.bc) in /usr/local/cuda&cuda-8.0/nvvm/libdevice.
I use gtx 1070.

**Comment by PumayHui** [comment] 2018-03-22 00:56
@HwangIkHwan 
I tried your suggestion, but still occurred the same error: 
Cuda Configuration Error: Cannot find libdevice.10.bc under /usr/local/cuda-8.0
INFO: Elapsed time: 0.383s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

**Comment by PumayHui** [comment] 2018-03-22 00:59
@HwangIkHwan 
The problem resolved, thank you so much!

**Comment by PumayHui** [comment] 2018-03-22 01:00
@HwangIkHwan yeah, it is successful, thank you so much!

**Comment by kkktch** [comment] 2018-03-22 15:21
@HwangIkHwan  it works, thanks!

**Comment by jart** [comment] 2018-03-25 00:07
Sounds like good documentation was created here on how to workaround this peculiar problem. Thanks everyone in the community for supporting.

**Comment by UndeadBlow** [comment] 2018-03-25 10:52
@jart That's not "peculiar problem". Current configurator will not work on any device with Cuda 8.0 and Tensorflow 1.7.

**Comment by jart** [comment] 2018-03-26 21:27
Please note the [install documentation](https://www.tensorflow.org/install/install_linux) says CUDA 9 is required. If you have CUDA 8, please try upgrading CUDA, or downgrading TF.

**Comment by roman-orekhov** [comment] 2018-03-26 23:11
@jart Sorry, I missed that 8.0 support is dropped since v1.6. Also some of TF current sources still contain code to deal with CUDA 8.0.

**Comment by maurice-g** [comment] 2018-03-27 10:55
@roman-orekhov @JarnoRFB doesn't the CUDA 9 requirement only apply to the precompiled versions (Docker, wheel etc.)? In the documentation about building it from source it mentions Cuda > 7.0 as hard requirement: https://www.tensorflow.org/install/install_sources#optional_install_tensorflow_for_gpu_prerequisites

**Comment by gangyahaidao** [comment] 2018-03-28 03:47
thanks very much
mv libdevice.compute_50.10.bc--->libdevice.10.bc
help me a lot!

**Comment by UndeadBlow** [comment] 2018-03-30 12:29
@jart 
In "install from source" documentation (https://www.tensorflow.org/install/install_sources) stated Cuda >= 7.0. You speak about precomiled versions, we speak about build from source.

**Comment by ziruizhuang** [comment] 2018-04-03 02:26
Same problem here and I believe this is a bug.
Either state CUDA>=9.0 requirement in docs or fix this issue.

**Comment by lcerman** [comment] 2018-04-28 09:43
Also hit this problem....

**Comment by ngc92** [comment] 2018-05-02 11:12
I ran into the same problem trying to compile 1.8 with CUDA 8

**Comment by JDeanThomas** [comment] 2018-05-03 09:40
Also just ran into the same problem trying to compile 1.8 with CUDA 8.0

**Comment by jart** [comment] 2018-05-03 23:27
It does appear to be the case that we document CUDA 7+ for source builds and CUDA 9+ for binary releases, per links above. Reopening and assigning to @gunan who has greater familiarity with CUDA support in TensorFlow.

**Comment by gunan** [comment] 2018-05-04 03:47
@reedwm @chsigg may know more about this.

**Comment by pjox** [comment] 2018-05-15 17:50
Is there a workaround without using root privileges? I am working on a cluster and I cannot move these files.

**Comment by han-qiu** [comment] 2018-05-16 04:44
has anyone successfully build the lastest version of tensorflow with **cuda8** and may share the python package file?

**Comment by han-qiu** [comment] 2018-05-16 04:45
has anyone successfully build the lastest version of tensorflow with **cuda8** and may share the python package file?

**Comment by han-qiu** [comment] 2018-05-16 04:45
has anyone successfully build the lastest version of tensorflow with **cuda8** and may share the python package file?

**Comment by JDeanThomas** [comment] 2018-05-17 00:18
@han-qiu, I did (cuDNN 6, on MacOS 10.11.6 using CLT 8.2), but then I realized it was this may be the last release to support CUDA 8 so I upgraded to 10.13 and CUDA 9.1 (cuDNN 7.0.5, CLT 8.3.2) so I don't have the package anymore. Likely wouldn't work anyway unless it was compiled using -march=core2

I played around with using LLVM (non-Apple Clang) and kinda wanna circle back to making that work.

**Comment by reedwm** [comment] 2018-05-17 21:16
I do not know what the issue is. But using `git bisect`, I found the issue is caused by c79c9512486daa119d3cda9c00bb36acb3933a5b.

@pwnall, can you fix this?

**Comment by pjox** [comment] 2018-05-18 11:29
@dominikzietlow Thank you, I think it is in [here](https://github.com/tensorflow/tensorflow/blob/851c28951b7345f303f4ec1d6490e3fadaa0a40e/third_party/toolchains/gpus/cuda/BUILD) line 1199. I'll have to test it.

**Comment by dominikzietlow** [comment] 2018-05-18 11:40
@pjox That is not the file I meant, I was referring to the file
``third_party/gpus/cuda_configure.bzl
in line 722 (this might depend on the settings used during the ./configure call)

**Comment by pwnall** [comment] 2018-05-19 04:17
@reedwm Sorry, I haven't tested on CUDA 8.0.

I can try to find some time to look at this late next week. Sorry for the high lag, I am currently adjusting to an expanded role at work.

**Comment by pjox** [comment] 2018-05-22 09:48
@dominikzietlow Thanks! your solution worked perfectly. :smile:

**Comment by cyberwillis** [comment] 2018-06-02 03:17
My solution was:
```
cd /usr/local/cuda-8.0/nvvm/libdevice
ln -s libdevice.compute_50.10.bc libdevice.10.bc
```

**Comment by struCoder** [comment] 2018-06-14 06:00
@HwangIkHwan 
Thanks.

**Comment by tensorflowbutler** [comment] 2018-06-28 12:36
Nagging Assignee @gunan: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by pwnall** [comment] 2018-07-09 22:43
A change equivalent to https://github.com/pwnall/tensorflow/commit/6a15fb400af3dd013284e9f6150256797e742afe has been committed to the internal repository. This issue should be fixed soon.

**Closed** 2018-07-09 22:44 UTC
