### ISSUE TITLE
TF2-gpu: _SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, 

### ISSUE THREAD

**Issue by ChuangLee** [tensorflow/tensorflow#31182] opened 2019-07-31 03:19 UTC
System information

OS Platform and Distribution: Linux Ubuntu 16.04
TensorFlow installed from binary:
TensorFlow version (use command below):tf-nightly-gpu-2.0-preview 2.0.0.dev20190729
Python version: 3.6.4
CUDA/cuDNN version: CUDA-10.0/ Cudnn7.6.1
GPU model and memory: 3 Titan XP 

**Describe the current behavior**
RNN Masking of length cause crash
**Code to reproduce the issue**
```
    mask = tf.sequence_mask(length, dtype=tf.bool)
    mask = K.expand_dims(mask)
    lstm = layers.LSTM(num_hidden[i], return_sequences=True,
                          return_state=True)
    inputs, _, _ = lstm(inputs, mask=mask)
```

**Other info / logs**
```

W0731 09:54:25.986333 139687813953280 network.py:896] Layer signature_rnn_0 was passed non-serializable keyword arguments: {'mask': <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=bool>}. They will not be included in the serialized model (and thus will be missing at deserialization time).
W0731 09:54:25.987287 139687813953280 network.py:896] Layer signature_rnn_1 was passed non-serializable keyword arguments: {'mask': <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=bool>}. They will not be included in the serialized model (and thus will be missing at deserialization time).
W0731 09:54:25.987648 139687813953280 network.py:896] Layer signature_rnn_2 was passed non-serializable keyword arguments: {'mask': <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=bool>}. They will not be included in the serialized model (and thus will be missing at deserialization time).
W0731 09:54:35.721126 139687813953280 deprecation.py:323] From /usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/optimizer_v2/optimizer_v2.py:468: BaseResourceVariable.constraint (from tensorflow.python.ops.resource_variable_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Apply a constraint manually following the optimizer update step.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 61, in quick_execute
    num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: ExpandDims:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 110, in <module>
    main()
  File "run.py", line 77, in main
    train_model.fit(train_dataset, callbacks=callbacks)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 724, in fit
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 681, in fit
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 298, in model_iteration
    batch_outs = f(actual_inputs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/distribute/distributed_training_utils.py", line 836, in execution_function
    return [out.numpy() for out in distributed_function(input_fn)]
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 451, in __call__
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1765, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1089, in _filtered_call
    self.captured_inputs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1167, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 471, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 75, in quick_execute
    "tensors, but found {}".format(keras_symbolic_tensors))
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=bool>]

```

**Comment by anush-o** [comment] 2019-08-01 05:16
@ChuangLee ,
In order to expedite the trouble-shooting process, please provide complete code snippet to reproduce the issue reported here.Thanks!

**Comment by oanush** [comment] 2019-08-08 05:59
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by oanush** 2019-08-08 05:59 UTC
Labels: 2.0, comp:keras, stat:awaiting response, type:support
