### ISSUE TITLE
Here is a list of operators for which you will need custom implementations: RandomUniform.

### ISSUE THREAD

**Issue by yuanlida** [tensorflow/tensorflow#37008] opened 2020-02-24 07:14 UTC
**System information**
- OS Platform and Distribution (MacOS 10.15.3 (19D76)):
- TensorFlow installed from ( binary):
- TensorFlow version (1.15.2)

**Provide the text output from tflite_convert**

```
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ARG_MAX, BIDIRECTIONAL_SEQUENCE_LSTM, CAST, FULLY_CONNECTED, GATHER, GREATER_EQUAL, MUL, RESHAPE. Here is a list of operators for which you will need custom implementations: RandomUniform.
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

**Comment by gadagashwini** [comment] 2020-02-24 08:35
@yuanlida, Looks duplicate of [#37009](https://github.com/tensorflow/tensorflow/issues/37009). Can we close this issue. Will track resolution there. Thanks

**Comment by gadagashwini** [comment] 2020-02-28 11:27
@yuanlida, You may try converting your model using Select TensorFlow Ops
Please take a look at similar [#35605(comment)](https://github.com/tensorflow/tensorflow/issues/35605#issuecomment-571737987) issue comment. Thanks!

**Comment by gadagashwini** [comment] 2020-03-06 08:43
@yuanlida, Were you able to resolve this?

**Comment by gadagashwini** [comment] 2020-03-13 09:56
Closing this issue since the resolution is provided. 
Please feel free to open if still issue persists. Thanks

**Closed by gadagashwini** 2020-03-13 09:56 UTC
Labels: TF 1.15, comp:lite, stat:awaiting response, type:support
