### ISSUE TITLE
errors meet after django  call several times saver.restore

### ISSUE THREAD

**Issue by lufengguang** [tensorflow/tensorflow#8645] opened 2017-03-23 03:24 UTC
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key wd1/Adam_7 not found in checkpoint
	 [[Node: save_3/RestoreV2_133 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_3/Const_0, save_3/RestoreV2_133/tensor_names, save_3/RestoreV2_133/shape_and_slices)]]

W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc4/Adam_9 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc3/Adam_11 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc3/Adam_10 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc2/Adam_9 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc2/Adam_8 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc2/Adam_7 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc2/Adam_6 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc5/Adam_10 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc5/Adam_11 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc2/Adam_11 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc2/Adam_10 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc1/Adam_9 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc1/Adam_8 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc1/Adam_7 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc1/Adam_6 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc1/Adam_11 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc1/Adam_10 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key out/Adam_9 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key out/Adam_8 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key out/Adam_7 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key out/Adam_6 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc5/Adam_6 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc5/Adam_7 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc5/Adam_8 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key wc5/Adam_9 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key out/Adam_11 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key out/Adam_10 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key beta2_power_5 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key beta2_power_4 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key beta2_power_3 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key beta1_power_5 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key beta1_power_4 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key beta1_power_3 not found in checkpoint

**Comment by drpngx** [comment] 2017-03-23 05:05
I am not sure it's a bug in TensorFlow. I think you're trying to restore from a checkpoing from different models. Do you have a simpler repro? Without django? (It could be concurrent access to the web server?)

**Comment by lufengguang** [comment] 2017-03-23 05:27
I'm sure the models  are the same .Otherwise the front  several times would not work . I send the repro to your email. Thanks~

**Comment by drpngx** [comment] 2017-03-24 00:27
Not sure if you have my email, but you can just use pastebin if it's public.

**Comment by aselle** [comment] 2017-03-24 16:53
@lufengguang, we cannot generally give help over private channels. You should make a reproducible example that can be posted publicly, please. That way other people than @drpngx, can help.

**Comment by girving** [comment] 2017-06-16 20:49
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by girving** 2017-06-16 20:49 UTC
Labels: stat:awaiting response, type:bug/performance

**Comment by sunyaping1991** [comment] 2017-07-06 09:40
@lufengguang I have same problem。How did you solve it?
