### ISSUE TITLE
TF 2.0.0-rc0 + TFP 0.7 broken combo: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key

### ISSUE THREAD

**Issue by kristofgiber** [tensorflow/tensorflow#32139] opened 2019-09-01 16:58 UTC
Error occurs:
tf-gpu 2.0.0-rc0 with tfp 0.7

Code to reproduce:

```
import tensorflow_probability as tfp
tfp.distributions.MultivariateNormalDiag([0.], [1.]).sample()
```

Error returned:

> 
> Traceback (most recent call last):
>   File "/home/pycharm_project/VAE/save_issue_reproduction.py", line 3, in <module>
>     tfp.distributions.MultivariateNormalDiag([0.], [1.]).sample()
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/distributions/distribution.py", line 840, in sample
>     return self._call_sample_n(sample_shape, seed, name, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/distributions/transformed_distribution.py", line 391, in _call_sample_n
>     y = self.bijector.forward(x, **bijector_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/bijectors/bijector.py", line 933, in forward
>     return self._call_forward(x, name, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/bijectors/bijector.py", line 904, in _call_forward
>     mapping = self._lookup(x=x, kwargs=kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/bijectors/bijector.py", line 1343, in _lookup
>     mapping = self._from_x[x].get(subkey, mapping).merge(x=x)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/bijectors/bijector.py", line 151, in __getitem__
>     return super(WeakKeyDefaultDict, self).__getitem__(weak_key)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_probability/python/bijectors/bijector.py", line 181, in __hash__
>     return hash(x)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/ops.py", line 713, in __hash__
>     raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
> TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.

**Comment by ablanch5** [comment] 2019-09-02 18:24
I'm getting the same error using the same versions of tensorflow and tensorflow probability. Here is my code trying to run MCMC which I adapted from "Bayesian Methods For Hackcers"

```
yards_data = array([ 7.,  7.,  4., 12.,  5., 17.], dtype=float32)

def joint_log_prob(yards_data, sigma):
    rv_mu = tfd.Normal(loc=M, scale=S)
    rv_sigma = tfd.Uniform(low=0.0, high=20.0)
    
    mu_sample = mu.sample()
    yards = tfd.Normal(loc=mu_sample,scale=sigma)
    #compute log prob
    return (
        yards.log_prob(yards_data)
        + rv_sigma.log_prob(sigma)
        + rv_mu.log_prob(mu_sample)
    )

def unnormalized_log_posterior(sigma):
    return joint_log_prob(yards_data, sigma)

initial_chain_state = [tf.cast(s, tf.float32) * tf.ones([], dtype=tf.float32, name="init_sigma")]
unconstraining_bijectors = [tfp.bijectors.Exp()]
step_size = tf.Variable(0.05, name='step_size', trainable=False)

# Sample from the chain.
[
    sigma_samples,
], kernel_results = tfp.mcmc.sample_chain(
    num_results=100000,
    num_burnin_steps=10000,
    current_state=initial_chain_state,
    kernel=tfp.mcmc.TransformedTransitionKernel(
        inner_kernel=tfp.mcmc.HamiltonianMonteCarlo(
            target_log_prob_fn=unnormalized_log_posterior,
            num_leapfrog_steps=2,
            step_size=step_size,
            step_size_update_fn=tfp.mcmc.make_simple_step_size_update_policy(1),
            state_gradients_are_stopped=True),
        bijector=unconstraining_bijectors))
```

This creates error:
```
c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\mcmc\internal\util.py:494: UserWarning: `step_size` is not a `tf.Tensor`, Python number, or Numpy array. If this parameter is mutable (e.g., a `tf.Variable`), then the behavior implied by `store_parameters_in_results` will silently change on 2019-08-01. Please consult the docstring for `store_parameters_in_results` details and use `store_parameters_in_results=True` to silence this warning.
  param_name))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-b8bfc92e8c79> in <module>
     13             step_size_update_fn=tfp.mcmc.make_simple_step_size_update_policy(1),
     14             state_gradients_are_stopped=True),
---> 15         bijector=unconstraining_bijectors))

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\mcmc\sample.py in sample_chain(num_results, current_state, previous_kernel_results, kernel, num_burnin_steps, num_steps_between_results, trace_fn, return_final_kernel_results, parallel_iterations, name)
    324         current_state)
    325     if previous_kernel_results is None:
--> 326       previous_kernel_results = kernel.bootstrap_results(current_state)
    327 
    328     if trace_fn is None:

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\mcmc\transformed_kernel.py in bootstrap_results(self, init_state, transformed_init_state)
    328         init_state_parts = (init_state if mcmc_util.is_list_like(init_state)
    329                             else [init_state])
--> 330         transformed_init_state_parts = self._inverse_transform(init_state_parts)
    331         transformed_init_state = (
    332             transformed_init_state_parts if mcmc_util.is_list_like(init_state)

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\mcmc\transformed_kernel.py in fn(state_parts)
     71   def fn(state_parts):
     72     return [b.inverse(sp)
---> 73             for b, sp in zip(bijector, state_parts)]
     74   return fn
     75 

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\mcmc\transformed_kernel.py in <listcomp>(.0)
     71   def fn(state_parts):
     72     return [b.inverse(sp)
---> 73             for b, sp in zip(bijector, state_parts)]
     74   return fn
     75 

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\bijectors\bijector.py in inverse(self, y, name, **kwargs)
    975       NotImplementedError: if `_inverse` is not implemented.
    976     """
--> 977     return self._call_inverse(y, name, **kwargs)
    978 
    979   def _compute_inverse_log_det_jacobian_with_caching(

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\bijectors\bijector.py in _call_inverse(self, y, name, **kwargs)
    944       if not self._is_injective:  # No caching for non-injective
    945         return self._inverse(y, **kwargs)
--> 946       mapping = self._lookup(y=y, kwargs=kwargs)
    947       if mapping.x is not None:
    948         return mapping.x

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\bijectors\bijector.py in _lookup(self, x, y, kwargs)
   1344     if y is not None:
   1345       # We removed y at caching time. Add it back if we lookup successfully.
-> 1346       mapping = self._from_y[y].get(subkey, mapping).merge(y=y)
   1347     return mapping
   1348 

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\bijectors\bijector.py in __getitem__(self, key)
    149   def __getitem__(self, key):
    150     weak_key = HashableWeakRef(key, lambda w: self.pop(w, None))
--> 151     return super(WeakKeyDefaultDict, self).__getitem__(weak_key)
    152 
    153   # This is the "DefaultDict" part.

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_probability\python\bijectors\bijector.py in __hash__(self)
    179     x = self()
    180     if not isinstance(x, np.ndarray):
--> 181       return hash(x)
    182     # Note: The following logic can never be reached by the public API because
    183     # the bijector base class always calls `convert_to_tensor` before accessing

c:\users\ablan\miniconda3\envs\tf2.0rc\lib\site-packages\tensorflow_core\python\framework\ops.py in __hash__(self)
    711     if (Tensor._USE_EQUALITY and executing_eagerly_outside_functions() and
    712         (g is None or g._building_function)):  # pylint: disable=protected-access
--> 713       raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
    714                       "Instead, use tensor.experimental_ref() as the key.")
    715     else:

TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.


```

**Comment by davmre** [comment] 2019-09-03 18:25
Thanks for the report! This is due to a change in TF's Tensor equality semantics that occurred between the TFP 0.7 release and the TF 2.0.0-rc0 prerelease. You can fix it by installing TFP 0.8-rc0 (`pip install tensorflow_probability==0.8.0rc0 --user --upgrade`), which should include the necessary updates.

**Comment by davmre** [comment] 2019-09-03 18:25
Closing for now; feel free to reopen if the problem still occurs.

**Closed by davmre** 2019-09-03 18:25 UTC
Labels: TF 2.0-rc0, comp:ops, type:bug

**Comment by TechMaster** [comment] 2019-09-17 08:43
**After upgrade** 
```
pip install tensorflow_probability==0.8.0rc0 --user --upgrade
```

**Error still happens**
```
File "/Users/techmaster/LearnAI/venv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 713, in __hash__
    raise TypeError("Tensor is unhashable if Tensor equality is enabled. "
TypeError: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key.
```

**My environment:**
- MacOSX High Sierra
- TensorFlow version 2.0.0-rc1
- tf-estimator-nightly  1.14.0.dev2019080601
- Keras                 2.2.5
- Keras-Applications    1.0.8
- Keras-Preprocessing   1.1.0

**Piece of code causes error**
```python
intermediate_layer_model = Model(inputs=self.model.input,
                                         outputs=self.model.get_layer("embedding").output)
        intermediate_output = intermediate_layer_model.predict(encoded_texts)
        return intermediate_output
```

**Comment by rajeeja** [comment] 2019-10-17 09:08
still doesn't work after installing rc0

**Comment by HaseebLUMS** [comment] 2019-10-24 18:39
tensorflow_probability==0.8.0rc0  did not fix the error. Any other solution?

**Comment by surrutiaquir** [comment] 2019-10-27 17:37
Same issue and the suggested solution doesn't work

**Comment by NabinAdhikari674** [comment] 2019-10-28 08:50
Same issue here. Doesn't work even after installing "ensorflow_probability==0.8.0rc0"

**Comment by igarag** [comment] 2019-10-28 09:13
Hi.

Same issue. As @NabinAdhikari674 says, `tensorflow_probability` doesn't work. In my case the problem comes from trying to migrate from TF 1.14 to TF 2.0 with Keras 2.3.1 (if it helps).

**Comment by huyinyx** [comment] 2019-10-29 06:57
pip install tf-hub-nightly
it works

**Comment by kirosc** [comment] 2019-11-01 15:43
> pip install tf-hub-nightly
> it works

That didn't work for me

**Comment by igarag** [comment] 2019-11-01 20:12
Me neither. :-(

**Comment by tomalbrecht** [comment] 2019-11-05 11:54
Me neither

**Comment by talipini** [comment] 2019-11-14 11:04
I am getting this error with tf2.0 migration on tf-nightly build.

**Comment by diptosarkar** [comment] 2019-11-16 13:49
I am also getting the same error when I am  trying to use the variable init_wt:
```

init_wt = tf.keras.initializers.TruncatedNormal(stddev=weight_init_std, mean=weight_init_mean, seed=100)

init_wt 

<tensorflow.python.ops.init_ops_v2.TruncatedNormal at 0x1b7d6519f08>

```

I think the problem is caused by a mismatch between Keras and Tensorflow libraries as mentioned in [this Stackoverflow question](https://stackoverflow.com/questions/58778872/typeerror-tensor-is-unhashable-if-tensor-equality-is-enabled-instead-use-tens). The solution proposed works for me. But, it means downgrading TF version and not being able to use GPU.

**Comment by jramkiss** [comment] 2019-11-28 16:51
I'ma having this problem as well

**Comment by aldasmallthings** [comment] 2019-12-11 14:45
ditto! :(

**Comment by jvdillon** [comment] 2019-12-11 20:11
(Not sure how I got assigned this; in fact I didnt even notice. Reassigned to alextp for further triage.)

**Comment by alextp** [comment] 2019-12-11 20:51
If the problem still occurs for you please open a new issue with the steps you need to reproduce the problem. As far as we can tell the TFP issue here has been fixed.
