### ISSUE TITLE
eager execution not working with placeholders

### ISSUE THREAD

**Issue by kirk86** [tensorflow/tensorflow#18165] opened 2018-04-02 00:49 UTC
------------
### System information
- **Have I written custom code: Yes**:
- **OS Platform and Distribution (Linux Ubuntu 16.04)**:
- **TensorFlow installed from (binary)**:
- **TensorFlow version (1.7)**:
- **Python version (3.6)**: 
- **CUDA/cuDNN version (9.0/7.0.)**:
- **GPU model and memory (1080 Ti)**:

### Describe the problem
I get the following error when I use eager execution on a simple graph with a couple of convolutional layers.
```
tf.placeholder() is not compatible with eager execution
```

Does that mean that eager execution is not working with placeholders. That would be useful to have since if have older code constructed using graphs and sessions we won't be able to utilize eager execution for debugging purposes.

**Comment by asimshankar** [comment] 2018-04-02 02:49
Placeholders don't quite make sense with eager execution since placeholders are meant to be "fed" in a call to `Session.run`, as part of the `feed_dict` argument. Since eager execution means immediate (and not deferred execution), there is no notion of a session or a placeholder.

Consider the following program with graph execution:

```python
import tensorflow as tf

def my_model(x):
  return tf.square(x) # you'd likely have something more sophisticated

x = tf.placeholder(tf.float32)
y = my_model(x)

with tf.Session() as sess:
  print(sess.run(y, feed_dict={x: 3.0})
```

With eager execution enabled, you can use `my_model` (and step through it, debug it etc.) with much less boilerplate and no placeholders / sessions:

```python
import tensorflow as tf

tf.enable_eager_execution()

def my_model(x):
  return tf.square(x)  # you'd likely have something more sophisticated

print(my_model(3.0)) 
```

Hope that helps.
More information in the [Getting Started](https://www.tensorflow.org/get_started/eager) and [Programmer's Guide](https://www.tensorflow.org/programmers_guide/eager) sections on eager execution.

I'm going to close this issue out since we'd like to keep GitHub issues focused on bugs or feature requests. If I have misunderstood what you're asking, then feel free to re-open with more details of what you're trying to do with placeholders and what precisely the bug/feature request is.

Thanks.

**Closed by asimshankar** 2018-04-02 02:49 UTC

**Comment by vaibhavsingh007** [comment] 2018-12-09 19:51
Issue was resolved after installing the nightly build, for me. 
` pip3 install --upgrade tf-nightly-gpu --user`

**Comment by aseem-hegshetye** [comment] 2019-02-20 02:51
> user

Did you mean eager exec works with placeholders after installing nightly-gpu?

**Comment by yselivonchyk** [comment] 2019-03-24 19:57
I am facing the same issue. I am converting my code to TF 2.0. After getting everything to the coherent state running the code I am getting 
`tf.placeholder() is not compatible with eager execution`
Which sounds a little funky, since I was not trying any eager execution at all. I am backwards and still trying to run in TF with a session.

So, the problem is 2-fold. First, the error message does not indicate an error. It states some fact, that might or might not be relevant to the situation. It seems to implicate that someone is trying the eager execution.

Second of all, it seems to be relevant to the migration script. The script was glad to convert my TF1.12 code to TF2.0 and now TF2.0 is not happy with the result.

**Comment by asimshankar** [comment] 2019-03-24 20:09
@yselivonchyk : You may want to file a new issue about this, particularly since this seems more about an issue with what the upgrade script should do rather than the fact that `eager execution doesn't work with placeholders`.

**Comment by qmeeus** [comment] 2019-03-29 11:53
Sorry to reopen this but any idea what is the right way to use the argument `target_tensors` of `tf.keras.models.Model.compile` ?

I used to have something like this:
```
autoencoder.compile(
    ...
    target_tensors=[
        tf.placeholder('float32', [None, self.input_size]),
        tf.placeholder('int32', [None, ])],
        ...)
...
autoencoder.fit(X_train, [X_train, y_train], ...)
```
The documentation says: If instead you would like to use your own target tensors, you can specify:
- a single tensor: does not apply
- a list of tensors: 
```
ValueError: ('Error when checking model target: expected no data, but got:', [<tf.Tensor: id=181, shape=(32, 1625), dtype=float32, numpy=array([[...]], dtype=float32)>, <tf.Tensor: id=182, shape=(32,), dtype=int32, numpy=array([...], dtype=int32)>])
```
- dict mapping output names to target tensors: 
```AttributeError: Tensor.name is meaningless when eager execution is enabled.```

So, what is the correct way to handle this?

Thank you

**Comment by Mainak431** [comment] 2019-04-04 20:44
@yselivonchyk  Tensorflow 2.0 by default uses Eager-Execution. Hence Placeholders are not getting executed. What is the point of even keeping a placeholder while no support for it is there in Tensorflow 2.0. 
How will we devise the unknown dimension or Dimension(None) from now on? Any answers ?

**Comment by sks4world** [comment] 2019-12-06 03:10
Thank you Mainak. The solution worked for me. 
tf.compat.v1.disable_eager_execution()

**Comment by bytetick** [comment] 2020-02-03 20:14
Finally found the answer. It worked for me also.  I understand why too. Thanks Mainak431

**Comment by yanxg** [comment] 2020-08-14 02:24
You could see the reason why it has a problem https://www.tensorflow.org/guide/eager there: since tensorflow 2.0 has the eager execution feature. If you still want to use the graphical feature in Tensorflow, you could always disable the eager execution based on suggestions from Mainak431

**Comment by wnagesh** [comment] 2020-08-26 11:56
`import tensorflow as tf
x = tf.placeholder(tf.float32)
y = my_model(x)`

instead of disabling the eager execution add 
`tf.executing_eagerly()` 

and remove on the `placeholder()` like

`import tensorflow as tf
tf.executing_eagerly()
y = my_model(x)`



hope works for you..:)
