### ISSUE TITLE
Error:Execution failed for task ':buildNativeBazel'. > A problem occurred starting process 'command '/usr/local/bin/bazel''

### ISSUE THREAD

**Issue by azemZejnil** [tensorflow/tensorflow#20274] opened 2018-06-25 12:27 UTC
When I download whole repository and try to run android application:
tensorflow-master/tensorflow/examples/android
I get the error from the title.

This error happens because of this code from build.gradle :
// set to 'bazel', 'cmake', 'makefile', 'none'
def nativeBuildSystem = 'bazel'

When I try to change to some other build system, I get different errors. For example, when I put to 'none', I get the camera problem, but I would like to solve this 'bazel' problem, because it looks like it is default build system.

I use Ubuntu 16.04,  
I have TensorFlow version 1.5.0
Bazel version: Build label: 0.13.0,
CUDA version: Cuda compilation tools, release 7.5, V7.5.17

GPU model and memory
Intel Corporation 4 Series Chipset Integrated Graphics Controller (rev 03) (prog-if 00 [VGA Controller])
Subsystem: Dell 4 Series Chipset Integrated Graphics Controller
4 GB

Thank you in advance

**Comment by tensorflowbutler** [comment] 2018-06-26 07:12
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
CUDA/cuDNN version
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-07-11 12:52
It has been 15 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-07-26 19:15
It has been 31 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by azemZejnil** [comment] 2018-07-26 19:39
No, somehow I managed to run the scripts I wasn't able at first.
feel free to close this.
Sorry and thank you

**Comment by angersson** [comment] 2018-08-01 21:15
It looks like this issue has been resolved, so I'm closing it. Thanks!

**Closed by angersson** 2018-08-01 21:15 UTC
