### ISSUE TITLE
dilated convolution leads to incorrect graph optimization

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#26797] opened 2019-03-17 06:43 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):archlinux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:n/a
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):b'v1.13.1-0-g6612da8' 1.13.1
- Python version:3.7
- Bazel version (if compiling from source):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version: 10.0 / 7.5.0
- GPU model and memory: GTX 1080Ti

The following code:
```python
import numpy as np
import tensorflow as tf

x = tf.placeholder(name='input', shape=[1, 1024, None, None], dtype=tf.float32)

hidden = tf.layers.Conv2D(256, 3, activation=tf.nn.relu, dilation_rate=2, data_format='channels_first', padding='SAME')(x)

label_logits = tf.layers.Conv2D(15, 1, data_format='channels_first', padding='SAME')(hidden)
shp1 = tf.shape(label_logits)

label_logits = tf.squeeze(label_logits, 0)
shp2 = tf.shape(label_logits)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
with sess.as_default():
    v = np.random.rand(1, 1024, 200, 19)
    print(sess.run([shp1, shp2], feed_dict={x: v}))
```
runs on GPU, and prints:
```
[array([  1,  15, 200,  19], dtype=int32), array([ 15, 256, 256], dtype=int32)]
```

The shape of tensor was changed by a `squeeze`. This is terribly wrong.

The issue was originally reported at https://github.com/tensorpack/tensorpack/issues/1110

![0316-23:43:26](https://user-images.githubusercontent.com/1381301/54486423-57883b80-4845-11e9-8137-c48c20aec743.png)

**Comment by ppwwyyxx** [comment] 2019-03-17 18:30
The bug only exists in `tf.layers` & `tf.keras.layers`. It does not exist if I call the op `tf.nn.conv2d(dilations=)` directly.
It turns out that `tf.layers.Conv2D(dilations=2)` actually will do some space-to-batch/batch-to-space conversion, and call `tf.nn.conv2d(dilations=1)` instead of dilations=2.
This logic is implemented in this commit: https://github.com/tensorflow/tensorflow/commit/c0502aff716a6b7889c5eb23cd06b5bda414bf9e . And something is probably wrong there.

**Comment by ppwwyyxx** [comment] 2019-03-17 22:01
Disabling the graph rewriter by `config.graph_options.rewrite_options.disable_meta_optimizer = True` can make the bug disappear.
I can see from logs that the last shape op was mistakenly rewritten to a constant op.

**Comment by tanzhenyu** [comment] 2019-04-26 17:25
This seem to be related to grappler, which I'm not familiar with.

**Comment by ppwwyyxx** [comment] 2019-09-10 23:54
The bug still exists in TF 1.15rc0.

**Comment by ahmadki** [comment] 2019-09-25 14:47
I can confirm that #32432 fixes the issue when using cuDNN and the keras API (you'll have to set the argument `fused=True`)

@houtoms FYI

**Comment by zhuzilin** [comment] 2020-06-07 15:30
Since the above commit was closed, here are some information for those who may have interest in fixing this bug.

The bug is mainly caused by the static shape inference in constant folding pass of grappler. You can close this pass instead of the whole meta optimizer to avoid it. Also, it is weird that changing `data_format` to `"channels_last"` or set `use_bias=False` will both make the bug disappear. From the log I dumped, the bug should be around the shape inference of `BatchToSpaceND`. However, the shape of this op relies on the input value, so I'm not sure the bug is the implementation of the shape inference function of `BatchToSpaceND` or the process of creating its input...

**Comment by ppwwyyxx** [comment] 2020-07-15 23:43
I ran the exact same code in TF2.2, built with `--config=v1` and run with `TF2_BEHAVIOR=0`. The bug still exists.

**Comment by tensorflowbutler** [comment] 2021-06-10 18:13
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Closed** 2021-06-17 19:22 UTC
Labels: comp:grappler, comp:keras, stat:awaiting tensorflower, type:bug
