### ISSUE TITLE
compile issue for bazel build tensorflow/python/tools:optimize_for_inference

### ISSUE THREAD

**Issue by starkdg** [tensorflow/tensorflow#22037] opened 2018-09-03 23:02 UTC
optimize_for_inference.py

## OS platform and distribution
Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

## Tensorflow version
Tensorflow version r1.9 (compiled from source for CPU)

## CUDA/cuDNN 
n/a

## gpu model and memory
n/a

## Python version
Python version 3.5

## Bazel version
Bazel version 0.16.0 

## Gcc version
gcc version 6.3.0

## No custom code used, just standard script:
optimize_for_inference.py

### Command to reproduce:

bazel build tensorflow/python/tools:optimize_for_inference

### Mobile device 

n/a

### Problem:

The result is a failure to build.  

### Source code / logs
The output is rather lengthy, but here is the relevant "ERROR" part:

ERROR: /home/david/tensorflow/tensorflow/contrib/coder/BUILD:144:1: C++ compilation of rule '//tensorflow/contrib/coder:python/ops/_coder_ops.so' failed (Exit 1)
In file included from /usr/include/c++/6/map:60:0,
                 from external/protobuf_archive/src/google/protobuf/stubs/common.h:40,
                 from external/protobuf_archive/src/google/protobuf/stubs/atomicops.h:59,
                 from external/protobuf_archive/src/google/protobuf/stubs/atomic_sequence_num.h:33,
                 from external/protobuf_archive/src/google/protobuf/arena_impl.h:38,
                 from external/protobuf_archive/src/google/protobuf/arena.h:54,
                 from ./tensorflow/core/platform/default/protobuf.h:22,
                 from ./tensorflow/core/platform/protobuf.h:31,
                 from ./tensorflow/core/platform/default/string_coding.h:23,
                 from ./tensorflow/core/platform/tensor_coding.h:29,
                 from ./tensorflow/core/framework/resource_handle.h:19,
                 from ./tensorflow/core/framework/allocator.h:24,
                 from ./tensorflow/core/framework/op_kernel.h:23,
                 from tensorflow/contrib/coder/kernels/pmf_to_cdf_op.cc:24:
/usr/include/c++/6/bits/stl_tree.h: In instantiation of 'std::pair<std::_Rb_tree_iterator<_Val>, std::_Rb_tree_iterator<_Val> > std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::equal_range(const _Key&) [with _Key = std::__cxx11::basic_string<char>*; _Val = std::__cxx11::basic_string<char>*; _KeyOfValue = std::_Identity<std::__cxx11::basic_string<char>*>; _Compare = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::InnerMap::KeyCompare; _Alloc = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::MapAllocator<std::__cxx11::basic_string<char>*>]':
/usr/include/c++/6/bits/stl_tree.h:2298:49:   required from 'std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::size_type std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::erase(const _Key&) [with _Key = std::__cxx11::basic_string<char>*; _Val = std::__cxx11::basic_string<char>*; _KeyOfValue = std::_Identity<std::__cxx11::basic_string<char>*>; _Compare = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::InnerMap::KeyCompare; _Alloc = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::MapAllocator<std::__cxx11::basic_string<char>*>; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::size_type = long unsigned int]'
/usr/include/c++/6/bits/stl_set.h:602:30:   required from 'std::set<_Key, _Compare, _Alloc>::size_type std::set<_Key, _Compare, _Alloc>::erase(const key_type&) [with _Key = std::__cxx11::basic_string<char>*; _Compare = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::InnerMap::KeyCompare; _Alloc = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::MapAllocator<std::__cxx11::basic_string<char>*>; std::set<_Key, _Compare, _Alloc>::size_type = long unsigned int; std::set<_Key, _Compare, _Alloc>::key_type = std::__cxx11::basic_string<char>*]'
external/protobuf_archive/src/google/protobuf/map.h:619:9:   required from 'void google::protobuf::Map<Key, T>::InnerMap::erase(google::protobuf::Map<Key, T>::InnerMap::iterator) [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::Map<Key, T>::InnerMap::iterator = google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::InnerMap::iterator_base<google::protobuf::Map<std::__cxx11::basic_string<char>, tensorflow::AttrValue>::KeyValuePair>]'
external/protobuf_archive/src/google/protobuf/map.h:1139:5:   required from 'google::protobuf::Map<Key, T>::iterator google::protobuf::Map<Key, T>::erase(google::protobuf::Map<Key, T>::iterator) [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue]'
external/protobuf_archive/src/google/protobuf/map.h:1144:20:   required from 'void google::protobuf::Map<Key, T>::erase(google::protobuf::Map<Key, T>::iterator, google::protobuf::Map<Key, T>::iterator) [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue]'
external/protobuf_archive/src/google/protobuf/map.h:1147:23:   required from 'void google::protobuf::Map<Key, T>::clear() [with Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue]'
external/protobuf_archive/src/google/protobuf/map_field_inl.h:180:3:   required from 'void google::protobuf::internal::MapField<Derived, Key, T, key_wire_type, value_wire_type, default_enum_value>::Clear() [with Derived = tensorflow::NameAttrList_AttrEntry_DoNotUse; Key = std::__cxx11::basic_string<char>; T = tensorflow::AttrValue; google::protobuf::internal::WireFormatLite::FieldType kKeyFieldType = (google::protobuf::internal::WireFormatLite::FieldType)9u; google::protobuf::internal::WireFormatLite::FieldType kValueFieldType = (google::protobuf::internal::WireFormatLite::FieldType)11u; int default_enum_value = 0]'
bazel-out/k8-opt/genfiles/tensorflow/core/framework/attr_value.pb.h:1764:15:   required from here
/usr/include/c++/6/bits/stl_tree.h:1739:5: internal compiler error: Segmentation fault
     }
     ^

**Comment by tensorflowbutler** [comment] 2018-09-04 06:35
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by starkdg** [comment] 2018-09-04 20:32
Now, I'm getting this error when I try to build the pip package.  If I recall correctly, I  believe I encountered this problem before, when trying to build from source, but  was able to build on a subsequent attempt.  However, I don't remember doing anything differently.

ERROR: /home/david/tensorflow/tensorflow/core/grappler/BUILD:61:1: C++ compilation of rule '//tensorflow/core/grappler:graph_view' failed (Exit 1)
tensorflow/core/grappler/graph_view.cc: In constructor 'tensorflow::grappler::GraphView::GraphView(tensorflow::GraphDef*)':
tensorflow/core/grappler/graph_view.cc:22:1: internal compiler error: Segmentation fault
 GraphView::GraphView(GraphDef* graph) : graph_(graph) {
 ^~~~~~~~~

**Comment by starkdg** [comment] 2018-09-05 01:46
Ok, I'm able to compile it now. However, I didn't do anything different.  I merely ran the command a second time.  Perhaps its  a bug in Bazel. I'm not sure, but it seems as though running the build command a second time after a clean ./configure did the trick.  Bazel does seem to be a bit flaky, as multiple runs would of often land on a  different error.   If anyone is looking into this, I'd be happy to provide more information, if you need it.  Thanks.

**Comment by gunan** [comment] 2018-09-16 21:27
```
/usr/include/c++/6/bits/stl_tree.h:1739:5: internal compiler error: Segmentation fault
```
This line suggests to me that this is actually a segmentation fault in gcc 6

**Comment by reedwm** [comment] 2018-09-24 23:46
Yeah this looks like a compiler bug. So I'm marking as contributions welcome.

**Comment by starkdg** [comment] 2018-09-27 17:43
Thanks. It is indeed an intermittent error.  I"ve since been able to compile it, but not sure what I did differently.  On successive runs, the error message is different each time.

**Comment by tensorflowbutler** [comment] 2018-10-12 12:48
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-10-27 12:36
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-11-11 18:37
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by tensorflowbutler** [comment] 2018-11-26 18:55
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by placidchat** [comment] 2019-03-23 18:25
I've noticed strange non deterministic errors as well, when some steps of the compilation works occasionally

**Comment by reedwm** [comment] 2020-12-03 01:40
I cannot reproduce with gcc 7. Since this is nondeterministic, I could have just gotten lucky. But since this issue is old and hard to reproduce, I'll close for now. Feel free to file a new issue if this is still a problem.

**Closed by reedwm** 2020-12-03 01:40 UTC
Labels: stat:contributions welcome
