### ISSUE TITLE
GradientTape.gradient needs to check target type.

### ISSUE THREAD

**Issue by aingo03304** [tensorflow/tensorflow#42386] opened 2020-08-15 06:55 UTC
https://github.com/tensorflow/tensorflow/blob/b36436b087bd8e8701ef51718179037cccdfc26e/tensorflow/python/eager/backprop.py#L991

Recently, I wrote some code below which is very simple,
```python
tape.gradient(loss, model.trainable_variables)
```
but it raises `TypeError: Cannot convert value None to a Tensorflow DType.`
It turns out my custom loss function is returning None. yes, I know I was dumb.

I had to check all of the related tensorflow code lines to find this dumb problem.

So, I suggest the type checking block inside of this code.
I think this suggestion can be helpful for fools like me.

Thanks in advance :)

**Comment by amahendrakar** [comment] 2020-08-17 10:07
@aingo03304,
In order to expedite the trouble-shooting process, could you please provide the TensorFlow version, the complete code to reproduce the issue and the dataset you are using. Thanks!

**Comment by aingo03304** [comment] 2020-08-18 06:26
@amahendrakar Thank you for the kind and quick response! 
You can reproduce with this code sample which is very simple.
```python
import tensorflow as tf
def get_loss(y_true, y_pred):
    pass

with tf.GradientTape() as tape:
    tape.gradient(get_loss(1, 2), None)
```
It raises `TypeError: Cannot convert value None to a TensorFlow DType.`on tensorflow `2.3.0`.
It is foolish code, but the error is raised in `tensorflow/python/framework/dtypes.py` and the message doesn't tell you that the loss function is wrong.

Because the error message should help people to find out where the code has a fault, I suggested you add some type check features in `gradient` function which is visible to users.

And the docstring on gradient function says,
```
 Args:
      target: a list or nested structure of Tensors or Variables to be
        differentiated.
      sources: a list or nested structure of Tensors or Variables. `target`
        will be differentiated against elements in `sources`.
      output_gradients: a list of gradients, one for each element of
        target. Defaults to None.
      unconnected_gradients: a value which can either hold 'none' or 'zero' and
        alters the value which will be returned if the target and sources are
        unconnected. The possible values and effects are detailed in
        'UnconnectedGradients' and it defaults to 'none'.
```

I would add the message like `TypeError: target should be a list or nested structure of Tensors or Variables to be differentiated, but (TYPE) given`.

**Comment by aingo03304** [comment] 2020-08-21 05:47
@ymodak Hi, can you tell me what the bug related to this issue? Just curious about it.

**Comment by ymodak** [comment] 2021-01-03 19:21
Closing this issue since the [3edb086](https://github.com/tensorflow/tensorflow/commit/f25125e50bab365642335413356466883bf7f361) commit fixes it. Thanks!

**Closed by ymodak** 2021-01-03 19:21 UTC
Labels: comp:eager, type:bug
