### ISSUE TITLE
Mirrored Strategy CUDA_ERROR_ILLEGAL_ADDRESS

### ISSUE THREAD

**Issue by adstep** [tensorflow/tensorflow#44281] opened 2020-10-24 06:41 UTC
**System information**
Have I written custom code: NO
OS: Windows 10
Tensorflow Version: v2.3.0-54-gfcc4b966f1 2.3.1
Python Version: Python 3.8.6
CUDA/cuDNN version: 10.1/cudnn-10.1-windows10-x64-v7.6.5.32
GPU model and memory: 2x GeForce RTX 2080 Ti 11GB

**Describe the current behavior**
Tensorflow fails with the folllowing error:

```
Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```
Only see this error when executing using MirroredStrategy. Single GPU works just fine.

**Describe the expected behavior**
Tensorflow should execute my code without any errors.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.applications import Xception
import numpy as np

num_samples = 1000
height = 224
width = 224
num_classes = 1000

strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    parallel_model = Xception(weights=None,
                     input_shape=(height, width, 3),
                     classes=num_classes)
    parallel_model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

# Generate dummy data.
x = np.random.random((num_samples, height, width, 3))
y = np.random.random((num_samples, num_classes))

parallel_model.summary()
parallel_model.fit(x, y, epochs=20, batch_size=16) #batch_sized changed to 16
```

**Other info / logs** 
```
2020-10-23 23:35:09.514415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:03:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-10-23 23:35:09.514583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties:
pciBusID: 0000:04:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-10-23 23:35:09.514832: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-23 23:35:09.518478: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-23 23:35:09.521479: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-23 23:35:09.522718: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-23 23:35:09.526250: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-23 23:35:09.528215: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-23 23:35:09.536133: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-23 23:35:09.536323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-10-23 23:35:09.536813: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-23 23:35:09.546403: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x14c16f08870 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-23 23:35:09.546511: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-23 23:35:09.749996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:03:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-10-23 23:35:09.750156: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties:
pciBusID: 0000:04:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-10-23 23:35:09.750429: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-23 23:35:09.750544: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-10-23 23:35:09.750639: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-10-23 23:35:09.750729: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-10-23 23:35:09.750818: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-10-23 23:35:09.750874: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-10-23 23:35:09.750958: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-10-23 23:35:09.751069: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-10-23 23:35:10.440797: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-23 23:35:10.440935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1
2020-10-23 23:35:10.441179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N N
2020-10-23 23:35:10.441273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   N N
2020-10-23 23:35:10.441592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9418 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)
2020-10-23 23:35:10.442616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9419 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:04:00.0, compute capability: 7.5)
2020-10-23 23:35:10.446257: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x14c88a25f70 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-23 23:35:10.446360: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-23 23:35:10.446450: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-10-23 23:35:11.113923: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2020-10-23 23:35:11.114521: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:220] Unexpected Event status: 1
```

**Comment by Saduf2019** [comment] 2020-10-27 12:35
@adstep 
Can you please refer to [this comment](https://github.com/tensorflow/tensorflow/issues/40814#issuecomment-663838196) and let us know if it helps.

Similar issues for reference:
#41891 [link](https://github.com/tensorflow/tensorflow/issues/6509), [link1](https://stackoverflow.com/questions/60771063/tensorflow-reported-cuda-error-illegal-address-bug-while-train-yolo), please check if you have any [batch size related issue](https://forums.developer.nvidia.com/t/intermittent-cuda-error-illegal-address-error-on-ubuntu-18-04-with-tensorflow-2-2-0/127744/3)

**Comment by adstep** [comment] 2020-10-27 17:30
@Saduf2019 thanks for the response!

I've tried the method in the suggested comment. 

```
os.environ['TF_CUDNN_DETERMINISTIC']='1'

random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)
```

I still experience the same error

```
2020-10-27 10:29:37.095946: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by nikitamaia** [comment] 2020-10-28 16:55
Hi @adstep, I was able to run this example on GCP with two GPUs. I did not encounter any errors. 
Since I am unable to reproduce, I'm wondering if maybe there's an issue with one of your GPUs. Can you first run a test to make sure each GPU is functioning by running training with a single GPU at a time? If you have more than one GPU in your system, the GPU with the lowest ID will be selected by default, so you'll need to specify which GPU you want utilized. You can do that with `tf.config.set_visible_devices` to specify which devices are visible to the runtime. This experiment is to confirm that both GPUs are (independently) working fine.

The second thing to check is to try 
`strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.ReductionToOneDevice())`
this is to check whether NCCL is causing problems.

**Comment by adstep** [comment] 2020-10-28 19:49
Hey @nikitamaia, I tried both of your suggestions.

I ran the following code limiting it to a single GPU, as suggested, and validated both cards are working properly individually:
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.applications import Xception
import numpy as np
import os
import random

os.environ['TF_CUDNN_DETERMINISTIC']='1'

random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)

num_samples = 1000
height = 224
width = 224
num_classes = 1000

physical_devices = tf.config.list_physical_devices('GPU')
tf.config.set_visible_devices(physical_devices[0:], 'GPU')

parallel_model = Xception(weights=None,
                    input_shape=(height, width, 3),
                    classes=num_classes)
parallel_model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

# Generate dummy data.
x = np.random.random((num_samples, height, width, 3))
y = np.random.random((num_samples, num_classes))

parallel_model.summary()
# This `fit` call will be distributed on 8 GPUs.
# Since the batch size is 256, each GPU will process 32 samples.
parallel_model.fit(x, y, epochs=20, batch_size=16) #batch_sized changed to 16
```

Additonally, I ran the MirroredStrategy with ReductionToOneDevice and experienced the same reported issue CUDA_ERROR_ILLEGAL_ADDRESS.

**Comment by adstep** [comment] 2020-10-30 00:20
@nikitamaia any more ideas for what I can try? Is there any additional information I can provide?

**Comment by nikitamaia** [comment] 2020-10-30 16:00
When you did the single GPU training, were you still using `MirroredStrategy`? The strategy should work even with a single GPU, so it's worth running that experiment with a strategy.

Can you also try running the original code but with the default distribution strategy? Basically you would replace `tf.distribute.MirroredStrategy()` with  `tf.distribute.get_strategy()`.

It might also be worth testing out a different model other than Xception.

**Comment by adstep** [comment] 2020-10-30 22:51
@nikitamaia 

Originally I didn't test using ```MirroredStrategy```. I re-reran the test using ```MirroredStrategy``` but limiting the visible GPUs. I tried a test limiting each GPU individually. Both tests worked fine.

I replaced ```tf.distribute.MirroredStrategy()``` with ```tf.distribute.get_strategy()``` and re-ran the test with no limitations on visible GPUs, and didn't see the error. However, it was only using 1 of the 2 GPUs so I don't think it's doing the right thing.

I have ran this on private models other than Xception and continue to see the same error when using ```MirroredStrategy```.

**Comment by nikitamaia** [comment] 2020-11-19 22:27
Hi @adstep, sorry for the delayed response here. I'm having a difficult time thinking of how to debug since I cannot reproduce this issue. For a baseline, have you tried running the [simple distributed mnist example from the docs?](https://www.tensorflow.org/tutorials/distribute/keras)

**Comment by adstep** [comment] 2020-11-19 23:20
Hello I tried running the mnist example. Hitting a different issue with it.

Code:
```
# Import TensorFlow and TensorFlow Datasets

import tensorflow_datasets as tfds
import tensorflow as tf

import os

datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)

mnist_train, mnist_test = datasets['train'], datasets['test']

strategy = tf.distribute.MirroredStrategy()

num_train_examples = info.splits['train'].num_examples
num_test_examples = info.splits['test'].num_examples

BUFFER_SIZE = 10000

BATCH_SIZE_PER_REPLICA = 64
BATCH_SIZE = BATCH_SIZE_PER_REPLICA * strategy.num_replicas_in_sync

def scale(image, label):
  image = tf.cast(image, tf.float32)
  image /= 255

  return image, label

train_dataset = mnist_train.map(scale).cache().shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
eval_dataset = mnist_test.map(scale).batch(BATCH_SIZE)

with strategy.scope():
  model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(32, 3, activation='relu', input_shape=(28, 28, 1)),
      tf.keras.layers.MaxPooling2D(),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(64, activation='relu'),
      tf.keras.layers.Dense(10)
  ])

  model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])

# Define the checkpoint directory to store the checkpoints

checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

# Function for decaying the learning rate.
# You can define any decay function you need.
def decay(epoch):
  if epoch < 3:
    return 1e-3
  elif epoch >= 3 and epoch < 7:
    return 1e-4
  else:
    return 1e-5

# Callback for printing the LR at the end of each epoch.
class PrintLR(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    print('\nLearning rate for epoch {} is {}'.format(epoch + 1,
                                                      model.optimizer.lr.numpy()))

callbacks = [
    tf.keras.callbacks.TensorBoard(log_dir='./logs'),
    tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix,
                                       save_weights_only=True),
    tf.keras.callbacks.LearningRateScheduler(decay),
    PrintLR()
]

model.fit(train_dataset, epochs=12, callbacks=callbacks)
```

Stdout:
```
2020-11-19 15:17:18.070203: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-11-19 15:17:21.499802: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-11-19 15:17:21.557219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-11-19 15:17:21.574089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:04:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-11-19 15:17:21.590150: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-11-19 15:17:21.602893: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-11-19 15:17:21.615903: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-11-19 15:17:21.627121: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-11-19 15:17:21.654699: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-11-19 15:17:21.669031: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-11-19 15:17:21.689263: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-11-19 15:17:21.703846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-11-19 15:17:21.717343: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-19 15:17:21.761689: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1935a3ab900 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-19 15:17:21.773593: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-19 15:17:22.063036: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:03:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-11-19 15:17:22.084841: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 1 with properties: 
pciBusID: 0000:04:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.635GHz coreCount: 68 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 573.69GiB/s
2020-11-19 15:17:22.112355: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-11-19 15:17:22.125436: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2020-11-19 15:17:22.139006: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
2020-11-19 15:17:22.152512: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
2020-11-19 15:17:22.166484: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
2020-11-19 15:17:22.180377: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
2020-11-19 15:17:22.194679: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
2020-11-19 15:17:22.208581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-11-19 15:17:22.923990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-19 15:17:22.932969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 
2020-11-19 15:17:22.942861: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N N 
2020-11-19 15:17:22.952796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   N N 
2020-11-19 15:17:22.958146: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9418 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)
2020-11-19 15:17:22.997793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 9419 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:04:00.0, compute capability: 7.5)
2020-11-19 15:17:23.020132: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1938f7312f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-11-19 15:17:23.033983: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-11-19 15:17:23.050604: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
2020-11-19 15:17:25.049350: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-11-19 15:17:25.054777: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1391] Profiler found 2 GPUs
2020-11-19 15:17:25.061183: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cupti64_101.dll'; dlerror: cupti64_101.dll not found
2020-11-19 15:17:25.090233: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cupti.dll'; dlerror: cupti.dll not found
2020-11-19 15:17:25.120624: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1441] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
Epoch 1/12
WARNING:tensorflow:From C:\Users\adstep\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\data\ops\multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
WARNING:tensorflow:From C:\Users\adstep\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\data\ops\multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
```

Stderr:
```
No OpKernel was registered to support Op 'NcclAllReduce' used by {{node NcclAllReduce}} with these attrs: [reduction="sum", shared_name="c1", T=DT_FLOAT, num_devices=2]
Registered devices: [CPU, GPU, XLA_CPU, XLA_GPU]
Registered kernels:
  <no registered kernels>

	 [[NcclAllReduce]] [Op:__inference_train_function_2229]
  File "C:\dev\github\dist_mnist\run.py", line 74, in <module>
    model.fit(train_dataset, epochs=12, callbacks=callbacks)
```

**Comment by adstep** [comment] 2020-11-19 23:23
I switched to using ```strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())``` based on recommendation from [this post](https://github.com/tensorflow/tensorflow/issues/33656#issuecomment-692710505). The code completes successfully now.

**Comment by nikitamaia** [comment] 2020-11-20 02:25
Okay seems like your GPUs are working okay (although for better performance in the longer term you might want to look into getting NCCL on your system). The only real difference here is that the MNIST example is smaller than the Xception example. So for the Xception example, have you tried to limit memory growth? https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth

One other thing to try is using tf.data instead of passing numpy arrays to `model.fit`

**Comment by adstep** [comment] 2020-11-20 04:25
Hey I went back to my original example and ran it again. Now, I get the same error about ```Nccl```. Using the cross_device_ops workaround from above I was able to get my original example working. I haven't updated CUDN/tf/python since we last spoke, but I have went through a couple of Windows Updates, which I suspect might have been the issue.

I'm not familiar with NCCL. I'm on Windows. Looking online it seems like it's not available for Windows. Is this the case?

**Comment by nikitamaia** [comment] 2020-11-24 00:30
NCCL is the default `cross_device_ops` when using `MirroredStrategy`, but if you don't have NCCL on your system then you can use `HierarchicalCopyAllReduce` or `ReductionToOneDevice`. I suspect `ReductionToOneDevice` will be the better option for you since `HierarchicalCopyAllReduce` is really best for a particular configuration of GPUs. But you can try out both.

As far as NCCL on Windows, I unfortunately am not familiar with that. You might want to check out the NCCL github repo to get more information on a Windows setup.

Closing this issue now because there is no bug present, and a workaround was found.

**Closed by nikitamaia** 2020-11-24 00:30 UTC
Labels: TF 2.3, comp:dist-strat, type:support

**Comment by xiongjiezk** [comment] 2021-11-09 02:42
I have the same error and find no way to solve it but turn down the `batch_size`, the error disappears automatically
