### ISSUE TITLE
Website claims that there is no internet connection

### ISSUE THREAD

**Issue by Apromixately** [tensorflow/tensorflow#29046] opened 2019-05-27 07:32 UTC
JavaScript on the website runs some sort of detection to see if there is network connectivity or tries to establish a connection in a surprising way.

This fails and I get a message "There is no Internet connection :(" which is clearly wrong. I am writing this issue with the same internet connection.

The JS console says:

    Failed to load ‘https://www.google-analytics.com/analytics.js’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.

    Failed to load ‘https://www.tensorflow.org/_d/profile/ogb’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.

    Failed to load ‘https://www.tensorflow.org/_d/profile/user’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.

**Comment by Breta01** [comment] 2019-05-28 16:33
I was facing exactly the same issue. Turns out it was caused by one of my browser's plugin which blocks trackers. It was blocking the loading of `https://www.tensorflow.org/_d/profile...`. Turning it off solved the issue for me.

**Comment by jvishnuvardhan** [comment] 2019-06-06 21:14
Automatically closing this out since I understand it to be resolved by @Breta01 suggestion, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-06-06 21:14 UTC
Labels: type:docs

**Comment by abcsds** [comment] 2019-07-10 00:36
Well, uninstalling privacy badger does make the website functional, but that means that anyone that wants to use the official documentation has to accept google analytics? Sounds like you're paying with your private data to use the documentation.

**Comment by Li357** [comment] 2019-08-06 16:13
Dealing with the same problem with Firebase docs, but disabling my adblocker (uBlock Origin) has no effect. Works fine in private browsing with the adblocker though.
