### ISSUE TITLE
Is Docker image tag "latest-devel-py3" Python2?

### ISSUE THREAD

**Issue by MatsumotoHiroko** [tensorflow/tensorflow#18372] opened 2018-04-10 04:43 UTC
I'd like to use Tensorflow with Python3 on Docker.
I set my Dockerfile below then build and run.

`FROM tensorflow/tensorflow:latest-devel-py3`

I entered in a shell on Docker and typed next command.

```
# python --version
Python 2.7.12
```

Is the image tag of "latest-devel-py3" Python2?

However, I tried to build and run using "latest-py3".
This response was,
```
# python --version
Python 3.5.2
```

Anyway, could anyone describe me about the difference between "latest-devel-py3" and "latest-py3"?

**Comment by tensorflowbutler** [comment] 2018-04-10 12:32
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yongtang** [comment] 2018-04-10 17:30
Python 3 was added to Dockerfile in #6030. I noticed that compared with `Dockerfile`, the `Dockerfile.devel` does not have 
```
# RUN ln -s /usr/bin/python3 /usr/bin/python#
```
That is the reason `python --version` output difference. (python 2 in latest-devel-py3 and python 3 in latest-py3)

I don't know if that was intentional in #6030, though.

**Comment by av8ramit** [comment] 2018-04-11 16:27
```
# docker run -it  tensorflow/tensorflow:latest-py3 bash
# python --version
Python 3.5.2
```

Should be fixed now. Please comment if there are still issues.

**Closed by av8ramit** 2018-04-11 16:27 UTC
Labels: stat:awaiting tensorflower
