### ISSUE TITLE
Dying Threads?

### ISSUE THREAD

**Issue by Anthony-Tatowicz** [tensorflow/tensorflow#3583] opened 2016-07-30 03:27 UTC
### Environment info
Operating System: Ubuntu trusty

Installed version of CUDA and cuDNN: Cuda compilation tools, release 7.5, V7.5.17

1. Which ~~pip~~ package you installed.  Docker gpu-devel image
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.9.0

### Steps to reproduce
1. Run inception model on training with inception_train.py

  bazel-bin/inception/(pick your data)_train \
    --train_dir="${TRAIN_DIR}" \
    --data_dir="${DATA_DIR}" \
    --pretrained_model_checkpoint_path="${PRETRAINED_DIR}" \
    --fine_tune=True \
    --initial_learning_rate=0.01 \
    --input_queue_memory_factor=12 \
    --batch_size=64 \
    --max_steps=100000 \
    --num_epochs_per_decay=30 \
    --num_preprocess_threads=4 \
    --num_readers=4 \
    --log_device_placement=True

### What have you tried?
1. This is ironic, because I have been wrestling with the problem for a few days, and serendipitously came to a conclusion. I was training the model and testing it out, and always
after 1000~ steps the training slows to a crawl utilizing my GPU only every 10s - 15s and the CPU seems to be only utilizing 2 threads to 100% at this point for preprocessing , when i specified 4 & 4 readers, but all threads kick in right before/at the GPU utilization. I tried restarted and playing with the threads and readers and other things, no luck, it still slowed after 1000~ steps. I left it running for whatever reason and later started running a Tensorflow bazel build, which used significant CPU for some time and after/during the build my training magically picked up to the original speed at the beginning, and by picked up i mean went from 1-4 exp/s not steady to 15 exp/s steady, hmm thats strange, because it had been crawling for hours at 1-4 exp/s? 

### Logs or other output that would be helpful
None

**Comment by michaelisard** [comment] 2016-07-31 19:55
Could you share a timeline trace? There are some tips for collecting timelines on [this StackOverflow thread](http://stackoverflow.com/questions/34293714/tensorflow-can-i-measure-the-execution-time-of-individual-operations).

**Comment by Anthony-Tatowicz** [comment] 2016-08-02 01:03
Now I get the following error when trying to run.

```
I tensorflow/stream_executor/dso_loader.cc:102] Couldn't open CUDA library libcupti.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
F tensorflow/core/platform/default/gpu/cupti_wrapper.cc:58] Check failed: f != nullptr could not find cuptiActivityRegisterCallbacksin libcupti DSO; dlerror: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cuptiActivityRegisterCallbacks
```

**Comment by poxvoculi** [comment] 2016-08-02 18:21
Hi, it seems likely that your second and first issues are unrelated.  Let's tackle the second issue first, since it's a blocker.  What changed between when you had the slow runs, and when the library could no longer be found?  It seems that one must be careful when using gpus with docker to use the correct image.  There's some recent discussion in #808

**Comment by Anthony-Tatowicz** [comment] 2016-08-02 21:34
Nothing changed, but the code for the time tracer if I comment out the tracer code it will run, but if I uncomment the tracer code I get the above error.

**Comment by poxvoculi** [comment] 2016-08-02 23:00
OK, thanks for clarifying.  It would be nice to get op times somehow, but I'm less optimistic that will be strongly helpful.   Weird slowdown errors can often be caused by memory problems, especially if they gradually build up over time, like you report.   Can you watch use of virtual memory and swap on your machine while this is going on?  I wonder whether you might be using up too much vmem for file buffers or similar.  I know that bazel is a memory hog, and maybe when you run that it forces some kind of GC that cleans things up temporarily.

**Comment by Anthony-Tatowicz** [comment] 2016-08-03 23:40
That sounds likely, I do recall massive vmem usage when I was running I will double check and report, back with my findings. I'm not sure what the issue is with the time tracer might be a docker issue, I will try again on a local install as well.

**Comment by Pcres91** [comment] 2016-09-12 08:34
Had the same issue, how I fixed it:
I'm running zsh on ubuntu 16.04, with cuda 7.5.18 and cudNN 4.0.7

running $LD_LIBRARY_PATH showed no path for the library, and so I had to manually add two lines to my .zshrc file:
```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64"
export CUDA_HOME=/usr/local/cuda
```

It seems strange they weren't there before, but once I did that and ran source `.zshrc`, the path updated and it worked

**Comment by drpngx** [comment] 2016-10-26 17:04
Closing since @Pcres91 provided an answer.

**Closed by drpngx** 2016-10-26 17:04 UTC
