### ISSUE TITLE
Not able to import tensorflow

### ISSUE THREAD

**Issue by Flock1** [tensorflow/tensorflow#18482] opened 2018-04-13 04:54 UTC
Ubuntu: 16.04.4
Tensorflow installed from Anaconda
Tensorflow version: 1.4.1
Python: Python3
CUDA: 8
Cudnn: 7.0.5
GPU: GTX 1080 8GB
Command: import tensorflow on ipython notebook
Error:
```
ImportError                               Traceback (most recent call last)
~/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~/anaconda3/envs/tf/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

~/anaconda3/envs/tf/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-64156d691fe5> in <module>()
----> 1 import tensorflow as tf

~/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

~/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 # Protocol buffers

~/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     70 for some common reasons and solutions.  Include the entire stack trace
     71 above this error message when asking for help.""" % traceback.format_exc()
---> 72   raise ImportError(msg)
     73 
     74 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/home/sarvagya/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/sarvagya/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/sarvagya/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/sarvagya/anaconda3/envs/tf/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/sarvagya/anaconda3/envs/tf/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

```
**UPDATE:**
I installed normal tensorflow and I was able to import tensorflow. However, now, I am not able use the GPU, even though tensoeflorw-gpu is installed in the environment.

**Comment by tensorflowbutler** [comment] 2018-04-13 18:40
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Flock1** [comment] 2018-04-16 03:53
Hi,
OS: Ubuntu 16.04.4
CUDA: 8.03, Cudnn: 7.0.5
GPU: 1080 8GB
No Bazel.
Command: No command. I am importing it in jupyter notebook and a conda env. So for import tensorflow, I get the error.

**Comment by Flock1** [comment] 2018-04-17 03:33
@tensorflowbutler, an Update:
I created a new profile on Ubuntu, no NVIDIA libraries like CUDA, cudnn and other installed, installed anaconda and an env with `python 3`. I installed tf gpu using conda (` conda install -c anaconda tensorflow-gpu`)  and it installed `1.0.1` `cudatoolkit 7.5` and `cudnn 5.1`. Now, it's working. 

Can you work on something to avoid all this? I'm guessing tf 1.0.1 is pretty old with a lot of features not available. What do you suggest I should do for tf 1.4 gpu to work?

**Comment by Flock1** [comment] 2018-04-17 05:31
**UPDATE**:
I solved it by adding `/path/to/libcuda.so.1` in the `LD_LIBRARY_PATH`. I rebooted and it worked.

**Comment by michaelisard** [comment] 2018-04-19 22:16
Closing since you solved the problem!

**Closed by michaelisard** 2018-04-19 22:16 UTC

**Comment by shyamStarwalt** [comment] 2018-11-28 10:37
File "C:\Users\DMLaptopWindows1\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\DMLaptopWindows1\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\python\__init__.py", line 59, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\DMLaptopWindows1\Anaconda3\envs\tensorflow1\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\Users\DMLaptopWindows1\Anaconda3\envs\tensorflow1\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
