### ISSUE TITLE
Ubuntu installation error using pip

### ISSUE THREAD

**Issue by tkwinfo** [tensorflow/tensorflow#106] opened 2015-11-10 23:15 UTC
Hi,

I am using Ubuntu 12.04 amd64 with Python 2.7.3. I have used the following command to want to install tensorflow :

pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

I get the following error :

###
/usr/bin/pip run on Wed Nov 11 07:00:36 2015
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Downloading from URL https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-k5gImY-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-k5gImY-build/setup.py'

Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 980, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 216, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 255, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
###

The output of "sudo pip --version" is "pip 1.0 from /usr/lib/python2.7/dist-packages (python 2.7)".

I want to know that is my pip version too low. What else should I try ? Any idea ?

Thanks for any suggestion.

Lawrence

**Comment by vrv** [comment] 2015-11-10 23:18
Likely a dupe of https://github.com/tensorflow/tensorflow/issues/56: let us know if it isn't (answer is to upgrade pip).  Re-open if that's not the case!

**Closed by vrv** 2015-11-10 23:18 UTC

**Comment by aolang** [comment] 2016-05-11 03:55
upgrade the pip can solve the problem, but when "Run TensorFlow from the Command Line", another issue came up,  "ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so)", 
and  check the libc, 
$ strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_PRIVATE
Ubuntu 12.04 libc not support "GLIBC_2.17"
