### ISSUE TITLE
many functions not found in libtensorflow-core.a

### ISSUE THREAD

**Issue by zig-kwin-hu** [tensorflow/tensorflow#7813] opened 2017-02-23 09:09 UTC
I am trying to compile Image Recognition with makefile (which is compiled with bazel originally). However, it raise error that:

image_ops.h: No such file..

Following the instructions in [#3017](https://github.com/tensorflow/tensorflow/issues/3017), I add **tensorflow/bazel-genfiles** to my header search path.

It does work, but another error comes out as fllows:

11 warnings generated.
Undefined symbols for architecture x86_64:
  "tensorflow::ops::DecodeJpeg::DecodeJpeg(tensorflow::Scope const&, tensorflow::Input, tensorflow::ops::DecodeJpeg::Attrs const&)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::ExpandDims::ExpandDims(tensorflow::Scope const&, tensorflow::Input, tensorflow::Input)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::ResizeBilinear::ResizeBilinear(tensorflow::Scope const&, tensorflow::Input, tensorflow::Input)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::Div::Div(tensorflow::Scope const&, tensorflow::Input, tensorflow::Input)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::Sub::Sub(tensorflow::Scope const&, tensorflow::Input, tensorflow::Input)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::Cast::Cast(tensorflow::Scope const&, tensorflow::Input, tensorflow::DataType)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::Const(tensorflow::Scope const&, tensorflow::Input::Initializer const&)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::TopKV2::TopKV2(tensorflow::Scope const&, tensorflow::Input, tensorflow::Input)", referenced from:
      GetTopLabels(std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> > const&, int, tensorflow::Tensor*, tensorflow::Tensor*) in main-b19045.o
  "tensorflow::ops::ReadFile::ReadFile(tensorflow::Scope const&, tensorflow::Input)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::DecodeGif::DecodeGif(tensorflow::Scope const&, tensorflow::Input)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::ops::DecodePng::DecodePng(tensorflow::Scope const&, tensorflow::Input, tensorflow::ops::DecodePng::Attrs const&)", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
  "tensorflow::Input::Initializer::Initializer(std::initializer_list<tensorflow::Input::Initializer> const&)", referenced from:
      tensorflow::Input::Input(std::initializer_list<tensorflow::Input::Initializer> const&) in main-b19045.o
  "tensorflow::Scope::NewRootScope()", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
      GetTopLabels(std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> > const&, int, tensorflow::Tensor*, tensorflow::Tensor*) in main-b19045.o
  "tensorflow::Operation::Operation(tensorflow::Node*)", referenced from:
      tensorflow::Output::Output() in main-b19045.o
      tensorflow::Input::Input(std::initializer_list<tensorflow::Input::Initializer> const&) in main-b19045.o
      tensorflow::Input::Input(tensorflow::Tensor const&) in main-b19045.o
      tensorflow::Input::Input(tensorflow::Input::Initializer const&) in main-b19045.o
  "tensorflow::Scope::ToGraphDef(tensorflow::GraphDef*) const", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
      GetTopLabels(std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> > const&, int, tensorflow::Tensor*, tensorflow::Tensor*) in main-b19045.o
  "tensorflow::Scope::WithOpName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      ReadTensorFromImageFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, int, float, float, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) in main-b19045.o
      GetTopLabels(std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> > const&, int, tensorflow::Tensor*, tensorflow::Tensor*) in main-b19045.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I think these ops are not included in libtensor-core.a. 
My question is: how to link these ops using makefile?

**Comment by petewarden** [comment] 2017-06-16 20:09
The makefile is aimed at mobile development, and doesn't include a lot of functionality that the label_image example depends on (e.g. jpeg decoding, generated C++ operators). Closing this as working as intended.

**Closed by petewarden** 2017-06-16 20:09 UTC
Labels: stat:awaiting tensorflower

**Comment by aqeeliqbal** [comment] 2017-06-21 11:19
So what should we do to implent this on iOS ?
