### ISSUE TITLE
Input shape for convolution1D

### ISSUE THREAD

**Issue by gharshini** [tensorflow/tensorflow#44065] opened 2020-10-15 22:08 UTC
I have sparse coefficients array of shape 1D. Each value in the 1D array corresponds to one class. For example, I just have an array 
a = [1,2,3,4,4,5,6,78,8543,35,878,.............]
class_label = [1,1,1,2,2,3,3,1,2,......]

How should I input this to Convolution1D? It always gives me an error of input dimensions.

**Comment by ravikyram** [comment] 2020-10-16 10:47
@gharshini 

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by gharshini** [comment] 2020-10-16 13:49
Could you please answer this?

**Comment by jvishnuvardhan** [comment] 2020-10-16 22:18
@gharshini Can you please share a standalone code to reproduce the issue? The example data you mentioned above is one dataset (x (featurers), y(labels))? Thanks!

**Comment by gharshini** [comment] 2020-10-19 16:30
model = Sequential()
model.add(Convolution1D(filters=32, kernel_size=1,strides = 3, input_shape=(1886,)))

I gave an input shape as above. I got the below error:

ValueError: Input 0 of layer conv1d_1 is incompatible with the layer: : expected min_ndim=3, found ndim=2. Full shape received: [None, 1886]

**Comment by gharshini** [comment] 2020-10-19 16:37
The data that I have is a sparse coefficient data that I got from the sparse representation of EEG signals. My task is to classify the sparse coefficients. They are 1D data. Please go through the link below:

https://www.frontiersin.org/files/Articles/567151/fnins-14-00808-HTML-r2/image_m/fnins-14-00808-g003.jpg

My architecture is similar to the link. I am stuck with the input shape of conv1d for 1D array.

**Comment by jvishnuvardhan** [comment] 2020-10-30 22:46
@gharshini From [Keras website](https://keras.io/api/layers/convolution_layers/convolution1d/),

> When using this `Convolution1D` layer as the first layer in a model, provide an input_shape argument (tuple of integers or None, e.g. (10, 128) for sequences of 10 vectors of 128-dimensional vectors, or (None, 128) for variable-length sequences of 128-dimensional vectors.

I had updated the input_shape as shown below and everything works as expected.
`model.add(Convolution1D(filters=32, kernel_size=1,strides = 3, input_shape=(1,1886)))`

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/3ce64184332aa2fbe503ba5f5c1e2f75/untitled.ipynb). Thanks!

I am closing this issue as this is resolved. Please feel free to reopen if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2020-10-30 22:46 UTC
Labels: comp:keras, type:support
