### ISSUE TITLE
ERROR: no such package '@rules_pkg//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz] to /private/var/tmp/_bazel_ysong2/b326506f60d8e1a7b80e7181271420e8/external/rules_pkg/temp3975631198066234777/rules_pkg-0.2.5.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by ysong2123** [tensorflow/tensorflow#59669] opened 2023-02-13 15:26 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tag: v2.11.0

### Custom Code

No

### OS Platform and Distribution

MacOS Montery 12.6.1

### Python version

3.9

### Bazel version

5.6

### GCC/Compiler version

clang 14.0

### CUDA/cuDNN version

none

### GPU model and memory

none

### Current Behaviour?

```shell
ERROR: no such package '@rules_pkg//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz] to /private/var/tmp/_bazel_ysong2/b326506f60d8e1a7b80e7181271420e8/external/rules_pkg/temp3975631198066234777/rules_pkg-0.2.5.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

tried add certificates into keystore but doesn't work.
```

### Standalone code to reproduce the issue

```shell
ERROR: no such package '@rules_pkg//': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz, https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz] to /private/var/tmp/_bazel_ysong2/b326506f60d8e1a7b80e7181271420e8/external/rules_pkg/temp3975631198066234777/rules_pkg-0.2.5.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

### Relevant log output

_No response_</details>

**Comment by ysong2123** [comment] 2023-02-14 08:32
any one could help on this?

**Comment by gaikwadrahul8** [comment] 2023-02-14 15:12
Hi, @ysong2123 

Apologize for the delay and it seems like the problem is due to SSL certificate on your machine and at the moment I'm providing some useful links which will help you to solve your SSL certificate problem [Ref-1](https://docs.mend.io/en-US/bundle/wsk/page/how_to_resolve_error_message__pkix_path_building_failed__sun_security_provider_certpath_suncertpathbuilderexception__unable_to_find_valid_certification_path_to_requested_target_.html), [Ref-2](https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ#:~:text=28-,Mac,-The%20accepted%20answer), [Ref-3](https://stackoverflow.com/questions/6908948/java-sun-security-provider-certpath-suncertpathbuilderexception-unable-to-find#:~:text=And%20if%20you%20are%20here%20in%202022%20and%20are%20on%20mac%20follow%20this) so please try to follow workaround from those references and please let me know is it resolving your issue?

Just to confirm are you looking to install `Tensorflow 2.11` build from source or you just want to install Bazel on Macos ? I hope you're following this [official documentation](https://www.tensorflow.org/install/source#macos) to install Tensorflow build from source

I'll also try to install `Tensorflow 2.11` build from source on `MacOS` once you confirm that you're looking to install Tensorflow 2.11 build from source so please confirm it ? Thank you!

**Comment by ysong2123** [comment] 2023-02-14 15:52
Hi Gaikwadrahul8,
Yes, i strictly followed the steps in the official doc,  after git clone tensorflow,    then cd to root directory,         then try:
'bazel  build //tensorflow/tools/pip_package:build_pip_package' (all prerequisites have been installed in advance),   finally i got the certificate issue above.

**Comment by gaikwadrahul8** [comment] 2023-02-15 13:10
Hi, @ysong2123 

Thank you for the details and usually users get this error `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` due to the system firewall. The system firewall restricts the application to connect to external systems. The firewall requires a valid certificate to allow access to the external systems.

Could you please confirm, whether you're installing [Bazel](https://bazel.build/install) normally or via `Bazelisk` because [Bazelisk](https://github.com/bazelbuild/bazelisk) is an easy way to install Bazel and automatically downloads the correct Bazel version for TensorFlow and if you're using Bazelisk then please download manually and please follow below steps :

1. `wget https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-darwin-arm64` (If you get any error with respect to certificate then you can use this command `wget --no-check-certificate https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-darwin-arm64`

2. `chmod +x bazelisk-darwin-arm64`

3. `sudo mv bazelisk-darwin-arm64 /usr/local/bin/bazel`

If you have already done above steps and installed Bazel correctly then please execute below steps to see the Bazel or Bazelisk location and if possible please help me with those details 

```
1. whereis bazel
2. whereis bazelisk
```

I'll try to install Tensorflow on my MacOS from my end till then by following our official documentation and I'll update the same here. Thank you!

**Comment by ysong2123** [comment] 2023-02-15 14:31
my new finding:
after run cmd in tensorflow root directory:      
'bazel  build //tensorflow/tools/pip_package:build_pip_package',  
Then i found  there's a jdk env auto-generated under path :/private/var/tmp/_bazel_ysong2/install/3c4a7a3c33b4c067b191587b066e5f1b/embedded_tools/jdk/

this JDK is isolated with my local JDK env.    so i wrote a simple java demo tried to make a java ssl call to get tensorflow dependencies.    If i use my local JDK(openjdk8 or openjdk11) i can get those dependencies with no any exception.  
But when i pointed to /private/var/tmp/_bazel_ysong2/install/3c4a7a3c33b4c067b191587b066e5f1b/embedded_tools/jdk/, 
i got the same ssl issue.          is there any way to adopt my local jdk for bazel build?

**Comment by ysong2123** [comment] 2023-02-16 06:05
i solved this problem using :
https://bazel.build/install/compile-source#bootstrap-unix,    
I commented out this 'for' and rebuild a binary version of bazel. 
Then using this to build tensorflow, no any exception now

**Comment by gaikwadrahul8** [comment] 2023-02-16 07:07
Hi, @ysong2123 

Good to hear that you're able to resolve your issue and even I was able to install `Tensorflow` build from source with `Bazelisk` approach and it seems like in your case there was some conflict between local JDK and Bazel embedded JDK and it got resolve by this command `env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh`

I have added screenshot below for your reference with `Bazelisk` Approach:

![image](https://user-images.githubusercontent.com/115997457/219292576-852d0a0f-ab4d-4e45-9d2b-c6be84e3f187.png)

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? if you need any further assistance please let us know? Thank you!

**Closed** 2023-02-16 07:21 UTC
Labels: stat:awaiting response, type:build/install, subtype:macOS, TF 2.11
