### ISSUE TITLE
Tensorflow 2.0 SavedModel format with GPU acceleration slowdown

### ISSUE THREAD

**Issue by SlavaKeshkov** [tensorflow/tensorflow#33201] opened 2019-10-10 09:58 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): tensorflow==2.0.0-rc1 (2.0.0rc0-gpu-py3 docker image)
- Python version: 3.5.0
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: -
- GPU model and memory: TeslaV100 

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I have a SavedModel trained with Tensorflow 2.0 which I use to make an inference as follows: 

```
 model= tf.saved_model.load(export_dir = 'path/to/savedmodel/1')
 infer = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
 outputs = infer(img_tensor)

```
The model predicts fast on a CPU but when using a GPU device, it scales linearly and GPU does not offer any advantage. When logging the device placement, I see that GPU is used.

To compare, I have the same model trained in Tensorflow 1.13 saved in frozen graph format. I use the model as follows:
```

   graph = load_graph('path/to/graph.pb')
   labels = load_labels('path/to/labels.txt')

    input_name = 'import/Placeholder'
    output_name = 'import/final_result'

    input_operation = graph.get_operation_by_name(input_name)
    output_operation = graph.get_operation_by_name(output_name)

    # initialize a tensorflow session
    with tf.compat.v1.Session(graph=graph) as sess:
        results = sess.run(
            output_operation.outputs[0],
            {input_operation.outputs[0]: img_array})

        sess.close()

def load_graph(model_file):
    graph = tf.Graph()
    graph_def = tf.compat.v1.GraphDef()

    with open(model_file, "rb") as file:
        graph_def.ParseFromString(file.read())

    with graph.as_default():
        tf.import_graph_def(graph_def)

    return graph

```

The timing of this model on GPU in the same environment is much faster than SavedModel format. I think this is a performance issue.

Here are the timing details:
TF2.0 SavedModel
Batch of 64 images CPU: 23 seconds
Batch of 64 images GPU: 14 seconds

TF13.0 Frozen Graph:
Batch of 64 images CPU: 25 seconds
Batch of 64 images GPU: 5 seconds

**Describe the expected behavior**
My expected behaviour is that Tensorflow 2.0 version with SavedModel would use GPU acceleration. Maybe I am missing on how to import the SavedModel in python. Please let me know what could be the route cause of it.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ravikyram** [comment] 2019-10-11 10:11
In order to expedite the trouble-shooting process, please provide a minimal standalone code and necessary files to reproduce the issue reported here in our environment.

**Comment by ravikyram** [comment] 2019-10-21 05:26
@SlavaKeshkov 

Any updates on this issue please.Thanks!

**Comment by ravikyram** [comment] 2019-10-25 10:37
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-10-25 10:37 UTC
Labels: TF 2.0, comp:model, stat:awaiting response, type:performance

**Comment by Stealers** [comment] 2020-03-05 02:25
@SlavaKeshkov ，
Has your problem been solved? Do you know how to use GPU to speed up savedmodel(TF2.0) inference？
