### ISSUE TITLE
Please enable ImageDataGenerator for tpu accelerator 

### ISSUE THREAD

**Issue by imrankhan441** [tensorflow/tensorflow#40628] opened 2020-06-20 01:52 UTC
please enable ImageDataGenerator for tpu because create TFRecordDataset is the complex and worst method I ever have seen my entire deep-learning experience . or make a function that converts ImageDataGenerator to TFRecordDataset. 

If converts ImageDataGenerator to TFRecordDataset gives me a reference.

Thank you

**Comment by ravikyram** [comment] 2020-06-22 04:47
@imrankhan441 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by nikitamaia** [comment] 2020-06-22 22:01
Hi @imrankhan441, if you haven't seen it already, it might be worth taking a look at issue #34346 which has some more information around the work involved in making ImageDataGenerator work with TPU.

**Comment by imrankhan441** [comment] 2020-06-23 15:10
**Please Run This Code you will understand what I mean.**


```
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
import zipfile



resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
tpu_strategy = tf.distribute.experimental.TPUStrategy(resolver)




def cnn_model(Classes, input_shape = (128, 128, 3)):

    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Conv2D(64, (5, 5), padding='same', input_shape = input_shape))
    model.add(tf.keras.layers.MaxPooling2D(strides=(2,2)))
    model.add(tf.keras.layers.Dropout(0.25))

    model.add(tf.keras.layers.Conv2D(128, (5, 5), padding='same'))
    model.add(tf.keras.layers.MaxPooling2D())
    model.add(tf.keras.layers.Dropout(0.25))

    model.add(tf.keras.layers.Conv2D(256, (5, 5), padding='same'))
    model.add(tf.keras.layers.MaxPooling2D(strides=(2,2)))
    model.add(tf.keras.layers.Dropout(0.25))

    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(Classes, activation="softmax"))


    return model



!wget --no-check-certificate \
    https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip \
    -O ./cats_and_dogs_filtered.zip



dataset_path = "./cats_and_dogs_filtered.zip"
zip_object = zipfile.ZipFile(file=dataset_path, mode="r")
zip_object.extractall("./")
zip_object.close()

dataset_path_new = "./cats_and_dogs_filtered/"
train_dir = os.path.join(dataset_path_new, "train")
validation_dir = os.path.join(dataset_path_new, "validation")

with tpu_strategy.scope():
    model = cnn_model(1)
    model.compile(optimizer=tf.keras.optimizers.RMSprop(lr=0.0001),loss="binary_crossentropy", metrics=["accuracy"])

batch_size = 8 * 128 

data_gen_train = ImageDataGenerator(rescale=1/255.)
data_gen_valid = ImageDataGenerator(rescale=1/255.)

train_generator = data_gen_train.flow_from_directory(train_dir, target_size=(128,128), batch_size=batch_size, class_mode="binary")
valid_generator = data_gen_valid.flow_from_directory(validation_dir, target_size=(128,128), batch_size=batch_size, class_mode="binary")

model.fit_generator(train_generator, epochs=5, validation_data=valid_generator)

```

**Comment by ravikyram** [comment] 2020-06-24 03:21
@imrankhan441 

I have tried in colab with TF version 2.2.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/b7b0de3f9bf059d18f19a75f9b5b48b8/untitled60.ipynb#scrollTo=3IsxUejJUJ7v).Are you seeing the same behavior?.Thanks!

**Comment by imrankhan441** [comment] 2020-06-24 03:34
@ravikyram 

**Yes exact same error Please fix this. This error didn't show in CPU and GPU. It shows tpu only.**


```
NotFoundError: {{function_node __inference_train_function_5687}} No registered 'PyFunc' OpKernel for 'CPU' devices compatible with node {{node PyFunc}}
	.  Registered:  <no registered kernels>

	 [[PyFunc]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNextAsOptional]]

```

**Comment by eaedk** [comment] 2020-07-26 01:05
I have the same issue as @imrankhan441 when i use ImageDataGenerator with TPU. please we need this fixed

**Comment by eaedk** [comment] 2020-07-26 01:11
I use flow_from_dataframe, and I didn't find any other way to debug my code

**Comment by nikitamaia** [comment] 2020-12-18 00:08
I'm closing this issue now because it is a duplicate of #34346. It is best to have one thread for tracking a particular feature. Any updates/progress will be posted there.

**Closed by nikitamaia** 2020-12-18 00:08 UTC
Labels: comp:dist-strat, comp:tpus, type:feature
