### ISSUE TITLE
48584629.0这个浮点数数据类型转换精度丢失

### ISSUE THREAD

**Issue by HelloWorld19930113** [tensorflow/tensorflow#50889] opened 2021-07-22 01:43 UTC
tf.cast(48584629.0,tf.float64)  转换后变成48584628

**Comment by tilakrayal** [comment] 2021-07-22 10:40
@HelloWorld19930113 ,

Looks like this is duplicate of issue #50888.Can you please close this issue, since it is already being tracked there? Thanks!

**Closed** 2021-08-06 16:05 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:ops
