### ISSUE TITLE
2.0 Reference Models: Keras Application Set (1 GPU)

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25341] opened 2019-01-31 01:24 UTC
Keras Applications is the `applications` module of the Keras deep learning library. It provides model definitions and pre-trained weights for a number of popular architectures, such as VGG16, ResNet50, Xception, MobileNet, and more.

The purpose of this issue is to migrate models into the TF 2.0 Keras API. Each migrated model must be eager and distribution compatible, with tests, and all associated engineering artifacts.

For more information on tf.keras.applications, check [here](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/applications).

**Comment by dynamicwebpaige** [comment] 2019-02-02 07:35
@Worthy7 You should still be able to use Keras in the nightly GPU preview of TF 2.0; full API reference docs are listed [here](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf).

Which version is listed when you try `tf.__version__`?

**Comment by Worthy7** [comment] 2019-02-02 09:59
![image](https://user-images.githubusercontent.com/4762399/52162808-85457500-271c-11e9-822b-500df7b9c4a8.png)

Do I need to ALSO have tf-nightly normal installed too? I thought CPU and GPU were standalone packages?

![image](https://user-images.githubusercontent.com/4762399/52162817-a5753400-271c-11e9-90a0-1fa17997ba71.png)

**Comment by Worthy7** [comment] 2019-02-06 01:41
It seems my notebook was in some kind of corrupt state with me installing/removing packages.
In the end I think this issue was ultimately caused by a combination of me not having Cuda 10 properly set up, and other versions of tf being held in python memory/not uninstalled properly.

**Comment by dynamicwebpaige** [comment] 2019-02-06 05:53
@Worthy7 - Glad to hear it, and sorry for the frustration! Is everything working as expected now?

**Comment by Worthy7** [comment] 2019-02-06 06:01
Actually no, I tried to install this on a different machine, and I can't
even get the package because it seems to perhaps be lacking some
dependencies? AFAIK, tf-nightly-2-gpu-preview only needs the estimator 2.0
package right?
Because I get this error:

`Could not install packages due to an EnvironmentError: [Errno 2] No such
file or directory:
'C:\\Users\\Ian\\AppData\\Local\\Temp\\pip-install-5nwjiit3\\tf-nightly-gpu-2.0-preview\\tf_nightly_gpu_2.0_preview-2.0.0.dev20190205.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h'`

>

**Comment by Worthy7** [comment] 2019-02-06 06:01
Actually no, I tried to install this on a different machine, and I can't
even get the package because it seems to perhaps be lacking some
dependencies? AFAIK, tf-nightly-2-gpu-preview only needs the estimator 2.0
package right?
Because I get this error:

`Could not install packages due to an EnvironmentError: [Errno 2] No such
file or directory:
'C:\\Users\\Ian\\AppData\\Local\\Temp\\pip-install-5nwjiit3\\tf-nightly-gpu-2.0-preview\\tf_nightly_gpu_2.0_preview-2.0.0.dev20190205.data/purelib/tensorflow/include/tensorflow/include/external/eigen_archive/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h'`

**Comment by dynamicwebpaige** [comment] 2019-02-06 06:08
@Worthy7 - Could you try this [solution](https://github.com/tensorflow/tensorflow/issues/24886) that worked for another user and let us know? Sometimes there are path length limits on Windows.

**Comment by Worthy7** [comment] 2019-02-06 06:38
That fixed it! Thanks @dynamicwebpaige. 
Now.. I did actually get the same issue again as I had originally. It seems that just the Tensorflow namespace exists (so it imports) but there are no functions (so I couldn't even run __version__).

I reinstalled the packages after removing anything else related to tf, and it seems to be working again.

**Comment by dynamicwebpaige** [comment] 2019-02-06 07:03
@Worthy7 Excellent! Feel free to reach out by email if you run into any other snags. 😄

**Comment by Worthy7** [comment] 2019-04-01 23:19
After reinstalling things the right way, you might find it simply doesn't
work because of some kind of cache somewhere (it seems).

I had to restart jupyter to see the changes to my packages sometimes.

**Comment by dorian821** [comment] 2019-04-02 10:31
Thanks, turns out the workaround suggested here doesn't work on Windows 7.  I attempted the solution suggested in the link below, but encountered another path error. Looks like I'll have to switch to Windows 10.

https://github.com/tensorflow/tensorflow/issues/24834

**Comment by kumariko** [comment] 2021-12-01 11:50
@dynamicwebpaige We are checking to see if you still need help on this issue. There is a high possibility that this was fixed with later TF versions. We recommend that you upgrade to 2.7 which is latest stable version of TF and let us know if the issue still persists in newer versions. Thanks!

**Closed** 2021-12-20 08:05 UTC
Labels: stat:awaiting response, type:feature, stalled, TF 2.0
