### ISSUE TITLE
Issue with tf.tpu.experimental.initialize_tpu_system in Google Colab

### ISSUE THREAD

**Issue by tunlee-koh** [tensorflow/tensorflow#29474] opened 2019-06-06 03:49 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave 10.14.4
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below): 2.0
- Python version: 3.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
```
import os
import pprint

if 'COLAB_TPU_ADDR' not in os.environ:
  print('ERROR: Not connected to a TPU runtime; please see the first cell in this notebook for instructions!')
else:
  tpu_address = 'grpc://' + os.environ['COLAB_TPU_ADDR']
  print ('TPU address is', tpu_address)
  
tf.config.experimental_connect_to_host(tpu_address)

cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=tpu_address)
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)
```

**Describe the expected behavior**
I get this error on the line - tf.tpu.experimental.initialize_tpu_system(cluster_resolver)

> NotFoundError: No registered 'ConfigureDistributedTPU' OpKernel for TPU_SYSTEM devices compatible with node {{node ConfigureDistributedTPU}}
> 	.  Registered:  <no registered kernels>
> 
> 	 [[{{node ConfigureDistributedTPU}}]]
> Additional GRPC error information:
> {"created":"@1559792051.046310667","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"No registered 'ConfigureDistributedTPU' OpKernel for TPU_SYSTEM devices compatible with node {{node ConfigureDistributedTPU}}\n\t.  Registered:  <no registered kernels>\n\n\t [[{{node ConfigureDistributedTPU}}]]","grpc_status":5} [Op:__inference__tpu_init_fn_68]

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by tunlee-koh** [comment] 2019-06-06 09:19
In addition, I get a similar error when I try to run it with GPU. With all GPU-specific changes necessary, I am getting this error when I run it with GPU:

> NotFoundError: No registered 'TensorDataset' OpKernel for GPU devices compatible with node {{node TensorDataset}}
	.  Registered:  device='CPU'

**Comment by saberkun** [comment] 2019-06-08 05:29
Hello, this error should be a basic issue that your Cloud TPU version is too old that does not contain the particular kernel you need. Could you try to contact Cloud TPU account team or raise an issue in https://github.com/tensorflow/tpu? I think you will need a tf 1.14 TPU at least (or tf-nightly), as it is close to tf 2.0 beta.

**Comment by gadagashwini** [comment] 2019-06-14 10:05
I could reproduce the above issue with Tensorflow 2.0.0.alpha0 on colab. Thanks!

**Comment by gadagashwini** [comment] 2019-06-19 10:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-19 10:16 UTC
Labels: 2.0.0-alpha0, comp:tpus, stat:awaiting response, type:bug/performance
