### ISSUE TITLE
Problem installing demo app on Android Studio because of Bazel

### ISSUE THREAD

**Issue by riyasinha** [tensorflow/tensorflow#17999] opened 2018-03-26 10:46 UTC
Hi I am trying to build the demo project on my linux pc and am getting this error. I opened the project after from the examples folder from the tensor flow library.

ERROR: /home/riya/.cache/bazel/_bazel_riya/e4d251743a4c03f32e2f3f7357bd97d7/external/bazel_tools/tools/android/BUILD:288:1: Executing genrule @bazel_tools//tools/android:no_android_sdk_repository_error failed (Exit 1)
This build requires an Android SDK. Please add the android_sdk_repository rule to your WORKSPACE.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 84.049s, Critical Path: 0.35s
FAILED: Build did NOT complete successfully

In my Android project I am getting the same error as this :
Error:Execution failed for task ':buildNativeBazel'.

A problem occurred starting process 'command '/usr/local/bin/bazel''

**Comment by tensorflowbutler** [comment] 2018-03-26 22:06
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by riyasinha** [comment] 2018-03-27 18:22
Apologies for the same
Have I written custom code :  I am trying to just run the demo project
OS Platform and Distribution : Linux Ubuntu 16.04
TensorFlow installed from : tensorflow github repository
Bazel version : Build label: 0.11.1

**Comment by poxvoculi** [comment] 2018-04-02 23:27
Are you following all the instructions at:
https://www.tensorflow.org/mobile/android_build

the error message suggests that either you have not installed the Android SDK or you haven't updated the WORKSPACE file with its location.

**Comment by poxvoculi** [comment] 2018-04-17 16:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by poxvoculi** 2018-04-17 16:27 UTC
Labels: stat:awaiting response
