### ISSUE TITLE
Tensorflow on Jetson TX2's performance suddenly decrease, don't know reason 

### ISSUE THREAD

**Issue by theiron97** [tensorflow/tensorflow#30868] opened 2019-07-19 04:11 UTC
A week ago, I run my face-id project, that achieved 7fps, but now, after one week, I dont know why my project just achieve 3-4 fps, I dont modify source code and any dependency library.

**Project**: Face-Id based on Tensorflow (FaceNet)
**OS**: Ubuntu 16.04
**Board**: Jetson TX2
**Cuda/CuDNN**: 9.0/7.1.5.14
**Tensorflow**: 1.9.0

**Comment by gadagashwini** [comment] 2019-07-22 08:22
@theiron97 In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-07-29 05:21
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-29 05:21 UTC
Labels: comp:model, stat:awaiting response, type:support
