### ISSUE TITLE
tf.TensorShape equality comparison can return True for non-fully defined shapes

### ISSUE THREAD

**Issue by leandro-gracia-gil** [tensorflow/tensorflow#17593] opened 2018-03-09 16:12 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, but trivial one-liner code.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: platform independent problem
- **TensorFlow installed from (source or binary)**: either
- **TensorFlow version (use command below)**: v1.6.0-0-gd2e24b6039 1.6.0
- **Python version**:  tested in 3.5 and 3.6
- **Bazel version (if compiling from source)**: not relevant
- **GCC/Compiler version (if compiling from source)**: not relevant
- **CUDA/cuDNN version**: not relevant
- **GPU model and memory**: not relevant
- **Exact command to reproduce**: see source one-liner below

### Describe the problem
tf.TensorShape equality comparison is designed to return None if any of its dimensions has a value of None. However, there is one case when this behavior fails and returns True when it shouldn't.

### Source code / logs
```python
dim = tf.Dimension(None)
tf.TensorShape(dim) == tf.TensorShape(dim) # Returns True instead of None.
tf.TensorShape([None]) == tf.TensorShape([None]) # Correctly returns None.
```

This can, of course, inadvertently appear in more complex shape manipulation codes and lead to unexpected results.

A bit of debugging suggests that if the dimension objects inside the TensorShape have the same id, they are skipped when invoking `tf.Dimension.__eq__`. This might be because dimension comparison is triggered through the list containing them rather than individually iterating them.

**Comment by yongtang** [comment] 2018-03-10 00:49
In the implementation of `tf.Dimension`, I could see the return value will be None for `==` if any of the dimensions compared is None. However, I couldn't find any reference pointing to the same behavior of TensorShape. Not sure if None should be returned for '==' against TensorShape.

I did find an issue related to the equality of TensorShape and that is related to the issue mentioned here:
```
# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.TensorShape([None]) == tf.TensorShape([None])
False
>>> tf.TensorShape([tf.Dimension(None)]) == tf.TensorShape([tf.Dimension(None)])
False
>>> dim = tf.Dimension(None)
>>> tf.TensorShape([dim]) == tf.TensorShape([dim])
True
>>> 
```

The inconsistency is caused by the implementation in `as_dimension` where dimension is directly assigned. Created a PR #17607 so that a copy of the value is performed (so that id will differ) to fix this issue.

**Comment by angersson** [comment] 2018-03-10 02:08
Looks like @yongtang is on this -- I'll assign the issue to him. Thanks Yong!

**Comment by tensorflowbutler** [comment] 2018-03-25 03:44
Nagging Assignee @yongtang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-08 18:30
Nagging Assignee @yongtang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-23 18:42
Nagging Assignee @yongtang: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment] 2018-04-23 18:50
The PR #17607 is pending review. Will update the status once PR #17607 is merged.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:02
Nagging Assignee @yongtang: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-26 18:50
Nagging Assignee @yongtang: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:55
Nagging Assignee @yongtang: It has been 47 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:17
Nagging Assignee @yongtang: It has been 62 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:08
Nagging Assignee @yongtang: It has been 77 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 19:02
Nagging Assignee @yongtang: It has been 92 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:05
Nagging Assignee @yongtang: It has been 107 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:47
Nagging Assignee @yongtang: It has been 122 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yongtang** [comment] 2018-08-24 21:55
See related discussion:
https://github.com/tensorflow/tensorflow/pull/17607#issuecomment-415445235
I think this issue could be closed as it is expected behavior.

**Closed by yongtang** 2018-08-24 21:55 UTC
