### ISSUE TITLE
image restauration

### ISSUE THREAD

**Issue by 2017develper** [tensorflow/tensorflow#18115] opened 2018-03-30 09:05 UTC

**Comment by tensorflowbutler** [comment] 2018-03-30 18:46
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-04-15 18:26
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-30 18:45
It has been 30 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by tatianashp** [comment] 2018-05-03 05:29
Closing due to lack of information - the issue is empty.

**Closed by tatianashp** 2018-05-03 05:29 UTC
Labels: stat:awaiting response
