### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras' has no attribute 'Model' #21927

### ISSUE THREAD

**Issue by VertexC** [tensorflow/tensorflow#29377] opened 2019-06-04 00:32 UTC
The same issue was closed #21927. May not get attention due to that.

**System information**
- Have I written custom code No
- OS Platform and Distribution: Ubuntu 16.04.3 LTS
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 1.40
- Python version: 3.6

**Describe the current behavior**
```bash
Traceback (most recent call last):
  File "model_keras.py", line 21, in <module>
    class sequentialLSTM(tf.keras.Model):
AttributeError: module 'tensorflow.python.keras' has no attribute 'Model'
```

**Comment by gadagashwini** [comment] 2019-06-05 06:01
@VertexC In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by VertexC** [comment] 2019-06-05 23:12
simply do `import tensorflow.keras.Model`

**Comment by gadagashwini** [comment] 2019-06-06 05:26
@VertexC Tensorflow keras model can be imported as 
```
import tensorflow as tf
tf.keras.Model()
```
Let us know if that solves the problem. Thanks!

**Comment by gadagashwini** [comment] 2019-06-14 05:09
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-06-14 05:09 UTC
Labels: comp:keras, stat:awaiting response

**Comment by shubhamgaygol** [comment] 2021-08-08 14:11
AttributeError: module 'tensorflow.keras.models' has no attribute 'Sequencial'
