### ISSUE TITLE
GPU Host To Device copies don't appear to respect GPU operation dependencies

### ISSUE THREAD

**Issue by sjperkins** [tensorflow/tensorflow#2848] opened 2016-06-14 09:34 UTC
I've been trying out the fancy new [tracing](http://stackoverflow.com/a/37774430/1611416) functionality in the Tensorflow nightlies. It's really great, thanks for providing it!

One thing I noticed while [enqueueing](https://github.com/ska-sa/montblanc/blob/29b264ee114a6ef63159808125b1a4505cc5ffa2/montblanc/tensorflow/rime_ops/test_all.py#L66-L127) multiple GPU operations with `tf.control_dependencies` is that Host to Device memory copies for the inputs of consecutive GPU ops can be scheduled in an interleaved pattern, instead of consecutively. In my case I have something like this:
1. op EBeam with inputs: ebeam
2. op SumCoherencies with inputs: gterm, ant2, model_vis, flag, ant1, ant2

but in the [trace](https://github.com/tensorflow/tensorflow/files/313540/timeline.json.zip) I see the memory copies scheduled as:
- ant1, flag, **ebeam**, gterm, ant2, model_vis

when I would expect, due to the the consecutive scheduling of EBeam and SumCoherencies ops, that the memory copies would be scheduled as:
- **ebeam**, ant1, flag,  gterm, ant2, model_vis

I also notice that the EBeam op only starts executing on the GPU after all the SumCoherencies inputs have been copied to the GPU (rather than just the ebeam input) so the GPU is idle. There is no dependency on SumCoherencies by EBeam (Its the other way round).

_There are several other ops and inputs that I haven't mentioned for the sake of brevity_
### Environment info

Operating System: `Ubuntu 14.04.4`

Installed version of CUDA and cuDNN: `CUDA 7.5 and cuDNN 4.0.7`
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

``` bash
~$ ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root    322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root        16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root        19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root    383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root    720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 3319 users       13 Feb  9 19:48 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.4
lrwxrwxrwx 1 3319 users       17 Feb  9 19:48 /usr/local/cuda/lib64/libcudnn.so.4 -> libcudnn.so.4.0.7
-rwxrwxr-x 1 3319 users 61453024 Feb  9 00:12 /usr/local/cuda/lib64/libcudnn.so.4.0.7
-rw-rw-r-- 1 3319 users 62025862 Feb  9 00:12 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:
1. Which pip package you installed. `python 2 GPU nightly`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. `0.8.0`

If installed from sources, provide the commit hash: **N/A**
### Steps to reproduce
1. Ran [this](https://github.com/ska-sa/montblanc/blob/29b264ee114a6ef63159808125b1a4505cc5ffa2/montblanc/tensorflow/rime_ops/test_all.py#L66-L127) script. (If necessary, source with Makefile is [here](https://github.com/ska-sa/montblanc/tree/29b264ee114a6ef63159808125b1a4505cc5ffa2/montblanc/tensorflow/rime_ops) and relevent commit is [29b264ee](https://github.com/ska-sa/montblanc/tree/29b264ee114a6ef63159808125b1a4505cc5ffa2))
2. Inspected the timeline ([timeline.json.zip](https://github.com/tensorflow/tensorflow/files/313540/timeline.json.zip)) in `chrome://tracing/`
### What have you tried?
1. Using `tf.control_dependencies` to modify op execution order
### Logs or other output that would be helpful

(If logs are large, please upload as attachment).

**Comment by prb12** [comment] 2016-06-14 17:46
This is indeed the expected behavior.   Control dependencies only constrain the order of evaluation of ops.  The device to host memcpy operations are executed as _Send/_Recv ops which are automatically inserted when the graph is partitioned between cpu and gpu devices.  

The _Recv ops  have zero inputs and so are schedulable immediately.  The _Send ops (and hence the transfers) are schedulable as soon as the input data has been produced (in this case by Identity ops with names like 'variable/read' which take a single "snapshot" of each variable).  

The order that the transfers happen _should_ have no influence on the result of the computation - but, in this case, do appear to have a significant impact on latency.  (You appear to have some *huge* transfers!)

In the distributed setting, GraphOptions.enable_recv_scheduling can be used to constrain the order of _Recv nodes.  However, this doesn't currently influence intra-machine transfers.

If you really care about hand-constraining the order of the GPU transfers, you could *probably* write something using a bunch of _additional_ identity ops on the cpu and gpu device and explicitly put control dependencies on these.   

@yuanbyu  might have more to say on this issue?

**Comment by sjperkins** [comment] 2016-06-14 20:42
@prb12 Thanks for the detailed feedback, its very helpful for understanding Tensorflow's transfer handling.

> The order that the transfers happen should have no influence on the result of the computation - but, in this case, do appear to have a significant impact on latency. (You appear to have some huge transfers!)

I think it's highly dependent on an algorithm's compute to I/O ratio -- Transfers don't matter much if one is performing a lot of GPU compute for a small amount of input data. As this ratio decreases one wants to ensure that one's data transfers overlap compute in order to maximise device usage. For instance, Gregg and Hazelwood have devised a [taxonomy](http://www.cs.virginia.edu/kim/docs/ispass11.pdf) for classifying GPU algorithms according to these properties.

But I suspect I'm preaching to the converted here ;-). Similar principles probably apply  to Google's bread and butter:  scheduling RPC network transfers and its encouraging to hear about the **enable_recv_scheduling** option. I'll have a look at `tf.identity` -- there is a nice  [stackoverflow](http://stackoverflow.com/a/34877802/1611416) answer for other's looking at this issue.

Having said that,  would there be scope for improving the scheduling of intra-machine send/recv ops?

**Comment by prb12** [comment] 2016-06-14 23:54
> Having said that, would there be scope for improving the scheduling of intra-machine send/recv ops?

In the general case, doing a good job of this requires having an accurate cost model including the computation cost of ops and the shapes of all Tensors.  In the presence of custom ops and dynamically fed tensors (whose shape we often don't know until runtime), there is a lot of missing information.  Even in the presence of full information, computing a good schedule is an expensive algorithm which needs to trade off a lot of variables (e.g. peak GPU memory usage, critical path latency, potential concurrency)  

Having said that, there are probably a bunch of fairly simple heuristics which may work well in simple cases like this...

**Comment by drpngx** [comment] 2017-01-23 23:32
Closing this since it has been a while and the code might have changed. Feel free to open a new issue if the problem persists with new code.

**Closed by drpngx** 2017-01-23 23:32 UTC
Labels: enhancement
