### ISSUE TITLE
[r2.0.0-rc1] Converting to TFLite format: Invalid quantization params for op RESHAPE

### ISSUE THREAD

**Issue by grwlf** [tensorflow/tensorflow#32495] opened 2019-09-13 13:02 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 18.04.2 LTS**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): **Source**
- TensorFlow version (use command below): **2.0.0-rc1 commit 59bf33**
- Python version: 3.6.8
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.0.130
- GPU model and memory: NVidia 1080Ti / 11G

**Describe the current behavior**

Conversion of TF2.0 function containing `softmax` and `reshape` ops to TFLite format fails with the following RuntimeError. Source code of the program is listed in the `Code` section below.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-ec9775ede022> in <module>
----> 1 run()

~/mironov/hbtest/tflite_softmax_bug_v2.py in run()
     20   converter.optimizations = [tf.lite.Optimize.DEFAULT]
     21
---> 22   tflite_model = converter.convert()
     23   model_file = "/tmp/tflite_softmax_bug_v2.tflite"
     24   open(model_file, "wb").write(tflite_model)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py in convert(self)
    448     if self._is_calibration_quantize():
    449       result = self._calibrate_quantize_model(result, constants.FLOAT,
--> 450                                               constants.FLOAT)
    451
    452     return result

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py in _calibrate_quantize_model(self, result, inference_input_type, inference_output_type)                                                                             
    237     return calibrate_quantize.calibrate_and_quantize(
    238         self.representative_dataset.input_gen, inference_input_type,
--> 239         inference_output_type, allow_float)
    240
    241   def _get_base_converter_args(self):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/optimize/calibrator.py in calibrate_and_quantize(self, dataset_gen, input_type, output_type, allow_float)                                                                   
     76     return self._calibrator.QuantizeModel(
     77         np.dtype(input_type.as_numpy_dtype()).num,
---> 78         np.dtype(output_type.as_numpy_dtype()).num, allow_float)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py in QuantizeModel(self, input_py_type, output_py_type, allow_float)                                                     
    113
    114     def QuantizeModel(self, input_py_type, output_py_type, allow_float):
--> 115         return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)                                                                                            
    116 CalibrationWrapper_swigregister = _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_swigregister
    117 CalibrationWrapper_swigregister(CalibrationWrapper)

RuntimeError: Invalid quantization params for op RESHAPE at index 1 in subgraph 0

```

**Describe the expected behavior**

`converter.convert()` call finishes without errors

**Code to reproduce the issue**

File: `tflite_softmax_bug_v2.py`
```
import tensorflow as tf
import numpy as np

@tf.function(input_signature=[
    tf.TensorSpec(shape=[10], dtype=tf.float32, name='inp0')])
def model(inp0):
  res = tf.nn.softmax(inp0)
  res = tf.reshape(res, [1, 10])
  print(res.shape)
  return res

def run():
  def _representative_dataset_gen():
    for i in range(10):
      yield [np.random.random_integers(0, 9, size=[10]).astype('float32'),]

  cfunc = model.get_concrete_function()
  converter = tf.lite.TFLiteConverter.from_concrete_functions([cfunc])
  converter.representative_dataset = _representative_dataset_gen
  converter.optimizations = [tf.lite.Optimize.DEFAULT]

  tflite_model = converter.convert()
  model_file = "/tmp/tflite_softmax_bug_v2.tflite"
  open(model_file, "wb").write(tflite_model)

  interpreter = tf.lite.Interpreter(model_path=model_file)
  interpreter.allocate_tensors()

if __name__ == '__main__':
  run()

```

**Other info / logs**
N/A

**Comment by paanguin** [comment] 2019-09-26 00:59
The error can be also reproduced in  tensorflow nightly gpu version 1.15,
```
2019-09-26 09:57:52.194571: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:786] Optimization results for grappler item: graph_to_optimize
2019-09-26 09:57:52.194601: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 4 nodes (-1), 3 edges (0), time = 1.698ms.
2019-09-26 09:57:52.194611: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:788]   constant_folding: Graph size after: 4 nodes (0), 3 edges (0), time = 0.198ms.
Traceback (most recent call last):
  File "tflite_softmax_bug_v1.py", line 33, in <module>
    tflite_model = converter.convert()
  File "/home/hh1208-kang/venv_py2_tf_nightly/local/lib/python2.7/site-packages/tensorflow_core/lite/python/lite.py", line 993, in convert
    inference_output_type)
  File "/home/hh1208-kang/venv_py2_tf_nightly/local/lib/python2.7/site-packages/tensorflow_core/lite/python/lite.py", line 239, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/home/hh1208-kang/venv_py2_tf_nightly/local/lib/python2.7/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 78, in calibrate_and_quantize
    np.dtype(output_type.as_numpy_dtype()).num, allow_float)
  File "/home/hh1208-kang/venv_py2_tf_nightly/local/lib/python2.7/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)
RuntimeError: Invalid quantization params for op RESHAPE at index 1 in subgraph 0
```
with this code.

```
import tensorflow as tf
import numpy as np


export_dir = 'test_saved_model'
builder = tf.saved_model.builder.SavedModelBuilder(export_dir)

ipts = tf.placeholder(dtype=tf.float32, shape=(10), name='x')
res = tf.nn.softmax(ipts)
res = tf.reshape(res, [1, 10])
print(res.shape)

def _representative_dataset_gen():
    for i in range(10):
      yield [np.random.random_integers(0, 9, size=[10]).astype('float32'),]



with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())

	builder.add_meta_graph_and_variables(sess, ["test"])
	builder.save(as_text=True)
	
	converter = tf.lite.TFLiteConverter.from_session(sess, [ipts], [res])

	converter.representative_dataset = _representative_dataset_gen
	converter.optimizations = [tf.lite.Optimize.DEFAULT]
	
	tflite_model = converter.convert()
```

It seems that the converter try to "quantize" the input 1, the op RESHAPE, I guess.
```
Inputs {
  0: Softmax, float[10]
  1: shape, int32[2] = {1, 10}
}
Outputs {
  0: Reshape, float[1x10]
}
Options {
  new_shape
}
```

**Comment by paanguin** [comment] 2019-09-26 06:24
Firstly, the converter set the quantization parameters of the output tensor of SOFTMAX op. Let's name it as A. The quantization parameter of the tensor A is set to {scale 0.003906, zp -128.000000}. But min and max are not set.

When the converter tries to quantize the output tensor of the RESHAPE op, which follows the SOFTMAX op, it reads the tensor A as the input tensor. It tries to use the quantization parameters of tensor A, however, it fails since the min and max of the tensor A is not set.

**Comment by paanguin** [comment] 2019-09-26 07:22
I was currently working with modifying the tensorflow r1.14 version. Thus I'm not sure about other versions. 

When I changed the following code 
https://github.com/tensorflow/tensorflow/blob/be5eb917fdea8a99ec8d5eb9428f2e8866858560/tensorflow/lite/tools/optimize/quantize_model.cc#L550

```
  } else if (tensor_property.restriction) {
    const auto scale_and_zp = tensor_property.restricted_value;
    // Apply to output.
    output_tensor->quantization = absl::make_unique<QuantizationParametersT>();
    output_tensor->quantization->scale.push_back(scale_and_zp.first);
    output_tensor->quantization->zero_point.push_back(scale_and_zp.second);
    output_tensor->type = TensorType_INT8;
  } else {
```
as
```
  } else if (property.restriction_on_output) {
    const auto scale_and_zp = property.restricted_value_on_output;
    // Apply to output.
    output_tensor->quantization = absl::make_unique<QuantizationParametersT>();
    output_tensor->quantization->scale.push_back(scale_and_zp.first);
    output_tensor->quantization->zero_point.push_back(scale_and_zp.second);
    output_tensor->type = TensorType_INT8;

    const int input_index = op->inputs[property.input_indexes[0]];
    TensorT* input_tensor = subgraph->tensors[input_index].get();   
    output_tensor->quantization->min.push_back(input_tensor->quantization->min[0]);
    output_tensor->quantization->max.push_back(input_tensor->quantization->max[0]);
  } else {
```
the converter completed the converting. However, I'm not sure this is safe or not.

**Comment by paanguin** [comment] 2019-10-02 02:31
Considering the tensorflow quantization specification (https://www.tensorflow.org/lite/performance/quantization_spec), 
```
SOFTMAX
  Input 0:
    data_type  : int8
    range      : [-128, 127]
    granularity: per-tensor
  Output 0:
    data_type  : int8
    range      : [-128, 127]
    granularity: per-tensor
    restriction: (scale, zero_point) = (1.0 / 256.0, -128)
```
it seems better to use fixed min/max values as follows, rather than using the same min/max from the input tensor.
```
    const float scale = output_tensor->quantization->scale[0];
    const int32_t zp = output_tensor->quantization->zero_point[0];
    float min = (-128 - zp) * scale;
    float max = (127 - zp) * scale;
    output_tensor->quantization->min.push_back(min);
    output_tensor->quantization->max.push_back(max);
    printf("scale=%g, zero_point=%d, min=%g, max=%g\n",
    output_tensor->quantization->scale[0], output_tensor->quantization->zero_point[0],
    output_tensor->quantization->min[0], output_tensor->quantization->max[0]);
```

**Comment by paanguin** [comment] 2019-10-10 09:40
Just a little update.
I'm working with the v2.0.0, and I think that following one line modification seems better.
https://github.com/tensorflow/tensorflow/blob/64c3d382cadf7bbe8e7e99884bede8284ff67f56/tensorflow/lite/tools/optimize/quantize_model.cc#L528
```
    //output_tensor->quantization = absl::make_unique<QuantizationParametersT>();
    if (!output_tensor->quantization){
        output_tensor->quantization = absl::make_unique<QuantizationParametersT>();
    }
```
When I checked my model, it seems that tensors have min/max parameters of their own. So it seems enough to prevent the initialization of the quantization parameter, when it already had been initialized.

**Comment by dreamibor** [comment] 2019-10-16 12:46
How is it going for now?

**Comment by paanguin** [comment] 2019-10-16 12:57
> How is it going for now?
Continued in this issue
https://github.com/tensorflow/tensorflow/issues/33233

**Comment by Oktai15** [comment] 2020-02-04 06:52
Any update about this issue? Reshape is very common operation in TFLite -- very strange to see that this problem is just skipped by Tensorflow Team about six months...

**Comment by InSightSuen** [comment] 2020-05-15 10:15
I have a similar problem, my model used MobileNet. When trying to optimize to int8 model under TF2.0, it raise: 

**return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, input_py_type, output_py_type, allow_float)
RuntimeError: Invalid quantization params for op RESHAPE at index 22 in subgraph 0**

After chaning to **TF2.1**, the error not rasized. And the output of tflite is correct.

**Comment by lubo92** [comment] 2020-09-22 14:12
We struggled in tensorflow-gpu 2.0.0 also with this bug. For us, the issue was resolved with an update from version 2.0.0 to 2.2.0.

**Comment by tensorflowbutler** [comment] 2021-06-10 18:14
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by Saduf2019** [comment] 2021-06-22 10:54
@grwlf 
Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.

**Closed** 2021-07-22 11:50 UTC
Labels: TF 2.0, comp:lite, stalled, stat:awaiting response, stat:awaiting tensorflower, type:bug
