### ISSUE TITLE
Issue with AttentionWrapper and non unique key dictionary in feed_dict

### ISSUE THREAD

**Issue by virginie-do** [tensorflow/tensorflow#30901] opened 2019-07-20 18:45 UTC
Hello,

I would like to use Bahdanau Attention in a decoder, using tf.dynamic_rnn

For my decoder, I am feeding the previous state of AttentionWrapperState at each time step.

~~~
    attn_meca = tf.contrib.seq2seq.BahdanauAttention(config.num_lstm_units, multimodal_feature)   
    attn_cell = tf.contrib.seq2seq.AttentionWrapper(lstm_cell_expl, attn_meca, output_attention=False)
    
...

        lstm_outputs, final_state = tf.nn.dynamic_rnn(cell=attn_cell,
                                                    inputs=seq_embedding,
                                                    sequence_length=sequence_length,
                                                    initial_state=initial_state,
                                                    dtype=tf.float32,
                                                    scope=lstm_scope)
~~~

I am feeding the state as follows 
~~~
 feed_dict={model['input_seqs']: current_pred, 
                   model['initial_state']: state, 
                   model['input_mask']: mask, 
                   model['dropout_input']: 1.0,
                   model['keep_prob']: keep_prob}

current_pred, state = sess.run([model['preds'], model['final_state']], feed_dict=feed_dict)
~~~

And I get this error :

`ValueError: Could not flatten dictionary: key Tensor("lstm/lstm/attention_wrapper/Softmax:0", shape=(?, ?), dtype=float32) is not unique.`

I printed the state that I'm feeding:
`AttentionWrapperState(cell_state=LSTMStateTuple(c=<tf.Tensor 'lstm/lstm/attention_wrapper/lstm_cell/add_1:0' shape=(?, 512) dtype=float32>, h=<tf.Tensor 'lstm/lstm/attention_wrapper/lstm_cell/mul_2:0' shape=(?, 512) dtype=float32>), attention=<tf.Tensor 'lstm/lstm/attention_wrapper/concat_1:0' shape=(?, 512) dtype=float32>, time=<tf.Tensor 'lstm/lstm/attention_wrapper/add:0' shape=() dtype=int32>, alignments=<tf.Tensor 'lstm/lstm/attention_wrapper/Softmax:0' shape=(?, ?) dtype=float32>, alignment_history=(), attention_state=<tf.Tensor 'lstm/lstm/attention_wrapper/Softmax:0' shape=(?, ?) dtype=float32>)`

So I see that there are two `'lstm/lstm/attention_wrapper/Softmax:0'`

How can I change that when I define my attention cell?

https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/AttentionWrapperState

Thanks in advance.

**Comment by gadagashwini** [comment] 2019-07-22 06:48
@virginie-do In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thanks!

**Comment by gadagashwini** [comment] 2019-07-29 05:25
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-29 05:25 UTC
Labels: comp:apis, contrib, stat:awaiting response, type:support
