### ISSUE TITLE
Classification signature on tf serving.

### ISSUE THREAD

**Issue by stefanondisponibile** [tensorflow/tensorflow#34968] opened 2019-12-09 16:57 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): `no`
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 18.04`
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: `no`
- TensorFlow installed from (source or binary): `no`
- TensorFlow version (use command below): `2.0.0`
- Python version: `3.7.3`
- Bazel version (if compiling from source): `-`
- GCC/Compiler version (if compiling from source): `-`
- CUDA/cuDNN version: `-`
- GPU model and memory: `-`

**Describe the current behavior**

It seem currently *not* possible to export a `classify` signature to use within `Tensorflow Serving`.

**Describe the expected behavior**
It should be possible to export a `classify` signature to use within `Tensorflow Serving`.
I was able to experience the issue also by exporting directly a `tf.Module` and a subclassed `tf.Model`. In [this](https://github.com/tensorflow/serving/issues/1420#issuecomment-552475340) comment I was also wondering about both the `inference` and `classify` signatures being *deprecated* since it looks like in [_generate_signatures](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/save.py#L466) the `method_name` is assigned to `signature_constants.PREDICT_METHOD_NAME`.

**Code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np

model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, activation="softmax"),
])
model.compile(optimizer="Adam", loss="categorical_crossentropy", metrics=["accuracy"])
X = [0.42]
Y = [[0, 1]]
model.fit(X, Y, epochs=1)
pred_before = model.predict(X)
print(f"*** pred : {pred_before} ***")
model.save("./mymodel/1", save_format="tf")
model = tf.keras.models.load_model("./mymodel/1")
model.predict([X])
print(f"*** signatures : {model.signatures} ***")
pred_after = model([X])
np.testing.assert_almost_equal(pred_before, pred_after)
print(model.predict([X]))
```

```bash
docker run -p 8501:8501 -v /path/to/mymodel:/models/mymodel -e MODEL_NAME=mymodel --name serving_tmp tensorflow/serving
```

```
curl -XPOST http://localhost:8501/v1/models/mymodel:classify -d '{"examples": [{}]}'
# { "error": "Expected classification signature method_name to be tensorflow/serving/classify. Was: tensorflow/serving/predict" }
```

**Other info / logs**
```
{ "error": "Expected classification signature method_name to be tensorflow/serving/classify. Was: tensorflow/serving/predict" }
```

If I modify `tensorflow_core/python/saved_model/save.py@469`
```python
# from
method_name=signature_constants.PREDICT_METHOD_NAME)

# to
method_name=signature_constants.CLASSIFY_METHOD_NAME)
``` 

I'm then able to get what expected:
```
curl -XPOST http://localhost:8501/v1/models/mymodel:classify -d '{"examples": [{}]}'
{ "error": "No classification inputs found in SignatureDef: inputs {\n  key: \"text\"\n  value {\n    name: \"serving_default_text:0\"\n    dtype: DT_FLOAT\n    tensor_shape {\n      dim {\n        size: -1\n      }\n      dim {\n        size: -1\n      }\n    }\n  }\n}\noutputs {\n  key: \"probabilities\"\n  value {\n    name: \"StatefulPartitionedCall_2:0\"\n    dtype: DT_FLOAT\n    tensor_shape {\n      dim {\n        size: -1\n      }\n      dim {\n        size: 99\n      }\n    }\n  }\n}\nmethod_name: \"tensorflow/serving/classify\"\n" }
```

**Comment by amahendrakar** [comment] 2019-12-11 10:33
@stefanondisponibile,

This issue seems to be related to Tensorflow serving, could you please raise an issue in [this repository](https://github.com/tensorflow/serving/issues/new). Thanks!

**Comment by stefanondisponibile** [comment] 2019-12-11 13:25
Thank you @amahendrakar, I'll open one there. I was reporting on this repo since I thought the problem was in the `tf.saved_model.save` function.

**Comment by amahendrakar** [comment] 2019-12-13 11:54
Closing this issue as it is related to TF Serving.

**Comment by stefanondisponibile** [comment] 2019-12-13 18:28
@amahendrakar as @gowthamkpr said on the Tensorflow Serving repo the issue seems related to TensorFlow (not Serving). The problem is that even if it is possible to export a custom signature via `@tf.function` it is **not** possible to define the exported signature's **`method_name`** (as everything's handled by TensorFlow under the hood).

**Comment by santhoshscs** [comment] 2019-12-24 06:33
> @stefanondisponibile,
> 
> This issue seems to be related to Tensorflow serving, could you please raise an issue in [this repository](https://github.com/tensorflow/serving/issues/new). Thanks!

There is already an issue reported #1521 - But it is closed refering that  the issue is to be reported on tensorflow core

**Comment by stefanondisponibile** [comment] 2020-02-17 00:50
Are there any updates on this? 🙂

**Comment by stefanondisponibile** [comment] 2020-02-25 13:04
@santhoshscs the issue is reported here :)

**Comment by ClementWalter** [comment] 2020-03-27 11:23
Is there any update on this topic ? Or any possibility (hack) to update the method_name afterwards?

**Comment by ClementWalter** [comment] 2020-03-27 11:47
This is definitely a bug because from the documentation of `tf.saved_model.save` one has:

> The keys of such a dictionary may be arbitrary strings, but will typically be from the `tf.saved_model.signature_constants` module.

but:

1. tf2.1 does not have such module available but rather I was able to import with `from tensorflow.python.saved_model import signature_constants`
1. setting the name of the signature as indicated in the documentation does not solve the problem (clear reason why when reading the source code though), as show in the example below:

```
> saved_model_cli show --dir my_model/1 --tag_set serve --signature_def tensorflow/serving/classify

The given SavedModel SignatureDef contains the following input(s):
  inputs['crop_window'] tensor_info:
      dtype: DT_INT32
      shape: (-1, 4)
      name: tensorflow/serving/classify_crop_window:0
  inputs['image_bytes'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: tensorflow/serving/classify_image_bytes:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['output_0'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1)
      name: StatefulPartitionedCall_5:0
Method name is: tensorflow/serving/predict
```

**Comment by aybuketurker** [comment] 2020-06-05 03:52
@ClementWalter I am trying to understand the difference between the default method, Predict versus Classify. For your particular use case what is it that not possible to do with Predict so you need Classify. Thank you so much in advance.

**Comment by goldiegadde** [comment] 2020-09-10 22:45
@stefanondisponibile  This function ([tf.compat.v1.saved_model.signature_def_utils.MethodNameUpdater](https://www.tensorflow.org/api_docs/python/tf/compat/v1/saved_model/signature_def_utils/MethodNameUpdater)) was specially added so that there's a way to change predict signatures to classify/regress.

Marking this issue as closed, please reopen if this does not work for you.

**Closed by goldiegadde** 2020-09-10 22:45 UTC
Labels: TF 2.0, comp:keras, type:bug

**Comment by stefanondisponibile** [comment] 2020-09-11 07:12
Awesome! 🥳

**Comment by florence27** [comment] 2020-09-14 13:19
@goldiegadde I'm super glad to hear that the `MethodNameUpdater()` function is available, cause it does exactly what I need. Unfortunately, I'm not able to use it (getting an `AttributeError`). Here's my setup: 

OS Platform: macOS Catalina, Version 10.15.5
Tensorflow Version: 2.3.0
Python Version: 3.7.9

Would be very happy about any help with this!

**Comment by goldiegadde** [comment] 2020-09-14 16:28
@florence27 can you please report a new issue along with the complete  code to reproduce the error that is not working and cc me on it as well. 
Thanks, 
Goldie
