### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by SlowMonk** [tensorflow/tensorflow#28108] opened 2019-04-24 09:46 UTC
'''
Generator 
'''
class Generator(tf.keras.Model):
    def __init__(self, input_shape=128):
        super(Generator, self).__init__()
        
        self.input_shape = input_shape
        self.conv = tf.keras.layers.Conv2D(64,(7,7), padding='same')
        #~ down sampling
        self.down = Downsampling_Part()
        
        
        #ResBlock
        self.res1 = ResBlock(256,(3,3))
        self.res2 = ResBlock(256,(3,3))
        self.res3 = ResBlock(256,(3,3))
        self.res4 = ResBlock(256,(3,3))
        self.res5 = ResBlock(256,(3,3))
        self.res6 = ResBlock(256,(3,3))
        
        # ~Up sampling
        self.upsampleblock = UpSampleBlock()
        
    def call(self, images, labels, training):
        # Down - sampling
        x = input_merge(images,labels)
        out = self.down(x);
        
        # Bottleneck
        out = self.res1(out, training=training)
        out = self.res2(out, training=training)
        out = self.res3(out, training=training)
        out = self.res4(out, training=training)
        out = self.res5(out, training=training)
        out = self.res6(out, training=training)
        
        #Up sampling
        out= self.upsampleblock(out)
        
        generated_images =  out
        
        return out

=======================================

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-569e07e14531> in <module>()
----> 1 Gen = Generator()

2 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __setattr__(self, name, value)
   1778         # Exclude @property.setters from tracking
   1779         hasattr(self.__class__, name)):
-> 1780       super(Layer, self).__setattr__(name, value)
   1781       return
   1782 

AttributeError: can't set attribute

**Comment by allenlavoie** [comment] 2019-04-24 23:58
I'm going to add a better error message and close this. The issue is that Model has a `@property` named `input_shape` which is read-only.

**Closed** 2019-04-25 00:45 UTC
