### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'

### ISSUE THREAD

**Issue by Mathias-Godwin** [tensorflow/tensorflow#45954] opened 2020-12-24 06:29 UTC
c:\users\gwinivac\.conda\envs\chatboty\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
c:\users\gwinivac\.conda\envs\chatboty\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
c:\users\gwinivac\.conda\envs\chatboty\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
c:\users\gwinivac\.conda\envs\chatboty\lib\importlib\_bootstrap.py:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gwinivac\.conda\envs\chatboty\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\rasa\__main__.py", line 115, in main
    rasa.telemetry.initialize_error_reporting()
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\rasa\telemetry.py", line 230, in decorated
    return f(*args, **kwargs)
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\rasa\telemetry.py", line 651, in initialize_error_reporting
    default_context = _default_context_fields()
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\rasa\telemetry.py", line 480, in _default_context_fields
    "gpu": len(tf.config.list_physical_devices("GPU")),
  File "c:\users\gwinivac\.conda\envs\chatboty\lib\site-packages\tensorflow_core\python\util\module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'

running on:
tensorflow version: 1.15.0
installed using conda

**Comment by amahendrakar** [comment] 2020-12-24 12:02
@Mathias-Godwin,
[tf.config.list_physical_devices](https://www.tensorflow.org/api_docs/python/tf/config/list_physical_devices) is a TensorFlow 2.x API, hence you are facing an error while running it on TensorFlow 1.x. Please take a look at [this gist](https://colab.research.google.com/gist/amahendrakar/8f878f458560dd7e00730128dde29fdf/45954.ipynb) for reference. 

Also, I'd suggest you to update TensorFlow to v2.4 as TensorFlow 1.x is not actively supported. Thanks!

**Comment by Mathias-Godwin** [comment] 2020-12-25 11:20
> @Mathias-Godwin,
> [tf.config.list_physical_devices](https://www.tensorflow.org/api_docs/python/tf/config/list_physical_devices) is a TensorFlow 2.x API, hence you are facing an error while running it on TensorFlow 1.x. Please take a look at [this gist](https://colab.research.google.com/gist/amahendrakar/8f878f458560dd7e00730128dde29fdf/45954.ipynb) for reference.
> 
> Also, I'd suggest you to update TensorFlow to v2.4 as TensorFlow 1.x is not actively supported. Thanks!

I found out a temporary solution
https://github.com/RasaHQ/rasa/issues/7634#issue-774259438

**Comment by amahendrakar** [comment] 2020-12-30 17:48
@Mathias-Godwin,
Glad the issue is resolved. Closing the issue, please feel free to re-open if necessary. Thanks!

**Closed by amahendrakar** 2020-12-30 17:48 UTC
Labels: TF 1.15, comp:apis, type:support

**Comment by sachinkmohan** [comment] 2022-01-07 14:19
Use `tf.compat.v1.config.experimental.set_visible_devices` for TF 1.15 or below, instead of `tf.config.set_visible_devices` which is for TF >= 2.0

**Comment by atabak-cve** [comment] 2022-02-28 22:47
On tf 1.15.0 Found it here: `tf.compat.v1.config.experimental.list_physical_devices('GPU')`
