### ISSUE TITLE
Cannot save model when not giving a name in Layer.add_weight call

### ISSUE THREAD

**Issue by arnomoonens** [tensorflow/tensorflow#36962] opened 2020-02-21 16:56 UTC
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): Yes
- OS Platform and Distribution: Manjaro 19.0.0 Kyria
- TensorFlow installed from: binary
- TensorFlow version: 2.1.0 
- Python version: 3.7.4

**Describe the current behavior**
I made a custom `tf.keras.layers.Layer`, where I make my weights in the `build` function using `self.add_weight`. However, I do not pass a name to this function. When I try to save the model that uses the layer, I get an error because the name of the weight is `None` (see traceback below).

**Describe the expected behavior**
I expected that the weight would either get a default name (possibly only upon saving), that I would get an error when calling `add_weight` or that I would get a more informative error when saving the model.

**Standalone code to reproduce the issue** 
```
import tensorflow as tf
class CustomLayer(tf.keras.layers.Layer):
    def build(self, input_shape):
        self.w = self.add_weight(shape=(input_shape[-1], 1))
    def call(self, x):
        return tf.matmul(x, self.w)
inp = tf.keras.Input((5,))
m = tf.keras.Model(inputs=inp, outputs=CustomLayer()(inp))
m.save("/tmp/savedmodel")
```

**Other info / logs**
```
Traceback (most recent call last):
  File "tfbug.py", line 9, in <module>
    m.save("/tmp/savedmodel")
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1008, in save
    signatures, options)
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 115, in save_model
    signatures, options)
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/save.py", line 78, in save 
    save_lib.save(model, filepath, signatures, options)
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 899, in save
    _ = _SaveableView(checkpoint_graph_view)
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/saved_model/save.py", line 165, in __init__
    self.checkpoint_view.objects_ids_and_slot_variables())
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 418, in objects_ids_and_slot_variables
    object_names[obj] = _object_prefix_from_path(path)
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 64, in _object_prefix_from_path
    for trackable in path_to_root))
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 64, in <genexpr>
    for trackable in path_to_root))
  File "/home/arno/conda/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/graph_view.py", line 57, in _escape_local_name
    return (name.replace(_ESCAPE_CHAR, _ESCAPE_CHAR + _ESCAPE_CHAR)
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by ravikyram** [comment] 2020-02-24 10:14
I have tried on colab with TF version 2.1.0 , 2.2.0-dev20200218 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/4157045803a448cc027f1aa58f9b4adb/untitled663.ipynb). Thanks!

**Comment by huonw** [comment] 2020-06-11 23:32
I still see this with TF 2.2.0 (GIT_VERSION: v2.2.0-rc4-8-g2b96f3662b). Even if this didn't work as is (via a default name in `add_weight`, or whatever), a slightly more specific error message would've cut the time it took me to work out the cause dramatically.

**Comment by Saduf2019** [comment] 2020-08-13 14:51
Issue is still reproducible with tf-nightly(2.4.0-dev20200813), please find the [gist here](https://colab.research.google.com/gist/Saduf2019/406eba10719ec4104af99afd2080b81f/untitled367.ipynb)

**Comment by jvishnuvardhan** [comment] 2021-04-14 02:00
@arnomoonens Passing a name to weight works without any error . Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/375dc80da27b5847a912af0665c59ac4/untitled367.ipynb). Thanks!

Please verify once and close the issue if this resolved your issue. Thanks!

**Comment by huonw** [comment] 2021-04-14 02:17
@jvishnuvardhan that makes the code work, but the issue and comments are specific that that's not the whole story:

> I expected that the weight would either get a default name (possibly only upon saving), that I would get an error when calling add_weight or that I would get a more informative error when saving the model.

> Even if this didn't work as is (via a default name in add_weight, or whatever), a slightly more specific error message would've cut the time it took me to work out the cause dramatically.

**Comment by jvishnuvardhan** [comment] 2021-04-14 17:27
@huonw Agree with you that this is an issue. Thanks!

**Comment by sachinprasadhs** [comment] 2021-05-25 07:04
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/86b4256812ec91f4e96ba18bd0246586/35650.ipynb). Thanks!

**Comment by tensorflowbutler** [comment] 2021-12-14 23:11
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!

**Closed** 2022-01-11 17:46 UTC
Labels: stat:awaiting tensorflower, type:bug, comp:keras, TF 2.1
