### ISSUE TITLE
error while converting from custom SSD_mobilenet to TFLITE

### ISSUE THREAD

**Issue by deep28vish** [tensorflow/tensorflow#37569] opened 2020-03-13 10:47 UTC
**System information**
- OS Platform : windows 10
- TensorFlow installed from : anazonda tf-14

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, LOGISTIC, RESHAPE. Here is a list of operators for which you will need custom implementations: TFLite_Detection_PostProcess.
```

using the file : 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/tflite_convert.py

and command as : python tflite_convert.py --graph_def_file=D:\models\research\object_detection\ava_tflite\tflite_graph.pb --output_file=D:\models\research\object_detection\ava_tflite\tf_output --output_format=TFLITE --input_arrays=normalized_input_image_tensor --input_shapes=1,600,600,3 --inference_type=FLOAT --output_arrays="TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3" --allow_customs_ops=False

ERROR OUTPUT: 

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, LOGISTIC, RESHAPE. Here is a list of operators for which you will need custom implementations: TFLite_Detection_PostProcess.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\Scripts\toco_from_protos-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "C:\ProgramData\Anaconda3\envs\tfgpu14\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: We are continually in the process of adding support to TensorFlow Lite for more ops. It would be helpful if you could inform us of how this conversion went by opening a github issue at https://github.com/tensorflow/tensorflow/issues/new?template=40-tflite-op-request.md
 and pasting the following:

Some of the operators in the model are not supported by the standard TensorFlow Lite runtime. If those are native TensorFlow operators, you might be able to use the extended runtime by passing --enable_select_tf_ops, or by setting target_ops=TFLITE_BUILTINS,SELECT_TF_OPS when calling tf.lite.TFLiteConverter(). Otherwise, if you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ADD, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, LOGISTIC, RESHAPE. Here is a list of operators for which you will need custom implementations: TFLite_Detection_PostProcess.

**Comment by jvishnuvardhan** [comment] 2020-03-13 21:44
@deep28vish Can you please provide a standalone code to reproduce the error? Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-17 16:26
@deep28vish Can you please provide a standalone code to reproduce the error? Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-26 02:15
Closing due to lack of recent activity. Please feel free to reopen when you have requested information. Thanks!

**Closed by jvishnuvardhan** 2020-03-26 02:15 UTC
Labels: comp:lite, stat:awaiting response, type:support
