### ISSUE TITLE
tf.image.ssim_multiscale broke in tensorflow 2.1.0-rc2

### ISSUE THREAD

**Issue by isaacgerg** [tensorflow/tensorflow#37393] opened 2020-03-06 15:08 UTC
**System information** 
Python 3.7.6 on Windows 10, x64. 

Using tensorflow 2.1.0-rc2.

GPU Hardware: pciBusID: 0000:01:00.0 name: TITAN X (Pascal) computeCapability: 6.1
coreClock: 1.531GHz coreCount: 28 deviceMemorySize: 12.00GiB deviceMemoryBandwidth: 447.48GiB/s

**Describe the current behavior**

Code should print the word 'done'

**Describe the expected behavior**

tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

**Standalone code to reproduce the issue** 
```
import tensorflow as tf
tf.test.gpu_device_name()
print(tf.__version__)

# Build model
img_input = tf.keras.layers.Input(shape=(128, 128, 1))
img_output = tf.keras.layers.Convolution2D(1, 1)(img_input) 
model = tf.keras.models.Model(img_input, img_output)

# Add reconstruction loss 
# Toggle between the next 2 lines of code to see that ssim_multiscale does not work but simple MSE does.
loss = tf.reduce_mean(tf.image.ssim_multiscale(img_input, img_output, 1.0))  # This loss does not
#loss = tf.reduce_mean((img_input - img_output)**2)  # This loss works
model.add_loss(loss)

model.compile(optimizer = tf.keras.optimizers.RMSprop(lr=1e-4), loss = None)  
model.summary()

# The error Iget when using the ssim_multiscale loss is:
#tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
    
print('done')
```

**Other info / logs** 

This problem is present in 1.15.0 and 2.1.0.  This bug is not present in in 1.13.1.

I have tried several image metrics in tf.image including ssim and psnr and they all result in the same error.

**Comment by amahendrakar** [comment] 2020-03-09 09:33
Was able to reproduce the issue with TF 2.1 and TF-nightly. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/a27e55132ee756c965af0069155a326d/37393.ipynb). Thanks!

**Comment by isaacgerg** [comment] 2020-03-09 13:28
@amahendrakar Thank you.  @ymodak Please let me know what you need form my end to help!

**Comment by isaacgerg** [comment] 2020-03-17 13:17
I was able to verify using the gist that psnr is also affected.

**Comment by mihaimaruseac** [comment] 2020-03-17 17:47
Can you test with 2.2.0-rc0?

**Comment by isaacgerg** [comment] 2020-03-17 17:57
Sure can. It results in the same error.  See the stack trace below.

```
2.2.0-rc0

---------------------------------------------------------------------------

OperatorNotAllowedInGraphError            Traceback (most recent call last)

<ipython-input-6-a09a88deacaf> in <module>()
     10 # Add reconstruction loss
     11 # Toggle between the next 2 lines of code to see that ssim_multiscale does not work but simple MSE does.
---> 12 loss = tf.reduce_mean(tf.image.ssim_multiscale(img_input, img_output, 1.0))  # This loss does not
     13 #loss = tf.reduce_mean((img_input - img_output)**2)  # This loss works
     14 model.add_loss(loss)

6 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _disallow_in_graph_mode(self, task)
    535     raise errors.OperatorNotAllowedInGraphError(
    536         "{} is not allowed in Graph execution. Use Eager execution or decorate"
--> 537         " this function with @tf.function.".format(task))
    538 
    539   def _disallow_bool_casting(self):

OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.
```

**Comment by isaacgerg** [comment] 2020-03-17 17:57
The gist is here: https://colab.research.google.com/gist/amahendrakar/a27e55132ee756c965af0069155a326d/37393.ipynb#scrollTo=WvVY2Xh_omcU

**Comment by isaacgerg** [comment] 2020-03-19 17:46
@mihaimaruseac Should I try with 2.2.rc1?

**Comment by mihaimaruseac** [comment] 2020-03-19 17:58
Let's try, just in case a cherry-pick fixed the issue. But I don't recall any work being done to fix this in the past 2 days

**Comment by isaacgerg** [comment] 2020-03-19 18:31
@mihaimaruseac Just tried with 2.2rc1 but I still get the same error. Same for psnr() function also.

**Comment by isaacgerg** [comment] 2020-03-25 20:49
@mihaimaruseac  I think I narrowed the problem down.  It appears to be coming from a sanity check on the vector.  I think if this can be cleaned up for tensorflow 2.x, everything should work.

**Comment by isaacgerg** [comment] 2020-04-06 13:14
@mihaimaruseac Can you confirm about the my post on the vector check?

**Comment by isaacgerg** [comment] 2020-04-08 19:11
@mihaimaruseac   I'm completely stuck and cant figure this out. I am just going to use someone else's ssim function until this gets fixed.

**Comment by mihaimaruseac** [comment] 2020-04-08 22:08
@isaacgerg Sorry, I was not able to reproduce due to having too much on my plate these few days. I'll raise this issue internally

**Comment by mihaimaruseac** [comment] 2020-04-08 22:10
I see you say you narrowed the problem down. Do you want to make a PR please?

**Comment by mihaimaruseac** [comment] 2020-04-08 22:28
See also #28274

**Comment by isaacgerg** [comment] 2020-04-08 23:50
@mihaimaruseac I thought I narrowed down the problem but now I'm stuck and can't get any further.  I looked at 28274 and as far as I can tell, this is a different issue than that.  If you can have someone from the tf team look at this, I think they can likely fix it quick.  Don't forget that if you fix msssim, you can apply the same patch to psnr also.

**Comment by perfinion** [comment] 2020-04-20 17:17
@isaacgerg whats the fix for this? do you have a link to the PR or commit hash?

**Comment by isaacgerg** [comment] 2020-04-20 17:19
@perfinion I don't know how to fix it.  That's why I posted the issue on github.

**Comment by isaacgerg** [comment] 2020-04-22 17:45
@mihaimaruseac Is there any update on when this will be fixed? Thank you.

**Comment by isaacgerg** [comment] 2020-06-19 18:37
@tomerk Any progress on this issue?

**Comment by tomerk** [comment] 2020-06-19 18:52
Hi @isaacgerg , we've been working on a rework of the implementation of Keras's functional api construction. As one side effect fixes several categories of issues with automatically turning non-keras tf api symbols into keras lambda layers. (I believe it should fix tf.image.ssim_multiscale)

This implementation rework is targeted for **TF 2.4**, not TF 2.3
That said you can start experimenting with it in the tf-nightlies by doing:

```
from tensorflow.python.keras.engine import keras_tensor
keras_tensor.enable_keras_tensors()
```
Keep in mind this is still experimental and not exposed in TF's API. It's a fully internal flag subject to change. But, feel free to start reporting issues you run into with it.

---------------------

If you need a stable workaround ASAP that works already, you should be able to just put `tf.image.ssim_multiscale` in a Keras Lambda layer or custom layer. Then call that layer instead of calling the `ssim_multiscale` directly.

**Comment by isaacgerg** [comment] 2020-06-19 19:27
Thanks for the quick reply @tomerk.  This is good news!  I will try working with the nightlies.  Any issues I find, I'll try to help debug.  Thank you again.

**Comment by Sajal-1** [comment] 2020-07-28 23:29
Could someone elaborate on what @tomerk meant by "If you need a stable workaround ASAP that works already, you should be able to just put tf.image.ssim_multiscale in a Keras Lambda layer or custom layer. Then call that layer instead of calling the ssim_multiscale directly."

I am not experienced in tensorflow and keras.

**Comment by tomerk** [comment] 2020-07-30 20:01
@Sajal-1 You can make & use custom layers in Keras, e.g. following this guide: https://www.tensorflow.org/guide/keras/custom_layers_and_models

Or use an arbitrary python lambda as a layer in Keras using this API:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Lambda?hl=en

**Comment by tomerk** [comment] 2020-08-05 21:44
This issue should now be fixed in the nightlies, as we've enabled the Functional API refactoring I mentioned above.

**Closed by tomerk** 2020-08-05 21:44 UTC
Labels: TF 2.1, comp:keras, type:bug

**Comment by isaacgerg** [comment] 2020-08-06 14:32
@tomerk   Many thanks for fixing this issue.  This fixes quite a bit of other bugs I had in my tensorflow codes!

**Comment by tomerk** [comment] 2020-08-06 20:31
Glad to hear it, thanks @isaacgerg! Please don't hesitate to report any other such issues you run into.
