### ISSUE TITLE
Model weights using the HDF5 format are not saved

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#45078] opened 2020-11-22 12:26 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Yes
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Not on mobile device
- TensorFlow version (use command below): 2.3
- Python version: 3.6.9
- Bazel version (if compiling from source): Not compiling from source
- GCC/Compiler version (if compiling from source): Not compiling from source
- CUDA/cuDNN version: No GPU
- GPU model and memory: No GPU

**Describe the current behavior**

When using the HDF5 format to save the weights of a model (directly added in the model class), the value of the weights I get when loading the model are not the same as the ones of the saved model.

**Describe the expected behavior**

The value of the weights of the loaded model should be the same as that of the saved model.

**Standalone code to reproduce the issue**

This is [the colab](https://colab.research.google.com/drive/1TAitBc7wM_5jj0vi3V00xoH7paFxy2YP?usp=sharing) I used to illustrate this issue.

**Other info / logs**

When using layers in the model, instead of weights added via (`self.add_weight`), the values of the layers' weights are correctly saved. So it's really a problem of the weights of a `Model` not being saved (or loaded correctly).

**Comment by zaccharieramzi** [comment] 2020-11-22 12:29
Small note, when not using the HDF5 format, i.e. `model.save_weights('model')`, I get the following error: `AttributeError: 'NoneType' object has no attribute 'replace'`.

The full stacktrace is:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-dcf87c4ca34b> in <module>()
----> 1 model.save_weights('model')

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in save_weights(self, filepath, overwrite, save_format, options)
   2099              'saved.\n\nConsider using a TensorFlow optimizer from `tf.train`.')
   2100             % (optimizer,))
-> 2101       self._trackable_saver.save(filepath, session=session, options=options)
   2102       # Record this checkpoint so it's visible from tf.train.latest_checkpoint.
   2103       checkpoint_management.update_checkpoint_state_internal(

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py in save(self, file_prefix, checkpoint_number, session, options)
   1198     file_io.recursive_create_dir(os.path.dirname(file_prefix))
   1199     save_path, new_feed_additions = self._save_cached_when_graph_building(
-> 1200         file_prefix_tensor, object_graph_tensor, options)
   1201     if new_feed_additions:
   1202       feed_dict.update(new_feed_additions)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py in _save_cached_when_graph_building(self, file_prefix, object_graph_tensor, options)
   1135     (named_saveable_objects, graph_proto,
   1136      feed_additions) = self._gather_saveables(
-> 1137          object_graph_tensor=object_graph_tensor)
   1138     if (self._last_save_object_graph != graph_proto
   1139         # When executing eagerly, we need to re-create SaveableObjects each time

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/util.py in _gather_saveables(self, object_graph_tensor)
   1101     """Wraps _serialize_object_graph to include the object graph proto."""
   1102     (named_saveable_objects, graph_proto,
-> 1103      feed_additions) = self._graph_view.serialize_object_graph()
   1104     if object_graph_tensor is None:
   1105       with ops.device("/cpu:0"):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/graph_view.py in serialize_object_graph(self)
    385     trackable_objects, path_to_root = self._breadth_first_traversal()
    386     return self._serialize_gathered_objects(
--> 387         trackable_objects, path_to_root)
    388 
    389   def frozen_saveable_objects(self, object_map=None, to_graph=None,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/graph_view.py in _serialize_gathered_objects(self, trackable_objects, path_to_root, object_map, call_with_mapped_captures)
    340     object_names = object_identity.ObjectIdentityDictionary()
    341     for obj, path in path_to_root.items():
--> 342       object_names[obj] = _object_prefix_from_path(path)
    343     node_ids = object_identity.ObjectIdentityDictionary()
    344     for node_id, node in enumerate(trackable_objects):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/graph_view.py in _object_prefix_from_path(path_to_root)
     62   return "/".join(
     63       (_escape_local_name(trackable.name)
---> 64        for trackable in path_to_root))
     65 
     66 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/graph_view.py in <genexpr>(.0)
     62   return "/".join(
     63       (_escape_local_name(trackable.name)
---> 64        for trackable in path_to_root))
     65 
     66 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/graph_view.py in _escape_local_name(name)
     55   # edges traversed to reach the variable, so we escape forward slashes in
     56   # names.
---> 57   return (name.replace(_ESCAPE_CHAR, _ESCAPE_CHAR + _ESCAPE_CHAR)
     58           .replace(r"/", _ESCAPE_CHAR + "S"))
     59 

AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by amahendrakar** [comment] 2020-11-23 15:07
@zaccharieramzi,
Please take a look at issue [#26811](https://github.com/tensorflow/tensorflow/issues/26811#issuecomment-474255444) with a similar error and let us know if it helps. Thanks!

**Comment by zaccharieramzi** [comment] 2020-11-23 15:45
Naming the weight didn't help unfortunately. You can see this in the same [colab](https://colab.research.google.com/drive/1TAitBc7wM_5jj0vi3V00xoH7paFxy2YP?usp=sharing).

**Comment by amahendrakar** [comment] 2020-11-24 16:47
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/12ef06e0238ccd4160f1470621dbca73/45078-2-3.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/33d6b2e906acbab5fd97213a9502d33e/45078-2-5.ipynb). Please find the attached gist. Thanks!

**Comment by rmothukuru** [comment] 2020-12-18 01:53
@zaccharieramzi,
I think this is an intended behavior (not very sure though) as per [this comment](https://github.com/tensorflow/tensorflow/issues/41116#issuecomment-657768371). Can you please check it and let me know? Thanks!

**Comment by zaccharieramzi** [comment] 2020-12-18 07:46
Hmmm I don't think so because it's not related the optimizer but really to actual model weights. The only difference is that they are instantiated inside a model object instead of inside a layer.

**Comment by sushreebarsa** [comment] 2021-06-18 03:57
Was able to replicate the issue with TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/dc72e669d69e3dfdba9e305a4173fefa/untitled267.ipynb) ..Thanks!

**Comment by jvishnuvardhan** [comment] 2021-12-20 18:11
@zaccharieramzi Looks like this was resolved in `TF2.7`. [Here](https://colab.research.google.com/gist/jvishnuvardhan/0607382ea383bad03880633fc8118bbe/model_direct_weights_not_saved.ipynb) is a gist for reference.

`model.b`
<tf.Variable 'bias:0' shape=() dtype=float32, numpy=1.9999998>

`other_model.b`
<tf.Variable 'bias:0' shape=() dtype=float32, numpy=1.9999998>


Can you please verify once and close the issue if this was resolved for you. Thanks!

**Closed** 2022-01-03 19:03 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:keras, TF 2.3
