### ISSUE TITLE
AttentionMechanism not be supported in Eager Mode

### ISSUE THREAD

**Issue by smallhaolzh** [tensorflow/tensorflow#27147] opened 2019-03-26 13:27 UTC
When I want to add certain classical AttetionMechansim through Tensorflow API, I find that Tensorflow 's AttentionMechansim API dose not support Eager Mode for the reason that "memory" parameter is in the attention mechiansim s' __init__ method. Because in general, I construct a AttentionMechanism in static graph mode, it must be constructed transferring a parameter "memory" , a tensor whose value is decided by the model input. However, in Eager Mode,  when constructing a AttentionMechanism, "memory" is deterministically taking real values, which enables me not to change to a new memory values in a new training iteration.

**Comment by jvishnuvardhan** [comment] 2019-03-28 22:05
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by tensorflowbutler** [comment] 2019-04-12 12:58
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment] 2019-04-12 20:40
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-04-12 20:40 UTC
Labels: comp:eager, stat:awaiting response, type:feature
