### ISSUE TITLE
text_classification_cnn dataset error

### ISSUE THREAD

**Issue by Aryal007** [tensorflow/tensorflow#6261] opened 2016-12-12 05:43 UTC
The dbpedia_csv.tar.gz file downloaded seems to be corrupt and the link for the dataset, i.e.
https://googledrive.com/host/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M/dbpedia_csv.tar.gz

is giving 404 error. The file dbpedia_csv.tar.gz seems to be downloaded but upon running tensorflow/tensorflow/examples/learn/text_classification_cnn.py, an error is produced giving

Successfully downloaded dbpedia_csv.tar.gz 1657 bytes.
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 88, in main
    'dbpedia', test_with_fake_data=FLAGS.test_with_fake_data, size='large')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py", line 64, in load_dataset
    return DATASETS[name](size, test_with_fake_data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/text_datasets.py", line 48, in load_dbpedia
    maybe_download_dbpedia(data_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/text_datasets.py", line 40, in maybe_download_dbpedia
    tfile = tarfile.open(archive_path, 'r:*')
  File "/usr/lib/python2.7/tarfile.py", line 1678, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by martinwicke** [comment] 2016-12-21 08:40
We're looking into finding a replacement link. In the meantime, you can probably download the file manually from https://drive.google.com/corp/drive/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M

**Comment by martinwicke** [comment] 2016-12-21 08:41
duplicate of #6174.

**Closed by martinwicke** 2016-12-21 08:41 UTC
Labels: awaiting googler
