### ISSUE TITLE
Error when using batch_norm with MirroredStrategy

### ISSUE THREAD

**Issue by jdvylder** [tensorflow/tensorflow#20874] opened 2018-07-17 09:10 UTC
### System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): using nvidia containter: https://docs.nvidia.com/deeplearning/dgx/tensorflow-release-notes/rel_18.06.html#rel_18.06
TensorFlow version (use command below):1.8.0
Python version: 3.5
Bazel version (if compiling from source): N/A
GCC/Compiler version (if compiling from source): N/A
CUDA/cuDNN version: 9.0.176
GPU model and memory: nvidia tesla v100
Exact command to reproduce: N/A

### Describe the problem
I want to apply transfer learning using an existing pretrained network (inception v4). For this I use the tf-slim models. When running this on a single GPU, This works as expected, however when using `tf.contrib.distribute.MirroredStrategy`  I get an exception. Apparently the MirroredStrategy has some issues with batch_norm

### Source code / logs
I tried to extract the relevant part from my code:
```
import research.slim.nets.nets_factory as nets_factory

...

def construct_architecture(self, input_tensor, mode):
        # network topology
        network_fn = nets_factory.get_network_fn('inception_v4', num_classes=self.configuration.get("nr_classes"),
                                                      is_training=True)
        logits,_ = network_fn(input_tensor)

        if mode == tf.estimator.ModeKeys.PREDICT:
            predicted_classes = tf.argmax(logits, 1)
            predictions = {
                'class_ids': predicted_classes[:, tf.newaxis],
                'probabilities': tf.nn.softmax(logits),
                'logits': logits,
            }
            self.output_tensor = predictions
        else:
            self.output_tensor = logits
```

This results in the following error trace:
```
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    experimenter.run_training_experiment(config)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 39, in run_training_experiment
    tf.estimator.train_and_evaluate(self.trainer, self.training_specs, self.eval_specs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 451, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 590, in run
    return self.run_local()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 691, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1143, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1255, in _train_model_distributed
    self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/distribute.py", line 777, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 308, in _call_for_each_tower
    coord.join(threads)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/onnx/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 519, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 111, in get_model_fn
    self.configure_network(input_tensor=features, output_tensor=labels, mode=mode)
  File "/media/local/BDA_tf_framework/neuralnetwork/trainingexperimenter.py", line 75, in configure_network
    self.network.construct_network(input_tensor=input_tensor, output_tensor=output_tensor, mode=mode)
  File "/media/local/myfiles/mynetwork.py", line 64, in construct_network
    self.construct_architecture(input_tensor=input_tensor,mode=mode)
  File "/media/local/myfiles/mynetwork.py", line 48, in construct_architecture
    logits,_ = network_fn(input_tensor)
  File "/opt/tf-slim/models/research/slim/nets/nets_factory.py", line 141, in network_fn
    return func(images, num_classes, is_training=is_training, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/slim-0.1-py3.5.egg/nets/inception_v4.py", line 286, in inception_v4
  File "/usr/local/lib/python3.5/dist-packages/slim-0.1-py3.5.egg/nets/inception_v4.py", line 178, in inception_v4_base
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1066, in convolution
    outputs = normalizer_fn(outputs, **normalizer_params)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 650, in batch_norm
    outputs = layer.apply(inputs, training=is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/normalization.py", line 158, in call
    return super(BatchNormalization, self).call(inputs, training=training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/normalization.py", line 514, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/normalization.py", line 420, in _fused_batch_norm
    momentum)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/normalization.py", line 369, in _assign_moving_average
    with ops.colocate_with(variable):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3939, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3992, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1255, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/distribute/python/values.py", line 414, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError
```

Thanks for the help

Jonas

**Comment by guptapriya** [comment] 2018-07-20 20:45
@yuefengz has a fix in progress relating to `contrib.layers` that might address this issue as well. He should be able to merge that in the a few days. After that you could try again and see if the issue still persists.

**Comment by tensorflowbutler** [comment] 2018-08-04 18:42
Nagging Assignee @yuefengz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-19 18:49
Nagging Assignee @yuefengz: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-03 18:39
Nagging Assignee @yuefengz: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by offthewallace** [comment] 2018-09-11 08:59
I had the same issues 

WARNING:tensorflow:Estimator's model_fn (<function model_fn at 0x7f1b5a16a320>) includes params argument, but params are not passed to Estimator.
2018-09-11 16:17:09.727266: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-11 16:17:09.728842: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-09-11 16:17:09.728874: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: mqq
2018-09-11 16:17:09.728885: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: mqq
2018-09-11 16:17:09.728914: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 384.81.0
2018-09-11 16:17:09.728945: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 384.130.0
2018-09-11 16:17:09.728955: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:308] kernel version 384.130.0 does not match DSO version 384.81.0 -- cannot find working devices in this configuration
WARNING:tensorflow:Not all devices in distribute strategy are visible by TensorFlow sessions.
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /data/guanlin/od_0730/object_detection/core/preprocessor.py:1205: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
WARNING:tensorflow:From /data/guanlin/od_0730/object_detection/builders/dataset_builder.py:146: batch_and_drop_remainder (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.batch(..., drop_remainder=True)`.
Traceback (most recent call last):
  File "object_detection/model_main.py", line 102, in <module>
    tf.app.run()
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "object_detection/model_main.py", line 98, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 451, in train_and_evaluate
    return executor.run()
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 590, in run
    return self.run_local()
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 691, in run_local
    saving_listeners=saving_listeners)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1143, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1255, in _train_model_distributed
    self.config)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/training/distribute.py", line 777, in call_for_each_tower
    return self._call_for_each_tower(fn, *args, **kwargs)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 308, in _call_for_each_tower
    coord.join(threads)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/mirrored_strategy.py", line 519, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/data/guanlin/od_0730/object_detection/model_lib.py", line 246, in model_fn
    preprocessed_images, features[fields.InputDataFields.true_image_shape])
  File "/data/guanlin/od_0730/object_detection/meta_architectures/ssd_meta_arch.py", line 393, in predict
    preprocessed_inputs)
  File "/data/guanlin/od_0730/object_detection/models/ssd_inception_v2_feature_extractor.py", line 118, in extract_features
    scope=scope)
  File "/data/guanlin/od_0730/slim/nets/inception_v2.py", line 117, in inception_v2_base
    scope=end_point)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 2785, in separable_convolution2d
    outputs = normalizer_fn(outputs, **normalizer_params)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 650, in batch_norm
    outputs = layer.apply(inputs, training=is_training)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 805, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 736, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/layers/normalization.py", line 158, in call
    return super(BatchNormalization, self).call(inputs, training=training)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/keras/layers/normalization.py", line 514, in call
    outputs = self._fused_batch_norm(inputs, training=training)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/keras/layers/normalization.py", line 420, in _fused_batch_norm
    momentum)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/keras/layers/normalization.py", line 369, in _assign_moving_average
    with ops.colocate_with(variable):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3939, in _colocate_with_for_gradient
    with self.colocate_with(op, ignore_existing):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3992, in colocate_with
    op = internal_convert_to_tensor_or_indexed_slices(op, as_ref=True).op
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1255, in internal_convert_to_tensor_or_indexed_slices
    value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1094, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/mqq/tensorflow1.9/env/local/lib/python2.7/site-packages/tensorflow/contrib/distribute/python/values.py", line 414, in _tensor_conversion_mirrored
    assert not as_ref
AssertionError

**Comment by guptapriya** [comment] 2018-09-18 02:05
The fix for this is in r1.11, could you please test with that and let us know?

**Comment by tensorflowbutler** [comment] 2018-10-03 06:49
Nagging Assignee @yuefengz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-17 13:10
Nagging Assignee @yuefengz: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by yuefengz** [comment] 2018-10-19 06:07
I am closing this issue for now. Feel free to reopen it or create a new one if the problem is still there.

**Closed by yuefengz** 2018-10-19 06:07 UTC
Labels: comp:dist-strat

**Comment by andreasjansson** [comment] 2018-11-06 22:04
As a workaround, `tf.keras.layers.BatchNormalization` appears to be working fine.

**Comment by cheneeheng** [comment] 2018-11-10 13:56
> As a workaround, `tf.keras.layers.BatchNormalization` appears to be working fine.

Hi there, i am also facing the same problem with mirrored strategy, even though i am using tf1.12...
How did u modify the code to put the keras layer in ? (Non-Keras user here)

**Comment by andreasjansson** [comment] 2018-11-10 21:34
@cheneeheng you can replace

```python
net = tf.contrib.layers.batch_norm(net)
```

with

```python
net = tf.keras.layers.BatchNormalization()(net)
```

in the example above.

**Comment by lorenzoriano** [comment] 2019-02-05 01:39
I've replaced `tf.contrib.layers.batch_norm(net)` with `tf.keras.layers.BatchNormalization()(net)` but I'm seeing the same problem

**Comment by nithingautham** [comment] 2019-03-25 14:09
any update on the solution here ?

**Comment by shejingbingxiansheng** [comment] 2019-09-30 07:06
I have the same problem

**Comment by SirjanK** [comment] 2019-10-19 04:14
Same problem here as well. tf version 1.12.

**Comment by guptapriya** [comment] 2019-10-19 23:08
@SirjanK - have you tested with the latest versions of TF? say TF 2.0 or TF 1.15? If the problem still persists, please re-open along with code to repro the issue

**Comment by antonyomusabini** [comment] 2020-11-18 17:25
The problem persists on TensorFlow 2.2.0-rc2 with Ubuntu 20.04.1 LTS with `tf.keras.layers.BatchNormalization()(net)` with the following error `ValueError: Tried to convert 'mean' to a tensor and failed. Error: Device assignment required for nccl collective ops`
