### ISSUE TITLE
RTX 2070 8GB tensorflow 1.13 build from source

### ISSUE THREAD

**Issue by timyee90** [tensorflow/tensorflow#25552] opened 2019-02-06 15:35 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.13/1.12
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip/conda
- Bazel version (if compiling from source): 0.21.0
- GCC/Compiler version (if compiling from source): Unsure
- CUDA/cuDNN version: 10.0/7.4
- GPU model and memory: MSI Armor RTX 2070 8GB 

**Describe the problem**

Unable to build 1.13 from source using bazel. bazel is properly installed using chocolatey. I get to the end of configuring my build but I cannot build. TF version 1.12 does not work properly on CUDA 10.0. on TF 1.12, training data loads into the GPU's VRAM but uses the CPU to compute.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

On first pass, I was able to get to configure.py in tensorflow folder and go through the configuration process. Upon finishing, I was not able to build. After a few days, I am now attempting to configure the build and I am getting an output 'Cannot find bazel. Please install bazel. I installed bazel through chocolately. Attached are the logs showing bazel install through chocolately. I also have some logs during the first attempt at building. I forget where I located the tensorflow building logs. If you can direct me, I'll happily provide those. I'm also curious as to when the 1.13 release becomes official. Thanks. 

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

[chocolatey.log](https://github.com/tensorflow/tensorflow/files/2836941/chocolatey.log)
[choco.summary.log](https://github.com/tensorflow/tensorflow/files/2836942/choco.summary.log)

**Comment by jvishnuvardhan** [comment] 2019-02-07 00:10
@timyee90 Please check [tested build configurations](https://www.tensorflow.org/install/source_windows#gpu). Also, there is a common issue with WIndows10 where long paths are creating an issue due to default limit on length of a path. Check the solutions provided [here](https://github.com/tensorflow/tensorflow/issues/24705) and [here](https://github.com/tensorflow/tensorflow/issues/24886). Please let me know how it progresses. Thanks!

**Comment by daidong** [comment] 2019-02-07 18:15
I also have problems compiling Tensorflow 1.13 with cuda 10.0/cuddnn 7 on RTX 2070 GPU. 

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
* Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
* TensorFlow installed from (source or binary): source
* TensorFlow version: 1.13
* Python version: 3.6
* Installed using virtualenv? pip? conda?: pip
* Bazel version (if compiling from source): 0.21.0
* GCC/Compiler version (if compiling from source): Visual Studio 2015 Update 3.
* CUDA/cuDNN version: 10.0/7.4.2
* GPU model and memory: RTX 2070 8GB

It fails after almost finishing all the compilation.  The error message looks like bellow:

```
ERROR: C:/codes/tensorflow/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
  cd C:/users/daido/_bazel_daido/arhjsgmd/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
    SET PATH=C:\msys64\usr\bin;C:\msys64\bin
    SET PYTHON_BIN_PATH=C:/Program Files/Python36/python.exe
    SET PYTHON_LIB_PATH=C:/Program Files/Python36/lib/site-packages
    SET TF_CUDA_CLANG=0
    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
    SET TF_CUDA_VERSION=10.0
    SET TF_CUDNN_VERSION=7
    SET TF_NEED_CUDA=1
    SET TF_NEED_OPENCL_SYCL=0
    SET TF_NEED_ROCM=0
  C:/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.sh
Execution platform: @bazel_tools//platforms:host_platform
Traceback (most recent call last):
  File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by daidong** [comment] 2019-02-07 18:15
```ERROR: C:/codes/tensorflow/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command  cd C:/users/daido/_bazel_daido/arhjsgmd/execroot/org_tensorflow  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0    SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0    SET PATH=C:\msys64\usr\bin;C:\msys64\bin    SET PYTHON_BIN_PATH=C:/Program Files/Python36/python.exe    SET PYTHON_LIB_PATH=C:/Program Files/Python36/lib/site-packages    SET TF_CUDA_CLANG=0    SET TF_CUDA_COMPUTE_CAPABILITIES=5.0    SET TF_CUDA_VERSION=10.0    SET TF_CUDNN_VERSION=7    SET TF_NEED_CUDA=1    SET TF_NEED_OPENCL_SYCL=0    SET TF_NEED_ROCM=0  C:/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.shExecution platform: @bazel_tools//platforms:host_platformTraceback (most recent call last):  File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>    from tensorflow.python.pywrap_tensorflow_internal import *  File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>    _pywrap_tensorflow_internal = swig_import_helper()  File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)  File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module    return load_dynamic(name, filename, file)  File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic    return _load(spec)ImportError: DLL load failed: The specified module could not be found.```

**Comment by jvishnuvardhan** [comment] 2019-02-07 22:16
@daidong Could you implement the solutions mentioned above to remove the default limit on length of a path in Windows10. Then, install TFlow again. Please let me know how it progresses. Thanks!

**Comment by daidong** [comment] 2019-02-08 06:13
@jvishnuvardhan thanks for your comment.  The path length in Windows 10 was already removed before I had these error messages.

**Comment by Yuui-Asuka** [comment] 2019-02-08 18:27
@daidong I also encountered this problem. How did you solve it?

**Comment by Yuui-Asuka** [comment] 2019-02-08 19:46
@daidong I have same problems when I build tensorflow1.13 from source with cuda10.0 and cuda9.2,how did you solve it?

**Comment by daidong** [comment] 2019-02-08 19:46
No, the issue is still there.

**Comment by gunan** [comment] 2019-02-08 23:32
Could you share full build logs using pastebin?
The error means dll cannot be found, but I think there was another issue building the DLL.

Could you also use pastebin to share the logs when you run configure?

**Comment by timyee90** [comment] 2019-02-11 14:15
I was able to run configure.py and get bazel to build, however, I am still not successfully able to build. I'm guessing it is related to what I type into "Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: avx2". Ideally I want CPU & GPU support in the same build which includes avx2, mkl, etc... Do I need to type 'AVX2'? I have an intel core i7 8700K, so I'm not sure what is preventing me from building. Please let me know what the exact build command is to include avx2 and mkl if possible. Thanks.

[build.txt](https://github.com/tensorflow/tensorflow/files/2851363/build.txt)
[configure.txt](https://github.com/tensorflow/tensorflow/files/2851364/configure.txt)

**Comment by daidong** [comment] 2019-02-11 16:26
> 
> 
> Could you share full build logs using pastebin?
> The error means dll cannot be found, but I think there was another issue building the DLL.
> 
> Could you also use pastebin to share the logs when you run configure?

please check the configuration logs at: https://pastebin.com/LGK64Yhk
and build logs at: https://pastebin.com/TiVAsvVb

Many warning generated during the building. But I think the last error stopped it.

**Comment by gunan** [comment] 2019-02-14 00:12
not sure what is going on here, CC @meteorcloudy may be able to help.

**Comment by meteorcloudy** [comment] 2019-02-14 09:00
This might be related to https://github.com/bazelbuild/bazel/issues/7026
Can you try build with `--incompatible_strict_action_env=false`? Or just upgrade Bazel to 0.22.0 in which the  flag flip is reverted.

**Comment by Yuui-Asuka** [comment] 2019-02-14 15:08
I tried to use tf1.12 with cuda 10.0 and the same problem happened, and when I build tensorflow1.13rc1 from source with cuda10, the error is also "dll not found", but when I get tf1.13rc1.wheel from pypi, this problem has been solved. When I installed tf1.13rc1.wheel with pip, some other libraries was installed automatically, maybe these libraries is the cause of "dll not found error".

**Comment by daidong** [comment] 2019-02-14 15:15
> This might be related to [bazelbuild/bazel#7026](https://github.com/bazelbuild/bazel/issues/7026)
> Can you try build with `--incompatible_strict_action_env=false`? Or just upgrade Bazel to 0.22.0 in which the flag flip is reverted.

I tried Bazel 0.22 before. But it complains and says please use Bazel 0.21.0 instead. I got the same configuration and version compiled well on Ubuntu.  I guess it should be just missing libraries in Windows now.

**Comment by alvaroslm** [comment] 2019-03-06 15:49
@gunan the problem here is the system path is completely gone and replaced with 

> SET PATH=C:\msys64\usr\bin;C:\msys64\bin

The _pywrap... library fails to load because it can't load almost any of its dependencies (not even python or cuda dlls) because they're not there and they're not in PATH. I've run the script manually with my system path and it works, but not under Bazel with its crippled path.

**Comment by alvaroslm** [comment] 2019-03-06 17:25
If you're using bazel 0.21 you can build with --incompatible_strict_action_env=false to fix the path issue.
(see https://github.com/bazelbuild/bazel/issues/7026 and https://github.com/bazelbuild/bazel/issues/6648 )

**Comment by asa008** [comment] 2019-05-05 05:51
I install tensorflow 1.13.1 from source with bazel 0.21 successfully, with cuda 10.0, cuDNN 7.5, RTX 2080, win10 x64, by command:
```
set BAZEL_VS=C:\Program Files (x86)\Microsoft Visual Studio 14.0

bazel build --config=opt --config=cuda --incompatible_strict_action_env=false  --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package --local_resources 6144,.5,1.0

bazel-bin\tensorflow\tools\pip_package\build_pip_package C:/tmp/tensorflow_pkg

pip3 install C:/tmp/tensorflow_pkg/tensorflow-version-cp35-cp35m-win_amd64.whl
```

**Comment by gitgithan** [comment] 2019-06-13 18:48
@asa008 
Could you share your .whl file? 
![image](https://user-images.githubusercontent.com/29853829/59459075-82872900-8e4e-11e9-857d-37e8bd0082e4.png)
Mine is Windows 10 RTX2070, i followed https://www.tensorflow.org/install/source_windows#gpu and finally got build failed because could not find cudart64_.dll. I see there is a cudart64_101.dll in my CUDA >v10.1 folder. Why is the prompt URL (https://developer.nvidia.com/cuda-90-download-archive) leading me to CUDA 9.0 (Can't work with RTX2070) when it already can pick up that i have CUDA10.1 when running configure.py?

**Comment by uve** [comment] 2019-06-20 03:38
I can confirm that command **--incompatible_strict_action_env=false** helped me to get rid of _"dll not found"_ error. My configuration:
RTX 2080
Windows 10
Tensorflow 1.13.1
CUDA 10.1
CuDNN 7.6

**Comment by Mouradost** [comment] 2019-06-26 15:06
> I also have problems compiling Tensorflow 1.13 with cuda 10.0/cuddnn 7 on RTX 2070 GPU.
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary): source
> * TensorFlow version: 1.13
> * Python version: 3.6
> * Installed using virtualenv? pip? conda?: pip
> * Bazel version (if compiling from source): 0.21.0
> * GCC/Compiler version (if compiling from source): Visual Studio 2015 Update 3.
> * CUDA/cuDNN version: 10.0/7.4.2
> * GPU model and memory: RTX 2070 8GB
> 
> It fails after almost finishing all the compilation. The error message looks like bellow:
> 
> ```
> ERROR: C:/codes/tensorflow/tensorflow/BUILD:573:1: Executing genrule //tensorflow:tf_python_api_gen_v1 failed (Exit 1): bash.exe failed: error executing command
>   cd C:/users/daido/_bazel_daido/arhjsgmd/execroot/org_tensorflow
>   SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
>     SET CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0
>     SET PATH=C:\msys64\usr\bin;C:\msys64\bin
>     SET PYTHON_BIN_PATH=C:/Program Files/Python36/python.exe
>     SET PYTHON_LIB_PATH=C:/Program Files/Python36/lib/site-packages
>     SET TF_CUDA_CLANG=0
>     SET TF_CUDA_COMPUTE_CAPABILITIES=5.0
>     SET TF_CUDA_VERSION=10.0
>     SET TF_CUDNN_VERSION=7
>     SET TF_NEED_CUDA=1
>     SET TF_NEED_OPENCL_SYCL=0
>     SET TF_NEED_ROCM=0
>   C:/msys64/usr/bin/bash.exe bazel-out/x64_windows-opt/genfiles/tensorflow/tf_python_api_gen_v1.genrule_script.sh
> Execution platform: @bazel_tools//platforms:host_platform
> Traceback (most recent call last):
>   File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "\\?\C:\Users\daido\AppData\Local\Temp\Bazel.runfiles__c2da756\runfiles\org_tensorflow\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "C:\Program Files\Python36\lib\imp.py", line 243, in load_module
>     return load_dynamic(name, filename, file)
>   File "C:\Program Files\Python36\lib\imp.py", line 343, in load_dynamic
>     return _load(spec)
> ImportError: DLL load failed: The specified module could not be found.
> ```

I also have the same error with rtx 2070
windows 10 home
tensorflow 1.13
cuda 10.1
cudnn 7.5
bazel 0.21.0

**Comment by bhack** [comment] 2021-05-13 17:45
Can we close this?

**Closed** 2021-05-13 17:50 UTC
Labels: TF 1.12, TF 1.13, subtype:windows, type:build/install
