### ISSUE TITLE
Session.run () takes a long time

### ISSUE THREAD

**Issue by gulingfengze** [tensorflow/tensorflow#22039] opened 2018-09-04 03:49 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:N/A
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:1.9.0
- **Python version**:3.6
- **Bazel version (if compiling from source)**:N/A
- **GCC/Compiler version (if compiling from source)**:6.4.0
- **CUDA/cuDNN version**:9.0 / 7.0
- **GPU model and memory**:GeForce GTX960
- **Exact command to reproduce**:N/A

### Describe the problem

Each time tensorflow performs session.run() for target detection, the detection time of the first image is very long (including some initialization operations, of course), while the detection time of other images is normal. Suppose I detect the image under a certain path (for example, there are ten images), the time of detecting the first image is relatively long, and the remaining nine images are relatively short (basically consistent). However, my operation in practical application is as follows: the session.run() is called every once in a while to detect a picture. I hope that the detection time after the first one is normal except for the long time. However, through my test (guess), after exiting the loop logic of detection, tensorflow redid a series of initialization operations the next time the detection was done, which puzzled me.

With other frameworks, such as mxnet, initial detection takes longer. And then the detection time is normal, as if it's not doing some initialization anymore. I thought, could tensorflow do the same thing?

### Source code / logs

2018-09-04 14:48:59.111510: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.57GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
time：5627.940655ms
0.9999423027038574
time：657.650471ms
0.9996843338012695
time：676.565170ms
0.9722122550010681
0.6320008635520935
time：667.881966ms
0.996504545211792

**Comment by gulingfengze** [comment] 2018-09-04 06:42
Each time tensorflow performs session.run() for target detection, the detection time of the first image is very long (including some initialization operations, of course), while the detection time of other images is normal. Suppose I detect the image under a certain path (for example, there are ten images), the time of detecting the first image is relatively long, and the remaining nine images are relatively short (basically consistent). However, my operation in practical application is as follows: the session.run() is called every once in a while to detect a picture. I hope that the detection time after the first one is normal except for the long time. However, through my test (guess), after exiting the loop logic of detection, tensorflow redid a series of initialization operations the next time the detection was done, which puzzled me.

With other frameworks, such as mxnet, initial detection takes longer. And then the detection time is normal, as if it's not doing some initialization anymore. I thought, could tensorflow do the same thing?

**Comment by feihugis** [comment] 2018-09-05 00:44
I met a similar problem. It seems to be caused by some lazy operations. That means some operations will be executed until the graph actually runs.

**Comment by gulingfengze** [comment] 2018-09-06 02:39
@bignamehyp Is there a way to solve this problem?

**Comment by tensorflowbutler** [comment] 2018-09-20 12:44
Nagging Assignee @bignamehyp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-05 19:09
Nagging Assignee @bignamehyp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-21 19:03
Nagging Assignee @bignamehyp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-05 18:59
Nagging Assignee @bignamehyp: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-12-05 19:00
Nagging Assignee @bignamehyp: It has been 90 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment] 2019-02-13 21:54
@gulingfengze is this still an issue? Could you load TF 1.12 (stable) or latest version and check whether the issue persists? It is will be good if you can share a simplified code to reproduce the issue. If it was solved by newer version, please close the issue. Thanks!

**Comment by gulingfengze** [comment] 2019-02-16 08:18
@jvishnuvardhan The latest version still has this problem, and my guess is that the program did some initialization like gpu at the beginning of execution.

**Comment by jlebar** [comment] 2019-02-19 17:49
@jvishnuvardhan I work on XLA, so this is outside of my area of ownership.

**Comment by jlebar** [comment] 2019-02-19 17:50
> my guess is that the program did some initialization like gpu at the beginning of execution.

Quite possibly.  To address this, when you run configure.py, you need to ensure that you tell TF to build for sm_XY corresponding to your machine's GPU.

**Comment by Saduf2019** [comment] 2020-07-14 11:05
@gulingfengze  
Please confirm if this is still an issue, or if possible use later stable versions of tf and let us know.

**Closed** 2020-07-28 12:32 UTC
Labels: comp:apis, stalled, stat:awaiting response, type:bug
