### ISSUE TITLE
TypeError: Input 'y' of 'Sub' Op has type int64 that does not match type int32 of argument 'x'.

### ISSUE THREAD

**Issue by dockiHan** [tensorflow/tensorflow#30404] opened 2019-07-04 08:01 UTC
System Info:
OS:  Mac OS 10.14.5
Python Version: 2.7.13
Tensorflow Version: 1.10.0 (CPU)
Tensorflow Installation: conda + pip install

---------------------------------------------------------

Issue Description:

I have a slice operation ( tf.slice ) in model graph.  the 'dtype'  of 'begin' and 'size' in tf.slice() is defined 'tf.int64', which looks like:
```python
begin_tensor = tf.convert_to_tensor([0, 0, 0, 0], dtype=tf.int64)
size_tensor = tf.convert_to_tensor([-1, -1, 1, -1], dtype=tf.int64)
# shape of A_t is [batch_size, max_sequence_len, hidden_dim, hidden_dim]
transition_A_t = tf.squeeze(tf.slice(A_t, begin=begin_tensor, size=size_tensor), axis=2)
```
When I start to train, it shows the error:
**TypeError: Input 'y' of 'Sub' Op has type int64 that does not match type int32 of argument 'x'.**
 From the Traceback, I guess there's something wrong in the backpropagation and gradient computation.

And everything goes on well when  I change the 'dtype'  of 'begin' and 'size' from 'tf.int64' to 'tf.int 32'  which likes:
```python
begin_tensor = tf.convert_to_tensor([0, 0, 0, 0], dtype=tf.int32)
size_tensor = tf.convert_to_tensor([-1, -1, 1, -1], dtype=tf.int32)
```
I don't know why there will be a tensor with dtype=tf.int32 in gradient computation. I'm sure the dtype of variables I defined is either tf.float32 or tf.int64.
I'm not sure if this is a bug. But it really confuses me for a long time. Please have look !
The whole Traceback is as follows:

> Traceback (most recent call last):
  File "/Users/xxx/working/xxx_project/classifiers/train_seasonal_content_classifier.py", line 230, in <module>
    tf.app.run()
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/Users/xxx/working/xxx_project/classifiers/train_seasonal_content_classifier.py", line 224, in main
    eval_result, _ = tf.estimator.train_and_evaluate(classifier, train_spec=train_spec, eval_spec=eval_spec)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 451, in train_and_evaluate
    return executor.run()
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 590, in run
    return self.run_local()
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/estimator/training.py", line 691, in run_local
    saving_listeners=saving_listeners)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1170, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Users/xxx/working/xxx_project/classifiers/models/universal_transformer_multi_tags_classifier.py", line 50, in model_fn
    mode=mode)
  File "/Users/xxx/working/xxx_project/classifiers/losses/multi_tags_loss.py", line 43, in process_multi_tag_loss_fn
    grads = tf.gradients(total_loss, tvars)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 779, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 398, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 779, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/ops/array_grad.py", line 250, in _SliceGrad
    array_ops.shape(input_vec) - slice_size - begin_vec, shape)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 8188, in sub
    "Sub", x=x, y=y, name=name)
  File "/Users/xxx/anaconda3/envs/tensorflow_1_10_py2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Sub' Op has type int64 that does not match type int32 of argument 'x'.

**Comment by rmothukuru** [comment] 2019-07-05 09:51
@dockiHan ,
Is there any specific reason that you are using Older Version of TF (1.10). If possible for you, can you please upgrade the TF Version to 1.14 and confirm if the issue still persists.

If the issue persists, can you please provide the value of Input Tensor (A_t) so that we can reproduce the error at our end.

**Comment by rmothukuru** [comment] 2019-07-17 09:52
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-07-17 09:52 UTC
Labels: comp:ops, stat:awaiting response

**Comment by cag472** [comment] 2019-07-28 00:06
I have the same problem in both 1.10 and 1.14. Problem occurs when I slice a tensor and use the slice in the loss function. Sorry no MWE.

**Comment by MoustafaMeshry** [comment] 2019-09-29 20:40
> I have the same problem in both 1.10 and 1.14. Problem occurs when I slice a tensor and use the slice in the loss function. Sorry no MWE.

Make sure to cast the indices you use for slicing to int32.

**Comment by agad495** [comment] 2020-05-11 21:06
@MoustafaMeshry can you please explain what you mean by casting the indices used for slicing to int32? Thanks!

**Comment by MoustafaMeshry** [comment] 2020-05-11 22:43
I meant to cast the "begin" and "size" arguments to int32 before passing them to tf.slice. However, looking at the [documentation](https://www.tensorflow.org/api_docs/python/tf/slice) of `tf.slice(input, begin, size)`, it seems that it now supports both int32 or int64 dtypes for the "begin" / "size" arguments.
