### ISSUE TITLE
Not supported for GpuManagedAllocator

### ISSUE THREAD

**Issue by ghostplant** [tensorflow/tensorflow#16239] opened 2018-01-19 10:41 UTC
GpuManagedAllocator was early supported at tensorflow/core/common_runtime/gpu/gpu_managed_allocator.cc.
But it seems there is no choice for users to use it according to the source code?
The GpuManagedAllocator can help to enlarge virtual GPU memory to fit huge training models, so it is very important to support them.
So what is the plan next about this feature?

**Comment by aselle** [comment] 2018-01-22 03:54
Do you have a concrete model that doesn't work well with our allocator that the ManagedAllocator works better on.  The code comments that the speed is worse with managedallocator since it migrates dirty pages. Perhaps that means your model wouldn't work as well with it anyways.

@zheng-xq, do you have any quick way to enable this mode for general running so @ghostplant could check if that helps their situation.

**Comment by ghostplant** [comment] 2018-01-22 11:40
@aselle It is really necessary. :)

I will provide some facts of deep learning models and why current tensorflow memory management is not suitable.

## 1. Tensorflow model migration problem:

Whatever MNIST_CNN, Alexnet, Inception, Resnet. etc, all nerual networks have a fixed structure so their GPU memory occupation can be precisely calculated if `batch_size` is given. So users expect a way that Tensorflow can provide something like `per_process_gpu_memory_quota_mb` in place of `per_process_gpu_memory_fraction`, because the latter makes the model migration very inconvenient. We expect a way like this:

```sh
(Assume MNIST_CNN model costs only 400MB GPU memory)
config.gpu_options.per_process_gpu_memory_quota_mb=400
```

However, currently the source code can be only like this:
```sh
config.gpu_options.per_process_gpu_memory_fraction=0.2
```
When the above code is executed using different GPUs (e.g. 16GB, 1GB), 16GB-GPU can succeed but 1GB-GPU will report BFC out-of-memory which is really annoying...


## 2. Huge model (inceptionV4, etc) training on Tensorflow problem:

VGG_VP and Inception models are known as huge deep learning models, whose convolutional filters are too large so they usually costs extremely-large GPU memory, e.g. at least 8GB memory is required by VGG_VP.

Assume we have a GPU memory of 2GB, and a host memory of 16GB. Based on the current Tensorflow management, VGG_VP and Inception CANNOT efficiently run on this GPU since Tensorflow only allocate full 2GB GPU memory which is way not enough.  If we use GpuManagedAllocator, it can allow to allocate up to 2GB + 16GB memory in total, so the VGG_VP and Inception models can be well fit in this GPU, and the training performance is very near to all-data-on-GPU-memory (85-95% according to our experiment).

So we expect something like:
```sh
config.gpu_options.allocator_type='GpuManaged'
```

In a word, I think BFC out-of-memory is really a high-frequent problem that reduces the user experience when using Tensorflow to train HUGE model, and above 2 suggestions are very helpful and supporting GpuManagedAllocator is a must to fix them in the first place.

**Comment by ghostplant** [comment] 2018-01-22 11:43
If you are interested in supporting this, maybe I can help on some of the implementing. :)

**Comment by zheng-xq** [comment] 2018-01-22 18:39
The current managed allocator is only used for internal testing purpose, and not exposed to real models. Adding @chsigg.

The down side of using cudaMallocManaged directly is that it forces a device/host synchronization on a fine granularity. That's why TF currently use a BFC suballocator.

That being said, it is worth trying to use cudaMallocManaged as the underlying TF allocator.

https://github.com/tensorflow/tensorflow/blob/4806cb0646bd21f713722bd97c0d0262c575f7e0/tensorflow/stream_executor/cuda/cuda_driver.cc#L934

We will have to test it on real models to see if there are a positive effect.

**Comment by ghostplant** [comment] 2018-01-23 02:57
I think BFC can still be used by default, while it also allows users to select `allocator_type='GpuManaged'`.
Besides, `config.gpu_options.per_process_gpu_memory_quota_mb=8192` is also needed because if your GPU has only 2GB memory, while you want to train an InceptionV3 model which requires 8GB tensor memory, Tensorflow will currently only allocate 2GB by default, so a larger memory allocation is needed which can be done by GpuManagedAllocator.

**Comment by zheng-xq** [comment] 2018-01-23 03:16
I'd like to see some measurements before enabling this feature.

In your example, it is unclear whether it is better to ask for 8GB of memory on a 2G GPU and having the Cuda system software swapping around. Or having the model use a smaller batch size. Many models have a batch size lower limit, mainly because of the batchnorm, but it is often much smaller than the regular setting.

The alternative is to swap memory explicitly in your model, such as set "swap_memory=True" in tf.while_loop. When the framework knows your execution schedule, it has more knowledge to make good choice on when to swap the memory before the execution.

**Comment by ghostplant** [comment] 2018-01-23 07:55
@zheng-xq 
I did a initial experiment as follows:

GPU-Version: Nvidia Tesla-P100, with 16GB GMem


==> model-A: Tensorflow-MNIST_CNN -- 28x28x1
1) batch_size=32
GMem-Current-TF: 49.070s (Real GMem Cost: 16000MB)
GMem-Managed-TF: 52.110s (Real GMem Cost: 600MB)


==> model-B: Keras-Resnet20 (using TF backend) -- 32x32x3
1) batch_size=32
GMem-Current-TF: 328.38s (Real GMem Cost: 16000MB)
GMem-Managed-TF: 330.676s (Real GMem Cost: 500MB)

2) batch_size=512
GMem-Current-TF: 1m11.385s (Real GMem Cost: 16000MB)
GMem-Managed-TF: 1m12.837s (Real GMem Cost: 2295MB)

3) batch_size=4096
GMem-Current-TF: 1m6.825s (Real GMem Cost: 16000MB)
GMem-Managed-TF: 1m9.154s (Real GMem Cost: 13000MB)

4) batch_size=8192
GMem-Current-TF: FATAL-ERROR. (Cannot support due to Out-of-BFC allocator)
GMem-Managed-TF: 6m59.930s (Real GMem Cost: 16000MB)


==> model-C: Keras-VGG16 (using TF backend) -- 224x224x3
1) batch_size=32
GMem-Current-TF: 109.448s (Real GMem Cost: 16000MB)
GMem-Managed-TF: 111.907s (Real GMem Cost: 8000MB)

2) batch_size=128
GMem-Current-TF: 301.289s (Real GMem Cost: 16000MB)
GMem-Managed-TF: 302.360s (Real GMem Cost: 14000MB)

3) batch_size=256
GMem-Current-TF: FATAL-ERROR. (Cannot support due to Out-of-BFC allocator)
GMem-Managed-TF: 548.711s (Real GMem Cost: 16000MB)

**Comment by zheng-xq** [comment] 2018-01-23 18:16
@ghostplant, thanks for the experiments, they look interesting.

Since users can control batch size, what is really important is whether they can get a higher throughput using more memory.

With your model-B Resnet20 result, at batch_size=8192, the throughput is 19.5 images/sec; at batch_size=4096, it is 61.31. So I don't think it is worthwhile to go for more managed memory.

With your model-C VGG16, the results is quite interesting: at batch_size=256, you get 0.46 images/sec; while at batch_size=128, you get 0.42 images/sec. So in this case, managed memory helps.

Could you share the patch for your experiment? I'll ask @chsigg to double check that. If everything looks good, I think this is a valuable contribution. Thanks!

**Comment by ghostplant** [comment] 2018-01-24 06:46
@zheng-xq 

On linux, we can just replace its underlay symbol link of cuMemAlloc_v2, which doesn't require to recompile Tensorflow project, but it is just for temporary experiment.


File `main.c`
```sh
/*
Compiling and Run Example:

1) gcc main.c -o replace.so -I/usr/local/cuda/include -L/usr/local/cuda/lib -shared -fPIC -lcudart -lcuda -ldl

2) LD_PRELOAD=`pwd`/replace.so python3 mnist_cnn.py   # to run keras examples with replaced API

3) nvidia-smi | grep -i def   # to see memory cost
*/

#include <stdio.h>
#include <assert.h>
#include <cuda.h>
#include <cuda_runtime.h>
#include <dlfcn.h>

CUresult cuMemAlloc_v2(CUdeviceptr *dptr, size_t bytes){
  printf("cuMemAlloc_v2 => bytes = %zd\n", bytes);
  static void *hd = NULL;
  if (!hd)
    assert((hd = dlopen("/usr/local/cuda/lib64/libcudart.so.8.0", RTLD_LAZY)) != NULL);
  return ((int(*)(void**, size_t, int))dlsym(hd, "cudaMallocManaged"))((void**)dptr, bytes, cudaMemAttachGlobal);
}

CUresult cuMemFree_v2(CUdeviceptr dptr) {
  assert(0);
  return CUDA_SUCCESS;
}
```

**Comment by ghostplant** [comment] 2018-01-24 10:57
Is `config.gpu_options.per_process_gpu_memory_quota_mb=xxx` going to be supported? I think this will help to describe the basic memory usage of a model and makes the same model to conveniently execute among different kinds of GPU.

**Comment by zheng-xq** [comment] 2018-01-24 18:37
Thanks for the experiments! This looks convincing enough. I'll ask @chsigg to look into this. Thanks!

**Comment by tensorflowbutler** [comment] 2018-02-10 19:18
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-03 07:50
Nagging Assignee @chsigg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-17 15:01
Nagging Assignee @chsigg: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ghostplant** [comment] 2018-03-17 16:52
Is this already supported now by some config.flags?

**Comment by smit-hinsu** [comment] 2018-04-03 01:18
Sorry for the delay in the follow-up.

I ran various experiments with some of the models in tf_cnn_benchmarks to observe model throughput using different batch sizes with cuMemAlloc and cuMemAllocManaged. It seems that cuMemAllocManaged does not really help increase the peak throughput observed across different batch sizes for a model. So, it should be possible to increase throughput for vgg16 model by adjusting the batch size without using batch size of 8192 and managed memory. By the way, the reported runtime for vgg16 model seems far too low for it to be the per-step duration. It should be possible to get much higher throughput for vgg16 using P100. Is that duration for N steps or something else? 

Now going back to the two points you mentioned in your initial comments:

**Huge model training**: As zheng-xq mentioned earlier, memory requirement for huge models can be decreased by decreasing the batch size. Using higher batch size by using managed memory does not seem to be giving a higher throughput. On the flip side, this can significantly slow down the training. This can be observed in the runtime you reported for Resnet20 model with batch size of 8192 which runs 6x times slower compared to batch size of 4096. I believe the slower model will be much more difficult to debug compared to the BFC out-of-memory failure.

**Model migration problem**: I believe, it might be worth considering absolute memory limits support along with specifying it as a fraction of the GPU memory. Just to further understand your use-case, could you provide more details about your use-case that will benefit with such an option? For example, do you generally run multiple models concurrently on a single GPU? If that is the case, then the scheduler will still need information about the total memory available in a particular GPU to decide how many models can safely run at the same time. If that is true then it should be possible to get memory requirement as a fraction of GPU memory based on the absolute limit and total memory in the GPU. However, I believe your use-case is different.

Thanks for reporting this and also sharing the experiment results.

**Comment by ghostplant** [comment] 2018-04-03 05:39
Hi @smit-hinsu , the source code of VGG16 is a keras-based implementation and executed with Tensorflow backend, and all each the time I posted stand for the real time spent to finish 1 epoch training, this is related to the scale of input data so absolute value is meaningless here.

**Huge model training** I just want a friendly way to get over BFC-overflow problem when using tensorflow, because the overflow is slow, not catch-able by python runtime and it is even hard to kill. Using GpuManagedAlloc is a suitable way to avoid such bad status for huge model.

**Model migration problem** User sensitive to absolute memory is definitely needed because they want to not only evaluate the resource usage for their defined models, but also know a model is runnable on a certain GPU from a hybrid cluster. However, considering the absolute memory is related to both model itself and also the batch_size, this value might not be a global constant one, so I recently think it would be better to to be able to pre-evaluate the memory occupation before sess.run, something like:

```sh
memory, .. = sess.evalutate_resources(target, ...)
sess.run(target, ...)
```
The value of memory can be a map of different devices, e.g:
```sh
memory = {
    '/gpu:0': 6000000000,
    '/gpu:1': 0
}
```

Thus, user can judge whether their model can fit into an unknown GPU, and also able to adjust a suitable batch_size completed before real session run.

```sh
free_memory = cuda.getMemFree(..)
batch_size = 256
while True:
    target = make_model(.., batch_size)
    if sess.evaluate_memory(target) > free_memory:
        batch_size /= 2
    else:
        break
# Safe to execute a model
sess.run(target)
```

**Comment by joe-of-all-trades** [comment] 2018-04-10 00:34
@smit-hinsu  I'm interested in this feature, too. In my case, I'm working on medical images of very large dimensions. For CT image, it could be 512*512*512 uint16. For pathology image, it could be larger 20000*20000*3 uint8. I can certainly do some cropping and resizing, but there's a limit. Even then, the image is way too big for a model to fit in a gpu. For me, it's the question of whether I can do it at all. I know there will be significant decrease in performance but without this feature, I can only give up on some tasks. 

I'd really appreciate this feature to be activated. I'm wondering if there's any way I can try it?

**Comment by ghostplant** [comment] 2018-04-10 00:46
@joe-of-all-trades This feature is only supported by NV cards that supports unified memory. Typically, Tesla P100 supports this feature, while Tesla K40c and all GTX cards doesn't.

**Comment by ghostplant** [comment] 2018-04-10 00:51
@joe-of-all-trades So for all normal NV cards, the basic method is still to reduce the batch_size when training models.

**Comment by joe-of-all-trades** [comment] 2018-04-10 01:05
@ghostplant  I'm using p40 so I believe think it should work ?  If I were to try, should I just follow the steps you listed in one of your previous comments that "we can just replace its underlay symbol link of cuMemAlloc_v2" ? Can you elaborate in a little more details ?  I don't quite understand how you did it.

**Comment by ghostplant** [comment] 2018-04-10 02:03
@joe-of-all-trades Yes, actually this only works on Linux. The procedure is compile `main.c` to `main.out` and then `export LD_PRELOAD=/where/is/your/main.out`. Finally, execute your tensorflow application within this session.

**Comment by tensorflowbutler** [comment] 2018-04-24 18:39
Nagging Assignee @smit-hinsu: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by smit-hinsu** [comment] 2018-05-08 08:52
Update: I am currently working on a change that introduces an option to make use of the unified memory supported by Pascal and newer GPUs. I will update this issue once that is available for use. After that, I will internally propose adding an option to specify memory limit as an absolute limit.

Regarding the "BFC-overflow" problem, that feels like a separate issue to me and is unexpected. Could you help file a different issue describing a way to reproduce the problem? Ideally, high memory usage should fail gracefully regardless of the unified memory support.

Thanks for adding more details about the use-case.

**Comment by ghostplant** [comment] 2018-05-09 14:18
Sound great! By using unified memory, users should be allowed to specify memory limit larger than GPU device memory.

**Comment by smit-hinsu** [comment] 2018-05-15 06:59
The change is currently in review.

Did you consider using MaxBytesInUse method that reports the peak memory usage of a device to find if a particular model and batch_size pair are runnable on an unknown GPU?
See https://www.tensorflow.org/api_docs/python/tf/contrib/memory_stats/MaxBytesInUse

**Comment by ontheway16** [comment] 2018-05-19 06:42
Hi, I am wondering if unified memory may help on inference side..?
I am currently using cpu-inference for object detection since my images are very high resolution, so any help coming by UM would be great.

**Comment by ghostplant** [comment] 2018-05-20 03:55
@smit-hinsu Is `MaxBytesInUse` to report memory usage during training or before training?

**Comment by ghostplant** [comment] 2018-05-20 04:03
@ontheway16 
I think unified memory will just allow you to do training/inference using large models without caring about GPU OOM. But when the model is huge to completely fit into whole device memory, it is also likely to slow down.
However, if not using unified memory, these huge models are even not able to run.

**Comment by ghostplant** [comment] 2018-05-20 04:08
@smit-hinsu Can you tell what the in-review change is going to support? e.g. Allow users to set fixed memory allocation quota? Allow users to enable `cudaMallocManaged` instead of `cuMemAlloc_v2`?

**Comment by ontheway16** [comment] 2018-05-20 06:42
@ghostplant I am comparing infererence performance under unified memory vs cpu only conditions, after completion the training in gpu mode. I think there will be some speed gain against cpu only inference.

**Comment by smit-hinsu** [comment] 2018-05-23 06:01
Regarding MaxBytesInUse, it would only be useful to find the peak memory usage in case when it does not run out of memory.

The in-review change supports use of cuda unified memory. Should be available at HEAD in one or two days.

It does not support absolute memory limit and it is still configured using the per_process_gpu_memory_fraction field. It would be possible to set greater than 1.0 value after the change. Absolute memory limit can be converted to the fraction using the BytesLimit method.
https://www.tensorflow.org/api_docs/python/tf/contrib/memory_stats/BytesLimit

Hope this helps!

**Comment by smit-hinsu** [comment] 2018-05-25 21:49
Following commit adds support for the unified memory. Sorry for the long delay.
https://github.com/tensorflow/tensorflow/commit/b1139814f91c5216eb5ff229ee7e1982e5f4e888

Closing this issue. Let me know if this helps you or you have any follow-up questions.

**Closed by smit-hinsu** 2018-05-25 21:49 UTC
Labels: type:feature

**Comment by sulantha2006** [comment] 2018-12-28 11:15
Hello, 
Thanks for the support of unified memory. Is there a config that needs to be set to using unified memory?

**Comment by sulantha2006** [comment] 2019-01-03 00:12
Hi, 
I was wondering, in a system with 2 GPUs with NVLINK interconnect (45GB/s, Peer-to-Peer working), `config.gpu_options.per_process_gpu_memory_fraction = 1.5` would use 0.5 of the second GPU instead of the host memory. 

If not, how can this be done? 
Thanks for the information.

**Comment by sulantha2006** [comment] 2019-01-03 04:07
Thanks. Mesh-tensorflow can be a solution, but it won't be as a plugin replacement for keras based models. 

Is it possible to share the GPU memory instead of host memory, if they already have UVA capability (at least with some config)? This way, GPU memory will be used first.
