### ISSUE TITLE
Tensorflow not showing summaries anymore

### ISSUE THREAD

**Issue by panmari** [tensorflow/tensorflow#718] opened 2016-01-07 12:56 UTC
On current master, the tensorboard will start as intended but only show the 'No scalar summaries found' error message. In the log, there are two errors:

```
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/external/paper-tabs/paper-tabs.html' on path /usr/local/lib/python2.7/dist-packages/external/paper-t
abs/paper-tabs.html

... some GET

WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/runs' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/runs
```

**Comment by skearnes** [comment] 2016-01-07 15:27
+1

**Comment by skearnes** [comment] 2016-01-07 16:59
Seems to be fixed by 5d824f1.

**Comment by panmari** [comment] 2016-01-08 12:47
Summaries are shown again, but the navigation is still broken. In the log there is still this error:

    WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/external/paper-tabs/paper-tabs.html' on path /usr/local/lib/python2.7/dist-packages/external/paper-tabs/paper-tabs.html

And clicking on e. g. `images` does redirect to `http://localhost:6006/#null`. Manually entering `http://localhost:6006/#images` works.

**Comment by danmane** [comment] 2016-01-08 19:42
Thanks for the report. The issue is that we took a dependency on paper-tabs but didn't update the root.workspace rule to download paper-tabs (there was a bug in the synchronization script). It's fixed now and should make its way to master shortly.

**Closed by danmane** 2016-01-08 19:42 UTC
Labels: tensorboard
