### ISSUE TITLE
tf.while example is not working in eager mode

### ISSUE THREAD

**Issue by arogozhnikov** [tensorflow/tensorflow#18257] opened 2018-04-05 11:39 UTC
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, see below
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.7, release
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 9.0 / 7.0
- **GPU model and memory**:  GTX TITAN, 6GB
- **Exact command to reproduce**: see below

### Describe the problem

`tf.while` example is not working in eager mode

### Source code / logs

Here is the code 
```python
import tensorflow as tf
tf.enable_eager_execution() # the only line added to the example

i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: tf.add(i, 1)
r = tf.while_loop(c, b, [i])
```

result:
TypeError: Cannot iterate over a scalar tensor.

### Reason

```python
b = lambda i: tf.add(i, 1)       # original
b = lambda i: (tf.add(i, 1), )   # fixed, working 
```

- Body code (`b`) returns a single scalar, which code later tries to unpack.
- Eager code doesn't support auto-wrapping single item to tuple

Possible solutions:
- require body function to always return tuple
- always check if body output is a single variable

**Comment by asimshankar** [comment] 2018-04-06 21:02
Thanks for the report, @akshaym is looking into fixing that.

**Comment by Danmou** [comment] 2019-10-24 11:00
This is fixed on TF 1.15 but broken on TF 2.0.

**Comment by akshaym** [comment] 2019-10-24 16:20
I can reproduce this on 2.0. @saxenasaurabh can you please help take a look?

**Comment by datdinhquoc** [comment] 2020-02-12 07:07
On Colab, TF 2, api: https://www.tensorflow.org/api_docs/python/tf/while_loop

Example in api doc:
```
i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: tf.add(i, 1)
r = tf.while_loop(c, b, [i])
```

TF 2 on Eager mode by default:<br/>
`TypeError: Cannot iterate over a scalar tensor.`

**Comment by yaowang1111** [comment] 2020-07-19 15:10
Has this bug been solved? I run tf2.1 and the problem is still there.

**Comment by lucagrementieri** [comment] 2021-06-25 09:31
The documentation has been update with the working code
```
i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: (tf.add(i, 1), )
r = tf.while_loop(c, b, [i])
```

I deduce that the `body` function should always return an iterable of the same size of `loop_vars` to work in Eager mode.

**Comment by mohantym** [comment] 2022-01-20 07:01
I was able to replicate this issue in [2.7 ](https://colab.sandbox.google.com/gist/mohantym/38a9d55e009edf9022393bf073f37dab/github_18257.ipynb)

**Comment by Engineero** [comment] 2022-01-21 22:48
It turns out this has been causing a headache for me through several versions of TF 2.x. I anxiously await a resolution.

**Closed** 2022-02-05 00:16 UTC
Labels: stat:awaiting response, stalled, comp:ops, TF 2.7
