### ISSUE TITLE
batch_flatten gives unpredictable results when batch_size is 1

### ISSUE THREAD

**Issue by Joshuaalbert** [tensorflow/tensorflow#13568] opened 2017-10-08 14:35 UTC
## Problem

When I attempt to use `tf.contrib.keras.backend.batch_flatten` or more readily `keras.backend.batch_flatten` on a Tensor of shape (1, a, b) it produces a Tensor with shape (None, None).

## MCVE

Note, I'll use keras tensorflow backend because that is how I noticed it. 

```
t = K.zeros((1,2,2))
print(K.int_shape(K.reshape(t,(-1,2*2))))
print(K.int_shape(K.batch_flatten(t)))
```
prints out `(1,4)` and `(None, None)`.
If you replace the first dimension to 2 or more it works as expected.

## System

tensorflow 1.2.0 
keras 2.0.8 python 3.6 installed from git repo

**Comment by yaroslavvb** [comment] 2017-10-08 18:07
cc @fchollet 
(is there a separate list for keras issues?)

**Comment by ozabluda** [comment] 2017-10-20 23:47
This was caused by https://github.com/fchollet/keras/pull/3253. The repository also has a list for keras issues.

**Comment by ozabluda** [comment] 2017-10-27 00:37
Maybe PR https://github.com/tensorflow/tensorflow/pull/13561 fixes it.

**Comment by tensorflowbutler** [comment] 2017-12-20 01:11
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-03 19:04
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-18 19:06
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-06 07:49
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-07 13:22
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 00:57
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-25 19:00
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 12:43
Nagging Assignee @tatianashp: It has been 195 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:11
Nagging Assignee @tatianashp: It has been 211 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:43
Nagging Assignee @tatianashp: It has been 226 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:08
Nagging Assignee @tatianashp: It has been 241 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:00
Nagging Assignee @tatianashp: It has been 256 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 18:55
Nagging Assignee @tatianashp: It has been 271 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 12:59
Nagging Assignee @tatianashp: It has been 286 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:42
Nagging Assignee @tatianashp: It has been 301 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:36
Nagging Assignee @tatianashp: It has been 316 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:43
Nagging Assignee @tatianashp: It has been 331 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatianashp** [comment] 2018-09-23 23:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by tatianashp** 2018-09-23 23:13 UTC
Labels: stat:awaiting tensorflower
