### ISSUE TITLE
 Why 'tf.python_io.TFRecordWriter' is so SLOW and STORAGE-CONSUMING in TensorFlow?

### ISSUE THREAD

**Issue by ericyue** [tensorflow/tensorflow#4467] opened 2016-09-19 17:20 UTC
I'm going to write to TFRecord file using this [code](https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/examples/how_tos/reading_data/convert_to_records.py#L68) The problem is that this process is very slow, such that it's not feasible to write a large dataset even in days! It's just a writer that serialize to disk. Why it's so slow?! Another problem is that the size of the output file is 10 times greater than the original file!

does anyone know any way to speed up the process of TFRecordWriter and compress the result?

**Comment by fwalch** [comment] 2016-09-19 17:26
Regarding compression, see https://github.com/tensorflow/tensorflow/blob/4addf4b5806cd731949c6582a83f5824599cd1ef/tensorflow/python/lib/io/tf_record.py#L26

**Comment by ericyue** [comment] 2016-09-19 18:18
@fwalch   thanks,  but the most important thing is the speed.  I have to split the file to 100000 slice and using multiprocessing to process each.    
is there any optimize method for speed up ?

**Comment by ericyue** [comment] 2016-09-19 18:19
is there a c++ demo for tfrecord? maybe faster?

**Comment by titusnicolae** [comment] 2016-09-20 18:52
I'm also having trouble reading from TFRecord. I only get 25MB/s instead of the 250MB/s I could get out of the SSD.

**Comment by titusnicolae** [comment] 2016-09-21 14:09
@ericyue I'm having some succes with FixedLengthRecordReader. It reads at 150-160MB/s from SSD

**Comment by victor-shepardson** [comment] 2016-09-23 23:52
I'm having a similar problem; TFRecordWriter doesn't appear to be the issue, rather it's the protobuf library. BytesList() is slow, and SerializeToString() is mega-slow. Writing 1 MiB:

```
%%prun
def quantize(x):
    return x.astype(np.int8).tostring()
feats = {'':tf.train.Feature(bytes_list=tf.train.BytesList(value=quantize(np.ones((2**10, 2**10)))))}
example = tf.train.Example(features=tf.train.Features(feature=feats))
writer = tf.python_io.TFRecordWriter('/dev/null')
writer.write(example.SerializeToString())
```

```
         15729132 function calls (15729090 primitive calls) in 6.355 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    1.679    0.839    2.488    1.244 encoder.py:260(RepeatedFieldSize)
        1    1.292    1.292    2.881    2.881 encoder.py:711(EncodeRepeatedField)
  1048580    0.701    0.000    1.013    0.000 encoder.py:372(EncodeVarint)
  3145731    0.535    0.000    0.535    0.000 containers.py:202(__getitem__)
  3145748    0.440    0.000    0.440    0.000 {method 'write' of '_io.BytesIO' objects}
        1    0.366    0.366    0.841    0.841 containers.py:261(extend)
  1048576    0.359    0.000    0.471    0.000 type_checkers.py:100(CheckValue)
3145753/3145751    0.289    0.000    0.289    0.000 {len}
  2097157    0.283    0.000    0.283    0.000 encoder.py:82(_VarintSize)
  1048592    0.150    0.000    0.150    0.000 {chr}
  1048621    0.113    0.000    0.113    0.000 {isinstance}
        1    0.109    0.109    6.355    6.355 <string>:2(<module>)
        6    0.021    0.003    0.021    0.003 {method 'extend' of 'list' objects}
     16/6    0.003    0.000    0.862    0.144 python_message.py:474(init)
      9/4    0.003    0.000    2.495    0.624 python_message.py:1035(ByteSize)
      5/1    0.003    0.001    5.383    5.383 python_message.py:1077(InternalSerialize)
        1    0.003    0.003    0.003    0.003 {_pywrap_tensorflow.PyRecordWriter_WriteRecord}
        1    0.003    0.003    0.003    0.003 {method 'astype' of 'numpy.ndarray' objects}
        1    0.002    0.002    0.002    0.002 {numpy.core.multiarray.copyto}
        1    0.001    0.001    0.001    0.001 {method 'getvalue' of '_io.BytesIO' objects}
        1    0.000    0.000    0.000    0.000 {method 'tostring' of 'numpy.ndarray' objects}
     10/5    0.000    0.000    0.018    0.004 python_message.py:1233(MergeFrom)
        1    0.000    0.000    0.000    0.000 {_pywrap_tensorflow.PyRecordWriter_New}
       21    0.000    0.000    0.000    0.000 python_message.py:1362(__init__)
       12    0.000    0.000    0.000    0.000 python_message.py:790(ListFields)
        8    0.000    0.000    0.000    0.000 python_message.py:429(MakeSubMessageDefault)
       12    0.000    0.000    0.000    0.000 python_message.py:775(_IsPresent)
       12    0.000    0.000    0.000    0.000 {method 'sort' of 'list' objects}
        5    0.000    0.000    0.017    0.003 containers.py:280(MergeFrom)
        5    0.000    0.000    0.000    0.000 containers.py:541(__getitem__)
       18    0.000    0.000    0.000    0.000 python_message.py:1381(Modified)
      4/1    0.000    0.000    5.382    5.382 encoder.py:760(EncodeField)
       40    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
    21/12    0.000    0.000    0.000    0.000 python_message.py:1317(Modified)
        5    0.000    0.000    0.000    0.000 python_message.py:1397(__init__)
      2/1    0.000    0.000    0.000    0.000 python_message.py:1141(IsInitialized)
        6    0.000    0.000    0.000    0.000 python_message.py:421(MakeRepeatedScalarDefault)
        1    0.000    0.000    4.130    4.130 encoder.py:818(EncodeField)
        4    0.000    0.000    0.000    0.000 type_checkers.py:162(CheckValue)
        1    0.000    0.000    5.384    5.384 python_message.py:1071(SerializePartialToString)
        1    0.000    0.000    0.003    0.003 <string>:2(quantize)
        1    0.000    0.000    1.246    1.246 encoder.py:351(FieldSize)
        1    0.000    0.000    0.002    0.002 numeric.py:136(ones)
        5    0.000    0.000    0.000    0.000 python_message.py:1406(Modified)
        2    0.000    0.000    0.000    0.000 python_message.py:660(field_setter)
        6    0.000    0.000    0.000    0.000 containers.py:237(__init__)
       21    0.000    0.000    0.000    0.000 {_weakref.proxy}
      5/2    0.000    0.000    2.488    1.244 encoder.py:307(FieldSize)
        1    0.000    0.000    0.004    0.004 containers.py:595(MergeFrom)
        1    0.000    0.000    0.000    0.000 tf_record.py:57(__init__)
        8    0.000    0.000    0.000    0.000 python_message.py:537(_GetFieldByName)
        5    0.000    0.000    0.000    0.000 python_message.py:1332(_UpdateOneofState)
        6    0.000    0.000    0.000    0.000 containers.py:192(__init__)
       10    0.000    0.000    0.000    0.000 python_message.py:1004(SetListener)
        2    0.000    0.000    0.000    0.000 {setattr}
        1    0.000    0.000    0.000    0.000 python_message.py:271(_IsMapField)
        5    0.000    0.000    0.000    0.000 containers.py:206(__len__)
        1    0.000    0.000    0.000    0.000 {numpy.core.multiarray.empty}
        1    0.000    0.000    0.003    0.003 tf_record.py:78(write)
        2    0.000    0.000    0.000    0.000 python_message.py:379(MakeMessageMapDefault)
        1    0.000    0.000    0.000    0.000 {_codecs.utf_8_decode}
        1    0.000    0.000    5.384    5.384 python_message.py:1057(SerializeToString)
        2    0.000    0.000    0.000    0.000 python_message.py:651(getter)
        1    0.000    0.000    0.003    0.003 pywrap_tensorflow.py:183(WriteRecord)
        2    0.000    0.000    0.000    0.000 containers.py:525(__init__)
        2    0.000    0.000    0.000    0.000 descriptor.py:118(GetOptions)
        1    0.000    0.000    0.000    0.000 {method 'decode' of 'str' objects}
        2    0.000    0.000    0.000    0.000 containers.py:586(__len__)
        5    0.000    0.000    0.000    0.000 {method 'setdefault' of 'dict' objects}
       12    0.000    0.000    0.000    0.000 {method 'get' of 'dict' objects}
       12    0.000    0.000    0.000    0.000 python_message.py:792(<lambda>)
        1    0.000    0.000    0.000    0.000 compat.py:27(as_bytes)
        1    0.000    0.000    0.000    0.000 utf_8.py:15(decode)
        3    0.000    0.000    0.000    0.000 containers.py:589(__iter__)
        4    0.000    0.000    0.000    0.000 {iter}
        1    0.000    0.000    0.000    0.000 python_message.py:277(_IsMessageMapField)
        1    0.000    0.000    0.000    0.000 pywrap_tensorflow.py:182(<lambda>)
        2    0.000    0.000    0.000    0.000 {method 'pop' of 'dict' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

```
```
def quantize(x):
    return x.astype(np.int8).tostring()
writer = tf.python_io.TFRecordWriter('/dev/null')
%time q = quantize(np.ones((2**10, 2**10))) #fast
%time bl = tf.train.BytesList(value=q) #slow
%time example = tf.train.Example(features=tf.train.Features(feature={'':tf.train.Feature(bytes_list=bl)})) #fast
%time s = example.SerializeToString() #very slow
%time writer.write(s) #fast
```
```
CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 5.11 ms
CPU times: user 440 ms, sys: 4 ms, total: 444 ms
Wall time: 440 ms
CPU times: user 20 ms, sys: 0 ns, total: 20 ms
Wall time: 20.4 ms
CPU times: user 2.21 s, sys: 16 ms, total: 2.23 s
Wall time: 2.22 s
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 2.81 ms
```

i'm using the docker image tensorflow/tensorflow:latest-gpu with nvidia-docker on ubuntu 16.04

**Comment by vrv** [comment] 2016-09-23 23:54
Try installing a protobuf-python wheel that we have built that uses optimized C++ code internally: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#protobuf-library-related-issues

**Comment by victor-shepardson** [comment] 2016-09-24 01:17
@vrv thanks! I missed that.
the pip command succeeded, except for some SSL warnings, but now:
```
root@58fb67668f0f:/notebooks# cat test.py
import tensorflow as tf
root@58fb67668f0f:/notebooks# gdb python
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
...
Reading symbols from python...Reading symbols from /usr/lib/debug//usr/bin/python2.7...done.
done.
(gdb) run test.py
Starting program: /usr/bin/python test.py
warning: Error disabling address space randomization: Operation not permitted
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1562] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
During startup program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
No stack.
(gdb)
```
looks like I have a cuDNN problem too, but that was present already and I assume it is unrelated. If I pip uninstall protobuf, the cuda messages still print before protobuf throws an importerror.

**Comment by vrv** [comment] 2016-09-24 01:31
@victor-shepardson: We're not sure why but the binary protobuf wheel we build doesn't work for everyone and results in segfaults for some, but it does work for others.

You might need to figure out how to build the optimized python protobuf package on your own.  Hopefully the github.com/google/protobuf folks can help.

**Comment by vrv** [comment] 2016-09-24 01:32
I'm going to close this, since it looks like the problem is related to not using the optimized protobuf/python package, and isn't strictly related to TF.  Thanks for the helpful performance debugging @victor-shepardson !

**Closed by vrv** 2016-09-24 01:32 UTC

**Comment by ericyue** [comment] 2016-11-23 12:43
thanks , I will try the c++ version of protobuf

**Comment by ericyue** [comment] 2017-01-14 07:41
can you show me a demo code for using FixedLengthRecordReader to read tfrecord files? I think the tfrecord are not fixed length , how to do this ? @titusnicolae

**Comment by ed-alertedh** [comment] 2017-05-09 01:11
According to google/protobuf#1332 the wheel on pypi for protobuf 3.2.0 now includes the C++ implementation and uses it by default (although maybe not yet on OS X). I was able to verify this on linux x86_64:
```
$ pip show protobuf
Name: protobuf
Version: 3.2.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: New BSD License
Location: /home/ed/.pyenv/versions/3.6.1/envs/py36/lib/python3.6/site-packages
Requires: six, setuptools
$ python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
cpp
```

**Comment by patrikhuber** [comment] 2018-01-16 17:13
Unfortunately this doesn't seem the case on Windows (x64):
```
$ pip show protobuf
Name: protobuf
Version: 3.5.1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: c:\users\patrik\appdata\local\programs\python\python36\lib\site-packages
Requires: six, setuptools

$ python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
python
```

**Comment by ed-alertedh** [comment] 2018-01-16 22:29
I'm on Windows these days and I get the same result on cpython 3.6 :(

**Comment by jackz314** [comment] 2020-06-13 06:08
On Windows it seems like the protobuf is still the old version. I'm getting extremely slow speeds writing TFRecords even with multiprocessing, at this point I'd be better off using something like Keras sequence.

**Comment by Azmisov** [comment] 2020-08-14 02:22
TFRecordWriter was incredibly slow for me. The only thing that worked for me was converting the output tensors I wanted to save to numpy arrays, and then saving using pyarrow. Here is some code if it helps anybody:

```python
import pyarrow as pa
import pyarrow.parquet as pq
import shutil, os
import numpy as np

# For faster writing of tensorflow output
class ParquetWriter():
  # context manager stuff
  """ dir_path: directory to put parquet files
    cols: column names for schema
    chunk_size: how many rows per file = chunk_size*buffer_size
    buffer_size: how many rows to buffer before writing (not exact, if using add_rows)
    overwrite: delete existing directory/file if found  
  """
  def __init__(self, dir_path, cols, chunk_size=10, buffer_size=5000, overwrite=True):
    self.chunk_size = chunk_size
    self.buffer_size = buffer_size
    self.dir_path = dir_path
    self.cols = cols
    self.chunk = 0
    self.file = 0
    self.writer = None
    self.new_buffer()
  def __enter__(self): 
      return self
  def __exit__(self, exc_type, exc_value, exc_traceback):
    if self.writer:
      self.writer.close()
  # clears buffer (does not write)
  def new_buffer(self):
    self.buffer = []
    for i in range(len(self.cols)):
      self.buffer.append([])
    self.buffered = 0
  # actually perform write to parquet file
  def flush(self):
    print("parquet write chunk {}, rows {}".format(self.chunk, self.buffered))
    # convert to chunked pyarrow arrays, instead of list of numpy arrays
    for i in range(len(self.buffer)):
      bi = self.buffer[i]
      # apparently pyarrow can't do > 1d arrays; but doesn't complain if its a list
      if len(bi[0].shape) > 1:
        self.buffer[i] = np.vstack(bi).tolist()
      else:
        self.buffer[i] = pa.chunked_array(bi)
    tbl = pa.Table.from_arrays(self.buffer, names=self.cols)
    # create new file
    if not self.chunk:
      if os.path.exists(self.dir_path):
        if os.path.isfile(self.dir_path):
          os.remove(self.dir_path)
        else:
          shutil.rmtree(self.dir_path)
      os.makedirs(self.dir_path)
      self.writer = pq.ParquetWriter(os.path.join(self.dir_path, "chunk_{}.part".format(self.file)), tbl.schema)
    self.writer.write_table(tbl)
    self.chunk += 1
    self.new_buffer()
    # finished file
    if self.chunk == self.chunk_size:
      print("finished file {}".format(self.file))
      self.chunk = 0
      self.file += 1
      self.writer.close()
      self.writer = None
  # buffer/write multiple rows
  def add_rows(self, rcols):
    assert len(rcols) == len(self.cols), "Doesn't match column schema length"
    self.buffered += len(rcols[0])
    for i in range(len(self.buffer)):
      self.buffer[i].append(rcols[i])
    if self.buffered >= self.buffer_size:
      self.flush()
```

Use it like so:
```python
with ParquetWriter("some_directory_path", ["col1","col2"]) as f:
  # perform inference here
  f.add_rows(out_col1.numpy(), out_col2.numpy())
```

**Comment by gebob19** [comment] 2020-12-09 02:38
I was having the same problem writing a large dataset -- the writing speed would get slower the longer the process ran (starting at 1iteration/sec and going up to 11sec/iteration). 

The way I solved it was to spin up sub-processes in a loop to write smaller blocks of the data. Ideally the blocks would be small enough so that the writing would remain at 1iteration/second. 

For example my slow code originally was something like:
```
pool = multiprocessing.Pool(n_processes)
process_blocked_data = split(data, n_processes) 
for block in process_blocked_data: 
    pool.start(write_tfrecord, args=(block))
pool.join()
```
And I fixed it by splitting up the data even more:
```
# split the data into even smaller blocks
factor = 100 
blocked_data = split(data, factor) 

for block in blocked_data: 
   # assign smaller block to each process
   pool = multiprocessing.Pool(n_processes)
   process_blocks = split(block, n_processes) 
   for smaller_pblock in process_blocks: 
       pool.start(write_tfrecord, args=(smaller_pblock))
   pool.join()
```

Doing it this way reduced the total write time from 11+hours to 1hour. 

My best guess is that the writing slows down the longer the process is run because something is written/added to the graph at each write command which ends up leading to a very large graph which slows write speeds down significantly.
