### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by Caselles** [tensorflow/tensorflow#10408] opened 2017-06-02 21:55 UTC
I have a memory leak with TensorFlow. I refered to https://stackoverflow.com/questions/35695183/tensorflow-memory-leak-even-while-closing-session to address my issue, and I followed the advices of the answer, that seemed to have solved the problem. However it does not work here. 

In order to recreate the memory leak, I have created a simple example. First, I use this function (that I got here : https://stackoverflow.com/questions/276052/how-to-get-current-cpu-and-ram-usage-in-python) to check the memory use of the python process : 

    def memory():
        import os
        import psutil
        pid = os.getpid()
        py = psutil.Process(pid)
        memoryUse = py.memory_info()[0]/2.**30  # memory use in GB...I think
        print('memory use:', memoryUse)

Then, everytime I call the `build_model` function, the use of memory increases.

Here is the `build_model` function that has a memory leak : 
 
    def build_model():

        '''Model'''

        tf.reset_default_graph()

        with tf.Graph().as_default(), tf.Session() as sess:
            tf.contrib.keras.backend.set_session(sess)

            labels = tf.placeholder(tf.float32, shape=(None, 1))
            input = tf.placeholder(tf.float32, shape=(None, 1))

            x = tf.contrib.keras.layers.Dense(30, activation='relu', name='dense1')(input)
            x1 = tf.contrib.keras.layers.Dropout(0.5)(x)
            x2 = tf.contrib.keras.layers.Dense(30, activation='relu', name='dense2')(x1)
            y = tf.contrib.keras.layers.Dense(1, activation='sigmoid', name='dense3')(x2)

            loss = tf.reduce_mean(tf.contrib.keras.losses.binary_crossentropy(labels, y))

            train_step = tf.train.AdamOptimizer(0.004).minimize(loss)

            #Initialize all variables
            init_op = tf.global_variables_initializer()
            sess.run(init_op)

            sess.close()

        tf.reset_default_graph()

        return 

 I would have thought that using the block ` with tf.Graph().as_default(), tf.Session() as sess: ` and then **closing the session** and **calling `tf.reset_default_graph`** would clear all the memory used by TensorFlow. Apparently it does not.

The memory leak can be recreated as following : 

    memory()
    build_model()
    memory()
    build_model()
    memory()

The output of this is (for my computer) :

    memory use: 0.1794891357421875
    memory use: 0.184417724609375
    memory use: 0.18923568725585938

Clearly we can see that all the memory used by TensorFlow is not freed afterwards. Why?

I hope I made myself clear.

**Comment by jart** [comment] 2017-06-03 00:22
Would you be able to plot memory usage over a thousand iterations? That will help us rule out the possibility that the memory usage is caused by modules being loaded, or garbage collector fanciness. It would also be great if you could narrow down the number of APIs being called.

**Comment by Caselles** [comment] 2017-06-03 13:01
![image](https://cloud.githubusercontent.com/assets/19774802/26753716/0e980254-486d-11e7-9ac8-4f57150b7815.png)
@jart Here you go. As you can see, the memory usage goes up in a linear way, which is exactly the problem.

About the number of APIs being called, do you refer to Keras by saying that ? I only use tf.contrib.keras, which is part of tensorflow. Hence I only use tensorflow here.

**Comment by jart** [comment] 2017-06-03 20:37
@Caselles Excellent. Thank you.

@fchollet There appears to be some type of memory leak in Keras.

**Comment by Dref360** [comment] 2017-06-05 15:43
Early tests seems to show that 
_GRAPH_LEARNING_PHASES is not cleared so there is tons of tensors that get kept.

Changing to ```def reset_uids():
  global _GRAPH_UID_DICTS
  global _GRAPH_LEARNING_PHASES
  _GRAPH_UID_DICTS = {}
  _GRAPH_LEARNING_PHASES = {}```

Seems to resolve the problem. 

> memory use: 0.13166046142578125
memory use: 0.13190841674804688
memory use: 0.13220977783203125
memory use: 0.13220977783203125
memory use: 0.13220977783203125
memory use: 0.13220977783203125
memory use: 0.13220977783203125
memory use: 0.13220977783203125

**Comment by Dref360** [comment] 2017-06-05 16:12
This is actually fixed in keras master branch.
https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L82
So waiting for the merge will fix the problem.

**Comment by fchollet** [comment] 2017-06-05 17:42
@Dref360 this is fixed in TF master: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/keras/python/keras/backend.py#L288

Does this resolve the problem?

**Comment by Dref360** [comment] 2017-06-05 17:50
K.clear_session is never called. maybe K.set_session should do a clear_session?

**Comment by Caselles** [comment] 2017-06-05 18:56
Before posting this issue, I tried calling K.clear_session(), but my tensorflow version was 1.1... Never lucky. By upgrading to 1.2 and calling K.clear_session(), the problem was solved. Thank you very much 👍

**Comment by fchollet** [comment] 2017-06-05 19:02
Independently of `clear_session`, I would expect the use of graph scopes to prevent this behavior. What's the status of that?

**Comment by Dref360** [comment] 2017-06-06 14:16
The graph is not cleared. Maybe because we still have a reference to it so the GC doesn't collect?
If you print `list(_GRAPH_LEARNING_PHASES.values())[1].graph.get_operations()` you can see that the operations are still there.

**Comment by Caselles** [comment] 2017-06-11 10:26
So the use of graph scopes will not prevent this behavior. Is this planned to be solved ? 

@Dref360 : Would you have a workaround to clear the operations still in the graph ? I would like **not** to clear all the operations in the graph, but only those that are created within the `with tf.Graph().as_default(), tf.Session() as sess:` block.

**Comment by fchollet** [comment] 2017-06-12 17:50
The solution is to make learning phases part of a graph collection, I believe. Potentially the same may also be true of layer name UIDs, which also keeps graph references.

Last time we tried this it caused a useless warning upon graph serialization which annoyed/scared users. We will also have to figure out how to remove that warning.

**Comment by Caselles** [comment] 2017-06-12 18:05
Ok thank you. Would you have a workaround for now ? In order to clear only the operations within the `with tf.Graph().as_default(), tf.Session() as sess:` block.

**Comment by fchollet** [comment] 2017-06-12 18:10
Add `K.clear_session()` at the end of your block (inside the block).

**Comment by Caselles** [comment] 2017-06-13 17:55
Problem is, I'm trying to run two model at the same time in a website. Hence, calling `K.clear_session` in the code clears operations that are used elsewhere. So this creates a bug. I really need to be able to specify the operations that I want to clear. Could you be a little more precise on how I could do that ?

**Comment by fchollet** [comment] 2017-06-13 18:27
There are only two possibilities:
1) you no longer use the graph. In that case `clear_session` destroys it,
and that is what you want.
2) you are still using the graph. In that case you cannot garbage-collect
it. And you don't have a "memory leak".

**Comment by Caselles** [comment] 2017-06-13 19:58
I'm sorry for not saying that earlier but calling `K.clear_session()` within the `tf.Graph().as_default(), tf.Session() as sess:` yields an error : 

IndexError                                Traceback (most recent call last)
<ipython-input-7-7793873c5c17> in <module>()
----> 1 build_model()

<ipython-input-6-3626073d2002> in build_model()
     31 
     32         K.set_session(sess)
---> 33         K.clear_session()
     34 
     35     tf.reset_default_graph()

/Users/Syzygy/anaconda/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     75                 value = type()
     76             try:
---> 77                 self.gen.throw(type, value, traceback)
     78                 raise RuntimeError("generator didn't stop after throw()")
     79             except StopIteration as exc:

/Users/Syzygy/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in get_controller(self, default)
   3626     finally:
   3627       if self._enforce_nesting:
-> 3628         if self.stack[-1] is not default:
   3629           raise AssertionError(
   3630               "Nesting violated for default stack of %s objects"

IndexError: list index out of range

**Comment by rohanag** [comment] 2017-06-29 18:42
has there been any progress on this issue? I have the exact same problem, and exact same error while calling clear_session. I'm using the latest keras and tensorflow version.

**Comment by myyan92** [comment] 2017-10-23 20:33
I have a very similar issue causing memory leak, but I'm only using tensorflow without keras. Here's the minimal code:

import tensorflow as tf
import numpy as np
for i in range(30):
    tf.Session().__enter__()
    tf.constant(np.random.random((800,500,500,1)))
    tf.get_default_session().close()
    tf.reset_default_graph()


When executing the loop the memory used keeps going up. How can I actually delete the old large constants and free the memory?
I'm using tensorflow 1.2 with python 3.4 on ubuntu 14.04

**Comment by tensorflowbutler** [comment] 2017-12-20 19:11
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-04 19:16
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tr1pzz** [comment] 2018-01-05 12:09
I have a similar problem where I am using a bunch of functions from OpenAI baselines for Reinforcement Learning. In those functions, policy nets are initialised using statements like:

`with tf.get_default_graph().as_default():`
- ...
- `return output_node`

and

`with tf.variable_scope('deepq', reuse=True):`
- ...
- `return output_node`

But the problem is that the pointer to the output node of those networks gets returned while still inside those nested scopes, which means that when accessing those functions from another .py job (using functions etc..) I am still inside those scopes.

When I try to run two of those jobs sequentially in the same python thread I get a ValueError: 
`"Variable deepq/... already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope?"`

So I tried doing something like:
`tf.get_default_session().close()`   followed by:
`tf.reset_default_graph()`
after every function call (I don't need the sessions to remain active since I'm dumping everything to disk)

But this gives me errors because I'm still inside a nested graph scope and so I can't reset the default graph.. 

My current solution is to run those functions in separate subprocesses in Python (and let the garbage collector do all the work), but this doensn't feel like a satisfactory solution.. 

Any ideas on how to would deal with this? Ideally I'd need something like **`tf.clear_all_graphs_and_sessions()`**

**Comment by tensorflowbutler** [comment] 2018-01-24 13:28
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-02-23 14:04
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-10 13:14
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-03-25 12:36
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-09 12:38
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:07
Nagging Assignee @fchollet: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by HasegawaKyosiro** [comment] 2018-05-25 08:13
@fchollet Perhaps, everyone is in trouble with this bug. Do not forget.

**Comment by ashokpant** [comment] 2018-06-03 10:57
I am getting the same issue with multiple models prediction, either in sequential or in parallel execution. The memory doesn't seem to free the memory after use.

**Comment by tensorflowbutler** [comment] 2018-06-18 18:45
Nagging Assignee @fchollet: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-03 12:47
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by carusyte** [comment] 2018-07-23 08:06
I recently resolved my model's "memory leak" issue, it turns out to be a counter-paradigm of how to construct and run the model(i.e various TensorOps)...
I mistakenly added [cosine_decay_restarts](https://www.tensorflow.org/api_docs/python/tf/train/cosine_decay_restarts) ops in every iteration of the training, something like:
```
while ... :
    ....
    dlr = tf.train.cosine_decay_restarts(
            learning_rate=LEARNING_RATE,
            global_step=cur_step,
            first_decay_steps=LR_DECAY_STEPS,
            t_mul=1.0,
            m_mul=1.0,
            alpha=LEARNING_RATE_ALPHA
        )
    lr = sess.run([dlr], feed_dict={cur_step: bno-DECAYED_LR_START})[0]
    ...
    #train the model using the decayed learning rate
```
And the training python process would get killed by the OOM killer at some point.
My instincts told me I shouldn't re-construct the `train.cosine_decay_restarts` in every loop, so after this simple remedy, the "memory leak" issue was gone...
```
dlr = tf.train.cosine_decay_restarts(
    learning_rate=LEARNING_RATE,
    global_step=cur_step,
    first_decay_steps=LR_DECAY_STEPS,
    t_mul=1.0,
    m_mul=1.0,
    alpha=LEARNING_RATE_ALPHA
)
...
while ... :
    ...
    lr = sess.run([dlr], feed_dict={cur_step: bno-DECAYED_LR_START})[0]
    ...
    #train the model using the decayed learning rate
```
So maybe everybody could make a coarse check of whether you are re-constructing the model in every loop...

**Comment by tensorflowbutler** [comment] 2018-08-07 18:59
Nagging Assignee @fchollet: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Dagalaki** [comment] 2018-08-09 14:01
Hello, 

I am also having a problem with memory leak on running label image logic in a loop
I use Tensorflow r1.0.1 and opencv 2.4.9
I am not sure yet if memory leak is opencv related or tensorflow related.
In some posts, seems that capture.read() can lead to memory leak(opencv related),  in other posts could be because of operators initialization inside loop(tensorflow related)
Below part of my code, I would appreciate if smo can check the code inside the loop in case there is smth obvious I should change to avoid memory leak, thank you in advance
`with tf.Session('',graph=graph, config=tf.ConfigProto(inter_op_parallelism_threads=1,intra_op_parallelism_threads=1)) as sess:

ret, frame = cap.read()

file_name = '...png'

if frame is not None: 

      cv2.imwrite(file_name,frame)

     input_name = "file_reader"

     output_name = "normalized"

     file_reader = tf.read_file(file_name, input_name)

     if file_name.endswith(".png"):

      image_reader = tf.image.decode_png(file_reader, channels = 3, name='png_reader')

     float_caster = tf.cast(image_reader, tf.float32)

     dims_expander = tf.expand_dims(float_caster, 0)


     resized = tf.image.resize_bilinear(dims_expander, [input_height, input_width])

     normalized = tf.divide(tf.subtract(resized, [input_mean]), [input_std])

     t = sess.run(normalized)

     results = sess.run(output_operation.outputs[0],
                      {input_operation.outputs[0]: t})

     results = np.squeeze(results)

     top_k = results.argsort()[-1:][::-1]

     labels = load_labels(label_file)

...
`
I am going to upgrade also opencv now in my system. Do you think I should upgrade also Tensorflow version. To be honest, I would keep same version of tensorflow in order to use .pb graph already generated because I am not sure if my .pb will be compatible with newer versions. 

Any suggestions to overcome memory leak problem and find what really causes this will be very helpful.

Thank you,

**Comment by tensorflowbutler** [comment] 2018-08-24 21:39
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:34
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:41
Nagging Assignee @fchollet: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:42
Nagging Assignee @fchollet: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-23 12:45
Nagging Assignee @fchollet: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jmhjimenez** [comment] 2018-10-31 04:40
I have the same issue. Just by running the same code again, the memory doesn't seem to get freed by clear_session. Below is my code. Please help!

`import keras
from keras.applications.vgg16 import VGG16

vgg16_model = VGG16()

model = Sequential()
for layer in vgg16_model.layers[:-1]:
    model.add(layer)
model.summary()

for layer in model.layers:
    layer.trainable = False

model.add(Dense(2,activation='softmax'))
model.summary()

K.clear_session()
K.reset_uids()`

**Comment by jmhjimenez** [comment] 2018-10-31 04:41
I have the same issue. Just by running the same code again, the memory doesn't seem to get freed by clear_session. Below is my code. Please help!

`import keras
from keras.applications.vgg16 import VGG16

vgg16_model = VGG16()

model = Sequential()
for layer in vgg16_model.layers[:-1]:
    model.add(layer)
model.summary()

for layer in model.layers:
    layer.trainable = False

model.add(Dense(2,activation='softmax'))
model.summary()

K.clear_session()
K.reset_uids()`

**Comment by tensorflowbutler** [comment] 2018-11-14 18:56
Nagging Assignee @fchollet: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-29 19:02
Nagging Assignee @fchollet: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wangyexiang** [comment] 2019-03-02 10:33
> Problem is, I'm trying to run two model at the same time in a website. Hence, calling K.clear_session in the code clears operations that are used elsewhere. So this creates a bug. I really need to be able to specify the operations that I want to clear. Could you be a little more precise on how I could do that ?

I have a very similar issue，and how to resolve your issue？thx.

**Comment by wangyexiang** [comment] 2019-03-02 10:33
I have a very similar issue，and how to resolve your issue？thx.@Caselles

**Comment by zdaiot** [comment] 2019-03-10 16:00
I just solve this problem by doing this:
FIrst, you should  `import tensorflow.contrib.keras.api.keras.backend as K` in the file,
Then, at the end of each iteration, use
```
        self.sess.close()
        K.clear_session()
```

**Comment by wangyexiang** [comment] 2019-05-06 00:35
> 
> 
> Problem is, I'm trying to run two model at the same time in a website. Hence, calling `K.clear_session` in the code clears operations that are used elsewhere. So this creates a bug. I really need to be able to specify the operations that I want to clear. Could you be a little more precise on how I could do that ?

Dear sir. How did you resovle your issue? I have the same issue.  Thx.  @Caselles

**Comment by Caselles** [comment] 2019-05-06 03:02
You might find some useful info here: https://stackoverflow.com/questions/44327803/memory-leak-with-tensorflow

**Comment by wangyexiang** [comment] 2019-05-07 00:31
Dear sir. Thank you for your reply. As you can see, calling K.clear_session in the code clears all graphs, however, I just want to clear one of them. Thx. @Caselles

**Comment by connors2015** [comment] 2019-07-27 04:45
Leaving this here so I remember to come back Monday and write out a work-around for the memory leak inside a loop issue using Keras.

**Comment by jvishnuvardhan** [comment] 2019-08-28 22:06
@Caselles Is this still an issue? I tried you code with `tf-nightly` and could not reproduce the issue. I have used `K.get_session()` and `K.clear_session()`. The memory usage is almost constant. 

```
for i in range(1000):
  memory()
  K.get_session()
  build_model()
  K.clear_session()
  memory()
  K.get_session()
  build_model()
  K.clear_session()
```
Output is 

```
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7448959350585938
memory use: 0.7444076538085938
memory use: 0.7444076538085938
memory use: 0.7444076538085938
memory use: 0.7444076538085938
memory use: 0.7444076538085938
memory use: 0.7444076538085938
memory use: 0.7444076538085938
```
Please let me know what you think? Here is the [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/1445ddf65ab642ffb7e502e6260f5482/tf_10408_keras_runtime.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-09-06 04:38
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-09-06 04:38 UTC
Labels: type:bug
