### ISSUE TITLE
TPU support is incomplete

### ISSUE THREAD

**Issue by martinwicke** [tensorflow/tensorflow#24412] opened 2018-12-18 03:57 UTC
TensorFlow version (use command below): **2.0 preview**

TPU support is work in progress, and the 2.0 preview does not yet contain a DistributionStrategy for TPU.

This is a tracking issue which will be updated when progress is made on this issue.

**Comment by huan** [comment] 2019-04-15 06:38
Hello @martinwicke, Thanks for set up this issue for the main tracking issue for TPU support with TF 2.0.

Do we have any plan of ETA now?

**Comment by martinwicke** [comment] 2019-04-15 17:06
@jhseu Any timeline you can share?

**Comment by jhseu** [comment] 2019-04-15 17:49
It works right now at master, but we don't have a matching Cloud TPU release. We'll release an official Cloud TPU version alongside TF 2.0 final.

**Comment by huan** [comment] 2019-04-15 21:21
@jhseu Thanks for letting me know that the master had already worked!

Do we have any code example to show how it works in TF 2.0 with TPU?

A demo with serval lines of core API calls will be enough, thanks!

**Comment by jhseu** [comment] 2019-04-15 21:51
@huan Yeah, there's an example here:
https://www.tensorflow.org/guide/distribute_strategy

You would use TPUStrategy instead of MirroredStrategy.

**Comment by TTaEE** [comment] 2019-04-17 03:10
Is it work on TPU Colab ? I got this error "InvalidArgumentError: /job:tpu_worker/replica:0/task:1/device:CPU:0 unknown device."

**Comment by bduclaux** [comment] 2019-04-21 07:37
@jhseu @TTaEE Same problem here. 

It seems that there is an issue with the job_name parameter in TPUClusterResolver. 
Either 'worker' or 'tpu_worker' don't work when using the TPUStrategy scope() method, in combination with a call to tf.config.experimental_connect_to_host.

I have submitted a bug report at #27992 , but it would be super helful to get a working notebook using TF 2.0 and TPUStrategy on Colab.

**Comment by bduclaux** [comment] 2019-04-21 09:45
The following code generates an exception on Colab with Tensorflow version 2.0.0-dev20190421 when instatiating a basic Keras model with the scope of a TPUStrategy.

ValueError: variable object with name 'cd2c89b7-88b7-44c8-ad83-06c2a9158347' already created. Use get_variable() if reuse is desired.



```
!pip install --upgrade tensorflow==2.0.0-alpha0
!pip install --upgrade tf-nightly-2.0-preview

import tensorflow as tf
import os
import sys

print("Tensorflow version " + tf.__version__)

TPU_WORKER = 'grpc://' + os.environ['COLAB_TPU_ADDR']
tf.config.experimental_connect_to_host(TPU_WORKER)
resolver = tf.distribute.cluster_resolver.TPUClusterResolver() 
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)
devices=tf.config.experimental_list_devices()
print(*devices,sep="\n")

with strategy.scope():
  model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
  model.compile(loss='mse', optimizer='sgd')

```

**Comment by AntGul** [comment] 2019-05-13 20:47
It would be good to have one working example with TF2.0.
1. This is a great article, but unfortunately, the code - [does not work with TF2.0 ](https://medium.com/tensorflow/tf-keras-on-tpus-on-colab-674367932aa0)
[see](https://colab.research.google.com/drive/1kQLwk1Y1IIBVMp3SWyNA-KZzHI4REHWV#scrollTo=G-piuNdoWJGS)
tpu_model = tf.contrib.tpu.keras_to_tpu_model(
    model,
    strategy=tf.contrib.tpu.TPUDistributionStrategy(
        tf.contrib.cluster_resolver.TPUClusterResolver(TPU_ADDRESS)))

Keras support is now deprecated in support of TPU Strategy. Please follow the distribution strategy guide on tensorflow.org to migrate to the 2.0 supported version.
---------------------------------------------------------------------------

2. On the other hand the example here [on distribution strategy ](https://www.tensorflow.org/guide/distribute_strategy)
does not seem to work [either](https://colab.research.google.com/drive/1NPCfh6ztGNJHTEMyHjlk1n_QaukA5Ptr#scrollTo=S954A0R22Ct2)
as already mentioned above

**Comment by lukemelas** [comment] 2019-06-08 00:59
Given that TF 2.0 beta is now out, is there an update with regard to this issue (about either the implementation or the timeline)?

**Comment by huan** [comment] 2019-06-08 01:12
@lukemelas +1

A roadmap or ETA would be very helpful for the cloud TPU fans!

**Comment by chiayewken** [comment] 2019-06-08 04:18
With reference to #29550, TPUStrategy in Tensorflow 2.0 Beta has not been working for me.

**Comment by huan** [comment] 2019-08-28 18:58
Is there any progress for the TPU usability for TF 2.0 RC?

Would love to hear from the TF team about the TPU support plan because I still can not find any news after did a hard search on the internet.

**Comment by jhseu** [comment] 2019-08-28 23:27
Yeah, the gist is that we intend to announce support for TPUStrategy alongside TensorFlow 2.1. TensorFlow 2.0 will work under limited use-cases but has many improvements (bug fixes, performance improvements) that we're including in TensorFlow 2.1, so we don't consider it ready yet.

We have some examples of usage here:
Custom training loop: https://github.com/tensorflow/tpu/blob/master/models/experimental/resnet50_keras/resnet50_ctl_tf2.py
Keras compile/fit:
https://github.com/tensorflow/tpu/blob/master/models/experimental/resnet50_keras/resnet50_tf2.py

**Comment by huan** [comment] 2019-08-29 05:50
@jhseu Thank you very much for the update information and the examples, it is great to know that we will officially announce support for TPUStrategy with TF 2.1!

I had just explored the examples you provided, it's great, and it will be greater if we could have a Colab to demonstrate those codes in notebook online because the Colab will be easy to get started.

Do we have any Colab Notebook to demo the TF 2.0 with TPU right now?

**Comment by giannisdaras** [comment] 2019-09-18 14:40
Hey everyone, I can confirm that I was able to train a custom keras model on TPUs, using `tf-nightly-gpu-preview-2.0. and the `tf.distribute.experimental.TPUStrategy`.
I faced a lot of issues in the process:
1) I had to wrap my model with the `Sequential` API, otherwise I was getting an error stating that `functional model was expected, but got subclass Model instead`. 
2) The slicing operation does not seem to work on TPUs. My output layer needs to return the first token out of a sequence of tokens, so I was basically doing something like that: `return x[:, 0, :]`. However, this returns the strange error: `FetchOutputs node strided_slice/stack:0: not found`. Moving this operation to the loss function resolved the issue, but I can't understand why is that the case.
3) I needed to build the model before compiling it, however that was not the case when training on GPUs.

I am wondering whether the aforementioned barriers are because of me not understanding fully the documentation of training on TPUs with Tensorflow 2, or because of actual bugs that would be resolved when TF 2.1 will become available. At any case, kudos for your excellent work with TF2 and I truly hope that TPUs training will be supported fully soon.

**Comment by EoinKenny** [comment] 2019-10-03 13:07
Is there any super simple example of using a TPU in Google colab? It seems so hard to get going in comparison to a GPU, I've been using a tonne of code online trying to get a pipeline that works, with no luck.

**Comment by jhorowitz** [comment] 2019-10-03 15:04
@EoinKenny This is not specifically for 2.0 but it's a TPU in colab tutorial.  https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/custom_training.ipynb

**Comment by qo4on** [comment] 2019-11-08 07:53
Almost a year has passed. Is there any update about running `TF 2.x` on `TPU`?

**Comment by weiweitoo** [comment] 2019-11-08 11:04
Same question. Was thinking to run TF2.0 on Colab TPU.

**Comment by martinwicke** [comment] 2019-11-08 13:30
We're targeting this for 2.1.

**Comment by qo4on** [comment] 2019-11-08 18:54
> We're targeting this for 2.1.

Are you going to update your tutorials `https://cloud.google.com/tpu/docs/colabs` with `2.1` release?

**Comment by exelents** [comment] 2020-01-07 12:31
Hello. I would like to run my model on TPU. As I see here, TPUs from Colab doesn't work with TF2. Can I use for this TPUs from Google Cloud services?

**Comment by fhaase2** [comment] 2020-01-09 10:27
Any update after releasing v2.1.0?

**Comment by fhaase2** [comment] 2020-01-09 10:32
According to the release notes of v2.1.0:

> Experimental support for Keras .compile, .fit, .evaluate, and .predict is available for Cloud TPUs, Cloud TPU, for all types of Keras models (sequential, functional and subclassing models).

So i guess this issue is kind of solved?

**Comment by dcavaller** [comment] 2020-01-18 19:06
Wath is work with tensorfloat in Jupiter Lab?

**Comment by dcavaller** [comment] 2020-01-18 19:07
I´m work in conda

**Comment by dcavaller** [comment] 2020-01-20 12:04
Thanks and regards for alll

**Comment by rxsang** [comment] 2020-01-21 08:43
Yes, TPUs work with TF2.1 now. The guide can be found here https://www.tensorflow.org/guide/tpu

**Closed** 2020-01-21 08:44 UTC
Labels: TF 2.1, comp:tpus, type:others
