### ISSUE TITLE
Executor failed to create kernel. Not found: No registered 'DataFormatDimMap' OpKernel for GPU devices compatible with node ReverseV2_1-1-DimMapNHWCToNCHW-LayoutOptimizer = DataFormatDimMap[T=DT_INT32, _kernel="host", dst_format="NCHW", src_format="NHWC", _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat)

### ISSUE THREAD

**Issue by tychota** [tensorflow/tensorflow#22285] opened 2018-09-14 19:45 UTC
Note: I'm noob to tensorflow. I can provide more info if needed.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No. I trained https://github.com/lightvector/GoNN on my own data (`data.h5`) without code modification
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: gentoo (kernel 4.17.14-gentoo)  uptodate
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: no mobile device
- **TensorFlow installed from (source or binary)**: source (from gentoo repository)
- **TensorFlow version (use command below)**: 'unknown' 1.10.0
- **Python version**: 3.6.5
- **Bazel version (if compiling from source)**: 0.16.0
- **GCC/Compiler version (if compiling from source)**: 7.3.0-r3 p1.4
- **CUDA/cuDNN version**: cuda 9.2.88 / cudnn 7.1.4
- **GPU model and memory**: GeForce GTX 1070 Ti 7.93GiB
- **Exact command to reproduce**: `./train.py -traindir models -fast-factor 50 -gamesh5 data.h5`

**Extra:** 
- ebuild from tensorflow I used: https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/tensorflow/tensorflow-1.10.0.ebuild
- use flag : 
`sci-libs/tensorflow cuda -jemalloc -system-libs -mpi PYTHON_TARGETS: -* python3_6`

### Describe the problem

When I run tensorflow on GPU, it crashed.

When I run on CPU, it works:

```
CUDA_VISIBLE_DEVICES="" ./train.py  -traindir models -fast-factor 50 -gamesh5 data.h5
```

### Source code / logs

Code:

https://github.com/lightvector/GoNN/tree/2d74b1300fef6700e75af7f2344d852798b713fb

Logs:

```
 ~/c/GoNN: ./train.py -traindir models -fast-factor 50 -gamesh5 data.h5                                                                                                                                      1058ms  ven. 14 sept. 2018 20:43:51 CEST
Building model
WARNING:tensorflow:From /home/tychota/code/GoNN/model.py:912: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

Adjusting gradient for rconv1/w1:0 by Tensor("PadV2:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv1/w2:0 by Tensor("PadV2_1:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv2/w1a:0 by Tensor("PadV2_2:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv2/w1b:0 by Tensor("PadV2_3:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv2/w2:0 by Tensor("PadV2_4:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv3/w1a:0 by Tensor("PadV2_5:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv3/w1b:0 by Tensor("PadV2_6:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv3/w2:0 by Tensor("PadV2_7:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv4/w1a:0 by Tensor("PadV2_8:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv4/w1b:0 by Tensor("PadV2_9:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv4/w2:0 by Tensor("PadV2_10:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv5/w1a:0 by Tensor("PadV2_11:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv5/w1b:0 by Tensor("PadV2_12:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv5/w2:0 by Tensor("PadV2_13:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv7/w1a:0 by Tensor("PadV2_14:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv7/w1b:0 by Tensor("PadV2_15:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv7/w2:0 by Tensor("PadV2_16:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv8/w1a:0 by Tensor("PadV2_17:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv8/w1b:0 by Tensor("PadV2_18:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv8/w2:0 by Tensor("PadV2_19:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv9/w1a:0 by Tensor("PadV2_20:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv9/w1b:0 by Tensor("PadV2_21:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv9/w2:0 by Tensor("PadV2_22:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv10/w1a:0 by Tensor("PadV2_23:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv10/w1b:0 by Tensor("PadV2_24:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv10/w2:0 by Tensor("PadV2_25:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv11/w1a:0 by Tensor("PadV2_26:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv11/w1b:0 by Tensor("PadV2_27:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv11/w2:0 by Tensor("PadV2_28:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv13/w1a:0 by Tensor("PadV2_29:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv13/w1b:0 by Tensor("PadV2_30:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv13/w2:0 by Tensor("PadV2_31:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv14/w1a:0 by Tensor("PadV2_32:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv14/w1b:0 by Tensor("PadV2_33:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for rconv14/w2:0 by Tensor("PadV2_34:0", shape=(3, 3, 1, 1), dtype=float32)
Adjusting gradient for p1/norm/beta:0 by 0.25
Adjusting gradient for p2/w:0 by 0.25
Model variable conv1/wcenter:0, 4256 parameters
Model variable conv1/w:0, 106400 parameters
Model variable rconv1/norm1/beta:0, 224 parameters
Model variable rconv1/w1:0, 451584 parameters
Model variable rconv1/norm2/beta:0, 224 parameters
Model variable rconv1/w2:0, 451584 parameters
Model variable rconv2/norm1/beta:0, 224 parameters
Model variable rconv2/w1a:0, 322560 parameters
Model variable rconv2/w1b:0, 129024 parameters
Model variable rconv2/norm2/beta:0, 224 parameters
Model variable rconv2/w2:0, 451584 parameters
Model variable rconv3/norm1/beta:0, 224 parameters
Model variable rconv3/w1a:0, 322560 parameters
Model variable rconv3/w1b:0, 129024 parameters
Model variable rconv3/norm2/beta:0, 224 parameters
Model variable rconv3/w2:0, 451584 parameters
Model variable rconv4/norm1/beta:0, 224 parameters
Model variable rconv4/w1a:0, 322560 parameters
Model variable rconv4/w1b:0, 129024 parameters
Model variable rconv4/norm2/beta:0, 224 parameters
Model variable rconv4/w2:0, 451584 parameters
Model variable rconv5/norm1/beta:0, 224 parameters
Model variable rconv5/w1a:0, 322560 parameters
Model variable rconv5/w1b:0, 129024 parameters
Model variable rconv5/norm2/beta:0, 224 parameters
Model variable rconv5/w2:0, 451584 parameters
Model variable rconv7/norm1/beta:0, 224 parameters
Model variable rconv7/w1a:0, 322560 parameters
Model variable rconv7/w1b:0, 129024 parameters
Model variable rconv7/norm1b/beta:0, 64 parameters
Model variable rconv7/w1r:0, 20480 parameters
Model variable rconv7/norm2/beta:0, 160 parameters
Model variable rconv7/w2:0, 322560 parameters
Model variable rconv8/norm1/beta:0, 224 parameters
Model variable rconv8/w1a:0, 322560 parameters
Model variable rconv8/w1b:0, 129024 parameters
Model variable rconv8/norm2/beta:0, 224 parameters
Model variable rconv8/w2:0, 451584 parameters
Model variable rconv9/norm1/beta:0, 224 parameters
Model variable rconv9/w1a:0, 322560 parameters
Model variable rconv9/w1b:0, 129024 parameters
Model variable rconv9/norm2/beta:0, 224 parameters
Model variable rconv9/w2:0, 451584 parameters
Model variable rconv10/norm1/beta:0, 224 parameters
Model variable rconv10/w1a:0, 322560 parameters
Model variable rconv10/w1b:0, 129024 parameters
Model variable rconv10/norm2/beta:0, 224 parameters
Model variable rconv10/w2:0, 451584 parameters
Model variable rconv11/norm1/beta:0, 224 parameters
Model variable rconv11/w1a:0, 322560 parameters
Model variable rconv11/w1b:0, 129024 parameters
Model variable rconv11/norm1b/beta:0, 64 parameters
Model variable rconv11/w1r:0, 20480 parameters
Model variable rconv11/norm2/beta:0, 160 parameters
Model variable rconv11/w2:0, 322560 parameters
Model variable rconv13/norm1/beta:0, 224 parameters
Model variable rconv13/w1a:0, 322560 parameters
Model variable rconv13/w1b:0, 129024 parameters
Model variable rconv13/norm2/beta:0, 224 parameters
Model variable rconv13/w2:0, 451584 parameters
Model variable rconv14/norm1/beta:0, 224 parameters
Model variable rconv14/w1a:0, 322560 parameters
Model variable rconv14/w1b:0, 129024 parameters
Model variable rconv14/norm2/beta:0, 224 parameters
Model variable rconv14/w2:0, 451584 parameters
Model variable trunk/norm/beta:0, 224 parameters
Model variable p1/intermediate_conv/w:0, 96768 parameters
Model variable g1/w:0, 64512 parameters
Model variable g1/norm/beta:0, 32 parameters
Model variable matmulg2w:0, 3072 parameters
Model variable p1/norm/beta:0, 48 parameters
Model variable p2/w:0, 48 parameters
Built model, 10901664 total parameters
Additional update op on train step: rconv1/norm1/AssignMovingAvg
Additional update op on train step: rconv1/norm1/AssignMovingAvg_1
Additional update op on train step: rconv1/norm2/AssignMovingAvg
Additional update op on train step: rconv1/norm2/AssignMovingAvg_1
Additional update op on train step: rconv2/norm1/AssignMovingAvg
Additional update op on train step: rconv2/norm1/AssignMovingAvg_1
Additional update op on train step: rconv2/norm2/AssignMovingAvg
Additional update op on train step: rconv2/norm2/AssignMovingAvg_1
Additional update op on train step: rconv3/norm1/AssignMovingAvg
Additional update op on train step: rconv3/norm1/AssignMovingAvg_1
Additional update op on train step: rconv3/norm2/AssignMovingAvg
Additional update op on train step: rconv3/norm2/AssignMovingAvg_1
Additional update op on train step: rconv4/norm1/AssignMovingAvg
Additional update op on train step: rconv4/norm1/AssignMovingAvg_1
Additional update op on train step: rconv4/norm2/AssignMovingAvg
Additional update op on train step: rconv4/norm2/AssignMovingAvg_1
Additional update op on train step: rconv5/norm1/AssignMovingAvg
Additional update op on train step: rconv5/norm1/AssignMovingAvg_1
Additional update op on train step: rconv5/norm2/AssignMovingAvg
Additional update op on train step: rconv5/norm2/AssignMovingAvg_1
Additional update op on train step: rconv7/norm1/AssignMovingAvg
Additional update op on train step: rconv7/norm1/AssignMovingAvg_1
Additional update op on train step: rconv7/norm1b/AssignMovingAvg
Additional update op on train step: rconv7/norm1b/AssignMovingAvg_1
Additional update op on train step: rconv7/norm2/AssignMovingAvg
Additional update op on train step: rconv7/norm2/AssignMovingAvg_1
Additional update op on train step: rconv8/norm1/AssignMovingAvg
Additional update op on train step: rconv8/norm1/AssignMovingAvg_1
Additional update op on train step: rconv8/norm2/AssignMovingAvg
Additional update op on train step: rconv8/norm2/AssignMovingAvg_1
Additional update op on train step: rconv9/norm1/AssignMovingAvg
Additional update op on train step: rconv9/norm1/AssignMovingAvg_1
Additional update op on train step: rconv9/norm2/AssignMovingAvg
Additional update op on train step: rconv9/norm2/AssignMovingAvg_1
Additional update op on train step: rconv10/norm1/AssignMovingAvg
Additional update op on train step: rconv10/norm1/AssignMovingAvg_1
Additional update op on train step: rconv10/norm2/AssignMovingAvg
Additional update op on train step: rconv10/norm2/AssignMovingAvg_1
Additional update op on train step: rconv11/norm1/AssignMovingAvg
Additional update op on train step: rconv11/norm1/AssignMovingAvg_1
Additional update op on train step: rconv11/norm1b/AssignMovingAvg
Additional update op on train step: rconv11/norm1b/AssignMovingAvg_1
Additional update op on train step: rconv11/norm2/AssignMovingAvg
Additional update op on train step: rconv11/norm2/AssignMovingAvg_1
Additional update op on train step: rconv13/norm1/AssignMovingAvg
Additional update op on train step: rconv13/norm1/AssignMovingAvg_1
Additional update op on train step: rconv13/norm2/AssignMovingAvg
Additional update op on train step: rconv13/norm2/AssignMovingAvg_1
Additional update op on train step: rconv14/norm1/AssignMovingAvg
Additional update op on train step: rconv14/norm1/AssignMovingAvg_1
Additional update op on train step: rconv14/norm2/AssignMovingAvg
Additional update op on train step: rconv14/norm2/AssignMovingAvg_1
Additional update op on train step: trunk/norm/AssignMovingAvg
Additional update op on train step: trunk/norm/AssignMovingAvg_1
Additional update op on train step: g1/norm/AssignMovingAvg
Additional update op on train step: g1/norm/AssignMovingAvg_1
Additional update op on train step: p1/norm/AssignMovingAvg
Additional update op on train step: p1/norm/AssignMovingAvg_1
Opening H5 file: data.h5
Adjusting H5 cache settings to: [0, 521, 134217728, 0.75]
Training
2018-09-14 20:44:04.209964: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-14 20:44:04.210288: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX 1070 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.34GiB
2018-09-14 20:44:04.210299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-14 20:44:04.581780: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-14 20:44:04.581800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2018-09-14 20:44:04.581804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2018-09-14 20:44:04.581914: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7077 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Began session
Training on 13234987 rows, validating on 688542/688542 rows
Epoch size = 20000
h5_chunk_size = 6000
Batch size = 200
L2 coeff value = 3e-05
use_ranks = False
predict_pass = False
2018-09-14 20:44:05.383592: E tensorflow/core/common_runtime/executor.cc:697] Executor failed to create kernel. Not found: No registered 'DataFormatDimMap' OpKernel for GPU devices compatible with node ReverseV2_1-1-DimMapNHWCToNCHW-LayoutOptimizer = DataFormatDimMap[T=DT_INT32, _kernel="host", dst_format="NCHW", src_format="NHWC", _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat)
	.  Registered:  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT32]

	 [[Node: ReverseV2_1-1-DimMapNHWCToNCHW-LayoutOptimizer = DataFormatDimMap[T=DT_INT32, _kernel="host", dst_format="NCHW", src_format="NHWC", _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat)]]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1278, in _do_call
    return fn(*args)
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'DataFormatDimMap' OpKernel for GPU devices compatible with node ReverseV2_1-1-DimMapNHWCToNCHW-LayoutOptimizer = DataFormatDimMap[T=DT_INT32, _kernel="host", dst_format="NCHW", src_format="NHWC", _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat)
	.  Registered:  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT32]

	 [[Node: ReverseV2_1-1-DimMapNHWCToNCHW-LayoutOptimizer = DataFormatDimMap[T=DT_INT32, _kernel="host", dst_format="NCHW", src_format="NHWC", _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 455, in <module>
    vmetrics_evaled = merge_dicts(run_validation_in_batches(vmetrics), np.sum)
  File "./train.py", line 325, in run_validation_in_batches
    result = run(fetches, rows, symmetries=[False,False,False], training=False)
  File "./train.py", line 309, in run
    model.is_training: training
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 877, in run
    run_metadata_ptr)
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1272, in _do_run
    run_metadata)
  File "/usr/lib64/python3.6/site-packages/tensorflow/python/client/session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: No registered 'DataFormatDimMap' OpKernel for GPU devices compatible with node ReverseV2_1-1-DimMapNHWCToNCHW-LayoutOptimizer = DataFormatDimMap[T=DT_INT32, _kernel="host", dst_format="NCHW", src_format="NHWC", _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat)
	.  Registered:  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT32]

	 [[Node: ReverseV2_1-1-DimMapNHWCToNCHW-LayoutOptimizer = DataFormatDimMap[T=DT_INT32, _kernel="host", dst_format="NCHW", src_format="NHWC", _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat)]]

```

**Comment by reedwm** [comment] 2018-09-24 21:59
/CC @zhangyaobit, any ideas what is happening here? The error message is complaining there is no GPU kernel for int32, but then in the list of supported combinations lists GPU with int32.

**Comment by tychota** [comment] 2018-09-25 18:11
@reedwm

> /CC @zhangyaobit, any ideas what is happening here? The error message is complaining there is no GPU kernel for int32, but then in the list of supported combinations lists GPU with int32.

That was what bugged me also. When i tried to looks https://github.com/tensorflow/tensorflow issues for already existing bugs, the similar bugs were coherant (even if I have no idea what that actually means in detail).

@zhangyaobit

> @tychota Thanks for reporting the issue. Could you provide a minimal example to reproduce the error?

(note that I have given a reproductible example, clearly not minimal in the first post : have you seen it ?)

I would love to but I did not find anyway to do a link between `ReverseV2_1-1-DimMapNHWCToNCHW-LayoutOptimizer`  and any code from https://github.com/lightvector/GoNN/tree/2d74b1300fef6700e75af7f2344d852798b713fb

There is two "reverse" occurences:

https://github.com/lightvector/GoNN/blob/0afa4e84b35967380bcfc3021fb748de8b8b7091/model.py#L274

https://github.com/lightvector/GoNN/blob/0afa4e84b35967380bcfc3021fb748de8b8b7091/model.py#L289

and no "layout" or "Optimizer" except a "MomentumOptimizer":

https://github.com/lightvector/GoNN/blob/a3903ccd1693a94c4a506c3ec0ee8b94f288edb3/train.py#L105

I'm really noob with tf (just started a few weeks ago); butI can try to build a minimal reproduction if you give me some pointer / pseudo code to help me going in the right direction.

**Comment by tensorflowbutler** [comment] 2018-10-10 12:41
Nagging Assignee @zhangyaobit: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2018-10-16 04:02
@tychota Did you get a chance to work on this?

> tychota@, To produce a smaller example, I think you can start with a trivial tensorflow program, next maybe try run the inference part only (forward pass) for the model to see if it hits the error; if so try reduce the model as much as possible and only keep the part that leads to the error.

**Comment by tychota** [comment] 2018-10-22 08:53
Not yet.

Trivial tensorflow works and I did not find the problematic line.
I will try next week end.

**Comment by lightvector** [comment] 2018-11-04 21:41
Any updates on this? In particular, does the test case I posted reproduce for anyone else?

**Comment by tensorflowbutler** [comment] 2018-11-20 07:49
Nagging Assignee @ymodak: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2018-12-03 18:52
Closing this issue due to lack of repro example. Feel free to reopen this issue when new information is available. @lightvector please open a new issue by providing all the information asked by the template. This will help us to reduce the troubleshooting time. Thanks!

**Closed by ymodak** 2018-12-03 18:52 UTC

**Comment by TharunAts** [comment] 2019-07-18 11:15
Did u get the solution? If so please discuss here.
