### ISSUE TITLE
KeyError u'ImageProjectiveTransform' when loading Tensorflow model

### ISSUE THREAD

**Issue by sadimanna** [tensorflow/tensorflow#22197] opened 2018-09-10 17:36 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: using pip
- **TensorFlow version (use command below)**:1.10.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**: 
- **GPU model and memory**: Tesla K80 on Google Colab
- **Exact command to reproduce**: 

### Describe the problem

I trained a ConvNet on MNIST, and saved the model using simple_save.

When loading the saved model, using 
`tf.saved_model.loader.load(sess,[tag_constants.SERVING],'/save_folder')`

I get this error `KeyError: u'ImageProjectiveTransform'`

Code for saving my ConvNet model

```
graph = tf.get_default_graph()

from tensorflow.python.saved_model import tag_constants
with graph.as_default():
  input_dict = {"x":x,"y":y,"keep_prob":keep_prob,"aug_img":aug_img}
  output_dict = {"logits":fc3}
  tf.saved_model.simple_save(sess,'/saved_model/',input_dict,output_dict)
```

I used tf.contrib.image.rotate as a augmentation technique, but didn't add that to any of the dicts while saving the model.

### Source code / logs

This is the code for the model and the training part
```
x = tf.placeholder(tf.float32,shape=[None,28,28])
y = tf.placeholder(tf.int64,shape=[None])
keep_prob = tf.placeholder(tf.float32,shape=())
lr = tf.placeholder(tf.float32,shape=())

aug_img = tf.placeholder(tf.float32,shape=[28,28])

img_rotate = tf.contrib.image.rotate(aug_img,-0.5+np.random.random(),interpolation='BILINEAR')
img_affine = tf.contrib.image.transform(aug_img,[np.random.random() for i in xrange(8)])

with tf.device('/gpu:0'):
  conv1 = tf.layers.conv2d(tf.reshape(x,shape=[-1,28,28,1]),filters=64,kernel_size=3,strides=1,padding='same',activation=tf.nn.leaky_relu)
  conv2 = tf.layers.conv2d(conv1,filters=64,kernel_size=3,strides=2,padding='same',activation=tf.nn.leaky_relu) #NX14X14
  conv3 = tf.layers.conv2d(conv2,filters=128,kernel_size=3,strides=1,padding='same',activation=tf.nn.leaky_relu)
  conv4 = tf.layers.conv2d(conv3,filters=64,kernel_size=1,strides=1,padding='same',activation=tf.nn.leaky_relu)
  conv5 = tf.layers.conv2d(conv4,filters=128,kernel_size=3,strides=2,padding='same',activation=tf.nn.leaky_relu) #NX7X7
  conv6 = tf.layers.conv2d(conv5,filters=64,kernel_size=1,strides=1,padding='same',activation=tf.nn.leaky_relu)
  conv7 = tf.layers.conv2d(conv6,filters=128,kernel_size=3,strides=2,padding='same',activation=tf.nn.leaky_relu) #NX3X3
  conv8 = tf.layers.conv2d(conv7,filters=128,kernel_size=3,strides=1,padding='same',activation=tf.nn.leaky_relu) #NX1X1
  flat = tf.contrib.layers.flatten(conv7)
  fc1 = tf.layers.dense(flat,units=256,activation=tf.nn.leaky_relu)
  do1 = tf.nn.dropout(fc1,keep_prob)
  fc2 = tf.layers.dense(do1,units=256,activation=tf.nn.leaky_relu)
  do2 = tf.nn.dropout(fc2,keep_prob)
  fc3 = tf.layers.dense(do2,units=10)
  
  cost = loss(fc3,y)
  opt = tf.train.AdamOptimizer(learning_rate=0.0001)
  opt_op = opt.minimize(cost)
  
  top1_acc = accuracy(fc3,y)

epochs = 25
ne=0
batchsize = 50
numiter = 400
while(ne<epochs):
    print 'Epoch:: ',ne+1,'-->'
    stime = time.time()
    if ne != 0:
       np.random.shuffle(index)
       images = images[index]
       labels = labels[index]
    for niter in xrange(numiter):
      offset = niter*batch_size
      x_iter, y_iter = np.array(images[offset:offset+batch_size,:,:]), np.array(labels[offset:offset+batch_size])
      for n in xrange(batch_size):
        augs = np.random.choice([True,False])
        if augs==True:
          x_iter[n] = sess.run(img_rotate,feed_dict={aug_img:x_iter[n]})
      feed_trdict={x:x_iter,y:y_iter,keep_prob:0.6}
      sess.run(opt_op,feed_dict=feed_trdict)
    ne+=1

```

**Comment by harshini-gadige** [comment] 2018-09-20 19:18
@asimshankar  Any update on this?

**Comment by tensorflowbutler** [comment] 2018-10-05 19:10
Nagging Assignee @asimshankar: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by asimshankar** [comment] 2018-10-05 22:20
@sadimanna : Can you provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve)?

Without a full reproduction, some questions that come to mind:
- Are you loading in the same Python process you saved the model in, or a separate on?
- If the latter, can you share the fill program for loading the model?
- Could you try adding an `import tensorflow.contrib.image` before calling `saved_model.loader.load`?

What I suspect is happening here is that since you're using `tf.contrib.image`, it defines some extension operations in a shared library ([`image_ops.so`](https://github.com/tensorflow/tensorflow/blob/c19e29306ce1777456b2dbb3a14f511edf7883a8/tensorflow/contrib/image/python/ops/image_ops.py#L34)). So you need to load that library explicitly before loading the model. Importing `tensorflow.contrib.image` does that, alternatively you can explicitly load the library using `tf.load_op_library`.

Hope that helps.

**Comment by tensorflowbutler** [comment] 2018-10-21 19:04
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-10-31 18:21
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-31 18:21 UTC
Labels: stat:awaiting response

**Comment by Bakaizhamgyrchiev** [comment] 2018-11-08 09:48
what about tensorflow serving? I am using tf.contrib.image.transform and when I serve model I get next message: 


`“Failed to start server. Error: Unknown: 1 servable(s) did not become available: {{{name: slider_universal version: 1} due to error: Not found: Op type not registered ‘ImageProjectiveTransformV2’ in binary running on 254345a5d9f1. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) tf.contrib.resampler should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.}, }” `

I tried it with docker. After I built with bazel I have also got this message

**Comment by ltrottier** [comment] 2018-12-13 22:23
I'm facing a similar issue.

I found a possible solution here:
https://stackoverflow.com/questions/53284674/tensorflow-serving-with-contrib-operations

**Comment by roymiles** [comment] 2019-03-01 13:25
I too am getting the same error using Tensorflow version 1.12.0  In fact, I can't export and read in the same meta file at all..

**Comment by svengateswaran** [comment] 2019-04-18 07:36
I also had a similar issue where I trained a model and saved it using Model Saver module of TF.
But when I tried to load the module, I got the following error.

`KeyError: u'StatelessRandomUniform' `

I was using a particular Module (`tf.contrib.stateless.stateless_random_uniform`) when training the model.
 
So after importing tensorflow in my inference script where I loaded the trained model, I also imported the module like below

`from tensorflow.contrib import stateless`

It Worked!

Similarly, for this problem, you could try the following import as stated below.

`from tensorflow.contrib import image`
