### ISSUE TITLE
Model converts to TFlite but invocation fails

### ISSUE THREAD

**Issue by raduslmn** [tensorflow/tensorflow#48482] opened 2021-04-12 12:06 UTC
**System information**
- OS Platform: Windows, Linux:
- TensorFlow 2.4.1:

**Standalone code to reproduce the issue** 
https://colab.research.google.com/drive/1f22ow0a4p1WQLdlm7AIZ0V3DHbxI8EjG

**or if you like. here is the same code as in Google Colab to reproduce the problem** 
```
from tensorflow.keras.layers import concatenate, Input, LSTM, Bidirectional, Embedding, Dense, TimeDistributed,SpatialDropout1D
from tensorflow.keras.models import Model
import tensorflow as tf
print(tf.__version__)

# Create Tensorflow model 
word_in = Input(shape=(300,), name="input_wor")
emb_wor = Embedding(input_dim=1834, output_dim=16, input_length=300, mask_zero=True, name="emb_wor")(word_in)
char_in = Input(shape=(300, 20 ,), name="input_char")
emb_char = TimeDistributed(Embedding(input_dim=132, output_dim=32, input_length=20, mask_zero=True, name="emb_char"))(char_in)
char_enc = TimeDistributed(LSTM(units=32, return_sequences=False, recurrent_dropout=0.15, name="char_enc"))(emb_char)
input_pos = Input(shape=(300, 4, ), name="input_pos")
input_par = Input(shape=(300, 3, ), name="input_par")

x = concatenate([emb_wor, char_enc, input_pos, input_par])
x = SpatialDropout1D(0.1)(x)
main_lstm = Bidirectional(LSTM(units=64, return_sequences=True, dropout=0., recurrent_dropout=0.1, name="main_lstm"))(x)
inputs=[word_in,char_in, input_pos, input_par]
outputs = TimeDistributed(Dense(4, activation="softmax", name="out"))(main_lstm)
model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")
print(model.summary())


# Convert Model to Tensorflow Lite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
converter.experimental_new_converter = True
tflite_model = converter.convert()
with open("model.tflite", 'wb') as f:
  f.write(tflite_model)


# # Install tflite_runtime
# !pip3 install --extra-index-url https://google-coral.github.io/py-repo/ tflite_runtime

use_tflite_runtime = False # If True then you need to first restart runtime before running this code
import numpy as np

if(use_tflite_runtime):
  import tflite_runtime.interpreter as tflite
  interpreter =  tflite.Interpreter(model_path="model.tflite")
else:
  import tensorflow as tf
  interpreter = tf.lite.Interpreter(model_path="model.tflite")

interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print("input_details", input_details)
print("output_details", output_details)

# Set random values
for i in range(len(input_details)):
    x = np.random.random(input_details[i]["shape"])
    interpreter.set_tensor(i, x.astype(input_details[i]["dtype"]))
    print(i, input_details[i]["name"], input_details[i]["shape"], input_details[i]["dtype"], "/", x.shape)

# Invoke
interpreter.invoke()
```

**Provide the text output from tflite_convert**

```
2021-04-12 13:24:02.507539: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
2021-04-12 13:24:07.691525: I tensorflow/core/grappler/devices.cc:69] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2021-04-12 13:24:07.691860: I tensorflow/core/grappler/clusters/single_machine.cc:357] Starting new session
2021-04-12 13:24:07.730306: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:1144] Optimization results for grappler item: graph_to_optimize
  function_optimizer: Graph size after: 447 nodes (0), 564 edges (0), time = 6.973ms.
  function_optimizer: Graph size after: 447 nodes (0), 564 edges (0), time = 6.713ms.
Optimization results for grappler item: model_bidirectional_forward_main_lstm_while_body_19625
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.
Optimization results for grappler item: model_bidirectional_backward_main_lstm_while_cond_19891
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.
Optimization results for grappler item: model_time_distributed_1_char_enc_while_body_19340
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.
Optimization results for grappler item: model_bidirectional_forward_main_lstm_while_cond_19624
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.
Optimization results for grappler item: model_time_distributed_1_char_enc_while_cond_19339
  function_optimizer: function_optimizer did nothing. time = 0ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.
Optimization results for grappler item: model_bidirectional_backward_main_lstm_while_body_19892
  function_optimizer: function_optimizer did nothing. time = 0.001ms.
  function_optimizer: function_optimizer did nothing. time = 0ms.

2021-04-12 13:24:08.058077: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:345] Ignored output_format.
2021-04-12 13:24:08.058217: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:348] Ignored drop_control_dependency.
2021-04-12 13:24:08.086587: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2021-04-12 13:24:08.172281: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1782] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):
Flex ops: FlexAll
Details:
	tf.All {device = "", keep_dims = false}
```

When I run the invocation using `tflite_runtime` i get this error:

```
RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 16 (FlexAll) failed to prepare.

```

When I run the invocation using tensorflow i get this following error

```
RuntimeError: external/org_tensorflow/tensorflow/lite/kernels/concatenation.cc:76 t->dims->data[d] != t0->dims->data[d] (300 != 1)Node number 37 (CONCATENATION) failed to prepare.
Node number 49 (WHILE) failed to invoke.

```

Either way, the invocation fails and it seems that is has something to do with the `concatenate`  layer. 
I would highly appreciate an answer or eventually a solution. As you can see the model does convert, but the invocation doesn't run. I tested it on both Windows and Linux,. same problem and same error.

**Comment by abattery** [comment] 2021-04-12 12:14
Could you try with the tf-nightly version? We have improved on the similar cases at the recent changes.

**Comment by abattery** [comment] 2021-04-12 12:18
FYI, tf.all op is now a part of TFLite builtin op set in the tf-nightly.

**Comment by raduslmn** [comment] 2021-04-12 12:18
> Could you try with the tf-nightly version? We have improved for the similar cases at the recent changes.

I did try and i still get the exact same error.

**Comment by abattery** [comment] 2021-04-12 12:25
If you didnt convert the model with the tf-nightly, please conduct the conversion again and re-try the model executation.

**Comment by raduslmn** [comment] 2021-04-12 12:30
> If you didnt convert the model with the tf-nightly, please conduct the conversion again and re-try the model executation.

I just did that, i tested with `tf-nightly-2.6.0.dev20210412` and the error is exactly the same.
I updated the Google Colab code where you can run and it will reproduce the exact same problem as i describe   https://colab.research.google.com/drive/1f22ow0a4p1WQLdlm7AIZ0V3DHbxI8EjG

**Comment by abattery** [comment] 2021-04-12 12:30
Via the above gist, I confirmed that the tf-nightly version also have the same issue.

**Comment by abattery** [comment] 2021-04-12 12:30
Let me take a look at the model structure.

**Comment by abattery** [comment] 2021-04-12 12:41
I confirmed that this issue is related to the pass for lowering static tensor list. Thanks for the bug report!

**Comment by abattery** [comment] 2021-04-12 12:42
@haozha111 could you take a look at this bug report?

**Comment by abattery** [comment] 2021-04-13 00:43
@raduslmn I landed the fix for this issue. Please make sure enable the select TF option as your conversion code and verify the fix with the tomorrow's tf-nightly version.

**Comment by abattery** [comment] 2021-04-13 00:44
https://github.com/tensorflow/tensorflow/commit/a5382257ac60dc0806c2fca7efaa5a133ee24ef6 is the fix.

**Comment by raduslmn** [comment] 2021-04-14 07:23
> [a538225](https://github.com/tensorflow/tensorflow/commit/a5382257ac60dc0806c2fca7efaa5a133ee24ef6) is the fix.
 
I did try today with the latest `tf-nightly` version and still the same error. I notice that you pushed  [a538225](https://github.com/tensorflow/tensorflow/commit/a5382257ac60dc0806c2fca7efaa5a133ee24ef6) which should be the fix but you also pushed another commit [8b07beb](https://github.com/tensorflow/tensorflow/commit/8b07beb41611302c4779f60031262745cacd20d9#diff-23e5220f335dd3aa115eb368edc4c5cfea78499328f7b3d8bce900ae706130a5) that reverts the fix back to the code before the fix. Was that intentional, is there a reason for that or was it a mistake? If it was a mistake, could push again the fix as now it's still the  old code prior to the fix: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/tf_tfl_passes.cc

**Comment by abattery** [comment] 2021-04-14 09:57
Sorry. The above change got rollbacked. However, we landed again with the experimental flag, `converter._experimental_lower_tensor_list_ops = True`.

If the `tflite_runtime` is based on TF 2.5 or beyonds, it will work.

**Comment by raduslmn** [comment] 2021-04-14 11:02
> Sorry. The above change got rollbacked. However, we landed again with the experimental flag, `converter._experimental_lower_tensor_list_ops = True`.

Does it mean that we first wait for the `tf-nightly` version and then try run the convertion again using `converter._experimental_lower_tensor_list_ops = True` flag. Is that correct?

**Comment by raduslmn** [comment] 2021-04-14 11:03
> Sorry. The above change got rollbacked. However, we landed again with the experimental flag, `converter._experimental_lower_tensor_list_ops = True`.
> 
> If the `tflite_runtime` is based on TF 2.5 or beyonds, it will work.

**Comment by abattery** [comment] 2021-04-14 11:04
https://github.com/tensorflow/tensorflow/commit/904b3926ed1c6c70380d5313d282d248a776baa1 is the fix.

**Comment by abattery** [comment] 2021-04-14 11:06
Please disable it for your case. ````converter._experimental_lower_tensor_list_ops = False```

**Comment by raduslmn** [comment] 2021-04-15 12:45
> [904b392](https://github.com/tensorflow/tensorflow/commit/904b3926ed1c6c70380d5313d282d248a776baa1) is the fix. I can expect that the tomorrow's tf-nightly version will have it.

The invocation works when using Tensorflow Lite from the `tf-nightly==2.6.0-dev20210414` Thank you. @abattery 

So this has solved only half of the problem, when I run the invocation using `tflite_runtime` alone I get this error:

`ValueError: Op builtin_code out of range: 140. Are you using old TFLite binary with newer model?Registration failed.`

on model import:
```
import tflite_runtime.interpreter as tflite
interpreter =  tflite.Interpreter(model_path="model.tflite")
```

You @abattery said that 
> If the `tflite_runtime` is based on TF 2.5 or beyonds, it will work.

Now, i used `tf-nightly==2.6.0-dev20210414` when creating the model, theoretically this should work, but it doesn't load the model. If you want you can see the error or replicate the problem here  using this [Google Colab](https://colab.research.google.com/drive/1f22ow0a4p1WQLdlm7AIZ0V3DHbxI8EjG#scrollTo=eTYhPLmiDK6T) code

Is there anything that could be done to make this model load and run invocation `tflite_runtime`? As of now the only version that i can find is `tflite-runtime-2.5.0` is there any other versions that i could use which are more recent?

**Comment by abattery** [comment] 2021-04-15 13:54
Since you are using tf 2.6 for conversion. The tflite-runtime should have the same TF version, 2.6 or beyonds. TF 2.6 version is too early version to have the prebuilt binaries.

For now, you need to compile your own tflite-runtime or just depend on the TF pip package.

**Comment by raduslmn** [comment] 2021-04-26 14:46
@abattery i have now tested with the built from source `tflite-runtime` on Linux and Windows.
When using Tflite from the full Tensorflow library then it works, but when using the built from source `tflite-runtime` then it still throws get error:

`RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 20 (FlexTensorListFromTensor) failed to prepare.`

You can reproduce the same error in the Google Colab which will build from source the `tflite-runtime` and then  run the entire logic:  https://colab.research.google.com/drive/1f22ow0a4p1WQLdlm7AIZ0V3DHbxI8EjG

Is there anyway this can be fixed? This is actually critical for production run.  It's fine that Tflite is now working with the full TF library but that only helps during development and model training but it's useless unless we can use the `tflite-runtime` inference during production.

**Comment by abattery** [comment] 2021-04-26 23:48
That is an intended behavior. The `tflite-runtime` package does not include the Select TF option. Please use the tensorflow package for your use case.

**Comment by raduslmn** [comment] 2021-04-27 07:47
@abattery will do, thank you fixing the lower tensor problem. When will Tensorflow 2.6 which includes this fix be officially released?  By the way, this issue can be closed as it is resolved thanks to you ;)

**Comment by abattery** [comment] 2021-04-27 08:07
I don't know when the 2.6 version will be released. FYI, the TF 2.5 version is still in the rc stage.

**Closed by abattery** 2021-04-27 08:07 UTC
Labels: TFLiteConverter, comp:lite, type:bug

**Comment by TimbusCalin** [comment] 2022-03-17 11:34
Invocation also fails in my case, 3DConvolution + 3DMaxPool, I was able eventually to convert them by specifying     `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]` prior to conversion; nevertheless invocation fails, with exit code "random integer 192391234313"

**Comment by GustavoMourao** [comment] 2022-04-12 20:08
@TimbusCalin , try this:
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter._experimental_lower_tensor_list_ops = False
```
