### ISSUE TITLE
tf.clip_by_norm documentation wrong

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#57525] opened 2022-08-30 12:18 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

TF2.8

### Custom Code

Yes

### Current Behaviour?

```shell
clip_norm should be a 0-D (scalar) Tensor > 0 written on documentation https://tensorflow.google.cn/versions/r2.4/api_docs/python/tf/clip_by_norm#args. However, when the clip_norm is a negative integral, the code works.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  arg_0 = tf.random.uniform([1, 5], dtype=tf.float32)
  results["res"] = tf.clip_by_norm(arg_0,clip_norm=-1)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
'''
{'res': <tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-0.54458696, -0.59545624, -0.31598726, -0.20027176, -0.4570559 ]],dtype=float32)>}
'''
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment] 2022-09-07 11:32
@gadagashwini  
The issue Was able to reproduce the issue on Colab using TF v2.9 and TF-nightly ,Please find the gist [here](https://colab.research.google.com/gist/tiruk007/1e93e91a0f72c59ed9f5da249d6e1cbf/57525.ipynb#scrollTo=NBkbFIy0b6J0) for reference .
Thank you!

**Comment by sachinprasadhs** [comment] 2022-09-16 21:54
This seems to be a duplicate issue of https://github.com/tensorflow/tensorflow/issues/54414, I have submitted a fix internally to allow `clip_norm` value greater than 0.
Could you please close this issue and track the progress in the linked issue. Thanks!

**Closed** 2022-09-17 08:11 UTC
Labels: type:docs-bug, stat:awaiting response, type:bug, comp:ops
