### ISSUE TITLE
Flawed memory management: allow_growth=True consumes more memory, causing out-of-memory

### ISSUE THREAD

**Issue by xuancong84** [tensorflow/tensorflow#6111] opened 2016-12-06 03:56 UTC
To prevent tensorflow (TF) from allocating the totality of graphic memory, I always use the following options when creating sessions:

```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
```

However, doing so causes some experiments to run out of memory while not doing so will not cause memory overflow. For example, when running experiments involving RNN, such as translate.py or ptb_word_lm.py in the sample code, if I specify allow_growth=True, I always encounter the following:

```
Training Epoch 0 ; learning_rate= 0.002 :                                                                                                
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 2631 get requests, put_count=2230 evicted_count=1000 eviction_rate=0.44843 and unsatisfied allocation rate=0.570506                                                                              
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 100 to 110                                     
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 2631 get requests, put_count=2546 evicted_count=1000 eviction_rate=0.392773 and unsatisfied allocation rate=0.421133                                                                             
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 256 to 281                                     
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:245] PoolAllocator: After 9384 get requests, put_count=9389 evicted_count=1000 eviction_rate=0.106508 and unsatisfied allocation rate=0.112319                                                                             
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:257] Raising pool_size_limit_ from 655 to 720                                     
E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 2.00G (2147483648 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY  
E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 1.80G (1932735232 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY  
E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 1.62G (1739461632 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY  
E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 1.46G (1565515520 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY  
E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 1.31G (1408964096 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY  
E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 1.18G (1268067840 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY  
```
However, without specifying allow_growth=True, I can run it successfully. Moreover, the OOM occurs only after going through some epoches in the training data, not right from the beginning.

In principle, for an ideal memory manager, whether OOM will occur should not depends on whether memory is pre-allocated in one go or allocated step-by-step dynamically. Thus, Tensorflow's low-level memory management code must be flawed in one way or another.

Below are my system info:
```
Operating System:
Ubuntu 14.04.5 LTS

Installed version of CUDA and cuDNN:
/usr/local/cuda-8.0
cudnn-8.0-linux-x64-v5.1.tgz

It is installed from binary pip package

A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

The output from python -c "import tensorflow; print(tensorflow.version)"
xuancong@wxc-i2r:~/projects/tf-rnnlm$ python -c "import tensorflow; print(tensorflow.version)"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
0.11.0
```

**Comment by zheng-xq** [comment] 2016-12-09 23:22
Could you post the entire log somewhere? We need to find out how much memory were requested when OOM happens? Also we would need a small model to reproduce the problem. 

allow_growth is expected to introduce some level of fragmentation. So if your model is running very close to GPU memory limit, it is possible that allow_growth can push you over the limit.

The current allocator design is a trade-off between performance and efficiency, and sure it is not perfect. That's why the option exists. It will get better as we keep improving it. If the system still has a lot of free memory, and the OOM still happens, then it is a more serious problem than if the model is already running close to the limit, where we would recommend not to use allow_growth.

**Comment by xuancong84** [comment] 2016-12-16 08:06
In principle, memory fragmentation should only affect the speed rather than the total available memory.

You can reproduce the problem by running **translate.py** or **ptb_word_lm.py** in the sample code, by setting a large enough vocabulary size for OOM to occur.

**Comment by zheng-xq** [comment] 2016-12-16 16:24
>> In principle, memory fragmentation should only affect the speed rather
than the total available memory.

I am not sure about that.

https://en.wikipedia.org/wiki/Fragmentation_(computing)

"In computer storage, fragmentation is a phenomenon in which storage space
is used inefficiently, reducing capacity or performance and often both."

**Comment by egavves** [comment] 2017-03-08 09:02
Hi,

I am testing the TF Slim package, fine-tuning the flowers dataset using the instructions in https://github.com/tensorflow/models/tree/master/slim

To allow for memory growth, I use the following code:

`    session_config.gpu_options.allow_growth = True
    session_config.gpu_options.allocator_type = 'BFC'
    session_config.gpu_options.per_process_gpu_memory_fraction = 0.4
    # gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=args.gpu_memory_fraction)
    # Run the training:
    final_loss = slim.learning.train(
        train_op,
        logdir=train_dir,
        init_fn=get_init_fn(),
        number_of_steps=2000,
        session_config=session_config)`

There are mainly two issues.

1. As the GPU memory is not big enough, I want to try to allow for GPU growth, so that the process does not crash. The code I am using is the one below, however, it doesn't make any difference at all. Is allow_growth and/or per_process_gpu_memory_fraction really supported for TF slim or not? I suppose this will be anyways an issue, given the original message on the thread. So, I guess all left to ask Is whether there any development on the issue (to begin with, is it really an issue)?

2. Is all the GPU needed for the allocation of the intermediate activation variables? Because the inception model is about 100 Mb, my total GPU memory (after killing also the X server) is 1.8 Gb, so it feels somewhat weird that the model needs in the end 18X more GPU RAM than the inception model size. When using Caffe with Alexnet (~350 Mb), there was no problem at all, no matter the batch size. I guess the way the gradients are computed is by allocating memory like: #MODEL_PARAMETERS x BATCH_SIZE, since for smaller batch sizes the code works. Given that batch gradients are cumultative over the batch samples, isn't this -although arguably faster- somehow redundant (?).

I will try to get the RAM metadata log file, if that is of any help.

**Comment by itsmeolivia** [comment] 2017-06-16 23:41
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Closed by itsmeolivia** 2017-06-16 23:41 UTC
Labels: type:bug/performance

**Comment by Netroman** [comment] 2018-10-01 15:40
Does anyone have a solution for this? 

I'm trying to run a Yolo example using tensorflow-gpu:
https://github.com/CornerStone12/yolov2-tensorflow

This works fine on my GeForce 1050Ti, as well as on the CPU, but trying to run on a Tesla V100 it allocates all the GPU memory and  seem to spawn a lot of processes just grabbing more and more memory until it is killed. 

The values of `gpu_options.allow_growth` and `gpu_options.per_process_gpu_memory_fraction` doesn't seem to make a difference.

```
PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command 
 6559 root       20   0 49.5G 2761M  606M S  0.0  8.6  0:00.00 python demo_yolo_v2.py
 6560 root       20   0 49.5G 2761M  606M S  0.0  8.6  0:00.00 python demo_yolo_v2.py
 6561 root       20   0 49.5G 2761M  606M S  0.0  8.6  0:00.00 python demo_yolo_v2.py
 6562 root       20   0 49.5G 2761M  606M S  0.0  8.6  0:00.00 python demo_yolo_v2.py
 6563 root       20   0 49.5G 2761M  606M S  0.0  8.6  0:00.00 python demo_yolo_v2.py
 6564 root       20   0 49.5G 2761M  606M S  0.0  8.6  0:00.00 python demo_yolo_v2.py
 6565 root       20   0 49.5G 2761M  606M S  0.0  8.6  0:00.00 python demo_yolo_v2.py
 6566 root       20   0 49.5G 2761M  606M S  0.0  8.6  0:00.00 python demo_yolo_v2.py
...
```
