### ISSUE TITLE
export/00000000-tmp/export-?????-of-00001 is not in all_model_checkpoint_paths. Manually adding it.

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#5073] opened 2016-10-19 19:21 UTC
Now that I am using the 11rc, I am seeing a lot of this printed out:

```
INFO in saver: /output/4885/export/00000000-tmp/export-?????-of-00001 is not in all_model_checkpoint_paths. Manually adding it.
```

I believe when I call:

```
# Done once:
saver = tf_saver.Saver(sharded=True)
model_exporter = exporter.Exporter(saver)
model_exporter.init(...)
...
# Done each epoch / step:
model_exporter.export(export_path, tf.constant(i), sess)
```
### Environment info

Operating System:
Using nvidia Docker,

```
uname -a
Linux b2dcea60c730 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
# ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root 322936 Aug 15  2015 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 383336 Aug 15  2015 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root 720192 Aug 15  2015 /usr/local/cuda/lib64/libcudart_static.a
```
1. The commit hash (`git rev-parse HEAD`)
   `8915f0f8072c406ae3fe0dff888f51b4cad02d7d`
2. The output of `bazel version`

```
# bazel version
INFO: Reading 'startup' options from /root/.bazelrc: --batch
Extracting Bazel installation...
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392
```

**Comment by asimshankar** [comment] 2016-10-19 20:01
@cancan101 : That is an informational log line, not an error. That logging line has been there for a while, so I'm surprised that you're seeing it only now. Perhaps your logs were being redirected somewhere else before and you didn't notice them?

Regardless, this shouldn't be causing any problems. Is it?

**Comment by cancan101** [comment] 2016-10-19 20:26
On older versions of TF, instead of the log I got exceptions like:
```
    model_exporter.export(export_path, tf.constant(i), sess)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/session_bundle/exporter.py", line 268, in export
    meta_graph_suffix=constants.EXPORT_SUFFIX_NAME)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1078, in save
    meta_graph_suffix=meta_graph_suffix)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 941, in _MaybeDeleteOldCheckpoints
    self._CheckpointFilename(p)):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 53, in get_matching_files
    return pywrap_tensorflow.GetMatchingFiles(compat.as_bytes(filename), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.NotFoundError: /output/gap/4887/export/00000000-tmp
```
which actually killed training.

Is there any way to suppress that log message? It fills my logs and I don't even know what / if I am doing anything wrong.

**Comment by asimshankar** [comment] 2016-10-19 22:27
@concretevitamin : Could you take a look at this?

**Comment by concretevitamin** [comment] 2016-10-22 01:01
@sukritiramesh: can you take a look?  Is it caused by the way `Exporter.export()` uses `Saver`?

**Comment by cancan101** [comment] 2016-10-22 21:32
I don't see it when just using the Saver

**Comment by sukritiramesh** [comment] 2016-10-24 15:59
@concretevitamin This might be related to exporter using a -tmp location and then performing an atomic copy to the final export location. In this case, the checkpoint file contents include the -tmp location but the actual export location is the final one. Do you think that might be the case here, re: interaction with how Saver reads the checkpoint file?

**Comment by concretevitamin** [comment] 2016-10-25 17:38
@sukritiramesh: yes, I agree w/ your hypothesis.  I think you're already working on making the paths in "checkpoint" relative?  That could mitigate the issue.

**Comment by sukritiramesh** [comment] 2016-10-26 16:47
@concretevitamin Not sure we'll be able to switch Exporter to use relative paths since that might impact existing exports. We could try to see if relative paths could be made the default in future versions though. Thoughts?

**Comment by cancan101** [comment] 2017-01-30 18:10
So I think this issue is related to the checkpoint file containing the `tmp` path before the rename occurs.

Inside the `checkpoint` folder:
```
# cat output/diam/20170130-005509/export/00000060/checkpoint
model_checkpoint_path: "/usr/src/app/output/diam/20170130-005509/export/00000060-tmp/export"
all_model_checkpoint_paths: "/usr/src/app/output/diam/20170130-005509/export/00000060-tmp/export"
```

but that folder has been renamed:
```
# ls /usr/src/app/output/diam/20170130-005509/export/00000060/
checkpoint  export.data-00000-of-00001  export.index  export.meta
```

**Comment by cancan101** [comment] 2017-04-20 01:21
Any way to suppress this INFO message? It is entirely spurious.

**Comment by kingaj12** [comment] 2017-05-14 21:39
This INFO message is not blocked even when I set:

    import os
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
    import tensorflow as tf

It seems like this is very old code?

**Comment by ecoue** [comment] 2017-06-09 08:08
`tf.logging.set_verbosity(tf.logging.WARN)`
This should have the desired effect

**Comment by tensorflowbutler** [comment] 2017-12-22 07:38
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:11
Nagging Awaiting TensorFlower: It has been 14 days with no activityand the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-24 13:21
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by itsmeolivia** [comment] 2018-02-07 23:59
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by itsmeolivia** 2018-02-07 23:59 UTC
Labels: stat:awaiting tensorflower
