### ISSUE TITLE
Need better error message for error in checkpoint loading

### ISSUE THREAD

**Issue by cinjon** [tensorflow/tensorflow#436] opened 2015-12-07 23:14 UTC
Hi, I'm loading a previously-built model using the tf.train.Saver and running into an error: `tensorflow.python.pywrap_tensorflow.StatusNotOK: Internal: Unable to get element from the feed.`.

I'm not quite sure what this is referring to as I can load other models just fine. This one also builds and runs as expected. It's only after, when retrieving it again, do I get this error. The ckpt file also points to the correct locations and is reading from the right place.

```
Traceback (most recent call last):
  File "bridge.py", line 518, in <module>
    tf.app.run()
  ...
  File "bridge.py", line 375, in train
    saver.restore(sess, checkpoint)
  File ".../site-packages/tensorflow/python/training/saver.py", line 887, in restore
    sess.run([self._restore_op_name], {self._filename_tensor_name: save_path})
  File ".../site-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File ".../site-packages/tensorflow/python/client/session.py", line 446, in _do_run
    six.reraise(e_type, e_value, e_traceback)
  File ".../site-packages/tensorflow/python/client/session.py", line 428, in _do_run
    target_list)
tensorflow.python.pywrap_tensorflow.StatusNotOK: Internal: Unable to get element from the feed.
```

Thoughts?

**Comment by girving** [comment] 2015-12-07 23:17
That's a terribly uninformative error message which should be fixed, but until then: can I see the whole `bridge.py` or at least more of the context?

**Comment by cinjon** [comment] 2015-12-08 19:55
Sorry about that! I posted more on what the bridge creates below. This version is just a linear mapping using cosine similarity. 

```
class Bridge(object):
    def __init__(self, state_size, bucket_sizes, bridge_learning_rate, 
                        bridge_learning_decay_factor, bridge_regularizer_factor):
        bridge_learning_rate = tf.get_variable(
            'bridge_learning_rate', shape=[], trainable=False,
            initializer=tf.constant_initializer(float(bridge_learning_rate)))   
        bridge_learning_decay_factor_op = self.bridge_learning_rate.assign(
            self.bridge_learning_rate * bridge_learning_decay_factor)
        bridge_global_step = tf.get_variable(
            'bridge_global_step', shape=[], trainable=False,
            initializer=tf.constant_initializer(0))

        initializer = tf.truncated_normal_initializer

        self.s1 = tf.placeholder("float", [None, state_size])
        self.s2 = tf.placeholder("float", [None, state_size])

        # W, b are the weight / bias matrices for the states.                                                                                                                                               
        # shape: [state_size x state_size], [state_size]                                                                                                                                                    
        W = tf.get_variable(
            'weights', [state_size, state_size],
            initializer=initializer())
        b = tf.get_variable(
            'bias', [state_size],
            initializer=initializer())

        self.y = tf.nn.xw_plus_b(self.s1, W, b)

        cost = self._cosine_cost(self.s2, self.y)
        reg = tf.reduce_sum(tf.square(W)) * bridge_regularizer_factor
        self.cost = tf.add(cost, reg)

        self.train_step = tf.train.AdagradOptimizer(
            bridge_learning_rate
            ).minimize(self.cost, global_step=bridge_global_step)

        tf.initialize_all_variables().run()

    @staticmethod
    def _cosine_cost(y, y_):
        def norm(v):
            return tf.sqrt(tf.reduce_sum(tf.square(v), 1, keep_dims=True))

        y = y / norm(y)
        y_ = y_ / norm(y_)
        return -tf.reduce_mean(tf.matmul(y, y_, transpose_b=True))
```

After creating the bridge, I then looked at ```tf.all_variables()``` and this was the result: 

```
[u'bridge/bridge_learning_rate:0', u'bridge/bridge_global_step:0', 
 u'bridge/weights:0', u'bridge/bias:0', 
 u'bridge/bridge/weights/Adagrad:0', u'bridge/bridge/bias/Adagrad:0']
```

**Comment by girving** [comment] 2015-12-09 05:54
It looks like you didn't include the code for the line that triggers the error, so I don't know what the problem is.  Wild, unlikely guess: Do you have Python 2 with `unicode_literals` imported from `__future__`?  I'm a bit surprised those variable names are showing up as unicode.

**Comment by cinjon** [comment] 2015-12-09 19:41
Ahh, this is my screwup. For note to others, this error happens when you try to restore using the object ```ckpt = tf.train.get_checkpoint_state(model_dir)``` and not the ckpt.model_checkpoint_path. Thanks so much for looking at this girving! My apologies for not being more careful :(

**Comment by girving** [comment] 2015-12-09 19:47
I think I've made that mistake too, so it would be good to get a more sensible error message.  I'll try to do that, though it not be this year.

**Comment by cinjon** [comment] 2015-12-09 19:49
:+1:

**Comment by girving** [comment] 2016-08-09 23:43
Apologies: looks like this one fell through the cracks.  Removing assignment for purposes of upcoming bug scrub.

**Comment by prb12** [comment] 2016-08-26 20:36
@girving This doesn't appear to be assigned to anybody on GitHub.  Any update here?

**Comment by girving** [comment] 2016-08-26 20:46
@prb12 @aselle I was expecting this to be triaged during the bug scrub, but I guess that didn't happen.  I'll close for now, but if someone wants to fix it I can reopen and mark contributions welcome.

**Comment by smorrel1** [comment] 2017-01-30 12:39
+1 on this. The error also arose if checkpoint_path=None. The error message should warn the ckpt file may not exist. 
Also it may be useful to know that a missing protobuf in the checkpoint_path directory gives  checkpoint_path=None while an error message would be more useful. HTH.

**Comment by jmchen-g** [comment] 2017-02-05 05:02
assigned to girving mostly because he has been following this bug. Feel free to re-assign. Thanks.

**Comment by girving** [comment] 2017-02-06 15:57
@jmchen-g Unassigning myself a second time.  I'll mark this contributions welcome.

**Comment by sahildua2305** [comment] 2017-08-10 21:05
@girving this seems like a low-effort and beginner-friendly task. If so, I'd like to get started with this. 🙂

**Comment by girving** [comment] 2017-08-10 21:13
@martinwicke: Handing off to you.

**Comment by martinwicke** [comment] 2017-08-10 22:26
@sahildua2305 Please go ahead! Send a PR whenever you're ready, and mention this issue in its description.

**Comment by ymodak** [comment] 2018-09-13 18:38
@sahildua2305 Just wanted to follow up. Did you get a chance to build a PR for this issue?.

**Comment by tensorflowbutler** [comment] 2018-09-28 12:42
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by ymodak** [comment] 2018-09-28 21:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-09-28 21:17 UTC
Labels: stat:awaiting response, stat:contributions welcome, type:feature
