### ISSUE TITLE
Error retrieving regularization losses after adding them to a pretrained model.

### ISSUE THREAD

**Issue by ujjwal-ai** [tensorflow/tensorflow#37511] opened 2020-03-11 15:55 UTC
It appears that adding regularization losses to a pre-trained model results in some issue which leads to an error when retrieving the losses. I am having this problem with the TensorFlow 2.2.  Its git version is `v1.12.1-26428-gcb73044`.

The reproducible code is shown below:

```
import tensorflow as tf

class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self._model = tf.keras.applications.ResNet101(include_top=False, weights='imagenet')

    def build(self, input_shape=None):
        for layer in self._model.layers:
            if type(layer) == tf.keras.layers.Conv2D:
                layer.add_loss( lambda : tf.keras.regularizers.l2(1e-5)(layer.kernel))

    def call(self, x):
        return self._net(x)


if __name__ == "__main__":
    m = Model()
    x = tf.random.uniform(shape=(1,3,512,512))
   m.build()
   print(m.losses)
```
   

The error message is -

 `AttributeError: 'Activation' object has no attribute 'kernel'`

**Comment by gadagashwini** [comment] 2020-03-12 06:46
I was able to reproduce the issue with Tf-nightly.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/74bc7c8242362aefd7db0798b57ea2ef/untitled440.ipynb). Thanks!

**Comment by ashutosh1919** [comment] 2020-03-15 06:31
@ujjwal-ai , Please find below code. It resolves the error.
```python
import tensorflow as tf

class Model(tf.keras.Model):
    def __init__(self):
        super(Model, self).__init__()
        self._model = tf.keras.applications.ResNet101(include_top=False, weights='imagenet')

    def build(self, input_shape=None):
        for layer in self._model.layers:
            if type(layer) == tf.keras.layers.Conv2D:
                layer.kernel_regularizer = tf.keras.regularizers.l2(1e-5)

    def call(self, x):
        return self._model(x)


if __name__ == "__main__":
    m = Model()
    x = tf.random.uniform(shape=(1, 512, 512, 3))
    m.build()
    m.call(x)
    print(m.losses)
```

It turns out that `add_loss()` is not compatible with eager execution. Please read more about it [here](https://github.com/tensorflow/compression/issues/9).

**Comment by ymodak** [comment] 2020-06-08 23:04
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2020-06-08 23:04 UTC
Labels: TF 2.0, comp:keras, type:bug

**Comment by meet-minimalist** [comment] 2020-06-28 08:23
> @ujjwal-ai , Please find below code. It resolves the error.
> 
> ```python
> import tensorflow as tf
> 
> class Model(tf.keras.Model):
>     def __init__(self):
>         super(Model, self).__init__()
>         self._model = tf.keras.applications.ResNet101(include_top=False, weights='imagenet')
> 
>     def build(self, input_shape=None):
>         for layer in self._model.layers:
>             if type(layer) == tf.keras.layers.Conv2D:
>                 layer.kernel_regularizer = tf.keras.regularizers.l2(1e-5)
> 
>     def call(self, x):
>         return self._model(x)
> 
> 
> if __name__ == "__main__":
>     m = Model()
>     x = tf.random.uniform(shape=(1, 512, 512, 3))
>     m.build()
>     m.call(x)
>     print(m.losses)
> ```
> 
> It turns out that `add_loss()` is not compatible with eager execution. Please read more about it [here](https://github.com/tensorflow/compression/issues/9).

Hey, thanks for the reference solution. I used this code to add regularization losses for pretrained model. But when I executed the code and listed down the losses, I got empty list. I am expecting a list of regularization losses based on number of convolutional layers in pretrained model.
