### ISSUE TITLE
module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by AquaDef** [tensorflow/tensorflow#32784] opened 2019-09-24 15:55 UTC
File "F:\AI\RedditChatBot\nmt-chatbot-master\nmt\gnmt_model.py", line 262, in <module>
    class GNMTAttentionMultiCell(tf.nn.rnn_cell.MultiRNNCell):
AttributeError: module 'tensorflow_core._api.v2.nn' has no attribute 'rnn_cell'

**Comment by mihaimaruseac** [comment] 2019-09-24 20:15
Can you please also post a code sample (using proper Markdown formatting so it's easy to read) that is a minimal reproduction example?

**Comment by Geoyi** [comment] 2019-10-02 21:11
@AquaDef, you may have `Tensorflow 2.0` installed, but the code you used was based on Tensorflow 1. xx. I would switch to install a lower version of TensorFlow.

**Comment by mitsuhisaT** [comment] 2019-10-07 23:32
I'm trying TensorFlow 2.0.
I got same error.

I used data is download from
https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip

```python
with ZipFile(AirQualityUCI.zip) as z:
    with z.open('AirQualityUCI.xlsx') as f:
        air_quality = pd.read_excel(
            f,
            index_col=0, parse_dates={'DateTime': [0, 1]},
            na_values=[-200.0],
            convert_float=False
        )

target_columns = ['T', 'AH', 'PT08.S1(CO)', 'PT08.S2(NMHC)',
                  'PT08.S3(NOx)', 'PT08.S4(NO2)']
air_quality = air_quality[target_columns]

dataset = TimeSeriesDataSet(air_quality)
train_dataset = dataset[dataset.times.year < 2005]
test_dataset = dataset[dataset.times.year >= 2005]

sess = tf.compat.v1.InteractiveSession()
tf.compat.v1.set_random_seed(12345)
SERIES_LENGTH = 72
FEATURE_COUNT = dataset.feature_count

tf.compat.v1.disable_eager_execution()
x = tf.compat.v1.placeholder(tf.float32, [None, SERIES_LENGTH, FEATURE_COUNT])
y = tf.compat.v1.placeholder(tf.float32, [None, FEATURE_COUNT])

cell = tf.nn.rnn_cell.BasicRNNCell(20)
```

**Comment by mihaimaruseac** [comment] 2019-10-08 16:38
There is no [`tf.nn.rnn_cell` in 2.0 API](https://www.tensorflow.org/api_docs/python/tf/nn/). 

Please consult https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility and run the upgrade script to update your code to work on 2.0.

**Comment by mitsuhisaT** [comment] 2019-10-08 22:32
> There is no [`tf.nn.rnn_cell` in 2.0 API](https://www.tensorflow.org/api_docs/python/tf/nn/).
> 
> Please consult https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility and run the upgrade script to update your code to work on 2.0.

Thank you, I try that.

**Comment by ravikyram** [comment] 2019-10-10 11:50
@AquaDef ,mitsuhisaT 
Did you get a chance to look @mihaimaruseac suggestion . Please close the issue if it was resolved already. Thanks!

**Comment by ravikyram** [comment] 2019-10-18 11:27
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2019-10-18 11:27 UTC
Labels: TF 2.0, comp:apis, stat:awaiting response, type:support

**Comment by yang12313** [comment] 2019-10-29 21:52
> > There is no [`tf.nn.rnn_cell` in 2.0 API](https://www.tensorflow.org/api_docs/python/tf/nn/).
> > Please consult https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility and run the upgrade script to update your code to work on 2.0.
> 
> Thank you, I try that.

Hi Buddy,

does it work?

**Comment by crisNguyen** [comment] 2020-05-29 07:34
I'm trying TensorFlow 2.2.
I got same error.
i can't fix it  from link https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility

please help me

**Comment by mihaimaruseac** [comment] 2020-05-29 16:27
TF 2.2 does not have `tensorflow_core`. Please check output of `pip lists`, it's likely you have packages predating this release.

Please open new issue, fill in issue template.

**Comment by Rahul-351** [comment] 2023-09-13 08:54
Hii @mitsuhisaT,  I am a very beginner can you please explain to me how I could the upgrade script to update your code to work on 2.0.
