### ISSUE TITLE
Stuck while using TFRecordWriter - TypeError: <class 'tensorflow.python.framework.ops.EagerTensor'>, but expected one of: (<class 'int'>,)

### ISSUE THREAD

**Issue by smescarzaga** [tensorflow/tensorflow#36580] opened 2020-02-08 18:24 UTC
I'm using Tensorflow-GPU 1.15.0 in a Colab notebook (Python 3.6.10) with local runtime on a Windows 10 device. I'm receiving the error above when trying to write the predictions I've created to a TfRecord File. It is based on [this](https://github.com/google/earthengine-api/blob/master/python/examples/ipynb/TF_demo1_keras.ipynb) colab notebook. It works fine on that hosted runtime but Running this job there is not an option as it takes too long.

```
# Instantiate the writer.
writer = tf.python_io.TFRecordWriter(outputImageFile)

# Every patch-worth of predictions we'll dump an example into the output
# file with a single feature that holds our predictions. Since our predictions
# are already in the order of the exported data, the patches we create here
# will also be in the right order.
patch = [[], [], [], []]
curPatch = 1
for prediction in predictions:
  patch[0].append(tf.argmax(prediction, 1))
  patch[1].append(prediction[0][0])
  patch[2].append(prediction[0][1])
  patch[3].append(prediction[0][2])
  # Once we've seen a patches-worth of class_ids...
  if (len(patch[0]) == PATCH_WIDTH * PATCH_HEIGHT):
    print('Done with patch ' + str(curPatch) + ' of ' + str(PATCHES) + '...')
    # Create an example
    example = tf.train.Example(
      features=tf.train.Features(
        feature={
          'prediction': tf.train.Feature(
              int64_list=tf.train.Int64List(
                  value=patch[0])),
          'bareProb': tf.train.Feature(
              float_list=tf.train.FloatList(
                  value=patch[1])),
          'vegProb': tf.train.Feature(
              float_list=tf.train.FloatList(
                  value=patch[2])),
          'waterProb': tf.train.Feature(
              float_list=tf.train.FloatList(
                  value=patch[3])),
        }
      )
    )
    # Write the example to the file and clear our patch array so it's ready for
    # another batch of class ids
    writer.write(example.SerializeToString())
    patch = [[], [], [], []]
    curPatch += 1

writer.close()
```

**Error:**
```
TypeError                                 Traceback (most recent call last)
<ipython-input-26-d7a6c8a0115c> in <module>
     21           'prediction': tf.train.Feature(
     22               int64_list=tf.train.Int64List(
---> 23                   value=patch[0])),
     24           'bareProb': tf.train.Feature(
     25               float_list=tf.train.FloatList(

c:\anaconda\envs\tfcollab\lib\site-packages\google\protobuf\internal\python_message.py in init(self, **kwargs)
    533             field_value = [_GetIntegerEnumValue(field.enum_type, val)
    534                            for val in field_value]
--> 535           copy.extend(field_value)
    536         self._fields[field] = copy
    537       elif field.cpp_type == _FieldDescriptor.CPPTYPE_MESSAGE:

c:\anaconda\envs\tfcollab\lib\site-packages\google\protobuf\internal\containers.py in extend(self, elem_seq)
    279       raise
    280 
--> 281     new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
    282     if new_values:
    283       self._values.extend(new_values)

c:\anaconda\envs\tfcollab\lib\site-packages\google\protobuf\internal\containers.py in <listcomp>(.0)
    279       raise
    280 
--> 281     new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]
    282     if new_values:
    283       self._values.extend(new_values)

c:\anaconda\envs\tfcollab\lib\site-packages\google\protobuf\internal\type_checkers.py in CheckValue(self, proposed_value)
    136       message = ('%.1024r has type %s, but expected one of: %s' %
    137                  (proposed_value, type(proposed_value), six.integer_types))
--> 138       raise TypeError(message)
    139     if not self._MIN <= int(proposed_value) <= self._MAX:
    140       raise ValueError('Value out of range: %d' % proposed_value)

TypeError: <tf.Tensor: id=408263, shape=(1,), dtype=int64, numpy=array([5], dtype=int64)> has type <class 'tensorflow.python.framework.ops.EagerTensor'>, but expected one of: (<class 'int'>,)
```

**Comment by ravikyram** [comment] 2020-02-10 10:32
@smescarzaga 

I tried to reproduce the issue by the link you have provided. But i am seeing the error when tried to execute the code `EEException: Permission denied.`Please, help me in reproducing the issue. Thanks!

**Comment by Saduf2019** [comment] 2020-02-17 09:12
@smescarzaga Please respond to the above comment.

**Comment by smescarzaga** [comment] 2020-02-18 05:49
> @smescarzaga
> 
> I tried to reproduce the issue by the link you have provided. But i am seeing the error when tried to execute the code `EEException: Permission denied.`Please, help me in reproducing the issue. Thanks!

The notebook was authored by Google Earth Engine developers and is public facing, not sure how I can help with your specific exception. Did you authorize earth engine api?

**Comment by gowthamkpr** [comment] 2020-03-06 23:36
@smescarzaga I am closing this issue as it is not related to bug/performance, build/install, feature request or doc related issues. Please post this issue on stackoverflow where there is a wider community to help. Thanks!

**Closed by gowthamkpr** 2020-03-06 23:36 UTC
Labels: TF 1.15, comp:data, type:support

**Comment by shivammalviya712** [comment] 2020-06-10 11:09
Please, can anyone tell what is the cause of this error?
I am also getting the same error, and unable to find the solution elsewhere.

**Comment by anuj-agarwal** [comment] 2020-06-17 02:21
I am getting this same error when I use the output dataset from tf.data.Dataset.from_tensor_slices() in both tf.data.experimental.TFRecordWriter as well as tf.io.TFRecordWriter.
However if I use the original features (in numpy format without transformations) passing it with a loop, I get error with boolean features and no error is if convert it to int.
The serialize_example for one observation run individually does not throw error with boolean values, and not even in TFRecordWriter.

See the attached notebook for the full run and error message. The code is one on the Tensorflow examples for TFExample and TFRecord.

I am using Tensorflow v2.1.0 with Python 3.6 installed in a conda env on a Windows 10 Machine.

[tf2_tfexample_tfrecord.zip](https://github.com/tensorflow/tensorflow/files/4789997/tf2_tfexample_tfrecord.zip)


Any help or suggestion would be appreciated.

**Comment by SunnyHong36** [comment] 2021-03-30 14:14
> I am getting this same error when I use the output dataset from tf.data.Dataset.from_tensor_slices() in both tf.data.experimental.TFRecordWriter as well as tf.io.TFRecordWriter.
> However if I use the original features (in numpy format without transformations) passing it with a loop, I get error with boolean features and no error is if convert it to int.
> The serialize_example for one observation run individually does not throw error with boolean values, and not even in TFRecordWriter.
> 
> See the attached notebook for the full run and error message. The code is one on the Tensorflow examples for TFExample and TFRecord.
> 
> I am using Tensorflow v2.1.0 with Python 3.6 installed in a conda env on a Windows 10 Machine.
> 
> [tf2_tfexample_tfrecord.zip](https://github.com/tensorflow/tensorflow/files/4789997/tf2_tfexample_tfrecord.zip)
> 
> Any help or suggestion would be appreciated.

I use TF2.3.0 and python3.7 run the code from the 'TFRecord and tf.Example' of 'Load and preprocess data' in Tensorflow Tutorials, and i also get this error:"TypeError: <tf.Tensor: shape=(), dtype=bool, numpy=True> has type <class 'tensorflow.python.framework.ops.EagerTensor'>, but expected one of: (<class 'int'>,) [Op:EagerPyFunc]"
Have you solved the problem?
Appreciating for your reply

**Comment by zuoyuwei** [comment] 2021-05-14 01:06
I meet the same error, please ask for solution? Thanks

**Comment by zuoyuwei** [comment] 2021-05-14 06:00
I recreate a conda environment, pip install 2.x.x(in my code use 2.4.1), it will install python package for example numpy and so on. Then the problem can fix.

**Comment by hxx3927** [comment] 2021-05-27 09:40
I meet the error in win10, but I run the same code in ubuntu is no problem
