### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GRUCell'

### ISSUE THREAD

**Issue by ymakkapa** [tensorflow/tensorflow#8822] opened 2017-03-29 23:26 UTC
Hello everyone,
I got the code from tensorflow website for this tutorial. It processed for a long while and got the following errors. Installing tensorflow from sources also did not work for me as it gave me many errors. so I deleted everything installed tensorflow on my Ubuntu 16.04 LTS. Please please help me in resolving these errors as it is an emergency. I am a beginner to tensorflow and its been 2 months already I have been seeing this error

Thanks in advance
![seq](https://cloud.githubusercontent.com/assets/20130992/24480978/67188b74-149c-11e7-89a5-63d69c3a8412.png)

**Comment by av8ramit** [comment] 2017-03-30 00:43
Closing this as a duplicate of #8821

**Closed by av8ramit** 2017-03-30 00:43 UTC
