### ISSUE TITLE
API function changed from Keras 2.3.1 to Keras 2.4.2?

### ISSUE THREAD

**Issue by shartoo** [tensorflow/tensorflow#34264] opened 2019-11-14 07:27 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version : `TF 2.0.0 stable + Keras 2.4.2 `(A )and `1.13.1 +Keras 2.3.1` (B)
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

I want to do a transfer learning on MobileNet and change the input size ,i copied the code [colab](https://colab.research.google.com/drive/1s1lkOiqKgl9_MsXJtPF--oh6uXHYkNYm#scrollTo=dV7a_Jca4cgC) according to [Changing input size of pre-trained models in Keras](https://medium.com/@ckyrkou/changing-input-size-of-pre-trained-models-in-keras-3dfbe3ca3091) .Everythin goes fine on my machine **B**(TF 1.13.1 + Keras 2.3.1) ,i could got exact the same output of author namely the input size got changed,while on my another machine **A**(TF 2..0.0+ Keras 2.4.2) i have to do some change and the result of input shape stays 224x224x3 but not as excepted 130x130x3.

+ Tensorflow 1.13.1+ Keras 2.3.1 works fine

```
# work on tensorflow 1.13.1 
import keras
import numpy as np
keras.backend.clear_session()

def change_model(model, new_input_shape=(None, 40, 40, 3)):
    # replace input shape of first layer
    model._layers[0].batch_input_shape = new_input_shape

    # rebuild model architecture by exporting and importing via json
    new_model = keras.models.model_from_json(model.to_json())

    # copy weights from old model to new one
    for layer in new_model.layers:
        try:
            layer.set_weights(model.get_layer(name=layer.name).get_weights())
            print("Loaded layer {}".format(layer.name))
        except:
            print("Could not transfer weights for layer {}".format(layer.name))
    return new_model

from keras.applications.mobilenet import MobileNet
from keras.preprocessing import image
from keras.applications.mobilenet import preprocess_input,decode_predictions
import numpy as np
model = MobileNet(weights='imagenet',include_top=True,input_shape=(224, 224,3))
new_model = change_model(model,new_input_shape=(None, 130, 130, 3))
new_model.summary()
```
ouput is 130x130x3
```
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         (None, 130, 130, 3)       0
_________________________________________________________________
conv1_pad (ZeroPadding2D)    (None, 131, 131, 3)       0
_________________________________________________________________
conv1 (Conv2D)               (None, 65, 65, 32)        864
_________________________________________________________________
conv1_bn (BatchNormalization (None, 65, 65, 32)        128
...
```
+ Tensorflow 2.0.0 + Keras 2.4.2 

```
# work on Tensorflow 2.0.0 
import keras
import tensorflow as tf
from keras_applications.mobilenet import MobileNet

def change_model(model, new_input_shape=(None,40, 40, 3)):
    # replace input shape of first layer
    model._layers[0].batch_input_shape = new_input_shape
    # rebuild model architecture by exporting and importing via json
    new_model = tf.keras.models.model_from_json(model.to_json())
    # copy weights from old model to new one
    for layer in new_model.layers:
        try:
            layer.set_weights(model.get_layer(name=layer.name).get_weights())
            print("Loaded layer {}".format(layer.name))
        except:
            print("Could not transfer weights for layer {}".format(layer.name))
    return new_model

model = MobileNet(include_top=True,weights="imagenet",input_shape=(224,224,3),backend = tf.keras.backend, layers = tf.keras.layers, models = tf.keras.models, utils = tf.keras.utils)
new_model = change_model(model,new_input_shape=(None,130,130,3))
print(new_model.summary())
```
output stays 224x224x3

```
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv1_pad (ZeroPadding2D)    (None, 225, 225, 3)       0         
_________________________________________________________________
conv1 (Conv2D)               (None, 112, 112, 32)      864       
_________________________________________________________________
conv1_bn (BatchNormalization (None, 112, 112, 32)      128       
_________________________________________________________________
conv1_relu (ReLU)            (None, 112, 112, 32)      0         
_________________________________________________________________
....
```

**Will this change the current api? How?**

not sure.

**Comment by kiflowb777** [comment] 2019-11-14 12:07
I noticed that different versions of the keras can return different layer shapes.
The output shape of the layer is different in the keras and tf.keras: https://github.com/tensorflow/tensorflow/issues/33785

**Comment by rmothukuru** [comment] 2019-11-15 10:56
Could reproduce the issue by changing the TF Version from 1.13 to 2.0. Here is the [Gist](https://colab.sandbox.google.com/gist/oanush/47bf6c47011dacd95beca106b25d654e/34264.ipynb). Thanks!

**Comment by yhliang2018** [comment] 2020-03-19 22:10
Hi @shartoo , with the current implementation, you may use the [`_batch_input_shape`](https://github.com/tensorflow/tensorflow/blob/a36fbd6a82d91f47cda9cc8da26d6a83d551b42a/tensorflow/python/keras/engine/base_layer.py#L374) for the attribute assignment to Keras Layer or Model. Can you try it to see if it works? Thanks.

**Comment by saikumarchalla** [comment] 2020-04-03 08:45
@shartoo  Closing this issue as it is the intended behaviour.Thanks!

**Closed by saikumarchalla** 2020-04-03 08:45 UTC
Labels: TF 2.0, comp:keras, type:bug
