### ISSUE TITLE
Provide GPU implementations for resize image methods

### ISSUE THREAD

**Issue by panmari** [tensorflow/tensorflow#533] opened 2015-12-17 14:57 UTC
As far as I can tell, these operations are only provided on CPU so far. It would be very convenient to also have GPU implementations. I'll have a go at it if there's nobody else working on it.

Edit: I mean methods such as resize_nearest_neighbor, not the reshape operator.

**Comment by girving** [comment] 2015-12-19 00:41
Tensors on the GPU still store their shapes on the CPU, and `reshape` already works in that case.  The shape will never be stored on the GPU, so I think this should be closed.  Presumably you're seeing an error caused by forcing the shape argument onto the GPU; if so there should possibly be a different bug about placer functionality.

**Comment by martinwicke** [comment] 2015-12-19 00:51
Wouldn't tf.shape return a tensor that could be shipped onto the GPU? In
that case, all information could be on the GPU, and the actual resizing
code should be able to run on the GPU.

**Comment by girving** [comment] 2015-12-19 00:53
The `Tensor` C++ class unconditionally stores the shape on the CPU regardless of where the data is, and essentially everything assumes this (for error detection, branching, etc.).  I think there's very little chance this situation will change.

**Comment by girving** [comment] 2015-12-19 00:54
Note that as long as all the shape data is on the CPU, a `reshape` does O(0) GPU work even if the data is on the GPU.

**Comment by martinwicke** [comment] 2015-12-19 01:01
I think I'm implicitly assuming we're talking about the resize_image ops.
Sorry, that may be misinterpreting panmari's original request.

**Comment by girving** [comment] 2015-12-19 01:05
Ah, all my comments are wrong if this is about image resizing.

**Comment by martinwicke** [comment] 2015-12-19 01:14
@panmari -- which ops are you thinking about?

**Comment by vrv** [comment] 2015-12-19 01:36
Given @panmari's recent pull request to extend the types supported by resize_image ops, I think it's those.

**Comment by panmari** [comment] 2015-12-19 15:22
Yes, as the @vrv and @martinwicke assumed, I meant the resize_image ops. I'll change the title to reflect that more clearly.

**Comment by TimZaman** [comment] 2016-11-29 18:21
Sorry to be the necromancer, but any plans on this?

**Comment by girving** [comment] 2016-11-29 18:27
@TimZaman I think it's still contributions welcome. :)

**Comment by TimZaman** [comment] 2016-11-29 18:32
@girving I will send you a wheel of cheese from the Netherlands if you get someone to implement this. All bribes aside, this PR matched with this issue: https://github.com/tensorflow/tensorflow/pull/588 but sadly it's the lowest quality algo.

**Comment by girving** [comment] 2016-11-29 18:39
@TimZaman It'd be better to send the wheel of cheese to whoever implements the feature.  Not sure where best to advertise that, though.

**Comment by TimZaman** [comment] 2017-02-13 09:31
So what's this then https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc

**Comment by girving** [comment] 2017-02-13 15:58
Looks like someone did it, at least for bilinear.  @panmari Should this be closed, or are there missing ones?

**Comment by yaroslavvb** [comment] 2017-02-13 17:39
PS resize bilinear and resize bicubic GPU implementations are slow (about 2 seconds for resizing to 1280 x 1280, same as on CPU), when we switched to nearest neighbor, it made our CNN run 10x faster

**Comment by panmari** [comment] 2017-02-14 09:38
I did the implementation for nearest neighbor in #588 (funny enough, blame doesn't show me anymore). That algorithm is good enough for my purposes and I've been using it since. So from my side, we can close this bug @girving. But there might be others that want fast implementations for other algorithms such as @TimZaman. Maybe I'll come around and do some benchmarking of the current implementation of bilinear and see what can be done. Who's the author of it?

**Comment by girving** [comment] 2017-02-14 15:22
Cc @gpapan.

**Comment by gpapan** [comment] 2017-02-14 17:04
I did the gpu implementation for bilinear interpolation. The Cuda kernel can get faster (e.g., have each thread compute multiple channels reusing the indexing arithmetic). However, I find the quoted "(about 2 seconds for resizing 375 x 667 to 1280 x 1280, same as on CPU)" too large. What is the benchmark used? Are we certain that the gpu path is activated? Which gpu? What is the depth of the tensors? Does this cover forward only or both forward and backward? In any case, I think writing a benchmark suite is the first step that we should accomplish.

**Comment by yaroslavvb** [comment] 2017-02-14 18:02
cc @strin who gave me these numbers

**Comment by girving** [comment] 2017-06-16 18:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by girving** 2017-06-16 18:16 UTC
Labels: stat:contributions welcome, type:feature

**Comment by zxzhijia** [comment] 2018-09-20 20:10
When I run resize_image using float32, it takes 18us. If I change it to float16, it changes to 60ms. Does anyone know what's going on?

**Comment by TimZaman** [comment] 2018-09-20 20:32
Ask questions on StackOverflow, please. _Speculating_: the fp32 might run on GPU, while the fp16 runs might run on CPU as no GPU implementation might be available.

**Comment by panmari** [comment] 2018-09-21 07:00
Indeed, half number types are not supported for bilinear resize on GPU, see [here] (https://github.com/tensorflow/tensorflow/blob/cf047f7755f3400ee128db2571042091fe9f8314/tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc#L215). 

You could try to compile it for all number types using TF_CALL_GPU_NUMBER_TYPES, then compile tensorflow and test it.

**Comment by SummitKwan** [comment] 2019-04-18 06:29
I have a related question: does gradient go through the image_resize op normally if I use this op in intermediate layers for upsampling?  Thank you

**Comment by robertlugg** [comment] 2019-06-12 18:21
@haeusser I believe not implemented for BICUBIC (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/kernels) GPU.

**Comment by ziyigogogo** [comment] 2019-06-25 06:24
@haeusser i tried using ResizeBicubic as part of my custom upsampling layer. Seems that it's 50x slower than Bilinear in backward pass. And I did not see any things related to Bicubic in your ref link. Could you share your solution? Or the current tf version just not implemented the bicubic grad yet?

**Comment by ziyigogogo** [comment] 2019-06-25 06:26
> I have a related question: does gradient go through the image_resize op normally if I use this op in intermediate layers for upsampling? Thank you

@SummitKwan , the Bilinear and NearestNeigbour works good as part of upsampling process on gpu. Bicubic works well but slow since it seems that there are no gpu support kernel for this op currently.

**Comment by suyashbakshi** [comment] 2019-07-26 19:45
> So what's this then https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc

Hello, I'm trying to use fp16 resize_bilinear on my RTX20280ti. Any information on which TF version contains this kernel? I installed tf1.15 nightly as well as tf2.0 using pip, but all i keep getting is "DLL load failed" error.

Any help is appreciated!

**Comment by NoneLand** [comment] 2021-07-13 07:33
It cost me one day to figure out that if you want to use gpu resize_images on tf1.13 you should pass tf.float32 images totf.image.resize_images. If you use uint8, it would on CPU due to lack of uin8 kernel.

**Comment by avirajBevli** [comment] 2024-03-13 05:04
Curious: Is anyone working on the GPU implementation for image resize with bicubic interpolation?
