### ISSUE TITLE
Data input pipeline does not implement Batch for "from_tensor_slices(dict(df))"

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#46067] opened 2020-12-30 08:08 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): latest from source
- TensorFlow version (use command below): latest from source
- Python version: 3.8
- Bazel version (if compiling from source): 3.6.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 2070

**Describe the current behavior**
```https://www.tensorflow.org/guide/data#consuming_csv_data```

```titanic_slices = tf.data.Dataset.from_tensor_slices(dict(df))```

That code will have dictionary object slice.
element_spec returns {dict:XX} This throws exception if we use Batch from the same documentation,

```def make_window_dataset(ds, window_size=5, shift=1, stride=1):
  windows = ds.window(window_size, shift=shift, stride=stride)

  def sub_to_batch(sub):
    return sub.batch(window_size, drop_remainder=True)

  windows = windows.flat_map(sub_to_batch)
  return windows
```

**Comment by Saduf2019** [comment] 2020-12-31 13:05
closing this as duplicate of #46066

**Closed by Saduf2019** 2020-12-31 13:05 UTC
Labels: comp:data, type:bug
