### ISSUE TITLE
ValueError: Unknown metric function: CustomMetric using custom metrics when loading tf saved model type with tf.keras.models.load_model 

### ISSUE THREAD

**Issue by AndersonHappens** [tensorflow/tensorflow#33646] opened 2019-10-23 20:10 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7

**Describe the current behavior**
ValueError: Unknown metric function: CustomMetric occurs when trying to load a tf saved model using  tf.keras.models.load_model with a custom metric. If you look at the code for load_model, it is clear the load_model currently ignores the custom_objects dict for the tf saved model format.

**Describe the expected behavior**
load_model loads the custom metric successfully either just implicitly or through the custom_objects dict. 

**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.metrics import Metric
import numpy as np

class CustomMetric(Metric):
  def __init__(self,
               name='score',
               dtype=tf.float32):
    super(CustomMetric, self).__init__(name=name)
    self.true_positives = self.add_weight(
        'true_positives',
        shape=[10],
        initializer='zeros',
        dtype=self.dtype)


  def update_state(self, y_true, y_pred, sample_weight=None):
    pass

  def result(self):
    return 0

  def get_config(self):
    """Returns the serializable config of the metric."""
    config = {}
    base_config = super(CustomMetric, self).get_config()
    return dict(list(base_config.items()) + list(config.items()))

  def reset_states(self):
    self.true_positives.assign(np.zeros(self.num_classes), np.float32)
    self.weights_intermediate.assign(
        np.zeros(self.num_classes), np.float32)
            
inputs = keras.Input(shape=(784,), name='digits')
x = layers.Dense(64, activation='relu', name='dense_1')(inputs)
x = layers.Dense(64, activation='relu', name='dense_2')(x)
outputs = layers.Dense(10, activation='softmax', name='predictions')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name='3_layer_mlp')

model.compile(loss='sparse_categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=.001), metrics=[CustomMetric()])

model.save("model/", save_format='tf')

new_model = keras.models.load_model('model/',  tf.keras.models.load_model ={'score': CustomMetric})
```

**Other info / logs**
```
Traceback (most recent call last):
  File "/home/sentim/Website/model_prediction/test_load_saved_model.py", line 46, in <module>
    new_model = keras.models.load_model('model/', custom_objects={'score': CustomMetric})
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 150, in load_model
    return saved_model_load.load(filepath, compile)
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/saved_model/load.py", line 93, in load
    model._training_config))  # pylint: disable=protected-access
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 356, in compile
    self._cache_output_metric_attributes(metrics, weighted_metrics)
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1901, in _cache_output_metric_attributes
    metrics, self.output_names, output_shapes, self.loss_functions)
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 813, in collect_per_output_metric_info
    metric_name = get_metric_name(metric, is_weighted)
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py", line 987, in get_metric_name
    metric = metrics_module.get(metric)
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/metrics.py", line 2857, in get
    return deserialize(identifier)
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/metrics.py", line 2851, in deserialize
    printable_module_name='metric function')
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 180, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/sentim/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 165, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown metric function: CustomMetric
```

**Comment by ravikyram** [comment] 2019-10-24 09:01
I have tried on colab with TF version 2.0 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/1c9190b3588867fa05dd7103b212bccb/untitled296.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2019-10-26 00:08
@AndersonHappens I think there is an issue with saving a model in *.tf version when the model has custom metrics. I have saved the model in  *.h5 format and everything works as expected. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/5cd85f60f1d6e975ce65675227422b3e/untitled296.ipynb). Thanks!

Please close the issue if it was resolved for you. Thanks!

**Comment by AndersonHappens** [comment] 2019-10-28 16:09
@jvishnuvardhan While it does work in the h5 format, if I have saved a model to the tf format, I cannot load the model to resave it to the h5 format later (since I can't load the model in the first place), so ultimately this is still an issue that needs to be addressed.

**Comment by j-o-d-o** [comment] 2019-11-06 17:49
Here is a workaround for the meantime:
```python
from tensorflow.python.saved_model import loader_impl
from tensorflow.python.keras.saving.saved_model import load as saved_model_load

loader_impl.parse_saved_model(load_path)
model = saved_model_load.load(load_path, custom_objects={"custom_metric": custom_metric})
```

**Comment by JustinhoCHN** [comment] 2019-12-12 01:48
same issue here, when you save the model in tf format, you can't re-load the model with custom_objects, this should be fixed.

**Comment by JustinhoCHN** [comment] 2019-12-12 02:04
> Here is a workaround for the meantime:
> 
> ```python
> from tensorflow.python.saved_model import loader_impl
> from tensorflow.python.keras.saving.saved_model import load as saved_model_load
> 
> loader_impl.parse_saved_model(load_path)
> model = saved_model_load.load(load_path, custom_objects={"custom_metric": custom_metric})
> ```

not working at keras 2.3.1, tf 2.0.0
```
TypeError: load() got an unexpected keyword argument 'custom_objects'
```

**Comment by jvishnuvardhan** [comment] 2019-12-12 17:30
> @jvishnuvardhan While it does work in the h5 format, if I have saved a model to the tf format, I cannot load the model to resave it to the h5 format later (since I can't load the model in the first place), so ultimately this is still an issue that needs to be addressed.

@AndersonHappens Can you please check with the `tf-nightly`. I saved model in "tf" format, then loaded model and saved in "h5" format without any issues. Please check the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/9f3c879cdb48821e6b7554e4fe700e0b/untitled702.ipynb).

Please let us know what you think. Thanks.
@JustinhoCHN can you please try `tf-nightly`. If you still have an issue, please open a new issue with a standalone code to reproduce the error.

I am closing this issue as it was resolved in recent `tf-nightly`. Please feel free to open if the issue persists again. Thanks!

**Comment by j-o-d-o** [comment] 2019-12-15 17:02
This should not be closed, the problem is not the loading in "tf" format as is, but if you have custom_objects to pass!

**Comment by j-o-d-o** [comment] 2019-12-15 17:07
@jvishnuvardhan This issue should not be closed. The loading as in your gist works, but once you use the model, e.g. to further train it you will get an error that the custom object is unkown.

**Comment by j-o-d-o** [comment] 2019-12-15 17:09
Here is a new workaround, not sure what changed that the old one does not work anymore:

```python
from tensorflow.python.saved_model import load as tf_load
from tensorflow.python.keras.saving.saved_model.load import KerasObjectLoader, RevivedModel
from tensorflow.python.keras.saving import saving_utils

custom_objects = {"compute_loss": loss}
model = tf_load.load_internal(PATH_TO_MODEL, loader_cls=KerasObjectLoader)
if isinstance(model, RevivedModel) and compile:
  if model._training_config is not None:
    model.compile(**saving_utils.compile_args_from_training_config(
    model._training_config, custom_objects))
```

**Comment by jvishnuvardhan** [comment] 2019-12-16 18:58
@j-o-d-o Can you try adding one more line as follows and train the model (`loaded_my_new_model_saved_in_h5`).

`loaded_my_new_model_saved_in_h5.compile(loss='sparse_categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=.001), metrics=[CustomMetric()])`

Thanks!

**Comment by j-o-d-o** [comment] 2019-12-17 08:16
The models saved in h5 format seem to work fine, the issue is about models saved with `tf` flag (SavedModel Format).

What is working is setting the compile flag to False and then compiling it on its own e.g.:
```python
import tensorflow as tf

# Save Keras Model as SavedModel (Keras model has some custom objects e.g. custom loss function)
tf.saved_model.save(my_keras_model, EXPORT_DIR)
...
# Load the model and compile on its own (working)
loaded_model = tf.keras.model.load(EXPORT_DIR, custom_objects={"custom_loss": my_custom_loss}, compile=False)
model.compile(optimizer=my_optimizer, loss=my_custom_loss)
# Load the model while also loading optimizer and compiling (failing with "Unkown loss function: my_custom_loss")
loaded_model = tf.keras.model.load(EXPORT_DIR, custom_objects={"custom_loss": my_custom_loss}) # compile is set to True by default
```

The point is:
1) The default way of loading models fails if there are custom objects involved.
2) By compiling yourself you are setting up a new optimizer instead of loading the previously trained models optimizer weights.

Moreover I already submited a PR that would fix this: https://github.com/tensorflow/tensorflow/pull/34048. But it seems nobody bothers about it : /

**Comment by jvishnuvardhan** [comment] 2020-02-04 21:58
@j-o-d-o Can you please check using `model.save` after compile and the use `keras.models.load_model` to load the model. I tried it without any issue. [Here](https://colab.sandbox.google.com/gist/jvishnuvardhan/0f8c9294cfd1e8ae945f9edae36831ad/untitled702.ipynb) is the gist. Please run it with `tf-nightly`. Thanks!

**Comment by jvishnuvardhan** [comment] 2020-03-03 20:43
I am closing this issue as it was resolved. Please feel free to reopen if the issue didn't resolve for you. Thanks!

**Closed by jvishnuvardhan** 2020-03-03 20:43 UTC
Labels: TF 2.0, comp:keras, type:bug

**Comment by ZhiliWang** [comment] 2020-03-22 20:55
Hello gentlemen, I am surprised that I am having a similar issue with a .h5 model. Do I have to define my custom metric as a class instead of a function? thank you!

**Comment by rodrigoruiz** [comment] 2020-04-01 19:51
`tf-nightly` works, but doesn't run on the GPU.

**Comment by jvishnuvardhan** [comment] 2020-04-01 20:28
@rodrigoruiz Can you please open a new issue with details and a simple standalone code to reproduce the issue? Currently `TF2.2.0rc2` is the latest release candidate. I expect there will be TF2.2 stable version will be released in the near future. Thanks!

**Comment by rodrigoruiz** [comment] 2020-04-01 20:32
@jvishnuvardhan I think i figured it out, `tf-nightly` does not run on GPU, `tf-nightly-gpu` does... It's just that this is not specified in the docs.
I'll just wait for the stable version I guess.

**Comment by timatim** [comment] 2020-05-09 19:35
Just tried this on 2.2.0. While it doesn't run into error, it seems to load an empty model. I'm using Feature Column API.

**Comment by jvishnuvardhan** [comment] 2020-05-09 21:15
@timatim Please create a new issue with a simple standalone to reproduce the issue. Thanks!

**Comment by rjurney** [comment] 2020-11-06 17:35
I have this problem loading an .h5 model on TF 2.3.0.

**Comment by dohanaga** [comment] 2021-01-21 01:22
I am using tensorflow v 2.3  in R, saving and loading the model with save_model_tf() , load_model_tf() and I get the same error because of my custom metric balanced accuracy.

I can't  compile it afterwards because I am running a grid search for the optimizer learning rate, so it wont be practical.

my issue was resolved by adding my custom metric in the custom_objects:
load_model_tf(path, custom_objects=list("CustomLayer" = CustomLayer))
