### ISSUE TITLE
Invalid License Error While Running bazel build for tensorflow

### ISSUE THREAD

**Issue by cagrigider** [tensorflow/tensorflow#19029] opened 2018-05-02 17:32 UTC
I am trying to compile tensorflow for Macbook, but every time I am getting same error.

When I Run this command

`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

I get this error

`/private/var/tmp/_bazel_cagrigider/2c548436011ab6b7308cd0cc70a91ed3/external/bazel_tools/tools/cpp/BUILD:3:1: invalid license type: 'notice'`

[Full Output Of Terminal](https://i.stack.imgur.com/S9MtY.png)

Mac OS 10.13.3

Xcode version = 9.2

Tensorflow version = 1.8

Bazel version = 0.13.0

Thanks.

**Comment by tensorflowbutler** [comment] 2018-05-03 01:25
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cagrigider** [comment] 2018-05-03 06:42
I am trying to use 
Tensorflow 1.8 on my 2015 Macbook Pro (OS X 10.13.3 High Sierra) CPU only.

I installed Tensorflow from [https://www.tensorflow.org/install/install_mac](tensorflow)

Tensorflow Version = 1.8
Bazel Version = 0.13.0

I am getting error with that command 
`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

**Comment by angersson** [comment] 2018-05-07 22:00
This looks like it could potentially be a bug with our build system or a problem with Bazel. Same failure instance: https://github.com/bazelbuild/bazel/issues/5157

@gunan Any clues on this? We could defer to the Bazel-side bug for now.

**Comment by gunan** [comment] 2018-05-08 20:00
This is an exact duplicate of bazelbuild/bazel#5157
The failure is also emitted from bazel_tools external repository.
I will close this as a duplicate.

**Closed by gunan** 2018-05-08 20:00 UTC
Labels: stat:awaiting tensorflower, type:build/install
