### ISSUE TITLE
How to create Flex-free model in TFLite

### ISSUE THREAD

**Issue by nehasoni3** [tensorflow/tensorflow#45875] opened 2020-12-19 13:36 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): Installed via PIP
- TensorFlow version (or github SHA if from source): Tensorflow 2.3.1

**Command used to run the converter or code if you’re using the Python API**
```python
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)

```
NOTE: Model is successfully converted.

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- TFlite model is working fine at CPU Linux 16.04 and RaspberryPi. But it gives BUS ERROR at edge device. [Details](https://github.com/tensorflow/tensorflow/issues/45504).

The original model is in PyTorch. I have used PyTorch-ONNX-Tensorflow-TFLite approach to convert the model in TFLite.
I am sharing graphs of ONNX and TFLite model. [Link](https://drive.google.com/drive/folders/1jzLZKus-9Dey2vgcMWjspBZfCRJbLCWW?usp=sharing)

Geeks says 
> Using Flex op requires to build TF op kernels which is difficult to support various targets.
If the required Flex op is only FlexMul, I think you might be able to create Flex-free model with some refactoring.

How can do this "create Flex-free "?

**Comment by abattery** [comment] 2020-12-21 03:08
Could you share your FlexMul op details? Which type being calculated? Which input shape being calculated?

TFLite Mul can support F32, I32, QI8, QUI8, and QI16 inputs and support up to 4 dims if broadcasting is needed or the same input shapes.

If you can modify your model to adjust the above Mul op constraints, the FlexMul op requirement will be gone.

**Comment by nehasoni3** [comment] 2020-12-22 07:38
> Could you share your FlexMul op details? Which type being calculated? Which input shape being calculated?
> 
> TFLite Mul can support F32, I32, QI8, QUI8, and QI16 inputs and support up to 4 dims if broadcasting is needed or the same input shapes regardless of dimensions.
> 
> If you can modify your model to meet the above Mul op constraints, the FlexMul op requirement will be gone.

I have already shared graphs.[Link](https://drive.google.com/drive/folders/1jzLZKus-9Dey2vgcMWjspBZfCRJbLCWW)
Input to model is = [1,500,120]

> If you can modify your model to meet the above Mul op constraints, the FlexMul op requirement will be gone.HOW?

**Comment by abattery** [comment] 2020-12-22 09:10
Could you share your Flex-enabled tflite model file to us instead of the graph and share some warning logs like the below example you can see those warnings in tf-nightly version when you are converting the model?

```
I1120 16:16:16.002125 2530115 flatbuffer_export.cc:...] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):

Flex ops: tf.MaxPool
Details:
        tf.MaxPool {data_format = "NCHW", device = "", explicit_paddings = [], ksize = [1, 1, 2, 2], padding = "VALID", strides = [1, 1, 2, 2]}
        tf.MaxPool {data_format = "NCHW", device = "", explicit_paddings = [], ksize = [1, 1, 3, 3], padding = "VALID", strides = [1, 1, 1, 1]}
```

Based on the above information, you can find which one is the original operators in the source graph and replace the one with the supported operator case by modifying the source graph.

**Comment by nehasoni3** [comment] 2020-12-22 12:31
> Could you share your Flex-enabled tflite model file to us instead of the graph image if possible? And it would be helpful to understand why the FlexMul op is introduced if you can share some warning logs like the below example. You can see the following warnings in tf-nightly version when you are converting the model.
> 
> ```
> I1120 16:16:16.002125 2530115 flatbuffer_export.cc:...] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):
> 
> Flex ops: tf.MaxPool
> Details:
>         tf.MaxPool {data_format = "NCHW", device = "", explicit_paddings = [], ksize = [1, 1, 2, 2], padding = "VALID", strides = [1, 1, 2, 2]}
>         tf.MaxPool {data_format = "NCHW", device = "", explicit_paddings = [], ksize = [1, 1, 3, 3], padding = "VALID", strides = [1, 1, 1, 1]}
> ```
> 
> Based on the above information, you can find which one is the corresponding operator in the source graph for the FlexMul op in the TensorFlow Lite and you can find a way to replace the source operator with the supported operator case by modifying the source graph.

Sorry,I can not share model. I have used TF 2.3.1 for conversion and while conversion there is no log as you mentioned.
For Flex ops details, There is FlexMul and FlexADDv2 in TFLite graph and MatMUL ops in source graph(ONNX).
![flexMUL](https://user-images.githubusercontent.com/31642462/102888895-a71a8300-447f-11eb-94c2-9667930c89d0.png)

![onnx](https://user-images.githubusercontent.com/31642462/102888814-818d7980-447f-11eb-8678-78f122e8825e.png)

**Comment by abattery** [comment] 2020-12-22 12:38
@nehasoni3 can you share the screenshot of the tabs that appear when you click Mul op and FlexMul op in the netron app?

And can you share the input tensor type of Mul op and input shape information of Mul op?

**Comment by nehasoni3** [comment] 2020-12-22 12:44
> @nehasoni3 can you share the screenshot of the tabs that appear when you click Mul op and FlexMul op in the netron app?
> 
> And can you share the input tensor type of Mul op and input shape information of Mul op?

![MatMUL_ONNX](https://user-images.githubusercontent.com/31642462/102889931-894e1d80-4481-11eb-8099-a845c3e75ba0.png)

**Comment by abattery** [comment] 2020-12-22 12:50
If you can click the + button, which is located at each input and each output, there is more information regarding input types and shapes.

**Comment by nehasoni3** [comment] 2020-12-22 13:24
If I use this only,
`converter.target_spec.supported_ops = [
  tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()`
This works but every op is of Flex.
But If I use, 
`converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS]
tflite_model = converter.convert()`
I got this log-
`---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/convert.py in toco_convert_protos(model_flags_str, toco_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    212                                                  debug_info_str,
--> 213                                                  enable_mlir_converter)
    214       return model_str

4 frames
Exception: <unknown>:0: error: loc(callsite(callsite("Mul@__inference___call___2921" at "PartitionedCall@__inference_signature_wrapper_2928") at "PartitionedCall")): 'tf.Mul' op is neither a custom op nor a flex op
<unknown>:0: note: loc("PartitionedCall"): called from
<unknown>:0: error: loc(callsite(callsite("add_2@__inference___call___2921" at "PartitionedCall@__inference_signature_wrapper_2928") at "PartitionedCall")): 'tf.AddV2' op is neither a custom op nor a flex op`

**Comment by abattery** [comment] 2020-12-22 13:43
Yes, this is an expected behavior. The current model input for conversion can not be covered by the TFLite builtin op set. So we need flex ops or custom ops.

**Comment by abattery** [comment] 2020-12-23 02:18
If you can fix the input shapes in the model during conversion, those Flex op requirements might be gone.

**Comment by nehasoni3** [comment] 2020-12-23 07:49
> If you can fix the input shapes in the model during conversion, those Flex op requirements might be gone.

How can I fix the input shapes. Do I need to change its dtype or what?

**Comment by abattery** [comment] 2020-12-24 01:46
I am assuming that the model is using float32 type, which is a typical choice among ML model. If it is true, the Flex requirement is due to the input shapes. The input shape can be fixed by (1) modifying the original source graph or (2) using TFLite converter V1 API's input_shapes argument https://www.tensorflow.org/api_docs/python/tf/compat/v1/lite/TFLiteConverter

**Comment by nehasoni3** [comment] 2020-12-27 09:57
@abattery Now, FlexMUL is removed but FlexAddV2 op is still there. Will you guide me to remove that FlexAddV2 op?

**Comment by abattery** [comment] 2020-12-28 04:00
The same strategy can be applied to FlexAddV2 ops. Fixing the input shape of the FlexAddV2 ops can help replacing them with TFLite Add ops.

**Closed** 2021-01-08 17:51 UTC
Labels: TF 2.3, TFLiteConverter, comp:lite, stat:awaiting response, type:bug
