### ISSUE TITLE
'tensorflow/contrib/reduce_slice_ops/_objs/python/ops/_reduce_slice_ops_gpu/tensorflow/contrib/reduce_slice_ops/kernels/reduce_slice_ops_gpu.cu.pic.o' was not created

### ISSUE THREAD

**Issue by Avinash01111992** [tensorflow/tensorflow#15573] opened 2017-12-22 06:40 UTC
Hi i'm running the tensorflow from the source and after building the tensorflow using bazel using below command 

**bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package** 

**The error message pasted below**

10 errors detected in the compilation of "/home/lb/.cache/bazel/_bazel_lb/144f5944ef8ff562c57e67fdaa41565f/execroot/org_tensorflow/tmpae8_5f0170552fd082f4/tmpxft_0000245c_00000000-6_reduce_slice_ops_gpu.cu.cpp1.ii".
ERROR: /home/lb/WorkSpace/AI-WORK/tensorflow/tensorflow/contrib/reduce_slice_ops/BUILD:14:1: output 'tensorflow/contrib/reduce_slice_ops/_objs/python/ops/_reduce_slice_ops_gpu/tensorflow/contrib/reduce_slice_ops/kernels/reduce_slice_ops_gpu.cu.pic.o' was not created
ERROR: /home/lb/WorkSpace/AI-WORK/tensorflow/tensorflow/contrib/reduce_slice_ops/BUILD:14:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 74.030s, Critical Path: 8.38s
FAILED: Build did NOT complete successfully

**Comment by gorogm** [comment] 2017-12-22 06:45
Don't you have other error messages above those? Can you post them as well?

**Comment by Avinash01111992** [comment] 2017-12-22 06:52
No i only have this much 
and i'm using 
CUDA 9.1 with GCC 5.4 version

**Comment by gorogm** [comment] 2017-12-22 06:55
Even the posted error message mentions '10 errors', try to find them :) I had today 10 errors as well, that was with Eigen...

**Comment by Avinash01111992** [comment] 2017-12-22 08:30
ERROR: /home/lb/WorkSpace/AI-WORK/tensorflow/tensorflow/contrib/rnn/BUILD:218:1: error while parsing .d file: /home/lb/.cache/bazel/_bazel_lb/144f5944ef8ff562c57e67fdaa41565f/execroot/org_tensorflow/bazel-out/k8-py3-opt/bin/tensorflow/contrib/rnn/_objs/python/ops/_lstm_ops_gpu/tensorflow/contrib/rnn/kernels/lstm_ops_gpu.cu.pic.d (No such file or directory)
In file included from external/eigen_archive/unsupported/Eigen/CXX11/Tensor:14:0,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/contrib/rnn/kernels/lstm_ops.h:19,
                 from tensorflow/contrib/rnn/kernels/lstm_ops_gpu.cu.cc:20:
external/eigen_archive/unsupported/Eigen/CXX11/../../../Eigen/Core:59:34: fatal error: math_functions.hpp: No such file or directory
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1804.018s, Critical Path: 117.24s
FAILED: Build did NOT complete successfully

**Comment by Avinash01111992** [comment] 2017-12-22 08:31
How to resolve this even i'm getting the same error with Eigen

**Comment by gorogm** [comment] 2017-12-22 08:37
Check these @Avinash01111992, a symlink will solve it:
https://github.com/tensorflow/tensorflow/issues/15389
https://stackoverflow.com/a/47807106

**Comment by Avinash01111992** [comment] 2017-12-22 09:17
INFO: From Compiling tensorflow/core/kernels/bincount_op_gpu.cu.cc:
./tensorflow/core/util/cuda_kernel_helper.h(116): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(116): error: expected a ")"

./tensorflow/core/util/cuda_kernel_helper.h(117): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(120): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(120): error: expected a ";"

./tensorflow/core/util/cuda_kernel_helper.h(126): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(126): error: expected a ")"

./tensorflow/core/util/cuda_kernel_helper.h(127): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(130): error: namespace "Eigen::half_impl" has no member "__half_raw"

./tensorflow/core/util/cuda_kernel_helper.h(130): error: expected a ";"

10 errors detected in the compilation of "/home/lb/.cache/bazel/_bazel_lb/144f5944ef8ff562c57e67fdaa41565f/execroot/org_tensorflow/tmp557_797e0d9b2e6c8ac1/tmpxft_0000709d_00000000-6_bincount_op_gpu.cu.cpp1.ii".
ERROR: /home/lb/WorkSpace/AI-WORK/tensorflow/tensorflow/core/kernels/BUILD:3236:1: output 'tensorflow/core/kernels/_objs/bincount_op_gpu/tensorflow/core/kernels/bincount_op_gpu.cu.pic.o' was not created
ERROR: /home/lb/WorkSpace/AI-WORK/tensorflow/tensorflow/core/kernels/BUILD:3236:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 688.604s, Critical Path: 79.75s
FAILED: Build did NOT complete successfully

**Comment by Avinash01111992** [comment] 2017-12-22 10:16
@gorogm  HI i did this Symlink stuff still i'm facing the same issue

**Comment by gorogm** [comment] 2017-12-22 10:33
If your message is still
`math_functions.hpp: No such file or directory`
than work a bit more on the symlink.

For the solution of Eigen::half_impls I'm afraid we have to wait a bit, I found a github-issue for this as well some hours ago:
https://github.com/tensorflow/tensorflow/issues/15108

**Comment by Avinash01111992** [comment] 2017-12-22 10:39
I done with symlink 

**ln: failed to create symbolic link '/usr/local/cuda/include/math_functions.hpp': File exists**

So still issue is exits for you also ?
IS this github-issues ?

**Comment by Avinash01111992** [comment] 2017-12-22 11:45
@gorogm  did you got the solution for  Eigen

**Comment by gorogm** [comment] 2017-12-22 12:00
@Avinash01111992 I'm using an older commit, which works.

**Comment by Avinash01111992** [comment] 2017-12-22 12:03
@gorogm  Ok thanks , I'll try with older commit and will let you know if i get any issues and please do intimate me if this issue resolved in master branch.

**Comment by gorogm** [comment] 2017-12-22 12:10
@Avinash01111992 I'll try my best, however I'm not a developer of tensorflow, just an other user :) So I won't have any private information, I can only suggest you to subscribe to the mentioned issues, and you'll be notified there. Have a nice day!

**Comment by Avinash01111992** [comment] 2017-12-22 13:06
@gorogm  Hi , After checkout with previous branch i'm getting the below error  

ERROR: /home/lb/ai@work/tensorflow/tensorflow/contrib/verbs/BUILD:60:1: C++ compilation of rule '//tensorflow/contrib/verbs:grpc_verbs_service' failed (Exit 1)
In file included from ./tensorflow/contrib/verbs/rdma_mgr.h:24:0,
                 from ./tensorflow/contrib/verbs/grpc_verbs_service.h:22,
                 from tensorflow/contrib/verbs/grpc_verbs_service.cc:22:
./tensorflow/contrib/verbs/rdma.h:21:30: fatal error: infiniband/verbs.h: No such file or directory
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1615.770s, Critical Path: 93.59s
FAILED: Build did NOT complete successfully


**Do you have any idea on this error ?**
Thanks and have a nice day

**Comment by jart** [comment] 2017-12-22 20:05
This this sounds like a duplicate of the aforementioned issue. Please click subscribe on that and thank you for helping our friend @gorogm.

**Closed by jart** 2017-12-22 20:05 UTC
