### ISSUE TITLE
why the pb model(saved by keras API) structure is so complicated？

### ISSUE THREAD

**Issue by SpongeBob-222** [tensorflow/tensorflow#39699] opened 2020-05-20 03:57 UTC
Hi, I use keras API to save my model in pb format, but the model structure is so complicated!
![image](https://user-images.githubusercontent.com/11664658/82403250-f84d3900-9a90-11ea-92ad-5d2965c16328.png)

On the contrary, if I save the model in h5 format, the model structure is very simple, which is exactly what I want.
![image](https://user-images.githubusercontent.com/11664658/82403218-e4a1d280-9a90-11ea-8590-95befec014d1.png)

what is the reason, and how can I get a simple model in pb format?

**Comment by ymodak** [comment] 2020-05-21 23:39
Please provide a reproducible code to investigate. Thanks!

**Comment by SpongeBob-222** [comment] 2020-05-25 01:45
```
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

def get_model():
    model = tf.keras.Sequential()
    # Adds a densely-connected layer with 64 units to the model:
    model.add(layers.Dense(64, activation='relu'))
    # Add another:
    model.add(layers.Dense(64, activation='relu'))
    # Add an output layer with 10 output units:
    model.add(layers.Dense(10))
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

model = get_model()

test_input = np.random.random((128,32))
test_target = np.random.random((128, 1))
model.fit(test_input, test_target)

# Save model in h5 format
model.save('./model.h5')
# Save model in pb format
model.save('./model_pb')
```

My python script is based on [Keras Overview](https://www.tensorflow.org/guide/keras/overview), 
 tensorflow version is 2.2.0, and platform is Ubuntu 18.04.

**Comment by SpongeBob-222** [comment] 2020-05-26 06:00
> Please provide a reproducible code to investigate. Thanks!

Hi, My code is here.

```
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

def get_model():
    model = tf.keras.Sequential()
    # Adds a densely-connected layer with 64 units to the model:
    model.add(layers.Dense(64, activation='relu'))
    # Add another:
    model.add(layers.Dense(64, activation='relu'))
    # Add an output layer with 10 output units:
    model.add(layers.Dense(10))
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

model = get_model()

test_input = np.random.random((128,32))
test_target = np.random.random((128, 1))
model.fit(test_input, test_target)

# Save model in h5 format
model.save('./model.h5')
# Save model in pb format
model.save('./model_pb')
```

My python script is based on Keras Overview,
tensorflow version is 2.2.0, and platform is Ubuntu 18.04.

**Comment by SpongeBob-222** [comment] 2020-05-26 06:01
@ymodak

**Comment by ymodak** [comment] 2020-05-28 23:26
This is caused due to the tool you are using to visualize the h5 and pb files.
There are two kinds of graph representations : op-level graph and conceptual graph.
In your case, the h5 visuals depict conceptual graph where as the pb visuals show op-level graph.
You may try using tensorboard to visualize your model.
By default it displays op level graph.
See https://www.tensorflow.org/tensorboard/graphs#op-level_graph
Thanks!

**Comment by SpongeBob-222** [comment] 2020-05-29 02:43
@ymodak 

In fact, I use Netron to visualize the model, and I will try it later using Tensorboard, thanks a lot!

**Comment by ymodak** [comment] 2020-06-14 19:56
Closing this issue for now. Feel free to reopen if necessary. Thanks!

**Closed by ymodak** 2020-06-14 19:56 UTC
Labels: comp:apis, stat:awaiting response, type:others
