### ISSUE TITLE
tf.data.Dataset run after loading  whole data without using shuffle method

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/tensorflow#22446] opened 2018-09-21 12:21 UTC
Does have any method to load sub of data then running model, without using `shuffle`,  I want the data order not changed.

**Comment by ymodak** [comment] 2018-09-21 16:41
@zh794390558 Please correct me if I am wrong: You are looking to run your model on a subset of whole data and not the whole dataset. Am I right?

**Comment by feihugis** [comment] 2018-09-23 07:50
@zh794390558  Will [tf.data.Dataset.list_files](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#list_files) work for your case? You can specify a file_pattern for the data subset.

**Comment by zh794390558** [comment] 2018-09-26 14:20
@ymodak  when is using dataset api without `shuflle`, tf will load all data into memory, then do own processing. If using `shuffle`, then tf will load `buffer_size` data into memory and do processing, but will shuffle the dataset. I want a interface and load `buffer_size` data into memory and do processing order by oder.

**Comment by feihugis** [comment] 2018-09-28 17:13
@zh794390558 There is a [PR](https://github.com/tensorflow/tensorflow/pull/22429) to avoid load all data into memory.

**Comment by zh794390558** [comment] 2018-10-01 02:15
@feihugis The issue is not same to me, I using tf.data.Dataset.from_generate to load data.

**Comment by feihugis** [comment] 2018-10-08 18:18
@zh794390558 Could you put your code here for reproducing the problem?

**Comment by ymodak** [comment] 2018-10-15 19:08
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-15 19:08 UTC
Labels: stat:awaiting response
