### ISSUE TITLE
Error installing Tensorflow 1.12

### ISSUE THREAD

**Issue by terminsen** [tensorflow/tensorflow#24470] opened 2018-12-20 14:47 UTC
Hi - 

I have 
- Windows 7
- Anaconda 3
- Python 3.6.5
- Tensorflow upgraded from 1.10 to 1.12 (via anaconda)
- No GPU
- CUDA toolkit 9.0 (conda installed)
- cuDNN 7.1.4 (conda installed)
- Bazel version: not installed
- Mobile device: None

All I did was updating tensorflow via anaconda: conda update tensorflow. It updated from 1.10 to 1.12:
2018-12-20 13:54:12  (rev 4)
     conda  {4.5.11 -> 4.5.12}
     tensorboard  {1.10.0 -> 1.12.0}
     tensorflow  {1.10.0 -> 1.12.0}
     tensorflow-base  {1.10.0 -> 1.12.0}
    +_tflow_select-2.1.0
    +cudatoolkit-9.0
    +cudnn-7.1.4
    +keras-applications-1.0.6
    +keras-preprocessing-1.0.5

I get the error message below when importing tensorflow into python:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     57 
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~\Anaconda3\lib\imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

~\Anaconda3\lib\imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344 

ImportError: DLL load failed: Det angivne modul blev ikke fundet.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-9b31ac0d4d77> in <module>()
      1 import pandas as pd
----> 2 import tensorflow as tf
      3 from datetime import datetime
      4 import matplotlib.pyplot as plt
      5 import numpy as np

~\Anaconda3\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 
     26 try:

~\Anaconda3\lib\site-packages\tensorflow\python\__init__.py in <module>()
     47 import numpy as np
     48 
---> 49 from tensorflow.python import pywrap_tensorflow
     50 
     51 from tensorflow.python.tools import component_api_helper

~\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75 
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\jet\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\jet\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\jet\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\jet\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\jet\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Det angivne modul blev ikke fundet.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by ymodak** [comment] 2018-12-20 19:38
Please provide following information. Thanks!
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:



**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**


**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment] 2018-12-26 17:47
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by terminsen** [comment] 2018-12-27 09:16
Hi - 

I already updated my question with additional information you requested. So, hope that you will take a look at my question again, please. 

Thanks.

**Comment by ymodak** [comment] 2018-12-27 18:48
Can you try following and confirm if that works for you?
conda install -c conda-forge tensorflow

**Comment by terminsen** [comment] 2018-12-27 19:30
I tried to run that line of code ... conda install -c conda-forge tensorflow

Python was able to import tensorflow (now 1.10):

2018-12-27 20:24:47  (rev 25)
     certifi  {2018.4.16 -> 2018.4.16 (conda-forge)}
     conda  {4.5.12 -> 4.5.12 (conda-forge)}
     tensorboard  {1.12.0 -> 1.10.0 (conda-forge)}
     tensorflow  {1.12.0 -> 1.10.0 (conda-forge)}

But I now got the following traceback;

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-5-94dcbe54bc91> in <module>()
     10 
     11 layers = [tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
---> 12           for layer in range(n_layers)]
     13 multi_layer_cell = tf.contrib.rnn.MultiRNNCell(layers)
     14 rnn_outputs, states = tf.nn.dynamic_rnn(multi_layer_cell, X, dtype=tf.float32)

<ipython-input-5-94dcbe54bc91> in <listcomp>(.0)
     10 
     11 layers = [tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
---> 12           for layer in range(n_layers)]
     13 multi_layer_cell = tf.contrib.rnn.MultiRNNCell(layers)
     14 rnn_outputs, states = tf.nn.dynamic_rnn(multi_layer_cell, X, dtype=tf.float32)

~\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in __getattr__(self, item)
     51 
     52   def __getattr__(self, item):
---> 53     module = self._load()
     54     return getattr(module, item)
     55 

~\Anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py in _load(self)
     40   def _load(self):
     41     # Import the target module and insert it into the parent's namespace
---> 42     module = importlib.import_module(self.__name__)
     43     self._parent_module_globals[self._local_name] = module
     44 

~\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

~\Anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\Anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\Anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\Anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

~\Anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\Anaconda3\lib\site-packages\tensorflow\contrib\__init__.py in <module>()
     29   from tensorflow.contrib import cloud
     30 from tensorflow.contrib import cluster_resolver
---> 31 from tensorflow.contrib import coder
     32 from tensorflow.contrib import compiler
     33 from tensorflow.contrib import constrained_optimization

~\Anaconda3\lib\site-packages\tensorflow\contrib\coder\__init__.py in <module>()
     20 
     21 # pylint: disable=wildcard-import
---> 22 from tensorflow.contrib.coder.python.layers.entropybottleneck import *
     23 from tensorflow.contrib.coder.python.ops.coder_ops import *
     24 # pylint: enable=wildcard-import

~\Anaconda3\lib\site-packages\tensorflow\contrib\coder\python\layers\entropybottleneck.py in <module>()
     22 import numpy as np
     23 
---> 24 from tensorflow.contrib.coder.python.ops import coder_ops
     25 
     26 from tensorflow.python.eager import context

~\Anaconda3\lib\site-packages\tensorflow\contrib\coder\python\ops\coder_ops.py in <module>()
     28 
     29 _coder_ops = loader.load_op_library(
---> 30     resource_loader.get_path_to_datafile("_coder_ops.so"))

~\Anaconda3\lib\site-packages\tensorflow\contrib\util\loader.py in load_op_library(path)
     54       return None
     55   path = resource_loader.get_path_to_datafile(path)
---> 56   ret = load_library.load_op_library(path)
     57   assert ret, 'Could not load %s' % path
     58   return ret

~\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py in load_op_library(library_filename)
     54     RuntimeError: when unable to load the library or get the python wrappers.
     55   """
---> 56   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     57 
     58   op_list_str = py_tf.TF_GetOpList(lib_handle)

NotFoundError: C:\Users\jet\Anaconda3\lib\site-packages\tensorflow\contrib\coder\python\ops\_coder_ops.so not found

**Comment by ymodak** [comment] 2019-02-04 23:05
Apologies for the delay in response. Is this still an issue for you? Can you please the minimal code snippet to reproduce the error message? Thanks!

**Comment by ymodak** [comment] 2019-02-08 01:01
Closing this issue since original installation error is resolved. Please post a new issue if running into bug/performance issue and provide all the info. asked by the template. Thanks!

**Closed by ymodak** 2019-02-08 01:01 UTC
Labels: stat:awaiting response, type:build/install

**Comment by vanshmohale** [comment] 2019-03-01 05:14
I'm also receiving the same error.
I've installed tensorflow as per [these](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md) instructions and when I try to run

`python object_detection/builders/model_builder_test.py`

I am receiving the following error along with this message box:
![screenshot 7](https://user-images.githubusercontent.com/28893609/53617708-6ac4c580-3c0e-11e9-9622-0fd11e98635b.png)


______________________________________
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\765349\Downloads\models\research\object_detection\builders\model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "C:\Users\765349\Downloads\models\research\object_detection\builders\box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "C:\Users\765349\Downloads\models\research\object_detection\predictors\convolutional_box_predictor.py", line 22, in <module>
    slim = tf.contrib.slim
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\contrib\__init__.py", line 31, in <module>
    from tensorflow.contrib import coder
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\contrib\coder\__init__.py", line 22, in <module>
    from tensorflow.contrib.coder.python.layers.entropybottleneck import *
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\contrib\coder\python\layers\entropybottleneck.py", line 24, in <module>
    from tensorflow.contrib.coder.python.ops import coder_ops
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\contrib\coder\python\ops\coder_ops.py", line 30, in <module>
    resource_loader.get_path_to_datafile("_coder_ops.so"))
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\contrib\util\loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\framework\load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\765349\AppData\Local\conda\conda\envs\tensorflow_cpu\lib\site-packages\tensorflow\contrib\coder\python\ops\_coder_ops.so not found
_______________________________________

And I tried to check that directory and _coder_ops.so was present there.
