### ISSUE TITLE
Building TensorFlow for iOS failed on macOS Sierra and xCode 8.0

### ISSUE THREAD

**Issue by derekshi** [tensorflow/tensorflow#4640] opened 2016-09-28 22:13 UTC
When running `compile_ios_protobuf.sh`, it says: 
checking whether we are cross compiling... configure: error: in '.../tensorflow/tensorflow/contrib/makefile/downloads/protobuf':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See`config.log' for more details

**Comment by concretevitamin** [comment] 2016-09-28 22:51
@satok16 - can you take a look?  Thanks.

**Comment by satok16** [comment] 2016-09-28 22:59
Ok, first of all, I need to find a mac running Sierra.

**Comment by concretevitamin** [comment] 2016-09-28 23:26
TensorFlow doesn't officially support Sierra, I think.  Marking this as contributions welcome.

**Comment by derekshi** [comment] 2016-09-29 03:18
I think it's not about running on Sierra. It's built on Sierra but running for iOS.

**Comment by derekshi** [comment] 2016-09-29 06:24
Actually I can run tensorflow on Sierra using python api without any issues.

**Comment by tomx** [comment] 2016-09-29 08:50
Same issue here. Been trying all sorts of things to no avail.

**Comment by alphamule** [comment] 2016-09-29 16:36
Here are some more details from config.log:

```
configure:3937: checking whether we are cross compiling
configure:3945: gcc -o conftest -DNDEBUG -g -O0 -pipe -fPIC -fcxx-exceptions -mios-simulator-version-min=9.2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk  -arch x86_64 -mios-simulator-version-min=9.2 -stdlib=libc++ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/usr/lib/system conftest.c -lc++ -lc++abi >&5
configure:3949: $? = 0
configure:3956: ./conftest
dyld: mach-o, but built for simulator (not macOS)
./configure: line 3958: 56606 Abort trap: 6           ./conftest$ac_cv_exeext
configure:3960: $? = 134
configure:3967: error: in `/Users/eric/Code/tensorflow/tensorflow/contrib/makefile/downloads/protobuf':
configure:3969: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```

**Comment by hagerty** [comment] 2016-09-29 21:44
I have the same issue.

**Comment by concretevitamin** [comment] 2016-09-29 22:13
Ah good point; I took off the labels.  @satok16 could you please take a look or re-assign if appropriate?  Thanks.

**Comment by arundasan91** [comment] 2016-09-29 23:50
@derekshi Are you using the latest `master` branch ? There is a lot going on regarding iOS. This might help us

**Comment by derekshi** [comment] 2016-09-30 01:25
yes, I cloned the master branch about 30 hours ago. Unless there are any changes since then.

**Comment by EvgenyVolkov** [comment] 2016-10-02 13:35
Same issue. Is there a workaround to build TensorFlow static library?

**Comment by alphamule** [comment] 2016-10-02 17:49
Downgrading to Xcode 8.0.0 -> 7.3.1 does not seem to fix it.

**Comment by tconkling** [comment] 2016-10-04 02:02
For me, at least, the `compile_ios_protobuf.sh` script is only failing when compiling for `-arch x86_64`. The other 4 targets - i386, armv7, armv7s, and arm64 - compile without an error. (So, I think this means it's not actually the iOS targets that are failing here; it's the 64-bit Mac OS version of the lib.)

**Comment by arundasan91** [comment] 2016-10-04 04:31
@derekshi, I am sorry. I am still using El Capitan in my local machine. I have access to a Sierra machine rarely here. So I tested whether the latest `master` is working properly with El Capitan.

Currently, I have a working environment with XCode8 in El Capitan and can successfully build and run both Simple and Camera examples. Works fine with iOS 10 as well. The branch is a few weeks old and I modified some files a bit. I see that all changes I made are reflected on the master branch so the changes I made shouldn't be a problem.

I downloaded the latest `master` branch today and the only file I see a change is the `download_dependencies.sh`. The bazel link was broken a few weeks back. So what I did is to use the bazel version inside `tensoflow/workspace.bzl` file and hardcoded it in the `download_dependencies.sh` script. However, I now see that the latest `master` corrected the bazel issues. I compiled the latest `master` on El Capitan now and verified the working with Simple example from ios_examples folder. The simulation works as expected.

So this might be an OS Version dependent issue itself. As @tconkling mentioned, the script is failing only for `x86_64` for him. I will get hold of a Sierra machine and will look into this in the coming days. I am sure that the TensorFlow members are looking into this as well.

**Comment by alphamule** [comment] 2016-10-04 23:04
As a temporary workaround, if you comment out the X86_64 bits in the build scripts, you can still build the protobuf and tensorflow libraries.  The resultant libraries will work on-device, but attempts to run in the simulator will fail.

https://github.com/alphamule/tensorflow/commit/672da4fef637c5511fd2cf78a4ac8e710d0efbda

**Comment by jiny2001** [comment] 2016-10-07 05:52
Hi alphamule,
Could you give me more detail like which file should be changed and which line to be masked?

**Comment by tachim** [comment] 2016-10-07 18:20
@alphamule thanks, that worked for me. @jiny2001 you want to modify ./tensorflow/contrib/makefile/compile_ios_protobuf.sh. Comment out the block that includes line 106  and then the lines containing `${LIBDIR}/iossim_x86_64/lib/libprotobuf.a` at the bottom (in the `lipo` invocations).

**Comment by alphamule** [comment] 2016-10-07 18:57
You must also make similar changes to ```tensorflow/contrib/makefile/compile_ios_tensorflow.sh``` to avoid building the X86_64 library and then also to avoid linking into the final artifact.

This is perhaps an easier split view of the necessary work-around changes:

https://github.com/alphamule/tensorflow/commit/672da4fef637c5511fd2cf78a4ac8e710d0efbda?diff=split

@arundasan91 I am also of the opinion that this is an OS issue.  My best guess is that, in the upgrade to Sierra, now when you link against the ios simulator libraries (sorry if this is the wrong nomenclature---I'm new to iOS dev) the resulting binary is not executable, whereas I presume it was in El Cap.  Even using old simulator versions does not fix the problem.  When I compile the same test binary as ```./configure``` but don't use the simulator for ```-isysroot```, the binary runs fine.

The only links to the mach-o error message from ```config.log``` I could find are:

https://curl.haxx.se/mail/lib-2016-09/0079.html
http://stack1.ocim.top/39762289/issue-with-executing-a-out-file-c-macos-sierra-10-12-1.html
http://stackoverflow.com/questions/39762289/issue-with-executing-a-out-file-c-macos-sierra-10-12-1

But none seem to have satisfactory answers here.

**Comment by jiny2001** [comment] 2016-10-07 22:34
Thank you so much @tachim and @alphamule !
Following those changes I could go advance.

**Comment by usamaoDATA** [comment] 2016-10-11 05:05
hi @jiny2001 can you or somebody please me more specific as to exactly which lines im suppose to comment. i've been stuck in this problem for a while now. any help would be appreciated

**Comment by usamaoDATA** [comment] 2016-10-11 06:36
okay, i found that link, sorry, noob mistake. building now

**Comment by usamaoDATA** [comment] 2016-10-11 07:21
i did the changes to the code, my build ended with 

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...

**Comment by alphamule** [comment] 2016-10-11 11:43
@usamaoDATA 

I'm going to guess that you tried to comment out the lines in the lipo commands.  You must delete those lines instead.  The problem is that the lipo command is multi-line:

```
lipo \
  ${LIBDIR}/iossim_386/lib/libprotobuf-lite.a \
  # ${LIBDIR}/iossim_x86_64/lib/libprotobuf-lite.a \
  ${LIBDIR}/ios_arm7/lib/libprotobuf-lite.a \
  ${LIBDIR}/ios_arm7s/lib/libprotobuf-lite.a \
  ${LIBDIR}/ios_arm64/lib/libprotobuf-lite.a \
  -create \
  -output ${LIBDIR}/libprotobuf-lite.a
```

so if you comment out a line in the middle, the ```\``` characters at the end cause all these lines to be considered one, so it ends up being interpreted as:

```lipo ${LIBDIR}/iossim_386/lib/libprotobuf-lite.a # ${LIBDIR}/iossim_x86_64/lib/libprotobuf-lite.a ${LIBDIR}/ios_arm7/lib/libprotobuf-lite.a ${LIBDIR}/ios_arm7s/lib/libprotobuf-lite.a ${LIBDIR}/ios_arm64/lib/libprotobuf-lite.a -create -output ${LIBDIR}/libprotobuf-lite.a```

which means the trailing command line arguments are considered commented out as well, so you get the error you saw about missing required options.

So, just delete those lines instead & it should work.

**Comment by kduy** [comment] 2016-10-14 09:40
hi guys, I follow @alphamule's guide, however, i got another error:

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: one of -create, -thin <arch_type>, -extract <arch_type>, -remove <arch_type>, -replace <arch_type> <file_name>, -verify_arch <arch_type> ... , -info or -detailed_info must be specified

fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo [input_file] ... [-arch <arch_type> input_file] ... [-info] [-detailed_info] [-output output_file] [-create] [-arch_blank <arch_type>] [-thin <arch_type>] [-remove <arch_type>] ... [-extract <arch_type>] ... [-extract_family <arch_type>] ... [-verify_arch <arch_type> ...] [-replace <arch_type> <file_name>] ...
```
Do you have any idea? Thank you.

**Comment by alphamule** [comment] 2016-10-14 12:07
This is the same error as @usamaoDATA and I described the solution in the response just before yours.  Make sure that you are deleting the lines for the lipo commands and not just commenting them out.

**Comment by kduy** [comment] 2016-10-14 12:36
@alphamule : thank you. I really did so as  alphamule@672da4f?diff=split . Perhaps my xcode cause the errror

**Comment by alphamule** [comment] 2016-10-14 14:30
Yeah, it's not Xcode, as you're still on the step before you can use Xcode (building the libraries).

Did you maybe misinterpret the deleted lines as empty lines?

It needs to look like this:

```
lipo \
${LIBDIR}/iossim_386/lib/libprotobuf-lite.a \
${LIBDIR}/ios_arm7/lib/libprotobuf-lite.a \
${LIBDIR}/ios_arm7s/lib/libprotobuf-lite.a \
${LIBDIR}/ios_arm64/lib/libprotobuf-lite.a \
-create \
-output ${LIBDIR}/libprotobuf-lite.a
```

not

```
lipo \
${LIBDIR}/iossim_386/lib/libprotobuf-lite.a \

${LIBDIR}/ios_arm7/lib/libprotobuf-lite.a \
${LIBDIR}/ios_arm7s/lib/libprotobuf-lite.a \
${LIBDIR}/ios_arm64/lib/libprotobuf-lite.a \
-create \
-output ${LIBDIR}/libprotobuf-lite.a
```

Or else, maybe did you remove one of those trailing backslashes?

From your error logs, I can tell that you are running the command:

```
+ lipo /Users/kduy/temp/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/iossim_386/lib/libprotobuf.a
```

which means that the second half of the command is getting cut off.

**Comment by kduy** [comment] 2016-10-14 18:02
Thank you so much, @alphamule . It's my bad, i left one of the empty line in between.

**Comment by usamaoDATA** [comment] 2016-10-16 18:21
@alphamule yes i deleted those lines and i still got that error, i googled it and apparently you have to enable a setting in Xcode build settings to only build the current architecture. and then the build completed successfully. i dont know if this was a fluke or some other random error. but i was very skeptical as the build settings are only edited for the current project opened in xcode. but never the less it worked and i was able to get the the app running for my custom model i created on my ipad mini 2 running ios 9.3.3. on my iphone 4s running 9.3.5 and a friends iphone 6s running iOS10
im still very new to this so please forgive me if i made some wrong assumptions

**Comment by alphamule** [comment] 2016-10-16 20:52
This makes sense, as we cut out the simulator architecture when building the library.  If you tried to build your app against the library for the simulator architecture, then it will fail.  I believe that, by default, Xcode won't build for all architectures, but it will if you switch your scheme's build configuration to be release rather than debug (at least that's how it was in my Xcode).

**Comment by clo-dan** [comment] 2016-10-17 17:28
Any progress on this issue? Workaround works but I can no longer build for the Simulator, where I test screen sizes for devices I don't have.

**Comment by levelvc** [comment] 2016-10-19 22:15
@arundasan91 any update on building this properly for `x86_64` on Sierra and Xcode 8?

**Comment by arundasan91** [comment] 2016-10-19 22:22
@levelvc , No, Sorry. I did not get my hands on one. My local machine in lab is still El Capitan and I haven't updated yet because of the issues.

I just asked a friend of mine for his machine. I might be able to update back in a few hours.

**Comment by arundasan91** [comment] 2016-10-20 02:18
I ran into some errors in my friends' machine. Had little time to debug. Will look into it hopefully by the end of this week. I was in a hurry so just told him to copy the log and send it over to me.
Take a look: [error](http://pastebin.com/re6WUua5).    

I did download all the dependencies. This might be an issue with his system though. Sorry for being less of an help guys.

**Comment by KevinAyuque** [comment] 2016-10-26 19:37
Thanks, I'm also having this error but the workaround fixes it for me

**Comment by clo-dan** [comment] 2016-10-26 19:41
@KevinAyuque The workaround lets you run on a device but you can't do anything with a simulator. @arundasan91 any update?

**Comment by levelvc** [comment] 2016-10-26 20:07
We were able to build on Sierra without arm64 architecture but for production we ended up building on El Capitain.

**Comment by ratzinho87** [comment] 2016-10-27 08:29
@arundasan91 That error is different and it's caused by missing libtool. Running `brew install libtool` should fix it.
If you are working on a fresh machine, you should also have automake and xcode command line tools installed (I recently ran into these problems).

I am also seeing the original error on Sierra and the config.log from my machine says this:

> 
configure:3937: checking whether we are cross compiling
configure:3945: gcc -o conftest -DNDEBUG -Os -pipe -fPIC -fno-exceptions -mios-simulator-version-min=8.2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk  -arch x86_64 -mios-simulator-version-min=8.2 -stdlib=libc++ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/usr/lib/ -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk/usr/lib/system conftest.c -lc++ -lc++abi >&5
configure:3949: $? = 0
configure:3956: ./conftest
dyld: mach-o, but built for simulator (not macOS)
./configure: line 3958: 79140 Abort trap: 6           ./conftest$ac_cv_exeext
configure:3960: $? = 134
configure:3967: error: in '/Users/sorinlumezeanu/_root/work/cvsl/WorkPhotos/tensorflow/tensorflow/contrib/makefile/downloads/protobuf':
configure:3969: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details


[Here](http://pastebin.com/Gmr79pQk) is the full config.log file.

**Comment by hagerty** [comment] 2016-10-30 18:58
The solution that @alphamule posted worked for me.

**Comment by poongd** [comment] 2016-11-11 10:08
@alphamule `s solution is work for me too.

**Comment by alphamule** [comment] 2016-11-19 23:56
With @Gubarev 's commit, it looks like we now build properly in Sierra.  But, I get a weird runtime error now when I try to run the benchmark or the simple app in the simulator (I'm assuming the camera app is failing because it can't get camera input in the simulator).  Benchmark crashes with this output:

```
I tensorflow/tensorflow/contrib/ios_examples/benchmark/BenchmarkViewController.mm:198] Session created.
I tensorflow/tensorflow/contrib/ios_examples/benchmark/BenchmarkViewController.mm:201] Graph created.
I tensorflow/tensorflow/contrib/ios_examples/benchmark/BenchmarkViewController.mm:207] Creating session.
I tensorflow/core/util/stat_summarizer.cc:33] StatSummarizer found 370 nodes
F tensorflow/tensorflow/contrib/ios_examples/benchmark/../../../../tensorflow/core/lib/core/refcount.h:79] Check failed: ref_.load() == 0 (1 vs. 0)
(lldb) 
```

This is on latest master and I made sure to re-run ```tensorflow/contrib/makefile/download_dependencies.sh```

Is this happening for anyone else?

**Comment by Gubarev** [comment] 2016-11-21 13:16
@alphamule 
I just have built latest TF from scratch (c7edafccc793bf87e29aaec90db64471a7a4bb02). I have not tried example camera app, but I have tried to build and run my own app: it works both for ARM64 iOS device (iPad Air 2) and x86_64 Simulator (iPhone 5s) without problems.

**Comment by QoT** [comment] 2016-12-29 07:11
I tried all recipes above but stuck having build error:

`Making clean in .
/bin/sh: /Volumes/Macintosh: No such file or directory
make: *** [clean-recursive] Error 1
`

So, I did fix that by changing path to my Xcode not to have delimiters like spaces:

`/Volumes/Macintosh HD/Xcode 8.2.app -> /Volumes/Macintosh-HD/Xcode.app `

and now I can succesfully build:

`tensorflow/contrib/makefile/compile_ios_protobuf.sh `

**Comment by Gubarev** [comment] 2016-12-29 07:18
@QoT Seems like your XCode location is not default. Usually it is installed via AppStore into /Applications/Xcode.app

**Comment by inflation** [comment] 2016-12-30 22:08
@QoT That is a typical space issue of the path. Try to link to a path without any space or round the path in the script with quotes.

**Comment by QoT** [comment] 2016-12-31 17:35
I am iOS developer and I typically have more than one versions on my system. Usually I call them like "Xcode 7.3" or "Xcode 8.2" without any problem.

But obvious some scripts have a problem with path what I did solve by excluding spaces as I did mention.

**Comment by Shoshin23** [comment] 2017-01-17 09:41
@alphamule's suggestion ended up working for me too. Given that you would be running the camera project on device commenting out those lines wouldnt affect your work much I guess.

**Comment by nukuok** [comment] 2017-02-14 08:10
I modified the camera sample to let it run on photos and succeeded to build in x86_64 on Sierra by following workaround.

```sh
➜  makefile git:(r0.10) ✗ ln -s /usr/bin/llvm-gcc /usr/local/bin/x86_64-apple-darwin15.0.0-gcc

➜  makefile git:(r0.10) ✗ diff -u compile_ios_protobuf.sh compile_ios_protobuf.sh_bkp
diff -u compile_ios_protobuf.sh_bkp compile_ios_protobuf.sh
--- compile_ios_protobuf.sh_bkp	2017-02-14 10:57:47.000000000 +0900
+++ compile_ios_protobuf.sh	2017-02-14 15:39:18.000000000 +0900
@@ -38,7 +38,9 @@
 LIBDIR=${GENDIR}lib
 mkdir -p ${LIBDIR}
 
-OSX_VERSION=darwin14.0.0
+# OSX_VERSION=darwin14.0.0
+OSX_VERSION=darwin15.0.0
+OSX_VERSION2=darwin16.4.0
 
 IPHONEOS_PLATFORM=`xcrun --sdk iphoneos --show-sdk-platform-path`
 IPHONEOS_SYSROOT=`xcrun --sdk iphoneos --show-sdk-path`
@@ -100,7 +102,7 @@
 make distclean
 ./configure \
 --build=x86_64-apple-${OSX_VERSION} \
---host=x86_64-apple-${OSX_VERSION} \
+--host=x86_64-apple-${OSX_VERSION2} \
 --disable-shared \
 --enable-cross-compile \
 --with-protoc="${PROTOC_PATH}" \
```

Although nonsence, values were picked from
"15.0.0" => "brew info gcc; ls /usr/local/Cellar/gcc/*/bin"
"16.4.0" => "uname -r"

**Comment by skye** [comment] 2017-06-16 18:41
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Closed by skye** 2017-06-16 18:41 UTC

**Comment by DonPex** [comment] 2018-07-17 15:16
Hi,
I have the same problem executing the script _compile_ios_protobufs.sh_.

I got this error:
`Making distclean in third_party/googletest
make[1]: *** No rule to make target 'distclean'.  Stop.
make: *** [distclean-recursive] Error 1`

I am using **MacOS HighSierra 10.13.6** and the latest TensorFlow from master branch.

Does anybody have found a solution?

**Comment by loganblevins** [comment] 2018-08-29 21:54
@DonPex Try the solution by @carloscabanero on: https://gist.github.com/BennettSmith/9487468ae3375d0db0cc .

**Comment by witaly-iwanow** [comment] 2020-03-06 09:18
I've forked off Bennett's script and fixed a few things (like wrong x86_64-simulator config args, missing multi-core build, disabling archs you don't need actually works now), bumped the protobuf version to 3.7.0. I've spent two days trying to make it work on my machine (macOS 10.15.3, Xcode 11.3.1), hate protobuf more than ever. Anyways, check my script out:
https://gist.github.com/witaly-iwanow/0af44af8ff66c0df82b3cdd73a4afcf5
