### ISSUE TITLE
Unability to reach some modules (feature_column and data) with previous working code

### ISSUE THREAD

**Issue by durandg12** [tensorflow/tensorflow#32957] opened 2019-10-01 17:33 UTC
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.13.6
- TensorFlow installed from (source or binary): pip install tensorflow==2.0.0-beta1
- TensorFlow version (use command below): v2.0.0-rc2-26-g64c3d382ca 2.0.0
- Python version: v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14

**Describe the current behavior**

`from tensorflow.feature_column import numeric_column`and `from tensorflow.data import Dataset` raise `ModuleNotFoundError: No module named 'tensorflow.feature_column'`and `ModuleNotFoundError: No module named 'tensorflow.data'`.

 The workaround `from tensorflow.python.data import Dataset` works but `from tensorflow.python.feature_column import numeric_column` fails and raises `ImportError: cannot import name 'numeric_column'`. To import `numeric_column` (or other functions of the module) I have found this workaround: `from tensorflow.compat.v2.feature_column import numeric_column`.

**Comment by oanush** [comment] 2019-10-03 06:18
@durandg12 ,
Thanks for reporting the issue, Can you share a simple and standalone code to reproduce the issue?

**Comment by durandg12** [comment] 2019-10-03 06:32
The two import lines are standalone code to reproduce the issue.

**Comment by oanush** [comment] 2019-10-10 08:54
@durandg12 ,
You can try using like this 
```
from tensorflow import feature_column
feature= feature_column.numeric_column
```
and also 
```
from tensorflow import data
Data=data.Dataset
```
Thanks!

**Comment by oanush** [comment] 2019-10-16 08:47
@durandg12 ,
Any update on the issue ?Thanks!

**Comment by durandg12** [comment] 2019-10-16 09:09
Since there is no new version of TF 2.0 since I posted the issue, it is obviously still here.

As you can see in my first post, I had already found some workarounds. My workarounds even success to load `numeric_column` and `Dataset` in the namespace.

But it bothers me that I have to change all my previous codes to work around a bug.

**Comment by jvishnuvardhan** [comment] 2019-10-17 23:07
@durandg12 Can you please try this so that you don't need to change much of your old code. Another point is anything under `tf.python.*` is private, intended for development only, rather than public use. Importing from tensorflow.python or any other modules (including import tensorflow_core...) is not supported, and can break unannounced. So, it is suggested not to use anything with tf.python.*.

```
import tensorflow as tf
from tensorflow import data
Dataset = data.Dataset 

from tensorflow import feature_column
numeric_column = feature_column.numeric_column
```

**Comment by durandg12** [comment] 2019-10-18 09:49
Your piece of code works. Nonetheless it seems strange to have to define those kind of aliases at the beginning of each file.

Furthermore I don't get why my issue is not considered a bug and have the flair "type:support" instead. I mean, is it really intended that
```
import tensorflow

fc = tensorflow.feature_column.numeric_column('test')
```
works well,
```
from tensorflow import feature_column

fc = feature_column.numeric_column('test')
```
also works, but then
```
from tensorflow.feature_column import numeric_column
```
throws me `ModuleNotFoundError: No module named 'tensorflow.feature_column'`? Given that the two previous blocks of code work, I am tempted to assume that there indeed exists a module named `tensorflow.feature_column`. This result is pretty counterintuitive and unnatural. And everything worked until at least the tf2.0.0-rc0 so I don't get the change.

**Comment by mihaimaruseac** [comment] 2019-10-18 16:21
That assumption is wrong actually. Consider this example:

```console
mihaimaruseac@ankh:/tmp/py$ tree
.
└── tensorflow
    ├── __init__.py
    └── test.py
```

Where `test.py` is:

```python
class C:
  def numeric_column(self, s):
    print(s)

feature_column=C()
```

and `__init__.py` is:

```python
from test import feature_column
```

In this case:

```console
mihaimaruseac@ankh:/tmp/py$ python
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.feature_column.numeric_column('test')
test
>>> 
mihaimaruseac@ankh:/tmp/py$ python
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow import feature_column
>>> feature_column.numeric_column('test')
test
>>> 
mihaimaruseac@ankh:/tmp/py$ python
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.feature_column import numeric_column
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named feature_column
>>> 
```

Proving that the assumption is wrong.

In our case, some of the modules have names attached to them as attributes, not as other modules. This is to provide machinery for deprecation notices (in 1.x), lazy loading, virtual pip, API generation, etc. 

In fact, the only supported API usage is

```
import tensorflow as tf
tf.get.here.all.the.attributes.you.want
```

Any other API usage can break at any time and fixing it is a best effort job.

**Comment by durandg12** [comment] 2019-10-21 13:36
> In fact, the only supported API usage is
> 
> ```
> import tensorflow as tf
> tf.get.here.all.the.attributes.you.want
> ```
> 
> Any other API usage can break at any time and fixing it is a best effort job.

It is good to know, thank you. But it makes me wonder why other API usages are displayed on a lot of [tensorflow tutorials](https://www.tensorflow.org/tutorials/), e.g. [this basic one on keras](https://www.tensorflow.org/tutorials/keras/classification) or [this quickstart for advanced user](https://www.tensorflow.org/tutorials/quickstart/advanced).

Thanks also for the counterexample on my assumption about modules, I have still lot of things to learn about Python.

**Comment by amahendrakar** [comment] 2020-05-20 19:16
> ```
> from tensorflow.feature_column import numeric_column
> ```
> 
> throws me `ModuleNotFoundError: No module named 'tensorflow.feature_column'`?

@durandg12,
I was able to reproduce the error with [TF v2.0](https://colab.research.google.com/gist/amahendrakar/925cce6dd8e7c8bb568d6aa3511a9c55/32957-2-0.ipynb). However, the issue seems to be fixed with [TF v2.2](https://colab.research.google.com/gist/amahendrakar/6ae2570cee8a170c81fc88ed33318e4a/32957.ipynb).

Please check the linked Colab gist and let us know if the issue is resolved. Thanks!

**Comment by durandg12** [comment] 2020-05-28 18:24
@amahendrakar I have checked the Colab gists and the issue seems solved indeed, I have also checked that I can import `Dataset` with `from tensorflow.data import Dataset`.

I never got an answer as to why the only supported API usage would be 
```
import tensorflow as tf
tf.get.here.all.the.attributes.you.want
```
when all official tutorials and guides deviate from it.

**Comment by amahendrakar** [comment] 2020-06-02 08:01
@durandg12,
> I never got an answer as to why the only supported API usage would be

Regarding this please check @mihaimaruseac's [comment](https://github.com/tensorflow/tensorflow/issues/32957#issuecomment-543819065) in this thread and [this](https://github.com/tensorflow/tensorflow/issues/33075#issuecomment-539070546) similar query from another issue. Thanks!

**Comment by durandg12** [comment] 2020-06-02 10:33
The comments you are pointing me out do not answer why the "bad usage" of not importing from the root is widely used in official guides and tutorials, [here for example](https://www.tensorflow.org/tutorials/quickstart/advanced).

I think that keeping such inconsistencies in the guides is likely to mislead users, for no benefit.

**Comment by mihaimaruseac** [comment] 2020-06-02 15:56
There is a difference between importing from Keras/Estimator (which are separate projects included into TF) and importing from private APIs in TF.

**Closed** 2020-06-23 16:53 UTC
Labels: TF 2.0, comp:data, stalled, stat:awaiting response, type:support
