### ISSUE TITLE
Unique Error with Image Retraining Tutorial

### ISSUE THREAD

**Issue by oweingrod** [tensorflow/tensorflow#1528] opened 2016-03-16 16:26 UTC
I'm using the image retraining tutorial ([here](https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html#using-the-retrained-model)) and keep getting a very odd error. Previously, retraining, then using the graph in a slightly modified `classify.py` script was possible, but as of two days ago, I get the following error when the graph is loaded by the expression `_ = tf.import_graph_def(graph_def, name='')`:

`InvalidArgumentError: NodeDef mentions attr 'data_format' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Mul, conv/conv2d_params)
	 [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Mul, conv/conv2d_params)]]
Caused by op u'conv/Conv2D', defined at:`

I looked into the API and saw that tf.nn.conv2d has an attribute, data_format, that always defaults to None. Is there some update to Tensorflow that has caused this to be changed? Has anyone encountered an error like this, or could provide some clue as to where to look to solve it?

**Comment by mrry** [comment] 2016-03-16 16:36
This sounds like a versioning issue. Does upgrading to a nightly version of TensorFlow solve it? Assigning to @shlens in case he knows of a change to the model that could have caused this.

**Comment by oweingrod** [comment] 2016-03-16 16:37
I figured it was a versioning issue, but I was under the impression that my versions were matched. I'll try updating to a nightly. Can this be done on OSX thru pip, or do I have to install via source in Docker?

**Comment by oweingrod** [comment] 2016-03-16 16:40
Found what seems to be the offending change. 

https://github.com/tensorflow/tensorflow/commit/ee5326c99ad6e01b3b62dedb954923e11b513a83

in conv2d, there is no longer a data format operation.

@shlens , do you think this may be the cause of my error?

**Comment by shlens** [comment] 2016-03-16 16:45
I am not aware of any changes in this code base. @petewarden but might be able to comment as well.

**Comment by mrry** [comment] 2016-03-16 16:45
I think this change might be more likely to have caused the error you're seeing: https://github.com/tensorflow/tensorflow/commit/01a6f5e504d9299395888a786e52c589c16af529

If the graph for the model that you're retraining was regenerated *after* that change, and you're using TensorFlow version 0.7.1, then I'd expect to see that message. I'm not sure of the provenance of the trained model graphs though. @oweingrod: Can you confirm how you obtained the graph (i.e. which download link)? @shlens or @petewarden: Would you know if the graph had changed since the 0.7.1 release?

Here are links to the Mac OS X nightly PIP packages: [Python 2](http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=mac-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-py2-none-any.whl) / [Python 3](http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_CONTAINER_TYPE=CPU,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.7.1-py3-none-any.whl)

**Comment by oweingrod** [comment] 2016-03-16 16:53
@mrry thanks for the prompt response! I'm using the bazel built inception graph retraining as described in the tutorial I linked to in my OP (the one recently written, I believe, by @petewarden). I'm assuming that it is the case that there is a discrepancy between the version of tensorflow used by bazel to build the inception graph for retraining, and my (likely slightly more recent) build that I am using to classify?

**Comment by vrv** [comment] 2016-03-16 17:09
@shlens: did you regenerate the graph at the same time that you regenerated the checkpoint?  If so, you'll probably need to replace the graph with the old version.

**Comment by petewarden** [comment] 2016-03-16 17:15
> I'm assuming that it is the case that there is a discrepancy between the version of tensorflow used by bazel to build the inception graph for retraining, and my (likely slightly more recent) build that I am using to classify?

I believe from @mrry and @shlens comments that you should only see the message if the version used for retraining was more recent than the version that you're calling in classify_image.py. Looking at the code, the data_format attribute was added to Conv2d back on February 19th:
https://github.com/tensorflow/tensorflow/commit/898d26a1cef46c0848188e22ba4b435846649b6d

I believe the other commit mentioned is a red herring, because it only affects pooling ops. So you'd have to be running code from before February 19th in classify_image.py to run into this error I believe. Can you try printing tf.version when you run your modified classify_image.py script?

**Comment by oweingrod** [comment] 2016-03-16 17:26
@petewarden I can't seem to find `tf.version` in the API, and when I attempt to use it in python, as `print tf.version()` or `print tf.version`, I get an error. Am I going about this in the wrong way?

Again, thank you so much for your prompt responses!

**Comment by petewarden** [comment] 2016-03-16 17:31
@martinwicke can you help on the version printing?

**Comment by oweingrod** [comment] 2016-03-16 17:43
@petewarden I discovered how to print. It's tf.__version__, not tf.version.

Anywho, I'm on 0.7.1 in classify.py. Is the example running on a different version?

**Comment by vrv** [comment] 2016-03-16 18:34
I have a feeling the example was regenerated by accident using a newer version of TF that introduced new attributes.  If we used the old graph but a new checkpoint, I think things would work.

**Comment by oweingrod** [comment] 2016-03-16 18:49
@vrv I think you're right. How can I go about making sure that my tensorflow versions are correctly matched? They seem to both be on 0.7.1, but maybe the graph (before retraining the final layer) is based on 0.7.0?

**Comment by oweingrod** [comment] 2016-03-16 18:50
Also, having a newer issue recently where I cannot access the "final_result:0" tensor after the graph has been retrained. TF tells me that it is not available or does not exist, but it _is_ specified as "final_result" in the `retrain.py` file. Any ideas?

**Comment by vrv** [comment] 2016-03-16 18:52
I bet the new graph was built on a version *newer* than 0.7.1.  My guess if you installed one of the pip nightlies off the main github page, you might have better luck, but we should really fix the graph.

**Comment by oweingrod** [comment] 2016-03-16 18:56
@vrv got it. So i'll update tensorflow to the absolute newest nightly, then retrain, then evaluate again on the absolute newest nightly. Fingers crossed!

**Comment by oweingrod** [comment] 2016-03-16 19:12
@vrv Looks like updating to the newest version has solved this issue—it no longer crashes on Graph creation. However, it looks like something is up with the graph creation, because I'm still unable to access "final_result:0", which is supposed to be the final inference layer. Any ideas?

**Comment by vrv** [comment] 2016-03-16 19:51
@shlens/@petewarden: deferring to you at this point, I've exhausted my knowledge of retrain.py :)

**Comment by petewarden** [comment] 2016-03-16 20:31
@oweingrod What's the exact error that you see when you run classify_image.py?

**Comment by oweingrod** [comment] 2016-03-16 20:57
@petewarden, problem has been solved. I accidentally deleted the `_ = tf.import_graph(graph, name='')` instead of commenting it. This resulted in me not being able to access the final result tensor. Thank you all so much for your help!

**Comment by petewarden** [comment] 2016-03-16 21:03
Great to hear, let us know what you end up building!

**Closed by petewarden** 2016-03-16 21:03 UTC

**Comment by mrry** [comment] 2016-03-16 21:07
@petewarden or @shlens Is there some way one of you could generate a graph that's compatible with the current release and upload it? I predict other people will run into the same issue, and telling people that they have to use the nightly isn't great....

**Comment by petewarden** [comment] 2016-03-16 21:13
The problem was that the image_retraining example (which loads in an old graph and writes out a new one) was run with a nightly build, and then later classify_image.py was run on that new graph with an older build of TensorFlow. So I don't believe this requires any changes to the graph. I'll stop by your desk to make sure I'm making sense!

**Comment by mrry** [comment] 2016-03-16 21:54
It does make sense. Thanks Pete!

**Comment by zxzhijia** [comment] 2016-06-23 03:34
@petewarden 
I run into the same problem on my computer. Do you mind to give any suggestion? I checked my tensorflow by pip show tensorflow:
---
Metadata-Version: 2.0
Name: tensorflow
Version: 0.8.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages
Requires: six, protobuf, wheel, numpy
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.7
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Software Development :: Libraries
Entry-points:
  [console_scripts]
  tensorboard = tensorflow.tensorboard.tensorboard:main

I added print tf.__version__ in my retrain_test.py code. It print out:
0.8.0

Below is the copy of my terminal:

(tensorflow)xu@xu-ThinkCentre-M72e:~/tensorflow/tensorflow/models/image/imagenet(master) $ python retrain_test.py /home/xu/Robotimages/Robot1/w/1.jpg
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
0.8.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX 750 Ti
major: 5 minor: 0 memoryClockRate (GHz) 1.2545
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.77GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0)
W tensorflow/core/kernels/batch_norm_op.cc:36] Op is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
W tensorflow/core/kernels/batch_norm_op.cc:36] Op is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
W tensorflow/core/kernels/batch_norm_op.cc:36] Op is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
E tensorflow/core/common_runtime/executor.cc:332] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float; attr=ksize:list(int),min=4; attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](pool/control_dependency)
	 [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](pool/control_dependency)]]
Traceback (most recent call last):
  File "retrain_test.py", line 25, in <module>
    {'DecodeJpeg/contents:0': image_data})
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: NodeDef mentions attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float; attr=ksize:list(int),min=4; attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](pool/control_dependency)
	 [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](pool/control_dependency)]]
Caused by op u'pool', defined at:
  File "retrain_test.py", line 18, in <module>
    _ = tf.import_graph_def(graph_def, name='')
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 240, in import_graph_def
    op_def=op_def)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()

**Comment by thammegowda** [comment] 2016-07-03 03:08
I am having the same problem. I see that the proposed solution was to use nightly build. 
I created a model using `v0.9.0` (which is built by pulling master branch today) and I am trying to use it in  a script which uses `v0.9.0` (installed by pip). 

The python source is here https://github.com/eldor4do/Tensorflow-Examples/blob/master/retraining-example.py

and full stack trace here :
<pre>
W tensorflow/core/framework/op_def_util.cc:332] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
E tensorflow/core/common_runtime/executor.cc:334] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float; attr=ksize:list(int),min=4; attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)
	 [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)]]
Traceback (most recent call last):
  File "classify.py", line 51, in <module>
    run_inference_on_image()
  File "classify.py", line 34, in run_inference_on_image
    {'DecodeJpeg/contents:0': image_data})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: NodeDef mentions attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float; attr=ksize:list(int),min=4; attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)
	 [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)]]
Caused by op u'pool', defined at:
  File "classify.py", line 51, in <module>
    run_inference_on_image()
  File "classify.py", line 28, in run_inference_on_image
    create_graph()
  File "classify.py", line 15, in create_graph
    _ = tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 274, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()
</pre>


CC @petewarden @mrry Please help!

**Comment by Waffleboy** [comment] 2016-07-08 09:20
Hi @thammegowda , Can I ask, how would I install it on ubuntu? thanks alot for your help! :)

**Comment by thammegowda** [comment] 2016-07-08 18:53
@Waffleboy Try using the same version for creating the model as well as for using the model (i.e. retrain.py and classify.py).

(Here are the scripts am I using to retrain & classify - https://github.com/thammegowda/notes/tree/master/deeplearning/imagerec, these are working fine with `v0.9.0rc0` - installed using pip on OS X )

**Comment by zxzhijia** [comment] 2016-07-08 21:29
@thammegowda I tried to use your classify.py as below: it gives me the same error:

python classify.py --in=/home/xu/Desktop/Robot/Data/a/0.jpg --model=/home/xu/Desktop/Robot/retrained_graph.pb --labels=/home/xu/Desktop/Robot/retrained_labels.txt   
W tensorflow/core/framework/op_def_util.cc:332] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
E tensorflow/core/common_runtime/executor.cc:334] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float; attr=ksize:list(int),min=4; attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)
	 [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)]]
Traceback (most recent call last):
  File "classify.py", line 81, in <module>
    run_inference(images=images, out_file=args['out'], labels=labels, model_file=args['model'])
  File "classify.py", line 35, in run_inference
    {'DecodeJpeg/contents:0': image_data})
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: NodeDef mentions attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float; attr=ksize:list(int),min=4; attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)
	 [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)]]
Caused by op u'pool', defined at:
  File "classify.py", line 81, in <module>
    run_inference(images=images, out_file=args['out'], labels=labels, model_file=args['model'])
  File "classify.py", line 20, in run_inference
    create_graph(model_file)
  File "classify.py", line 13, in create_graph
    _ = tf.import_graph_def(graph_def, name='')
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 274, in import_graph_def
    op_def=op_def)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()

**Comment by zxzhijia** [comment] 2016-07-08 21:31
@thammegowda  I trained and tested them on my linux with anaconda installed tensorflow 0.9.0.

**Comment by zxzhijia** [comment] 2016-07-08 22:07
@thammegowda  Ok, I reinstalled tensorflow 0.9.0rc0. It still shows the same error.

(tensorflow)xu@xu-Lenovo-Yoga-2-Pro:~$ pip show tensorflow
---
Metadata-Version: 2.0
Name: tensorflow
Version: 0.9.0rc0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages
Requires: numpy, six, protobuf, wheel
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.7
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Software Development :: Libraries
Entry-points:
  [console_scripts]
  tensorboard = tensorflow.tensorboard.tensorboard:main

**Comment by zxzhijia** [comment] 2016-07-09 00:36
@thammegowda Ok, it works now. I was using example files from tensorflow 0.9.0 from github. I updated it to 0.9.0rc0, now it works. Thank you.

**Comment by thammegowda** [comment] 2016-07-10 01:46
@zxzhijia I am glad you found a way to get around with this issue! Good luck
