### ISSUE TITLE
Betainc_op_test fails on ARM because one of the gradients is NaN

### ISSUE THREAD

**Issue by MattConley** [tensorflow/tensorflow#23356] opened 2018-10-29 18:34 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **no**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Linux for Tegra (Ubuntu 18.04)**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **Jetson AGX Xavier (ARM-aarch64)**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **1.11**
- Python version: **2.7**
- Bazel version (if compiling from source): **0.15.0**
- GCC/Compiler version (if compiling from source): **Linaro 7.3.0**
- CUDA/cuDNN version: **CUDA 10 cuDNN 7.3**
- GPU model and memory: **Jetson AGX Xavier, 16GB (shared with host)**

**Describe the current behavior**

The betainc_op test testBetaIncFpropAndBpropAreNeverNAN (within tensorflow/python/kernel_tests/betainc_op_test.py) fails because one of the gradient values is NaN.

**Describe the expected behavior**

The betainc_op test testBetaIncFpropAndBpropAreNeverNAN should pass, where none of the values are NaN

**Code to reproduce the issue**

Running tensorflow/python/kernel_tests/betainc_op_test.py on an ARM architecture machine should reproduce the issue.
In addition, this small python script shows the same results:

```
import tensorflow as tf
import numpy as np
from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.ops import gradients_impl
from tensorflow.python.ops import math_ops

with tf.Session() as sess:
  ga_s = [.4, .1, .2, .3]
  gb_s = [.4, .1, .2, .3]
  gx_s = [.7, .8, .9, 1.]

  ga_s_t = constant_op.constant(ga_s, dtype=dtypes.float32)
  gb_s_t = constant_op.constant(gb_s, dtype=dtypes.float32)
  gx_s_t = constant_op.constant(gx_s, dtype=dtypes.float32)
  tf_gout_t = math_ops.betainc(ga_s_t, gb_s_t, gx_s_t)
  tf_gout, grads_x = sess.run(
      [tf_gout_t,
       gradients_impl.gradients(tf_gout_t, [ga_s_t, gb_s_t, gx_s_t])[2]])

  print(np.isnan(tf_gout))
  print(np.isnan(grads_x))
  print(grads_x)

```

**Other info / logs**

This appears to be caused by one of the inputs to the betainc function being set to 1, as changing the  testBetaIncFpropAndBpropAreNeverNAN definition of space_x from
	

> space_x = np.linspace(1e-16, 1 – 1e-16).tolist()

to
	

> space_x = np.linspace(1e-16, 1 – 1e-8).tolist()

removes the NaN.

Interestingly, if the number of elements in the tensor is less than four, the gradient is returned correctly (inf instead of nan)

Here is the output of the failed test:

> FAIL: testBetaIncFpropAndBpropAreNeverNAN (__main__.BetaincTest)
> 
> Traceback (most recent call last):
>   File "tensorflow/python/kernel_tests/betainc_op_test.py", line 160, in testBetaIncFpropAndBpropAreNeverNAN
>     np.isnan(grads_x))
>   File "/home/nvidia/Tensorflow/tensorflow/tf_env2.7/local/lib/python2.7/site-packages/tensorflow/python/framework/test_util.py", line 1556, in assertAllEqual
>     np.testing.assert_array_equal(a, b, err_msg=msg)
>   File "/home/nvidia/Tensorflow/tensorflow/tf_env2.7/local/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 855, in assert_array_equal
>     verbose=verbose, header='Arrays are not equal')
>   File "/home/nvidia/Tensorflow/tensorflow/tf_env2.7/local/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
>     raise AssertionError(msg)
> AssertionError:
> Arrays are not equal
> 
> (mismatch 2.0%)
>  x: array([False, False, False, ..., False, False, False])
>  y: array([False, False, False, ..., False, False,  True])

**Comment by ymodak** [comment] 2018-11-20 23:14
Sorry for the delay in response. I was not able to reproduce your issue due to lack of hardware config. Assigning to ebrevdo, he may know more.

**Comment by ebrevdo** [comment] 2018-11-21 01:14
This is a tough one to debug because the main impl is in written in Eigen.  Looks like the issue happens when the 2nd argument is near 1, but it's hard to dig deeper than that without having proper hardware to test on.  @petewarden do we have the ability to easily run some of our python unit tests on ARM hardware?

**Comment by MattConley** [comment] 2018-11-26 20:54
Thanks for the update; sounds like it might be an Eigen issue

**Comment by MattConley** [comment] 2019-10-01 20:17
Was addressed and fixed in Eigen

**Closed** 2019-10-01 20:17 UTC
Labels: comp:ops
