### ISSUE TITLE
tf.gradients like functionality in the C and C++ API

### ISSUE THREAD

**Issue by aselle** [tensorflow/tensorflow#7044] opened 2017-01-24 19:39 UTC
Currently gradients can only be computed manually in C++ or automatically in Python with tf.gradients. Work on registering C++ implemented gradients for all the OPs has started. However, there is currently no easy way to automatically use those gradients to generate a graph. The C-api also does not have gradient creation calls yet.

This supercedes the gradient part of #476, since the rest of #476's issue was addressed.

**Comment by asimshankar** [comment] 2017-01-24 21:09
Closing this as duplicate of #6268

**Closed by asimshankar** 2017-01-24 21:09 UTC
Labels: type:feature
