### ISSUE TITLE
4x slowdown in feed_dict in tf-nightly-gpu

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#17233] opened 2018-02-23 23:46 UTC
Upgrading to `pip install tf-nightly-gpu` from `pip install tensorflow` (1.5) slows down feeding about 4x

Feeding 100MB array used to take 15ms, and it takes 60ms after the change. I think this is due to change in alignment requirements for AVX-compiled binary. I want to start the thread to figure out how to regain the performance before these changes make it into official release

benchmark: [align_feed_bug.py](https://github.com/diux-dev/cluster/blob/0edf19d919ee02273c7beb3af2ea378496a95610/yuxin_numpy/align_feed_bug.py)

```
# version: 1.5.0
python align_feed_bug.py
feed-cpu-variable   : min: 17.17, median: 19.95, mean: 19.82

# After upgrading to tf nightly
# version: 1.7.0-dev20180221
python align_feed_bug.py
feed-cpu-variable   : min: 53.97, median: 57.15, mean: 66.60
```

I've tried using @eamartin 's recipe (https://github.com/numpy/numpy/issues/5312#issuecomment-299533915) to make sure numpy array are 128-byte aligned, but that didn't make any difference in speed
```
python align_feed_bug.py --align=1
feed-cpu-variable   : min: 49.54, median: 50.50, mean: 60.06
```

cc @martinwicke

**Comment by yaroslavvb** [comment] 2018-02-24 02:57
OK, here's a hacky way of aligning an existing array. This removes the speed penalty of speed dict, and you can copy new data into existing aligned memory using `np.copyto`

```
def align_numpy(unaligned):
  sess = tf.get_default_session()
  aligned = sess.run(tf.ones(unaligned.shape, dtype=unaligned.dtype))
  np.copyto(aligned, unaligned)
  return aligned

```

**Comment by yaroslavvb** [comment] 2018-02-24 03:17
@alextp what is the algorithm to determine if existing numpy memory is aligned?

**Comment by gunan** [comment] 2018-02-24 05:01
Just to check. Does the regression also affect 1.6 RC1?

**Comment by martinwicke** [comment] 2018-02-24 05:22
Also, could this be related to the AVX build?

**Comment by eamartin** [comment] 2018-02-24 15:35
I suspect an extra memcpy is the cause. The slowdown is 45ms, and 100MB/45ms = 2.2GB/s. This is about the throughput of a memcpy that causes a lot of pagefaults.

```python
In [5]: x = np.ones(100 * 1 << 20, dtype=np.uint8)

In [6]: %time y = np.copy(x)
CPU times: user 32 ms, sys: 8 ms, total: 40 ms
Wall time: 36.9 ms
```

GIven this, I suspect the TF changes caused an additional memcpy on feed. The memcpy theory can be further tested by running the test at 200MB instead of 100MB. If slowdown roughly doubles to 90ms, strong indicator that memcpy (or at least something that touches every fed byte) is the source of slowdown.

**Comment by martinwicke** [comment] 2018-02-24 16:19
That would be consistent with an alignment mismatch forcing a copy.

**Comment by yaroslavvb** [comment] 2018-02-25 03:10
@gunan it would affect it if RC1 is built with avx

I regain the speed when using TensorFlow to allocate memory and writing my own data into that memory using `np.copyto`.

benchmark: [tf_numpy_benchmark.py](https://github.com/diux-dev/cluster/blob/41b318a5e5248b8e236c31c323be6d7777fa6133/yuxin_numpy/tf_numpy_benchmark.py)

Using 100 MB of data, times are in ms

```
python tf_numpy_benchmark.py --allocator=tf --benchmark=feed_cpu_tensor
feed_cpu_tensor               :   2.0 GB/sec, min: 50.10, median: 53.48, mean: 54.61

python tf_numpy_benchmark.py --allocator=numpy --benchmark=feed_cpu_tensor
feed_cpu_tensor               :  12.9 GB/sec, min:  7.77, median:  8.53, mean:  8.88
```

**Comment by gunan** [comment] 2018-02-25 06:40
Thank you very much for the analysis.
Since this will require some investigation, I will release 1.6 final without a fix for this, however I want to follow up on this and once we have a fix prepare patch releases for 1.5 and 1.6.
@tfboyd @tatianashp FYI

**Comment by alextp** [comment] 2018-02-26 18:07
@yaroslavvb this is the test we apply https://github.com/tensorflow/tensorflow/blob/26ae3287a12c71fccaec9ea74f55b6a51a3d33c6/tensorflow/c/c_api.cc#L197 and it hasn't changed recently so I don't know what's going on. The call site to this is in https://github.com/tensorflow/tensorflow/blob/26ae3287a12c71fccaec9ea74f55b6a51a3d33c6/tensorflow/c/c_api.cc#L197 and that hasn't changed recently either.

**Comment by yaroslavvb** [comment] 2018-02-26 18:15
@alextp I think what's going on is that `EIGEN_MAX_ALIGN_BYTES` has changed recently in `tf-nightly` due to switching to AVX build

**Comment by yaroslavvb** [comment] 2018-02-27 22:41
@alextp is there any other place that copy can happen? I'm finding that there's significant penalty in feeding read-only numpy arrays. This comes up when trying to feed data from Ray which uses read-only memory buffers

IE,
```
sess.run(some_op, feed_dict={a:arr})  # 12.6 GB/sec
arr.flags['WRITEABLE']=False
sess.run(some_op, feed_dict={a:arr})  # 1.2 GB/sec
```

[tf_numpy_benchmark.py](https://github.com/diux-dev/cluster/blob/ee5c07056a9d1dadb118aaa93e721bc81a962428/yuxin_numpy/tf_numpy_benchmark.py)

```
python tf_numpy_benchmark.py --benchmark=feed_cpu_tensor --allocator=tf --num-iters=51
feed_cpu_tensor               :  12.9 GB/sec, min:  7.75, median:  8.98, mean:  9.01

python tf_numpy_benchmark.py --benchmark=feed_cpu_tensor --allocator=tf_readonly --num-iters=51
feed_cpu_tensor               :   1.1 GB/sec, min: 88.48, median: 91.55, mean: 93.30


```

**Comment by yaroslavvb** [comment] 2018-02-28 00:26
Moving "read-only" slowness to separate issue https://github.com/tensorflow/tensorflow/issues/17315 because it's unrelated to alignment

**Comment by niklas88** [comment] 2018-03-07 13:57
I [have to](https://stackoverflow.com/q/46712934) use feed_dict for a large (> 2 GB) embedding matrix and I'm seeing a 60 fold slowdown in my Siamese CNN between Tensorflow 1.5 and 1.6 (via nvidia-docker and the official images). While a batch takes about 1 second in 1.5 it takes > 1 minute in 1.6. I strongly suspect this could also be caused by this issue. Also it seems this gets much worse with CPU load where it slows down to 3 minutes on 1.6. I can provide code and embeddings if needed.

**Comment by tatianashp** [comment] 2018-03-07 16:28
CPU slowdown has also been reported in #17383, Could you please provide data about your environment and build? Does the workaround suggested by @yaroslavvb help you?

**Comment by niklas88** [comment] 2018-03-07 17:57
@tatianashp the problem occurs on nvidia-docker with `gcr.io/tensorflow/tensorflow:1.6.0-gpu-py3` on an NVIDIA TITAN X (Maxwell and Pascal). Both inside Kubernetes as well as on the Ubuntu 16.04 LTS host + Docker CE.  Driver version is 390.25 but the same happened with an older version already (tried updating today during our investigation). As for the docker image there are almost no other dependencies (gensim + joblib) and those remain the same when changing from 1.5 to 1.6.

I have spent some time trying to get @yaroslavvb 's align_numpy_tf() hack to work but it's a bit hairy because the embeddings' size is taken into account when building the graph and at that point there is no session yet. I got it working with a hack but couldn't really see a performance difference. Still, I think that the very large NumPy array feed is a likely culprit as other models by colleagues don't show a similar degradation but also don't feed large NumPy arrays.

I can try to create a reproducer tomorrow though.

**Comment by yaroslavvb** [comment] 2018-03-07 19:28
@niklas88 GPU at low utilization while TF only uses 1 core is consistent with copy problem. memcpy of 1GB array would take 1 second and will use a single core. You could check if `align_numpy_tf` is working for you by feeding 1GB aligned array and checking if takes 1 sec vs 1ms

**Comment by niklas88** [comment] 2018-03-08 09:41
@tatianashp ok I've tried integrating @yaroslavvb 's `align_numpy_tf()` again. First I can confirm that with his `tf_numpy_benchmark.py` I definitely see the slowdown on my setup. However integrating it for my embedding doesn't significantly speed things up. I also tried running with `align_numpy_tf()` on 1.5 and it's as fast as always (1 second per epoch) but on 1.6 it remains at 1 minute per epoch. So there is still something very weird going on. I still think it's got to be related. So now I'll put together a reproducer, the code isn't too pretty but also not too large.

**Comment by niklas88** [comment] 2018-03-08 13:06
I've put together a reproducer [here](https://github.com/niklas88/tf_perf_regression) and also host the required data (see the README for instructions). This is the code with @yaroslavvb 's workaround just to make sure I've applied it correctly. If you need me to further simplify the code I can of course look into that still. *Note: I may remove the repository when this is fixed*

**Comment by yaroslavvb** [comment] 2018-03-08 16:50
@niklas88 have you isolated this problem to `feed_dict`? If `align_numpy_tf` doesn't help, it suggests that extra memcpy on feed-dict is not the problem. 

Also, just in case, you could try running this beforehand. That's an alternative way of making your numpy arrays aligned.
```
sudo apt-get install -y google-perftools
export LD_PRELOAD="/usr/lib/libtcmalloc.so.4"
```

**Comment by niklas88** [comment] 2018-03-08 17:22
@yaroslavvb so with `align_numpy_tf()` as used in my posted code I didn't see an improvement. However using  `LD_PRELOAD` does the trick and the performance returns to 1.5 levels however tcmalloc warns of `large alloc`s. 

Maybe `align_numpy_tf()` doesn't work since the embedding uses [vstack](https://github.com/niklas88/tf_perf_regression/blob/master/deep_relscorer.py#L156) or because the placeholder has an [explicit shape](https://github.com/niklas88/tf_perf_regression/blob/e7bdac70ceba120ad20820cc3f93f8e4493b1a8b/deep_relscorer.py#L702)?

**Comment by yaroslavvb** [comment] 2018-03-08 17:36
OK, it looks like your issue is also due to change in alignment requirements in TF 1.6

The reason `align_numpy_tf` didn't help is possibly because you were calling it too many times. Each time you call it, it involves a memory copy into aligned memory. The way I use it is to call it once, and then do in-place operations on the resulting array.
 
PS, you can check alignment of various allocators using this utility

```
# install ray, pytorch, then
wget -N https://raw.githubusercontent.com/diux-dev/cluster/fa98c59d07447e2b7923fde8ee294f9a054f9fbb/yuxin_numpy/tf_numpy_benchmark.py
python tf_numpy_benchmark.py --benchmark=allocator_alignment
```
it prints how many bytes you are off 64-byte alignment, ie, I see something like this with tcmalloc
```
     numpy: 0
       ray: 48
   pytorch: 0
        tf: 0
```

**Comment by niklas88** [comment] 2018-03-08 17:50
@yaroslavvb that can't be it. I only call it when I build the graph which happens exactly once in the reproducer. But it was a quick addition so I might simply have screwed up.

Im getting the following alignments (only tested tf and numpy):

     numpy: 16
     tf: 0

**Comment by tensorflowbutler** [comment] 2018-04-24 18:39
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-10 01:00
Nagging Assignee @tatianashp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-05-27 03:00
Nagging Assignee @tatianashp: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:53
Nagging Assignee @tatianashp: It has been 61 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:16
Nagging Assignee @tatianashp: It has been 76 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:07
Nagging Assignee @tatianashp: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 19:01
Nagging Assignee @tatianashp: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:04
Nagging Assignee @tatianashp: It has been 121 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:46
Nagging Assignee @tatianashp: It has been 136 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:40
Nagging Assignee @tatianashp: It has been 151 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:46
Nagging Assignee @tatianashp: It has been 166 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:46
Nagging Assignee @tatianashp: It has been 181 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-23 12:48
Nagging Assignee @tatianashp: It has been 196 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-07 19:09
Nagging Assignee @tatianashp: It has been 211 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by wt-huang** [comment] 2018-11-16 23:47
Closing as this is resolved, feel free to reopen if problem persists.

**Closed by wt-huang** 2018-11-16 23:47 UTC
Labels: type:bug/performance
