### ISSUE TITLE
Keras scikit-learn wrapper not compatible with keras functional model

### ISSUE THREAD

**Issue by karimmohraz** [tensorflow/tensorflow#34689] opened 2019-11-28 13:50 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow version (use command below): TF version: 2.0, 1.15
- Python version: 3.6 , 3.7

**Describe the current behavior**
when using a keras functional api model via the keras scikit-learn wrapper a crash occurs.
see: 
https://github.com/tensorflow/tensorflow/blob/13f2db1e7071ae109d2f51c7202867a154f587d2/tensorflow/python/keras/wrappers/scikit_learn.py#L241
**Describe the expected behavior**
model.predict() should work on all keras model types besides sequential 

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
import tensorflow.keras
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

def build_model():
  input = tf.keras.layers.Input(shape=(2,))
  pred = tf.keras.layers.Dense(2, activation='softmax')(input)
  model = tf.keras.models.Model(inputs=input, outputs=pred)
  model.compile(loss='categorical_crossentropy', metrics=['accuracy'])
  return model

X = np.array([[1,2],[3,1]])
Y = np.array([[1,0], [0,1]])
model = build_model()
model.fit(X, Y)
print(model.predict(X))  # this works

model_wrapped = KerasClassifier(build_model)
model_wrapped.fit(X, Y)
model_wrapped.predict(X)  # this crashes
```
Output: 
Train on 2 samples
2/2 [==============================] - 0s 62ms/sample - loss: 1.1024 - acc: 0.5000
[[0.62487346 0.37512657]
 [0.8205698  0.17943017]]
Train on 2 samples
2/2 [==============================] - 0s 64ms/sample - loss: 0.2733 - acc: 1.0000
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-48bacae97b80> in <module>()
     19 model_wrapped = KerasClassifier(build_model)
     20 model_wrapped.fit(X, Y)
---> 21 model_wrapped.predict(X)  # this crashes
     22 
     23 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/wrappers/scikit_learn.py in predict(self, x, **kwargs)
    239     """
    240     kwargs = self.filter_sk_params(Sequential.predict_classes, kwargs)
--> 241     classes = self.model.predict_classes(x, **kwargs)
    242     return self.classes_[classes]
    243 

AttributeError: 'Model' object has no attribute 'predict_classes'
```

**Comment by gadagashwini** [comment] 2019-11-29 09:40
Could replicate the issue with Tf 2.0 and Tf 1.15.
Please take a look at the gist for [Tf 2.0](https://colab.sandbox.google.com/gist/gadagashwini/a75cf412027db7dd67d5684a738db5bf/untitled281.ipynb) and [Tf 1.15](https://colab.sandbox.google.com/gist/gadagashwini/1a6524d0fb5fcbdee556d27792bc2f42/untitled282.ipynb). Thanks!

**Comment by rmothukuru** [comment] 2019-11-29 10:08
@karimmohraz,
As per this [Source Code](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/keras/wrappers/scikit_learn.py#L225-L242) of  `predict` method of `Keras Classifier Wrapper` for `Scikit-Learn` works only on `Keras Sequential` Model, not on `tf.keras.models.Model`. 

So, this behavior is expected.

**Comment by karimmohraz** [comment] 2019-11-29 15:07
We are aware that this is a current limitation of the implementation, but from a design standpoint this severely limits applicability for various use-cases. One major problem is that neither multiple output nor multiple input layers are supported by Keras sequential model, e.g. **BERT** or a mixture of softmax/sigmoid outputs. In our solution we also monkey-patched the functional model to support predict_classes which solves the issue. In our opinion it would make sense to either extend the functional model to support Sklearn wrapper or rewrite the Sklearn wrapper to not use predict_classes s.t. it can be used in a wider context. If required we could also submit a PR doing exactly that (if a resource constraint on your side is the reason you call this behavior as expected).

**Comment by FirefoxMetzger** [comment] 2020-03-28 16:31
I ran into the same issue; however, upon reflection, it makes sense to only support the `Sequential` model. It is always possible to wrap a functional graph into a custom Keras layer and add that to a sequential model; I've done this a while ago with residual layers, see [link](https://sebastianwallkoetter.wordpress.com/2018/04/08/layered-layers-residual-blocks-in-the-sequential-keras-api/) for an example.

This other limitation of `Sequential` vs `Model` is the number of inputs and outputs. As far as I am aware scikit learn doesn't natively support multiple inputs (not sure about outputs). I would have to write custom code to support multiple inputs on the scikit side AND on the tensorflow side to make this work. What is the desired usecase?

One bug in the `KerasClassifier` wrapper that I've noticed is that it doesn't declare `self._estimator_type = "classifier"` in the `__init__`, which makes the majority of scikit functions reject the estimator. I saw that #37201 addresses this, so I will just wait until it gets merged :)

**Comment by karimmohraz** [comment] 2020-03-30 08:43
My use case is: 
- take a pretrained keras network (e.g. https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/1) 
- add a classification layer on top for transfer learning
- use scikitlearn GridsearchCV for hyperparameter tuning

We discarded the keras scikit wrapper as we also use multihead output and a custom scorer which requires too much monkey patching.
A much simpler solution is to wrap the Bert classifier as a scikitlearn estimator which can be used by GridsearchCV.
see <script src="https://gist.github.com/karimmohraz/7dde3bfcc0786b56673461bf20cfdf5b.js"></script>

**Comment by adriangb** [comment] 2020-04-12 17:01
Hi everyone,

From discussion with the Keras team, it looks like #37201 may not be merged and instead the functionality may be made into a separate package that will be easier to maintain and have more flexibility. The wrappers would then be deprecated from Keras/TF. This is not final, but I created a PyPi package to test out the idea. Please take a look and let me know if this satisfies the use cases in this PR. Any input is welcome.
Link: https://pypi.org/project/sklearn-keras-wrap/

**Comment by shurjo042** [comment] 2020-04-26 18:43
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
 def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 100)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
when i run those code in spyder(python 3.7.7) I got an exception like:

  File "<ipython-input-2-57e958f5fe78>", line 5
    def build_classifier():
    ^
IndentationError: unexpected indent

whats is about please help me :(

**Comment by ralfmue** [comment] 2020-06-23 16:48
In Python, indentations do matter. try this:

```
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
return classifier
```

**Comment by mayer79** [comment] 2020-08-07 19:39
This Python package seems to support also the functional API: https://pypi.org/project/scikeras/

**Comment by adriangb** [comment] 2020-08-07 20:01
> This Python package seems to support also the functional API: https://pypi.org/project/scikeras/

Yep it does! It also supports subclassed models and quite a few other things.

**Comment by mayer79** [comment] 2020-08-07 20:08
Oops, it seems I missed part of above discussions. Great work, thank you!

**Comment by adriangb** [comment] 2020-08-07 21:11
I think maybe this issue can be closed @gbaned ?

**Comment by ravikyram** [comment] 2020-08-18 10:53
I have tried in colab with TF version 2.3, nightly version(`2.4.0-dev20200818`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/79b8500741d40b00e1274eddebe7a537/untitled260.ipynb).Thanks!

**Comment by rmothukuru** [comment] 2021-04-09 11:07
@karimmohraz,
Can you please confirm if we can close this issue with respect to [Adrian's comment](https://github.com/tensorflow/tensorflow/issues/34689#issuecomment-612645946)? Thanks!

**Comment by karimmohraz** [comment] 2021-04-09 12:18
you can go ahead and close this issue. We have already removed the keras scikit wrapper from our project.
We will evaluate Adrian's package in due time.

**Closed** 2021-04-09 12:27 UTC
Labels: TF 1.15, TF 2.0, comp:keras, stat:awaiting response, type:feature

**Comment by ralfmue** [comment] 2021-04-10 08:18
Ok for me, thanks

rmothukuru ***@***.***> schrieb am Fr., 9. Apr. 2021, 13:07:

**Comment by irfnt** [comment] 2021-05-31 18:30
/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_weight_boosting.py in _validate_estimator(self)
    454         if not has_fit_parameter(self.base_estimator_, "sample_weight"):
    455             raise ValueError("%s doesn't support sample_weight."
--> 456                              % self.base_estimator_.__class__.__name__)
    457 
    458     def _boost(self, iboost, X, y, sample_weight, random_state):

ValueError: KerasClassifier doesn't support sample_weight.



i am getting following error when I use neural network as a base classifier in adaboost. how we can solve this problem

**Comment by AMIRA-g-bit** [comment] 2023-09-04 15:46
Hello,
I have successfully installed tensorflow but still python showing this issue:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
ModuleNotFoundError: No module named 'tensorflow.keras.wrappers'
could any one help in this matter?
thanks!

**Comment by ArupSankarRoy** [comment] 2023-09-07 20:07
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[14], line 3
      1 import keras
      2 import tensorflow
----> 3 from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

ModuleNotFoundError: No module named 'tensorflow.keras.wrappers'
