### ISSUE TITLE
Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors

### ISSUE THREAD

**Issue by Sudhan97** [tensorflow/tensorflow#46388] opened 2021-01-13 05:50 UTC
**Description**

We converted the Matterpot Mask RCNN object detection model (using hdf5 weight file) into tflite format using tensorflow (version 2.3.0).  We are able to get the prediction in android using the version 'org.tensorflow:tensorflow-lite:2.4.0'. Inference time in android devices takes around 40 seconds using CPU (kirin 655 ). So we aiming to use the GPU support to improve inference time for our model in Android devices but the following error is raised 
`Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors`. 
We tried using batch size as 1 but the same error is raised.

We have included below link where we have shared `H5 format model, converted tflite model and text file containing keras model summary`
LINK : https://drive.google.com/drive/folders/1nTzifGDX7wXxYNXnHFw4a3Sz0p0_GdBe?usp=sharing

Is there tflite GPU support for graph with dynamic sized tensors or how can we mitigate this issue?

**We have included two images of graph visualized using graphviz**

**Comment by Sudhan97** [comment] 2021-01-15 03:10
**graph visualized using graphviz**
![model_grahviz_image_nmsv3_before_changing_rpm](https://user-images.githubusercontent.com/43716772/104676213-f6fe0a00-570c-11eb-9534-08ef628dc2d4.png)

**Comment by MarcosJNS** [comment] 2021-01-15 10:45
Hi Sudharshan,

I'm facing the same issue as I'm trying to use Mask RCNN in a TPU (RuntimeError: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors). Have you been able to find a fix?

Thanks in advance

> **Description**
> 
> We converted the Matterpot Mask RCNN object detection model (using hdf5 weight file) into tflite format using tensorflow (version 2.3.0). We are able to get the prediction in android using the version 'org.tensorflow:tensorflow-lite:2.4.0'. Inference time in android devices takes around 40 seconds using CPU (kirin 655 ). So we aiming to use the GPU support to improve inference time for our model in Android devices but the following error is raised
> `Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors`.
> We tried using batch size as 1 but the same error is raised.
> 
> We have included below link where we have shared `H5 format model, converted tflite model and text file containing keras model summary`
> LINK : https://drive.google.com/drive/folders/1nTzifGDX7wXxYNXnHFw4a3Sz0p0_GdBe?usp=sharing
> 
> Is there tflite GPU support for graph with dynamic sized tensors or how can we mitigate this issue?
> 
> **We have included two images of graph visualized using graphviz**

**Comment by srjoglekar246** [comment] 2021-01-15 22:31
I took a look at the model.
Unfortunately, atleast for now, our GPU backend doesn't support graphs with dynamic tensors. This is because the GPU delegate may not work well So I don't exactly have a 'perfect' solution to this issue, but I can share a few pointers :-)

1. Did you try multi-threaded inference? That usually speeds things up on the CPU. If you are using our Java bindings, [this option](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/java/org/tensorflow/lite/Interpreter.java#L180) can be set to 4.

2. Even then, an input size of 1024x1024 is pretty large for on-device inference. Is there any way for you to retrain it to a smaller dimension? Even bringing it down to 640-512 will help *significantly*.

3. If we were to look into removing the 'dynamic' parts of the graph (and thus enable GPU acceleration), it looks like the [NMS call](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L319) in the MaskRCNN model is causing the issues. One thing that some advanced clients have done in the past, is split a graph into the 1) Backbone/Feature extraction (all the convolution/fully-connected/math layers which have static shapes) & 2) Post-processing (which contains tricky bits like NMS)

Will this be feasible for you? I appreciate that this answer isn't the most convenient, but the size of MaskRCNN causes these issues :-). Out of curiosity, are you using the segmentation mask outputs from MaskRCNN?

**Comment by Sudhan97** [comment] 2021-01-18 04:22
@srjoglekar246 
We are using the multi-threading inference with threads set to 4. Reducing image size is not convenient for our model accuracy.also we are not using the segmentation mask output.

Is there any other known model with high accuracy similar to MaskRCNN, where we can get the object detection boxes prediction and able to get the GPU support when the model is converted to tflite?
,

**Comment by srjoglekar246** [comment] 2021-01-19 18:44
Yes. If you only need bounding boxes, look at some of the SSD ResNet models [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). You can read [these docs](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md) to figure out how to convert the models, and [this notebook](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb) for pointers on how to pass inputs & outputs to the model.

**Comment by Sudhan97** [comment] 2021-01-20 12:22
@srjoglekar246 Thank you for your response

**Comment by dagongji10** [comment] 2021-06-28 08:39
> I took a look at the model.
> Unfortunately, atleast for now, our GPU backend doesn't support graphs with dynamic tensors. This is because the GPU delegate may not work well So I don't exactly have a 'perfect' solution to this issue, but I can share a few pointers :-)
> 
> 1. Did you try multi-threaded inference? That usually speeds things up on the CPU. If you are using our Java bindings, [this option](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/java/src/main/java/org/tensorflow/lite/Interpreter.java#L180) can be set to 4.
> 2. Even then, an input size of 1024x1024 is pretty large for on-device inference. Is there any way for you to retrain it to a smaller dimension? Even bringing it down to 640-512 will help _significantly_.
> 3. If we were to look into removing the 'dynamic' parts of the graph (and thus enable GPU acceleration), it looks like the [NMS call](https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/model.py#L319) in the MaskRCNN model is causing the issues. One thing that some advanced clients have done in the past, is split a graph into the 1) Backbone/Feature extraction (all the convolution/fully-connected/math layers which have static shapes) & 2) Post-processing (which contains tricky bits like NMS)
> 
> Will this be feasible for you? I appreciate that this answer isn't the most convenient, but the size of MaskRCNN causes these issues :-). Out of curiosity, are you using the segmentation mask outputs from MaskRCNN?

@srjoglekar246 
I have the same error when I use DB(DifferentiableBinarizationNet) to do text detection. The output shape of DB is (1, 640, 640, 1), just like segmentation mask outputs of MaskRCNN.

So, did you bring up the segmentation issue separately because Tensorflow GPU backend doesn't support segmentation output yet ?

**Comment by srjoglekar246** [comment] 2021-06-28 20:22
@dagongji10 Not sure if your graph has dynamic tensors. If not, then the TFLite GPU delegate should support it. Do you see any error?

**Comment by dagongji10** [comment] 2021-06-30 03:48
> @dagongji10 Not sure if your graph has dynamic tensors. If not, then the TFLite GPU delegate should support it. Do you see any error?

Thanks! I have sloved the problem.
In fact, I got the same error : 
```Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.```
And the reason is I forgot to set batch_size for input image tensor. Now although the output of DB is segmentation mask, the `.tflite` can run normally with GPU delegate!

**Comment by rmothukuru** [comment] 2021-06-30 05:49
@Sudhan97,
With respect to [this comment](https://github.com/tensorflow/tensorflow/issues/46388#issuecomment-871074251), can you please let us know if your issue is resolved so that we can close this it? Thanks!

**Closed** 2021-07-14 06:50 UTC
Labels: TF 2.4, comp:lite, stalled, stat:awaiting response, type:bug

**Comment by mosactycon** [comment] 2022-07-19 11:01
when i press the button to run the face detection feature i got this error, anyone have an idea how to fix this and anyone know anything about this error? please help me... i really appreciate any answer from you....

ja va.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mataBot/com.example.mataBot.faceRecognitionActivity}: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3800)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3976)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8550)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegate(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:367)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:85)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:277)
        at com.example.mataBot.faceRecognitionClass.<init>(faceRecognitionClass.java:48)
        at com.example.mataBot.faceRecognitionActivity.onCreate(faceRecognitionActivity.java:104)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3773)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3976) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2315) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8550) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by hi-tech-AI** [comment] 2025-02-20 00:59
When I try to use Selenium browser as headless mode, I get this error message.

"Created TensorFlow Lite XNNPACK delegate for CPU.
Attempting to use a delegate that only supports static-sized tensors with a graph that has dyn
amic-sized tensors (tensor#-1 is a dynamic-sized tensor)."

How can I fix it?

**Comment by nassimus26** [comment] 2025-02-28 20:54
I am getting the same issue, here's the colab code : https://colab.research.google.com/drive/1WKSgxQUSZp4Q5dHeq2HgJvjjVzxJUoqA?usp=sharing

**Comment by Z7Sept** [comment] 2025-03-02 12:54
Same issue for me. only one difference, for me it's the 58th tensor which have a dynamic size.
I'm trying to webscrape a shop's site which sells bearing
