### ISSUE TITLE
[TF2] TRT Engine Ops are not garbage collected, resulting in incorrect reuse

### ISSUE THREAD

**Issue by MattConley** [tensorflow/tensorflow#36675] opened 2020-02-12 03:12 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1
- Python version: 3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 10.0 cuDNN 7.6.5, TensorRT 6.0.1
- GPU model and memory: RTX 2080 

**Describe the current behavior**

When TRTEngineOps are created for different runs back to back, the first one is not properly cleared, resulting in potential reuse with an incorrect configuration.

In the reproducing case, running the dynamic input shapes TFTRT test creates and uses an fp16 engine op as expected, but the fp32 test does not create a new instance, instead reusing the one from before.  This behavior may result in the test failing, depending on the particular numerical results and tolerances.  In the case where the test passes, the bug can still be observed by parsing through the logs from the run (some snippets of mine are included below).

I'm not sure if the issue is limited to TFTRT, or is the result of a larger problem with the resource manager in TF2.  This forced garbage collection is likely an attempted workaround for the issue:
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py#L372

**Describe the expected behavior**

Created TRTEngineOps should be handled by the resource manager such that they aren't reused in a separate invocation.

**Code to reproduce the issue**

Running the dynamic_input_shapes_test.py with increased verbosity will demonstrate the failure in the logs:
`env TF_CPP_VMODULE=convert_nodes=2,trt_engine_op=1 python tensorflow/python/compiler/tensorrt/test/dynamic_input_shapes_test.py`

**Other info / logs**

(Full log attached)
In the first creation of a TRTEngineOp for the test, we can see that none are found in the TF-TRT cache, so one will be created:

> 2020-02-11 18:21:13.440748: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at trt_engine_resource_ops.cc:183 : Not found: Container TF-TRT does not exist. (Could not find resource: TF-TRT/TRTEngineOp_0)
> INFO:tensorflow:Could not find TRTEngineOp_0 in TF-TRT cache. This can happen if build() is not called, which means TensorRT engines will be built and cached at runtime.
> I0211 18:21:13.440817 140386763036416 trt_convert.py:1074] Could not find TRTEngineOp_0 in TF-TRT cache. This can happen if build() is not called, which means TensorRT engines will be built and cached at runtime.
> INFO:tensorflow:Assets written to: /tmp/dynamic_input_shapes_test0vdtk5_4/tmpsu9l_mk2/tmpd2ckucmp/assets
> I0211 18:21:13.468731 140386763036416 builder_impl.py:775] Assets written to: /tmp/dynamic_input_shapes_test0vdtk5_4/tmpsu9l_mk2/tmpd2ckucmp/assets
> ...
> ...
> 2020-02-11 18:21:13.624985: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:257] Constructing PartitionedCall/TRTEngineOp_0
> 2020-02-11 18:21:13.625010: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:237] Constructing function handle
> 2020-02-11 18:21:13.625334: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:736] Building a new TensorRT engine for PartitionedCall/TRTEngineOp_0 with input shapes: [[1,5,5,1]]
> 2020-02-11 18:21:13.625404: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
> 2020-02-11 18:21:13.829528: I tensorflow/compiler/tf2tensorrt/convert/convert_nodes.cc:5645] Starting engine conversion, precision mode: FP16

However, in the FP32 test run later, we do not see the warning about an engine op not being found in the cache, and there is no new engine op created:

> 
> WARNING:tensorflow:From /home/mconley/TF2.1_test_env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
> Instructions for updating:
> If using Keras pass *_constraint arguments to layers.
> W0211 18:21:16.109585 140386763036416 deprecation.py:506] From /home/mconley/TF2.1_test_env/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1635: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
> Instructions for updating:
> If using Keras pass *_constraint arguments to layers.
> INFO:tensorflow:Assets written to: /tmp/dynamic_input_shapes_test0vdtk5_4/tmp45kosn5r/tmpou7_kbrm/assets
> I0211 18:21:16.131422 140386763036416 builder_impl.py:775] Assets written to: /tmp/dynamic_input_shapes_test0vdtk5_4/tmp45kosn5r/tmpou7_kbrm/assets
> WARNING:tensorflow:Unresolved object in checkpoint: (root).trt_engine_resources.TRTEngineOp_0._serialized_trt_resource_filename
> W0211 18:21:16.308784 140386763036416 util.py:144] Unresolved object in checkpoint: (root).trt_engine_resources.TRTEngineOp_0._serialized_trt_resource_filename
> ...
> ...
> 2020-02-11 18:21:16.378245: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:257] Constructing PartitionedCall/TRTEngineOp_0
> 2020-02-11 18:21:16.378281: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:237] Constructing function handle
> 2020-02-11 18:21:16.378781: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:515] Executing TRT engine: PartitionedCall/TRTEngineOp_0
> 2020-02-11 18:21:16.379594: I tensorflow/compiler/tf2tensorrt/kernels/trt_engine_op.cc:515] Executing TRT engine: PartitionedCall/TRTEngineOp_0
> [logged_output.log](https://github.com/tensorflow/tensorflow/files/4189640/logged_output.log)
>

**Comment by sanjoy** [comment] 2020-02-13 00:19
> This forced garbage collection is likely an attempted workaround for the issue:
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/compiler/tensorrt/test/tf_trt_integration_test_base.py#L372

That looks super fishy to me as well -- we should never need to rely on GC for *correctness*.

Is this happening because we are creating key-ing TRT engines on the tensor shapes of the inputs and ignoring the dtypes?  I.e. the key does not capture enough information?

If so I'd suggest the following fix:

 * Make sure each `TRTEngineOp` has a `segment_func` with a (process wide) different name.
 * Key the `EngineContext` on the tensor shapes, dtypes, ID and `segment_func` name.

**Comment by sanjoy** [comment] 2020-02-13 00:20
@bixia1 @DEKHTIARJonathan Do either of you have cycles to pick this up?

**Comment by bixia1** [comment] 2020-02-20 00:48
I ran the test without the forced garbage collection in tf_trt_integration_test_base.py, and did see TRT engines created for both F16 and F32. So the problem is gone in the current tree.  My commands are similar to this:

$ blaze run -c opt tensorflow/python/compiler/tensorrt:gpu_dynamic_input_shapes_test --define use_experimental_tensorrt=1 --config=cuda  --test_env=TF_CPP_VMODULE=convert_nodes=2,trt_engine_op=1  --test_arg=--logtostderr>& t.log
$ grep -e "trt_engine_op" -e "DynamicInputShapesTest" t.log
[ RUN      ] DynamicInputShapesTest.testTfTrt_OfflineConversion_DynamicEngine_FP16_NoCalibration
I0219 15:36:59.883159  143904 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,5,5,1]]
I0219 15:37:00.669233  143905 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[10,5,5,1]]
I0219 15:37:01.309641  143903 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,3,1,1]]
I0219 15:37:01.961832  143903 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[2,9,9,1]]
I0219 15:37:02.754980  143905 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,224,224,1]]
I0219 15:37:03.625179  143902 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,128,224,1]]
I0219 15:37:04.565040  143903 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,5,5,1]]
I0219 15:37:05.345535  143904 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[10,5,5,1]]
I0219 15:37:06.050820  143903 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,3,1,1]]
I0219 15:37:06.776347  143903 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[2,9,9,1]]
I0219 15:37:07.644002  143902 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,224,224,1]]
I0219 15:37:08.518280  143902 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,128,224,1]]
[       OK ] DynamicInputShapesTest.testTfTrt_OfflineConversion_DynamicEngine_FP16_NoCalibration
[ RUN      ] DynamicInputShapesTest.testTfTrt_OfflineConversion_DynamicEngine_FP32_NoCalibration
I0219 15:37:09.430716  143905 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,5,5,1]]
I0219 15:37:09.614939  143904 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[10,5,5,1]]
I0219 15:37:09.722950  143904 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,3,1,1]]
I0219 15:37:09.859450  143905 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[2,9,9,1]]
I0219 15:37:10.052555  143903 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,224,224,1]]
I0219 15:37:10.234415  143902 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,128,224,1]]
I0219 15:37:10.486743  143905 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,5,5,1]]
I0219 15:37:10.672606  143905 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[10,5,5,1]]
I0219 15:37:10.777662  143902 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,3,1,1]]
I0219 15:37:10.913178  143905 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[2,9,9,1]]
I0219 15:37:11.098235  143902 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,224,224,1]]
I0219 15:37:11.295327  143905 trt_engine_op.cc:984] Building a new TensorRT engine for TRTEngineOp_0 with input shapes: [[1,128,224,1]]
[       OK ] DynamicInputShapesTest.testTfTrt_OfflineConversion_DynamicEngine_FP32_NoCalibration
[ RUN      ] DynamicInputShapesTest.testTfTrt_OfflineConversion_DynamicEngine_INT8_NoCalibration
[       OK ] DynamicInputShapesTest.testTfTrt_OfflineConversion_DynamicEngine_INT8_NoCalibration
[ RUN      ] DynamicInputShapesTest.testTfTrt_OfflineConversion_DynamicEngine_INT8_UseCalibration
[       OK ] DynamicInputShapesTest.testTfTrt_OfflineConversion_DynamicEngine_INT8_UseCalibration
[ RUN      ] DynamicInputShapesTest.testTfTrt_OfflineConversion_StaticEngine_FP16_NoCalibration
[       OK ] DynamicInputShapesTest.testTfTrt_OfflineConversion_StaticEngine_FP16_NoCalibration
[ RUN      ] DynamicInputShapesTest.testTfTrt_OfflineConversion_StaticEngine_FP32_NoCalibration
[       OK ] DynamicInputShapesTest.testTfTrt_OfflineConversion_StaticEngine_FP32_NoCalibration
[ RUN      ] DynamicInputShapesTest.testTfTrt_OfflineConversion_StaticEngine_INT8_NoCalibration
[       OK ] DynamicInputShapesTest.testTfTrt_OfflineConversion_StaticEngine_INT8_NoCalibration

**Comment by sanjoy** [comment] 2020-02-20 00:55
@bixia1 if this issue is fixed at head, can you do the following:

- Delete the explicit call to the Python GC in the test.
- Add a test case that would have caught the original issue if feasible.

**Comment by bixia1** [comment] 2020-02-20 15:05
I am not sure that I understand this. While I see the TRT engine being created I don't see the cache being accessed. That is I don't things related to  message " trt_convert.py:1074] Could not find TRTEngineOp_0 in TF-TRT cache. This can happen if build() is not called, which means TensorRT engines will be built and cached at runtime" in the initial bug description.

**Comment by MattConley** [comment] 2020-02-26 01:09
Thanks for your help with this bug!
Unfortunately, I was still able to reproduce the issue as of commit 5a037e9954a9e9c883acc504a20ecb4a10c131d9

Also, adding in additional `gc.collect()` calls around each test did not seem to solve this problem; maybe this issue is on a different level than the python garbage collection?

**Comment by nouiz** [comment] 2020-02-26 13:13
Small note, you could need to call multiple time gc.collect() to be sure all is collected from Python. I normally call it 3 times and up to now it was always enough to recover all the object.

**Comment by bixia1** [comment] 2020-02-26 19:25
tfeher@ is going to work on it.

**Comment by sushreebarsa** [comment] 2021-08-01 15:08
@MattConley  It looks like you are using an older Version of Tensorflow. Many bugs have been fixed in the latest version. Could you please execute your code using Latest Version 2.4.1 or 2.5 and let us know if the issue still persists? Thanks!

**Closed** 2021-08-17 18:53 UTC
Labels: stat:awaiting response, type:bug, stalled, TF 2.1, comp:gpu:tensorrt
