### ISSUE TITLE
Failed to build minimal example of Tensorflow Lite on Qualcomm robotic kit rb5

### ISSUE THREAD

**Issue by hamounTUK** [tensorflow/tensorflow#51737] opened 2021-08-29 17:10 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Device: Qualcomm Robotic kit rb5 with 16Gb RAM (I connect the board directly to a monitor using HDMI) 
- TensorFlow installed from (source or binary): 2.6 build from source using Cmake (Also I tried 2.5)
- TensorFlow version: - 
- Python version:  2.7
- Installed using virtualenv? pip? conda?: -
- Bazel version (if compiling from source): - 
- GCC/Compiler version (if compiling from source): Cmake 3.20.5
- CUDA/cuDNN version: - 
- GPU model and memory: GPU: Qualcomm Adreno 650         DSP: Qualcomm Hexagon 698

Dear All,
I’v followed the instruction in this [link](https://www.tensorflow.org/lite/guide/build_cmake) and successfully build Tensorflow Lite using Cmake. I tried to build the minimal example in this [link](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/minimal), but I get a black screen after the build process is 98% completed. Then the black screen remains permanently. 
Anyone has an idea why this happens?

My ultimate goal is to link Tensorflow lite as a static library to a ROS(melodic) package and run an inference for Tensorflow Lite models using Hexagon delegate on the Qualcomm rb5 DSP in order to do an object detection task. Anyone has an idea what is the best way to do it?

Thanks
Hamoun

**Comment by vulkomilev** [comment] 2021-08-30 20:10
Black screen .Like the whole system freezes and it needs a reset? If this is the case I don't think the problem is from the tensorflow. Have you tried to compile something other than tensorflow with cmake ?

**Comment by hamounTUK** [comment] 2021-09-14 17:27
Finally, I was able to solve the problem. It wasn't the Cmake problem. The problem was coming from setting the default parallelization values. Before that, I used: `cmake --build . -j` in order to build the TFLite. I changed it to `cmake --build . -j4` and it worked successfully.
But I still don't know how and why it solved the problem?

**Comment by karimnosseir** [comment] 2021-09-23 07:46
I don't know why the build on your machine was freezing and limiting threads worked. 
But looks like you don't have an issue now. 
Closing the issue, feel free to reopen if needed.

Thanks

**Closed by karimnosseir** 2021-09-23 07:46 UTC
Labels: type:build/install, comp:lite, 2.6.0
