### ISSUE TITLE
Possible corruption in Load or freeze in TF2.0

### ISSUE THREAD

**Issue by pooyadavoodi** [tensorflow/tensorflow#33060] opened 2019-10-04 23:29 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary 2.0.0
- TensorFlow version (use command below): 2.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 7.6.4
- GPU model and memory: Volta/Turing

**Describe the current behavior**
When I run load and freeze in two different python functions, I get a crash that says: 

```AssertionError: Called a function referencing variables which have been deleted. This likely means that function-local variables were created and not referenced elsewhere in the program. This is generally a mistake; consider storing variables in an object attribute on first call.```

But when I run both of load and freeze in the same python function, then it works as expected.

**Describe the expected behavior**
Calling load and freeze in different python functions should work unless there is some hidden assumption in TF 2.0. My guess is that there is a leak or some dependency between the two APIs.

**Code to reproduce the issue**
```
import argparse
import numpy as np
import tensorflow as tf
from tensorflow.python.saved_model import signature_constants
from tensorflow.python.saved_model import tag_constants
from tensorflow.python.framework import convert_to_constants

def get_dataset(batch_size, input_size):
  features = np.random.normal(
      loc=112, scale=70,
      size=(batch_size, input_size, input_size, 3)).astype(np.float32)
  features = np.clip(features, 0.0, 255.0)
  features = tf.convert_to_tensor(value=tf.compat.v1.get_variable(
      "features", dtype=tf.float32, initializer=tf.constant(features)))
  dataset = tf.data.Dataset.from_tensor_slices([features])
  dataset = dataset.repeat()
  return dataset


def run_func(saved_model_dir):

  def load_model():
    saved_model_loaded = tf.saved_model.load(
        saved_model_dir, tags=[tag_constants.SERVING])
    graph_func = saved_model_loaded.signatures[
        signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
    return graph_func
  graph_func = load_model()

# Replace load_model function and its call with the following to make it work
#  saved_model_loaded = tf.saved_model.load(
#      saved_model_dir, tags=[tag_constants.SERVING])
#  graph_func = saved_model_loaded.signatures[
#      signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY]

  frozen_func = convert_to_constants.convert_variables_to_constants_v2(graph_func)
  def wrap_func(*args, **kwargs):
    return frozen_func(*args, **kwargs)[0]
  inference_graph_func = wrap_func
  dataset = get_dataset(batch_size=8, input_size=224)
  for i, (batch_feats) in enumerate(dataset):
    batch_preds = inference_graph_func(batch_feats).numpy()
    print(batch_preds)


if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='Evaluate model')
  parser.add_argument('--saved_model_dir', type=str, default=None,
                      help='Directory containing a particular saved model.')
  args = parser.parse_args()

  run_func(saved_model_dir=args.saved_model_dir)
```

**Other info / logs**
Command line to run: `python tfv2_load_issue.py --saved_model_dir path_to_saved_model`

```
2019-10-04 20:35:48.913525: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:734] Optimization results for grappler item: graph_to_optimize
2019-10-04 20:35:48.913553: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:736]   function_optimizer: Graph size after: 1314 nodes (1044), 2670 edges (2400), time = 23.171ms.
2019-10-04 20:35:48.913557: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:736]   function_optimizer: function_optimizer did nothing. time = 0.371ms.
Traceback (most recent call last):
  File "run.py", line 51, in <module>
    run_func(saved_model_dir=args.saved_model_dir)
  File "run.py", line 35, in run_func
    frozen_func = convert_to_constants.convert_variables_to_constants_v2(graph_func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/convert_to_constants.py", line 411, in convert_variables_to_constants_v2
    tensor_data = _get_tensor_data(func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/convert_to_constants.py", line 182, in _get_tensor_data
    for var in func.graph.variables:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 435, in variables
    "Called a function referencing variables which have been deleted. "
AssertionError: Called a function referencing variables which have been deleted. This likely means that function-local variables were created and not referenced elsewhere in the program. This is generally a mistake; consider storing variables in an object attribute on first call.
```

**Comment by rmothukuru** [comment] 2019-10-09 08:42
@pooyadavoodi,
I have reproduced your issue with the Exported Model of Iris Data and I have executed the command line argument provided by you but I didn't get any error. It printed the values. Can you please help me reproduce the issue. Thanks!

**Comment by rmothukuru** [comment] 2019-10-21 12:48
@pooyadavoodi,
Can you please let us know if your issue is resolved. Else, can you please help us reproduce the issue. Thanks!

**Comment by rmothukuru** [comment] 2019-11-05 12:16
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-11-05 12:16 UTC
Labels: TF 2.0, comp:apis, stat:awaiting response, type:bug

**Comment by tensorflowbutler** [comment] 2019-11-05 12:33
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by s4sarath** [comment] 2020-03-15 16:24
I am facing the same issue . When returning a ```tf.saved_model.load``` object inside a function and then try to use it, it is not working. 

I am having a file ```sample.py``` 
```
#### sample.py

import tensorflow as tf
def load_model(model_dir):

    # Load Model
    loaded = tf.saved_model.load(model_dir)
    model = loaded.signatures['serving_default']
    print("Model Loaded")
    return model

```

When I am executing ```main.py```

```
from sample import load_model

model_dir = 'som_path of a saved model'
model1 = load_model(model_dir)
```

If I print model.variables I am getting following error

```
AssertionError: Called a function referencing variables which have been deleted. This likely means that function-local variables were created and not referenced elsewhere in the program. This is generally a mistake; consider storing variables in an object attribute on first call.

```

But. If load the model with same code inside the function, but not using the function it works fine

```
#### main.py
loaded = tf.saved_model.load(model_dir)
model = loaded.signatures['serving_default']
```
If I print model.variables, its working as expected.

**Comment by etsygankov** [comment] 2020-07-01 16:00
@s4sarath encountered the same issue, it seems that that the function loading the model must return `tf.saved_model.load(path)` not just an inference function obtained by referencing `signature` property `tf.saved_model.load(path).signatures['serving_default']`.

**Comment by s4sarath** [comment] 2020-07-02 13:56
Glad someone mentioned it. It's very critical right.
