### ISSUE TITLE
Build ERROR: undeclared inclusion(s) in rule '//tensorflow/core/kernels:batchtospace_op_gpu':

### ISSUE THREAD

**Issue by skydoorkai** [tensorflow/tensorflow#4148] opened 2016-09-01 09:59 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Linux RHL 7.2

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): cuda 7.5 + cudnn 5

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
./configure (select to support GPU)
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package  --verbose_failures

### What other attempted solutions have you tried?
Rebuild from scratch, still repro.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

ERROR: /data/tools/tensorflow/core/kernels/BUILD:1509:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:batchtospace_op_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/batchtospace_op_gpu.cu.cc':
  '/usr/local/cuda-7.5/include/cuda_runtime.h'
  '/usr/local/cuda-7.5/include/host_config.h'
  '/usr/local/cuda-7.5/include/builtin_types.h'
  '/usr/local/cuda-7.5/include/device_types.h'
  '/usr/local/cuda-7.5/include/host_defines.h'
  '/usr/local/cuda-7.5/include/driver_types.h'
  '/usr/local/cuda-7.5/include/surface_types.h'
  '/usr/local/cuda-7.5/include/texture_types.h'
  '/usr/local/cuda-7.5/include/vector_types.h'
  '/usr/local/cuda-7.5/include/channel_descriptor.h'
  '/usr/local/cuda-7.5/include/cuda_runtime_api.h'
  '/usr/local/cuda-7.5/include/cuda_device_runtime_api.h'
  '/usr/local/cuda-7.5/include/driver_functions.h'
  '/usr/local/cuda-7.5/include/vector_functions.h'
  '/usr/local/cuda-7.5/include/vector_functions.hpp'
  '/usr/local/cuda-7.5/include/common_functions.h'
  '/usr/local/cuda-7.5/include/math_functions.h'
  '/usr/local/cuda-7.5/include/math_functions.hpp'
  '/usr/local/cuda-7.5/include/math_functions_dbl_ptx3.h'
  '/usr/local/cuda-7.5/include/math_functions_dbl_ptx3.hpp'
  '/usr/local/cuda-7.5/include/cuda_surface_types.h'
  '/usr/local/cuda-7.5/include/cuda_texture_types.h'
...

**Comment by davidzchen** [comment] 2016-09-07 01:21
@skydoorkai - Are you explicitly specifying the CUDA version when running `./configure`? If not, then most likely, you are hitting #3985.

**Comment by cshallue** [comment] 2016-09-07 15:25
I had this issue and fixed it by explicitly specifying the CUDA version (8.0) when running ./configure.

**Comment by martinwicke** [comment] 2016-09-07 15:40
I'm closing this as a duplicate of #3985.

**Closed by martinwicke** 2016-09-07 15:40 UTC
Labels: awaiting googler
