### ISSUE TITLE
max_pool_with_argmax: No gradient defined

### ISSUE THREAD

**Issue by thematrixduo** [tensorflow/tensorflow#2098] opened 2016-04-25 16:42 UTC
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Linux Ubuntu 14.04

Installed version of CUDA and cuDNN: None
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide: pip package:
tensorflow-0.8.0-cp34-cp34m-linux_x86_64.whl

1. Which pip package you installed.  
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".

If installed from sources, provide the commit hash:

### Steps to reproduce
1. include a max_pool_with_argmax layer in a convolutional neural network and use it for training.
The process terminate with this error:
LookupError: No gradient defined for operation 'conv2/MaxPoolWithArgmax' (op type: MaxPoolWithArgmax)

**Comment by poxvoculi** [comment] 2016-04-25 22:33
Thanks for the bug report.  Fix in process.

**Comment by girving** [comment] 2016-06-07 04:41
@zheng-xq, @poxvoculi: Is a fix really in progress?  It's only 10 or so lines of code, and @mwalton already wrote most of it here: https://github.com/tensorflow/tensorflow/issues/1793

**Comment by zheng-xq** [comment] 2016-06-07 05:05
@girving, a PR is welcome.

**Comment by girving** [comment] 2016-06-07 05:08
Closing as duplicate of #1793.

**Closed by girving** 2016-06-07 05:08 UTC
Labels: awaiting response
