### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'uint32'

### ISSUE THREAD

**Issue by vijaysinghkadam** [tensorflow/tensorflow#26295] opened 2019-03-03 11:31 UTC
import tensorflow as tf
tf.unit32

it works fine with the tf.unit16 and tf.unit8 but it gives error while accessing tf.unit32
I tried reinstalling tensorflow but it wont work.
I have installed tensorflow using anaconda . then i run the code and i have this problem:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-0a81b7b43fe1> in <module>
----> 1 tf.uint32

AttributeError: module 'tensorflow' has no attribute 'uint32'
----------------------------------------------------------------------------

i have also tried ' pip install --upgrade --force-reinstall tensorflow ' as per the answer in
https://stackoverflow.com/questions/51654346/attributeerror-module-tensorflow-has-no-attribute-float32
but it still wont work

**Comment by ymodak** [comment] 2019-03-06 23:20
Please provide following information. Thanks!
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:


You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ymodak** [comment] 2019-03-11 17:02
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-11 17:02 UTC
Labels: stat:awaiting response

**Comment by subash143** [comment] 2020-05-20 04:32
Have you tried tf.cast(x, dtype=tf.int32)?
