### ISSUE TITLE
tf.contrib.summary.create_file_writer 'name' parameter is not recognized

### ISSUE THREAD

**Issue by Kshitij09** [tensorflow/tensorflow#28423] opened 2019-05-05 22:08 UTC
While creating summary writer in eager execution, name parameter is not recognized properly, hence all the graphs are getting associated with single (default) name.
```
logdir = 'logs'
model_name = 'mnist-dense-128'
summary_writer = tf.contrib.summary.create_file_writer(logdir, flush_millis=10000,
name=model_name)
summary_writer.set_as_default()
```
Attaching [screenshot](https://drive.google.com/open?id=1bwOFOA631vtBvejoXGu9Xf6oVTXtqnVI) of Tensorboard for reference

Tensorflow version: 1.13

**Comment by jvishnuvardhan** [comment] 2019-05-22 21:30
@Kshitij09 I think it is more related to tensorboard repo. Could you post it [there](https://github.com/tensorflow/tensorboard/issues). If you think it is more related to TF Core, then please provide a standalone code to reproduce the issue. Thanks!

**Comment by tensorflowbutler** [comment] 2019-06-07 13:16
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by Kshitij09** [comment] 2019-06-08 13:26
@jvishnuvardhan I found that, we used to create sub-directories in order to maintain separate logs of models. Tensorboard label the respective statistics by their directory name. Is this the only way to assign names to graphs ? then what's the use of 'name' parameter in `create_file_writer()` method ?

**Comment by jvishnuvardhan** [comment] 2019-07-16 23:07
Closing this out since it is more related to Tensorboard repo. Thanks!

**Closed by jvishnuvardhan** 2019-07-16 23:07 UTC
Labels: TF 1.13, comp:eager, comp:tensorboard, contrib, type:support
