### ISSUE TITLE
[Lite] tf.strided_slice sometimes computes wrong indices

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#19260] opened 2018-05-13 23:06 UTC
### System information
- **Have I written custom code**: yes
- **OS Platform and Distribution**: Ubuntu 16.04.2 LTS
- **TensorFlow installed from**: source
- **TensorFlow version**: v1.8.0-1520-g1f03f82 1.8.0
- **Python version**: 3.5.2
- **Bazel version**: 0.13.0

### Problem
I tried using the [TOCO tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/toco) on a graph that contains a [`strided_slice`](https://www.tensorflow.org/api_docs/python/tf/strided_slice) op.
The code determining the fixed size of this op, fails at an assertion and throws an error (see below).

### Logs
2018-05-14 00:42:56.816500: F [tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:1305](https://github.com/tensorflow/tensorflow/blob/1f03f829285ca0fbd47a99350e9f5d99aa10e9b9/tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc#L1305)] Check failed: dim_size > 0 (-1 vs. 0)Output size for an axis must be greater than 0. Axis 0 computes to size -1 for StridedSlice op with output "stft/frame/strided_slice".

### Minimum Reproducible Example
[Source files](https://github.com/tensorflow/tensorflow/files/1999035/mre.zip)
(set `TF_ROOT` in `freeze` and `toco`)
```
./mre.py
./freeze
./toco
```
This produces a directory "model" with the graph, weights and frozen graph.
The offending error is thrown by last step.

**Comment by Androbin** [comment] 2018-05-14 01:39
The failing assertion was introduced in commit 83418120b7c2659fedddd7c85b65d3c3e6aa94e3
(Fixing a bug in strided slice. The op was not handling negative indices correctly)

**Comment by alanchiao** [comment] 2018-05-17 20:29
Robin, would it be possible for you to provide the model.pb file (or something similar that produces the same error)?

**Comment by Androbin** [comment] 2018-05-17 20:56
I've attached the full source above. For convenience, here are the important snippets.

Model:
```
import tensorflow as tf
import tensorflow.contrib.signal as signal

x = tf.placeholder(tf.float32, [None, 9152], name="x")
y = tf.placeholder(tf.int64, [None], name="y")

v = tf.Variable(1.)

magspec = signal.stft(x, frame_length, frame_step, num_frames, None)
magspec = tf.abs(magspec) * v

features = tf.expand_dims(magspec, 3)

y_conv = tf.identity(features, name="y_conv")
```
Freezing:
```
bazel-bin/tensorflow/python/tools/freeze_graph \
  --input_graph=model.pb \
  --input_checkpoint=model.ckpt \
  --output_graph=frozen_model.pb \
  --output_node_names=y_conv
```
TOCO tool:
```
bazel-bin/tensorflow/contrib/lite/toco/toco \
  --input_file=frozen_model.pb \
  --input_format=TENSORFLOW_GRAPHDEF \
  --output_format=TFLITE \
  --output_file=model.tflite \
  --inference_type=FLOAT \
  --input_type=FLOAT \
  --input_arrays=x \
  --output_arrays=y_conv \
  --input_shapes=1,9152
```

**Comment by Androbin** [comment] 2018-05-20 00:30
@aselle Friendly ping.

**Comment by alanchiao** [comment] 2018-05-21 17:46
In my local run, the inputs to strided_slice were begin=[1], end=[0], strides=[1]. The strided_slice op is called as a part of the stft op.

With these inputs, strided_slice should either error out or return an empty tensor (since end < begin, which is causing the check to fail). We should likely do the latter since tensorflow itself doesn't error out. 

I'm looping in rryan@ to see if these inputs to strided_slice make sense for stft and whether returning an empty tensor makes sense.


I've attached my model and frozen graph for debugging.
[model.zip](https://github.com/tensorflow/tensorflow/files/2023519/model.zip)

**Comment by alanchiao** [comment] 2018-05-21 17:50
@rryan: do you think these inputs are expected for stft and that returning an empty tensor makes sense?

**Comment by rryan** [comment] 2018-05-21 22:58
@Androbin what frame_length / frame_step / num_frames are you using here?

**Comment by alanchiao** [comment] 2018-05-21 23:06
@rryan: the info is in his attached source files.

num_frames = 49
frame_length = 512
frame_step = 180

**Comment by rryan** [comment] 2018-05-21 23:09
Hm, if I'm not mistaken, `stft/frame/strided_slice` is from [this line](https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/signal/python/ops/shape_ops.py#L114). Axis is always `-1` when called from `tf.contrib.signal.stft`, so this boils down to `tf.range(tf.rank(x))[-1]`.

**Comment by Androbin** [comment] 2018-05-21 23:38
@rryan Could not handling the negative index appropiately lead to the values reported by @alanchiao?
> the inputs to strided_slice were begin=[1], end=[0], strides=[1]

**Comment by Androbin** [comment] 2018-05-21 23:46
check in `tf.concat`:
```
// Negative axis means the count starts at the back of the dims().
int axis = op->axis;
if (axis < 0) axis += first_input_array.shape().dims().size();
```

check in `tf.stack`:
```
int axis = op->axis;
if (axis < 0) {
  // Handle negative axis
  axis += stacked_shape->dims().size() + 1;
}
```

Isn't the second one wrong?

**Comment by Androbin** [comment] 2018-05-21 23:51
Regarding `tf.strided_slice`, TOCO seems to be generally aware of negative indices.
But here it expects (stop_index - start_index) and op->strides[axis] to be of the same sign.
```
int dim_size = ceil(static_cast<float>(stop_index - start_index) / op->strides[axis]);
CHECK_GT(dim_size, 0)
```
The values `begin=[1], end=[0], strides=[1]` should be either of these:
* `begin=[0], end=[1], strides=[1]`
* `begin=[1], end=[0], strides=[-1]`

**Comment by rryan** [comment] 2018-05-22 00:12
> int axis = op->axis;
> if (axis < 0) {
>   // Handle negative axis
>   axis += stacked_shape->dims().size() + 1;
> }
> i
> Isn't the second one wrong?

It confused me too but I think it's ok:
 
* `tf.stack(x, axis=0)` -> `[len(x), d0, ..., dn]`
* `tf.stack(x, axis=1)` -> `[d0, len(x), ..., dn]`
* `tf.stack(x, axis=rank(x))` -> `[d0, ..., dn, len(x)]`
* `tf.stack(x, axis=-1)` -> `[d0, ..., dn, len(x)]`

So for `axis=-1`,  the code computes `axis = rank(shape) + axis + 1` -> `rank(shape) + -1 + 1` -> `rank(shape)`, which is the same as the `tf.stack(x, axis=rank(x))` case.

**Comment by alanchiao** [comment] 2018-05-22 00:51
I think it should be the call to [tf.strided_slice]( https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/signal/python/ops/shape_ops.py#L161) instead.

The pbtxt file shows the name "stft/frame/strided_slice" attached to a StridedSlice operator and there isn't any other StridedSlice op in the pbtxt file.

This is [what Tensorboard shows for the frozen graph](https://user-images.githubusercontent.com/4323109/40336477-a3d89a88-5d1e-11e8-834f-7e11e32cc625.png) and we can see the output feeds into the reshape op, matching the code.

```
    subframes = array_ops.reshape(array_ops.strided_slice(
        signal, array_ops.zeros_like(signal_shape),
        slice_shape), subframe_shape)
```

The **subframes** variable (output of reshape) then feeds into a GatherV2 op, which matches the code below.

```
frames = array_ops.reshape(
        array_ops.gather(subframes, selector, axis=axis),
        array_ops.concat([outer_dimensions, [num_frames, frame_length],
                          inner_dimensions], 0)) 
```

**Comment by rryan** [comment] 2018-05-22 01:06
@alanchiao I believe that's `stft/frame/StridedSlice`, not `stft/frame/strided_slice`. 

There are 2 StridedSlice ops created by `tf.contrib.signal.stft`: [example colab](https://colab.research.google.com/drive/11o_xv1_h1LK3QWQAmLMrwySRM3emudoz#scrollTo=67b2nLDw81sZ). Note that numpy-style slices are `StridedSlice` ops under the covers.

Here's the op definition for `stft/frame/strided_slice` which is the node the error message refers to. Its first input is `stft/frame/range`, which is the result of `tf.range(tf.rank(x))`
```
node {
  name: "stft/frame/strided_slice"
  op: "StridedSlice"
  input: "stft/frame/range"
  input: "stft/frame/strided_slice/stack"
  input: "stft/frame/strided_slice/stack_1"
  input: "stft/frame/strided_slice/stack_2"
  attr {
    key: "Index"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "begin_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "ellipsis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "end_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "new_axis_mask"
    value {
      i: 0
    }
  }
  attr {
    key: "shrink_axis_mask"
    value {
      i: 1
    }
  }
}
```

**Comment by rryan** [comment] 2018-05-22 19:14
Here's a minimal reproduction of the failure:
In `tensorflow/contrib/lite/kernels/strided_slice_test.cc`:
```c++
TEST(StridedSliceOpTest, In1D_ShrinkAxisMask1_NegativeSlice) {
  // This is equivalent to tf.range(4)[-1].
  StridedSliceOpModel<> m({4}, {1}, {1}, {1}, 0, 0, 0, 0, 1);
  m.SetInput({1, 2, 3, 4});
  m.SetBegin({-1});
  m.SetEnd({0});
  m.SetStrides({1});

  m.Invoke();
  EXPECT_TRUE(m.GetOutputShape().empty());
  EXPECT_THAT(m.GetOutput(), ElementsAreArray({4}));
}
```

```
[ RUN      ] StridedSliceOpTest.In1D_ShrinkAxisMask1_NegativeSlice
ERROR: third_party/tensorflow/contrib/lite/kernels/strided_slice_test.cc:397 
Value of: m.GetOutput()
Expected: has 1 element that is equal to 4
  Actual: { -1.21979e-12 }, whose element #0 doesn't match
Stack trace:
0x55ebb4b9a8ab: tflite::(anonymous namespace)::StridedSliceOpTest_In1D_ShrinkAxisMask1_NegativeSlice_Test::TestBody() @ ??:??
0x7f6e29315fad: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) @ ??:??
0x7f6e29307ad1: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) @ ??:??
0x7f6e292fa485: testing::Test::Run() @ ??:??
0x7f6e292fabdf: testing::TestInfo::Run() @ ??:??
... gUnit internal frames ...
```

**Comment by mjmatthews** [comment] 2018-05-30 17:22
If I execute the following slice, both TensorFlow's slicing operator and `strided_slice` return the correct empty list:
```
print sess.run(tf.constant([1,2,3,4])[-1:0:1])
print sess.run(tf.strided_slice([1, 2, 3, 4], [-1], [0], [1]))
[]
[]
```
Which agrees with python's slicing:
```
foo=[1,2,3,4]
print foo[-1:0:1]
[]
```
All good.

Where it gets weird is adding in the shrink_axis flag on the first dimension:
```
print sess.run(tf.strided_slice([1, 2, 3, 4], [-1], [0], [1], shrink_axis_mask=1))
4
```
If we try to do the equivalent in numpy:
```
foo=np.array([1,2,3,4])
print np.shape(foo[-1:0:1])
print foo[-1:0:1].squeeze(axis=0)

(0,)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-fb8485f97d3e> in <module>()
      2 foo=np.array([1,2,3,4])
      3 print np.shape(foo[-1:0:1])
----> 4 print foo[-1:0:1].squeeze(axis=0)
      5 print np.shape(foo[-1:0:1])
      6 bar = np.squeeze(foo[-1:0:1], axis=0)

ValueError: cannot select an axis to squeeze out which has size not equal to one
```
we get an error, which I believe is the correct response. This is also stated in the [documentation](https://www.tensorflow.org/api_docs/python/tf/strided_slice) for `strided_slice`.

> If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks the dimensionality by 1. begin[i], end[i] and strides[i] must imply a slice of size 1 in the dimension.

I could be wrong in my understanding of the equivalence of what `shrink_axis_mask` and `np.squeeze` are doing, and there are some strange subtleties to TensorFlow's handling of zero and one dimensional scalars, but on the surface of it, this looks like a bug in TensorFlow's implementation of `shrink_axis_mask` in `strided_slice`. Or maybe this was an explicit design decision for some reason?

**Comment by mjmatthews** [comment] 2018-05-30 17:48
And I suspect the desired behavior on the `strided_slice` operator would be generated with `end_mask=1`.

**Comment by rryan** [comment] 2018-06-08 03:48
@mjmatthews 

Yea, the `end` is just `start + 1` in this case, so it makes sense the interval is not length 1.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L488

Which violates the requirements of shrink_axis_mask:
```
If the ith bit of shrink_axis_mask is set, it implies that the ith specification shrinks 
the dimensionality by 1. begin[i], end[i] and strides[i] must imply a slice of size 1 
in the dimension. For example in Python one might do foo[:, 3, :] 
which would result in shrink_axis_mask equal to 2.
```

There is a workaround implemented in C++ here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/strided_slice_op.cc#L290-L300

It's unfortunate, but tf.lite should probably follow suit, right?

/cc: @aselle

**Comment by rryan** [comment] 2018-06-11 15:41
Anyway, @Androbin I noticed you're using tf.contrib.signal.stft here -- note that tf.lite doesn't support complex numbers at the moment so once you get past this bug you'll still have issues. 

I'm in the process of adding complex64 and RFFT/IRFFT support to tf.lite and I'll be making sure tf.contrib.signal.stft works in the process. complex64 is currently out for code review, so I'm hopeful this can make it into the next TensorFlow release.

**Comment by Androbin** [comment] 2018-06-11 20:23
Thanks for your efforts @rryan.

Slightly off topic: I'm actually using `tf.abs( tf.contrib.signal.stft( x ) )`.
Since complex numbers are a combination of absolute value and "argument":
Can this be rewritten as a single op which doesn't require complex numbers?
Maybe this would also be somewhat more battery efficient?

**Comment by aselle** [comment] 2018-06-12 06:13
When shrinking an axis there is only a single index not a begin and end, so the end being wrong shouldn't matter. It becomes a useless parameter. So yes, follow suite with the tf implementation. I think your work around is correct.

**Comment by rryan** [comment] 2018-06-12 16:56
Great, thanks @aselle -- I'll go ahead and send out my fix for review.

**Comment by rryan** [comment] 2018-06-12 17:17
> Slightly off topic: I'm actually using tf.abs( tf.contrib.signal.stft( x ) ).
> Since complex numbers are a combination of absolute value and "argument":
> Can this be rewritten as a single op which doesn't require complex numbers?
> Maybe this would also be somewhat more battery efficient?

Hm, you always have to compute both the real and imaginary parts of the DFT in order to get the magnitude so I think even if there are no complex-valued tensors the op would be calculating it internally. You can factor the calculation into a real and imaginary part to avoid needing a complex type in tf.lite itself, but this will probably be less efficient than computing them jointly because the real and imaginary parts share the same memory access patterns when they're being computed. 

One thing that might help is doing a fixed-point FFT instead of floating point. I haven't thought much about how to support that with TensorFlow's `RFFT` op, but it should be do-able.

If you're building a mobile algorithm that operates in a streaming fashion you probably want to pass in frames of audio at a time to your tf.lite model. In this situation, `tf.contrib.signal.stft` isn't going to be appropriate because it's going to frame the audio you pass in for you, and it doesn't support being run in a stateful manner where you're feeding it chunks of audio at a time. You may want to fall back on `tf.contrib.signal.hann_window` (or any window) and `tf.spectral.rfft` to window and compute the RFFT on the incoming frame you're processing in this scenario.

**Comment by aselle** [comment] 2018-06-12 17:53
Hm one could have the fft return a buffer where the last last dimension of
the tenosor is 2-dimensional so...
real = foo[..., 0]
im = foo[..., 1]
Then you wouldnmt' strictly need complex numbers. Then you could add
tensors using the existing add, but you'd have to be careful using
operations that weren't  decoupled  in real and imaginary behavior like *,
but you could do real part by doing then

tf.sqrt(tf.reduce_add(foo * foo, axis=-1))
-A

**Comment by aselle** [comment] 2018-06-12 21:53
Well I agree we should fix array_ops.cc too, but you don't just need to fix the -1 case right? you need to fix -2 because otherwise you'll mill -2 which also needs the same treatment. Also, you have to consider that s may be a tensor itself so you can't actually compare it to 1 with an if condition. So you may need to do this:
```python
  else:
    strides.append(1)
    begin.append(s)
    const_s = tensor_util.constant_value(s)
    if const_s is not None:
      end.append(s+1 if s>=0 else s-1)
    else:
      end.append(tf.where(s>=0, s+1, s-1))
    shrink_axis_mask |= (1 << index)
```

**Comment by mjmatthews** [comment] 2018-06-13 19:16
I believe we're ok in the -2 case. The existing code should produce:
```
print sess.run(tf.constant([1,2,3,4])[-2:-1:1])
[3]
```
I think the s-1 case your pointing out would be for a negative stride, ie:
```
print sess.run(tf.constant([1,2,3,4])[0])
print sess.run(tf.constant([1,2,3,4])[0:-1:-1])
print sess.run(tf.constant([1,2,3,4])[0:  :-1])
1
[]
[1]
```
but since we pick the stride to be positive, we can always use s+1. These are the one case where the interval crosses zero, causing the logic to differ and requiring the use of end_mask. 

I was unaware of s possibly being a tensor. If we're computing on an element-wise basis, wouldn't we have to set the end_mask as well too? Not quite sure what that would look like.

**Comment by aselle** [comment] 2018-06-14 21:47
Don't know if this covers any more ground, but I believe that the TensorFlow implementation of tf.strided_slice ignores the end index that is passed if shrink axis is true, because just naively adding 1 doesn't work for -1 case:

```
foo = [0,1,2]
foo[-1]  ==> 2
```
, where you'd get -1 + 1 = 0 which is the beginning and would be a degenerate interval.

I make a comment here to ignore it here
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/strided_slice_op.cc#L131

Special rules for shrinking are here (only stride 1 is allowed even though the op's parameter space allowed it, it couldn't generated with getitem):
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/strided_slice_op.cc#L280
And also 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/strided_slice_op.cc#L290

So it is documented in the comments, but it might be helpful to document in the spec and docstrings on both python and tflite side.

**Comment by tensorflowbutler** [comment] 2018-06-29 18:57
Nagging Assignees @rryan, @alanchiao: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by rryan** [comment] 2018-07-02 20:08
This should be fixed by https://github.com/tensorflow/tensorflow/commit/9bcbfc1636d98e99d821c1a5292a5fe70663ccdb.

**Closed by rryan** 2018-07-02 20:08 UTC
Labels: comp:lite
