### ISSUE TITLE
Internal: No unary variant unary_op function found for unary variant op enum: 1 Variant type_name: RaggedTensorVariant for device type: GPU

### ISSUE THREAD

**Issue by julilien** [tensorflow/tensorflow#44231] opened 2020-10-22 12:17 UTC
**System information**
- Have I written custom code: yes
- OS Platform and Distribution: Linux Ubuntu 20.04 Focal
- TensorFlow installed from (source or binary): Source as also used in nightly build from 20201021; also tested the official tf-nightly-gpu.dev20201021 build installed with pip
- TensorFlow version (use command below): 2.4.0 (pre-release due to source build)
- Python version: 3.8.5
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: 11 / 8
- GPU model and memory: RTX 2080, 8 GB VRAM

**Describe the current behavior**

Whenever `RaggedTensor` objects are returned from a nested `tf.map_fn` call, Tensorflow is unable to find a GPU implementation or some "unary variant unary_op function" by given the following `InternalError`:

```
2020-10-22 12:00:57.819438: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at constant_op.cc:243 : Internal: No unary variant unary_op function found for unary variant op enum: 1 Variant type_name: RaggedTensorVariant for device type: GPU
Traceback (most recent call last):
  File "/home/julilien/Programming/tf_gpu_issue.py", line 23, in <module>
    optimizer.minimize(f, [x])
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 496, in minimize
    grads_and_vars = self._compute_gradients(
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 539, in _compute_gradients
    loss = loss()
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 894, in _call
    return self._concrete_stateful_fn._call_flat(
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1933, in _call_flat
    forward_backward.record(flat_outputs)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1458, in record
    self._functions.record(
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1302, in record
    backward_function, to_record = self._wrap_backward_function(
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1250, in _wrap_backward_function
    variant_zeros_like[output_index] = default_gradient.zeros_like(output)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/ops/default_gradient.py", line 57, in zeros_like
    return array_ops.zeros_like(t)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2921, in zeros_like
    return zeros_like_impl(tensor, dtype, name, optimize)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 2982, in zeros_like_impl
    return gen_array_ops.zeros_like(tensor, name=name)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 12442, in zeros_like
    _ops.raise_from_not_ok_status(e, name)
  File "/home/julilien/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InternalError: No unary variant unary_op function found for unary variant op enum: 1 Variant type_name: RaggedTensorVariant for device type: GPU [Op:ZerosLike]
```

On CPU, however, it works without any issue, e.g., when I explicitly disable the GPU support (by setting the `CUDA_VISIBLE_DEVICES` to `-1`). I've also observed the same behavior in a "conventional" training setting within Keras training code. According to [this](https://github.com/tensorflow/tensorflow/issues/42047#issuecomment-691208579) comment, I would have expected this error not being an issue due to the CUDA version that I've used.

**Describe the expected behavior**

I would expect to be able to run this code on both CPU and GPU providing the same results.

**Standalone code to reproduce the issue**

I was able to (successfully) run this code on my CPU but not on a GPU (Nvidia RTX 2080, Driver Version: 455.23.05, CUDA Version: 11 with cuDNN 8).

```
import tensorflow as tf

if __name__ == '__main__':
    x = tf.Variable([1., 2., 3.], name='x', trainable=True, dtype=tf.float32)


    @tf.function
    def f():
        seg_data = tf.constant([[0, 0, 1], [0, 1, 2]])

        def seg_batch_fn(loc_segs):
            return tf.math.unsorted_segment_prod(x, loc_segs, tf.reduce_max(loc_segs) + 1)

        return tf.reduce_sum(tf.map_fn(seg_batch_fn, seg_data,
                                       fn_output_signature=tf.RaggedTensorSpec(shape=[None],
                                                                               dtype=tf.float32), name="seg_batch_fn"))


    optimizer = tf.optimizers.SGD()
    optimizer.minimize(f, [x])

```

**Other info / logs**
```
2020-10-22 11:29:44.986842: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-10-22 11:29:46.802265: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-10-22 11:29:46.802836: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2020-10-22 11:29:46.858113: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-22 11:29:46.858476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 computeCapability: 7.5
coreClock: 1.71GHz coreCount: 46 deviceMemorySize: 7.77GiB deviceMemoryBandwidth: 417.23GiB/s
2020-10-22 11:29:46.858494: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-10-22 11:29:46.860514: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-10-22 11:29:46.860564: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2020-10-22 11:29:46.861269: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2020-10-22 11:29:46.861446: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2020-10-22 11:29:46.863415: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2020-10-22 11:29:46.863890: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2020-10-22 11:29:46.863996: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-10-22 11:29:46.864087: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-22 11:29:46.864466: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-22 11:29:46.865040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2020-10-22 11:29:46.865065: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2020-10-22 11:29:47.286906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-22 11:29:47.286929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2020-10-22 11:29:47.286934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2020-10-22 11:29:47.287113: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-22 11:29:47.287681: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-22 11:29:47.287996: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-10-22 11:29:47.288286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6942 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5)
2020-10-22 11:29:50.715204: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2020-10-22 11:29:50.737811: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3600000000 Hz
Epoch 1/40
2020-10-22 11:30:03.130840: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-10-22 11:30:04.518337: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-10-22 11:30:04.822802: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
2020-10-22 11:30:17.122236: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at constant_op.cc:243 : Internal: No unary variant unary_op function found for unary variant op enum: 1 Variant type_name: RaggedTensorVariant for device type: GPU
```

**Comment by sachinprasadhs** [comment] 2021-06-02 10:24
Was able to reproduce your issue in Tensorflow GPU 2.5, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/2e6636659aaedfef6550905d9fbea798/44231.ipynb). Thanks!

**Comment by sanjoy** [comment] 2021-06-11 04:59
Closing as I believe this is a duplicate of https://github.com/tensorflow/tensorflow/issues/46635.  Please reopen if you disagree.

Separately @julilien, are you willing to contribute a PR fixing this issue?

**Closed by sanjoy** 2021-06-11 04:59 UTC
Labels: comp:gpu, stat:awaiting tensorflower, type:bug
