### ISSUE TITLE
tensorflow lite performance slower than regular tensorflow model

### ISSUE THREAD

**Issue by Red025** [tensorflow/tensorflow#35380] opened 2019-12-24 07:07 UTC
i converted object detection model into tensorflow lite and i am trying to run it in raspberry pi but the performance of tensorflow lite is slower in desktop. How can i increase the performance speed of the tensorflow lite?

**Comment by ravikyram** [comment] 2019-12-26 04:04
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Request you to provide simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Red025** [comment] 2019-12-26 04:45
- OS: Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 1.12
- Python version: 3.6
- Bazel version (if compiling from source): 0.15.2
- CUDA/cuDNN version: 9.0


    def __init__(self, model_path='TFLite_model/detect.tflite'):
        self.car_boxes = []
        # define lite graph and load tensorflow
        self.interpreter = Interpreter(model_path=model_path)
        self.interpreter.allocate_tensors()
        self.input_details = self.interpreter.get_input_details()
        self.output_details = self.interpreter.get_output_details()

    # Helper function to convert image into numpy array
    """def load_image_into_numpy_array(self, image):
        (im_width, im_height) = image.size
        return np.array(image.getdata()).reshape(
            (im_height, im_width, 3)).astype(np.uint8)
        # Helper function to convert normalized box coordinates to pixels"""

    def box_normal_to_pixel(self, box, dim):
        height, width = dim[0], dim[1]
        box_pixel = [int(box[0] * height), int(box[1] * width), int(box[2] * height), int(box[3] * width)]
        return np.array(box_pixel)

    def get_localization(self, image):
        # Resize and normalize image for network input
        frame = cv2.resize(image, (300, 300))
        frame = np.expand_dims(frame, axis=0)
        frame = (2.0 / 255.0) * frame - 1.0
        frame = frame.astype('float32')

        category_index = {1: {'id': 1, 'name': u'pothole'}}

        # run model
        self.interpreter.set_tensor(self.input_details[0]['index'], frame)
        self.interpreter.invoke()

        # get results
        boxes = self.interpreter.get_tensor(self.output_details[0]['index'])
        classes = self.interpreter.get_tensor(self.output_details[1]['index'])
        scores = self.interpreter.get_tensor(self.output_details[2]['index'])
        num = self.interpreter.get_tensor(self.output_details[3]['index'])

        visualization_utils.visualize_boxes_and_labels_on_image_array(image,
                                                                      np.squeeze(boxes[0]),
                                                                      np.squeeze(classes[0]+1).astype(np.int32),
                                                                      np.squeeze(scores[0]),
                                                                      category_index,
                                                                      use_normalized_coordinates=True,
                                                                      min_score_thresh=.4,
                                                                      line_thickness=3)

        # plt.figure(figsize=(9, 6))
        # plt.imshow(image)
        # plt.show()

        boxes = np.squeeze(boxes[0])
        classes = np.squeeze(classes[0]+1)
        scores = np.squeeze(scores[0])

This is the code I have been running but it is quite slow. Can you please tell me why its performance speed is so slow?

**Comment by abhinavsp0730** [comment] 2019-12-26 13:14
Hey, @Red025  I will suggest you for optimizing your tf.lite model. You can look here for Model optimization.
https://www.tensorflow.org/lite/performance/model_optimization
I hope this is what you're looking for.

**Comment by karimnosseir** [comment] 2019-12-30 21:03
Hi,

Not all kernels are optimized to run on desktop. What is the model you're trying to run ? can you share it ?

Thanks

**Comment by Red025** [comment] 2020-01-02 06:51
i have used ssd_mobilenet to train the model

**Comment by karimnosseir** [comment] 2020-01-08 22:45
Assigning to T.J who looks in work related to desktop.

T.J can you please have a look.

**Comment by talumbau** [comment] 2020-01-29 04:46
Hi,

May I ask, what model of Raspberry Pi are you using and may I see the bazel command you used to build? Thanks!

**Comment by dps42** [comment] 2020-03-02 15:24
Duplicate of https://github.com/tensorflow/tensorflow/issues/21698.
https://stackoverflow.com/questions/54093424/why-is-tensorflow-lite-slower-than-tensorflow-on-desktop

Tensorflow Lite is optimized for ARM neon, and is slower running on your x86_64 desktop.

**Comment by tensorflowbutler** [comment] 2021-02-01 14:12
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.

**Closed** 2021-02-09 05:52 UTC
Labels: TF 1.12, comp:lite, type:performance

**Comment by Nagarajb14** [comment] 2021-10-16 13:30
I am running it on TF2.0/Windows Desktop with GPU. ITs extremely slow
Can someone help me?

**Comment by LemonCANDY42** [comment] 2021-12-13 14:13
> I am running it on TF2.0/Windows Desktop with GPU. ITs extremely slow Can someone help me?

me too..
