### ISSUE TITLE
NotFoundError: ..._cudnn_rnn_ops.so [0.12.0]

### ISSUE THREAD

**Issue by meereeum** [tensorflow/tensorflow#6188] opened 2016-12-08 10:19 UTC
no luck with new build so far (running linux-64, conda 4.2.13, Python3.5)

`conda install -c jjhelmus tensorflow=0.12.0rc0 `

trying to run a script I get:
```
NotFoundError: /home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/_cudnn_rnn_ops.so: cannot open shared object file: No such file or directory
```

**Comment by kmario23** [comment] 2016-12-14 15:38
@meereeum I also face similar issue. Thus, a quick fix is to use tensorflow version  0.11, while the issue is being fixed.

**Comment by meereeum** [comment] 2016-12-14 15:45
@kmario23 yep - that's my strategy at the moment. the new embedding projector is really great though !

**Comment by gunan** [comment] 2016-12-19 08:11
@meereeum Could you provide a minimal example?
Maybe a subset of the script you are running?

If I can reproduce the problem, I might be able to help.
As our tests do not show that there is a problem, I am not sure if this is due to your installation or something in TF.

**Comment by meereeum** [comment] 2016-12-19 17:21
@gunan 

```
import tensorflow as tf
tf.contrib.layers.optimize_loss
```

(not even creating the tensorflow op, just referring to it)

```
---------------------------------------------------------------------
NotFoundError                       Traceback (most recent call last)
<ipython-input-2-00e1e97a2d9c> in <module>()
----> 1 tf.contrib.layers.optimize_loss

/home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/__init__.py in __getattr__(self, item)
     33     # Replace the lazy loader with the imported module itself.
     34     import importlib  # pylint: disable=g-import-not-at-top
---> 35     contrib = importlib.import_module('tensorflow.contrib')
     36     return getattr(contrib, item)
     37 

/home/miriam/anaconda2/envs/py35/lib/python3.5/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/home/miriam/anaconda2/envs/py35/lib/python3.5/importlib/_bootstrap.py in _gcd_import(name, package, level)

/home/miriam/anaconda2/envs/py35/lib/python3.5/importlib/_bootstrap.py in _find_and_load(name, import_)

/home/miriam/anaconda2/envs/py35/lib/python3.5/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/home/miriam/anaconda2/envs/py35/lib/python3.5/importlib/_bootstrap.py in _load_unlocked(spec)

/home/miriam/anaconda2/envs/py35/lib/python3.5/importlib/_bootstrap_external.py in exec_module(self, module)

/home/miriam/anaconda2/envs/py35/lib/python3.5/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/__init__.py in <module>()
     23 from tensorflow.contrib import copy_graph
     24 from tensorflow.contrib import crf
---> 25 from tensorflow.contrib import cudnn_rnn
     26 from tensorflow.contrib import distributions
     27 from tensorflow.contrib import factorization

/home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py in <module>()
     19 from __future__ import print_function
     20 
---> 21 from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnGRU
     22 from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnLSTM
     23 from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnRNNRelu

/home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py in <module>()
     26 
     27 _cudnn_rnn_ops_so = loader.load_op_library(
---> 28     resource_loader.get_path_to_datafile("_cudnn_rnn_ops.so"))
     29 
     30 _cudnn_rnn_common_doc_string = """

/home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/util/loader.py in load_op_library(path)
     40   if os.name != 'nt':
     41     path = resource_loader.get_path_to_datafile(path)
---> 42     ret = load_library.load_op_library(path)
     43     assert ret, 'Could not load %s' % path
     44     return ret

/home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     62       # pylint: disable=protected-access
     63       raise errors_impl._make_specific_exception(
---> 64           None, None, error_msg, error_code)
     65       # pylint: enable=protected-access
     66   finally:

NotFoundError: /home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/_cudnn_rnn_ops.so: cannot open shared object file: No such file or directory
```

**Comment by gunan** [comment] 2016-12-19 20:59
Hmm, I still cannot reproduce the issue.
Which OS are you using? Anything outside ubuntu, you will probably need to rebuild tensorflow from source.

Also, could you print the contents of the folder `/home/miriam/anaconda2/envs/py35/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/`

And finally, could you reinstall the rc1, and see if the issue is resolved in that version?

**Comment by kmario23** [comment] 2016-12-19 23:40
Hello,
  In r0.11, the contents of the folder ( ..../cudnn_rnn/python/ops/) is: 
 __init__.py
cudnn_rnn_ops.py
__init__.pyc
cudnn_rnn_ops.pyc
_cudnn_rnn_ops.so
__pycache__

Just wondering, could this be caused because of using anaconda2 but Python3.x & tf 0.12?

**Comment by gunan** [comment] 2016-12-19 23:54
Not sure if this can be caused by anaconda vs python version mismatch. But to me more and more this looks like an anaconda bug, as with python (native) python(virtualenv) it all works fine.

The only thing I am not sure is, your OS.
I can see that `_cudnn_rnn_ops.so` is there for you, so it should be accessible. The only reason it wont would be permissions or your OS not being able to read it, but I have not come accross that before.

**Comment by meereeum** [comment] 2016-12-20 02:22
I'm using debian (jessie), but have had no problems with tensorflow packages built from this anaconda contributor before...

in contrast to above, I see only
```
cudnn_rnn_ops.py
__init__.py
__pycache__
```

so am lacking the `_cudnn_rnn_ops.so` file indicated by the error

**Comment by meereeum** [comment] 2016-12-20 02:27
aha, definitely something with the anaconda build (which is unfortunate), as a `pip install` (with PYTHONPATH pointing to conda python) seems to work

**Comment by gunan** [comment] 2016-12-20 03:47
Thanks for verifying.
I will then close this issue as it seems to be an anaconda problem.
In the meantime, we will consider removing anaconda instructions.

**Closed by gunan** 2016-12-20 03:47 UTC
Labels: community support, type:build/install
