### ISSUE TITLE
set_weights crashes in tf.function because it tries to convert tensors into numpy arrays

### ISSUE THREAD

**Issue by bionicles** [tensorflow/tensorflow#32927] opened 2019-09-30 19:06 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2 rc2
- Python version: 3.6
- CUDA/cuDNN version: 10
- GPU model and memory: 1070, n/a

**Describe the current behavior**
if you try set_weights inside tf.function, your program crashes because keras attempts to convert tensors into numpy arrays

```
        self.layer.set_weights(weights)
CAUSES:
        x.assign(np.asarray(value, dtype=dtype(x)))
    anaconda3/envs/tfg/lib/python3.6/site-packages/numpy/core/_asarray.py:85 asarray
        return array(a, dtype, copy=False, order=order)

    TypeError: __array__() takes 1 positional argument but 2 were given
OR
       weights.append(w.numpy())
CAUSES:
    AttributeError: 'Tensor' object has no attribute 'numpy'
OR
        weights.append(w.eval())
CAUSES
    ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`
```

**Describe the expected behavior**
keras should work as described in the API without calling numpy behind the scenes in graph mode and crashing

**Code to reproduce the issue**
```
from functools import reduce
from operator import mul
import tensorflow as tf
B = tf.keras.backend
L = tf.keras.layers


def get_size(shape):
    return shape[0] if len(shape) is 1 else reduce(mul, shape)


def pipe(*args, repeats=1):

    def call(x):
        for i in range(repeats):
            for arg in args:
                x = arg(x)
        return x
    return call


class Hyper(L.Wrapper):

    def __init__(self, layer):
        super().__init__(layer)

    def build(self, shape):
        super().build(shape)
        shapes = [w.shape for w in self.layer.get_weights()]
        self.hypers = []
        for k, shape in enumerate(shapes):
            print("shape", k, shape)
            hyper = L.Dense(get_size(shape))
            super().__setattr__("hyper_{k}", hyper)
            reshape = L.Reshape(shape)
            super().__setattr__("reshape_{k}", reshape)
            self.hypers.append(pipe(hyper, reshape))
        self.flatten = L.Flatten()

    @tf.function
    def call(self, inputs):
        batch = B.int_shape(inputs)[0]
        Y = []
        for x in tf.split(inputs, batch):
            x = self.flatten(x)
            weights = []
            for hyper in self.hypers:
                w = hyper(x)
                w = tf.squeeze(w, 0)
                weights.append(w)
            self.layer.set_weights(weights)
            y = self.layer(x)
            Y.append(y)
        return tf.concat(Y, 0)

**Other info / logs**

**Comment by gadagashwini** [comment] 2019-10-01 08:01
@bionicles, Can you help us in reproducing the reported issue. When i tried, it throws `ImportError: cannot import name 'log'`. `tools` is installed but still its giving the error. Thanks!

**Comment by bionicles** [comment] 2019-10-12 14:38
ahh sorry, was at a conference, I will fix that

**Comment by bionicles** [comment] 2019-10-12 14:42
ill try again without tf.function tomorrow (long day of flights today)

**Comment by gadagashwini** [comment] 2019-10-17 07:06
@bionicles, Did you get a chance work on this. Thanks!

**Comment by gadagashwini** [comment] 2019-10-30 08:18
@bionicles, Any update!

**Comment by gadagashwini** [comment] 2019-11-08 09:34
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-11-08 09:34 UTC
Labels: TF 2.0-rc0, comp:keras, stat:awaiting response, type:support

**Comment by caio-davi** [comment] 2021-09-03 20:58
Any news on this issue?
