### ISSUE TITLE
Could not find device for node: {{node Qr}} = Qr[T=DT_HALF]

### ISSUE THREAD

**Issue by iCodite** [tensorflow/tensorflow#56610] opened 2022-06-28 15:22 UTC
* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2
* TensorFlow installed from (source or binary): Binary
* TensorFlow version (use command below): Tensorflow 2.7
* Python version: 3.7

I’m running into errors when using `tf.linalg.qr()` with inputs of half precision. The [documentation](https://www.tensorflow.org/api_docs/python/tf/linalg/qr) lists float16 as a supported type. Everything works fine for iterations of single precision.

Testing with this snippet returns a similar error to what happens when I run the source code below.
```
import tensorflow as tf

tn = tf.constant([ [1, 2], [3, 4] ], dtype=tf.half)
[Q, R] = tf.linalg.qr(tn);
```

[Source](https://github.com/cyanguwa/DeepLearningProfiling/blob/master/Basic-Kernels/python/rnn1d_tf2.py)
Output: 
```
  File "./rnn1d_tf2.py", line 184, in <module>
    enable_xla=parsed.enable_xla)
  File "./rnn1d_tf2.py", line 123, in main
    compfunc(input_image, basic_cell)
  File "./rnn1d_tf2.py", line 53, in run_forward
    output_result, states_cur, _ = rnn1d(input_image, basic_cell) 
  File "./rnn1d_tf2.py", line 41, in rnn1d
    whole_seq_output, final_memory_state, final_carry_state = tf.keras.layers.RNN(basic_cell, return_sequences=True, return_state=True)(input_data)
  File "/home/wano/virtual_environments/tf2/lib/python3.7/site-packages/keras/layers/recurrent.py", line 679, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/wano/virtual_environments/tf2/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/wano/virtual_environments/tf2/lib/python3.7/site-packages/keras/initializers/initializers_v2.py", line 620, in __call__
    q, r = tf.linalg.qr(a, full_matrices=False)
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Qr}} = Qr[T=DT_HALF, full_matrices=false]
All kernels registered for op Qr:
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_COMPLEX128]
 [Op:Qr]
```

**Comment by chunduriv** [comment] 2022-06-29 12:57
@iCodite,

Thanks for opening this issue. This is a duplicate of issue https://github.com/tensorflow/tensorflow/issues/56441.  Can you please close this issue, since it is already being tracked there?

**Comment by iCodite** [comment] 2022-06-29 19:49
Sure thing

**Comment by iCodite** [comment] 2022-07-19 20:02
@chunduriv The other thread has been closed but I am still experiencing the same issue for v2.7, v2.8, and release 2.9 even after fresh installs.

**Comment by iCodite** [comment] 2022-07-19 20:03
@chunduriv The other thread has been closed but I am still experiencing the same issue for v2.7, v2.8, and release 2.9 even after fresh installs.

**Comment by chunduriv** [comment] 2022-07-20 05:13
@iCodite,

>I am still experiencing the same issue for v2.7, v2.8, and release 2.9 even after fresh installs.

This issue is fixed in `tf-nightly` and it will be part of the next stable release `TF2.10`. 

For now please try to install `tf-nightly` as  `!pip install tf-nightly` (Not the versions mentioned above)

```
import tensorflow as tf
print(tf.__version__)

tn = tf.constant([ [1, 2], [3, 4] ], dtype=tf.half)
[Q, R] = tf.linalg.qr(tn);
print(Q)
print(R)
```
Output:
```
2.10.0-dev20220719
tf.Tensor(
[[-0.3164 -0.948 ]
 [-0.948   0.317 ]], shape=(2, 2), dtype=float16)
tf.Tensor(
[[-3.162 -4.43 ]
 [ 0.    -0.629]], shape=(2, 2), dtype=float16)
```
Thank you.

**Closed** 2022-08-03 06:46 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:apis, TF 2.7
