### ISSUE TITLE
TF 1.14 Python CPU single thread configuration

### ISSUE THREAD

**Issue by deHsien** [tensorflow/tensorflow#33627] opened 2019-10-23 06:28 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution**: Ubuntu 18.04
- **TensorFlow installed from**: pip2 install intel-tensorflow==1.14.0
- **TensorFlow version (use command below)**: 1.14
- **Python version**: 2.7

### Describe the problem
I'm going to participate in submissions limited to use CPU single thread. My implementation is in Python and I found that when construct tf.Session, a threadpool is created. However, I can't set it to single threaded even with the following suggested configuration:
```python
sess = tf.Session(config=tf.ConfigProto(
    intra_op_parallelism_threads=1,
    inter_op_parallelism_threads=1,
    device_count = {'CPU': 1}
))
```
How can I reach single threaded?  
Thank you !!

**Comment by ymodak** [comment] 2019-10-25 05:11
Are you using Intel MKL optimized TF version? Also can you try with following snippet;
```python
import tensorflow as tf
config = tf.ConfigProto(intra_op_parallelism_threads=1, 
                        inter_op_parallelism_threads=1, 
                        allow_soft_placement=True,
                        device_count = {'CPU': 1})
session = tf.Session(config=config)
```

**Comment by deHsien** [comment] 2019-10-25 06:44
Yes, I am using Intel MKL optimized TF version with pip2 install intel-tensorflow==1.14.0.
The suggestion above doesn't work either.

**Comment by preethivenkatesh** [comment] 2019-11-08 21:17
Could you please try export OMP_NUM_THREADS=1 to restrict the MKL threadpool to 1

**Comment by deHsien** [comment] 2019-11-13 06:35
I had tried and it didn't work either.

**Comment by wei-v-wang** [comment] 2019-11-13 06:50
to test single thread please use "numactl" or "taskset" to confine the application (TF) to one core. And then set inter/intra op/OMP_NUM_THREADS to 1

**Comment by crystalwan** [comment] 2019-12-20 03:26
I also encountered the same problem, did you solve it?

**Comment by deHsien** [comment] 2019-12-20 03:35
No.

**Comment by fisakhan** [comment] 2020-08-18 16:30
@wei-v-wang Can you please explain your answer with a simple example? "to test single thread please use "numactl" or "taskset" to confine the application (TF) to one core. And then set inter/intra op/OMP_NUM_THREADS to 1"

**Comment by wei-v-wang** [comment] 2020-08-18 19:10
Yes @fisakhan please see below for an example: 
export OMP_NUM_THREADS=1; numactl --physcpubind=2 --membind=0  python app.py --inter_op_parallelism_threads=1 --intra_op_parallelism_threads=1 
The above runs the app on physical CPU 2 (i.e. just the 3rd core).

**Comment by fisakhan** [comment] 2020-08-20 14:30
@deHsien Did you solve the problem? I'm facing the same problem.

**Comment by fisakhan** [comment] 2020-08-20 14:57
@deHsien Did you solve the problem? I'm facing the same problem.

**Comment by fisakhan** [comment] 2020-08-25 13:29
Thanks @wei-v-wang but I need to control the threads from within a c++ program that will be called by another party (NIST FRVT). In such a setting, the solution you provided doesn't work.
https://github.com/tensorflow/tensorflow/issues/42510
https://stackoverflow.com/questions/60206113/how-to-stop-tensorflow-from-multi-threading

**Comment by wei-v-wang** [comment] 2020-08-27 01:20
@fisakhan  Ok, it seems a complex task. I have two more comments:
1) Build TF from source but with --config=mkl_threadpool command, with this you do not need to worry about setting OMP_NUM_THREADS at all. *NOTE this needs to be with relatively newer version of TF*  
2) consider invoking in your C++ program the thread affinity APIs, https://man7.org/linux/man-pages//man3/pthread_setaffinity_np.3.html and somehow confine the TF to the specified set of cores?

**Comment by fisakhan** [comment] 2020-09-10 07:27
@wei-v-wang Once I Build TF 2.3 (latest version) from source with --config=mkl_threadpool command, what/how should I change my following piece of code to restrict the number of threads to 1? 
As soon as I load the model the number of threads reaches 8 ((using "top -H -b -n1 | grep example | wc -l" command on linux).
```
Status LoadGraph(string graph_file_name, std::unique_ptr<tensorflow::Session>* session) {
  tensorflow::GraphDef graph_def;
  Status load_graph_status =
      ReadBinaryProto(tensorflow::Env::Default(), graph_file_name, &graph_def);
  if (!load_graph_status.ok()) {
    return tensorflow::errors::NotFound("Failed to load compute graph at '",
                                        graph_file_name, "'");
  }
  
  // initialize the number of worker threads
    tensorflow::SessionOptions options;
    tensorflow::ConfigProto & config = options.config;
    config.set_inter_op_parallelism_threads(1);
    config.set_intra_op_parallelism_threads(1);
    config.set_use_per_session_threads(false); 

  session->reset(tensorflow::NewSession(options));
  Status session_create_status = (*session)->Create(graph_def);
  if (!session_create_status.ok()) {
    return session_create_status;
  }

  return Status::OK();
}
```

**Comment by wei-v-wang** [comment] 2020-09-14 16:22
You have already set inter/intra to 1, so I don't expect any other changes.  Adding @Srini511 for help. 
@Srini511  Please see the unexpected behaviour with mkl_threadpool above. @fisakhan  wanted to use single thread TF but are getting 8 threads even though inter/intra ops are set to 1.

**Comment by aliqing0122** [comment] 2020-09-28 08:32
@fisakhan I have the same problem, have you found a solution?

**Comment by fisakhan** [comment] 2020-09-28 10:33
@aliqing0122 Not yet. I'm still struggling to find its solution. I also tried suggestions provided at the following link but all in vain. Can you please share the solution if you find?
#42510
#33627
usnistgov/frvt#12
tensorflow/models#3176
#13853
https://stackoverflow.com/questions/47548145/understanding-tensorflow-inter-intra-parallelism-threads
https://stackoverflow.com/questions/60206113/how-to-stop-tensorflow-from-multi-threading
https://stackoverflow.com/questions/34389945/changing-the-number-of-threads-in-tensorflow-on-cifar10
https://stackoverflow.com/questions/39035639/importing-tensorflow-spawns-threads

**Comment by fisakhan** [comment] 2020-09-30 11:36
@aliqing0122  @wei-v-wang @Srini511  Do you agree with the reason given at the following link? It explains that TensorFlow cannot be a single threaded. 
https://stackoverflow.com/questions/48696900/why-tensorflow-creates-so-many-cpu-threads

**Comment by deHsien** [comment] 2020-10-05 08:21
I had migrated my models to mxnet for the single threaded constraint.

**Comment by fisakhan** [comment] 2020-10-05 11:33
@deHsien Thanks for your response. I'm also migrating my code to either mxnet or caffe. It is not possible to have a single threaded TensorFlow.

**Comment by NeoZhangJianyu** [comment] 2020-10-27 05:33
@fisakhan
`config.set_inter_op_parallelism_threads(1); config.set_intra_op_parallelism_threads(1);` can't work well because there would be many python libs to be executed in a AI script. It's possible other libs will enable multiple threads.

And above two parameters only limit the tensroflow train/infer. They can't limit other functions in Tensorflow like load model/dataset.

There is simple method to limit one thread, like:
numactl -C 1 python train.py

It sets the python running on the No.1 CPU core only.
If you use 'htop', you will see only No.1 CPU core is busy.

**Comment by fisakhan** [comment] 2020-10-27 09:07
@NeoZhangJianyu There are no other python libs that are under execution. I have verified that session creation and session run in TensorFlow are generating all the threads. We have already discussed your second suggestion https://github.com/tensorflow/tensorflow/issues/33627#issuecomment-680025939

**Comment by fisakhan** [comment] 2020-10-27 09:17
If I build TensorFlow from source then what code should I change to disable threading by TensorFlow?

**Comment by NeoZhangJianyu** [comment] 2020-10-28 07:37
@fisakhan 

Currently, the method to control thread number by external is only for process, instead of library (your case).
The current env variables/parameters are only impact the AI operation part. Like OMP_NUM_THREADS and inter_op_parallelism_threads, intra_op_parallelism_threads.

I think they are working for AI operation of Tensorflow. But they won't impact the other part of tensorflow to use single thread or multiple threads. For example, load dataset.

Your case need whole tensorflow use single thread.
It's a little hard: even if the source code of tensorflow is changed to use single thread, but it's hard to make sure the 3rd party libs used by tensorflow to use single thread.

I have two alternatives:

1. Modify the source code of tensorflow to set the thread number variables to 1 by hard code.
It's big work, and would be fault, because it can't control the 3rd party lib.

2. Refactor your software structure:
Sperate the software into two processes. The function call is changed to IPC.
Your code is running as child process and receive the parameters/return result by IPC.
So the thread number can be controlled by 'numactrl'.

**Comment by NeoZhangJianyu** [comment] 2020-12-03 01:58
@deHsien 

Could you close this issue?  Since your issue is not present.

**Closed** 2020-12-07 02:41 UTC
Labels: TF 1.14, comp:mkl, type:support

**Comment by NeoZhangJianyu** [comment] 2020-12-07 02:43
@deHsien 

Thank you very much!

**Comment by Koussailakadi** [comment] 2022-02-18 14:06
Hi guys, please, did anyone manage to solve this problem, I still have the problem of multi-threads running every time, and I can't find a solution.  ??

**Comment by louie-tsai** [comment] 2022-02-18 19:52
> For using 1 thread for your TF session, you could follow below comment.
https://github.com/tensorflow/tensorflow/issues/33627#issuecomment-675661637

Overall, threadpool will be created, so there should have 2 threads at last (master process + 1 thread from threadpool).

**Comment by fisakhan** [comment] 2022-02-19 19:06
@Koussailakadi why do you need it? I couldn't reduce the number of threads to 1 or 2 but solved the problem for which I required the reduce the threads.

**Comment by Koussailakadi** [comment] 2022-02-21 08:44
@fisakhan   I want to use tensorflow with MPI on a cluster of CPUs ( in C++), so I need to run a single thread at runtime. 

@louie-tsai  , thank you very much for your answer, I'm looking for how to run a single thread instead of two to use MPI afterwards.

**Comment by Koussailakadi** [comment] 2022-02-21 14:05
TF_Graph* Graph = TF_NewGraph();
    TF_Status* Status = TF_NewStatus();

    TF_SessionOptions* SessionOpts = TF_NewSessionOptions();
    TF_Buffer* RunOpts = NULL;

    const char* saved_model_dir = "../../models/LR_model.pb";
    const char* tags = "serve"; 
    int ntags = 1;

    //solution :///////////////////////////////////////////////////////////////////////////////////////////////
    uint8_t intra_op_parallelism_threads = 1;
    uint8_t inter_op_parallelism_threads = 1;
    uint8_t buf[]={0x10,intra_op_parallelism_threads,0x28,inter_op_parallelism_threads};
    TF_SetConfig(SessionOpts, buf,sizeof(buf),Status); 
    /////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    TF_Session* Session = TF_LoadSessionFromSavedModel(SessionOpts, RunOpts, saved_model_dir, &tags, ntags, Graph, NULL, Status);
    if(TF_GetCode(Status) == TF_OK)
    {
        printf("TF_LoadSessionFromSavedModel OK\n");
    }
    else
    {
        printf("%s",TF_Message(Status));
    }

![proc2TF_thr](https://user-images.githubusercontent.com/66485079/154969173-bbaeddb7-5666-428e-8cdd-a3be68024062.png)

this solution works, but always with 2 theads, a master that starts automatically, then a thread that does the task. as you see on the screenshot
