### ISSUE TITLE
Graph transform : fold_constant issue since tf v 1.5

### ISSUE THREAD

**Issue by LucasMahieu** [tensorflow/tensorflow#16545] opened 2018-01-29 15:53 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux centos 7
- **TensorFlow installed from (source or binary)**: with pip
- **TensorFlow version (use command below)**: 1.5.0 (vs 1.4.1)
- **Python version**: 2.7.5
- **Bazel version (if compiling from source)**: No
- **GCC/Compiler version (if compiling from source)**: No
- **CUDA/cuDNN version**: No
- **GPU model and memory**: No
- **Exact command to reproduce**:

Clone the tensorflow/models repo.
then 
```
cd models/research/slim/
python export_inference_graph.py \
  --model_name=inception_v1 \
  --image_size=224 \
  --output_file=/tmp/inception_v1.pb
```
Then freeze the graph : 
```
cd tensorflow/tensorflow/python/tools/
python freeze_graph.py \
--input_graph /tmp/inception_v1.pb \
--input_checkpoint /tmp/inception_v1.ckpt \
--output_graph /tmp/inception_v1_frozen.pb \
--input_binary True \
--output_node_names "InceptionV1/Logits/Predictions/Reshape_1"
```

Then in python do : 
```
import tensorflow as tf
from tensorflow.core.framework import graph_pb2
from tensorflow.python.platform import gfile
import tensorflow.tools.graph_transforms as graph_transforms
graph = graph_pb2.GraphDef()
with open("/tmp/inception_v1_frozen.pb", 'rb') as f:
    s = f.read()
    graph.ParseFromString(s)
graph = graph_transforms.TransformGraph(graph,
            ["input"], # inputs nodes
            ["InceptionV1/Logits/Predictions/Reshape_1"], # outputs nodes
            ['fold_constants()'])
with gfile.FastGFile("/tmp/inception_v1_frozen"+"_optimized.pbtxt", "w") as f:
    f.write(str(graph))
```

### Describe the problem
I am using the graph_transform to fold constants in by graph saved as .pb.
When I use the fold_constants() transformation, some inputs of some nodes are renamed but not the corresponding nodes in the whole graph. So the graph is no longer valid... 

I have an "input" placeholder in the graph.
And the node connected to this placeholder as an input name "input:0" instead of "input".

With the version 1.4.1 of tensorflow, I didn't have this issue.

To reproduce, follow the instructions below, and take a look to the /tmp/inception_v1_frozen_optimized.pbtxt graph. And search le node named "input" it is the input placeholder. Then search node which has an input named "input:0". This name ("input:0") is node a node of the graph.

**Comment by reedwm** [comment] 2018-01-30 19:21
/CC @petewarden, can you take a look?

**Comment by tensorflowbutler** [comment] 2018-03-03 07:48
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tadeegan** [comment] 2018-03-07 19:00
We also ran into this issue!

**Comment by mrfortynine** [comment] 2018-03-07 19:10
Just ran into this today too.

**Comment by tensorflowbutler** [comment] 2018-03-25 00:54
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-04-10 12:32
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatianashp** [comment] 2018-04-18 00:37
@mrfortynine Please post information on how we can reproduce the problem that you see.

**Comment by LucasMahieu** [comment] 2018-04-26 12:29
All information about how to reproduce are given in the fist post ... Does someone know how to solve this issue ?

**Comment by LucasMahieu** [comment] 2018-05-11 13:52
The problem is still not solved...

Given this example : 
```
name: "input"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
name: "Pad"
op: "Pad"
input: "input"
input: "Pad/paddings"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
```

The fold_constant() transformation change the name of the input tensor from "input" to "input:0".
But the node named input is still named "input" and not "input:0". 
like this : 
```
name: "input"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
name: "Pad"
op: "Pad"
input: "input:0"
input: "Pad/paddings"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
```

So, after this transformation of the graph, the connection between the input node "input" and the next node is broken.

(The input placeholder is not connected any more to the Pad node...)

**Comment by LucasMahieu** [comment] 2018-05-11 14:45
@tensorflower-gardener Do you think this issue is related to your commit :   
https://github.com/tensorflow/tensorflow/commit/38bcb3c02fbc5185d6c1fb7e8327a070284b66e4

**Comment by tensorflowbutler** [comment] 2018-05-27 03:02
Nagging Assignee @tatianashp: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-10 18:51
Nagging Assignee @tatianashp: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-06-25 19:14
Nagging Assignee @tatianashp: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-10 19:05
Nagging Assignee @tatianashp: It has been 59 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-07-25 19:00
Nagging Assignee @tatianashp: It has been 74 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-09 13:03
Nagging Assignee @tatianashp: It has been 89 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-08-24 21:45
Nagging Assignee @tatianashp: It has been 104 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-08 18:39
Nagging Assignee @tatianashp: It has been 119 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-09-23 18:46
Nagging Assignee @tatianashp: It has been 134 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-08 12:45
Nagging Assignee @tatianashp: It has been 149 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-10-23 12:48
Nagging Assignee @tatianashp: It has been 164 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-07 19:09
Nagging Assignee @tatianashp: It has been 179 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-11-22 18:44
Nagging Assignee @tatianashp: It has been 194 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by ymodak** [comment] 2019-08-23 23:34
Closing this issue due to staleness. Please check with the latest version of TensorFlow. Feel free to reopen if issue still persists. Thanks!

**Closed by ymodak** 2019-08-23 23:34 UTC

**Comment by herbakamil** [comment] 2019-10-15 13:03
@ymodak this issue occurs in TF 1.14
at least when using this set of transforms:
```
DEFAULT_TRANSFORMS = [
    'remove_nodes(op=Identity, op=CheckNumerics)',
    'merge_duplicate_nodes',
    'strip_unused_nodes',
    'fold_constants',
    'flatten_atrous_conv',
    'fold_batch_norms',
    'fold_old_batch_norms',
    'remove_control_dependencies',
    'sort_by_execution_order'
]
```
after removing fold_constants from this list rename doesn't occur.

I will solve it by manual rename of nodes in generated graph but it doesn't solve the problem for the other users.
