### ISSUE TITLE
I got This error by upgrading to TensorFlow 2.1: "AttributeError: 'Operation' object has no attribute '_graph'" .

### ISSUE THREAD

**Issue by hu26hase** [tensorflow/tensorflow#36954] opened 2020-02-21 12:11 UTC
My code is written under TensorFlow 2.0 and I run it on Ubuntu 18.04.04. The code is perfectly run with TensorFlow 2.0. But I need to use TensorFlow 2.1 because of some functionality of TensorFlow_addones library.  I upgrade the Tensorflow within my virtual environment by the command " conda install tensorflow-gpu" and run the code. The code run for the first epoch and save the result but as soon as it starts next epoch, it stop and show this error.
If I downgrade the TensorFlow to 2.0, again the code run without any problem. Does anybody know what is the issue?

**Comment by gadagashwini** [comment] 2020-02-24 06:03
@hu26hase, Can you share the standalone code to analyze the reported issue. Thanks!

**Comment by hu26hase** [comment] 2020-02-24 11:59
I figured it out that this Error is gone if I am not saving the model after each epoch.
I used tf.save_model.save(model, path). If I comment it then, then it will no error.

Then I use model.save(path), which is keras version of the saving model, it has no error.

**Comment by gadagashwini** [comment] 2020-02-26 08:37
@hu26hase, Closing this issue since its resolved. Please feel free to comment or open if you still face issue.Thanks

**Comment by gavinlive** [comment] 2020-03-16 16:26
I've reproduced this issue. It is a bug in TensorFlow-Keras. Please re-open as a bug.

Issue: Model cannot be used to .predict or __call__. 'Operation' object has no attribute '_graph'. Happens if you save a model that you later want to extract layers from. E.g. keras.model(inputs=prev_model.inputs, outputs=prev_model.layers[-1].output)

**Comment by gadagashwini** [comment] 2020-03-17 05:36
@gavinlive, Please provide the complete standalone code to reproduce the reported issue. Thanks

**Comment by gadagashwini** [comment] 2020-03-26 07:43
@gavinlive , Can you provide the code snippet to analyze the issue. Thanks!

**Comment by gadagashwini** [comment] 2020-04-02 09:17
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2020-04-02 09:17 UTC
Labels: TF 2.1, comp:keras, stat:awaiting response, type:support

**Comment by enkhee0906** [comment] 2020-04-19 14:14
@gadagashwini I also got the same error in Tensorflow 2.1. Error occurs when I call `tf.keras.layers.Conv2D` layer with `dilation_rate` greater than 1, after saving the model using `model.save`. Following is the standalone code producing the error. FYI, it gives no error in Tensorflow 2.0.

```
import tensorflow as tf
print(tf.__version__).   # 2.1.0

class ConvBlock(tf.keras.layers.Layer):
    """Conv + BatchNorm + ReLU"""
    def __init__(self,
            filters,
            kernel_size,
            strides=1,
            padding="SAME",
            dilation_rate=1,
            use_bias=False,
            kernel_initializer="he_normal",
            kernel_regularizer=None,
            **bn_params):
        super(ConvBlock, self).__init__()
        self.filters = filters
        self.kernel_size = kernel_size
        self.strides = strides
        self.padding = padding
        self.dilation_rate = dilation_rate
        self.use_bias = use_bias
        self.kernel_initializer = kernel_initializer
        self.kernel_regularizer = kernel_regularizer
        self.bn_params = bn_params
        
    def get_config(self) -> Dict[str, Any]:
        config = super().get_config()
        config.update({
            'filters': self.filters,
            'kernel_size': self.kernel_size,
            'strides': self.strides,
            'padding': self.padding,
            'use_bias': self.use_bias,
            'dilation_rate': self.dilation_rate,
            'kernel_initializer': self.kernel_initializer,
            'kernel_regularizer': self.kernel_regularizer,
            'bn_params': self.bn_params,
        })
        return config

    def build(self, input_shape):
        self.conv = tf.keras.layers.Conv2D(
            self.filters, 
            self.kernel_size, 
            strides=self.strides,
            padding=self.padding, 
            dilation_rate=self.dilation_rate, 
            use_bias=self.use_bias,
            kernel_initializer=self.kernel_initializer, 
            kernel_regularizer=self.kernel_regularizer)
        self.bn = tf.keras.layers.BatchNormalization(**self.bn_params)

    def call(self, x, training=None):
        x = self.conv(x)
        x = self.bn(x, training=training)
        x = tf.nn.relu(x)
        return x

conv_block = ConvBlock(filters=64, kernel_size=3, strides=1, dilation_rate=2)

inputs = tf.keras.Input(shape=[32, 32, 1], batch_size=1)
outputs = conv_block(inputs=inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs, name="debug")

x = tf.zeros((1, 32, 32, 1))
y = model(x)

model.save("initial") 

x = tf.zeros((1, 32, 32, 1))
y = model(x)
```

Error message I got:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-1239edcd3dd0> in <module>
      1 x = tf.zeros((1, 32, 32, 1))
----> 2 y = model(x)

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    820           with base_layer_utils.autocast_context_manager(
    821               self._compute_dtype):
--> 822             outputs = self.call(cast_inputs, *args, **kwargs)
    823           self._handle_activity_regularization(inputs, outputs)
    824           self._set_mask_metadata(inputs, outputs, input_masks)

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py in call(self, inputs, training, mask)
    715     return self._run_internal_graph(
    716         inputs, training=training, mask=mask,
--> 717         convert_kwargs_to_constants=base_layer_utils.call_context().saving)
    718 
    719   def compute_output_shape(self, input_shape):

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py in _run_internal_graph(self, inputs, training, mask, convert_kwargs_to_constants)
    889 
    890           # Compute outputs.
--> 891           output_tensors = layer(computed_tensors, **kwargs)
    892 
    893           # Update tensor_dict.

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    820           with base_layer_utils.autocast_context_manager(
    821               self._compute_dtype):
--> 822             outputs = self.call(cast_inputs, *args, **kwargs)
    823           self._handle_activity_regularization(inputs, outputs)
    824           self._set_mask_metadata(inputs, outputs, input_masks)

<ipython-input-3-1f8b326cfcd9> in call(self, x, training)
     52 
     53     def call(self, x, training=None):
---> 54         x = self.conv(x)
     55         x = self.bn(x, training=training)
     56         x = tf.nn.relu(x)

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    820           with base_layer_utils.autocast_context_manager(
    821               self._compute_dtype):
--> 822             outputs = self.call(cast_inputs, *args, **kwargs)
    823           self._handle_activity_regularization(inputs, outputs)
    824           self._set_mask_metadata(inputs, outputs, input_masks)

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/keras/layers/convolutional.py in call(self, inputs)
    207       inputs = array_ops.pad(inputs, self._compute_causal_padding())
    208 
--> 209     outputs = self._convolution_op(inputs, self.kernel)
    210 
    211     if self.use_bias:

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py in __call__(self, inp, filter)
   1133           call_from_convolution=False)
   1134     else:
-> 1135       return self.conv_op(inp, filter)
   1136     # copybara:strip_end
   1137     # copybara:insert return self.conv_op(inp, filter)

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py in __call__(self, inp, filter)
    638 
    639   def __call__(self, inp, filter):  # pylint: disable=redefined-builtin
--> 640     return self.call(inp, filter)
    641 
    642 

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py in _with_space_to_batch_call(self, inp, filter)
    614         input_shape=input_spatial_shape,
    615         base_paddings=base_paddings,
--> 616         block_shape=self.dilation_rate)
    617 
    618     dilation_rate = _with_space_to_batch_adjust(self.dilation_rate, 1,

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py in required_space_to_batch_paddings(input_shape, block_shape, base_paddings, name)
   3280   """
   3281   with ops.name_scope(name, "required_space_to_batch_paddings",
-> 3282                       [input_shape, block_shape]):
   3283     input_shape = ops.convert_to_tensor(
   3284         input_shape, dtype=dtypes.int32, name="input_shape")

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py in name_scope(name, default_name, values)
   6183     # pylint: enable=unidiomatic-typecheck
   6184     if graph_value is not None:
-> 6185       return graph_value.graph.name_scope(name)
   6186   return name_scope_v2(name or "")
   6187 

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py in graph(self)
    414   def graph(self):
    415     """The `Graph` that contains this tensor."""
--> 416     return self._op.graph
    417 
    418   @property

~/.miniconda3/envs/py3.6-tf2.1/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py in graph(self)
   2223   def graph(self):
   2224     """The `Graph` that contains this operation."""
-> 2225     return self._graph
   2226 
   2227   @property

AttributeError: 'Operation' object has no attribute '_graph'
```
Thank you for your time!

**Comment by yzhangswingman** [comment] 2020-07-30 16:56
Any updates on this issue? I ran into the same thing on the end of the 2nd training epoch. Strangely enough, it saved correctly on the first epoch end.
