### ISSUE TITLE
Recreate Variables in tf.function

### ISSUE THREAD

**Issue by sumanthratna** [tensorflow/tensorflow#39864] opened 2020-05-26 03:08 UTC
I'll preface this issue with the following:
- I've thought about this for a really long time (I've watched the talks and read the docs), and I can't find any solutions, which is why I'm creating this issue
- I know this is a pretty big change to the fundamental concept of "don't create `Variable`s in `tf.function`s" (see https://youtu.be/Up9CvRLIIIw?t=478 and https://www.tensorflow.org/guide/function#variables)

**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): no—this seems like it'll take a lot of time—I might be able to work on this in 2 years, when I'm in college :) 

**Describe the feature and the current behavior/state.**
Currently, creating a `tf.Variable` in a `tf.function` raises a `ValueError`, for good reason: https://youtu.be/Up9CvRLIIIw?t=431. 

Suppose I want to run a function multiple times for benchmarking purposes (I know `tf.test` exists). If this function creates Variables, I can't run it multiple times. Instead, I need to create the variables outside of `tf.function`, and pass them to the `tf.function`. This makes for unclear and illogical code. 

What I want is to be able to **create/delete/recreate Variables in a `tf.function`**. 

**Will this change the current API? How?**
I don't think so; I don't expect any new functions or classes to be added to the external API. 

**Who will benefit with this feature?**
People who wants to run a function (with new state) multiple times—e.g., benchmarking, hyperparameter optimization, etc. I realize that "with new state" isn't the best word choice; what I mean is I want each run to be independent, and create new `Variables`.

**Any Other info.**
For the use-cases I have in mind, I think being able to delete Variables is what we need. I have no problem deleting `tf.Variable`s at the end of the `tf.function`. The reason I mention being able to create `tf.Variable`s in `tf.function`s is because I might be missing a use-case. 

I'm also unsure if this will help: `tf.variable_creator_scope`

**Comment by kkimdev** [comment] 2020-05-27 10:52
I'm sorry for the trouble but this was an explicit API decision now allowing variable recreation in tf.function.

If you don't want to create variable outside, there are two workarounds:

```

# Creating a new @tf.function instance
foo_tf_function = tf.function(foo)

#
```

**Comment by sumanthratna** [comment] 2020-05-27 17:46
Thanks for the reply! Is it possible to add a method called `tf.reset_all_variables` that `del`s `Variable`s and removes them under the hood? IMO this would make for much cleaner and readable code (although I do recall that TF 2 is aiming to do less Variable management on its own). The variable-creations would still be in the method graph, but after each function call, they would be appropriately deleted, allowing for them to be recreated. Maybe something like https://github.com/tensorflow/tensorflow/issues/859 for TF 2?

To anyone else who's come across this thread, this might help: https://github.com/tensorflow/tensorflow/issues/27120.

**Comment by sumanthratna** [comment] 2020-06-09 14:24
Hi—I know you all are very busy, but I'd like to bump this thread. If what I described earlier doesn't make sense, I'm really just asking for:

- https://www.youtube.com/watch?v=MSXouZPyTrc&feature=youtu.be&t=983

At the time of the talk, Dr. Passos mentioned that both eager and graph semantics are easy to implement—would it be possible to allow the user to choose which execution mode to go with (e.g., via `tf.config` or with a keyword argument in `tf.function`)? 

In the talk, [Dr. Passos mentions, "once there's no more TF v1 code out there, then I think we can flip the flag and allow all variable creation inside `tf.function` with fully eager semantics, but that's going to take a while."](https://youtu.be/MSXouZPyTrc?t=1153) If there hasn't been a change of heart, do you have an ETA on when TF 1.x will be fully out of business? 
- > In the future we may want to allow for function local `tf.Variable`s, which are created and destroyed each time the decorated function is invoked.

(from the original [RFC](https://github.com/tensorflow/community/blob/master/rfcs/20180918-functions-not-sessions-20.md), also see ["Function-local state"](https://github.com/tensorflow/community/blob/master/rfcs/20180918-functions-not-sessions-20.md#function-local-state))

---

Also: is `tf.init_scope` any help in recreating variables in functions? I tried and it still raised `ValueError`. Perhaps we could allow recreating Variables (e.g., eager semantics) as long as their creation is within a `tf.init_scope` context manager. 

I'm really sorry for consistently bugging you guys; I totally understand if this is something that you all don't want to work on.

**Comment by saikumarchalla** [comment] 2020-10-05 17:13
@sumanthratna  Closing this issue since it was the intended behavior. Please feel free to re-open the issue if you have any concern.Thanks!

**Closed by saikumarchalla** 2020-10-05 17:13 UTC
Labels: comp:core, type:feature

**Comment by sjtusmartboy** [comment] 2021-08-12 13:25
@sumanthratna hi,have you solved this issue and by how? I think this is really the demand that tf should work on because I've seen many tf users who have raised this issue on stackoverflow and github. Although it's the rule the variable inside the tf.function should not be created twice, but this design may not be reasonable because it's not what users need.

**Comment by sumanthratna** [comment] 2021-08-12 14:43
hi @sjtusmartboy, I think the TensorFlow team has taken a look at this (see https://github.com/tensorflow/tensorflow/issues/27120) and they have added an internal flag: 
https://github.com/tensorflow/tensorflow/blob/5cbc6f7e53c5a55753fcdf2877b278a8f48970d5/tensorflow/python/eager/def_function.py#L103

I'm not sure on the best tf/python syntax to use this feature, but something like this should work: 

```python
from tensorflow.python.eager import def_function  # def_function is the same as tf.function

def_function.ALLOW_DYNAMIC_VARIABLE_CREATION = True

@def_function.function
def myfunc(val):
    tf.Variable(val)

myfunc(0.3)
myfunc(0.9)
```

see https://github.com/tensorflow/tensorflow/blob/9d97737008bae61a3a96abdac8cd676e025fd3c0/tensorflow/python/eager/def_function_test.py for more examples

**Comment by sjtusmartboy** [comment] 2021-08-13 01:47
@sumanthratna  Thanks for your immediate answer. This is the first time for me to know this flag. I've tried your example, but somehow it gives out the error `ValueError: tf.function-decorated function tried to create variables on non-first call.` Any idea what happens?

**Comment by sjtusmartboy** [comment] 2021-08-13 03:19
For the testcase you mentioned above, I've tried it and found it not easy to understand the function of that flag because whether 
`def_function.ALLOW_DYNAMIC_VARIABLE_CREATION` is true of false, the following testcase would pass.

```
from tensorflow.python.eager import def_function  # def_function is the same as tf.function
from tensorflow.python.ops import variables
from absl.testing import parameterized
from tensorflow.python.platform import test

class DefFunctionTest(test.TestCase, parameterized.TestCase):

    def testMethodAllowDynamicVariable(self):
        class Foo:

            def __init__(self):
                self._flag_keyed_vars = {}
                self.trace_count = 0

            def __call__(self, var_creation_flag):
                self.compute(var_creation_flag)
                return self._flag_keyed_vars[var_creation_flag]

            @def_function.function
            def compute(self, var_creation_flag):
                self.trace_count += 1
                if var_creation_flag not in self._flag_keyed_vars:
                    if var_creation_flag:
                        self._flag_keyed_vars[var_creation_flag] = variables.Variable(1.0)
                    else:
                        self._flag_keyed_vars[var_creation_flag] = variables.Variable(2.0)

        def_function.ALLOW_DYNAMIC_VARIABLE_CREATION = False
        foo = Foo()
        self.assertAllEqual(foo(True), 1.0)
        self.assertEqual(foo.trace_count, 2)
        self.assertAllEqual(foo(True), 1.0)
        self.assertEqual(foo.trace_count, 2)
        self.assertAllEqual(foo(False), 2.0)
        self.assertEqual(foo.trace_count, 3)
```

**Comment by sjtusmartboy** [comment] 2021-08-13 12:13
@sumanthratna Also would you please help me look at this demand, https://github.com/tensorflow/tensorflow/issues/51453. Is it possible to solve it with `def_function.ALLOW_DYNAMIC_VARIABLE_CREATION`. Thanks a million.

**Comment by sumanthratna** [comment] 2021-08-16 19:39
@sjtusmartboy I think I may be understanding the purpose of that flag, then—sorry for the misleading suggestion! I think for now it is safe to assume that there's no way to create `Variable`s in a `function` (I'm also confused by the test-case you sent)

Regarding the issue that you linked, I'm not sure how to resolve it; I think you'll have to use eager execution if possible
