### ISSUE TITLE
updation issue

### ISSUE THREAD

**Issue by geet2019** [tensorflow/tensorflow#39292] opened 2020-05-08 02:46 UTC
https://github.com/geet2019/rgn
sir I wanted to implement this code. but his instruction is to have python 2.7 and TensorFlow in between 1.4 and 1.11
doubt :
Can I able to execute in Python 3.7 and in TensorFlow 2.1?
whether I am able to execute all functions in TensorFlow <1.11 in TensorFlow 2.1. If not, is there any possible way to do so?
As you know "https://github.com/geet2019/rgn " this a GitHub project ? is there any way to execute it in GitHub desktop itself. If so, can you please provide me with help as early as possible.

Looking forward to a quick response from you that helps me a lot.
thank you so much for your valuable support for my work.

**Comment by amahendrakar** [comment] 2020-05-08 14:41
@geet2019,
You'll have to migrate your code from TensorFlow 1.x to 2.x, in order to run the code. Please take look at [this guide](https://www.tensorflow.org/guide/migrate) which might help you in this case.

Also, this question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is a larger community that reads questions there. Thanks!

**Comment by mihaimaruseac** [comment] 2020-05-08 18:07
Closing as not a coding issue but a question better asked on StackOverflow.

**Closed by mihaimaruseac** 2020-05-08 18:07 UTC
Labels: stat:awaiting response, type:support

**Comment by geet2019** [comment] 2020-05-09 01:55
thanking you for your reply and suggestion
Regards
Geethu S
