### ISSUE TITLE
Non-deterministic behaviour: tf.math.unsorted_segment_sum uses CUDA Atomic Operations

### ISSUE THREAD

**Issue by gavinlive** [tensorflow/tensorflow#39751] opened 2020-05-21 11:39 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):v2.1.0-rc2-17-ge5bf8de and v2.2.0-rc4-8-g2b96f3662b
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1.105 and 7.6.5.32
- GPU model and memory: RTX6000 24GB

**Describe the current behavior**
Currently, tf.math.unsorted_segment_sum uses non-deterministic GPU kernels which lead significant failings in the TensorFlow determinism venture. Other TensorFlow functions make use of tf.math.unsorted_segment_sum such as tf.gather (on backprop).

Some functions affected that I've discovered:
 - tfa.image.dense_image_warp (on backprop)
 - tf.gather (on backprop)

**Describe the expected behavior**

When TF_DETERMINISTIC_OPS=1,  tf.math.unsorted_segment_sum should use deterministic GPU kernels leading to reproducibility.

**Who will benefit from this bug fix correction?**
Determinism is an extremely important part of our venture into deep learning as a community. Without determinism, it is hard to reliably tune hyperparameters and conduct other types of investigations such ablation studies. Whilst many TensorFlow operations have a deterministic alternative upon setting the OS Environment variable TF_DETERMINISTIC_OPS=1, tf.math.unsorted_segment_sum seems to have fallen under the radar, perhaps because other operations took priority (such as tf.reduce_sum). 

Introducing this level of determinism to TensorFlow will allow it to be a better candidate for deep learning deployments in more sensitive environments such as medical. I.e. it doesn't make sense that a radiologist will look at result during one scan and then conduct the same scan and get a different result. It also affects the public's trust in AI venture altogether. ~~As far as I'm aware, PyTorch offers full deterministic capabilities (perhaps due to the benefit of hindsight with TensorFlow not having it).~~ 

**Standalone code to reproduce the issue**
Code to reproduce the issue:
(Edit: Please see the code here instead: https://github.com/tensorflow/tensorflow/issues/39751#issuecomment-632590302

I've added seed settings, TF_DETERMINISTIC_OPS, etc... and the issue still reproduces)

```
import tensorflow as tf
import numpy as np

num_segments = 4
data = tf.random.normal([30, 256, 256])
data = tf.constant(data)
segments = np.random.randint(low=0, high=num_segments, size=data.shape)

for i in range(5):
    reduced_summed = tf.math.unsorted_segment_sum(data, segments, num_segments)
    print(reduced_summed)
```
Output:

tf.Tensor([-273.92117  380.23163 1279.9718  -839.6437 ], shape=(4,), dtype=float32)
tf.Tensor([-273.92395  380.22168 1279.9834  -839.62573], shape=(4,), dtype=float32)
tf.Tensor([-273.91425  380.22177 1279.9773  -839.62976], shape=(4,), dtype=float32)
tf.Tensor([-273.9177  380.2243 1279.9733 -839.6427], shape=(4,), dtype=float32)
tf.Tensor([-273.91568  380.2217  1279.9747  -839.64166], shape=(4,), dtype=float32)

# Note: all printed results are different but in reality, they should be the same

Colab notebook with this code can be found at : https://colab.research.google.com/drive/1HNHSfERQ_IDDDM7bgabii9TQPufpsutp?usp=sharing

** Unit Tests **
Essentially, the code above will produce the same result, rather than a different result every time it is executed in the for loop.

Coming soon.

**Other info / logs**

More information about the GPU operation can be found at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/segment_reduction_ops_gpu.cu.cc

More information coming soon

**Comment by amahendrakar** [comment] 2020-05-22 08:20
@gavinlive,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by gavinlive** [comment] 2020-05-22 08:42
> @gavinlive,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

Hi, the code to reproduce the issue has now been added to the first post and again here:
```
import tensorflow as tf
import numpy as np

num_segments = 4
data = tf.random.normal([30, 256, 256])
data = tf.constant(data)
segments = np.random.randint(low=0, high=num_segments, size=data.shape)

for i in range(5):
    reduced_summed = tf.math.unsorted_segment_sum(data, segments, num_segments)
    print(reduced_summed)
```
Output:

tf.Tensor([-273.92117  380.23163 1279.9718  -839.6437 ], shape=(4,), dtype=float32)
tf.Tensor([-273.92395  380.22168 1279.9834  -839.62573], shape=(4,), dtype=float32)
tf.Tensor([-273.91425  380.22177 1279.9773  -839.62976], shape=(4,), dtype=float32)
tf.Tensor([-273.9177  380.2243 1279.9733 -839.6427], shape=(4,), dtype=float32)
tf.Tensor([-273.91568  380.2217  1279.9747  -839.64166], shape=(4,), dtype=float32)

# Note: all printed results are different but in reality, they should be the same

**Comment by gavinlive** [comment] 2020-05-22 09:18
> @gavinlive,
> In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

Please add TF2.2 label.

Results are reproducible in TF2.2 as well.

For completeness, I've added seeds and TF_DETERMINISTIC_OPS within Python script:

```
import os
seed=1114
os.environ['TF_DETERMINISTIC_OPS'] = '1'
os.environ['PYTHONHASHSEED'] = str(seed)
import tensorflow as tf
import numpy as np
import random
random.seed(seed)
np.random.seed(seed)
tf.random.set_seed(seed)

print(tf.version.VERSION)
print(tf.version.GIT_VERSION)



num_segments = 4
data = tf.random.normal([30, 256, 256])
data = tf.constant(data).numpy()
segments = np.random.randint(low=0, high=num_segments, size=data.shape)



for i in range(5):
    #data = tf.cast(data, tf.float64)
    reduced_summed = tf.math.unsorted_segment_sum(data, segments, num_segments)
    #reduced_summed = tf.cast(reduced_summed, tf.float32)
    print(reduced_summed)

# Note: all printed results are different but in reality, they should be the same
```

**Comment by gavinlive** [comment] 2020-05-22 10:24
Added a Colab notebook also: https://colab.research.google.com/drive/1HNHSfERQ_IDDDM7bgabii9TQPufpsutp

**Comment by amahendrakar** [comment] 2020-05-27 17:38
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/17820dde35568591baa98206d1388a20/39751-2-1.ipynb), [TF v2.2](https://colab.research.google.com/gist/amahendrakar/fca593f80e7de9d32a3665bd98c1a531/39751-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/1d2d581d32e765c575bf52e19a1a7856/39751-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by duncanriach** [comment] 2020-06-03 04:48
@gavinlive,

> PyTorch offers full deterministic capabilities

This is not true. TensorFlow's support for GPU determinism is now at least comparable to that of PyTorch.

Both TensorFlow and PyTorch have (had) various ops that function non-deterministically on GPU, some that have already been addressed, some that are in line to be addressed, some that are coming into awareness (such as this one), and likely others that are still to be discovered.

**Comment by gavinlive** [comment] 2020-06-03 13:54
> @gavinlive,
> 
> > PyTorch offers full deterministic capabilities
> 
> This is not true. TensorFlow's support for GPU determinism is now at least comparable to that of PyTorch.
> 
> Both TensorFlow and PyTorch have (had) various ops that function non-deterministically on GPU, some that have already been addressed, some that are in line to be addressed, some that are coming into awareness (such as this one), and likely others that are still to be discovered.
> 
> We are gradually working though these non-deterministic ops, identifying them, confirming that they truly operate non-deterministically, and implementing/testing fully-functional deterministic versions of them. These deterministic versions are then either enabled via `TF_DETERMINISTIC_OPS` (or a future equivalent) or completely replace the original, if that does not negatively impact performance.
> 
> Thank you for bringing the non-determinism of `unsorted_segment_sum` to our attention.

Thanks for that! :) I'll correct my comment.

**Comment by gavinlive** [comment] 2020-06-03 13:55
> **System information**
> 
> * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04.3
> * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> * TensorFlow installed from (source or binary): binary
> * TensorFlow version (use command below):v2.1.0-rc2-17-ge5bf8de and v2.2.0-rc4-8-g2b96f3662b
> * Python version: 3.7.7
> * Bazel version (if compiling from source):
> * GCC/Compiler version (if compiling from source):
> * CUDA/cuDNN version: 10.1.105 and 7.6.5.32
> * GPU model and memory: RTX6000 24GB
> 
> **Describe the current behavior**
> Currently, tf.math.unsorted_segment_sum uses non-deterministic GPU kernels which lead significant failings in the TensorFlow determinism venture. Other TensorFlow functions make use of tf.math.unsorted_segment_sum such as tf.gather (on backprop).
> 
> Some functions affected that I've discovered:
> 
> * tfa.image.dense_image_warp (on backprop)
> * tf.gather (on backprop)
> 
> **Describe the expected behavior**
> 
> When TF_DETERMINISTIC_OPS=1, tf.math.unsorted_segment_sum should use deterministic GPU kernels leading to reproducibility.
> 
> **Who will benefit from this bug fix correction?**
> Determinism is an extremely important part of our venture into deep learning as a community. Without determinism, it is hard to reliably tune hyperparameters and conduct other types of investigations such ablation studies. Whilst many TensorFlow operations have a deterministic alternative upon setting the OS Environment variable TF_DETERMINISTIC_OPS=1, tf.math.unsorted_segment_sum seems to have fallen under the radar, perhaps because other operations took priority (such as tf.reduce_sum).
> 
> Introducing this level of determinism to TensorFlow will allow it to be a better candidate for deep learning deployments in more sensitive environments such as medical. I.e. it doesn't make sense that a radiologist will look at result during one scan and then conduct the same scan and get a different result. It also affects the public's trust in AI venture altogether. As far as I'm aware, PyTorch offers full deterministic capabilities (perhaps due to the benefit of hindsight with TensorFlow not having it).
> 
> **Standalone code to reproduce the issue**
> Code to reproduce the issue:
> (Edit: Please see the code here instead: [#39751 (comment)](https://github.com/tensorflow/tensorflow/issues/39751#issuecomment-632590302)
> 
> I've added seed settings, TF_DETERMINISTIC_OPS, etc... and the issue still reproduces)
> 
> ```
> import tensorflow as tf
> import numpy as np
> 
> num_segments = 4
> data = tf.random.normal([30, 256, 256])
> data = tf.constant(data)
> segments = np.random.randint(low=0, high=num_segments, size=data.shape)
> 
> for i in range(5):
>     reduced_summed = tf.math.unsorted_segment_sum(data, segments, num_segments)
>     print(reduced_summed)
> ```
> 
> Output:
> 
> tf.Tensor([-273.92117 380.23163 1279.9718 -839.6437 ], shape=(4,), dtype=float32)
> tf.Tensor([-273.92395 380.22168 1279.9834 -839.62573], shape=(4,), dtype=float32)
> tf.Tensor([-273.91425 380.22177 1279.9773 -839.62976], shape=(4,), dtype=float32)
> tf.Tensor([-273.9177 380.2243 1279.9733 -839.6427], shape=(4,), dtype=float32)
> tf.Tensor([-273.91568 380.2217 1279.9747 -839.64166], shape=(4,), dtype=float32)
> 
> # Note: all printed results are different but in reality, they should be the same
> Colab notebook with this code can be found at : https://colab.research.google.com/drive/1HNHSfERQ_IDDDM7bgabii9TQPufpsutp?usp=sharing
> 
> ** Unit Tests **
> Essentially, the code above will produce the same result, rather than a different result every time it is executed in the for loop.
> 
> Coming soon.
> 
> **Other info / logs**
> 
> More information about the GPU operation can be found at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/segment_reduction_ops_gpu.cu.cc
> 
> More information coming soon

**Comment by duncanriach** [comment] 2020-07-02 23:31
By the way, I wouldn't call this a bug. This a feature request. This is a request to extend the functionality of `TF_DETERMINISTIC_OPS`.

**Comment by duncanriach** [comment] 2020-07-03 04:35
I've reproduced this nondeterminism with the code in [this gist](https://gist.github.com/duncanriach/136fe08905af67f30c4eb775b34290d7). There's an issue with your code above, @gavinlive, in that the size of segments is not equal to the size of the first dimension of data.  With this addressed, the GPU-specific non-determinism is still present, but the API of the op is being more correctly followed. The code in the gist also includes a post-reduction of the summed segments in order to demonstrate the variation of a final scalar result. The gist runs compared the functionality on the CPU and the GPU and produces the following output:

```
on CPU: -1957.1707153320312
on CPU: -1957.1707153320312
on CPU: -1957.1707153320312
on CPU: -1957.1707153320312
on CPU: -1957.1707153320312
on GPU: -1957.1702117919922
on GPU: -1957.1699676513672
on GPU: -1957.1700134277344
on GPU: -1957.1698608398438
on GPU: -1957.1700744628906
```

**Comment by duncanriach** [comment] 2020-07-23 02:14
This [other issue](https://github.com/NVIDIA/framework-determinism/issues/25) led me to look at `tf.math.segment_sum` and I've confirmed that it also injects nondeterminism when running on a GPU. I have updated the aforementioned [gist](https://gist.github.com/duncanriach/136fe08905af67f30c4eb775b34290d7) to repro and also to maximize the probability of nondeterminism and minimize the run time. The output looks like this:

```
-----------------------------------
tf.math.unsorted_segment_sum on cpu

  71.9827442169189
  71.9827442169189
  71.9827442169189
  71.9827442169189
  71.9827442169189
-----------------------------------
tf.math.unsorted_segment_sum on gpu

  71.9828128814697
  71.9828295707703
  71.9827938079834
  71.9828252792358
  71.9828085899353
-----------------------------------
tf.math.segment_sum on cpu

  71.9828114509583
  71.9828114509583
  71.9828114509583
  71.9828114509583
  71.9828114509583
-----------------------------------
tf.math.segment_sum on gpu

  71.9828183650970
  71.9828221797943
  71.9828226566315
  71.9828269481659
  71.9828283786774
-----------------------------------
```

**Comment by dangthatsright** [comment] 2020-07-24 22:58
@gavinlive 
Thanks for your fix for `tf.gather`, I was also facing this issue. However, it seems like `tf.gather` doesn't explicitly call `unsorted_segment_sum` if `axis=0` in `tf.gather` https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/array_grad.py#L642. But `gen_math_ops.unsorted_segment_sum` does indeed get called at some point. I'm not familiar with how tensorflow code works and how gradients are automatically computed so I couldn't make the necessary changes in `array_grad.py`. Instead I just changed `unsorted_segment_sum` directly in `tensorflow/python/ops/gen_math_ops.py`, which seemed to do the trick for me!

**Comment by duncanriach** [comment] 2020-07-25 04:28
@dangthatsright,

Looking back at the email conversation I had with @gavinlive before he created this issue, I can see that I traced down to [`_GatherGrad`](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/array_grad.py#L543-L564) in `tensorflow/python/ops/array_grad.py`, which _always_ calls [`_IndexedSlicesToTensorNoWarning`](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/array_grad.py#L529-L540) in the same file, which in turn calls `math_ops.unsorted_segment_sum` (the internal way of calling `tf.math.unsorted_segment_sum`).

Based on your comments above, I see that for the TF2 API, the `tf.gather` forward path is implemented by [`gather_v2`](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/array_ops.py#L4681-L4695) in `tensorflow/python/ops/array_ops.py`. which, incidentally, immediately calls the API 1 version of the gather functionality (named `gather`). However, as your comment implies, the gradient function in the TF 2 API is implemented by [`GatherV2`](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/array_grad.py#L618-L688). Which, however, again also _always_ calls `_IndexedSlicesToTensorNoWarning` in the same file, which in turn (as before) calls `math_ops.unsorted_segment_sum` (the internal way of calling `tf.math.unsorted_segment_sum`).

This is why/how the API-equivalent version of `tf.math.unsorted_segment_sum` is _always_ called to calculate the backprop of `tf.gather`.

The python modules (files) with names starting with `gen_`, such as `gen_math_ops` are automatically generated by the TensorFlow build process (from protobuffer interface specifications), and are part of the linkage between the C++/CUDA code and the python API code. When the code in `tensorflow/python/ops` calls a function in `gen_*_ops`, I see it as calling down to that lower level.

I can't find where `tf.math.segment_sum` or `tf.math.unsorted_segment_sum` are explicitly exported (with @tf_export), even in [`tensorflow/python/ops/math_ops.py`](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/math_ops.py) and I'm assuming that the API linkage gets automatically generated (using [`tensorflow/core/api_def/python_api/api_def_UnsortedSegmentSum.pbtxt`](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/core/api_def/python_api/api_def_UnsortedSegmentSum.pbtxt)) and that there doesn't need to be any intermediate code.

What specifically did you change about `unsorted_segment_sum` in `tensorflow/python/ops/gen_math_ops.py` to get deterministic functionality? I'm wondering if this change could be implemented in `tensorflow/python/ops/array_grad.py` under the control of `TF_DETERMINISTIC_OPS` as a temporary solution until we implement deterministic CUDA kernels for these ops.

**Comment by dangthatsright** [comment] 2020-07-25 21:11
You are right that gather always calls `_IndexedSlicesToTensorNoWarning`, so I was curious as to why it wasn't giving me deterministic results still. After putting in prints right before https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/array_grad.py#L533 and L538, I found that my code always takes the first return path. (Or maybe it doesn't and the print gets optimized out or something?). In fact I put prints before all the `math_ops.unsorted_segment_sum` in the file and I saw nothing so I am a bit at loss as to which part of my code is actually calling this function.

Anyways, the change I made is to the `gen_math_ops.py` file is a bit hacky haha
Following the hint: 
Replace the original `unsorted_segment_sum` with:

```
def unsorted_segment_sum(data, segment_ids, num_segments, name=None):
  orig_dtype = data.dtype
  if 'float' in str(data.dtype):
    data = cast(data, _dtypes.float64)
  elif 'complex' in str(data.dtype):
    data = cast(data, _dtypes.complex128)
  result = unsorted_segment_sum_base(data, segment_ids, num_segments, name)
  result = cast(result, orig_dtype)
  return result
```

and then take the code previously in `unsorted_segment_sum` and put it in

`
def unsorted_segment_sum_base(data, segment_ids, num_segments, name=None):
`

This gave me deterministic results.

It could be possible that I have another function calling `unsorted_segment_sum` but that seems unlikely because calling `tf.gather` with cpu also allowed me to get deterministic results.

**Comment by duncanriach** [comment] 2020-07-28 04:08
Ah, right. Yes, I forgot about the temporary solution that @gavinlive provided ([link to his comment](https://github.com/tensorflow/tensorflow/issues/39751#issuecomment-632618778) above). I reviewed this back when he wrote it and then I got side-tracked and I forgot to come back and comment on it. This is a super-accumulator style solution. It's good to know that it doesn't have a significant negative performance impact in the context of your application.

When I looked at this briefly before, I was not convinced that this would provide a perfectly deterministic solution. I was concerned that there might be rare cases where it would produce a different result between runs. I've been thinking about this some more today and I'm still concerned. Here's a conceptual example using decimal arithmetic in which the super-accumulator has four decimal places and the input/output values have only two decimal places:

Super-Accumulator Run 1: 0.9999
Super-Accumulator Run 2: 1.0001

Output Run 1: 0.99
Output Run 2: 1.00

The nondeterminism in the super-accumulator still gets through, even though its variance is much smaller than the precision of the output data type.

The above assumes that `tf.cast` simply discards the least-significant bits, which I'm almost certain it does (though I have not checked). I suspect that it could be made more robust with rounding before truncating, and that would protect the output from variance that was smaller that half the LSB in the output precision.

That still assumes that you don't have enough accumulated 64-bit floating-point rounding errors to spill up into the 32-bit mantissa. My sense is that that would be true in many or most cases, but without an in-depth analysis I would not be willing to claim that the solution was robustly deterministic.

Regarding making sure that the changes get run. I notice that `_GatherGradV2` [calls](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/array_grad.py#L677) [`_BatchGatherGrad`](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/array_grad.py#L588-L615) when `axis_static != 0`. `_BatchGatherGrad` calls `math_ops.unsorted_segment_sum`. Perhaps that's the other path the was being taken into the nondeterministic version of `math_ops.unsorted_segment_sum`.

You, and others reading this, might be interested in the following: rather than modifying the source code in the auto-generated file `gen_math_ops.py`, it's possible to apply a dynamic patch from your python program, after importing TensorFlow. You can create a copy of the reference to the existing function, initially bound to `math_ops.unsorted_segment_sum`, and can then call that from your new wrapper function (similar to what you have provided above), which can then be bound to `math_ops.unsorted_segment_sum`. This kind of (dynamic programming) re-binding approach is used with the existing, and upcoming, `fwd9m.tensorflow` patches. Here is an [example](https://github.com/NVIDIA/framework-determinism/blob/b4ec855d5b72107218ed5980004955e89df572a4/fwd9m/tensorflow/patch.py#L84-L87) for `tf.nn.bias_add`, which demonstrates only function replacement and not the wrapping.

Conclusion:

  1. I recommend rounding rather than truncating. I think this will be more deterministic.
  2. If this works consistently for your model, then that's awesome.
  3. I'm going to reconsider whether to implement and deploy this temporary solution (probably initially via a patch).
  4. You, or others, might want to implement this temporary solution, for now, using the dynamic programming approach rather than modifying the auto-generated source code or post-bazel-built code and/or having to rebuild a wheel.

**Comment by dangthatsright** [comment] 2020-07-28 05:54
Thank you for introducing me to what a super accumulator is!

Regarding your edge case and rounding: that makes a lot of sense and I agree that it also depends on how tf.cast is implemented. I don't know how it's implemented, but trying these two examples out they seem to be the same
```
tf.cast(tf.constant([0.99999999], dtype=tf.float64),tf.float32)
tf.cast(tf.constant([1.00000001], dtype=tf.float64),tf.float32)
```
so that's promising at least. That said rounding seems like a reasonable safety net.

Regarding accumulating enough errors to spill into float32: while it is theortically possible, I am pretty sure it won't for our system, since it's pretty small. Looking at https://en.wikipedia.org/wiki/Kahan_summation_algorithm#Accuracy, it seems like it can handle 10^16 values? 

Regarding where `_GatherGradV2` actually calls `unsorted_segment_sum`: I know that my code always takes the L533 branch, that I mentioned above, so it is still a mystery to me when `unsorted_segment_sum` actually gets called. 

Regarding the dynamic rebinding of the functions: thanks for this, I was having a hard time figuring out how to incorporate this code into my codebase but this provides me a much better alternative approach.

**Comment by dangthatsright** [comment] 2020-07-28 15:56
Got the patch to work for me! Just a modification: `tf.python.ops.math_ops.unsorted_segment_sum` should be `tf.python.math_ops.unsorted_segment_sum`

**Comment by duncanriach** [comment] 2020-07-29 00:41
Regarding the code path: in the version of `array_grad.py` that you link to above, there is no `_GatherGradV2`. It's in the V2 version of the grad function, when `axis_static != 0`, that first `_IndexedSlicesToTensorNoWarning` is [called](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/array_grad.py#L668), and then `_BatchGatherGrad` is [called](https://github.com/tensorflow/tensorflow/blob/v2.3.0-rc2/tensorflow/python/ops/array_grad.py#L668). This is an example where the line you're mentioning could be traversed before `math_ops.unsorted_segment_sum` is called. My understanding, from our discussion on framework-determinism [issue 25](https://github.com/NVIDIA/framework-determinism/issues/25), is that you're using TensorFlow version 2.2.0. The [version of that file](https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/ops/array_grad.py#L618-L687) under the `v2.2.0` tag definitely contains `_GatherGradV2`, which calls `_BatchGatherGrad`.

Regarding your example related to truncation and rounding: thank you for checking. I used decimal examples earlier only to demonstrate the concept. To take it to a deeper level of rigor, I tested the hypothesis using decimal numbers that should exactly translate into floating-point representations with a clear precision difference. FP32 has 23 bits of mantissa; FP64 has 52 bits of mantissa. A difference from 1.0 that is definitely representable by FP64 but not by FP32 would be 0.5^40 (one bit shifted to the right 40 places). So I tested this:

```
import tensorflow as tf

def test_cast(n):
  fp64 = tf.constant(n, dtype=tf.float64)
  print("\nFP64: %16.13f" % fp64)
  fp32 = tf.cast(fp64, dtype=tf.float32)
  print("FP32: %16.13f" % fp32)

d = 0.5**40
for n in [1-d, 1+d, -1-d, -1+d]:
  test_cast(n)
```

Which produces:

```
FP64:  0.9999999999991
FP32:  1.0000000000000

FP64:  1.0000000000009
FP32:  1.0000000000000

FP64: -1.0000000000009
FP32: -1.0000000000000

FP64: -0.9999999999991
FP32: -1.0000000000000
```

For completeness, I also tested (results reasonable and expected):
  * `d=0.5**23`: all the combinations (1-d, 1+d, -1-d, and -1+d) are exactly representable in both FP32 and FP64 formats (+/- `0.9999998807907` => +/- `0.9999998807907`).
  * `d=0.5**24`: half the combinations (1-d, -1+d) were exactly representable in both FP32 and FP64 formats (`0.9999999503954` => `0.9999999503954`) and the other half (1+d, -1-d) were not (+/- `1.0000000596046` => +/- `1.0000000000000`).
 * `d=0.5**25`: all the combinations round the same way (+/- `0.9999999701977` => +/- `1.0000000000000` and +/- `1.0000000298023` => `1.0000000000000`).

This is solid confirmation that `tf.cast` does, in fact, round and does not truncate (as `cast` does in at least some other languages). So, I'm happy with using `tf.cast` without pre-rounding. Pre-rounding isn't necessary.

Regarding accumulating enough errors to spill up into float32: Refining what you wrote, going from 52 to 23 mantissa bits, it would be necessary for there to be on the order of 2^(52-23) = 2^29 = 536,870,912 floating-point rounding errors that accumulated in the same direction (with no canceling-out) for the error to spill up into the 32-bit result. I've also just recognized that this would be limited to each output element of the segment sum and not to the entire model. I think there is almost zero probability of there being 536,870,912 of the same segment ID in the `segment_ids` list parameter in any case. Therefore, I'm now also comfortable with this aspect of the (temporary) solution.

> Got the patch to work for me! Just a modification: tf.python.ops.math_ops.unsorted_segment_sum should be tf.python.math_ops.unsorted_segment_sum

Thanks. I've edited that in [my comment](https://github.com/tensorflow/tensorflow/issues/39751#issuecomment-664764793) above.

Conclusion: I'm planning to add this patch, thoroughly tested, to `framework-determinism.tensorflow` to enhance determinism in all versions of TensorFlow going back to at least version 1.14. Once that's done it may be possible/worth upstreaming this temporary solution.

**Comment by duncanriach** [comment] 2020-07-29 14:13
For those who are interested, I've enhanced the analysis of `tf.cast` rounding in [this gist](https://gist.github.com/duncanriach/84b067302dad6c573ae9ebc8573dc489) to show the effects on the bits of the mantissa directly.

**Comment by duncanriach** [comment] 2020-10-23 16:51
We (@wenscarl and I) have isolated and reproduced a source of nondeterminism relevant to this issue. When `tf.gather` is used (such as when selecting embeddings for words in a sentence), backprop into a dense trainable variable (such as an embedding matrix) is nondeterministic, but not because the backprop of `tf.gather` is itself nondeterministic (as previously suggested). `tf.gather` produces sparse gradients, encoded using `tf.IndexedSlices`. When more than any given row in the embedding matrix is to be updated by more than two indexed slices in the sparse gradient tensor (more than two repeated indices), then the reduction via `tf.convert_to_tensor` introduces nondeterminism because it uses one of the segment sum ops, which have been confirmed to operate nondeterministically (see above).

We are currently working on releasing a temporary dynamic patch for the segment sum ops in [GitHub/NVIDIA/framework-determinism](https://github.com/NVIDIA/framework-determinism), which will be upstreamed if possible in advance of a higher-performance and more complete (CUDA-level) solution (later).

Here is [a gist](https://gist.github.com/duncanriach/c8155b34314ad829d9160fc2d5a80430) that repros this nondeterminism from `tf.convert_to_tensor`.

**Comment by duncanriach** [comment] 2021-04-16 01:50
Note that [PR 47772](https://github.com/tensorflow/tensorflow/pull/47772), which has been merged and will be present in TensorFlow version 2.5 onwards, causes TensorFlow to throw `tf.errors.UnimplementedError` when `TF_DETERMINISTIC_OPS` is set to `"true"` or `"1"` (when determinism is expected) and the segment reduction ops are used in such a way that truly random noise will be injected into the model's functionality.

This exception-throwing functionality can currently be disabled by setting `TF_DISABLE_SEGMENT_REDUCTION_OP_DETERMINISM_EXCEPTIONS` to `"true"` or `"1"` in case you're using a temporary patch solution that relies on higher-precision, nondeterministic underlying functionality to make the op function deterministically on the GPU.

This move to implement d9m-unimplemented exception throwing is orchestrated under this [determinism RFC](https://github.com/tensorflow/community/blob/master/rfcs/20210119-determinism.md).

**Comment by ChenchengLiang** [comment] 2021-04-25 13:22
Hey,
Thanks for the discussion. I found adding rounding + casting after unsorted_segment_sum is a temporary solution at least in my application:

x= tf.math.unsorted_segment_sum(...)
x = _my_tf_round(x,2)
def _my_tf_round(x, decimals=0):
    multiplier = tf.constant(10 ** decimals, dtype=x.dtype)
    return tf.cast(tf.cast(tf.round(x * multiplier),tf.int32),tf.float32) / multiplier

**Comment by duncanriach** [comment] 2021-04-27 21:25
@ChenchengLiang, thanks for the suggestion. Please will you put your code into a [code block](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks), with proper indenting, to make it easier to read?

I believe that the work-around you have provided is robust in terms of making the overall operation perfectly reproducible, assuming that the maximum number of segments in a reduction is below an extremely large number (on the order of 2^17 = 131k). However, the rounding to two decimal places removes most of the precision, including the very high precision with very small numbers near zero. This means that this approach cannot be used where very high precision is required, such as when combining gradients to update a word embedding.

**Comment by reedwm** [comment] 2021-09-16 18:47
This is fixed with https://github.com/tensorflow/tensorflow/pull/51861.

**Closed by reedwm** 2021-09-16 18:47 UTC
Labels: type:bug, comp:ops, TF 2.2

**Comment by ddaspit** [comment] 2021-11-30 03:56
This still does not seemed to be fixed on Windows. Should this issue be re-opened? Or should a new issue be created?

**Comment by reedwm** [comment] 2021-11-30 18:49
> This still does not seemed to be fixed on Windows. Should this issue be re-opened? Or should a new issue be created?

I think a new issue should be opened.
