### ISSUE TITLE
Tensor.eval() Performance Decay

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#2340] opened 2016-05-12 17:41 UTC
I used Tensorflow 0.6 (I pip installed TensorFlow: `pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.6.0-cp34-none-linux_x86_64.whl`) with Python 3 to train Neural Network on GPU (Nvidia GeForce GTX Titan X with Cuda 7.0 and Cudnn 6.5), and I noticed an interesting problem: The time consumption for running `tensor.eval(session=..., feed_dict=...)` at each iteration was continuously growing as iteration goes by, which indicated that performance of tensor.eval() decayed. Specifically, the code looks like this:
```
import tensorflow as tf
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.1)
session = tf.Session(config=tensorflow.ConfigProto(gpu_options=gpu_options))

"""Then build the neural network tensor graph, For example,"""
"""we define an neural network to compute output layer tensor a."""

# input tensor is an numpy array with dimension 32 * 336 * 84.
dict = {input_tensor: input_tensor}
for _ in 1000000:
     a.eval(session=session, feed_dict=dict)
```

In this code, the running time for each `a.eval()` gradually got larger and larger as iteration time goes by. So I used Profiling tooI (CProfile) to dig into the code to see at which part of code performance going wrong, and it indicated that time consumption for executing `built-in method TF_Run` for running `a.eval()` was very long and kept growing. I am pretty sure the `input_tensor` size keeps exactly same for each iteration, I wonder if anyone can help me figure out the problem, and how I can improve my current performance. Thanks!!!

**Comment by mrry** [comment] 2016-05-12 18:28
Does the problem persist in TensorFlow 0.8? Can you share a complete program that exhibits the problem? In particular, how are `a` and `input_tensor` defined?

**Comment by RuofanKong** [comment] 2016-05-12 18:47
@mrry Thanks for your answer :) Yes, for TF 0.8, we used the same profiling tool to test it, and still got linear performance decay as running time goes by. Actually, I'm really eager to show all my code here, but the complete code has more than 2000 lines... But I can show you the data shape that I defined: it's `[array([[…], …, […]]), array([[…], …, […]]), …, array([[…], …, […]])]` - list with dimensions 32 * 336 * 84.

**Comment by mrry** [comment] 2016-05-12 19:42
If you simply fetch a constant containing that data using `Tensor.eval()` in a loop, does the time increase for each call?

I expect that the problem is somewhere in the other part of the 2000 lines, and it's just being accounted to `TF_Run()` since that's the main entry-point to the native runtime. It would be helpful to make a minimal example that still exhibits the problem. For example, are there queues, loops, or other more exotic features in your program?

**Comment by mrry** [comment] 2016-05-12 19:52
I just tried to reproduce this with a simple program, and while the distribution of step times is noisy, it doesn't seem to show an increasing trend:

![figure_1](https://cloud.githubusercontent.com/assets/192142/15228283/41845590-1840-11e6-9c1e-f8ad6a217909.png)

```python
import time

import matplotlib.pyplot as plt
import tensorflow as tf

c = tf.constant(5)
times = []
with tf.Session():
  c.eval()  # Ignore first, slow step.
  for _ in range(100000):
    start = time.time()
    c.eval()
    times.append(time.time() - start)

plt.plot(times)
plt.ylim(0, 0.0010)
plt.show()
```

**Comment by RuofanKong** [comment] 2016-05-13 02:01
@mrry I think you are right. I also tested `tensor.eval()` in a single loop by myself, and seems time for running this function is not growing. So there might be some places in my code getting the time consumption problem... By the way, I wonder whether or not `tensorflow.concat()` creates new nodes in tensor graph. Also, I wonder if there are tensorflow methods that creates new nodes. Thanks!!!

**Comment by mrry** [comment] 2016-05-13 02:07
When we've seen this problem in the past, it's usually because something in the training loop is creating new graph nodes, and the TF runtime has to do more work each time you call `eval()`, because it believes it's running a new graph (even if it's structurally identical to the old ones). If you're calling `tf.concat()` in the training loop, that would be adding new nodes to the graph, and would lead to bad performance. One quick way to test this is to call `tf.get_default_graph().finalize()` before your training loop, and you will get an exception if anything is added to the graph.

You can usually avoid these performance issues by creating `tf.placeholder()` nodes, defining the (e.g.) `tf.concat()` in terms of them outside the loop, and feeding in the appropriate values.

I'm going to close this issue for now, but let us know if you have other questions!

**Closed by mrry** 2016-05-13 02:07 UTC
