### ISSUE TITLE
tensorflow.python.framework.errors_impl.AlreadyExistsError while importing freezed graph

### ISSUE THREAD

**Issue by dchatterjee172** [tensorflow/tensorflow#25540] opened 2019-02-06 10:04 UTC
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): YES
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):Binary
- TensorFlow version (use command below):1.12.0
- Python version:3.5.2

**Describe the current behavior**
The functions used to freeze graph, I don't receive any error while freezing the graph        
```
tmp_g = tf.graph_util.convert_variables_to_constants(
          sess, tmp_g, [n.name[:-2] for n in output_tensors]
)
```   
```
with tf.gfile.GFile("inference_graph", "wb") as f:
    f.write(tmp_g.SerializeToString())
```       
The functions used to load graph        
``` 
with tf.gfile.GFile("inference_graph", "rb") as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())```
start_logits, end_logits = tf.import_graph_def(                                                                                        
                graph_def,
                input_map={k: features[k[:-2]] for k in input_names},
                return_elements=["unstack:0", "unstack:1"],
            )
```    
The error,        
```
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
2019-02-06 15:26:25.816370: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not c$
mpiled to use: AVX512F
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
2019-02-06 15:26:40.501236: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_
step_6/import/magic/while/embeddings/ArithmeticOptimizer/AddOpsRewrite_add_1/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
Traceback (most recent call last):
  File "/home/dj/.local/share/virtualenvs/bert-squeeze-test12-a8EWmLrd/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in
 _do_call
    return fn(*args)
  File "/home/dj/.local/share/virtualenvs/bert-squeeze-test12-a8EWmLrd/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in
 _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dj/.local/share/virtualenvs/bert-squeeze-test12-a8EWmLrd/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in
 _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_6/import/magic/while/embeddings/ArithmeticOptimizer/AddOpsRewrite_add_
1/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
         [[{{node import/magic/while/embeddings/ArithmeticOptimizer/AddOpsRewrite_add_1/tmp_var}} = TemporaryVariable[dtype=DT_FLOAT, shape=[1,384,768
], var_name="import/magic/while/embeddings/ArithmeticOptimizer/AddOpsRewrite_add_1/tmp_var", _device="/job:localhost/replica:0/task:0/device:CPU:0"](^
import/magic/while/embeddings/Reshape_3)]]

tensorflow.python.framework.errors_impl.AlreadyExistsError: Resource __per_step_6/import/magic/while/embeddings/ArithmeticOptimizer/AddOpsRewrite_add$
1/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
         [[{{node import/magic/while/embeddings/ArithmeticOptimizer/AddOpsRewrite_add_1/tmp_var}} = TemporaryVariable[dtype=DT_FLOAT, shape=[1,384,76$
], var_name="import/magic/while/embeddings/ArithmeticOptimizer/AddOpsRewrite_add_1/tmp_var", _device="/job:localhost/replica:0/task:0/device:CPU:0"](^
import/magic/while/embeddings/Reshape_3)]]
```

**Comment by jvishnuvardhan** [comment] 2019-03-12 17:09
@dchatterjee172  Could you try TF2.0 and let us know whether the bug persists? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-03-18 21:37
I assume that you found a solution for the issue. Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Comment by pekaalto** [comment] 2019-06-14 08:51
I have this same issue in tf 2.0 beta0 when training with Keras. This is my error:
```
2019-06-14 15:50:47.135616: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_0/training/gradients/lstm/while_grad/lstm/while_grad/body/_437/gradients/AddN_8/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
2019-06-14 15:50:47.135640: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Already exists: Resource __per_step_0/training/gradients/lstm/while_grad/lstm/while_grad/body/_437/gradients/AddN_8/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node training/gradients/lstm/while_grad/lstm/while_grad/body/_437/gradients/AddN_8/tmp_var}}]]
2019-06-14 15:50:47.136076: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at variable_ops.cc:104 : Already exists: Resource __per_step_0/training/gradients/lstm/while_grad/lstm/while_grad/body/_437/gradients/AddN_8/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
Traceback (most recent call last):
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d5d4b32b3ef3>", line 2, in <module>
    model.fit(dd, np.zeros(len(data)), batch_size=150, verbose=1)
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 643, in fit
    use_multiprocessing=use_multiprocessing)
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 664, in fit
    steps_name='steps_per_epoch')
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 383, in model_iteration
    batch_outs = f(ins_batch)
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3510, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 572, in __call__
    return self._call_flat(args)
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 671, in _call_flat
    outputs = self._inference_function.call(ctx, args)
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 445, in call
    ctx=ctx)
  File "/anaconda3/envs/py36tf2/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.AlreadyExistsError:  Resource __per_step_0/training/gradients/lstm/while_grad/lstm/while_grad/body/_437/gradients/AddN_8/tmp_var/N10tensorflow19TemporaryVariableOp6TmpVarE
	 [[{{node training/gradients/lstm/while_grad/lstm/while_grad/body/_437/gradients/AddN_8/tmp_var}}]] [Op:__inference_keras_scratch_graph_3658]
Function call stack:
keras_scratch_graph
```

I can't reproduce with small example though.
Looks similar to this issue https://github.com/tensorflow/tensorflow/issues/23780

**Comment by jvishnuvardhan** [comment] 2019-06-17 17:43
@pekaalto Please open a new issue by filling template and providing a standalone code to reproduce the issue. Thanks!

**Comment by pekaalto** [comment] 2019-06-18 04:48
Hi @jvishnuvardhan unfortunately I haven't been able to reproduce with small example and I can't publish my full-data. However, my issue seems to be the same as in the linked-open issue, except I'm using TF 2.0.  

So maybe in this case opening a new issue is not necessary, right?  Thanks.

**Comment by jvishnuvardhan** [comment] 2019-06-24 21:32
@pekaalto I have requested you to open a new issue considering "users" who can get benefited from your issue. But I will open the issue. Could you share a standalone code to reproduce your issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-07-12 20:08
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-07-12 20:08 UTC
Labels: comp:ops, type:bug/performance
