### ISSUE TITLE
[XLA] tf.where not working with xla.compile

### ISSUE THREAD

**Issue by samwise2nd** [tensorflow/tensorflow#24476] opened 2018-12-20 17:07 UTC
tf.where doesn't seem to be supported when using xla.compile. Are there any ways around the issue, or would it be possible to implement?

Example code:

```
import tensorflow as tf
import tensorflow.contrib.compiler.xla as xla

test_tensor = tf.constant([[1, 2, 3, 0.00004, 5], [6, 7, 8, 9, 10]], dtype=tf.float32)


def func():
    return tf.where(test_tensor < 1e-2)


with tf.device("/device:CPU:0"):
    compiled_func = xla.compile(func)

with tf.Session() as session:
    res = session.run(compiled_func)
    print(res)
```

Error output:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Detected unsupported operations when trying to compile graph cluster_5308246905621824101[] on XLA_CPU_JIT: Where (No registered 'Where' OpKernel for XLA_CPU_JIT devices compatible with node node Where
	.  Registered:  device='CPU'; T in [DT_BOOL]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT64]

**Comment by jlebar** [comment] 2018-12-20 21:50
> tf.where doesn't seem to be supported when using xla.compile.

Correct, this is due to a fundamental design choice in XLA, see https://medium.com/tensorflow/pushing-the-limits-of-gpu-performance-with-xla-53559db8e473.  We are currently working on relaxing this, but it is a lot of work.

> Are there any ways around the issue

Not that I know of today with `xla.compile`.

You could try using autoclustering instead of xla.compile, by setting the `TF_XLA_FLAGS` environment variable to include `--tf_xla_auto_jit=2`.  Or you could try moving the `where` out of xla.compile.

Since this is working as intended (but not necessarily desired) I'm going to close this, but I don't mean to end the conversation if you have other questions.

**Closed by jlebar** 2018-12-20 21:50 UTC
Labels: comp:xla
