### ISSUE TITLE
RuntimeError: Unable to create link (name already exists) during model saving with ModelCheckpoint

### ISSUE THREAD

**Issue by iLeW** [tensorflow/tensorflow#27688] opened 2019-04-09 15:24 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): TF 2.0 downloaded from repo
- TensorFlow version (use command below): 
tf-nightly-gpu-2.0-preview --> 2.0.0.dev20190314 
tensorflow-hub  --> 0.4.0
- Python version: 3.6
- CUDA/cuDNN version: CUDA Version 10.0.130/ cuDNN 7.5.0
- GPU model and memory: Nvidia RTX 2080 Ti 11GB (and GTX 1060 6GB) 

**Describe the current behavior**
I've downloaded an inception model from TF-Hub (specifically this one: https://tfhub.dev/google/tf2-preview/inception_v3/feature_vector/2), I have added to it two Keras layers (a Dropout layer and a Dense layer) and during the training, I'm trying to save the model using the `ModelCheckpoint` Keras callback. Unfortunately, after one epoch and during the model saving I receive the following error:
``` python
Traceback (most recent call last):
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3945e7fb8367>", line 1, in <module>
    runfile('/run/media/federico/XData/PycharmProjectsXData/ash/ash/prova_gan_plain_test.py', wdir='/run/media/federico/XData/PycharmProjectsXData/ash/ash')
  File "/opt/pycharm-professional/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/pycharm-professional/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/run/media/federico/XData/PycharmProjectsXData/ash/ash/prova_gan_plain_test.py", line 98, in <module>
    main()
  File "/run/media/federico/XData/PycharmProjectsXData/ash/ash/prova_gan_plain_test.py", line 90, in main
    logdir,
  File "/run/media/federico/XData/PycharmProjectsXData/ash/ash/testers/gan_plain.py", line 85, in __init__
    self._model = self._download_and_train_model()
  File "/run/media/federico/XData/PycharmProjectsXData/ash/ash/testers/gan_plain.py", line 255, in _download_and_train_model
    callbacks=[cback_checkpoint],
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1508, in fit_generator
    steps_name='steps_per_epoch')
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 324, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 290, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/tensorflow/python/keras/callbacks.py", line 892, in on_epoch_end
    self.model.save_weights(filepath, overwrite=True)
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1395, in save_weights
    hdf5_format.save_weights_to_hdf5_group(f, self.layers)
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 693, in save_weights_to_hdf5_group
    param_dset = g.create_dataset(name, val.shape, dtype=val.dtype)
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/h5py/_hl/group.py", line 139, in create_dataset
    self[name] = dset
  File "/run/media/federico/XData/virtualenvs/python36_tf2preview/lib/python3.6/site-packages/h5py/_hl/group.py", line 371, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)
```

Highlighting the error: **RuntimeError: Unable to create link (name already exists)**

**Describe the expected behavior**
I'm expecting to be able to use the `ModelCheckpoint` callback to save the (best) model.
Alternatively, I'm also expecting to be able to save the model with the `model.save(filepath)` function.

**Code to reproduce the issue**
You could reproduce the error on the following TF-Hub Colab page: https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/tf2_image_retraining.ipynb#scrollTo=CCpdfXPsh47Q 

adding a cell with the `ModelCheckpoint` code

``` python
cback_checkpoint = tf.keras.callbacks.ModelCheckpoint(
            filepath="best.h5",
            verbose=1,
            save_best_only=True,
        )  
```

and then adding the callback to the `fit_generator` function of the model:

``` python
steps_per_epoch = train_generator.samples // train_generator.batch_size
validation_steps = valid_generator.samples // valid_generator.batch_size
hist = model.fit_generator(
    train_generator,
    epochs=5, steps_per_epoch=steps_per_epoch,
    validation_data=valid_generator,
    validation_steps=validation_steps,
    callbacks=[cback_checkpoint]).history
```

**Other info / logs**
I've found some issues online regarding a similar problem like [this](https://groups.google.com/forum/#!topic/keras-users/my13TUe2dlU) and issues: [#5280](https://github.com/keras-team/keras/issues/5820), [#6844](https://github.com/keras-team/keras/issues/6844) and the more recent #26811. Many of them speak about some problem regarding the naming of the layers (or weights) or about creating the `ModelCheckpoint` with `save_best_only=True` or `save_weights_only=True`. I have tried all the proposed approaches but without success.
Even with `model.save(filepath)` Keras function I face the same problem.

**EDIT**: Please follow [this Colab link](https://colab.research.google.com/drive/1_sDTb1DLaoBlNGbRfKqMWgWV6B2DaYUv) to have all the code set up to be reproduced.

**Comment by gadagashwini** [comment] 2019-04-16 04:50
@iLeW When I try to run the google colab that you have provided, unfortunately I did not get any error. Thanks!

**Comment by iLeW** [comment] 2019-04-16 07:13
@gadagashwini I have just tried again, and it gives me the same error:
```python
h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.link()

RuntimeError: Unable to create link (name already exists) 
```
Have you added, before running it, the line of code as indicated in my post? For your convenience, I filled out the Colab for you. You can find it at [this link](https://colab.research.google.com/drive/1_sDTb1DLaoBlNGbRfKqMWgWV6B2DaYUv) with the necessary changes (i.e.: the callback added to the model). Please try to run this configuration. It should give you the same `RuntimeError` error.

**Comment by atomextranova** [comment] 2019-04-17 06:53
I am having the same problem at #27909. I suspect this is a problem related to h5py/hdf5 because internally the traceback suggests the error happened when trying to save the model using the library. Also to note the keras already set overwrite=True, so the error should not happen.

I am using hdf5==1.10.4 and h5py=2.9.0. I suspect there is problem with the library.

**Comment by qwtsc** [comment] 2019-04-20 01:19
The same problem happened to me, Tensorflow2.0, Cuda:10.0, Python3.6.8.

**Comment by KUASWoodyLIN** [comment] 2019-05-02 02:29
I also encountered the same problem.
Tensorflow:2.0.0a0
Cuda:10.0
Python:3.6.8
IDE:Jupyter  NoteBook

**Comment by rchao** [comment] 2019-05-02 23:13
Thanks for the report. Confirming I can repro. Feel free to add more information while we're looking into it.

**Comment by arnoegw** [comment] 2019-05-03 15:59
The crash of Model.save() when using hub.KerasLayer likely needs to be fixed in tensorflow-hub, not tensorflow. I've filed issue tensorflow/hub#287 for that.

Can this issue here be closed then?

**Comment by rchao** [comment] 2019-05-06 20:44
> The crash of Model.save() when using hub.KerasLayer likely needs to be fixed in tensorflow-hub, not tensorflow. I've filed issue [tensorflow/hub#287](https://github.com/tensorflow/hub/issues/287) for that.
> 
> Can this issue here be closed then?

Sounds good - thanks arnoegw@! Let's follow up in tensorflow/hub#287 for this issue.

**Closed by rchao** 2019-05-06 20:44 UTC
Labels: 2.0, comp:keras, type:bug/performance

**Comment by arnoegw** [comment] 2019-05-10 11:36
FYI - issue https://github.com/tensorflow/hub/issues/287 has been solved (upgrade Hub module version to /3).

**Comment by rchao** [comment] 2019-05-10 16:49
> FYI - issue [tensorflow/hub#287](https://github.com/tensorflow/hub/issues/287) has been solved (upgrade Hub module version to /3).

Thanks for the updates!

**Comment by miraculixx** [comment] 2019-06-20 15:44
I also encountered the same problem. Note it **only occurs with eager execution enabled.**
Tensorflow:1.13.1
Python:3.6.8 Anaconda Inc.
IDE:Jupyter NoteBook

**Comment by ppham27** [comment] 2019-07-03 06:54
For the error with eager execution, make sure you're using OptimizerV2 from here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/keras/optimizer_v2. The optimizers in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizers.py don't inherit from Trackable so the variables aren't named correctly.

**Comment by off99555** [comment] 2019-07-13 11:57
@ppham27 I can save keras model in `tensorflow-gpu-1.13` fine until I trigger `tf.enable_eager_execution()` that is when I cannot save the model. When I call `model.save(path)` the `Unable to create link` error immediately occurs if eager execution is enabled. If I set `include_optimizer` to False then it will let me save. But I think this is a stupid workaround.

I see that it's related to the optimizer somehow like you mentioned in your comment. So I tried importing the Adam optimizer from `tensorflow.python.keras.optimizer_v2.adam.Adam` and it works like a charm! So thank you for the advice.

**Comment by ppham27** [comment] 2019-07-13 16:58
Hi @off99555,

Sorry, can't seem to figure out why that would be occurring without more code.

We have at least one test in the test suite that saves the model with an optimizer: https://github.com/tensorflow/tensorflow/blob/3cb03d093610e51cf2d36bfbf43c446a5de52941/tensorflow/python/keras/saving/hdf5_format_test.py#L810-L811

I changed the line `SGD` to `Adam` and the test still passes. Maybe try upgrading to a later version of Tensorflow?

**Comment by off99555** [comment] 2019-07-13 18:46
It seems to be a version issue. I tested with tensorflow2.0 and there is no problem (because there is no tf.enable_eager_execution()). I cannot upgrade the version easily considering that I followed this installation guide that only has version 1.13 as the latest from conda: https://www.pugetsystems.com/labs/hpc/The-Best-Way-to-Install-TensorFlow-with-GPU-Support-on-Windows-10-Without-Installing-CUDA-1187/

Here is the exact code I used to reproduce the error
```py
import tensorflow as tf   # only work from tensorflow==1.9.0-rc1 and after
tf.enable_eager_execution()
from tensorflow.python.keras.optimizer_v2.adam import Adam

def keras_model():
    from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout, Input

    inputs = Input(shape=(28, 28, 1))
    x = Conv2D(32, (3, 3),activation='relu', padding='valid')(inputs)
    x = MaxPool2D(pool_size=(2, 2))(x)
    x = Conv2D(64, (3, 3), activation='relu')(x)
    x = MaxPool2D(pool_size=(2, 2))(x)
    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    x = Dropout(0.5)(x)
    outputs = Dense(10, activation='softmax')(x)

    return tf.keras.Model(inputs, outputs)

model = keras_model()
model.compile(Adam(), 'categorical_crossentropy', metrics=['acc'])
model.save('mnist.h5')
model2 = tf.keras.models.load_model('mnist.h5') # it will raise TypeError: Unexpected keyword argument passed to optimizer: name
```

**Comment by ppham27** [comment] 2019-07-13 22:43
Hmm, there appears to be a mismatch in the optimizer being loaded. Really, my advice would be to upgrade to at least TF1.14, but it might work passing in `custom_objects={'adam': Adam}` as a keyword argument into `tf.keras.models.load_model`.

Or putting this at the top of your program:
```
import os

os.environ['TF2_BEHAVIOR'] = '1'
```

**Comment by off99555** [comment] 2019-07-14 09:49
That trick about `custom_objects` seem to work!
I changed the loading code to `model2 = tf.keras.models.load_model('mnist.h5', custom_objects=dict(adam=Adam))` and it is able to load using Adam v2 optimizer.

**Comment by gogasca** [comment] 2019-07-14 23:29
I was using a TF.Hub model based on this tutorial https://www.tensorflow.org/tutorials/images/hub_with_keras  and change the TF hub model from version 2 to 4.
and now works for me:
https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4

**Comment by ahmadalsharef994** [comment] 2020-02-05 08:20
WORKING SOLUTION:

1. Go to: Miniconda3\Lib\site-packages or wherever h5py is installed.
2. Delete h5py Folder
3. Delete h5py-2.10.0.dist-info Folder (This might be different if you have a different 4. version).
4. Install h5py again.

It worked for me after a long search. Finally, I tried to delete it manually and reinstall it. IT WORKED!!!!!

By uninstalling them using cmd, pip, anaconda Some files might be stuck and will cause errors even after installing a different version.

**Comment by felixnext** [comment] 2020-02-06 10:09
I got the same error in Tensorflow 2.1 when calling `save_weigths("model.h5", overwrite=True)`.
None of the above mentioned fixes worked for me (I am not using hub and optimizer is passed as `SGD(...)`).
Are there any other solutions to this?

**Comment by m-nasiri** [comment] 2020-03-06 20:23
The reason why it didn't work was because I had the same namestrings for all the weights in my custom keras layers. 
Lesson: If you make keras layers, give them different name strings!

**Comment by nikhil1008** [comment] 2020-06-27 16:36
I get the same problem when I enable eager execution, without it everything works fine

**Comment by 2t2c** [comment] 2021-04-11 20:08
> I also encountered the same problem. Note it **only occurs with eager execution enabled.**
> Tensorflow:1.13.1
> Python:3.6.8 Anaconda Inc.
> IDE:Jupyter NoteBook
> 
> I was able to solve the .save error with the following snippet. Is this a good idea?
> 
> ```
> from tensorflow.python.keras import backend as K
>    
> with K.name_scope(model.optimizer.__class__.__name__):
>     for i, var in enumerate(model.optimizer.weights):
>         name = 'variable{}'.format(i)
>         model.optimizer.weights[i] = tf.Variable(var, name=name)
> ```

I've been trying to resolve this issue since past few hours. Thank you for saving me!

**Comment by kamushekp** [comment] 2021-04-27 19:13
You can also face this problem in case of no-unique 'group' part of name in case of using multi-input models with transfer learning (for example - several MobileNet at input).

Wrote this code, it helped (summary, with changing other meta, such as model name and layer names):

```
import uuid
def unique_name():
    return uuid.uuid4().hex.upper()[0:10]

def postprocess_weight_name(name):
    group, name = name.split('/')
    return f'{group}{unique_name()}/{name}'
    print((group, name))

model._name = model._name + unique_name()
        
for layer in model.layers:
    layer._name = layer._name + unique_name()
        
for i in range(len(model.weights)):
    model.weights[i]._handle_name = postprocess_weight_name(model.weights[i].name)
```

**Comment by lisherlock** [comment] 2022-04-29 07:43
> 如果使用具有迁移学习的多输入模型（例如 - 输入中的多个 MobileNet），_在权重_中没有唯一的“组”部分名称的情况下，您也可能会遇到此问题。
> 
> 编写此代码，它有所帮助（总结，更改其他元，例如模型名称和层名称）：
> 
> ```
> import uuid
> def unique_name():
>     return uuid.uuid4().hex.upper()[0:10]
> 
> def postprocess_weight_name(name):
>     group, name = name.split('/')
>     return f'{group}{unique_name()}/{name}'
>     print((group, name))
> 
> model._name = model._name + unique_name()
>         
> for layer in model.layers:
>     layer._name = layer._name + unique_name()
>         
> for i in range(len(model.weights)):
>     model.weights[i]._handle_name = postprocess_weight_name(model.weights[i].name)
> ```

It works in my code. Thanks a lot!
