### ISSUE TITLE
Incorrect result when subtracting 1 from exponential of Variable 

### ISSUE THREAD

**Issue by charmasaur** [tensorflow/tensorflow#33192] opened 2019-10-10 04:07 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.14.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: 3.7.3
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: Intel Iris Plus Graphics 640 1536 MB

**Describe the current behavior**
With the following setup
```
session = tf.Session()
variable = tf.Variable(4j)
exp = tf.exp(variable)
session.run(tf.global_variables_initializer())
```
the following code
```
print(session.run(exp-1))
print(session.run(exp)-1)
```
produces two different outputs, specifically:
```
(2.897081749192498+1.3258713481172573j)
(-1.6536436208636118-0.7568024953079282j)
```

**Describe the expected behavior**
That code should print identical arrays (the latter is correct, the former is not). 

**Code to reproduce the issue**
```
session = tf.Session()
variable = tf.Variable(4j)
exp = tf.exp(variable)
session.run(tf.global_variables_initializer())

print(session.run(exp-1))
print(session.run(exp)-1)
```
Also see Colab notebook here: https://colab.research.google.com/drive/1KT2gfuWeezhWOr3zfyHhk9HvCH7JcShm

**Other info / logs**
I have no idea what's happening, but some observations:
 - there needs to be a Variable involved. If I use a constant instead of a Variable, all works as expected.
 - the exponent value is important. If I change the 4's to 1's then all works as expected, for example.
 - the TF exponential is important. If instead I calculate the exponential with numpy and then set the Variable to that exponential, subtracting 1 works correctly.
 - specifically subtracting 1 seems important. If instead I subtract 2, or 0.1, or 1j, all works as expected.

**Comment by ravikyram** [comment] 2019-10-11 09:14
I have tried on colab with TF version 1.14, 1.15.0-rc3 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/dd87c7a8f850af52f1d667d1eac67899/untitled257.ipynb). Thanks!

**Comment by JameerBabu** [comment] 2019-10-13 08:00
Exp and Exp-1 are two different values. How can they produce the same result.  print(session.run(exp-1)) produces the result of value which is equal to exp - 1.
print(session.run(exp)-1) produces the result equal to one subtracted from the result of value which equals exp. Hence they are two different. I guess there is no issue. It is working properly.

**Comment by charmasaur** [comment] 2019-10-13 09:44
Sorry, I don't follow. In both cases you describe, the eventual value printed should be the value of e^(4j)-1.

**Comment by JameerBabu** [comment] 2019-10-13 10:50
No. It will be  (e^4j) -1 and e^(4j - 1)

**Comment by mdanatg** [comment] 2019-10-24 13:07
It looks like a bug in Eigen, specifically `expm1` seems to produce incorrect results for complex numbers with imaginary part 4 or greater. I've asked a few folks internally who are familiar with the code, but it would be nice to confirm this with the Eigen team.

The reason why the bug only manifests for variables is most likely a consequence of how the optimizer simplifies mathematical expressions.

**Comment by charmasaur** [comment] 2019-10-24 21:33
Ah, nice find! It hadn't even occurred to me that `exp(x)-1` might get simplified to a single function call, but in hindsight that makes sense.

**Comment by srvasude** [comment] 2019-12-21 21:22
Hi, I submitted
https://gitlab.com/libeigen/eigen/merge_requests/18
in Eigen, which fixes Eigen's implementation of expm1.

This is being used in the current tf-nightly:

>>> tf.math.expm1(4j)
<tf.Tensor: shape=(), dtype=complex128, numpy=(-1.653643620863612-0.7568024953079282j)>

This issue should be fixed now.

**Closed by srvasude** 2019-12-21 21:22 UTC
Labels: TF 1.14, TF 1.15, comp:ops, type:bug

**Comment by charmasaur** [comment] 2019-12-22 22:15
Thanks!

**Comment by charmasaur** [comment] 2019-12-22 22:17
Should we expect the next minor release (2.1.0, I guess) to have the fix?

**Comment by charmasaur** [comment] 2020-06-02 08:20
Turns out 2.2.0 has the fix
