### ISSUE TITLE
cmake vs bazel

### ISSUE THREAD

**Issue by nvarini** [tensorflow/tensorflow#6923] opened 2017-01-18 07:37 UTC
Hello I am writing with regard compiling tensorflow on linux clusters. 
As far as I understood bazel recompiles everything it needs. On out cluster we use spack (https://github.com/LLNL/spack) to compile new software and provide modules to the users. With spack it's easy to track dependencies and provenance of a given installation.
By recompiling everything bazel's need the dependencies are messed up and we don't understand how tensorflow has been compiled from a spack point of view. 
Why is it stated" N.B. We provide Linux build instructions primarily for the purpose of testing the build. We recommend using the standard Bazel-based build on Linux."?
Actually, how can we tell to bazel to use system-provided libraries like boost?

Thanks very much,

Nicola

**Comment by jart** [comment] 2017-01-18 07:55
I'm closing this issue since it's not a bug or feature request. But I'm happy to answer your Bazel questions here since Bazel is still relatively new and we want the community to feel comfortable with it.

Like Spack, Bazel was also designed for supercomputers^Wextremely large clusters of inexpensive hardware. Unlike Spack, Bazel is designed so every piece of software exists only at one version, in order to make dependencies tractable.

Beyond that cursory glance, I don't really know much about Spack and I don't understand your question or how it relates to cmake. Speaking of which, we actually have a cmake build in our contrib directory. If you're familiar with cmake, it may suit you, although it's community supported.

**Closed by jart** 2017-01-18 07:55 UTC
Labels: type:support

**Comment by nvarini** [comment] 2017-01-18 09:10
Thanks for your answer. Spack relies mainly on cmake or configure to build packages. In configure or cmake you usually need to specify where a particular library is.
I am working to create a spack package to tensorflow based on cmake. The idea is that you can install tensorflow with cuda support and gcc compiler like: spack install tensorflow +cuda %gcc. 
So, I am perfectly fine with using cmake, and it is well integrated in spack. My concern is related to the statement:  We provide Linux build instructions primarily for the purpose of testing the build. If I would like to provide tensorflow for production purpose either bazel or cmake would do? Is there any difference between the two way of building tensorflow?

Thanks

**Comment by jart** [comment] 2017-01-18 19:03
The difference is that Bazel is the build system we actually use. The make, cmake, and xcode build systems are contributed / supported by the community and are only capable of building a subset of TensorFlow. We smoke test make and cmake so we don't break it when we make changes. So it has some official support. But we strongly recommend using Bazel if it's capable of running on your system.

**Comment by nvarini** [comment] 2017-01-19 02:35
There is a bazel package in spack (https://github.com/LLNL/spack/tree/develop/var/spack/repos/builtin/packages/bazel).  And also a tensorflow pr(https://github.com/LLNL/spack/pull/2043). The problem is to understand how to prevent bazel from recompiling libraries and tell bazel to use libraries already compiled by spack. Any idea?

**Comment by jart** [comment] 2017-01-19 03:03
Libraries such as what? Like eigen, png, gif, jpeg, nasm, highwayhash, farmhash, pcre, swig, curl, proto, grpc, boringssl, etc. defined in [workspace.bzl](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl) and [WORKSPACE](https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE)? You could potentially have a very long road ahead of you.

Blaze was designed to be a *hermetically sealed* build system that doesn't take anything into consideration that isn't defined in its own build graph. So the solution is to put the stuff built by Spack into the build graph. 

If I were you, and I was determined to do what you want to do, I would probably start by patching TensorFlow to eliminate its default WORKSPACE file. Then I would redefine all those http_archive rules with build rules that basically point at the things that spack built. It would be super painful.

**Comment by jart** [comment] 2017-01-19 03:16
Examples? Like eigen, png, gif, jpeg, nasm, highwayhash, farmhash, pcre, swig, curl, proto, grpc, boringssl, etc. defined in [workspace.bzl](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl) and [WORKSPACE](https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE)? TensorFlow's Bazel configuration is actually doing a deceptively large amount of work. It builds all those things from scratch. So you could potentially have a very long road ahead of you. 

Blaze was designed to be hermetically sealed and not take anything into consideration anything that isn't defined in its own build graph. It's basically the Gentoo of build systems. So the solution is to put the stuff built by Spack into the build graph, using plain old BUILD code.

If I were you, and I was determined to do what you want to do, I would probably start by patching TensorFlow to eliminate its default WORKSPACE file. Then I would redefine all those http_archive rules with build rules that basically point at the things that spack built. It would be super painful.

For example, you can define a cc_library() where the srcs list contains a .so file, if I remember correctly. That .so file could just be a symlink to some compiled file in a spack output directory.

**Comment by RoboEvangelist** [comment] 2017-04-04 05:33
how do I create a tensorflow workspace outside the tensorflow examples folder? I want to put my tensorflow code in a repository, but having to put it in the examples folder all the time make it kinda inconvenient.

**Comment by OakSuen** [comment] 2017-12-07 10:15
I have the same question as yours.
