### ISSUE TITLE
[TF2.0] Incorect Loss calculation in `keras.Model.evaluate` when last batch size is different.

### ISSUE THREAD

**Issue by HanGuo97** [tensorflow/tensorflow#27993] opened 2019-04-19 21:55 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): TF2.0 Alpha
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
The loss value returned from `Keras.Model.evaluate()` is an arithmetic average over losses for each batch. However, when the last batch has a smaller batch size than previous batches (e.g. a dataset has 101 examples, with batch-size=10), the calculation is incorrect because it will mistakenly give higher weight to the last batch's loss.

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by achandraa** [comment] 2019-04-22 12:21
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by achandraa** [comment] 2019-04-29 04:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-04-29 04:25 UTC
Labels: 2.0.0-alpha0, comp:keras, stat:awaiting response, type:bug/performance
