### ISSUE TITLE
Crash when running tf.keras.backend.eye

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59440] opened 2023-01-25 03:08 UTC
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Crash
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/15yiYmGH1wXnKryDbJ8NHOaI1Je_SQjib?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by gaikwadrahul8** [comment] 2023-01-30 16:11
Hi, @nimashiri 

Apologize for the delay and I was able to replicate the issue on Google Colab and code is getting crashed so I'll dig more into this issue and I'll update here soon about this issue 

For your reference I have added screenshot of error log below, Thank you!

![image](https://user-images.githubusercontent.com/115997457/215530618-9953232d-c04e-423d-86f6-71b4929e930e.png)

**Comment by mihaimaruseac** [comment] 2023-01-30 18:24
Please post code snippet and error directly on the issue, not via a link. The link might become stale, searching for the error will not uncover it

**Comment by mihaimaruseac** [comment] 2023-02-07 19:33
Not actionable, closing. Please report using the right channels.

**Comment by rainwoodman** [comment] 2023-02-10 00:07
The colab refers to a pickle while which appears to be unavailable. Could you make a self contained reproducer, e.g. by constructing the **data argument directly in the colab? Thanks!

**Comment by mihaimaruseac** [comment] 2023-02-10 15:49
(that's the reason I closed this as not actionable)

**Comment by sachinprasadhs** [comment] 2023-02-14 17:53
@dmc1778 , Could you please provide reproducible code, without which it would be difficult to debug the root cause of the issue. Thanks!

**Closed** 2023-02-23 23:23 UTC
Labels: stat:awaiting response, type:bug, stalled, comp:ops, TF 2.10
