### ISSUE TITLE
tf.math.argmin and tf.math.argmax don't support complex

### ISSUE THREAD

**Issue by jstzwj** [tensorflow/tensorflow#41437] opened 2020-07-16 02:39 UTC
**System information**
- OS Platform and Distribution: Windows10 1909
- TensorFlow installed from : binary
- TensorFlow version: 2.2.0rc2
- Python version: 3.8.0
- CUDA/cuDNN version: None

**Describe the current behavior**
The documentation says that input of `argmax` must be one of the following types: float32, float64, int32, uint8, int16, int8, **complex64**, int64, qint8, quint8, qint32, bfloat16, uint16, **complex128** , half, uint32, uint64.
However, I encounter problem when I use complex tensors as input.

**Standalone code to reproduce the issue**
argmin
```python3
a = tf.constant([1j], dtype=tf.complex64)
b = tf.math.argmin(a)
```
argmax
```python3
a = tf.constant([1j], dtype=tf.complex64)
b = tf.math.argmax(a)
```
**Output**
```
2020-07-16 10:27:30.370246: F tensorflow/compiler/xla/literal_util.cc:289] Unhandled primitive type 15
Aborted (core dumped)
```

**Comment by Dynmi** [comment] 2020-07-16 03:54
- **tf.math.argmax** : *Returns the index with the largest value across axes of a tensor.*
- **tf.math.argmin**  : *Returns the index with the smallest value across axes of a tensor.*

But complex numbers can't tell the larger one and the smaller one....
I think that's the reason why they don't support *complex64* and *complex128*

**Comment by jstzwj** [comment] 2020-07-16 04:52
> * **tf.math.argmax** : _Returns the index with the largest value across axes of a tensor._
> * **tf.math.argmin**  : _Returns the index with the smallest value across axes of a tensor._
> 
> But complex numbers can't tell the larger one and the smaller one....
> I think that's the reason why they don't support _complex64_ and _complex128_

Though complex numbers cannot be ordered, many numerical computational softwares, such as numpy and matlab, compare the real part of complex numbers.

**Comment by 4d55397500** [comment] 2020-07-16 05:02
Agreed with @jstzwj , I think the library should be consistent with numpy.

**Comment by ravikyram** [comment] 2020-07-16 05:11
I tried in colab with TF 2.2, 2.3-rc1 and i am seeing the session is crashed.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/87d420209bafe25f94d3f6b11df4ff49/untitled138.ipynb).Thanks!

**Comment by rmothukuru** [comment] 2021-05-04 12:17
Could reproduce the error with **`Tensorflow Version 2.4.1`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/e85c132120cad4dafcef3de086e9eb79/untitled138.ipynb). Thanks!

**Comment by sushreebarsa** [comment] 2021-05-25 12:35
I tried this using tf-nightly version ,got no error as reported .Please check this [gist](https://colab.research.google.com/gist/sushreebarsa/4b1938b1cb6b9278d3e1b900fc3c7a57/untitled111.ipynb?authuser=1)....Thanks !

**Comment by sushreebarsa** [comment] 2021-06-04 11:05
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!

**Closed by sushreebarsa** 2021-06-04 11:05 UTC
Labels: TF 2.2, comp:ops, stat:awaiting tensorflower, type:bug
