### ISSUE TITLE
Unresolved reference from tensorflow.python

### ISSUE THREAD

**Issue by christk1** [tensorflow/tensorflow#29936] opened 2019-06-18 22:23 UTC
**System information**
- Have I written custom code:No
- OS Platform and Distribution:Ubuntu 18.04.2
- TensorFlow installed from:binary
- TensorFlow version:tf-nightly-gpu 1.14.1.dev20190617
- Python version:3.7
- CUDA/cuDNN version:10.0
- GPU model and memory:rtx 2070 8gb

**Describe the current behavior**
cannot import anything from tensorflow.python. 
**Describe the expected behavior**
In tensorflow version 1.13 it works
**Code to reproduce the issue**
from tensorflow.python import tf2 and i get Unresolved reference

**Comment by mihaimaruseac** [comment] 2019-06-19 15:34
Can you please post a code sample and an error message you get?

**Comment by mihaimaruseac** [comment] 2019-06-19 16:20
Can't reproduce:

```bash
mihaimaruseac@ankh:/tmp/github/2$ source bin/activate
(2) mihaimaruseac@ankh:/tmp/github/2$ pip install tf-nightly-gpu
Collecting tf-nightly-gpu
  Downloading https://files.pythonhosted.org/packages/71/e3/f4452d768f2fdc742da9eede23ae65791ba63d52d36f7c98e90b8b8b6c4e/tf_nightly_gpu-1.14.1.dev20190619-cp37-cp37m-manylinux1_x86_64.whl (370.7MB)
     |████████████████████████████████| 370.7MB 140kB/s 
Requirement already satisfied: wheel>=0.26 in ./lib/python3.7/site-packages (from tf-nightly-gpu) (0.33.4)
Collecting termcolor>=1.1.0 (from tf-nightly-gpu)
Collecting absl-py>=0.7.0 (from tf-nightly-gpu)
Collecting astor>=0.6.0 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
Collecting numpy<2.0,>=1.14.5 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/fc/d1/45be1144b03b6b1e24f9a924f23f66b4ad030d834ad31fb9e5581bd328af/numpy-1.16.4-cp37-cp37m-manylinux1_x86_64.whl
Collecting tf-estimator-nightly (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/ff/35/ca8675a841a561ce410b95d17202e7baaa38a8ae29977600c06bad1efb48/tf_estimator_nightly-1.14.0.dev2019061901-py2.py3-none-any.whl
Collecting grpcio>=1.8.6 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/a2/66/a44fc7eb9bd3a9c480a70c30306f175521ca0531e2cf1ca54b74a450fdb9/grpcio-1.21.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting protobuf>=3.6.1 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/ce/86/9f6123c4c6f481862f286dbe13aa2e97bdedd7662f5fc3033c1a41f32f88/protobuf-3.8.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting wrapt>=1.11.1 (from tf-nightly-gpu)
Collecting tb-nightly<1.15.0a0,>=1.14.0a0 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/3a/60/afa129c3621d62c885599076f8e89737d66e5dfffad1a08842b1c11b4540/tb_nightly-1.14.0a20190614-py3-none-any.whl
Collecting keras-preprocessing>=1.0.5 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
Collecting google-pasta>=0.1.6 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/d0/33/376510eb8d6246f3c30545f416b2263eee461e40940c2a4413c711bdf62d/google_pasta-0.1.7-py3-none-any.whl
Collecting keras-applications>=1.0.8 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/71/e3/19762fdfc62877ae9102edf6342d71b28fbfd9dea3d2f96a882ce099b03f/Keras_Applications-1.0.8-py3-none-any.whl
Collecting gast>=0.2.0 (from tf-nightly-gpu)
Collecting six>=1.10.0 (from tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./lib/python3.7/site-packages (from protobuf>=3.6.1->tf-nightly-gpu) (41.0.1)
Collecting markdown>=2.6.8 (from tb-nightly<1.15.0a0,>=1.14.0a0->tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl
Collecting werkzeug>=0.11.15 (from tb-nightly<1.15.0a0,>=1.14.0a0->tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
Collecting h5py (from keras-applications>=1.0.8->tf-nightly-gpu)
  Using cached https://files.pythonhosted.org/packages/8e/fd/2ca5c4f4ed33ac4178f9c4d551e3946ab480866e3cd67a65a67a4bb35367/h5py-2.9.0-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: termcolor, six, absl-py, astor, numpy, tf-estimator-nightly, grpcio, protobuf, wrapt, markdown, werkzeug, tb-nightly, keras-preprocessing, google-pasta, h5py, keras-applications, gast, tf-nightly-gpu
Successfully installed absl-py-0.7.1 astor-0.8.0 gast-0.2.2 google-pasta-0.1.7 grpcio-1.21.1 h5py-2.9.0 keras-applications-1.0.8 keras-preprocessing-1.1.0 markdown-3.1.1 numpy-1.16.4 protobuf-3.8.0 six-1.12.0 tb-nightly-1.14.0a20190614 termcolor-1.1.0 tf-estimator-nightly-1.14.0.dev2019061901 tf-nightly-gpu-1.14.1.dev20190619 werkzeug-0.15.4 wrapt-1.11.2
(2) mihaimaruseac@ankh:/tmp/github/2$ python
```

```python
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python import tf2
>>> import tensorflow as tf
>>> tf.VERSION
'1.14.1-dev20190619'
```

**Comment by mihaimaruseac** [comment] 2019-06-19 16:24
Also, if IDE complains and not Python interpreter, you should also specify which IDE it is. Python doesn't have `Undefined reference` errors on imports.

Probably related: #25602 and follow-up in #29144

**Comment by christk1** [comment] 2019-06-19 16:48
```
from tensorflow.python import tf2

if tf2.enabled():
    print("ok")
else:
    print("not enabled")
```

i tried this and it works but the problem is with pycharm

**Comment by mihaimaruseac** [comment] 2019-06-19 17:03
Then I guess we can close this as a duplicate of #29144. Please reopen if you think it is not a duplicate

**Closed by mihaimaruseac** 2019-06-19 17:03 UTC
