### ISSUE TITLE
Bus Error when running a session

### ISSUE THREAD

**Issue by cSchubes** [tensorflow/tensorflow#15062] opened 2017-12-02 21:57 UTC
### System information
- Running on an ODROID-XU4
- Have I written custom code: No
- OS Platform and Distribution: Linux Ubuntu Mate 16.04
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
- TensorFlow installed from: source
- TensorFlow version: 1.4.0
- Python version: 3.5.2
- Bazel version: 0.8.0
- GCC Version: 5.4.0
- Exact command to reproduce:
python3.5
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow')
sess - tf.Session()
print(sess.run(hello))

### Describe the problem
I have built and installed TensorFlow as a pip package onboard an ODROID-XU4 (32-bit ARM), following the steps in this guide: https://hackernoon.com/running-yolo-on-odroid-yolodroid-5a89481ec141
Everything went smoothly, and I was able to install TensorFlow after a lengthy build time. However, when I try to run any session (such as in the basic example above), the program fails with a Bus Error. Running `pip3 list` shows that Tensorflow is indeed installed, and no errors are thrown when I merely import TensorFlow.

### Source code / logs
I traced the bus error by looking into the /var/log/syslog file and found the following lines associated with the error: `Dec  2 21:24:21 odroid kernel: [ 3658.433306] Alignment trap: python3.5 (10189) PC=0xac0bac42 Instr=0xf9068a1f Address=0xbe8a7da4 FSR 0x811
Dec  2 21:24:21 odroid kernel: [ 3658.433313] Alignment trap: not handling instruction f9068a1f at [<ac0bac42>]
Dec  2 21:24:21 odroid kernel: [ 3658.439021] Unhandled fault: alignment exception (0x811) at 0xbe8a7da4`
So, it appears to be an alignment issue. I tried to force the kernel to attempt to fix the error instead of simply failing by using the following command: `echo 3 > /proc/cpu/alignment`
The three is meant to tell the kernel to fix these alignment issues. However, this strategy has not changed anything about the Bus Error when attempting to run a session. 

Perhaps this is related to the 32-bit architecture I am attempting to run on?

**Comment by tensorflowbutler** [comment] 2017-12-03 06:58
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by cSchubes** [comment] 2017-12-04 03:51
I have updated the post with those specifications

**Comment by drpngx** [comment] 2017-12-05 17:07
Is it 32-bit only? I'm afraid 32-bit won't work.

**Comment by cSchubes** [comment] 2017-12-05 22:16
Yes, the processor onboard is a 32-bit ARM big.LITTLE architecture. It has a Cortex A7 and a Cortex A15 for a total of 8 cores.

**Comment by tensorflowbutler** [comment] 2017-12-22 07:34
It has been 14 days with no activity and this issue has an assignee.Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment] 2018-01-05 19:08
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by drpngx** [comment] 2018-01-05 19:24
@petewarden feel free to remove the label or unassign yourself. thanks!

**Comment by tensorflowbutler** [comment] 2018-01-24 13:17
As this issue has invited community support, please remove the assignee. Otherwise, remove the `community support` label. Thank you.

**Comment by yuanbuckingham** [comment] 2018-01-30 17:48
I come across the same problem, though I installed TensorFlow on BeagleBone Black.
python2.7.13
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow')
sess - tf.Session()
print(sess.run(hello))
Bus eeror

Is there any suggestions of how to fix this?

**Comment by petewarden** [comment] 2018-01-31 19:34
We don't officially support odroid or BeagleBones, but I am surprised to see this error. I have some details on cross-compiling for the similar Pi platforms here:
https://petewarden.com/2017/08/20/cross-compiling-tensorflow-for-the-raspberry-pi/

I did see similar symptoms when I was cross-compiling and wasn't using matching alignment options on the Pi 3, which was fixed by some compile flags:
https://raspberrypi.stackexchange.com/questions/48225/whats-causing-these-crashes-after-cross-compiling

I don't know how this relates to your problem though, and since these are unsupported platforms, closing this bug.

**Closed by petewarden** 2018-01-31 19:34 UTC
Labels: stat:community support

**Comment by Corentin-pro** [comment] 2018-04-10 07:35
@petewarden I have the same issue, I guess my platforms is not supported too.

Where can I find the supported platform list?

**Comment by cedricve** [comment] 2018-08-28 04:46
having the same issue on Raspberry Pi 3.

**Comment by PINTO0309** [comment] 2018-11-05 14:15
@cedricve 
I solved **`Bus Error`**.
I do not know if I can contribute to you, but I preserved the binaries pre-created below.
**https://github.com/PINTO0309/Tensorflow-bin.git**
I just built a native build on RaspberryPi3.

**Comment by cSchubes** [comment] 2018-11-06 02:56
@PINTO0309 I am no longer working with the device I had this problem with, however I am happy to see some progress on this. I will test this when I get the chance.

**Comment by Kishwar** [comment] 2019-01-01 20:18
@PINTO0309 It seems binaries are for Pi and TX2. I am also facing same issue with Odroid. Could you please explain how you solved bus error?

Thanks.

**Comment by PINTO0309** [comment] 2019-01-01 22:51
@Kishwar 

I just built a **`native build`** on RaspberryPi3 and TX2.
There seems to be a problem with cross compile scripts.
The point you need to be aware of is that it takes dozens of hours for native builds to use low-spec devices.
Unfortunately, I do not own "Odroid", so I can not try it.

**Comment by Kishwar** [comment] 2019-01-03 10:19
@PINTO0309 

Thanks for the response. Your binary for Pi is working on Odroid XU4. 

```
>>> import tensorflow as tf
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
b'Hello, TensorFlow!'
```

Warning msg because binaries are compiled for Python3.5 but Odroid have 3.6.

If anyone installing binary compiled with 3.5 with pip3 of python will get following error msg:

**tensorflow-1.11.0-cp35-cp35m-linux_armv7l.whl is not a supported wheel on this platform.**

Solution: 
1. Rename file to tensorflow-1.11.0-cp36-cp36m-linux_armv7l.whl 
2. Install using python3 -m pip install tensorflow-1.11.0-cp36-cp36m-linux_armv7l.whl 

Enjoy :)
