### ISSUE TITLE
Please offer binary without SSE4.1 instructions

### ISSUE THREAD

**Issue by pannous** [tensorflow/tensorflow#25519] opened 2019-02-05 10:50 UTC
Some machines don't have SSE4.1 CPU instructions, resulting in this error:
https://github.com/tensorflow/tensorflow/issues/7138

Instead of forcing users to manually compile their version of tensorflow you should offer a compiled binary (on pip) with SSE4.1 instructions disabled.

**Comment by gunan** [comment] 2019-02-05 21:57
Marking as duplicate of https://github.com/tensorflow/tensorflow/issues/19584
I understand your pain, and we are working on a system to enable custom build and delivery of binaries to users. But that is still a few months away.

**Closed by gunan** 2019-02-05 21:57 UTC
Labels: type:build/install, type:feature
