### ISSUE TITLE
zlib.h not found when compile tensorflow with GPU support

### ISSUE THREAD

**Issue by 333caowei** [tensorflow/tensorflow#2364] opened 2016-05-14 08:45 UTC
I am trying to compile tensorflow from source. I can build it **successfully** with CPU support only( i.e. not use ```--config=cuda```) .

But when I try to build it with GPU support, I get error:
```
[chaowei@node07 tensorflow]$ export EXTRA_BAZEL_ARGS='-s --verbose_failures --ignore_unsupported_sandboxing --genrule_strategy=standalone --spawn_strategy=standalone --jobs 8'
[chaowei@node07 tensorflow]$ 
[chaowei@node07 tensorflow]$ /gpfs/home/chaowei/download/bazel-0.1.5/output/bazel  build -c opt --config=cuda --linkopt '-lrt' --copt="-DGPR_BACKWARDS_COMPATIBILITY_MODE" --conlyopt="-std=c99" //tensorflow/tools/pip_package:build_pip_package
...........
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /gpfs/home/chaowei/.cache/bazel/_bazel_chaowei/2ce35f089de902cec16e4a2c6a450834/external/grpc/BUILD:485:1: C++ compilation of rule '@grpc//:grpc_unsecure' failed: gcc failed: error executing command /gpfs/home/chaowei/software/gcc-6.1.0/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 ... (remaining 39 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/grpc/src/core/compression/message_compress.c:41:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 71.894s, Critical Path: 58.77s
```

**I also compile python3 from source in my computer. And when I ```import zlib```, it works fine.**

Here is the information of my system:
```[chaowei@mgt ~]$ cat /etc/redhat-release Red Hat Enterprise Linux Server release 6.5 (Santiago)```

```
[chaowei@node07 gcc-6.1.0]$ gcc -v
built-in specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/gpfs/home/chaowei/software/gcc-6.1.0/libexec/gcc/x86_64-pc-linux-gnu/6.1.0/lto-wrapper
Target：x86_64-pc-linux-gnu
Configured with：./configure --prefix=/gpfs/home/chaowei/software/gcc-6.1.0
Thread model：posix
gcc version 6.1.0 (GCC) 
```

I wonder  why I get ```zlib.h``` error  when I only build tensorflow with GPU support.

**Comment by hholst80** [comment] 2016-05-16 07:29
You need zlib1g**-dev** installed.

**Comment by 333caowei** [comment] 2016-05-16 07:41
@hholst80 I have tried ```yum install zlib-delve``` before and it showed ```zlib-devel has been installed```

**Comment by girving** [comment] 2016-06-07 16:40
@333caowei: Where is your `zlib.h`?

**Comment by girving** [comment] 2016-06-07 17:34
Closing as duplicate of #2536, which was filed later but seems to have a more useful thread.

**Closed by girving** 2016-06-07 17:34 UTC
Labels: awaiting response
