### ISSUE TITLE
MultiRNNCell with attention cause Dimensions error

### ISSUE THREAD

**Issue by fword** [tensorflow/tensorflow#15841] opened 2018-01-04 09:55 UTC
when i use MultiRNNCell  and attention for decoding,it goes to 

> ValueError: Dimensions must be equal, but are 2048 and 3072 for 'read/decode/seq_decode/while/BasicDecoderStep/seq_decode/attention_wrapper/attention_wrapper/multi_rnn_cell/cell_0/cell_0/lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [?,2048], [3072,4096].

I trace the code,and found it maybe a bug:
https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/python/ops/rnn_cell_impl.py:
line:1066 calls to LSTMCell(line:600),its _linear1 is initialization from the first LSTMCELL, and will not initialization from the second LSTMCELL. my first LSTMCELL input is with attention.its shape is (?, emb+attention)
but,my second LSTMCELL input is without attention because it called in the while loop, which shape is (?, emb).,When second LSTMCELL use _linear1 is initialization from the first LSTMCELL,it goes to this error

**Comment by tensorflowbutler** [comment] 2018-01-04 19:05
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by tensorflowbutler** [comment] 2018-01-24 13:14
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-02-08 19:25
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by fword** [comment] 2018-02-09 02:32
yes

**Comment by skye** [comment] 2018-02-09 17:39
Please edit your original post to include the information requested by the butler above (or if you wish, close this issue and fill out a new one using the issue template, which requests the same information). We need this information to reproduce the problem you're experiencing, among other reasons. Thanks.

**Comment by tensorflowbutler** [comment] 2018-03-03 08:01
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-03-18 16:01
Nagging Awaiting Response: It has been 14 days with no activityand the `awaiting response` label was assigned. Is this still an issue?

**Comment by tensorflowbutler** [comment] 2018-04-02 12:28
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by reedwm** [comment] 2018-04-03 01:54
Closing since the issue template is not filled out. Please reopen and fill out the template if you are still encountering the issue.

**Closed by reedwm** 2018-04-03 01:54 UTC
Labels: stat:awaiting response
