### ISSUE TITLE
Segmentation fault with nightly-gpu docker

### ISSUE THREAD

**Issue by ben-arnao** [tensorflow/tensorflow#37717] opened 2020-03-19 15:38 UTC
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): No
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: No
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): Nightly-gpu (2.2)
- Python version: - Bazel
version (if compiling from source): Python 3.6.9
- GCC/Compiler version (if compiling from
source): N/A
- CUDA/cuDNN version: - GPU model and memory: RTX 2080 Ti 11GB CUDA 10.1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

Segmentation fault (core dumped) mid-train after calling model.fit()

I use a callback to check memory and it seems like may be there is a memory leak.

**Describe the expected behavior**

Not have this happen

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Cannot provide, i have a large dataset (10gb for training inputs).

I can train fine on my local 1060 6gb card with same amount of CPU memory (32GB). But it seems like this docker image has a problem with a memory leak.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

No logs, just this error.

**Comment by amahendrakar** [comment] 2020-03-20 05:59
@ben-arnao,
In order to expedite the trouble-shooting process, we need the reproducible code. 
Is it possible to provide the minimal code snippet with a sample dataset. Thanks!

**Comment by amahendrakar** [comment] 2020-03-30 07:12
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment] 2020-04-07 12:54
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by amahendrakar** 2020-04-07 12:54 UTC
Labels: stat:awaiting response, type:bug
