### ISSUE TITLE
reset_states raising 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#25852] opened 2019-02-18 22:25 UTC
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OS X 10.14.3
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.13.0-dev20190215
- Python version: 3.7

**Describe the current behavior**
```python
import tensorflow as tf

import tensorflow.keras as keras 

rnn=keras.layers.SimpleRNN(1, stateful=True)

rnn.reset_states()
```

causes

```
TypeError                                 Traceback (most recent call last)
<ipython-input-8-271e0ab7f330> in <module>
      5 rnn=keras.layers.SimpleRNN(1, stateful=True)
      6 
----> 7 rnn.reset_states()

/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/recurrent.py in reset_states(self, states)
    889       batch_size = self.input_spec[0].shape[1]
    890     else:
--> 891       batch_size = self.input_spec[0].shape[0]
    892     if not batch_size:
    893       raise ValueError('If a RNN is stateful, it needs to know '

TypeError: 'NoneType' object is not subscriptable
```

**Describe the expected behavior**

A meaningful error message is generated with instructions on why this doesn't work.

**Comment by ajimenezUCLA** [comment] 2019-02-19 00:11
I think I can fix this for you and raise the error you want. I believe the issue is you're setting stateful to True, its used the last state in the batches as the initial state for the sample. Could you better describe what it is you're trying to do with the code?

**Comment by qlzh727** [comment] 2019-03-11 14:25
This should now be fixed by https://github.com/tensorflow/tensorflow/commit/83df61b4d4ad11f3b8cf05ee98d29e6fb5e25506.

**Comment by qlzh727** [comment] 2019-03-12 16:07
This should now be fixed by https://github.com/tensorflow/tensorflow/commit/6108cbd1dbfbb0ac9dd9d88ada1064925b7f5b19.

**Closed by qlzh727** 2019-03-12 16:07 UTC
Labels: TF 1.13, comp:keras, stat:awaiting tensorflower
