### ISSUE TITLE
experimental apis in iOS pod is missing.

### ISSUE THREAD

**Issue by songww** [tensorflow/tensorflow#46852] opened 2021-02-02 10:16 UTC
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): v2.4
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
experimental apis  in iOS pod is missing.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**

**Any Other info.**

**Comment by rmothukuru** [comment] 2021-02-02 10:26
@songww, 
Can you please elaborate. Also, can you please specify a use case with respect to this request. Thanks!

**Comment by songww** [comment] 2021-02-02 10:41
Invoke `TfLiteInterpreterResetVariableTensors` .
the results of prediction for same inputs super difference within one interpreter.

**Comment by jdduke** [comment] 2021-02-03 17:58
It's still not clear what the issue is. 

> experimental apis in iOS pod is missing.

> Invoke TfLiteInterpreterResetVariableTensors .

Are you saying that you'd like this API to be added to the iOS Cocoapods?

**Comment by songww** [comment] 2021-02-04 04:01
> Are you saying that you'd like this API to be added to the iOS Cocoapods?
Yes.

**Comment by teijeong** [comment] 2021-02-08 01:56
Seems APIs in `tensorflow/lite/c/c_api_experimental.h` are not exported to to CocoaPods for now, not sure if we have plans to do so. Assigning @yyoon for further information.

**Comment by songww** [comment] 2021-02-19 16:06
@yyoon  Any plan for that?

**Comment by yyoon** [comment] 2021-02-22 06:11
Seems reasonable to add, given that the same feature has been available on Android side for a while. Will add this feature soon.

**Comment by songww** [comment] 2021-02-22 12:32
> Seems reasonable to add, given that the same feature has been available on Android side for a while. Will add this feature soon.

Thanks.

**Comment by yyoon** [comment] 2021-07-27 05:36
Hi @songww. I believe this should be done as #49313 is merged. This will be included in the next stable release, and also should be available through nightly builds in the meantime. Please let us know if you still have issues.

**Closed by yyoon** 2021-07-27 05:36 UTC
Labels: comp:lite, type:feature
