### ISSUE TITLE
The error occurs during the training

### ISSUE THREAD

**Issue by chengjianhong** [tensorflow/tensorflow#29349] opened 2019-06-03 08:34 UTC
Hi, The following error occurs during the training, and I don't know what is wrong and why ? Can you give me some guides?

> Epoch 14/500
> 
>   1/379 [..............................] - ETA: 2:47 - loss: 0.3781 - acc: 0.0589 - dice_coefficient: 0.6219
>   2/379 [..............................] - ETA: 2:42 - loss: 0.4649 - acc: 0.1007 - dice_coefficient: 0.5351
>   3/379 [..............................] - ETA: 2:41 - loss: 0.4255 - acc: 0.1039 - dice_coefficient: 0.5745
>   4/379 [..............................] - ETA: 2:40 - loss: 0.5212 - acc: 0.1125 - dice_coefficient: 0.4788
>   5/379 [..............................] - ETA: 2:40 - loss: 0.4794 - acc: 0.0989 - dice_coefficient: 0.5206
>   6/379 [..............................] - ETA: 2:39 - loss: 0.4852 - acc: 0.0932 - dice_coefficient: 0.5148
>   7/379 [..............................] - ETA: 2:42 - loss: 0.4820 - acc: 0.0836 - dice_coefficient: 0.5180
>   8/379 [..............................] - ETA: 2:42 - loss: 0.5002 - acc: 0.0879 - dice_coefficient: 0.4998
>   9/379 [..............................] - ETA: 2:41 - loss: 0.4970 - acc: 0.0849 - dice_coefficient: 0.5030
>  10/379 [..............................] - ETA: 2:41 - loss: 0.4749 - acc: 0.0865 - dice_coefficient: 0.5251
>  11/379 [..............................] - ETA: 2:40 - loss: 0.4679 - acc: 0.0840 - dice_coefficient: 0.5321
>  12/379 [..............................] - ETA: 2:39 - loss: 0.4617 - acc: 0.0879 - dice_coefficient: 0.5383
>  13/379 [>.............................] - ETA: 3:42 - loss: 0.4474 - acc: 0.0889 - dice_coefficient: 0.5526
>  14/379 [>.............................] - ETA: 4:58 - loss: 0.4365 - acc: 0.0878 - dice_coefficient: 0.5635
>  15/379 [>.............................] - ETA: 5:51 - loss: 0.4238 - acc: 0.0836 - dice_coefficient: 0.5762
>  16/379 [>.............................] - ETA: 6:52 - loss: 0.4224 - acc: 0.0866 - dice_coefficient: 0.5776
>  17/379 [>.............................] - ETA: 7:45 - loss: 0.4172 - acc: 0.0905 - dice_coefficient: 0.58282019-06-03 16:02:15.556534: F tensorflow/stream_executor/cuda/cuda_dnn.cc:521] Check failed: cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)batch_descriptor: {count: 0 feature_map_count: 3 spatial: 64 64 64  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}

**Comment by achandraa** [comment] 2019-06-04 08:16
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact minimal code snippet to reproduce the issue included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment] 2019-06-10 08:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by achandraa** 2019-06-10 08:28 UTC
Labels: comp:ops, stat:awaiting response, type:support
