### ISSUE TITLE
order of the inputs and the outputs, within the TF-lite model, is not according to the original TF model. How to solve it?

### ISSUE THREAD

**Issue by gideonKogan** [tensorflow/tensorflow#57693] opened 2022-09-14 12:11 UTC
### 1. System information

- macOS 12.5.1
- TensorFlow 2.10.0

### 2. Code

```
input1 = tf.keras.layers.Input(shape=(3,3,2), name="input1")
input2 = tf.keras.layers.Input(shape=(3,3,4), name="input2")
input3 = tf.keras.layers.Input(shape=(3,3,6), name="input3")
input4 = tf.keras.layers.Input(shape=(3,3,8), name="input4")

input5 = tf.keras.layers.concatenate([input1, input2, input3, input4], axis=-1, name="input5")
model = tf.keras.Model(inputs=[input1, input2, input3, input4], outputs=[input1, input2, input3, input4, input5])
```

[Colab notebook with the model above and the prints of the input/output details + signatures](https://colab.research.google.com/drive/1Zegxc5kR8ckJYnVhg6lLpAX6dD54pSiz?usp=sharing)

### 3. Failure after conversion

The order of the inputs and the outputs, within the TF-lite model, is not according to the original TF model. I have seen similar issues such as [56985](https://github.com/tensorflow/tensorflow/issues/56985) and [57043](https://github.com/tensorflow/tensorflow/issues/57043) with suggestions related to the signature and the names' sorting. Nevertheless, I could not manage to find the order of inputs and the outputs, within the TF-lite model, with respect to the original TF model.

**Comment by mohantym** [comment] 2022-09-16 08:42
Hi @sachinprasadhs !
Could you look at this issue. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/c3bcc903577f0f6bb437a9286a740893/untitled0.ipynb#scrollTo=L6EtpUn1ebKz), [2.9](https://colab.sandbox.google.com/gist/mohantym/7f16ce33a0b14ea8f88b4f207bab0bd2/untitled0.ipynb#scrollTo=L6EtpUn1ebKz), [2.10 ](https://colab.sandbox.google.com/gist/mohantym/2409456161de92ddf602c813f4eb68f7/untitled0.ipynb#scrollTo=7RuWg_LlGfXl)and [nightly](https://colab.sandbox.google.com/gist/mohantym/ed3d51743fc6f896e6385e40969f0278/untitled0.ipynb) for reference.
Thank you!

**Comment by sachinprasadhs** [comment] 2022-09-16 19:07
Hi, This issue seems to be the duplicate of the issues which you have mentioned above, could you please track the progress in those issues and close this issue. Thanks!

**Comment by gideonKogan** [comment] 2022-09-17 19:39
@sachinprasadhs, several solutions have been suggested but non of them have been demonstrated on a minimal example. Since I have tried implementing some of those solutions on my example without any success, I wanted to encourage the responders in the attached posts to demonstrate their solutions on this example. Do you think that we can integrate all these posts into one with a minimal example?

**Comment by sachinprasadhs** [comment] 2022-09-19 18:20
Team has looked into those linked issues, and will come up with the possible outcome.
You can track the status in those linked issues, since the issues are still open, it would be easier for us to track it in a single source. Thanks!

**Closed** 2022-09-19 20:01 UTC
Labels: stat:awaiting response, type:bug, comp:lite, TFLiteConverter, TF 2.10
