### ISSUE TITLE
Unknown: input/output error

### ISSUE THREAD

**Issue by slala2121** [tensorflow/tensorflow#50824] opened 2021-07-18 15:50 UTC
When running my training script, I encounter this error inconsistently for different tfrecords (in the run below it was 11, but this number changes). I don't think it's an issue with the particular file mentioned below as I've been able to read every tfrecord I'm using with a separate script.

Unknown: dataset-train.tfrecord-00011-of00032; Input/output error
[[{{node MultiDeviceIteratorGetNextShard}}]][[RemoteCall]][[while/boy/_1/IteratorGetNext_1]][[while/body/_1/replica_1/mod/y/_39]]

Does anyone have thoughts on what is triggered this inconsistency?

**Comment by saikumarchalla** [comment] 2021-07-19 05:09
@slala2121 Could you please fill the issue template.Also Please provide the simple standalone code/ colab link to reproduce the issue at our end.Thanks

**Comment by saikumarchalla** [comment] 2021-07-28 16:43
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by saikumarchalla** 2021-07-28 16:43 UTC
Labels: stalled, stat:awaiting response, type:others
