### ISSUE TITLE
tf2.1 with gpu can't open cuda 10.2

### ISSUE THREAD

**Issue by jacketchan** [tensorflow/tensorflow#37253] opened 2020-03-03 09:51 UTC
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  windows 10 (profession)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: v2.1.0-rc2-17-ge5bf8de410
- Python version:  3.68
- Installed using virtualenv? pip? conda?:  pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2 cuda / 7.6 cudnn
- GPU model and memory:  2G

**Describe the problem**

ERROR: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] cannot opened dynamic library cudart64_101.dll

**Provide the exact sequence of commands / steps that you executed before running into the problem**

My computer has windows 10 professional vesion os, and GPU-GTX1050. Then Install the cuda 10.2 and cudnn 7.6 version.  I use Pycharm professional version create a virtual env. Wait a moment, use pip install the tensorflow-2.1-gpu version, successfully. When I test the tensorflow2.1-gpu version, it arises the error "cannot opened dynamic library cudart64_101.dll".

How do I resolve? 
Maybe It is something wrong with cuda10.2, therefore ,I search the dir where i install the cuda. I find the directory-bin which has cudart64_102.dll , not cudart64_101.dll. For safely, i copy cudart64_102.dll, and rename , push into the bin directory. 

Then i rerun the tf, it can work...
2020-03-03 16:38:19.699659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll

**Any other info / logs**

Maybe it is something wrong with cuda10.2 and tensorflow-2.1-gpu.
Tensorflow can't find the cudart64_101.dll. The cuda10.2 has not cudart64_101.dll, but has cudart64_102.dll. Ok, it should be the api.

**Comment by gadagashwini** [comment] 2020-03-03 10:59
@jacketchan, Tensorflow-gpu==2.1 supports CUDA 10.1 which will have cudart64_101.dll file. 
Since, CUDA 10.2 will have cudart64_102.dll file which is not supported by Tensorflow 2.1. 
Please downgrade the CUDA version to 10.1. Let us know how it progresses. Thanks!

**Comment by liuxingbaoyu** [comment] 2020-03-03 11:24
You can try [this](https://github.com/fo40225/tensorflow-windows-wheel)

**Comment by gadagashwini** [comment] 2020-03-13 10:23
@jacketchan, Issue still persists?

**Comment by gadagashwini** [comment] 2020-03-26 08:06
Since the title of the issue is resolved.Closing this issue. Thanks

**Closed by gadagashwini** 2020-03-26 08:06 UTC
Labels: TF 2.1, stat:awaiting response, subtype:windows, type:build/install
