### ISSUE TITLE
mixed keras import levels lead to untracked variables

### ISSUE THREAD

**Issue by qp-qp** [tensorflow/tensorflow#50249] opened 2021-06-14 02:06 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.2 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5
- Python version: Ubuntu 20.04.2 
- CUDA/cuDNN version: 11.2/8.1.0
- GPU model and memory: RTX 2080 TI

**Describe the current behavior**
Mixing layers (e.g. Input, Dense) which are imported via
`from tensorflow import keras`
`Input = keras.layers.Input()`
and 
`from keras.layers import Dense`
`Linear = Dense()`
leads to variables not being tracked
**Describe the expected behavior**
variables should be tracked

**Standalone code to reproduce the issue**
```
from tensorflow import keras
from keras.layers import Input, Dense


input1 = keras.layers.Input(shape=(2, 2))
input2 = Input(shape=(2, 2))
linear_layer = Dense(4)

y = linear_layer(input1)
model1 = keras.Model(input1, y)

y = linear_layer(input2)
model2 = keras.Model(input2, y)
print(model1.trainable_variables)
#outputs:
#[]
print(model2.trainable_variables)
#outputs:
#[<tf.Variable 'dense/kernel:0' shape=(2, 4) dtype=float32, numpy=
#array([[ 0.26048756,  0.08715534,  0.3931222 , -0.02270007],
#       [-0.17754197, -0.7752099 , -0.3470106 ,  0.85839653]],
#      dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]
```
**Any Other info**
Tensorflow issues a warning related to Lambda layers: 
```WARNING:tensorflow:
The following Variables were used a Lambda layer's call (tf.tensordot), but
are not present in its tracked objects:
  <tf.Variable 'dense/kernel:0' shape=(2, 4) dtype=float32>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.'```

**Comment by UsharaniPagadala** [comment] 2021-06-14 14:52
@qp-qp 

I reproduced the code shared with minimal code changes with no errors.Please find the [gist](https://colab.research.google.com/gist/UsharaniPagadala/03744c3054a6f4eae40ae6d907a811df/untitled92.ipynb) here, and let us know if it  helps.Thanks

**Comment by qp-qp** [comment] 2021-06-14 15:28
@UsharaniPagadala 
Hey thanks for the reply. I know that it is possible to change the code such that the variables are being tracked (Hence I included the example of model2 with tracked variables).
My problem is that I think that the behavior exhibited in my code example is quite prone to cause bugs.

**Comment by jvishnuvardhan** [comment] 2021-06-15 04:36
@qp-qp Looks like some layers were imported from `keras` and others from `tf.keras`. I changed one line in your code and everything works as expected.

```
# from keras.layers import Input, Dense # this imports Dense from keras and results in [] variables for model 1
from tensorflow.keras.layers import Input, Dense 
```

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/d2b0a3660f882aa5aff1533b4a8d15a0/untitled92.ipynb).

Please verify once and close the issue if this is resolved for you. Thanks!

**Comment by qp-qp** [comment] 2021-06-15 16:41
@jvishnuvardhan
I am aware that the problem is caused by mixing layer imports from `keras` and tf.keras. This was the reason for raising this issue, as I thought that this behavior was a bug.
However, if it is the intended behavior that mixing layers leads to untracked variables while everything else (e.g. forward pass) . works normally, I will close this issue.

**Comment by jvishnuvardhan** [comment] 2021-06-15 17:54
@qp-qp Looks like this is a bug. What I gave above was a workaround, so we will keep this open. Thanks!

**Comment by chenmoneygithub** [comment] 2021-07-01 22:11
Briefly, keras and tf.keras referred to different packages, so there are some integration errors. In Tensorflow 2.6 (release soon) this error is fixed.

**Closed by chenmoneygithub** 2021-07-01 22:11 UTC
Labels: TF 2.5, comp:keras, stat:awaiting tensorflower, type:bug
