### ISSUE TITLE
Tensorboard not executing as '__main__', name conflict with directory?

### ISSUE THREAD

**Issue by mikowals** [tensorflow/tensorflow#5133] opened 2016-10-22 03:47 UTC
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

[Similar errors identified as name conflicts between module and directory](http://stackoverflow.com/questions/24829769/module-object-has-no-attribute-main-django)

### Environment info
Operating System:  macOS Sierra

If installed from binary pip package, provide:

1. A link to the pip package you installed:
current osx [nightly](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=mac-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0rc0-py2-none-any.whl)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11.0rc0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

In terminal window run 'tensorboard'

Output: 

>File "<TENSORFLOW DIR>/tensorflow/lib/python2.7/site-packages/tensorflow/tensorboard/tensorboard.py", line 43, in main
    logdir = os.path.expanduser(FLAGS.logdir)
AttributeError: 'NoneType' object has no attribute 'logdir'

### What other attempted solutions have you tried?
A workaround is to rename tensorboard.py (I used tensorboard1.py) and execute with full path to that file.

Originally I printed `__name__`  and learned it was 'tensorflow.tensorboard.tensorboard'.

**Comment by llhe** [comment] 2016-10-22 07:36
Looks like it's a regression introduced by the argparse refactoring

**Comment by asimshankar** [comment] 2016-10-22 08:03
Thanks for the report @mikowals and the diagnosis @llhe. This is indeed a result of the argparse refactoring.

FYI @elibixby

**Comment by elibixby** [comment] 2016-10-22 15:57
This is a duplicate of #4903 a rollback of the offending CLs changes to Tensorboard is in  progress.

**Closed by elibixby** 2016-10-22 15:57 UTC
