### ISSUE TITLE
libcuda.so.1: cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by iantimmis** [tensorflow/tensorflow#30670] opened 2019-07-13 01:13 UTC
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version: 1.13
- Python version: 3.7
- Installed using virtualenv? pip? conda?: Conda
- CUDA/cuDNN version: cudatoolkit version 10 and cudnn version 7.6 (according to conda list)
- GPU model and memory: 2080ti 11gb 🥇 

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

I create a new conda environment and run conda install tensorflow-gpu. Next I start up a python terminal and import tensorflow as tf. My error message received is in next section.

**Any other info / logs**

> Traceback (most recent call last):
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/home/ian/anaconda3/envs/tf_gpu/lib/python3.7/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.

**Comment by gadagashwini** [comment] 2019-07-15 13:00
@iantimmis Just to verify, Did you install CUDA toolkit in the same environment? Thanks!

**Comment by iantimmis** [comment] 2019-07-15 13:34
I think so. I'm under the impression that conda handles that for you. When I run "conda list", I see that cudatoolkit version 10 is present.

**Comment by gadagashwini** [comment] 2019-07-16 08:41
@iantimmis Looks like similar issue, please take a look at [#26209](https://github.com/tensorflow/tensorflow/issues/26209). Let us know if that helps. Thanks!

**Comment by gadagashwini** [comment] 2019-07-23 05:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by gadagashwini** 2019-07-23 05:25 UTC
Labels: stat:awaiting response, subtype: ubuntu/linux, type:build/install

**Comment by nashit-mashkoor** [comment] 2020-09-16 09:12
The isssue is still exisiting

**Comment by nashit-mashkoor** [comment] 2020-09-16 09:12
The issue is still exisiting

**Comment by Didayolo** [comment] 2020-09-17 16:59
Yes, same issue with same configuration

**Comment by sksenthilkumar** [comment] 2020-09-21 13:58
The issue is still existing

**Comment by eddiem3** [comment] 2020-09-21 19:11
Just ran into it myself
