### ISSUE TITLE
Wrong x_lerp computation in "ResizeBilinearKernel_faster" and "ResizeBilinearKernel"

### ISSUE THREAD

**Issue by PCSCI** [tensorflow/tensorflow#38389] opened 2020-04-09 12:13 UTC
This is a bug on compute the **x_lerp** in CUDA version of resize_bilinear. See the code in 
[ResizeBilinearKernel_faster](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc#L62) and [ResizeBilinearKernel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc#L141). 

The computation of **x_lerp** is different from **y_lerp** in cuda version, which should regarded the symmetric operation on different axis.  When computing the grad, the **x_lerp** has been computed correctly, see code [ResizeBilinearGradKernel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op_gpu.cu.cc#L199)

Besides, its also different from the cpu version of resize_bilinear, see code in [ResizeGradCore](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resize_bilinear_op.cc#L339).

**System information** 
Ubuntu 18.04
standard TF 2.1 (installed from pip)

**Describe the current behavior**
`const float x_lerp = in_x - left_x_index;`

**Describe the expected behavior**
`const float x_lerp = in_x - floorf(in_x);`

The bug comes from the incorrect computation of x_lerp (as described above). And the code link is also listed above (The links on ResizeBilinearKernel and ResizeBilinearKernel_faster)

**Standalone code to reproduce the issue**
The bug comes from the CUDA code, which is found by reading the code myself.

**Comment by ravikyram** [comment] 2020-04-13 10:27
@PCSCI 

Please, let us know which tensorflow version you are using? Also, request you to fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose)

Also, please share simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by PCSCI** [comment] 2020-04-13 13:27
> Also, please share simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

I have updated the description. Besides, I think my previous description is also simple and straightforward, as I have put the code links, which referring to the line I described.  The bug is contained in the standard distribution of TF 2.1 (w.r.t to the code release), and I could not provide the code to reproduce it, since I find the bug by reading the tensorflow code.

**Comment by Saduf2019** [comment] 2021-05-19 11:25
@PCSCI 

Is this still an issue?

Could you please check if you are facing the same error with TF v2.4.1/nightly as well? Thanks!

**Comment by bhack** [comment] 2021-05-19 11:33
One master `const int left_x_index = in_x > 0.0 ? floorf(in_x) : 0;` so I think that we could close this

https://github.com/tensorflow/tensorflow/blob/3fd3ae1fbb10961dd1aa6805280674c781fd4609/tensorflow/core/kernels/image/resize_bilinear_op_gpu.cu.cc#L60-L63

**Comment by PCSCI** [comment] 2021-05-19 11:56
Is this still an issue @Saduf2019 @bhack 。

Although for in_x > 0.0, the computation of x_lerp and y_lerp are the same. But for in_x < 0, the computation formula is different. This kind of difference is weird during application of reisze kernels.

**Comment by bhack** [comment] 2021-05-19 12:07
Mhh.. Can you extend the test to cover `in_x < 0 case`? 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/resize_bilinear_op_test.cc

**Comment by PCSCI** [comment] 2021-05-27 08:17
> Mhh.. Can you extend the test to cover `in_x < 0 case`?

I will try to learn it in weekends.

**Comment by PCSCI** [comment] 2021-05-27 08:19
> Mhh.. Can you extend the test to cover `in_x < 0 case`?
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/resize_bilinear_op_test.cc

It seems difficult for me to add the test cases in resize_bilinear_op_test.cc, as I don't have the environment available to build the tensorflow gpu version now.

**Comment by bhack** [comment] 2021-05-27 11:38
@PCSCI If the diff it is not too large to be developed you could use directly the CI tests with a PR

**Comment by bhack** [comment] 2021-06-03 12:17
@sanjoy What do you think?

**Comment by reedwm** [comment] 2021-06-04 21:20
The inconsistency between the computation of `x_lerp` and `y_lerp` will never result in incorrect output. The calculations of both values is below:

https://github.com/tensorflow/tensorflow/blob/c78f78dc015b8b75fd7ba5e0186899f755eeb8ef/tensorflow/core/kernels/image/resize_bilinear_op_gpu.cu.cc#L131-L142

`x_lerp` is currently set to `in_x - left_x_index`, while the issue suggests changing it to `in_x - floorf(in_x)` instead, to be more consistent with `y_lerp`. However, making such a change will never change the output. To see why, note making such a change only affects the value of `x_lerp` when `in_x <= 0`. In such a case, `left_x_index` and `right_x_index` will both be zero, so so the left edge and right edge of the box will be the same. However, this means that `x_lerp` is ignored, since `x_lerp` is only used to extrapolate a value between the left and right edges, and this extrapolation has no effect when the two edges are equal. Therefore, changing `x_lerp` from `in_x - left_x_index` to `in_x - floorf(in_x)` has no functional impact.

Still, making such a change would make the code more consistent and easier to understand, so I'll make the change.

**Closed** 2021-06-04 22:36 UTC
Labels: TF 2.1, comp:core, stalled, stat:awaiting response, type:bug
