### ISSUE TITLE
logging broken with Python-3.8: findCaller() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by olk** [tensorflow/tensorflow#35027] opened 2019-12-11 14:17 UTC
**System information**System information
- OS Platform and Distribution: Arch Linux, 5.4.2-arch1-1-ARCH
- TensorFlow installed from: binary
- TensorFlow version: 2.1.0rc0-1
- Keras version: 2.2.4-tf
- Python version: 3.8
- GPU model and memory: 2x GTX 1080 Ti 11GB"`

**Describe the current behavior**
execution of MNIST example fails with error:

> TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

**Code to reproduce the issue**
```
import tensorflow as tf
import tensorflow_datasets as tfds

from tensorflow.keras.optimizers import Adam

def scale(image, label):
  image = tf.cast(image, tf.float32)
  image /= 255
  return image, label

def build_model():
    filters = 56
    units = 24
    kernel_size = 5
    learning_rate = 1e-2
    model = tf.keras.Sequential([
      tf.keras.layers.Conv2D(filters=filters, kernel_size=(kernel_size, kernel_size), activation='relu', input_shape=(28, 28, 1)),
      tf.keras.layers.MaxPooling2D(),
      tf.keras.layers.Flatten(),
      tf.keras.layers.Dense(units, activation='relu'),
      tf.keras.layers.Dense(10, activation='softmax')
    ])
    model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate), metrics=['accuracy'])
    return model

datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)
mnist_train, mnist_test = datasets['train'], datasets['test']

num_train_examples = info.splits['train'].num_examples
num_test_examples = info.splits['test'].num_examples

BUFFER_SIZE = 10000
BATCH_SIZE = 128

train_dataset = mnist_train.map(scale).shuffle(BUFFER_SIZE).repeat().batch(BATCH_SIZE).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
eval_dataset = mnist_test.map(scale).shuffle(BUFFER_SIZE).repeat().batch(BATCH_SIZE).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

model = build_model()

epochs=5
model.fit(
        train_dataset,
        validation_data=eval_dataset,
        steps_per_epoch=num_train_examples/epochs,
        validation_steps=num_test_examples/epochs,
        epochs=epochs)
```

**Other info / logs**

```
traceback:
Downloading and preparing dataset mnist (11.06 MiB) to /home/graemer/tensorflow_datasets/mnist/1.0.0...
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    datasets, info = tfds.load(name='mnist', with_info=True, as_supervised=True)
  File "/usr/lib/python3.8/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow_datasets/core/registered.py", line 302, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py", line 316, in download_and_prepare
    logging.warning(GCS_HOSTED_MSG, self.name)
  File "/usr/lib/python3.8/site-packages/absl/logging/__init__.py", line 322, in warning
    log(WARNING, msg, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/absl/logging/__init__.py", line 485, in log
    _absl_logger.log(standard_level, msg, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/absl/logging/__init__.py", line 1047, in log
    super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by gadagashwini** [comment] 2019-12-17 07:46
@olk, Is this still issue!

**Comment by olk** [comment] 2019-12-18 07:11
@gadagashwini yes still an issue

**Comment by gadagashwini** [comment] 2019-12-19 06:22
May be issue is with Python 3.8.
It is working without any error message on Colab with Python3.6. Thanks!

**Comment by jsimsa** [comment] 2019-12-19 18:58
@jvishnuvardhan please assign "tensorflow_datasets" / TFDS issue to @rsepassi for triage.

**Comment by mihaimaruseac** [comment] 2019-12-19 20:00
Note that we currently don't release python3.8 pip packages.

**Comment by ppwwyyxx** [comment] 2020-01-06 02:52
should now be fixed by https://github.com/abseil/abseil-py/pull/126

**Comment by ravikyram** [comment] 2020-04-24 11:42
@olk 

Is it possible for you to try latest TF versions(`!pip install tensorflow==2.2-rc3`) and let us know whether the issue persists? .Windows/Linux binaries for py3.8 are available in TF 2.2 .Please verify once and close the issue if the issue was resolved. Thanks!

**Comment by ravikyram** [comment] 2020-05-13 12:53
@olk 

Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ravikyram** 2020-05-13 12:53 UTC
Labels: TF 2.1, comp:data, type:bug

**Comment by lgeiger** [comment] 2020-08-13 10:18
This error was reintroduced in the latest release of TensorFlow Metadata.

https://github.com/tensorflow/metadata/pull/10 fixes the problem by loosening the requirements on abseil.
@mihaimaruseac @rsepassi @ravikyram Could you take a look at the PR?

**Comment by mihaimaruseac** [comment] 2020-08-13 16:14
I don't have approval powers over that repo.

**Comment by robotalker** [comment] 2020-09-02 00:06
I am seeing this issue after installing the TensorFlow Object Detection API following along the instructions on this page:

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

and running the test script:

python object_detection/builders/model_builder_tf2_test.py

This is using python 3.8.5 on MacOS Catalina (10.15.6)

Full error from test script:
ERROR: test_create_ssd_models_from_config (__main__.ModelBuilderTF2Test)
test_create_ssd_models_from_config (__main__.ModelBuilderTF2Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/object_detection/builders/model_builder_test.py", line 212, in test_create_ssd_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/object_detection/builders/model_builder.py", line 1061, in build
    return build_func(getattr(model_config, meta_architecture), is_training,
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/object_detection/builders/model_builder.py", line 372, in _build_ssd_model
    feature_extractor = _build_ssd_feature_extractor(
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/object_detection/builders/model_builder.py", line 350, in _build_ssd_feature_extractor
    return feature_extractor_class(**kwargs)
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 294, in __init__
    super(SSDEfficientNetB0BiFPNKerasFeatureExtractor, self).__init__(
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/object_detection/models/ssd_efficientnet_bifpn_feature_extractor.py", line 143, in __init__
    logging.info('EfficientDet EfficientNet backbone version: %s',
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/absl/logging/__init__.py", line 338, in info
    log(INFO, msg, *args, **kwargs)
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/absl/logging/__init__.py", line 485, in log
    _absl_logger.log(standard_level, msg, *args, **kwargs)
  File "/Users/matt/workspace/cv/lib/python3.8/site-packages/absl/logging/__init__.py", line 1047, in log
    super(ABSLLogger, self).log(level, msg, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1500, in log
    self._log(level, msg, args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1565, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

**Comment by alimuldal** [comment] 2020-11-27 11:33
I recently encountered this - the root cause seems to be an incompatibility between `absl-py<0.9` and Python 3.8 (see https://github.com/icubam/icubam/pull/2). Upgrading to a newer version of `absl-py` solved the problem for me.
