### ISSUE TITLE
CMake: Build break occurs when making tf_python_build_pip_package using cmake.

### ISSUE THREAD

**Issue by again4you** [tensorflow/tensorflow#20568] opened 2018-07-05 15:14 UTC
### Problem
Build break occurs when making __tf_python_build_pip_package__ using __cmake__ instead of Bazel.

### System information
* Have I written custom code: N/A
* OS Platform and Distribution: Ubuntu 16.04.4 LTS
* TensorFlow installed from: Not installed
* TensorFlow version: N/A
* Python version: 2.7.12
* Bazel version: Not used since CMake build
* CMake version: 3.5.1
* GCC/Compiler version: 5.4.0
* CUDA/cuDNN version: 9.0 (But not important in this case)
* GPU model and memory: Nvidia 1080ti / 11G
* Exact command to reproduce: refer the below 'How to reproduce'

### Source code information
* Branch: r1.9
* Commit ID: e3f2b5903c56ec09fa501dd8e95dd0e4336843fc (latest when I built)
* Just clone without modification

### How to reproduce 
```bash
$ git clone https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
$ git checkout -b cmake_build_test e3f2b5903c56ec09fa501dd8e95dd0e4336843fc
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ../tensorflow/contrib/cmake
$ make VERBOSE=1 -j4  tf_python_build_pip_package &> cmake_build_log.txt
```

### Error message
* ImportError: No module named tensorflow.python.util
* Download the full build log message: [link](https://www.dropbox.com/s/5hfgqugzbwwu3i2/cmake_build_log.txt?dl=0)
```bash
make[3]: Entering directory '/home/again4you/tensorflow/build'                  
[100%] Generating __init__.py files for Python API.                             
cd /home/again4you/tensorflow/build/tf_python && /usr/bin/cmake -E remove -f /home/again4you/tensorflow/build/tf_python/tensorflow/__init__.py
cd /home/again4you/tensorflow/build/tf_python && /usr/bin/cmake -E env PYTHONPATH=/home/again4you/tensorflow/build/tf_python /usr/bin/python /home/again4you/tensorflow/build/tf_python/tensorflow/tools/api/generator/create_python_api.py --root_init_template=/home/again4you/tensorflow/build/tf_python/tensorflow/api_template.__init__.py --apidir=/home/again4you/tensorflow/build/tf_python/tensorflow /home/again4you/tensorflow/api_init_files_list.txt
Traceback (most recent call last):                                              
  File "/home/again4you/tensorflow/build/tf_python/tensorflow/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.util import tf_decorator                             
ImportError: No module named tensorflow.python.util                             
CMakeFiles/tf_python_api.dir/build.make:57: recipe for target 'tf_python/tensorflow/__init__.py' failed
make[3]: *** [tf_python/tensorflow/__init__.py] Error 1                         
make[3]: Leaving directory '/home/again4you/tensorflow/build'
```

### Detailed reason that I found
* __tf_python/tensorflow/\_\_init.py\_\___ does not exist as below.
```bash
$ ls tf_python/tensorflow/__init__.py
ls: cannot access 'tf_python/tensorflow/__init__.py': No such file or directory
```

* ~~When building tensorflow using __python 3__, it does not matter since python3 supports [Implicit Namespace Packages](https://www.python.org/dev/peps/pep-0420/). So `create_python_api.py` runs without errors. However, __ImportError__ occurs when using __python 2__ if tf_python/tensorflow/\_\_init\_\_.py does not exist.~~
* The similar error occurs when using __python 3__. Refer my below comment.

* After checking the build log with 'VERBOSE' option, I found out the below message.
Because of 'tf_python/tensorflow/**app**' module, 'tf_python/tensorflow/\_\_init\_\_.py' is deleted. But I can't find any 'app' module in tf_python.

```bash
...
[100%] Built target tf_extension_ops                                            
make -f CMakeFiles/tf_python_api.dir/build.make CMakeFiles/tf_python_api.dir/depend
make[3]: Entering directory '/home/again4you/tensorflow/build'                  
cd /home/again4you/tensorflow/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/again4you/tensorflow/tensorflow/contrib/cmake /home/again4you/tensorflow/tensorflow/contrib/cmake /home/again4you/tensorflow/build /home/again4you/tensorflow/build /home/again4you/tensorflow/build/CMakeFiles/tf_python_api.dir/DependInfo.cmake --color=
Deleting primary custom command output "/home/again4you/tensorflow/build/tf_python/tensorflow/__init__.py" because another output "/home/again4you/tensorflow/build/tf_python/tensorflow/app/__init__.py" does not exist.
Dependee "/home/again4you/tensorflow/build/CMakeFiles/tf_python_api.dir/DependInfo.cmake" is newer than depender "/home/again4you/tensorflow/build/CMakeFiles/tf_python_api.dir/depend.internal".
...
```

**Comment by tensorflowbutler** [comment] 2018-07-06 00:48
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
TensorFlow installed from
CUDA/cuDNN version
Exact command to reproduce

**Comment by again4you** [comment] 2018-07-06 06:58
@tensorflowbutler bot. Thanks for quick reply  :)
I just added some omitted information that you requested but i think it is not important. 

@angersson IMHO, it looks like a kind bug. Feel free to ask me if you have any question about this issue. Thanks in advance.

**Comment by again4you** [comment] 2018-07-07 01:37
In case of __Python 3__, the same error also occurs. My test result is as below.

### System information
* Python version: 3.5.3
* Everything is the same except the python version

### Source code information
* Branch: r1.9
* Commit ID: e34327d766016bf4901d847c6ce9eb671db7abb9 (latest at that time)
* Just clone without modification


### How to reproduce
```bash
$ git clone https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
$ git checkout -b cmake_build_test e34327d766016bf4901d847c6ce9eb671db7abb9
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ../tensorflow/contrib/cmake
$ make VERBOSE=1 -j4  tf_python_build_pip_package &> cmake_build_py3_log.txt
```


### Error message
* Download the full build log message: [link](https://www.dropbox.com/s/jfbrqrw7omha6gv/cmake_build_py3_log.txt)
```bash
...
[100%] Built target tf_extension_ops
make -f CMakeFiles/tf_python_api.dir/build.make CMakeFiles/tf_python_api.dir/depend
make[3]: Entering directory '/home/again4you/github_work/tensorflow/build'
cd /home/again4you/github_work/tensorflow/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/again4you/github_work/tensorflow/tensorflow/contrib/cmake /home/again4you/github_work/tensorflow/tensorflow/contrib/cmake /home/again4you/github_work/tensorflow/build /home/again4you/github_work/tensorflow/build /home/again4you/github_work/tensorflow/build/CMakeFiles/tf_python_api.dir/DependInfo.cmake --color=
Deleting primary custom command output "/home/again4you/github_work/tensorflow/build/tf_python/tensorflow/__init__.py" because another output "/home/again4you/github_work/tensorflow/build/tf_python/tensorflow/app/__init__.py" does not exist.
Dependee "/home/again4you/github_work/tensorflow/build/CMakeFiles/tf_python_api.dir/DependInfo.cmake" is newer than depender "/home/again4you/github_work/tensorflow/build/CMakeFiles/tf_python_api.dir/depend.internal".
Dependee "/home/again4you/github_work/tensorflow/build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/again4you/github_work/tensorflow/build/CMakeFiles/tf_python_api.dir/depend.internal".
Scanning dependencies of target tf_python_api
make[3]: Leaving directory '/home/again4you/github_work/tensorflow/build'
make -f CMakeFiles/tf_python_api.dir/build.make CMakeFiles/tf_python_api.dir/build
make[3]: Entering directory '/home/again4you/github_work/tensorflow/build'
[100%] Generating __init__.py files for Python API.
cd /home/again4you/github_work/tensorflow/build/tf_python && /usr/bin/cmake -E remove -f /home/again4you/github_work/tensorflow/build/tf_python/tensorflow/__init__.py
cd /home/again4you/github_work/tensorflow/build/tf_python && /usr/bin/cmake -E env PYTHONPATH=/home/again4you/github_work/tensorflow/build/tf_python /usr/bin/python /home/again4you/github_work/tensorflow/build/tf_python/tensorflow/tools/api/generator/create_python_api.py --root_init_template=/home/again4you/github_work/tensorflow/build/tf_python/tensorflow/api_template.__init__.py --apidir=/home/again4you/github_work/tensorflow/build/tf_python/tensorflow /home/again4you/github_work/tensorflow/api_init_files_list.txt
Traceback (most recent call last):
  File "/home/again4you/github_work/tensorflow/build/tf_python/tensorflow/tools/api/generator/create_python_api.py", line 28, in <module>
    from tensorflow.tools.api.generator import doc_srcs
ImportError: No module named 'tensorflow.tools.api'
...
```

**Comment by again4you** [comment] 2018-07-07 01:54
@annarev, I faced 'ImportError' when running __create_python_api.py__. I am still fighting to resolve this issue but I can't find any doubtful codes until now. Please look and see this issue and let me know the problem if I made a mistake.

**Comment by annarev** [comment] 2018-07-07 02:11
Hi again4you,
Is it possible you have an old version of TensorFlow installed on your system?
It might be that create_python_api.py ends up importing system-installed tensorflow package instead of the one in the build directory.

**Comment by again4you** [comment] 2018-07-07 02:42
@annarev
Thanks for quick reply. 

You means that I __have to__ install Tensorflow on my system to build the Tensorflow from the scratch using cmake. right? If then, I thinks that is not a good point.

Moreover, as you can see the build log that I submit, `create_python_api.py` script runs with __PYTHONPATH=/home/again4you/github_work/tensorflow/build/tf_python__ option so it does not refer system-installed python environment.

```bash
cd /home/again4you/github_work/tensorflow/build/tf_python && /usr/bin/cmake -E env PYTHONPATH=/home/again4you/github_work/tensorflow/build/tf_python /usr/bin/python /home/again4you/github_work/tensorflow/build/tf_python/tensorflow/tools/api/generator/create_python_api.py --root_init_template=/home/again4you/github_work/tensorflow/build/tf_python/tensorflow/api_template.__init__.py --apidir=/home/again4you/github_work/tensorflow/build/tf_python/tensorflow /home/again4you/github_work/tensorflow/api_init_files_list.txt
```

**Comment by again4you** [comment] 2018-07-07 04:55
@annarev, Even installing a previous tensorflow, I faced the same error message.
My test environment is as below.
* python: 3.5.3
* tensorflow: 1.6.0
```python
$ python
Python 3.5.3 (default, Nov 23 2017, 11:34:05) 
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.__version__
'1.6.0'
```

**Comment by angersson** [comment] 2018-07-09 20:31
The TF team only officially supports Bazel builds on Linux, so I'm marking this issue as Community-Supported. Can you try using Bazel instead?

Sorry for the inconvenience.

**Comment by annarev** [comment] 2018-07-09 21:04
@again4you, I meant that if you have an old version installed without that module available, you might see the error. If that is the case, you can create and activate virtualenv before running the build. This way you can make sure system-installed TF does not get picked up by the import in create_python_api.py.

**Comment by harshini-gadige** [comment] 2018-10-31 16:33
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by harshini-gadige** 2018-10-31 16:33 UTC
Labels: stat:community support, type:build/install
