### ISSUE TITLE
Facing error while building APK 

### ISSUE THREAD

**Issue by patilsamruddhi** [tensorflow/tensorflow#8800] opened 2017-03-29 10:34 UTC
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Currently trying to run tensorflow android code downloaded from Github facing following error
Error:Execution failed for task ':buildNativeMake'.
A problem occurred starting process 'command 'tensorflow/contrib/makefile/build_all_android.sh''

### Environment info
Operating System: 64 bit
Android Studio : 2.3
Bazel: 0.3.0
python: 3.5
JDK: 8

Please get back to us today ASAP
Thanking you in advance.

[build_gradle.txt](https://github.com/tensorflow/tensorflow/files/878702/build_gradle.txt)

**Comment by andrewharp** [comment] 2017-03-29 18:54
Closing as duplicate of #8797. Also please add your OS there, since 64 bit isn't very descriptive these days :)

**Closed by andrewharp** 2017-03-29 18:54 UTC

**Comment by patilsamruddhi** [comment] 2017-03-30 06:35
Hi Andrew Harp,

I have referred your link and trying to run bash.exe on windows 7. I get error while executing following commands,
Step 1:
Command: unzip android-ndk-r12b-linux-x86_64.zip -d ~/android
Error: unzip command is not present

Step 2:
Command: tensorflow/contrib/makefile/build_all_android.sh \
          -s tensorflow/contrib/makefile/sub_makefiles/android/Makefile.in \
          -t "libtensorflow_inference.so libtensorflow_demo.so"
Error: build_all_android.sh no such directory found



I also tried another way which mention on Github, Following are the steps

1.      Download bazel 0.3.0

2.      Download Android NDK and unzip it somewhere

3.      Clone Repo from github

4.      Install Assets for Demo

5.      Build native library

CPU = armeabi –v7a

Bazel build //tensorflow/examples/android:tensorflow_native_Libs –crosstool_top = // external : android/crosstool –cpu = $CPU – host_crosstool_top = @bazel_tools//tools/cpp:toolchain



NATIVE_FOLDER = tensorflow/examples/android/libs/$CPU

Mkdir –p $ NATIVE_FOLDER

cp bazel-bin/ tensorflow/examples/android/libtensorflow_demo.so $ NATIVE_FOLDER



6.      Set up the android project (opening project in android studio)

1.      Open an existing android studio project

2.      Configure AndroidManifest.xml

I have stuck in highlighted steps. Can you please help me to solve it?
