### ISSUE TITLE
bazel build tensorflow/python/tools:freeze_graph Error:no package '@icu//'

### ISSUE THREAD

**Issue by lhxy1991** [tensorflow/tensorflow#26565] opened 2019-03-11 07:37 UTC
when i use freeza_graph ,i face a problem:
$bazel build tensorflow/python/tools:freeze_graph
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 1327e781-b5f7-4f42-9ce5-dc35448da7db
ERROR: /mnt/hgfs/share1/tensorflow-master/tensorflow/core/kernels/BUILD:4791:1: no such package '@icu//': java.io.IOException: thread interrupted and referenced by '//tensorflow/core/kernels:string_util'
ERROR: Analysis of target '//tensorflow/python/tools:freeze_graph' failed; build aborted: no such package '@icu//': java.io.IOException: thread interrupted
INFO: Elapsed time: 612.379s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (194 packages loaded, 10048 target\
s configured)
    Fetching @icu; fetching 547s
How I can solove this problem?

**Comment by steige2** [comment] 2019-03-11 18:18
CUDA 10.0
CuDNN 7.4
OS Linux ***.iu.edu 3.10.0-862.6.3.el7.x86_64
bazel 0.22
NVidia P100 and V100

I reproduce the initial error (no such package...) but the java.io.. error is different:

$bazel build --config=opt --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka //tensorflow/tools/pip_package:build_pip_package
INFO: Invocation ID: d790060c-7ae2-4ecd-8834-8fda6454b5f4
ERROR: /N/dc2/projects/osg-storage/Python-3.7.2/tensorflow/tensorflow/tools/pip_package/BUILD:147:1: no such package '@icu//': java.io.IOException: Disk quota exceeded and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@icu//': java.io.IOException: Disk quota exceeded
INFO: Elapsed time: 85.256s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

The /N/dc2 filesystem has 414 TB of free space, I suspect the error messages after the icu error are spurious.

**Comment by steige2** [comment] 2019-03-12 12:00
turns out it was my home directory that was getting fragged. Bazel is rather aggressive with cacheing and was using /home/... rather than the large FS I thought it would use. Deleting /home/.cache/bazel did no harm and fixed my problem.

**Comment by jvishnuvardhan** [comment] 2019-03-12 21:53
@steige2 Is this resolved? Please close it if it was resolved. Thanks!

**Comment by steige2** [comment] 2019-03-13 12:04
I’ve decided to abandon MPI support for this at my institution after the support situation was explained.
I was the ticket in a closed state and I did not reopen it, it must be the other reporter.
S

If you tear a hole in a net you have fewer holes

Scott Teige PhD
Deep Learning
Indiana University Research Technologies
steige@iu.edu
Office: +1 812 856 7331

**Comment by jvishnuvardhan** [comment] 2019-03-20 23:40
I think it was resolved. I am closing the issue. If you think I made a mistake, please open another issue. Thanks!

**Closed by jvishnuvardhan** 2019-03-20 23:40 UTC
Labels: stat:awaiting response, type:build/install
