### ISSUE TITLE
(ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by Cesarcs7** [tensorflow/tensorflow#21977] opened 2018-08-30 16:34 UTC
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
1.10
- **Python version**:
3.6.2

Tensorflow CPU

### Describe the problem
whenever trying to import tensorflow i get this error.(ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.)

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems
```
I know this problem has to do with the windows installation, some problem with the visual c++ compiler 2015 update 3.
The thing is i have them already and it doesnt work. I have tried using an Anaconda enviorment and it didnt work neither whe i used pip3 install --upgrade tensorflow there. But, when i install with the conda installer (conda install tensorflow) it worked perfectly. 

So i assume the problem has to do with some path or something like that in my native enviorment. But i dont have a clue...

**Comment by tensorflowbutler** [comment] 2018-08-31 07:51
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by skye** [comment] 2018-08-31 21:55
@yifeif do you have any idea what would cause this?

**Comment by Cesarcs7** [comment] 2018-09-01 00:02
@tensorflowbutler Hi, im using the CPU version of it, i dont know if it has something to do because im really new to this. I test it in others computers and worked fine.
What do you mean by exact command to reproduce? 
Im sorry for not having the knowledge to anser to your questions, im new to all this and im trying to learn...

**Comment by gunan** [comment] 2018-09-05 21:28
Potential duplicate of https://github.com/tensorflow/tensorflow/issues/19584
What is your CPU make/model?

**Comment by gunan** [comment] 2018-09-16 21:26
Suspected duplicate of #19584
Please reopen if you have data to suggest otherwise.

**Closed by gunan** 2018-09-16 21:26 UTC
Labels: stat:awaiting response

**Comment by eytansuchard** [comment] 2019-03-10 07:04
Same issue in PyCharm, Windows 10 64 bits,
Errors:
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Failed to load the native TensorFlow runtime.

Code in Python:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import tensorflow as TF_NAMESPACE
# Create tensor.
TF_EXERCISE_msg_tensor = TF_NAMESPACE.string_join(["Hellow ","TensorFlow!"])
# Launch session.
with TF_NAMESPACE.session as TF_EXERCISE_sess:
    print(TF_EXERCISE_sess.run(TF_EXERCISE_msg_tensor))

**Comment by RoshanBaghwar** [comment] 2020-04-17 07:37
> ### System information
> * **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
> * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
>   Windows 10
> * **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
> * **TensorFlow installed from (source or binary)**:
>   Source
> * **TensorFlow version (use command below)**:
>   1.10
> * **Python version**:
>   3.6.2
> 
> Tensorflow CPU
> 
> ### Describe the problem
> whenever trying to import tensorflow i get this error.(ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.)
> 
> ```
> >>> import tensorflow as tf
> Traceback (most recent call last):
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 560, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 922, in create_module
>   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
>     return importlib.import_module('_pywrap_tensorflow_internal')
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
>     return importlib.import_module(mname)
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 560, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 922, in create_module
>   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
> ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 17, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 16, in swig_import_helper
>     return importlib.import_module('_pywrap_tensorflow_internal')
>   File "C:\Users\Cesar\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/install_sources#common_installation_problems
> ```
> 
> I know this problem has to do with the windows installation, some problem with the visual c++ compiler 2015 update 3.
> The thing is i have them already and it doesnt work. I have tried using an Anaconda enviorment and it didnt work neither whe i used pip3 install --upgrade tensorflow there. But, when i install with the conda installer (conda install tensorflow) it worked perfectly.
> 
> So i assume the problem has to do with some path or something like that in my native enviorment. But i dont have a clue...

This worked for me;

Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\rosha\.conda\envs\MachineLEarning\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> exit()

(MachineLEarning) C:\Users\rosha\Downloads\Documents\Python\DMProject>pip install tensorflow==2.0.0a0
Collecting tensorflow==2.0.0a0
  Downloading https://files.pythonhosted.org/packages/c7/90/cf5e7fbf4a3c14b314e1ed6571eae1f9ad3b5e32a4e24b2b817466435a21/tensorflow-2.0.0a0-cp37-cp37m-win_amd64.whl (49.4MB)
     |████████████████████████████████| 49.5MB 139kB/s
Requirement already satisfied: termcolor>=1.1.0 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (1.1.0)
Requirement already satisfied: numpy<2.0,>=1.14.5 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (1.18.2)
Requirement already satisfied: google-pasta>=0.1.2 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (0.2.0)
Requirement already satisfied: gast>=0.2.0 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (0.2.2)
Collecting tb-nightly<1.14.0a20190302,>=1.14.0a20190301
  Downloading https://files.pythonhosted.org/packages/a9/51/aa1d756644bf4624c03844115e4ac4058eff77acd786b26315f051a4b195/tb_nightly-1.14.0a20190301-py3-none-any.whl (3.0MB)
     |████████████████████████████████| 3.0MB 156kB/s
Requirement already satisfied: wheel>=0.26 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (0.34.2)
Requirement already satisfied: protobuf>=3.6.1 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (3.11.3)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (0.9.0)
Requirement already satisfied: six>=1.10.0 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (1.14.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (1.1.0)
Requirement already satisfied: astor>=0.6.0 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (0.8.1)
Requirement already satisfied: keras-applications>=1.0.6 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (1.0.8)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tensorflow==2.0.0a0) (1.28.1)
Collecting tf-estimator-nightly<1.14.0.dev2019030116,>=1.14.0.dev2019030115
  Downloading https://files.pythonhosted.org/packages/13/82/f16063b4eed210dc2ab057930ac1da4fbe1e91b7b051a6c8370b401e6ae7/tf_estimator_nightly-1.14.0.dev2019030115-py2.py3-none-any.whl (411kB)
     |████████████████████████████████| 419kB 182kB/s
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tb-nightly<1.14.0a20190302,>=1.14.0a20190301->tensorflow==2.0.0a0) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from tb-nightly<1.14.0a20190302,>=1.14.0a20190301->tensorflow==2.0.0a0) (3.2.1)
Requirement already satisfied: setuptools in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from protobuf>=3.6.1->tensorflow==2.0.0a0) (46.1.3)
Requirement already satisfied: h5py in c:\users\rosha\.conda\envs\machinelearning\lib\site-packages (from keras-applications>=1.0.6->tensorflow==2.0.0a0) (2.10.0)
Installing collected packages: tb-nightly, tf-estimator-nightly, tensorflow
  Found existing installation: tensorflow 2.1.0
    Uninstalling tensorflow-2.1.0:
      Successfully uninstalled tensorflow-2.1.0
Successfully installed tb-nightly-1.14.0a20190301 tensorflow-2.0.0a0 tf-estimator-nightly-1.14.0.dev2019030115

(MachineLEarning) C:\Users\rosha\Downloads\Documents\Python\DMProject>python
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\rosha\.conda\envs\MachineLEarning\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
>>> import tensorflow as tf
>>> import tensorflow as tf
>>> import tensorflow
>>> tensorflow --version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'version' is not defined
>>> tf.VERSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'VERSION'
>>> x1 = tf.constant([1,2,3,4])
2020-04-17 07:27:33.083319: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
>>> x1 = tf.constant([1])
>>> x2 = tf.constant([5])
>>> result = tf.multiply(x1,x2)
>>> print(result)
tf.Tensor([5], shape=(1,), dtype=int32)
>>> a = tf.constant([3,4])
>>> b = tf.constant([45,8])
>>> print(tf.mu;tiply(a,b))
  File "<stdin>", line 1
    print(tf.mu;tiply(a,b))
               ^
SyntaxError: invalid syntax
>>> print(tf.multiply(a,b))
tf.Tensor([135  32], shape=(2,), dtype=int32)
>>> x1 = tf.constant([1,2,3,4])
>>> x2 = tf.constant([5,6,7,8])
>>> result = tf.multiply(x1, x2)
>>> print(result)
tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
