### ISSUE TITLE
Examples in 'Getting started with tensor flow' use deprecated methods

### ISSUE THREAD

**Issue by pcherkasova** [tensorflow/tensorflow#11278] opened 2017-07-04 19:39 UTC
https://www.tensorflow.org/get_started/get_started 
Basic Usage example output:

WARNING:tensorflow:Using temporary folder as model directory: C:\Users\pocherka\AppData\Local\Temp\tmpaq48b_3u
WARNING:tensorflow:From C:\Users\pocherka\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:625: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From C:\Users\pocherka\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:625: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From C:\Users\pocherka\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\head.py:625: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
train loss: {'global_step': 1000, 'loss': 2.3828899e-11}
eval loss: {'global_step': 1000, 'loss': 0.0025255322}sic usage

**Comment by drpngx** [comment] 2017-07-04 21:16
There is a PR against #11159 to fix that.

**Comment by cy89** [comment] 2017-07-07 18:04
Closing as a duplicate of #11159. Please reopen if that PR doesn't fix the issue.

**Closed by cy89** 2017-07-07 18:04 UTC
