### ISSUE TITLE
Memory leak in tf.train.Example/tf.train.Features/tf.gfile

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorflow#23733] opened 2018-11-14 11:18 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Archlinux
- TensorFlow installed from (source or binary): repository
- TensorFlow version (use command below): 1.12
- Python version: 3.7
- CUDA/cuDNN version: cuda 10, cudnn 7
- GPU model and memory: nvidia 1080ti

**Describe the current behavior**

The system goes OOM and I have 64 GiB of memory.

**Describe the expected behavior**

I should be able to create a dataset converting files I read from Google Cloud to local tfrecords.

I'm debugging the memory usage of python and as you can see below, the usage is around 670K - hence the memory allocation should be outside of python, and the only library I'm using is Tensorflow.

**Code to reproduce the issue**

```python
import subprocess
import multiprocessing
from glob import glob
import tensorflow as tf
from tensorflow import keras as k
import json
import os
import logging
from typing import Pattern, List, Tuple, Callable
import linecache
import tracemalloc


def display_top(snapshot, key_type="lineno", limit=10):
    snapshot = snapshot.filter_traces(
        (
            tracemalloc.Filter(False, "<frozen importlib._bootstrap>"),
            tracemalloc.Filter(False, "<unknown>"),
        )
    )
    top_stats = snapshot.statistics(key_type)

    print("Top %s lines" % limit)
    for index, stat in enumerate(top_stats[:limit], 1):
        frame = stat.traceback[0]
        # replace "/path/to/module/file.py" with "module/file.py"
        filename = os.sep.join(frame.filename.split(os.sep)[-2:])
        print(
            "#%s: %s:%s: %.1f KiB" % (index, filename, frame.lineno, stat.size / 1024)
        )
        line = linecache.getline(frame.filename, frame.lineno).strip()
        if line:
            print("    %s" % line)

    other = top_stats[limit:]
    if other:
        size = sum(stat.size for stat in other)
        print("%s other: %.1f KiB" % (len(other), size / 1024))
    total = sum(stat.size for stat in top_stats)
    print("Total allocated size: %.1f KiB" % (total / 1024))


tracemalloc.start()

CACHE = os.path.join(os.getcwd(), ".data")
ROWS_PER_RECORD = 32
SPLITS = ("train", "validation", "test")

LOG = logging.Logger(__name__)
LOG.setLevel(logging.INFO)


def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def _float_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))


def _bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def rows_in_tfrecord(path):
    """Count the number of elements in a tfrecord file.
    Args:
        path: The path of the TFRecord file
    Return:
        The number of examples in the TFRecord
    """
    return sum(1 for _ in tf.io.tf_record_iterator(path))


def _is_dir(path: str):
    """Determines if path is a directory only looking at the filename.
    It's ugly, but is the only way to get a decent speed.
    Args:
        path: The input path
    Return:
        value: True if the path looks like a directory
    """
    return path.endswith("/") or not "." in path.split("/")[-1]


def list_dir(root):
    """Recursively list a directory and returns the list of all the files.
    Args:
        root: The path of the root directory
    Return:
        List of all the files found in this directory and its subfolders.
    """
    ret = []
    for full_path in tf.gfile.Glob(os.path.join(root, "*")):
        if _is_dir(full_path):
            return ret + list_dir(full_path)
        else:
            ret.append(full_path)
    return ret


def _gs2tfrecord(gs_paths: List[str], patterns: List[Pattern], cache: str = CACHE):
    """Fetch images from google cloud storage, conver to tf_record and
    properly handle cache.

    Args:
        gs_paths: list of paths on google cloud storage
        patterns: list of compiled regex to fiter the data on each gs_paths
        cache: local cache/dataset folder
    """
    gcloud_auth = os.path.join(
        os.path.expanduser("~"),
        ".config",
        "gcloud",
        "application_default_credentials.json",
    )
    if not os.path.exists(gcloud_auth):
        subprocess.check_call(["gcloud", "auth", "application-default", "login"])

    meta_file = os.path.join(cache, "meta.json")
    dataset_path = os.path.join(cache, "dataset")
    if not os.path.exists(cache):
        os.makedirs(dataset_path)
        for split in SPLITS:
            os.makedirs(os.path.join(dataset_path, split))
        meta = {"local_files": {path: [] for path in gs_paths}}
    else:
        with open(meta_file, "r") as fp:
            meta = json.load(fp)

    for remote_path, pattern in zip(gs_paths, patterns):
        remote_files = set()
        for name in list_dir(remote_path):
            if pattern.search(name.replace(remote_path, "")):
                remote_files.add(name)

        local_files = set(meta["local_files"][remote_path])

        diff = remote_files - local_files
        LOG.warn("New remote elements: {}".format(len(diff)))
        if diff:
            # Check the current tfrecords, find the last one created
            # Fill the empty spaces in this one (rewriting it completely)
            # And create the other ones
            record_id = sum(
                len(glob(os.path.join(dataset_path, split, "*.tfrecord")))
                for split in SPLITS
            )

            last_tf_record = os.path.join(dataset_path, "train", "1.tfrecord")
            for split in SPLITS:
                last_path = os.path.join(dataset_path, split, f"{record_id}.tfrecord")
                if os.path.exists(last_path):
                    last_tf_record = last_path
                    break

            examples = []
            if os.path.exists(last_tf_record):
                rows_in_last = rows_in_tfrecord(last_tf_record)
                if rows_in_last < ROWS_PER_RECORD:
                    # read all rows in the last tfrecord
                    # we're going to add the last one
                    # and recreate it
                    for row in tf.io.tf_record_iterator(last_tf_record):
                        example = tf.train.Example()
                        examples.append(example.ParseFromString(row))
                else:
                    record_id += 1

            # fetch new files and update the tfrecords
            tot_new_elements = len(diff)
            for idx, new_element in enumerate(diff):
                LOG.warn(f"File: {new_element}")
                with tf.gfile.GFile(new_element, "rb") as fp:
                    img = fp.read()
                remote_meta = os.path.join(os.path.realpath(new_element), "meta.json")
                if not tf.gfile.Exists(remote_meta):
                    example_meta = {
                        "count": _int64_feature(1),
                        "feature1": _float_feature(1076),
                        "feature2": _float_feature(100),
                        "f3": _float_feature(1076),
                        "f4": _float_feature(100),
                        "f5": _bytes_feature("mango".encode("UTF-8")),
                        "f7": _bytes_feature(
                            "banana".encode("UTF-8")
                        ),
                    }
                else:
                    with tf.gfile.GFile(remote_meta, "r") as fp:
                        example_meta = json.loads(fp.read())

                # TODO: check if image is an old style image and convert to new format
                example_meta["img"] = _bytes_feature(img)
                examples.append(
                    tf.train.Example(features=tf.train.Features(feature=example_meta))
                )

                if len(examples) == ROWS_PER_RECORD or idx == tot_new_elements - 1:
                    # write (always in the training dataset) and reset examples buffer
                    filename = os.path.join(
                        dataset_path, "train", f"{record_id}.tfrecord"
                    )
                    with tf.io.TFRecordWriter(filename) as writer:
                        for example in examples:
                            writer.write(example.SerializeToString())
                    # Reset example buffer
                    examples.clear()
                    # Increment tfrecord id
                    record_id += 1
                    LOG.warn(f"TFRecord: {filename} written")
                    snapshot = tracemalloc.take_snapshot()
                    display_top(snapshot)
                    # break

```

Just use the `_gs2tfrecord` function. I'm using it to fetch data from Google Cloud Storage, but since I'm using `tf.gfile` a local path can be used too.

My guess is that leak can be somewhere in `tf.train.Example` or in `tf.train.Feature` since those are the only 2 functions I call in a loop.

**UPDATE**

I've created another function that just download the images from Google Cloud and store them locally. It goes out of memory in the same way.

Maybe the leak is in `tf.gfile`?

Here's the function
```python
def _gs2folder(
    gs_paths: List[str], patterns: List[Pattern], names: List[str], cache: str = CACHE
):
    """Fetch images from google cloud storage, conver to tf_record and
    properly handle cache.

    Args:
        gs_paths: list of paths on google cloud storage
        patterns: list of compiled regex to fiter the data on each gs_paths
        names: list of dataset name
        cache: local cache/dataset folder
    """
    assert len(gs_paths) == len(patterns) and len(patterns) == len(names)

    gcloud_auth = os.path.join(
        os.path.expanduser("~"),
        ".config",
        "gcloud",
        "application_default_credentials.json",
    )
    if not os.path.exists(gcloud_auth):
        subprocess.check_call(["gcloud", "auth", "application-default", "login"])

    for remote_path, pattern, name in zip(gs_paths, patterns, names):
        meta_file = os.path.join(cache, name, "meta.json")
        dataset_path = os.path.join(cache, name, "original")
        if not os.path.exists(cache):
            os.makedirs(dataset_path)
            meta = {"local_files": {path: [] for path in gs_paths}}
        else:
            with open(meta_file, "r") as fp:
                meta = json.load(fp)

        remote_files = set()
        for file_name in list_dir(remote_path):
            if pattern.search(file_name.replace(remote_path, "")):
                remote_files.add(file_name)

        local_files = set(meta["local_files"][remote_path])
        diff = remote_files - local_files
        LOG.warning("New remote elements: {}".format(len(diff)))
        last_id = len(local_files) + 1
        if diff:
            # fetch new files and store them
            tot_new_elements = len(diff)

            for idx, new_element in enumerate(diff):
                LOG.warning(f"File: {new_element}")
                with tf.gfile.GFile(new_element, "rb") as fp:
                    img_bytes = fp.read()

                image = Image.open(io.BytesIO(img_bytes))
                image = np.array(image)
                if image.shape[-1] == 4:
                    # remove transparency
                    image = image[..., :3]
                remote_meta = os.path.join(os.path.realpath(new_element), "meta.json")
                if not tf.gfile.Exists(remote_meta):
                    example_meta = {
                        "count": 1
                    }
                else:
                    with tf.gfile.GFile(remote_meta, "r") as fp:
                        example_meta = json.loads(fp.read())

                image = Image.fromarray(image)
                # Just save the image file with its meta info
                image.save(os.path.join(dataset_path, f"{last_id}.png"))
                with open(os.path.join(dataset_path, f"{last_id}.json"), "w") as fp:
                    json.dump(example_meta, fp)
                last_id += 1

        meta["local_files"][remote_path] = remote_files

    with open(meta, "w") as fp:
        json.dump(meta, fp)
```

**Other info / logs**

This is the output of a `display_top` invocation:

```
Top 10 lines
#1: python3.7/linecache.py:137: 246.9 KiB
    lines = fp.readlines()
#2: util/compat.py:80: 150.0 KiB
    return bytes_or_text.decode(encoding)
#3: datasets/floorplans.py:143: 64.2 KiB
    diff = remote_files - local_files
#4: datasets/floorplans.py:139: 32.0 KiB
    remote_files.add(name)
#5: internal/python_message.py:475: 21.6 KiB
    self._oneofs = {}
#6: internal/python_message.py:425: 15.5 KiB
    result = message_type._concrete_class()
#7: python3.7/tracemalloc.py:185: 13.4 KiB
    self._frames = tuple(reversed(frames))
#8: internal/python_message.py:472: 12.0 KiB
    self._fields = {}
#9: internal/python_message.py:1402: 10.3 KiB
    self._parent_message_weakref = weakref.proxy(parent_message)
#10: internal/python_message.py:1155: 5.1 KiB
    for field, value in list(self._fields.items()):  # dict can change size!
228 other: 104.0 KiB
Total allocated size: 675.1 KiB
```

**Comment by galeone** [comment] 2018-11-14 14:55
Update: probably the leak is in `tf.gfile` since I can see that the memory grows every time I run the line:

```python
                with tf.gfile.GFile(new_element, "rb") as fp:
                    img_bytes = fp.read()
```
In the loop.

I've also tried to change it to:

```python
fp = tf.gfile.GFile(new_element, "rb")
img_bytes = fp.read()
fp.close()
fp = None
```

But every time I `read()` the memory is never released

**Comment by galeone** [comment] 2018-11-14 15:56
Another update: the problem is related to the tensorflow package I'm using, that's the one shipped by the Archlinux devs.

If I create a virtualenv with python3.6 and I use the tensorflow package installed via pip, it works correctly.

**Comment by asimshankar** [comment] 2018-11-20 06:53
@galeone : Thanks for all the details. I wanted to confirm the state after all your digging and investigation.

Is it accurate to say that there is no problem observed in the official TensorFlow release binaries and you're only seeing this in a package built by the Archlinux folks?

**Comment by galeone** [comment] 2018-11-20 16:54
Update: the same happen with Tensorflow installed from conda

**Comment by asimshankar** [comment] 2018-12-04 09:34
@galeone : With "conda" - still Python 3.7?

**Comment by galeone** [comment] 2018-12-04 10:15
No, with Python 3.6.7 and tensorflow-gpu (1.12) installed using conda into the conda environement.
Here's the detail:

- cuda toolkit: 9.2
- cudnn: 7.2.1
- conda version: 4.3.27
- cupti: 9.2.148

**Comment by ygoncharov** [comment] 2019-02-08 13:50
The same problem exists on the official Cloud Deep Learning VM Image (TF 1.12, CUDA 10). It runs out of memory within a few minutes when training data on gs://. Runs perfectly fine when the bucket is mounted to the local fs.

**Comment by urimerhav** [comment] 2019-02-28 08:44
Is there any update on this? I'm running out of memory with a simple 

```
def generate_writer(self):
        tfrecord_fname = ''.join([random.choice(string.ascii_letters + string.digits) for n in xrange(9)]) + '.tfrecord'
        opts = tf.python_io.TFRecordOptions(tf.python_io.TFRecordCompressionType.ZLIB)
        writer = tf.python_io.TFRecordWriter(tfrecord_fname, options=opts)
        return writer, tfrecord_fname

writer, fname = self.generate_writer()
while True:
            sample = {
                'video': Feature(float_list=FloatList(value=(e['video'].reshape(-1)))),
                'video_shape': Feature(int64_list=Int64List(value=(e['video'].shape))),
                'tx_path': Feature(bytes_list=BytesList(value=wrap(e['tx_path']))),
                'tx_type': Feature(bytes_list=BytesList(value=wrap(e['tx_type']))),
                'item_scanned': Feature(int64_list=Int64List(value=(e['item_scanned'])))
            }
            feature = tf.train.Features(feature=sample)
            example = tf.train.Example(features=feature)
            writer.write(example.SerializeToString())
            del example

            i += 1

            if i % 10 == 0:
                writer.flush()
                writer.close()
                writer, fname = self.generate_writer()
```

**Comment by rxsang** [comment] 2019-02-28 17:55
Thanks for the simple example. I'll take a look today.

**Comment by jing-dong** [comment] 2019-03-01 01:42
I tried to look into this problem today.

@urimend I cannot reproduce the memory leaks from your sample code using either tensorflow 1.12 installed from python3 virtualenv or anaconda. Can you please provide more details about this issue? Does the size of e['video'] matter? I tried setting e['video'] to numpy.zeros(10**5).

@galeone I cannot reproduce the memory leaks you reported in the following code with tensorflow 1.12 with ananconda.
```
with tf.gfile.GFile(new_element, "rb") as fp:
      img_bytes = fp.read()
```
I have some trouble making tensorflow-gpu run in my machine. Can you please check to see if you can reproduce the memory leak using tensorflow instead of tensorflow-gpu?

**Comment by urimend** [comment] 2019-03-01 04:13
@jing-dong - you meant @urimerhav :)

**Comment by ygoncharov** [comment] 2019-03-01 09:03
For me, it is reproduced for almost every scenario. Just try to read a few thousands of files directly from gs:// using tf.gfile.GFile with the "with" statement. You will see a memory leak right away.

The important part that it should be tf 1.12 built for CUDA 10. It seems that it doesn't repro for CUDA 9 or CPU builds.

**Comment by urimerhav** [comment] 2019-03-01 19:32
@jing-dong I'm sorry. I relaunched my aws instance from the same image and now I can't reproduce my error. I guess I'm retracting my bug report since I'm not able to reproduce

**Comment by ygoncharov** [comment] 2019-03-01 20:10
For me, it also didn't repro today with the official tensorflow-gpu 1.13.1

**Comment by urimerhav** [comment] 2019-03-02 03:01
ugh, so it does reproduce on a ubuntu16, python2.7 with the latest v1.13.1 with the above code. 

I tried launching a fresh ubuntu 16 instance, install python 2.7 with stock tensorflow (cpu) and the memory creeps down. I can confirm that removing the "writer" and simply generating examples doesn't resolve the issue.

**Comment by urimerhav** [comment] 2019-03-02 09:06
Update: So this problem _is_ reproducible for me, with ubuntu 16 python 2.7 and tflow (both cpu and gpu) 1.13.1.

The only thing I can add that might be going on here, is that I'm fetching the data from an s3 path, though I really can't imagine how that would effect anything.

**Comment by galeone** [comment] 2019-03-02 09:17
The problem is still present in the 2 different environments I reported (python 3.7 - cuda 10 - archlinux build *and* python 3.6 - tensorflow-gpu 1.12 - conda env). When I read a file, using GFile, from Google Cloud storage there's a memory leak that saturates all the system memory.
It happens both when using context manager or when manually opening and closing the files (I thought the leak could be caused by a wrong implementation of the context manager that doesn't close the file when exiting the context - but it is not the case).

**Comment by urimerhav** [comment] 2019-03-02 09:20
@galeone do you happen to know of a version with python 2.7 where the memory leak doesn't occur?

**Comment by galeone** [comment] 2019-03-02 09:24
@urimerhav no, never used python 2.x with Tensorflow; never tried

**Comment by jing-dong** [comment] 2019-03-02 16:57
@urimerhav Can you please confirm that the memory leaks only occur when you try to read from s3 path by trying to read from local FS or gcs path (gs://) if that is available to you? If the memory leak only happens when reading the s3 paths, it may be because the s3 file reader in TF contains a leak.

@galeone Would it be easy for you to try to experiment with tensorflow (without gpu) to see if you can reproduce the leaks there? As I said earlier, I have trouble running tensorflow-gpu in my environment.  Also, just to confirm, the code that produces the memory leak for you is the following, right?
```
while True:
    with tf.gfile.GFile(gs_path, "rb") as fp:
        img_bytes = fp.read()
```

**Comment by quirkyllama** [comment] 2019-03-28 14:54
Any update on this bug? We're seeing some sort of memory leak after moving from TF 1.1.9 to TF 1.1.3 on Python 2.7

**Comment by ygoncharov** [comment] 2019-03-28 15:04
I confirm that the bug still exists in TF 1.13. Env: the latest NVIDIA TF 1.13 container running on Google Gloud, python2 (nvcr.io/nvidia/tensorflow:19.03-py2)

**Comment by urimerhav** [comment] 2019-03-28 17:11
@ygoncharov  @quirkyllama can you confirm that python3 doesn't have that memory leak?

**Comment by galeone** [comment] 2019-03-28 17:37
@urimerhav with this setup https://github.com/tensorflow/tensorflow/issues/23733#issuecomment-444046925 the leak is still present and is Python 3

**Comment by urimerhav** [comment] 2019-03-28 17:49
Well, I'm willing to use just about any TF distribution that will rid me of this bug, so far it seems like the only report on a working setup is 1.1.9 on python 2?

**Comment by galeone** [comment] 2019-03-28 18:00
Reading the comments looks like yes, 1.1.9 py2 works - but you can try with some new tensorflow release that support Python 2 to see if the leak is still there or is gone

**Comment by jing-dong** [comment] 2019-03-28 18:26
@galeone @ygoncharov @urimend Can you please describe a python environment and a minimum code snippet that reproduces this memory leak? I will try to see if I can reproduce this in a GCloud VM and go from there.

**Comment by jing-dong** [comment] 2019-04-06 19:18
Since I have not heard back regarding this issue, I will close it for now. Please feel free to reopen the issue with a setup to reproduce the problem.

**Comment by ygoncharov** [comment] 2019-04-06 20:00
@jing-dong this thread contains the exact environment (see my post the latest NVIDIA TF 1.13 container running on Google Gloud, python2 (nvcr.io/nvidia/tensorflow:19.03-py2) and the code (see @urimerhav  post) to reproduce the issue.

For easier repro try the following:
1. Env: nvcr.io/nvidia/tensorflow:19.03-py2 running on GC v100
2. Create a GS bucket with ~100k files
3. Read all these files one by one using tf.gfile.Open from gs:// and write them to the local FS
-> you program will hit OOM 

This is a critical issue that appears across a few TF release builds in many environment, not sure why it was closed.

**Comment by jing-dong** [comment] 2019-04-08 16:50
Thanks @ygoncharov. I will reopen the issue and look into reproducing the problem.

**Comment by jing-dong** [comment] 2019-04-08 19:48
@ygoncharov, I am able to reproduce the problem as you described. Thanks for the detailed instructions. One strange thing I noted that the memory leak problem does not happen if I use tensorflow-gpu (1.13.1) installed on the host directly without using the nivida docker image for both python2 and python3. Can you please confirm that is the case? If so, the problem probably comes from how Nvidia built the docker image.

**Comment by ygoncharov** [comment] 2019-04-09 08:20
@jing-dong Glad that you were able to reproduce the issue. Indeed it seems the issue does not repro in some environments, but I cannot pinpoint the exact reason for that. I don't think that the problem is in the docker image since I (and it seems other people in this thread) had this problem in a docker-less environment before.

**Comment by jing-dong** [comment] 2019-04-09 19:01
@ygoncharov I tried the following setup that seems to work:
1. Env: nvcr.io/nvidia/tensorflow:19.02-py2 running on GC v100  (note the version is 19.02)
2. Inside the docker container, create python virtualenv
3. pip install tensorflow-gpu==1.13.1
4. The test script runs without memory leak

Can you please try this out to see if this works for you?

The default installed tensorflow in the docker image also has the memory leak issue as you noticed. It suggests that the problem comes from how nvidia built the tensorflow for the docker image. If you can reproduce the memory leak issue without using the nvidia docker image, we can investigate further on this. If not, can you please report the problem to nvidia to investigate further?

**Comment by jing-dong** [comment] 2019-04-09 20:58
@ygoncharov There seems to be a related problem reported in the nvidia developer forum:

https://devtalk.nvidia.com/default/topic/1046985/docker-and-nvidia-docker/tensorflow-model-memory-issues-with-new-docker-version-19-01/

**Comment by ygoncharov** [comment] 2019-04-10 08:40
@jing-dong sounds good, I will try those steps to verify your conclusion

**Comment by jing-dong** [comment] 2019-04-12 16:35
@ygoncharov How does the workaround work for you? Were you able to reproduce the memory leak outside of the nvidia docker image?

**Comment by jing-dong** [comment] 2019-04-16 16:35
@ygoncharov I will close this ticket for now. If you still have any issues, please feel free to re-open this ticket.

**Comment by ygoncharov** [comment] 2019-04-18 09:01
@jing-dong I did a similar experiment: run the script on an official GC deep learning image and then pip installed tensorflow-gpu==1.13.1 in a clean virtualenv. I got the same result: memory leak in the first case and no memory leak in the second.

**Comment by Luxas98** [comment] 2019-04-18 14:03
Hi everybody, I'm joining to the memory leaking club.

Environment:
Docker container base: FROM python:3.7-stretch
Tensorflow: conda install -c conda-forge tensorflow  (tried pip install tensorflow=1.13.1 as well)

Use case:
Running loading from GS using GFile in callback on message from pubsub (sending messages 1 by one for testing) - I can see that data is not released,

File1:
      9    196.6 MiB    196.6 MiB   @profile
    10                                             def read(filename):
    11    196.6 MiB      0.0 MiB            with tf.gfile.GFile(filename, 'rb') as dicom_file_obj:
    12    327.9 MiB    131.3 MiB              return dicom_file_obj.read()
File 2:
    11    328.0 MiB      0.0 MiB       with tf.gfile.GFile(filename, 'rb') as dicom_file_obj:
    12    715.7 MiB    387.8 MiB           return dicom_file_obj.read()
File 3:
    11    715.8 MiB      0.0 MiB       with tf.gfile.GFile(filename, 'rb') as dicom_file_obj:
    12    973.6 MiB    257.8 MiB           return dicom_file_obj.read()
 
and just grows with every file, first I though it it's pubsub problem but I removed everything from the pubsub callback and I only read the file and return and finish. Memory still grows.

Any ideas?

**Comment by jing-dong** [comment] 2019-04-18 16:46
@Luxas98 Can you please post a minimal Dockerfile and sample script here that I can use to reproduce the problem? I will try to see what I can do from there.

@ygoncharov Can you please clarify what the "official GC deep learning image" refers to? Is it  nvcr.io/nvidia/tensorflow:19.03-py2 that you used earlier?

**Comment by ygoncharov** [comment] 2019-04-18 17:51
@jing-dong no, it was not a docker image. It is an official Google Cloud image preconfigured for Tensorflow from https://cloud.google.com/deep-learning-vm/

The link to the current marketplace image is below, but please note that in my test I used the previous version (the one that came with tensorflow 1.12).
https://console.cloud.google.com/marketplace/details/click-to-deploy-images/deeplearning?_ga=2.212830999.-2046381496.1540473489

**Comment by Luxas98** [comment] 2019-04-19 08:17
@jing-dong Hi, check example of leak and no leak in https://github.com/Luxas98/tensorflow-gfile-memory-leak 

Please let me know when you are done so I can remove the service account secrets and gs files :-)

**Comment by jing-dong** [comment] 2019-04-19 21:14
@Luxas98 Thanks for the simple examples for reproducing the memory leaks. I am able to reproduce the same problem as you described. I will look into the problem and update here if there is any findings.

**Comment by jing-dong** [comment] 2019-04-19 21:23
Setting the following environment variable prevents the memory leak problem in Python 3.7 for me.
export ENV GCS_READ_CACHE_MAX_SIZE_MB=0

Can you please give it a try and see if this works for you? In the mean time, I will look into the root cause for the problem.

**Comment by jing-dong** [comment] 2019-04-26 20:35
We identified the root cause of the memory leak problem and will cherry-pick the fix to TF 1.14 soon. For earlier versions, you can continue to use "export GCS_READ_CACHE_MAX_SIZE_MB=0" as the workaround for this problem.

**Comment by jing-dong** [comment] 2019-04-26 21:28
The fix has been cherry-picked to TF 1.14. Please feel free to re-open the ticket if there are further issues related to this bug.

**Closed by jing-dong** 2019-04-26 21:28 UTC
Labels: comp:runtime, type:bug/performance

**Comment by galeone** [comment] 2019-04-26 22:34
Great!

**Comment by jperl** [comment] 2019-07-14 15:03
Thank you for fixing this. I can confirm `export ENV GCS_READ_CACHE_MAX_SIZE_MB=0` fixes the leak for me in `1.13.1` and it works in `1.14.0` without setting that.

I spent a day tracking down the memory leak since it does not show up in python profiling with `tracemalloc`. Is there any way to profile how much memory tensorflow is using to help with isolating future memory leaks?

**Comment by jing-dong** [comment] 2019-07-14 18:02
One tool that I found helpful is the heap profiler in Gperftools (https://gperftools.github.io/gperftools/heapprofile.html). You may want to try it out next time when you suspect there are memory leaks.

**Comment by jperl** [comment] 2019-07-14 19:00
Thank you @jing-dong I will try that next time :pray:

**Comment by w4-sjcho** [comment] 2019-07-19 04:37
Is there a way to pass this flag when running on TPUs?
