### ISSUE TITLE
Xcode 13.3.1 builds ImageClassification iOS TensorFlow Lite example failed

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#56175] opened 2022-05-20 02:51 UTC
git clone https://github.com/tensorflow/examples
cd examples/lite/examples/image_classification/ios
pod install
open open ImageClassification.xcodeproj 
Using Xcode to build ImageClassification project. But the following error occurred.
No such module 'TensorFlowLite'

**Comment by sachinprasadhs** [comment] 2022-05-20 20:42
Could you please close this issue since the issue is similar to the issue which you have reported here https://github.com/tensorflow/tensorflow/issues/56176 and it's easier to track and escalate issue, since the underlying problem seems to be same for both the issue. Thanks!

**Closed** 2022-05-20 23:55 UTC
Labels: stat:awaiting response, type:bug, comp:lite-examples, TF 2.9
