### ISSUE TITLE
tf.data.Dataset.padded_batch does not actually pad data when working on multiple GPUs.

### ISSUE THREAD

**Issue by remydubois** [tensorflow/tensorflow#28541] opened 2019-05-09 09:23 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
X
- **TensorFlow installed from (source or binary)**:
Binary
- **TensorFlow version (use command below)**:
v1.12.0-9492-g2c319fb415 2.0.0-alpha0
- **Python version**:
3.6
- **Bazel version (if compiling from source)**:
X
- **GCC/Compiler version (if compiling from source)**:
X
- **CUDA/cuDNN version**:
10.0
- **GPU model and memory**:
Tesla K80 / 12GB RAM
- **Exact command to reproduce**:
See test below

### Describe the problem
The problem appears when one wants to use a multi-gpu-compiled model with variable-shaped data, fed from a tf.data pipeline. 
Batching data using padded_batch (compulsory here, since the data is of variable shape) does not seem to really pad the tensors comprised in a batch. Calling `fit`or `predict `after doing so raises:
`ValueError: Input tensor shapes do not match for distributed tensor inputs PerReplica`.

See below a MVCE:
- A python generator is used to generate tensors of variable shape: (4, 4, 1), then (5, 5, 1), then (4, 4, 1), then (5, 5, 1), etc...
- A tf.data Dataset is built using `tf.data.Dataset.from_generator`, including a consistency check.
- A dummy model is built using the tf.keras functional API and a `tf.distribute.MirroredStrategy` on several GPUS.

### Source code / logs
MVCE:

```
import tensorflow as tf
import numpy as np


def data_generator():
    """
    Creates a generator of variable_sized tensors.
        tensor 1: (4, 4, 1)
        tensor 2: (5, 5, 1)
        tensor 3: (4, 4, 1)
        tensor 4: (5, 5, 1)
        ...
    """
    i = 0

    while True:
        size = (4 + i % 2, 4 + i % 2, 1)
        x = tf.random.normal(shape=size)
        yield x
        i += 1


def build_data_pipeline():
    """
    Builds a tf.data pipeline yielding variably-sized tensors.
    """
    dataset = tf.data.Dataset.from_generator(
        generator=data_generator,
        output_types=tf.float32,
        output_shapes=[None, None, 1])

    # Padded batch, should output (batch_size, 5, 5, 1) - shaped tensors.
    dataset = dataset.padded_batch(
        batch_size=2,
        padded_shapes=(None, None, 1),
        padding_values=0.)

    # Juste making sure that the tf.data pipeline is as expected
    it = iter(dataset)
    batch_1 = next(it)  #~= tf.data.experimental.get_single_element(dataset)
    batch_2 = next(it)  #~= tf.data.experimental.get_single_element(dataset)

    np.testing.assert_allclose(batch_1.shape, batch_2.shape)
    np.testing.assert_allclose(batch_1.shape, (2, 5, 5, 1))

    return dataset


def run_on_multi_gpus():
    """
    Building multi-gpu model using MirroredStrategy,
    And trying to predict
    """
    strat = tf.distribute.MirroredStrategy()

    with strat.scope():

        i_ = tf.keras.layers.Input((None, None, 1))
        model = tf.keras.models.Model(i_, i_)

        model.compile(optimizer='adam',
                      loss='binary_crossentropy')

    dataset = build_data_pipeline()
    model.predict(dataset, steps=1, verbose=1)


if __name__ == '__main__':
    run_on_multi_gpus()
```

**Comment by jsimsa** [comment] 2019-05-20 21:46
@jvishnuvardhan the error is coming from TF distribution strategy, which I am not familiar with. Could you please re-assign this to someone from that team? Thank you.

**Comment by isaprykin** [comment] 2019-06-05 20:53
Why do you think it's not padded if these statements pass:
```
    np.testing.assert_allclose(batch_1.shape, batch_2.shape)
    np.testing.assert_allclose(batch_1.shape, (2, 5, 5, 1))
```

Looks padded, doesn't it?  Since all of the batches are ..., 5,5,1.

**Comment by remydubois** [comment] 2019-06-07 07:40
Hi,
I agree that the title is misleading: 
The issue here comes when using a `padded_batch` `tf.data.dataset` with a multi_gpu model, built using a `MirroredStrategy`.

Doing so raises:
`ValueError: Input tensor shapes do not match for distributed tensor inputs PerReplica`. This error prints along each sub-batch (one sub-batch per worker).
Consequently, The MVCE above will print two tensors: 
- one of shape (1, 4, 4, 1), 
- the other of shape (1, 5, 5, 1)

My issue here is that I can not train a Distributed model one varying-sized input.

**Comment by isaprykin** [comment] 2019-07-26 18:24
Yes, it's an issue and we are currently working on fixing it.  Thanks for reporting.

**Comment by isaprykin** [comment] 2019-07-29 18:01
FYI it should work if there were fully defined shapes instead of None in padded_batch.

**Comment by remydubois** [comment] 2019-07-31 12:07
@isaprykin thanks, good to know

**Comment by jvishnuvardhan** [comment] 2019-07-31 22:06
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Comment by guptapriya** [comment] 2019-07-31 23:01
I don't think the issue is resolved yet, Igor simply suggested a workaround for now. The bug is still there and needs to be fixed.

**Comment by guptapriya** [comment] 2019-11-04 00:45
I think this issue should now be fixed. Please re-open if not.

**Closed by guptapriya** 2019-11-04 00:45 UTC
Labels: comp:dist-strat, type:bug
